// 영어 학습용 원고 (한국 초등, 영어 초급). 세계 도시 탐방: 유럽. 문장은 자체 집필.
// 키 = stories/city-c.js 의 이야기 id. lines 의 첫 칸은 원래 이야기 cast 의 한국어 이름 그대로.
export default {
  'ct-paris-1': {
    title: 'Paris, Part 1',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 레아: 'Lea' },
    outro: [
      'Did you enjoy our trip to Paris?',
      'Which place in Paris would you visit first?',
      'Is there an old building or bridge in your town?',
    ],
    lines: [
      ['해설', 'Hana and the Guide arrive in Paris.'],
      ['하나', 'Where is Paris?'],
      ['안내인', 'Paris is the capital of France, in western Europe.'],
      ['안내인', 'The Seine River runs through the middle of the city.'],
      ['해설', 'Paris has four seasons. It is not too hot or cold.'],
      ['레아', 'Bonjour! I am Lea. I live in Paris.'],
      ['하나', 'What does bonjour mean?'],
      ['레아', 'It means hello in French.'],
      ['안내인', 'Let’s learn about the history of Paris.'],
      ['안내인', 'About two thousand years ago, a people called the Parisii lived here.'],
      ['해설', 'The name Paris comes from them.'],
      ['안내인', 'Later, the Romans came. They called the town Lutetia.'],
      ['해설', 'In the 1100s, people began to build Notre Dame.'],
      ['안내인', 'In 1789, the French Revolution began in Paris.'],
      ['안내인', 'In 1889, the Eiffel Tower was built for a big fair.'],
      ['레아', 'Look! The Eiffel Tower is made of iron.'],
      ['안내인', 'The Louvre was once a royal palace. Now it is a museum.'],
      ['레아', 'The Mona Lisa is in the Louvre.'],
      ['안내인', 'Notre Dame had a big fire in 2019.'],
      ['해설', 'People fixed it, and it opened again.'],
      ['하나', 'Paris has so many old stories!'],
      ['해설', 'Paris is the capital of France, on the Seine River.'],
    ],
  },

  'ct-paris-2': {
    title: 'Paris, Part 2',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 제빵사: 'Baker', 레아: 'Lea' },
    outro: [
      'Was the food in Paris yummy?',
      'Why do people say bonjour in a shop?',
      'Which would you like to try, a baguette or a crepe?',
    ],
    lines: [
      ['해설', 'Last time, Hana learned about the history of Paris.'],
      ['해설', 'Today, she visits a bakery.'],
      ['제빵사', 'Bonjour! Would you like a fresh baguette?'],
      ['하나', 'Wow, it is long like a stick!'],
      ['안내인', 'A baguette is made with flour, water, salt and yeast.'],
      ['제빵사', 'It is crunchy outside and soft inside.'],
      ['제빵사', 'This is a croissant. It has lots of butter.'],
      ['하나', 'Crunch, crunch! It is so flaky!'],
      ['레아', 'A crepe is a thin pancake. It can be sweet or salty.'],
      ['안내인', 'In Paris, say bonjour when you walk into a shop.'],
      ['레아', 'Good friends often greet with a little kiss on the cheek.'],
      ['안내인', 'July 14 is a national holiday. There are fireworks!'],
      ['하나', 'How do people get around?'],
      ['안내인', 'Many people take the metro. Many ride bikes, too.'],
      ['레아', 'We buy fruit and cheese at open-air markets.'],
      ['하나', 'Tell me a fun fact!'],
      ['안내인', 'The Eiffel Tower was meant to stand for only twenty years.'],
      ['안내인', 'But it was useful for radio, so it stayed.'],
      ['레아', 'Paris has twenty parts. Their numbers go round like a snail!'],
      ['해설', 'Today we learned about bread, crepes and saying bonjour.'],
      ['해설', 'Paris is a city of bread, art and the Seine.'],
    ],
  },

  'ct-london-1': {
    title: 'London, Part 1',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 올리버: 'Oliver' },
    outro: [
      'Did you have fun in London?',
      'How did people rebuild London after the great fire?',
      'How would you feel if you saw a bridge open up?',
    ],
    lines: [
      ['해설', 'Hana and the Guide arrive in London.'],
      ['하나', 'Where is London?'],
      ['안내인', 'London is the capital of the United Kingdom.'],
      ['안내인', 'The country is on islands west of mainland Europe.'],
      ['안내인', 'The River Thames flows through London to the sea.'],
      ['해설', 'London is not very hot or cold. It rains often.'],
      ['올리버', 'Hello! I am Oliver. I live in London.'],
      ['안내인', 'Let’s learn about the history of London.'],
      ['안내인', 'About two thousand years ago, the Romans built a town here.'],
      ['해설', 'They called it Londinium. They built a bridge, too.'],
      ['안내인', 'After 1066, King William began to build the Tower of London.'],
      ['안내인', 'In 1666, a great fire burned much of the city.'],
      ['하나', 'Oh no! What happened next?'],
      ['안내인', 'People built the city again, with a new St Paul’s Cathedral.'],
      ['해설', 'In 1863, London opened the first underground railway in the world.'],
      ['올리버', 'Big Ben is a big bell in a clock tower.'],
      ['안내인', 'Next to it are the Houses of Parliament.'],
      ['안내인', 'Buckingham Palace is a famous royal palace.'],
      ['올리버', 'The guards wear red coats and tall fur hats!'],
      ['안내인', 'Tower Bridge opens up when big ships pass.'],
      ['하나', 'The Tower of London is right next to it!'],
      ['해설', 'London is the capital of the UK, on the River Thames.'],
    ],
  },

  'ct-london-2': {
    title: 'London, Part 2',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 할머니: 'Grandma', 올리버: 'Oliver' },
    outro: [
      'Did you enjoy tea time in London?',
      'Why do people in Britain think waiting in line matters?',
      'Where would you sit on a double-decker bus?',
    ],
    lines: [
      ['해설', 'Last time, Hana learned about the history of London.'],
      ['해설', 'Today, she visits Oliver’s grandma.'],
      ['할머니', 'Come in, dear. I made tea and scones.'],
      ['할머니', 'We put cream and strawberry jam on scones.'],
      ['안내인', 'Afternoon tea is an old British custom.'],
      ['올리버', 'My favorite food is fish and chips!'],
      ['안내인', 'It is fried fish with thick, hot chips.'],
      ['올리버', 'I put salt and vinegar on top. Yum!'],
      ['할머니', 'Some people eat a full English breakfast.'],
      ['안내인', 'It has eggs, bacon, sausages, beans and toast.'],
      ['안내인', 'In Britain, people wait in line politely.'],
      ['할머니', 'We say please, thank you and sorry a lot.'],
      ['올리버', 'In August, there is the Notting Hill Carnival!'],
      ['안내인', 'People enjoy Caribbean music, costumes and dancing.'],
      ['하나', 'How do people get around?'],
      ['올리버', 'Red double-decker buses! I like the top front seat.'],
      ['안내인', 'People call the London underground the Tube.'],
      ['올리버', 'Many schools in Britain have school uniforms.'],
      ['안내인', 'On the Tube, you hear, Mind the gap.'],
      ['안내인', 'It means, watch the space by the train.'],
      ['해설', 'Today we learned about scones, fish and chips and good manners.'],
      ['해설', 'London is a city of old customs and red buses.'],
    ],
  },

  'ct-rome-1': {
    title: 'Rome, Part 1',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 루카: 'Luca' },
    outro: [
      'Did you like our trip to Rome?',
      'Why did the Pantheon have a hole in its roof?',
      'What wish would you make at the Trevi Fountain?',
    ],
    lines: [
      ['해설', 'Hana and the Guide arrive in Rome.'],
      ['하나', 'Where is Rome?'],
      ['안내인', 'Rome is the capital of Italy, in southern Europe.'],
      ['안내인', 'Italy looks like a boot in the sea.'],
      ['안내인', 'The Tiber River flows through Rome. The city grew on seven hills.'],
      ['해설', 'Summers are hot and dry. Winters are mild.'],
      ['루카', 'Ciao! I am Luca. I live in Rome.'],
      ['루카', 'Ciao means hi and bye between friends.'],
      ['안내인', 'A legend says twin brothers started Rome.'],
      ['안내인', 'Rome grew big. It ruled lands around the Mediterranean Sea.'],
      ['해설', 'Romans built strong roads and long bridges for water.'],
      ['안내인', 'About two thousand years ago, they built the Colosseum.'],
      ['안내인', 'Later, Rome became the center of the Catholic Church.'],
      ['해설', 'Artists like Michelangelo made beautiful works here.'],
      ['안내인', 'In 1871, Rome became the capital of Italy.'],
      ['루카', 'At the Colosseum, many people watched games long ago.'],
      ['안내인', 'The Pantheon has a big round hole in its roof.'],
      ['하나', 'Doesn’t the rain come in?'],
      ['안내인', 'Yes, but small holes in the floor drain the water.'],
      ['루카', 'Throw a coin into the Trevi Fountain. Then you will come back!'],
      ['안내인', 'There is a tiny country inside Rome, Vatican City.'],
      ['해설', 'Rome is the capital of Italy, on the Tiber River.'],
    ],
  },

  'ct-rome-2': {
    title: 'Rome, Part 2',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 요리사: 'Cook', 루카: 'Luca' },
    outro: [
      'Was the food in Rome tasty?',
      'Why do many people in Rome ride scooters?',
      'What gelato flavor would you pick?',
    ],
    lines: [
      ['해설', 'Last time, Hana saw the Colosseum and the Trevi Fountain.'],
      ['해설', 'Today, she visits a little restaurant.'],
      ['요리사', 'Buongiorno! Are you hungry?'],
      ['안내인', 'Buongiorno means good morning in Italian.'],
      ['요리사', 'Try Roman pizza. It is thin and crispy.'],
      ['루카', 'You can buy square pizza by the slice, too!'],
      ['요리사', 'This is carbonara pasta. It is famous in Rome.'],
      ['안내인', 'It has egg, cheese, pork and pepper. There is no cream.'],
      ['루카', 'For dessert, we eat gelato. It is Italian ice cream!'],
      ['안내인', 'Italians often talk with their hands.'],
      ['안내인', 'April 21 is the birthday of Rome.'],
      ['요리사', 'Cover your shoulders and knees in a church.'],
      ['하나', 'How do people get around?'],
      ['루카', 'The streets are narrow, so many people ride scooters.'],
      ['안내인', 'Old streets have small square stones.'],
      ['요리사', 'I buy fresh fruit at the morning market.'],
      ['하나', 'Tell me a fun fact!'],
      ['안내인', 'Rome has many small street fountains with cool water.'],
      ['루카', 'We call them big noses!'],
      ['안내인', 'Coins from the Trevi Fountain are used to help people.'],
      ['해설', 'Today we learned about pizza, pasta and gelato.'],
      ['해설', 'Rome is a living city with a very long history.'],
    ],
  },

  'ct-barcelona-1': {
    title: 'Barcelona, Part 1',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 마르타: 'Marta' },
    outro: [
      'Did you enjoy our trip to Barcelona?',
      'How does it feel to build something for so long?',
      'If you were a builder, what would you build?',
    ],
    lines: [
      ['해설', 'Hana and the Guide arrive in Barcelona, Spain.'],
      ['하나', 'Is Barcelona the capital of Spain?'],
      ['안내인', 'No. The capital of Spain is Madrid.'],
      ['안내인', 'Barcelona is by the Mediterranean Sea, with hills behind it.'],
      ['해설', 'Barcelona is sunny. Winters are quite warm.'],
      ['마르타', 'Hola! I am Marta. I live in Barcelona.'],
      ['마르타', 'Here, we speak Spanish and Catalan.'],
      ['안내인', 'Let’s learn about the history of Barcelona.'],
      ['안내인', 'About two thousand years ago, the Romans built a town here.'],
      ['해설', 'Later, the city grew rich from trade by sea.'],
      ['마르타', 'The Gothic Quarter has old, twisty streets!'],
      ['안내인', 'In the 1800s, the old city walls came down.'],
      ['해설', 'Then the builder Gaudi made amazing buildings here.'],
      ['안내인', 'In 1992, Barcelona hosted the Summer Olympics.'],
      ['마르타', 'People began to build the Sagrada Familia in 1882.'],
      ['하나', 'Was it finished fast?'],
      ['안내인', 'People have built it for more than a hundred years!'],
      ['마르타', 'Park Guell has a lizard made of colorful tiles.'],
      ['안내인', 'The tiles are small broken pieces. They sparkle in the sun.'],
      ['마르타', 'La Rambla is a long street for walking.'],
      ['하나', 'These buildings look like a fairy tale!'],
      ['해설', 'Barcelona is a sunny city by the sea, full of Gaudi’s buildings.'],
    ],
  },

  'ct-barcelona-2': {
    title: 'Barcelona, Part 2',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 상인: 'Seller', 마르타: 'Marta' },
    outro: [
      'Was the food in Barcelona yummy?',
      'What is most important for building a human tower?',
      'What book would you give a friend?',
    ],
    lines: [
      ['해설', 'Last time, Hana saw Gaudi’s amazing buildings.'],
      ['해설', 'Today, she visits a big food market with Marta.'],
      ['상인', 'Hola! Would you like some fruit juice?'],
      ['마르타', 'We often eat bread with tomato.'],
      ['안내인', 'Rub tomato on bread. Add olive oil and salt.'],
      ['상인', 'This is paella. It has rice and seafood.'],
      ['안내인', 'A spice called saffron makes the rice yellow.'],
      ['마르타', 'The crispy rice at the bottom is the best!'],
      ['상인', 'Tapas are small plates of food to share.'],
      ['마르타', 'Here, people build human towers!'],
      ['안내인', 'People stand on shoulders. A child climbs to the top.'],
      ['하나', 'Is the child scared?'],
      ['마르타', 'No! The child wears a helmet. Everyone holds tight.'],
      ['안내인', 'On April 23, people give books and roses.'],
      ['안내인', 'In September, the La Merce festival has parades and fireworks.'],
      ['마르타', 'We eat dinner quite late, after dark.'],
      ['상인', 'People ride the metro, buses and bikes.'],
      ['하나', 'Tell me a fun fact!'],
      ['안내인', 'Many city blocks have cut corners.'],
      ['안내인', 'From the sky, they look like octagons.'],
      ['해설', 'Today we learned about paella, tapas and human towers.'],
      ['해설', 'Barcelona is full of sea, sun and big ideas.'],
    ],
  },

  'ct-berlin-1': {
    title: 'Berlin, Part 1',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 막스: 'Max' },
    outro: [
      'What did you think of Berlin?',
      'How did people feel when the wall came down?',
      'What would you say to a friend you have not seen for long?',
    ],
    lines: [
      ['해설', 'Hana and the Guide arrive in Berlin.'],
      ['하나', 'Where is Berlin?'],
      ['안내인', 'Berlin is the capital of Germany, in the middle of Europe.'],
      ['안내인', 'The Spree River flows through Berlin. There are many lakes.'],
      ['해설', 'Berlin has four seasons. Winters are quite cold.'],
      ['막스', 'Hallo! I am Max. I live in Berlin.'],
      ['막스', 'We also say guten Tag. It means good day.'],
      ['안내인', 'About eight hundred years ago, two small towns grew here.'],
      ['해설', 'Slowly, the two towns became one city, Berlin.'],
      ['안내인', 'The Brandenburg Gate was built in the late 1700s.'],
      ['안내인', 'In 1871, Berlin became the capital of the German Empire.'],
      ['해설', 'After a big war, Berlin was split into east and west.'],
      ['안내인', 'In 1961, a tall wall was built across the city.'],
      ['하나', 'So families could not meet?'],
      ['안내인', 'Right. But in 1989, the wall came down.'],
      ['해설', 'In 1990, Germany became one country again.'],
      ['막스', 'The Brandenburg Gate is the symbol of Berlin!'],
      ['안내인', 'Now everyone can walk through it.'],
      ['막스', 'At the East Side Gallery, artists painted on the old wall.'],
      ['안내인', 'You can walk up the glass dome on the parliament building.'],
      ['하나', 'I can see the whole city from up there!'],
      ['해설', 'Berlin was split by a wall in 1961. It came down in 1989.'],
    ],
  },

  'ct-berlin-2': {
    title: 'Berlin, Part 2',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 할아버지: 'Grandpa', 막스: 'Max' },
    outro: [
      'Did you enjoy the food in Berlin?',
      'Why is it good to return empty bottles?',
      'What gift would you like on your first school day?',
    ],
    lines: [
      ['해설', 'Last time, Hana learned about the Berlin Wall.'],
      ['해설', 'Today, she walks around town with Max’s grandpa.'],
      ['할아버지', 'Guten Tag! Let’s eat currywurst first.'],
      ['안내인', 'It is sausage with ketchup sauce and curry powder.'],
      ['할아버지', 'People say it was first made in Berlin.'],
      ['막스', 'Next is doner kebab! It is meat and vegetables in bread.'],
      ['안내인', 'People from Turkey brought it. Now everyone loves it.'],
      ['할아버지', 'This is a pretzel. It is bread tied in a knot.'],
      ['막스', 'It is chewy and salty. Yum!'],
      ['안내인', 'In winter, there are Christmas markets with bright lights.'],
      ['막스', 'Bring back empty bottles, and you get some money!'],
      ['할아버지', 'Many shops close on Sundays. It is a rest day.'],
      ['하나', 'How do people get around?'],
      ['막스', 'We take the subway, trains and trams. Many people ride bikes.'],
      ['할아버지', 'On the first school day, children get a big paper cone.'],
      ['막스', 'It is full of school things and sweets!'],
      ['하나', 'Tell me a fun fact!'],
      ['안내인', 'The symbol of Berlin is a bear. It is on the flag.'],
      ['막스', 'Look at the traffic light! The little man wears a hat.'],
      ['안내인', 'It comes from old East Berlin. People still love it.'],
      ['해설', 'Today we learned about currywurst, pretzels and life in Berlin.'],
      ['해설', 'Berlin is a city that became one again.'],
    ],
  },
};
