// 영어 학습용 원고: 세계 도시 탐방 (동아시아). 문장은 자체 집필.
// 키 = stories/city-a.js 의 이야기 id. lines 의 첫 칸은 한국어 cast 이름 그대로.
export default {
  'ct-seoul-1': {
    title: 'Seoul, Part 1',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 민준: 'Minjun' },
    outro: [
      'Did you enjoy our first day in Seoul?',
      'Why did Joseon choose a city by the Han River?',
      'Which place in Seoul would you like to visit?',
    ],
    lines: [
      ['해설', 'Today, Hana and the Guide went to Seoul.'],
      ['하나', 'Seoul is the capital of Korea, right?'],
      ['안내인', 'Yes! Seoul is in the middle of the Korean Peninsula.'],
      ['안내인', 'The wide Han River flows through the city.'],
      ['안내인', 'Seoul has four clear seasons. Summer is hot. Winter is cold.'],
      ['민준', 'Hi! I am Minjun. Welcome to Seoul!'],
      ['해설', 'The Guide told the story of Seoul.'],
      ['안내인', 'Long ago, Baekje had its capital near the Han River.'],
      ['안내인', 'In 1394, King Taejo of Joseon moved the capital here.'],
      ['민준', 'Back then, Seoul was called Hanyang.'],
      ['안내인', 'In 1395, the king built Gyeongbokgung Palace.'],
      ['안내인', 'In 1446, King Sejong shared the Korean alphabet here.'],
      ['안내인', 'In 1988, Seoul held the Olympic Games.'],
      ['해설', 'Then they visited three famous places.'],
      ['민준', 'First, Gyeongbokgung Palace! It stands below a mountain.'],
      ['하나', 'Look! The roof corners point up to the sky.'],
      ['안내인', 'Second, Namsan. From the tower, you can see all of Seoul.'],
      ['민준', 'Third, Cheonggyecheon. It is a stream in the city center.'],
      ['하나', 'I can hear water between the tall buildings!'],
      ['해설', 'Seoul has the Han River. It became the capital in 1394.'],
      ['해설', 'Next time, we will learn about food and life in Seoul.'],
    ],
  },

  'ct-seoul-2': {
    title: 'Seoul, Part 2',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 상인: 'Seller' },
    outro: [
      'Was our food trip in Seoul tasty?',
      'What did the big gates do in old Seoul?',
      'Which Seoul food do you want to try most?',
    ],
    lines: [
      ['해설', 'Last time, Hana learned about the history of Seoul.'],
      ['해설', 'Today, she went to an old market.'],
      ['상인', 'Welcome! Try a crispy bindaetteok!'],
      ['하나', 'What is it made of?'],
      ['상인', 'Ground mung beans. I fry them in oil. Sizzle, sizzle!'],
      ['안내인', 'Dip it in soy sauce and eat it warm.'],
      ['하나', 'Next is tteokbokki! It is red and chewy.'],
      ['안내인', 'Rice cakes cook in a spicy red pepper sauce.'],
      ['상인', 'Third is seolleongtang. It is a milky beef bone soup.'],
      ['안내인', 'Add salt and green onion. Eat it with rice.'],
      ['해설', 'Then they walked to the palace gate.'],
      ['하나', 'Look! Guards in old clothes are marching!'],
      ['안내인', 'It is the changing of the gate guards.'],
      ['안내인', 'In spring, colorful lanterns light up the streets.'],
      ['상인', 'Give things to elders with two hands. That is polite.'],
      ['안내인', 'People ride subways and buses all over the city.'],
      ['안내인', 'Long ago, a stone wall went around Seoul.'],
      ['안내인', 'It had big gates, like Sungnyemun and Heunginjimun.'],
      ['해설', 'Seoul foods are bindaetteok, tteokbokki, and seolleongtang.'],
      ['해설', 'In Seoul, old and new things live side by side.'],
    ],
  },

  'ct-gyeongju-1': {
    title: 'Gyeongju, Part 1',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 할머니: 'Grandma' },
    outro: [
      'Did you enjoy our first day in Gyeongju?',
      'Why did Silla people watch the stars?',
      'What would you build for people a thousand years later?',
    ],
    lines: [
      ['해설', 'Hana and the Guide took a train to Gyeongju.'],
      ['안내인', 'Gyeongju is in the southeast of Korea.'],
      ['안내인', 'A river flows through it. Mountains are all around.'],
      ['안내인', 'It has four seasons. Cherry blossoms bloom in spring.'],
      ['할머니', 'Eoseo oiso! That means welcome here.'],
      ['해설', 'Grandma told an old story.'],
      ['할머니', 'A legend says Silla’s first king came from an egg.'],
      ['안내인', 'Silla lasted almost one thousand years.'],
      ['안내인', 'Gyeongju was its capital the whole time.'],
      ['안내인', 'In the 600s, Silla built Cheomseongdae to watch stars.'],
      ['안내인', 'In the 600s, Silla also united three kingdoms.'],
      ['안내인', 'In the 700s, people began to build Bulguksa and Seokguram.'],
      ['안내인', 'In 935, Silla ended and Goryeo came next.'],
      ['해설', 'Then they visited three famous places.'],
      ['할머니', 'First, Bulguksa Temple. Two stone towers stand side by side.'],
      ['안내인', 'Second, Seokguram. A stone Buddha sits in a stone cave.'],
      ['하나', 'People built a cave with stones? Amazing!'],
      ['할머니', 'Third, Cheomseongdae. It is round and made of stones.'],
      ['하나', 'It looks like a big bottle!'],
      ['해설', 'Gyeongju was Silla’s capital for almost one thousand years.'],
      ['해설', 'Next time, we will learn about food and life in Gyeongju.'],
    ],
  },

  'ct-gyeongju-2': {
    title: 'Gyeongju, Part 2',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 지우: 'Jiu' },
    outro: [
      'Was our second day in Gyeongju fun?',
      'Why should we not climb on the royal tombs?',
      'What would you show people in your town?',
    ],
    lines: [
      ['해설', 'Last time, Hana learned about old Silla in Gyeongju.'],
      ['해설', 'Today, her friend Jiu showed her around.'],
      ['지우', 'Hi, Hana! Let’s eat something yummy first.'],
      ['지우', 'This is Gyeongju bread. It has sweet red beans inside.'],
      ['지우', 'This is barley bread. It is soft and chewy.'],
      ['하나', 'Yum! It tastes nutty.'],
      ['안내인', 'Third is ssambap. Wrap rice in fresh leaves.'],
      ['하나', 'Rice, sauce, and lettuce. One big bite!'],
      ['해설', 'Then they walked to Daereungwon.'],
      ['하나', 'Wow! The green hills are so round!'],
      ['안내인', 'They are not hills. They are tombs of Silla kings.'],
      ['안내인', 'A painting of a flying horse was found in one.'],
      ['지우', 'Do not climb the tombs. Walk quietly.'],
      ['해설', 'In autumn, there is a big Silla festival.'],
      ['지우', 'Many people ride bikes around the old places.'],
      ['지우', 'The museum has a huge old bell from Silla.'],
      ['안내인', 'People call Gyeongju a museum without a roof.'],
      ['지우', 'Many shops here have old tile roofs.'],
      ['해설', 'Gyeongju foods are Gyeongju bread, barley bread, and ssambap.'],
      ['해설', 'The whole city is a treasure box of Silla.'],
    ],
  },

  'ct-tokyo-1': {
    title: 'Tokyo, Part 1',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 유키: 'Yuki' },
    outro: [
      'Did you enjoy our first day in Tokyo?',
      'How did the small village of Edo become a big city?',
      'After a big earthquake, what would you rebuild first?',
    ],
    lines: [
      ['해설', 'Hana and the Guide flew to Tokyo, the capital of Japan.'],
      ['안내인', 'Japan is an island country in East Asia.'],
      ['안내인', 'Tokyo is on Honshu, the biggest island.'],
      ['안내인', 'It is by Tokyo Bay. The Sumida River flows here.'],
      ['안내인', 'It has four seasons and a rainy season in early summer.'],
      ['유키', 'Konnichiwa! I am Yuki. That means hello.'],
      ['해설', 'The Guide told the story of Tokyo.'],
      ['안내인', 'Long ago, it was a small village called Edo.'],
      ['안내인', 'In 1603, Tokugawa Ieyasu set up his government in Edo.'],
      ['안내인', 'Then Edo grew into a big, busy city.'],
      ['안내인', 'In 1868, its name changed to Tokyo. It means eastern capital.'],
      ['안내인', 'In 1923, a big earthquake hit. People rebuilt the city.'],
      ['안내인', 'In 1964, Tokyo held the first Olympics in Asia.'],
      ['해설', 'Then they visited three famous places.'],
      ['유키', 'First, Sensoji. People say it is Tokyo’s oldest temple.'],
      ['하나', 'Look! A big red lantern hangs on the gate!'],
      ['유키', 'Second, the Imperial Palace. Old Edo Castle stood there.'],
      ['유키', 'Third, Meiji Shrine. It has a big forest.'],
      ['안내인', 'People planted trees from all over Japan there.'],
      ['해설', 'Tokyo was once Edo. It became Tokyo in 1868.'],
      ['해설', 'Next time, we will learn about food and life in Tokyo.'],
    ],
  },

  'ct-tokyo-2': {
    title: 'Tokyo, Part 2',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 요리사: 'Cook' },
    outro: [
      'Was our food trip in Tokyo tasty?',
      'Why do people in Tokyo talk quietly on trains?',
      'What do you say before you eat?',
    ],
    lines: [
      ['해설', 'Last time, Hana learned how Edo became Tokyo.'],
      ['해설', 'Today, she learned about food and life in Tokyo.'],
      ['요리사', 'Irasshaimase! That means welcome.'],
      ['안내인', 'First is sushi. Fish sits on top of rice.'],
      ['요리사', 'People say hand-made sushi spread from Edo.'],
      ['요리사', 'Dip the fish side in soy sauce. Eat it in one bite.'],
      ['안내인', 'Second is tempura. Shrimp and vegetables are fried crispy.'],
      ['안내인', 'Third is monjayaki. Thin batter cooks on a hot plate.'],
      ['요리사', 'Eat it right off the plate with a tiny spatula.'],
      ['하나', 'That is different from home. It is fun!'],
      ['안내인', 'Before meals, people say itadakimasu. It means thank you for the food.'],
      ['안내인', 'In spring, people enjoy cherry blossoms in the park.'],
      ['안내인', 'In summer, fireworks light up the Sumida River.'],
      ['요리사', 'At the Sanja festival, people carry a shrine through the streets.'],
      ['안내인', 'Trains go everywhere, and they are right on time.'],
      ['안내인', 'On trains, people do not talk loudly on the phone.'],
      ['요리사', 'Kids carry square school bags called randoseru.'],
      ['안내인', 'In Shibuya, crowds cross a big street from every side.'],
      ['해설', 'Tokyo foods are sushi, tempura, and monjayaki.'],
      ['해설', 'Tokyo mixes old Edo with a busy new city.'],
    ],
  },

  'ct-kyoto-1': {
    title: 'Kyoto, Part 1',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 할아버지: 'Grandpa' },
    outro: [
      'Did you enjoy our first day in Kyoto?',
      'Why are Kyoto’s streets straight like a game board?',
      'How would you feel walking through the red gates?',
    ],
    lines: [
      ['해설', 'Hana and the Guide arrived in Kyoto, an old capital of Japan.'],
      ['안내인', 'Kyoto is on Honshu, like Tokyo.'],
      ['안내인', 'Mountains are on three sides. The Kamo River flows here.'],
      ['안내인', 'Summer is very hot. Winter is quite cold.'],
      ['할아버지', 'Oideyasu! That means welcome in Kyoto.'],
      ['해설', 'Grandpa told the story of Kyoto.'],
      ['할아버지', 'In 794, the capital of Japan moved here.'],
      ['안내인', 'Its streets were made straight, like a game board.'],
      ['할아버지', 'The emperors lived here for over a thousand years.'],
      ['안내인', 'In the 1400s, a big war burned many buildings.'],
      ['안내인', 'People built them again.'],
      ['안내인', 'In the late 1800s, the capital moved to Tokyo.'],
      ['해설', 'Then they visited three famous places.'],
      ['할아버지', 'First, Kiyomizu-dera. It has a big wooden stage.'],
      ['하나', 'I can see all of Kyoto from here!'],
      ['할아버지', 'Second, Kinkaku-ji. A golden building shines over a pond.'],
      ['할아버지', 'Third, Fushimi Inari Shrine. Red gates go on and on.'],
      ['하나', 'One, two, three... There are too many to count!'],
      ['안내인', 'These red gates are called torii.'],
      ['해설', 'From 794, Kyoto was Japan’s capital for over a thousand years.'],
      ['해설', 'Next time, we will learn about food and life in Kyoto.'],
    ],
  },

  'ct-kyoto-2': {
    title: 'Kyoto, Part 2',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 찻집주인: 'Tea Lady' },
    outro: [
      'Was our second day in Kyoto fun?',
      'Why should we ask before taking a photo of someone?',
      'If streets in your town had numbers, how would you name them?',
    ],
    lines: [
      ['해설', 'Last time, Hana visited famous places in Kyoto.'],
      ['해설', 'Today, she went into a small tea shop.'],
      ['찻집주인', 'Oideyasu! Would you like some matcha?'],
      ['하나', 'What is matcha? It is green!'],
      ['찻집주인', 'It is tea powder. Mix it with hot water.'],
      ['하나', 'It is a little bitter, but it smells nice.'],
      ['찻집주인', 'Try yatsuhashi, too. It is a famous Kyoto sweet.'],
      ['안내인', 'It is made of rice flour and tastes like cinnamon.'],
      ['안내인', 'Third is yudofu. Warm tofu is dipped in sauce.'],
      ['하나', 'The tofu is soft and mild.'],
      ['해설', 'Then they walked to the Gion area.'],
      ['안내인', 'That girl is a maiko. She learns old dances and songs.'],
      ['안내인', 'Do not take her photo without asking.'],
      ['찻집주인', 'In July, big floats roll slowly down the streets.'],
      ['안내인', 'That is the Gion Festival. People say it is very old.'],
      ['안내인', 'At temples and shrines, walk quietly.'],
      ['찻집주인', 'Many people here ride buses and bikes.'],
      ['안내인', 'Some streets have numbers in their names.'],
      ['안내인', 'Shijo means the fourth street.'],
      ['해설', 'Kyoto foods are matcha, yatsuhashi, and yudofu.'],
      ['해설', 'In Kyoto, old Japan is still alive today.'],
    ],
  },

  'ct-beijing-1': {
    title: 'Beijing, Part 1',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 샤오린: 'Xiaolin' },
    outro: [
      'Did you enjoy our first day in Beijing?',
      'Why are the palace roofs yellow?',
      'Who would you like to walk the Great Wall with?',
    ],
    lines: [
      ['해설', 'Hana and the Guide arrived in Beijing, the capital of China.'],
      ['안내인', 'Beijing is in the north of China, in East Asia.'],
      ['안내인', 'Mountains are to the north and west.'],
      ['안내인', 'Winter is cold and dry. Summer is hot and rainy.'],
      ['샤오린', 'Ni hao! I am Xiaolin. That means hello.'],
      ['해설', 'The Guide told the story of Beijing.'],
      ['안내인', 'People have lived here for a very long time.'],
      ['안내인', 'In the 1200s, the Yuan built a capital here.'],
      ['안내인', 'In the early 1400s, the Ming moved their capital here.'],
      ['안내인', 'They built the Forbidden City.'],
      ['샤오린', 'Beijing means northern capital.'],
      ['안내인', 'Later, the Qing also made Beijing their capital.'],
      ['안내인', 'Beijing held the Summer Olympics in 2008.'],
      ['안내인', 'It held the Winter Olympics in 2022.'],
      ['해설', 'Then they visited three famous places.'],
      ['샤오린', 'First, the Forbidden City. Emperors lived in this palace.'],
      ['안내인', 'The roofs are yellow. Yellow was the emperor’s color.'],
      ['안내인', 'Second, the Great Wall. It runs over the mountains.'],
      ['하나', 'It looks like a dragon on the hills!'],
      ['샤오린', 'Third, the Temple of Heaven. Emperors prayed for good crops.'],
      ['해설', 'Beijing means northern capital. It has the Forbidden City.'],
      ['해설', 'Next time, we will learn about food and life in Beijing.'],
    ],
  },

  'ct-beijing-2': {
    title: 'Beijing, Part 2',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 할아버지: 'Grandpa' },
    outro: [
      'Was our food trip in Beijing tasty?',
      'Why do the hutong houses have a yard in the middle?',
      'What food does your family make on New Year’s Day?',
    ],
    lines: [
      ['해설', 'Last time, Hana visited the Forbidden City.'],
      ['해설', 'Today, she met a grandpa in an old alley.'],
      ['할아버지', 'Ni hao! Welcome to my hutong!'],
      ['안내인', 'A hutong is an old, narrow alley in Beijing.'],
      ['할아버지', 'Our houses have a square yard in the middle.'],
      ['할아버지', 'First, try roast duck. The skin is crispy!'],
      ['안내인', 'Wrap duck, green onion, and cucumber in a thin pancake.'],
      ['할아버지', 'Second, zhajiangmian. Noodles with a salty bean sauce.'],
      ['안내인', 'It is like Korean jjajangmyeon, but saltier.'],
      ['할아버지', 'Third, tanghulu. Red fruits on a stick, coated in sugar.'],
      ['하나', 'Crunch! Sweet outside and sour inside!'],
      ['해설', 'Then they went to the park.'],
      ['할아버지', 'This slow exercise is tai chi. It keeps us healthy.'],
      ['안내인', 'People also kick shuttlecocks and fly kites here.'],
      ['안내인', 'Beijing opera is famous. Singers paint their faces brightly.'],
      ['할아버지', 'At Lunar New Year, we hang red lanterns and make dumplings.'],
      ['안내인', 'Children get money in red envelopes.'],
      ['할아버지', 'Do not stand chopsticks up in your rice.'],
      ['안내인', 'People ride subways, buses, and bikes.'],
      ['안내인', 'Ring roads circle the city again and again.'],
      ['해설', 'Beijing foods are roast duck, zhajiangmian, and tanghulu.'],
      ['해설', 'Beijing mixes old palaces with friendly alleys.'],
    ],
  },
};
