// 영어 학습용 원고: 세계 도시 탐방 (하노이, 방콕, 델리, 이스탄불, 카이로). 문장은 자체 집필.
// 키 = stories/city-b.js 의 이야기 id. lines 의 첫 칸은 원래 이야기 cast 의 한국어 이름 그대로.
export default {
  'ct-hanoi-1': {
    title: 'Hanoi, Part 1',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 린: 'Linh' },
    outro: [
      'Did you enjoy our trip to Hanoi?',
      'What is the old story about Hoan Kiem Lake?',
      'What would you like to see in a very old city?',
    ],
    lines: [
      ['해설', 'Hana and the Guide arrive in Hanoi, Vietnam.'],
      ['하나', 'Wow, so many motorbikes! Vroom, vroom!'],
      ['안내인', 'Hanoi is the capital of Vietnam, in Southeast Asia.'],
      ['안내인', 'The Red River flows beside the city.'],
      ['안내인', 'Hanoi means inside the rivers.'],
      ['해설', 'Summers are hot and rainy. Winters are cool.'],
      ['린', 'Xin chao! I am Linh. Welcome to Hanoi!'],
      ['안내인', 'Xin chao means hello in Vietnamese.'],
      ['린', 'In 1010, a king moved the capital here.'],
      ['안내인', 'Its old name, Thang Long, means rising dragon.'],
      ['해설', 'In 1070, people built the Temple of Literature.'],
      ['안내인', 'Soon a school opened there. It is called Vietnam’s first university.'],
      ['해설', 'Later, France ruled Vietnam for many years.'],
      ['안내인', 'In 1945, Vietnam declared independence in Hanoi.'],
      ['안내인', 'Since 1976, Hanoi has been the capital of united Vietnam.'],
      ['해설', 'First, we visit Hoan Kiem Lake.'],
      ['린', 'A legend says a king returned a magic sword here.'],
      ['해설', 'Next, we visit the Temple of Literature.'],
      ['안내인', 'Stone turtles carry tablets with old names on them.'],
      ['해설', 'Then we walk in the Old Quarter.'],
      ['린', 'Long ago, each street sold one kind of thing.'],
      ['하나', 'A silver street and a bamboo street! How fun!'],
      ['해설', 'Hanoi is over one thousand years old.'],
    ],
  },

  'ct-hanoi-2': {
    title: 'Hanoi, Part 2',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 린: 'Linh', 아주머니: 'Cook' },
    outro: [
      'Was the food trip fun?',
      'Where do people stand in a water puppet show?',
      'Which Hanoi food do you want to try?',
    ],
    lines: [
      ['해설', 'Last time, Hana visited old Hanoi. Today, she tries the food.'],
      ['린', 'Let’s eat pho for breakfast!'],
      ['아주머니', 'Pho is flat rice noodles in a clear meat soup.'],
      ['안내인', 'Pho comes from northern Vietnam.'],
      ['하나', 'Slurp! The soup is warm and yummy!'],
      ['해설', 'For lunch, they eat bun cha.'],
      ['린', 'Dip the noodles and grilled pork in the sweet sauce.'],
      ['해설', 'For dinner, they try cha ca, a yellow fish dish.'],
      ['안내인', 'The fish is cooked at the table with dill.'],
      ['해설', 'Hanoi has water puppet shows.'],
      ['안내인', 'People stand in the water behind a screen.'],
      ['안내인', 'They move the puppets with long poles.'],
      ['해설', 'The biggest holiday is Tet, the Lunar New Year.'],
      ['아주머니', 'At Tet, we make square sticky rice cakes.'],
      ['린', 'At the moon festival, kids carry lanterns!'],
      ['안내인', 'Give things to elders with two hands.'],
      ['해설', 'Many people ride motorbikes to school and work.'],
      ['린', 'Hold a grown-up’s hand and cross slowly.'],
      ['안내인', 'Fun fact! Hanoi has egg coffee with sweet foam.'],
      ['하나', 'Hanoi is full of surprises!'],
      ['해설', 'Pho, bun cha, cha ca, and puppets make Hanoi special.'],
    ],
  },

  'ct-bangkok-1': {
    title: 'Bangkok, Part 1',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 솜: 'Som' },
    outro: [
      'Did you like our trip to Bangkok?',
      'When was Bangkok made the capital?',
      'How would you make your own special hello?',
    ],
    lines: [
      ['해설', 'Hana and the Guide arrive in Bangkok, Thailand.'],
      ['하나', 'It is so sunny! What are those shiny roofs?'],
      ['안내인', 'Bangkok is the capital of Thailand, in Southeast Asia.'],
      ['안내인', 'The Chao Phraya River flows through the city.'],
      ['해설', 'It is hot all year, with a rainy season.'],
      ['솜', 'Sawasdee ka! I am Som. Welcome to Bangkok!'],
      ['안내인', 'Sawasdee means hello. Girls add ka, and boys add krap.'],
      ['해설', 'Som puts her hands together and bows. This is a wai.'],
      ['솜', 'We call our city Krung Thep, the city of angels.'],
      ['안내인', 'Long ago, the capital was Ayutthaya.'],
      ['안내인', 'Ayutthaya fell in a war in 1767.'],
      ['안내인', 'In 1782, a new king built a capital here.'],
      ['해설', 'That was Bangkok. The Grand Palace was started then.'],
      ['안내인', 'In the 1800s, kings built railways and schools.'],
      ['안내인', 'In 1932, Thailand got a constitution.'],
      ['해설', 'First, we visit the Grand Palace and Wat Phra Kaew.'],
      ['솜', 'The Emerald Buddha is there. It is green stone.'],
      ['해설', 'Next is Wat Pho, with a huge lying Buddha.'],
      ['하나', 'Look at its big, shiny feet!'],
      ['해설', 'Then we see Wat Arun, the Temple of Dawn.'],
      ['안내인', 'Colorful bits of china make it sparkle.'],
      ['해설', 'Bangkok became Thailand’s capital in 1782.'],
    ],
  },

  'ct-bangkok-2': {
    title: 'Bangkok, Part 2',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 솜: 'Som', 상인: 'Seller' },
    outro: [
      'Was the Bangkok food trip yummy?',
      'What did people first do with water at Songkran?',
      'Who would you wish good luck to at New Year?',
    ],
    lines: [
      ['해설', 'Last time, Hana saw temples in Bangkok. Today, she eats!'],
      ['해설', 'First, she tries tom yum goong, a spicy shrimp soup.'],
      ['상인', 'It has lemongrass, lime leaves, and chili.'],
      ['하나', 'Slurp! Spicy, sour, and yummy!'],
      ['해설', 'Next is pad thai, fried rice noodles with egg.'],
      ['상인', 'Add peanuts and squeeze some lime.'],
      ['솜', 'For dessert, mango with sticky rice and coconut milk!'],
      ['안내인', 'Thai people eat with a spoon and a fork.'],
      ['안내인', 'The fork pushes food onto the spoon.'],
      ['해설', 'In April, Thai people celebrate Songkran, the Thai New Year.'],
      ['솜', 'We splash water on each other! Splash, splash!'],
      ['안내인', 'Long ago, people gently poured water on elders’ hands.'],
      ['해설', 'At Loy Krathong, people float little boats on the river.'],
      ['안내인', 'Do not touch someone’s head.'],
      ['안내인', 'Take off your shoes in a temple.'],
      ['해설', 'People ride boats, trains, and buses.'],
      ['하나', 'What is that little car with three wheels?'],
      ['솜', 'It is a tuk-tuk!'],
      ['안내인', 'Fun fact! Bangkok’s full name is very, very long.'],
      ['하나', 'I would run out of breath!'],
      ['해설', 'Tom yum, pad thai, and Songkran make Bangkok special.'],
    ],
  },

  'ct-delhi-1': {
    title: 'Delhi, Part 1',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 라비: 'Ravi' },
    outro: [
      'Did you enjoy our trip to Delhi?',
      'What else did the emperor Shah Jahan build?',
      'Have you ever visited an old castle or tower?',
    ],
    lines: [
      ['해설', 'Hana and the Guide arrive in Delhi, India.'],
      ['하나', 'So many people! Beep, beep go the cars!'],
      ['안내인', 'Delhi is a big city in South Asia.'],
      ['안내인', 'New Delhi, the capital of India, is part of Delhi.'],
      ['안내인', 'The Yamuna River flows by the city.'],
      ['해설', 'Summers are very hot. Winters are cool.'],
      ['라비', 'Namaste! I am Ravi. Welcome to Delhi!'],
      ['안내인', 'Namaste is a Hindi hello. Put your hands together.'],
      ['라비', 'Many kings built new cities here, again and again.'],
      ['안내인', 'About 800 years ago, they began the Qutub Minar.'],
      ['안내인', 'In the 1600s, Shah Jahan built the Red Fort.'],
      ['안내인', 'He also built the Taj Mahal in Agra.'],
      ['해설', 'Later, Britain ruled India for a long time.'],
      ['안내인', 'In 1911, the British moved the capital to Delhi.'],
      ['안내인', 'India became independent on August 15, 1947.'],
      ['라비', 'On that day each year, we fly kites!'],
      ['해설', 'First, we visit the Red Fort.'],
      ['안내인', 'Its long walls are made of red stone.'],
      ['해설', 'Next is the Qutub Minar, a very tall tower.'],
      ['해설', 'Then we see India Gate, a big stone arch.'],
      ['안내인', 'It honors Indian soldiers from long-ago wars.'],
      ['해설', 'Delhi has many layers of history by the Yamuna River.'],
    ],
  },

  'ct-delhi-2': {
    title: 'Delhi, Part 2',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 라비: 'Ravi', 상인: 'Seller' },
    outro: [
      'Was the Delhi food trip yummy?',
      'What do people light at Diwali?',
      'How would you decorate your home for a festival of lights?',
    ],
    lines: [
      ['해설', 'Last time, Hana saw old Delhi. Today, she visits a market.'],
      ['라비', 'Let’s go to Chandni Chowk!'],
      ['안내인', 'This market street is hundreds of years old.'],
      ['상인', 'Welcome! Try some crunchy chaat!'],
      ['안내인', 'Chaat is a snack with yogurt and sauces.'],
      ['하나', 'Crunch! Sweet, sour, and a little spicy!'],
      ['해설', 'Next is paratha, a flat bread with potato inside.'],
      ['해설', 'Then they eat butter chicken, a soft and creamy curry.'],
      ['안내인', 'People say butter chicken was first made in Delhi.'],
      ['라비', 'Tear the bread and dip it in the curry.'],
      ['안내인', 'In India, people usually eat with the right hand.'],
      ['해설', 'After dinner, they drink chai, a spiced milk tea.'],
      ['해설', 'In autumn, Delhi celebrates Diwali, the festival of lights.'],
      ['라비', 'We light little lamps and share sweets!'],
      ['해설', 'In spring, people throw colored powder at Holi.'],
      ['안내인', 'Take off your shoes in a temple.'],
      ['해설', 'People ride the metro and auto rickshaws.'],
      ['라비', 'At school, I learn Hindi and English.'],
      ['안내인', 'Fun fact! Delhi has a temple shaped like a lotus flower.'],
      ['하나', 'A lotus temple! I want to see it!'],
      ['해설', 'Chaat, butter chicken, and Diwali make Delhi special.'],
    ],
  },

  'ct-istanbul-1': {
    title: 'Istanbul, Part 1',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 엘리프: 'Elif' },
    outro: [
      'Did you enjoy our trip to Istanbul?',
      'Which two continents is Istanbul on?',
      'How would you feel crossing to another continent by boat?',
    ],
    lines: [
      ['해설', 'Hana and the Guide arrive in Istanbul, Turkey.'],
      ['하나', 'So many boats on the water! Toot, toot!'],
      ['안내인', 'This water is the Bosphorus.'],
      ['안내인', 'The west side is Europe. The east side is Asia.'],
      ['하나', 'So Istanbul is on two continents?'],
      ['안내인', 'Yes! It is a very rare city.'],
      ['해설', 'Summers are warm. Winters are rainy and cool.'],
      ['엘리프', 'Merhaba! I am Elif. Welcome to Istanbul!'],
      ['안내인', 'Merhaba means hello in Turkish.'],
      ['엘리프', 'Long ago, Greek people built a city called Byzantion.'],
      ['안내인', 'In 330, a Roman emperor made it his capital.'],
      ['안내인', 'It was called Constantinople.'],
      ['해설', 'In 537, the Hagia Sophia was finished.'],
      ['안내인', 'In 1453, the Ottomans took the city.'],
      ['안내인', 'It was their capital for about 470 years.'],
      ['해설', 'In 1923, Ankara became the capital of Turkey.'],
      ['해설', 'First, we visit the Hagia Sophia, with its huge dome.'],
      ['해설', 'Next is the Blue Mosque.'],
      ['엘리프', 'It has blue tiles inside and six towers!'],
      ['해설', 'Then we see Topkapi Palace, home of Ottoman sultans.'],
      ['하나', 'I can see the sea from the garden!'],
      ['해설', 'Istanbul sits on both Europe and Asia.'],
    ],
  },

  'ct-istanbul-2': {
    title: 'Istanbul, Part 2',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 엘리프: 'Elif', 상인: 'Seller' },
    outro: [
      'Was the Istanbul food trip yummy?',
      'How do people in Istanbul care for street cats?',
      'What would you like to take care of in your town?',
    ],
    lines: [
      ['해설', 'Last time, Hana saw old Istanbul. Today, she takes a boat.'],
      ['해설', 'She crosses the sea from Europe to Asia.'],
      ['하나', 'One boat ride, and I am in Asia!'],
      ['상인', 'Try simit, a round bread with sesame seeds.'],
      ['안내인', 'People drink tea in small tulip-shaped glasses.'],
      ['해설', 'For lunch, they eat kebab, grilled meat.'],
      ['상인', 'We slice the meat and wrap it in bread.'],
      ['하나', 'Yum! The meat is soft and tasty!'],
      ['엘리프', 'For a treat, we eat lokum. It is chewy and sweet.'],
      ['해설', 'Then they visit the Grand Bazaar, a huge covered market.'],
      ['상인', 'Come and see lamps, rugs, and spices!'],
      ['안내인', 'In a mosque, take off your shoes.'],
      ['해설', 'After Ramadan, families enjoy a sweet holiday for three days.'],
      ['엘리프', 'I kiss my grandma’s hand. She gives me candy!'],
      ['해설', 'In spring, tulips bloom all over the city.'],
      ['안내인', 'People ride ferries, trams, and a train under the sea.'],
      ['안내인', 'Fun fact! Istanbul has many street cats.'],
      ['엘리프', 'People put out food and water for them.'],
      ['하나', 'Meow! The cats live like neighbors!'],
      ['해설', 'Simit, kebab, and ferries make Istanbul special.'],
    ],
  },

  'ct-cairo-1': {
    title: 'Cairo, Part 1',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 유수프: 'Yusuf' },
    outro: [
      'Did you enjoy our trip to Cairo?',
      'Which is older, the pyramids or the city of Cairo?',
      'What would you leave for kids far in the future?',
    ],
    lines: [
      ['해설', 'Hana and the Guide arrive in Cairo, Egypt.'],
      ['하나', 'The sun is bright, and the sky is clear!'],
      ['안내인', 'Cairo is the capital of Egypt, in Africa.'],
      ['안내인', 'The long Nile River flows through the city.'],
      ['해설', 'Cairo is hot and dry. It rarely rains.'],
      ['유수프', 'Salaam alaikum! I am Yusuf. Welcome to Cairo!'],
      ['안내인', 'It is an Arabic hello. It means peace be with you.'],
      ['유수프', 'There is a very old treasure near Cairo.'],
      ['안내인', 'The pyramids of Giza are about 4,500 years old.'],
      ['안내인', 'They were tombs for kings called pharaohs.'],
      ['해설', 'The city of Cairo was built much later.'],
      ['안내인', 'It was built in the 900s. Its name means the victorious.'],
      ['해설', 'Soon, Al-Azhar became a famous place of learning.'],
      ['해설', 'In the 1100s, Saladin began a strong fort on a hill.'],
      ['해설', 'First, we visit the pyramids and the Sphinx.'],
      ['유수프', 'The Sphinx has a lion’s body and a human face.'],
      ['하나', 'How did people stack such big stones?'],
      ['해설', 'Next is the Citadel. We can see all of Cairo!'],
      ['해설', 'Then we walk in old Islamic Cairo.'],
      ['안내인', 'It is called the city of a thousand minarets.'],
      ['해설', 'Cairo sits by the Nile, near the great pyramids.'],
    ],
  },

  'ct-cairo-2': {
    title: 'Cairo, Part 2',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 유수프: 'Yusuf', 요리사: 'Cook' },
    outro: [
      'Was the Cairo food trip yummy?',
      'What makes a felucca move on the Nile?',
      'What would you put in your own mixed bowl?',
    ],
    lines: [
      ['해설', 'Last time, Hana saw the pyramids. Today, she tries Cairo food.'],
      ['유수프', 'Are you hungry? Let’s eat koshari!'],
      ['요리사', 'Koshari has rice, lentils, pasta, and chickpeas.'],
      ['요리사', 'We add tomato sauce and crispy onions.'],
      ['하나', 'Mix, mix, yum! It is so filling!'],
      ['해설', 'For breakfast, people eat ful, soft cooked fava beans.'],
      ['유수프', 'We eat it with round, flat bread.'],
      ['해설', 'Next is taameya, fried balls of fava beans.'],
      ['하나', 'Crunchy outside, green inside!'],
      ['해설', 'Then they visit Khan el-Khalili, a very old market.'],
      ['유수프', 'Lamps, spices, and glass bottles! Shiny, shiny!'],
      ['해설', 'During Ramadan, colorful lanterns hang in the streets.'],
      ['안내인', 'In spring, families have picnics and color eggs.'],
      ['안내인', 'Egyptians welcome guests warmly.'],
      ['해설', 'People ride the metro, buses, and boats.'],
      ['하나', 'What is that boat with a white sail?'],
      ['유수프', 'It is a felucca! The wind moves it.'],
      ['안내인', 'Fun fact! The Nile flows from south to north.'],
      ['안내인', 'The wind often comes from the north. Boats could sail upriver.'],
      ['하나', 'The wind and the river worked together!'],
      ['해설', 'Koshari, ful, and feluccas make Cairo special.'],
    ],
  },
};
