// 영어 학습용 원고 (한국 초등 저학년, 영어 초급). 문장은 자체 각색.
// 키 = stories/*.js 의 이야기 id. lines 의 첫 칸은 원래 이야기 cast 의 한국어 이름 그대로.
export default {
  'wf-anansi-wisdom-pot': {
    title: 'Anansi and the Pot of Wisdom',
    names: { 해설: 'Narrator', 아난시: 'Anansi', 은티쿠마: 'Ntikuma' },
    outro: [
      'Did you like Anansi’s story?',
      'If you were Anansi, would you share the wisdom?',
      'Who helped you learn something new?',
    ],
    lines: [
      ['해설', 'Long ago, Anansi the spider lived in a forest in Ghana.'],
      ['해설', 'One day, the Sky God gave Anansi a big pot.'],
      ['해설', 'The pot was full of all the wisdom in the world.'],
      ['아난시', 'All the wisdom is mine! I will not share it.'],
      ['아난시', 'I will hide it at the top of a tall tree.'],
      ['해설', 'Anansi tied the pot to his front.'],
      ['해설', 'He began to climb. Up, up, up!'],
      ['해설', 'But the pot hit the tree. Bump, bump!'],
      ['아난시', 'Oh no! I keep slipping down!'],
      ['해설', 'His son Ntikuma watched from below.'],
      ['은티쿠마', 'Dad, tie the pot on your back!'],
      ['해설', 'Anansi tied the pot on his back.'],
      ['해설', 'Now he climbed up easily.'],
      ['아난시', 'My little son is wise, too!'],
      ['해설', 'Anansi was so surprised. He dropped the pot.'],
      ['해설', 'Crash! The pot broke on a rock.'],
      ['해설', 'The wind blew. Whoosh! The wisdom flew all over the world.'],
      ['은티쿠마', 'Look, Dad! The wisdom is going everywhere!'],
      ['아난시', 'Ha ha. Now everyone has a little wisdom.'],
      ['해설', 'Wisdom grows when we share it.'],
    ],
  },

  'wf-anansi-turtle': {
    title: 'Anansi and Turtle',
    names: { 해설: 'Narrator', 아난시: 'Anansi', 거북: 'Turtle' },
    outro: [
      'Was Anansi’s story fun?',
      'If you were Turtle, how would you feel?',
      'What snack do you like to share with friends?',
    ],
    lines: [
      ['해설', 'Long ago, Anansi the spider lived in West Africa.'],
      ['해설', 'One day, Anansi cooked some yams. They smelled so good!'],
      ['해설', 'Knock, knock! Turtle came to the door.'],
      ['거북', 'Hello, Anansi. I walked all day. I am so hungry.'],
      ['아난시', 'Come in. But your hands are dirty.'],
      ['아난시', 'Go to the river and wash them.'],
      ['해설', 'Turtle walked slowly to the river. He washed his hands.'],
      ['해설', 'But on the way back, his hands got dirty again.'],
      ['아난시', 'Your hands are dirty! Go and wash them again.'],
      ['해설', 'Turtle went again. Anansi ate all the yams. Yum!'],
      ['아난시', 'Sorry, Turtle. The yams are all gone.'],
      ['거북', 'That is okay. Come to my house next time.'],
      ['해설', 'Turtle’s house was under the river.'],
      ['해설', 'Anansi jumped in, but he floated up.'],
      ['해설', 'So he put stones in his jacket. Down he went!'],
      ['거북', 'Welcome! At my house, we take off our jackets.'],
      ['해설', 'Anansi took off his jacket. Up he floated!'],
      ['아난시', 'Oh no! Now I cannot eat.'],
      ['아난시', 'Now I know how Turtle felt.'],
      ['해설', 'The next day, Anansi shared his yams with Turtle.'],
      ['해설', 'If you play tricks, tricks can come back to you.'],
    ],
  },

  'wf-mosquito-buzz': {
    title: 'Why Mosquitoes Buzz in Our Ears',
    names: { 해설: 'Narrator', 모기: 'Mosquito', 이구아나: 'Iguana', 비단뱀: 'Python', 토끼: 'Rabbit', 부엉이: 'Owl', 사자: 'Lion' },
    outro: [
      'Did you like this funny story?',
      'If you were Mosquito, what would you say to Lion?',
      'When did you tell the truth, even when it was hard?',
    ],
    lines: [
      ['해설', 'Long ago, a chatty mosquito lived in a forest.'],
      ['모기', 'Iguana! I saw an ant as big as a house!'],
      ['이구아나', 'That is silly! I do not want to hear it.'],
      ['해설', 'Iguana put sticks in his ears and walked away.'],
      ['비단뱀', 'Good morning, Iguana!'],
      ['해설', 'But Iguana could not hear. He said nothing.'],
      ['비단뱀', 'Is Iguana angry at me? I will hide!'],
      ['해설', 'Python went into Rabbit’s hole.'],
      ['토끼', 'Help! A python! Run!'],
      ['해설', 'Rabbit ran out. A monkey saw her and jumped.'],
      ['해설', 'Snap! A branch fell near Owl’s nest.'],
      ['해설', 'The baby owls cried. Mother Owl hugged them all night.'],
      ['해설', 'She forgot to hoot and wake the sun.'],
      ['해설', 'The sun did not come up. It stayed dark.'],
      ['사자', 'Everyone, come here! Why is it still dark?'],
      ['부엉이', 'The monkey scared us. Rabbit scared the monkey.'],
      ['토끼', 'Python scared me!'],
      ['비단뱀', 'Iguana did not say hello. I was scared.'],
      ['이구아나', 'Mosquito told me a silly story!'],
      ['해설', 'Mosquito hid in a bush. Owl hooted. Hoo, hoo!'],
      ['해설', 'The sun came up. The forest was bright again.'],
      ['해설', 'Now Mosquito buzzes in our ears. Is everyone still angry?'],
      ['해설', 'One small lie can make a big mess.'],
    ],
  },

  'wf-sun-moon-sky': {
    title: 'The Sun, the Moon, and Water',
    names: { 해설: 'Narrator', 해: 'Sun', 달: 'Moon', 물: 'Water' },
    outro: [
      'Did you like this story?',
      'If you were the Sun, would you open the door?',
      'How do you welcome friends to your home?',
    ],
    lines: [
      ['해설', 'Long ago, the Sun and the Moon lived on the earth.'],
      ['해설', 'Their best friend was Water.'],
      ['해', 'Water, please come to our house!'],
      ['물', 'My family is very big. Your house is too small.'],
      ['해', 'Then we will build a very big house!'],
      ['해설', 'The Sun and the Moon built a big house. Bang, bang!'],
      ['물', 'Knock, knock! May I come in?'],
      ['달', 'Yes! Come in, friend!'],
      ['해설', 'Water came in. Fish and frogs came in, too.'],
      ['해설', 'Soon the water was up to their knees.'],
      ['물', 'My family is still coming. Is that okay?'],
      ['해', 'Yes! A promise is a promise.'],
      ['해설', 'More water came in. Splash, splash!'],
      ['해설', 'The Sun and the Moon stood on chairs.'],
      ['해설', 'Then they climbed up on the roof.'],
      ['해설', 'The water came up to the roof, too.'],
      ['해설', 'The Sun and the Moon went up, up, up into the sky!'],
      ['달', 'Look! We can see the whole world!'],
      ['해', 'I will shine in the day. You can shine at night.'],
      ['해설', 'Water stayed on the earth. It became rivers and seas.'],
      ['해설', 'Keep your promises and be kind to friends.'],
    ],
  },

  'wf-tortoise-shell': {
    title: 'Why Tortoise’s Shell Is Cracked',
    names: { 해설: 'Narrator', 거북: 'Tortoise', 앵무새: 'Parrot', 하늘사람: 'Sky Person' },
    outro: [
      'Did you enjoy the story?',
      'If you were a bird, would you lend Tortoise a feather?',
      'When do you share food with your friends?',
    ],
    lines: [
      ['해설', 'Long ago, Tortoise had a smooth, shiny shell.'],
      ['해설', 'One day, the birds were asked to a party in the sky.'],
      ['앵무새', 'There is a big party in the sky! Tweet!'],
      ['거북', 'I want to go! Can I have some feathers?'],
      ['해설', 'Each bird gave him one feather. Now he had wings!'],
      ['해설', 'They all flew up to the sky. Flap, flap!'],
      ['거북', 'At parties, we use new names. My name is All of You!'],
      ['앵무새', 'All of You? What a funny name!'],
      ['하늘사람', 'Welcome! This food is for all of you.'],
      ['거북', 'All of You is me! The food is mine!'],
      ['해설', 'Tortoise ate almost all the food. Munch, munch!'],
      ['앵무새', 'That is not fair! Give back our feathers!'],
      ['해설', 'The birds took back their feathers.'],
      ['거북', 'Parrot, ask my wife to put soft grass in the yard.'],
      ['해설', 'But Tortoise jumped too soon. Whoosh!'],
      ['해설', 'Bump! He landed in the yard. Crack, crack!'],
      ['거북', 'Ouch! My smooth shell is cracked.'],
      ['해설', 'His wife and friends put the pieces back together.'],
      ['거북', 'Thank you. I will not be greedy again.'],
      ['해설', 'That is why Tortoise’s shell has many pieces.'],
      ['해설', 'Being greedy can hurt you in the end.'],
    ],
  },

  'wf-hare-tug-of-war': {
    title: 'Hare’s Tug-of-War',
    names: { 해설: 'Narrator', 토끼: 'Hare', 코끼리: 'Elephant', 하마: 'Hippo' },
    outro: [
      'Was the tug-of-war fun?',
      'If you were Hare, what would you say to your friends?',
      'What game do you like to play with friends?',
    ],
    lines: [
      ['해설', 'Long ago in Africa, there lived a clever little hare.'],
      ['토끼', 'I am the strongest animal of all!'],
      ['코끼리', 'Ha ha! But you are so small!'],
      ['토끼', 'Let us play tug-of-war. Hold this rope tomorrow.'],
      ['해설', 'Hare took the other end of the long rope to the river.'],
      ['토끼', 'Hippo, let us play tug-of-war!'],
      ['하마', 'You? Ha ha! Okay, little Hare.'],
      ['토끼', 'Hold this rope. Pull when I shake it.'],
      ['해설', 'Hare hid in the bushes. He shook the rope.'],
      ['해설', 'Elephant pulled. Hippo pulled. Pull, pull!'],
      ['코끼리', 'Wow! Hare is so strong!'],
      ['하마', 'How can little Hare pull so hard?'],
      ['해설', 'They pulled all day long.'],
      ['토끼', 'Hee hee! They are pulling each other!'],
      ['해설', 'At last, Elephant and Hippo walked along the rope.'],
      ['해설', 'They met in the middle of the forest.'],
      ['코끼리', 'Hippo? I was pulling you all day!'],
      ['하마', 'Hare tricked us both!'],
      ['토끼', 'I am sorry. I wanted to look strong.'],
      ['코끼리', 'You are clever. But do not trick your friends.'],
      ['하마', 'Next time, let us all pull together!'],
      ['해설', 'Use your clever ideas to help your friends.'],
    ],
  },

  'wf-honeyguide': {
    title: 'The Honeyguide Bird',
    names: { 해설: 'Narrator', 꿀잡이새: 'Honeyguide', 깅길레: 'Gingile' },
    outro: [
      'Did you like the honeyguide bird?',
      'If you were Gingile, how would you share the honey?',
      'Who helps you, and how do you thank them?',
    ],
    lines: [
      ['해설', 'Long ago, a young man named Gingile went hunting.'],
      ['꿀잡이새', 'Chit, chit! Follow me! I know where honey is!'],
      ['깅길레', 'A honeyguide bird! Honey is better than hunting!'],
      ['해설', 'The bird flew from tree to tree. Gingile followed.'],
      ['해설', 'At last, the bird stopped at a big tree. Buzz, buzz!'],
      ['꿀잡이새', 'Here it is! Please share some honey with me.'],
      ['해설', 'Gingile made smoke. The bees flew away.'],
      ['깅길레', 'So much honey! I will take it all!'],
      ['꿀잡이새', 'Where is my share? I showed you the way!'],
      ['깅길레', 'Go away, little bird!'],
      ['해설', 'Gingile took all the honey home.'],
      ['해설', 'A few days later, the bird sang again.'],
      ['꿀잡이새', 'Chit, chit! Follow me! I have a big surprise!'],
      ['깅길레', 'More honey? I will take it all again!'],
      ['해설', 'The bird stopped at a bush. Gingile looked inside.'],
      ['해설', 'A big lion was sleeping there! Snore, snore.'],
      ['해설', 'The lion opened his eyes and yawned. Roar!'],
      ['깅길레', 'That is not honey! Run!'],
      ['해설', 'Gingile climbed a tree. The lion went back to sleep.'],
      ['깅길레', 'I am sorry, little bird. Next time, I will share.'],
      ['해설', 'After that, Gingile always left honey for the bird.'],
      ['해설', 'Always thank the friends who help you.'],
    ],
  },

  'wf-sky-far-away': {
    title: 'Why the Sky Is Far Away',
    names: { 해설: 'Narrator', 하늘: 'Sky', 임금님: 'King', 아데세: 'Adese' },
    outro: [
      'Did you like the story about the sky?',
      'If you were Adese, what would you do with the extra food?',
      'What can you do to not waste food?',
    ],
    lines: [
      ['해설', 'Long ago, the sky was very close to the ground.'],
      ['해설', 'When people were hungry, they ate a piece of the sky.'],
      ['해설', 'The sky tasted like any food they wanted. Yum!'],
      ['해설', 'But people took too much. They threw food away.'],
      ['하늘', 'Rumble! Take only what you can eat.'],
      ['하늘', 'If you waste me, I will go far away.'],
      ['임금님', 'Everyone, listen! Take only a little sky.'],
      ['해설', 'A woman named Adese lived in the town.'],
      ['해설', 'One day, there was a big party. Boom, boom!'],
      ['아데세', 'It is a party! I will take a big piece!'],
      ['해설', 'Adese cut a very big piece of the sky.'],
      ['아데세', 'Yum, yum. Oh, I am so full!'],
      ['아데세', 'Friends, please help me eat this!'],
      ['해설', 'But everyone was full, too.'],
      ['해설', 'Adese threw the rest of the sky away.'],
      ['하늘', 'Rumble! You did not listen to me.'],
      ['하늘', 'Now I will go far away. Grow your own food.'],
      ['해설', 'The sky went up, up, and far away.'],
      ['아데세', 'I am so sorry. I was too greedy.'],
      ['임금님', 'Let us plant seeds together.'],
      ['해설', 'Since then, people grow food on farms.'],
      ['해설', 'Take only what you can eat, and do not waste food.'],
    ],
  },

  'wf-rabbit-sticky-doll': {
    title: 'Rabbit and the Sticky Doll',
    names: { 해설: 'Narrator', 토끼: 'Rabbit', 여우: 'Fox' },
    outro: [
      'Was Rabbit’s story fun?',
      'If you were Rabbit, what would you say to the doll?',
      'What do you do when you feel angry?',
    ],
    lines: [
      ['해설', 'Long ago, a clever rabbit lived in the woods.'],
      ['해설', 'Rabbit liked to play tricks on Fox.'],
      ['여우', 'This time, I will catch that rabbit!'],
      ['해설', 'Fox made a doll out of sticky tree sap.'],
      ['해설', 'He put a hat on it and sat it by the road.'],
      ['해설', 'Then Fox hid in the bushes.'],
      ['토끼', 'Hello! It is a nice day!'],
      ['해설', 'The doll did not say anything.'],
      ['토끼', 'Hello? Can you hear me?'],
      ['토끼', 'You are rude! I will push you!'],
      ['해설', 'Rabbit pushed the doll. His paw got stuck!'],
      ['해설', 'Then his other paw got stuck. Then his feet!'],
      ['여우', 'Ha ha! I caught you, Rabbit!'],
      ['토끼', 'Do anything you want, Fox.'],
      ['토끼', 'But please do not throw me in the thorn bush!'],
      ['여우', 'You hate the thorn bush? Then in you go!'],
      ['해설', 'Fox threw Rabbit into the thorn bush.'],
      ['토끼', 'Thank you, Fox! I was born in a thorn bush!'],
      ['해설', 'Rabbit hopped away. Hop, hop, hop!'],
      ['여우', 'Oh no! He tricked me again!'],
      ['해설', 'Stay calm when you are in trouble, and use your head.'],
    ],
  },

  'wf-rabbit-in-moon': {
    title: 'The Rabbit in the Moon',
    names: { 해설: 'Narrator', 케찰코아틀: 'Quetzalcoatl', 토끼: 'Rabbit' },
    outro: [
      'Did you like the rabbit in the moon?',
      'If you were the rabbit, what would you give?',
      'What shapes do you see when you look at the moon?',
    ],
    lines: [
      ['해설', 'Long ago, a sky god came down to Mexico.'],
      ['해설', 'His name was Quetzalcoatl. He looked like a man.'],
      ['케찰코아틀', 'I will walk and see the world.'],
      ['해설', 'He walked all day. Step, step, step.'],
      ['해설', 'Night came. A big round moon came up.'],
      ['케찰코아틀', 'I am so tired and hungry.'],
      ['해설', 'A little rabbit was eating grass nearby.'],
      ['토끼', 'Hello! You look tired. Please eat some grass!'],
      ['케찰코아틀', 'Thank you. But people cannot eat grass.'],
      ['토끼', 'I only have grass. But I want to help you.'],
      ['토끼', 'I will give you anything I have.'],
      ['케찰코아틀', 'You are small, but your heart is big!'],
      ['해설', 'He turned back into a shining god.'],
      ['토끼', 'Wow! You are a god!'],
      ['해설', 'He held the rabbit gently and lifted her up high.'],
      ['해설', 'Up, up, up, all the way to the moon!'],
      ['해설', 'The rabbit’s picture stayed on the moon.'],
      ['케찰코아틀', 'Now everyone will remember your kind heart.'],
      ['해설', 'Then he put the rabbit back on the grass.'],
      ['토끼', 'Thank you! I am in the moon!'],
      ['해설', 'Look at the moon tonight. Can you find the rabbit?'],
      ['해설', 'A kind heart shines like the moon.'],
    ],
  },

  'wf-fox-sky-party': {
    title: 'The Fox Who Went to the Sky',
    names: { 해설: 'Narrator', 여우: 'Fox', 콘도르: 'Condor', 앵무새: 'Parrots' },
    outro: [
      'Did you like the fox’s trip to the sky?',
      'If you were Fox, what would you say to Condor?',
      'What kind words can you say to a friend today?',
    ],
    lines: [
      ['해설', 'Long ago, a fox and a condor lived in the Andes.'],
      ['콘도르', 'Tomorrow, I am going to a party in the sky.'],
      ['여우', 'Please take me! I want to eat yummy food!'],
      ['콘도르', 'Get on my back. But be good.'],
      ['해설', 'Condor flew up above the clouds. Whoosh!'],
      ['해설', 'The party had lots of food and grain.'],
      ['여우', 'Yum, yum! This is mine! That is mine, too!'],
      ['콘도르', 'Slow down, Fox. Share with the others.'],
      ['여우', 'I am smarter than you, big bird!'],
      ['해설', 'Condor was sad. He flew home without Fox.'],
      ['여우', 'Oh no! How can I get down?'],
      ['해설', 'The sky people gave Fox a long rope.'],
      ['해설', 'Fox filled his bag with seeds and climbed down.'],
      ['앵무새', 'Hello, Fox! Squawk! Play with us!'],
      ['여우', 'Go away, noisy birds! Your voices are terrible!'],
      ['해설', 'The parrots got angry. Peck, peck! The rope broke.'],
      ['해설', 'Fox fell down onto soft grass. Bump!'],
      ['여우', 'Ouch! But I am okay.'],
      ['해설', 'His bag broke. Seeds flew all over the mountains.'],
      ['해설', 'The seeds grew into a grain called quinoa.'],
      ['여우', 'My mean words made my friends go away.'],
      ['해설', 'Kind words make friends. Mean words send them away.'],
    ],
  },

  'wf-night-coconut': {
    title: 'How Night Came',
    names: { 해설: 'Narrator', 딸: 'Daughter', 남편: 'Husband', 큰뱀: 'Great Snake', 하인: 'Helper' },
    outro: [
      'Did you like the story of the night?',
      'If you were a helper, would you open the coconut?',
      'What do you like to do at night?',
    ],
    lines: [
      ['해설', 'Long ago, there was no night. It was always day.'],
      ['해설', 'The Great Snake had a daughter.'],
      ['해설', 'She married a young man and lived in his village.'],
      ['딸', 'It is always bright here. I cannot sleep.'],
      ['딸', 'My father keeps the night under the river.'],
      ['남편', 'Helpers, please go and get the night.'],
      ['해설', 'The helpers went down the river in a canoe.'],
      ['큰뱀', 'Take this coconut to my daughter.'],
      ['큰뱀', 'Do not open it on the way!'],
      ['하인', 'Yes! We will not open it.'],
      ['해설', 'On the way, they heard sounds inside.'],
      ['해설', 'Chirp, chirp! Croak, croak! Hoo, hoo!'],
      ['하인', 'What is that? Let us take a little look.'],
      ['해설', 'They opened it. Darkness came out!'],
      ['해설', 'The darkness covered the whole world.'],
      ['해설', 'Crickets, frogs, and owls began to sing.'],
      ['딸', 'This is night! Now I can sleep.'],
      ['해설', 'She slept well all night long.'],
      ['딸', 'Bird, please sing and call the morning.'],
      ['해설', 'The bird sang. The sun came up again.'],
      ['해설', 'Since then, day and night take turns.'],
      ['하인', 'We are sorry. We broke our promise.'],
      ['해설', 'Even when you are curious, keep your promises.'],
    ],
  },

  'wf-coyote-fire': {
    title: 'How Coyote Brought Fire',
    names: { 해설: 'Narrator', 코요테: 'Coyote', 다람쥐: 'Squirrel', 개구리: 'Frog', 불지킴이: 'Fire Keeper' },
    outro: [
      'Did you like the story about fire?',
      'If you were an animal in the line, how would you help?',
      'What hard thing did you do with your friends?',
    ],
    lines: [
      ['해설', 'Long ago, people had no fire.'],
      ['해설', 'In winter, everyone was very cold. Brr!'],
      ['코요테', 'The Fire Keepers have fire on the mountain.'],
      ['코요테', 'Let us work together and get some fire.'],
      ['다람쥐', 'I can climb trees! I will help!'],
      ['개구리', 'I can jump far! I will help, too!'],
      ['해설', 'The animals waited in a long line.'],
      ['해설', 'Coyote went up the mountain quietly.'],
      ['불지킴이', 'This fire is ours. We will not share it.'],
      ['해설', 'The Fire Keepers fell asleep. Coyote grabbed a burning stick.'],
      ['불지킴이', 'Hey! Stop! Bring back our fire!'],
      ['코요테', 'Squirrel, catch! Huff, huff!'],
      ['해설', 'Squirrel ran from tree to tree.'],
      ['다람쥐', 'Ouch, it is hot! My tail is curling up!'],
      ['다람쥐', 'Frog, it is your turn!'],
      ['해설', 'Frog jumped and jumped. Hop, hop!'],
      ['개구리', 'Tree, please keep the fire safe!'],
      ['해설', 'Frog threw the fire into a big tree.'],
      ['해설', 'The Fire Keepers could not take it out.'],
      ['해설', 'Coyote showed people how to rub sticks. Rub, rub, spark!'],
      ['해설', 'Now everyone could stay warm by the fire.'],
      ['해설', 'When friends work together, they can do hard things.'],
    ],
  },

  'wf-coyote-stars': {
    title: 'Coyote and the Stars',
    names: { 해설: 'Narrator', 별지기: 'Star Keeper', 코요테: 'Coyote' },
    outro: [
      'Did you like the story of the stars?',
      'If you were Coyote, would you go slowly?',
      'What do you do slowly and carefully?',
    ],
    lines: [
      ['해설', 'Long ago, the night sky was dark. There were no stars.'],
      ['해설', 'The Star Keeper had a blanket full of shining stones.'],
      ['별지기', 'I will put these stars in the sky, one by one.'],
      ['별지기', 'Then people can find their way at night.'],
      ['해설', 'She put one star up. Then another. Slowly and carefully.'],
      ['해설', 'Coyote came by. Sniff, sniff.'],
      ['코요테', 'Wow! So shiny! Can I help?'],
      ['별지기', 'Yes. But go slowly and carefully.'],
      ['해설', 'Coyote put one star up. Then another.'],
      ['코요테', 'This is too slow! It will take forever!'],
      ['별지기', 'Do not hurry. Good work takes time.'],
      ['코요테', 'I will do it all at once!'],
      ['해설', 'Coyote grabbed the blanket and shook it. Whoosh!'],
      ['해설', 'The stars flew all over the sky.'],
      ['해설', 'Some stars made a long, bright river.'],
      ['별지기', 'Oh, Coyote! The stars are everywhere!'],
      ['코요테', 'I am sorry. I wanted to finish fast.'],
      ['별지기', 'That is okay. The sky is very bright now.'],
      ['코요테', 'Next time, I will go slowly.'],
      ['해설', 'Look at the sky tonight. Find Coyote’s stars!'],
      ['해설', 'Slow and careful work makes beautiful things.'],
    ],
  },

  'wf-possum-tail': {
    title: 'Why Possum’s Tail Is Bare',
    names: { 해설: 'Narrator', 주머니쥐: 'Possum', 토끼: 'Rabbit', 귀뚜라미: 'Cricket' },
    outro: [
      'Did you like Possum’s story?',
      'If you were Possum, how would you feel?',
      'What are you good at, and how can you share it kindly?',
    ],
    lines: [
      ['해설', 'Long ago, Possum had a big, fluffy tail.'],
      ['주머니쥐', 'Look at my tail! It is the best in the forest!'],
      ['해설', 'Every day, Possum combed his tail and sang.'],
      ['주머니쥐', 'La la la! My tail is so pretty!'],
      ['해설', 'Rabbit had a short tail. He was jealous.'],
      ['토끼', 'Possum always shows off. I will play a trick.'],
      ['해설', 'One day, the animals planned a big dance.'],
      ['토끼', 'Possum, I will send a friend to fix your tail.'],
      ['주머니쥐', 'Really? Thank you! My tail will look great!'],
      ['토끼', 'Cricket, please cut all the hair off Possum’s tail.'],
      ['귀뚜라미', 'A trick? Okay! Chirp, chirp!'],
      ['해설', 'Cricket wrapped the tail with red string.'],
      ['귀뚜라미', 'Do not take off the string until the dance.'],
      ['해설', 'But Cricket cut off all the hair. Snip, snip!'],
      ['해설', 'At the dance, Possum took off the string.'],
      ['주머니쥐', 'Look at my pretty tail! La la la!'],
      ['해설', 'All the animals laughed. Ha ha ha!'],
      ['해설', 'The tail had no hair at all.'],
      ['주머니쥐', 'Oh no! My fluffy tail! I am so embarrassed!'],
      ['해설', 'Possum fell over and lay very still.'],
      ['토끼', 'I am sorry, Possum. My trick was too mean.'],
      ['주머니쥐', 'I am sorry, too. I showed off too much.'],
      ['해설', 'Do not show off, and do not play mean tricks.'],
    ],
  },
};
