// 영어 학습용 원고 (한국 초등 저학년, 영어 초급). 문장은 자체 각색.
// 키 = stories/*.js 의 이야기 id. lines 의 첫 칸은 원래 이야기 cast 의 한국어 이름 그대로.
export default {
  'hs-dangun': {
    title: 'The Bear Who Became a Woman',
    names: { 해설: 'Narrator', 환웅: 'Hwanung', 곰: 'Bear', 호랑이: 'Tiger', 단군: 'Dangun' },
    outro: [
      'Did you like the story of Dangun?',
      'If you were the Bear, could you wait in the dark cave?',
      'What did you work hard for and never give up?',
    ],
    lines: [
      ['해설', 'Long, long ago, a king lived in the sky.'],
      ['해설', 'His son Hwanung looked down at the land every day.'],
      ['환웅', 'Father, I want to go down and help the people.'],
      ['해설', 'Hwanung came down with the wind, the rain, and the clouds.'],
      ['환웅', 'I will help everyone. I want all people to be happy.'],
      ['해설', 'In a cave, a bear and a tiger lived together.'],
      ['곰', 'Hwanung, we want to be people. Please help us.'],
      ['호랑이', 'Roar! Me too! I want to be a person!'],
      ['환웅', 'Eat this garlic and these bitter plants.'],
      ['환웅', 'Stay in the dark cave for one hundred days.'],
      ['호랑이', 'Yuck! It is bitter and hot!'],
      ['곰', 'Let’s wait a little more. We can do it.'],
      ['해설', 'One day, two days, ten days went by.'],
      ['호랑이', 'I can’t wait anymore. I want to run and play!'],
      ['해설', 'The tiger ran out of the cave. Whoosh!'],
      ['해설', 'But the bear waited and waited.'],
      ['해설', 'After twenty-one days, the bear became a woman!'],
      ['곰', 'Wow! I am a person now! Thank you!'],
      ['해설', 'She married Hwanung, and they had a baby boy.'],
      ['해설', 'The baby was Dangun.'],
      ['단군', 'I will help people, just like my father.'],
      ['해설', 'Dangun grew up and started the first Korean kingdom.'],
      ['해설', 'Never give up, and your dream can come true.'],
    ],
  },

  'hs-jumong': {
    title: 'Jumong the Archer',
    names: { 해설: 'Narrator', 유화: 'Yuhwa', 금와왕: 'King Geumwa', 주몽: 'Jumong', 대소: 'Prince Daeso' },
    outro: [
      'Did you like the story of Jumong?',
      'If you were Jumong, how would you feel at the deep river?',
      'What do you want to be good at? How can you practice?',
    ],
    lines: [
      ['해설', 'Long ago, King Geumwa met a sad woman by a river.'],
      ['유화', 'I am Yuhwa, the daughter of the river god.'],
      ['금와왕', 'Come and live in my palace.'],
      ['해설', 'Soon, Yuhwa had a big egg.'],
      ['해설', 'Animals walked around the egg. Birds kept it warm.'],
      ['해설', 'Crack, crack! A baby boy came out of the egg.'],
      ['해설', 'The boy made his own bow. He never missed!'],
      ['해설', 'So people called him Jumong. It means good archer.'],
      ['주몽', 'Zing! I hit the middle again!'],
      ['해설', 'The king’s sons did not like Jumong.'],
      ['대소', 'Jumong is too good. We must stop him.'],
      ['유화', 'Jumong, it is not safe here. Go far away.'],
      ['주몽', 'Mother, I will be a great man. Don’t worry.'],
      ['해설', 'Jumong rode south with his friends. Clip-clop, clip-clop!'],
      ['해설', 'But a deep river was in front of them.'],
      ['해설', 'And soldiers were coming from behind!'],
      ['주몽', 'I am the grandson of the river god! River, help me!'],
      ['해설', 'Fish and turtles came up and made a bridge.'],
      ['해설', 'Jumong and his friends crossed the river safely.'],
      ['대소', 'Oh no! The bridge is gone!'],
      ['해설', 'Jumong started a new country. It was called Goguryeo.'],
      ['주몽', 'Let’s work together and make a good country!'],
      ['해설', 'Be brave in hard times, and a way will open.'],
    ],
  },

  'hs-hyeokgeose': {
    title: 'The King from the Egg',
    names: { 해설: 'Narrator', 촌장: 'Old Chief', 젊은촌장: 'Young Chief', 혁거세: 'Hyeokgeose', 알영: 'Aryeong' },
    outro: [
      'Did you enjoy the story of the egg king?',
      'If you were a chief, what would you think of the shining egg?',
      'Who is a good leader in your home or class?',
    ],
    lines: [
      ['해설', 'Long ago, there were six villages in Korea.'],
      ['해설', 'Each village had a chief, but there was no king.'],
      ['촌장', 'We need a good king to lead us.'],
      ['젊은촌장', 'Yes! Let’s ask the sky for help.'],
      ['해설', 'Then they saw a bright light by a well.'],
      ['해설', 'A white horse was bowing there.'],
      ['젊은촌장', 'Look! There is a big egg next to the horse!'],
      ['해설', 'The horse flew up into the sky. Neigh!'],
      ['해설', 'The chiefs opened the purple egg. A baby boy was inside!'],
      ['촌장', 'The sky sent us this baby!'],
      ['해설', 'They washed him, and his body began to shine.'],
      ['촌장', 'Let’s call him Hyeokgeose. It means a bright ruler.'],
      ['해설', 'On the same day, a baby girl was born by another well.'],
      ['해설', 'Her lips looked like a bird’s beak.'],
      ['해설', 'They washed her in a stream. Pop! The beak fell off.'],
      ['젊은촌장', 'Let’s call her Aryeong, like the name of the well.'],
      ['해설', 'The two children grew up well.'],
      ['해설', 'Later, Hyeokgeose became king, and Aryeong became queen.'],
      ['혁거세', 'I will make a happy country for everyone.'],
      ['알영', 'I will visit the villages and help the farmers.'],
      ['해설', 'This was the start of a kingdom called Silla.'],
      ['해설', 'A good leader always thinks about the people first.'],
    ],
  },

  'hs-yeonorang': {
    title: 'The Sun and Moon Couple',
    names: { 해설: 'Narrator', 연오랑: 'Yeono', 세오녀: 'Seo', 신라왕: 'King', 신하: 'Helper' },
    outro: [
      'Did you like the story of Yeono and Seo?',
      'If you were Seo, what gift would you send home?',
      'What gift do you want to give someone far away?',
    ],
    lines: [
      ['해설', 'Long ago, Yeono and Seo lived by the sea in Silla.'],
      ['해설', 'Yeono picked seaweed. Seo made beautiful silk.'],
      ['연오랑', 'I am going to the sea. See you later!'],
      ['세오녀', 'Be careful! I will make silk at home.'],
      ['해설', 'Yeono stood on a big rock by the sea.'],
      ['해설', 'Suddenly, the rock moved like a boat!'],
      ['연오랑', 'Oh! The rock is floating away!'],
      ['해설', 'The rock went across the sea to Japan.'],
      ['해설', 'The people there made Yeono their king.'],
      ['세오녀', 'Where is my husband? Here are his shoes!'],
      ['해설', 'Seo stood on the rock, and it floated away, too.'],
      ['연오랑', 'Seo! I am so happy to see you!'],
      ['해설', 'But in Silla, the sun and the moon went dark.'],
      ['신라왕', 'Why is it so dark? Go and ask them to come back.'],
      ['해설', 'The helper went across the sea by boat.'],
      ['연오랑', 'We can’t go back. The sky wants us here.'],
      ['세오녀', 'But please take this silk. I made it.'],
      ['세오녀', 'Give it to the sky, and the light will come back.'],
      ['해설', 'The helper went home and gave the silk to the sky.'],
      ['해설', 'Flash! The sun and the moon were bright again!'],
      ['신라왕', 'Keep this silk safe. It is our treasure.'],
      ['해설', 'Even when we are far apart, love can still reach our friends.'],
    ],
  },

  'hs-ondal': {
    title: 'Ondal and the Princess',
    names: { 해설: 'Narrator', 공주: 'Princess', 임금: 'King', 온달: 'Ondal', 어머니: 'Mother' },
    outro: [
      'Did you enjoy the story of Ondal and the princess?',
      'If you were the princess, would you leave the palace?',
      'Who believes in you and cheers for you?',
    ],
    lines: [
      ['해설', 'Long ago, a little princess lived in Goguryeo.'],
      ['해설', 'She cried a lot. Waah, waah!'],
      ['임금', 'Stop crying, or you will marry Silly Ondal!'],
      ['해설', 'Ondal was poor, but he had a kind heart.'],
      ['해설', 'People laughed at him and called him silly.'],
      ['해설', 'The princess grew up. The king wanted her to marry a rich man.'],
      ['공주', 'Father, you said I would marry Ondal. A king must keep his word.'],
      ['임금', 'What? Then leave the palace!'],
      ['해설', 'The princess went to Ondal’s little house.'],
      ['어머니', 'Who are you? Your hands are so soft.'],
      ['온달', 'A princess can’t live here! Please go home!'],
      ['공주', 'I mean it. Let’s work hard together.'],
      ['해설', 'At last, Ondal and his mother said yes.'],
      ['공주', 'Let’s sell my jewels and buy a thin old horse.'],
      ['해설', 'The princess fed the horse every day. It became fast and strong.'],
      ['해설', 'Ondal practiced riding and shooting every day.'],
      ['온달', 'Giddy up! Zing! I hit the middle!'],
      ['해설', 'In spring, there was a big hunting contest.'],
      ['해설', 'Ondal was the fastest and the best of all.'],
      ['임금', 'Who is that young man? He is great!'],
      ['온달', 'My name is Ondal, Your Majesty.'],
      ['임금', 'Ondal is not silly at all! Welcome, my son!'],
      ['해설', 'Ondal became a great general. He lived happily with the princess.'],
      ['해설', 'With someone who believes in you, you can do great things.'],
    ],
  },

  'hs-jieun': {
    title: 'Jieun, the Good Daughter',
    names: { 해설: 'Narrator', 지은: 'Jieun', 어머니: 'Mother', 효종랑: 'Hyojong', 임금: 'King' },
    outro: [
      'Did you like the story of Jieun?',
      'If you were Jieun, what would you say to your mother?',
      'What can you do to help your family?',
    ],
    lines: [
      ['해설', 'Long ago in Silla, a girl named Jieun lived with her mother.'],
      ['해설', 'Her mother could not see. They were very poor.'],
      ['지은', 'Mother, here is some warm soup for you.'],
      ['어머니', 'Thank you, Jieun. Did you eat, too?'],
      ['지은', 'Yes, I am full.'],
      ['해설', 'But Jieun was hungry. She gave the food to her mother first.'],
      ['해설', 'One year, there was not enough food.'],
      ['지은', 'My mother can’t be hungry. I will find a job.'],
      ['해설', 'Jieun worked for a rich family from morning to night.'],
      ['지은', 'Mother, today we have white rice!'],
      ['어머니', 'The rice is good, but my heart hurts. What is wrong?'],
      ['해설', 'Jieun told her mother everything. They hugged and cried.'],
      ['어머니', 'I am sorry, my dear daughter.'],
      ['지은', 'I am happy when I am with you, Mother.'],
      ['해설', 'A young man named Hyojong heard their story.'],
      ['효종랑', 'What a kind daughter! I will help her.'],
      ['해설', 'Hyojong sent rice and clothes. Jieun could come home.'],
      ['해설', 'His friends sent rice, too.'],
      ['임금', 'Give this good daughter a house and some rice!'],
      ['지은', 'Mother, now we can live happily together.'],
      ['해설', 'Loving your family can touch many hearts.'],
    ],
  },

  'hs-sejong': {
    title: 'King Sejong and Hangul',
    names: { 해설: 'Narrator', 세종: 'King Sejong', 백성: 'Farmer', 학자: 'Scholar', 신하: 'Officer', 아이: 'Child' },
    outro: [
      'Did you enjoy the story of King Sejong?',
      'If you were King Sejong, what would you say to the officer?',
      'What word do you want to write in Hangul first?',
    ],
    lines: [
      ['해설', 'Long ago, King Sejong loved his people very much.'],
      ['해설', 'At that time, people wrote with Chinese letters.'],
      ['해설', 'There were too many letters. They were very hard to learn.'],
      ['백성', 'I want to write a letter, but I can’t.'],
      ['세종', 'My people can’t write their words. That is so sad.'],
      ['세종', 'I will make easy letters for everyone.'],
      ['해설', 'King Sejong studied the sounds of Korean late at night.'],
      ['해설', 'Many scholars helped him, too.'],
      ['학자', 'Your Majesty, your eyes are red. Please rest.'],
      ['세종', 'I am fine. This work is for my people.'],
      ['해설', 'He looked at the mouth and tongue when people spoke.'],
      ['해설', 'Some letters show the shape of the mouth and tongue.'],
      ['신하', 'We already have Chinese letters. Why make new ones?'],
      ['세종', 'Easy letters help the people. That helps the whole country.'],
      ['해설', 'At last, the new Korean letters were ready!'],
      ['해설', 'Today, we call these letters Hangul.'],
      ['해설', 'Hangul is easy. You can learn it in a few days!'],
      ['아이', 'Look! I can write my name!'],
      ['백성', 'Now I can write a letter, too!'],
      ['해설', 'People in Korea still read and write Hangul every day.'],
      ['해설', 'When you work hard to help others, many people become happy.'],
    ],
  },

  'hs-yisunsin': {
    title: 'Admiral Yi and the Turtle Ship',
    names: { 해설: 'Narrator', 이순신: 'Yi Sun-sin', 군사: 'Sailor', 목수: 'Builder', 백성: 'Villager' },
    outro: [
      'Did you like the story of Admiral Yi?',
      'If you were Admiral Yi, what would you say to the villagers?',
      'How do you get ready for something important?',
    ],
    lines: [
      ['해설', 'Long ago in Korea, there was a leader named Yi Sun-sin.'],
      ['해설', 'He kept the southern sea safe.'],
      ['이순신', 'Enemies may come across the sea. We must get ready.'],
      ['해설', 'He fixed the ships and trained the sailors every day.'],
      ['군사', 'Row, row! Heave-ho, heave-ho!'],
      ['이순신', 'Good work! Our hard work will keep the people safe.'],
      ['이순신', 'Let’s build a ship with a strong roof.'],
      ['목수', 'Let’s put sharp spikes on the roof!'],
      ['목수', 'And let’s put a dragon head on the front!'],
      ['해설', 'Bang, bang! Knock, knock! The new ship was ready.'],
      ['해설', 'It looked like a big turtle. People called it the turtle ship.'],
      ['군사', 'Wow! It is as hard as a turtle shell!'],
      ['해설', 'Then, enemy ships really came across the sea.'],
      ['백성', 'Admiral Yi, help! Many ships are coming!'],
      ['이순신', 'Don’t worry. We will protect the sea.'],
      ['해설', 'Admiral Yi watched the waves and the islands carefully.'],
      ['해설', 'The turtle ship went first. Splash, splash!'],
      ['해설', 'Admiral Yi’s ships won again and again.'],
      ['군사', 'We did it! The sea is safe!'],
      ['해설', 'Admiral Yi wrote in his diary, even in busy times.'],
      ['백성', 'Our village is safe. Thank you, Admiral Yi!'],
      ['해설', 'Korean people still remember him as a hero.'],
      ['해설', 'Get ready and work hard, and you can do hard things.'],
    ],
  },

  'hs-jangyeongsil': {
    title: 'Jang Yeong-sil the Inventor',
    names: { 해설: 'Narrator', 장영실: 'Jang Yeong-sil', 세종: 'King Sejong', 신하: 'Officer', 아이: 'Child', 농부: 'Farmer' },
    outro: [
      'Did you enjoy the story of Jang Yeong-sil?',
      'If you were Jang Yeong-sil, what would you make for people?',
      'What thing at home do you want to make better?',
    ],
    lines: [
      ['해설', 'Long ago, a man named Jang Yeong-sil lived in Korea.'],
      ['해설', 'He was not from a rich family. But he was very clever.'],
      ['장영실', 'If I turn this wheel, it will move. Click, click!'],
      ['해설', 'King Sejong heard about him.'],
      ['세종', 'A clever person should work for the country.'],
      ['신하', 'But Your Majesty, he is not from a high family.'],
      ['세종', 'His skills can help the people. That is what matters.'],
      ['해설', 'Jang Yeong-sil and other scholars made many tools.'],
      ['해설', 'One was a sundial. It looked like a round bowl.'],
      ['장영실', 'The sun moves, and the shadow moves, too.'],
      ['장영실', 'Look at the shadow, and you can tell the time!'],
      ['아이', 'I can’t read, but I can see the animal pictures!'],
      ['신하', 'But what about at night, or on cloudy days?'],
      ['장영실', 'Water can help. Water drips at night, too. Drip, drop!'],
      ['해설', 'He made a water clock. Little dolls rang bells and hit drums!'],
      ['세종', 'Ding! Dong! The clock tells the time by itself!'],
      ['해설', 'At that time, people also made a rain gauge.'],
      ['해설', 'It showed how much rain fell.'],
      ['농부', 'Now we know about the rain. We can farm better!'],
      ['장영실', 'I will make anything to help the people.'],
      ['세종', 'Thank you. Your work makes our country bright.'],
      ['해설', 'Today, Jang Yeong-sil is a famous Korean scientist.'],
      ['해설', 'If you keep doing what you love, you can help many people.'],
    ],
  },

  'hs-saimdang': {
    title: 'Shin Saimdang the Painter',
    names: { 해설: 'Narrator', 사임당: 'Saimdang', 어머니: 'Mother', 손님: 'Guest', 이이: 'Yi I' },
    outro: [
      'Did you like the story of Shin Saimdang?',
      'If you were Saimdang, what would you paint in the garden?',
      'What small thing did you look at for a long time?',
    ],
    lines: [
      ['해설', 'Long ago, a girl named Shin Saimdang lived in Korea.'],
      ['해설', 'She loved to paint and read books.'],
      ['사임당', 'Mother, look! A butterfly is on the flower!'],
      ['어머니', 'Look carefully, and paint what you see.'],
      ['해설', 'Saimdang painted flowers, grass, and little bugs.'],
      ['해설', 'Her pictures looked real.'],
      ['해설', 'There is an old story about her painting.'],
      ['해설', 'A chicken tried to peck the bugs in it! Peck, peck!'],
      ['손님', 'Ha ha! The chicken thinks the bugs are real!'],
      ['해설', 'Saimdang also wrote poems. Her handwriting was beautiful.'],
      ['해설', 'She grew up and had seven children.'],
      ['해설', 'She took care of her family and kept painting.'],
      ['이이', 'Mother, how do you make your flowers look so real?'],
      ['사임당', 'Look for a long time. Feel it in your heart.'],
      ['이이', 'I will look carefully at everything, too!'],
      ['해설', 'Her son Yi I grew up to be a great teacher.'],
      ['해설', 'One day, Saimdang moved far away from her mother.'],
      ['사임당', 'I miss my mother. It is hard to say goodbye.'],
      ['어머니', 'My dear daughter, I am always with you.'],
      ['해설', 'Saimdang wrote a poem about missing her mother.'],
      ['해설', 'Today, many people still love her paintings.'],
      ['해설', 'Look closely and do your best, and you can make beautiful things.'],
    ],
  },

  'hs-mandeok': {
    title: 'Kim Man-deok Shares Her Rice',
    names: { 해설: 'Narrator', 만덕: 'Man-deok', 상인: 'Trader', 마을사람: 'Villager', 아이: 'Child', 정조: 'King Jeongjo' },
    outro: [
      'Did you enjoy the story of Kim Man-deok?',
      'If you were Man-deok, would you give away all your money?',
      'What did you share with a friend or neighbor?',
    ],
    lines: [
      ['해설', 'Long ago, a woman named Kim Man-deok lived on Jeju Island.'],
      ['해설', 'She had a hard life, but she worked very hard.'],
      ['만덕', 'I will sell island things and buy rice and cloth.'],
      ['상인', 'Good idea! The island people need those things.'],
      ['해설', 'Man-deok was always honest. People trusted her.'],
      ['해설', 'She became rich.'],
      ['해설', 'Then, strong winds came for years. Nothing grew well.'],
      ['마을사람', 'We have no food. Our children are hungry.'],
      ['해설', 'Ships with rice could not cross the rough sea easily.'],
      ['만덕', 'I will use my money and buy rice for everyone.'],
      ['상인', 'All your money? Really?'],
      ['만덕', 'I can make money again. People are more important.'],
      ['해설', 'Man-deok bought lots of rice and brought it by ship.'],
      ['해설', 'She gave the rice to the hungry people.'],
      ['아이', 'Yummy, warm rice! Thank you!'],
      ['마을사람', 'Man-deok saved us!'],
      ['해설', 'King Jeongjo heard about her kind heart.'],
      ['정조', 'What a good woman! Ask her what she wishes for.'],
      ['만덕', 'I wish to see the palace and Mount Geumgang.'],
      ['해설', 'Back then, Jeju women could not leave the island.'],
      ['정조', 'Let her wish come true!'],
      ['해설', 'Man-deok crossed the sea and visited beautiful Mount Geumgang.'],
      ['해설', 'When we share what we have, everyone’s heart gets warm.'],
    ],
  },
};
