// 영어 학습용 원고 (한국 초등 저학년, 영어 초급). 문장은 자체 각색.
// 키 = stories/*.js 의 이야기 id. lines 의 첫 칸은 원래 이야기 cast 의 한국어 이름 그대로.
export default {
  'fox-stork': {
    title: 'The Fox and the Stork',
    names: { 해설: 'Narrator', 여우: 'Fox', 두루미: 'Stork' },
    outro: [
      'Did you like the story?',
      'If you were the Stork, what would you do?',
      'What food do you like to share with friends?',
    ],
    lines: [
      ['해설', 'Once upon a time, there was a fox.'],
      ['해설', 'The fox liked to play tricks on friends.'],
      ['해설', 'One day, the fox met a stork. The stork had a long beak.'],
      ['여우', 'Hello, Stork! Come to my house for dinner!'],
      ['두루미', 'Thank you, Fox! I will come.'],
      ['해설', 'In the evening, the stork went to the fox’s house. Knock, knock!'],
      ['여우', 'Come in, Stork. The soup is ready.'],
      ['해설', 'The fox put the soup on a flat plate.'],
      ['해설', 'The stork tried and tried. Peck, peck. But she could not eat.'],
      ['두루미', 'Oh no! I cannot eat my soup.'],
      ['여우', 'You do not want it? Then I will eat it all!'],
      ['해설', 'The stork went home. She was very hungry.'],
      ['해설', 'A few days later, the stork asked the fox to dinner.'],
      ['두루미', 'Fox, come to my house! I have good food for you.'],
      ['여우', 'Yummy! I am coming!'],
      ['해설', 'The stork put the food in a tall, thin jar.'],
      ['해설', 'The stork put her long beak in the jar. Yum, yum!'],
      ['해설', 'The fox could not put his nose in. Sniff, sniff.'],
      ['여우', 'I cannot eat! Now I know how you felt.'],
      ['여우', 'Stork, I am sorry. I was not kind to you.'],
      ['두루미', 'That is okay, Fox. Next time, let us eat together.'],
      ['해설', 'From then on, the fox and the stork were good friends.'],
      ['해설', 'Be kind to your friends, and they will be kind to you.'],
    ],
  },

  'sun-wind': {
    title: 'The Sun and the Wind',
    names: { 해설: 'Narrator', 바람: 'Wind', 해님: 'Sun', 나그네: 'Man' },
    outro: [
      'Was the story fun?',
      'If you were the man, how would you feel in the wind?',
      'What makes you feel warm and happy?',
    ],
    lines: [
      ['해설', 'Long ago, the Sun and the Wind lived in the sky.'],
      ['바람', 'I am the strongest! I can move big trees!'],
      ['해님', 'Really? Let us see who is stronger.'],
      ['해님', 'Look at that man. He has a coat.'],
      ['해님', 'Who can take off his coat first?'],
      ['바람', 'That is easy! I will go first.'],
      ['해설', 'The Wind blew and blew. Whoosh, whoosh!'],
      ['나그네', 'Brr! It is so cold!'],
      ['해설', 'The man held his coat tight.'],
      ['바람', 'I will blow harder! Whoosh!'],
      ['나그네', 'Brr! I need my coat. I will close it.'],
      ['해설', 'The harder the Wind blew, the tighter the man held his coat.'],
      ['바람', 'Oh no. I am so tired.'],
      ['해님', 'Now it is my turn.'],
      ['해설', 'The Sun came out and smiled.'],
      ['해설', 'The Sun was warm. Then warmer and warmer.'],
      ['나그네', 'Oh, it is warm now. It is nice.'],
      ['나그네', 'Now it is hot! I will take off my coat.'],
      ['해설', 'The man took off his coat and sat under a tree.'],
      ['바람', 'You win, Sun. Being strong is not everything.'],
      ['해님', 'You can help, too, Wind. Blow softly on hot days.'],
      ['바람', 'Okay! I will blow softly.'],
      ['해설', 'Being warm and kind is stronger than pushing hard.'],
    ],
  },

  'hare-tortoise': {
    title: 'The Hare and the Tortoise',
    names: { 해설: 'Narrator', 토끼: 'Hare', 거북이: 'Tortoise', 부엉이: 'Owl' },
    outro: [
      'Did you enjoy the race?',
      'If you were the Tortoise, how would you feel at the end?',
      'What do you keep trying every day?',
    ],
    lines: [
      ['해설', 'Once upon a time, there was a fast hare. There was a slow tortoise, too.'],
      ['토끼', 'Tortoise, you are so slow! Ha ha!'],
      ['해설', 'The tortoise was a little sad.'],
      ['거북이', 'I am slow, but I do not stop. Let us have a race!'],
      ['토끼', 'A race with me? Okay! I will win.'],
      ['해설', 'All the animals came to see. The wise owl helped.'],
      ['부엉이', 'Run to the big tree on the hill.'],
      ['부엉이', 'Ready, set, go!'],
      ['해설', 'The hare ran fast. Hop, hop, hop!'],
      ['해설', 'The tortoise walked slowly. Step, step, step.'],
      ['토끼', 'I cannot see the tortoise. I will take a nap.'],
      ['해설', 'The hare lay down under a tree. Soon he was asleep.'],
      ['해설', 'The tortoise did not stop. Step, step, step.'],
      ['거북이', 'I am tired, but I will keep going.'],
      ['해설', 'The tortoise walked past the sleeping hare.'],
      ['거북이', 'Step, step, step. I can see the big tree!'],
      ['해설', 'Later, the hare woke up.'],
      ['토끼', 'Oh no! I slept too long!'],
      ['해설', 'The hare ran and ran. But the tortoise was at the tree first.'],
      ['부엉이', 'The tortoise wins!'],
      ['토끼', 'I am sorry, Tortoise. You are great.'],
      ['거북이', 'Thank you. Next time, let us walk together.'],
      ['해설', 'Go slowly, but keep going, and you can win!'],
    ],
  },

  'lion-mouse': {
    title: 'The Lion and the Mouse',
    names: { 해설: 'Narrator', 사자: 'Lion', 생쥐: 'Mouse' },
    outro: [
      'Did you like the story?',
      'If you were the Mouse, would you help the Lion?',
      'When did a friend help you?',
    ],
    lines: [
      ['해설', 'Once upon a time, there was a big lion.'],
      ['해설', 'One day, the lion was sleeping under a tree.'],
      ['해설', 'A little mouse ran over his nose.'],
      ['사자', 'Achoo! Roar! Who woke me up?'],
      ['해설', 'The lion caught the mouse with his big paw.'],
      ['생쥐', 'Please let me go! I am sorry!'],
      ['생쥐', 'Let me go, and one day I will help you.'],
      ['사자', 'Ha ha! A little mouse help me? That is funny.'],
      ['사자', 'Okay. You can go.'],
      ['생쥐', 'Thank you, Lion! I will not forget.'],
      ['해설', 'A few days later, the lion got stuck in a big net.'],
      ['사자', 'Roar! Help! I cannot get out!'],
      ['해설', 'The other animals were scared. Nobody came.'],
      ['해설', 'But the little mouse heard the lion.'],
      ['생쥐', 'Lion, I am here! Wait a little.'],
      ['사자', 'You are so small. How can you help?'],
      ['생쥐', 'I have small but strong teeth. Look!'],
      ['해설', 'The mouse bit the net. Bite, bite, bite.'],
      ['해설', 'Soon there was a big hole. The lion was free!'],
      ['사자', 'Thank you, Mouse! I am sorry I laughed at you.'],
      ['생쥐', 'I said I would help you!'],
      ['해설', 'From then on, the lion and the mouse were best friends.'],
      ['해설', 'Small friends can be a big help. Be kind to everyone.'],
    ],
  },

  'ant-grasshopper': {
    title: 'The Ant and the Grasshopper',
    names: { 해설: 'Narrator', 개미: 'Ant', 베짱이: 'Grasshopper' },
    outro: [
      'Was the story fun?',
      'If you were the Ant, would you share your food?',
      'What do you get ready for before school?',
    ],
    lines: [
      ['해설', 'It was a hot summer day.'],
      ['해설', 'The ants worked hard. They carried food. Work, work, work!'],
      ['해설', 'The grasshopper sang all day. La la la!'],
      ['베짱이', 'Ant, it is so hot. Why do you work? Come and play!'],
      ['개미', 'I need food for winter. Winter is cold.'],
      ['베짱이', 'Winter is far away. I want to sing. La la la!'],
      ['개미', 'You need food, too. Please get some food.'],
      ['베짱이', 'Not now. Maybe tomorrow.'],
      ['해설', 'Every day, the ant worked. Every day, the grasshopper sang.'],
      ['해설', 'Then fall came. The wind got cold.'],
      ['개미', 'Grasshopper, get some food now!'],
      ['베짱이', 'Not now. Maybe tomorrow.'],
      ['해설', 'Then winter came. White snow fell.'],
      ['해설', 'There was no food in the field.'],
      ['베짱이', 'I am so cold and hungry.'],
      ['해설', 'The grasshopper went to the ant’s house. Knock, knock.'],
      ['베짱이', 'Ant, I am sorry. Can you share some food?'],
      ['개미', 'Come in, Grasshopper. Sit by the fire.'],
      ['해설', 'The ant shared the food with the grasshopper.'],
      ['베짱이', 'Thank you, Ant. Next summer, I will work, too.'],
      ['베짱이', 'And I will sing songs for you!'],
      ['개미', 'Great! We can work, and then sing together.'],
      ['해설', 'Get ready early, and you will not worry later.'],
    ],
  },

  'shepherd-boy': {
    title: 'The Boy Who Cried Wolf',
    names: { 해설: 'Narrator', 소년: 'Boy', 아저씨: 'Man', 아주머니: 'Woman' },
    outro: [
      'Did you like the story?',
      'If you were the boy, what would you say to the people?',
      'Why is it good to tell the truth?',
    ],
    lines: [
      ['해설', 'Once upon a time, a boy took care of sheep. Baa, baa.'],
      ['아저씨', 'If you see a wolf, call us. We will come.'],
      ['소년', 'Okay!'],
      ['해설', 'Every day, the boy watched the sheep. There was no wolf.'],
      ['소년', 'I am so bored. I have an idea!'],
      ['소년', 'Wolf! Wolf! Help me!'],
      ['해설', 'The people ran up the hill.'],
      ['아저씨', 'Where is the wolf?'],
      ['소년', 'Ha ha! There is no wolf!'],
      ['아주머니', 'That is not nice! Do not do that.'],
      ['해설', 'A few days later, the boy was bored again.'],
      ['소년', 'Wolf! Wolf! Help me!'],
      ['해설', 'The people ran up the hill again. But there was no wolf.'],
      ['아저씨', 'You told a lie again. We will not believe you.'],
      ['해설', 'One evening, a real wolf came!'],
      ['소년', 'Wolf! Wolf! This time it is true! Please help!'],
      ['아주머니', 'It is a lie again. We will not go.'],
      ['해설', 'Nobody came. The wolf chased the sheep away.'],
      ['해설', 'The boy looked for his sheep all night.'],
      ['소년', 'I told lies. So nobody believed me.'],
      ['소년', 'I am sorry. I will not tell lies again.'],
      ['아주머니', 'Okay. Now tell the truth every day.'],
      ['해설', 'If you tell lies, people will not believe you. Tell the truth!'],
    ],
  },

  'en-three-pigs': {
    title: 'The Three Little Pigs',
    names: { 해설: 'Narrator', 첫째돼지: 'First Pig', 둘째돼지: 'Second Pig', 막내돼지: 'Third Pig', 늑대: 'Wolf' },
    outro: [
      'Was the story fun?',
      'If you were a pig, what house would you make?',
      'What do you like about your home?',
    ],
    lines: [
      ['해설', 'Once upon a time, there were three little pigs.'],
      ['해설', 'Each pig made a house.'],
      ['첫째돼지', 'I will make a house of straw. It is fast!'],
      ['둘째돼지', 'I will make a house of sticks. It is fast, too!'],
      ['막내돼지', 'I will make a house of bricks. It is strong!'],
      ['해설', 'Then a hungry wolf came.'],
      ['늑대', 'Little pig, little pig, let me come in!'],
      ['첫째돼지', 'No, no, no! I will not open the door!'],
      ['늑대', 'Then I will huff and puff and blow your house down!'],
      ['해설', 'Huff, puff! The straw house fell down. The pig ran away.'],
      ['늑대', 'Little pigs, little pigs, let me come in!'],
      ['둘째돼지', 'No, no, no! I will not open the door!'],
      ['늑대', 'Then I will huff and puff and blow your house down!'],
      ['해설', 'Huff, puff! The stick house fell down. The pigs ran away.'],
      ['막내돼지', 'Come in, come in! Close the door!'],
      ['늑대', 'Let me come in, or I will blow your house down!'],
      ['해설', 'Huff, puff! Huff, puff! But the brick house did not fall.'],
      ['늑대', 'Then I will go down the chimney!'],
      ['막내돼지', 'Quick! Make a fire and put on hot water!'],
      ['해설', 'The wolf came down. Splash! His bottom went in the hot water.'],
      ['늑대', 'Ouch! Hot, hot, hot! I will never come back!'],
      ['해설', 'The wolf ran far, far away.'],
      ['첫째돼지', 'Thank you! Now we will make strong houses, too.'],
      ['해설', 'Work hard and take your time. It makes you strong.'],
    ],
  },

  'en-goldilocks': {
    title: 'Goldilocks and the Three Bears',
    names: { 해설: 'Narrator', 골디락스: 'Goldilocks', 아빠곰: 'Papa Bear', 엄마곰: 'Mama Bear', 아기곰: 'Baby Bear' },
    outro: [
      'Did you like the story?',
      'If you were Baby Bear, what would you say to Goldilocks?',
      'What is just right for you, hot soup or cold soup?',
    ],
    lines: [
      ['해설', 'Three bears lived in a little house in the woods.'],
      ['엄마곰', 'The soup is too hot. Let us go for a walk.'],
      ['해설', 'Then a girl came to the house. Her name was Goldilocks.'],
      ['골디락스', 'Knock, knock! Hello? Mmm, it smells good!'],
      ['해설', 'There were three bowls of soup. Big, middle, and small.'],
      ['골디락스', 'This soup is too hot! This soup is too cold!'],
      ['골디락스', 'This soup is just right! Yum, yum.'],
      ['해설', 'Then she saw three chairs.'],
      ['골디락스', 'Too hard! Too soft! This chair is just right!'],
      ['해설', 'Crack! The little chair broke.'],
      ['해설', 'Goldilocks was sleepy. She went upstairs and saw three beds.'],
      ['골디락스', 'Too high! Too low! This bed is just right!'],
      ['해설', 'Soon the bears came home.'],
      ['아빠곰', 'Someone ate my soup!'],
      ['엄마곰', 'Someone ate my soup, too!'],
      ['아기곰', 'Someone ate all my soup! And my chair is broken!'],
      ['아기곰', 'Look! Someone is in my bed!'],
      ['해설', 'Goldilocks woke up. She saw the three bears.'],
      ['골디락스', 'I am so sorry. I ate your soup and broke your chair.'],
      ['아기곰', 'That is okay. Thank you for saying sorry.'],
      ['골디락스', 'I will fix your chair with my dad!'],
      ['아빠곰', 'Ha ha! Come and play with us next time.'],
      ['해설', 'Goldilocks and Baby Bear became good friends.'],
      ['해설', 'Ask first, and say sorry when you do something wrong.'],
    ],
  },

  'en-little-red-hen': {
    title: 'The Little Red Hen',
    names: { 해설: 'Narrator', 암탉: 'Little Red Hen', 강아지: 'Dog', 고양이: 'Cat', 오리: 'Duck' },
    outro: [
      'Was the story fun?',
      'If you were the Dog, would you help the Hen?',
      'How do you help at home?',
    ],
    lines: [
      ['해설', 'Once upon a time, a little red hen lived on a farm.'],
      ['해설', 'One day, she found some seeds.'],
      ['암탉', 'Who will help me plant the seeds?'],
      ['강아지', 'Not I!'],
      ['고양이', 'Not I!'],
      ['오리', 'Not I!'],
      ['암탉', 'Then I will do it myself.'],
      ['해설', 'The seeds grew and grew.'],
      ['암탉', 'Who will help me cut the wheat?'],
      ['강아지', 'Not I!'],
      ['고양이', 'Not I!'],
      ['오리', 'Not I!'],
      ['해설', 'So the hen did it herself.'],
      ['암탉', 'Who will help me make the bread?'],
      ['해설', 'Not I! Not I! Not I! So the hen made the bread.'],
      ['해설', 'Mmm! The bread smelled so good.'],
      ['암탉', 'Who will help me eat the bread?'],
      ['강아지', 'I will!'],
      ['고양이', 'Me too!'],
      ['오리', 'Quack! Me too!'],
      ['암탉', 'You did not help me. Not one time.'],
      ['강아지', 'We are sorry, Hen. Next time, we will help.'],
      ['암탉', 'Okay! Today, let us share the bread.'],
      ['해설', 'Work together, and you can share the fun together.'],
    ],
  },

  'en-jack-beanstalk': {
    title: 'Jack and the Beanstalk',
    names: { 해설: 'Narrator', 잭: 'Jack', 엄마: 'Mom', 거인: 'Giant', 하프: 'Harp' },
    outro: [
      'Did you like the story?',
      'If you were Jack, would you climb the beanstalk?',
      'What would you like to grow in a garden?',
    ],
    lines: [
      ['해설', 'Once upon a time, Jack lived with his mom.'],
      ['해설', 'They had no food. They had only one old cow.'],
      ['엄마', 'Jack, sell the cow. Then we can buy bread.'],
      ['해설', 'On the way, Jack met an old man. He gave Jack magic beans for the cow.'],
      ['잭', 'Magic beans? Okay!'],
      ['엄마', 'Oh no, Jack! Only beans? Throw them out!'],
      ['해설', 'That night, the beans grew and grew. Up to the sky!'],
      ['잭', 'Wow! A big beanstalk! I will climb it.'],
      ['해설', 'Jack climbed up, up, up. He saw a big castle.'],
      ['해설', 'Boom! Boom! Boom! A giant came.'],
      ['거인', 'Sniff, sniff! Who is here?'],
      ['해설', 'Jack hid. The giant had a hen and a magic harp.'],
      ['거인', 'Hen, lay a gold egg! Harp, sing!'],
      ['해설', 'Then the giant fell asleep. Snore, snore.'],
      ['하프', 'Please take us home. We are from your town.'],
      ['잭', 'The giant took you from us! I will take you home.'],
      ['해설', 'Jack ran with the hen and the harp. But the harp went ding!'],
      ['거인', 'Stop! Come back!'],
      ['해설', 'Jack climbed down fast.'],
      ['잭', 'Mom! Give me the axe!'],
      ['해설', 'Chop, chop! The giant went back up. The beanstalk fell down.'],
      ['해설', 'Jack gave the hen and the harp back to the town.'],
      ['해설', 'Everyone was happy, and they had lots of food.'],
      ['해설', 'Be brave and do the right thing, and everyone can be happy.'],
    ],
  },
};
