// 영어 학습용 원고 (한국 초등 저학년, 영어 초급). 문장은 자체 각색.
// 키 = stories/*.js 의 이야기 id. lines 의 첫 칸은 원래 이야기 cast 의 한국어 이름 그대로.
export default {
  'nt-dung-beetle': {
    title: 'The Dung Beetle',
    names: { 해설: 'Narrator', 파브르: 'Mr. Fabre', 쇠똥구리: 'Beetle', 욕심쟁이: 'Greedy Beetle' },
    outro: [
      'Did you like the beetle story?',
      'If you were the beetle, how would you feel when the ball rolled away?',
      'What is the most amazing bug you have seen?',
    ],
    lines: [
      ['해설', 'Long ago, Mr. Fabre lived in a small town in France.'],
      ['해설', 'Mr. Fabre loved bugs very much.'],
      ['파브르', 'Let’s go to the field. Who is busy today?'],
      ['해설', 'He lay down in the grass with a magnifying glass.'],
      ['파브르', 'Oh, a dung beetle! What are you making?'],
      ['쇠똥구리', 'A ball! A round, round ball of dung!'],
      ['해설', 'The beetle stood on its head and pushed with its back legs.'],
      ['쇠똥구리', 'Push, push! I walk backward, but I know the way!'],
      ['해설', 'Roll, roll. The ball went over stones and grass.'],
      ['해설', 'Oops! The ball rolled down a hill.'],
      ['쇠똥구리', 'Oh no! That’s okay. I will push it again!'],
      ['파브르', 'You never give up. Good job, little beetle!'],
      ['해설', 'Then another beetle came near.'],
      ['욕심쟁이', 'I will help you. Let’s be friends!'],
      ['해설', 'But this beetle wanted to take the ball.'],
      ['쇠똥구리', 'This is my ball! I will hold it tight!'],
      ['해설', 'At last, the beetle dug a hole and put the ball inside.'],
      ['쇠똥구리', 'I will eat it in my hole. Yum, yum!'],
      ['해설', 'Mother beetles put an egg in a pear-shaped ball.'],
      ['해설', 'The baby eats the ball and grows big.'],
      ['파브르', 'You clean the field. You are the field cleaners!'],
      ['해설', 'Little beetles help keep nature clean.'],
    ],
  },

  'nt-cicada-ant': {
    title: 'What Cicadas and Ants Really Do',
    names: { 해설: 'Narrator', 파브르: 'Mr. Fabre', 매미: 'Cicada', 개미: 'Ant' },
    outro: [
      'Were you surprised by the true story?',
      'If you were the Cicada, would you share the sweet water?',
      'Have you heard a cicada in summer? What did it sound like?',
    ],
    lines: [
      ['해설', 'It was a hot summer day. The cicadas were singing.'],
      ['매미', 'Buzz, buzz! I love summer!'],
      ['파브르', 'People say cicadas are lazy. They only sing.'],
      ['파브르', 'Is that true? I will look with my own eyes.'],
      ['해설', 'Mr. Fabre sat under a tree and watched.'],
      ['해설', 'The cicada put its sharp mouth into the tree.'],
      ['매미', 'Sip, sip! Sweet tree water!'],
      ['해설', 'Sweet water came out like a little spring.'],
      ['해설', 'Then thirsty ants came, one by one.'],
      ['개미', 'Sweet water! We want some too!'],
      ['매미', 'Okay, let’s drink together. There is a lot.'],
      ['해설', 'But the ants wanted more and more.'],
      ['개미', 'Move, move! This spot is ours!'],
      ['해설', 'The ants pulled the cicada’s legs and wings.'],
      ['매미', 'Oh well. I will go to another tree.'],
      ['파브르', 'Look! The cicada shared. The ants took!'],
      ['해설', 'Baby cicadas live under the ground for years.'],
      ['해설', 'Then they come up, open their wings, and sing.'],
      ['매미', 'My summer is short. So I sing with all my heart!'],
      ['개미', 'Cicada, I am sorry. Thank you for the sweet water.'],
      ['매미', 'That’s okay. Let’s enjoy summer together!'],
      ['해설', 'Look at nature with your own eyes to know the truth.'],
    ],
  },

  'nt-hunter-wasp': {
    title: 'The Hunting Wasp',
    names: { 해설: 'Narrator', 파브르: 'Mr. Fabre', 폴: 'Paul', 나나니벌: 'Wasp' },
    outro: [
      'Did you like the wasp story?',
      'If you were the wasp, what room would you make for your baby?',
      'What can you do that nobody taught you?',
    ],
    lines: [
      ['해설', 'One sunny day, Mr. Fabre and his son Paul went to the sand.'],
      ['폴', 'Dad, look! That bee has a very thin waist!'],
      ['파브르', 'It is a hunting wasp. Shh, let’s watch.'],
      ['해설', 'The wasp started to dig in the sand. Dig, dig!'],
      ['나나니벌', 'I must dig deep. This is my baby’s room.'],
      ['해설', 'Then the wasp closed the door with a little stone.'],
      ['폴', 'Wow! She closed the door!'],
      ['나나니벌', 'Now I will find food for my baby.'],
      ['해설', 'Later, the wasp came back with a fat caterpillar.'],
      ['폴', 'It is bigger than she is! She is so strong!'],
      ['해설', 'The sand was wide, but she found her hole at once.'],
      ['파브르', 'There is no sign. How does she know?'],
      ['나나니벌', 'I am getting food ready for my baby.'],
      ['해설', 'She put the food in the hole and laid one egg.'],
      ['해설', 'Then she covered the hole and tapped it with a stone.'],
      ['폴', 'Dad, she uses the stone like a hammer!'],
      ['파브르', 'Yes. She makes the sand hard and safe.'],
      ['폴', 'Nobody taught her. How does she know all this?'],
      ['파브르', 'It is called instinct. Her body knows from birth.'],
      ['해설', 'The baby ate the food and grew.'],
      ['해설', 'The next year, a new wasp flew out of the sand.'],
      ['해설', 'Even a small wasp has amazing wisdom in nature.'],
    ],
  },

  'nt-glowworm': {
    title: 'The Glowworm',
    names: { 해설: 'Narrator', 파브르: 'Mr. Fabre', 반디: 'Glowworm', 날개반디: 'Flying Glowworm' },
    outro: [
      'Did you like the glowworm story?',
      'If you were a glowworm, who would you send your light to?',
      'Have you seen something shining at night?',
    ],
    lines: [
      ['해설', 'On a summer night, little green lights shone in the grass.'],
      ['파브르', 'Let’s go and meet the glowworms tonight.'],
      ['해설', 'Mr. Fabre turned off his lamp and walked quietly.'],
      ['해설', 'A glowworm with no wings sat on a leaf.'],
      ['반디', 'Hello! Do you like my light?'],
      ['파브르', 'It is so pretty! Where does it come from?'],
      ['반디', 'From the end of my body. It is a cool light.'],
      ['해설', 'The light is not hot like a candle.'],
      ['파브르', 'Will she turn off her light at a loud sound?'],
      ['해설', 'Mr. Fabre hit a pot. Bang, bang!'],
      ['반디', 'Ha ha! That does not stop me. Twinkle, twinkle!'],
      ['파브르', 'Why don’t you have wings?'],
      ['반디', 'I am a mother glowworm. I have no wings, but a bright light.'],
      ['해설', 'Then a glowworm with wings flew down.'],
      ['날개반디', 'I see a bright light! There you are!'],
      ['파브르', 'Her light says, I am here!'],
      ['해설', 'Later, the mother laid tiny eggs in the grass.'],
      ['파브르', 'Look! The eggs glow a little too!'],
      ['날개반디', 'Little baby, you shine too!'],
      ['반디', 'We need clean, wet grass to shine.'],
      ['파브르', 'Thank you, glowworms. I saw stars on the ground tonight.'],
      ['해설', 'Take care of the grass and the dark night for little lights.'],
    ],
  },

  'nt-raggylug': {
    title: 'Raggylug the Little Rabbit',
    names: { 해설: 'Narrator', 몰리: 'Molly', 래기러그: 'Rag', 여우: 'Fox' },
    outro: [
      'Did you like the story of Raggylug?',
      'If you were Rag, where would you hide from the fox?',
      'What useful thing did your mom or dad teach you?',
    ],
    lines: [
      ['해설', 'A rabbit family lived in the grass by a swamp.'],
      ['해설', 'Mother Molly and little Raggylug lived there.'],
      ['몰리', 'Rag, hide in the grass while I find food.'],
      ['래기러그', 'Okay, Mom. I will lie low and not move.'],
      ['해설', 'Then a big snake came near. Hiss, hiss!'],
      ['래기러그', 'Mom! Mom, help me!'],
      ['해설', 'Molly ran fast and kicked the snake. Thump, thump!'],
      ['해설', 'The snake was scared and slid away.'],
      ['몰리', 'Rag, are you okay? Oh, your ear is a little torn.'],
      ['해설', 'So he got the name Raggylug. It means raggy ear.'],
      ['몰리', 'One, when you are scared, lie low and do not move.'],
      ['몰리', 'Two, when I stamp my foot, it means danger.'],
      ['몰리', 'Three, the bramble bush is our friend.'],
      ['래기러그', 'Stamp means danger. The bramble is my friend!'],
      ['해설', 'One day, a fox came. Sniff, sniff.'],
      ['여우', 'I smell a rabbit. Where is it?'],
      ['해설', 'Molly stamped her foot. Rag jumped into the bramble bush.'],
      ['여우', 'Ouch! The bush is too sharp!'],
      ['해설', 'Rag jumped on logs, hop, hop. The fox lost his smell.'],
      ['해설', 'The fox shook his head and went away.'],
      ['래기러그', 'Mom, now I can hide all by myself!'],
      ['해설', 'Rag grew up to be a fast and smart rabbit.'],
      ['해설', 'Animals live each day with what their mothers taught them.'],
    ],
  },

  'nt-wahb': {
    title: 'Wahb the Grizzly Bear',
    names: { 해설: 'Narrator', 왑: 'Wahb', 엄마곰: 'Mother Bear', 젊은곰: 'Young Bear' },
    outro: [
      'How did you like the story of Wahb?',
      'If you were Wahb, how would you feel all alone?',
      'Where do you like to rest when you feel sad?',
    ],
    lines: [
      ['해설', 'Long ago, a baby grizzly bear named Wahb lived on a mountain.'],
      ['해설', 'Wahb picked berries with his mother and brothers.'],
      ['엄마곰', 'Wahb, turn over the log. There is a snack!'],
      ['왑', 'Yum, yum! Mom, you are the best!'],
      ['해설', 'But one day, Wahb lost his family.'],
      ['왑', 'Mom, where are you? I am all alone.'],
      ['해설', 'Other animals chased little Wahb away.'],
      ['왑', 'When I am big, nobody will chase me!'],
      ['해설', 'Wahb found food alone. In winter, he slept in a cave.'],
      ['해설', 'Year by year, Wahb grew big and strong.'],
      ['왑', 'This valley is mine! Stay away!'],
      ['해설', 'Wahb scratched marks high up on a tree.'],
      ['해설', 'Other bears saw the marks and went away.'],
      ['해설', 'But Wahb was always alone. He was lonely.'],
      ['해설', 'When his legs hurt, he sat in a warm spring.'],
      ['왑', 'Ah, so warm. My legs feel better.'],
      ['해설', 'Years went by. Wahb’s fur turned white.'],
      ['젊은곰', 'Hee hee! I will stand on a rock and scratch higher.'],
      ['왑', 'A bigger bear is here. I am old now.'],
      ['왑', 'No more fighting. I want to rest.'],
      ['해설', 'Wahb walked slowly to a quiet valley.'],
      ['왑', 'It is so quiet here. I remember picking berries with Mom.'],
      ['해설', 'Wahb closed his eyes and rested in the warm sun.'],
      ['해설', 'Wild animals need quiet forests to rest, too.'],
    ],
  },

  'gj-simcheong': {
    title: 'Simcheong',
    names: { 해설: 'Narrator', 심청: 'Simcheong', 심봉사: 'Father', 스님: 'Monk', 용왕: 'Sea King' },
    outro: [
      'Did you like the story of Simcheong?',
      'If you were Simcheong, what would you do for your father?',
      'What would you like to do for your family?',
    ],
    lines: [
      ['해설', 'Long ago, a blind man lived with his daughter, Simcheong.'],
      ['해설', 'Simcheong was kind. She loved her father very much.'],
      ['심청', 'Father, I will make warm rice for you.'],
      ['해설', 'One day, her father fell into a stream. Splash!'],
      ['심봉사', 'Help! I cannot see! I cannot get out!'],
      ['해설', 'A monk came by and pulled him out.'],
      ['스님', 'Give three hundred bags of rice. Then you can see.'],
      ['심봉사', 'Really? I will give the rice!'],
      ['해설', 'But they were poor. They had no rice.'],
      ['심청', 'I will go on a ship. Please send the rice.'],
      ['해설', 'The ship sailed far out to the stormy sea.'],
      ['심청', 'Father, please open your eyes someday!'],
      ['해설', 'Simcheong went into the sea. The waves held her softly.'],
      ['해설', 'They carried her gently to the Sea King’s palace.'],
      ['용왕', 'You are a good child. Rest here.'],
      ['해설', 'Later, the Sea King sent her up in a big flower.'],
      ['해설', 'The flower went to the palace. Simcheong became the queen.'],
      ['심청', 'I miss my father. Please invite all the blind people.'],
      ['해설', 'There was a big party. Her father came with his stick.'],
      ['심청', 'Father! It is me, Simcheong!'],
      ['심봉사', 'My daughter? Let me see your face!'],
      ['해설', 'He rubbed his eyes. And his eyes opened!'],
      ['심봉사', 'I can see! My daughter is so pretty!'],
      ['해설', 'A loving heart for your family can make wonders.'],
    ],
  },

  'gj-hong-gildong': {
    title: 'Hong Gildong',
    names: { 해설: 'Narrator', 길동: 'Gildong', 아버지: 'Father', 할머니: 'Grandma', 임금: 'King' },
    outro: [
      'Did you like the story of Hong Gildong?',
      'If you were Gildong, how would you feel?',
      'If a friend is treated unfairly, how can you help?',
    ],
    lines: [
      ['해설', 'Long ago, a boy named Hong Gildong lived in Korea.'],
      ['해설', 'Gildong was smart and strong.'],
      ['해설', 'But he could not call his father Father.'],
      ['길동', 'I cannot call you Father. My heart hurts.'],
      ['아버지', 'Gildong, I am sorry. You can call me Father now.'],
      ['길동', 'Father! I will go and help people in need.'],
      ['해설', 'Gildong went to the mountains and learned magic.'],
      ['해설', 'He could ride clouds and make many of himself.'],
      ['해설', 'In a town, he met a crying grandma.'],
      ['할머니', 'A greedy officer took all our rice!'],
      ['길동', 'Don’t worry, Grandma. I will get it back.'],
      ['해설', 'Gildong and his friends opened the bad officer’s storehouse.'],
      ['해설', 'They gave the rice back to the people.'],
      ['할머니', 'Our rice is back! Thank you, thank you!'],
      ['해설', 'The King said, Catch Gildong!'],
      ['해설', 'But look! There were eight Gildongs!'],
      ['임금', 'Oh my! Who is the real Gildong?'],
      ['해설', 'Clap! The Gildongs turned into straw dolls.'],
      ['해설', 'The real Gildong came down on a cloud.'],
      ['길동', 'King, I only stopped bad officers.'],
      ['임금', 'You are right. I will help my people.'],
      ['해설', 'Gildong sailed to an island and made a new country.'],
      ['해설', 'In his country, everyone was treated the same.'],
      ['해설', 'Everyone is special. Do not treat people unfairly.'],
    ],
  },

  'gj-jeon-uchi': {
    title: 'Jeon Woochi',
    names: { 해설: 'Narrator', 우치: 'Woochi', 백성: 'Villager', 임금: 'King', 화담: 'Hwadam' },
    outro: [
      'Did you like the story of Jeon Woochi?',
      'If you were Woochi, how would you feel when you lost?',
      'Have you used something you are good at to help a friend?',
    ],
    lines: [
      ['해설', 'Long ago, a young man named Jeon Woochi lived in Korea.'],
      ['해설', 'Woochi found a magic bead and learned magic.'],
      ['우치', 'Ha ha! Now I can ride the clouds!'],
      ['해설', 'One year, there was no rice in the village.'],
      ['백성', 'We have no rice. Our children are hungry.'],
      ['우치', 'Hmm. I have a good idea!'],
      ['해설', 'Woochi dressed like a man from the sky and flew to the palace.'],
      ['우치', 'King, the King of the Sky wants a golden beam.'],
      ['임금', 'The King of the Sky? Make a golden beam now!'],
      ['해설', 'Woochi took the gold and flew away. Whoosh!'],
      ['해설', 'He sold the gold and bought rice for the people.'],
      ['백성', 'Rice from the sky! Now we can eat!'],
      ['해설', 'Later, the King got angry. He said, Catch Woochi!'],
      ['해설', 'But Woochi rode a painted donkey into a picture.'],
      ['임금', 'He went into a picture? What magic!'],
      ['우치', 'Ha ha! Nobody is better than me!'],
      ['해설', 'One day, Woochi met a wise teacher, Hwadam.'],
      ['화담', 'Young man, let’s have a magic contest.'],
      ['해설', 'Woochi became a hawk. Hwadam became a bigger eagle.'],
      ['해설', 'Woochi became a cloud. Hwadam blew it away.'],
      ['우치', 'You win. You are better than me.'],
      ['화담', 'Do not show off your magic. Use it well.'],
      ['우치', 'Teacher, please teach me more.'],
      ['해설', 'The more you can do, the kinder and humbler you should be.'],
    ],
  },

  'gj-park-ssi': {
    title: 'Lady Park',
    names: { 해설: 'Narrator', 박씨: 'Lady Park', 시백: 'Sibaek', 시아버지: 'Father-in-law', 장수: 'General' },
    outro: [
      'Did you like the story of Lady Park?',
      'If you were Lady Park, what would you do?',
      'Have you found something good in a friend, not just their looks?',
    ],
    lines: [
      ['해설', 'Long ago, a young man named Sibaek married Lady Park.'],
      ['해설', 'Lady Park had rough, bumpy skin on her face.'],
      ['시백', 'I do not want to see her face.'],
      ['시아버지', 'A good heart is more important than a face.'],
      ['박씨', 'Please build me a little house. I will live there.'],
      ['해설', 'Lady Park planted many trees around her little house.'],
      ['해설', 'One day, she bought a thin little horse.'],
      ['박씨', 'With good food and care, he will be a great horse.'],
      ['해설', 'The horse grew big and ran very fast.'],
      ['해설', 'Sibaek went to take a big test.'],
      ['박씨', 'Use the water in this jar for your ink.'],
      ['해설', 'Sibaek wrote with the ink. He got first place!'],
      ['해설', 'One night, Lady Park took off her bumpy skin.'],
      ['해설', 'Her face was as pretty as the moon.'],
      ['시백', 'Is that you? I am so sorry!'],
      ['박씨', 'Do not judge people by their looks. Let’s be happy.'],
      ['해설', 'Years later, soldiers came from the north.'],
      ['해설', 'People ran to Lady Park’s house with the trees.'],
      ['장수', 'People are hiding there! Get them!'],
      ['해설', 'The trees turned into a thick forest. Whoosh, whoosh!'],
      ['장수', 'I cannot see the way! The trees are like soldiers!'],
      ['박씨', 'Nobody here will be hurt. Go away now!'],
      ['장수', 'Her magic is too strong. Let’s go home!'],
      ['해설', 'Look at the heart, not just the face.'],
    ],
  },
};
