// 영어 학습용 원고 (한국 초등 저학년, 영어 초급). 문장은 자체 각색.
// 키 = stories/*.js 의 이야기 id. lines 의 첫 칸은 원래 이야기 cast 의 한국어 이름 그대로.
export default {
  'wa-urashima': {
    title: 'Urashima Taro',
    names: { 해설: 'Narrator', 타로: 'Taro', 거북이: 'Turtle', 공주: 'Princess', 아이들: 'Kids' },
    outro: [
      'Did you like the story?',
      'If you were Taro, would you open the box?',
      'What promise did you keep?',
    ],
    lines: [
      ['해설', 'Long ago in Japan, a fisherman named Taro lived by the sea.'],
      ['해설', 'One day, some kids poked a little turtle with a stick.'],
      ['아이들', 'Go, slow turtle! Poke, poke!'],
      ['타로', 'Stop, kids! The turtle is hurt.'],
      ['해설', 'Taro put the turtle back into the sea. Splash!'],
      ['거북이', 'Thank you, Taro! I will help you one day.'],
      ['해설', 'A few days later, the turtle came back.'],
      ['거북이', 'Get on my back. I will take you to the sea palace.'],
      ['해설', 'Down, down they went into the deep blue sea. Bubble, bubble.'],
      ['공주', 'Welcome, Taro! Thank you for saving the turtle.'],
      ['해설', 'There was good food. The fish danced and danced.'],
      ['타로', 'This is like a dream! I am so happy!'],
      ['해설', 'Three days went by.'],
      ['타로', 'Princess, I must go home now. My mother is waiting.'],
      ['공주', 'Take this box. But never, never open it.'],
      ['타로', 'I promise.'],
      ['해설', 'Taro went home. But his village looked very different.'],
      ['타로', 'Where is my house? I don’t know anyone here!'],
      ['해설', 'Three days under the sea were three hundred years on land.'],
      ['해설', 'Taro was sad. He forgot his promise and opened the box.'],
      ['해설', 'Puff! White smoke came out. Now Taro was an old man.'],
      ['타로', 'Oh no! I should have kept my promise.'],
      ['해설', 'This old story comes from Japan.'],
      ['해설', 'Always keep your promises, even small ones.'],
    ],
  },

  'wa-hanasaka': {
    title: 'The Flower Grandpa',
    names: { 해설: 'Narrator', 할아버지: 'Grandpa', 할머니: 'Grandma', 흰둥이: 'Shiro', 욕심쟁이: 'Greedy Man', 영주: 'Lord' },
    outro: [
      'Was the story fun?',
      'If you were Shiro, how would you feel?',
      'Where would you like to make flowers bloom?',
    ],
    lines: [
      ['해설', 'Long ago in Japan, a kind old man and woman lived together.'],
      ['해설', 'They had a white dog. His name was Shiro.'],
      ['흰둥이', 'Woof, woof! Grandpa, dig here!'],
      ['해설', 'Grandpa dug and dug. He found shiny gold coins!'],
      ['할머니', 'Wow! Thank you, Shiro!'],
      ['해설', 'A greedy man next door saw it all.'],
      ['욕심쟁이', 'Give me that dog! I want gold, too.'],
      ['해설', 'But he only found broken plates and rocks.'],
      ['욕심쟁이', 'Go away, bad dog!'],
      ['해설', 'Shiro was scared. He ran far into the hills.'],
      ['해설', 'Grandpa planted a little tree where Shiro dug.'],
      ['해설', 'The tree grew big. Grandpa made a bowl from it.'],
      ['해설', 'He made rice cakes in the bowl. They turned into gold!'],
      ['해설', 'The greedy man took the bowl and burned it.'],
      ['할아버지', 'Oh, my bowl is now ashes. I will keep them.'],
      ['해설', 'The wind blew the ashes onto a dry tree.'],
      ['해설', 'Pop, pop! Pink flowers bloomed everywhere!'],
      ['영주', 'Wonderful! You will get a big gift!'],
      ['해설', 'The greedy man tried, too. Ashes flew into the lord’s eyes.'],
      ['영주', 'Achoo! I can’t see! Shame on you!'],
      ['해설', 'That evening, Shiro came home, wagging his tail.'],
      ['흰둥이', 'Woof! I missed you!'],
      ['해설', 'This old story comes from Japan.'],
      ['해설', 'A kind heart makes flowers bloom.'],
    ],
  },

  'wa-omusubi': {
    title: 'The Rolling Rice Ball',
    names: { 해설: 'Narrator', 할아버지: 'Grandpa', 할머니: 'Grandma', 쥐들: 'Mice', 욕심쟁이: 'Greedy Man' },
    outro: [
      'Did you enjoy the story?',
      'If you were Grandpa, which box would you pick?',
      'What yummy food do you share with friends?',
    ],
    lines: [
      ['해설', 'Long ago in Japan, an old man went to the mountain.'],
      ['할머니', 'Here are rice balls for your lunch.'],
      ['할아버지', 'Thank you! See you later.'],
      ['해설', 'At lunch, he dropped a rice ball.'],
      ['해설', 'Roll, roll, roll! It fell into a little hole.'],
      ['해설', 'Then he heard a song from the hole.'],
      ['쥐들', 'Rice ball, roll, roll, roll! Squeak, squeak!'],
      ['할아버지', 'What a fun song! Here is one more.'],
      ['쥐들', 'Rice ball, roll, roll, roll! Squeak, squeak!'],
      ['해설', 'The old man leaned in. Oops! He fell into the hole.'],
      ['해설', 'Down there was a little mouse village.'],
      ['쥐들', 'Thank you for the rice balls! Come to our party!'],
      ['해설', 'The mice sang and danced for him.'],
      ['쥐들', 'Pick a gift box. A big one or a small one?'],
      ['할아버지', 'I am old. A small box is enough.'],
      ['해설', 'At home, he opened the box. It was full of treasure!'],
      ['해설', 'The greedy man next door went to the hole, too.'],
      ['욕심쟁이', 'I want all the treasure! Meow, meow!'],
      ['해설', 'The mice were scared. They turned off the lights.'],
      ['욕심쟁이', 'It’s so dark! Where is the way out?'],
      ['해설', 'He dug all night. He came out covered in dirt.'],
      ['해설', 'This old story comes from Japan.'],
      ['해설', 'Be thankful for small things.'],
    ],
  },

  'wa-zodiac-race': {
    title: 'The Great Animal Race',
    names: { 해설: 'Narrator', 옥황상제: 'Jade Emperor', 쥐: 'Rat', 소: 'Ox', 호랑이: 'Tiger', 토끼: 'Rabbit', 용: 'Dragon' },
    outro: [
      'Was the race fun?',
      'If you were the Ox, how would you feel?',
      'What is your animal year?',
    ],
    lines: [
      ['해설', 'Long ago in China, the years had no names.'],
      ['옥황상제', 'Animals, cross the big river! The first twelve will name the years.'],
      ['쥐', 'Squeak! I can’t swim well. What can I do?'],
      ['쥐', 'Ox, can I ride on your back?'],
      ['소', 'Moo. Okay, hold on tight.'],
      ['해설', 'The ox swam and swam. Splash, splash!'],
      ['해설', 'Near the end, the rat jumped off and ran.'],
      ['쥐', 'I am first!'],
      ['소', 'Moo. I am second. That is okay.'],
      ['호랑이', 'Roar! The water was strong, but I am third!'],
      ['토끼', 'Hop, hop! I jumped on logs. I am fourth!'],
      ['해설', 'The dragon came fifth.'],
      ['옥황상제', 'Dragon, you can fly. Why are you late?'],
      ['용', 'A village needed rain. So I helped them.'],
      ['옥황상제', 'Good job! Helping others is never a shame.'],
      ['해설', 'Then came the snake, horse, sheep, and monkey.'],
      ['해설', 'Last came the rooster, dog, and pig.'],
      ['해설', 'The cat was asleep. The rat forgot to wake him.'],
      ['쥐', 'Sorry, Cat. I will keep my promise next time.'],
      ['소', 'We don’t have to be first. We are all special.'],
      ['해설', 'This story comes from China.'],
      ['해설', 'Never give up, and you will find your place.'],
    ],
  },

  'wa-houyi-suns': {
    title: 'Hou Yi and the Ten Suns',
    names: { 해설: 'Narrator', 예: 'Hou Yi', 임금: 'King', 농부: 'Farmer', 아이: 'Child' },
    outro: [
      'Did you like the story?',
      'If you were Hou Yi, would you save the last sun?',
      'What do you do on a very hot day?',
    ],
    lines: [
      ['해설', 'Long ago, there were ten suns in the sky.'],
      ['해설', 'Each day, one sun came out. They took turns.'],
      ['해설', 'But one day, all ten suns came out together!'],
      ['아이', 'It is so hot! There is no water!'],
      ['농부', 'Oh no. All the plants are dry.'],
      ['해설', 'The king called Hou Yi. He was very good with a bow.'],
      ['임금', 'Hou Yi, please help my people.'],
      ['예', 'Suns! Please go back! The world is too hot!'],
      ['해설', 'But the naughty suns did not listen.'],
      ['예', 'Then I must use my bow.'],
      ['해설', 'Zing! The arrow flew into the sky.'],
      ['해설', 'The sun turned into a black bird and flew away.'],
      ['해설', 'Zing, zing! One, two, three. Nine suns flew away.'],
      ['아이', 'A cool wind! And look, it is raining!'],
      ['임금', 'Stop, Hou Yi! We need one sun.'],
      ['임금', 'Without a sun, plants cannot grow.'],
      ['예', 'You are right. I will keep the last sun.'],
      ['해설', 'Now one sun comes out every day.'],
      ['농부', 'Thank you, Hou Yi! The plants are growing!'],
      ['해설', 'This old story comes from China.'],
      ['해설', 'Too much is not good. Just right is best.'],
    ],
  },

  'wa-change-moon': {
    title: 'Chang’e on the Moon',
    names: { 해설: 'Narrator', 서왕모: 'Queen Mother', 예: 'Hou Yi', 항아: 'Chang’e', 봉몽: 'Peng Meng', 옥토끼: 'Jade Rabbit' },
    outro: [
      'Was the story beautiful?',
      'If you were Chang’e, what would you do?',
      'What do you see on the full moon?',
    ],
    lines: [
      ['해설', 'Long ago in China, Hou Yi and Chang’e lived together.'],
      ['해설', 'One day, the Queen Mother gave Hou Yi a magic drink.'],
      ['서왕모', 'Drink this, and you will fly to the sky.'],
      ['예', 'I don’t want to leave Chang’e. Please keep it safe.'],
      ['항아', 'Yes. I will hide it in a box.'],
      ['해설', 'But a bad man named Peng Meng heard them.'],
      ['봉몽', 'I want that magic drink!'],
      ['해설', 'When Hou Yi was out, Peng Meng came.'],
      ['봉몽', 'Give me the drink now!'],
      ['항아', 'No! I will not give it to you!'],
      ['해설', 'Chang’e drank it all. Gulp!'],
      ['해설', 'She became light like a feather. Up, up she went!'],
      ['항아', 'Oh! I am flying!'],
      ['해설', 'Chang’e landed on the moon.'],
      ['옥토끼', 'Hello, Chang’e! I will be your friend.'],
      ['항아', 'Thank you, Rabbit. But I miss Hou Yi.'],
      ['예', 'Chang’e! Where are you?'],
      ['해설', 'Hou Yi looked up. Chang’e waved from the moon.'],
      ['예', 'I will put out cakes and fruit for you.'],
      ['해설', 'Peng Meng was sent far away.'],
      ['해설', 'In China, people eat moon cakes under the full moon.'],
      ['해설', 'It is brave to protect what is important.'],
    ],
  },

  'wa-lion-rabbit': {
    title: 'The Lion and the Clever Rabbit',
    names: { 해설: 'Narrator', 사자: 'Lion', 토끼: 'Rabbit', 사슴: 'Deer', 원숭이: 'Monkey' },
    outro: [
      'Was the rabbit clever?',
      'If you were the Rabbit, what would you do?',
      'Have you seen yourself in the water?',
    ],
    lines: [
      ['해설', 'Long ago in India, a mean lion lived in the forest.'],
      ['사자', 'Roar! I am the king! Do what I say!'],
      ['사슴', 'We are scared of the lion.'],
      ['원숭이', 'Lion, we will serve you every day. Please calm down.'],
      ['사자', 'Okay. But don’t be late!'],
      ['해설', 'One day, it was the little rabbit’s turn.'],
      ['토끼', 'Hmm. I have a good idea.'],
      ['해설', 'The rabbit went very, very slowly.'],
      ['사자', 'Roar! Why are you so late?'],
      ['토끼', 'I met another lion. He says he is the king!'],
      ['사자', 'What? Show me that lion now!'],
      ['해설', 'The rabbit took the lion to a deep well.'],
      ['토끼', 'He is in there. Look!'],
      ['해설', 'The lion looked in. He saw a lion in the water.'],
      ['사자', 'Roar! Get out of my forest!'],
      ['해설', 'Roar! The lion in the water roared, too.'],
      ['해설', 'It was only the lion’s own face in the water.'],
      ['해설', 'Splash! The lion jumped in.'],
      ['사자', 'Oh, it’s cold! Nobody is here!'],
      ['해설', 'He climbed out, all wet. He was so ashamed.'],
      ['해설', 'The lion left the forest and never came back.'],
      ['사슴', 'Thank you, Rabbit! You are small, but so smart!'],
      ['해설', 'This story comes from India.'],
      ['해설', 'You don’t need to be big. Be smart!'],
    ],
  },

  'wa-tiger-brahman': {
    title: 'The Brahman and the Tiger',
    names: { 해설: 'Narrator', 브라만: 'Brahman', 호랑이: 'Tiger', 나무: 'Tree', 길: 'Road', 자칼: 'Jackal' },
    outro: [
      'Did you like the clever jackal?',
      'If you were the Brahman, would you open the cage?',
      'How do you say thank you to people?',
    ],
    lines: [
      ['해설', 'Long ago in India, there lived a kind teacher.'],
      ['해설', 'People called him the Brahman.'],
      ['호랑이', 'Please, let me out! I will be good!'],
      ['브라만', 'Will you eat me?'],
      ['호랑이', 'No, no! I promise!'],
      ['해설', 'The Brahman opened the cage. Out jumped the tiger!'],
      ['호랑이', 'Roar! I am hungry. I will eat you!'],
      ['브라만', 'You broke your promise! Let’s ask others first.'],
      ['나무', 'People rest in my shade. Then they cut my branches.'],
      ['길', 'People walk on me every day. They never say thanks.'],
      ['호랑이', 'See? Now I will eat you!'],
      ['해설', 'Then a clever jackal came by.'],
      ['자칼', 'What happened? I don’t understand.'],
      ['자칼', 'Was the Brahman in the cage? Or the tiger?'],
      ['호랑이', 'Silly jackal! I was in the cage, like this!'],
      ['해설', 'The tiger walked into the cage.'],
      ['자칼', 'Oh, I see! And how was the door?'],
      ['브라만', 'It was closed like this. Click!'],
      ['자칼', 'Now I understand. Let’s leave it that way!'],
      ['호랑이', 'Roar! You tricked me! Let me out!'],
      ['해설', 'This old story comes from India.'],
      ['해설', 'Remember kindness, and stay calm when there is danger.'],
    ],
  },

  'wa-blind-elephant': {
    title: 'Touching the Elephant',
    names: { 해설: 'Narrator', 임금: 'King', 코끼리: 'Elephant', 첫째: 'First Man', 둘째: 'Second Man', 셋째: 'Third Woman', 넷째: 'Fourth Woman' },
    outro: [
      'Did you like the story?',
      'If you touched the elephant, what would you say?',
      'Have you ever disagreed with a friend?',
    ],
    lines: [
      ['해설', 'Long ago in India, four people could not see.'],
      ['해설', 'They never met an elephant before.'],
      ['임금', 'Here is an elephant. Touch it and tell me.'],
      ['코끼리', 'Toot! Please be gentle. That tickles!'],
      ['해설', 'The first man touched a leg.'],
      ['첫째', 'An elephant is like a big pole!'],
      ['해설', 'The second man touched an ear. Flap, flap.'],
      ['둘째', 'No! An elephant is like a big fan!'],
      ['해설', 'The third woman touched the long trunk.'],
      ['셋째', 'No! An elephant is like a big snake!'],
      ['해설', 'The fourth woman held the tail.'],
      ['넷째', 'You are all wrong. It is like a rope!'],
      ['해설', 'They argued and argued. So noisy!'],
      ['코끼리', 'Toot! Please don’t fight!'],
      ['임금', 'Each of you is right. And each of you is wrong.'],
      ['임금', 'You each touched only one part. Now switch places.'],
      ['해설', 'They touched the legs, the ears, the trunk, and the tail.'],
      ['넷째', 'Oh! An elephant is all of these together!'],
      ['둘째', 'I am sorry. I only listened to myself.'],
      ['해설', 'This old story comes from India.'],
      ['해설', 'Listen to your friends. They may see other parts.'],
    ],
  },

  'wa-moon-rabbit': {
    title: 'The Rabbit in the Moon',
    names: { 해설: 'Narrator', 토끼: 'Rabbit', 원숭이: 'Monkey', 수달: 'Otter', 자칼: 'Jackal', 할아버지: 'Old Man' },
    outro: [
      'Did you like the kind rabbit?',
      'If you were the Rabbit, what would you give?',
      'Can you find the rabbit in the moon tonight?',
    ],
    lines: [
      ['해설', 'Long ago in India, four animal friends lived in a forest.'],
      ['토끼', 'Friends, let’s help hungry people tomorrow.'],
      ['원숭이', 'Yes! Let’s share our food!'],
      ['해설', 'A god in the sky heard them.'],
      ['해설', 'He became a hungry old man and came to the forest.'],
      ['할아버지', 'Oh, I am so hungry.'],
      ['수달', 'Here is a fish from the river.'],
      ['원숭이', 'Here is a sweet mango.'],
      ['자칼', 'Here is a bowl of milk.'],
      ['해설', 'But the rabbit only ate grass. She had nothing to give.'],
      ['토끼', 'Friends, please make a warm fire.'],
      ['토끼', 'Old man, I have no food. I will give myself.'],
      ['해설', 'The rabbit got ready to jump. The old man caught her!'],
      ['할아버지', 'Stop, kind rabbit! Your kind heart is enough.'],
      ['해설', 'The old man turned into a shining god.'],
      ['할아버지', 'Everyone will remember your kind heart.'],
      ['해설', 'He drew the rabbit on the moon.'],
      ['토끼', 'Wow! I am on the moon!'],
      ['수달', 'We will see you every night!'],
      ['해설', 'This story comes from old stories in India.'],
      ['해설', 'Sharing with a true heart is the best gift.'],
    ],
  },

  'wa-watermelon': {
    title: 'The First Watermelon',
    names: { 해설: 'Narrator', 안띠엠: 'An Tiem', 아내: 'Wife', 임금: 'King', 신하: 'Officer', 새들: 'Birds' },
    outro: [
      'Was the story sweet?',
      'If you were An Tiem, what would you do first?',
      'What have you planted and grown?',
    ],
    lines: [
      ['해설', 'Long ago in Vietnam, there lived a young man named An Tiem.'],
      ['신하', 'The king gave us all these nice things!'],
      ['안띠엠', 'Yes. But things from our own hard work are special, too.'],
      ['신하', 'King! An Tiem is not thankful to you!'],
      ['임금', 'What? Then go live on a far island!'],
      ['해설', 'An Tiem and his wife went to an empty island.'],
      ['아내', 'There is no house here. There is no farm.'],
      ['안띠엠', 'Don’t worry. We can make them with our hands.'],
      ['해설', 'They built a house and caught fish.'],
      ['해설', 'One day, white birds dropped black seeds.'],
      ['새들', 'Tweet, tweet! Plant these seeds!'],
      ['해설', 'An Tiem planted the seeds and gave them water.'],
      ['해설', 'Big green fruits grew on the vines.'],
      ['해설', 'Crack! Inside, the fruit was red and sweet.'],
      ['아내', 'Yummy! It is so cool and sweet!'],
      ['해설', 'An Tiem wrote his name on the fruits.'],
      ['해설', 'He put them in the sea. Float, float.'],
      ['해설', 'At last, a fruit came to the king.'],
      ['임금', 'An Tiem did this all by himself! Bring him back.'],
      ['안띠엠', 'King, I will share these watermelon seeds with everyone.'],
      ['해설', 'People in Vietnam tell this story about the first watermelon.'],
      ['해설', 'Work hard and never give up. Sweet things will come.'],
    ],
  },

  'wa-banh-chung': {
    title: 'The Square and Round Cakes',
    names: { 해설: 'Narrator', 임금: 'King', 랑리에우: 'Lang Lieu', 큰왕자: 'Big Prince', 둘째왕자: 'Second Prince', 신령: 'Spirit' },
    outro: [
      'Did you like the rice cakes?',
      'If you were Lang Lieu, how would you feel?',
      'What do you eat on New Year’s Day?',
    ],
    lines: [
      ['해설', 'Long ago in Vietnam, a king had many sons.'],
      ['임금', 'Bring me the best food for New Year’s Day.'],
      ['임금', 'The best one will be the next king.'],
      ['큰왕자', 'I will find a rare fish in the sea!'],
      ['둘째왕자', 'I will find a rare fruit on the mountain!'],
      ['해설', 'The youngest prince, Lang Lieu, was poor.'],
      ['랑리에우', 'What can I bring? I only have rice.'],
      ['해설', 'That night, a spirit came in his dream.'],
      ['신령', 'Nothing is better than rice. Make rice cakes.'],
      ['신령', 'The earth is square. The sky is round.'],
      ['해설', 'Lang Lieu washed the rice. Swish, swish.'],
      ['해설', 'He made a square cake wrapped in green leaves.'],
      ['랑리에우', 'This square cake is the earth.'],
      ['해설', 'Then he made a round white cake.'],
      ['랑리에우', 'This round cake is the sky.'],
      ['해설', 'On New Year’s Day, the princes brought their food.'],
      ['큰왕자', 'Ha! Only rice cakes?'],
      ['해설', 'The king tasted the cakes. He listened to Lang Lieu.'],
      ['임금', 'Rice comes from the hard work of our people.'],
      ['임금', 'These cakes are the best! Lang Lieu will be king.'],
      ['둘째왕자', 'Good things are not far away. Well done, brother!'],
      ['해설', 'People in Vietnam still make these cakes at New Year.'],
      ['해설', 'A gift with love is better than an expensive gift.'],
    ],
  },

  'wa-horsehead-fiddle': {
    title: 'The White Horse and the Fiddle',
    names: { 해설: 'Narrator', 수호: 'Suho', 할머니: 'Grandma', 하얀말: 'White Horse', 친구들: 'Friends', 영주: 'Lord' },
    outro: [
      'How did the story make you feel?',
      'If you were Suho, what would you say to the lord?',
      'What do you do when you miss someone?',
    ],
    lines: [
      ['해설', 'Long ago in Mongolia, a boy named Suho lived with Grandma.'],
      ['해설', 'One evening, Suho found a little white horse on the grass.'],
      ['수호', 'Don’t worry. I will take care of you.'],
      ['할머니', 'It is as white as snow. Take good care of it.'],
      ['해설', 'The little horse grew big and strong.'],
      ['하얀말', 'Neigh! Get on my back, Suho!'],
      ['해설', 'One day, there was a big horse race.'],
      ['친구들', 'Suho, your white horse will win!'],
      ['해설', 'The white horse ran like the wind. It won the race!'],
      ['영주', 'What a great horse! Leave it here.'],
      ['수호', 'No! My horse is my family!'],
      ['해설', 'But the lord took the horse away. Suho cried.'],
      ['해설', 'The lord got on the horse. The horse shook hard.'],
      ['하얀말', 'Neigh! I want to go to Suho!'],
      ['해설', 'The lord fell down. Bump! The horse ran away.'],
      ['해설', 'The horse had to hide far away in the mountains.'],
      ['해설', 'That night, Suho saw his horse in a dream.'],
      ['하얀말', 'Make a fiddle that looks like me. Then we can be together.'],
      ['해설', 'Suho made a fiddle with a horse head.'],
      ['해설', 'The music sounded like a running horse.'],
      ['수호', 'Can you hear me? We are always together.'],
      ['해설', 'This fiddle is still loved in Mongolia today.'],
      ['해설', 'Love can connect us, even when we are far apart.'],
    ],
  },

  'wa-kancil': {
    title: 'Kancil the Little Deer',
    names: { 해설: 'Narrator', 칸칠: 'Kancil', 악어대장: 'Big Crocodile', 악어들: 'Crocodiles' },
    outro: [
      'Was Kancil clever?',
      'If you were Kancil, how would you cross the river?',
      'When did you use a good idea?',
    ],
    lines: [
      ['해설', 'Long ago in Indonesia, there lived a little deer named Kancil.'],
      ['칸칠', 'Yummy fruit is on that tree across the river!'],
      ['해설', 'But hungry crocodiles lived in the river.'],
      ['칸칠', 'Hmm. I have an idea!'],
      ['칸칠', 'Crocodiles! The king wants to count you all!'],
      ['악어대장', 'The king? Why?'],
      ['칸칠', 'He will have a party for you. Line up!'],
      ['악어들', 'A party! Let’s line up!'],
      ['해설', 'The crocodiles made a long line across the river.'],
      ['칸칠', 'One! Two! Three!'],
      ['해설', 'Kancil hopped on their backs. Hop, hop, hop!'],
      ['칸칠', 'Four! Five! Six! Seven!'],
      ['악어대장', 'That tickles. Be gentle.'],
      ['칸칠', 'Eight! Nine! Ten!'],
      ['해설', 'With one last hop, Kancil landed on the other side.'],
      ['악어대장', 'So how many are we? When is the party?'],
      ['칸칠', 'Sorry! There is no party. I just wanted to cross!'],
      ['악어들', 'What? We were tricked!'],
      ['해설', 'Kancil ate the sweet fruit. Yum, yum.'],
      ['칸칠', 'I am sorry I lied. Here, I will share my fruit.'],
      ['해설', 'Kids in Indonesia and Malaysia love Kancil stories.'],
      ['해설', 'Even if you are small, stay calm and think.'],
    ],
  },

  'wa-monkey-turtle': {
    title: 'The Monkey and the Turtle',
    names: { 해설: 'Narrator', 원숭이: 'Monkey', 거북이: 'Turtle' },
    outro: [
      'Did you like the story?',
      'If you were the Turtle, what would you say?',
      'What did you share with a friend?',
    ],
    lines: [
      ['해설', 'Long ago in the Philippines, a monkey and a turtle were friends.'],
      ['해설', 'One day, they found a banana tree in the river.'],
      ['거북이', 'Let’s cut it in half and plant it.'],
      ['원숭이', 'I want the top! It has pretty leaves!'],
      ['해설', 'The turtle got the bottom with the roots.'],
      ['해설', 'The monkey’s tree dried up.'],
      ['해설', 'The turtle’s tree grew and grew. Yellow bananas came out!'],
      ['거북이', 'I can’t climb the tree.'],
      ['원숭이', 'I will get them for you! Let’s share!'],
      ['해설', 'The monkey climbed up. But he ate all the bananas.'],
      ['원숭이', 'Yum, yum! So good!'],
      ['거북이', 'Monkey, please give me some!'],
      ['원숭이', 'Ha! You can have the peels!'],
      ['해설', 'The turtle put thorns around the tree.'],
      ['해설', 'The monkey came down. Ouch! The thorns poked him.'],
      ['원숭이', 'I will throw you in the river!'],
      ['거북이', 'Oh, please! Not the river!'],
      ['원숭이', 'You don’t like the river? Then in you go!'],
      ['해설', 'Splash! The turtle swam away happily.'],
      ['거북이', 'Thank you, Monkey! The river is my home!'],
      ['원숭이', 'I was greedy. Sorry, Turtle. Next time, I will share.'],
      ['해설', 'This old story comes from the Philippines.'],
      ['해설', 'Share with your friends, and you will keep them.'],
    ],
  },
};
