// 영어 학습용 원고 (한국 초등 저학년, 영어 초급). 문장은 자체 각색.
// 키 = stories/*.js 의 이야기 id. lines 의 첫 칸은 원래 이야기 cast 의 한국어 이름 그대로.
export default {
  'kr2-snail-bride': {
    title: 'The Snail Lady',
    names: { 해설: 'Narrator', 총각: 'Farmer', 우렁각시: 'Snail Lady' },
    outro: [
      'Did you like the story?',
      'If you were the farmer, could you wait three days?',
      'Who helps you every day? How can you say thank you?',
    ],
    lines: [
      ['해설', 'Long ago, a poor young farmer lived alone.'],
      ['해설', 'Every day, he worked hard in the rice field.'],
      ['총각', 'I work so hard. But who will eat with me?'],
      ['우렁각시', 'I will eat with you!'],
      ['총각', 'Who said that? Nobody is here.'],
      ['해설', 'He looked down. There was a big pond snail.'],
      ['총각', 'Little snail, come home with me.'],
      ['해설', 'He put the snail in a big water jar.'],
      ['해설', 'The next day, he came home. What a surprise!'],
      ['해설', 'Hot rice and soup were on the table.'],
      ['총각', 'Who made this dinner for me?'],
      ['해설', 'The next day, and the next day, dinner was ready again.'],
      ['총각', 'Today I will hide and watch.'],
      ['해설', 'The snail came out of the jar. Pop! It became a lady.'],
      ['해설', 'Clink, clank! She cooked rice and soup.'],
      ['총각', 'Who are you? Why do you help me?'],
      ['우렁각시', 'I am the Snail Lady. You always work so hard.'],
      ['우렁각시', 'Please wait three days. Then I can be a person.'],
      ['해설', 'One day, two days, three days. He waited and waited.'],
      ['해설', 'On the third day, she became a real person.'],
      ['총각', 'Now we can live and work together!'],
      ['해설', 'They worked in the field together and lived happily.'],
      ['해설', 'Work hard and wait patiently. Good things will come.'],
    ],
  },

  'kr2-gyeonwoo-jiknyeo': {
    title: 'The Herdsman and the Weaver',
    names: { 해설: 'Narrator', 옥황상제: 'Sky King', 견우: 'Gyeonu', 직녀: 'Jiknyeo', 까치: 'Magpie' },
    outro: [
      'Did you enjoy the story?',
      'If you were a magpie, how would you help them?',
      'Who do you miss? When can you see them?',
    ],
    lines: [
      ['해설', 'Long ago, Jiknyeo lived in the sky. She made beautiful cloth.'],
      ['해설', 'Gyeonu lived across the Milky Way. He took care of cows.'],
      ['해설', 'The Milky Way is a big river of stars.'],
      ['옥황상제', 'Jiknyeo, Gyeonu is kind and works hard.'],
      ['옥황상제', 'You two can marry and live together.'],
      ['견우', 'Jiknyeo, let us be happy together.'],
      ['직녀', 'Yes, Gyeonu! I am so happy.'],
      ['해설', 'But they played all day. They forgot their work.'],
      ['해설', 'There was no new cloth. The cows were hungry. Moo, moo!'],
      ['옥황상제', 'You forgot your work! Now you must live apart.'],
      ['옥황상제', 'You can meet only on one day each year.'],
      ['해설', 'Gyeonu lived on one side. Jiknyeo lived on the other side.'],
      ['해설', 'At last, that day came. But the river was too wide.'],
      ['견우', 'I can see her, but there is no bridge.'],
      ['직녀', 'I miss you, Gyeonu.'],
      ['해설', 'They cried. Their tears fell down as rain.'],
      ['해설', 'The magpies on the earth saw the rain.'],
      ['까치', 'Let us fly up and make a bridge!'],
      ['해설', 'Many birds flew up. They made a bridge with their wings.'],
      ['견우', 'Thank you, magpies! Now I can see Jiknyeo!'],
      ['해설', 'After that, they worked hard and waited every year.'],
      ['해설', 'Have fun, but always do your own work, too.'],
    ],
  },

  'kr2-dog-cat-bead': {
    title: 'The Dog, the Cat, and the Bead',
    names: { 해설: 'Narrator', 할아버지: 'Grandpa', 잉어: 'Carp', 욕심할멈: 'Greedy Woman', 바둑이: 'Dog', 나비: 'Cat' },
    outro: [
      'Was the story fun?',
      'If you were the dog, what would you say to the cat?',
      'What did you do together with a friend?',
    ],
    lines: [
      ['해설', 'Long ago, a kind grandpa lived by a river.'],
      ['해설', 'He had a dog and a cat. He loved them very much.'],
      ['해설', 'One day, Grandpa caught a big fish. It was a carp.'],
      ['잉어', 'Please let me go home!'],
      ['할아버지', 'Okay, little fish. Go home to your mom.'],
      ['해설', 'The carp was the son of the Dragon King.'],
      ['잉어', 'Thank you! This magic bead makes wishes come true.'],
      ['해설', 'Now Grandpa always had rice. Everyone was happy.'],
      ['해설', 'But a greedy woman lived across the river.'],
      ['욕심할멈', 'I want that bead! I will take it.'],
      ['해설', 'She took the magic bead and left a fake one.'],
      ['바둑이', 'Cat, let us get Grandpa’s bead back!'],
      ['해설', 'The cat rode on the dog. They swam across the river.'],
      ['나비', 'Mice, please help me find the bead.'],
      ['해설', 'The mice found the bead. The cat held it in her mouth.'],
      ['바둑이', 'Cat, do you have the bead? Tell me!'],
      ['해설', 'The cat opened her mouth. Plop! The bead fell in the river.'],
      ['바둑이', 'Oh no! You dropped it!'],
      ['해설', 'The dog was angry and went home alone.'],
      ['해설', 'Then the carp came. It gave the bead back to the cat.'],
      ['해설', 'The cat took the bead home to Grandpa.'],
      ['할아버지', 'Good cat! Thank you!'],
      ['해설', 'Since then, dogs and cats do not get along.'],
      ['해설', 'Do not blame your friends. Help each other instead.'],
    ],
  },

  'kr2-teacher-honey': {
    title: 'The Teacher’s Honey Pot',
    names: { 해설: 'Narrator', 훈장님: 'Teacher', 돌이: 'Dori', 순이: 'Suni' },
    outro: [
      'Did you like the story?',
      'If you were the teacher, what would you say at first?',
      'Who do you want to share yummy food with?',
    ],
    lines: [
      ['해설', 'Long ago, a teacher taught children in a village school.'],
      ['해설', 'He had a little pot in his closet.'],
      ['해설', 'He often ate something from it. Lick, lick!'],
      ['돌이', 'Teacher, what is in that pot?'],
      ['훈장님', 'It is medicine for grown-ups. Children get a tummy ache.'],
      ['해설', 'One day, the teacher went to a party.'],
      ['훈장님', 'Read your books. Do not touch my pot!'],
      ['해설', 'When he left, the children ran to the closet.'],
      ['순이', 'It smells sweet. Is it really medicine?'],
      ['돌이', 'Yum! It is not medicine. It is honey!'],
      ['해설', 'One spoon, two spoons. Soon the pot was empty.'],
      ['순이', 'Oh no! The teacher will be angry.'],
      ['돌이', 'Do not worry. I have an idea.'],
      ['해설', 'Dori dropped the teacher’s ink stone. Crack! It broke.'],
      ['해설', 'An ink stone is a stone for making ink.'],
      ['해설', 'In the evening, the teacher came back.'],
      ['훈장님', 'Oh no! Who broke my ink stone?'],
      ['돌이', 'We broke it. So we ate your medicine as punishment.'],
      ['순이', 'But we ate it all. Our tummies feel fine!'],
      ['해설', 'The teacher’s face turned red.'],
      ['훈장님', 'I told a lie. I should share good food.'],
      ['돌이', 'We are sorry, too. We will work to pay for it.'],
      ['해설', 'After that, the teacher always shared his snacks.'],
      ['해설', 'Little lies come out. Always tell the truth.'],
    ],
  },

  'kr2-millet-groom': {
    title: 'One Grain of Millet',
    names: { 해설: 'Narrator', 총각: 'Young Man', 주인: 'Host', 정승: 'Minister', 아가씨: 'Lady' },
    outro: [
      'Was the story fun?',
      'If you were the first host, would you give him a mouse?',
      'What small thing is very special to you?',
    ],
    lines: [
      ['해설', 'Long ago, a young man set out with one grain of millet.'],
      ['해설', 'Millet is a tiny yellow grain, like a little seed.'],
      ['총각', 'With this grain, I will find a wife!'],
      ['총각', 'Please keep my grain. It is very special.'],
      ['주인', 'One grain is special? Okay, I will keep it.'],
      ['해설', 'At night, a mouse ate the grain. Munch, munch!'],
      ['총각', 'The mouse ate my grain. So give me the mouse.'],
      ['해설', 'At the next house, a cat chased the mouse away.'],
      ['총각', 'The cat chased my mouse. So give me the cat.'],
      ['해설', 'At the next house, a dog barked. The cat ran away.'],
      ['총각', 'The dog chased my cat. So give me the dog.'],
      ['해설', 'At the next house, a horse stamped. The dog ran away.'],
      ['총각', 'The horse scared my dog. So give me the horse.'],
      ['해설', 'Grain, mouse, cat, dog, horse! It got bigger and bigger.'],
      ['해설', 'Then he stayed at a rich minister’s house.'],
      ['정승', 'You got a horse with one grain? How funny!'],
      ['해설', 'The next morning, the minister’s daughter rode the horse.'],
      ['아가씨', 'Oh no! The horse ran away!'],
      ['총각', 'The lady lost my horse. So give me the lady!'],
      ['정승', 'Ha ha ha! You are a brave young man!'],
      ['해설', 'The minister talked with him. He was smart and kind.'],
      ['정승', 'You care about small things. You may marry my daughter.'],
      ['해설', 'So he got married with just one grain of millet!'],
      ['해설', 'Small things are precious. Take good care of them.'],
    ],
  },

  'kr2-banjjogi': {
    title: 'Banjjogi, the Half Boy',
    names: { 해설: 'Narrator', 반쪽이: 'Banjjogi', 큰형: 'Big Brother', 호랑이: 'Tiger', 부자: 'Rich Man' },
    outro: [
      'What did you think of the story?',
      'If you were Banjjogi, would you forgive your brothers?',
      'What is something good about your friend?',
    ],
    lines: [
      ['해설', 'Long ago, a mother had three sons.'],
      ['해설', 'The youngest was Banjjogi. His name means half boy.'],
      ['해설', 'He had one eye, one arm, and one leg.'],
      ['해설', 'But he was very strong and brave.'],
      ['반쪽이', 'Brothers, take me with you!'],
      ['큰형', 'No! You look funny. Stay here.'],
      ['해설', 'The brothers tied him to a big rock.'],
      ['반쪽이', 'Heave-ho! This rock is easy!'],
      ['해설', 'He lifted the rock and hopped after them. Hop, hop!'],
      ['큰형', 'Oh no! He is coming with the rock!'],
      ['해설', 'On a mountain, tigers jumped out. Roar!'],
      ['해설', 'The brothers shook and hid behind a tree.'],
      ['반쪽이', 'Leave my brothers alone!'],
      ['해설', 'He held the tigers by their tails and spun them around.'],
      ['호랑이', 'I am dizzy! Sorry! We will be good!'],
      ['해설', 'The tigers ran far away into the mountain.'],
      ['큰형', 'Thank you, Banjjogi. We were wrong about you.'],
      ['해설', 'Later, a big rock blocked a village stream.'],
      ['부자', 'A half boy? What can you do?'],
      ['해설', 'Banjjogi pushed. The rock rolled away. The water ran again.'],
      ['부자', 'I am sorry. I only looked at the outside.'],
      ['해설', 'Banjjogi lived happily with his mother and brothers.'],
      ['해설', 'Do not judge people by how they look.'],
    ],
  },

  'kr2-five-friends': {
    title: 'Five Amazing Friends',
    names: { 해설: 'Narrator', 주먹이: 'Fist Boy', 콧김이: 'Blow Boy', 오줌이: 'Pee Boy', 무쇠다리: 'Iron Legs', 큰귀: 'Big Ears', 호랑이: 'Tiger' },
    outro: [
      'Was the story fun?',
      'If you were one of the friends, what skill would you want?',
      'What are you good at? How can it help a friend?',
    ],
    lines: [
      ['해설', 'Long ago, there were five friends with special skills.'],
      ['주먹이', 'One punch, and a big tree falls down!'],
      ['콧김이', 'One blow from my nose makes a big wind!'],
      ['오줌이', 'When I pee, it makes a river! Ha ha!'],
      ['무쇠다리', 'My legs are strong like iron.'],
      ['큰귀', 'I can hear an ant from far away.'],
      ['해설', 'The five friends went on a trip together.'],
      ['큰귀', 'Shh! Tigers are coming. They want to scare us.'],
      ['호랑이', 'Roar! This is our mountain! Let us have a contest!'],
      ['호랑이', 'Who can knock down more trees?'],
      ['해설', 'Fist Boy punched. Boom, boom! The trees fell down.'],
      ['호랑이', 'Then who can make a bigger wind?'],
      ['해설', 'Blow Boy blew. Whoosh! The tigers rolled away.'],
      ['호랑이', 'Then who can cross the river first?'],
      ['해설', 'Pee Boy made the river very big and deep.'],
      ['해설', 'The tigers splashed and splashed. Splash, splash!'],
      ['해설', 'Iron Legs walked across the deep river. Step, step!'],
      ['무쇠다리', 'I am first! We win!'],
      ['호랑이', 'We lose. We will not scare people again.'],
      ['해설', 'The tigers ran away over the mountain.'],
      ['주먹이', 'Alone we are small. Together we are great!'],
      ['해설', 'Everyone is good at something different.'],
      ['해설', 'When we work together, we can do anything.'],
    ],
  },

  'kr2-tiger-brother': {
    title: 'Big Brother Tiger',
    names: { 해설: 'Narrator', 나무꾼: 'Woodcutter', 호랑이: 'Tiger', 어머니: 'Mother' },
    outro: [
      'What did you think of the story?',
      'If you met a tiger, what idea would you have?',
      'How can you say thank you to your family?',
    ],
    lines: [
      ['해설', 'Long ago, a kind woodcutter lived with his old mother.'],
      ['해설', 'Every day, he went up the mountain to cut wood.'],
      ['해설', 'One day, a big tiger jumped in front of him.'],
      ['호랑이', 'Roar! I caught you!'],
      ['해설', 'The woodcutter was scared. But he had an idea.'],
      ['나무꾼', 'Oh, Big Brother! I finally found you!'],
      ['호랑이', 'Brother? I am not your brother!'],
      ['나무꾼', 'Mother says my brother became a tiger long ago.'],
      ['나무꾼', 'She cries for you every day.'],
      ['해설', 'The tiger blinked. Then he started to cry.'],
      ['호랑이', 'Oh, I forgot! I cannot visit her like this.'],
      ['호랑이', 'But I can still help my mother.'],
      ['해설', 'After that, presents came every night.'],
      ['해설', 'Berries, honey, and firewood! Thump!'],
      ['어머니', 'Son, who brings us these good things?'],
      ['나무꾼', 'My big brother from the mountain.'],
      ['해설', 'But the woodcutter felt bad inside.'],
      ['나무꾼', 'Brother is kind and true. I must be a true brother, too.'],
      ['해설', 'He took rice cakes to the tiger every time.'],
      ['나무꾼', 'Brother, Mother made these rice cakes for you.'],
      ['호랑이', 'Yum! Mother’s rice cakes are the best!'],
      ['어머니', 'My son on the mountain, stay healthy!'],
      ['해설', 'They were like real brothers for a long, long time.'],
      ['해설', 'Give back kindness with a true heart.'],
    ],
  },

  'kr2-rabbit-trial': {
    title: 'The Rabbit Judge',
    names: { 해설: 'Narrator', 호랑이: 'Tiger', 나그네: 'Traveler', 소나무: 'Pine Tree', 소: 'Ox', 토끼: 'Rabbit' },
    outro: [
      'Did you like the story?',
      'If you were the traveler, would you help the tiger out?',
      'When someone helped you, how did you say thank you?',
    ],
    lines: [
      ['해설', 'Long ago, a tiger fell into a deep hole.'],
      ['호랑이', 'Help! Please get me out!'],
      ['해설', 'A kind traveler walked by.'],
      ['호랑이', 'Please help me. I will thank you.'],
      ['해설', 'The traveler put a long log in the hole. The tiger climbed out.'],
      ['호랑이', 'Roar! I am hungry. I will eat you!'],
      ['나그네', 'What? You said you would thank me!'],
      ['나그네', 'Let us ask others. Who is right?'],
      ['해설', 'First, they asked a pine tree.'],
      ['소나무', 'People rest in my shade. Then they cut me. The tiger is right.'],
      ['해설', 'Next, they asked an old ox.'],
      ['소', 'People make me work all day. The tiger is right.'],
      ['해설', 'Then a rabbit hopped by. Hop, hop!'],
      ['토끼', 'I do not understand. Show me how it started.'],
      ['호랑이', 'I was in this hole! Like this!'],
      ['해설', 'The tiger jumped back into the hole.'],
      ['토끼', 'Traveler, where was the log?'],
      ['나그네', 'It was here. I put it in.'],
      ['토끼', 'Then take it out, like at the start.'],
      ['해설', 'The traveler took the log out. The tiger was stuck again!'],
      ['토끼', 'Now it is just like the start. The end!'],
      ['호랑이', 'I am sorry! I will not forget kindness again!'],
      ['해설', 'Never forget when someone helps you.'],
    ],
  },

  'kr2-tree-shade': {
    title: 'The Man Who Bought the Shade',
    names: { 해설: 'Narrator', 부자: 'Rich Man', 총각: 'Young Man' },
    outro: [
      'Was the story fun?',
      'If you were the rich man, would you sell the shade?',
      'What do you share with your friends?',
    ],
    lines: [
      ['해설', 'Long ago, a greedy rich man lived in a village.'],
      ['해설', 'A big tree stood in front of his house.'],
      ['해설', 'On a hot day, a young man sat in the cool shade.'],
      ['부자', 'Hey! This is my tree. The shade is mine, too. Go away!'],
      ['총각', 'Then sell me the shade. Here are five coins.'],
      ['부자', 'Ha ha! Money for shade? Okay, I will sell it!'],
      ['해설', 'The rich man wrote a paper. Now the shade was the young man’s.'],
      ['해설', 'Every day, the young man rested in the shade.'],
      ['해설', 'In the afternoon, the shade moved into the yard.'],
      ['해설', 'The young man moved into the yard, too.'],
      ['부자', 'Why are you in my yard?'],
      ['총각', 'My shade is here. So I am here, too.'],
      ['해설', 'In the evening, the shade went into the house!'],
      ['해설', 'The young man and his friends sat in the house. Ha ha, ho ho!'],
      ['부자', 'Oh no! My house is not my house!'],
      ['총각', 'I bought this shade. Here is the paper.'],
      ['부자', 'I was too greedy. Please sell the shade back.'],
      ['총각', 'Okay. But let everyone rest under the tree.'],
      ['부자', 'Yes, I promise.'],
      ['해설', 'After that, the shade was for everyone in the village.'],
      ['해설', 'Sharing feels better than keeping everything for yourself.'],
    ],
  },

  'kr2-youth-spring': {
    title: 'The Magic Spring',
    names: { 해설: 'Narrator', 할아버지: 'Grandpa', 할머니: 'Grandma', 욕심영감: 'Greedy Man' },
    outro: [
      'What did you think of the story?',
      'If you were the greedy man, how much would you drink?',
      'Did you ever eat too much? What happened?',
    ],
    lines: [
      ['해설', 'Long ago, a kind grandpa and grandma lived on a mountain.'],
      ['해설', 'One day, Grandpa was thirsty. He found a little spring.'],
      ['할아버지', 'I am so thirsty. I will drink some water.'],
      ['해설', 'Gulp, gulp! Grandpa drank the clear water.'],
      ['해설', 'His white beard was gone. His back was straight.'],
      ['할아버지', 'Wow! I am young again!'],
      ['해설', 'He went home, singing a happy song.'],
      ['할머니', 'Who are you? Where is my husband?'],
      ['할아버지', 'It is me! I drank from the magic spring!'],
      ['해설', 'Grandma drank the water, too. She became young again.'],
      ['해설', 'A greedy man next door heard about it.'],
      ['욕심영감', 'I will drink a lot. I will be very young!'],
      ['해설', 'He ran to the spring. Gulp, gulp, gulp!'],
      ['욕심영감', 'One more cup! One more cup!'],
      ['해설', 'He drank and drank. He did not stop.'],
      ['해설', 'In the evening, he did not come home.'],
      ['할아버지', 'Where is our neighbor? Let us go and look.'],
      ['해설', 'At the spring, they heard a sound. Waah, waah!'],
      ['할머니', 'Oh my! He is a little baby now!'],
      ['해설', 'He drank too much. So he became a baby.'],
      ['할아버지', 'Let us take care of him.'],
      ['해설', 'They raised the baby with love. He grew up kind.'],
      ['해설', 'Too much of a good thing is not good.'],
    ],
  },

  'kr2-gold-brothers': {
    title: 'The Brothers and the Gold',
    names: { 해설: 'Narrator', 형: 'Big Brother', 아우: 'Little Brother', 뱃사공: 'Boatman' },
    outro: [
      'What did you think of the story?',
      'If you were the little brother, could you throw the gold away?',
      'What is more special than money or toys?',
    ],
    lines: [
      ['해설', 'Long ago, two brothers loved each other very much.'],
      ['해설', 'One day, they saw something shiny on the road.'],
      ['아우', 'Look, Brother! Two lumps of gold!'],
      ['형', 'Wow! Let us take one each.'],
      ['해설', 'They went to the river and got on a boat.'],
      ['뱃사공', 'Here we go! Row, row!'],
      ['해설', 'In the middle of the river, the little brother stood up.'],
      ['해설', 'He threw his gold into the water. Splash!'],
      ['형', 'Why did you throw away your gold?'],
      ['아우', 'I had a bad thought, Brother.'],
      ['아우', 'I wanted your gold, too.'],
      ['아우', 'I did not want to hate you. So I threw it away.'],
      ['해설', 'The big brother looked at the water for a long time.'],
      ['형', 'I had the same bad thought.'],
      ['형', 'Gold must not come between us.'],
      ['해설', 'He threw his gold into the water, too. Splash!'],
      ['뱃사공', 'Ha ha! You threw away gold? How strange!'],
      ['형', 'Our love is better than gold.'],
      ['아우', 'Yes! With my brother, I am rich.'],
      ['해설', 'The brothers held hands and crossed the river.'],
      ['해설', 'A kind heart is better than gold.'],
    ],
  },

  'kr2-lazy-ox': {
    title: 'The Lazy Man Who Became an Ox',
    names: { 해설: 'Narrator', 게으름뱅이: 'Lazy Man', 아내: 'Wife', 노인: 'Old Man', 농부: 'Farmer' },
    outro: [
      'Was the story fun?',
      'If you were the ox, what would you be sorry about?',
      'What do you have to do, even when you do not want to?',
    ],
    lines: [
      ['해설', 'Long ago, there was a very lazy man.'],
      ['해설', 'He did not work. He slept all day.'],
      ['아내', 'Please go and work in the field today.'],
      ['게으름뱅이', 'I do not want to work. I want an easy life.'],
      ['해설', 'He walked and met an old man. The old man made a mask.'],
      ['노인', 'Wear this ox mask. Then you will not work.'],
      ['게으름뱅이', 'Really? Let me try it!'],
      ['해설', 'He put on the mask. Oh no! He became an ox!'],
      ['게으름뱅이', 'Moo! I am an ox!'],
      ['해설', 'The old man sold the ox to a farmer.'],
      ['노인', 'Never give this ox any radish.'],
      ['해설', 'Now the ox worked from morning to night.'],
      ['농부', 'Go, go! Pull harder!'],
      ['게으름뱅이', 'Moo. Working as a man was much easier.'],
      ['게으름뱅이', 'I was so lazy. I miss my wife.'],
      ['해설', 'One day, the ox saw a radish field.'],
      ['게으름뱅이', 'I must not eat radish. But I will try one.'],
      ['해설', 'Crunch, crunch! The mask fell off. He was a man again!'],
      ['해설', 'He ran all the way home.'],
      ['게으름뱅이', 'I am sorry. I will work hard from now on!'],
      ['아내', 'Where were you? I am so happy you are home.'],
      ['해설', 'After that, he was the hardest worker in the village.'],
      ['해설', 'If you are lazy now, it gets harder later.'],
    ],
  },

  'kr2-red-blue-fan': {
    title: 'The Red Fan and the Blue Fan',
    names: { 해설: 'Narrator', 나무꾼: 'Woodcutter', 부자: 'Rich Man', 하늘사람: 'Sky Guard' },
    outro: [
      'Did you like the story?',
      'If you were the woodcutter, how would you use the fans?',
      'If you had a magic fan, who would you help?',
    ],
    lines: [
      ['해설', 'Long ago, a poor woodcutter found two fans.'],
      ['해설', 'One fan was red. One fan was blue.'],
      ['해설', 'He waved the red fan. His nose grew long!'],
      ['나무꾼', 'Oh no! My nose is getting longer!'],
      ['해설', 'He waved the blue fan. His nose got short again.'],
      ['나무꾼', 'Ha ha! These are magic fans!'],
      ['해설', 'He went to the house of a mean rich man.'],
      ['해설', 'The rich man was asleep. The woodcutter waved the red fan.'],
      ['부자', 'Oh no! My nose is so long! Help me!'],
      ['부자', 'I will pay anyone who can fix my nose!'],
      ['해설', 'The woodcutter waved the blue fan. The nose got short.'],
      ['부자', 'Thank you! Here is rice and money!'],
      ['해설', 'Now the woodcutter was rich. But one day he was bored.'],
      ['나무꾼', 'How long can my nose grow? Let me see!'],
      ['해설', 'He waved the red fan again and again.'],
      ['해설', 'His nose went up, up, up into the sky!'],
      ['하늘사람', 'Whose nose is this? I will tie it to a post.'],
      ['해설', 'He waved the blue fan. His nose got shorter.'],
      ['해설', 'Up, up went the woodcutter! He hung from the post.'],
      ['나무꾼', 'Help! I am sorry! I will not play tricks again!'],
      ['해설', 'The sky guard let him down on a soft cloud.'],
      ['해설', 'The woodcutter took the fans back to the mountain.'],
      ['해설', 'Do not use special power for tricks or greed.'],
    ],
  },

  'kr2-ttokbo': {
    title: 'Ttokbo and the Visitor',
    names: { 해설: 'Narrator', 떡보: 'Ttokbo', 사신: 'Visitor', 임금님: 'King' },
    outro: [
      'Was the story fun?',
      'If you were Ttokbo, what would the circle make you think of?',
      'What is your favorite food in the world?',
    ],
    lines: [
      ['해설', 'Long ago, there was a man named Ttokbo.'],
      ['해설', 'He loved tteok, Korean rice cakes, more than anything.'],
      ['떡보', 'Yum! Soft, chewy rice cakes are the best!'],
      ['해설', 'One day, a visitor came from a big country.'],
      ['사신', 'Is anyone here wise? Let us talk with only our hands.'],
      ['임금님', 'Oh no! Who can do it?'],
      ['떡보', 'I will go! But give me lots of rice cakes first!'],
      ['해설', 'Ttokbo ate many rice cakes. Then he sat down.'],
      ['해설', 'The visitor drew a circle in the air.'],
      ['떡보', 'A round rice cake? Ha! I ate a square one!'],
      ['해설', 'So Ttokbo drew a square.'],
      ['사신', 'Wow! The sky is round, and the earth is square!'],
      ['해설', 'Next, the visitor showed three fingers.'],
      ['떡보', 'Three rice cakes? I ate five!'],
      ['해설', 'So Ttokbo showed five fingers.'],
      ['사신', 'I asked about three rules. He knows five! So wise!'],
      ['해설', 'Then the visitor touched his long beard.'],
      ['해설', 'Ttokbo patted his full tummy. Pat, pat!'],
      ['사신', 'His tummy is full of wisdom! This country is amazing!'],
      ['임금님', 'Ttokbo, well done! What do you want?'],
      ['떡보', 'Rice cakes, please! Lots of rice cakes!'],
      ['해설', 'Ttokbo shared his rice cakes with everyone.'],
      ['해설', 'Be brave and try. Good things can happen.'],
    ],
  },

  'kr2-jaringobi': {
    title: 'Jaringobi, the Saving Man',
    names: { 해설: 'Narrator', 자린고비: 'Jaringobi', 아들: 'Son', 이웃: 'Neighbor' },
    outro: [
      'Did you enjoy the story?',
      'If you were the son, how many times would you look at the fish?',
      'What things do you take good care of?',
    ],
    lines: [
      ['해설', 'Long ago, a very stingy man lived in a village.'],
      ['해설', 'People called him Jaringobi. He never wasted anything.'],
      ['해설', 'He hung a dried fish from the ceiling.'],
      ['자린고비', 'Children, eat one spoon of rice. Then look at the fish once.'],
      ['아들', 'Yes, Father. Rice, then fish. Rice, then fish.'],
      ['해설', 'But the youngest son looked at the fish twice.'],
      ['자린고비', 'Hey! Do not look twice! It is too salty!'],
      ['아들', 'Ha ha! Father, can fish be salty just by looking?'],
      ['해설', 'One day, a fly sat on his soy sauce jar.'],
      ['자린고비', 'Oh no! That fly has my soy sauce on its legs!'],
      ['해설', 'He ran after the fly. Over the hill, across the stream!'],
      ['이웃', 'Where are you running?'],
      ['자린고비', 'I want my soy sauce back!'],
      ['이웃', 'Oh my! He is so stingy!'],
      ['해설', 'He saved and saved. Soon he had lots of rice.'],
      ['해설', 'One year, there was no rain. Nobody had food.'],
      ['이웃', 'We have no rice. The children are hungry.'],
      ['해설', 'Then Jaringobi opened his rice storehouse.'],
      ['자린고비', 'Come and take some rice. I saved it for times like this.'],
      ['이웃', 'Thank you so much! We are sorry we laughed at you.'],
      ['아들', 'Father, is that why you saved so much?'],
      ['자린고비', 'Yes. We save so we can share when people need help.'],
      ['해설', 'Save what you have. Share it when others need it.'],
    ],
  },

  'kr2-story-pouch': {
    title: 'The Story Pouch',
    names: { 해설: 'Narrator', 도령: 'Young Master', 머슴: 'Helper', 이야기: 'Story', 꼬마이야기: 'Little Story' },
    outro: [
      'Did you like the story?',
      'If you were a story in the pouch, what would you say?',
      'What is your favorite story? Who will you tell it to?',
    ],
    lines: [
      ['해설', 'Long ago, a boy loved to hear stories.'],
      ['도령', 'Please tell me one more story!'],
      ['해설', 'He put every story into a little pouch.'],
      ['도령', 'These stories are mine. I will not tell anyone.'],
      ['해설', 'The pouch got fat. It hung in the attic.'],
      ['해설', 'Years later, the boy was going to get married.'],
      ['해설', 'That night, his helper heard voices in the attic.'],
      ['이야기', 'We are stuck! Let us play a trick on him!'],
      ['꼬마이야기', 'I will be red berries. He will get a tummy ache!'],
      ['이야기', 'I will be spring water. He will feel sick!'],
      ['이야기', 'I will be lots of frogs. Ribbit! He will be scared!'],
      ['머슴', 'Oh no! I must keep the boy safe.'],
      ['해설', 'The next day, they went to the bride’s house.'],
      ['도령', 'I am thirsty. Get me some water.'],
      ['머슴', 'No, sir. We must hurry.'],
      ['도령', 'Then get me some berries.'],
      ['머슴', 'No, sir. Please wait.'],
      ['해설', 'At the bride’s house, the helper chased the frogs away.'],
      ['도령', 'Why do you keep saying no?'],
      ['해설', 'The helper told him about the stories.'],
      ['도령', 'Oh! The stories were sad. I was greedy.'],
      ['해설', 'He opened the pouch. The stories flew all over the world.'],
      ['해설', 'Good things are better when you share them.'],
    ],
  },

  'kr2-clever-rabbit': {
    title: 'The Clever Rabbit',
    names: { 해설: 'Narrator', 토끼: 'Rabbit', 호랑이: 'Tiger' },
    outro: [
      'Was the story fun?',
      'If you were the tiger, which trick would surprise you most?',
      'When did you think hard and solve a problem?',
    ],
    lines: [
      ['해설', 'Long ago, a clever rabbit lived in the mountains.'],
      ['해설', 'One day, a hungry tiger stopped the rabbit.'],
      ['호랑이', 'Roar! I will eat you today!'],
      ['토끼', 'Wait! I will cook yummy rice cakes for you.'],
      ['해설', 'The rabbit put round stones on the fire.'],
      ['토끼', 'Eat them when they are ready. I will get honey.'],
      ['해설', 'The rabbit hopped away. The tiger bit a stone.'],
      ['호랑이', 'Ouch! Hot! Hard! This is a stone!'],
      ['해설', 'In winter, the tiger met the rabbit by a frozen river.'],
      ['토끼', 'Put your tail in the water. Fish will come.'],
      ['토끼', 'When your tail is heavy, you have lots of fish!'],
      ['해설', 'The tiger put his tail in a hole in the ice.'],
      ['해설', 'In the morning, his tail was heavy. But it was frozen!'],
      ['호랑이', 'Pull! Pull! My tail is stuck!'],
      ['해설', 'He pulled hard and fell on the ice. Bump!'],
      ['호랑이', 'Ouch! You tricked me again!'],
      ['해설', 'In spring, the tiger saw the rabbit under a big rock.'],
      ['토끼', 'Help! The sky is falling! I am holding it up!'],
      ['토끼', 'I am so tired. Please hold it for a minute!'],
      ['해설', 'The tiger held the rock. The rabbit ran away.'],
      ['호랑이', 'The sky is fine! I was tricked again!'],
      ['토끼', 'I am small, but I can think fast!'],
      ['해설', 'Stay calm and think. You can solve hard problems.'],
    ],
  },

  'kr2-anchovy-dream': {
    title: 'The Anchovy’s Dream',
    names: { 해설: 'Narrator', 멸치: 'Anchovy', 가자미: 'Flounder', 망둥이: 'Goby', 메기: 'Catfish', 꼴뚜기: 'Little Squid' },
    outro: [
      'Did you like the story?',
      'If you were Flounder, what would you say to Anchovy?',
      'Do you remember a dream you had?',
    ],
    lines: [
      ['해설', 'Long ago, an old anchovy lived in the sea.'],
      ['해설', 'An anchovy is a small fish. One night, he had a strange dream.'],
      ['멸치', 'I flew up to the sky. Then it snowed. Hot, then cold!'],
      ['멸치', 'Flounder, please bring Goby. He knows about dreams.'],
      ['가자미', 'Okay, Grandpa Anchovy! I will go!'],
      ['해설', 'Flounder swam far, far away. He brought Goby.'],
      ['해설', 'But Anchovy gave yummy food only to Goby.'],
      ['가자미', 'I worked hard. But nobody says thank you.'],
      ['망둥이', 'You flew to the sky. You will be a dragon!'],
      ['멸치', 'A dragon? Ha ha! What a great dream!'],
      ['가자미', 'No! A fishing net will pull you up to the sky!'],
      ['멸치', 'What? You are ruining my good dream!'],
      ['해설', 'Anchovy slapped Flounder. Slap!'],
      ['해설', 'Flounder’s eyes moved to one side.'],
      ['가자미', 'Oh no! My eyes are on one side!'],
      ['해설', 'Catfish laughed so hard. His mouth got very big.'],
      ['메기', 'Ha ha ha! I cannot close my mouth!'],
      ['꼴뚜기', 'I did not see anything! Really!'],
      ['해설', 'Goby was so surprised. His eyes popped out.'],
      ['멸치', 'Flounder, I am sorry. I should say thank you first.'],
      ['가자미', 'I am sorry, too. I was not nice.'],
      ['해설', 'That is why flounders have eyes on one side.'],
      ['해설', 'Say thank you first. And use kind words.'],
    ],
  },

  'kr2-short-pants': {
    title: 'The Short Pants',
    names: { 해설: 'Narrator', 아버지: 'Dad', 할머니: 'Grandma', 엄마: 'Mom', 딸: 'Daughter' },
    outro: [
      'Was the story fun?',
      'If you were the daughter, what would you do first?',
      'What did you secretly do for your family?',
    ],
    lines: [
      ['해설', 'Long ago, a happy family lived in a village.'],
      ['해설', 'One day, Dad bought new pants at the market.'],
      ['아버지', 'I will wear my new pants to the party tomorrow!'],
      ['해설', 'But the pants were a little too long.'],
      ['아버지', 'Mother, can you make my pants shorter?'],
      ['할머니', 'Sorry, my legs hurt today.'],
      ['아버지', 'Dear, can you make my pants shorter?'],
      ['엄마', 'Sorry, I have too much washing today.'],
      ['아버지', 'Sweetie, can you help me?'],
      ['딸', 'Sorry, Dad. I must take care of my brothers.'],
      ['아버지', 'Okay. I will wear them like this.'],
      ['해설', 'That night, Grandma got up quietly.'],
      ['할머니', 'I will make them shorter. Snip, snip!'],
      ['해설', 'Later, Mom got up quietly.'],
      ['엄마', 'I will make them shorter. Snip, snip!'],
      ['해설', 'Early in the morning, the daughter got up quietly.'],
      ['딸', 'I will make them shorter. Snip, snip!'],
      ['해설', 'In the morning, Dad put on his new pants.'],
      ['아버지', 'Oh! My pants are so short!'],
      ['해설', 'Each one cut off one hand’s length. Now they were shorts!'],
      ['딸', 'We all wanted to help you, Dad!'],
      ['아버지', 'Ha ha ha! Thank you, everyone. I will wear them!'],
      ['해설', 'Helping is good. Talking together is good, too.'],
    ],
  },
};
