// 영어 학습용 원고 (한국 초등 저학년, 영어 초급). 문장은 자체 각색.
// 키 = stories/aesop2.js 의 이야기 id. lines 의 첫 칸은 원래 이야기 cast 의 한국어 이름 그대로.
export default {
  'ae2-bear-friends': {
    title: 'The Two Friends and the Bear',
    names: { 해설: 'Narrator', 날쌘이: 'Quick', 느림보: 'Slow', 곰: 'Bear' },
    outro: [
      'Did you like the story?',
      'If you were Slow, what would you say to Quick?',
      'When did you help a friend?',
    ],
    lines: [
      ['해설', 'Once upon a time, two friends went for a walk.'],
      ['해설', 'One was Quick. One was Slow.'],
      ['날쌘이', 'Slow, let us always help each other!'],
      ['느림보', 'Yes! We are best friends.'],
      ['해설', 'They walked into the forest.'],
      ['해설', 'Then they heard a sound. Rustle, rustle!'],
      ['곰', 'Grr! Who is in my forest?'],
      ['해설', 'A big bear came out. Stomp, stomp!'],
      ['날쌘이', 'A bear! I will climb up the tree!'],
      ['해설', 'Quick climbed a tree all alone.'],
      ['느림보', 'Help me, Quick! I cannot climb!'],
      ['해설', 'But Quick did not help.'],
      ['느림보', 'What can I do? I will lie down and be still.'],
      ['해설', 'The bear came close. Sniff, sniff.'],
      ['곰', 'You do not move. You are no fun. I will go home.'],
      ['해설', 'The bear went away.'],
      ['날쌘이', 'Phew! What did the bear say in your ear?'],
      ['느림보', 'He said, do not walk with a friend who runs away.'],
      ['날쌘이', 'I am sorry. I only thought about me.'],
      ['느림보', 'Next time, please stay with me.'],
      ['날쌘이', 'I will. I promise.'],
      ['해설', 'A true friend stays with you in hard times.'],
    ],
  },

  'ae2-salt-donkey': {
    title: 'The Donkey and the Salt',
    names: { 해설: 'Narrator', 당나귀: 'Donkey', 장수: 'Man' },
    outro: [
      'Was the story fun?',
      'If you were the Donkey, what would you do with the heavy bag?',
      'What hard job did you finish all the way?',
    ],
    lines: [
      ['해설', 'Once upon a time, a man had a donkey.'],
      ['해설', 'Every day, the donkey carried a big bag of salt.'],
      ['당나귀', 'Oh, this bag is so heavy!'],
      ['장수', 'Let us go to the market, Donkey.'],
      ['해설', 'On the way, they crossed a little river.'],
      ['해설', 'The donkey slipped and fell in. Splash!'],
      ['해설', 'The salt melted in the water.'],
      ['당나귀', 'Wow! My bag is light now!'],
      ['장수', 'Oh no! My salt is gone!'],
      ['해설', 'The next day, the donkey fell in again. Splash!'],
      ['당나귀', 'Hee hee! It is light again!'],
      ['장수', 'He is doing it on purpose. I have an idea.'],
      ['해설', 'The next day, the man filled the bag with cotton.'],
      ['해설', 'The donkey sat down in the river again. Splash!'],
      ['해설', 'The cotton drank up the water.'],
      ['당나귀', 'Oh no! Why is it so heavy now?'],
      ['해설', 'The donkey walked out very slowly. Huff, puff.'],
      ['당나귀', 'I played a trick, but it was a bad idea.'],
      ['장수', 'Tricks can make things harder for you.'],
      ['당나귀', 'I am sorry. I will work hard now.'],
      ['해설', 'Do not be lazy. Working hard is the best way.'],
    ],
  },

  'ae2-lion-skin': {
    title: 'The Donkey in the Lion Skin',
    names: { 해설: 'Narrator', 당나귀: 'Donkey', 여우: 'Fox', 토끼: 'Rabbit' },
    outro: [
      'Did you enjoy the story?',
      'If you were the Donkey, how would you say sorry?',
      'What is great about you?',
    ],
    lines: [
      ['해설', 'Once upon a time, there was a silly donkey.'],
      ['해설', 'One day, he found a lion skin in the grass.'],
      ['당나귀', 'A lion coat! I will put it on!'],
      ['당나귀', 'Now I am a big lion! Ha ha!'],
      ['해설', 'The donkey walked into the field.'],
      ['토끼', 'Oh no, a lion! Run, run!'],
      ['해설', 'All the animals ran and hid.'],
      ['당나귀', 'This is fun! They are all scared of me!'],
      ['해설', 'Then a clever fox came by.'],
      ['당나귀', 'I will scare the fox, too.'],
      ['해설', 'The donkey opened his mouth and made a big sound.'],
      ['당나귀', 'Hee-haw! Hee-haw!'],
      ['여우', 'A lion says hee-haw? You are a donkey!'],
      ['당나귀', 'Oh! How did you know?'],
      ['여우', 'You can change your coat. But you cannot change your voice.'],
      ['토끼', 'It is just the donkey! We were so scared.'],
      ['당나귀', 'I am sorry, friends. I will just be me.'],
      ['해설', 'The donkey took off the lion skin.'],
      ['해설', 'He played with his friends all day.'],
      ['해설', 'Just be you. That is the best.'],
    ],
  },

  'ae2-dove-ant': {
    title: 'The Dove and the Ant',
    names: { 해설: 'Narrator', 개미: 'Ant', 비둘기: 'Dove', 사냥꾼: 'Hunter' },
    outro: [
      'Did you like the story?',
      'If you were the Ant, how would you help the Dove?',
      'When did a friend help you?',
    ],
    lines: [
      ['해설', 'Once upon a time, a little ant lived by a river.'],
      ['개미', 'I am thirsty. I will drink some water.'],
      ['해설', 'Oh no! The ant fell into the river. Splash!'],
      ['개미', 'Help! Help me!'],
      ['해설', 'A dove saw the ant from a tree.'],
      ['비둘기', 'I will help you, little ant!'],
      ['해설', 'The dove dropped a leaf into the water.'],
      ['비둘기', 'Climb on the leaf!'],
      ['해설', 'The ant climbed on. The leaf floated to the land.'],
      ['개미', 'Thank you, Dove! You saved me.'],
      ['해설', 'A few days later, a hunter came with a net.'],
      ['사냥꾼', 'I will catch that dove.'],
      ['해설', 'The dove was sleeping on a branch.'],
      ['개미', 'Oh no! The dove is in danger!'],
      ['해설', 'The ant ran and bit the hunter’s foot.'],
      ['사냥꾼', 'Ouch! Ouch!'],
      ['해설', 'The dove woke up and flew away. Flap, flap!'],
      ['사냥꾼', 'Oh no! The dove is gone.'],
      ['비둘기', 'Thank you, Ant! You saved me, too.'],
      ['개미', 'You helped me first. Now I helped you.'],
      ['해설', 'Even a small friend can be a big help.'],
    ],
  },

  'ae2-miller-donkey': {
    title: 'Father, Son, and the Donkey',
    names: { 해설: 'Narrator', 아버지: 'Father', 아들: 'Son', 마을사람: 'Man', 할아버지: 'Grandpa', 아줌마: 'Woman' },
    outro: [
      'Was the story funny?',
      'If you were the Son, what would you do?',
      'What do you do when friends think differently from you?',
    ],
    lines: [
      ['해설', 'A father and his son went to the market.'],
      ['해설', 'They took their donkey to sell.'],
      ['마을사람', 'Look! They have a donkey, but they walk!'],
      ['아버지', 'Son, you ride the donkey.'],
      ['할아버지', 'The young son rides. The old father walks. That is bad!'],
      ['아들', 'Father, you ride. I will walk.'],
      ['아줌마', 'Look! The little boy walks. That is not nice!'],
      ['아버지', 'Then we will both ride.'],
      ['해설', 'The donkey was very tired. Huff, puff.'],
      ['마을사람', 'Poor donkey! Two people are too heavy!'],
      ['아들', 'Father, what can we do now?'],
      ['아버지', 'We will carry the donkey!'],
      ['해설', 'They carried the donkey on a long pole.'],
      ['해설', 'Everyone laughed. Ha ha ha!'],
      ['해설', 'On a bridge, the donkey kicked and kicked.'],
      ['해설', 'Splash! The donkey fell into the river.'],
      ['해설', 'The donkey swam out and ran away.'],
      ['아들', 'Oh no, Father! The donkey is gone.'],
      ['아버지', 'We listened to everyone. That was a mistake.'],
      ['아버지', 'Next time, let us think for ourselves.'],
      ['해설', 'Listen to others, but think for yourself, too.'],
    ],
  },

  'ae2-fox-goat': {
    title: 'The Fox and the Goat',
    names: { 해설: 'Narrator', 여우: 'Fox', 염소: 'Goat', 농부: 'Farmer' },
    outro: [
      'Did you enjoy the story?',
      'If you were the Goat, what would you ask first?',
      'Did you ever make a mistake because you were in a hurry?',
    ],
    lines: [
      ['해설', 'One hot day, a fox was very thirsty.'],
      ['해설', 'He fell into a well. Splash!'],
      ['여우', 'I drank the water. But how do I get out?'],
      ['해설', 'Then a goat came by.'],
      ['염소', 'Fox, is the water good?'],
      ['여우', 'Yes! It is very good. Come down!'],
      ['해설', 'The goat jumped in without thinking.'],
      ['염소', 'Yum! But how do we get out?'],
      ['여우', 'Stand up by the wall. I will climb on you.'],
      ['여우', 'Then I will pull you up.'],
      ['해설', 'The fox climbed on the goat and jumped out.'],
      ['염소', 'Now pull me up, Fox!'],
      ['여우', 'Sorry, I must go. Think before you jump!'],
      ['해설', 'The fox ran away.'],
      ['염소', 'Oh no. I did not think first.'],
      ['해설', 'The goat cried. Maa, maa!'],
      ['해설', 'A farmer came with a rope.'],
      ['농부', 'Here, Goat! Hold the rope.'],
      ['해설', 'The goat got out of the well.'],
      ['염소', 'Thank you! Next time, I will think first.'],
      ['해설', 'Always think before you jump.'],
    ],
  },

  'ae2-kid-flute': {
    title: 'The Little Goat and the Flute',
    names: { 해설: 'Narrator', 아기염소: 'Little Goat', 늑대: 'Wolf', 양치기개: 'Dog' },
    outro: [
      'Was the story fun?',
      'If you were the Little Goat, what trick would you use?',
      'What should you do when you are lost?',
    ],
    lines: [
      ['해설', 'Once upon a time, there was a little goat.'],
      ['해설', 'Her mom always said, do not go far.'],
      ['아기염소', 'The grass looks good over there!'],
      ['해설', 'The little goat walked far, far away.'],
      ['아기염소', 'Where am I? Mom! Mom!'],
      ['해설', 'Then a wolf came out from behind a rock.'],
      ['늑대', 'Ha ha! A little goat! Dinner for me!'],
      ['아기염소', 'Oh no! I am scared. But I must think.'],
      ['아기염소', 'Mr. Wolf, wait! I have one wish.'],
      ['늑대', 'A wish? What is it?'],
      ['아기염소', 'I love to dance. Please play music for me.'],
      ['늑대', 'Okay. I can play the flute.'],
      ['해설', 'The wolf played the flute. Toot, toot!'],
      ['해설', 'The little goat danced and danced.'],
      ['아기염소', 'Louder, please! Play louder!'],
      ['해설', 'The music went far over the hill.'],
      ['양치기개', 'Woof, woof! What is that sound?'],
      ['해설', 'The dogs ran to the little goat. Fast, fast!'],
      ['늑대', 'Oh no, dogs! I must run!'],
      ['해설', 'The wolf ran away.'],
      ['아기염소', 'Thank you, dogs! I will stay close to Mom.'],
      ['해설', 'When you are scared, stay calm and think.'],
    ],
  },

  'ae2-jay-feathers': {
    title: 'The Crow with Peacock Feathers',
    names: { 해설: 'Narrator', 까마귀: 'Crow', 공작: 'Peacock', 친구까마귀: 'Friend' },
    outro: [
      'Did you like the story?',
      'If you were the Crow, what would you say to your friends?',
      'What do you like about yourself?',
    ],
    lines: [
      ['해설', 'Once upon a time, there was a black crow.'],
      ['까마귀', 'My feathers are all black. I do not like them.'],
      ['해설', 'Some peacocks walked by. Their tails were so pretty.'],
      ['까마귀', 'Wow! I want to be pretty, too.'],
      ['해설', 'The crow found some peacock feathers on the ground.'],
      ['까마귀', 'I will put these feathers on me!'],
      ['까마귀', 'Now I am a peacock! Ha ha!'],
      ['친구까마귀', 'Crow, let us play together.'],
      ['까마귀', 'No! I am a peacock now. Go away!'],
      ['해설', 'The crow went to the peacocks.'],
      ['까마귀', 'Hello! Can I play with you?'],
      ['공작', 'Wait. These are our feathers! You are a crow!'],
      ['해설', 'The peacocks took back their feathers.'],
      ['해설', 'The crow was black again. He was sad.'],
      ['까마귀', 'Friends, I am sorry. Can I play with you?'],
      ['친구까마귀', 'Of course! We like your black feathers.'],
      ['친구까마귀', 'They shine in the sun!'],
      ['해설', 'The crow looked at his feathers and smiled.'],
      ['해설', 'Love who you are. You are special.'],
    ],
  },

  'ae2-frog-king': {
    title: 'The Frogs Who Wanted a King',
    names: { 해설: 'Narrator', 개구리: 'Frog', 큰개구리: 'Big Frog', 하늘님: 'Sky King', 황새: 'Stork' },
    outro: [
      'Was the story fun?',
      'If you were a Frog, what would you ask for?',
      'What are you thankful for today?',
    ],
    lines: [
      ['해설', 'Once upon a time, many frogs lived in a pond.'],
      ['해설', 'They sang every day. Ribbit, ribbit!'],
      ['큰개구리', 'We do not have a king. Let us ask for one.'],
      ['개구리', 'Sky King, please give us a king!'],
      ['하늘님', 'A king? Here you go.'],
      ['해설', 'A big log fell into the pond. Splash!'],
      ['해설', 'The frogs were scared. They hid in the water.'],
      ['큰개구리', 'The king does not move. Let us look.'],
      ['해설', 'The frogs jumped on the log. Hop, hop!'],
      ['개구리', 'This king is boring. He does not talk.'],
      ['개구리', 'Sky King, please give us a strong king!'],
      ['하늘님', 'Are you sure? Okay. Here is a stork.'],
      ['황새', 'I am your new king! Do what I say!'],
      ['해설', 'The stork chased the frogs. Peck, peck!'],
      ['개구리', 'Ouch! This king is too scary!'],
      ['큰개구리', 'Our old pond was the best.'],
      ['개구리', 'Sky King, we are sorry. We do not need a king.'],
      ['하늘님', 'Now you know. Stork, come back home.'],
      ['해설', 'The stork flew away. The frogs sang again.'],
      ['해설', 'Be happy with what you have.'],
    ],
  },

  'ae2-gnat-lion': {
    title: 'The Lion and the Mosquito',
    names: { 해설: 'Narrator', 사자: 'Lion', 모기: 'Mosquito', 거미: 'Spider' },
    outro: [
      'Did you enjoy the story?',
      'If you were the Mosquito, what would you do after you won?',
      'How do you feel when you do something well?',
    ],
    lines: [
      ['해설', 'Once upon a time, there was a big lion.'],
      ['사자', 'Roar! I am the king! Everyone is scared of me!'],
      ['해설', 'A tiny mosquito flew by. Buzz, buzz.'],
      ['모기', 'I am not scared of you!'],
      ['사자', 'What? You are so small!'],
      ['해설', 'The mosquito bit the lion on the nose.'],
      ['사자', 'Ouch! Go away!'],
      ['해설', 'The mosquito bit his ear. Then his cheek.'],
      ['사자', 'Itchy, itchy! Stop, please! You win!'],
      ['모기', 'I beat the lion! I am the best!'],
      ['해설', 'The mosquito sang and flew around. Buzz, buzz!'],
      ['해설', 'He did not look where he was going.'],
      ['해설', 'He flew into a spider web.'],
      ['모기', 'Oh no! I cannot move!'],
      ['거미', 'Who is in my web?'],
      ['모기', 'Please help me, Spider! I was showing off.'],
      ['거미', 'You beat a lion, but not my little web.'],
      ['모기', 'You are right. I will not show off again.'],
      ['거미', 'Okay. I will let you go this time.'],
      ['해설', 'Do not show off. Be careful, even when you win.'],
    ],
  },

  'ae2-wolf-crane': {
    title: 'The Wolf and the Crane',
    names: { 해설: 'Narrator', 늑대: 'Wolf', 두루미: 'Crane', 다람쥐: 'Squirrel' },
    outro: [
      'Was the story fun?',
      'If you were the Crane, what would you say to the Wolf?',
      'How do you say thank you to someone who helps you?',
    ],
    lines: [
      ['해설', 'Once upon a time, there was a hungry wolf.'],
      ['해설', 'The wolf ate very fast. Gulp, gulp!'],
      ['해설', 'Oh no! A bone got stuck in his throat.'],
      ['늑대', 'Cough, cough! Help me, please!'],
      ['다람쥐', 'My hands are too short. Go to the crane!'],
      ['늑대', 'Crane, please help me. Take out the bone.'],
      ['늑대', 'I will give you a big gift!'],
      ['두루미', 'Okay. Open your mouth wide.'],
      ['해설', 'The crane put her long neck in.'],
      ['해설', 'She took out the bone with her beak.'],
      ['늑대', 'Phew! I feel better now.'],
      ['두루미', 'Now, can I have my gift?'],
      ['늑대', 'A gift? Your head was in my mouth.'],
      ['늑대', 'And you are fine. That is your gift!'],
      ['해설', 'The wolf did not say thank you. He just left.'],
      ['두루미', 'I helped him. But he was not thankful.'],
      ['다람쥐', 'You were very kind, Crane.'],
      ['두루미', 'Thank you. Next time, I will help a kind friend.'],
      ['해설', 'Always say thank you, and keep your promises.'],
    ],
  },

  'ae2-bat': {
    title: 'The Bat, Birds, and Animals',
    names: { 해설: 'Narrator', 박쥐: 'Bat', 독수리: 'Eagle', 곰: 'Bear' },
    outro: [
      'Did you like the story?',
      'If you were the Bat, which side would you choose?',
      'What do you do when your friends fight?',
    ],
    lines: [
      ['해설', 'Long ago, the birds and the animals had a fight.'],
      ['독수리', 'Birds are the best! Birds, come here!'],
      ['곰', 'No! Animals are the best! Animals, come here!'],
      ['박쥐', 'Hmm. Who will win? I want to be on the winning side.'],
      ['해설', 'The birds were winning. The bat flew to them.'],
      ['박쥐', 'Eagle, I am a bird! Look at my wings!'],
      ['독수리', 'Okay. You are on our side.'],
      ['해설', 'Then the animals were winning.'],
      ['박쥐', 'Bear, I am an animal! Look at my fur!'],
      ['곰', 'Okay. You are on our side.'],
      ['해설', 'The bat went this way and that way.'],
      ['해설', 'Then the birds and the animals stopped fighting.'],
      ['독수리', 'Let us be friends now.'],
      ['곰', 'Wait. Whose side was the bat on?'],
      ['독수리', 'He told us he was a bird!'],
      ['곰', 'He told us he was an animal!'],
      ['박쥐', 'Um, I just wanted to be on the winning side.'],
      ['독수리', 'We cannot trust you, Bat.'],
      ['해설', 'Nobody played with the bat.'],
      ['해설', 'So the bat hid in a cave in the daytime.'],
      ['박쥐', 'I am sorry. From now on, I will be honest.'],
      ['해설', 'Be honest, and do not keep changing sides.'],
    ],
  },

  'ae2-rooster-jewel': {
    title: 'The Rooster and the Jewel',
    names: { 해설: 'Narrator', 수탉: 'Rooster', 암탉: 'Hen', 병아리: 'Chick', 소녀: 'Girl' },
    outro: [
      'Was the story fun?',
      'If you were the Rooster, what would you do with the jewel?',
      'What is more special to you than a jewel?',
    ],
    lines: [
      ['해설', 'Once upon a time, a rooster lived on a farm.'],
      ['수탉', 'Cock-a-doodle-doo! Good morning!'],
      ['해설', 'Every day, he looked for food. Scratch, scratch!'],
      ['병아리', 'Dad, I am hungry. Peep, peep!'],
      ['수탉', 'Wait a little. I will find food.'],
      ['해설', 'Then something shiny came out of the dirt.'],
      ['수탉', 'What is this? A shiny stone?'],
      ['암탉', 'That is a jewel! People love jewels.'],
      ['수탉', 'Can we eat it?'],
      ['해설', 'He pecked it. Peck, peck. It was too hard.'],
      ['수탉', 'A jewel is no good for us.'],
      ['수탉', 'One little seed is better for my chicks.'],
      ['해설', 'Then a girl came by. She was crying.'],
      ['소녀', 'Where is my jewel? My grandma gave it to me.'],
      ['수탉', 'Here it is! You can have it.'],
      ['소녀', 'My jewel! Thank you, Rooster!'],
      ['해설', 'The girl gave the chickens lots of corn.'],
      ['병아리', 'Yummy corn! Thank you!'],
      ['해설', 'Know what you really need. That is the smart way.'],
    ],
  },

  'ae2-tortoise-eagle': {
    title: 'The Tortoise and the Eagle',
    names: { 해설: 'Narrator', 거북이: 'Tortoise', 독수리: 'Eagle' },
    outro: [
      'Did you enjoy the story?',
      'If you were the Tortoise, would you listen to the Eagle?',
      'What are you good at?',
    ],
    lines: [
      ['해설', 'Once upon a time, a tortoise lived by a pond.'],
      ['거북이', 'I want to fly like the birds.'],
      ['해설', 'One day, a big eagle came down.'],
      ['거북이', 'Eagle, please teach me to fly!'],
      ['독수리', 'You have no wings. You cannot fly.'],
      ['거북이', 'Please! I really want to fly!'],
      ['독수리', 'It is not safe. But okay.'],
      ['해설', 'The eagle held the tortoise and flew up high.'],
      ['거북이', 'Wow! The houses look so small!'],
      ['거북이', 'I am flying! Let me go now!'],
      ['독수리', 'Are you sure? You cannot fly alone.'],
      ['거북이', 'Yes! I can fly! Let me go!'],
      ['해설', 'The eagle let him go over the pond.'],
      ['거북이', 'Oh no! I am going down!'],
      ['해설', 'Splash! The tortoise fell into the pond.'],
      ['독수리', 'Are you okay? I told you.'],
      ['거북이', 'You were right. I have no wings.'],
      ['거북이', 'But look! I can swim very well!'],
      ['독수리', 'Yes! That is your special skill.'],
      ['해설', 'Be happy with what you are good at.'],
    ],
  },

  'ae2-nut-jar': {
    title: 'The Boy and the Jar of Nuts',
    names: { 해설: 'Narrator', 아이: 'Boy', 엄마: 'Mom' },
    outro: [
      'Was the story funny?',
      'If you were the Boy, how many nuts would you take?',
      'When did wanting too much get you in trouble?',
    ],
    lines: [
      ['해설', 'Once upon a time, a boy lived with his mom.'],
      ['해설', 'There was a jar of nuts in the kitchen.'],
      ['엄마', 'You can have some nuts for a snack.'],
      ['아이', 'Yay! I love nuts!'],
      ['해설', 'The boy put his hand into the jar.'],
      ['아이', 'I want lots and lots of nuts!'],
      ['해설', 'He took a big handful.'],
      ['해설', 'But his hand got stuck in the jar.'],
      ['아이', 'Oh no! My hand is stuck!'],
      ['해설', 'He pulled and pulled. But it did not come out.'],
      ['아이', 'Mom! Help me!'],
      ['엄마', 'You have too many nuts in your hand.'],
      ['엄마', 'Let some go. Then your hand will come out.'],
      ['아이', 'But I want all of them!'],
      ['엄마', 'If you hold them all, you get none.'],
      ['해설', 'The boy let half of the nuts go.'],
      ['해설', 'Pop! His hand came out.'],
      ['아이', 'I did it! I still have nuts!'],
      ['아이', 'Mom, here is one for you.'],
      ['엄마', 'Thank you, sweetie.'],
      ['해설', 'Do not try to take too much at once.'],
    ],
  },

  'ae2-oak-reed': {
    title: 'The Oak and the Reed',
    names: { 해설: 'Narrator', 떡갈나무: 'Oak', 갈대: 'Reed', 바람: 'Wind' },
    outro: [
      'Did you like the story?',
      'If you were the Oak, what would you do in the wind?',
      'When did you let a friend go first?',
    ],
    lines: [
      ['해설', 'Once upon a time, a big oak tree stood by a river.'],
      ['해설', 'Little reeds grew near the oak.'],
      ['떡갈나무', 'Reed, you are so weak. You move in the wind.'],
      ['떡갈나무', 'Look at me. I stand tall and strong.'],
      ['갈대', 'Yes, I am small. So I bend in the wind.'],
      ['떡갈나무', 'Bend? I never bend!'],
      ['해설', 'That night, a big wind came.'],
      ['바람', 'Whoosh! Whoosh! Here I come!'],
      ['해설', 'The reeds bent low. The wind went over them.'],
      ['해설', 'But the oak did not bend.'],
      ['떡갈나무', 'I will not bend! I am strong!'],
      ['바람', 'Then I will blow harder! Whoosh!'],
      ['해설', 'Crack! The big branches of the oak broke.'],
      ['떡갈나무', 'Oh no! My branches!'],
      ['해설', 'In the morning, the sun came out.'],
      ['해설', 'The reeds stood up again and danced.'],
      ['떡갈나무', 'Reed, you are not weak. Bending is strong, too.'],
      ['갈대', 'You are strong, too. Birds make homes in your branches.'],
      ['떡갈나무', 'Thank you, Reed. Let us learn from each other.'],
      ['해설', 'Sometimes it is good to bend a little.'],
    ],
  },

  'ae2-wolf-dog': {
    title: 'The Wolf and the Dog',
    names: { 해설: 'Narrator', 늑대: 'Wolf', 개: 'Dog' },
    outro: [
      'Was the story fun?',
      'If you were the Wolf, where would you live?',
      'How do you feel when you can play freely?',
    ],
    lines: [
      ['해설', 'Once upon a time, there was a thin wolf.'],
      ['늑대', 'I am so hungry. I have no food.'],
      ['해설', 'Then a big, happy dog came.'],
      ['개', 'Hello, Wolf! Why are you so thin?'],
      ['늑대', 'I have no food. Why are you so big?'],
      ['개', 'I live with a man. He gives me food every day.'],
      ['개', 'Come with me! You can eat, too.'],
      ['늑대', 'Really? Yes, I will come!'],
      ['해설', 'They walked to the town together.'],
      ['해설', 'Then the wolf saw a mark on the dog’s neck.'],
      ['늑대', 'Dog, what is on your neck?'],
      ['개', 'Oh, that is from my rope.'],
      ['개', 'In the day, I stay on a rope.'],
      ['늑대', 'So you cannot run where you want?'],
      ['개', 'No. But the food is good!'],
      ['해설', 'The wolf stopped and thought.'],
      ['늑대', 'I like to run in the forest.'],
      ['늑대', 'I like to sing to the moon.'],
      ['늑대', 'Sorry, Dog. I will stay free in the forest.'],
      ['개', 'Okay, Wolf. Goodbye, friend!'],
      ['해설', 'Being free is very special.'],
    ],
  },

  'ae2-crab': {
    title: 'Mom Crab and Baby Crab',
    names: { 해설: 'Narrator', 엄마게: 'Mom Crab', 아기게: 'Baby Crab' },
    outro: [
      'Did you enjoy the story?',
      'If you were Baby Crab, what would you say to Mom?',
      'How can you show a friend the right way?',
    ],
    lines: [
      ['해설', 'Once upon a time, there were two crabs.'],
      ['해설', 'Mom Crab and Baby Crab lived on a beach.'],
      ['해설', 'Crabs walk to the side. Side, side, side.'],
      ['엄마게', 'Baby, do not walk to the side. Walk straight!'],
      ['아기게', 'Straight? How?'],
      ['엄마게', 'Put your feet out in front, like this.'],
      ['아기게', 'Okay, Mom. One, two!'],
      ['해설', 'But Baby Crab went to the side again.'],
      ['아기게', 'Oops! It is too hard.'],
      ['엄마게', 'Then watch me. I will show you.'],
      ['아기게', 'Okay! Show me, Mom.'],
      ['엄마게', 'Look. Walk straight, like this!'],
      ['해설', 'But Mom Crab went to the side, too!'],
      ['아기게', 'Ha ha! Mom, you walk to the side, too!'],
      ['엄마게', 'Oh my! You are right.'],
      ['엄마게', 'I am sorry. I cannot do it either.'],
      ['아기게', 'That is okay, Mom. We are fast to the side!'],
      ['엄마게', 'Yes! Let us race to the rock.'],
      ['해설', 'Mom Crab and Baby Crab ran side by side.'],
      ['해설', 'Show others the way first. Then they can learn.'],
    ],
  },

  'ae2-full-fox': {
    title: 'The Fox with a Full Tummy',
    names: { 해설: 'Narrator', 여우: 'Fox', 다람쥐: 'Squirrel' },
    outro: [
      'Was the story funny?',
      'If you were the Fox, what would you do with the food?',
      'Did you ever eat too much?',
    ],
    lines: [
      ['해설', 'Once upon a time, there was a hungry fox.'],
      ['여우', 'I am so hungry. Where is some food?'],
      ['해설', 'Then he smelled something good. Sniff, sniff.'],
      ['해설', 'There was food in a hole in a tree.'],
      ['여우', 'Bread and meat! Yummy!'],
      ['해설', 'The fox was thin. He went into the hole.'],
      ['해설', 'He ate and ate and ate.'],
      ['여우', 'Burp! I am full. Now I will go out.'],
      ['해설', 'But his tummy was too big. He was stuck!'],
      ['여우', 'Oh no! I cannot get out! Help!'],
      ['해설', 'A squirrel came by.'],
      ['다람쥐', 'Fox, what are you doing?'],
      ['여우', 'I ate too much. Now I am stuck.'],
      ['다람쥐', 'You were thin. Now your tummy is big.'],
      ['다람쥐', 'Wait. When you are thin again, you can get out.'],
      ['여우', 'Wait? Oh no.'],
      ['해설', 'The fox waited and waited until the evening.'],
      ['해설', 'At last, he got out. Pop!'],
      ['여우', 'Phew! I will not take food that is not mine.'],
      ['다람쥐', 'And do not eat too much.'],
      ['해설', 'Do not be greedy. Too much is not good.'],
    ],
  },

  'ae2-milkmaid': {
    title: 'The Girl and the Milk',
    names: { 해설: 'Narrator', 소녀: 'Girl', 엄마: 'Mom' },
    outro: [
      'Did you like the story?',
      'If you were the Girl, what would you buy with the money?',
      'Did you ever make a mistake because you were daydreaming?',
    ],
    lines: [
      ['해설', 'Once upon a time, there was a girl on a farm.'],
      ['엄마', 'Please take this milk to the market.'],
      ['소녀', 'Okay, Mom!'],
      ['해설', 'The girl put the milk pail on her head.'],
      ['해설', 'She walked and started to dream.'],
      ['소녀', 'I will sell the milk and buy eggs.'],
      ['소녀', 'The eggs will become baby chicks. Peep, peep!'],
      ['소녀', 'The chicks will grow big. I will sell them.'],
      ['소녀', 'Then I will buy a pretty new dress!'],
      ['소녀', 'Everyone will look at me.'],
      ['소녀', 'I will turn my head like this!'],
      ['해설', 'The girl turned her head. Whoosh!'],
      ['해설', 'The pail fell down. Splash!'],
      ['소녀', 'Oh no! My milk is gone!'],
      ['소녀', 'No eggs. No chicks. No new dress.'],
      ['해설', 'The girl went home with an empty pail.'],
      ['소녀', 'Mom, I am sorry. I was dreaming.'],
      ['엄마', 'Dreams are good. But think about what you are doing.'],
      ['소녀', 'Okay. I will be careful tomorrow.'],
      ['해설', 'Dream big, but do your job first.'],
    ],
  },

  'ae2-lion-boar': {
    title: 'The Lion and the Boar',
    names: { 해설: 'Narrator', 사자: 'Lion', 멧돼지: 'Boar', 까마귀: 'Crow' },
    outro: [
      'Was the story fun?',
      'If you were the Lion, what would you say to the Boar?',
      'Did you ever fight with a friend about going first?',
    ],
    lines: [
      ['해설', 'One hot summer day, everyone was very thirsty.'],
      ['해설', 'A lion and a boar came to a little pond.'],
      ['사자', 'Roar! I will drink first. Move!'],
      ['멧돼지', 'Oink! No! I was here first!'],
      ['사자', 'I am the king. The king drinks first!'],
      ['멧돼지', 'I am strong, too! I will not move!'],
      ['해설', 'They pushed and pushed. Bump, bump!'],
      ['해설', 'Then they heard some crows in a tree.'],
      ['까마귀', 'Look! They are fighting. Let us drink the water!'],
      ['까마귀', 'Caw, caw! The water is all ours!'],
      ['해설', 'The lion and the boar stopped.'],
      ['사자', 'Boar, did you hear that?'],
      ['멧돼지', 'Yes! The crows are drinking our water!'],
      ['사자', 'If we fight, we will get no water.'],
      ['멧돼지', 'You are right. Let us share.'],
      ['사자', 'I am sorry, Boar.'],
      ['멧돼지', 'I am sorry, too, Lion.'],
      ['해설', 'The crows flew away. Flap, flap!'],
      ['해설', 'The lion and the boar drank together. Gulp, gulp!'],
      ['사자', 'Ah! Water is better with a friend.'],
      ['해설', 'Fighting is bad for everyone. Sharing makes everyone happy.'],
    ],
  },

  'ae2-two-goats': {
    title: 'The Two Goats on the Bridge',
    names: { 해설: 'Narrator', 흰염소: 'White Goat', 검은염소: 'Black Goat' },
    outro: [
      'Did you enjoy the story?',
      'If you were the White Goat, what would you do on the bridge?',
      'When did you feel good after taking turns?',
    ],
    lines: [
      ['해설', 'Once upon a time, there was a very narrow bridge.'],
      ['해설', 'Under the bridge, a river went splash, splash.'],
      ['해설', 'A white goat and a black goat came to the bridge.'],
      ['해설', 'They met in the middle.'],
      ['흰염소', 'Move! I will go first.'],
      ['검은염소', 'No, you move! I was here first!'],
      ['흰염소', 'I will not go back!'],
      ['검은염소', 'Me, too! I will not go back!'],
      ['해설', 'They pushed with their horns. Bump, bump!'],
      ['해설', 'Splash! They both fell into the river.'],
      ['흰염소', 'Oh no! The water is cold!'],
      ['검은염소', 'Swim! Swim out!'],
      ['해설', 'The two goats got out. They were all wet.'],
      ['흰염소', 'We did not cross the bridge. We fell in.'],
      ['해설', 'The next day, they met on the bridge again.'],
      ['흰염소', 'I will lie down. Walk over my back.'],
      ['검은염소', 'Really? Thank you!'],
      ['해설', 'The black goat walked over softly.'],
      ['검은염소', 'Thank you, White Goat! Next time, I will lie down.'],
      ['해설', 'When we take turns, we can all go.'],
    ],
  },

  'ae2-miser': {
    title: 'The Old Man and the Gold',
    names: { 해설: 'Narrator', 구두쇠: 'Old Man', 이웃: 'Neighbor' },
    outro: [
      'Was the story interesting?',
      'If you were the Old Man, how would you use the gold?',
      'Do you have something you keep but never use?',
    ],
    lines: [
      ['해설', 'Once upon a time, there was a greedy old man.'],
      ['해설', 'He never spent his money.'],
      ['구두쇠', 'I have a lump of gold! I will hide it.'],
      ['해설', 'He dug a hole under a tree. Dig, dig.'],
      ['해설', 'He put the gold in the hole.'],
      ['구두쇠', 'I will come and look at it every day.'],
      ['해설', 'Every day, he dug it up and looked at it.'],
      ['구두쇠', 'Hee hee! My shiny gold!'],
      ['해설', 'One night, someone took the gold away.'],
      ['구두쇠', 'Oh no! My gold is gone! Boo hoo!'],
      ['해설', 'His neighbor came running.'],
      ['이웃', 'What is wrong?'],
      ['구두쇠', 'Someone took my gold!'],
      ['이웃', 'What did you do with the gold?'],
      ['구두쇠', 'Nothing. I just looked at it.'],
      ['이웃', 'Then put a stone in the hole.'],
      ['이웃', 'You did not use the gold. A stone is the same.'],
      ['구두쇠', 'You are right. I never used my gold.'],
      ['구두쇠', 'From now on, I will share with others.'],
      ['해설', 'Things are useful only when you use them.'],
    ],
  },

  'ae2-horse-donkey': {
    title: 'The Horse and the Donkey',
    names: { 해설: 'Narrator', 말: 'Horse', 당나귀: 'Donkey', 주인: 'Man' },
    outro: [
      'Did you like the story?',
      'If you were the Horse, would you help the Donkey?',
      'When did you share hard work with a friend?',
    ],
    lines: [
      ['해설', 'Once upon a time, a man went on a long trip.'],
      ['해설', 'He took a horse and a donkey.'],
      ['해설', 'The horse had nothing on his back.'],
      ['해설', 'The donkey had many heavy bags.'],
      ['당나귀', 'Oh, this is so heavy!'],
      ['당나귀', 'Horse, can you help me carry some bags?'],
      ['말', 'No! They are your bags. Not mine!'],
      ['해설', 'The donkey walked up the hill. Huff, puff.'],
      ['당나귀', 'I am too tired. I cannot walk.'],
      ['해설', 'The donkey sat down.'],
      ['주인', 'Poor donkey. You need to rest.'],
      ['주인', 'Horse, you will carry all the bags.'],
      ['말', 'What? All of them?'],
      ['해설', 'The horse carried everything. It was so heavy!'],
      ['말', 'I should have helped the donkey before.'],
      ['해설', 'Soon the donkey felt better.'],
      ['당나귀', 'Horse, I can carry some bags now.'],
      ['말', 'I am sorry, Donkey. I was not kind.'],
      ['당나귀', 'That is okay. Let us carry them together.'],
      ['해설', 'Help each other. Then the work is easy.'],
    ],
  },

  'ae2-stag': {
    title: 'The Deer and His Horns',
    names: { 해설: 'Narrator', 사슴: 'Deer', 토끼: 'Rabbit', 사냥개: 'Dog' },
    outro: [
      'Was the story fun?',
      'If you were the Deer, would you like your horns or your legs?',
      'What part of your body are you thankful for?',
    ],
    lines: [
      ['해설', 'Once upon a time, a deer lived in the forest.'],
      ['해설', 'One day, he looked at himself in the water.'],
      ['사슴', 'Look at my horns! They are so pretty!'],
      ['사슴', 'But my legs are so thin. I do not like them.'],
      ['토끼', 'Deer, your legs are great. You are so fast!'],
      ['사슴', 'Fast legs are nothing. My horns are the best.'],
      ['해설', 'Then they heard a sound. Woof, woof!'],
      ['사냥개', 'There is a deer! Let us go!'],
      ['토끼', 'Run, Deer! Run!'],
      ['해설', 'The deer ran fast with his long legs.'],
      ['사냥개', 'He is too fast!'],
      ['해설', 'The deer ran into the forest.'],
      ['해설', 'Oh no! His horns got stuck in a tree.'],
      ['사슴', 'My horns are stuck! I cannot move!'],
      ['해설', 'He pulled and pulled. At last, he got out.'],
      ['해설', 'Then he ran away on his fast legs.'],
      ['사슴', 'Phew! My legs saved me.'],
      ['사슴', 'But my pretty horns got me stuck.'],
      ['토끼', 'See? Your legs are very special.'],
      ['사슴', 'Yes. Now I love my legs, too.'],
      ['해설', 'What looks pretty is not always the most useful.'],
    ],
  },
};
