// 영어 학습용 원고 — 명작 연재 (stories/serial-b.js). 문장은 자체 각색.
// 키 = stories/serial-b.js 의 이야기 id. lines 의 첫 칸은 원래 이야기 cast 의 한국어 이름 그대로.
export default {
  'sb-jungle-1': {
    title: 'The Jungle Book 1: Mowgli',
    names: { 해설: 'Narrator', 모글리: 'Mowgli', 엄마늑대: 'Mother Wolf', 시어칸: 'Shere Khan', 아켈라: 'Akela', 발루: 'Baloo', 바기라: 'Bagheera' },
    outro: [
      'Did you like the first Jungle Book story?',
      'If you were Mowgli, what would you say to Mother Wolf?',
      'Who in your family takes care of you?',
    ],
    lines: [
      ['해설', 'Long ago, a wolf family lived in a big jungle in India.'],
      ['해설', 'One night, a little baby walked to their cave.'],
      ['엄마늑대', 'Oh! A human baby! He is not scared at all.'],
      ['해설', 'Then a big tiger came. It was Shere Khan.'],
      ['시어칸', 'That baby is mine! Give him to me!'],
      ['엄마늑대', 'No! He is our baby now. Go away!'],
      ['해설', 'The cave was too small. Shere Khan could not come in.'],
      ['엄마늑대', 'You look like a little frog. Your name is Mowgli.'],
      ['해설', 'Soon, all the wolves met at the big rock.'],
      ['아켈라', 'I am Akela, the leader. Look at this baby, wolves.'],
      ['시어칸', 'Give me the baby! Wolves do not need a human!'],
      ['아켈라', 'Who will speak for this baby?'],
      ['해설', 'A big, sleepy bear stepped up. It was Baloo.'],
      ['발루', 'I will teach him the Law of the Jungle.'],
      ['해설', 'Then a black panther jumped down from a tree.'],
      ['바기라', 'I am Bagheera. Keep the baby, and I will give you a bull.'],
      ['아켈라', 'Okay. Mowgli is part of our pack now!'],
      ['시어칸', 'Grr! You will be sorry!'],
      ['해설', 'Mowgli grew up with his wolf brothers.'],
      ['모글리', 'Baloo, Bagheera! What will we learn today?'],
      ['발루', 'The Law of the Jungle. But watch out for the monkeys!'],
      ['해설', 'Up in the trees, the monkeys were watching Mowgli.'],
      ['해설', 'Kind hearts can make anyone a family.'],
    ],
  },

  'sb-jungle-2': {
    title: 'The Jungle Book 2: Monkeys',
    names: { 해설: 'Narrator', 모글리: 'Mowgli', 발루: 'Baloo', 바기라: 'Bagheera', 원숭이: 'Monkeys', 카: 'Kaa' },
    outro: [
      'Was the story exciting?',
      'If you were Mowgli, would you play with the monkeys?',
      'Who helps you when you are in trouble?',
    ],
    lines: [
      ['해설', 'Mowgli was a wolf boy now. Baloo taught him every day.'],
      ['발루', 'Say this: We are one blood, you and I!'],
      ['모글리', 'We are one blood, you and I! Why do I learn this?'],
      ['발루', 'With these words, all jungle animals will help you.'],
      ['해설', 'But Mowgli was bored. He yawned and yawned.'],
      ['해설', 'Then the monkeys came down from the trees.'],
      ['원숭이', 'Come and play with us! We play all day!'],
      ['모글리', 'Wow! That sounds fun!'],
      ['해설', 'The monkeys grabbed Mowgli and climbed up, up, up.'],
      ['모글리', 'Too high! Put me down!'],
      ['원숭이', 'Ha ha! You are ours now!'],
      ['해설', 'They took him to an old, broken city.'],
      ['발루', 'Oh no! Bagheera, we are too slow for the monkeys.'],
      ['바기라', 'Monkeys are scared of Kaa, the big snake. Let us ask him.'],
      ['카', 'Sss. The monkeys called me a worm? I will come.'],
      ['해설', 'In the old city, Mowgli saw a bird in the sky.'],
      ['모글리', 'We are one blood, you and I! Tell Baloo where I am!'],
      ['해설', 'The bird flew to Baloo. Baloo’s words helped Mowgli!'],
      ['해설', 'At night, Kaa came. The monkeys screamed and ran away.'],
      ['모글리', 'I am sorry, Baloo. I followed the monkeys.'],
      ['발루', 'It is okay. You remembered the jungle words. Good boy!'],
      ['바기라', 'Choose your friends carefully, little brother.'],
      ['해설', 'Far away, Shere Khan was talking to the young wolves.'],
      ['해설', 'Listen to the friends who really care about you.'],
    ],
  },

  'sb-jungle-3': {
    title: 'The Jungle Book 3: Red Flower',
    names: { 해설: 'Narrator', 모글리: 'Mowgli', 바기라: 'Bagheera', 아켈라: 'Akela', 시어칸: 'Shere Khan', 엄마늑대: 'Mother Wolf', 발루: 'Baloo' },
    outro: [
      'Did you like the last Jungle Book story?',
      'If you were Mowgli, who would you say goodbye to first?',
      'When were you brave?',
    ],
    lines: [
      ['해설', 'Mowgli was a brave jungle boy now. But Akela was getting old.'],
      ['바기라', 'Mowgli, Shere Khan is talking to the young wolves.'],
      ['바기라', 'They want you to leave the jungle.'],
      ['모글리', 'But the wolves are my brothers!'],
      ['바기라', 'Go to the village. Bring the Red Flower. Bring fire.'],
      ['해설', 'At night, Mowgli went to the village.'],
      ['해설', 'He carried home a little pot of hot coals.'],
      ['해설', 'That week, Akela missed a deer. He was too old.'],
      ['해설', 'The wolves met at the big rock. Shere Khan came, too.'],
      ['시어칸', 'Akela is too old! And give me the human boy!'],
      ['아켈라', 'I am old. But Mowgli always helped our pack.'],
      ['모글리', 'Okay. I will go. But first, look at this!'],
      ['해설', 'Mowgli put a dry stick in the fire. Whoosh!'],
      ['해설', 'He held the burning stick up high. The wolves stepped back.'],
      ['모글리', 'Shere Khan, go away! Never come back to our pack!'],
      ['시어칸', 'The Red Flower! Take it away!'],
      ['해설', 'Shere Khan ran far, far away.'],
      ['해설', 'Then tears ran down Mowgli’s face.'],
      ['바기라', 'Those are tears, Mowgli. You are becoming a man.'],
      ['모글리', 'Mother, I will go to the village. But I will come back.'],
      ['엄마늑대', 'Come back any time. We are your family.'],
      ['발루', 'Remember, little brother. We are one blood, you and I!'],
      ['해설', 'Your family’s love goes with you everywhere.'],
    ],
  },

  'sb-heidi-1': {
    title: 'Heidi 1: Up the Mountain',
    names: { 해설: 'Narrator', 하이디: 'Heidi', 데테: 'Aunt Dete', 할아버지: 'Grandfather', 페터: 'Peter', 할머니: 'Grandmother' },
    outro: [
      'Did you enjoy Heidi’s story?',
      'If you were Heidi, what would you do first on the mountain?',
      'How did you feel in a new place?',
    ],
    lines: [
      ['해설', 'Long ago, a little girl named Heidi lived in Switzerland.'],
      ['데테', 'Heidi, I must go away to work. You will live with Grandfather.'],
      ['해설', 'They walked up and up the mountain. Huff, puff!'],
      ['해설', 'Grandfather had a long beard. He did not smile.'],
      ['데테', 'Here is your granddaughter. Now it is your turn!'],
      ['할아버지', 'Hmm. Leave her here.'],
      ['하이디', 'Hello, Grandfather! Can I look inside?'],
      ['하이디', 'Wow, a hay bed! I can see the sky!'],
      ['할아버지', 'Ha ha. I will make it soft for you.'],
      ['해설', 'For dinner, Heidi had warm cheese and goat milk.'],
      ['하이디', 'Yum! This is the best milk!'],
      ['해설', 'In the morning, Peter came with the goats.'],
      ['페터', 'Hi! I am Peter. Come to the meadow with me!'],
      ['해설', 'The meadow had yellow and blue flowers. Heidi jumped and jumped.'],
      ['해설', 'In the evening, the mountains turned red.'],
      ['하이디', 'Peter, look! The mountains are on fire!'],
      ['페터', 'Ha ha! No. The sun is saying good night.'],
      ['해설', 'Heidi visited Peter’s grandmother. She could not see.'],
      ['할머니', 'You sound like a little bird, Heidi.'],
      ['해설', 'Grandfather came and fixed her window. Bang, bang!'],
      ['해설', 'Heidi made Grandfather smile more and more.'],
      ['해설', 'But one day, Aunt Dete came back.'],
      ['데테', 'Heidi, come to the city! A sick girl needs a friend.'],
      ['해설', 'A happy child can warm a lonely heart.'],
    ],
  },

  'sb-heidi-2': {
    title: 'Heidi 2: In the City',
    names: { 해설: 'Narrator', 하이디: 'Heidi', 클라라: 'Clara', 로텐마이어: 'Miss Rottenmeier', 세바스찬: 'Sebastian', 의사: 'Doctor' },
    outro: [
      'What did you think of Heidi in the city?',
      'If you were Clara, what would you say to Heidi?',
      'Have you ever missed your home?',
    ],
    lines: [
      ['해설', 'Heidi went to a big city called Frankfurt.'],
      ['해설', 'There she met Clara. Clara could not walk.'],
      ['클라라', 'Hello, Heidi! Will you be my friend?'],
      ['하이디', 'Yes! But I cannot see the mountains here.'],
      ['로텐마이어', 'Heidi! Sit still at the table!'],
      ['해설', 'Miss Rottenmeier was very strict.'],
      ['해설', 'Heidi put soft white bread in her pocket.'],
      ['하이디', 'This bread is for Peter’s grandmother.'],
      ['해설', 'One day, Heidi brought kittens home. Meow, meow!'],
      ['로텐마이어', 'Kittens! Sebastian, take them away!'],
      ['세바스찬', 'Do not worry, Heidi. I will keep them safe.'],
      ['클라라', 'Ha ha! Every day is fun with you, Heidi!'],
      ['해설', 'Heidi learned to read. But at night, she cried.'],
      ['하이디', 'I miss Grandfather. I miss the goats.'],
      ['해설', 'Then something strange happened. The front door opened every night.'],
      ['세바스찬', 'There is a ghost! We will watch tonight.'],
      ['해설', 'A small girl in white walked down the stairs.'],
      ['의사', 'Heidi? What are you doing here?'],
      ['하이디', 'I was dreaming. I wanted to go to the mountains.'],
      ['의사', 'She misses her home. She must go back now.'],
      ['클라라', 'I will miss you. But I do not want you to be sick.'],
      ['하이디', 'Come to my mountain, Clara! I will show you everything!'],
      ['해설', 'Choo, choo! Heidi’s train went to the mountains.'],
      ['해설', 'When we are far away, we see what is precious.'],
    ],
  },

  'sb-heidi-3': {
    title: 'Heidi 3: Clara Walks',
    names: { 해설: 'Narrator', 하이디: 'Heidi', 할아버지: 'Grandfather', 할머니: 'Grandmother', 클라라: 'Clara', 페터: 'Peter' },
    outro: [
      'Did the story make you happy?',
      'If you were Peter, how would you say sorry?',
      'Did you ever cheer for a friend?',
    ],
    lines: [
      ['해설', 'Heidi was back on the mountain with Grandfather.'],
      ['할아버지', 'Ha ha! My Heidi is home!'],
      ['해설', 'Heidi gave the white bread to Peter’s grandmother.'],
      ['할머니', 'Soft bread! Thank you, Heidi.'],
      ['하이디', 'Grandmother, I can read now. Let me read to you!'],
      ['해설', 'In spring, Clara came up the mountain in her wheelchair.'],
      ['클라라', 'Wow! The sky is so blue!'],
      ['해설', 'But Peter was sad. Heidi always played with Clara.'],
      ['페터', 'Heidi does not play with me now. It is that chair!'],
      ['해설', 'One morning, Peter pushed the empty wheelchair.'],
      ['해설', 'It rolled down the hill. Crash! It broke.'],
      ['클라라', 'My chair! How can I go to the meadow?'],
      ['할아버지', 'Do not worry. I will carry you.'],
      ['해설', 'In the meadow, Heidi held Clara’s hand.'],
      ['하이디', 'Hold my shoulder, Clara. Try one step!'],
      ['클라라', 'My legs shake. But I will try. One step, two steps.'],
      ['해설', 'Peter came and held her other arm.'],
      ['클라라', 'I am walking! Heidi, Peter, I am walking!'],
      ['페터', 'Clara, I pushed your chair. I am so sorry.'],
      ['클라라', 'Thank you for telling me. And now I can walk!'],
      ['해설', 'Clara’s father came. He hugged Clara and cried happy tears.'],
      ['하이디', 'Grandfather, the mountain is the best!'],
      ['해설', 'When we hold hands, hard steps become easy.'],
    ],
  },

  'sb-gulliver-1': {
    title: 'Gulliver 1: Tiny People',
    names: { 해설: 'Narrator', 걸리버: 'Gulliver', 병사: 'Soldier', 꼬마: 'Child', 황제: 'Emperor' },
    outro: [
      'Was Gulliver’s story fun?',
      'If you were Gulliver, what would you say to the tiny people?',
      'Do you take care of someone smaller than you?',
    ],
    lines: [
      ['해설', 'Long ago, Gulliver was a ship doctor in England.'],
      ['해설', 'One day, a big storm hit his ship.'],
      ['해설', 'Gulliver swam to a beach and fell asleep.'],
      ['해설', 'In the morning, he could not move!'],
      ['걸리버', 'What? I am tied down with tiny strings!'],
      ['해설', 'Then a tiny man walked onto his chest.'],
      ['병사', 'The giant is awake! Be careful!'],
      ['해설', 'Tiny arrows flew. They felt like little needles.'],
      ['걸리버', 'Ouch! I will not hurt you. I am just hungry.'],
      ['병사', 'The giant is hungry! Bring bread and meat!'],
      ['해설', 'The tiny people carried food up ladders.'],
      ['걸리버', 'Ha ha! This bread is as small as a bean!'],
      ['꼬마', 'Wow! The giant drank all our water!'],
      ['해설', 'This land was called Lilliput.'],
      ['해설', 'A thousand horses pulled Gulliver to the city.'],
      ['황제', 'Giant, where are you from? Are you here to fight?'],
      ['걸리버', 'No, Your Majesty. A storm brought me here. I want to be friends.'],
      ['황제', 'You talk kindly. But I cannot trust you yet.'],
      ['해설', 'Gulliver stayed in an old temple, with a chain on his leg.'],
      ['꼬마', 'Hello, giant! Can I stand on your hand?'],
      ['걸리버', 'Sure! Come up slowly. You are very brave.'],
      ['걸리버', 'One day, will they let me see their country?'],
      ['해설', 'Big or small, a kind heart feels the same.'],
    ],
  },

  'sb-gulliver-2': {
    title: 'Gulliver 2: The Egg Fight',
    names: { 해설: 'Narrator', 걸리버: 'Gulliver', 황제: 'Emperor', 병사: 'Soldier', 꼬마: 'Child', 렐드레살: 'Reldresal' },
    outro: [
      'Did you like the egg story?',
      'If you were Gulliver, what would you tell the two countries?',
      'Did you ever fight with a friend over a small thing?',
    ],
    lines: [
      ['해설', 'Gulliver lived in Lilliput and learned their words.'],
      ['걸리버', 'Your Majesty, please take off my chain. I will be good.'],
      ['황제', 'First, we must check your pockets.'],
      ['해설', 'Two soldiers climbed into his pocket.'],
      ['병사', 'Your Majesty! There is a big silver box. It goes tick, tock!'],
      ['걸리버', 'Ha ha! That is my watch. It tells the time.'],
      ['황제', 'Here is the rule. Do not step on my people!'],
      ['걸리버', 'I promise. I will watch my feet.'],
      ['해설', 'Clink! The chain came off. Gulliver stretched.'],
      ['꼬마', 'Look! The giant’s shoe is bigger than my house!'],
      ['해설', 'One day, Reldresal came to see Gulliver.'],
      ['렐드레살', 'Gulliver, we have a big problem. It is about eggs.'],
      ['걸리버', 'Eggs? Why are eggs a problem?'],
      ['렐드레살', 'Long ago, we broke eggs on the big end.'],
      ['렐드레살', 'Then the king said, break them on the small end!'],
      ['렐드레살', 'Some people left for the island of Blefuscu.'],
      ['렐드레살', 'Now our two countries fight all the time.'],
      ['걸리버', 'But the eggs taste the same!'],
      ['렐드레살', 'And now Blefuscu has many ships. They want to attack!'],
      ['황제', 'Gulliver, please help us!'],
      ['걸리버', 'I will help. But I will not hurt anyone.'],
      ['해설', 'That night, Gulliver saw fifty tiny ships across the sea.'],
      ['해설', 'Do not fight over little things. Respect different ideas.'],
    ],
  },

  'sb-gulliver-3': {
    title: 'Gulliver 3: Going Home',
    names: { 해설: 'Narrator', 걸리버: 'Gulliver', 꼬마: 'Child', 황제: 'Emperor', 렐드레살: 'Reldresal', 이웃왕: 'King of Blefuscu' },
    outro: [
      'Did you like Gulliver’s last story?',
      'If you were Gulliver, would you say no to the Emperor?',
      'How can you use your strength to help others?',
    ],
    lines: [
      ['해설', 'The Emperor asked Gulliver to stop the Blefuscu ships.'],
      ['걸리버', 'Fifty ropes and fifty hooks. Let us go!'],
      ['해설', 'Gulliver walked into the sea. Splash, splash!'],
      ['해설', 'The Blefuscu sailors saw the giant and ran away.'],
      ['해설', 'Gulliver put a hook on every ship.'],
      ['걸리버', 'Pull, pull! Come with me, little ships!'],
      ['꼬마', 'Wow! The giant brought all the ships!'],
      ['황제', 'Good! Now go and take all of Blefuscu for me!'],
      ['걸리버', 'No, Your Majesty. I will not hurt people.'],
      ['황제', 'Hmph! You will not listen to me?'],
      ['렐드레살', 'Please, Your Majesty. Gulliver stopped the fight.'],
      ['해설', 'Later, the King of Blefuscu invited Gulliver.'],
      ['이웃왕', 'You did not hurt anyone. Thank you, giant.'],
      ['해설', 'One day, Gulliver found a big boat on the beach.'],
      ['걸리버', 'This boat is my size! I can go home!'],
      ['해설', 'Everyone helped him fix the boat.'],
      ['렐드레살', 'Goodbye, Gulliver. Our Emperor wants peace now, too.'],
      ['꼬마', 'Do not forget us, giant!'],
      ['걸리버', 'I will never forget you. Goodbye, my little friends!'],
      ['해설', 'Gulliver put tiny cows and sheep in his pocket.'],
      ['해설', 'He sailed away. Soon he was home in England.'],
      ['걸리버', 'Look, everyone! A cow as small as my thumb!'],
      ['해설', 'A true giant uses his strength for peace.'],
    ],
  },

  'sb-peterpan-1': {
    title: 'Peter Pan 1: Off We Fly',
    names: { 해설: 'Narrator', 피터: 'Peter', 웬디: 'Wendy', 팅커벨: 'Tinker Bell', 존: 'John', 마이클: 'Michael' },
    outro: [
      'Was Peter Pan exciting?',
      'If you were Wendy, would you fly with Peter?',
      'If you could fly, where would you go?',
    ],
    lines: [
      ['해설', 'Long ago in London, Wendy, John, and Michael lived together.'],
      ['해설', 'Their nanny was a big dog named Nana.'],
      ['해설', 'One night, a boy flew in the window.'],
      ['피터', 'Where is my shadow? I left it here!'],
      ['해설', 'He found his shadow. But it did not stick.'],
      ['피터', 'It will not stay on! Boo hoo!'],
      ['웬디', 'Why are you crying? I am Wendy.'],
      ['피터', 'I am Peter Pan. I will never grow up!'],
      ['웬디', 'I can sew your shadow on. It may hurt a little.'],
      ['피터', 'Ha ha! My shadow moves with me!'],
      ['피터', 'Thank you, Wendy! Here is an acorn button for you.'],
      ['해설', 'Ring, ring! A tiny fairy came out. It was Tinker Bell.'],
      ['팅커벨', 'Ring! Who is this girl, Peter? Hmph!'],
      ['존', 'Wow, a real fairy! Peter, how do you fly?'],
      ['피터', 'Think happy thoughts. Then add some fairy dust!'],
      ['마이클', 'Birthday cake! Look, I am flying!'],
      ['웬디', 'Mother will worry. But let us go just once!'],
      ['피터', 'Come to Neverland, Wendy! Tell us stories!'],
      ['해설', 'Nana barked, but the children flew out the window.'],
      ['피터', 'See that star? Second on the right! Fly till morning!'],
      ['존', 'I see an island! Is that Neverland?'],
      ['해설', 'On the island, pirates and a crocodile were waiting.'],
      ['해설', 'Happy thoughts can make your heart fly.'],
    ],
  },

  'sb-peterpan-2': {
    title: 'Peter Pan 2: Wendy’s House',
    names: { 해설: 'Narrator', 피터: 'Peter', 웬디: 'Wendy', 팅커벨: 'Tinker Bell', 투틀스: 'Tootles', 존: 'John', 마이클: 'Michael' },
    outro: [
      'Did you like Wendy’s new house?',
      'If you were Tootles, how would you say sorry?',
      'How do you say sorry to a friend?',
    ],
    lines: [
      ['해설', 'The children flew all night. At last, they came to Neverland.'],
      ['해설', 'There were mermaids, pirates, and a secret house under the ground.'],
      ['피터', 'You go first. I will look for pirates!'],
      ['해설', 'Tinker Bell flew to the Lost Boys.'],
      ['팅커벨', 'Ring, ring! A big bird is coming! Peter says shoot it!'],
      ['투틀스', 'Really? Okay, I will try!'],
      ['해설', 'Tootles shot a toy arrow. Wendy fell down softly.'],
      ['투틀스', 'Oh no! It is not a bird. It is a girl!'],
      ['피터', 'Wendy! She came to tell us stories!'],
      ['해설', 'But the arrow hit the acorn button on her neck.'],
      ['웬디', 'Where am I? I am okay.'],
      ['피터', 'The acorn button saved Wendy! Hooray!'],
      ['투틀스', 'Wendy, I am so sorry.'],
      ['피터', 'Tinker Bell, you told a lie! Go away for a week!'],
      ['팅커벨', 'Ring, ring. I am sorry, Peter. I was jealous.'],
      ['해설', 'The boys built a little house around Wendy. Bang, bang!'],
      ['마이클', 'Let us use John’s hat for the chimney!'],
      ['존', 'My hat? Okay. It is for Wendy.'],
      ['웬디', 'What a pretty house! Thank you, boys!'],
      ['해설', 'Wendy became a mother for the boys. She told stories every night.'],
      ['해설', 'Then they heard a sound. Tick, tock, tick, tock.'],
      ['피터', 'That is the crocodile. He swallowed a clock.'],
      ['피터', 'And Captain Hook is scared of him!'],
      ['해설', 'Say sorry, and a strange place can feel like home.'],
    ],
  },

  'sb-peterpan-3': {
    title: 'Peter Pan 3: Tinker Bell',
    names: { 해설: 'Narrator', 피터: 'Peter', 웬디: 'Wendy', 팅커벨: 'Tinker Bell', 존: 'John', 후크: 'Captain Hook', 스미: 'Smee' },
    outro: [
      'Did you clap for Tinker Bell?',
      'If you were Tinker Bell, what would you do for Peter?',
      'When were you brave for a friend?',
    ],
    lines: [
      ['해설', 'In Neverland, Wendy was a happy mother for the boys.'],
      ['해설', 'On a pirate ship, Captain Hook was angry.'],
      ['후크', 'Peter Pan! One day, I will get that boy!'],
      ['스미', 'Captain, why do you shake at the tick-tock sound?'],
      ['후크', 'Shh! That crocodile follows me everywhere!'],
      ['해설', 'One night, Wendy looked at the stars.'],
      ['웬디', 'Mother and Father are waiting for us.'],
      ['존', 'I cannot remember Mother’s face!'],
      ['웬디', 'Let us go home. Lost Boys, come with us!'],
      ['피터', 'I will not go. I do not want to grow up.'],
      ['해설', 'But pirates were hiding in the forest. They caught the children!'],
      ['스미', 'Captain, we have them all!'],
      ['해설', 'Peter was asleep. Hook put bad medicine in Peter’s cup.'],
      ['팅커벨', 'Ring! Peter, do not drink it! It is bad!'],
      ['피터', 'Wendy gave me that. I will drink it!'],
      ['해설', 'Tinker Bell drank it first. Her light grew dim.'],
      ['팅커벨', 'Peter, children must believe in fairies. Then I can shine.'],
      ['피터', 'Children everywhere! Do you believe in fairies? Clap your hands!'],
      ['해설', 'Clap, clap, clap! Can you clap, too?'],
      ['해설', 'Tinker Bell’s light grew bright again!'],
      ['팅커벨', 'Ring, ring! I can fly! Thank you!'],
      ['피터', 'Let us go save Wendy! Here I come, Hook!'],
      ['해설', 'Good friends are brave for each other.'],
    ],
  },

  'sb-peterpan-4': {
    title: 'Peter Pan 4: Tick-Tock',
    names: { 해설: 'Narrator', 피터: 'Peter', 웬디: 'Wendy', 마이클: 'Michael', 투틀스: 'Tootles', 후크: 'Captain Hook', 스미: 'Smee', 엄마: 'Mother' },
    outro: [
      'Did you like the end of Peter Pan?',
      'If you were Peter, would you grow up or stay in Neverland?',
      'What happy thought do you want to keep forever?',
    ],
    lines: [
      ['해설', 'Peter flew to the pirate ship to save his friends.'],
      ['해설', 'Wendy and the boys were tied to the mast.'],
      ['후크', 'Ha ha! Now you will all be my pirates!'],
      ['마이클', 'No! We are Peter Pan’s friends!'],
      ['해설', 'Then they heard a sound. Tick, tock, tick, tock.'],
      ['후크', 'The crocodile! Hide me! Hurry!'],
      ['해설', 'But it was not the crocodile. It was Peter!'],
      ['해설', 'Peter went into the cabin and hid.'],
      ['스미', 'Captain! Something scary is in the cabin!'],
      ['해설', 'Peter tied up the pirates. Then he set the children free.'],
      ['피터', 'It is me, Peter Pan! Come on, everyone!'],
      ['해설', 'The pirates jumped into the sea. Splash!'],
      ['후크', 'You bad boy! I will catch you!'],
      ['피터', 'Here I am, Hook! Catch me if you can!'],
      ['해설', 'Then a real tick-tock came. The crocodile opened its big mouth!'],
      ['후크', 'A real crocodile! Go away!'],
      ['해설', 'Hook swam far away. Tick, tock! The crocodile followed him.'],
      ['해설', 'The children sailed home to London.'],
      ['엄마', 'Wendy! John! Michael! You are home!'],
      ['투틀스', 'Can we live here, too? We will be good!'],
      ['엄마', 'Of course! You are all my children now.'],
      ['피터', 'I will go back to Neverland. I will visit every spring!'],
      ['웬디', 'Promise, Peter. Let us never forget each other.'],
      ['해설', 'Keep happy thoughts and good friends in your heart forever.'],
    ],
  },
};
