// 영어 학습용 원고 (한국 초등 저학년, 영어 초급). 문장은 자체 각색.
// 키 = stories/*.js 의 이야기 id. lines 의 첫 칸은 원래 이야기 cast 의 한국어 이름 그대로.
// 세계 도시 탐방 2차: 중앙아시아·중동·아프리카 (stories/city-f.js)
export default {
  'ct-ulaanbaatar-1': {
    title: 'Ulaanbaatar, Part 1',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 바타: 'Bata' },
    outro: [
      'Did you enjoy our first day in Ulaanbaatar?',
      'Why did the town move many times?',
      'If your house could move, where would you go?',
    ],
    lines: [
      ['해설', 'Today, Hana and the Guide arrived in Ulaanbaatar.'],
      ['하나', 'The wind is cold! Where are we?'],
      ['안내인', 'We are in Mongolia, in the middle of Asia.'],
      ['안내인', 'The Tuul River flows by the city.'],
      ['안내인', 'Summer is short. Winter is long and very cold.'],
      ['바타', 'Sain baina uu! Welcome to Ulaanbaatar!'],
      ['바타', 'It means hello in Mongolian.'],
      ['안내인', 'In the 1200s, Genghis Khan united the Mongol tribes.'],
      ['안내인', 'In the 1600s, the town began around a big temple.'],
      ['바타', 'It was a town of gers. It moved many times!'],
      ['안내인', 'Later, it stayed near the Tuul River.'],
      ['하나', 'A town that moved? How funny!'],
      ['안내인', 'In 1924, it got the name Ulaanbaatar.'],
      ['안내인', 'It means red hero.'],
      ['바타', 'First, Gandan Monastery. It has a very big Buddha.'],
      ['바타', 'Second, the Winter Palace of the Bogd Khan.'],
      ['안내인', 'Third, Zaisan Hill. You can see the whole city.'],
      ['하나', 'Puff, puff! I see the river and the mountains!'],
      ['해설', 'Ulaanbaatar is Mongolia’s capital. It got its name in 1924.'],
      ['해설', 'Next time, we will learn about its food and life.'],
    ],
  },

  'ct-ulaanbaatar-2': {
    title: 'Ulaanbaatar, Part 2',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 할머니: 'Grandma' },
    outro: [
      'Was our visit to the ger warm and fun?',
      'What three games do people play at Naadam?',
      'What would you do in a ger for one night?',
    ],
    lines: [
      ['해설', 'Last time, Hana learned about the history of Ulaanbaatar.'],
      ['해설', 'Today, a grandma invited her into a ger.'],
      ['하나', 'A round tent house! It is warm inside.'],
      ['할머니', 'Come in. The stove keeps us warm in winter.'],
      ['안내인', 'A ger is made of wood and thick felt.'],
      ['할머니', 'First, try buuz. They are steamed meat dumplings.'],
      ['안내인', 'Many families make lots of buuz for the new year.'],
      ['할머니', 'Next is khuushuur. It is fried meat pastry.'],
      ['하나', 'Crunch, crunch! It is easy to hold.'],
      ['할머니', 'Now drink suutei tsai. It is milk tea with salt.'],
      ['하나', 'Salt in tea? It is different, but yummy!'],
      ['안내인', 'Around July, there is the Naadam festival.'],
      ['안내인', 'People wrestle, race horses, and shoot arrows.'],
      ['할머니', 'Children ride the horses in the races.'],
      ['할머니', 'Do not step on the ger door frame. Step over it.'],
      ['안내인', 'Many people live in apartments in the city center.'],
      ['안내인', 'Many ger homes spread out around the edges.'],
      ['안내인', 'Fun fact! Old Mongolian letters go from top to bottom.'],
      ['하나', 'I want to write like that, too!'],
      ['해설', 'Ulaanbaatar foods are buuz, khuushuur, and suutei tsai.'],
      ['해설', 'In Ulaanbaatar, grassland ways and city life live together.'],
    ],
  },

  'ct-samarkand-1': {
    title: 'Samarkand, Part 1',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 딜노자: 'Dilnoza' },
    outro: [
      'Did you enjoy our first day in Samarkand?',
      'Why did traders come to Samarkand long ago?',
      'What do you want to know about the stars?',
    ],
    lines: [
      ['해설', 'Today, Hana and the Guide came to Samarkand.'],
      ['하나', 'Where is Samarkand?'],
      ['안내인', 'It is in Uzbekistan, in Central Asia.'],
      ['안내인', 'It sits in a green river valley.'],
      ['안내인', 'It is dry and sunny. Summer is hot.'],
      ['딜노자', 'Assalomu alaykum! Welcome to Samarkand!'],
      ['안내인', 'It means peace be with you.'],
      ['안내인', 'Samarkand is more than two thousand years old.'],
      ['안내인', 'Alexander the Great came here long, long ago.'],
      ['안내인', 'Later, it was a big stop on the Silk Road.'],
      ['딜노자', 'Camels carried silk, paper, and spices.'],
      ['안내인', 'In the 1200s, a Mongol army broke the city.'],
      ['안내인', 'In the 1300s, Timur made it his capital.'],
      ['안내인', 'His grandson Ulugh Beg built a place to study stars.'],
      ['하나', 'Grandpa built buildings. Grandson watched stars!'],
      ['딜노자', 'First, Registan Square. Three big old schools face each other.'],
      ['안내인', 'Look at the shiny blue tiles!'],
      ['딜노자', 'Second, Gur-e-Amir. Timur rests there.'],
      ['안내인', 'Third, Ulugh Beg’s star place. A big tool is underground.'],
      ['하나', 'They studied stars with no telescope. Wow!'],
      ['해설', 'Samarkand was a Silk Road stop and Timur’s capital.'],
      ['해설', 'Next time, we will learn about its food and life.'],
    ],
  },

  'ct-samarkand-2': {
    title: 'Samarkand, Part 2',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 요리사: 'Cook' },
    outro: [
      'Was our food trip in Samarkand tasty?',
      'Why don’t people put bread upside down?',
      'How does your family welcome guests?',
    ],
    lines: [
      ['해설', 'Last time, Hana learned about the history of Samarkand.'],
      ['해설', 'Today, she went to a big market.'],
      ['하나', 'Look! A mountain of round bread!'],
      ['요리사', 'This is non. We stamp a pretty pattern in the middle.'],
      ['안내인', 'It bakes on the wall of a clay oven.'],
      ['요리사', 'Bread is special. We never put it upside down.'],
      ['요리사', 'Next is plov. Rice, carrots, lamb, and onions.'],
      ['안내인', 'People often cook it for parties and guests.'],
      ['요리사', 'Third is samsa. It is a baked meat pastry.'],
      ['하나', 'Crispy outside, soft inside!'],
      ['요리사', 'I pour guests a little tea, again and again.'],
      ['요리사', 'It means, please stay longer.'],
      ['안내인', 'Around March 21, people celebrate Navruz, the spring new year.'],
      ['요리사', 'Some cook sweet sumalak and stir it all night.'],
      ['하나', 'All night? My arms would hurt!'],
      ['안내인', 'Some people greet with a hand on the heart.'],
      ['안내인', 'At the bazaar, people sell fruit, nuts, and bread.'],
      ['안내인', 'Fun fact! Registan means a sandy place.'],
      ['안내인', 'Long ago, Samarkand was famous for good paper.'],
      ['해설', 'Samarkand foods are non, plov, and samsa.'],
      ['해설', 'In Samarkand, Silk Road stories live in blue tiles.'],
    ],
  },

  'ct-dubai-1': {
    title: 'Dubai, Part 1',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 라시드: 'Rashid' },
    outro: [
      'Did you enjoy our first day in Dubai?',
      'What did people in old Dubai do in the sea?',
      'How would you keep a house cool on a hot day?',
    ],
    lines: [
      ['해설', 'Today, Hana and the Guide came to Dubai.'],
      ['하나', 'It is so sunny! Where is Dubai?'],
      ['안내인', 'It is in the United Arab Emirates, in West Asia.'],
      ['안내인', 'It is by the sea. The desert is behind it.'],
      ['안내인', 'A long waterway called Dubai Creek comes into the city.'],
      ['안내인', 'Summer is very hot. Winter is warm and nice.'],
      ['라시드', 'Marhaba! Welcome to Dubai!'],
      ['안내인', 'It means welcome in Arabic.'],
      ['안내인', 'Long ago, Dubai was a small fishing village.'],
      ['라시드', 'Divers held their breath and found pearls.'],
      ['안내인', 'In the 1800s, more families came to live by the creek.'],
      ['안내인', 'Boats came and went. It became a busy port.'],
      ['안내인', 'In the 1960s, people found oil under the sea.'],
      ['안내인', 'In 1971, Dubai helped start the United Arab Emirates.'],
      ['라시드', 'First, Al Fahidi. Old houses have wind towers.'],
      ['안내인', 'Wind towers catch the wind and cool the house.'],
      ['라시드', 'Second, the abra. It is a small wooden boat.'],
      ['하나', 'Putt, putt! The sea wind feels cool!'],
      ['안내인', 'Third, Burj Khalifa. It almost touches the clouds.'],
      ['하나', 'I can’t see the top!'],
      ['해설', 'Dubai grew from a pearl village. It joined the UAE in 1971.'],
      ['해설', 'Next time, we will learn about its food and life.'],
    ],
  },

  'ct-dubai-2': {
    title: 'Dubai, Part 2',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 상인: 'Seller' },
    outro: [
      'Was our food trip in Dubai sweet?',
      'What do you do with your cup when you finish coffee?',
      'What would you share with friends from other countries?',
    ],
    lines: [
      ['해설', 'Last time, Hana learned about the history of Dubai.'],
      ['해설', 'Today, she went to an old market called a souk.'],
      ['하나', 'The spices tickle my nose!'],
      ['상인', 'Welcome! Have some dates and Arabic coffee.'],
      ['안내인', 'Dates and coffee are an old way to say welcome.'],
      ['상인', 'The coffee has cardamom. We use tiny cups.'],
      ['상인', 'Done? Shake your cup a little. That means no more.'],
      ['하나', 'Shaking a cup is fun!'],
      ['상인', 'This is machboos. Spicy rice with meat or fish.'],
      ['안내인', 'People often share it from a big plate.'],
      ['상인', 'For dessert, luqaimat! Fried dough balls with date syrup.'],
      ['하나', 'Crunchy, fluffy, and sweet!'],
      ['안내인', 'In Ramadan, Muslims do not eat in the daytime.'],
      ['안내인', 'December 2 is the country’s birthday. Flags are everywhere.'],
      ['상인', 'Use your right hand to eat and give things.'],
      ['안내인', 'People from many countries live in Dubai.'],
      ['안내인', 'You can hear Arabic, English, and many other languages.'],
      ['상인', 'Near the creek, there are gold and spice markets.'],
      ['안내인', 'Fun fact! The falcon is a symbol of the UAE.'],
      ['안내인', 'There are even hospitals for falcons.'],
      ['해설', 'Dubai foods are machboos, luqaimat, dates, and coffee.'],
      ['해설', 'In Dubai, desert and sea, old and new, meet.'],
    ],
  },

  'ct-marrakech-1': {
    title: 'Marrakech, Part 1',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 이야기꾼: 'Storyteller' },
    outro: [
      'Did you enjoy our first day in Marrakech?',
      'Why is Marrakech called the Red City?',
      'If you were a storyteller, what story would you tell?',
    ],
    lines: [
      ['해설', 'Today, Hana and the Guide arrived in Marrakech.'],
      ['하나', 'The houses and walls are all red!'],
      ['안내인', 'That is why people call it the Red City.'],
      ['안내인', 'It is in Morocco, in North Africa.'],
      ['안내인', 'The Atlas Mountains are near the city.'],
      ['안내인', 'It is dry. Summer is hot, and winter is mild.'],
      ['이야기꾼', 'Salam alaikum! Welcome to the Red City!'],
      ['안내인', 'It means peace be with you in Arabic.'],
      ['안내인', 'In the Amazigh language, people also say azul.'],
      ['이야기꾼', 'A kingdom built this city in the 1000s.'],
      ['안내인', 'Traders stopped here on the way across the desert.'],
      ['이야기꾼', 'In the 1100s, people built the tall Koutoubia tower.'],
      ['안내인', 'In the 1500s, it became a capital again.'],
      ['이야기꾼', 'People say the name Morocco comes from Marrakech.'],
      ['하나', 'A city name became a country name. Wow!'],
      ['이야기꾼', 'First, Jemaa el-Fnaa Square. I tell stories there.'],
      ['안내인', 'At night, food stalls fill the square.'],
      ['하나', 'Boom, boom! I hear drums and flutes!'],
      ['이야기꾼', 'Second, the Koutoubia Mosque. Its tall tower shows the way.'],
      ['안내인', 'Third, Bahia Palace. It has colorful tiles and wood.'],
      ['해설', 'Marrakech is the Red City. It began in the 1000s.'],
      ['해설', 'Next time, we will learn about its food and life.'],
    ],
  },

  'ct-marrakech-2': {
    title: 'Marrakech, Part 2',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 요리사: 'Cook' },
    outro: [
      'Was our food trip in Marrakech yummy?',
      'Is tagine the name of a pot or a food?',
      'What would you like to buy at the market?',
    ],
    lines: [
      ['해설', 'Last time, Hana learned about the history of Marrakech.'],
      ['해설', 'Today, she walked into the twisty market streets.'],
      ['하나', 'It is like a maze!'],
      ['안내인', 'Carts and donkeys go through these narrow streets.'],
      ['요리사', 'Welcome! First, try tagine.'],
      ['요리사', 'Tagine is a clay pot with a pointy lid.'],
      ['안내인', 'Meat and vegetables cook slowly inside.'],
      ['요리사', 'Use bread and your right hand to eat it.'],
      ['하나', 'The bread is my spoon!'],
      ['요리사', 'Second is couscous. It is tiny steamed bits of wheat.'],
      ['안내인', 'Many families eat couscous together on Fridays.'],
      ['요리사', 'Third is tanjia. It is meat cooked in a clay jar.'],
      ['안내인', 'Some cook it in the warm ashes of a bathhouse fire.'],
      ['하나', 'Cooking with a bathhouse fire? Amazing!'],
      ['요리사', 'Now, mint tea. I pour it from high up.'],
      ['안내인', 'At the market, people often talk about the price.'],
      ['안내인', 'You can hear Arabic, Amazigh, and French here.'],
      ['안내인', 'November 18 is Morocco’s Independence Day.'],
      ['안내인', 'Craftspeople make leather shoes, lamps, and rugs by hand.'],
      ['하나', 'Pointy leather shoes! They are called babouches.'],
      ['안내인', 'Fun fact! The square’s storytellers are a world treasure.'],
      ['해설', 'Marrakech foods are tagine, couscous, and tanjia.'],
      ['해설', 'Marrakech is full of old stories and busy markets.'],
    ],
  },

  'ct-nairobi-1': {
    title: 'Nairobi, Part 1',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 관리인: 'Ranger' },
    outro: [
      'Did you enjoy our first day in Nairobi?',
      'How did Nairobi begin?',
      'Which wild animal would you like to see up close?',
    ],
    lines: [
      ['해설', 'Today, Hana and the Guide arrived in Nairobi.'],
      ['안내인', 'Nairobi is the capital of Kenya, in East Africa.'],
      ['안내인', 'It is a little south of the equator.'],
      ['하나', 'Then it must be very hot!'],
      ['안내인', 'It is high up, so it is cooler than you think.'],
      ['관리인', 'Jambo! Welcome to Nairobi!'],
      ['안내인', 'Jambo means hello in Swahili.'],
      ['안내인', 'People say Nairobi means cool water in the Maasai language.'],
      ['안내인', 'In 1899, a railway station was built here.'],
      ['안내인', 'The railway went from the sea to inland Africa.'],
      ['안내인', 'The station town grew fast.'],
      ['하나', 'A city began at a train station!'],
      ['안내인', 'In 1963, Kenya became free. Nairobi became its capital.'],
      ['관리인', 'Later, a UN office for nature came here, too.'],
      ['관리인', 'First, Nairobi National Park. I protect animals there.'],
      ['하나', 'I see giraffes and tall buildings together!'],
      ['관리인', 'Second, a home for baby elephants.'],
      ['하나', 'The baby drinks milk from a big bottle!'],
      ['안내인', 'Third, the Giraffe Centre. You can meet giraffes up close.'],
      ['하나', 'Its tongue is so long and dark!'],
      ['해설', 'Nairobi began in 1899. It became Kenya’s capital in 1963.'],
      ['해설', 'Next time, we will learn about its food and life.'],
    ],
  },

  'ct-nairobi-2': {
    title: 'Nairobi, Part 2',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 아마니: 'Amani' },
    outro: [
      'Was our day with Amani fun?',
      'What does the name sukuma wiki mean?',
      'Where would you plant a tree in your town?',
    ],
    lines: [
      ['해설', 'Last time, Hana learned about the history of Nairobi.'],
      ['해설', 'Today, she visited her friend Amani.'],
      ['아마니', 'Jambo, Hana! Let’s eat lunch together.'],
      ['아마니', 'This is ugali. It is made from corn flour.'],
      ['안내인', 'Roll a little ball with your hand. Scoop up some food.'],
      ['아마니', 'These greens are sukuma wiki.'],
      ['안내인', 'People say the name means stretch the week.'],
      ['아마니', 'On weekends, we eat nyama choma. It is grilled meat.'],
      ['하나', 'Sizzle, sizzle! I am hungry already!'],
      ['안내인', 'Many groups of people live in Kenya.'],
      ['안내인', 'People speak Swahili and English.'],
      ['아마니', 'December 12 is Jamhuri Day. It is a national holiday.'],
      ['안내인', 'People shake hands and ask, how are you?'],
      ['아마니', 'I wear a uniform and ride a matatu to school.'],
      ['안내인', 'A matatu is a small bus. Some have bright pictures.'],
      ['하나', 'A bus with pictures! I want to ride one!'],
      ['아마니', 'Maasai beadwork colors have special meanings.'],
      ['안내인', 'Fun fact! Kenya is famous for long-distance runners.'],
      ['안내인', 'Wangari Maathai from Kenya led a tree-planting movement.'],
      ['안내인', 'She won the Nobel Peace Prize in 2004.'],
      ['하나', 'I want to plant a tree, too!'],
      ['해설', 'Nairobi foods are ugali, sukuma wiki, and nyama choma.'],
      ['해설', 'In Nairobi, people, animals, and cultures live together.'],
    ],
  },
};
