// 영어 학습용 원고: 세계 도시 탐방 2차 (유럽). 문장은 자체 집필.
// 키 = stories/city-g.js 의 이야기 id. lines 의 첫 칸은 한국어 cast 이름 그대로.
export default {
  'ct-amsterdam-1': {
    title: 'Amsterdam, Part 1',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 얀: 'Jan' },
    outro: [
      'Did you enjoy our first day in Amsterdam?',
      'Why did people build a dam on the Amstel River?',
      'If you built a house on the water, what would it look like?',
    ],
    lines: [
      ['해설', 'Hana and the Guide arrived in Amsterdam.'],
      ['하나', 'Look! There are canals everywhere!'],
      ['안내인', 'Amsterdam is the capital of the Netherlands.'],
      ['안내인', 'The Amstel River flows here. The North Sea is near.'],
      ['안내인', 'The land is very flat. Some land is lower than the sea.'],
      ['해설', 'It is windy, and it rains often all year.'],
      ['얀', 'Hallo! I am Jan. Hallo means hello.'],
      ['안내인', 'Let’s learn about the history of Amsterdam.'],
      ['안내인', 'In the 1200s, there was a small fishing village here.'],
      ['안내인', 'People built a dam on the Amstel River.'],
      ['해설', 'The name Amsterdam comes from the dam on the Amstel.'],
      ['안내인', 'In the 1600s, ships sailed all the way to Asia.'],
      ['안내인', 'The city grew rich. People call it the Golden Age.'],
      ['해설', 'People dug rings of canals around the city.'],
      ['안내인', 'The painter Rembrandt worked here in those days.'],
      ['해설', 'Then they visited three famous places.'],
      ['얀', 'First, the canal ring! It is a World Heritage Site.'],
      ['안내인', 'Second, the national art museum. It has Rembrandt’s Night Watch.'],
      ['얀', 'Third, the Anne Frank House.'],
      ['안내인', 'In the war, a girl named Anne hid here. She wrote a diary.'],
      ['해설', 'Amsterdam began with a dam on the Amstel River.'],
      ['해설', 'It grew big with canals in the Golden Age.'],
    ],
  },

  'ct-amsterdam-2': {
    title: 'Amsterdam, Part 2',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 상인: 'Seller', 얀: 'Jan' },
    outro: [
      'Was our sweet trip in Amsterdam fun?',
      'Why do the canal houses have hooks at the top?',
      'Where would you go by bike in your town?',
    ],
    lines: [
      ['해설', 'Last time, Hana learned about the history of Amsterdam.'],
      ['해설', 'Today, she went to a street market with Jan.'],
      ['상인', 'Welcome! Try a warm stroopwafel!'],
      ['하나', 'Two thin cookies are stuck together!'],
      ['상인', 'There is sweet, sticky syrup between two thin waffles.'],
      ['얀', 'Put it on top of a warm drink. The syrup gets soft.'],
      ['안내인', 'This is herring. It is lightly salted raw fish.'],
      ['얀', 'Add chopped onions. Some people hold the tail and eat it!'],
      ['상인', 'Third, poffertjes! They are tiny pancakes.'],
      ['안내인', 'Eat them with butter and lots of powdered sugar.'],
      ['안내인', 'In late April, there is King’s Day. People wear orange.'],
      ['얀', 'Anyone can sell old things on the street that day.'],
      ['안내인', 'Around December 5, children get presents from Sinterklaas.'],
      ['하나', 'How do people get around here?'],
      ['안내인', 'By bike! There are bike lanes all over the city.'],
      ['얀', 'The land is flat, so kids and grandmas ride. Ring, ring!'],
      ['하나', 'Tell me something fun!'],
      ['안내인', 'The canal houses are narrow and tall, with hooks on top.'],
      ['얀', 'The stairs are narrow. People lift big sofas through windows!'],
      ['해설', 'Today, Hana learned about stroopwafels, herring, and poffertjes.'],
      ['해설', 'Amsterdam is a city of bikes and canals.'],
    ],
  },

  'ct-vienna-1': {
    title: 'Vienna, Part 1',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 레나: 'Lena' },
    outro: [
      'Did you enjoy our first day in Vienna?',
      'Why did so many famous musicians come to Vienna?',
      'What music or instrument do you like?',
    ],
    lines: [
      ['해설', 'Hana and the Guide arrived in Vienna.'],
      ['안내인', 'Vienna is the capital of Austria, in the middle of Europe.'],
      ['안내인', 'The Danube River flows by the city.'],
      ['안내인', 'To the west, there is a big forest on the hills.'],
      ['해설', 'Vienna has four seasons. Winter is quite cold.'],
      ['레나', 'Gruss Gott! I am Lena. It means hello.'],
      ['안내인', 'People in Austria speak German.'],
      ['안내인', 'About two thousand years ago, the Romans built a camp here.'],
      ['안내인', 'From the late 1200s, the Habsburg family ruled Austria.'],
      ['안내인', 'They ruled from Vienna for hundreds of years.'],
      ['안내인', 'In 1683, a big army surrounded Vienna. But the city held on.'],
      ['해설', 'From the 1700s, many famous musicians came to Vienna.'],
      ['레나', 'Mozart and Beethoven lived and made music here!'],
      ['안내인', 'In 1918, the empire ended. Austria became a republic.'],
      ['해설', 'Then they visited three famous places.'],
      ['레나', 'First, Schonbrunn Palace! The royal family spent summers here.'],
      ['안내인', 'It has a big garden. It is a World Heritage Site.'],
      ['레나', 'Second, St. Stephen’s Cathedral. Its roof has colorful tiles.'],
      ['안내인', 'Third, the giant Ferris wheel. It was built in 1897.'],
      ['하나', 'It is over one hundred years old! I want to ride it!'],
      ['해설', 'Vienna is the capital of Austria, by the Danube River.'],
      ['해설', 'The Habsburgs ruled here, and Mozart lived here.'],
    ],
  },

  'ct-vienna-2': {
    title: 'Vienna, Part 2',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 요리사: 'Cook', 레나: 'Lena' },
    outro: [
      'Was our food trip in Vienna tasty?',
      'Why do people in Vienna like to sit long in cafes?',
      'Have you ever danced or gone to a concert with your family?',
    ],
    lines: [
      ['해설', 'Last time, Hana learned about the history of Vienna.'],
      ['해설', 'Today, she went to an old restaurant with Lena.'],
      ['요리사', 'Welcome! Today we have Wiener schnitzel.'],
      ['요리사', 'I make the meat thin. Then I fry it in breadcrumbs.'],
      ['레나', 'Squeeze lemon on it. Eat it with potato salad.'],
      ['요리사', 'For dessert, try apple strudel.'],
      ['안내인', 'Thin dough is rolled up with apples and cinnamon.'],
      ['요리사', 'And this is Kaiserschmarrn. It is a torn, fluffy pancake.'],
      ['안내인', 'Kaiser means emperor. Eat it with sugar and plum jam.'],
      ['안내인', 'Vienna has many old cafes. Coffee often comes with water.'],
      ['레나', 'Grown-ups read newspapers there for a long time.'],
      ['안내인', 'In January and February, there are many big dances called balls.'],
      ['레나', 'People dance the waltz. Round and round they go!'],
      ['안내인', 'On January 1, there is a New Year concert.'],
      ['하나', 'How do people get around here?'],
      ['안내인', 'Red and white trams and the subway connect the city.'],
      ['하나', 'Tell me something fun!'],
      ['안내인', 'Vienna has vineyards inside the city.'],
      ['안내인', 'And the palace has a very old zoo. It opened in 1752.'],
      ['해설', 'Today, Hana learned about schnitzel, apple strudel, and Kaiserschmarrn.'],
      ['해설', 'Vienna is a city of music, cafes, and vineyards.'],
    ],
  },

  'ct-prague-1': {
    title: 'Prague, Part 1',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 토마시: 'Tomas' },
    outro: [
      'Did you enjoy our first day in Prague?',
      'Why was it special that the two countries split peacefully?',
      'What kind of special clock would you like in your room?',
    ],
    lines: [
      ['해설', 'Hana and the Guide arrived in Prague.'],
      ['하나', 'Wow! There are so many pointy towers!'],
      ['안내인', 'People call Prague the city of a hundred spires.'],
      ['안내인', 'Prague is the capital of the Czech Republic.'],
      ['안내인', 'The Vltava River flows through the city.'],
      ['해설', 'Prague has four seasons. Winter is cold and snowy.'],
      ['토마시', 'Dobry den! I am Tomas. It means good day.'],
      ['해설', 'An old legend says a princess saw a great city here.'],
      ['안내인', 'In the 800s, people began building Prague Castle on a hill.'],
      ['안내인', 'In the 1300s, King Charles the Fourth made Prague grand.'],
      ['안내인', 'In 1348, he started a university. Then he began a stone bridge.'],
      ['토마시', 'That is Charles Bridge! It has his name.'],
      ['안내인', 'In 1989, people changed the country peacefully.'],
      ['안내인', 'In 1993, the Czech Republic and Slovakia split peacefully.'],
      ['해설', 'Then they visited three famous places.'],
      ['토마시', 'First, Prague Castle! You can see red roofs everywhere.'],
      ['토마시', 'Second, Charles Bridge. Statues stand on both sides.'],
      ['안내인', 'Third, the old clock in the square. It is from the early 1400s.'],
      ['해설', 'Every hour, little windows open and figures move past.'],
      ['하나', 'Tick, tock! The figures look like they are waving!'],
      ['해설', 'Prague is the capital of the Czech Republic, on the Vltava.'],
      ['해설', 'It grew under Charles the Fourth. It has towers, bridges, and a clock.'],
    ],
  },

  'ct-prague-2': {
    title: 'Prague, Part 2',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 할아버지: 'Grandpa', 토마시: 'Tomas' },
    outro: [
      'Was our dinner in Prague tasty?',
      'Why do so many people touch the statue on Charles Bridge?',
      'If you made a puppet show, who would be the hero?',
    ],
    lines: [
      ['해설', 'Last time, Hana learned about the history of Prague.'],
      ['해설', 'Today, she visited Tomas’s grandpa for dinner.'],
      ['할아버지', 'Welcome! Please take off your shoes in our house.'],
      ['토마시', 'Here are some slippers for you!'],
      ['할아버지', 'Tonight we have svickova. It is beef with a creamy sauce.'],
      ['안내인', 'The sauce is made with root vegetables like carrots.'],
      ['토마시', 'These white slices are knedliky. They are dumplings.'],
      ['하나', 'They are soft and soak up the sauce!'],
      ['안내인', 'People also eat goulash. It is a red meat stew.'],
      ['할아버지', 'For dessert, kolache! Round buns with jam or poppy seeds.'],
      ['안내인', 'Czech people have a long history of string puppets.'],
      ['토마시', 'Pull the strings, and the puppets dance!'],
      ['안내인', 'On the evening of December 5, Saint Mikulas visits.'],
      ['할아버지', 'An angel and a devil come with him.'],
      ['안내인', 'On Christmas Eve, many families eat carp.'],
      ['토마시', 'We ride trams and the subway. Walking is fun, too.'],
      ['하나', 'Tell me something fun!'],
      ['토마시', 'Touch a statue plate on Charles Bridge. People say it brings luck.'],
      ['안내인', 'So many people touch it that it shines.'],
      ['해설', 'Today, Hana learned about svickova, knedliky, goulash, and kolache.'],
      ['해설', 'Prague is a city of towers, stories, and puppets.'],
    ],
  },

  'ct-venice-1': {
    title: 'Venice, Part 1',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 줄리아: 'Giulia' },
    outro: [
      'Did you enjoy our first day in Venice?',
      'Why did people long ago move to the small islands?',
      'If you lived on an island, how would you go to school?',
    ],
    lines: [
      ['해설', 'Hana and the Guide arrived in Venice by boat.'],
      ['하나', 'Look! There are canals instead of roads!'],
      ['안내인', 'Venice is in northeast Italy, by the Adriatic Sea.'],
      ['안내인', 'It is built on more than one hundred small islands.'],
      ['해설', 'Canals and bridges connect the islands.'],
      ['해설', 'Summer is hot. In winter, there can be fog and high water.'],
      ['줄리아', 'Ciao! I am Giulia. Ciao means hi.'],
      ['안내인', 'The word ciao first came from old Venice.'],
      ['안내인', 'About fifteen hundred years ago, people moved to these islands.'],
      ['안내인', 'Later, Venice chose its own leader, called the Doge.'],
      ['해설', 'The Republic of Venice lasted about one thousand years.'],
      ['안내인', 'Venice traded with far countries by ship and grew rich.'],
      ['줄리아', 'Marco Polo was from Venice! He traveled to Asia.'],
      ['안내인', 'In 1797, the republic ended. Later, Venice joined Italy.'],
      ['해설', 'Then they visited three famous places.'],
      ['줄리아', 'First, St. Mark’s Square! The church has gold mosaics.'],
      ['안내인', 'Second, the Rialto Bridge. It is an old stone bridge.'],
      ['하나', 'There are shops on the bridge!'],
      ['안내인', 'Third, the Doge’s Palace. The Doge lived and ruled there.'],
      ['하나', 'The whole city looks like a museum on water!'],
      ['해설', 'Venice is a city built on islands in Italy.'],
      ['해설', 'Its republic grew rich by sea trade for about a thousand years.'],
    ],
  },

  'ct-venice-2': {
    title: 'Venice, Part 2',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 줄리아: 'Giulia', 사공: 'Gondolier' },
    outro: [
      'Was our boat trip in Venice exciting?',
      'With no cars, how do people in Venice carry heavy things?',
      'If you made a carnival mask, what colors would you use?',
    ],
    lines: [
      ['해설', 'Last time, Hana learned about the history of Venice.'],
      ['해설', 'Today, she went to a small place by a canal.'],
      ['줄리아', 'These are cicchetti. They are small bites of food.'],
      ['안내인', 'Many are bread with fish or vegetables on top.'],
      ['줄리아', 'This is sarde in saor. Fried sardines with onions and vinegar.'],
      ['안내인', 'It is sweet and sour. Sailors liked it long ago.'],
      ['하나', 'What is this black rice?'],
      ['줄리아', 'It is risotto with cuttlefish ink! The ink makes it black.'],
      ['안내인', 'In February, there is a carnival. People wear fancy masks.'],
      ['줄리아', 'I wore a shiny mask. Nobody knew it was me!'],
      ['안내인', 'In September, old boats race on the Grand Canal.'],
      ['사공', 'Want a gondola ride? I stand and row with one oar.'],
      ['하나', 'Only one oar, but the boat goes straight!'],
      ['사공', 'The two sides of a gondola are a little different.'],
      ['하나', 'Do people drive cars here?'],
      ['안내인', 'No roads for cars here. People walk or take water buses.'],
      ['줄리아', 'Ambulances are boats, too. Putt, putt, putt!'],
      ['하나', 'Tell me something fun!'],
      ['안내인', 'The buildings stand on wooden poles in the mud.'],
      ['안내인', 'Wood under water does not rot easily.'],
      ['해설', 'Today, Hana learned about cicchetti, sardines, ink risotto, and gondolas.'],
      ['해설', 'In Venice, boats are the buses!'],
    ],
  },

  'ct-lisbon-1': {
    title: 'Lisbon, Part 1',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 마리아: 'Maria' },
    outro: [
      'Did you enjoy our first day in Lisbon?',
      'How did people build Lisbon again after the earthquake?',
      'If you sailed to a faraway land, where would you go?',
    ],
    lines: [
      ['해설', 'Hana and the Guide arrived in Lisbon.'],
      ['하나', 'So many hills! Up, up, up!'],
      ['안내인', 'Lisbon is called the city of seven hills.'],
      ['안내인', 'It is the capital of Portugal, at the west end of Europe.'],
      ['안내인', 'Here, the Tagus River meets the Atlantic Ocean.'],
      ['해설', 'Lisbon is sunny. Winter is not very cold.'],
      ['마리아', 'Bom dia! I am Maria. It means good morning.'],
      ['안내인', 'Lisbon is very old. The Romans called it Olisipo.'],
      ['안내인', 'In 1147, the first king of Portugal took the city.'],
      ['안내인', 'In the 1400s and 1500s, big ships sailed from Lisbon.'],
      ['해설', 'In 1498, Vasco da Gama’s ships reached India by sea.'],
      ['안내인', 'In 1755, a big earthquake hit the city.'],
      ['안내인', 'People built straight streets and strong buildings again.'],
      ['안내인', 'In 1974, the country changed without a big fight.'],
      ['마리아', 'People put carnations in soldiers’ guns. It was the Carnation Revolution.'],
      ['해설', 'Then they visited three famous places.'],
      ['마리아', 'First, Belem Tower! It is a white stone tower by the river.'],
      ['마리아', 'Second, Jeronimos Monastery. It has stone ropes and shells.'],
      ['안내인', 'Both are World Heritage Sites.'],
      ['마리아', 'Third, Saint George Castle. You can see the whole city!'],
      ['해설', 'Lisbon is the capital of Portugal, where the river meets the sea.'],
      ['해설', 'Ships sailed far from here. The city came back after 1755.'],
    ],
  },

  'ct-lisbon-2': {
    title: 'Lisbon, Part 2',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 제빵사: 'Baker', 마리아: 'Maria' },
    outro: [
      'Was our food trip in Lisbon sweet and tasty?',
      'How do people in Lisbon go up the steep hills?',
      'If you painted a wall in your town, what would you paint?',
    ],
    lines: [
      ['해설', 'Last time, Hana learned about the history of Lisbon.'],
      ['해설', 'Today, she went to a bakery with Maria.'],
      ['제빵사', 'Bom dia! Try a warm pastel de nata!'],
      ['하나', 'It is a little tart with yellow cream!'],
      ['제빵사', 'Egg cream goes in crispy pastry. I bake it very hot.'],
      ['안내인', 'People say monks in Belem made them first.'],
      ['하나', 'Obrigada! That means thank you, right?'],
      ['제빵사', 'Yes! Girls say obrigada. Boys say obrigado.'],
      ['마리아', 'This is bacalhau. It is salted, dried cod.'],
      ['안내인', 'Soak it in water first. People say there are hundreds of recipes.'],
      ['안내인', 'In June, there is a big festival. People grill sardines.'],
      ['마리아', 'We put grilled sardines on bread. Yum!'],
      ['안내인', 'Lisbon has a kind of song called fado. It sounds a little sad.'],
      ['안내인', 'Look at the walls. They have painted tiles called azulejos.'],
      ['마리아', 'Many tiles are blue and white. They shine in the sun!'],
      ['하나', 'How do people go up the steep hills?'],
      ['안내인', 'Yellow trams climb the narrow streets. Clang, clang!'],
      ['마리아', 'There is an iron elevator over one hundred years old!'],
      ['하나', 'Tell me something fun!'],
      ['안내인', 'The sidewalks have little white and black stones in patterns.'],
      ['마리아', 'Some look like waves. It feels like walking on the sea!'],
      ['해설', 'Today, Hana learned about pastel de nata, bacalhau, sardines, and fado.'],
      ['해설', 'Lisbon is a city by the sea, with trams on its hills.'],
    ],
  },
};
