// 영어 학습용 원고 (한국 초등 저학년, 영어 초급). 문장은 자체 각색.
// 키 = stories/aesop3.js 의 이야기 id. lines 의 첫 칸은 원래 이야기 cast 의 한국어 이름 그대로.
export default {
  'ae3-wolf-lamb': {
    title: 'The Wolf and the Lamb',
    names: { 해설: 'Narrator', 늑대: 'Wolf', 아기양: 'Lamb', 양치기: 'Shepherd' },
    outro: [
      'Did you like the story?',
      'If you were the Lamb, what would you say to the Wolf?',
      'What can you do when someone is unfair?',
    ],
    lines: [
      ['해설', 'Once upon a time, a little lamb drank from a stream.'],
      ['해설', 'Lap, lap. The water was cool and good.'],
      ['해설', 'Up the stream, a hungry wolf came.'],
      ['늑대', 'Hey, little lamb! You made my water dirty!'],
      ['아기양', 'But the water runs from you to me.'],
      ['아기양', 'I cannot make your water dirty.'],
      ['늑대', 'Hmm. Then you said bad things to me last year!'],
      ['아기양', 'I was not born last year.'],
      ['늑대', 'Then it was your brother!'],
      ['아기양', 'I do not have a brother.'],
      ['늑대', 'Be quiet! I will get you anyway!'],
      ['해설', 'The wolf only wanted to be mean.'],
      ['아기양', 'He will not listen. I must run!'],
      ['해설', 'Baa, baa! The lamb ran into the field.'],
      ['양치기', 'Go away, Wolf! Leave my lamb alone!'],
      ['해설', 'The shepherd ran with his stick. His dog barked, woof!'],
      ['늑대', 'Oh no, the shepherd! Run, run!'],
      ['해설', 'The wolf ran far into the forest.'],
      ['아기양', 'Thank you. I was so scared.'],
      ['양치기', 'Do not argue with a bully. Ask for help.'],
      ['해설', 'The lamb went back to her mother.'],
      ['해설', 'Some bullies do not listen. Then ask a grown-up for help.'],
    ],
  },

  'ae3-vineyard': {
    title: 'The Treasure in the Vineyard',
    names: { 해설: 'Narrator', 아버지: 'Father', 큰아들: 'Big Son', 작은아들: 'Little Son' },
    outro: [
      'Was the story fun?',
      'If you were the sons, how would you feel with no treasure?',
      'When did hard work give you something good?',
    ],
    lines: [
      ['해설', 'Once upon a time, a farmer had a grape field.'],
      ['해설', 'He had two sons. They did not like to work.'],
      ['큰아들', 'Yawn. I want to take a nap.'],
      ['작은아들', 'Me too! Farm work is too hard.'],
      ['해설', 'The father grew old. One day, he got sick.'],
      ['아버지', 'Boys, come here. There is treasure in our field.'],
      ['큰아들', 'Treasure? Where is it?'],
      ['아버지', 'I forgot. You must find it.'],
      ['작은아들', 'Let us go dig right now!'],
      ['해설', 'The sons dug and dug. Dig, dig, dig!'],
      ['큰아들', 'Not here. Let us dig over there!'],
      ['해설', 'They dug every day until the sun went down.'],
      ['해설', 'But they did not find any treasure box.'],
      ['작은아들', 'There is no treasure. We worked for nothing.'],
      ['해설', 'Then autumn came. Something wonderful happened.'],
      ['해설', 'The vines were full of big, sweet grapes!'],
      ['큰아들', 'Wow! So many grapes!'],
      ['해설', 'The soft soil helped the vines grow.'],
      ['해설', 'The sons sold the grapes and got lots of money.'],
      ['아버지', 'Now you see. Hard work is the real treasure.'],
      ['큰아들', 'Yes, Father. We will work hard now.'],
      ['해설', 'When you work hard, your work becomes a treasure.'],
    ],
  },

  'ae3-fox-lion': {
    title: 'The Fox Who Met a Lion',
    names: { 해설: 'Narrator', 여우: 'Fox', 사자: 'Lion' },
    outro: [
      'Did you enjoy the story?',
      'If you were the Fox, how would you say hello?',
      'What was scary at first but okay later?',
    ],
    lines: [
      ['해설', 'Once upon a time, a little fox lived in the forest.'],
      ['해설', 'She had never seen a lion.'],
      ['해설', 'One day, a big lion walked by.'],
      ['사자', 'Roar! What a sunny day!'],
      ['여우', 'Eek! What a big mane! I am so scared!'],
      ['해설', 'The fox ran into her hole and shook.'],
      ['해설', 'A few days later, she saw the lion again.'],
      ['여우', 'It is that lion! But I will not run this time.'],
      ['해설', 'She hid behind a rock and peeked.'],
      ['해설', 'The lion drank water. His tail went swish, swish.'],
      ['여우', 'Oh, he is not so scary.'],
      ['해설', 'The third time, the fox walked up to the lion.'],
      ['여우', 'Hello, Mr. Lion. I am a fox from this forest.'],
      ['사자', 'Oh! You are the first one who did not run.'],
      ['여우', 'I was scared at first. So I hid.'],
      ['사자', 'Ha ha! New things scare me a little, too.'],
      ['여우', 'Really? The king of the forest?'],
      ['사자', 'Yes. My first hedgehog was very scary!'],
      ['해설', 'The fox and the lion talked for a long time.'],
      ['여우', 'Now you are not scary at all.'],
      ['해설', 'New things can be scary. Get to know them, and you feel brave.'],
    ],
  },

  'ae3-two-pots': {
    title: 'The Two Pots',
    names: { 해설: 'Narrator', 쇠항아리: 'Iron Pot', 흙항아리: 'Clay Pot' },
    outro: [
      'Was the story fun?',
      'If you were the Clay Pot, what would you say?',
      'How do you take care of a friend who is different?',
    ],
    lines: [
      ['해설', 'Once upon a time, two pots sat in a kitchen.'],
      ['해설', 'One was made of iron. One was made of clay.'],
      ['쇠항아리', 'I am very strong. Bang, bang! I never break.'],
      ['흙항아리', 'I must be careful. One bump can break me.'],
      ['해설', 'One night, the rain came down hard.'],
      ['해설', 'The river came into the kitchen. Splash!'],
      ['흙항아리', 'Oh no! We are floating away!'],
      ['쇠항아리', 'Stay close to me. I will keep you safe.'],
      ['흙항아리', 'Thank you. But I will stay a little far.'],
      ['쇠항아리', 'Why? I am so strong.'],
      ['흙항아리', 'If the water pushes us, we will bump.'],
      ['흙항아리', 'You will be fine, but I will break.'],
      ['쇠항아리', 'Oh, I did not think of that.'],
      ['해설', 'The two pots floated apart. Bob, bob.'],
      ['해설', 'Big waves came again and again.'],
      ['해설', 'But the pots did not bump.'],
      ['해설', 'At last, the rain stopped. They landed on the sand.'],
      ['흙항아리', 'Phew! I do not have a single crack!'],
      ['쇠항아리', 'Good! You were right.'],
      ['흙항아리', 'Thank you for wanting to help me.'],
      ['해설', 'Friends are different. Know the difference and be kind.'],
    ],
  },

  'ae3-fox-hedgehog': {
    title: 'The Fox and the Hedgehog',
    names: { 해설: 'Narrator', 여우: 'Fox', 고슴도치: 'Hedgehog' },
    outro: [
      'Did you like the story?',
      'If you were the Fox, would you take the help?',
      'When did you think hard before changing something?',
    ],
    lines: [
      ['해설', 'Once upon a time, a fox swam across a river.'],
      ['해설', 'The water was too fast. Splash, splash!'],
      ['여우', 'Help! The water is so strong!'],
      ['해설', 'The fox got out, but he was stuck in a bush.'],
      ['여우', 'I am so tired. I cannot move.'],
      ['해설', 'Then little bugs came. Buzz, buzz! Bite, bite!'],
      ['여우', 'Ouch, ouch! That itches!'],
      ['해설', 'A hedgehog walked by.'],
      ['고슴도치', 'Fox, are you okay? Shall I chase the bugs away?'],
      ['여우', 'Thank you, but please leave them.'],
      ['고슴도치', 'Why? They are biting you!'],
      ['여우', 'These bugs are full now. They only bite a little.'],
      ['여우', 'If they go, new hungry bugs will come.'],
      ['여우', 'New bugs will bite much harder.'],
      ['고슴도치', 'Oh, I see! You are so smart.'],
      ['고슴도치', 'Then I will help you out of the bush.'],
      ['해설', 'The hedgehog pulled the twigs away, one by one.'],
      ['해설', 'Pop! The fox was free.'],
      ['여우', 'I am free! Thank you, Hedgehog!'],
      ['해설', 'The fox shook his fur, and the bugs flew away.'],
      ['해설', 'Think before you change things. Things can get worse.'],
    ],
  },

  'ae3-sun-frogs': {
    title: 'The Sun’s Wedding',
    names: { 해설: 'Narrator', 해님: 'Sun', 개구리: 'Frog', 할머니: 'Grandma Frog' },
    outro: [
      'Was the story fun?',
      'If you were the Sun, what would you do for the frogs?',
      'When you are happy, do you think of others, too?',
    ],
    lines: [
      ['해설', 'Once upon a time, the Sun had big news.'],
      ['해님', 'Everyone, I am getting married this summer!'],
      ['해설', 'The animals jumped for joy.'],
      ['해설', 'The frogs got ready for a party. Ribbit, ribbit!'],
      ['개구리', 'The Sun is getting married! Let us sing!'],
      ['해설', 'But Grandma Frog sighed.'],
      ['할머니', 'Children, do not be so happy yet.'],
      ['개구리', 'Why, Grandma? It is good news.'],
      ['할머니', 'With one sun, our pond gets dry every summer.'],
      ['개구리', 'Yes. Last summer, the water went down.'],
      ['할머니', 'What if the Sun has many baby suns?'],
      ['개구리', 'Two suns, three suns, four suns! Oh no!'],
      ['할머니', 'Then all the ponds will dry up.'],
      ['개구리', 'Where will we live?'],
      ['해설', 'The frogs croaked loudly. The Sun heard them.'],
      ['해님', 'Frogs, what is wrong?'],
      ['개구리', 'Many suns will make our pond dry.'],
      ['해님', 'Oh, I did not think of that.'],
      ['해님', 'I will not be too hot. I will ask the clouds for rain.'],
      ['해설', 'That summer, cool rain fell on the pond.'],
      ['개구리', 'Ribbit! Happy wedding, Sun!'],
      ['해설', 'Even on happy days, think about others, too.'],
    ],
  },

  'ae3-gnat-bull': {
    title: 'The Gnat and the Bull',
    names: { 해설: 'Narrator', 모기: 'Gnat', 황소: 'Bull' },
    outro: [
      'Did you enjoy the story?',
      'If you were the Gnat, how would you feel?',
      'What are you good at?',
    ],
    lines: [
      ['해설', 'Once upon a time, a big bull lived in a field.'],
      ['해설', 'He ate grass all day. Munch, munch.'],
      ['해설', 'One day, a little gnat flew by. Buzz, buzz!'],
      ['모기', 'My wings are tired. I will rest here.'],
      ['해설', 'The gnat sat on the bull’s horn.'],
      ['모기', 'Mr. Bull, am I too heavy for you?'],
      ['황소', 'Moo. Munch, munch.'],
      ['해설', 'The bull did not answer.'],
      ['모기', 'I must be very heavy.'],
      ['해설', 'Later, the gnat spoke very loudly.'],
      ['모기', 'Mr. Bull! I am leaving now!'],
      ['황소', 'Huh? Who is talking?'],
      ['모기', 'Me! The gnat on your horn!'],
      ['황소', 'Oh, I did not know you were there.'],
      ['모기', 'You did not know?'],
      ['황소', 'No. I did not feel you come or go.'],
      ['모기', 'I thought I was very big.'],
      ['황소', 'Do not be sad. You can fly. I cannot.'],
      ['모기', 'That is true! Now I feel better.'],
      ['해설', 'The gnat sang and flew up into the sky.'],
      ['해설', 'Do not show off. Just be you.'],
    ],
  },

  'ae3-nettle': {
    title: 'The Boy and the Nettle',
    names: { 해설: 'Narrator', 소년: 'Boy', 엄마: 'Mom' },
    outro: [
      'Was the story fun?',
      'If you were the Boy, would you hold the nettle again?',
      'What did you do bravely?',
    ],
    lines: [
      ['해설', 'Once upon a time, a boy saw a green plant.'],
      ['소년', 'The leaves look soft. I will touch them.'],
      ['해설', 'He touched a leaf very gently.'],
      ['소년', 'Ouch! It stings!'],
      ['해설', 'It was a nettle. It had tiny stinging hairs.'],
      ['해설', 'The boy ran to his mom, crying.'],
      ['소년', 'Mom! I touched it gently, but it stung me.'],
      ['엄마', 'Let us wash your hand in cold water.'],
      ['엄마', 'If you touch a nettle gently, it stings more.'],
      ['소년', 'Really? Why?'],
      ['엄마', 'The tiny hairs poke your skin.'],
      ['엄마', 'But if you hold it tight, the hairs go flat.'],
      ['소년', 'Then it will not hurt?'],
      ['엄마', 'Put on gloves and try. I am right here.'],
      ['해설', 'The boy put on gloves.'],
      ['소년', 'I am scared, but I will be brave.'],
      ['해설', 'He held the nettle tight. Squeeze!'],
      ['소년', 'It does not hurt at all!'],
      ['엄마', 'Good job! Let us pull them out.'],
      ['소년', 'Now my friends will not get stung!'],
      ['엄마', 'Hard things get easy when you are brave.'],
      ['해설', 'When something is hard, do not wait. Try it bravely.'],
    ],
  },

  'ae3-old-lion': {
    title: 'The Old Lion and the Fox',
    names: { 해설: 'Narrator', 사자: 'Lion', 여우: 'Fox', 염소: 'Goat' },
    outro: [
      'Did you like the story?',
      'If you were the Fox, what would you do at the cave?',
      'When did you look carefully and find something?',
    ],
    lines: [
      ['해설', 'Once upon a time, there was a very old lion.'],
      ['해설', 'He was too slow to hunt.'],
      ['사자', 'I am hungry, but I cannot run. I need a trick.'],
      ['해설', 'He lay in his cave and made sick sounds.'],
      ['사자', 'Ooh, I am sick. Please come and visit me.'],
      ['염소', 'Poor Mr. Lion! I will go in and see him.'],
      ['해설', 'The goat went in. But she did not come out.'],
      ['해설', 'The lion locked her in the back of the cave.'],
      ['해설', 'A sheep went in. A calf went in. Nobody came out.'],
      ['해설', 'Then a fox came to the cave.'],
      ['사자', 'Come in, Fox. I am so sick.'],
      ['해설', 'The fox looked down at the ground.'],
      ['여우', 'Hmm. All the footprints go in.'],
      ['여우', 'But no footprints come out.'],
      ['여우', 'Mr. Lion, I will say hello from here.'],
      ['사자', 'Why? Come in!'],
      ['여우', 'I do not go where nobody comes out.'],
      ['해설', 'The fox called all her forest friends.'],
      ['해설', 'A strong elephant pushed a rock and opened the back.'],
      ['염소', 'We are free! Thank you, Fox!'],
      ['사자', 'Oh no! My trick did not work.'],
      ['해설', 'Do not just believe words. Look carefully with your eyes.'],
    ],
  },

  'ae3-mountain-mouse': {
    title: 'The Mountain and the Mouse',
    names: { 해설: 'Narrator', 농부: 'Farmer', 아이: 'Child', 생쥐: 'Mouse' },
    outro: [
      'Was the story fun?',
      'What did you think would come out of the mountain?',
      'What did you finish without talking big?',
    ],
    lines: [
      ['해설', 'Once upon a time, a village sat under a big mountain.'],
      ['해설', 'One morning, the mountain made a noise. Rumble, rumble!'],
      ['농부', 'What is that? The mountain is shaking!'],
      ['아이', 'Dad, I am scared! What will happen?'],
      ['농부', 'Something very big, I think.'],
      ['해설', 'People came from other villages, too.'],
      ['농부', 'Maybe a giant will come out!'],
      ['아이', 'Maybe a dragon will come out!'],
      ['해설', 'Rumble, boom! The mountain shook again.'],
      ['해설', 'Everyone held their breath and watched.'],
      ['해설', 'At last, something came out of a little hole.'],
      ['생쥐', 'Squeak! It is too noisy. I cannot sleep.'],
      ['해설', 'It was just a little mouse!'],
      ['아이', 'It is only a mouse!'],
      ['농부', 'Ha ha! So much noise for one little mouse!'],
      ['해설', 'Everyone laughed and laughed.'],
      ['생쥐', 'Why are you laughing? I am just moving house.'],
      ['생쥐', 'Some rocks rolled down. That made the noise.'],
      ['농부', 'A big noise does not mean a big thing.'],
      ['아이', 'Dad, I will not just talk big. I will do it.'],
      ['해설', 'Doing a small thing is better than talking big.'],
    ],
  },

  'ae3-crow-swan': {
    title: 'The Crow and the Swan',
    names: { 해설: 'Narrator', 까마귀: 'Crow', 백조: 'Swan' },
    outro: [
      'Did you enjoy the story?',
      'If you were the Crow, would you want to be a swan?',
      'What is special about you?',
    ],
    lines: [
      ['해설', 'Once upon a time, a crow lived in a tree.'],
      ['해설', 'Every day, he looked at a white swan on the lake.'],
      ['까마귀', 'The swan is so white. Why am I black?'],
      ['까마귀', 'I know! She washes all day in the water!'],
      ['해설', 'The crow flew to the lake.'],
      ['백조', 'Hello, Crow. Why are you here?'],
      ['까마귀', 'I want to be white like you. I will wash!'],
      ['해설', 'Splash, splash! Scrub, scrub!'],
      ['까마귀', 'Am I white now?'],
      ['해설', 'No. He was still black.'],
      ['해설', 'He washed the next day, and the next day.'],
      ['해설', 'But there was no good food for a crow.'],
      ['백조', 'Do you want some water plants? They are yummy.'],
      ['까마귀', 'Yuck! I cannot eat those.'],
      ['해설', 'His tummy went growl, growl.'],
      ['까마귀', 'I am still black, and now I am hungry.'],
      ['백조', 'Crow, you are great as you are.'],
      ['백조', 'Your black feathers shine in the sun.'],
      ['까마귀', 'Really? I did not know that.'],
      ['까마귀', 'I will just be me!'],
      ['해설', 'The crow went home and ate yummy berries.'],
      ['해설', 'Do not try to be someone else. Love being you.'],
    ],
  },

  'ae3-cat-mice': {
    title: 'The Cat and the Mice',
    names: { 해설: 'Narrator', 고양이: 'Cat', 생쥐: 'Mouse', 늙은쥐: 'Old Mouse' },
    outro: [
      'Was the story fun?',
      'If you were the little Mouse, what would you do?',
      'When did you make a mistake by only looking?',
    ],
    lines: [
      ['해설', 'Once upon a time, mice lived in a kitchen.'],
      ['해설', 'A fast cat lived there, too.'],
      ['고양이', 'Meow! I will catch the mice!'],
      ['생쥐', 'Squeak! The cat! Hide!'],
      ['해설', 'The mice always ran into their hole.'],
      ['고양이', 'They never come out. I need a trick.'],
      ['해설', 'The cat rolled in the flour. Roll, roll!'],
      ['해설', 'Now he was all white. He curled up in a corner.'],
      ['고양이', 'Now I look like a lump of flour.'],
      ['해설', 'The mice peeked out of the hole.'],
      ['생쥐', 'No cat! Look, a lump of flour!'],
      ['생쥐', 'Let us go and eat it! Yum, yum!'],
      ['늙은쥐', 'Wait! Do not go near it.'],
      ['생쥐', 'Why, Grandpa? It is just flour.'],
      ['늙은쥐', 'Sniff, sniff. It smells like a cat.'],
      ['늙은쥐', 'And look. A tail is moving.'],
      ['생쥐', 'Oh! I see the tail!'],
      ['늙은쥐', 'A white cat is still a cat.'],
      ['해설', 'The mice hid again.'],
      ['고양이', 'Achoo! I am all white, and I caught nothing.'],
      ['생쥐', 'Thank you, Grandpa!'],
      ['해설', 'Do not just look at the outside. Look carefully.'],
    ],
  },

  'ae3-plane-tree': {
    title: 'The Travelers and the Tree',
    names: { 해설: 'Narrator', 나그네: 'Traveler', 친구: 'Friend', 나무: 'Tree' },
    outro: [
      'Did you like the story?',
      'If you were the Tree, what would you say?',
      'Who do you want to say thank you to?',
    ],
    lines: [
      ['해설', 'Once upon a time, two travelers walked on a hot day.'],
      ['해설', 'The sun was very hot. They were sweaty.'],
      ['나그네', 'It is so hot. Where can we rest?'],
      ['친구', 'Look! A big tree!'],
      ['해설', 'They sat down in the cool shade.'],
      ['나그네', 'Ah, this is so nice and cool.'],
      ['해설', 'They drank water and took a nap.'],
      ['나그네', 'But this tree has no fruit.'],
      ['친구', 'Right. It is a useless tree.'],
      ['해설', 'Then the leaves moved. Rustle, rustle.'],
      ['나무', 'Excuse me, travelers.'],
      ['나그네', 'Oh my! The tree can talk!'],
      ['나무', 'You rested in my shade, right?'],
      ['친구', 'Yes, we did.'],
      ['나무', 'And now you say I am useless?'],
      ['해설', 'The travelers’ faces turned red.'],
      ['나그네', 'We are sorry. We did not say thank you.'],
      ['친구', 'Your shade gave us strength.'],
      ['나무', 'Thank you. Come and rest again.'],
      ['해설', 'The travelers bowed and walked on.'],
      ['해설', 'When someone helps you, say thank you.'],
    ],
  },

  'ae3-hercules': {
    title: 'Hercules and the Wagon Driver',
    names: { 해설: 'Narrator', 마부: 'Driver', 헤라클레스: 'Hercules' },
    outro: [
      'Was the story fun?',
      'If you were the Driver, what would you do first?',
      'What did you try by yourself before asking for help?',
    ],
    lines: [
      ['해설', 'Once upon a time, a man drove a wagon.'],
      ['해설', 'It rained all night. The road was muddy.'],
      ['마부', 'Giddyup, horse! A little more!'],
      ['해설', 'Then the wheel got stuck in the mud.'],
      ['마부', 'Oh no! The wheel will not move!'],
      ['해설', 'The man sat down in the road.'],
      ['마부', 'I cannot do it. Hercules, please help me!'],
      ['해설', 'He only looked up at the sky and prayed.'],
      ['해설', 'Then a big voice came from the clouds.'],
      ['헤라클레스', 'Driver, why are you sitting there?'],
      ['마부', 'My wagon is stuck. I want your help.'],
      ['헤라클레스', 'Will the wagon come out by itself?'],
      ['헤라클레스', 'Get up. Push the wheel with your shoulder.'],
      ['헤라클레스', 'And tell your horse to pull.'],
      ['마부', 'You want me to try first?'],
      ['헤라클레스', 'Yes. I help people who help themselves.'],
      ['마부', 'Push! Push! Pull, horse, pull!'],
      ['해설', 'Pop! The wheel came out of the mud.'],
      ['마부', 'It is out! I did it!'],
      ['헤라클레스', 'Good job. You are stronger than you think.'],
      ['해설', 'Before you ask for help, try it yourself first.'],
    ],
  },

  'ae3-dog-manger': {
    title: 'The Dog in the Hay Box',
    names: { 해설: 'Narrator', 개: 'Dog', 소: 'Cow', 농부: 'Farmer' },
    outro: [
      'Did you enjoy the story?',
      'If you were the Cow, what would you say to the Dog?',
      'What did you share with a friend?',
    ],
    lines: [
      ['해설', 'Once upon a time, a cow lived on a farm.'],
      ['해설', 'Her food box was full of sweet hay.'],
      ['해설', 'One afternoon, a dog came into the barn.'],
      ['개', 'The hay is so soft! I will nap here.'],
      ['해설', 'The dog curled up in the food box.'],
      ['해설', 'In the evening, the cow came back from work.'],
      ['소', 'Moo, I am hungry. I want my hay.'],
      ['개', 'Grr! Go away! This is my place!'],
      ['소', 'Dog, I only want to eat.'],
      ['개', 'Woof! No! Do not come close!'],
      ['소', 'But you do not eat hay. Please move.'],
      ['개', 'No! Nobody can eat it!'],
      ['해설', 'The hungry cow stepped back.'],
      ['소', 'He cannot eat it, but I cannot eat it either.'],
      ['해설', 'The farmer saw the dog.'],
      ['농부', 'Dog! You do not eat hay. Why are you mean?'],
      ['개', 'I did not want to lose my bed.'],
      ['농부', 'The cow worked all day. She is very hungry.'],
      ['개', 'I am sorry, Cow.'],
      ['해설', 'The dog jumped out. The cow ate her hay.'],
      ['소', 'Thank you, Dog. Sleep on that soft straw.'],
      ['해설', 'If you do not need it, share it with a friend.'],
    ],
  },

  'ae3-frog-ox': {
    title: 'The Frog Who Puffed Up',
    names: { 해설: 'Narrator', 엄마: 'Mother Frog', 아기: 'Baby Frog' },
    outro: [
      'Was the story fun?',
      'If you were the Baby Frog, what would you say?',
      'When did you feel sad comparing yourself to others?',
    ],
    lines: [
      ['해설', 'Once upon a time, frogs lived in a pond.'],
      ['해설', 'One day, a baby frog hopped home fast.'],
      ['아기', 'Mom! I saw a big, big monster!'],
      ['엄마', 'A monster? What did it look like?'],
      ['아기', 'It had horns. It said moo. It was huge!'],
      ['엄마', 'That is an ox. How big can it be?'],
      ['해설', 'Mother Frog took a big breath. Puff!'],
      ['엄마', 'Was it this big?'],
      ['아기', 'No, much bigger!'],
      ['엄마', 'Puff, puff! This big?'],
      ['아기', 'No, Mom! Much, much bigger!'],
      ['엄마', 'Puff, puff, puff! This big?'],
      ['아기', 'Stop, Mom! You will pop!'],
      ['해설', 'But she puffed more. Then, pfffft! The air came out.'],
      ['해설', 'She spun around and fell in the pond. Splash!'],
      ['아기', 'Mom! Are you okay?'],
      ['엄마', 'Oh, I am so dizzy.'],
      ['해설', 'Then the real ox walked by. Stomp, stomp.'],
      ['엄마', 'Oh my! He is so big!'],
      ['아기', 'You do not need to be big, Mom.'],
      ['엄마', 'You are right. But I can jump high!'],
      ['해설', 'Mother Frog jumped onto a lily pad. Hop!'],
      ['해설', 'Do not try to be like others. Love what you can do.'],
    ],
  },

  'ae3-hares-frogs': {
    title: 'The Hares and the Frogs',
    names: { 해설: 'Narrator', 토끼: 'Hare', 큰토끼: 'Big Hare', 개구리: 'Frog' },
    outro: [
      'Did you like the story?',
      'If you were the Hare, what would you think?',
      'How do you feel brave when you are scared?',
    ],
    lines: [
      ['해설', 'Once upon a time, some hares lived in a field.'],
      ['해설', 'They were scared of everything.'],
      ['토끼', 'Eek! What was that? A wolf?'],
      ['큰토끼', 'No, it was just a falling leaf.'],
      ['토끼', 'Why are we so scared all the time?'],
      ['큰토끼', 'Let us go far away. Let us find a safe place.'],
      ['해설', 'The hares hopped away. Hop, hop, hop!'],
      ['해설', 'Soon they came to a big pond.'],
      ['해설', 'Frogs were sitting by the pond.'],
      ['개구리', 'Ribbit! Big animals are coming!'],
      ['해설', 'The frogs jumped into the water. Plop, plop!'],
      ['토끼', 'Look! The frogs ran away from us!'],
      ['큰토끼', 'Some animals are scared of us!'],
      ['해설', 'One frog peeked out of the water.'],
      ['개구리', 'Who are you? Will you hurt us?'],
      ['토끼', 'No! We only eat grass. Sorry we scared you.'],
      ['개구리', 'Phew! We get scared easily.'],
      ['큰토끼', 'Just like us! We are not the only ones.'],
      ['토끼', 'Then let us not worry so much.'],
      ['큰토끼', 'Yes. Let us be careful, but brave!'],
      ['해설', 'The hares waved and hopped back home.'],
      ['해설', 'Everyone is scared sometimes. Be brave, little by little.'],
    ],
  },

  'ae3-monkey-camel': {
    title: 'The Monkey and the Camel',
    names: { 해설: 'Narrator', 원숭이: 'Monkey', 낙타: 'Camel', 사자: 'Lion' },
    outro: [
      'Was the story fun?',
      'If you were the Camel, how would you feel?',
      'What can you do better than others?',
    ],
    lines: [
      ['해설', 'Once upon a time, the animals had a big party.'],
      ['사자', 'Let us have fun! Who will show us a trick?'],
      ['원숭이', 'Me, me! I will dance!'],
      ['해설', 'The monkey spun and jumped and flipped.'],
      ['사자', 'Wonderful! Clap, clap, clap!'],
      ['해설', 'Everyone loved the monkey. The camel was jealous.'],
      ['낙타', 'I can dance, too. I will dance better!'],
      ['낙타', 'Watch me! One, two, three!'],
      ['해설', 'The camel tried to spin. Wobble, wobble!'],
      ['해설', 'He tried to jump. Thump! He fell down.'],
      ['원숭이', 'Be careful, Camel!'],
      ['해설', 'Crash! The camel knocked over the food table.'],
      ['사자', 'Oh no! What a mess!'],
      ['낙타', 'I am sorry. I wanted to be like the monkey.'],
      ['사자', 'Camel, you are good at other things.'],
      ['낙타', 'Me? What am I good at?'],
      ['사자', 'You can walk in the desert for days.'],
      ['원숭이', 'And you can carry heavy things! I cannot.'],
      ['낙타', 'That is true! I will bring more food.'],
      ['해설', 'The camel carried big baskets of food.'],
      ['해설', 'Everyone clapped for the camel, too.'],
      ['해설', 'Do not be jealous. Shine by doing what you do well.'],
    ],
  },

  'ae3-dog-rooster': {
    title: 'The Rooster, Dog, and Fox',
    names: { 해설: 'Narrator', 수탉: 'Rooster', 개: 'Dog', 여우: 'Fox' },
    outro: [
      'Did you enjoy the story?',
      'If you were the Rooster, what trick would you use?',
      'When did a friend make you feel safe?',
    ],
    lines: [
      ['해설', 'Once upon a time, a dog and a rooster were best friends.'],
      ['개', 'Rooster, let us go on a trip!'],
      ['수탉', 'Yes! Cock-a-doodle-doo! Let us go!'],
      ['해설', 'They walked all day to a deep forest.'],
      ['개', 'I will sleep in this hole in the tree.'],
      ['수탉', 'I will sleep up on a branch. Good night!'],
      ['해설', 'In the morning, the rooster sang.'],
      ['수탉', 'Cock-a-doodle-doo! Good morning!'],
      ['해설', 'A hungry fox heard him and came close.'],
      ['여우', 'Mr. Rooster, what a lovely song!'],
      ['여우', 'Come down. I want to give you a hug.'],
      ['수탉', 'The fox wants to catch me. I need a trick.'],
      ['수탉', 'Okay. But first, wake up my doorkeeper.'],
      ['여우', 'Doorkeeper? Where is he?'],
      ['수탉', 'He is sleeping in the hole down there.'],
      ['해설', 'The fox put his head into the hole.'],
      ['여우', 'Wake up, Doorkeeper! Open the door!'],
      ['개', 'Grr! Woof, woof! Who woke me up?'],
      ['여우', 'Oh no, a dog! Run, run!'],
      ['해설', 'The fox ran far away into the forest.'],
      ['개', 'Ha ha! Rooster, you are so clever!'],
      ['수탉', 'You made me feel safe, my friend.'],
      ['해설', 'A bad trick can come back to the trickster.'],
    ],
  },

  'ae3-two-frogs': {
    title: 'The Two Frogs and the Well',
    names: { 해설: 'Narrator', 성급이: 'Hasty', 찬찬이: 'Careful' },
    outro: [
      'Was the story fun?',
      'If you were Hasty, what would you do at the well?',
      'When were you glad you stopped to think?',
    ],
    lines: [
      ['해설', 'Once upon a time, two frogs lived in a small pond.'],
      ['해설', 'One was Hasty. One was Careful.'],
      ['해설', 'One summer, it did not rain. The pond dried up.'],
      ['성급이', 'Ribbit! I am so thirsty! There is no water!'],
      ['찬찬이', 'Let us find a new home.'],
      ['해설', 'They hopped and hopped. Hop, hop!'],
      ['해설', 'Soon they found a deep well.'],
      ['성급이', 'Look! There is water down there!'],
      ['성급이', 'Let us jump in right now!'],
      ['찬찬이', 'Wait! Let us think first.'],
      ['성급이', 'Think about what? There is so much water!'],
      ['찬찬이', 'What if the well dries up, too?'],
      ['찬찬이', 'The walls are high. Can we get out?'],
      ['해설', 'Hasty looked down again. The walls were smooth and deep.'],
      ['성급이', 'You are right. We could not get out.'],
      ['성급이', 'Phew! That was close.'],
      ['해설', 'They hopped on. Then they heard a sound. Trickle, trickle.'],
      ['찬찬이', 'A stream! It is easy to go in and out.'],
      ['성급이', 'Yay! This is a good home!'],
      ['성급이', 'Thank you, Careful. I will think before I jump.'],
      ['찬찬이', 'Ribbit! Now let us swim!'],
      ['해설', 'Before you do something, think about what comes next.'],
    ],
  },
};
