// 영어 학습용 원고: 세계 도시 탐방 2차 (한국·동아시아). 문장은 자체 집필.
// 키 = stories/city-e.js 의 이야기 id. lines 의 첫 칸은 한국어 cast 이름 그대로.
export default {
  'ct-busan-1': {
    title: 'Busan, Part 1',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 도윤: 'Doyun' },
    outro: [
      'Was our first day in Busan as fresh as the sea?',
      'Why did many people come to Busan during the war?',
      'What would you do if you lived by the sea?',
    ],
    lines: [
      ['해설', 'Hana and the Guide took a train to Busan.'],
      ['하나', 'I can smell the sea! Where is Busan?'],
      ['안내인', 'It is at the southeast end of Korea.'],
      ['안내인', 'Busan is a big port city by the sea.'],
      ['안내인', 'The Nakdong River meets the sea here.'],
      ['안내인', 'Winters are fairly mild because of the sea.'],
      ['도윤', 'Hi! I am Doyun. Welcome to Busan!'],
      ['해설', 'The Guide told the story of Busan.'],
      ['안내인', 'Long ago, the center of this area was called Dongnae.'],
      ['안내인', 'In 1592, the first battle of a big war was here.'],
      ['안내인', 'In 1876, Busan opened its port to trade.'],
      ['안내인', 'During the Korean War, Busan was the temporary capital.'],
      ['도윤', 'In 2002, Busan held the Asian Games.'],
      ['해설', 'Then they visited three famous places.'],
      ['도윤', 'First, Haeundae Beach! The sand is long and soft.'],
      ['안내인', 'Second, Gamcheon Culture Village. It has colorful houses on a hill.'],
      ['도윤', 'Third, Gwangan Bridge. It crosses the sea.'],
      ['하나', 'At night, the bridge sparkles with lights!'],
      ['해설', 'Busan opened its port in 1876. It was a wartime capital.'],
      ['해설', 'Next time, we will learn about food and life in Busan.'],
    ],
  },

  'ct-busan-2': {
    title: 'Busan, Part 2',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 아지매: 'Market Lady' },
    outro: [
      'Was our food trip in Busan tasty?',
      'How did milmyeon begin, according to the story?',
      'If you made a movie, what would it be about?',
    ],
    lines: [
      ['해설', 'Last time, Hana learned about Busan’s history and beaches.'],
      ['해설', 'Today, they went to Jagalchi, a big fish market.'],
      ['아지매', 'Come in, look around, and buy some fresh fish!'],
      ['하나', 'Wow! The fish are flapping!'],
      ['아지매', 'First, try dwaeji gukbap. It is pork bone soup with rice.'],
      ['안내인', 'Add chives and salty shrimp. Then slurp it up.'],
      ['아지매', 'Second, milmyeon. It is cold noodle soup made with wheat.'],
      ['안내인', 'People say refugees made it with wheat flour during the war.'],
      ['아지매', 'Third, eomuk. It is fried fish cake on a stick.'],
      ['하나', 'Warm fish cake in hot soup is yummy!'],
      ['안내인', 'Every September or October, Busan has a big film festival.'],
      ['안내인', 'It started in 1996. Movies come from many countries.'],
      ['안내인', 'Big ships carry boxes in and out of Busan Port.'],
      ['안내인', 'There are many hills, so roads curve along the mountains.'],
      ['하나', 'Tell me a fun fact, please!'],
      ['안내인', 'The name Haeundae came from a scholar of old Silla.'],
      ['안내인', 'Yeongdo Bridge can lift up so big ships can pass.'],
      ['하나', 'A bridge that goes up? How amazing!'],
      ['해설', 'Busan’s famous foods are dwaeji gukbap, milmyeon, and eomuk.'],
      ['해설', 'Busan is a lively port city of sea, markets, and movies.'],
    ],
  },

  'ct-jeju-1': {
    title: 'Jeju, Part 1',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 은별: 'Eunbyeol' },
    outro: [
      'Did you enjoy our first day on Jeju Island?',
      'Why does Jeju have so many black rocks and caves?',
      'What would you do on an island for one day?',
    ],
    lines: [
      ['해설', 'Hana and the Guide flew over the sea to Jeju.'],
      ['하나', 'Jeju is an island, right?'],
      ['안내인', 'Yes! It is the biggest island in Korea.'],
      ['안내인', 'Jeju City is the main city in the north.'],
      ['안내인', 'Hallasan is the highest mountain in South Korea.'],
      ['안내인', 'Jeju is warm and very windy.'],
      ['은별', 'Honjeo opseoye! That means welcome in Jeju words.'],
      ['해설', 'The Guide told the story of Jeju.'],
      ['안내인', 'Long ago, volcanoes made this island.'],
      ['은별', 'A legend says three men rose from the ground here.'],
      ['은별', 'They started an old kingdom called Tamna.'],
      ['안내인', 'Later, during Goryeo, Tamna became part of Goryeo.'],
      ['안내인', 'In the 1700s, a merchant named Kim Mandeok shared rice.'],
      ['안내인', 'In 2007, Jeju became a World Natural Heritage site.'],
      ['해설', 'Then they visited three famous places.'],
      ['은별', 'First, Seongsan Ilchulbong. You can watch the sunrise there.'],
      ['은별', 'Second, Manjanggul. Hot lava made this long cave.'],
      ['하나', 'It is cool and bumpy inside!'],
      ['안내인', 'Third, Yongduam. This lava rock looks like a dragon’s head.'],
      ['해설', 'Jeju is Korea’s biggest island. Volcanoes made it.'],
      ['해설', 'Next time, we will learn about food and life in Jeju.'],
    ],
  },

  'ct-jeju-2': {
    title: 'Jeju, Part 2',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 해녀: 'Haenyeo' },
    outro: [
      'Was our second day in Jeju as sweet as a tangerine?',
      'How do haenyeo work under the sea?',
      'If your home had jeongnang, what rule would you make?',
    ],
    lines: [
      ['해설', 'Last time, Hana learned about Jeju’s volcanoes and Tamna.'],
      ['해설', 'Today, they met a haenyeo grandma by the sea.'],
      ['하나', 'Grandma, what does a haenyeo do?'],
      ['해녀', 'I hold my breath and dive for abalone and shellfish.'],
      ['안내인', 'In 2016, haenyeo culture joined the UNESCO heritage list.'],
      ['해녀', 'First, try gogi guksu. It is noodles in pork soup.'],
      ['하나', 'The soup is rich, and the meat is soft!'],
      ['안내인', 'Second, momguk. It is pork soup with seaweed.'],
      ['해녀', 'We shared it at big village parties.'],
      ['안내인', 'Third, omegi tteok. It is a sweet millet rice cake.'],
      ['하나', 'It is chewy and sweet!'],
      ['안내인', 'Look! This is a dol hareubang, a stone grandpa.'],
      ['안내인', 'Around October, the Tamna Culture Festival shows old customs.'],
      ['안내인', 'People build black stone walls to block the wind.'],
      ['해녀', 'In winter, we pick yellow tangerines.'],
      ['안내인', 'Small volcanic hills called oreum are all over the island.'],
      ['하나', 'Do you have a fun fact?'],
      ['안내인', 'Old Jeju homes used wooden poles called jeongnang, not gates.'],
      ['안내인', 'The poles showed if someone was home.'],
      ['해설', 'Jeju’s famous foods are gogi guksu, momguk, and omegi tteok.'],
      ['해설', 'Jeju is a beautiful island of sea, stone, and wind.'],
    ],
  },

  'ct-shanghai-1': {
    title: 'Shanghai, Part 1',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 샤오밍: 'Xiaoming' },
    outro: [
      'Did you enjoy our first day in Shanghai?',
      'How did a small river village become a big port?',
      'Would you visit the old side or the new side first?',
    ],
    lines: [
      ['해설', 'Hana and the Guide flew to Shanghai in China.'],
      ['하나', 'Where is Shanghai?'],
      ['안내인', 'It is a big port city on China’s east coast.'],
      ['안내인', 'It is near the mouth of the Yangtze River.'],
      ['안내인', 'The Huangpu River flows through the city.'],
      ['안내인', 'Summers are hot and wet. Early summer is rainy.'],
      ['샤오밍', 'Nong ho! That means hello in Shanghai words.'],
      ['해설', 'The Guide told the story of Shanghai.'],
      ['안내인', 'Long ago, it was a small fishing and trading village.'],
      ['안내인', 'About 700 years ago, it became a county town.'],
      ['안내인', 'In the 1500s, people made Yuyuan Garden.'],
      ['안내인', 'In the mid-1800s, the port opened to many countries.'],
      ['샤오밍', 'Then stone buildings went up along the river.'],
      ['안내인', 'In 2010, Shanghai held a World Expo.'],
      ['해설', 'Then they visited three famous places.'],
      ['샤오밍', 'First, the Bund. It is a street along the river.'],
      ['안내인', 'Second, the Oriental Pearl Tower. It looks like big beads.'],
      ['안내인', 'Third, Yuyuan Garden. It has ponds and little bridges.'],
      ['하나', 'A quiet garden among tall buildings!'],
      ['해설', 'Shanghai is a port city. It grew big after the 1800s.'],
      ['해설', 'Next time, we will learn about food and life in Shanghai.'],
    ],
  },

  'ct-shanghai-2': {
    title: 'Shanghai, Part 2',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 요리사: 'Cook' },
    outro: [
      'Was our food trip in Shanghai yummy?',
      'Why should you eat xiaolongbao slowly and carefully?',
      'Where in another country can you find Korean history?',
    ],
    lines: [
      ['해설', 'Last time, Hana learned about Shanghai’s history and river.'],
      ['해설', 'Today, they went into a steamy dumpling shop.'],
      ['요리사', 'Welcome! First, try xiaolongbao.'],
      ['안내인', 'These little dumplings have hot soup inside.'],
      ['요리사', 'Put one on a spoon. Sip the soup first.'],
      ['하나', 'Ouch, hot! But the soup is so good.'],
      ['요리사', 'Second, shengjianbao. The bottoms are fried and crispy.'],
      ['안내인', 'Third, hongshao rou. It is pork in soy sauce and sugar.'],
      ['요리사', 'Shanghai food is often sweet and salty.'],
      ['안내인', 'At Lunar New Year, Yuyuan Garden fills with lanterns.'],
      ['요리사', 'At the Mid-Autumn Festival, we share mooncakes.'],
      ['안내인', 'Subways connect the city. Ferries cross the river.'],
      ['요리사', 'Old lanes have shikumen houses with stone door frames.'],
      ['안내인', 'In the morning, people do tai chi in the park.'],
      ['하나', 'Tell me a fun fact, please!'],
      ['안내인', 'Shanghai means on the sea.'],
      ['안내인', 'In 1919, Korea’s government in exile started in Shanghai.'],
      ['하나', 'So Shanghai is part of Korean history, too!'],
      ['해설', 'Shanghai’s famous foods are xiaolongbao, shengjianbao, and hongshao rou.'],
      ['해설', 'Shanghai has tasty food, old lanes, and tall buildings.'],
    ],
  },

  'ct-osaka-1': {
    title: 'Osaka, Part 1',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 하루토: 'Haruto' },
    outro: [
      'Did you enjoy our first day in Osaka?',
      'Why was Osaka called the kitchen of the nation?',
      'What nickname would you give your town?',
    ],
    lines: [
      ['해설', 'Hana and the Guide arrived in Osaka, Japan.'],
      ['하나', 'Where is Osaka?'],
      ['안내인', 'It is on Honshu, the biggest island of Japan.'],
      ['안내인', 'It faces Osaka Bay. The Yodo River flows through it.'],
      ['안내인', 'Osaka has four seasons. Summer is hot and sticky.'],
      ['하루토', 'Maido! I am Haruto. Welcome to Osaka!'],
      ['안내인', 'Shopkeepers in Osaka often say maido as a friendly hello.'],
      ['해설', 'The Guide told the story of Osaka.'],
      ['안내인', 'Long ago, this place was called Naniwa.'],
      ['안내인', 'In the 600s, Naniwa was a capital for a while.'],
      ['안내인', 'In the late 1500s, Toyotomi Hideyoshi built Osaka Castle.'],
      ['하루토', 'Later, Osaka was called the kitchen of the nation.'],
      ['안내인', 'In 1970, Osaka held the first World Expo in Asia.'],
      ['해설', 'Then they visited three famous places.'],
      ['하루토', 'First, Osaka Castle. Stone walls and water surround it.'],
      ['안내인', 'The main tower was rebuilt in 1931.'],
      ['하루토', 'Second, Dotonbori. Food shops line the canal.'],
      ['하나', 'The big signs are so bright!'],
      ['안내인', 'Third, Tsutenkaku Tower in Shinsekai.'],
      ['하루토', 'From the top, you can see the whole city.'],
      ['해설', 'Osaka was once Naniwa. It was a great trading city.'],
      ['해설', 'Next time, we will learn about food and life in Osaka.'],
    ],
  },

  'ct-osaka-2': {
    title: 'Osaka, Part 2',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 상인: 'Seller' },
    outro: [
      'Was our food trip in Osaka tasty?',
      'Why do people dip kushikatsu in the sauce only once?',
      'What table rules do you keep with your friends?',
    ],
    lines: [
      ['해설', 'Last time, Hana learned about Osaka’s history and castle.'],
      ['해설', 'Today, they walked down a long covered shopping street.'],
      ['상인', 'Maido! Try some takoyaki.'],
      ['상인', 'There is octopus inside. We turn the balls with a pick.'],
      ['하나', 'Round and soft! Hot, hot!'],
      ['상인', 'Second, okonomiyaki. It has batter and lots of cabbage.'],
      ['안내인', 'It cooks on a hot plate. Sauce and fish flakes go on top.'],
      ['하나', 'The fish flakes are dancing!'],
      ['상인', 'Third, kushikatsu. Meat and vegetables are fried on sticks.'],
      ['안내인', 'Dip only once in the shared sauce. That is the rule.'],
      ['안내인', 'In July, the Tenjin Festival has boats on the river.'],
      ['상인', 'At night, fireworks light up the sky. Boom, boom!'],
      ['안내인', 'Osaka people are known for loving jokes and laughter.'],
      ['안내인', 'Manzai is a funny show with two talkers.'],
      ['상인', 'We ride trains and shop at covered shopping streets.'],
      ['안내인', 'Many people stand on the right on escalators here.'],
      ['하나', 'Do you have a fun fact?'],
      ['안내인', 'Kuidaore means eating until you fall down.'],
      ['안내인', 'Osaka has many rivers and canals. It is a water city.'],
      ['해설', 'Osaka’s famous foods are takoyaki, okonomiyaki, and kushikatsu.'],
      ['해설', 'Osaka is a friendly city full of food and laughter.'],
    ],
  },

  'ct-singapore-1': {
    title: 'Singapore, Part 1',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 아이샤: 'Aisha' },
    outro: [
      'Did you enjoy our first day in Singapore?',
      'How did a small island become a busy port?',
      'If you named a city, which animal would you choose?',
    ],
    lines: [
      ['해설', 'Hana and the Guide arrived in Singapore, near the equator.'],
      ['하나', 'Is Singapore a city or a country?'],
      ['안내인', 'Both! It is a city-state. The city is the country.'],
      ['안내인', 'It is a small island at the tip of the Malay Peninsula.'],
      ['안내인', 'It is hot and wet all year. Showers come often.'],
      ['아이샤', 'Selamat pagi! That means good morning in Malay.'],
      ['안내인', 'People here use English, Malay, Chinese, and Tamil.'],
      ['해설', 'The Guide told the story of Singapore.'],
      ['아이샤', 'A legend says a prince saw a lion-like animal here.'],
      ['안내인', 'So the name Singapura means lion city.'],
      ['안내인', 'In 1819, Raffles from Britain opened a trading port.'],
      ['안내인', 'Ships and people came, and the port grew big.'],
      ['안내인', 'In 1963, it joined Malaysia. In 1965, it became independent.'],
      ['해설', 'Then they visited three famous places.'],
      ['아이샤', 'First, the Merlion. It has a lion head and a fish body.'],
      ['하나', 'Water shoots out of its mouth!'],
      ['안내인', 'Second, Gardens by the Bay. It is a big garden by the sea.'],
      ['아이샤', 'Giant tree towers glow at night.'],
      ['안내인', 'Third, the Singapore Botanic Gardens. They are over 160 years old.'],
      ['안내인', 'In 2015, they became a UNESCO World Heritage Site.'],
      ['해설', 'Singapore became independent in 1965. Its name means lion city.'],
      ['해설', 'Next time, we will learn about food and life in Singapore.'],
    ],
  },

  'ct-singapore-2': {
    title: 'Singapore, Part 2',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 요리사: 'Cook' },
    outro: [
      'Was our food trip in Singapore yummy?',
      'Why does a hawker center have food from many cultures?',
      'What food would you share at a festival with friends?',
    ],
    lines: [
      ['해설', 'Last time, Hana learned about Singapore’s history and gardens.'],
      ['해설', 'Today, they went to a hawker center full of food stalls.'],
      ['안내인', 'In 2020, hawker culture joined the UNESCO heritage list.'],
      ['요리사', 'Welcome! First, try chicken rice.'],
      ['요리사', 'We cook the rice in chicken soup.'],
      ['안내인', 'Dip the chicken in chili or ginger sauce.'],
      ['요리사', 'Second, chili crab. The sauce is sweet and spicy.'],
      ['안내인', 'Dip fried buns in the sauce.'],
      ['요리사', 'Third, laksa. It is spicy noodle soup with coconut milk.'],
      ['하나', 'Soft and a little spicy. Slurp!'],
      ['안내인', 'Chinese, Malay, Indian, and other people live here together.'],
      ['안내인', 'They share holidays like Lunar New Year, Hari Raya, and Deepavali.'],
      ['요리사', 'In October or November, Deepavali lights little lamps.'],
      ['안내인', 'People ride trains and buses. Many live in tall public flats.'],
      ['안내인', 'Kids study in English and learn their family language, too.'],
      ['하나', 'Tell me a fun fact, please!'],
      ['요리사', 'People save a seat with a pack of tissues.'],
      ['안내인', 'In 1992, Singapore made a law to stop selling gum.'],
      ['해설', 'Singapore’s famous foods are chicken rice, chili crab, and laksa.'],
      ['해설', 'Singapore is a green city-state where many cultures live together.'],
    ],
  },
};
