// 영어 학습용 원고: 세계 도시 탐방 (아메리카·오세아니아). 문장은 자체 집필.
// 키 = stories/city-d.js 의 이야기 id. lines 의 첫 칸은 원래 이야기 cast 의 한국어 이름 그대로.
export default {
  'ct-newyork-1': {
    title: 'New York, Part 1',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 에밀리: 'Emily' },
    outro: [
      'Did you enjoy the trip to New York?',
      'Why do people from many countries live in New York?',
      'Which place in New York would you visit first?',
    ],
    lines: [
      ['해설', 'Today Hana and the Guide arrived in New York.'],
      ['하나', 'Wow! The buildings almost touch the sky!'],
      ['안내인', 'This is New York, the biggest city in the United States.'],
      ['안내인', 'It is in North America, where a river meets the sea.'],
      ['안내인', 'The Hudson River flows into the Atlantic Ocean here.'],
      ['해설', 'Summers are hot, and winters are cold and snowy.'],
      ['에밀리', 'Hello! I am Emily. I live in New York.'],
      ['안내인', 'Long ago, the Lenape people lived on this land.'],
      ['안내인', 'About four hundred years ago, Dutch people built a town here.'],
      ['안내인', 'Later, the English took it and named it New York.'],
      ['에밀리', 'Many people came here on big ships from far away.'],
      ['하나', 'So people from many countries live here together!'],
      ['해설', 'Now let’s visit three famous places.'],
      ['안내인', 'First, the Statue of Liberty. It was a gift from France.'],
      ['에밀리', 'She holds up a torch to welcome people from the sea.'],
      ['안내인', 'Second, Central Park. It is a big park among tall buildings.'],
      ['에밀리', 'In winter, we go ice skating there!'],
      ['안내인', 'Third, Times Square. Big bright signs shine all night.'],
      ['하나', 'It is night, but it is bright like day!'],
      ['해설', 'New York grew from a small Dutch town into a big city.'],
      ['해설', 'The Statue of Liberty, Central Park, and Times Square are famous.'],
    ],
  },

  'ct-newyork-2': {
    title: 'New York, Part 2',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 상인: 'Seller', 에밀리: 'Emily' },
    outro: [
      'Did you like the food in New York?',
      'Why can you find food from many countries in New York?',
      'What nickname would you give your town?',
    ],
    lines: [
      ['해설', 'Last time, Hana saw the famous places in New York.'],
      ['하나', 'Today I want to eat New York food!'],
      ['안내인', 'First, a bagel. People often eat it for breakfast.'],
      ['안내인', 'The dough is boiled first. Then it is baked.'],
      ['에밀리', 'Cut it in half and add cream cheese. Yum!'],
      ['안내인', 'Second, New York pizza. The slices are thin and big.'],
      ['에밀리', 'Fold your slice in half like this!'],
      ['상인', 'Hot dogs! Hot dogs with mustard!'],
      ['안내인', 'Third, hot dogs from street carts.'],
      ['하나', 'Food tastes better when we walk and eat!'],
      ['해설', 'People from all over the world live in New York.'],
      ['상인', 'My street has Chinese, Italian, and Korean food.'],
      ['안내인', 'On Thanksgiving, giant balloons float down the street.'],
      ['에밀리', 'On New Year’s Eve, a shiny ball comes down.'],
      ['하나', 'Let’s count down together! Ten, nine, eight!'],
      ['안내인', 'Many people ride the subway. It runs at night, too.'],
      ['상인', 'Yellow taxis are everywhere. Just raise your hand!'],
      ['에밀리', 'I ride a yellow school bus to school.'],
      ['안내인', 'Here is a fun fact. New York’s nickname is the Big Apple.'],
      ['하나', 'Is it because the city is sweet like an apple?'],
      ['안내인', 'Nobody knows for sure. People just love this city.'],
      ['해설', 'Bagels, pizza, and hot dogs are New York foods.'],
      ['해설', 'New York is a city where many people live together.'],
    ],
  },

  'ct-mexicocity-1': {
    title: 'Mexico City, Part 1',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 루시아: 'Lucia' },
    outro: [
      'Did you enjoy the trip to Mexico City?',
      'Where did the Aztec people first build their city?',
      'What would you like to see from a colorful boat?',
    ],
    lines: [
      ['해설', 'Today Hana and the Guide came to Mexico City.'],
      ['하나', 'I can see high mountains. Where are we?'],
      ['안내인', 'This is Mexico City, the capital of Mexico.'],
      ['안내인', 'It is in a wide valley with mountains and volcanoes.'],
      ['해설', 'The city is high up, so the weather is mild.'],
      ['루시아', 'Hola! I am Lucia. Hola means hello in Spanish.'],
      ['안내인', 'Long ago, there was a big lake here.'],
      ['안내인', 'About seven hundred years ago, the Aztecs built a city here.'],
      ['안내인', 'They built it on an island in the lake.'],
      ['루시아', 'A legend says they saw an eagle on a cactus.'],
      ['루시아', 'That eagle is on the Mexican flag today!'],
      ['안내인', 'In the 1500s, people from Spain came and took the city.'],
      ['안내인', 'They built a new city, and the lake slowly disappeared.'],
      ['안내인', 'About two hundred years ago, Mexico became free from Spain.'],
      ['해설', 'Now let’s visit three famous places.'],
      ['안내인', 'First, the Zocalo. It is a very big square.'],
      ['안내인', 'Second, the Templo Mayor. It was a great Aztec temple.'],
      ['하나', 'An old city was hiding under the ground!'],
      ['안내인', 'Third, Xochimilco. Old water paths from the lake are still here.'],
      ['루시아', 'We can ride colorful boats along the water.'],
      ['하나', 'The boats look like rainbows!'],
      ['해설', 'Mexico City began as an Aztec city on a lake.'],
      ['해설', 'The Zocalo, Templo Mayor, and Xochimilco are famous places.'],
    ],
  },

  'ct-mexicocity-2': {
    title: 'Mexico City, Part 2',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 요리사: 'Cook', 루시아: 'Lucia' },
    outro: [
      'Did you like the food and festivals of Mexico City?',
      'How do people remember their family on the Day of the Dead?',
      'What food does your family eat on holidays?',
    ],
    lines: [
      ['해설', 'Last time, Hana learned about the city on a lake.'],
      ['하나', 'Something smells good! What is that?'],
      ['요리사', 'Hola! These are tacos. Try one!'],
      ['안내인', 'A taco is a thin corn tortilla with meat and vegetables.'],
      ['요리사', 'Fold it and add lime and salsa.'],
      ['하나', 'It is a little spicy and fresh!'],
      ['안내인', 'Long, long ago, people in Mexico first grew corn.'],
      ['안내인', 'Second, tamales. Corn dough is wrapped in corn husks and steamed.'],
      ['안내인', 'Third, mole. It is a thick chili sauce. Some have chocolate!'],
      ['하나', 'Chocolate sauce on meat? That is new to me!'],
      ['안내인', 'In early November, there is the Day of the Dead.'],
      ['루시아', 'We remember family members who have died.'],
      ['루시아', 'We decorate with photos, food, and orange flowers.'],
      ['하나', 'It is like Chuseok in Korea!'],
      ['안내인', 'Mariachi bands sing and play guitars in the square.'],
      ['루시아', 'The markets are full of fruit, chilies, and flowers.'],
      ['안내인', 'Each subway station has its own little picture sign.'],
      ['안내인', 'Here is a fun fact. The city is slowly sinking.'],
      ['안내인', 'That is because it stands on soft old lake land.'],
      ['루시아', 'A smiling salamander, the axolotl, lives in Xochimilco.'],
      ['해설', 'Tacos, tamales, and mole are Mexico City foods.'],
      ['해설', 'Mexico City is full of corn, festivals, and old stories.'],
    ],
  },

  'ct-cusco-1': {
    title: 'Cusco, Part 1',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 호세: 'Jose' },
    outro: [
      'Did you enjoy the trip to Cusco?',
      'What did the Spanish build on top of the Inca walls?',
      'How would you move a very big stone?',
    ],
    lines: [
      ['해설', 'Today Hana and the Guide arrived in Cusco, Peru.'],
      ['하나', 'I am out of breath after a short walk.'],
      ['안내인', 'Cusco is very high in the Andes Mountains.'],
      ['안내인', 'It is in South America. Walk slowly and drink water.'],
      ['해설', 'Days are sunny and strong. Nights are chilly.'],
      ['호세', 'Buenos dias! I am Jose. It means good morning.'],
      ['안내인', 'People here speak Spanish and also Quechua.'],
      ['안내인', 'Cusco was the capital of the Inca Empire.'],
      ['호세', 'A legend says the first Inca king started this city.'],
      ['안내인', 'In the 1400s, the Incas ruled much of the Andes.'],
      ['안내인', 'They built long roads over the mountains.'],
      ['안내인', 'In the 1500s, people from Spain took the city.'],
      ['안내인', 'They built churches and houses on top of Inca walls.'],
      ['호세', 'In big earthquakes, the old Inca walls stayed strong.'],
      ['해설', 'Now let’s visit three famous places.'],
      ['안내인', 'First, the Plaza de Armas. It is the main square.'],
      ['안내인', 'Second, the stone with twelve corners.'],
      ['하나', 'The stones fit so tightly! No gaps at all!'],
      ['안내인', 'Third, Sacsayhuaman. It has zigzag walls of giant stones.'],
      ['호세', 'People still wonder how they moved those stones.'],
      ['해설', 'Cusco was the Inca capital long ago.'],
      ['해설', 'The main square, the twelve-cornered stone, and Sacsayhuaman are famous.'],
    ],
  },

  'ct-cusco-2': {
    title: 'Cusco, Part 2',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 할머니: 'Grandma', 호세: 'Jose' },
    outro: [
      'Did you like the food and life in Cusco?',
      'What did the Incas use instead of letters to record numbers?',
      'What is your favorite potato dish?',
    ],
    lines: [
      ['해설', 'Last time, Hana visited Cusco, the old Inca capital.'],
      ['하나', 'So many potatoes! They are all different colors!'],
      ['안내인', 'People first grew potatoes long ago in the Andes.'],
      ['할머니', 'We have yellow, purple, and bumpy potatoes.'],
      ['안내인', 'First, chuno. Potatoes are frozen and dried again and again.'],
      ['할머니', 'They keep for a long time. We put them in soup.'],
      ['안내인', 'Second, choclo. It is corn with very big kernels.'],
      ['하나', 'Each kernel is bigger than my fingernail!'],
      ['안내인', 'Third, chicha morada. It is a purple corn drink.'],
      ['호세', 'It has fruit and cinnamon. It is sweet!'],
      ['안내인', 'Every June, there is a sun festival called Inti Raymi.'],
      ['호세', 'People wear bright clothes, dance, and march.'],
      ['할머니', 'Look at my cloth. I made it with alpaca wool.'],
      ['안내인', 'People here have raised llamas and alpacas for a long time.'],
      ['안내인', 'Alpacas give wool. Llamas carry heavy bags.'],
      ['호세', 'I help my mom at the market. It is always busy.'],
      ['할머니', 'The market sells fruit juice and hot soup.'],
      ['안내인', 'Here is a fun fact. The Incas used knotted strings.'],
      ['안내인', 'These strings were called quipu. They recorded numbers.'],
      ['하나', 'Counting with knots! How clever!'],
      ['해설', 'Chuno, choclo, and chicha morada are Cusco foods.'],
      ['해설', 'Cusco keeps the old ways of the Incas and the Andes.'],
    ],
  },

  'ct-rio-1': {
    title: 'Rio de Janeiro, Part 1',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 주앙: 'Joao' },
    outro: [
      'Did you enjoy the trip to Rio?',
      'What does the name Rio de Janeiro mean?',
      'What would you like to see from a cable car?',
    ],
    lines: [
      ['해설', 'Today Hana and the Guide came to Rio de Janeiro, Brazil.'],
      ['하나', 'Wow! Pointy mountains stand next to the sea!'],
      ['안내인', 'Rio is in South America, by the Atlantic Ocean.'],
      ['안내인', 'The name is long, so people just say Rio.'],
      ['해설', 'Rio is warm all year. Summers are hot and rainy.'],
      ['주앙', 'Bom dia! I am Joao. It means good morning.'],
      ['주앙', 'People in Brazil speak Portuguese.'],
      ['안내인', 'Long ago, native people lived here.'],
      ['안내인', 'About five hundred years ago, Portuguese ships came in January.'],
      ['안내인', 'People say they thought the bay was a river.'],
      ['하나', 'So Rio de Janeiro means River of January!'],
      ['안내인', 'About two hundred years ago, the Portuguese king moved here.'],
      ['안내인', 'Rio was the capital of Brazil for a long time.'],
      ['안내인', 'In 1960, the capital moved to Brasilia.'],
      ['해설', 'Now let’s visit three famous places.'],
      ['안내인', 'First, the big statue of Christ on a high hill.'],
      ['주앙', 'His arms are wide open, like a big hug.'],
      ['안내인', 'Second, Sugarloaf Mountain. It looks like a lump of sugar.'],
      ['하나', 'From the cable car, I can see the sea!'],
      ['안내인', 'Third, Copacabana Beach. It is long and beautiful.'],
      ['주앙', 'The sidewalk has a wavy pattern. Walk on the waves!'],
      ['해설', 'Rio was the capital of Brazil for a long time.'],
      ['해설', 'The statue, Sugarloaf, and Copacabana are famous places.'],
    ],
  },

  'ct-rio-2': {
    title: 'Rio de Janeiro, Part 2',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 상인: 'Seller', 주앙: 'Joao' },
    outro: [
      'Did you like the food and festivals of Rio?',
      'How did the Tijuca Forest grow back?',
      'What would you wear to dance in a parade?',
    ],
    lines: [
      ['해설', 'Last time, Hana visited Rio, the River of January.'],
      ['하나', 'I am hungry. What do people eat in Rio?'],
      ['안내인', 'First, feijoada. It is black beans cooked with meat.'],
      ['상인', 'Eat it with rice and orange slices.'],
      ['하나', 'It is warm and filling!'],
      ['안내인', 'Second, pao de queijo. It is a round cheese bread.'],
      ['주앙', 'It is soft and chewy. Eat it warm!'],
      ['상인', 'Third, acai. It is a purple fruit from the Amazon.'],
      ['안내인', 'It is frozen and blended. Eat it with bananas.'],
      ['하나', 'Cold and sweet! Perfect for a hot day!'],
      ['안내인', 'Rio is famous for its Carnival festival.'],
      ['주앙', 'Samba schools dance and march to the drums. Boom, boom!'],
      ['안내인', 'A samba school is not a real school. It is a dance group.'],
      ['하나', 'My shoulders are dancing, too!'],
      ['안내인', 'Capoeira also comes from Brazil. It mixes dance and martial arts.'],
      ['주앙', 'On weekends, my family goes to the beach.'],
      ['상인', 'I sell cold coconuts. Drink with a straw!'],
      ['안내인', 'People from Rio call themselves Cariocas.'],
      ['안내인', 'Here is a fun fact. Rio has a big forest inside the city.'],
      ['안내인', 'Many trees were cut down. Then people planted them again.'],
      ['하나', 'A jungle in the city! How cool!'],
      ['해설', 'Feijoada, cheese bread, and acai are Rio foods.'],
      ['해설', 'Rio is a city of sea, forest, and samba.'],
    ],
  },

  'ct-sydney-1': {
    title: 'Sydney, Part 1',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 올리비아: 'Olivia' },
    outro: [
      'Did you enjoy the trip to Sydney?',
      'Why are the seasons in Sydney opposite to Korea?',
      'If you designed a building, what shape would it be?',
    ],
    lines: [
      ['해설', 'Today Hana and the Guide came to Sydney, Australia.'],
      ['하나', 'Look! A building with white sails is by the sea!'],
      ['안내인', 'Sydney is on the east coast of Australia, in Oceania.'],
      ['안내인', 'It has a big harbor that opens to the Pacific Ocean.'],
      ['해설', 'Sydney is in the south, so the seasons are opposite.'],
      ['해설', 'December is summer here!'],
      ['올리비아', 'G’day! I am Olivia. G’day means hello.'],
      ['안내인', 'Native people have lived here for many thousands of years.'],
      ['안내인', 'In 1788, ships from Britain came into this harbor.'],
      ['안내인', 'In the 1800s, gold was found nearby.'],
      ['하나', 'Many people came to find gold!'],
      ['올리비아', 'Now people from many countries live here.'],
      ['안내인', 'In 1901, Australia became one country.'],
      ['해설', 'Now let’s visit three famous places.'],
      ['안내인', 'First, the Sydney Opera House. Its roof looks like sails.'],
      ['올리비아', 'A Danish architect designed it. There are concerts inside.'],
      ['안내인', 'Second, the Harbour Bridge. It is a big arch bridge.'],
      ['올리비아', 'Its nickname is the Coathanger!'],
      ['하나', 'It really looks like a giant coat hanger!'],
      ['안내인', 'Third, Bondi Beach. Many people surf the big waves.'],
      ['올리비아', 'One day, I want to ride a big wave.'],
      ['해설', 'Sydney grew from a British town by the harbor in 1788.'],
      ['해설', 'The Opera House, Harbour Bridge, and Bondi Beach are famous.'],
    ],
  },

  'ct-sydney-2': {
    title: 'Sydney, Part 2',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 구조대원: 'Lifeguard', 올리비아: 'Olivia' },
    outro: [
      'Did you like the food and life in Sydney?',
      'Between which flags should you swim at the beach?',
      'What would you do on a summer Christmas?',
    ],
    lines: [
      ['해설', 'Last time, Hana saw the Opera House and the Harbour Bridge.'],
      ['하나', 'Today I want to taste Sydney food!'],
      ['안내인', 'First, a meat pie. It is full of meat inside.'],
      ['올리비아', 'Hold it in your hand and add tomato sauce.'],
      ['안내인', 'Second, a lamington. It is a sponge cake with chocolate.'],
      ['올리비아', 'Then we roll it in coconut.'],
      ['안내인', 'Third, pavlova. It is a baked meringue with cream and fruit.'],
      ['올리비아', 'We often eat it at Christmas.'],
      ['안내인', 'Many people cook meat on barbecues in the park.'],
      ['올리비아', 'Christmas is in summer, so we go to the beach.'],
      ['하나', 'Maybe Santa wears shorts here!'],
      ['안내인', 'At midnight on New Year’s Eve, fireworks fill the harbor.'],
      ['올리비아', 'The night sky is full of colors. Bang, bang!'],
      ['안내인', 'Many people ride ferries across the harbor to work.'],
      ['올리비아', 'At school, we wear hats outside. The sun is strong.'],
      ['구조대원', 'At the beach, swim between the red and yellow flags!'],
      ['구조대원', 'Lifeguards watch that area.'],
      ['하나', 'Okay! I will swim between the flags!'],
      ['안내인', 'Here is a fun fact. Sydney is not the capital.'],
      ['안내인', 'The capital of Australia is Canberra.'],
      ['올리비아', 'In parks, you can hear the kookaburra. It sounds like laughing!'],
      ['해설', 'Meat pies, lamingtons, and pavlova are Sydney foods.'],
      ['해설', 'Sydney is a sunny city by the sea.'],
    ],
  },
};
