// 영어 학습용 원고 (한국 초등 저학년, 영어 초급). 문장은 자체 각색.
// 키 = stories/*.js 의 이야기 id. lines 의 첫 칸은 원래 이야기 cast 의 한국어 이름 그대로.
export default {
  'gr-bremen': {
    title: 'The Bremen Town Musicians',
    names: { 해설: 'Narrator', 당나귀: 'Donkey', 개: 'Dog', 고양이: 'Cat', 수탉: 'Rooster' },
    outro: [
      'Did you like the story?',
      'If you were the Donkey, what friends would you take?',
      'What music do you like to play or sing?',
    ],
    lines: [
      ['해설', 'Once upon a time, there was an old donkey.'],
      ['해설', 'He was old and tired. He could not carry big bags.'],
      ['당나귀', 'I am old now. I will go to Bremen. I will play music there!'],
      ['해설', 'On the road, the donkey saw an old dog.'],
      ['개', 'I am too old to run. I have no home.'],
      ['당나귀', 'Come with me! You can play the drum.'],
      ['개', 'Yes! Woof, woof! Let us go!'],
      ['해설', 'Then they saw a sad old cat.'],
      ['고양이', 'I can not catch mice now. Nobody wants me. Meow.'],
      ['당나귀', 'You sing very well. Come with us!'],
      ['해설', 'Then they saw a rooster on a wall.'],
      ['수탉', 'Cock-a-doodle-doo! I sing loud, but nobody wants me.'],
      ['당나귀', 'Come with us! You can be our singer!'],
      ['해설', 'They walked and walked. Night came in the dark forest.'],
      ['수탉', 'Look! I see a light. There is a house!'],
      ['해설', 'In the house, some bad men were eating lots of food.'],
      ['고양이', 'How can we make them go away?'],
      ['당나귀', 'I have an idea! Let us stand on top of each other!'],
      ['해설', 'Donkey, Dog, Cat, and Rooster stood up tall. Then they sang very loud.'],
      ['해설', 'Hee-haw! Woof! Meow! Cock-a-doodle-doo! The bad men ran away!'],
      ['해설', 'The four friends ate and ate. Then they went to sleep.'],
      ['당나귀', 'We do not need to go to Bremen. This is our home!'],
      ['해설', 'Alone, we are small. Together, we can do big things.'],
    ],
  },

  'gr-red-riding-hood': {
    title: 'Little Red Riding Hood',
    names: { 해설: 'Narrator', 빨간모자: 'Red Riding Hood', 엄마: 'Mom', 늑대: 'Wolf', 할머니: 'Grandma', 나무꾼: 'Woodcutter' },
    outro: [
      'Was that a fun story?',
      'If you were Red Riding Hood, what would you say to the wolf?',
      'Who do you tell when a stranger talks to you?',
    ],
    lines: [
      ['해설', 'Once upon a time, there was a little girl. She always wore a red hood.'],
      ['해설', 'So everyone called her Red Riding Hood.'],
      ['엄마', 'Grandma is sick. Please take her this bread.'],
      ['엄마', 'Stay on the path. Do not talk to strangers.'],
      ['빨간모자', 'Okay, Mom! I will go right to Grandma.'],
      ['해설', 'Red Riding Hood walked into the forest. Then she met a wolf.'],
      ['늑대', 'Hello, little girl. Where are you going?'],
      ['빨간모자', 'I am going to my grandma. She lives by the big tree.'],
      ['늑대', 'Look at the pretty flowers! Pick some for Grandma.'],
      ['해설', 'She forgot what Mom said. She went off the path.'],
      ['해설', 'The wolf ran fast to Grandma’s house.'],
      ['할머니', 'Oh no, a wolf! I will hide in the closet.'],
      ['해설', 'The wolf put on Grandma’s hat. He got into her bed.'],
      ['빨간모자', 'Hi, Grandma! Wow, what big ears you have!'],
      ['늑대', 'The better to hear you with.'],
      ['빨간모자', 'Grandma, what big eyes you have!'],
      ['늑대', 'The better to see you with.'],
      ['해설', 'Then she saw a long furry tail!'],
      ['빨간모자', 'You are not Grandma. You are the wolf! Help! Help!'],
      ['해설', 'A woodcutter heard her. He ran to the house.'],
      ['나무꾼', 'Go away, wolf! Never come back!'],
      ['해설', 'The wolf jumped out the window. He ran far, far away.'],
      ['할머니', 'I am safe! You were very brave.'],
      ['해설', 'Do not go with strangers. Tell a grown-up.'],
    ],
  },

  'gr-elves-shoemaker': {
    title: 'The Elves and the Shoemaker',
    names: { 해설: 'Narrator', 구두장이: 'Shoemaker', 아내: 'Wife', 요정: 'Elf', 손님: 'Customer' },
    outro: [
      'Did you enjoy the story?',
      'If you were the shoemaker, what gift would you make for the elves?',
      'Who helps you every day? How can you say thank you?',
    ],
    lines: [
      ['해설', 'Once upon a time, there was a kind shoemaker.'],
      ['해설', 'He worked hard, but he was very poor.'],
      ['구두장이', 'I have leather for only one pair of shoes.'],
      ['아내', 'It is okay. You can make them tomorrow.'],
      ['해설', 'He cut the leather. Then he went to bed.'],
      ['해설', 'In the morning, he opened his eyes wide.'],
      ['구두장이', 'Look! The shoes are all made!'],
      ['아내', 'Wow! They are so pretty!'],
      ['손님', 'I love these shoes! I will pay a lot for them.'],
      ['해설', 'Every night he cut leather. Every morning, there were new shoes!'],
      ['아내', 'Who is helping us? Let us watch tonight.'],
      ['해설', 'At night, they hid and watched.'],
      ['해설', 'Two little elves came in the window.'],
      ['요정', 'Tap, tap, tap! Let us make shoes!'],
      ['해설', 'But the elves had old clothes. They were cold.'],
      ['아내', 'Poor elves! Let us make them warm clothes.'],
      ['구두장이', 'Good idea! I will make little shoes for them.'],
      ['해설', 'That night, they put the gifts on the table.'],
      ['요정', 'Look! New clothes for us! Thank you, thank you!'],
      ['해설', 'The elves danced and danced. Then they went away.'],
      ['구두장이', 'Thank you, little elves! Goodbye!'],
      ['해설', 'Say thank you. It makes everyone happy.'],
    ],
  },

  'an-ugly-duckling': {
    title: 'The Ugly Duckling',
    names: { 해설: 'Narrator', 엄마오리: 'Mother Duck', 아기새: 'Little Bird', 형오리: 'Big Brother Duck', 할머니: 'Old Woman', 백조: 'Swan' },
    outro: [
      'Did you like the story?',
      'If you were the little bird, how would you feel?',
      'What can you do well? What do you want to learn?',
    ],
    lines: [
      ['해설', 'It was summer. A mother duck sat on her eggs.'],
      ['해설', 'Crack, crack! Little yellow ducks came out.'],
      ['해설', 'But one big egg did not open.'],
      ['엄마오리', 'This egg is so big. I will wait a little more.'],
      ['해설', 'At last, a big gray bird came out.'],
      ['형오리', 'You are big and gray. You do not look like us!'],
      ['아기새', 'I am a duck too. I can swim like you.'],
      ['해설', 'He could swim very well. But the other ducks laughed at him.'],
      ['엄마오리', 'Stop it! You are all my babies.'],
      ['아기새', 'Nobody likes me here. I will go far away.'],
      ['해설', 'He walked far, far away. He was all alone.'],
      ['해설', 'In fall, he saw big white birds in the sky.'],
      ['아기새', 'Wow, they are so pretty! I want to fly like them.'],
      ['해설', 'Then winter came. It was very cold. Snow fell.'],
      ['할머니', 'Oh, poor bird! Come into my warm house.'],
      ['해설', 'Then spring came. The sun was warm.'],
      ['해설', 'The bird opened his wings. He flew up high!'],
      ['백조', 'Hello, friend! Come swim with us!'],
      ['아기새', 'Me? But I am an ugly gray bird.'],
      ['백조', 'Look in the water. You are a white swan like us!'],
      ['아기새', 'I am a swan! I am not alone now.'],
      ['해설', 'We all grow in our own time. Your day will come too.'],
    ],
  },

  'an-emperor-clothes': {
    title: 'The Emperor’s New Clothes',
    names: { 해설: 'Narrator', 임금님: 'Emperor', 재봉사: 'Tailor', 신하: 'Helper', 아이: 'Child' },
    outro: [
      'Was the story funny?',
      'If you were the child, would you say it too?',
      'When did you tell the truth, even when it was hard?',
    ],
    lines: [
      ['해설', 'Once upon a time, there was an emperor. He loved new clothes.'],
      ['해설', 'One day, two tailors came to see him.'],
      ['재봉사', 'We make magic cloth. It is very special.'],
      ['재봉사', 'Silly people can not see it!'],
      ['임금님', 'Wow! Make me new clothes right now!'],
      ['해설', 'The emperor gave them lots of gold. They hid it in their bags.'],
      ['해설', 'Then they made nothing. They only pretended to work.'],
      ['신하', 'I can not see anything! Am I silly?'],
      ['신하', 'Oh, what pretty cloth!'],
      ['해설', 'He did not want to look silly. So he did not tell the truth.'],
      ['재봉사', 'Here are your new clothes. They are light, right?'],
      ['임금님', 'I can not see them. But I will not say it.'],
      ['임금님', 'Yes! These are very good clothes!'],
      ['해설', 'The emperor walked down the street in his new clothes.'],
      ['신하', 'Wow! Nice clothes! Hooray for the emperor!'],
      ['해설', 'Everyone clapped. Nobody told the truth.'],
      ['아이', 'Look! The emperor is in his underwear!'],
      ['해설', 'Then everyone said it. He has no clothes!'],
      ['임금님', 'Oh no! I was tricked!'],
      ['해설', 'The tailors ran away fast.'],
      ['임금님', 'Thank you, child. Now I know the truth is important.'],
      ['해설', 'Say what you really see. The truth is the best.'],
    ],
  },

  'wd-giant-turnip': {
    title: 'The Giant Turnip',
    names: { 해설: 'Narrator', 할아버지: 'Grandpa', 할머니: 'Grandma', 손녀: 'Girl', 강아지: 'Puppy', 생쥐: 'Mouse' },
    outro: [
      'Did you have fun?',
      'If you were the little mouse, what would you say?',
      'What did you do with your family or friends together?',
    ],
    lines: [
      ['해설', 'Once upon a time, Grandpa planted a turnip seed.'],
      ['할아버지', 'Grow, turnip, grow! Grow big and sweet!'],
      ['해설', 'The turnip grew and grew. It got very, very big!'],
      ['할아버지', 'Now I will pull it out. Pull, pull!'],
      ['해설', 'He pulled and pulled. But the turnip did not come out!'],
      ['할아버지', 'Grandma, please come and help me!'],
      ['할머니', 'Okay! I will help you.'],
      ['해설', 'They pulled and pulled. But the turnip did not come out!'],
      ['할머니', 'Come here, my girl! Please help us!'],
      ['손녀', 'Okay, Grandma! I am coming!'],
      ['해설', 'They pulled and pulled. But the turnip did not come out!'],
      ['손녀', 'Puppy, come here! Help us pull!'],
      ['강아지', 'Woof, woof! I am strong!'],
      ['해설', 'Then a cat came too. They pulled and pulled. But the turnip did not come out!'],
      ['할아버지', 'Oh no. We all pulled. It is still there.'],
      ['해설', 'Then a little mouse came.'],
      ['생쥐', 'Squeak! Can I help you?'],
      ['강아지', 'You are so small. But okay, let us try!'],
      ['해설', 'One, two, three! They pulled and pulled and pulled!'],
      ['해설', 'Pop! The big turnip came out! Everyone fell down.'],
      ['손녀', 'We did it! Thank you, little mouse!'],
      ['생쥐', 'Squeak! We all did it together!'],
      ['할머니', 'Let us make turnip soup. We can all eat together!'],
      ['해설', 'Small help is good help. Together, we can do big things.'],
    ],
  },

  'kr-sun-moon': {
    title: 'The Sun and the Moon',
    names: { 해설: 'Narrator', 엄마: 'Mom', 호랑이: 'Tiger', 오빠: 'Brother', 동생: 'Sister' },
    outro: [
      'Did you like this Korean story?',
      'If you were the brother, what would you do?',
      'Do you like the sun or the moon more? Why?',
    ],
    lines: [
      ['해설', 'Long ago in Korea, a mom lived with her son and daughter.'],
      ['해설', 'One day, Mom went to work. She got some rice cakes.'],
      ['엄마', 'Children, lock the door. Wait for me.'],
      ['해설', 'On the way home, a big tiger came out.'],
      ['호랑이', 'Roar! Give me a rice cake!'],
      ['해설', 'Mom gave him one rice cake, then another. He ate them all.'],
      ['엄마', 'No more rice cakes! I will go home another way.'],
      ['해설', 'The tiger went to the children’s house.'],
      ['호랑이', 'Children, it is Mom. Open the door.'],
      ['동생', 'Your voice is funny. You are not Mom!'],
      ['오빠', 'Show us your hand.'],
      ['해설', 'The hand was big and furry.'],
      ['오빠', 'It is a tiger! Run, sister!'],
      ['해설', 'They ran out the back door. They climbed up a tall tree.'],
      ['호랑이', 'How did you get up there?'],
      ['동생', 'Use an ax to climb up!'],
      ['해설', 'Oh no! The tiger started to climb the tree.'],
      ['오빠', 'Please help us! Send down a strong rope!'],
      ['해설', 'A strong rope came down from the sky. The children went up.'],
      ['해설', 'The tiger got an old rope. Snap! He fell down.'],
      ['호랑이', 'Ouch! I will never come back!'],
      ['해설', 'The sister became the sun. The brother became the moon.'],
      ['해설', 'Mom got home safe. She smiled at the sun and the moon.'],
      ['해설', 'Do not open the door for strangers. Ask a grown-up first.'],
    ],
  },

  'kr-heungbu': {
    title: 'Heungbu and Nolbu',
    names: { 해설: 'Narrator', 흥부: 'Heungbu', 놀부: 'Nolbu', 제비: 'Swallow', 도깨비: 'Goblin' },
    outro: [
      'Did you enjoy the story?',
      'If you were Heungbu, would you help Nolbu?',
      'What do you like to share with your friends?',
    ],
    lines: [
      ['해설', 'Long ago in Korea, there were two brothers, Heungbu and Nolbu.'],
      ['해설', 'Nolbu was the big brother. He wanted everything for himself.'],
      ['놀부', 'Heungbu, go away! I will not give you any rice!'],
      ['해설', 'Heungbu was kind, but he was very poor.'],
      ['해설', 'One day, a baby swallow fell from its nest. It hurt its leg.'],
      ['흥부', 'Oh, poor bird! I will help you.'],
      ['제비', 'Tweet, tweet! Thank you! I will not forget you.'],
      ['해설', 'Next spring, the swallow came back with a seed.'],
      ['해설', 'Heungbu planted the seed. Big round gourds grew on the roof.'],
      ['흥부', 'Let us cut open this gourd.'],
      ['해설', 'Crack! Rice and gold came out!'],
      ['흥부', 'Wow! Let us share it with everyone!'],
      ['놀부', 'I want gold too! I will find a swallow.'],
      ['해설', 'Nolbu hurt a baby swallow on purpose. Then he fixed its leg.'],
      ['제비', 'Ouch! That was not nice!'],
      ['해설', 'Next spring, that swallow gave Nolbu a seed too.'],
      ['놀부', 'I will get lots of gold! Let us open it!'],
      ['해설', 'Crack! But goblins jumped out!'],
      ['도깨비', 'You hurt the bird, Nolbu! Now we take your things!'],
      ['놀부', 'Oh no! I was wrong. I have nothing now.'],
      ['흥부', 'Do not worry, brother. Come live with me.'],
      ['놀부', 'I am sorry, Heungbu. Now I will share too.'],
      ['해설', 'Do not be greedy. Sharing makes us happy.'],
    ],
  },

  'kr-green-frog': {
    title: 'The Green Frog',
    names: { 해설: 'Narrator', 엄마: 'Mom Frog', 청개구리: 'Green Frog' },
    outro: [
      'Did you like the story?',
      'If you were the green frog, what would you say to Mom?',
      'What does your mom or dad often tell you?',
    ],
    lines: [
      ['해설', 'Long ago, a mom frog lived by a river. She had a little green frog.'],
      ['해설', 'The green frog always did the opposite.'],
      ['엄마', 'Go play on the hill today.'],
      ['청개구리', 'No! I will play by the river.'],
      ['엄마', 'Frogs say ribbit, ribbit.'],
      ['청개구리', 'Tibbir, tibbir! Tibbir, tibbir!'],
      ['엄마', 'Walk slowly by the water.'],
      ['청개구리', 'No! I will jump and splash!'],
      ['해설', 'Mom said sit down. He stood up. Mom said go to sleep. He opened his eyes.'],
      ['엄마', 'Oh, my baby. When will you listen to me?'],
      ['해설', 'Years went by. Mom frog got very old.'],
      ['해설', 'She had to go far, far away.'],
      ['엄마', 'He always does the opposite. So I will ask for the opposite.'],
      ['엄마', 'Please make a stone tower for me by the river. Not on the hill.'],
      ['청개구리', 'Mom, please do not go!'],
      ['해설', 'Mom went away. The green frog cried and cried.'],
      ['청개구리', 'I never listened to Mom. This time, I will do what she said.'],
      ['해설', 'He made the stone tower by the river.'],
      ['해설', 'But Mom really wanted it on the hill.'],
      ['해설', 'When it rained, the river got very big.'],
      ['청개구리', 'Oh no! The water will take Mom’s stones away!'],
      ['청개구리', 'I am sorry, Mom. I should have listened. Ribbit, ribbit!'],
      ['해설', 'So on rainy days, green frogs still say ribbit, ribbit.'],
      ['해설', 'Grown-ups talk to us with love. Let us listen to them.'],
    ],
  },

  'three-friends': {
    title: 'The Three Friends',
    names: { 해설: 'Narrator', 아저씨: 'Man', 첫째친구: 'First Friend', 둘째친구: 'Second Friend', 셋째친구: 'Third Friend' },
    outro: [
      'Did you like the story?',
      'If you were the man, which friend would you thank?',
      'What good thing did you do today?',
    ],
    lines: [
      ['해설', 'Once there was a man. He had three friends.'],
      ['해설', 'He loved the first friend the most. They were together every day.'],
      ['해설', 'He liked the second friend too. They played sometimes.'],
      ['해설', 'The third friend was always there. But the man did not care much.'],
      ['해설', 'One day, the king called the man to his castle.'],
      ['아저씨', 'Why does the king want me? I am scared.'],
      ['아저씨', 'I do not want to go alone. I will ask my friends.'],
      ['아저씨', 'First friend, will you come with me?'],
      ['첫째친구', 'Sorry. I can not go. Goodbye.'],
      ['아저씨', 'Oh, I loved you the most. But you will not come.'],
      ['아저씨', 'Second friend, will you come with me?'],
      ['둘째친구', 'I will go to the door with you. But I can not go in.'],
      ['아저씨', 'Thank you. But I must go in alone.'],
      ['아저씨', 'Third friend, I am sorry. I was not nice to you.'],
      ['아저씨', 'Can you come with me?'],
      ['셋째친구', 'Yes! I will go all the way. I will tell the king you are good.'],
      ['아저씨', 'Really? Thank you so much!'],
      ['해설', 'The third friend went in with him. He told the king about the man’s good work.'],
      ['해설', 'Who are the three friends? Let me tell you.'],
      ['해설', 'The first friend is money and things. We can not keep them forever.'],
      ['해설', 'The second friend is family and neighbors. They go with us for a while.'],
      ['해설', 'The third friend is the good things we do. They stay with us forever.'],
      ['해설', 'So do good things every day.'],
    ],
  },
};
