// 영어 학습용 원고: 세계 도시 탐방 2차 (아메리카·오세아니아). 문장은 자체 집필.
// 키 = stories/city-h.js 의 이야기 id. lines 의 첫 칸은 원래 이야기 cast 의 한국어 이름 그대로.
export default {
  'ct-vancouver-1': {
    title: 'Vancouver, Part 1',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 에밀리: 'Emily' },
    outro: [
      'Did you enjoy the trip to Vancouver?',
      'Whose name did the city of Vancouver get?',
      'Would you rather visit the sea or the mountains?',
    ],
    lines: [
      ['해설', 'Today Hana and the Guide came to Vancouver, Canada.'],
      ['하나', 'Look! The sea is in front, and mountains are behind!'],
      ['안내인', 'Vancouver is on the west coast of Canada.'],
      ['안내인', 'It faces the Pacific Ocean. The Fraser River flows nearby.'],
      ['안내인', 'Winters are mild here, but it often rains.'],
      ['에밀리', 'Hi! I am Emily. I live in Vancouver.'],
      ['안내인', 'Canada has two official languages, English and French.'],
      ['안내인', 'Native peoples have lived here for thousands of years.'],
      ['에밀리', 'They caught salmon and built houses from big cedar trees.'],
      ['안내인', 'In 1792, a British sailor named George Vancouver came here.'],
      ['하나', 'So the city has his name!'],
      ['안내인', 'The city began in 1886. A big fire burned it that year.'],
      ['안내인', 'In 1887, a train came here from across Canada.'],
      ['안내인', 'In 2010, Vancouver hosted the Winter Olympics.'],
      ['에밀리', 'First, Stanley Park. It is a big forest by the sea.'],
      ['안내인', 'Native people carved the tall totem poles in the park.'],
      ['안내인', 'Second, the Lions Gate Bridge. It hangs from strong cables.'],
      ['에밀리', 'Third, Gastown. It is one of the oldest parts of the city.'],
      ['안내인', 'Its steam clock whistles and puffs steam.'],
      ['하나', 'The clock is singing a song!'],
      ['해설', 'Vancouver became a city in 1886, on old Native land.'],
      ['해설', 'Stanley Park, Lions Gate Bridge, and Gastown are famous.'],
    ],
  },

  'ct-vancouver-2': {
    title: 'Vancouver, Part 2',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 상인: 'Seller' },
    outro: [
      'Did you like the food and life in Vancouver?',
      'What stories did Native people carve on totem poles?',
      'What would you carve on a pole about your family?',
    ],
    lines: [
      ['해설', 'Last time, Hana saw Stanley Park and the steam clock.'],
      ['해설', 'Today she took a small boat to Granville Island Market.'],
      ['상인', 'Welcome! Look at this fresh salmon!'],
      ['안내인', 'First, salmon. Many salmon swim in these rivers and seas.'],
      ['상인', 'We cook it on a cedar board. It smells like wood.'],
      ['안내인', 'Native people smoked salmon to keep it for a long time.'],
      ['상인', 'Second, the Nanaimo bar. Nanaimo is a nearby city.'],
      ['안내인', 'It has a crumb bottom, sweet cream, and chocolate on top.'],
      ['안내인', 'You don’t bake it. You chill it and cut it.'],
      ['상인', 'Third, dim sum. These are small dumplings in bamboo baskets.'],
      ['안내인', 'Many people from China live here, so dim sum is popular.'],
      ['안내인', 'Totem poles tell family stories with animal shapes.'],
      ['하나', 'I see an eagle and a bear!'],
      ['안내인', 'In January or February, Chinatown has a New Year parade.'],
      ['상인', 'Many people thank the driver when they get off the bus.'],
      ['안내인', 'The SkyTrain runs by itself. It has no driver!'],
      ['안내인', 'People ride the SeaBus boat across the water to work.'],
      ['안내인', 'Some kids take their school classes in French.'],
      ['안내인', 'Here is a fun fact. You can ski and go to the beach.'],
      ['안내인', 'On a nice day, you can do both in one day!'],
      ['해설', 'Salmon, Nanaimo bars, and dim sum are Vancouver foods.'],
      ['해설', 'Vancouver is a city of sea, mountains, and many cultures.'],
    ],
  },

  'ct-quebec-1': {
    title: 'Quebec City, Part 1',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 루이: 'Louis' },
    outro: [
      'Did you enjoy the trip to Quebec City?',
      'What does the name Quebec mean?',
      'What would you look for on an old city wall?',
    ],
    lines: [
      ['해설', 'Today Hana and the Guide came to Quebec City, Canada.'],
      ['하나', 'Look! There is a stone wall on the hill!'],
      ['안내인', 'Quebec City is in eastern Canada, in North America.'],
      ['안내인', 'It sits on a high cliff by the Saint Lawrence River.'],
      ['안내인', 'Winters are very cold and snowy. Summers are warm.'],
      ['루이', 'Bonjour! I am Louis. People here speak French.'],
      ['안내인', 'Native people lived here long ago.'],
      ['안내인', 'Quebec may mean where the river gets narrow.'],
      ['안내인', 'In 1608, a Frenchman named Champlain built a town here.'],
      ['루이', 'That is why we still speak French!'],
      ['안내인', 'In 1759, Britain and France fought in a field nearby.'],
      ['안내인', 'Britain ruled after that, but people kept French culture.'],
      ['안내인', 'In 1985, the old town became a World Heritage Site.'],
      ['루이', 'First, the Chateau Frontenac. It is a hotel like a castle.'],
      ['안내인', 'You can see its green roofs from all over the city.'],
      ['안내인', 'Second, Petit Champlain Street. It is a narrow old street.'],
      ['루이', 'A little cable train goes up the steep hill.'],
      ['안내인', 'Third, Montmorency Falls. They are taller than Niagara Falls.'],
      ['하나', 'Wow! The water goes splash, splash!'],
      ['안내인', 'Few cities in North America still have their old walls.'],
      ['해설', 'French people built Quebec City on a cliff in 1608.'],
      ['해설', 'The Chateau, Petit Champlain, and the falls are famous.'],
    ],
  },

  'ct-quebec-2': {
    title: 'Quebec City, Part 2',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 요리사: 'Cook' },
    outro: [
      'Did you like the food and winter in Quebec City?',
      'Where do people pour hot syrup to make maple taffy?',
      'What would you like to do on a snowy day?',
    ],
    lines: [
      ['해설', 'Last time, Hana saw the old walls and the big falls.'],
      ['요리사', 'Bonjour! Would you like some hot poutine?'],
      ['안내인', 'Poutine started in Quebec.'],
      ['요리사', 'It is fries with cheese curds and thick brown gravy.'],
      ['하나', 'The cheese squeaks when I chew it!'],
      ['안내인', 'Second, maple syrup. It comes from maple tree sap.'],
      ['요리사', 'Around March, people boil the sap in little forest cabins.'],
      ['안내인', 'They pour hot syrup on clean snow. It gets soft and chewy.'],
      ['요리사', 'Then roll it on a stick. That is maple taffy!'],
      ['하나', 'Candy made on snow! So sweet!'],
      ['요리사', 'Third, tourtiere. It is a pie with ground meat.'],
      ['안내인', 'Families often share it around Christmas.'],
      ['안내인', 'In late January and February, the Winter Carnival begins.'],
      ['요리사', 'A snowman in a red hat welcomes everyone.'],
      ['안내인', 'People race canoes on the icy river!'],
      ['하나', 'Canoes on ice? How brave!'],
      ['안내인', 'Ferries cross the river, even in winter.'],
      ['안내인', 'Most school classes here are in French.'],
      ['요리사', 'When you say merci, we say bienvenue. It means you’re welcome.'],
      ['안내인', 'Fun fact! Quebec car plates say I remember in French.'],
      ['해설', 'Poutine, maple taffy, and tourtiere are Quebec foods.'],
      ['해설', 'Quebec City is a city of French, snow, and festivals.'],
    ],
  },

  'ct-buenosaires-1': {
    title: 'Buenos Aires, Part 1',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 마테오: 'Mateo' },
    outro: [
      'Did you enjoy the trip to Buenos Aires?',
      'Why are the houses in La Boca so colorful?',
      'What colors would you paint the houses on your street?',
    ],
    lines: [
      ['해설', 'Today Hana and the Guide came to Buenos Aires, Argentina.'],
      ['하나', 'The river is as wide as the sea!'],
      ['안내인', 'Buenos Aires is the capital of Argentina, in South America.'],
      ['안내인', 'It is by the wide Rio de la Plata.'],
      ['안내인', 'Summers are hot and wet. Winters are mostly mild.'],
      ['마테오', 'Hola! I am Mateo. Hola means hello in Spanish.'],
      ['안내인', 'Buenos Aires means good air or good winds.'],
      ['안내인', 'In the 1500s, people from Spain built a city here.'],
      ['안내인', 'In May 1810, the people here began to rule themselves.'],
      ['마테오', 'So our main square is called May Square!'],
      ['안내인', 'In 1816, Argentina said it was free from Spain.'],
      ['안내인', 'Later, many people came by ship from Italy and Spain.'],
      ['하나', 'So many cultures mixed together here!'],
      ['마테오', 'First, May Square. The president’s pink house is there.'],
      ['안내인', 'It is called the Casa Rosada. That means pink house.'],
      ['안내인', 'Second, Caminito Street in La Boca, by the port.'],
      ['마테오', 'People say they used leftover boat paint on the houses.'],
      ['하나', 'Red, yellow, and blue! Like colored paper!'],
      ['안내인', 'Third, the Colon Theater. It opened in 1908.'],
      ['안내인', 'Music sounds beautiful inside this theater.'],
      ['해설', 'Buenos Aires is the capital of Argentina, free since 1816.'],
      ['해설', 'May Square, Caminito, and the Colon Theater are famous.'],
    ],
  },

  'ct-buenosaires-2': {
    title: 'Buenos Aires, Part 2',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 할머니: 'Grandma' },
    outro: [
      'Did you like the food and tango in Buenos Aires?',
      'What do you say when you want no more mate?',
      'What food do you want when your family gets together?',
    ],
    lines: [
      ['해설', 'Last time, Hana walked down colorful Caminito Street.'],
      ['해설', 'Today a grandma invited her home.'],
      ['할머니', 'Welcome! I am cooking asado in the yard.'],
      ['안내인', 'Asado is beef cooked slowly on a grill over hot coals.'],
      ['할머니', 'On weekends, the whole family eats and talks for hours.'],
      ['할머니', 'Second, empanadas. They are baked pastries with meat inside.'],
      ['안내인', 'You hold them in your hand. The edges are folded nicely.'],
      ['할머니', 'Third, dulce de leche. We cook milk and sugar for hours.'],
      ['안내인', 'It is sweet like caramel. People spread it on bread.'],
      ['할머니', 'Now, some mate tea. We share one cup together.'],
      ['안내인', 'When you want no more, just say gracias.'],
      ['하나', 'Thank you also means no more, thank you!'],
      ['안내인', 'Listen! That music is tango.'],
      ['안내인', 'Tango began in the port towns here in the late 1800s.'],
      ['안내인', 'Two people dance close together to bandoneon music.'],
      ['할머니', 'Around August, there is a big tango festival.'],
      ['안내인', 'In 1913, the first subway in South America opened here.'],
      ['할머니', 'Kids at public schools wear white coats over their clothes.'],
      ['안내인', 'Fun fact! People here often eat dinner after nine at night.'],
      ['하나', 'I am sleepy by then!'],
      ['해설', 'Asado, empanadas, and dulce de leche are Buenos Aires foods.'],
      ['해설', 'Buenos Aires is a port city full of tango and stories.'],
    ],
  },

  'ct-honolulu-1': {
    title: 'Honolulu, Part 1',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 카이: 'Kai' },
    outro: [
      'Aloha! Did you enjoy the trip to Honolulu?',
      'What did old Hawaiian sailors watch to find their way?',
      'If you followed the stars, which star would you look for?',
    ],
    lines: [
      ['해설', 'Today Hana and the Guide came to Honolulu, Hawaii.'],
      ['하나', 'The sea is sparkling, and the palm trees are waving!'],
      ['안내인', 'Honolulu is on Oahu Island, in the middle of the Pacific.'],
      ['안내인', 'Hawaii is a state of the United States.'],
      ['안내인', 'It is warm all year, with cool winds.'],
      ['카이', 'Aloha! I am Kai. I live in Honolulu.'],
      ['안내인', 'Aloha means hello. It also means love and kindness.'],
      ['안내인', 'Long ago, Polynesian people came here in big canoes.'],
      ['카이', 'They watched the stars, waves, and birds to find the way.'],
      ['하나', 'They crossed the big sea without a map!'],
      ['안내인', 'Around 1810, King Kamehameha united the islands.'],
      ['안내인', 'Later, Honolulu became the capital of the Hawaiian Kingdom.'],
      ['안내인', 'In 1893, the kingdom ended. Later, America took the islands.'],
      ['안내인', 'In 1959, Hawaii became the fiftieth state.'],
      ['카이', 'First, Iolani Palace. Hawaiian kings and queens lived there.'],
      ['안내인', 'It was built in 1882. It had electric lights early.'],
      ['안내인', 'Second, Waikiki Beach. Many people surf here.'],
      ['카이', 'Surfing was a game of the old Hawaiians.'],
      ['안내인', 'Third, Diamond Head. It is an old volcano crater.'],
      ['하나', 'From the top, I can see the sea and the city!'],
      ['해설', 'Honolulu was the capital of the Hawaiian Kingdom.'],
      ['해설', 'Iolani Palace, Waikiki, and Diamond Head are famous.'],
    ],
  },

  'ct-honolulu-2': {
    title: 'Honolulu, Part 2',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 할머니: 'Grandma' },
    outro: [
      'Mahalo! Did you like the food and culture of Honolulu?',
      'What do hula dancers tell with their hands?',
      'Like a lei, what gift would you give to say thanks?',
    ],
    lines: [
      ['해설', 'Last time, Hana saw Iolani Palace and Waikiki.'],
      ['할머니', 'Aloha! This is a lei. It says welcome.'],
      ['안내인', 'A lei is made of flowers, leaves, or shells.'],
      ['안내인', 'Don’t take it off right away in front of the giver.'],
      ['할머니', 'First, poi. We cook and pound taro root.'],
      ['하나', 'It is purple! It tastes mild and a little sour.'],
      ['안내인', 'Poi was an important food for Hawaiians long ago.'],
      ['할머니', 'Second, poke. It is raw fish cut into small cubes.'],
      ['안내인', 'Some people add salt, seaweed, and sesame oil.'],
      ['할머니', 'Third, kalua pig. We cook it in an oven in the ground.'],
      ['안내인', 'Hot stones and leaves cook it slowly. It gets soft.'],
      ['안내인', 'Hula is a dance that tells stories with songs and hands.'],
      ['할머니', 'Wavy hands mean the sea. High hands mean the sky.'],
      ['안내인', 'May first is Lei Day in Hawaii.'],
      ['안내인', 'Hawaiian language and hula almost disappeared once.'],
      ['할머니', 'Now some schools teach in Hawaiian.'],
      ['안내인', 'Many people take off their shoes before going inside.'],
      ['안내인', 'Fun fact! Hawaiian uses only a few letters.'],
      ['할머니', 'Thank you is mahalo.'],
      ['하나', 'Mahalo, Grandma! I love my lei.'],
      ['해설', 'Poi, poke, and kalua pig are Honolulu foods.'],
      ['해설', 'Honolulu is a city where aloha and Hawaiian culture live on.'],
    ],
  },

  'ct-auckland-1': {
    title: 'Auckland, Part 1',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 아로하: 'Aroha' },
    outro: [
      'Kia ora! Did you enjoy the trip to Auckland?',
      'What did the Maori build on the volcano hills?',
      'If you climbed a volcano hill, what would you look at first?',
    ],
    lines: [
      ['해설', 'Today Hana and the Guide came to Auckland, New Zealand.'],
      ['하나', 'Look! So many white sailboats in the harbor!'],
      ['안내인', 'Auckland is a city on the North Island of New Zealand.'],
      ['안내인', 'The land is narrow, so it has two harbors.'],
      ['안내인', 'The weather is mild, but sun and rain change quickly.'],
      ['아로하', 'Kia ora! I am Aroha. Kia ora is a Maori greeting.'],
      ['안내인', 'It means be well.'],
      ['안내인', 'Hundreds of years ago, Maori people came by canoe.'],
      ['안내인', 'They built villages with fences on the volcano hills.'],
      ['아로하', 'You can still see their old garden steps on the hills.'],
      ['안내인', 'In 1840, Maori chiefs and Britain signed the Treaty of Waitangi.'],
      ['안내인', 'The next year, Auckland became the capital.'],
      ['안내인', 'In 1865, the capital moved to Wellington.'],
      ['안내인', 'First, the Sky Tower. You can see it from everywhere.'],
      ['아로하', 'Second, Maungawhau. It is also called Mount Eden.'],
      ['안내인', 'It is an old volcano crater. It is special to Maori people.'],
      ['아로하', 'So we don’t walk inside the crater.'],
      ['안내인', 'Third, Rangitoto Island. A volcano made it about 600 years ago.'],
      ['하나', 'It looks like a flat hat!'],
      ['안내인', 'Auckland is built on many small volcanoes.'],
      ['해설', 'Auckland, in New Zealand, was the capital from 1841.'],
      ['해설', 'The Sky Tower, Maungawhau, and Rangitoto are famous.'],
    ],
  },

  'ct-auckland-2': {
    title: 'Auckland, Part 2',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 할아버지: 'Grandpa' },
    outro: [
      'Did you like the food and Maori culture of Auckland?',
      'How do people do the hongi, and what do they share?',
      'What would you remember and wish for at New Year?',
    ],
    lines: [
      ['해설', 'Last time, Hana saw the volcanoes and harbors of Auckland.'],
      ['해설', 'Today she visited a marae, a Maori meeting place.'],
      ['할아버지', 'Kia ora! Welcome to our marae.'],
      ['안내인', 'Guests are welcomed with songs and speeches.'],
      ['할아버지', 'Then we gently press noses and foreheads. It is the hongi.'],
      ['안내인', 'The hongi means sharing breath with each other.'],
      ['안내인', 'Take off your shoes before going into the meeting house.'],
      ['할아버지', 'First, hangi. We cook food with hot stones in the ground.'],
      ['안내인', 'Meat and kumara, a sweet potato, cook slowly under soil.'],
      ['하나', 'The food is steaming!'],
      ['안내인', 'Second, fish and chips. People eat them by the beach.'],
      ['안내인', 'Third, hokey pokey ice cream.'],
      ['안내인', 'It is vanilla ice cream with crunchy honeycomb toffee.'],
      ['하나', 'Crunch, crunch! So sweet!'],
      ['안내인', 'The kids are doing the haka. They stamp and shout.'],
      ['할아버지', 'We do the haka to welcome guests and on big days.'],
      ['안내인', 'In June or July, Maori people celebrate Matariki, the New Year.'],
      ['할아버지', 'It starts when the Matariki stars rise in the dawn sky.'],
      ['안내인', 'Some people take ferries to work from nearby islands.'],
      ['안내인', 'Fun fact! New Zealanders call themselves Kiwis.'],
      ['할아버지', 'The kiwi is a bird that cannot fly.'],
      ['해설', 'Hangi, fish and chips, and hokey pokey are Auckland foods.'],
      ['해설', 'Auckland is a city of sea, volcanoes, and Maori culture.'],
    ],
  },
};
