// 영어 학습용 원고 (한국 초등 저학년, 영어 초급). 문장은 자체 각색.
// 키 = stories/korean3.js 의 이야기 id. lines 의 첫 칸은 원래 이야기 cast 의 한국어 이름 그대로.
export default {
  'kr3-three-year-hill': {
    title: 'The Three-Year Hill',
    names: { 해설: 'Narrator', 할아버지: 'Grandpa', 할머니: 'Grandma', 돌이: 'Dori' },
    outro: [
      'Did you like the story?',
      'If you were Dori, what would you tell Grandpa?',
      'When did a new idea make you feel better?',
    ],
    lines: [
      ['해설', 'Once upon a time, there was a special hill.'],
      ['해설', 'People said, fall here and you live only three years.'],
      ['해설', 'So everyone walked on the hill very slowly.'],
      ['해설', 'One day, Grandpa walked over the hill.'],
      ['할아버지', 'Careful, careful. One step, two steps.'],
      ['해설', 'But he tripped on a rock. Thud!'],
      ['할아버지', 'Oh no! Now I have only three years!'],
      ['해설', 'Grandpa went to bed and did not get up.'],
      ['할머니', 'Please eat something, dear.'],
      ['할아버지', 'I cannot eat. I am too sad.'],
      ['해설', 'Then little Dori came to visit.'],
      ['돌이', 'Grandpa, why are you in bed?'],
      ['할아버지', 'I fell on the Three-Year Hill.'],
      ['돌이', 'Do not worry! I have a good idea.'],
      ['돌이', 'Fall once, three years. Fall twice, six years!'],
      ['돌이', 'Fall ten times, and you get thirty years!'],
      ['할아버지', 'You are right! What a smart boy!'],
      ['해설', 'Grandpa ran to the hill and rolled down. Roll, roll!'],
      ['할아버지', 'Three years, six years, nine years!'],
      ['할머니', 'Ha ha! That is enough rolling, dear.'],
      ['해설', 'Grandpa lived a long and happy life.'],
      ['해설', 'Change how you think, and worry can go away.'],
    ],
  },

  'kr3-stone-trial': {
    title: 'The Stone on Trial',
    names: { 해설: 'Narrator', 비단장수: 'Silk Seller', 원님: 'Judge', 구경꾼: 'Woman', 도둑: 'Thief' },
    outro: [
      'Was the story fun?',
      'If you were the Judge, how would you find the thief?',
      'When did a strange idea turn out to be smart?',
    ],
    lines: [
      ['해설', 'Once upon a time, a man was selling silk.'],
      ['비단장수', 'I am so tired. I will rest by this stone.'],
      ['해설', 'He fell asleep next to a tall stone post.'],
      ['해설', 'When he woke up, his silk was gone!'],
      ['비단장수', 'Oh no! Who took my silk?'],
      ['해설', 'He ran to the Judge for help.'],
      ['비단장수', 'Nobody was there. Only the stone post was there.'],
      ['원님', 'Then the stone saw everything. Bring me the stone!'],
      ['해설', 'Men tied up the stone and pulled it in.'],
      ['구경꾼', 'Ha ha! The Judge wants to talk to a stone!'],
      ['원님', 'Stone, tell me! Who took the silk?'],
      ['해설', 'The stone did not say a word.'],
      ['해설', 'All the people laughed and laughed.'],
      ['원님', 'Do not laugh here! Each of you, bring me silk.'],
      ['해설', 'The people brought silk to the Judge.'],
      ['비단장수', 'Look! This is my silk! I know my mark.'],
      ['구경꾼', 'I bought it at the market yesterday.'],
      ['해설', 'The Judge found the seller and caught the thief.'],
      ['도둑', 'I am sorry. I will never steal again.'],
      ['해설', 'Everyone got their silk back.'],
      ['해설', 'A strange idea can hide a very wise plan.'],
    ],
  },

  'kr3-crooked-grandma': {
    title: 'Crooked Grandma',
    names: { 해설: 'Narrator', 할머니: 'Grandma', 강아지: 'Puppy' },
    outro: [
      'Did you enjoy the story?',
      'If you were Grandma, what would you share with Puppy?',
      'What funny word do you like to say?',
    ],
    lines: [
      ['해설', 'Once upon a time, there was a crooked grandma.'],
      ['해설', 'She had a crooked stick and walked a crooked road.'],
      ['할머니', 'Crooked, crooked. I will go to the market!'],
      ['해설', 'She went up a crooked hill to a crooked tree.'],
      ['할머니', 'Oh my! I need to go poo!'],
      ['해설', 'She went behind the crooked tree. Plop!'],
      ['할머니', 'Ha ha! Now I feel much better.'],
      ['해설', 'Then a crooked puppy came. Sniff, sniff.'],
      ['강아지', 'What is that smell? Is it food?'],
      ['할머니', 'No, no! That is not food! Go away!'],
      ['해설', 'Grandma waved her crooked stick. Swish, swish!'],
      ['강아지', 'Yip, yip! I am scared!'],
      ['해설', 'The puppy ran away with its tail down.'],
      ['할머니', 'Oh, maybe the puppy was just hungry.'],
      ['해설', 'Grandma took out some crunchy rice snacks.'],
      ['할머니', 'Come here, Puppy. You can eat this.'],
      ['강아지', 'Crunch, crunch! Yummy! Thank you!'],
      ['할머니', 'Let us go to the market together.'],
      ['해설', 'They walked the crooked road side by side.'],
      ['강아지', 'Woof! Let us go again tomorrow!'],
      ['해설', 'Think about how others feel, and you can make friends.'],
    ],
  },

  'kr3-grateful-tiger': {
    title: 'The Thankful Tiger',
    names: { 해설: 'Narrator', 나무꾼: 'Woodcutter', 호랑이: 'Tiger', 어머니: 'Mother' },
    outro: [
      'Did you like the story?',
      'If you were the Woodcutter, would you help the Tiger?',
      'When did someone thank you for your help?',
    ],
    lines: [
      ['해설', 'Once upon a time, a kind woodcutter lived with his mother.'],
      ['해설', 'One day, he heard a sad sound in the forest.'],
      ['해설', 'A big tiger was crying with its mouth open.'],
      ['나무꾼', 'A tiger! But it looks hurt.'],
      ['호랑이', 'A bone is stuck in my throat. It hurts!'],
      ['나무꾼', 'I am scared, but I will help you.'],
      ['해설', 'He reached in and pulled out the bone. Pop!'],
      ['호랑이', 'Thank you! I will pay you back one day.'],
      ['해설', 'That winter, his mother got very sick.'],
      ['어머니', 'Cough, cough. I feel so weak.'],
      ['해설', 'Only a special mountain root could help her.'],
      ['나무꾼', 'How can I find it in the snow?'],
      ['해설', 'Then the tiger came out of the trees.'],
      ['호랑이', 'Why are you sad, my friend?'],
      ['나무꾼', 'I need a special root for my mother.'],
      ['호랑이', 'Get on my back. I know where it grows.'],
      ['해설', 'The tiger ran like the wind. Whoosh!'],
      ['나무꾼', 'There it is! Thank you, Tiger!'],
      ['해설', 'His mother ate the root and got better.'],
      ['어머니', 'I feel strong again! Please thank the tiger.'],
      ['해설', 'Kindness you give will come back to you.'],
    ],
  },

  'kr3-mole-groom': {
    title: 'The Strongest Groom',
    names: {
      해설: 'Narrator', 아빠두더지: 'Papa Mole', 엄마두더지: 'Mama Mole', 해님: 'Sun',
      구름: 'Cloud', 바람: 'Wind', 돌부처: 'Stone Statue', 딸두더지: 'Little Mole',
    },
    outro: [
      'Was the story fun?',
      'If you were Papa Mole, who would you think is strongest?',
      'What is a great power your family has?',
    ],
    lines: [
      ['해설', 'Once upon a time, a mole family lived under the ground.'],
      ['아빠두더지', 'Our daughter needs the strongest husband in the world.'],
      ['엄마두더지', 'Who is the strongest? Maybe the Sun!'],
      ['아빠두더지', 'Sun, you are the strongest. Please marry our girl.'],
      ['해님', 'Cloud is stronger. Cloud can cover me.'],
      ['아빠두더지', 'Cloud, you are strong. Please marry our girl.'],
      ['구름', 'Wind is stronger. Wind blows me away.'],
      ['엄마두더지', 'Wind, you are strong. Please marry our girl.'],
      ['바람', 'The Stone Statue is stronger. It never moves.'],
      ['아빠두더지', 'Stone Statue, please marry our girl.'],
      ['돌부처', 'Ho ho. A mole is stronger than me.'],
      ['돌부처', 'When a mole digs under me, I fall down. Thump!'],
      ['엄마두더지', 'A mole? Really?'],
      ['돌부처', 'Yes! Nobody digs like a mole.'],
      ['아빠두더지', 'Ha ha! The strongest one was here all along!'],
      ['해설', 'They went home and met a young mole next door.'],
      ['해설', 'He was the best digger of all.'],
      ['딸두더지', 'Papa, Mama, I like him too!'],
      ['해설', 'They got married and lived happily.'],
      ['해설', 'Good things are often very close to you.'],
    ],
  },

  'kr3-winter-berry': {
    title: 'Berries in Winter',
    names: { 해설: 'Narrator', 원님: 'Mayor', 아버지: 'Father', 꼬마: 'Boy' },
    outro: [
      'Did you enjoy the story?',
      'If you were the Boy, what would you say to the Mayor?',
      'What can you say when someone asks something silly?',
    ],
    lines: [
      ['해설', 'Once upon a time, there was a mean mayor.'],
      ['해설', 'One snowy winter day, he called a farmer.'],
      ['원님', 'Bring me a basket of berries in three days!'],
      ['아버지', 'But it is winter. There are no berries.'],
      ['원님', 'Bring them, or you will be in trouble!'],
      ['아버지', 'Oh no. What can I do?'],
      ['꼬마', 'Father, do not worry. I will go.'],
      ['해설', 'Three days later, the boy went to the Mayor.'],
      ['원님', 'Who are you? Where are my berries?'],
      ['꼬마', 'My father could not come. A snake bit him.'],
      ['원님', 'Ha ha! There are no snakes in winter!'],
      ['꼬마', 'Then there are no berries in winter, too.'],
      ['해설', 'The Mayor could not say a word. Blink, blink.'],
      ['해설', 'All the people tried not to laugh.'],
      ['원님', 'Hmm. You are right. I was being silly.'],
      ['원님', 'Forget about the berries.'],
      ['꼬마', 'Thank you, sir!'],
      ['해설', 'The boy ran home and told his father.'],
      ['아버지', 'My boy, you are so clever!'],
      ['해설', 'Stay calm and think, and you will find a smart answer.'],
    ],
  },

  'kr3-toad-groom': {
    title: 'The Toad Groom',
    names: { 해설: 'Narrator', 할머니: 'Grandma', 두꺼비: 'Toad', 정승: 'Lord', 언니: 'Big Sister', 셋째딸: 'Youngest' },
    outro: [
      'Did you like the story?',
      'If you were the Youngest, would you marry the Toad?',
      'Who is a friend that is kind inside?',
    ],
    lines: [
      ['해설', 'Once upon a time, an old couple had no children.'],
      ['해설', 'One day, a toad hopped to Grandma. Hop, hop!'],
      ['두꺼비', 'Grandma, please let me be your son.'],
      ['할머니', 'A talking toad! Yes, you are my son now.'],
      ['해설', 'The toad grew up and helped a lot.'],
      ['두꺼비', 'Mother, I want to marry the Lord’s daughter.'],
      ['해설', 'The toad hopped to the Lord’s big house.'],
      ['정승', 'What? A toad wants to marry my daughter?'],
      ['두꺼비', 'Yes. I will take good care of her.'],
      ['언니', 'No way! I will never marry a bumpy toad!'],
      ['셋째딸', 'I will. He seems kind and good.'],
      ['해설', 'So the toad and the youngest daughter got married.'],
      ['두꺼비', 'Please pull the skin on my back.'],
      ['해설', 'She pulled, and the toad skin came off!'],
      ['해설', 'Inside was a fine young man!'],
      ['셋째딸', 'Oh my! Who are you?'],
      ['두꺼비', 'I am from the sky. I wanted a kind wife.'],
      ['언니', 'Oh, I only looked at the outside.'],
      ['해설', 'They lived happily with Grandma and Grandpa.'],
      ['해설', 'Look at the heart, not just the outside.'],
    ],
  },

  'kr3-ant-waist': {
    title: 'Why Ants Have Thin Waists',
    names: { 해설: 'Narrator', 개미: 'Ant', 메뚜기: 'Grasshopper', 물총새: 'Kingfisher' },
    outro: [
      'Was the story fun?',
      'If you were Kingfisher, what would you say to Grasshopper?',
      'What can you do when a friend makes a mistake?',
    ],
    lines: [
      ['해설', 'Once upon a time, three friends lived in a field.'],
      ['해설', 'They were Ant, Grasshopper, and Kingfisher.'],
      ['메뚜기', 'Let us have a party!'],
      ['물총새', 'Yes! Everyone, bring some food.'],
      ['해설', 'Ant followed a lady with a lunch basket.'],
      ['개미', 'Yay! Some rice fell down. I will take it!'],
      ['해설', 'Kingfisher flew to the pond.'],
      ['물총새', 'A big fish! I will catch it!'],
      ['해설', 'But the fish was strong and pulled hard.'],
      ['물총새', 'I will not let go! Pull, pull!'],
      ['해설', 'Kingfisher’s beak got long, long, long.'],
      ['해설', 'Grasshopper just played in the grass. Hop, hop.'],
      ['해설', 'In the evening, the friends met at the big rock.'],
      ['메뚜기', 'I caught this fish! I am the strongest!'],
      ['물총새', 'No! I caught it with my beak!'],
      ['해설', 'Grasshopper jumped and hit his head. Bonk!'],
      ['메뚜기', 'Ouch! Now my head is shiny and bald!'],
      ['개미', 'Ha ha ha! My tummy! My waist!'],
      ['해설', 'Ant laughed so hard her waist got thin.'],
      ['해설', 'That is why ants have thin waists today.'],
      ['해설', 'Do not show off, and do not laugh at friends too much.'],
    ],
  },

  'kr3-tree-boy': {
    title: 'The Tree Boy',
    names: { 해설: 'Narrator', 큰나무: 'Father Tree', 나무도령: 'Tree Boy', 개미: 'Ant', 소년: 'Other Boy', 할머니: 'Grandma' },
    outro: [
      'Did you enjoy the story?',
      'If you were the Tree Boy, would you help the ants?',
      'When did you help a small animal?',
    ],
    lines: [
      ['해설', 'Once upon a time, a boy was born to a big tree.'],
      ['해설', 'One day, it rained and rained. Pitter-patter!'],
      ['해설', 'Soon the whole world was covered with water.'],
      ['큰나무', 'My son, climb on my back!'],
      ['해설', 'The Tree Boy floated on his father tree.'],
      ['개미', 'Help! We ants are in the water!'],
      ['나무도령', 'Father, can the ants come with us?'],
      ['큰나무', 'Yes, they can.'],
      ['소년', 'Help me! Please let me on!'],
      ['나무도령', 'Father, we must help him, too.'],
      ['해설', 'The rain stopped on top of a high mountain.'],
      ['해설', 'A grandma lived there with her daughter.'],
      ['소년', 'Grandma, he can pick rice out of sand!'],
      ['해설', 'The Other Boy told a lie to trick him.'],
      ['할머니', 'Really? Then pick the rice out of this sand.'],
      ['나무도령', 'Oh no. How can I do that?'],
      ['해설', 'Then the ants came and picked the rice, one by one.'],
      ['개미', 'You saved us. Now we will help you!'],
      ['할머니', 'Wow! Please marry my daughter!'],
      ['소년', 'I am sorry I lied. You saved me, too.'],
      ['해설', 'The Tree Boy forgave him, and they all lived together.'],
      ['해설', 'Help even small creatures, and help will come back.'],
    ],
  },

  'kr3-fire-dogs': {
    title: 'The Fire Dog and the Sun',
    names: { 해설: 'Narrator', 임금: 'King', 불개: 'Fire Dog' },
    outro: [
      'Was the story fun?',
      'If you were the Fire Dog, would you bite the Sun or the Moon?',
      'What would be hard in a world with no sun?',
    ],
    lines: [
      ['해설', 'Once upon a time, there was a very dark land.'],
      ['해설', 'There was no sun and no moon.'],
      ['임금', 'Our land is too dark. I want the sun!'],
      ['임금', 'Fire Dog, go and bring me the sun!'],
      ['불개', 'Woof! Yes, my King!'],
      ['해설', 'The Fire Dog ran up into the sky. Zoom!'],
      ['해설', 'He bit the sun. Chomp!'],
      ['불개', 'Ouch! Hot, hot, hot!'],
      ['해설', 'He spat out the sun and ran home.'],
      ['임금', 'Then bring me the moon. It is cool.'],
      ['해설', 'The Fire Dog ran up and bit the moon. Chomp!'],
      ['불개', 'Brr! Cold, cold! My teeth hurt!'],
      ['해설', 'He spat out the moon, too.'],
      ['임금', 'Do not give up! Try again!'],
      ['해설', 'People say the Fire Dog still tries sometimes.'],
      ['해설', 'When he bites the sun, part of it goes dark.'],
      ['해설', 'But he always spits it out, and it shines again.'],
      ['불개', 'The sun is too hot. The moon is too cold!'],
      ['임금', 'Ha ha. The sun and moon belong in the sky.'],
      ['해설', 'Today we know the moon and Earth make the shadow.'],
      ['해설', 'Things for everyone should not be taken by one.'],
    ],
  },

  'kr3-nail-rat': {
    title: 'The Rat Who Ate Fingernails',
    names: { 해설: 'Narrator', 선비: 'Scholar', 가짜선비: 'Fake Scholar', 아내: 'Wife', 원님: 'Judge', 스님: 'Monk', 고양이: 'Cat' },
    outro: [
      'Did you like the story?',
      'If you were the Scholar, how would you show you are real?',
      'Where should we throw away our nail clippings?',
    ],
    lines: [
      ['해설', 'Once upon a time, a scholar studied in the mountains.'],
      ['해설', 'He cut his fingernails and threw them anywhere.'],
      ['해설', 'A little rat ate his fingernails. Nibble, nibble.'],
      ['해설', 'Then the rat turned into a man just like him!'],
      ['해설', 'When the scholar came home, the fake man was there.'],
      ['선비', 'Who are you? This is my house!'],
      ['가짜선비', 'No! This is my house!'],
      ['아내', 'Oh my! You look the same! Who is real?'],
      ['해설', 'They went to the Judge.'],
      ['원님', 'How many spoons are in your house?'],
      ['가짜선비', 'Ten spoons and ten pairs of chopsticks!'],
      ['선비', 'I do not know. I was away for a long time.'],
      ['원님', 'Then you are the fake one. Go away!'],
      ['해설', 'The sad scholar went back to the mountain.'],
      ['스님', 'Take this cat home with you.'],
      ['해설', 'The scholar went home and let the cat out.'],
      ['고양이', 'Meow!'],
      ['가짜선비', 'Eek! A cat!'],
      ['해설', 'The fake man turned back into a rat and ran away.'],
      ['아내', 'Oh! The fake one was a rat!'],
      ['선비', 'From now on, I will clean up my nails.'],
      ['해설', 'Do not throw things anywhere. Put them in the right place.'],
    ],
  },

  'kr3-luck-journey': {
    title: 'The Search for Good Luck',
    names: { 해설: 'Narrator', 총각: 'Young Man', 주인: 'Rich Man', 이무기: 'Great Snake', 신령님: 'Spirit' },
    outro: [
      'Was the story fun?',
      'If you were the Young Man, would you help others first?',
      'When did helping someone make you happy, too?',
    ],
    lines: [
      ['해설', 'Once upon a time, a young man was always poor.'],
      ['총각', 'Why do I have no luck? I will ask the Spirit.'],
      ['해설', 'He walked a long, long way to the west.'],
      ['해설', 'He stayed one night at a rich man’s house.'],
      ['주인', 'My pear tree has no flowers. Please ask why.'],
      ['총각', 'Yes, I will ask for you.'],
      ['해설', 'Then he came to a big river.'],
      ['이무기', 'I will carry you across. Please ask a question for me.'],
      ['이무기', 'Why can I not become a dragon?'],
      ['해설', 'At last, he met the Spirit.'],
      ['신령님', 'A pot of gold is under the pear tree.'],
      ['신령님', 'The snake has two magic pearls. He must give one away.'],
      ['총각', 'But what about my luck?'],
      ['신령님', 'You helped others first. Luck will follow you.'],
      ['해설', 'He went back and told the snake.'],
      ['이무기', 'Thank you! Here is one pearl for you.'],
      ['해설', 'The snake flew up and became a dragon. Whoosh!'],
      ['해설', 'They dug under the tree and found the gold.'],
      ['주인', 'Thank you! Half of the gold is yours.'],
      ['해설', 'The young man shared his luck with poor neighbors.'],
      ['해설', 'Help others first, and good luck will find you.'],
    ],
  },

  'kr3-persimmon-branch': {
    title: 'Whose Persimmons?',
    names: { 해설: 'Narrator', 오성: 'Oseong', 하인: 'Servant', 대감: 'Old Lord' },
    outro: [
      'Did you enjoy the story?',
      'If you were Oseong, what clever idea would you have?',
      'What can you say when something feels unfair?',
    ],
    lines: [
      ['해설', 'Long ago, people told a story about a clever boy.'],
      ['해설', 'His name was Oseong.'],
      ['해설', 'A big persimmon tree grew in his yard.'],
      ['해설', 'One branch grew over the wall to the next house.'],
      ['해설', 'The servants next door picked those persimmons.'],
      ['오성', 'Hey! Those are from our tree!'],
      ['하인', 'They are over our wall, so they are ours!'],
      ['해설', 'Oseong thought and thought.'],
      ['해설', 'He went to the Old Lord’s room.'],
      ['해설', 'He pushed his arm through the paper door. Pop!'],
      ['대감', 'Oh! Whose arm is this?'],
      ['오성', 'Sir, whose arm is this?'],
      ['대감', 'It is your arm, of course.'],
      ['오성', 'It is in your room. Is it still my arm?'],
      ['대감', 'Yes, it is still yours.'],
      ['오성', 'Then the branch over your wall is still ours!'],
      ['대감', 'Ha ha! You are right, clever boy!'],
      ['대감', 'Give back all the persimmons.'],
      ['오성', 'Sorry about the door. I will fix it.'],
      ['해설', 'When something is unfair, explain it calmly and clearly.'],
    ],
  },

  'kr3-two-oxen': {
    title: 'The Yellow Ox and the Black Ox',
    names: { 해설: 'Narrator', 황희: 'Hwang Hui', 농부: 'Farmer' },
    outro: [
      'Was the story fun?',
      'If you were the Black Ox, how would you feel?',
      'When did you speak kindly to protect a friend?',
    ],
    lines: [
      ['해설', 'Long ago, people told a story about Hwang Hui.'],
      ['해설', 'One day, he sat down near a field.'],
      ['해설', 'A farmer was working with two oxen.'],
      ['해설', 'One was yellow. One was black.'],
      ['해설', 'Moo, moo! They pulled hard.'],
      ['황희', 'Hello! Which ox works better?'],
      ['해설', 'The farmer stopped and walked over.'],
      ['황희', 'Why not just tell me from there?'],
      ['해설', 'The farmer whispered in his ear.'],
      ['농부', 'The yellow ox works a little better.'],
      ['황희', 'Ha ha. Why do you whisper?'],
      ['농부', 'The oxen can hear us, too.'],
      ['농부', 'The black ox would feel sad.'],
      ['농부', 'He works very hard, too.'],
      ['해설', 'Hwang Hui was surprised.'],
      ['황희', 'You care about an ox’s feelings.'],
      ['황희', 'I asked without thinking. I am sorry.'],
      ['농부', 'That is all right, young man.'],
      ['해설', 'Hwang Hui remembered this all his life.'],
      ['해설', 'He grew up to be a kind and wise leader.'],
      ['해설', 'Think about others’ feelings before you speak.'],
    ],
  },

  'kr3-goblin-hat': {
    title: 'The Goblin’s Magic Hat',
    names: { 해설: 'Narrator', 나무꾼: 'Woodcutter', 도깨비: 'Goblin', 떡장수: 'Cake Seller' },
    outro: [
      'Did you like the story?',
      'If you had the magic hat, what would you do?',
      'When did you do the right thing when nobody saw?',
    ],
    lines: [
      ['해설', 'One night, a woodcutter saw goblins playing.'],
      ['도깨비', 'Hat on, you cannot see me! Hat off, you can!'],
      ['해설', 'The rooster crowed. Cock-a-doodle-doo!'],
      ['해설', 'The goblins ran away and left one hat.'],
      ['나무꾼', 'A magic hat! Let me try it on.'],
      ['해설', 'He put it on and disappeared!'],
      ['나무꾼', 'Ha ha! Nobody can see me!'],
      ['나무꾼', 'I can eat anything at the market.'],
      ['해설', 'He went to the market and took rice cakes.'],
      ['떡장수', 'Oh my! My rice cakes are flying away!'],
      ['해설', 'One day, the hat got a little hole.'],
      ['해설', 'His wife fixed it with a red patch.'],
      ['해설', 'He went to the market again.'],
      ['떡장수', 'Look! A red patch is floating in the air!'],
      ['떡장수', 'That is the cake thief! Catch it!'],
      ['해설', 'People grabbed the red patch. The hat fell off!'],
      ['나무꾼', 'I am sorry! I ate the cakes!'],
      ['떡장수', 'You must not take things that are not yours!'],
      ['해설', 'He worked hard and paid for all the cakes.'],
      ['해설', 'Even when nobody sees, do not take what is not yours.'],
    ],
  },

  'kr3-goblin-debt': {
    title: 'The Goblin Who Paid Back',
    names: { 해설: 'Narrator', 농부: 'Farmer', 도깨비: 'Goblin', 아내: 'Wife' },
    outro: [
      'Was the story fun?',
      'If you were the Farmer, what would you do with the money?',
      'When did you keep a promise to a friend?',
    ],
    lines: [
      ['해설', 'Once upon a time, a kind farmer lived in a village.'],
      ['해설', 'One night, someone knocked. Knock, knock!'],
      ['도깨비', 'Please lend me three coins. I will pay you back.'],
      ['농부', 'A goblin! But he needs help.'],
      ['해설', 'The farmer gave the goblin three coins.'],
      ['도깨비', 'Thank you! I will not forget!'],
      ['해설', 'The next night, the goblin came back.'],
      ['도깨비', 'Here are the three coins from yesterday!'],
      ['농부', 'Thank you. You keep your promise.'],
      ['해설', 'But the next night, he came again!'],
      ['도깨비', 'Here are the three coins from yesterday!'],
      ['농부', 'But you already paid me!'],
      ['해설', 'The goblin forgot. He came every night.'],
      ['해설', 'The coins piled up. Clink, clink!'],
      ['아내', 'What should we do with all this money?'],
      ['농부', 'It is not ours. Let us use it for others.'],
      ['해설', 'They built a bridge and shared rice with neighbors.'],
      ['농부', 'Goblin, you paid me back already. You can stop.'],
      ['도깨비', 'Really? Hooray!'],
      ['해설', 'The goblin danced all the way home.'],
      ['해설', 'Pay back what you borrow, and share what you have.'],
    ],
  },

  'kr3-singing-turtle': {
    title: 'The Singing Turtle',
    names: { 해설: 'Narrator', 동생: 'Little Brother', 형: 'Big Brother', 남생이: 'Turtle' },
    outro: [
      'Did you enjoy the story?',
      'If you were the Turtle, how would you feel?',
      'How do you take care of a pet or a friend?',
    ],
    lines: [
      ['해설', 'Once upon a time, there were two brothers.'],
      ['해설', 'Big Brother was greedy. Little Brother was kind.'],
      ['해설', 'One day, Little Brother heard a song by the pond.'],
      ['남생이', 'La la la! The sun is warm on my shell!'],
      ['동생', 'Wow! A singing turtle!'],
      ['남생이', 'Take me to the market. I will sing there.'],
      ['동생', 'Everyone, come and hear the singing turtle!'],
      ['남생이', 'La la la! The market is so fun!'],
      ['해설', 'People clapped and gave him coins. Clap, clap!'],
      ['형', 'A singing turtle? Give it to me!'],
      ['동생', 'Please be gentle with the turtle.'],
      ['형', 'Pay me money! My turtle will sing!'],
      ['해설', 'But the turtle did not sing.'],
      ['형', 'Sing! Sing now!'],
      ['해설', 'He shook the turtle. The turtle hid in its shell.'],
      ['해설', 'People got angry and wanted their money back.'],
      ['해설', 'The turtle crawled back to the pond.'],
      ['형', 'I am sorry. I was too greedy.'],
      ['동생', 'Let us go and say sorry to the turtle.'],
      ['남생이', 'La la la! Now I feel better!'],
      ['해설', 'Friends are not for using. Take good care of them.'],
    ],
  },

  'kr3-rice-cake-name': {
    title: 'What Was That Rice Cake?',
    names: { 해설: 'Narrator', 사위: 'Husband', 장모: 'Grandma', 아내: 'Wife' },
    outro: [
      'Was the story fun?',
      'If you were the Husband, how would you remember the name?',
      'When did you forget something funny?',
    ],
    lines: [
      ['해설', 'Once upon a time, a man always forgot things.'],
      ['해설', 'One day, he visited his wife’s mother.'],
      ['장모', 'Here, try this rice cake.'],
      ['사위', 'Yum! It is so chewy! What is it called?'],
      ['장모', 'It is called chaltteok.'],
      ['사위', 'Chaltteok! I will ask my wife to make it.'],
      ['해설', 'On the way home, he said the name again and again.'],
      ['사위', 'Chaltteok, chaltteok, chaltteok.'],
      ['해설', 'Then he came to a little stream.'],
      ['사위', 'Heave-ho!'],
      ['해설', 'He jumped over the stream.'],
      ['사위', 'Heave-ho, heave-ho, heave-ho.'],
      ['해설', 'Oh no! He forgot the real name!'],
      ['사위', 'Wife, please make me some heave-ho!'],
      ['아내', 'Heave-ho? What is that?'],
      ['사위', 'You know! The chewy, yummy heave-ho!'],
      ['해설', 'He stamped his feet and bumped his head. Bonk!'],
      ['아내', 'Oh! Your head is puffy like chaltteok!'],
      ['사위', 'Chaltteok! That is it!'],
      ['아내', 'Ha ha! I will make it tomorrow.'],
      ['해설', 'Write important things down so you do not forget.'],
    ],
  },

  'kr3-storehouse-key': {
    title: 'The Storehouse Key',
    names: { 해설: 'Narrator', 시아버지: 'Father', 큰며느리: 'First Wife', 둘째며느리: 'Second Wife', 막내며느리: 'Youngest Wife' },
    outro: [
      'Did you like the story?',
      'If you got one grain of rice, what would you do?',
      'What small thing did you save to make something big?',
    ],
    lines: [
      ['해설', 'Once upon a time, a father had three sons’ wives.'],
      ['시아버지', 'Who should keep the storehouse key?'],
      ['해설', 'He gave each of them one grain of rice.'],
      ['시아버지', 'Take good care of this rice.'],
      ['큰며느리', 'Only one grain? It is nothing.'],
      ['해설', 'The First Wife threw it away.'],
      ['둘째며느리', 'I will just eat it. Munch.'],
      ['막내며느리', 'Even one grain is special. What can I do?'],
      ['해설', 'The Youngest Wife fed it to a little chick.'],
      ['해설', 'The chick grew into a hen. Cluck, cluck!'],
      ['해설', 'The hen laid eggs, and more chicks came out.'],
      ['해설', 'She traded the chickens for a pig.'],
      ['해설', 'Then she traded the pigs for a little calf.'],
      ['시아버지', 'Now, bring me your grain of rice.'],
      ['큰며느리', 'I threw mine away.'],
      ['둘째며느리', 'I ate mine.'],
      ['막내며느리', 'Mine is in the yard, Father.'],
      ['해설', 'In the yard stood a big cow. Moo!'],
      ['시아버지', 'Ha ha! One grain became a cow!'],
      ['시아버지', 'You will keep the storehouse key.'],
      ['해설', 'Take care of small things, and they can grow big.'],
    ],
  },

  'kr3-rice-rock': {
    title: 'The Rice Rock',
    names: { 해설: 'Narrator', 노스님: 'Old Monk', 꼬마스님: 'Little Monk', 나그네: 'Traveler' },
    outro: [
      'Was the story fun?',
      'If you were the Little Monk, would you want more rice?',
      'What are you thankful for today?',
    ],
    lines: [
      ['해설', 'Once upon a time, there was a little temple.'],
      ['해설', 'An old monk and a little monk lived there.'],
      ['해설', 'Rice came out of a hole in a rock.'],
      ['해설', 'Every day, there was just enough for two.'],
      ['노스님', 'We have just enough. Thank you.'],
      ['나그네', 'Hello. May I stay for one night?'],
      ['노스님', 'Of course. Please come in.'],
      ['해설', 'That day, there was rice for three!'],
      ['꼬마스님', 'Wow! More people, more rice!'],
      ['꼬마스님', 'If I make the hole bigger, I will get more!'],
      ['해설', 'At night, he went to the rock. Tap, tap, tap!'],
      ['꼬마스님', 'Bigger, bigger!'],
      ['해설', 'The next morning, he ran to the rock.'],
      ['꼬마스님', 'What? No rice?'],
      ['해설', 'Only water came out. Drip, drip.'],
      ['노스님', 'Why is the hole so big?'],
      ['꼬마스님', 'I wanted more rice. I am sorry.'],
      ['노스님', 'If you are greedy, you can lose everything.'],
      ['노스님', 'Now we will grow our own food.'],
      ['해설', 'They worked hard in the field together.'],
      ['해설', 'Be thankful for what you have. Do not be greedy.'],
    ],
  },

  'kr3-my-own-luck': {
    title: 'I Live by My Own Luck',
    names: { 해설: 'Narrator', 아버지: 'Father', 큰딸: 'Oldest Daughter', 셋째딸: 'Youngest Daughter', 숯총각: 'Charcoal Maker' },
    outro: [
      'Did you enjoy the story?',
      'If you were the Youngest Daughter, what would you say?',
      'What did you do all by yourself?',
    ],
    lines: [
      ['해설', 'Once upon a time, a rich man had three daughters.'],
      ['아버지', 'Girls, who gives you such a good life?'],
      ['큰딸', 'You do, Father.'],
      ['셋째딸', 'I think I live by my own luck.'],
      ['아버지', 'What? Then go and live by your own luck!'],
      ['해설', 'The angry father sent her away.'],
      ['셋째딸', 'Okay. I will live by my own hands.'],
      ['해설', 'She came to a little hut in the mountains.'],
      ['숯총각', 'Hello! Please come in and rest.'],
      ['해설', 'He was poor, but very kind.'],
      ['해설', 'They got married and worked hard together.'],
      ['셋째딸', 'Look! These stones shine! They are gold!'],
      ['숯총각', 'Gold? I thought they were just stones!'],
      ['해설', 'They became rich and helped poor neighbors.'],
      ['해설', 'But her father lost all his money.'],
      ['해설', 'She had a big party and invited him.'],
      ['셋째딸', 'Father, it is me, your youngest daughter.'],
      ['아버지', 'It is you! You live so well!'],
      ['아버지', 'I am sorry. Everyone has their own luck.'],
      ['셋째딸', 'Please come and live with us, Father.'],
      ['해설', 'Believe in yourself and work hard, and your luck will bloom.'],
    ],
  },
};
