// 영어 학습용 원고: 세계 도시 탐방 3차 (북유럽). 문장은 자체 집필.
// 키 = stories/city-i.js 의 이야기 id. lines 의 첫 칸은 한국어 cast 이름 그대로.
export default {
  'ct-helsinki-1': {
    title: 'Helsinki, Part 1',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 아이노: 'Aino' },
    outro: [
      'Did you enjoy our first day in Helsinki?',
      'Why did people build a fortress on the islands?',
      'If the sky stayed bright at night, what would you do?',
    ],
    lines: [
      ['해설', 'Hana and the Guide arrived in Helsinki by boat.'],
      ['하나', 'Look! There are so many little islands!'],
      ['안내인', 'Helsinki is the capital of Finland, in northern Europe.'],
      ['안내인', 'It sits by the sea, on the Gulf of Finland.'],
      ['안내인', 'Finland has many forests and lakes.'],
      ['해설', 'Winters are long and cold. The sea can freeze.'],
      ['해설', 'In midsummer, the sky never gets fully dark at night.'],
      ['아이노', 'Moi! I am Aino. Moi means hi.'],
      ['안내인', 'People here speak Finnish and Swedish.'],
      ['안내인', 'Let’s learn about the history of Helsinki.'],
      ['안내인', 'In 1550, a Swedish king started a trading town here.'],
      ['해설', 'Back then, Finland was part of Sweden.'],
      ['안내인', 'In the 1700s, Sweden built a sea fortress on the islands.'],
      ['안내인', 'In 1809, Finland became part of the Russian Empire.'],
      ['안내인', 'In 1812, Helsinki became the new capital.'],
      ['안내인', 'Finland became independent on December 6, 1917.'],
      ['해설', 'In 1952, Helsinki hosted the Summer Olympics.'],
      ['아이노', 'First, Senate Square! A white cathedral stands above the steps.'],
      ['안내인', 'Second, Suomenlinna. It is a World Heritage Site.'],
      ['안내인', 'Third, the Rock Church. It was built inside a big rock.'],
      ['해설', 'Helsinki became the capital of Finland in 1812.'],
      ['해설', 'It is a seaside city with a fortress and a white cathedral.'],
    ],
  },

  'ct-helsinki-2': {
    title: 'Helsinki, Part 2',
    names: { 해설: 'Narrator', 안내인: 'Guide', 하나: 'Hana', 아이노: 'Aino', 상인: 'Seller', 할아버지: 'Grandpa' },
    outro: [
      'Did our trip to Helsinki warm you up?',
      'Why do people wear reflectors in the dark winter?',
      'What would you like to borrow from your library?',
    ],
    lines: [
      ['해설', 'Last time, Hana learned about the history of Helsinki.'],
      ['해설', 'Today, she went to the market square with Aino.'],
      ['상인', 'Welcome! Try some warm salmon soup!'],
      ['상인', 'It has salmon, potatoes, milk, and fresh dill.'],
      ['아이노', 'Next, Karelian pie. It is rye crust with rice inside.'],
      ['안내인', 'Some people top it with egg butter.'],
      ['아이노', 'Third, a cinnamon bun! It looks like an ear.'],
      ['할아버지', 'Welcome to the sauna. Warm yourself up.'],
      ['안내인', 'Sauna is a Finnish word. Now the whole world uses it.'],
      ['할아버지', 'Throw water on the hot stones. Feel the steam!'],
      ['아이노', 'Then some people jump into the cold sea!'],
      ['안내인', 'Finnish sauna culture is on a UNESCO heritage list.'],
      ['안내인', 'On May Day, people wear white student caps.'],
      ['안내인', 'At Midsummer in late June, people light big bonfires.'],
      ['아이노', 'On Independence Day, we put two candles in the window.'],
      ['안내인', 'People ride green trams, the metro, and ferries.'],
      ['아이노', 'Some libraries even lend musical instruments!'],
      ['안내인', 'Students in Finland get free school lunches.'],
      ['안내인', 'Anyone may walk in the forest and pick berries.'],
      ['아이노', 'In winter, we wear reflectors so drivers can see us.'],
      ['해설', 'Hana learned about salmon soup, Karelian pie, and saunas.'],
      ['해설', 'Helsinki loves saunas, forests, and the sea.'],
    ],
  },
};
