// 영어 학습용 원고 (한국 초등 저학년, 영어 초급). 문장은 자체 각색.
// 키 = stories/talmud2.js 의 이야기 id. lines 의 첫 칸은 원래 이야기 cast 의 한국어 이름 그대로.
export default {
  'tm2-feathers': {
    title: 'The Scattered Feathers',
    names: { 해설: 'Narrator', 아주머니: 'Woman', 선생님: 'Teacher', 빵집아저씨: 'Baker' },
    outro: [
      'Did you like the story?',
      'If you were the Woman, what would you say to the Baker?',
      'What can you do when you hear talk about a friend?',
    ],
    lines: [
      ['해설', 'Once upon a time, a woman loved to talk.'],
      ['해설', 'She told stories to everyone. Whisper, whisper.'],
      ['아주머니', 'The baker makes his bread too small!'],
      ['해설', 'But it was not true.'],
      ['해설', 'Soon nobody went to the bakery.'],
      ['빵집아저씨', 'Why does nobody come to my shop?'],
      ['해설', 'The woman felt bad. She went to a wise teacher.'],
      ['아주머니', 'I said a wrong thing. How can I take it back?'],
      ['선생님', 'Take a feather pillow up the hill.'],
      ['선생님', 'Open it and let the feathers fly.'],
      ['해설', 'Whoosh! The feathers flew far away.'],
      ['아주머니', 'I did it. Am I done now?'],
      ['선생님', 'No. Now pick up every feather again.'],
      ['아주머니', 'I cannot! They are everywhere!'],
      ['선생님', 'Words are like feathers.'],
      ['선생님', 'Once they fly, you cannot get them all back.'],
      ['해설', 'The woman went to the baker.'],
      ['아주머니', 'I am so sorry. My words were wrong.'],
      ['빵집아저씨', 'Thank you for telling me.'],
      ['해설', 'Think before you speak. Words can fly far.'],
    ],
  },

  'tm2-chimney': {
    title: 'Two Kids in the Chimney',
    names: { 해설: 'Narrator', 선생님: 'Teacher', 제자: 'Student' },
    outro: [
      'Was the story fun?',
      'How would you answer the first question?',
      'Do you look at yourself before you look at others?',
    ],
    lines: [
      ['해설', 'Once upon a time, a teacher loved riddles.'],
      ['선생님', 'Here is a riddle for you.'],
      ['제자', 'Yes! I can answer any riddle.'],
      ['선생님', 'Two kids clean a chimney together.'],
      ['선생님', 'One has a dirty face. One has a clean face.'],
      ['선생님', 'Who goes to wash his face?'],
      ['제자', 'That is easy. The dirty one!'],
      ['선생님', 'No. The dirty one sees a clean face.'],
      ['선생님', 'So he thinks, I am clean too.'],
      ['선생님', 'The clean one sees a dirty face.'],
      ['선생님', 'So he thinks, I am dirty too. He washes.'],
      ['제자', 'Oh! Ask me one more time, please.'],
      ['선생님', 'Two kids clean a chimney again. Who washes?'],
      ['제자', 'I know now! The clean one!'],
      ['선생님', 'No, that is wrong too.'],
      ['제자', 'But you just said so!'],
      ['선생님', 'Think again. They went down the same chimney.'],
      ['선생님', 'Can only one face be clean?'],
      ['제자', 'Oh! Both faces are dirty!'],
      ['선생님', 'Yes. Look at the question carefully.'],
      ['해설', 'Look at yourself first, and always think one more time.'],
    ],
  },

  'tm2-donkey-jewel': {
    title: 'The Jewel on the Donkey',
    names: { 해설: 'Narrator', 선생님: 'Teacher', 제자: 'Student', 장사꾼: 'Seller' },
    outro: [
      'Did you enjoy the story?',
      'If you were the Teacher, would you give the jewel back?',
      'What do you do when you find something that is not yours?',
    ],
    lines: [
      ['해설', 'Once upon a time, there was a good teacher.'],
      ['해설', 'Every day, he carried heavy wood. Huff, puff.'],
      ['제자', 'Teacher, we will buy you a donkey!'],
      ['선생님', 'Thank you. Now I can study more.'],
      ['해설', 'The students washed the donkey in the river. Splash!'],
      ['해설', 'Then something was shining on its neck.'],
      ['제자', 'Look! A big jewel!'],
      ['제자', 'Teacher, now you do not need to work!'],
      ['선생님', 'Did the seller know about the jewel?'],
      ['제자', 'No. So now it is ours.'],
      ['선생님', 'No. We bought a donkey, not a jewel.'],
      ['선생님', 'Let us give it back.'],
      ['해설', 'They walked to the seller. Step, step.'],
      ['선생님', 'This was on the donkey. It is yours.'],
      ['장사꾼', 'Nobody knew. Why do you give it back?'],
      ['선생님', 'I know. It is not mine.'],
      ['장사꾼', 'Wow. You are a very honest man.'],
      ['제자', 'Teacher, I learned something better than a jewel.'],
      ['해설', 'If it is not yours, give it back to the owner.'],
    ],
  },

  'tm2-tightrope': {
    title: 'The Girl on the Rope',
    names: { 해설: 'Narrator', 줄타기소녀: 'Rope Girl', 소년: 'Boy', 할아버지: 'Grandpa' },
    outro: [
      'Was the story fun?',
      'If you were on the rope, how would you keep your balance?',
      'How do you share your day between play and study?',
    ],
    lines: [
      ['해설', 'There was a big party in the town. Boom, boom!'],
      ['해설', 'A long rope hung between two roofs.'],
      ['해설', 'A girl walked on the rope. Step, step.'],
      ['소년', 'Wow! How can she walk on that?'],
      ['해설', 'She leaned a little, but she did not fall.'],
      ['해설', 'Everyone clapped. Clap, clap, clap!'],
      ['소년', 'Why do you never fall? Tell me the secret.'],
      ['줄타기소녀', 'It is easy.'],
      ['줄타기소녀', 'When I lean right, I lean left a little.'],
      ['줄타기소녀', 'When I lean left, I lean right a little.'],
      ['소년', 'Can I lean a lot?'],
      ['줄타기소녀', 'No. Then you fall the other way. Just a little.'],
      ['할아버지', 'That is true for life, too.'],
      ['소년', 'What do you mean, Grandpa?'],
      ['할아버지', 'If you only play, lean to study a little.'],
      ['할아버지', 'If you only study, lean to play a little.'],
      ['소년', 'Oh! Not too much on one side!'],
      ['해설', 'That night, the boy walked on a line.'],
      ['소년', 'I did it! A little at a time!'],
      ['해설', 'Do not go too far one way. Keep your balance.'],
    ],
  },

  'tm2-goat-house': {
    title: 'The Goat in the House',
    names: { 해설: 'Narrator', 아저씨: 'Farmer', 선생님: 'Teacher' },
    outro: [
      'Did you like the story?',
      'Did the house really get bigger? Why did it feel big?',
      'What are you thankful for in your home?',
    ],
    lines: [
      ['해설', 'Once upon a time, a farmer had a tiny house.'],
      ['해설', 'His big family lived there.'],
      ['아저씨', 'Oh, my house is too small!'],
      ['해설', 'He went to a wise teacher.'],
      ['아저씨', 'My house is too small. What can I do?'],
      ['선생님', 'Bring your goat into the house.'],
      ['해설', 'Baa, baa! The goat jumped all around.'],
      ['아저씨', 'Teacher, now it is smaller!'],
      ['선생님', 'Now bring your hens inside, too.'],
      ['해설', 'Cluck, cluck! Feathers flew everywhere.'],
      ['아저씨', 'Teacher, I cannot live like this!'],
      ['선생님', 'Now bring your cow inside, too.'],
      ['해설', 'Moo! The house was full. Nobody could sleep.'],
      ['아저씨', 'Please help me!'],
      ['선생님', 'Now take them all outside.'],
      ['해설', 'The farmer took the animals out. Then he cleaned.'],
      ['아저씨', 'Wow! My house is so big now!'],
      ['선생님', 'Your house is the same. Your heart changed.'],
      ['해설', 'Be thankful for what you have.'],
    ],
  },

  'tm2-akiva': {
    title: 'The Water Drop and the Rock',
    names: { 해설: 'Narrator', 아키바: 'Akiva', 아들: 'Son' },
    outro: [
      'Did you enjoy the story?',
      'If you were Akiva, would you start to learn at forty?',
      'What did you get good at, little by little?',
    ],
    lines: [
      ['해설', 'Once upon a time, Akiva took care of sheep.'],
      ['해설', 'He was forty years old. He could not read.'],
      ['아키바', 'I want to read. But am I too old?'],
      ['해설', 'One day, he went to a well.'],
      ['해설', 'He saw a hard rock with a hole in it.'],
      ['아키바', 'Who made a hole in this hard rock?'],
      ['해설', 'Water was dripping on the rock. Drip, drip.'],
      ['해설', 'It dripped there every day for a long time.'],
      ['아키바', 'Soft water made a hole in a hard rock!'],
      ['아키바', 'So I can learn, a little every day!'],
      ['해설', 'Akiva sat with his little son.'],
      ['아들', 'Dad, this is the first letter. Say it with me!'],
      ['아키바', 'Ha ha! You are my study buddy.'],
      ['아들', 'Dad, some people laugh. Are you shy?'],
      ['아키바', 'No. The water drop did not stop. I will not stop.'],
      ['해설', 'He studied every day. Drip, drip.'],
      ['해설', 'Many years went by.'],
      ['해설', 'Akiva became a very wise teacher.'],
      ['아들', 'Dad, you did it, just like the water drop!'],
      ['해설', 'It is never too late. Little by little, you can do it.'],
    ],
  },

  'tm2-short-road': {
    title: 'The Short Long Road',
    names: { 해설: 'Narrator', 선생님: 'Teacher', 꼬마: 'Kid' },
    outro: [
      'Was the story fun?',
      'If you were the Teacher, which road would you take?',
      'When did you hurry and end up late?',
    ],
    lines: [
      ['해설', 'Once upon a time, a wise teacher was walking.'],
      ['해설', 'The road split into two roads.'],
      ['선생님', 'Which way goes to the town?'],
      ['해설', 'A kid was sitting by the road.'],
      ['선생님', 'Which road goes to the town?'],
      ['꼬마', 'This road is short and long.'],
      ['꼬마', 'That road is long and short.'],
      ['선생님', 'Short? Then I will take this road.'],
      ['해설', 'Soon he saw the town. It was close!'],
      ['해설', 'But there were trees and a fence all around.'],
      ['해설', 'He could not find a gate.'],
      ['선생님', 'Oh no. The town is right there!'],
      ['해설', 'He walked all the way back. Step, step.'],
      ['선생님', 'You said this road was short!'],
      ['꼬마', 'I said short and long. It looks short, but it is long.'],
      ['꼬마', 'That road looks long, but it is short.'],
      ['선생님', 'Ha! You are wiser than me.'],
      ['해설', 'He took the other road. He got to the town.'],
      ['선생님', 'A fast road is not always fast.'],
      ['해설', 'Listen to the end, and then think.'],
    ],
  },

  'tm2-fox-fish': {
    title: 'The Fox and the Fish',
    names: { 해설: 'Narrator', 여우: 'Fox', 물고기: 'Old Fish', 꼬마물고기: 'Little Fish' },
    outro: [
      'Did you like the story?',
      'If you were the Little Fish, would you believe the Fox?',
      'What do you do when you hear very sweet words?',
    ],
    lines: [
      ['해설', 'Fish were swimming in a clear river.'],
      ['해설', 'Then fishermen threw nets into the water. Splash!'],
      ['꼬마물고기', 'A net! Swim away!'],
      ['해설', 'A fox was watching from the river bank.'],
      ['여우', 'Hee hee. I have a good idea.'],
      ['여우', 'Fish, why are you swimming so fast?'],
      ['물고기', 'We are running away from the nets.'],
      ['여우', 'Come out of the water. Live with me!'],
      ['여우', 'There are no nets on the land.'],
      ['꼬마물고기', 'No nets? Let us go!'],
      ['물고기', 'Wait, little one! Stop!'],
      ['물고기', 'Fox, we are scared even in the water.'],
      ['물고기', 'Out of the water, we cannot breathe.'],
      ['꼬마물고기', 'Oh, that is right! We need water.'],
      ['여우', 'Humph! My trick did not work.'],
      ['해설', 'The fox went back to the forest.'],
      ['꼬마물고기', 'Thank you. That was close!'],
      ['물고기', 'Stay where you belong. Think about sweet words.'],
      ['해설', 'Do not trust sweet words too fast.'],
    ],
  },

  'tm2-desert-tree': {
    title: 'The Tree in the Desert',
    names: { 해설: 'Narrator', 나그네: 'Traveler', 낙타: 'Camel' },
    outro: [
      'Did you enjoy the story?',
      'If you were the Traveler, what would you say to the tree?',
      'What nice words can you say to someone kind?',
    ],
    lines: [
      ['해설', 'A traveler and a camel walked in the desert.'],
      ['해설', 'The sun was very hot.'],
      ['나그네', 'I am hungry, thirsty, and hot.'],
      ['낙타', 'My legs are tired, too.'],
      ['해설', 'Then they saw something green.'],
      ['나그네', 'Look! A tree!'],
      ['해설', 'The tree had sweet fruit.'],
      ['해설', 'It had cool shade. It had fresh water, too.'],
      ['해설', 'The traveler ate and drank. Yum, gulp!'],
      ['낙타', 'Ah, I feel so much better.'],
      ['해설', 'They took a nap in the shade.'],
      ['나그네', 'Thank you, tree. I want to wish you something.'],
      ['나그네', 'Sweet fruit? You have it.'],
      ['나그네', 'Cool shade? You have it.'],
      ['나그네', 'Fresh water? You have it, too.'],
      ['낙타', 'Then what will you wish?'],
      ['나그네', 'I hope your seeds grow into trees like you.'],
      ['나그네', 'Then other travelers can rest, too.'],
      ['해설', 'The leaves moved in the wind. Swish, swish.'],
      ['해설', 'Say thank you, and wish good things for others.'],
    ],
  },

  'tm2-clay-jar': {
    title: 'The Wine in the Clay Jar',
    names: { 해설: 'Narrator', 공주: 'Princess', 선생님: 'Teacher', 임금님: 'King' },
    outro: [
      'Was the story fun?',
      'If you were the Princess, what would you say to the Teacher?',
      'Did you ever judge a friend by looks?',
    ],
    lines: [
      ['해설', 'Once upon a time, a wise teacher visited a palace.'],
      ['해설', 'His clothes were plain. He looked plain, too.'],
      ['공주', 'So much wisdom in such a plain man?'],
      ['해설', 'The teacher just smiled.'],
      ['선생님', 'Princess, where do you keep your wine?'],
      ['공주', 'In clay jars.'],
      ['선생님', 'Clay jars? Why not gold jars?'],
      ['공주', 'You are right! I will change them.'],
      ['해설', 'She put the wine in gold and silver jars.'],
      ['해설', 'A few days later, the king drank some wine.'],
      ['임금님', 'Yuck! It is sour! What happened?'],
      ['공주', 'I put it in gold jars. The teacher told me to.'],
      ['임금님', 'Teacher, why did you say that?'],
      ['선생님', 'Wine stays good in plain clay jars.'],
      ['선생님', 'A shiny jar does not make the wine better.'],
      ['선생님', 'Wisdom is the same. Looks are not everything.'],
      ['공주', 'I am sorry. I only looked at your clothes.'],
      ['임금님', 'Ha ha. My girl learned a big lesson today.'],
      ['해설', 'Do not judge by looks. What is inside matters most.'],
    ],
  },

  'tm2-snake-tail': {
    title: 'The Snake’s Head and Tail',
    names: { 해설: 'Narrator', 머리: 'Head', 꼬리: 'Tail' },
    outro: [
      'Did you like the story?',
      'If you were the Tail, would you want to go first?',
      'What are you good at when you play with friends?',
    ],
    lines: [
      ['해설', 'A long snake lived in the forest.'],
      ['해설', 'The head always went first. The tail followed.'],
      ['꼬리', 'Why do you always go first, Head?'],
      ['머리', 'I have eyes to see the way. My tongue can smell, too.'],
      ['꼬리', 'That is not fair! Today I will go first!'],
      ['머리', 'Okay. Just for today.'],
      ['꼬리', 'Yay! I am the leader now!'],
      ['해설', 'But the tail had no eyes. It could not see.'],
      ['해설', 'Splash! They fell into a mud puddle.'],
      ['머리', 'Yuck! Mud in my mouth!'],
      ['해설', 'Then they went into a thorny bush.'],
      ['머리', 'Ouch, ouch! That hurts!'],
      ['해설', 'Then they got stuck between two rocks.'],
      ['꼬리', 'Help me, Head! I cannot move!'],
      ['해설', 'The head looked and found the way out.'],
      ['꼬리', 'I am sorry, Head. Leading is not easy.'],
      ['머리', 'It is okay. You help me keep my balance.'],
      ['머리', 'We are each good at different things.'],
      ['해설', 'Everyone has a job. Respect each other’s job.'],
    ],
  },

  'tm2-water-wine': {
    title: 'The Wine That Became Water',
    names: { 해설: 'Narrator', 촌장: 'Chief', 아저씨: 'Man', 아주머니: 'Woman', 아이: 'Child' },
    outro: [
      'Did you enjoy the story?',
      'If you lived in the town, what would you pour in?',
      'What is your small part at home or at school?',
    ],
    lines: [
      ['해설', 'A town was getting ready for a big party.'],
      ['촌장', 'We need wine for the party.'],
      ['촌장', 'Each home, please pour one bottle into this big barrel.'],
      ['해설', 'That night, a man held his bottle.'],
      ['아저씨', 'I want to keep my wine. I will pour water.'],
      ['아저씨', 'Nobody will know.'],
      ['해설', 'He poured water into the barrel. Trickle, trickle.'],
      ['아주머니', 'Just one bottle of water is okay.'],
      ['해설', 'The woman poured water, too.'],
      ['해설', 'The next house did the same. And the next!'],
      ['해설', 'The party day came. Boom, boom!'],
      ['촌장', 'Let us all drink wine together!'],
      ['해설', 'The chief opened the barrel. Glug, glug!'],
      ['아이', 'Hey! This is just water!'],
      ['아저씨', 'Oh no. I thought only I poured water.'],
      ['아주머니', 'Me too. I thought just one was okay.'],
      ['촌장', 'Everyone thought that. So the wine became water.'],
      ['아이', 'Let us all bring real wine now!'],
      ['해설', 'Everyone brought real wine. The party was happy.'],
      ['해설', 'Your small part matters. Do your part honestly.'],
    ],
  },
};
