// 영어 학습용 원고 (한국 초등 저학년, 영어 초급). 문장은 자체 각색.
// 키 = stories/world-euro.js 의 이야기 id. lines 의 첫 칸은 원래 이야기 cast 의 한국어 이름 그대로.
export default {
  'we-snow-maiden': {
    title: 'The Snow Maiden',
    names: { 해설: 'Narrator', 할아버지: 'Grandpa', 할머니: 'Grandma', 눈아가씨: 'Snow Girl', 친구들: 'Friends' },
    outro: [
      'Did you like the story?',
      'If you were the Snow Girl, what would you do in spring?',
      'What do you like to play in winter?',
    ],
    lines: [
      ['해설', 'Long ago in Russia, an old couple lived in a snowy village.'],
      ['해설', 'They had no children. They felt a little lonely.'],
      ['할머니', 'Let us make a little girl out of snow!'],
      ['할아버지', 'Yes! A snow girl, not a snowman.'],
      ['해설', 'They pressed the snow and made a little girl.'],
      ['해설', 'Then her eyes opened. Blink, blink!'],
      ['눈아가씨', 'Hello, Grandpa! Hello, Grandma!'],
      ['할머니', 'She can talk! Now we have a child!'],
      ['해설', 'All winter, she played with the village kids.'],
      ['친구들', 'Snow Girl, let us have a snowball fight!'],
      ['해설', 'But when spring came, she felt weak.'],
      ['눈아가씨', 'The sun is too warm. I like the shade.'],
      ['해설', 'One summer day, her friends made a campfire.'],
      ['해설', 'The Snow Girl stood near the fire.'],
      ['해설', 'She became light and turned into a white cloud.'],
      ['눈아가씨', 'I am going up to the sky. I will come back in winter!'],
      ['할머니', 'We will miss you, dear.'],
      ['해설', 'That winter, the first snow fell softly.'],
      ['할아버지', 'Look! Our girl came back as snow!'],
      ['해설', 'They caught the snowflakes and smiled.'],
      ['해설', 'This old story comes from Russia.'],
      ['해설', 'Love stays with us, even when we are apart.'],
    ],
  },

  'we-bear-tail': {
    title: 'Why the Bear Has a Short Tail',
    names: { 해설: 'Narrator', 여우: 'Fox', 곰: 'Bear' },
    outro: [
      'Was the story fun?',
      'If you were the Bear, would you believe the Fox?',
      'What can you do when something sounds too easy?',
    ],
    lines: [
      ['해설', 'Long ago, the bear had a long, fluffy tail.'],
      ['해설', 'One cold day, a fox carried a lot of fish.'],
      ['곰', 'Fox, where did you get those fish?'],
      ['여우', 'I caught them with my tail.'],
      ['곰', 'With your tail? How?'],
      ['여우', 'Make a hole in the ice. Put your tail in the water.'],
      ['여우', 'If your tail stings, the fish are biting. Wait a long time.'],
      ['곰', 'That is easy! I will do it now.'],
      ['해설', 'The bear put his long tail into the icy water.'],
      ['곰', 'Brr, it is cold! But I will wait.'],
      ['해설', 'The wind blew. The snow fell.'],
      ['해설', 'His tail stung. The bear was happy.'],
      ['곰', 'So many fish! Just a little longer!'],
      ['해설', 'But it was not fish. It was ice!'],
      ['해설', 'The water froze around his tail.'],
      ['곰', 'Now I will pull up the fish. Heave-ho!'],
      ['해설', 'The bear stood up. His tail stayed in the ice!'],
      ['해설', 'Only a short, stubby tail was left.'],
      ['곰', 'No fish, and my nice tail is short!'],
      ['여우', 'Hee hee! Do not believe everything you hear.'],
      ['해설', 'The bear ran after the fox. Stomp, stomp!'],
      ['해설', 'That is why bears have short tails today.'],
      ['해설', 'This old story comes from Norway.'],
      ['해설', 'If something sounds too easy, think again.'],
    ],
  },

  'we-finn-giant': {
    title: 'Finn and the Big Giant',
    names: { 해설: 'Narrator', 핀: 'Finn', 우나: 'Oona', 큰거인: 'Big Giant' },
    outro: [
      'Did you like the story?',
      'If you were Oona, how would you send the giant away?',
      'When did you solve a problem with a clever idea?',
    ],
    lines: [
      ['해설', 'Long ago in Ireland, there lived a giant named Finn.'],
      ['해설', 'He lived on a hill with his wife, Oona.'],
      ['해설', 'One day, they heard loud steps. Boom, boom!'],
      ['핀', 'Oh no! A much bigger giant is coming to fight me!'],
      ['우나', 'Do not worry. Let us use our heads, not our fists.'],
      ['해설', 'Oona dressed Finn like a baby. He lay in a big cradle.'],
      ['해설', 'Then she baked bread with iron inside.'],
      ['해설', 'Knock, knock! The Big Giant was at the door.'],
      ['큰거인', 'Where is Finn? I want to fight him!'],
      ['우나', 'He is out. Please have some bread.'],
      ['해설', 'The giant bit the bread. Clank! His teeth hurt.'],
      ['큰거인', 'Ouch! This bread is so hard!'],
      ['우나', 'Really? My husband eats ten every day.'],
      ['해설', 'Oona gave soft bread to baby Finn. Yum, yum!'],
      ['큰거인', 'The baby eats this too? Let me feel his teeth.'],
      ['해설', 'The giant put his finger in the cradle.'],
      ['해설', 'Finn bit it hard. Chomp!'],
      ['큰거인', 'Ow! If the baby is this strong, what about his dad?'],
      ['해설', 'The Big Giant ran home across the sea.'],
      ['핀', 'Oona, we won without a fight!'],
      ['해설', 'This old story comes from Ireland.'],
      ['해설', 'A clever idea can beat great strength.'],
    ],
  },

  'we-seal-catcher': {
    title: 'The Man Who Saved a Seal',
    names: { 해설: 'Narrator', 어부: 'Fisherman', 손님: 'Stranger', 아빠물개: 'Papa Seal', 아기물개: 'Baby Seal' },
    outro: [
      'What did you think of the story?',
      'If you were the Fisherman, what would you promise?',
      'How have you been kind to an animal?',
    ],
    lines: [
      ['해설', 'Long ago in Scotland, a fisherman caught seals.'],
      ['해설', 'One day, he hurt a baby seal on a rock.'],
      ['해설', 'The baby seal swam away. Splash!'],
      ['해설', 'That night, a stranger on a horse came to his house.'],
      ['손님', 'I want to buy many seals. Come with me.'],
      ['해설', 'They went to the edge of a high rock.'],
      ['해설', 'Then the stranger jumped into the sea with him!'],
      ['어부', 'I cannot breathe! Oh, wait. I can breathe!'],
      ['해설', 'Deep under the sea, there was a seal town.'],
      ['해설', 'The stranger was now a big seal.'],
      ['아빠물개', 'The baby you hurt is my son.'],
      ['아기물개', 'Ouch, my flipper hurts.'],
      ['어부', 'I am so sorry, little one.'],
      ['아빠물개', 'Only your touch can heal him.'],
      ['해설', 'The man gently touched the flipper. It was well again!'],
      ['아기물개', 'It does not hurt! I can swim!'],
      ['아빠물개', 'Please promise to never catch seals again.'],
      ['어부', 'I promise. I will protect my sea friends.'],
      ['해설', 'The seal took him home. There was a bag of gold.'],
      ['해설', 'The man kept his promise. He waved to the seals.'],
      ['해설', 'This old story comes from Scotland.'],
      ['해설', 'Say sorry and change, and an enemy can become a friend.'],
    ],
  },

  'we-befana': {
    title: 'Old Befana',
    names: { 해설: 'Narrator', 베파나: 'Befana', 손님: 'Visitor' },
    outro: [
      'What did you think of the story?',
      'If you were Befana, would you go with the visitors?',
      'Have you ever missed something because you were busy?',
    ],
    lines: [
      ['해설', 'Long ago in Italy, there lived an old woman named Befana.'],
      ['해설', 'Every day, she swept her house with a broom.'],
      ['베파나', 'Swish, swish! My house must be the cleanest!'],
      ['해설', 'One winter night, a bright star shone in the sky.'],
      ['해설', 'Knock, knock! Three visitors came to her door.'],
      ['손님', 'We follow that star to see a special new baby.'],
      ['손님', 'Will you come with us?'],
      ['베파나', 'Oh, I am busy. I must finish cleaning.'],
      ['해설', 'The visitors went away, following the star.'],
      ['해설', 'Befana swept and swept.'],
      ['해설', 'When she finished, she felt empty inside.'],
      ['베파나', 'I should have gone. I will go now!'],
      ['해설', 'She filled a basket with candy and cookies.'],
      ['해설', 'But the bright star was gone.'],
      ['베파나', 'Where is the baby? Is it this house?'],
      ['해설', 'She put candy in the socks of sleeping children.'],
      ['해설', 'In the morning, the children found the candy. Hooray!'],
      ['베파나', 'Their smiles make my heart warm.'],
      ['해설', 'Now she brings gifts to children every year.'],
      ['해설', 'Children in Italy wait for her on January 6.'],
      ['해설', 'Put the people you love before busy work.'],
    ],
  },

  'we-half-chick': {
    title: 'Half-Chick',
    names: { 해설: 'Narrator', 병아리: 'Half-Chick', 엄마닭: 'Mother Hen', 시냇물: 'Stream', 불: 'Fire', 바람: 'Wind' },
    outro: [
      'Was the story fun?',
      'If you were Half-Chick, would you help Stream, Fire, and Wind?',
      'What do you do when someone asks for help?',
    ],
    lines: [
      ['해설', 'Long ago on a farm in Spain, a strange chick was born.'],
      ['해설', 'He had one eye, one wing, and one leg.'],
      ['병아리', 'I am special! I will go to the city to see the king.'],
      ['엄마닭', 'Be kind to everyone, my dear.'],
      ['해설', 'Half-Chick hopped away on one leg. Hop, hop!'],
      ['시냇물', 'Chick, please move these sticks. I cannot flow.'],
      ['병아리', 'No! I am too busy.'],
      ['불', 'Chick, please give me some leaves. I am going out.'],
      ['병아리', 'No! That is your job.'],
      ['바람', 'Chick, please help me. I am stuck in a bush.'],
      ['병아리', 'No! I have no time to help!'],
      ['해설', 'In the city, he went into the palace kitchen.'],
      ['해설', 'The cook put him right next to a pot.'],
      ['병아리', 'Stream, cool the water! Fire, please be small!'],
      ['시냇물', 'You did not help me.'],
      ['불', 'You did not help me, either.'],
      ['해설', 'Half-Chick jumped out the window.'],
      ['병아리', 'Wind, please take me away!'],
      ['바람', 'I have no time to help you. Whoosh!'],
      ['해설', 'The wind blew him to the top of a tall tower.'],
      ['해설', 'He became a weathervane. He spins and spins.'],
      ['병아리', 'I should have helped my friends.'],
      ['해설', 'This old story comes from Spain.'],
      ['해설', 'Help others, and others will help you.'],
    ],
  },

  'we-wawel-dragon': {
    title: 'The Dragon of Wawel Hill',
    names: { 해설: 'Narrator', 임금님: 'King', 스쿠바: 'Skuba', 용: 'Dragon' },
    outro: [
      'Was the story fun?',
      'If you were Skuba, how would you send the dragon away?',
      'When did you solve a hard problem in a new way?',
    ],
    lines: [
      ['해설', 'Long ago in Poland, a dragon lived in a cave.'],
      ['해설', 'The cave was under Wawel Hill in Krakow.'],
      ['해설', 'The dragon took the sheep and cows from the town.'],
      ['용', 'Grr! I am hungry! Bring me more sheep!'],
      ['임금님', 'Oh no! My people will have no food.'],
      ['임금님', 'Whoever sends the dragon away will get a prize!'],
      ['해설', 'Brave knights came with swords. They all ran back.'],
      ['해설', 'Then Skuba, a young shoemaker, raised his hand.'],
      ['스쿠바', 'King, I cannot fight. But I have an idea.'],
      ['해설', 'Skuba made a toy sheep.'],
      ['해설', 'He filled it with hot, spicy yellow powder.'],
      ['해설', 'He put it in front of the cave.'],
      ['용', 'Oh, a fat sheep! Gulp!'],
      ['해설', 'Soon the dragon’s tummy was very hot.'],
      ['용', 'Hot, hot! Water, water!'],
      ['해설', 'He ran to the river and drank and drank.'],
      ['해설', 'His tummy got as big as a balloon.'],
      ['용', 'Oh, my tummy! This town is too scary.'],
      ['해설', 'The dragon flew far away. He never came back.'],
      ['임금님', 'Skuba, well done! Here is your prize.'],
      ['해설', 'Everyone danced and sang.'],
      ['해설', 'This old story comes from Krakow, Poland.'],
      ['해설', 'A smart idea can be a great power.'],
    ],
  },

  'we-rooster-coin': {
    title: 'The Rooster’s Gold Coin',
    names: { 해설: 'Narrator', 수탉: 'Rooster', 임금님: 'King', 할머니: 'Grandma' },
    outro: [
      'Was the story fun?',
      'If you were the Rooster, what would you say to the King?',
      'What can you say if someone takes your things?',
    ],
    lines: [
      ['해설', 'Long ago in Hungary, a grandma had a little rooster.'],
      ['해설', 'One day, the rooster found a shiny gold coin.'],
      ['수탉', 'Cock-a-doodle-doo! I found gold!'],
      ['해설', 'Then a greedy king came by.'],
      ['임금님', 'A gold coin! That is mine!'],
      ['해설', 'The king took the coin to his palace.'],
      ['수탉', 'Cock-a-doodle-doo! King, give back my coin!'],
      ['임금님', 'So noisy! Put him in the well!'],
      ['수탉', 'Tummy, tummy, drink the water! Gulp, gulp!'],
      ['해설', 'The rooster drank up all the water.'],
      ['수탉', 'King, give back my coin!'],
      ['임금님', 'Put him by the hot stove!'],
      ['수탉', 'Tummy, tummy, let the water out! Splash!'],
      ['해설', 'The water put out the fire. Hiss!'],
      ['임금님', 'Put him in the bee room!'],
      ['수탉', 'Tummy, tummy, take in the bees!'],
      ['해설', 'The rooster let the bees out near the king. Buzz, buzz!'],
      ['해설', 'The bees stung the king’s bottom.'],
      ['임금님', 'Ouch! All right! Take your coin!'],
      ['해설', 'The rooster went home with the coin.'],
      ['할머니', 'My brave little rooster!'],
      ['해설', 'This old story comes from Hungary.'],
      ['해설', 'Even small ones can win by standing up for what is right.'],
    ],
  },

  'we-twelve-months': {
    title: 'The Twelve Months',
    names: { 해설: 'Narrator', 엄마: 'Mother', 첫째달: 'First Month', 막내달: 'Youngest Month', 이웃: 'Neighbor' },
    outro: [
      'What did you think of the story?',
      'If you were the Mother, which month would you like best?',
      'Which month do you like best? Why?',
    ],
    lines: [
      ['해설', 'Long ago in Greece, a poor mother lived in the hills.'],
      ['해설', 'One day, she got lost on a mountain.'],
      ['해설', 'At the top, twelve brothers sat by a fire.'],
      ['첫째달', 'Welcome. We are the twelve months of the year.'],
      ['막내달', 'Which month do you like best?'],
      ['엄마', 'I like them all.'],
      ['엄마', 'Winter brings snow, and the land can rest.'],
      ['엄마', 'Spring brings flowers. Summer brings fruit.'],
      ['엄마', 'Fall brings food from the fields. Thank you all.'],
      ['첫째달', 'What kind words!'],
      ['해설', 'They filled her basket and sent her home.'],
      ['해설', 'At home, she opened it. Gold coins!'],
      ['해설', 'A greedy neighbor heard and went up the mountain.'],
      ['막내달', 'Which month do you like best?'],
      ['이웃', 'I like none of you! Winter is cold. Summer is hot.'],
      ['첫째달', 'I see. Take this basket.'],
      ['해설', 'The neighbor ran home and opened it.'],
      ['해설', 'Inside, there were only frogs. Ribbit, ribbit!'],
      ['이웃', 'Oh, I only complained. That is why.'],
      ['해설', 'After that, she looked for good things in every month.'],
      ['해설', 'This old story comes from Greece.'],
      ['해설', 'Be thankful, and every day can be a good day.'],
    ],
  },

  'we-owl-raven': {
    title: 'Why the Raven Is Black',
    names: { 해설: 'Narrator', 올빼미: 'Owl', 까마귀: 'Raven' },
    outro: [
      'Was the story fun?',
      'If you were Raven, what would you say to Owl?',
      'How do you wait when a friend makes something for you?',
    ],
    lines: [
      ['해설', 'Long ago, Owl and Raven lived in a land of snow.'],
      ['해설', 'Back then, both birds were white.'],
      ['해설', 'On long winter nights, they sewed by a lamp.'],
      ['까마귀', 'Owl, let us make clothes for each other!'],
      ['올빼미', 'Yes! I will make yours first.'],
      ['해설', 'Owl made Raven a pair of shiny boots.'],
      ['까마귀', 'Wow! Now I will make yours.'],
      ['해설', 'Raven made Owl a spotted coat.'],
      ['까마귀', 'Put it on. Now stand still!'],
      ['해설', 'But Owl was so happy. She hopped and hopped.'],
      ['올빼미', 'It is so pretty! Let me see!'],
      ['까마귀', 'Owl, please stand still!'],
      ['올빼미', 'I am too excited to stand still!'],
      ['해설', 'Raven got angry and picked up the lamp.'],
      ['해설', 'Black soot spilled all over Raven!'],
      ['까마귀', 'Oh no! My feathers are black!'],
      ['올빼미', 'I am sorry, Raven. I should have stood still.'],
      ['까마귀', 'I am sorry, too. I got angry.'],
      ['해설', 'They said sorry and became friends again.'],
      ['해설', 'Now Owl has spots, and Raven is black.'],
      ['해설', 'This story is told by the Inuit people of the Arctic.'],
      ['해설', 'Be patient and stay calm, and things go better.'],
    ],
  },

  'we-aurora-ball': {
    title: 'The Ball Game in the Sky',
    names: { 해설: 'Narrator', 아기크: 'Akik', 할머니: 'Grandma' },
    outro: [
      'What did you think of the story?',
      'If you were Akik, what would you say to the lights?',
      'How do you feel when you think of someone you miss?',
    ],
    lines: [
      ['해설', 'Far in the north, a boy named Akik lived in an igloo.'],
      ['해설', 'Winter there was long and very dark.'],
      ['아기크', 'Grandma, the night is so long. When will the sun come?'],
      ['할머니', 'Wait, dear. Tonight, a special guest will come.'],
      ['해설', 'They went outside. Crunch, crunch went the snow.'],
      ['해설', 'Then green lights danced across the sky.'],
      ['아기크', 'Wow! The sky is dancing! It is green and pink!'],
      ['할머니', 'Those are spirits playing ball in the sky.'],
      ['아기크', 'Playing ball in the sky?'],
      ['할머니', 'Yes. Our grandparents from long ago are playing.'],
      ['할머니', 'When the lights move fast, they are kicking the ball.'],
      ['아기크', 'Is Grandpa up there, too?'],
      ['할머니', 'Yes. He is kicking the ball the hardest.'],
      ['아기크', 'Hello, Grandpa! I am doing well!'],
      ['해설', 'The lights shone brighter. Twinkle, twinkle!'],
      ['할머니', 'He heard you. He is saying hello.'],
      ['아기크', 'Now the long night is not scary.'],
      ['해설', 'They held hands and went back to the warm igloo.'],
      ['해설', 'We call these dancing lights the aurora.'],
      ['해설', 'This story is told by the Inuit people of the Arctic.'],
      ['해설', 'Love for those who are gone is always with us.'],
    ],
  },

  'we-sun-reindeer': {
    title: 'The Sun’s Daughter’s Reindeer',
    names: { 해설: 'Narrator', 해님딸: 'Sun’s Daughter', 해님: 'Sun', 청년: 'Young Man' },
    outro: [
      'What did you think of the story?',
      'If you were the Sun’s Daughter, what gift would you give?',
      'How do you take care of a special gift?',
    ],
    lines: [
      ['해설', 'Long ago, the Sun and his daughter lived high in the sky.'],
      ['해설', 'The daughter took care of shining reindeer.'],
      ['해님딸', 'Father, the people in the north look cold and hungry.'],
      ['해님', 'Yes. There is only snow and ice there.'],
      ['해님딸', 'I want to go down and help them.'],
      ['해설', 'She came down on a ladder of sunlight.'],
      ['해설', 'A kind young man was blowing on his cold hands.'],
      ['청년', 'Who are you? Your light is so warm.'],
      ['해님딸', 'I am the Sun’s daughter. I came to help.'],
      ['해설', 'She brought reindeer from the sky. Jingle, jingle!'],
      ['해님딸', 'They will pull sleds and give you warm fur and milk.'],
      ['청년', 'Thank you! Now we can live through the winter!'],
      ['해님딸', 'But promise me. Always take good care of them.'],
      ['청년', 'I promise. I will care for them like family.'],
      ['해설', 'The people walked far to find moss for the reindeer.'],
      ['해설', 'The reindeer pulled their sleds. Swoosh!'],
      ['해님', 'Daughter, your gift made the land warm.'],
      ['해설', 'Even today, people in the north live with reindeer.'],
      ['해설', 'This story is told by the Sami people of northern Europe.'],
      ['해설', 'Take care of your gifts, and they will take care of you.'],
    ],
  },

  'we-kiwi': {
    title: 'How the Kiwi Lost Its Wings',
    names: { 해설: 'Narrator', 타네: 'Tane', 투이: 'Tui', 푸케코: 'Pukeko', 키위: 'Kiwi' },
    outro: [
      'What did you think of the story?',
      'If you were Kiwi, would you give up your wings?',
      'When did you give up something you liked for others?',
    ],
    lines: [
      ['해설', 'Long ago in New Zealand, Tane was the forest god.'],
      ['해설', 'The Maori people tell stories about him.'],
      ['해설', 'One day, Tane saw that the trees were sick.'],
      ['타네', 'Oh no! Bugs are eating the tree roots.'],
      ['해설', 'Tane called all the birds of the sky.'],
      ['타네', 'Who will come down and live on the ground?'],
      ['해설', 'The birds were quiet. Only the leaves rustled.'],
      ['타네', 'Tui, will you come down?'],
      ['투이', 'No. The ground is too dark. I like the sun.'],
      ['타네', 'Pukeko, will you come down?'],
      ['푸케코', 'No. The ground is too wet for my feet.'],
      ['타네', 'Kiwi, will you leave the sky and live on the ground?'],
      ['해설', 'Kiwi looked at the trees. Then at the sky.'],
      ['키위', 'Yes, I will go. I want to save our forest.'],
      ['타네', 'Thank you. But you may never fly again.'],
      ['키위', 'That is okay. I want the forest to be well.'],
      ['해설', 'Kiwi went down and ate the bugs. Peck, peck!'],
      ['해설', 'The trees grew tall and green again.'],
      ['투이', 'Thank you, Kiwi. You saved our forest.'],
      ['타네', 'Kiwi, you will be the most loved bird of all.'],
      ['해설', 'Today, people in New Zealand love the kiwi very much.'],
      ['해설', 'Children in New Zealand often hear this story.'],
      ['해설', 'Giving for others is a shining gift.'],
    ],
  },

  'we-tiddalik': {
    title: 'Tiddalik the Frog',
    names: { 해설: 'Narrator', 티달릭: 'Tiddalik', 캥거루: 'Kangaroo', 웜뱃: 'Wombat', 장어: 'Eel' },
    outro: [
      'Was the story fun?',
      'If you were Tiddalik, how would you say sorry?',
      'What funny thing did you do to make a friend laugh?',
    ],
    lines: [
      ['해설', 'Long ago in Australia, there lived a big frog named Tiddalik.'],
      ['해설', 'One morning, Tiddalik woke up very thirsty.'],
      ['티달릭', 'I am so thirsty! I will drink it all!'],
      ['해설', 'He drank the ponds, rivers, and lakes. Gulp, gulp!'],
      ['해설', 'His tummy got as big as a hill.'],
      ['캥거루', 'Oh no! There is no water left!'],
      ['웜뱃', 'We must make Tiddalik give the water back.'],
      ['캥거루', 'Let us make him laugh!'],
      ['해설', 'Kangaroo jumped on his tail. Boing, boing!'],
      ['티달릭', 'That is not funny.'],
      ['해설', 'Wombat rolled over and fell down. Bump!'],
      ['티달릭', 'That is not funny, either.'],
      ['해설', 'Then Eel came wiggling out.'],
      ['장어', 'Let me try. Watch my dance!'],
      ['해설', 'Eel twisted and curled and spun around.'],
      ['해설', 'Then he fell down. Flop!'],
      ['티달릭', 'Ha ha ha! That is so funny!'],
      ['해설', 'Water rushed out of his mouth. Whoosh!'],
      ['해설', 'The ponds, rivers, and lakes were full again.'],
      ['티달릭', 'I am sorry, everyone. Let us share the water.'],
      ['해설', 'This story is told by Aboriginal people of Australia.'],
      ['해설', 'Do not keep good things to yourself. Share them.'],
    ],
  },

  'we-menehune': {
    title: 'The Menehune’s Night',
    names: { 해설: 'Narrator', 추장: 'Chief', 메네후네: 'Menehune', 마을사람: 'Villager' },
    outro: [
      'Was the story fun?',
      'If you were a Menehune, what would you build in one night?',
      'When did you work with friends to do something big?',
    ],
    lines: [
      ['해설', 'Long ago in Hawaii, small people lived deep in the forest.'],
      ['해설', 'They were the Menehune. They were small but strong.'],
      ['해설', 'They were shy, so they only worked at night.'],
      ['추장', 'I want a fish pond, but the stones are too heavy.'],
      ['마을사람', 'Chief, let us ask the Menehune.'],
      ['추장', 'Menehune, please build us a fish pond.'],
      ['메네후네', 'Okay! But we must finish in one night.'],
      ['메네후네', 'And no one may watch us.'],
      ['추장', 'We promise. We will all stay in bed.'],
      ['해설', 'At night, they heard sounds from the forest.'],
      ['해설', 'The Menehune passed stones from hand to hand.'],
      ['메네후네', 'Take one, pass one! Heave-ho!'],
      ['해설', 'Thump, thump! The stone wall grew and grew.'],
      ['마을사람', 'I want to look. But a promise is a promise.'],
      ['해설', 'Just before sunrise, the last stone went in.'],
      ['해설', 'In the morning, there was a big fish pond!'],
      ['추장', 'Wow! They built it in one night!'],
      ['해설', 'The chief left lots of shrimp as a thank-you gift.'],
      ['메네후네', 'Yum! The shrimp are so good. Thank you!'],
      ['해설', 'This story is told by the people of Hawaii.'],
      ['해설', 'Keep promises and work together to do great things.'],
    ],
  },

  'we-eat-coat': {
    title: 'Eat, My Coat, Eat!',
    names: { 해설: 'Narrator', 나스레딘: 'Nasreddin', 주인: 'Host', 하인: 'Servant' },
    outro: [
      'Was the story fun?',
      'If you were Nasreddin, what would you say to the host?',
      'What should we look at first in a person?',
    ],
    lines: [
      ['해설', 'Long ago in Turkey, there lived a funny man named Nasreddin.'],
      ['해설', 'One day, he was invited to a big party.'],
      ['해설', 'He came from the field in old, dirty clothes.'],
      ['나스레딘', 'Hello! Thank you for inviting me!'],
      ['하인', 'Um, sit over there in the corner.'],
      ['해설', 'No one gave him any food.'],
      ['나스레딘', 'Hmm. It must be my clothes.'],
      ['해설', 'He went home and put on his best coat.'],
      ['해설', 'He came back. Now everyone smiled at him.'],
      ['주인', 'Welcome, dear guest! Sit here, please!'],
      ['하인', 'Please have some soup and chicken.'],
      ['해설', 'But Nasreddin did not pick up his spoon.'],
      ['해설', 'He put his coat sleeve in the soup.'],
      ['나스레딘', 'Eat, my coat, eat! Yum, yum!'],
      ['주인', 'Sir! What are you doing?'],
      ['나스레딘', 'In my old clothes, no one gave me food.'],
      ['나스레딘', 'My nice coat came, and the food came.'],
      ['나스레딘', 'So my coat should eat this food.'],
      ['주인', 'I looked only at clothes. I am so sorry.'],
      ['해설', 'Everyone laughed and ate together.'],
      ['해설', 'Nasreddin stories are told in Turkey and the Middle East.'],
      ['해설', 'Look at a person’s heart, not their clothes.'],
    ],
  },

  'we-pot-baby': {
    title: 'The Pot Had a Baby',
    names: { 해설: 'Narrator', 나스레딘: 'Nasreddin', 이웃: 'Neighbor' },
    outro: [
      'Was the story fun?',
      'If you were the Neighbor, would you believe the pot had a baby?',
      'Do you only believe words that are good for you?',
    ],
    lines: [
      ['해설', 'One day, Nasreddin borrowed a big pot from his neighbor.'],
      ['나스레딘', 'May I use your pot for a party?'],
      ['이웃', 'Sure. Please bring it back.'],
      ['해설', 'Days later, he gave back the big pot.'],
      ['해설', 'Inside it, there was a little pot.'],
      ['이웃', 'What is this little pot?'],
      ['나스레딘', 'Good news! Your pot had a baby!'],
      ['이웃', 'Ha ha! A baby pot! Lucky me!'],
      ['해설', 'Weeks later, Nasreddin came again.'],
      ['나스레딘', 'May I use your big pot one more time?'],
      ['이웃', 'Of course! Take it!'],
      ['해설', 'The neighbor waited for another baby pot.'],
      ['해설', 'But days went by. No pot came back.'],
      ['이웃', 'Nasreddin, where is my pot?'],
      ['나스레딘', 'I have sad news. Your pot is gone forever.'],
      ['이웃', 'What? A pot cannot do that!'],
      ['나스레딘', 'But you believed a pot could have a baby.'],
      ['나스레딘', 'If it can have a baby, it can go away, too.'],
      ['이웃', 'Oh! I only believed what was good for me.'],
      ['해설', 'Nasreddin smiled and gave back the big pot.'],
      ['해설', 'Nasreddin stories are told in Turkey and the Middle East.'],
      ['해설', 'Do not believe only the words you like. Think carefully.'],
    ],
  },

  'we-camels': {
    title: 'The Seventeen Camels',
    names: { 해설: 'Narrator', 첫째: 'Oldest', 둘째: 'Middle', 막내: 'Youngest', 노인: 'Wise Man' },
    outro: [
      'Was the story fun?',
      'If you were the Wise Man, how would you help the brothers?',
      'What is a good way to share with friends?',
    ],
    lines: [
      ['해설', 'Long ago in the desert, a father had seventeen camels.'],
      ['해설', 'He gave them to his three sons.'],
      ['해설', 'The oldest would get one half. The middle son would get one third.'],
      ['해설', 'The youngest would get one ninth.'],
      ['첫째', 'Half of seventeen is eight and a half. We cannot cut a camel!'],
      ['둘째', 'One third does not work, either!'],
      ['막내', 'One ninth does not work. What can we do?'],
      ['해설', 'The brothers started to fight.'],
      ['첫째', 'I am the oldest. I should get more!'],
      ['둘째', 'No! That is not fair!'],
      ['해설', 'Then a wise man came by on his camel.'],
      ['노인', 'Boys, why are you fighting?'],
      ['막내', 'We cannot share seventeen camels.'],
      ['노인', 'Then I will add my camel. Now there are eighteen.'],
      ['노인', 'Half of eighteen is nine. One third is six.'],
      ['노인', 'One ninth is two.'],
      ['해설', 'Nine, six, and two. That makes seventeen!'],
      ['막내', 'Look! One camel is left!'],
      ['노인', 'Ha ha! That one is my camel.'],
      ['해설', 'The wise man rode away, whistling.'],
      ['둘째', 'Brother, I am sorry I yelled.'],
      ['첫째', 'I am sorry, too. Let us be good brothers.'],
      ['해설', 'This wise story comes from the deserts of Arabia.'],
      ['해설', 'When you fight, add a little kindness and find a way.'],
    ],
  },
};
