// 영어 학습용 원고 (한국 초등 저학년, 영어 초급). 문장은 자체 집필.
// 키 = stories/nature2.js 의 이야기 id. lines 의 첫 칸은 원래 이야기 cast 의 한국어 이름 그대로.
export default {
  'nt2-frog': {
    title: 'From Tadpole to Frog',
    names: { 해설: 'Narrator', 올챙이: 'Tadpole', 엄마개구리: 'Mother Frog', 송사리: 'Little Fish' },
    outro: [
      'Did you like the story?',
      'If you were the Tadpole, how would you feel with new legs?',
      'How are you different from when you were a baby?',
    ],
    lines: [
      ['해설', 'It was spring. Frog eggs floated in a little pond.'],
      ['엄마개구리', 'Grow well in the warm sun, my babies.'],
      ['해설', 'Soon, little black dots in the eggs began to wiggle.'],
      ['올챙이', 'Hello! I am a tadpole. I just came out!'],
      ['해설', 'The tadpole had a round head and a long tail.'],
      ['올챙이', 'Swish, swish! My tail helps me swim fast.'],
      ['송사리', 'Are you a fish? You breathe in the water like me.'],
      ['올챙이', 'I do not know. My mom is a frog.'],
      ['송사리', 'You are a frog? You do not look like one!'],
      ['해설', 'The tadpole ate water plants and grew bigger.'],
      ['해설', 'One day, two back legs came out. Pop!'],
      ['해설', 'Later, two front legs came out too.'],
      ['올챙이', 'Look! I have four legs now!'],
      ['올챙이', 'But my tail is getting shorter.'],
      ['엄마개구리', 'Do not worry. Your tail will go away.'],
      ['해설', 'Inside, the tadpole grew lungs to breathe air.'],
      ['해설', 'When the tail was gone, the tadpole was a frog.'],
      ['올챙이', 'Ribbit, ribbit! I am a real frog now!'],
      ['해설', 'The little frog jumped onto a lily pad. Hop!'],
      ['엄마개구리', 'Now you will eat little flying bugs.'],
      ['송사리', 'Come and visit me, okay?'],
      ['해설', 'We all grow at our own speed, and that is okay.'],
    ],
  },

  'nt2-butterfly': {
    title: 'From Caterpillar to Butterfly',
    names: { 해설: 'Narrator', 애벌레: 'Caterpillar', 무당벌레: 'Ladybug' },
    outro: [
      'Was the story fun?',
      'If you were in the chrysalis, what would you think about?',
      'When did you wait a long time for something good?',
    ],
    lines: [
      ['해설', 'A tiny egg was on a cabbage leaf.'],
      ['해설', 'One day, a little caterpillar came out.'],
      ['애벌레', 'I am hungry! First, I will eat my eggshell.'],
      ['애벌레', 'Now the cabbage leaf! Munch, munch!'],
      ['무당벌레', 'You eat all day long!'],
      ['애벌레', 'Yes! Eating is my job. I must grow big.'],
      ['해설', 'When it grew, it took off its old skin.'],
      ['애벌레', 'My old skin was too tight. Now I feel good!'],
      ['해설', 'The caterpillar became big, fat, and green.'],
      ['애벌레', 'Now I am full and sleepy.'],
      ['해설', 'It held on to a stem with silk.'],
      ['해설', 'Then it became a hard chrysalis.'],
      ['무당벌레', 'Caterpillar, are you in there?'],
      ['해설', 'The chrysalis did not eat or move.'],
      ['해설', 'But inside, its body was changing.'],
      ['해설', 'After about ten days, the chrysalis opened.'],
      ['무당벌레', 'Wow! You have white wings!'],
      ['해설', 'The wings opened and dried in the sun.'],
      ['애벌레', 'I am a butterfly now! Flap, flap!'],
      ['해설', 'It drank sweet nectar with its long, curly mouth.'],
      ['해설', 'Egg, caterpillar, chrysalis, butterfly. That is its life cycle.'],
      ['해설', 'Quiet waiting time is also growing time.'],
    ],
  },

  'nt2-bee-dance': {
    title: 'The Honeybee Dance',
    names: { 해설: 'Narrator', 일벌: 'Worker Bee', 막내벌: 'Little Bee', 언니벌: 'Big Sister Bee' },
    outro: [
      'Did you like the story?',
      'If you were a bee, how would you dance?',
      'Did you ever tell something without words?',
    ],
    lines: [
      ['해설', 'Inside a beehive, the bees were very busy. Buzz, buzz!'],
      ['막내벌', 'Sister, how do we find the flowers?'],
      ['언니벌', 'A bee will tell us with a dance. Watch!'],
      ['해설', 'A worker bee flew into the hive.'],
      ['일벌', 'I found flowers! So many flowers!'],
      ['해설', 'The worker bee danced round and round.'],
      ['언니벌', 'A round dance means the flowers are very close.'],
      ['막내벌', 'Wow! She does not need words!'],
      ['언니벌', 'Smell her, too. Find flowers with that smell.'],
      ['해설', 'Then another bee came back from far away.'],
      ['일벌', 'This time, the flowers are far. Watch me!'],
      ['해설', 'She danced in the shape of an eight.'],
      ['해설', 'In the middle, she wiggled her bottom. Wiggle, wiggle!'],
      ['막내벌', 'A bottom dance! That is so funny!'],
      ['언니벌', 'The wiggle shows the way to the flowers.'],
      ['언니벌', 'The dance uses the sun to show the way.'],
      ['언니벌', 'A long wiggle means the flowers are far.'],
      ['해설', 'Little Bee flew out with the other bees.'],
      ['막내벌', 'Here they are! Lots of flowers!'],
      ['해설', 'She drank nectar and got pollen on her legs.'],
      ['막내벌', 'Now I will go back and dance, too!'],
      ['해설', 'When you find something good, share it with friends.'],
    ],
  },

  'nt2-ant-trail': {
    title: 'The Ant Smell Road',
    names: { 해설: 'Narrator', 정찰개미: 'Scout Ant', 꼬마개미: 'Little Ant', 아이: 'Child' },
    outro: [
      'Was the story fun?',
      'If you were Little Ant, how would you feel on the smell road?',
      'What did you do together with your friends?',
    ],
    lines: [
      ['해설', 'An ant walked under a bench at the playground.'],
      ['해설', 'It was a scout ant. It looked for food.'],
      ['정찰개미', 'Sniff, sniff. I smell something sweet!'],
      ['해설', 'Ants smell with their feelers.'],
      ['정찰개미', 'Cookie crumbs! I must tell my friends.'],
      ['해설', 'On the way home, it touched the ground with its tail end.'],
      ['정찰개미', 'I make a smell road for my friends.'],
      ['정찰개미', 'Everyone! I found food! Follow the smell road!'],
      ['꼬마개미', 'Where? I cannot see a road.'],
      ['정찰개미', 'Do not look. Smell it with your feelers.'],
      ['꼬마개미', 'Sniff, sniff. Oh! I can smell the road!'],
      ['해설', 'The ants walked in a long line.'],
      ['해설', 'More ants made the smell stronger.'],
      ['아이', 'Look, Mom! The ants walk like a train!'],
      ['꼬마개미', 'This crumb is too big for me.'],
      ['정찰개미', 'Let us carry it together. One, two, lift!'],
      ['해설', 'The ants carried the food home together.'],
      ['해설', 'When the food was gone, the smell faded away.'],
      ['꼬마개미', 'No food, no road! How smart!'],
      ['아이', 'The ants talk with smells!'],
      ['해설', 'Small ants can do big things when they work together.'],
    ],
  },

  'nt2-spider-web': {
    title: 'The Sticky Spider Web',
    names: { 해설: 'Narrator', 거미: 'Spider', 나방: 'Moth' },
    outro: [
      'Did you like the story?',
      'If you were the Spider, where would you make your web?',
      'Did you ever see water drops on a spider web?',
    ],
    lines: [
      ['해설', 'In the morning, a round web shone in the grass.'],
      ['해설', 'A spider sat in the middle of the web.'],
      ['나방', 'Spider, where does your silk come from?'],
      ['거미', 'It comes out of the end of my body.'],
      ['나방', 'It is so thin. Will it break?'],
      ['거미', 'It is thin, but it is very strong.'],
      ['해설', 'First, the spider made lines like a wheel.'],
      ['거미', 'These lines are not sticky. I walk on them.'],
      ['해설', 'Then it made a round and round line.'],
      ['거미', 'This line has tiny drops of glue.'],
      ['나방', 'Why do you make sticky lines?'],
      ['거미', 'Little bugs get stuck. Then I have dinner.'],
      ['나방', 'Oh! I must be careful, then!'],
      ['나방', 'Why do you not get stuck?'],
      ['거미', 'I walk on the lines that are not sticky.'],
      ['거미', 'And I step very, very softly.'],
      ['해설', 'Then a leaf fell on the web. Shake, shake!'],
      ['해설', 'The spider ran to it fast.'],
      ['거미', 'Oh, it is just a leaf!'],
      ['해설', 'Spiders feel the web shake to know what is there.'],
      ['해설', 'The spider fixed the web with new silk.'],
      ['해설', 'Even small spiders have their own great skills.'],
    ],
  },

  'nt2-dandelion': {
    title: 'The Dandelion Seed Trip',
    names: { 해설: 'Narrator', 민들레: 'Dandelion', 씨앗: 'Seed', 바람: 'Wind' },
    outro: [
      'Was the story fun?',
      'If you were the Seed, where would you fly?',
      'Did you ever blow on a dandelion puff?',
    ],
    lines: [
      ['해설', 'In spring, a yellow dandelion bloomed by the road.'],
      ['민들레', 'I look like one flower, but I am not.'],
      ['민들레', 'I am many tiny flowers together.'],
      ['해설', 'Later, the dandelion became a white puffball.'],
      ['씨앗', 'Mom, we all have little white umbrellas!'],
      ['민들레', 'They help you fly in the wind.'],
      ['해설', 'The dandelion stem grew taller.'],
      ['민들레', 'A tall stem can catch the wind.'],
      ['씨앗', 'Why must we go far away?'],
      ['민들레', 'Here, there is not enough sun and water for all.'],
      ['해설', 'Then the wind came. Whoosh!'],
      ['바람', 'Little seeds! Are you ready for a trip?'],
      ['씨앗', 'I am a little scared, but yes!'],
      ['해설', 'The seeds flew up into the sky.'],
      ['씨앗', 'I am flying! I can see a river!'],
      ['바람', 'Hold on! I will take you far.'],
      ['해설', 'The seed landed softly on the ground.'],
      ['씨앗', 'This is my new home. Thank you, Wind!'],
      ['해설', 'The rain came, and a tiny root came out.'],
      ['해설', 'The next spring, a new dandelion bloomed.'],
      ['씨앗', 'Look, Mom! I am a flower now!'],
      ['해설', 'Be brave, and you can bloom in a new place.'],
    ],
  },

  'nt2-salmon': {
    title: 'The Salmon Goes Home',
    names: { 해설: 'Narrator', 연어: 'Salmon', 물새: 'Water Bird', 아기연어: 'Baby Salmon' },
    outro: [
      'Did you like the story?',
      'If you were the Salmon, what would you say at the waterfall?',
      'Where is the coziest place for you?',
    ],
    lines: [
      ['해설', 'A baby salmon was born in a clear mountain stream.'],
      ['아기연어', 'The water here is cold and clean!'],
      ['해설', 'The baby salmon swam down the river.'],
      ['해설', 'The river went into the big sea.'],
      ['아기연어', 'Yuck! The water is salty! This is the sea!'],
      ['해설', 'The salmon lived in the sea for a few years.'],
      ['해설', 'It ate a lot and grew big.'],
      ['연어', 'Now I must go home to my stream.'],
      ['물새', 'Salmon, the sea is so big. How do you find home?'],
      ['연어', 'In the sea, I can feel the way.'],
      ['연어', 'In the river, I smell my home stream!'],
      ['물새', 'You find home by smell? Wow!'],
      ['해설', 'The salmon swam up the river.'],
      ['해설', 'The water was strong. Splash, splash!'],
      ['해설', 'Then there was a little waterfall.'],
      ['연어', 'One, two, three! Jump!'],
      ['해설', 'The salmon jumped high over the water.'],
      ['물새', 'You did it! Go, Salmon!'],
      ['해설', 'At last, the salmon came back to its stream.'],
      ['해설', 'The salmon dug in the stones and laid eggs.'],
      ['해설', 'In spring, many baby salmon came out.'],
      ['아기연어', 'Someday, I will go to the sea and come back!'],
      ['해설', 'Salmon never forget their home, even far away.'],
    ],
  },

  'nt2-wild-geese': {
    title: 'The Long Trip of the Geese',
    names: { 해설: 'Narrator', 아빠기러기: 'Papa Goose', 꼬마기러기: 'Little Goose', 참새: 'Sparrow' },
    outro: [
      'Was the story fun?',
      'If you were in front, what would you say to a tired friend?',
      'When did you take turns with a friend?',
    ],
    lines: [
      ['해설', 'In fall, the land in the north gets very cold.'],
      ['아빠기러기', 'Children, it is time to fly south.'],
      ['꼬마기러기', 'Is it far? I have never flown so far.'],
      ['아빠기러기', 'It is far. But we can do it together.'],
      ['해설', 'The geese flew up into the sky. Honk, honk!'],
      ['해설', 'They flew in the shape of a big V.'],
      ['꼬마기러기', 'Papa, why do we fly like this?'],
      ['아빠기러기', 'It makes flying easier for the birds behind.'],
      ['해설', 'The goose in front got tired.'],
      ['해설', 'So it went to the back. Another goose led.'],
      ['꼬마기러기', 'We take turns! That is so cool!'],
      ['해설', 'The geese in the back honked to cheer.'],
      ['꼬마기러기', 'Papa, how do we find the way?'],
      ['아빠기러기', 'We look at the sun in the day.'],
      ['아빠기러기', 'At night, we look at the stars.'],
      ['해설', 'They flew over mountains and the sea.'],
      ['꼬마기러기', 'Papa, my wings hurt.'],
      ['아빠기러기', 'Let us rest in that rice field.'],
      ['참새', 'Hello! Where did you come from?'],
      ['꼬마기러기', 'From the cold north. We will stay for winter.'],
      ['아빠기러기', 'We move with the seasons. We are migrating birds.'],
      ['해설', 'A long trip is easier when we go together.'],
    ],
  },

  'nt2-bear-sleep': {
    title: 'The Bear’s Winter Sleep',
    names: { 해설: 'Narrator', 반달곰: 'Mother Bear', 다람쥐: 'Chipmunk', 아기곰: 'Baby Bear' },
    outro: [
      'Did you like the story?',
      'If you were the Bear, what would you eat before winter?',
      'How do you feel after a good long sleep?',
    ],
    lines: [
      ['해설', 'It was fall. The leaves were red and yellow.'],
      ['해설', 'A black bear ate and ate.'],
      ['반달곰', 'Yum! Acorns, berries, and honey!'],
      ['다람쥐', 'Why do you eat so much?'],
      ['반달곰', 'I will sleep all winter. I will not eat.'],
      ['반달곰', 'So I need to get fat now.'],
      ['다람쥐', 'I keep acorns in my hole for winter.'],
      ['해설', 'The bear got rounder every day.'],
      ['해설', 'A cold wind blew. The bear went into a cave.'],
      ['반달곰', 'Soft leaves for my bed. Good night.'],
      ['해설', 'Snow fell, and the mountain turned white.'],
      ['해설', 'In winter sleep, the bear breathes very slowly.'],
      ['해설', 'Her body uses the fat for food.'],
      ['해설', 'In the middle of winter, there was a tiny sound.'],
      ['아기곰', 'Squeak, squeak.'],
      ['해설', 'The mother bear had a baby in the cave!'],
      ['반달곰', 'Drink my milk and stay warm, little one.'],
      ['해설', 'Then spring came. The snow melted.'],
      ['반달곰', 'Yawn! I slept well. Now I am thin.'],
      ['아기곰', 'Mom, the world is so bright!'],
      ['다람쥐', 'You have a baby! Hooray!'],
      ['해설', 'Get ready early and rest well to get through hard times.'],
    ],
  },

  'nt2-bat': {
    title: 'The Bat Who Sees with Sound',
    names: { 해설: 'Narrator', 박쥐: 'Bat', 부엉이: 'Owl', 아이: 'Child' },
    outro: [
      'Was the story fun?',
      'If you were the Bat, where would you fly at night?',
      'Can you guess things with your eyes closed?',
    ],
    lines: [
      ['해설', 'The sun went down. The sky was dark.'],
      ['해설', 'A bat hung upside down in a cave.'],
      ['박쥐', 'Yawn! Now it is time to work.'],
      ['해설', 'The bat flew out into the night sky.'],
      ['부엉이', 'Hoo, hoo! Bat, can you see in the dark?'],
      ['박쥐', 'I can see a little. But my ears help more.'],
      ['박쥐', 'I make very high sounds when I fly.'],
      ['부엉이', 'Sounds? I cannot hear anything.'],
      ['박쥐', 'They are too high for most people to hear.'],
      ['해설', 'These very high sounds are called ultrasound.'],
      ['박쥐', 'The sounds hit a tree and come back.'],
      ['박쥐', 'Then I know where things are.'],
      ['부엉이', 'Like an echo in the mountains?'],
      ['박쥐', 'Yes! But I do it very fast.'],
      ['아이', 'Ouch! A mosquito bit me again!'],
      ['해설', 'Whoosh! The bat caught the mosquito.'],
      ['박쥐', 'Mosquitoes and moths are my dinner.'],
      ['부엉이', 'You eat bugs that hurt farm plants, too!'],
      ['아이', 'Thank you, Bat! You are a good friend.'],
      ['박쥐', 'I am not a bird. My babies drink milk.'],
      ['해설', 'In the morning, the bat went back to sleep.'],
      ['해설', 'Do not judge by looks. See what someone does.'],
    ],
  },

  'nt2-sunflower': {
    title: 'A Sunflower’s Day',
    names: { 해설: 'Narrator', 해바라기: 'Sunflower', 할머니: 'Grandma', 나비: 'Butterfly' },
    outro: [
      'Did you like the story?',
      'If you were the young Sunflower, what would you say to the sun?',
      'What did you like when you were little?',
    ],
    lines: [
      ['해설', 'In summer, a young sunflower was growing in a field.'],
      ['해설', 'It had a green bud, but no flower yet.'],
      ['해바라기', 'Good morning, Sun! You came from the east!'],
      ['해설', 'In the morning, the bud looked east at the sun.'],
      ['해설', 'In the evening, it slowly turned to the west.'],
      ['나비', 'You follow the sun all day!'],
      ['해바라기', 'Yes! The sun helps me grow.'],
      ['해설', 'At night, the sunflower turned back to the east.'],
      ['해바라기', 'I want to see the sun first tomorrow!'],
      ['해설', 'The sunflower grew taller than a grown-up.'],
      ['해설', 'One morning, a big yellow flower opened.'],
      ['나비', 'Wow! You look like the sun!'],
      ['해바라기', 'But now my head does not turn.'],
      ['할머니', 'Grown-up sunflowers stop turning. Most face east.'],
      ['해바라기', 'So only young sunflowers follow the sun?'],
      ['할머니', 'Yes. The morning sun warms the flower.'],
      ['할머니', 'Bees and butterflies like warm flowers.'],
      ['해설', 'Bees and butterflies came. Buzz! Flap!'],
      ['해설', 'In fall, the flower was full of black seeds.'],
      ['해바라기', 'My seeds will follow the sun next year!'],
      ['해설', 'As we grow, we change, and each time has its job.'],
    ],
  },

  'nt2-sea-turtle': {
    title: 'The Baby Sea Turtles',
    names: { 해설: 'Narrator', 엄마거북: 'Mother Turtle', 아기거북: 'Baby Turtle', 게: 'Crab' },
    outro: [
      'Was the story fun?',
      'If you were the Baby Turtle, how would you feel in the sea?',
      'What can you do to help sea turtles at the beach?',
    ],
    lines: [
      ['해설', 'On a summer night, a mother turtle came out of the sea.'],
      ['엄마거북', 'This is the beach where I was born.'],
      ['해설', 'She dug a hole in the sand.'],
      ['해설', 'She laid about one hundred round eggs.'],
      ['엄마거북', 'The warm sand will keep you safe.'],
      ['해설', 'She covered the eggs and went back to the sea.'],
      ['해설', 'The sun warmed the sand for about two months.'],
      ['해설', 'One night, the eggs cracked. Tap, tap!'],
      ['아기거북', 'I am out! Let us go up together!'],
      ['해설', 'The babies pushed the sand up and up.'],
      ['아기거북', 'Where do we go? Nobody tells us.'],
      ['게', 'Look there! The bright, shiny side is the sea!'],
      ['해설', 'Baby turtles find the sea by its light.'],
      ['아기거북', 'I see it! Let us hurry!'],
      ['게', 'Be careful! Do not go to the street lights!'],
      ['해설', 'Bright lights can make baby turtles lost.'],
      ['해설', 'So some beaches turn off their lights at night.'],
      ['해설', 'Splash! The first wave hugged the baby turtle.'],
      ['아기거북', 'Wow! The sea is cool and big!'],
      ['아기거북', 'Someday, I will come back to this beach.'],
      ['게', 'Goodbye, baby turtles! Grow strong!'],
      ['해설', 'Keep beaches clean and dark to help baby turtles.'],
    ],
  },
};
