// 영어 학습용 원고 (한국 초등 저학년, 영어 초급). 문장은 자체 각색.
// 키 = stories/andersen2.js 의 이야기 id. lines 의 첫 칸은 원래 이야기 cast 의 한국어 이름 그대로.
export default {
  'an2-tinderbox': {
    title: 'The Tinderbox',
    names: { 해설: 'Narrator', 병사: 'Soldier', 할멈: 'Old Woman', 임금님: 'King', 공주: 'Princess' },
    outro: [
      'Did you like the story?',
      'If you were the Soldier, what would you ask the dogs?',
      'Who would you help with a magic box?',
    ],
    lines: [
      ['해설', 'Once upon a time, a soldier walked home.'],
      ['할멈', 'Soldier, there is money in this tree.'],
      ['할멈', 'Take the money. Just bring me the old tinderbox.'],
      ['병사', 'Okay! That is easy.'],
      ['해설', 'He went down into the tree.'],
      ['해설', 'He saw three dogs with very big eyes.'],
      ['해설', 'They sat on boxes of coins.'],
      ['병사', 'Wow, what big eyes! Please stay still.'],
      ['해설', 'He took gold and the tinderbox.'],
      ['병사', 'What is this old box for?'],
      ['할멈', 'That is not for you to know!'],
      ['해설', 'The old woman got angry and ran away.'],
      ['해설', 'Later, the soldier spent all his money.'],
      ['병사', 'I have no money for a candle. I will use this box.'],
      ['해설', 'Click! A big dog came out. It gave him anything!'],
      ['해설', 'He was rich again. He helped poor people.'],
      ['해설', 'At night, the dog took the princess to see stars.'],
      ['임금님', 'Who takes my daughter out at night? Catch him!'],
      ['해설', 'The soldier went to jail.'],
      ['해설', 'Click, click, click! Three dogs ran in.'],
      ['공주', 'Father, he is kind. He showed me the stars.'],
      ['임금님', 'I see. I kept you inside too long.'],
      ['해설', 'The soldier and the princess got married.'],
      ['해설', 'Remember hard times, and share with others.'],
    ],
  },

  'an2-flying-trunk': {
    title: 'The Flying Trunk',
    names: { 해설: 'Narrator', 청년: 'Young Man', 공주: 'Princess', 왕비: 'Queen', 임금님: 'King' },
    outro: [
      'How was the story?',
      'If you were the Young Man, what would you tell the Princess?',
      'Where would you fly in a magic trunk?',
    ],
    lines: [
      ['해설', 'Once upon a time, a rich man had a son.'],
      ['해설', 'The son spent all the money.'],
      ['해설', 'A friend gave him an old trunk.'],
      ['청년', 'I have nothing to pack. I will sit in it.'],
      ['해설', 'He pushed the lock. The trunk flew up!'],
      ['청년', 'Wow! My trunk can fly!'],
      ['해설', 'Whoosh! He flew to a faraway land.'],
      ['해설', 'A princess lived in a tall tower.'],
      ['해설', 'At night, he flew to her window. Knock, knock.'],
      ['공주', 'Who are you? How did you get here?'],
      ['청년', 'I came down from the sky.'],
      ['해설', 'He told her many fun stories.'],
      ['왕비', 'You are from the sky? Tell us a story, too.'],
      ['임금님', 'Ha ha, very good! You may marry the Princess.'],
      ['해설', 'Before the wedding, he bought lots of fireworks.'],
      ['해설', 'Bang, bang! Fireworks filled the night sky.'],
      ['해설', 'But a spark fell on the trunk.'],
      ['해설', 'The trunk was burned. It could not fly.'],
      ['청년', 'Oh no. I said I came from the sky.'],
      ['해설', 'He was ashamed. He did not go back.'],
      ['해설', 'After that, he told stories from town to town.'],
      ['공주', 'When will he come back?'],
      ['해설', 'Do not show off. Telling the truth is better.'],
    ],
  },

  'an2-fir-tree': {
    title: 'The Fir Tree',
    names: { 해설: 'Narrator', 전나무: 'Fir Tree', 참새: 'Sparrow', 아이: 'Child', 생쥐: 'Mouse' },
    outro: [
      'Did you like the story?',
      'If you were the Fir Tree, what would you enjoy in the forest?',
      'What was the best part of your day today?',
    ],
    lines: [
      ['해설', 'A little fir tree lived in the forest.'],
      ['해설', 'The sun and the wind were kind to it.'],
      ['전나무', 'When will I be big? I want to grow fast!'],
      ['해설', 'A rabbit jumped over the little tree. Hop!'],
      ['전나무', 'Oh! A rabbit jumped over me. I am sad.'],
      ['해설', 'The sun said, enjoy growing now.'],
      ['해설', 'But the tree did not listen.'],
      ['전나무', 'Sparrow, where do those trees go?'],
      ['참새', 'Tweet! They go to warm houses. People make them pretty.'],
      ['전나무', 'I want to go, too!'],
      ['해설', 'Years later, the fir tree went to a big house.'],
      ['해설', 'People put candy, candles, and a star on it.'],
      ['아이', 'Wow, a Christmas tree! It is so pretty!'],
      ['해설', 'The children sang and danced around the tree.'],
      ['해설', 'The next day, people put the tree in the dark attic.'],
      ['전나무', 'Why is it so dark and quiet here?'],
      ['생쥐', 'Tree, can you tell us about the forest?'],
      ['전나무', 'I was happy in the forest. Now I know.'],
      ['해설', 'In spring, people took the tree outside.'],
      ['해설', 'A pinecone fell from the tree. Plop!'],
      ['아이', 'Little pinecone, I will plant you in the forest.'],
      ['전나무', 'Little one, enjoy every day.'],
      ['해설', 'Enjoy today. Do not just wait for tomorrow.'],
    ],
  },

  'an2-red-shoes': {
    title: 'The Red Shoes',
    names: { 해설: 'Narrator', 카렌: 'Karen', 할머니: 'Grandma', 군인: 'Old Soldier' },
    outro: [
      'How was the story?',
      'If you were Karen, would you stay with Grandma?',
      'When did you want something but had a job to do?',
    ],
    lines: [
      ['해설', 'Once upon a time, there was a poor girl, Karen.'],
      ['해설', 'She had no shoes.'],
      ['할머니', 'Karen, come and live with me.'],
      ['카렌', 'Thank you, Grandma! I will be good.'],
      ['해설', 'One day, Karen saw shiny red shoes.'],
      ['카렌', 'They are so pretty! I want them!'],
      ['해설', 'Karen wore the red shoes to church.'],
      ['할머니', 'Karen, wear black shoes to church.'],
      ['카렌', 'Okay. But the red shoes are prettier.'],
      ['군인', 'What fine dancing shoes! Stay on when she dances.'],
      ['해설', 'Then Grandma got sick.'],
      ['할머니', 'Cough, cough. Karen, please stay with me today.'],
      ['카렌', 'I will be back soon. I want to dance.'],
      ['해설', 'Karen put on the red shoes. Her feet began to dance.'],
      ['해설', 'Tap, tap, spin, spin! The shoes did not stop.'],
      ['카렌', 'Stop! Please stop!'],
      ['해설', 'She danced through fields and forests all night.'],
      ['카렌', 'I left sick Grandma alone. I was wrong.'],
      ['카렌', 'I am so sorry. I want to go home.'],
      ['해설', 'Then the shoes stopped. They came off her feet.'],
      ['해설', 'Karen ran all the way home.'],
      ['카렌', 'Grandma, I will take care of you now.'],
      ['할머니', 'Thank you for coming back, my dear.'],
      ['해설', 'People we love are more important than pretty things.'],
    ],
  },

  'an2-five-peas': {
    title: 'Five Peas in a Pod',
    names: { 해설: 'Narrator', 첫째콩: 'First Pea', 둘째콩: 'Second Pea', 막내콩: 'Little Pea', 소녀: 'Girl', 엄마: 'Mom' },
    outro: [
      'Did you like the story?',
      'If you were the Little Pea, what would you say to the Girl?',
      'When did a small thing make you happy?',
    ],
    lines: [
      ['해설', 'Five green peas sat in one pod.'],
      ['첫째콩', 'When can we go out? I want to see the world!'],
      ['해설', 'One day, the pod popped open. Pop!'],
      ['해설', 'A boy put the peas in his toy shooter.'],
      ['첫째콩', 'I will fly far, far away! Whoosh!'],
      ['둘째콩', 'I will fly to the sun! Whoosh!'],
      ['해설', 'Two peas rolled into a puddle.'],
      ['해설', 'They got fat and said, we are the best.'],
      ['막내콩', 'I will grow well, wherever I go.'],
      ['해설', 'The little pea flew into a window crack.'],
      ['해설', 'A sick girl lived in that room.'],
      ['엄마', 'I must go to work. I will be back soon.'],
      ['해설', 'In spring, a green sprout came up.'],
      ['소녀', 'Mom, look! A little plant is at the window!'],
      ['엄마', 'It is a pea plant. It is your little garden.'],
      ['소녀', 'Hello, little plant! How big are you today?'],
      ['해설', 'The plant grew bigger every day.'],
      ['해설', 'The girl got stronger every day, too.'],
      ['막내콩', 'Be strong, girl! I will grow, too.'],
      ['해설', 'One day, a pink flower opened.'],
      ['소녀', 'Mom, a flower! I can sit up now!'],
      ['엄마', 'Thank you, little pea.'],
      ['해설', 'Grow well where you are. You can make someone happy.'],
    ],
  },

  'an2-shepherdess': {
    title: 'The Shepherdess and the Sweep',
    names: { 해설: 'Narrator', 목동소녀: 'Shepherdess', 청소부: 'Sweep', 할아버지: 'Old China Man', 염소다리: 'Goat Legs' },
    outro: [
      'How was the story?',
      'If you were the Sweep, what would you do on the chimney top?',
      'Where do you feel most safe and happy?',
    ],
    lines: [
      ['해설', 'Little china dolls lived on a table.'],
      ['해설', 'The Shepherdess and the Sweep loved each other.'],
      ['해설', 'A wooden man with goat legs lived on the cupboard.'],
      ['염소다리', 'Shepherdess, marry me! My cupboard is full of treasure.'],
      ['할아버지', 'Nod, nod. Yes, yes. Marry him tonight.'],
      ['목동소녀', 'No! I do not want to live in that dark cupboard.'],
      ['청소부', 'Then let us go out into the big world!'],
      ['해설', 'They climbed down the table leg.'],
      ['할아버지', 'Stop! Where are you going?'],
      ['해설', 'They climbed up the chimney. Up, up, up!'],
      ['해설', 'At the top, they saw the big sky and stars.'],
      ['청소부', 'Look! That is the big world!'],
      ['목동소녀', 'It is too big. I am scared. I want to go back.'],
      ['청소부', 'Okay. If you are scared, we will go back.'],
      ['해설', 'They went back to the table.'],
      ['해설', 'But the Old China Man fell and broke. Crash!'],
      ['목동소녀', 'Oh no! What can we do?'],
      ['청소부', 'Do not worry. He can be fixed.'],
      ['해설', 'The owner glued him. But now he could not nod.'],
      ['염소다리', 'Old man, can I marry the Shepherdess now?'],
      ['해설', 'The Old China Man did not nod.'],
      ['해설', 'So the Shepherdess and the Sweep stayed together.'],
      ['해설', 'Home is where the people you love are.'],
    ],
  },

  'an2-clod-hans': {
    title: 'Clumsy Hans',
    names: { 해설: 'Narrator', 한스: 'Hans', 첫째형: 'Big Brother', 둘째형: 'Middle Brother', 공주: 'Princess' },
    outro: [
      'Was the story fun?',
      'If you were Hans, what funny thing would you say?',
      'When did you speak up even though you were nervous?',
    ],
    lines: [
      ['해설', 'Once upon a time, a man had three sons.'],
      ['해설', 'Two sons were very smart. The youngest was Hans.'],
      ['해설', 'The Princess said, I will marry the best talker.'],
      ['첫째형', 'I know the whole dictionary. I will win.'],
      ['둘째형', 'I know all the town rules. I will win.'],
      ['해설', 'They rode fine horses to the palace.'],
      ['한스', 'I will go, too! I will ride my goat.'],
      ['한스', 'Look! I found a big egg on the road!'],
      ['첫째형', 'Silly Hans! What is that for?'],
      ['해설', 'Hans also took an old wooden shoe and some mud.'],
      ['해설', 'The palace room was very hot.'],
      ['공주', 'Hello. It is hot in here, is it not?'],
      ['첫째형', 'Um, um, well, I, um.'],
      ['해설', 'The brothers could not say a word.'],
      ['해설', 'Then Hans came in on his goat.'],
      ['한스', 'Wow, it is so hot in here!'],
      ['공주', 'I am cooking chickens.'],
      ['한스', 'Great! Can I cook my egg, too?'],
      ['공주', 'Yes. But what will you cook it in?'],
      ['한스', 'In my wooden shoe!'],
      ['공주', 'And the sauce?'],
      ['한스', 'Here it is! Mud sauce!'],
      ['공주', 'Ha ha! You are funny and brave. I will marry you!'],
      ['해설', 'Be brave and say what you think.'],
    ],
  },

  'an2-old-man-right': {
    title: 'Grandpa Is Always Right',
    names: { 해설: 'Narrator', 할아버지: 'Grandpa', 할머니: 'Grandma', 신사: 'Gentleman' },
    outro: [
      'How was the story?',
      'If you were Grandma, what would you say about the apples?',
      'What do you want to thank your family for?',
    ],
    lines: [
      ['해설', 'An old man and an old woman had one horse.'],
      ['할머니', 'Please trade the horse for something good.'],
      ['할아버지', 'Okay, dear. I will go to the market.'],
      ['해설', 'On the way, he traded the horse for a cow.'],
      ['할아버지', 'Now we will have milk every day!'],
      ['해설', 'Then he traded the cow for a sheep.'],
      ['해설', 'Then a goose. Then a hen.'],
      ['해설', 'Last, he traded the hen for a bag of old apples.'],
      ['신사', 'Ha! Your wife will be angry.'],
      ['할아버지', 'No. She will give me a kiss.'],
      ['신사', 'Let us bet a bag of gold!'],
      ['해설', 'They all went to the little house.'],
      ['할머니', 'Welcome home! What did you get?'],
      ['할아버지', 'First, I got a cow.'],
      ['할머니', 'Milk! Good job!'],
      ['할아버지', 'Then a sheep, a goose, and a hen.'],
      ['할머니', 'Wool, a goose, and eggs! Good job!'],
      ['할아버지', 'Then I got this bag of apples.'],
      ['할머니', 'Great! Our neighbor did not share her apples today.'],
      ['할머니', 'You are always right, dear. Kiss!'],
      ['신사', 'Ha ha! We lost. Here is your gold.'],
      ['해설', 'Trust each other, and your heart will be rich.'],
    ],
  },

  'an2-snowman': {
    title: 'The Snowman',
    names: { 해설: 'Narrator', 눈사람: 'Snowman', 개: 'Old Dog', 아이: 'Child' },
    outro: [
      'Did you like the story?',
      'If you were the Snowman, how would you feel about the stove?',
      'What do you love and miss the most?',
    ],
    lines: [
      ['해설', 'On a cold day, children made a big snowman.'],
      ['아이', 'Hello, Snowman! You look great!'],
      ['눈사람', 'Crunch, crunch. I feel nice and cold.'],
      ['해설', 'The sun went down. The moon came up.'],
      ['눈사람', 'What is that round thing?'],
      ['개', 'Woof! That is the moon.'],
      ['해설', 'The Snowman looked in the window.'],
      ['해설', 'He saw a black stove with a red light.'],
      ['눈사람', 'What is that? It is so pretty!'],
      ['개', 'That is the stove. I slept by it when I was young.'],
      ['눈사람', 'I want to go to the stove.'],
      ['개', 'You will melt there. Stay here.'],
      ['해설', 'But the Snowman looked at the stove all day.'],
      ['해설', 'Soon it got warm. Drip, drip.'],
      ['해설', 'The Snowman got smaller and smaller.'],
      ['해설', 'One morning, there was only a puddle.'],
      ['해설', 'In the puddle, there was a stove poker.'],
      ['아이', 'Look! A stove poker!'],
      ['개', 'Woof! Now I know. It was inside the Snowman.'],
      ['개', 'That is why he loved the stove.'],
      ['아이', 'Goodbye, Snowman! See you next winter!'],
      ['해설', 'We all miss something. That feeling is special.'],
    ],
  },

  'an2-piggy-bank': {
    title: 'The Piggy Bank',
    names: { 해설: 'Narrator', 저금통: 'Piggy Bank', 인형: 'Doll', 나무말: 'Wooden Horse' },
    outro: [
      'Was the story fun?',
      'If you were the Piggy Bank, would you join the play?',
      'What was more fun because you did it with friends?',
    ],
    lines: [
      ['해설', 'A piggy bank sat on a tall cupboard.'],
      ['해설', 'It was full of coins. Clink, clink!'],
      ['저금통', 'I am the richest one in this room!'],
      ['저금통', 'I can buy all the toys!'],
      ['해설', 'At night, the toys woke up.'],
      ['인형', 'Let us put on a play!'],
      ['나무말', 'Piggy Bank, come and play with us!'],
      ['저금통', 'No. I will watch from here. I am too special.'],
      ['해설', 'The Doll sang. The Wooden Horse danced.'],
      ['인형', 'Piggy Bank, do you like it? Clap for us!'],
      ['저금통', 'Hmm, it is okay.'],
      ['해설', 'The Piggy Bank leaned out to see better.'],
      ['해설', 'Oops! It slipped and fell. Crash!'],
      ['해설', 'Coins rolled all over the floor.'],
      ['나무말', 'Piggy Bank, are you okay?'],
      ['저금통', 'I only showed off. Playing with you is better.'],
      ['인형', 'It is okay. We will help you.'],
      ['해설', 'The next day, the child fixed the Piggy Bank.'],
      ['해설', 'Now it sat on a low shelf with the toys.'],
      ['저금통', 'Can I join the play tonight?'],
      ['인형', 'Of course! You can be our best audience!'],
      ['해설', 'Playing together is better than having a lot.'],
    ],
  },

  'an2-ida-flowers': {
    title: 'Little Ida’s Flowers',
    names: { 해설: 'Narrator', 이다: 'Ida', 학생: 'Student', 인형: 'Doll', 꽃: 'Flower' },
    outro: [
      'How was the story?',
      'If you were Ida, what would you say to the dancing flowers?',
      'What did you take good care of?',
    ],
    lines: [
      ['해설', 'Little Ida loved flowers.'],
      ['해설', 'But today, her flowers looked tired.'],
      ['이다', 'Flowers, why are you so tired?'],
      ['학생', 'They danced at a party all night.'],
      ['이다', 'Flowers can dance? Where?'],
      ['학생', 'In a big castle. Maybe in your room tonight!'],
      ['해설', 'Ida put the flowers in her doll’s bed.'],
      ['이다', 'Sleep well. Feel better tomorrow.'],
      ['해설', 'That night, Ida heard piano music.'],
      ['해설', 'She peeked into the next room.'],
      ['해설', 'The flowers were dancing! Spin, spin!'],
      ['인형', 'What a fun night!'],
      ['꽃', 'Thank you, Ida. This was our last dance.'],
      ['꽃', 'Please put us in the garden tomorrow.'],
      ['꽃', 'Then we will bloom again in summer.'],
      ['이다', 'Okay. I promise.'],
      ['해설', 'In the morning, Ida put them in a pretty box.'],
      ['해설', 'She put them in the garden soil.'],
      ['이다', 'See you in summer, flowers.'],
      ['해설', 'Ida gave them water every day.'],
      ['해설', 'In summer, many flowers bloomed.'],
      ['해설', 'Take care of little things. Good days will come again.'],
    ],
  },

  'an2-teapot': {
    title: 'The Teapot',
    names: { 해설: 'Narrator', 찻주전자: 'Teapot', 찻잔: 'Teacup', 아주머니: 'Woman' },
    outro: [
      'Did you like the story?',
      'If you were the Teapot, how would you feel when you broke?',
      'Did you ever use an old thing in a new way?',
    ],
    lines: [
      ['해설', 'There was a shiny white teapot.'],
      ['찻주전자', 'Look at my long spout. I am so pretty!'],
      ['찻잔', 'But your lid has a crack.'],
      ['찻주전자', 'Shh! Do not say that. I am the queen of the table.'],
      ['해설', 'Every day, people poured tea from the teapot.'],
      ['해설', 'One day, someone dropped the teapot. Crash!'],
      ['해설', 'The spout broke. The handle broke, too.'],
      ['찻주전자', 'Now I am no good.'],
      ['찻잔', 'Teapot, do not be so sad.'],
      ['해설', 'The teapot was given to a poor woman.'],
      ['아주머니', 'Thank you. I will use it well.'],
      ['해설', 'She filled the teapot with soil.'],
      ['해설', 'She planted a flower bulb inside.'],
      ['찻주전자', 'Something is in my tummy. It tickles!'],
      ['해설', 'The woman gave it water and sun.'],
      ['해설', 'A green sprout came up. Pop!'],
      ['찻주전자', 'A sprout! It is growing inside me!'],
      ['해설', 'One morning, a pretty flower opened.'],
      ['아주머니', 'How pretty! It is the best flower in my house.'],
      ['찻주전자', 'I have no spout, but I am so happy.'],
      ['찻주전자', 'Now I share joy, not tea.'],
      ['해설', 'Even when things change, you can still do good things.'],
    ],
  },
};
