// 영어 학습용 원고 (한국 초등 저학년, 영어 초급). 문장은 자체 각색.
// 키 = stories/*.js 의 이야기 id. lines 의 첫 칸은 원래 이야기 cast 의 한국어 이름 그대로.
export default {
  'magic-apple': {
    title: 'The Magic Apple',
    names: { 해설: 'Narrator', 첫째: 'First Brother', 둘째: 'Second Brother', 셋째: 'Third Brother', 임금님: 'King', 공주: 'Princess' },
    outro: [
      'Did you like the story?',
      'If you had a magic apple, who would you give it to?',
      'What do you like to share with your family?',
    ],
    lines: [
      ['해설', 'Once upon a time, there were three brothers.'],
      ['해설', 'Each brother had one magic thing.'],
      ['첫째', 'I have a magic glass. I can see far, far away.'],
      ['둘째', 'I have a magic carpet. It can fly anywhere.'],
      ['셋째', 'I have a magic apple. It can make sick people well.'],
      ['해설', 'One day, the first brother looked in his magic glass.'],
      ['첫째', 'Oh no! A princess is very sick. She is far away.'],
      ['둘째', 'Let us go on my carpet! Quick!'],
      ['셋째', 'Yes! I will take my apple.'],
      ['해설', 'The three brothers flew on the carpet. Whoosh!'],
      ['임금님', 'Welcome. My daughter is sick. Please help her.'],
      ['해설', 'The third brother gave the apple to the princess.'],
      ['해설', 'She ate the apple. Bite, bite. Then she smiled.'],
      ['공주', 'Father, I feel good now! I am not sick!'],
      ['임금님', 'Thank you! But who helped her the most?'],
      ['첫째', 'My glass found her.'],
      ['둘째', 'My carpet brought us here fast.'],
      ['셋째', 'My apple made her well.'],
      ['공주', 'The glass is still here. The carpet is still here.'],
      ['공주', 'But the apple is gone. He gave me all of it.'],
      ['임금님', 'Yes. He gave everything he had. That is a big heart.'],
      ['해설', 'The princess married the third brother. The other brothers were happy, too.'],
      ['해설', 'Sharing what you have is the best gift.'],
    ],
  },

  'fox-vineyard': {
    title: 'The Fox and the Grape Garden',
    names: { 해설: 'Narrator', 여우: 'Fox', 참새: 'Sparrow' },
    outro: [
      'Was the story fun?',
      'If you were the fox, what would you do at the hole?',
      'What do you want very, very much?',
    ],
    lines: [
      ['해설', 'A hungry fox walked by a grape garden.'],
      ['해설', 'There were many big grapes inside.'],
      ['여우', 'Yum! I want to eat those grapes!'],
      ['해설', 'But there was a tall fence all around.'],
      ['해설', 'The fox walked around the fence. He found a small hole.'],
      ['여우', 'I will go in here! Push, push!'],
      ['해설', 'But the fox was too big. He could not go in.'],
      ['여우', 'I know! I will not eat for three days. Then I will be thin.'],
      ['참새', 'Tweet, tweet! Fox, is that a good idea?'],
      ['여우', 'Yes! The grapes look so good!'],
      ['해설', 'The fox did not eat for three days. He got thin.'],
      ['해설', 'Now he could go in the hole. Wiggle, wiggle!'],
      ['여우', 'Yay! Now I can eat and eat!'],
      ['해설', 'The fox ate lots of grapes. His tummy got big and round.'],
      ['해설', 'Then he tried to go out. But he was stuck!'],
      ['여우', 'Oh no! My tummy is too big!'],
      ['해설', 'The fox hid in the garden. He did not eat for three days again.'],
      ['해설', 'He got thin again. Then he went out of the hole.'],
      ['참새', 'Tweet, tweet! Fox, were the grapes good?'],
      ['여우', 'I was hungry when I went in.'],
      ['여우', 'And I am hungry now. I have nothing.'],
      ['해설', 'Being greedy does not give you much in the end.'],
    ],
  },

  'carob-tree': {
    title: 'The Old Man and the Tree',
    names: { 해설: 'Narrator', 할아버지: 'Grandpa', 나그네: 'Traveler', 손주: 'Grandchild' },
    outro: [
      'Did you enjoy the story?',
      'If you planted a tree, who would you plant it for?',
      'What good thing did someone do for you?',
    ],
    lines: [
      ['해설', 'One sunny day, a man walked down a road.'],
      ['해설', 'He saw an old man in a field. Dig, dig.'],
      ['나그네', 'Hello, Grandpa! What are you doing?'],
      ['할아버지', 'I am planting a tree. It will have sweet fruit.'],
      ['나그네', 'When will it have fruit?'],
      ['할아버지', 'In seventy years.'],
      ['나그네', 'Seventy years? But you cannot eat the fruit then!'],
      ['나그네', 'So why do you plant it?'],
      ['해설', 'The old man smiled.'],
      ['할아버지', 'When I was little, I ate sweet fruit from big trees.'],
      ['할아버지', 'My grandpa planted those trees for me.'],
      ['할아버지', 'Now I plant a tree for my grandchildren.'],
      ['나그네', 'Oh, now I understand.'],
      ['해설', 'Just then, a little child ran over. Tap, tap, tap!'],
      ['손주', 'Grandpa! I have water for the tree!'],
      ['할아버지', 'Thank you. Give the tree lots of water.'],
      ['손주', 'Grow big, little tree! Grow big!'],
      ['나그네', 'I want to help, too. I will press the dirt down.'],
      ['할아버지', 'Someday, someone will eat this fruit. They will be happy.'],
      ['해설', 'Many years later, the tree was big and tall.'],
      ['해설', 'Children picked the sweet fruit and smiled.'],
      ['해설', 'Other people planted good things for us. Let us plant good things, too.'],
    ],
  },

  'tongue': {
    title: 'The Best and Worst Food',
    names: { 해설: 'Narrator', 임금님: 'King', 요리사: 'Cook' },
    outro: [
      'Hello again! Did you like the story?',
      'If you were the king, what kind words would you say?',
      'What nice words did you say today?',
    ],
    lines: [
      ['해설', 'Long ago, there was a king. He had a wise cook.'],
      ['임금님', 'Cook, make me the best food in the world.'],
      ['요리사', 'Yes, King.'],
      ['해설', 'The next day, the cook brought a big plate.'],
      ['해설', 'On the plate, there was a tongue.'],
      ['임금님', 'A tongue? Why is this the best food?'],
      ['요리사', 'The tongue says good words.'],
      ['요리사', 'Thank you. I love you. Good job. We say them with the tongue.'],
      ['요리사', 'Good words make sad friends smile.'],
      ['임금님', 'Ha ha! Good answer!'],
      ['임금님', 'Now make me the worst food in the world.'],
      ['해설', 'The next day, the cook brought a big plate again.'],
      ['해설', 'On the plate, there was a tongue again!'],
      ['임금님', 'A tongue again? Why?'],
      ['요리사', 'The tongue says bad words, too.'],
      ['요리사', 'Go away. I will not play with you. Those words hurt.'],
      ['해설', 'The king was quiet for a long time.'],
      ['임금님', 'Yesterday, I was angry. I said bad words to my helper.'],
      ['임금님', 'The same tongue can say good words or bad words.'],
      ['해설', 'The king called his helper.'],
      ['임금님', 'I am sorry for my words.'],
      ['해설', 'The helper smiled. The palace was full of kind words.'],
      ['해설', 'Our words can make friends smile. Say kind words every day.'],
    ],
  },

  'all-for-good': {
    title: 'It Is All for Good',
    names: { 해설: 'Narrator', 선생님: 'Teacher', 마을사람: 'Townsman' },
    outro: [
      'Thank you for listening!',
      'If your light went out, what would you say?',
      'Did a sad thing ever turn into a good thing for you?',
    ],
    lines: [
      ['해설', 'Long ago, a kind teacher went on a trip.'],
      ['해설', 'He had a donkey, a rooster and a lamp.'],
      ['선생님', 'Everything happens for a good reason.'],
      ['해설', 'At night, the teacher came to a town.'],
      ['선생님', 'Hello. Can I sleep here tonight?'],
      ['마을사람', 'Sorry. We have no room.'],
      ['해설', 'Nobody had a room for him.'],
      ['선생님', 'That is okay. It is all for good.'],
      ['해설', 'The teacher slept in a field outside the town.'],
      ['해설', 'Whoosh! The wind blew out his lamp.'],
      ['선생님', 'My lamp is out. That is okay. It is all for good.'],
      ['해설', 'Then the rooster ran away. The donkey ran away, too.'],
      ['선생님', 'They are gone. That is okay. It is all for good.'],
      ['해설', 'The teacher went to sleep in the dark, quiet field.'],
      ['해설', 'That night, some bad men came to the town.'],
      ['해설', 'They looked for lights and animal sounds. They took many things.'],
      ['해설', 'But the teacher was dark and quiet. They did not find him.'],
      ['마을사람', 'Bad men took our things last night! Are you okay?'],
      ['선생님', 'I am okay. Now I understand.'],
      ['선생님', 'My lamp was out. My animals were quiet. So they did not see me.'],
      ['해설', 'The teacher helped the town fix their houses.'],
      ['해설', 'A sad thing can become a good thing later. Wait and see.'],
    ],
  },

  'boat-hole': {
    title: 'The Hole in the Boat',
    names: { 해설: 'Narrator', 고집쟁이: 'Stubborn Man', 뱃사공: 'Boatman', 아주머니: 'Woman' },
    outro: [
      'Did you like the boat story?',
      'If you were on the boat, what would you say to the man?',
      'What can you do to help your class?',
    ],
    lines: [
      ['해설', 'A boat went across a big river.'],
      ['해설', 'Many people were on the boat.'],
      ['뱃사공', 'We are almost there. Hold on tight!'],
      ['해설', 'Then one man took out a sharp tool.'],
      ['해설', 'He started to make a hole under his seat. Squeak, squeak.'],
      ['아주머니', 'Oh my! What are you doing?'],
      ['고집쟁이', 'I am making a hole. I want to put my feet in the water.'],
      ['아주머니', 'No! Water will come into the boat!'],
      ['고집쟁이', 'So what? This is my seat. I can do what I want.'],
      ['해설', 'Everyone was surprised.'],
      ['뱃사공', 'Yes, it is your seat. But we have only one boat.'],
      ['뱃사공', 'A hole in your seat lets water into the whole boat.'],
      ['아주머니', 'Then the boat will go down. We will all get wet!'],
      ['고집쟁이', 'Oh! Me too?'],
      ['뱃사공', 'Yes. We are all in the same boat.'],
      ['해설', 'The man looked down. Drip, drip. Water was coming in!'],
      ['고집쟁이', 'Oh no! Water!'],
      ['해설', 'The people put a cloth in the hole. No more water came in.'],
      ['고집쟁이', 'I was wrong. I am very sorry.'],
      ['아주머니', 'That is okay. Let us go across together.'],
      ['해설', 'The boat got to the other side safely.'],
      ['해설', 'We are all in one boat. What we do matters to others.'],
    ],
  },

  'one-foot': {
    title: 'On One Foot',
    names: { 해설: 'Narrator', 청년: 'Young Man', 샴마이: 'Shammai', 힐렐: 'Hillel' },
    outro: [
      'Hello, friends! Did you enjoy the story?',
      'If you were the young man, what would you learn next?',
      'What do you not like? How can you be kind to friends?',
    ],
    lines: [
      ['해설', 'Long ago, there was a young man. He was always in a hurry.'],
      ['청년', 'Learning takes too long. I want to learn it all fast!'],
      ['해설', 'He went to a teacher. His name was Shammai.'],
      ['청년', 'Teacher, I will stand on one foot.'],
      ['청년', 'Teach me everything before I put my foot down!'],
      ['해설', 'The young man stood on one foot. Wobble, wobble.'],
      ['샴마이', 'What? That takes a whole life to learn!'],
      ['샴마이', 'Do not play games with me. Go home!'],
      ['청년', 'Oh, he sent me away. I will ask one more teacher.'],
      ['해설', 'Next, he went to Hillel. Hillel was kind to everyone.'],
      ['청년', 'Teacher, can you teach me everything on one foot?'],
      ['해설', 'He stood on one foot again. Wobble, wobble.'],
      ['힐렐', 'Ha ha. Okay. Listen well.'],
      ['힐렐', 'Do not do to others what you do not like.'],
      ['청년', 'That is all? Really?'],
      ['힐렐', 'Yes. That is the most important thing.'],
      ['힐렐', 'You do not like to be teased. So do not tease friends.'],
      ['힐렐', 'You do not like to be hit. So do not hit friends.'],
      ['힐렐', 'Now put your foot down. Learn slowly, one step at a time.'],
      ['청년', 'Thank you, Teacher. I will learn slowly.'],
      ['해설', 'The young man became a very good student.'],
      ['해설', 'What you do not like, your friends do not like. Be kind.'],
    ],
  },

  'never-angry': {
    title: 'The Teacher Who Never Got Mad',
    names: { 해설: 'Narrator', 장난꾸러기: 'Joker', 친구: 'Friend', 힐렐: 'Hillel' },
    outro: [
      'Was the story fun?',
      'If you were Hillel, how would you feel?',
      'What do you do when you feel angry?',
    ],
    lines: [
      ['해설', 'Long ago, there was a teacher named Hillel.'],
      ['해설', 'People said Hillel never got angry.'],
      ['친구', 'Hillel never gets angry. Never!'],
      ['장난꾸러기', 'Ha ha! Everyone gets angry. I will make him angry!'],
      ['친구', 'Okay! If you do, I will give you a basket of apples.'],
      ['해설', 'One afternoon, Hillel was taking a bath.'],
      ['장난꾸러기', 'Hillel! Hillel! Are you there?'],
      ['해설', 'Hillel got out of the bath. He put on his clothes.'],
      ['힐렐', 'Yes? What is it?'],
      ['장난꾸러기', 'I have a question. Why do ducks have flat feet?'],
      ['힐렐', 'Good question! Flat feet help ducks swim.'],
      ['해설', 'Hillel went back to his bath. But soon he heard a call again.'],
      ['장난꾸러기', 'Hillel! I have one more question!'],
      ['해설', 'Hillel put on his clothes again and came out.'],
      ['장난꾸러기', 'Why do camels have long eyelashes?'],
      ['힐렐', 'Good question! They keep sand out of their eyes.'],
      ['해설', 'The boy called him again and again. Five times!'],
      ['해설', 'But each time, Hillel smiled and answered kindly.'],
      ['장난꾸러기', 'Oh no! You did not get angry. I lost my apples!'],
      ['힐렐', 'Ha ha. But you learned many new things!'],
      ['힐렐', 'Come back any time. Questions are good.'],
      ['장난꾸러기', 'I am sorry, Teacher. Next time, I will ask real questions.'],
      ['해설', 'Stay calm and be kind. Then others can change, too.'],
    ],
  },

  'road-stones': {
    title: 'The Stones on the Road',
    names: { 해설: 'Narrator', 아저씨: 'Farmer', 할아버지: 'Grandpa' },
    outro: [
      'Good job listening!',
      'If you saw stones on the road, what would you do?',
      'What place do you share with other people?',
    ],
    lines: [
      ['해설', 'A farmer had a big field. It had many stones.'],
      ['아저씨', 'Too many stones! I cannot plant seeds.'],
      ['해설', 'He threw the stones over the wall. Toss, toss!'],
      ['해설', 'The stones fell on the road.'],
      ['해설', 'Everyone in town walked on that road.'],
      ['해설', 'An old man saw the farmer.'],
      ['할아버지', 'Why do you throw stones on your own road?'],
      ['아저씨', 'Ha ha! My own road? No, Grandpa.'],
      ['아저씨', 'This field is mine. The road is not mine.'],
      ['할아버지', 'Hmm. Think about it.'],
      ['해설', 'The old man smiled and walked away.'],
      ['해설', 'The farmer kept throwing stones on the road.'],
      ['해설', 'Many years went by. The farmer sold his field.'],
      ['아저씨', 'Now the field is not mine.'],
      ['해설', 'The farmer walked down the road. Then, bump!'],
      ['아저씨', 'Ouch! Ouch!'],
      ['해설', 'He fell over a stone. It was his old stone!'],
      ['아저씨', 'Now I understand the old man.'],
      ['아저씨', 'The field was mine for a short time. I walk on this road every day.'],
      ['해설', 'The farmer picked up the stones, one by one.'],
      ['해설', 'Now children can run on the road and not fall.'],
      ['해설', 'Places we share are ours, too. Take care of them.'],
    ],
  },

  'solomon-judge': {
    title: 'Wise King Solomon',
    names: { 해설: 'Narrator', 솔로몬: 'Solomon', 첫째엄마: 'First Woman', 둘째엄마: 'Second Woman', 신하: 'Helper' },
    outro: [
      'Did you like the story of the wise king?',
      'If you were King Solomon, what would you do?',
      'Who loves you very much? How do you know?',
    ],
    lines: [
      ['해설', 'Long ago, there was a wise king. His name was Solomon.'],
      ['해설', 'One day, two women came with one baby.'],
      ['첫째엄마', 'King, this is my baby!'],
      ['둘째엄마', 'No, King. This is my baby!'],
      ['해설', 'The baby cried. Waah, waah!'],
      ['신하', 'King, they say the same thing. Who is right?'],
      ['솔로몬', 'Hmm. This is hard.'],
      ['해설', 'The king thought and thought. Then he had a clever idea.'],
      ['해설', 'Of course, the king would never hurt the baby.'],
      ['솔로몬', 'You both say you are the mother.'],
      ['솔로몬', 'So let us cut the baby in half. You can each have half.'],
      ['둘째엄마', 'Okay. That is fine with me.'],
      ['첫째엄마', 'No, King! Please do not!'],
      ['첫째엄마', 'Give the baby to her. I just want the baby to be safe.'],
      ['해설', 'The first woman cried and looked at the baby.'],
      ['해설', 'The king smiled.'],
      ['솔로몬', 'Now I know. She is the real mother.'],
      ['신하', 'Really? The woman who gave the baby away?'],
      ['솔로몬', 'A real mother never wants her baby hurt.'],
      ['솔로몬', 'She thinks of the baby first.'],
      ['해설', 'The king gave the baby to the first woman.'],
      ['첫째엄마', 'Thank you, King! Baby, let us go home.'],
      ['해설', 'True love thinks of the other person first.'],
    ],
  },

  'king-feast': {
    title: 'The King’s Party',
    names: { 해설: 'Narrator', 임금님: 'King', 슬기: 'Seulgi', 느긋이: 'Neugeusi' },
    outro: [
      'Hi, friends! Did you enjoy the party story?',
      'If you were Neugeusi, what would you do next time?',
      'What do you get ready before school?',
    ],
    lines: [
      ['해설', 'Long ago, there was a kind king.'],
      ['임금님', 'You all work hard. Soon, I will have a big party for you.'],
      ['느긋이', 'A party! When is it, King?'],
      ['임금님', 'It is a secret. I will call you when it is ready.'],
      ['해설', 'Everyone went home happy.'],
      ['해설', 'Seulgi washed her face and hands at home.'],
      ['해설', 'She put on her best clothes.'],
      ['슬기', 'The king can call any time. I will be ready now.'],
      ['해설', 'Seulgi sat near the palace door and waited.'],
      ['해설', 'Neugeusi kept working in the field. His clothes were dirty.'],
      ['느긋이', 'A party takes a long time. It is not today.'],
      ['슬기', 'Neugeusi, why not get ready now?'],
      ['느긋이', 'It is okay. I can do it later.'],
      ['해설', 'That evening, there was a loud sound. Toot, toot!'],
      ['임금님', 'Come in, everyone! The party starts now!'],
      ['해설', 'Seulgi walked in with clean clothes.'],
      ['해설', 'Neugeusi ran fast. But he was all dirty.'],
      ['임금님', 'Neugeusi, you cannot sit at the table like that.'],
      ['임금님', 'Today, you must wait outside the door.'],
      ['느긋이', 'Oh, I should get ready early. I am so sad.'],
      ['슬기', 'Next time, let us get ready early together.'],
      ['느긋이', 'Yes. Next time, I will be ready early!'],
      ['해설', 'Do not wait until later. Get ready today.'],
    ],
  },

  'david-spider': {
    title: 'David and the Spider',
    names: { 해설: 'Narrator', 다윗: 'David', 거미: 'Spider', 대장: 'Captain', 병사: 'Soldier' },
    outro: [
      'Did you like the spider story?',
      'If you were David, what would you say to the spider?',
      'What small thing helps you every day?',
    ],
    lines: [
      ['해설', 'Long ago, there was a boy named David.'],
      ['해설', 'David looked after sheep and sang songs.'],
      ['해설', 'One day, David saw a spider web on a tree.'],
      ['다윗', 'Spiders only make sticky webs. They are no good.'],
      ['거미', 'David, everything in the world is good for something.'],
      ['다윗', 'Ha ha! What good is a little spider?'],
      ['해설', 'Years went by. David grew up.'],
      ['해설', 'But King Saul was angry at David. He sent soldiers to catch him.'],
      ['해설', 'David ran to a hill. He hid in a small cave.'],
      ['다윗', 'Phew! I hope they do not see me.'],
      ['해설', 'Just then, a little spider came down to the cave door.'],
      ['거미', 'Back and forth, back and forth. Make it strong!'],
      ['해설', 'Soon, a big white web was over the cave door.'],
      ['해설', 'Then the soldiers came. Stomp, stomp.'],
      ['병사', 'Captain, here is a cave. Should we go in?'],
      ['대장', 'Wait. Look at the web on the door.'],
      ['대장', 'If someone went in, the web would be broken.'],
      ['병사', 'Oh, you are right. No one is in there.'],
      ['해설', 'The soldiers went far away.'],
      ['다윗', 'Thank you, Spider. You helped me.'],
      ['거미', 'See? A little spider is good for something!'],
      ['다윗', 'Yes. Now I know. Everything is special.'],
      ['해설', 'Even small things are important. Nothing is useless.'],
    ],
  },

  'greedy-dog': {
    title: 'The Greedy Dog',
    names: { 해설: 'Narrator', 멍멍이: 'Doggy', 고양이: 'Cat' },
    outro: [
      'Thank you for listening!',
      'If you were the dog, what would you do with the meat?',
      'What did you share with a friend?',
    ],
    lines: [
      ['해설', 'Once upon a time, there was a dog. He did not like to share.'],
      ['해설', 'One day, a man gave the dog a big piece of meat.'],
      ['멍멍이', 'Wow, meat! It is so big!'],
      ['고양이', 'Hello, Doggy. Can I have a little bite?'],
      ['멍멍이', 'No! It is all mine. I will eat it at home.'],
      ['해설', 'The dog ran home with the meat in his mouth.'],
      ['해설', 'On the way, there was a little river. Splash, splash.'],
      ['해설', 'The dog walked on a small bridge.'],
      ['해설', 'He looked down into the water.'],
      ['해설', 'He saw a dog with meat in the water!'],
      ['멍멍이', 'That dog has meat, too. It looks bigger than mine!'],
      ['멍멍이', 'I want that meat, too. I will take it!'],
      ['해설', 'The dog made an angry face. The water dog made an angry face, too.'],
      ['멍멍이', 'Woof! Woof, woof!'],
      ['해설', 'Plop! His meat fell into the water.'],
      ['해설', 'The meat went away down the river.'],
      ['멍멍이', 'Oh no! My meat! My meat!'],
      ['해설', 'He looked again. The water dog had no meat now.'],
      ['멍멍이', 'Oh! That dog was me. It was my picture in the water.'],
      ['멍멍이', 'I wanted more. Now I have nothing.'],
      ['멍멍이', 'I should share with the cat next time.'],
      ['해설', 'If you want too much, you can lose what you have.'],
    ],
  },

  'town-country-mouse': {
    title: 'Town Mouse and Country Mouse',
    names: { 해설: 'Narrator', 시골쥐: 'Country Mouse', 도시쥐: 'Town Mouse' },
    outro: [
      'Did you like the two mice?',
      'If you were Country Mouse, where would you live?',
      'Where do you feel happy and safe?',
    ],
    lines: [
      ['해설', 'Country Mouse lived in a little hole in a field.'],
      ['해설', 'One day, her friend Town Mouse came to visit.'],
      ['시골쥐', 'Welcome, friend! Here are beans and corn. Eat a lot!'],
      ['도시쥐', 'Beans and corn? They are hard. They are not yummy.'],
      ['도시쥐', 'Come to the town with me. We have yummy food!'],
      ['시골쥐', 'Really? Okay, let us go!'],
      ['해설', 'They went to the town. Beep, beep! It was very loud.'],
      ['시골쥐', 'Wow, so many people! So much noise!'],
      ['해설', 'They went into a big kitchen. Tiptoe, tiptoe.'],
      ['해설', 'There was cheese, cake and sweet fruit on the table.'],
      ['시골쥐', 'Wow! I never saw food like this!'],
      ['도시쥐', 'See? Let us eat!'],
      ['해설', 'Then the door opened. Bang!'],
      ['도시쥐', 'A person! Hide, quick!'],
      ['해설', 'They ran into a small hole. Their hearts went thump, thump.'],
      ['해설', 'They went back to the table. Then a cat came. Meow!'],
      ['시골쥐', 'A cat! Run!'],
      ['해설', 'They hid again. The cat sat and waited.'],
      ['해설', 'The two mice were hungry all night.'],
      ['시골쥐', 'The food here is yummy. But I am too scared to eat.'],
      ['시골쥐', 'I will go home. Beans in a safe home are best for me.'],
      ['도시쥐', 'Okay, my friend. Have a safe trip!'],
      ['시골쥐', 'I am home! My home is the best!'],
      ['해설', 'A calm, safe home can be better than yummy food.'],
    ],
  },

  'honest-woodcutter': {
    title: 'The Honest Woodcutter',
    names: { 해설: 'Narrator', 나무꾼: 'Woodcutter', 산신령: 'Mountain Spirit', 욕심쟁이: 'Greedy Man' },
    outro: [
      'Good listening, everyone!',
      'If you were the woodcutter, what would you say?',
      'When did you tell the truth?',
    ],
    lines: [
      ['해설', 'Once upon a time, there was a kind woodcutter.'],
      ['해설', 'Every day, he cut wood on the mountain. Chop, chop!'],
      ['해설', 'One day, his ax fell into a pond. Splash!'],
      ['나무꾼', 'Oh no! That is my only ax!'],
      ['해설', 'Then a mountain spirit came out of the pond.'],
      ['산신령', 'Why are you sad?'],
      ['나무꾼', 'My ax fell in the pond. I need it to work.'],
      ['해설', 'The spirit went into the pond. He came out with a gold ax.'],
      ['산신령', 'Is this gold ax yours?'],
      ['나무꾼', 'No, it is not mine.'],
      ['산신령', 'Is this silver ax yours?'],
      ['나무꾼', 'No, that is not mine, either.'],
      ['산신령', 'Is this old iron ax yours?'],
      ['나무꾼', 'Yes! That is my ax! Thank you!'],
      ['산신령', 'You are honest. Take all three axes!'],
      ['해설', 'A greedy man heard the story. He ran to the pond.'],
      ['욕심쟁이', 'I want a gold ax, too. Hee hee.'],
      ['해설', 'He threw his ax into the pond.'],
      ['산신령', 'Is this gold ax yours?'],
      ['욕심쟁이', 'Yes, yes! That is my ax!'],
      ['산신령', 'That is not true. I will give you nothing.'],
      ['해설', 'The spirit went away. The greedy man lost his own ax, too.'],
      ['해설', 'Being honest is the best treasure.'],
    ],
  },

  'fox-grapes': {
    title: 'The Fox and the Grapes',
    names: { 해설: 'Narrator', 여우: 'Fox', 다람쥐: 'Squirrel' },
    outro: [
      'Did you like the fox?',
      'If you were the fox, how would you get the grapes?',
      'What hard thing did you try again?',
    ],
    lines: [
      ['해설', 'It was a hot summer day. A fox walked in the woods.'],
      ['여우', 'I am so hungry. Is there any food?'],
      ['해설', 'The fox saw a big grape tree.'],
      ['해설', 'Purple grapes hung up high.'],
      ['여우', 'Grapes! They look so sweet!'],
      ['해설', 'The fox reached up. But the grapes were too high.'],
      ['여우', 'I will jump. One, two, three, jump!'],
      ['해설', 'The fox jumped and jumped. But he could not get one.'],
      ['여우', 'Huff, huff. My legs hurt.'],
      ['해설', 'A squirrel was in the tree.'],
      ['다람쥐', 'Fox, put some stones under the tree. Then stand on them!'],
      ['해설', 'But the fox turned away.'],
      ['여우', 'No, thank you. Those grapes are sour anyway.'],
      ['다람쥐', 'No, they are not. I ate one. It was sweet!'],
      ['여우', 'They are sour. I do not like sour grapes.'],
      ['해설', 'The fox walked away.'],
      ['다람쥐', 'Ha ha. He just could not get them.'],
      ['해설', 'At home, the fox was hungry. He could not sleep.'],
      ['여우', 'I really wanted those grapes. I should try again.'],
      ['해설', 'The next day, the fox put stones under the tree. One, two, three.'],
      ['해설', 'He stood on the stones and reached up. He got the grapes!'],
      ['여우', 'Yum! So sweet! Thank you, Squirrel!'],
      ['해설', 'Do not make excuses. Try a new way again.'],
    ],
  },
};
