// 영어 학습용 원고 (한국 초등 저학년, 영어 초급). 문장은 자체 각색.
// 키 = stories/*.js 의 이야기 id. lines 의 첫 칸은 원래 이야기 cast 의 한국어 이름 그대로.
export default {
  'crow-pitcher': {
    title: 'The Crow and the Pitcher',
    names: { 해설: 'Narrator', 까마귀: 'Crow', 참새: 'Sparrow' },
    outro: [
      'Did you enjoy the story?',
      'If you were the Crow, what would you do?',
      'When something is hard for you, what do you do?',
    ],
    lines: [
      ['해설', 'It was a hot summer. There was no rain.'],
      ['해설', 'The rivers were dry. The ponds were dry, too.'],
      ['해설', 'A crow flew in the sky. Caw, caw!'],
      ['까마귀', 'I am so thirsty. I want some water.'],
      ['해설', 'Then the crow saw a pitcher in a yard.'],
      ['까마귀', 'A pitcher! Maybe there is water in it.'],
      ['해설', 'There was a little water at the bottom.'],
      ['해설', 'The crow put in his beak. But it was too short.'],
      ['까마귀', 'A little more, a little more! Oh, I cannot reach it.'],
      ['참새', 'Crow, push the pitcher over!'],
      ['까마귀', 'No. Then the water will go into the ground.'],
      ['참새', 'Then you must give up. Too bad.'],
      ['까마귀', 'No, I will not give up. I will think.'],
      ['해설', 'The crow thought and thought. Then he saw small stones.'],
      ['까마귀', 'I have a good idea!'],
      ['해설', 'He dropped a stone into the pitcher. Plop!'],
      ['해설', 'Plop, plop, plop! One stone, two stones, many stones.'],
      ['참새', 'Crow, what are you doing? You cannot eat stones.'],
      ['까마귀', 'Look! The water is coming up.'],
      ['해설', 'The water came up, up, up to the top.'],
      ['까마귀', 'Gulp, gulp! Ah, that is good! Sparrow, you drink, too.'],
      ['참새', 'Thank you, Crow! You are so smart!'],
      ['해설', 'Do not give up. Think, and you can find a way.'],
    ],
  },

  'golden-goose': {
    title: 'The Golden Goose',
    names: { 해설: 'Narrator', 농부: 'Farmer', 아내: 'Wife', 거위: 'Goose' },
    outro: [
      'Was the story fun?',
      'If you were the farmer, what would you do?',
      'What do you have that is special to you?',
    ],
    lines: [
      ['해설', 'Long ago, a poor farmer and his wife lived in a village.'],
      ['해설', 'They had a white goose.'],
      ['거위', 'Honk, honk! Honk, honk!'],
      ['해설', 'One morning, the farmer looked in the nest.'],
      ['농부', 'Come and look! The egg is shiny!'],
      ['아내', 'Oh my! It is a golden egg!'],
      ['해설', 'The farmer sold the egg. He bought rice and warm clothes.'],
      ['해설', 'The next day, the goose gave one more golden egg.'],
      ['해설', 'Every morning, one golden egg. One, one, one.'],
      ['아내', 'We are not hungry now. Thank you, Goose.'],
      ['해설', 'The farmer became rich. But he wanted more and more.'],
      ['농부', 'One egg a day is too little. I want more now!'],
      ['농부', 'Goose, can you give me two eggs today?'],
      ['거위', 'Honk? Honk, honk.'],
      ['해설', 'The goose gave only one egg again.'],
      ['농부', 'There must be many eggs inside the goose.'],
      ['농부', 'I will open the goose and take them all!'],
      ['아내', 'No! Do not hurt our goose!'],
      ['해설', 'The farmer did not listen. He ran at the goose.'],
      ['해설', 'The goose was scared. Flap, flap! She flew far away.'],
      ['해설', 'The goose never came back. No more golden eggs.'],
      ['농부', 'Oh no. I wanted too much. Now I have nothing.'],
      ['아내', 'One egg a day was enough.'],
      ['해설', 'Do not be greedy. Be happy with what you have.'],
    ],
  },

  'bell-cat': {
    title: 'Belling the Cat',
    names: {
      해설: 'Narrator',
      할아버지쥐: 'Grandpa Mouse',
      꼬마쥐: 'Little Mouse',
      뚱뚱이쥐: 'Chubby Mouse',
      날쌘쥐: 'Quick Mouse',
    },
    outro: [
      'Thank you for listening!',
      'If you were a mouse, what would you say?',
      'Is there something easy to say but hard to do?',
    ],
    lines: [
      ['해설', 'Many mice lived in a big house.'],
      ['해설', 'There was a lot of food. The mice were happy.'],
      ['해설', 'One day, a big cat came to the house. Meow!'],
      ['해설', 'The cat walked very quietly. The mice were scared.'],
      ['할아버지쥐', 'Everyone, come here. Let us talk about the cat.'],
      ['뚱뚱이쥐', 'The cat is so quiet. We cannot hear her.'],
      ['날쌘쥐', 'I run fast. But the cat almost got me!'],
      ['할아버지쥐', 'Hmm. What can we do?'],
      ['해설', 'Then the little mouse put up his hand.'],
      ['꼬마쥐', 'I have an idea! Let us put a bell on the cat.'],
      ['꼬마쥐', 'Ring, ring! Then we can hear her and hide.'],
      ['뚱뚱이쥐', 'Wow, that is a great idea!'],
      ['날쌘쥐', 'Yes! Then we will not be scared.'],
      ['해설', 'All the mice clapped. Clap, clap, clap!'],
      ['할아버지쥐', 'It is a good idea. But who will put on the bell?'],
      ['해설', 'Suddenly, it was very quiet.'],
      ['뚱뚱이쥐', 'Not me. I am too slow.'],
      ['날쌘쥐', 'Not me. I am too scared.'],
      ['꼬마쥐', 'Not me. I am too small.'],
      ['해설', 'The mice looked at each other. Nobody said yes.'],
      ['할아버지쥐', 'Saying is easy. Doing is hard.'],
      ['할아버지쥐', 'Let us think of a plan we can really do.'],
      ['해설', 'A good idea is nice. But can we really do it? Think about that, too.'],
    ],
  },

  'fox-crow': {
    title: 'The Fox and the Crow',
    names: { 해설: 'Narrator', 여우: 'Fox', 까마귀: 'Crow' },
    outro: [
      'Did you like the story?',
      'If you were the Crow, what would you do?',
      'What do you do when someone says very nice words to you?',
    ],
    lines: [
      ['해설', 'One sunny day, a crow found a piece of cheese.'],
      ['까마귀', 'Cheese! I will sit on a high branch and eat it.'],
      ['해설', 'The crow held the cheese in her beak.'],
      ['해설', 'A hungry fox walked under the tree.'],
      ['여우', 'Sniff, sniff. I smell cheese!'],
      ['여우', 'I want that cheese. But I cannot climb trees.'],
      ['여우', 'I know! I will play a trick.'],
      ['여우', 'Hello, Crow! Your feathers are so black and shiny!'],
      ['해설', 'The crow was happy. She opened her wings a little.'],
      ['여우', 'Your eyes are pretty. You are the best bird in the forest.'],
      ['해설', 'The crow felt very proud.'],
      ['여우', 'Your voice must be pretty, too. Can you sing for me?'],
      ['해설', 'The crow wanted to show her voice.'],
      ['해설', 'She opened her beak wide and sang.'],
      ['까마귀', 'Caw! Caw!'],
      ['해설', 'Oh no! The cheese fell down. Drop!'],
      ['해설', 'The fox caught the cheese. Yum, yum!'],
      ['여우', 'Thank you, Crow! The cheese is very good.'],
      ['까마귀', 'Oh no, my cheese!'],
      ['여우', 'Next time, be careful of nice words. Bye!'],
      ['까마귀', 'Sweet words tricked me. I will be careful next time.'],
      ['해설', 'Be careful when people say only sweet words. Think again.'],
    ],
  },

  'bundle-sticks': {
    title: 'The Bundle of Sticks',
    names: { 해설: 'Narrator', 아버지: 'Father', 첫째: 'Big Brother', 둘째: 'Middle Brother', 막내: 'Little Brother' },
    outro: [
      'Was the story fun?',
      'If you were one of the brothers, what would you do?',
      'What do you like to do together with your family?',
    ],
    lines: [
      ['해설', 'Long ago, a father lived with his three sons.'],
      ['해설', 'The three brothers fought every day.'],
      ['첫째', 'This apple is mine. I am the oldest!'],
      ['둘째', 'No! I saw it first!'],
      ['막내', 'You always eat it. I never get any! Hmph!'],
      ['해설', 'The father was sad.'],
      ['아버지', 'Children, go and get one stick each.'],
      ['해설', 'The brothers came back with one stick each.'],
      ['아버지', 'Now, break your stick.'],
      ['해설', 'Snap! Snap! Snap! The sticks broke easily.'],
      ['막내', 'That was so easy!'],
      ['해설', 'Then the father tied many sticks together.'],
      ['아버지', 'Now, break this bundle.'],
      ['첫째', 'Easy! Ugh!'],
      ['해설', 'The big brother pushed hard. But the bundle did not break.'],
      ['둘째', 'Let me try. Ugh, ugh!'],
      ['막내', 'Ugh! I cannot do it, too!'],
      ['아버지', 'One stick breaks easily. Many sticks together do not break.'],
      ['아버지', 'You are like the sticks. Together, you are strong.'],
      ['첫째', 'Brothers, I am sorry.'],
      ['둘째', 'I am sorry, too. Let us share the apples.'],
      ['막내', 'Yes! Let us stay together, like the sticks!'],
      ['해설', 'From then on, the brothers helped each other.'],
      ['해설', 'Together, we are stronger than one.'],
    ],
  },

  'kr-rabbit-turtle': {
    title: 'The Rabbit and the Turtle',
    names: { 해설: 'Narrator', 용왕: 'Sea King', 자라: 'Turtle', 토끼: 'Rabbit' },
    outro: [
      'Did you enjoy the story?',
      'If you were the Rabbit, what would you do?',
      'When you are in trouble, how do you stay calm?',
    ],
    lines: [
      ['해설', 'Long ago, a Sea King lived in a palace under the sea.'],
      ['해설', 'One day, the Sea King got very sick.'],
      ['용왕', 'Oh, I am so sick. Is there any medicine?'],
      ['해설', 'The doctor said, a rabbit liver is good medicine.'],
      ['자라', 'My King, I will go and bring a rabbit!'],
      ['해설', 'The turtle swam slowly to the land.'],
      ['해설', 'A rabbit was hopping in the forest. Hop, hop!'],
      ['자라', 'Rabbit, come to the sea palace! There is a lot of food.'],
      ['토끼', 'The sea palace? I want to go!'],
      ['해설', 'The rabbit sat on the turtle. Down, down into the sea!'],
      ['용왕', 'Welcome, Rabbit. I need your liver for my medicine.'],
      ['토끼', 'My liver? Oh no! What can I do?'],
      ['해설', 'The rabbit was scared. But he thought fast.'],
      ['토끼', 'Oh, my King! My liver is not here.'],
      ['토끼', 'I washed it and left it on a rock to dry.'],
      ['용왕', 'Then go and get it. Turtle, take him back.'],
      ['해설', 'The turtle swam back to the land with the rabbit.'],
      ['해설', 'On the sand, the rabbit jumped off. Hop!'],
      ['토끼', 'Turtle, nobody can take out a liver! Ha ha!'],
      ['자라', 'Oh no, you tricked me! Come back!'],
      ['토끼', 'Tell the King to find other medicine. Bye!'],
      ['해설', 'The turtle found a good plant by the sea.'],
      ['해설', 'The King ate the plant. Slowly, he got well.'],
      ['해설', 'When you are in trouble, stay calm and think.'],
    ],
  },

  'kr-lump-old-man': {
    title: 'The Old Man with a Lump',
    names: { 해설: 'Narrator', 착한영감: 'Kind Grandpa', 욕심영감: 'Greedy Grandpa', 도깨비: 'Goblin' },
    outro: [
      'Thank you for listening!',
      'If you were the goblins, what would you do?',
      'What makes you happy, like singing?',
    ],
    lines: [
      ['해설', 'Long ago, an old man had a big lump on his cheek.'],
      ['해설', 'One day, he was in the mountains. It got dark.'],
      ['착한영감', 'It is so dark. I will rest in that empty house.'],
      ['해설', 'The old man sang a happy song.'],
      ['착한영감', 'The moon is bright, the stars are bright. La la la!'],
      ['해설', 'Then some goblins came in. Goblins are magic monsters with horns.'],
      ['도깨비', 'What a great song! Where does your song come from?'],
      ['착한영감', 'Hmm. Maybe it comes from this lump.'],
      ['도깨비', 'Give us the lump! We will give you treasure.'],
      ['해설', 'The goblin touched the lump. Pop! It came off. It did not hurt.'],
      ['착한영감', 'No more lump, and treasure, too! Thank you, goblins!'],
      ['해설', 'Another old man heard about this. He also had a lump.'],
      ['욕심영감', 'I want treasure, too. I will go to the goblins.'],
      ['해설', 'He went to the empty house and sang loudly.'],
      ['욕심영감', 'Give me treasure, give me treasure, give it now!'],
      ['해설', 'His song was very bad.'],
      ['욕심영감', 'This song comes from my lump. Take it and give me treasure.'],
      ['도깨비', 'No! The last lump had no song. You tricked us!'],
      ['도깨비', 'Here, take this lump back!'],
      ['해설', 'Pop! The goblin put the old lump on his other cheek.'],
      ['욕심영감', 'Oh no! Now I have two lumps!'],
      ['욕심영감', 'I was greedy and told a lie. I will be honest now.'],
      ['해설', 'The kind grandpa visited him and was kind to him.'],
      ['해설', 'Good things come to people who are honest and happy.'],
    ],
  },

  'kr-magpie': {
    title: 'The Magpie and the Bell',
    names: { 해설: 'Narrator', 선비: 'Young Man', 까치: 'Magpie', 구렁이: 'Snake' },
    outro: [
      'Did you like the story?',
      'If you were the magpie, what would you do?',
      'Who helped you before? How did you say thank you?',
    ],
    lines: [
      ['해설', 'Long ago, a young man was walking to the big city.'],
      ['해설', 'On the mountain road, he heard a bird. Caw, caw!'],
      ['해설', 'A big snake was going up to a magpie nest.'],
      ['까치', 'Help! Please help my baby birds!'],
      ['선비', 'Oh no! Go away, Snake!'],
      ['해설', 'The young man threw a stone. The snake ran away.'],
      ['까치', 'Thank you! I will not forget you.'],
      ['해설', 'The young man walked on. Soon it was dark.'],
      ['해설', 'He found a little house and went to sleep.'],
      ['해설', 'At night, he woke up. He could not move!'],
      ['해설', 'The snake was holding him tight.'],
      ['구렁이', 'You took my dinner away. So I will not let you go.'],
      ['선비', 'I only helped the baby birds. Please let me go.'],
      ['구렁이', 'Okay. If the temple bell rings three times, you can go.'],
      ['구렁이', 'But nobody is at the temple. The bell will not ring.'],
      ['선비', 'Oh no. Who can ring the bell at night?'],
      ['해설', 'In the early morning, he heard the bell. Dong!'],
      ['해설', 'Dong! Dong! It rang three times!'],
      ['구렁이', 'Who rang the bell? Well, a promise is a promise.'],
      ['해설', 'The snake let him go and went far away.'],
      ['해설', 'At the temple, there were many magpies. They pushed the bell together!'],
      ['까치', 'You helped our babies. So we helped you!'],
      ['선비', 'Thank you, Magpies. You are my good friends.'],
      ['해설', 'When you help others, help comes back to you.'],
    ],
  },

  'kr-red-bean-grandma': {
    title: 'Grandma and the Tiger',
    names: { 해설: 'Narrator', 할멈: 'Grandma', 호랑이: 'Tiger', 알밤: 'Chestnut', 자라: 'Turtle', 멍석: 'Straw Mat' },
    outro: [
      'Was the story fun?',
      'If you were one of Grandma’s friends, how would you help?',
      'When did you work together with friends?',
    ],
    lines: [
      ['해설', 'Long ago, a grandma lived alone near a mountain.'],
      ['해설', 'One day, she was planting red beans. A tiger came.'],
      ['호랑이', 'Roar! I am hungry. I will take all your food!'],
      ['할멈', 'Tiger, wait. On the coldest day, I will make red bean porridge.'],
      ['할멈', 'Red bean porridge is a warm, sweet soup. Come then.'],
      ['호랑이', 'Okay! I will come back for the porridge. Roar!'],
      ['해설', 'The cold day came. Grandma cooked and cried.'],
      ['할멈', 'The tiger will come tonight. What can I do?'],
      ['해설', 'Then a chestnut rolled in. Roll, roll!'],
      ['알밤', 'Grandma, do not cry! Give me some porridge. I will help.'],
      ['해설', 'The chestnut ate and hid in the fire.'],
      ['자라', 'I will help, too! I will hide in the water jar.'],
      ['해설', 'A mat lay in the yard. More friends hid in the house.'],
      ['멍석', 'Do not worry, Grandma. Together, we are strong!'],
      ['해설', 'At night, the tiger came in. Stomp, stomp!'],
      ['호랑이', 'Grandma, I am here! Brr, it is cold. I need the fire.'],
      ['알밤', 'Pop! Here I am!'],
      ['호랑이', 'Ouch, my nose! I need water!'],
      ['자라', 'Snap! Do not bother our grandma!'],
      ['해설', 'The tiger slipped and fell. Then he sat on something sharp.'],
      ['호랑이', 'Ouch, ouch! What a strange house! I must go!'],
      ['해설', 'The mat rolled up the tiger and took him far away.'],
      ['호랑이', 'I will never come to that house again!'],
      ['해설', 'Small friends can win when they work together.'],
    ],
  },

  'kr-kongjwi': {
    title: 'Kongjwi and Patjwi',
    names: { 해설: 'Narrator', 콩쥐: 'Kongjwi', 팥쥐: 'Patjwi', 새어머니: 'Stepmother', 두꺼비: 'Toad', 원님: 'Mayor' },
    outro: [
      'Thank you for listening!',
      'If you were Kongjwi, what would you do?',
      'Who helps you when things are hard?',
    ],
    lines: [
      ['해설', 'Long ago, there was a kind girl. Her name was Kongjwi.'],
      ['해설', 'Her stepmother loved only her own girl, Patjwi.'],
      ['새어머니', 'Kongjwi, fill this big jar with water. Patjwi, you can rest.'],
      ['팥쥐', 'Work hard, Kongjwi! I am going to play.'],
      ['해설', 'But the jar had a hole. The water ran out.'],
      ['콩쥐', 'The jar does not fill up. What can I do?'],
      ['해설', 'Then a big toad came.'],
      ['두꺼비', 'Do not worry, Kongjwi. I will close the hole.'],
      ['해설', 'The toad sat on the hole. The jar filled up.'],
      ['콩쥐', 'Thank you, Toad! Thank you so much!'],
      ['해설', 'One day, there was a big party in town.'],
      ['새어머니', 'Kongjwi, finish all the work. Then you can come.'],
      ['해설', 'Birds and a fairy helped her. The fairy gave her pretty shoes.'],
      ['콩쥐', 'Thank you, everyone! Now I can go to the party!'],
      ['해설', 'On the way, one shoe fell into the water. Splash!'],
      ['원님', 'Whose pretty shoe is this? I will find her.'],
      ['팥쥐', 'It is mine! Oh? My foot does not fit.'],
      ['해설', 'Kongjwi tried the shoe. It fit just right!'],
      ['원님', 'It is you! You are kind and you work hard.'],
      ['해설', 'The mayor and Kongjwi got married.'],
      ['새어머니', 'Kongjwi, I am sorry. I was not kind to you.'],
      ['팥쥐', 'I am sorry, too. I will help you from now on.'],
      ['콩쥐', 'That is okay. Let us be kind to each other.'],
      ['해설', 'Be kind, even when it is hard. Friends will help you.'],
    ],
  },

  'kr-fart-bride': {
    title: 'The Farting Bride',
    names: { 해설: 'Narrator', 며느리: 'Bride', 시아버지: 'Father-in-law', 신랑: 'Husband', 비단장수: 'Silk Seller' },
    outro: [
      'Did you laugh at the story?',
      'If you were the bride, what would you do?',
      'What is something special you are good at?',
    ],
    lines: [
      ['해설', 'Long ago, a young bride came to a new family.'],
      ['해설', 'She worked well. But her face turned yellow.'],
      ['시아버지', 'My dear, are you sick? Your face is yellow.'],
      ['며느리', 'Well, I am holding in my farts.'],
      ['시아버지', 'Farts? Do not hold them in. Let them out!'],
      ['며느리', 'Then everyone, hold on tight! My farts are very strong.'],
      ['해설', 'Everyone held on to the door and the posts.'],
      ['며느리', 'Here I go! One, two, three!'],
      ['해설', 'Boom! The door shook. The house shook!'],
      ['시아버지', 'Whoa! I am flying! Stop, stop!'],
      ['신랑', 'Father, are you okay? What a big fart!'],
      ['시아버지', 'Our house will fly away! Go to your old home for a while.'],
      ['해설', 'The sad bride walked with her father-in-law.'],
      ['해설', 'They saw a tall tree with yellow pears.'],
      ['비단장수', 'I am thirsty. But the pears are too high.'],
      ['며느리', 'Can I get the pears for you?'],
      ['비단장수', 'How? If you can, I will give you all my silk.'],
      ['며느리', 'One, two, three! Boom!'],
      ['해설', 'The pears fell down. Plop, plop, plop!'],
      ['비단장수', 'Wow! Here is my silk, as I promised.'],
      ['시아버지', 'Your fart is a treasure! Let us go home.'],
      ['신랑', 'Your fart is great! Do not hold it in.'],
      ['해설', 'After that, her face was pink and happy.'],
      ['해설', 'Everyone has a special gift. Being different is okay.'],
    ],
  },

  'kr-fairy-woodcutter': {
    title: 'The Woodcutter and the Fairy',
    names: { 해설: 'Narrator', 나무꾼: 'Woodcutter', 사슴: 'Deer', 선녀: 'Fairy', 옥황상제: 'Sky King' },
    outro: [
      'Thank you for listening!',
      'If you were the woodcutter, what would you do?',
      'Is there a promise you keep every day?',
    ],
    lines: [
      ['해설', 'Long ago, a kind woodcutter lived in the mountains.'],
      ['사슴', 'Help! A hunter is coming! Please hide me!'],
      ['해설', 'The woodcutter hid the deer. The hunter went away.'],
      ['사슴', 'Thank you! Do you have a wish?'],
      ['나무꾼', 'I live alone. I want a family.'],
      ['사슴', 'Go to the pond on the full moon night. Fairies come to swim.'],
      ['사슴', 'Hide one fairy dress. The fairy cannot fly without it.'],
      ['사슴', 'But do not show her the dress until you have three children.'],
      ['해설', 'On the full moon night, the fairies played in the pond.'],
      ['해설', 'The woodcutter hid one dress.'],
      ['선녀', 'Where is my dress? I cannot fly home!'],
      ['나무꾼', 'Do not worry. Come and live with me.'],
      ['해설', 'They were happy. They had two children.'],
      ['선녀', 'Please, can I see my dress just once?'],
      ['해설', 'The woodcutter showed her the dress.'],
      ['해설', 'She put it on and flew to the sky with the children.'],
      ['선녀', 'I am sorry. I missed my home in the sky.'],
      ['나무꾼', 'Oh no! I did not keep my promise.'],
      ['사슴', 'Do not cry. A bucket comes down from the sky. Get in it.'],
      ['해설', 'The woodcutter got in the bucket. Up, up to the sky!'],
      ['선녀', 'It is you! The children missed you every day.'],
      ['옥황상제', 'You are a kind man. Live here with your family.'],
      ['해설', 'The family lived happily in the sky.'],
      ['해설', 'Keep your promises. If you make a mistake, try to fix it.'],
    ],
  },

  'kr-goblin-club': {
    title: 'The Goblin’s Magic Club',
    names: { 해설: 'Narrator', 동생: 'Younger Brother', 형: 'Older Brother', 도깨비: 'Goblin', 꼬마도깨비: 'Little Goblin' },
    outro: [
      'Did you enjoy the story?',
      'If you were the younger brother, what would you do?',
      'What good things do you share with your family?',
    ],
    lines: [
      ['해설', 'Long ago, there were two brothers.'],
      ['해설', 'The younger brother was kind. The older brother was greedy.'],
      ['해설', 'One day, the younger brother found some nuts in the mountains.'],
      ['동생', 'This one is for Dad. This one is for Mom.'],
      ['동생', 'This one is for my brother. The last one is for me!'],
      ['해설', 'It got dark. He rested in an empty house.'],
      ['해설', 'At night, goblins came in. Goblins are magic monsters.'],
      ['해설', 'He hid up high on a wood beam.'],
      ['도깨비', 'Gold, come out! Silver, come out! Bang, bang!'],
      ['해설', 'The goblin hit the floor with a magic club. Gold came out!'],
      ['해설', 'The boy was hungry. He bit a nut. Crack!'],
      ['꼬마도깨비', 'The house is falling down! Run!'],
      ['해설', 'The goblins ran away. They left the magic club.'],
      ['해설', 'The younger brother became rich. He helped his neighbors.'],
      ['형', 'I want to be rich, too! All the nuts are mine!'],
      ['해설', 'The older brother went to the empty house.'],
      ['도깨비', 'Gold, come out! Silver, come out!'],
      ['해설', 'The older brother bit a nut. Crack!'],
      ['꼬마도깨비', 'That sound again! We will not run this time!'],
      ['도깨비', 'You took our club! Nose, grow long! Bang!'],
      ['해설', 'His nose grew long, like an elephant nose!'],
      ['형', 'I am sorry! I was greedy!'],
      ['해설', 'The goblins made his nose small again. He was kind after that.'],
      ['해설', 'Sharing good things first is the real treasure.'],
    ],
  },

  'kr-tiger-persimmon': {
    title: 'The Tiger and the Dried Fruit',
    names: { 해설: 'Narrator', 호랑이: 'Tiger', 엄마: 'Mom', 아기: 'Baby', 소도둑: 'Cow Thief' },
    outro: [
      'Was the story fun?',
      'If you were the tiger, what would you do?',
      'What was scary to you before, but not now?',
    ],
    lines: [
      ['해설', 'Long ago, on a snowy winter night, a tiger came down.'],
      ['호랑이', 'Roar! I am hungry. Let me look in the village.'],
      ['해설', 'The tiger went quietly next to a house.'],
      ['해설', 'In the house, a baby was crying.'],
      ['엄마', 'Stop crying, baby! A tiger will come!'],
      ['아기', 'Waaah! Waaah!'],
      ['호랑이', 'Ha! The baby is not scared of me.'],
      ['엄마', 'Here is a gotgam! Gotgam is a sweet dried fruit.'],
      ['해설', 'The baby stopped crying right away.'],
      ['호랑이', 'What? The baby stopped crying for a gotgam!'],
      ['호랑이', 'A gotgam must be scarier than me!'],
      ['해설', 'The tiger hid in the cow house. He was shaking.'],
      ['해설', 'That night, a thief came to take a cow.'],
      ['해설', 'It was very dark. The thief thought the tiger was a cow.'],
      ['소도둑', 'What a big, strong cow!'],
      ['해설', 'The thief jumped on the tiger’s back.'],
      ['호랑이', 'Help! The gotgam is on my back!'],
      ['해설', 'The tiger ran and ran to the mountain.'],
      ['소도둑', 'This cow is so fast! Oh, it is a tiger!'],
      ['해설', 'The thief grabbed a branch and got off.'],
      ['소도둑', 'I will never take a cow again.'],
      ['호랑이', 'I ran away from the gotgam. I will never go to the village again.'],
      ['해설', 'The baby ate the sweet fruit and fell asleep.'],
      ['해설', 'Do not be scared first. Find out what it is.'],
    ],
  },

  'kr-good-brothers': {
    title: 'The Good Brothers',
    names: { 해설: 'Narrator', 형: 'Big Brother', 아우: 'Little Brother', 형수: 'Big Brother’s Wife', 제수: 'Little Brother’s Wife' },
    outro: [
      'Thank you for listening!',
      'If you were the brothers, what would you do?',
      'What nice thing can you do for your family?',
    ],
    lines: [
      ['해설', 'Long ago, two good brothers lived in a village.'],
      ['해설', 'They grew rice together in their fields.'],
      ['형', 'We have a lot of rice this year. Let us share it.'],
      ['아우', 'Yes, Brother. Half for you and half for me.'],
      ['해설', 'That night, the big brother could not sleep.'],
      ['형', 'My brother has a new home. He needs more rice.'],
      ['형수', 'Yes. Let us give him some of our rice.'],
      ['해설', 'The big brother quietly took rice to his brother’s field.'],
      ['해설', 'That same night, the little brother could not sleep.'],
      ['아우', 'My brother has a big family. He needs more rice.'],
      ['제수', 'Yes. Let us take some rice to his field.'],
      ['해설', 'The little brother quietly took rice to his brother’s field.'],
      ['해설', 'The next morning, the big brother counted his rice.'],
      ['형', 'Huh? I gave some away. But I have the same rice!'],
      ['아우', 'That is strange. My rice is the same, too.'],
      ['해설', 'The next night and the next, they did it again.'],
      ['해설', 'On the third night, the moon was big and bright.'],
      ['해설', 'The two brothers met on the road.'],
      ['형', 'Little Brother! It was you!'],
      ['아우', 'Big Brother! You were carrying rice, too!'],
      ['해설', 'The brothers put down the rice and hugged.'],
      ['형', 'So that is why our rice did not get smaller!'],
      ['해설', 'They lived happily and helped each other.'],
      ['해설', 'Think of your family first. Your heart will be happy.'],
    ],
  },

  'kr-magic-millstone': {
    title: 'The Magic Millstone',
    names: { 해설: 'Narrator', 임금님: 'King', 신하: 'Helper', 도둑: 'Thief', 어부: 'Fisherman' },
    outro: [
      'Did you like the story?',
      'If you had the magic millstone, what would you make?',
      'When do you need to stop, even if you want more?',
    ],
    lines: [
      ['해설', 'Long ago, a king had a magic millstone.'],
      ['해설', 'A millstone is a round stone. You turn it around and around.'],
      ['해설', 'Say what you want and turn it. It comes out!'],
      ['임금님', 'Rice, come out! Rice, come out!'],
      ['해설', 'Round and round! White rice came out.'],
      ['임금님', 'That is enough. Stop, stop!'],
      ['신하', 'My King, can we give this rice to hungry people?'],
      ['임금님', 'Yes, give it to everyone.'],
      ['해설', 'A greedy thief heard about the millstone.'],
      ['도둑', 'With that millstone, I can be rich!'],
      ['해설', 'At night, the thief took the millstone. He went out to sea.'],
      ['도둑', 'I will make salt and sell it! Salt, come out!'],
      ['해설', 'Round and round! White salt came out.'],
      ['도둑', 'Good! More, more, more!'],
      ['해설', 'The boat was full of salt. It got very heavy.'],
      ['도둑', 'That is enough! Stop! Stop now!'],
      ['해설', 'But the thief did not know the magic words to stop it.'],
      ['해설', 'The boat went down into the sea. Splash!'],
      ['도둑', 'Help me! I was greedy!'],
      ['해설', 'A fisherman came and pulled the thief into his boat.'],
      ['어부', 'You wanted too much. You were lucky today.'],
      ['해설', 'The thief went to the king and said sorry.'],
      ['해설', 'The millstone still makes salt under the sea. So the sea is salty!'],
      ['해설', 'Do not take other people’s things. Know when to stop.'],
    ],
  },
};
