// 영어 학습용 원고 (한국 초등 저학년, 영어 초급). 문장은 자체 각색.
// 키 = stories/*.js 의 이야기 id. lines 의 첫 칸은 원래 이야기 cast 의 한국어 이름 그대로.
export default {
  'en-gingerbread-man': {
    title: 'The Gingerbread Man',
    names: { 해설: 'Narrator', 할머니: 'Grandma', 할아버지: 'Grandpa', 진저브레드: 'Gingerbread Man', 소: 'Cow', 여우: 'Fox' },
    outro: [
      'Hello again! Did you run with the Gingerbread Man?',
      'If you were the Gingerbread Man, would you ride on the fox?',
      'Who do you ask for help when you need it?',
    ],
    lines: [
      ['해설', 'An old woman and an old man lived in a little house.'],
      ['할머니', 'Today I will make a gingerbread boy!'],
      ['해설', 'She gave him two raisin buttons. Then she put him in the oven.'],
      ['해설', 'She opened the oven. The gingerbread boy jumped up and ran!'],
      ['진저브레드', 'Run, run, I am fast! Nobody can catch me!'],
      ['할아버지', 'Stop! Come back here!'],
      ['해설', 'Grandma and Grandpa ran and ran. But they could not catch him.'],
      ['소', 'Moo! You look yummy. Please stop!'],
      ['진저브레드', 'Run, run, I am fast! You cannot catch me, Cow!'],
      ['해설', 'Then he came to a big river. He stopped.'],
      ['진저브레드', 'Oh no! If I get wet, I will get soft.'],
      ['해설', 'A fox came out of the grass.'],
      ['여우', 'Do not worry. Sit on my tail. I will take you across.'],
      ['해설', 'The Gingerbread Man sat on the tail. The fox swam. Splash, splash!'],
      ['여우', 'The water is deep. Go up on my back.'],
      ['여우', 'It is deeper now. Go up on my nose.'],
      ['해설', 'He went up on the nose. The fox opened his big mouth!'],
      ['진저브레드', 'Oh no! It is a trick!'],
      ['해설', 'Just then, the fox’s feet touched the sand. Jump! The Gingerbread Man jumped to the grass.'],
      ['여우', 'Oh! I almost had him!'],
      ['해설', 'The Gingerbread Man ran all the way home.'],
      ['진저브레드', 'Grandma, Grandpa, I am sorry I ran away.'],
      ['할머니', 'We are so happy you are safe. Stay with us.'],
      ['해설', 'Do not show off. And be careful of sweet words from strangers.'],
    ],
  },

  'en-chicken-licken': {
    title: 'The Sky Is Falling!',
    names: { 해설: 'Narrator', 삐약이: 'Chick', 꼬꼬댁: 'Hen', 꽥꽥이: 'Duck', 뒤뚱이: 'Goose', 칠면조: 'Turkey', 여우: 'Fox' },
    outro: [
      'Thank you for listening! Was the little chick silly?',
      'If you were the Chick, what would you do first?',
      'What do you do when you feel scared?',
    ],
    lines: [
      ['해설', 'One day, a little chick was playing under an oak tree.'],
      ['해설', 'Bonk! An acorn fell on her head.'],
      ['삐약이', 'Ouch! The sky is falling! I must tell the king!'],
      ['해설', 'The chick ran and ran. She met the hen.'],
      ['꼬꼬댁', 'Little Chick, where are you going?'],
      ['삐약이', 'The sky is falling! I am going to tell the king!'],
      ['꼬꼬댁', 'Oh my! I will come, too.'],
      ['해설', 'Then they met the duck.'],
      ['꽥꽥이', 'Quack, quack! Why are you running?'],
      ['꼬꼬댁', 'The sky is falling! We are going to tell the king!'],
      ['해설', 'The duck came. The goose came. The turkey came, too.'],
      ['칠면조', 'Gobble, gobble. Together we are not scared.'],
      ['해설', 'Then a fox came out.'],
      ['여우', 'Hello, friends! I know a short way to the king. Follow me.'],
      ['해설', 'They followed the fox to a dark cave. A big pot was bubbling.'],
      ['칠면조', 'Wait! This is not the king’s house. This is the fox’s cave!'],
      ['뒤뚱이', 'And look! The sky is still blue!'],
      ['꽥꽥이', 'It is a trick! Run, everybody!'],
      ['해설', 'Flap, flap! Waddle, waddle! They all ran away.'],
      ['여우', 'Oh no! I did not catch any of them!'],
      ['해설', 'Back under the oak tree, another acorn fell. Bonk!'],
      ['꼬꼬댁', 'Look, Chick. It is not the sky. It is an acorn!'],
      ['삐약이', 'Oh! I am sorry. I did not look carefully.'],
      ['해설', 'Look carefully first. And do not follow strangers.'],
    ],
  },

  'en-tom-thumb': {
    title: 'Tom Thumb',
    names: { 해설: 'Narrator', 엄마: 'Mom', 마법사: 'Wizard', 아빠: 'Dad', 톰: 'Tom', 임금님: 'King' },
    outro: [
      'Hi there! Did you like little Tom?',
      'If you were as small as Tom, where would you go?',
      'What can you do well, even if you are small?',
    ],
    lines: [
      ['해설', 'Long ago, a farmer and his wife lived in a small village.'],
      ['엄마', 'I want a baby. Even a baby as small as my thumb!'],
      ['마법사', 'I heard you. I will make your wish come true.'],
      ['해설', 'Soon a tiny baby was born. He was as small as a thumb!'],
      ['아빠', 'Let us call him Tom Thumb!'],
      ['톰', 'I am small, but I can do a lot!'],
      ['해설', 'One day, Mom was making pudding in a big bowl.'],
      ['해설', 'Tom sat on the bowl to look. Oops! He fell in.'],
      ['톰', 'Yuck! It is so sticky! Mom, help me!'],
      ['엄마', 'Oh, Tom! You almost became a pudding!'],
      ['해설', 'Another day, Tom sat on a flower. A cow ate the flower!'],
      ['톰', 'Hey, Cow! I am not grass! Open your mouth!'],
      ['해설', 'The cow said moo, and Tom jumped out.'],
      ['해설', 'Another day, Tom fell in the river. A big fish swallowed him!'],
      ['해설', 'A fisherman caught the fish. It went to the king’s kitchen.'],
      ['해설', 'The cook opened the fish. Out came Tom!'],
      ['톰', 'Hello! I am Tom Thumb. Where am I?'],
      ['임금님', 'Such a small and brave boy!'],
      ['톰', 'King, I am small, but I can sing and dance!'],
      ['해설', 'Tom danced on the table. Everybody laughed and clapped.'],
      ['임금님', 'You will be my smallest knight!'],
      ['해설', 'Tom rode a mouse like a horse. He brought Mom and Dad to the castle.'],
      ['해설', 'You can be small and still do big things.'],
    ],
  },

  'en-dick-whittington': {
    title: 'Dick Whittington and His Cat',
    names: { 해설: 'Narrator', 딕: 'Dick', 상인: 'Merchant', 요리사: 'Cook', 종소리: 'Bells', 왕: 'King', 선장: 'Captain' },
    outro: [
      'Good job listening! Did you like Dick and his cat?',
      'If you were Dick, would you go back to London?',
      'What do you keep trying, even when it is hard?',
    ],
    lines: [
      ['해설', 'Long ago, a poor boy named Dick lived in the country.'],
      ['딕', 'The streets in London are made of gold! I will go there!'],
      ['해설', 'Dick walked and walked. At last, he came to London.'],
      ['딕', 'Huh? There is no gold. There is only dirt.'],
      ['해설', 'Dick was hungry and tired. He sat down by a rich man’s door.'],
      ['상인', 'Poor boy. You can work and live in my kitchen.'],
      ['요리사', 'Hurry up! Wash the pots!'],
      ['해설', 'The cook was not kind. And Dick’s little room had many mice.'],
      ['해설', 'Dick got one coin. He bought a cat with it.'],
      ['딕', 'Kitty, you are my friend now. Please chase the mice.'],
      ['해설', 'One day, the merchant’s ship was going far away.'],
      ['상인', 'Everyone, give one thing to sell on my ship.'],
      ['딕', 'I only have my cat. I will send her.'],
      ['해설', 'Dick was sad and lonely. He ran away early in the morning.'],
      ['종소리', 'Ding, dong! Go back, Dick! You will be the mayor of London!'],
      ['딕', 'Me? The mayor? Then I will go back and try again!'],
      ['해설', 'Far away, the ship came to a land with many mice.'],
      ['왕', 'Mice everywhere! I cannot eat my dinner!'],
      ['선장', 'King, we have an animal that catches mice!'],
      ['해설', 'The cat ran and jumped. All the mice ran away.'],
      ['왕', 'Wonderful! I will give you a box of gold for this cat.'],
      ['상인', 'Dick, your cat got this gold. It is all yours.'],
      ['해설', 'Dick shared gifts with everyone. Later, he became the mayor of London.'],
      ['해설', 'Do not give up. Keep working hard, and good days will come.'],
    ],
  },

  'en-lazy-jack': {
    title: 'Lazy Jack',
    names: { 해설: 'Narrator', 엄마: 'Mom', 잭: 'Jack', 부자: 'Rich Man', 아가씨: 'Girl' },
    outro: [
      'Hello, friend! Was Jack funny?',
      'If you were Jack, how would you carry the milk?',
      'What do you think about before you do something?',
    ],
    lines: [
      ['해설', 'Long ago, a boy named Jack lived with his mom.'],
      ['해설', 'Jack did nothing all day. He just lay by the fire.'],
      ['엄마', 'Jack, you must work now!'],
      ['잭', 'Okay, Mom. I will work tomorrow.'],
      ['해설', 'Jack worked for a farmer. He got a coin. But he dropped it in a stream.'],
      ['엄마', 'Oh, Jack! Put it in your pocket next time!'],
      ['해설', 'The next day, Jack got milk. He put it in his pocket.'],
      ['해설', 'Splish, splash! The milk spilled out.'],
      ['엄마', 'Oh, Jack! Carry it on your head next time!'],
      ['해설', 'The next day, Jack got cheese. He put it on his head.'],
      ['해설', 'The sun was hot. The cheese melted in his hair!'],
      ['엄마', 'Oh, Jack! Carry it in your hands next time!'],
      ['해설', 'The next day, Jack got a cat. He held it in his hands.'],
      ['해설', 'Meow! The cat scratched him and ran away.'],
      ['엄마', 'Oh, Jack! Pull it on a string next time!'],
      ['해설', 'The next day, Jack got meat. He pulled it on a string. It got dirty.'],
      ['엄마', 'Oh, Jack! Carry it on your back next time!'],
      ['해설', 'The next day, Jack got a donkey. He put it on his back!'],
      ['부자', 'My daughter never laughs. If someone makes her laugh, he can marry her.'],
      ['아가씨', 'Ha ha ha! Look! A boy is carrying a donkey!'],
      ['부자', 'My daughter laughed! Jack, you can marry her.'],
      ['해설', 'Jack married the girl. They lived happily with his mom.'],
      ['잭', 'Now I will think first before I do things!'],
      ['해설', 'Do not just copy. Think about what is right each time.'],
    ],
  },

  'gr-hansel-gretel': {
    title: 'Hansel and Gretel',
    names: { 해설: 'Narrator', 헨젤: 'Hansel', 그레텔: 'Gretel', 할멈: 'Old Woman', 아빠: 'Dad', 엄마: 'Mom' },
    outro: [
      'Did you enjoy the story? Hansel and Gretel were brave!',
      'If you were Gretel, what plan would you make?',
      'Who do you help at home?',
    ],
    lines: [
      ['해설', 'Hansel and Gretel lived in a little house near the woods.'],
      ['해설', 'One day, they went deep into the woods to pick berries.'],
      ['헨젤', 'Let us drop bread crumbs. Then we will not get lost.'],
      ['해설', 'But birds came. Peck, peck! They ate all the crumbs.'],
      ['그레텔', 'Hansel, the path is gone! Where is home?'],
      ['헨젤', 'Do not worry, Gretel. Hold my hand.'],
      ['해설', 'They walked and walked. Then they saw a strange house.'],
      ['해설', 'The walls were cookies. The roof was cake!'],
      ['헨젤', 'Wow, a cookie house! Crunch, crunch!'],
      ['그레텔', 'Yum! The window is candy!'],
      ['해설', 'The door opened. An old woman came out.'],
      ['할멈', 'Who is eating my house? It is all mine!'],
      ['할멈', 'Now you must work for me. I will lock the door.'],
      ['해설', 'Hansel carried wood. Gretel baked cookies every day.'],
      ['헨젤', 'I miss Mom and Dad so much.'],
      ['그레텔', 'I have a plan. She loves sweet things.'],
      ['해설', 'Gretel baked a very big honey cake.'],
      ['할멈', 'Yum, yum! It is all mine!'],
      ['해설', 'The old woman ate it all. Then she fell asleep. Snore, snore.'],
      ['해설', 'Hansel took the key very quietly. Click! The door opened.'],
      ['할멈', 'Nobody is here. I was greedy, and now I am alone.'],
      ['아빠', 'Hansel! Gretel! We looked for you all night!'],
      ['엄마', 'My babies! You are safe!'],
      ['해설', 'Being greedy makes you lonely. Helping each other makes you strong.'],
    ],
  },

  'gr-frog-prince': {
    title: 'The Frog Prince',
    names: { 해설: 'Narrator', 공주: 'Princess', 개구리: 'Frog', 임금님: 'King', 왕자: 'Prince' },
    outro: [
      'Hello again! Did the princess keep her promise?',
      'If you were the Princess, would you open the door for the frog?',
      'What promise did you make and keep?',
    ],
    lines: [
      ['해설', 'Long ago, a young princess lived in a castle.'],
      ['해설', 'She had a shiny gold ball. She loved it very much.'],
      ['해설', 'One day, she played by a well. Plop! The ball fell in.'],
      ['공주', 'My gold ball! Boo hoo! Please help me!'],
      ['개구리', 'Ribbit! Why are you crying? I can get your ball.'],
      ['개구리', 'But please be my friend. Let us eat from one plate.'],
      ['공주', 'Yes, yes, I promise! Please get it!'],
      ['해설', 'The frog jumped in. He came up with the ball.'],
      ['해설', 'The princess took the ball and ran home.'],
      ['개구리', 'Wait, Princess! Take me with you!'],
      ['해설', 'The next evening, there was a knock at the door. Knock, knock.'],
      ['개구리', 'Princess, open the door. Did you forget your promise?'],
      ['임금님', 'Did you make a promise? Then you must keep it.'],
      ['공주', 'Yes, Father. I made a promise.'],
      ['해설', 'The princess put the frog on the table.'],
      ['개구리', 'This soup is good. It is better when we eat together.'],
      ['해설', 'The frog told funny stories. The princess laughed.'],
      ['공주', 'You are my friend now. Thank you for my ball.'],
      ['해설', 'Then there was a bright light. The frog became a prince!'],
      ['왕자', 'Thank you! A bad spell made me a frog.'],
      ['왕자', 'You kept your promise, so the spell is gone.'],
      ['임금님', 'Keeping a promise brings good things.'],
      ['해설', 'Always keep your promises. Then friends can trust you.'],
    ],
  },

  'gr-wolf-seven-kids': {
    title: 'The Wolf and the Seven Kids',
    names: { 해설: 'Narrator', 엄마염소: 'Mother Goat', 늑대: 'Wolf', 아기염소들: 'Little Goats', 막내: 'Littlest Goat' },
    outro: [
      'Thank you for listening! The little goats were safe.',
      'If you were a little goat, where would you hide?',
      'What do you do when someone knocks on your door?',
    ],
    lines: [
      ['해설', 'Once upon a time, a mother goat lived with seven little goats.'],
      ['엄마염소', 'I am going to the woods to get food.'],
      ['엄마염소', 'Do not open the door for the wolf. He has a low voice and black feet.'],
      ['아기염소들', 'Okay, Mom! We will be careful.'],
      ['해설', 'Soon, there was a knock. Knock, knock, knock.'],
      ['늑대', 'Children, it is Mom. Open the door.'],
      ['아기염소들', 'Our mom has a soft voice. You are the wolf!'],
      ['해설', 'The wolf ate some honey. Now his voice was soft.'],
      ['늑대', 'Children, it is Mom. Open the door.'],
      ['아기염소들', 'Our mom has white feet. You are the wolf!'],
      ['해설', 'The wolf put white flour on his feet.'],
      ['해설', 'A soft voice and white feet! The little goats opened the door.'],
      ['해설', 'The wolf came in! The goats ran and hid.'],
      ['해설', 'The wolf found six goats. He put them in a big bag.'],
      ['해설', 'But the littlest goat was in the big clock.'],
      ['해설', 'The wolf lay down under a tree. Snore, snore.'],
      ['막내', 'Mom! I am in the clock! The wolf took everyone!'],
      ['엄마염소', 'Do not cry. Let us go find them.'],
      ['해설', 'Snip, snip! Mom cut the bag. Out jumped the little goats!'],
      ['엄마염소', 'Shh! Bring some stones. Let us fill the bag.'],
      ['늑대', 'This bag is so heavy! Clunk, clunk.'],
      ['해설', 'The wolf fell into the well. Splash! He ran far away.'],
      ['아기염소들', 'The wolf ran away! Hooray!'],
      ['해설', 'If someone asks you to open the door, ask a grown-up first.'],
    ],
  },

  'gr-sweet-porridge': {
    title: 'The Magic Porridge Pot',
    names: { 해설: 'Narrator', 소녀: 'Girl', 할머니: 'Old Woman', 엄마: 'Mom', 이웃: 'Neighbor' },
    outro: [
      'Hi! Did you like the magic pot?',
      'If you had a magic pot, what food would you make?',
      'What do you do when you forget something?',
    ],
    lines: [
      ['해설', 'Long ago, a kind girl lived with her mom.'],
      ['해설', 'They were very poor. They had no food.'],
      ['소녀', 'Mom is hungry. I will look for berries in the woods.'],
      ['해설', 'In the woods, the girl met an old woman.'],
      ['할머니', 'Little girl, why are you sad?'],
      ['소녀', 'We have no food. Here, please have some berries.'],
      ['할머니', 'You are so kind. Here is a little pot for you.'],
      ['할머니', 'Say, Cook, little pot, cook! Then it makes sweet porridge.'],
      ['할머니', 'Say, Stop, little pot, stop! Then it stops. Remember!'],
      ['소녀', 'Mom, look! Cook, little pot, cook!'],
      ['해설', 'Bubble, bubble! The pot was full of sweet porridge.'],
      ['엄마', 'Wow! This porridge is so good!'],
      ['소녀', 'Stop, little pot, stop! See? It stopped.'],
      ['해설', 'One day, the girl went out. Mom was home alone.'],
      ['엄마', 'I am hungry. Cook, little pot, cook!'],
      ['엄마', 'Now stop! Hmm, what were the words? Stop, pot! Oh no!'],
      ['해설', 'The porridge filled the kitchen. It went out the door.'],
      ['해설', 'Porridge in the street! Porridge in every yard!'],
      ['이웃', 'What is this? Porridge is at my door!'],
      ['소녀', 'Stop, little pot, stop!'],
      ['해설', 'The pot stopped. The porridge stopped, too.'],
      ['이웃', 'To go home, we must eat our way!'],
      ['해설', 'Everyone ate porridge all the way home. Yum, yum!'],
      ['해설', 'Remember important words. If you forget, ask.'],
    ],
  },

  'gr-golden-goose': {
    title: 'The Golden Goose',
    names: { 해설: 'Narrator', 막내: 'Youngest Brother', 할아버지: 'Old Man', 큰딸: 'Big Sister', 농부: 'Farmer', 공주: 'Princess', 임금님: 'King' },
    outro: [
      'Hello, friend! Was the long line funny?',
      'If you were the youngest brother, would you share your bread?',
      'What do you like to share with others?',
    ],
    lines: [
      ['해설', 'Long ago, there were three brothers. People laughed at the youngest one.'],
      ['해설', 'The big brothers met a hungry old man. They did not share their bread.'],
      ['막내', 'Now it is my turn to go to the woods!'],
      ['할아버지', 'I am hungry. Can you share some food?'],
      ['막내', 'I only have old bread. But let us eat together.'],
      ['해설', 'He opened his bag. The old bread was now soft cake!'],
      ['할아버지', 'You are kind. Cut down that old tree.'],
      ['해설', 'Chop! Under the tree sat a golden goose!'],
      ['막내', 'Wow! Shiny gold feathers!'],
      ['해설', 'That night, he stayed at an inn with the goose.'],
      ['큰딸', 'I will take just one gold feather.'],
      ['해설', 'She touched the goose. Her hand got stuck!'],
      ['큰딸', 'Oh no! My hand is stuck!'],
      ['해설', 'Her two sisters came to help. They got stuck, too!'],
      ['해설', 'The next day, the boy walked with the goose. The girls came, too.'],
      ['농부', 'Hey, girls! Why are you following him? Oh no, I am stuck!'],
      ['해설', 'More and more people got stuck. The line was like a train!'],
      ['임금님', 'My daughter never laughs. Who can make her laugh?'],
      ['공주', 'Ha ha ha! Look at that line! So funny!'],
      ['임금님', 'She laughed! At last, she laughed!'],
      ['해설', 'Then everyone came unstuck. They all went home.'],
      ['해설', 'The youngest brother married the princess. They lived happily.'],
      ['해설', 'A kind heart that shares brings good things.'],
    ],
  },

  'gr-snow-white': {
    title: 'Snow White',
    names: { 해설: 'Narrator', 왕비: 'Queen', 거울: 'Mirror', 사냥꾼: 'Hunter', 백설공주: 'Snow White', 난쟁이: 'Little Man', 왕자: 'Prince' },
    outro: [
      'Good to see you! Did you like Snow White?',
      'If you were Snow White, would you open the door?',
      'How do you help your friends?',
    ],
    lines: [
      ['해설', 'Long ago, there was a kind princess named Snow White.'],
      ['해설', 'The new queen had a magic mirror.'],
      ['왕비', 'Mirror, mirror, who is the most beautiful?'],
      ['거울', 'You are beautiful, Queen. But Snow White is the most beautiful.'],
      ['왕비', 'What? Send her far away into the woods!'],
      ['사냥꾼', 'Princess, run far away. Do not come back to the castle.'],
      ['해설', 'Snow White walked in the dark woods. She found a tiny house.'],
      ['해설', 'Seven little chairs. Seven little plates. Seven little beds.'],
      ['백설공주', 'I am so tired. I will rest a little.'],
      ['해설', 'In the evening, seven little men came home from work.'],
      ['난쟁이', 'Look! Someone is sleeping in my bed!'],
      ['백설공주', 'I am sorry. I have no home.'],
      ['난쟁이', 'Then live with us! We can help each other.'],
      ['난쟁이', 'When we are out, do not open the door for anyone.'],
      ['해설', 'The queen was angry again. She made a sleepy apple.'],
      ['왕비', 'Knock, knock! Try this red apple, dear!'],
      ['해설', 'Snow White took a bite. She fell into a deep sleep.'],
      ['해설', 'The little men cried. They watched over her every day.'],
      ['왕자', 'I want to take care of this sleeping princess.'],
      ['해설', 'Bump! The bed shook. The apple piece came out. Snow White opened her eyes!'],
      ['난쟁이', 'She is awake! Hooray, hooray!'],
      ['해설', 'The queen was sent far away. She was sorry.'],
      ['해설', 'Snow White married the prince. Everyone danced at the party.'],
      ['해설', 'Caring for others is more beautiful than being jealous.'],
    ],
  },

  'gr-rapunzel': {
    title: 'Rapunzel',
    names: { 해설: 'Narrator', 아내: 'Wife', 남편: 'Husband', 마녀: 'Witch', 라푼젤: 'Rapunzel', 왕자: 'Prince' },
    outro: [
      'Thank you for listening! Rapunzel sang so well.',
      'If you were in a tall tower, what would you do all day?',
      'What song do you like to sing?',
    ],
    lines: [
      ['해설', 'Long ago, a husband and wife wanted a baby.'],
      ['해설', 'Next to their house was a witch’s garden.'],
      ['아내', 'I really want to eat the green leaves in that garden.'],
      ['해설', 'At night, the husband went into the garden. The witch saw him!'],
      ['마녀', 'Who is taking my leaves?'],
      ['남편', 'I am sorry! My wife wanted them so much.'],
      ['마녀', 'Take them. But when your baby is born, I will take the baby.'],
      ['해설', 'The husband was scared, so he said yes. The witch took the baby girl.'],
      ['해설', 'Her name was Rapunzel. The witch put her in a tall tower.'],
      ['해설', 'The tower had no door and no stairs. It had one small window.'],
      ['마녀', 'Rapunzel, Rapunzel! Let down your long hair!'],
      ['해설', 'Rapunzel let down her long hair. The witch climbed up.'],
      ['해설', 'Rapunzel often sang at the window. One day, a prince heard her.'],
      ['왕자', 'What a pretty song! It is coming from the tower.'],
      ['왕자', 'Rapunzel, Rapunzel! Let down your long hair!'],
      ['라푼젤', 'Oh! Who are you? Nobody comes here.'],
      ['왕자', 'Do not be scared. I love your song. Let us be friends.'],
      ['라푼젤', 'Bring me silk every time. I will make a ladder.'],
      ['마녀', 'You tricked me! Go far away to the desert!'],
      ['해설', 'The witch cut Rapunzel’s hair and sent her away.'],
      ['왕자', 'Rapunzel, where are you? I will find you!'],
      ['해설', 'The prince looked for years. Then he heard a song he knew.'],
      ['라푼젤', 'Is that you? My prince!'],
      ['해설', 'Trust each other and never give up. Then you can meet again.'],
    ],
  },

  'gr-star-coins': {
    title: 'The Star Coins',
    names: { 해설: 'Narrator', 소녀: 'Girl', 할아버지: 'Old Man', 남자아이: 'Boy', 여자아이: 'Little Girl', 꼬마: 'Small Child' },
    outro: [
      'Hello! Did you see the stars fall?',
      'If you were the girl, what would you give?',
      'What nice thing did you do for someone today?',
    ],
    lines: [
      ['해설', 'Long ago, there was a poor girl. She had no home.'],
      ['해설', 'She had only her clothes and a piece of bread.'],
      ['해설', 'But she had a very kind heart.'],
      ['소녀', 'I will go to the big field. Maybe something good will happen.'],
      ['해설', 'She met a hungry old man.'],
      ['할아버지', 'I am so hungry. Do you have any food?'],
      ['소녀', 'Here is my bread. You can have it all.'],
      ['할아버지', 'Thank you, dear. Good things will come to you.'],
      ['해설', 'Then she met a boy. He was shaking.'],
      ['남자아이', 'My head is so cold. The wind is blowing.'],
      ['소녀', 'Take my hat. It will keep you warm.'],
      ['해설', 'Then she met a little girl with no jacket.'],
      ['여자아이', 'I am cold, so cold!'],
      ['소녀', 'Take my jacket. I am okay.'],
      ['해설', 'Then she gave her skirt to a small child.'],
      ['꼬마', 'Thank you! Now I am not cold at all.'],
      ['해설', 'Night came. Now the girl had nothing left.'],
      ['해설', 'She looked up at the sky. The stars were twinkling.'],
      ['해설', 'Then the stars began to fall. One, two, three!'],
      ['해설', 'The stars turned into silver coins. Clink, clink!'],
      ['소녀', 'Wow! Coins are falling from the sky!'],
      ['해설', 'And she had soft, new, white clothes on.'],
      ['소녀', 'I am so warm! Thank you!'],
      ['해설', 'A heart that shares shines like the stars.'],
    ],
  },

  'gr-rumpelstiltskin': {
    title: 'Rumpelstiltskin',
    names: { 해설: 'Narrator', 방앗간주인: 'Miller', 임금님: 'King', 아가씨: 'Girl', 난쟁이: 'Little Man', 신하: 'Helper' },
    outro: [
      'Hi, friend! Could you guess his name?',
      'If you were the girl, what would you say to the king?',
      'Is it easy or hard for you to keep a promise?',
    ],
    lines: [
      ['해설', 'Long ago, a poor miller told the king a big story.'],
      ['방앗간주인', 'King, my daughter can make gold from straw!'],
      ['임금님', 'Really? Then make this straw into gold tonight.'],
      ['아가씨', 'I cannot do that! What can I do? Boo hoo.'],
      ['해설', 'The door opened. A little man came in.'],
      ['난쟁이', 'Why are you crying? What will you give me for gold?'],
      ['아가씨', 'I will give you my necklace.'],
      ['해설', 'The wheel went round and round. In the morning, there was gold!'],
      ['해설', 'The king wanted more. The little man came again and took her ring.'],
      ['임금님', 'Do it one more time. Then you will be my queen!'],
      ['난쟁이', 'You have nothing now. Give me your first baby.'],
      ['해설', 'The girl was scared. She said yes.'],
      ['해설', 'She became the queen. A year later, she had a baby.'],
      ['난쟁이', 'I am here for the baby!'],
      ['아가씨', 'Please, no! Take all my treasure instead!'],
      ['난쟁이', 'Hmm. Guess my name in three days. Then I will go.'],
      ['아가씨', 'Is it Hans? Is it Fritz?'],
      ['난쟁이', 'No, no! Two days left!'],
      ['신하', 'Queen! I saw a little man in the woods. He was singing.'],
      ['난쟁이', 'Nobody knows my name is Rumpelstiltskin!'],
      ['아가씨', 'Is your name Rumpelstiltskin?'],
      ['난쟁이', 'What? Who told you? Grr!'],
      ['해설', 'He stamped his feet and ran away. He never came back.'],
      ['해설', 'Do not tell lies or make hard promises. They bring big worries.'],
    ],
  },

  'pr-cinderella': {
    title: 'Cinderella',
    names: { 해설: 'Narrator', 신데렐라: 'Cinderella', 새언니들: 'Stepsisters', 요정: 'Fairy', 왕자: 'Prince' },
    outro: [
      'Thank you for listening! Did the glass shoe fit?',
      'If you were Cinderella, would you forgive your sisters?',
      'When did you say sorry or forgive someone?',
    ],
    lines: [
      ['해설', 'Long ago, kind Cinderella lived with her stepmother and two stepsisters.'],
      ['해설', 'Every day, Cinderella cleaned and cleaned. She slept by the fire.'],
      ['새언니들', 'Cinderella! Brush my hair! Where is my ribbon?'],
      ['해설', 'One day, news came. The prince was having a big party!'],
      ['새언니들', 'We are going to the party. You stay home!'],
      ['신데렐라', 'I want to go to the party just once.'],
      ['해설', 'Then, sparkle! A fairy came.'],
      ['요정', 'Do not cry, dear. Bring me a pumpkin.'],
      ['해설', 'Tap! The pumpkin became a gold coach.'],
      ['해설', 'Six mice became horses. Her old dress became a star dress.'],
      ['해설', 'And she had shiny glass shoes on her feet.'],
      ['요정', 'But remember! At twelve o’clock, the magic will end.'],
      ['신데렐라', 'I will remember! Thank you!'],
      ['왕자', 'Hello. Will you dance with me?'],
      ['해설', 'They danced and danced. Then the clock rang. Dong, dong, dong!'],
      ['신데렐라', 'Oh no! It is twelve! I must go!'],
      ['해설', 'She ran down the stairs. One glass shoe fell off.'],
      ['왕자', 'I will find the girl with this shoe.'],
      ['새언니들', 'Push! Push! Oh, it is too small!'],
      ['신데렐라', 'May I try it on, please?'],
      ['해설', 'It fit! Then Cinderella took out the other shoe.'],
      ['새언니들', 'Cinderella, we are sorry. We were not nice.'],
      ['신데렐라', 'It is okay. Let us be good sisters now.'],
      ['해설', 'A kind heart will shine. Forgiving makes everyone happy.'],
    ],
  },

  'pr-puss-in-boots': {
    title: 'Puss in Boots',
    names: { 해설: 'Narrator', 고양이: 'Cat', 막내: 'Youngest Son', 임금님: 'King', 농부: 'Farmer', 도깨비: 'Ogre' },
    outro: [
      'Hello again! Was the cat clever?',
      'If you were the cat, what plan would you make?',
      'When is it important for you to tell the truth?',
    ],
    lines: [
      ['해설', 'Long ago, a miller had three sons.'],
      ['해설', 'The first son got the mill. The second got a donkey. The youngest got a cat.'],
      ['막내', 'I only have a cat. What can I do?'],
      ['고양이', 'Do not worry! Just give me boots and a bag.'],
      ['해설', 'The cat put on the boots. Then he took berries to the king.'],
      ['고양이', 'King, this is a gift from Lord Carabas.'],
      ['임금님', 'Lord Carabas? How kind!'],
      ['해설', 'One day, the king and the princess went to the river.'],
      ['고양이', 'Master, jump in the river! Trust me!'],
      ['막내', 'In the river? Okay! Splash!'],
      ['고양이', 'Help! A robber took Lord Carabas’s clothes!'],
      ['임금님', 'Oh no! Bring him my best clothes!'],
      ['해설', 'The youngest son got in the king’s coach. The cat ran ahead.'],
      ['고양이', 'Farmers, please say this field is Lord Carabas’s!'],
      ['농부', 'This field? Yes, it is Lord Carabas’s!'],
      ['해설', 'But really, the land was an ogre’s. He lived in a big castle.'],
      ['고양이', 'Mr. Ogre, can you really turn into a lion?'],
      ['도깨비', 'Easy! Roar!'],
      ['고양이', 'Wow! Can you turn into a tiny mouse, too?'],
      ['도깨비', 'Easy! Pop!'],
      ['해설', 'The mouse saw the cat and ran far away.'],
      ['막내', 'King, I am not a lord. I am just a miller’s son.'],
      ['임금님', 'You told the truth. I trust you. Take care of this castle.'],
      ['해설', 'Be clever, but in the end, always tell the truth.'],
    ],
  },
};
