// 영어 학습용 원고 (한국 초등 저학년, 영어 초급). 문장은 자체 각색.
// 키 = stories/*.js 의 이야기 id. lines 의 첫 칸은 원래 이야기 cast 의 한국어 이름 그대로.
export default {
  'an-thumbelina': {
    title: 'Thumbelina',
    names: { 해설: 'Narrator', 엄지공주: 'Thumbelina', 두꺼비: 'Toad', 들쥐: 'Field Mouse', 두더지: 'Mole', 제비: 'Swallow' },
    outro: [
      'Did you like Thumbelina?',
      'If you were Thumbelina, what would you do for the cold bird?',
      'Who helped you when you needed help?',
    ],
    lines: [
      ['해설', 'Once upon a time, a woman planted a little seed.'],
      ['해설', 'A flower opened. Inside was a very tiny girl!'],
      ['해설', 'She was as small as a thumb. Her name was Thumbelina.'],
      ['해설', 'One night, a big toad hopped in. Hop, hop!'],
      ['두꺼비', 'Croak! This tiny girl can marry my son!'],
      ['해설', 'The toad put her on a leaf in the river.'],
      ['엄지공주', 'I want to go home. I do not want to live with toads.'],
      ['해설', 'Kind fish cut the leaf free. The leaf floated away.'],
      ['해설', 'All summer, she drank drops of water from the flowers.'],
      ['해설', 'Then winter came. It was very cold.'],
      ['들쥐', 'Oh, you are so cold! Come in and stay with me.'],
      ['해설', 'Next door lived a rich mole. He lived under the ground.'],
      ['두더지', 'I do not like the sun or flowers. Marry me!'],
      ['해설', 'In the mole’s long tunnel, Thumbelina saw a sick bird.'],
      ['엄지공주', 'Poor Swallow, you are cold. I will keep you warm.'],
      ['해설', 'Every night, she covered the bird with soft grass.'],
      ['제비', 'Thank you! I will come back in the spring.'],
      ['해설', 'Spring came. Soon it was the day to marry the mole.'],
      ['엄지공주', 'Goodbye, Sun. I will not see you again.'],
      ['제비', 'Thumbelina! Get on my back. Let us fly away!'],
      ['해설', 'They flew to a warm land full of flowers.'],
      ['해설', 'A tiny flower prince gave her shiny wings.'],
      ['엄지공주', 'I can fly now! Thank you, Swallow!'],
      ['해설', 'A little kindness can come back to you as a big gift.'],
    ],
  },

  'an-princess-pea': {
    title: 'The Princess and the Pea',
    names: { 해설: 'Narrator', 왕자: 'Prince', 왕비: 'Queen', 임금님: 'King', 공주: 'Princess' },
    outro: [
      'Was the story fun?',
      'If you were the Princess, what would you say in the morning?',
      'How do you sleep at night? Do you have a soft bed?',
    ],
    lines: [
      ['해설', 'Once upon a time, a prince wanted to marry a real princess.'],
      ['해설', 'He went all over the world. He met many princesses.'],
      ['왕자', 'Who is a real princess? I do not know.'],
      ['해설', 'The prince came home. He was sad.'],
      ['해설', 'One night, there was a big storm. Boom! Rain, rain!'],
      ['해설', 'Knock, knock! Someone was at the door.'],
      ['임금님', 'Who is out in the rain? Open the door!'],
      ['해설', 'A girl stood at the door. She was very wet.'],
      ['공주', 'I am a princess. Can I stay here tonight?'],
      ['왕비', 'Hmm. Is she a real princess? I will find out.'],
      ['해설', 'The queen put one small pea on the bed.'],
      ['해설', 'Then she put on one, two, three soft mattresses.'],
      ['해설', 'Ten, fifteen, twenty mattresses! The bed was very tall.'],
      ['임금님', 'Ha ha! She needs a ladder to go to bed!'],
      ['해설', 'That night, the princess turned and turned.'],
      ['왕비', 'Good morning! Did you sleep well?'],
      ['공주', 'No, I did not sleep at all. Something hard was in my bed.'],
      ['왕비', 'She felt one pea under twenty mattresses!'],
      ['임금님', 'Only a real princess can feel that!'],
      ['왕자', 'I found a real princess! Will you marry me?'],
      ['공주', 'Yes! But tonight, one mattress is enough!'],
      ['해설', 'They got married. The pea went to a museum.'],
      ['해설', 'An honest heart shows who you really are.'],
    ],
  },

  'an-tin-soldier': {
    title: 'The Brave Tin Soldier',
    names: { 해설: 'Narrator', 병정: 'Soldier', 무희: 'Dancer', 도깨비: 'Jack-in-the-Box', 쥐: 'Rat', 소년: 'Boy' },
    outro: [
      'Did you enjoy the trip with the tin soldier?',
      'If you were the soldier on the paper boat, how would you feel?',
      'What is your favorite toy?',
    ],
    lines: [
      ['해설', 'A boy got twenty-five tin soldiers for his birthday.'],
      ['해설', 'The last soldier had only one leg.'],
      ['병정', 'I have one leg, but I can stand tall.'],
      ['해설', 'On the table, there was a paper castle.'],
      ['해설', 'A paper dancer stood there on one leg.'],
      ['병정', 'She has one leg, too. I want to be her friend.'],
      ['무희', 'Hello, Soldier. You stand so well!'],
      ['해설', 'At night, a jack-in-the-box jumped out. Pop!'],
      ['도깨비', 'Hey, Soldier! Do not look at the dancer!'],
      ['해설', 'The next day, the soldier stood by the window.'],
      ['해설', 'Whoosh! The wind blew. He fell into the street.'],
      ['해설', 'Some children put him in a paper boat.'],
      ['해설', 'The boat went down the water. Round and round!'],
      ['병정', 'I am scared, but I will stand tall.'],
      ['쥐', 'Stop! Show me your ticket!'],
      ['해설', 'The boat went past the rat. Swish!'],
      ['해설', 'Then the boat got wet. The soldier fell in the water.'],
      ['해설', 'Gulp! A big fish ate him.'],
      ['해설', 'Later, the fish came to the same house!'],
      ['소년', 'My soldier is back! What a long trip!'],
      ['해설', 'That night, the wind blew the dancer next to the soldier.'],
      ['무희', 'Soldier, now we are always together.'],
      ['해설', 'After that, the boy always kept them side by side.'],
      ['해설', 'Be strong in hard times, and keep your friends close.'],
    ],
  },

  'an-nightingale': {
    title: 'The Nightingale',
    names: { 해설: 'Narrator', 황제: 'Emperor', 신하: 'Helper', 부엌아이: 'Kitchen Girl', 나이팅게일: 'Nightingale' },
    outro: [
      'Did you like the little bird’s song?',
      'If you were the Nightingale, would you come back to sing?',
      'What song do you like to sing?',
    ],
    lines: [
      ['해설', 'Long ago, an emperor lived in a beautiful palace.'],
      ['해설', 'In the forest, there was a small gray bird. It was a nightingale.'],
      ['해설', 'When the bird sang, everyone stopped to listen.'],
      ['황제', 'A wonderful bird in my forest? Bring it to me!'],
      ['신하', 'Yes! But where does the bird live?'],
      ['부엌아이', 'I know! It sings in the forest by the sea.'],
      ['신하', 'Oh, it is a small, plain bird.'],
      ['나이팅게일', 'I will sing for the Emperor.'],
      ['해설', 'The bird sang. The emperor cried happy tears.'],
      ['황제', 'What a beautiful song! Thank you, little bird.'],
      ['해설', 'One day, a gift came. It was a toy bird.'],
      ['해설', 'It had shiny jewels. It sang when you wound it up.'],
      ['신하', 'This bird never gets tired!'],
      ['해설', 'Everyone liked the toy bird. The nightingale flew home.'],
      ['해설', 'A year later, the toy bird broke. Snap!'],
      ['해설', 'Then the emperor got very sick.'],
      ['황제', 'It is so dark. Please, someone, sing for me.'],
      ['해설', 'The toy bird did not sing. But then, a song came!'],
      ['나이팅게일', 'I heard you were sick. So I came.'],
      ['해설', 'The bird sang. The emperor felt warm again.'],
      ['황제', 'I forgot you, but you came back. Thank you.'],
      ['나이팅게일', 'Your tears were my gift. I will come and sing again.'],
      ['해설', 'The next morning, the emperor was well.'],
      ['해설', 'Real things from the heart are better than shiny things.'],
    ],
  },

  'an-wild-swans': {
    title: 'The Wild Swans',
    names: { 해설: 'Narrator', 왕비: 'Queen', 공주: 'Princess', 첫째왕자: 'Big Brother', 요정: 'Fairy', 임금님: 'King' },
    outro: [
      'Was the story exciting?',
      'If you were the Princess, could you stay quiet for a long time?',
      'What do you do for your family?',
    ],
    lines: [
      ['해설', 'Long ago, there were eleven princes and one little princess.'],
      ['해설', 'A new queen came. She had a cold heart.'],
      ['왕비', 'Princes, turn into birds and fly away!'],
      ['해설', 'The princes became eleven white swans.'],
      ['해설', 'The princess was alone in the forest.'],
      ['공주', 'Where are my brothers? I will find them.'],
      ['해설', 'At sunset, eleven swans came to the beach.'],
      ['해설', 'When the sun went down, the swans became princes!'],
      ['첫째왕자', 'Little sister! We are swans in the day and boys at night.'],
      ['해설', 'The brothers carried her far away over the sea.'],
      ['요정', 'Make eleven shirts from prickly plants.'],
      ['요정', 'But do not say a word until you finish.'],
      ['해설', 'The plants hurt her hands. But she did not stop.'],
      ['해설', 'One day, a young king saw her in the forest.'],
      ['임금님', 'Why are you alone here? Come to my castle.'],
      ['해설', 'At the castle, she made shirts every night.'],
      ['해설', 'People thought she was a witch. She did not say a word.'],
      ['해설', 'Then eleven swans flew down. Flap, flap!'],
      ['해설', 'She threw a shirt on each swan. They became princes!'],
      ['해설', 'One shirt had no sleeve. So one brother kept one wing.'],
      ['공주', 'Now I can talk! I am not a witch.'],
      ['첫째왕자', 'Our sister made these shirts to save us.'],
      ['임금님', 'I am sorry. You are very brave.'],
      ['해설', 'Love that never gives up is very strong.'],
    ],
  },

  'an-snow-queen': {
    title: 'The Snow Queen',
    names: { 해설: 'Narrator', 카이: 'Kai', 게르다: 'Gerda', 눈의여왕: 'Snow Queen', 까마귀: 'Crow', 산적소녀: 'Robber Girl', 순록: 'Reindeer' },
    outro: [
      'Did you like Gerda’s long trip?',
      'If you were Gerda, would you go far to find your friend?',
      'Who is your best friend?',
    ],
    lines: [
      ['해설', 'Long ago, a bad mirror broke into tiny pieces.'],
      ['해설', 'Kai and Gerda were best friends. They played by the roses.'],
      ['카이', 'Ouch! Something is in my eye.'],
      ['해설', 'A piece of the mirror went into Kai’s eye and heart.'],
      ['카이', 'Roses are boring. You are boring, too!'],
      ['해설', 'One winter day, a white sled came.'],
      ['눈의여왕', 'You look cold. Get in my sled.'],
      ['해설', 'The Snow Queen took Kai far to the north.'],
      ['게르다', 'Kai is gone! I will go and find him.'],
      ['해설', 'Gerda walked and walked. She looked everywhere.'],
      ['까마귀', 'Caw! I saw a white sled go north.'],
      ['해설', 'In the forest, Gerda met a robber girl.'],
      ['산적소녀', 'You are so brave! Take my reindeer.'],
      ['순록', 'Hold on tight! Let us go north!'],
      ['해설', 'At last, they came to the ice palace.'],
      ['해설', 'Kai was there alone. He was very cold.'],
      ['게르다', 'Kai! It is me, Gerda! I found you!'],
      ['해설', 'Gerda hugged Kai. Her warm tears fell on him.'],
      ['해설', 'The ice in his heart melted away.'],
      ['해설', 'Kai cried, too. The mirror piece came out of his eye.'],
      ['카이', 'Gerda! Where am I? I want to go home.'],
      ['해설', 'They rode the reindeer home, hand in hand.'],
      ['해설', 'The roses were blooming. Welcome home!'],
      ['해설', 'Warm love can melt a cold heart.'],
    ],
  },

  'an-match-girl': {
    title: 'The Little Match Girl',
    names: { 해설: 'Narrator', 소녀: 'Girl', 행인: 'Man', 할머니: 'Grandma' },
    outro: [
      'Thank you for listening to this story.',
      'If you saw the girl in the snow, what would you do?',
      'What makes you feel warm on a cold day?',
    ],
    lines: [
      ['해설', 'It was the last night of the year. Snow was falling.'],
      ['해설', 'A little girl walked in the cold street. She had no shoes.'],
      ['소녀', 'Matches! Please buy my matches!'],
      ['행인', 'I am busy. Go away.'],
      ['해설', 'Nobody bought her matches.'],
      ['소녀', 'My hands are so cold. I will light one match.'],
      ['해설', 'Swish! A small, bright light came.'],
      ['해설', 'She saw a big, warm stove!'],
      ['소녀', 'Oh, a stove! My hands feel warm.'],
      ['해설', 'But the light went out. The stove was gone.'],
      ['해설', 'She lit a second match. Swish!'],
      ['소녀', 'I see bread and hot soup! Yummy!'],
      ['해설', 'She lit a third match. She saw a big, bright tree.'],
      ['해설', 'The lights went up and up. They became stars.'],
      ['해설', 'She lit one more match. There was her grandma!'],
      ['소녀', 'Grandma! I missed you! Please do not go.'],
      ['할머니', 'My sweet girl. You are cold. Grandma is here.'],
      ['해설', 'The girl lit all the matches. It was very bright.'],
      ['할머니', 'Now you will not be cold or hungry. Rest with me.'],
      ['소녀', 'Grandma, your hug is so warm.'],
      ['해설', 'Grandma held her. They went up into the bright stars.'],
      ['해설', 'Like a sweet dream, the girl was not cold anymore.'],
      ['해설', 'If someone is cold or hungry, be kind to them.'],
    ],
  },

  'an-little-mermaid': {
    title: 'The Little Mermaid',
    names: { 해설: 'Narrator', 할머니: 'Grandma', 인어공주: 'Little Mermaid', 마녀: 'Sea Witch', 왕자: 'Prince', 공기요정: 'Air Fairy' },
    outro: [
      'Did you like the Little Mermaid?',
      'If you were the Little Mermaid, what would you wish for?',
      'When did you wish for a friend to be happy?',
    ],
    lines: [
      ['해설', 'Deep in the blue sea, there lived six mermaid sisters.'],
      ['해설', 'The youngest one wanted to see the world above.'],
      ['할머니', 'When you are fifteen, you can go up and see.'],
      ['해설', 'On her fifteenth birthday, she swam up. Splash!'],
      ['해설', 'She saw a big ship. A young prince was on it.'],
      ['해설', 'Boom! A storm came. The prince fell into the sea.'],
      ['인어공주', 'Oh no! I will save you!'],
      ['해설', 'She swam all night and put him on the sand.'],
      ['해설', 'In the morning, a girl came. The mermaid hid.'],
      ['인어공주', 'I want to be with the prince. I want legs.'],
      ['마녀', 'I will give you legs. But give me your voice.'],
      ['마녀', 'And your feet will hurt when you walk.'],
      ['인어공주', 'That is okay. I want to see the prince.'],
      ['해설', 'Now she had legs. But she could not talk.'],
      ['왕자', 'Who are you? Come and live at my castle.'],
      ['해설', 'Her feet hurt, but she smiled and danced.'],
      ['왕자', 'I found the girl from the beach. I will marry her.'],
      ['해설', 'She wanted to say, I saved you. But she had no voice.'],
      ['해설', 'Her heart hurt. But she wished the prince to be happy.'],
      ['해설', 'In the morning, she felt light. She went up into the sky.'],
      ['공기요정', 'Welcome! We are daughters of the air.'],
      ['인어공주', 'My voice is back! I can fly!'],
      ['공기요정', 'Let us fly and bring cool wind to hot places.'],
      ['해설', 'A heart that wishes others happy grows shiny wings.'],
    ],
  },

  'pr-sleeping-beauty': {
    title: 'Sleeping Beauty',
    names: { 해설: 'Narrator', 임금님: 'King', 늙은요정: 'Old Fairy', 요정: 'Young Fairy', 공주: 'Princess', 왕자: 'Prince' },
    outro: [
      'Did you like this story?',
      'If you were the young fairy, what gift would you give?',
      'How long can you wait for something good?',
    ],
    lines: [
      ['해설', 'Long ago, a baby princess was born. Everyone was happy.'],
      ['해설', 'The king had a party. Seven good fairies came.'],
      ['해설', 'They gave her gifts. A kind heart, a sweet voice!'],
      ['해설', 'Bang! An old fairy came in. She was not asked.'],
      ['늙은요정', 'You did not ask me? Here is my gift!'],
      ['늙은요정', 'The princess will touch a needle and fall asleep forever!'],
      ['해설', 'Everyone was scared. Then the young fairy spoke.'],
      ['요정', 'Do not worry. I can change the magic.'],
      ['요정', 'She will sleep for one hundred years. A prince will wake her.'],
      ['임금님', 'Take away all the spinning wheels!'],
      ['해설', 'The princess grew up. She was kind to everyone.'],
      ['해설', 'One day, she saw an old woman spinning in a tower.'],
      ['공주', 'What is that? Can I try? Ouch!'],
      ['해설', 'She touched the needle. She fell asleep.'],
      ['요정', 'She will be lonely. Everyone, go to sleep, too.'],
      ['해설', 'The cooks, the dogs, everyone fell asleep. Zzz.'],
      ['해설', 'Big thorny bushes grew around the castle.'],
      ['해설', 'One hundred years went by. A prince came.'],
      ['왕자', 'Is there really a sleeping princess here?'],
      ['해설', 'The bushes moved away. The prince went in.'],
      ['왕자', 'Princess, wake up. One hundred years are over.'],
      ['공주', 'Oh, I slept well. I waited for you.'],
      ['해설', 'Everyone woke up. Woof, woof! The dog was happy, too.'],
      ['해설', 'Bad magic cannot beat a warm heart. Good days will come.'],
    ],
  },

  'pr-fairies': {
    title: 'The Fairy at the Well',
    names: { 해설: 'Narrator', 엄마: 'Mother', 동생: 'Younger Sister', 언니: 'Older Sister', 요정: 'Fairy', 왕자: 'Prince' },
    outro: [
      'Was the story fun?',
      'If you were the older sister, what would you say at the well?',
      'What kind words did you say today?',
    ],
    lines: [
      ['해설', 'Once upon a time, a mother had two girls.'],
      ['해설', 'The older sister was rude and lazy.'],
      ['해설', 'The younger sister was kind and hard-working.'],
      ['엄마', 'Go to the well and get some water!'],
      ['해설', 'At the well, there was an old woman.'],
      ['요정', 'I am thirsty. Can I have some water?'],
      ['동생', 'Of course! Here is some cool water.'],
      ['요정', 'You are so kind. I am a fairy.'],
      ['요정', 'When you talk, flowers and jewels will come out.'],
      ['해설', 'She went home and talked. Out came roses and jewels!'],
      ['엄마', 'Wow! Diamonds! Older girl, go to the well, too!'],
      ['언니', 'Ugh. Why do I have to get water?'],
      ['해설', 'At the well, there was a pretty lady. It was the fairy.'],
      ['요정', 'Can I have some water, please?'],
      ['언니', 'No! Get it yourself.'],
      ['요정', 'That is not nice. Now frogs will come out when you talk.'],
      ['해설', 'She went home and talked. Out came frogs and toads!'],
      ['해설', 'The mother was angry at the younger girl. She ran to the forest.'],
      ['왕자', 'Why are you crying?'],
      ['동생', 'I had to leave home. I do not know where to go.'],
      ['해설', 'When she talked, flowers and jewels fell.'],
      ['왕자', 'You have kind words and a kind heart. Come with me.'],
      ['해설', 'The older sister started to learn kind words.'],
      ['해설', 'Kind words shine like jewels. Say kind words today!'],
    ],
  },

  'pr-tom-thumb': {
    title: 'Little Thumb',
    names: { 해설: 'Narrator', 엄지: 'Little Thumb', 아빠: 'Dad', 엄마: 'Mom', 거인: 'Giant', 거인아내: 'Giant’s Wife' },
    outro: [
      'Did you enjoy Little Thumb’s adventure?',
      'If you were Little Thumb, what would you drop on the path?',
      'When were you brave?',
    ],
    lines: [
      ['해설', 'Long ago, a poor family had seven boys.'],
      ['해설', 'The youngest was very small. His name was Little Thumb.'],
      ['해설', 'He was small, but he was very smart.'],
      ['해설', 'One year, there was no food in the house.'],
      ['아빠', 'Maybe someone in the forest can feed the children.'],
      ['엄마', 'I am so sad. But we have no other way.'],
      ['해설', 'Little Thumb heard them. He picked up white stones.'],
      ['해설', 'On the way to the forest, he dropped the stones.'],
      ['해설', 'At night, his brothers cried. Mom and Dad were gone.'],
      ['엄지', 'Do not cry! Follow the stones home.'],
      ['엄마', 'You are back! I am so sorry.'],
      ['해설', 'Later, they went to the forest again. He dropped bread.'],
      ['엄지', 'Oh no! The birds ate all the bread!'],
      ['해설', 'They saw a light far away. It was a giant’s house.'],
      ['거인아내', 'A giant lives here! Hide under the bed!'],
      ['거인', 'Sniff, sniff. Who is in my house?'],
      ['해설', 'When the giant slept, the boys ran away.'],
      ['해설', 'The giant put on magic boots. They could go very far.'],
      ['거인', 'Stop, little boys!'],
      ['해설', 'The boys hid in the rocks. The tired giant fell asleep.'],
      ['엄지', 'Now! I will take these boots.'],
      ['해설', 'He worked for the king in the boots. He got money.'],
      ['엄지', 'Mom, Dad! We will not be hungry anymore!'],
      ['해설', 'Small people can be brave and smart, too.'],
    ],
  },

  'wd-ali-baba': {
    title: 'Ali Baba',
    names: { 해설: 'Narrator', 알리바바: 'Ali Baba', 카심: 'Kasim', 두목: 'Chief Thief', 모르지아나: 'Morgiana' },
    outro: [
      'Did you like the magic words?',
      'If you were Morgiana, what would you do with the marks?',
      'When did you share instead of taking all?',
    ],
    lines: [
      ['해설', 'Long ago, there lived a poor but kind man, Ali Baba.'],
      ['해설', 'His brother Kasim was rich, but he always wanted more.'],
      ['해설', 'One day, Ali Baba heard horses. Clop, clop!'],
      ['알리바바', 'Who is that? I will hide in a tree.'],
      ['해설', 'Some thieves stopped at a big rock.'],
      ['두목', 'Open, sesame!'],
      ['해설', 'The rock opened! When the thieves left, Ali Baba tried.'],
      ['알리바바', 'Open, sesame!'],
      ['해설', 'Inside, there was a lot of gold. Shiny, shiny!'],
      ['알리바바', 'The thieves took these. I will give them back.'],
      ['카심', 'A cave of gold? I want it all!'],
      ['해설', 'Kasim went in. He took many bags of gold.'],
      ['카심', 'Open, beans! Open, rice! Oh no, what is the word?'],
      ['해설', 'The rock did not open. Kasim was stuck.'],
      ['해설', 'At night, Ali Baba came and opened the rock.'],
      ['카심', 'Thank you, brother. I will not be greedy again.'],
      ['두목', 'Someone came into our cave. I will find him!'],
      ['해설', 'The chief drew a circle on Ali Baba’s door.'],
      ['모르지아나', 'A strange mark! I will draw it on every door.'],
      ['두목', 'A circle here, a circle there! Which house is it?'],
      ['모르지아나', 'Now! Guards, the thieves are here!'],
      ['해설', 'The guards caught the thieves. The gold went back.'],
      ['해설', 'Everyone said, Smart Morgiana!'],
      ['해설', 'Being greedy traps you. Being smart and brave helps everyone.'],
    ],
  },

  'wd-monkey-crocodile': {
    title: 'The Monkey and the Crocodile',
    names: { 해설: 'Narrator', 원숭이: 'Monkey', 악어: 'Crocodile', 아내악어: 'Crocodile’s Wife' },
    outro: [
      'Was the monkey smart?',
      'If you were the Monkey in the river, what would you do?',
      'What do you do when you feel scared?',
    ],
    lines: [
      ['해설', 'Long ago, a big mango tree grew by a river.'],
      ['해설', 'A monkey lived in the tree. He ate sweet mangoes.'],
      ['해설', 'One day, a crocodile swam to the tree.'],
      ['악어', 'Monkey, those mangoes look good. Can I have one?'],
      ['원숭이', 'Sure! Here you are!'],
      ['해설', 'The monkey threw mangoes. They became friends.'],
      ['해설', 'The crocodile took mangoes home to his wife.'],
      ['아내악어', 'The monkey eats sweet mangoes. His heart must be sweet, too!'],
      ['아내악어', 'Bring me the monkey’s heart!'],
      ['악어', 'What? But the monkey is my friend.'],
      ['해설', 'But the crocodile said yes to his wife.'],
      ['악어', 'Monkey, come to my house! Get on my back.'],
      ['원숭이', 'Really? Yay!'],
      ['해설', 'In the middle of the river, the crocodile stopped.'],
      ['악어', 'I am sorry. My wife wants to eat your heart.'],
      ['원숭이', 'What? Oh no. I cannot run away here.'],
      ['해설', 'The monkey was scared. But he took a deep breath.'],
      ['원숭이', 'Oh! My heart is in the mango tree. Let us go get it!'],
      ['해설', 'The crocodile swam back to the tree.'],
      ['해설', 'Jump! The monkey went up to the top of the tree.'],
      ['원숭이', 'No one keeps a heart in a tree! Goodbye!'],
      ['악어', 'I lost a good friend. I am so sorry.'],
      ['해설', 'The monkey lived happily in his tree again.'],
      ['해설', 'When you are scared, stay calm and think.'],
    ],
  },

  'wd-stone-soup': {
    title: 'Stone Soup',
    names: { 해설: 'Narrator', 나그네: 'Traveler', 할머니: 'Grandma', 농부: 'Farmer', 아이: 'Child' },
    outro: [
      'Did you like the stone soup?',
      'If you were in the village, what would you bring for the soup?',
      'What do you like to share with your family?',
    ],
    lines: [
      ['해설', 'Once upon a time, a hungry man came to a village.'],
      ['해설', 'Knock, knock! But nobody gave him food.'],
      ['할머니', 'Sorry. We have no food.'],
      ['농부', 'This year is hard. We have nothing to share.'],
      ['나그네', 'Hmm. I have a good idea.'],
      ['해설', 'He put a big pot of water in the town square.'],
      ['해설', 'Then he put in one smooth stone. Plop!'],
      ['아이', 'What are you doing?'],
      ['나그네', 'I am making the best stone soup!'],
      ['아이', 'Soup from a stone? Wow!'],
      ['해설', 'The water bubbled. People came to see.'],
      ['나그네', 'Mmm. A little salt will make it better.'],
      ['할머니', 'I have some salt. I will get it!'],
      ['나그네', 'Some carrots will make it sweet.'],
      ['농부', 'I have carrots in my field!'],
      ['아이', 'I have potatoes! I will bring them!'],
      ['해설', 'People brought onions, beans, and more. Bubble, bubble!'],
      ['나그네', 'The soup is ready! Bring your bowls!'],
      ['해설', 'Everyone sat down and ate the hot soup.'],
      ['농부', 'This is the best soup ever!'],
      ['아이', 'Is it a magic stone?'],
      ['나그네', 'No. The real magic is sharing.'],
      ['해설', 'That night, the village sang happy songs.'],
      ['해설', 'When we share a little, everyone can be happy.'],
    ],
  },

  'wd-mitten': {
    title: 'The Mitten',
    names: { 해설: 'Narrator', 할아버지: 'Grandpa', 생쥐: 'Mouse', 개구리: 'Frog', 토끼: 'Rabbit', 여우: 'Fox', 늑대: 'Wolf', 곰: 'Bear' },
    outro: [
      'Was the mitten warm and cozy?',
      'If you were in the mitten, would you let the bear in?',
      'Do you share your space with friends?',
    ],
    lines: [
      ['해설', 'On a snowy day, Grandpa walked in the forest.'],
      ['할아버지', 'Achoo! It is so cold today.'],
      ['해설', 'Oops! Grandpa dropped one mitten. He did not know.'],
      ['해설', 'A little mouse ran to the mitten.'],
      ['생쥐', 'Squeak! A soft mitten! I will live here.'],
      ['개구리', 'Ribbit! I am cold. Who lives in the mitten?'],
      ['생쥐', 'I am Mouse. Who are you?'],
      ['개구리', 'I am Frog. Can I come in?'],
      ['생쥐', 'Sure! Come in.'],
      ['토끼', 'Knock, knock! Who lives in the mitten? Can I come in?'],
      ['해설', 'Mouse and Frog moved over. Rabbit came in.'],
      ['여우', 'Sniff, sniff. It smells warm. Can I come in?'],
      ['해설', 'Fox came in, too. The mitten got bigger.'],
      ['늑대', 'Awoo! My feet are cold. Can I come in?'],
      ['토끼', 'It is small, but come in!'],
      ['해설', 'Now the mitten was like a big balloon.'],
      ['해설', 'Stomp, stomp! A big bear came.'],
      ['곰', 'I am so cold. Can I come in, too?'],
      ['여우', 'Bear, it is full!'],
      ['곰', 'Just a little bit. Please move over.'],
      ['해설', 'The bear pushed in. The mitten started to rip!'],
      ['해설', 'Woof, woof! Grandpa’s dog came. All the animals ran out!'],
      ['할아버지', 'Ha ha! My mitten was a house for animals!'],
      ['해설', 'Sharing on a cold day makes your heart warm.'],
    ],
  },

  'wd-grateful-crane': {
    title: 'The Grateful Crane',
    names: { 해설: 'Narrator', 할아버지: 'Grandpa', 할머니: 'Grandma', 아가씨: 'Young Woman' },
    outro: [
      'Did you like the crane’s story?',
      'If you were Grandpa, would you look into the room?',
      'What promise did you keep?',
    ],
    lines: [
      ['해설', 'Long ago, Grandpa and Grandma lived in the snowy hills.'],
      ['해설', 'One winter day, Grandpa saw a crane in a trap.'],
      ['할아버지', 'Oh, poor bird. I will help you.'],
      ['해설', 'Grandpa let the crane go. It flew up high.'],
      ['해설', 'That night, knock, knock! Someone was at the door.'],
      ['아가씨', 'I am lost. Can I stay here tonight?'],
      ['할머니', 'Come in! It is so cold outside.'],
      ['해설', 'The kind young woman stayed with them.'],
      ['아가씨', 'I will make cloth for you.'],
      ['아가씨', 'But never look into my room. Promise me.'],
      ['할아버지', 'Okay. We promise.'],
      ['해설', 'For three days, they heard a sound. Clack, clack.'],
      ['해설', 'The cloth was white like snow. It was so shiny.'],
      ['할머니', 'Wow! What beautiful cloth!'],
      ['해설', 'They sold the cloth and had a warm winter.'],
      ['해설', 'She made more cloth. But she looked very tired.'],
      ['할머니', 'I am worried about her. How does she make it?'],
      ['할아버지', 'We made a promise. But I want to know, too.'],
      ['해설', 'They looked into the room. There was a white crane!'],
      ['아가씨', 'I am the crane you saved. I wanted to thank you.'],
      ['아가씨', 'But you saw me. Now I must go.'],
      ['할머니', 'We are sorry. We did not keep our promise.'],
      ['아가씨', 'I was very happy here. Please stay well.'],
      ['해설', 'Always say thank you, and keep your promises.'],
    ],
  },
};
