// 영어 학습용 원고 (한국 초등 저학년, 영어 초급). 문장은 자체 각색.
// 키 = stories/*.js 의 이야기 id. lines 의 첫 칸은 원래 이야기 cast 의 한국어 이름 그대로.
export default {
  'wd-momotaro': {
    title: 'The Peach Boy',
    names: {
      해설: 'Narrator', 할머니: 'Grandma', 할아버지: 'Grandpa', 모모타로: 'Momotaro',
      강아지: 'Dog', 원숭이: 'Monkey', 꿩: 'Bird', 도깨비: 'Ogre',
    },
    outro: [
      'Did you like the peach boy?',
      'If you were Momotaro, which friend would you take with you?',
      'Who helps you when something is hard?',
    ],
    lines: [
      ['해설', 'Long ago in Japan, an old man and woman lived together.'],
      ['해설', 'One day, Grandma saw a big peach in the river.'],
      ['할머니', 'Oh my! What a big peach! I will share it with Grandpa.'],
      ['해설', 'At home, the peach opened. Crack! There was a baby boy inside!'],
      ['할아버지', 'He came from a peach. Let us call him Momotaro!'],
      ['해설', 'Momotaro grew big and strong. He was kind, too.'],
      ['해설', 'But ogres came from an island. They took the village things.'],
      ['모모타로', 'I will go to the ogre island. I will get our things back.'],
      ['할머니', 'Be careful. Take these rice cakes with you.'],
      ['강아지', 'Woof! Give me a rice cake, and I will come too!'],
      ['모모타로', 'Here you are. Let us go together!'],
      ['원숭이', 'Me too! I am good at climbing trees!'],
      ['꿩', 'Take me, too! I can look from the sky!'],
      ['해설', 'The four friends went to the island by boat.'],
      ['해설', 'The bird flew up high. The monkey opened the big gate.'],
      ['도깨비', 'Who are you? Why are you here?'],
      ['모모타로', 'Give back the village things!'],
      ['해설', 'The dog barked. The monkey tickled. The bird pecked. Peck, peck!'],
      ['도깨비', 'Stop, stop! We are sorry. Here are all your things.'],
      ['해설', 'Momotaro and his friends went home with the things.'],
      ['할아버지', 'Well done, Momotaro! You are all safe!'],
      ['해설', 'The people in the village danced. They were so happy.'],
      ['해설', 'When friends work together, hard things become easy.'],
    ],
  },

  'wd-pied-piper': {
    title: 'The Magic Pipe Man',
    names: { 해설: 'Narrator', 주민: 'Townsman', 시장: 'Mayor', 사나이: 'Piper', 아이: 'Child' },
    outro: [
      'Thank you for listening!',
      'If you were the mayor, what would you say to the piper?',
      'What promise did you keep this week?',
    ],
    lines: [
      ['해설', 'Long ago, a town in Germany had a big problem.'],
      ['해설', 'There were rats everywhere! They ate the bread and the cheese.'],
      ['주민', 'Mayor, help us! There are too many rats!'],
      ['시장', 'Oh dear. I do not know what to do.'],
      ['해설', 'Then a man came to town. He wore bright clothes and had a pipe.'],
      ['사나이', 'I can take all the rats away. Please give me a bag of gold.'],
      ['시장', 'Yes! I will give you the gold. I promise.'],
      ['해설', 'The man played his pipe. The rats came out and followed him.'],
      ['해설', 'The rats went far away. They never came back.'],
      ['사나이', 'The rats are gone. Now please give me my gold.'],
      ['시장', 'That is too much for a little song. Take only a few coins.'],
      ['사나이', 'You did not keep your promise.'],
      ['해설', 'The next morning, the man played a new song.'],
      ['해설', 'This time, the children followed him, laughing.'],
      ['아이', 'What a fun song! Let us go, too!'],
      ['해설', 'The children went to a field full of flowers in the hills.'],
      ['해설', 'The town was very quiet. The moms and dads were sad.'],
      ['주민', 'Our children are gone! It is because we broke our promise!'],
      ['시장', 'I was wrong. Here is all the gold. I am sorry.'],
      ['사나이', 'Thank you for keeping your promise. The children will come home.'],
      ['해설', 'The man played his pipe. The children came back in a line.'],
      ['아이', 'Mom, Dad! We played in a pretty flower field!'],
      ['해설', 'Everyone hugged the children. They were so happy.'],
      ['해설', 'Keep your promise, and people will trust you.'],
    ],
  },

  'wd-aladdin': {
    title: 'The Boy and the Magic Lamp',
    names: {
      해설: 'Narrator', 알라딘: 'Aladdin', 마법사: 'Bad Wizard', 거인: 'Lamp Giant',
      어머니: 'Mother', 공주: 'Princess',
    },
    outro: [
      'Was the magic lamp fun?',
      'If you had a magic lamp, what would you wish for?',
      'When were you brave and smart?',
    ],
    lines: [
      ['해설', 'Long ago, a poor boy named Aladdin lived with his mother.'],
      ['해설', 'One day, a strange wizard came to see him.'],
      ['마법사', 'Boy, there is an old lamp in that cave. Get it for me.'],
      ['해설', 'The wizard gave Aladdin a ring. Aladdin went into the cave.'],
      ['해설', 'The cave was full of shiny jewels.'],
      ['알라딘', 'I found the lamp! Please help me out first.'],
      ['마법사', 'No! Give me the lamp first!'],
      ['해설', 'Aladdin did not give it. So the wizard closed the cave. Bang!'],
      ['해설', 'Aladdin rubbed the ring. A little helper came and took him home.'],
      ['해설', 'At home, Mother rubbed the old lamp. Poof! A big giant came out!'],
      ['거인', 'Master of the lamp, what do you wish?'],
      ['어머니', 'Oh my! What is this?'],
      ['알라딘', 'Giant, we are hungry. Please give us warm food.'],
      ['해설', 'In a moment, there was yummy food on the table.'],
      ['해설', 'Later, Aladdin married a princess. They lived in a shiny palace.'],
      ['마법사', 'New lamps for old lamps! Give me your old lamp!'],
      ['공주', 'A new lamp? Here is our old one.'],
      ['해설', 'The wizard rubbed the lamp. Whoosh! The palace flew far away.'],
      ['알라딘', 'Ring, please take me to the princess!'],
      ['해설', 'The wizard fell asleep. Aladdin and the princess took the lamp back.'],
      ['알라딘', 'Giant, bring the palace home! Send the wizard far away!'],
      ['공주', 'Aladdin, I knew you would come!'],
      ['해설', 'Aladdin used the lamp wisely. He was never greedy.'],
      ['해설', 'Being smart and brave is better than being greedy.'],
    ],
  },

  'wd-anansi-stories': {
    title: 'Anansi and the Story Box',
    names: {
      해설: 'Narrator', 아난시: 'Anansi', 하늘신: 'Sky God', 비단뱀: 'Snake',
      말벌: 'Wasps', 표범: 'Leopard',
    },
    outro: [
      'Hello, story friend! Did you like it?',
      'If you were Anansi, how would you catch the snake?',
      'What is your favorite story?',
    ],
    lines: [
      ['해설', 'Long ago, all the stories were in a box in the sky.'],
      ['해설', 'There were no stories on the ground. The nights were boring.'],
      ['아난시', 'I will get the stories! I will climb up my web.'],
      ['해설', 'Anansi was a little spider. He climbed up to the sky.'],
      ['아난시', 'Sky God, can I have the story box?'],
      ['하늘신', 'Bring me a snake, some wasps, and a leopard.'],
      ['아난시', 'I am small, but I am smart. I will try!'],
      ['해설', 'First, Anansi took a long stick to the snake.'],
      ['아난시', 'Who is longer, you or this stick?'],
      ['비단뱀', 'I am longer, of course! Look at me!'],
      ['해설', 'The snake lay next to the stick. Anansi tied him up. Got you!'],
      ['해설', 'Next came the wasps. Anansi splashed water on their home.'],
      ['아난시', 'It is raining! Come into my pot!'],
      ['말벌', 'Buzz, buzz! Thank you!'],
      ['해설', 'The wasps flew in. Anansi closed the pot.'],
      ['해설', 'Last was the leopard. Anansi dug a hole. Thump! In fell the leopard.'],
      ['표범', 'Grr! Help me out!'],
      ['해설', 'Anansi gave him a web rope. The leopard got stuck in the web.'],
      ['하늘신', 'Little Anansi, you did it! The box is yours.'],
      ['해설', 'The snake, the wasps, and the leopard went home to the forest.'],
      ['해설', 'Anansi opened the box. The stories flew all over the world.'],
      ['해설', 'Even if you are small, you can do big things. Think and try!'],
    ],
  },

  'wd-tortoise-swans': {
    title: 'The Tortoise Who Flew',
    names: { 해설: 'Narrator', 거북이: 'Tortoise', 큰백조: 'Big Swan', 작은백조: 'Little Swan', 아이: 'Child' },
    outro: [
      'Hi there! Did you enjoy the flying tortoise?',
      'If you were the Tortoise, could you keep your mouth closed?',
      'When is it hard for you to be quiet?',
    ],
    lines: [
      ['해설', 'Long ago in India, a tortoise lived in a pond.'],
      ['해설', 'The tortoise loved to talk. Two swans were his friends.'],
      ['해설', 'One year, there was no rain. The pond got smaller and smaller.'],
      ['큰백조', 'Tortoise, there is a big lake over the hill.'],
      ['작은백조', 'We can fly there. But what about you?'],
      ['거북이', 'I cannot fly. Please do not leave me!'],
      ['큰백조', 'Bite the middle of this stick. We will hold the ends.'],
      ['큰백조', 'But promise me. Do not open your mouth!'],
      ['거북이', 'Okay, okay! I will keep my mouth closed.'],
      ['해설', 'The swans flew up high. The tortoise flew, too!'],
      ['아이', 'Look! A tortoise is flying!'],
      ['아이', 'Ha ha! That is so funny!'],
      ['해설', 'The tortoise wanted to talk back. Just one word!'],
      ['큰백조', 'Tortoise, wait! We are almost there!'],
      ['거북이', 'What is so funny? I am...'],
      ['해설', 'He opened his mouth. Down, down he fell. Splash!'],
      ['해설', 'He fell into soft mud. His hard shell kept him safe.'],
      ['작은백조', 'Tortoise, are you okay?'],
      ['거북이', 'I am okay. I am sorry I did not keep my promise.'],
      ['큰백조', 'That is okay. Let us try again.'],
      ['해설', 'This time, the tortoise kept his mouth closed all the way.'],
      ['거북이', 'We are here! Can I talk now?'],
      ['해설', 'Sometimes we need to stay quiet. It keeps us and our friends safe.'],
    ],
  },

  'wd-billy-goats': {
    title: 'Three Goats and the Troll',
    names: { 해설: 'Narrator', 작은염소: 'Little Goat', 둘째염소: 'Middle Goat', 큰염소: 'Big Goat', 트롤: 'Troll' },
    outro: [
      'Trip, trap! Was the story fun?',
      'If you were the Little Goat, what would you say to the Troll?',
      'Who helps you when you feel scared?',
    ],
    lines: [
      ['해설', 'Once upon a time, there were three goat brothers.'],
      ['해설', 'A little goat, a middle goat, and a very big goat.'],
      ['해설', 'Over the river, there was a hill with sweet grass.'],
      ['해설', 'But a grumpy troll lived under the bridge.'],
      ['작은염소', 'Let us go eat grass! I will go first.'],
      ['해설', 'The little goat walked on the bridge. Trip, trap, trip, trap.'],
      ['트롤', 'Who is walking on my bridge?'],
      ['작은염소', 'It is me, the little goat. I am going to eat grass.'],
      ['트롤', 'I will chase you off my bridge!'],
      ['작은염소', 'I am too small. My bigger brother is coming soon.'],
      ['트롤', 'Oh? Then go on.'],
      ['해설', 'Then the middle goat walked on the bridge. Trip, trap!'],
      ['트롤', 'Who is walking on my bridge?'],
      ['둘째염소', 'It is me, the middle goat. My big brother is much bigger.'],
      ['트롤', 'Oh? Then go on.'],
      ['해설', 'Last came the big goat. Stomp, stomp, stomp!'],
      ['트롤', 'Who is walking on my bridge?'],
      ['큰염소', 'It is me, the big goat! Do not be mean to my brothers!'],
      ['해설', 'The big goat ran at the troll. Bump! The troll flew up high.'],
      ['해설', 'Splash! The troll fell into the river.'],
      ['트롤', 'Brr, it is cold! I will never come back!'],
      ['해설', 'The troll swam far away. The goats ate lots of grass.'],
      ['해설', 'Help each other and be brave. Then bullies cannot win.'],
    ],
  },

  'gs-saeong': {
    title: 'The Old Man and His Horse',
    names: { 해설: 'Narrator', 할아버지: 'Old Man', 아들: 'Son', 이웃: 'Neighbor' },
    outro: [
      'Good job listening!',
      'If you were the old man, how would you feel about the horse?',
      'Did something bad ever turn into something good for you?',
    ],
    lines: [
      ['해설', 'Long ago, an old man lived in a village far away.'],
      ['해설', 'He had a horse. He loved his horse very much.'],
      ['해설', 'One day, the horse ran away.'],
      ['이웃', 'Oh no! Your horse ran away! That is bad!'],
      ['할아버지', 'Maybe. Who knows? It may be good.'],
      ['해설', 'A few months later, the horse came back.'],
      ['해설', 'And it brought a new, strong horse with it!'],
      ['이웃', 'Wow! Now you have two horses! That is good!'],
      ['할아버지', 'Maybe. Who knows? It may be bad.'],
      ['아들', 'Father, I will ride the new horse!'],
      ['해설', 'One day, the son fell off the horse. He hurt his leg.'],
      ['아들', 'Ouch! My leg hurts. I cannot walk.'],
      ['이웃', 'Oh no! Your son is hurt! That is bad!'],
      ['할아버지', 'Maybe. Who knows? It may be good.'],
      ['해설', 'Soon, there was a big fight in the country.'],
      ['해설', 'All the young men had to go far away to fight.'],
      ['해설', 'But the son had a hurt leg. So he stayed home.'],
      ['아들', 'Father, now I can stay with you.'],
      ['할아버지', 'Yes, my son. We are together.'],
      ['이웃', 'You were right! Nobody knows what will happen!'],
      ['해설', 'In old China, people made a saying from this story.'],
      ['해설', 'Good things and bad things can change places.'],
      ['해설', 'So do not be too sad. And do not be too proud.'],
    ],
  },

  'gs-ugong': {
    title: 'The Man Who Moved Mountains',
    names: { 해설: 'Narrator', 우공: 'Grandpa Yu', 손자: 'Grandson', 이웃: 'Neighbor', 산신령: 'Mountain Spirit' },
    outro: [
      'Hello, little helper! Did you like it?',
      'If you were the grandson, would you help Grandpa Yu?',
      'What do you practice a little every day?',
    ],
    lines: [
      ['해설', 'Long ago, there was a very old man. His name was Grandpa Yu.'],
      ['해설', 'Two big mountains stood in front of his house.'],
      ['해설', 'To go to the market, he had to walk all day.'],
      ['우공', 'Let us move the mountains. Then we can make a road.'],
      ['손자', 'Okay, Grandpa! I will help, too!'],
      ['해설', 'The whole family dug and carried rocks and dirt.'],
      ['해설', 'They took the dirt far away to the sea.'],
      ['이웃', 'Ha ha! You are so old. You cannot move a mountain!'],
      ['우공', 'If I cannot finish, my son will help.'],
      ['우공', 'Then my grandson will help. Then his children will help.'],
      ['우공', 'Mountains do not grow. One day, they will be gone.'],
      ['이웃', 'Hmm. I have nothing to say.'],
      ['해설', 'Every day, the family moved dirt. They did not stop.'],
      ['손자', 'Grandpa, I moved one basket today!'],
      ['우공', 'Good job! One basket at a time can move a mountain.'],
      ['산신령', 'Oh no! This family will never stop!'],
      ['해설', 'The mountain spirit told the King of the Sky.'],
      ['해설', 'The King of the Sky was moved by Grandpa Yu.'],
      ['해설', 'He sent two giants. They lifted the mountains and took them away.'],
      ['손자', 'Wow, Grandpa! The mountains are gone! We have a road!'],
      ['우공', 'I am glad we did not give up.'],
      ['해설', 'In old China, people made a saying from this story.'],
      ['해설', 'If you keep trying, you can do hard things.'],
    ],
  },

  'gs-sujudaeto': {
    title: 'Waiting for a Rabbit',
    names: { 해설: 'Narrator', 농부: 'Farmer', 아내: 'Wife', 마을사람: 'Villager' },
    outro: [
      'Did you like the silly farmer?',
      'If you were the farmer, what would you do the next day?',
      'What do you work hard on every day?',
    ],
    lines: [
      ['해설', 'Long ago in China, there was a farmer.'],
      ['해설', 'Every day, he worked hard in his field.'],
      ['해설', 'In the field, there was an old tree stump.'],
      ['해설', 'One day, a rabbit ran fast. Bump! It hit the stump and fell down.'],
      ['농부', 'Wow! A rabbit came to me all by itself!'],
      ['해설', 'But the rabbit woke up and ran away.'],
      ['농부', 'Oh, it ran away. That is okay. Another one will come.'],
      ['농부', 'I can just sit and wait for rabbits!'],
      ['해설', 'The next day, the farmer did not work.'],
      ['해설', 'He sat by the stump all day. He waited and waited.'],
      ['아내', 'Dear, are you not going to work? The weeds are growing!'],
      ['농부', 'Shh! A rabbit may come. Just wait.'],
      ['해설', 'One day, two days, ten days went by.'],
      ['해설', 'No rabbit came. Not even one.'],
      ['농부', 'That is strange. Maybe today? Maybe tomorrow?'],
      ['해설', 'Weeds grew tall in the field. The plants got dry and brown.'],
      ['마을사람', 'Ha ha! Look at him! He is waiting for a rabbit!'],
      ['아내', 'Dear, that rabbit came only once. Rabbits do not come every day.'],
      ['농부', 'You are right. I was silly. I will work again tomorrow.'],
      ['해설', 'The farmer worked hard again. In fall, he got a little food.'],
      ['해설', 'In old China, people made a saying from this story.'],
      ['해설', 'It means waiting for good luck and not working.'],
      ['해설', 'Good luck does not come every day. Keep working hard.'],
    ],
  },

  'gs-osip': {
    title: 'Fifty Steps, One Hundred Steps',
    names: { 해설: 'Narrator', 동이: 'Dongi', 순이: 'Suni', 선생님: 'Teacher' },
    outro: [
      'Ready, set, go! Did you like the race?',
      'If you were Suni, what would you say to Dongi?',
      'What do you want to finish all the way?',
    ],
    lines: [
      ['해설', 'Long ago, there was a running race in a village.'],
      ['해설', 'The children had to run to the big tree.'],
      ['선생님', 'Run all the way to the end. Ready, set, go!'],
      ['해설', 'Dongi and Suni ran fast, too.'],
      ['순이', 'Huff, puff. I am so tired.'],
      ['해설', 'Suni ran fifty steps. Then she sat down.'],
      ['동이', 'Huff, puff. I will stop, too.'],
      ['해설', 'Dongi ran one hundred steps. Then he stopped.'],
      ['해설', 'The other children ran all the way to the big tree.'],
      ['동이', 'Ha ha, Suni! You ran only fifty steps!'],
      ['순이', 'What? You stopped, too!'],
      ['동이', 'But I ran one hundred steps. That is more than you!'],
      ['순이', 'But you did not get to the big tree, too!'],
      ['해설', 'Their faces got red. They fought and fought.'],
      ['선생님', 'Dongi, Suni ran fifty steps. You ran one hundred steps.'],
      ['선생님', 'But you both stopped. Is that not the same?'],
      ['동이', 'Oh, you are right. I stopped, too.'],
      ['순이', 'Yes. We both did not finish.'],
      ['동이', 'Suni, I am sorry I laughed at you.'],
      ['순이', 'That is okay. Next time, let us run to the end together!'],
      ['해설', 'In old China, people made a saying from this story.'],
      ['해설', 'It means a small difference is really the same.'],
      ['해설', 'Before you laugh at others, look at yourself first.'],
    ],
  },

  'gs-eobuji': {
    title: 'The Bird and the Clam',
    names: { 해설: 'Narrator', 조개: 'Clam', 도요새: 'Bird', 어부: 'Fisherman' },
    outro: [
      'Hello again! Was the story fun?',
      'If you were the Clam, what would you do?',
      'How do you stop a fight with a friend?',
    ],
    lines: [
      ['해설', 'On a warm spring day, a clam was on the sand. Its shell was open.'],
      ['조개', 'Ah, the sun is warm. It is a good time for a nap.'],
      ['해설', 'Then a bird came walking by.'],
      ['도요새', 'Yummy! A clam! I will peck it.'],
      ['해설', 'The bird put in its long beak. Snap! The clam closed its shell.'],
      ['도요새', 'Ouch! My beak! Let me go!'],
      ['조개', 'No! You pecked me first. I will not let go!'],
      ['도요새', 'If there is no rain, you will dry up!'],
      ['조개', 'If you cannot get out, you will get hungry!'],
      ['도요새', 'Let go first!'],
      ['조개', 'No! You say sorry first!'],
      ['해설', 'They pulled and pulled until the sun went down.'],
      ['해설', 'Then a fisherman came by with his net.'],
      ['어부', 'Ha ha! A clam and a bird, both at once!'],
      ['해설', 'The fisherman picked them up and put them in his basket.'],
      ['조개', 'Oh no! Now we are both in trouble!'],
      ['도요새', 'We were fighting. We forgot to run away.'],
      ['해설', 'The clam opened its shell. The bird got its beak out.'],
      ['어부', 'You fought, so I got you both so easily.'],
      ['어부', 'I will let you go this time. Do not fight like this again.'],
      ['도요새', 'Clam, I am sorry. Let us not fight.'],
      ['조개', 'I am sorry, too. Let us be friends.'],
      ['해설', 'In old China, people made a saying from this story.'],
      ['해설', 'When two fight, a third one gets the prize.'],
    ],
  },

  'gs-josam': {
    title: 'Three in the Morning',
    names: { 해설: 'Narrator', 저공: 'Grandpa Ju', 대장원숭이: 'Big Monkey', 꼬마원숭이: 'Little Monkey' },
    outro: [
      'Let us count together! Did you like it?',
      'If you were the monkeys, would you want three or four in the morning?',
      'What do you like to count?',
    ],
    lines: [
      ['해설', 'Long ago in China, Grandpa Ju loved monkeys very much.'],
      ['해설', 'Many monkeys lived in his yard. They loved to eat nuts.'],
      ['해설', 'But one year, there were not many nuts.'],
      ['저공', 'Oh dear. We do not have enough nuts.'],
      ['저공', 'Monkeys, I will give you three in the morning. And four at night.'],
      ['대장원숭이', 'Only three in the morning? No, no, no!'],
      ['꼬마원숭이', 'We are hungry in the morning! We want to play!'],
      ['해설', 'The monkeys jumped and shouted.'],
      ['해설', 'Grandpa Ju thought and thought.'],
      ['저공', 'Okay. Four in the morning, and three at night.'],
      ['대장원숭이', 'Four in the morning! That is one more!'],
      ['꼬마원숭이', 'Yay! Grandpa Ju is the best!'],
      ['해설', 'The monkeys clapped. Clap, clap!'],
      ['해설', 'But let us count. Three and four make seven.'],
      ['해설', 'Four and three make seven, too. It is the same!'],
      ['꼬마원숭이', 'Big Monkey, how many nuts do we get in one day?'],
      ['대장원숭이', 'One, two, three... Oh! It is seven.'],
      ['꼬마원숭이', 'It was seven before, too!'],
      ['대장원숭이', 'Oh my. We made a fuss for nothing.'],
      ['저공', 'Ha ha. You are happy, so I am happy, too.'],
      ['해설', 'In old China, people made a saying from this story.'],
      ['해설', 'It means a small change fools us, but it is the same.'],
      ['해설', 'Do not just look. Count and think carefully.'],
    ],
  },

  'gs-jeongjeo': {
    title: 'The Frog in the Well',
    names: { 해설: 'Narrator', 개구리: 'Frog', 거북이: 'Sea Turtle' },
    outro: [
      'Ribbit, ribbit! Did you like the frog?',
      'If you were the Frog, what would you want to see first?',
      'What new place do you want to visit?',
    ],
    lines: [
      ['해설', 'Once upon a time, a frog lived in an old well.'],
      ['해설', 'The frog never went out of the well.'],
      ['개구리', 'Ribbit! My well is the best place in the world!'],
      ['개구리', 'I swim in the water. I sleep between the rocks.'],
      ['개구리', 'That round sky is mine, too. I am so happy!'],
      ['해설', 'One day, a sea turtle walked by the well.'],
      ['개구리', 'Hello, Turtle! Come and see my great home!'],
      ['거북이', 'Okay. Let me try.'],
      ['해설', 'The turtle put one foot in. But he got stuck.'],
      ['거북이', 'Oh, your well is too small for me.'],
      ['개구리', 'What? Is there a bigger place than this?'],
      ['거북이', 'Yes! I live in the big sea. Let me tell you.'],
      ['거북이', 'The sea is very, very big. You cannot see the end.'],
      ['거북이', 'It is very deep, too. You cannot see the bottom.'],
      ['해설', 'The frog could almost hear the waves. Swish, swish.'],
      ['개구리', 'Wow! Is there really a place like that?'],
      ['개구리', 'I thought my little sky was everything.'],
      ['거북이', 'That is okay. Now you know. You can go and see more.'],
      ['개구리', 'Turtle, one day I will go and see the sea!'],
      ['해설', 'The frog looked up at the sky. He had a big dream.'],
      ['해설', 'In old China, people made a saying from this story.'],
      ['해설', 'A frog in a well knows only a small world.'],
      ['해설', 'The world is very big. Be curious and learn more!'],
    ],
  },

  'gs-hwasa': {
    title: 'A Snake with Feet',
    names: { 해설: 'Narrator', 주인: 'Master', 돌쇠: 'Dolsoe', 복남이: 'Boknam' },
    outro: [
      'Hello, artist! Did you like the story?',
      'If you were Dolsoe, would you draw feet on the snake?',
      'What do you like to draw?',
    ],
    lines: [
      ['해설', 'Long ago in China, some workers helped at a big house.'],
      ['주인', 'Thank you for your work. Here is some honey water.'],
      ['해설', 'But there was only a little honey water.'],
      ['복남이', 'If we all share, we get only one sip.'],
      ['돌쇠', 'Let us have a contest! Draw a snake on the ground.'],
      ['돌쇠', 'The first one to finish gets all the honey water!'],
      ['복남이', 'Okay! Ready, go!'],
      ['해설', 'They drew snakes with sticks. Scratch, scratch.'],
      ['해설', 'Dolsoe was very fast. He finished first.'],
      ['돌쇠', 'I am first! The honey water is mine!'],
      ['해설', 'Dolsoe held the honey water. He looked around.'],
      ['돌쇠', 'They are so slow. I have time. I will draw feet, too!'],
      ['해설', 'He drew one, two, three, four feet on the snake.'],
      ['돌쇠', 'Look! A great snake with feet!'],
      ['해설', 'Just then, Boknam finished his snake.'],
      ['복남이', 'I am done! The honey water is mine!'],
      ['돌쇠', 'What? I finished first!'],
      ['복남이', 'Dolsoe, does a snake have feet?'],
      ['돌쇠', 'Um... No. Snakes do not have feet.'],
      ['복남이', 'A snake with feet is not a snake. So I am first.'],
      ['해설', 'Boknam drank the honey water. Gulp, gulp! Yum!'],
      ['돌쇠', 'Oh no. I should not have drawn the feet.'],
      ['해설', 'In old China, people made a saying from this story.'],
      ['해설', 'Adding too much can spoil a good thing. When it is done, stop.'],
    ],
  },

  'gs-gakju': {
    title: 'The Mark on the Boat',
    names: { 해설: 'Narrator', 선비: 'Scholar', 뱃사공: 'Boatman', 아이: 'Child' },
    outro: [
      'Splash! Did you enjoy the story?',
      'If you were the scholar, how would you find the sword?',
      'What do you do when your plan does not work?',
    ],
    lines: [
      ['해설', 'Long ago in China, a man was crossing a river by boat.'],
      ['해설', 'He had a sword. He loved his sword very much.'],
      ['선비', 'The water is so clear. Let me look.'],
      ['해설', 'He leaned over. Splash! His sword fell into the river!'],
      ['선비', 'Oh no! My sword! My dear sword!'],
      ['해설', 'Quickly, he made a mark on the side of the boat.'],
      ['선비', 'There! I made a mark. Now I will not forget the place.'],
      ['아이', 'Sir, why did you make a mark on the boat?'],
      ['선비', 'My sword fell here. I will look for it here later.'],
      ['해설', 'The boat kept going across the river.'],
      ['해설', 'At last, the boat got to the other side.'],
      ['선비', 'Now, let me find my sword. Here is my mark.'],
      ['해설', 'He jumped into the water under the mark.'],
      ['해설', 'He looked and looked. But there was no sword.'],
      ['선비', 'That is strange. I made a mark right here!'],
      ['아이', 'Ha ha! Sir, the boat moved!'],
      ['뱃사공', 'Your sword is still in the middle of the river.'],
      ['뱃사공', 'The boat moved, so your mark moved, too.'],
      ['선비', 'Oh, I see. I did not think about that.'],
      ['아이', 'Next time, look at a tree by the river!'],
      ['선비', 'Yes. You are smarter than me.'],
      ['해설', 'In old China, people made a saying from this story.'],
      ['해설', 'It means doing the old way when things have changed.'],
      ['해설', 'When things change, change your thinking, too.'],
    ],
  },

  'gs-hoga': {
    title: 'The Fox and the Tiger',
    names: { 해설: 'Narrator', 여우: 'Fox', 호랑이: 'Tiger', 토끼: 'Rabbit' },
    outro: [
      'Roar! Did you like the story?',
      'If you were the Tiger, would you believe the Fox?',
      'What can you do well all by yourself?',
    ],
    lines: [
      ['해설', 'Long ago, a big tiger lived deep in the mountains.'],
      ['해설', 'One day, the tiger caught a fox.'],
      ['호랑이', 'Roar! I got you, little fox!'],
      ['해설', 'The fox was scared. But he had a smart idea.'],
      ['여우', 'Wait! You cannot hurt me.'],
      ['호랑이', 'What? You are so small!'],
      ['여우', 'The Sky King made me king of all animals.'],
      ['여우', 'If you hurt me, the Sky King will be very angry.'],
      ['호랑이', 'Hmm. How can I believe you?'],
      ['여우', 'Walk behind me. All the animals will run away from me.'],
      ['해설', 'The fox walked in front. The tiger walked behind him.'],
      ['해설', 'A rabbit was playing in the grass. It saw them.'],
      ['토끼', 'Oh no! Run!'],
      ['해설', 'The rabbit ran. The deer ran. The birds flew away.'],
      ['여우', 'See? Everyone is scared of me!'],
      ['호랑이', 'You are right. You really are the king.'],
      ['해설', 'The tiger let the fox go. He walked away slowly.'],
      ['토끼', 'Silly tiger! We were scared of the tiger, not the fox.'],
      ['해설', 'Yes. The animals ran away from the tiger behind the fox.'],
      ['해설', 'The fox used the tiger to look strong.'],
      ['해설', 'In old China, people made a saying from this story.'],
      ['해설', 'It means showing off with someone else’s power.'],
      ['해설', 'Do not show off with others’ power. Be strong in your own way.'],
    ],
  },

  'gs-maengmo': {
    title: 'A Mother Moves Three Times',
    names: { 해설: 'Narrator', 어머니: 'Mother', 맹자: 'Mengzi', 이웃: 'Neighbor' },
    outro: [
      'Hello, good friend! Did you like the story?',
      'If you were Mengzi’s mother, where would you live?',
      'What good things do you learn from your friends?',
    ],
    lines: [
      ['해설', 'Long ago in China, a boy named Mengzi lived with his mother.'],
      ['해설', 'Mengzi copied everything he saw.'],
      ['해설', 'First, they lived near a place where people were buried.'],
      ['해설', 'Mengzi saw people cry and bow there every day.'],
      ['맹자', 'Boo hoo. Bow, bow.'],
      ['해설', 'Mengzi played crying and bowing all day.'],
      ['어머니', 'Oh dear. This is not a good place for my boy.'],
      ['해설', 'So they moved near a busy market.'],
      ['이웃', 'Fresh fish! Buy my fish! Very cheap!'],
      ['맹자', 'Buy, buy! My things are the best!'],
      ['해설', 'Now Mengzi played selling things all day.'],
      ['어머니', 'Oh dear. This is not a good place for my boy, too.'],
      ['해설', 'So they moved again. This time, they lived next to a school.'],
      ['해설', 'The children read books. They said hello politely.'],
      ['맹자', 'Good morning, teacher!'],
      ['해설', 'Mengzi opened a book and read, too.'],
      ['해설', 'He bowed nicely to grown-ups.'],
      ['이웃', 'That boy is so good and polite!'],
      ['어머니', 'This is the right place for my boy!'],
      ['해설', 'Mengzi learned a lot there. Later, he became a great teacher.'],
      ['해설', 'In old China, people made a saying from this story.'],
      ['해설', 'It means the place around a child is very important.'],
      ['해설', 'With good friends and good places, we learn good things.'],
    ],
  },
};
