// 영어 학습용 원고 (한국 초등 저학년, 영어 초급). 문장은 자체 각색.
// 키 = stories/classics.js 의 이야기 id. lines 의 첫 칸은 원래 이야기 cast 의 한국어 이름 그대로.
export default {
  'cl-happy-prince': {
    title: 'The Happy Prince',
    names: { 해설: 'Narrator', 왕자: 'Prince', 제비: 'Swallow', 아이: 'Child' },
    outro: [
      'Thank you for listening to the end.',
      'If you were the Swallow, would you stay with the Prince?',
      'What would you like to share with a friend?',
    ],
    lines: [
      ['해설', 'Long ago, a statue stood high above a town.'],
      ['해설', 'It was the Happy Prince. He was all gold.'],
      ['해설', 'His eyes were blue jewels. His sword had a red ruby.'],
      ['해설', 'One cold night, a little swallow sat at his feet.'],
      ['제비', 'Drip, drip. Is it raining? No, the Prince is crying!'],
      ['왕자', 'I see many sad people from up here.'],
      ['왕자', 'A little child is sick. His mother has no money.'],
      ['왕자', 'Please take my ruby to them, little Swallow.'],
      ['제비', 'My friends are waiting. But okay, just one night.'],
      ['해설', 'The swallow flew and put the ruby by the child.'],
      ['아이', 'Mom, I feel better. I heard little wings!'],
      ['제비', 'It is cold, but my heart is warm.'],
      ['왕자', 'That is because you did a kind thing.'],
      ['해설', 'Then the Prince gave his blue eyes to poor people.'],
      ['제비', 'Now you cannot see. I will stay with you.'],
      ['왕자', 'Thank you. Please give my gold to hungry children.'],
      ['해설', 'Piece by piece, the gold went away. The children smiled.'],
      ['해설', 'Then the snow came. The swallow was very cold.'],
      ['제비', 'Dear Prince, I want to rest now.'],
      ['왕자', 'Rest by me, my kind friend.'],
      ['해설', 'The swallow curled up at his feet and fell asleep.'],
      ['해설', 'An angel came and gently carried them up to the sky.'],
      ['해설', 'Now they sing together in a happy garden.'],
      ['해설', 'Sharing what you have is the best treasure of all.'],
    ],
  },

  'cl-selfish-giant': {
    title: 'The Selfish Giant',
    names: { 해설: 'Narrator', 거인: 'Giant', 아이: 'Children', 꼬마: 'Little Boy' },
    outro: [
      'Did you like the story?',
      'If you were the Giant, when would you break the wall?',
      'What place is more fun when you share it with friends?',
    ],
    lines: [
      ['해설', 'There was a big, beautiful garden full of flowers.'],
      ['해설', 'Every day, children came to play there.'],
      ['아이', 'Listen to the birds! Let’s play tag!'],
      ['해설', 'The garden belonged to a very big giant.'],
      ['거인', 'This is my garden! Go away, all of you!'],
      ['해설', 'The giant built a tall wall around his garden.'],
      ['해설', 'Spring came to the town. Flowers came out everywhere.'],
      ['해설', 'But in the giant’s garden, it was still winter.'],
      ['거인', 'Why is it always cold in my garden?'],
      ['해설', 'One morning, the giant heard birds singing.'],
      ['해설', 'The children came in through a little hole.'],
      ['해설', 'They sat in the trees, and the trees bloomed.'],
      ['꼬마', 'I want to climb, too. But I am too small.'],
      ['거인', 'Oh, I was so selfish. I will help him.'],
      ['해설', 'The giant gently lifted the boy into the tree.'],
      ['해설', 'The tree bloomed, and the boy kissed the giant.'],
      ['거인', 'Children, this is your garden now. Come and play!'],
      ['해설', 'The giant took down the wall. Every year, children played there.'],
      ['해설', 'Many years later, the giant was old and gray.'],
      ['꼬마', 'Thank you, Grandpa Giant. Now you can rest here.'],
      ['해설', 'The giant smiled and rested under the white blossoms.'],
      ['해설', 'When you share, spring comes to your heart, too.'],
    ],
  },

  'cl-what-men-live-by': {
    title: 'What People Live By',
    names: { 해설: 'Narrator', 세몬: 'Simon', 아내: 'Wife', 미하일: 'Michael', 신사: 'Rich Man', 부인: 'Lady' },
    outro: [
      'Thank you for listening so well.',
      'If you were Simon, would you give your coat to a stranger?',
      'When did someone’s kindness make you smile?',
    ],
    lines: [
      ['해설', 'Long ago, a poor shoemaker named Simon lived in Russia.'],
      ['해설', 'One snowy day, he saw a cold man by the road.'],
      ['세몬', 'You have no clothes! Here, take my coat.'],
      ['해설', 'Simon took the man home. His wife was not happy.'],
      ['아내', 'We do not have enough bread for us!'],
      ['세몬', 'He is hungry, too. Let’s share a little.'],
      ['해설', 'The wife gave him warm soup. The man smiled.'],
      ['미하일', 'Thank you. My name is Michael.'],
      ['해설', 'Michael learned to make shoes. He was very good.'],
      ['신사', 'Make me strong boots! They must last one year!'],
      ['해설', 'But Michael made soft slippers, not boots.'],
      ['세몬', 'Michael, why slippers? He wanted boots!'],
      ['해설', 'Soon a helper came. The rich man had a bad fall.'],
      ['해설', 'He had to stay in bed, so he needed slippers. Michael smiled again.'],
      ['해설', 'Years later, a lady came with twin girls.'],
      ['부인', 'They had no mom or dad. So I took care of them.'],
      ['부인', 'They are not my children, but I love them so much.'],
      ['해설', 'Michael smiled a third time. He began to shine.'],
      ['미하일', 'I am an angel. I had to learn three things.'],
      ['미하일', 'There is love in people’s hearts.'],
      ['미하일', 'People do not know what tomorrow brings.'],
      ['미하일', 'And people live by love for one another.'],
      ['해설', 'Then Michael flew away into the bright light.'],
      ['해설', 'We live by loving and caring for each other.'],
    ],
  },

  'cl-ivan-fool': {
    title: 'Ivan the Fool',
    names: { 해설: 'Narrator', 이반: 'Ivan', 첫째: 'Big Brother', 둘째: 'Second Brother', 꼬마악마: 'Little Imp', 늙은악마: 'Old Imp' },
    outro: [
      'Was the story fun?',
      'If you were Ivan, would you share with your brothers?',
      'What hard work made you feel proud?',
    ],
    lines: [
      ['해설', 'Long ago, there were three brothers.'],
      ['해설', 'People called the youngest one Ivan the Fool.'],
      ['해설', 'Ivan worked hard on his farm every day.'],
      ['첫째', 'Ivan, give me half of your grain!'],
      ['이반', 'Okay, Brother. Take it. I can work more.'],
      ['꼬마악마', 'Hee hee! Let’s make the brothers fight!'],
      ['해설', 'The imps made the big brothers greedy.'],
      ['해설', 'Soon the brothers lost everything and came home.'],
      ['둘째', 'Ivan, we are sorry. Can you feed us?'],
      ['이반', 'Of course! Let’s eat together.'],
      ['해설', 'An imp made Ivan’s field very hard.'],
      ['이반', 'The ground is hard? Then I will dig harder!'],
      ['해설', 'Ivan never stopped. The tired imp got caught.'],
      ['꼬마악마', 'Let me go! I will give you a magic root!'],
      ['해설', 'With the root, Ivan made a sick princess well.'],
      ['해설', 'The happy king made Ivan the new king.'],
      ['이반', 'Anyone with working hands can eat with us.'],
      ['늙은악마', 'Listen! I will teach you to work with your head!'],
      ['해설', 'The old imp just talked and talked on a tower.'],
      ['해설', 'He got hungry and rolled down the stairs. Bump, bump!'],
      ['이반', 'Oh, so this is working with your head!'],
      ['해설', 'The old imp ran away and never came back.'],
      ['해설', 'Honest work and sharing are the real wisdom.'],
    ],
  },

  'cl-two-old-men': {
    title: 'The Two Old Men',
    names: { 해설: 'Narrator', 예핌: 'Efim', 엘리사: 'Elisha', 소녀: 'Girl', 할머니: 'Grandma' },
    outro: [
      'What did you think of the story?',
      'If you were Elisha, would you help the family or keep going?',
      'Did you ever stop your plans to help a friend?',
    ],
    lines: [
      ['해설', 'Long ago, two old friends lived in a village.'],
      ['해설', 'Their names were Efim and Elisha.'],
      ['예핌', 'Elisha, let’s take a long trip to the holy city.'],
      ['엘리사', 'Yes! Let’s go tomorrow morning.'],
      ['해설', 'They walked and walked for many weeks.'],
      ['해설', 'One day, Elisha went into a little house for water.'],
      ['예핌', 'I will walk on slowly. Come soon!'],
      ['해설', 'Inside, a family was very weak and hungry.'],
      ['소녀', 'Grandpa, we have had no food for days.'],
      ['엘리사', 'Oh dear! Please eat my bread first.'],
      ['해설', 'Elisha brought water and bread. He cooked warm soup.'],
      ['할머니', 'Thank you, kind man. The children feel better now.'],
      ['해설', 'Elisha bought them a field, a cow, and seeds.'],
      ['엘리사', 'Now my money is gone. But that is okay.'],
      ['해설', 'Elisha quietly went back home.'],
      ['해설', 'Efim walked on and reached the holy city.'],
      ['해설', 'In the church, he saw Elisha standing in the light!'],
      ['예핌', 'Elisha? How did you get here first?'],
      ['해설', 'On his way home, Efim visited the little house.'],
      ['소녀', 'A kind grandpa helped us. He was like an angel.'],
      ['해설', 'Back home, Elisha was taking care of his bees.'],
      ['엘리사', 'Efim, welcome back! I got lost on the way.'],
      ['예핌', 'No, my friend. You took the best road of all.'],
      ['해설', 'Helping people in need is the most special trip.'],
    ],
  },

  'cl-elephant-nose': {
    title: 'The Elephant’s Child',
    names: { 해설: 'Narrator', 아기코끼리: 'Baby Elephant', 기린: 'Giraffe', 콜로콜로새: 'Kolokolo Bird', 비단뱀: 'Python', 악어: 'Crocodile' },
    outro: [
      'Did you enjoy the story?',
      'If you were the Baby Elephant, would you go to the river alone?',
      'What do you wonder about these days?',
    ],
    lines: [
      ['해설', 'Long ago, elephants had short, fat noses.'],
      ['해설', 'A baby elephant asked questions all day long.'],
      ['아기코끼리', 'Giraffe, why do you have spots?'],
      ['기린', 'Another question? Shh, be quiet!'],
      ['아기코끼리', 'Then what does the crocodile eat for dinner?'],
      ['기린', 'Shh! Do not ask that!'],
      ['콜로콜로새', 'Go to the big gray river. You will find out.'],
      ['해설', 'The baby elephant took some bananas and set off.'],
      ['해설', 'Stomp, stomp. At last, he came to the river.'],
      ['해설', 'A big python was lying on a rock.'],
      ['아기코끼리', 'Have you seen a crocodile?'],
      ['비단뱀', 'Hiss. He is right by your feet. Be careful.'],
      ['해설', 'A log opened its eyes. It was the crocodile!'],
      ['악어', 'Come closer, little one. I will tell you a secret.'],
      ['해설', 'Snap! The crocodile caught the baby’s nose.'],
      ['아기코끼리', 'Ouch! Let go! My nose hurts!'],
      ['비단뱀', 'I will help you! Hold on to my tail!'],
      ['해설', 'Pull, pull! The nose got longer and longer. Pop!'],
      ['해설', 'Splash! The crocodile went back into the water.'],
      ['아기코끼리', 'Oh no. My nose is so long now.'],
      ['비단뱀', 'Try it. See what your nose can do.'],
      ['해설', 'He picked high leaves. He sprayed cool water. Whoosh!'],
      ['아기코끼리', 'Wow! I love my long nose!'],
      ['해설', 'Asking questions and looking for answers is a great power.'],
    ],
  },

  'cl-camel-hump': {
    title: 'How the Camel Got His Hump',
    names: { 해설: 'Narrator', 낙타: 'Camel', 말: 'Horse', 개: 'Dog', 소: 'Ox', 정령: 'Desert Spirit' },
    outro: [
      'Was the story fun?',
      'If you were the Horse, what would you say to the Camel?',
      'How do you get ready for a job you do not like?',
    ],
    lines: [
      ['해설', 'Long ago, all the animals worked to help people.'],
      ['해설', 'But a lazy camel lived in the middle of the desert.'],
      ['해설', 'He just ate thorns and did nothing all day.'],
      ['말', 'Camel, come and run with us!'],
      ['낙타', 'Humph!'],
      ['개', 'Camel, come and carry things with us!'],
      ['낙타', 'Humph!'],
      ['소', 'Camel, come and work in the field with us!'],
      ['낙타', 'Humph!'],
      ['해설', 'So the horse, the dog, and the ox worked extra hard.'],
      ['소', 'This is not fair. The camel just plays!'],
      ['해설', 'Then the Desert Spirit came flying in the sandy wind.'],
      ['말', 'Spirit, please talk to that lazy camel!'],
      ['정령', 'Camel, your friends work hard because of you.'],
      ['낙타', 'Humph!'],
      ['정령', 'Humph again? Do not say that too much.'],
      ['낙타', 'Humph!'],
      ['해설', 'Puff! A big round hump grew on the camel’s back.'],
      ['정령', 'This is your humph! Now you can work without food.'],
      ['낙타', 'I am sorry. I will work with my friends now.'],
      ['해설', 'From then on, the camel carried things across the desert.'],
      ['해설', 'And camels still have humps today.'],
      ['해설', 'When we all help, work is fun for everyone.'],
    ],
  },

  'cl-leopard-spots': {
    title: 'How the Leopard Got His Spots',
    names: { 해설: 'Narrator', 표범: 'Leopard', 원숭이: 'Baboon', 기린: 'Giraffe', 얼룩말: 'Zebra' },
    outro: [
      'Did you like the story?',
      'If you were the Leopard, what pattern would you want?',
      'Have you ever moved to a new place? How was it?',
    ],
    lines: [
      ['해설', 'Long ago, the leopard was all sandy yellow.'],
      ['해설', 'He lived in a wide, yellow field.'],
      ['해설', 'The giraffe and the zebra were yellow, too.'],
      ['표범', 'Roar! I caught you! I am the tag champion!'],
      ['기린', 'Oh no, again! We cannot hide in this field.'],
      ['얼룩말', 'Let’s move to the deep, dark forest!'],
      ['해설', 'So the giraffe and the zebra went into the forest.'],
      ['해설', 'Sun and shadows made patterns on the trees.'],
      ['해설', 'Slowly, the giraffe got patches. The zebra got stripes.'],
      ['표범', 'Where did everyone go? I am so bored.'],
      ['해설', 'The leopard went to see the wise baboon.'],
      ['원숭이', 'They went to the forest. You must change, too.'],
      ['해설', 'The leopard went into the forest. He saw only shadows.'],
      ['표범', 'Sniff, sniff. I can smell them, but I cannot see them!'],
      ['얼룩말', 'Hee hee! We see you, Leopard. You are too yellow!'],
      ['표범', 'I want a forest coat, too.'],
      ['해설', 'The baboon put his fingers in dark shadow paint.'],
      ['원숭이', 'Stay still. Tap, tap, tap!'],
      ['해설', 'Little spots came out all over the leopard.'],
      ['표범', 'Wow! Now I can hide in the shadows, too!'],
      ['기린', 'Leopard, let’s play hide-and-seek in the forest!'],
      ['해설', 'That is why leopards have spots today.'],
      ['해설', 'In a new place, we can change a little and fit in.'],
    ],
  },

  'cl-flanders-dog': {
    title: 'A Dog of Flanders',
    names: { 해설: 'Narrator', 넬로: 'Nello', 할아버지: 'Grandpa', 알루아: 'Alois', 코게즈: 'Mr. Cogez' },
    outro: [
      'Thank you for listening to the end.',
      'If you were Alois, what would you do for Nello?',
      'Who is always there for you, a friend or a pet?',
    ],
    lines: [
      ['해설', 'Long ago, a boy named Nello lived in Flanders.'],
      ['해설', 'He lived with his old grandpa in a small house.'],
      ['해설', 'One day, Nello found a tired dog by the road.'],
      ['넬로', 'Grandpa, can we take care of this dog?'],
      ['할아버지', 'Yes. We are poor, but we can still share.'],
      ['해설', 'Nello named the dog Patrasche.'],
      ['해설', 'Every day, they pulled a milk cart to the big city.'],
      ['넬로', 'I want to be a painter. I want to see the big painting.'],
      ['해설', 'But you needed money to see the painting in the church.'],
      ['알루아', 'Nello, thank you for drawing my picture!'],
      ['코게즈', 'Alois, do not play with that poor boy!'],
      ['해설', 'Nello drew a picture for a big contest.'],
      ['해설', 'But on Christmas Eve, another boy won.'],
      ['넬로', 'Patrasche, where should we go now?'],
      ['해설', 'In the snow, Patrasche found Mr. Cogez’s lost money bag.'],
      ['넬로', 'This is not ours. We must give it back.'],
      ['코게즈', 'Nello is honest and kind. I was wrong about him.'],
      ['해설', 'That night, the church door was a little open.'],
      ['해설', 'In the moonlight, Nello saw the big painting at last.'],
      ['넬로', 'Look, Patrasche! I am so happy now.'],
      ['해설', 'Nello and Patrasche hugged and fell asleep under the painting.'],
      ['해설', 'In a warm dream, they walked together into the light.'],
      ['해설', 'If a friend is lonely, go and hold their hand.'],
    ],
  },

  'cl-christmas-carol': {
    title: 'A Christmas Carol',
    names: { 해설: 'Narrator', 스크루지: 'Scrooge', 밥: 'Bob', 말리: 'Marley', 과거유령: 'Past Ghost', 현재유령: 'Present Ghost', 팀: 'Tim' },
    outro: [
      'Did you enjoy the story?',
      'If you were Scrooge, what would you do first?',
      'What would you like to share at Christmas?',
    ],
    lines: [
      ['해설', 'Long ago in London, there lived a man named Scrooge.'],
      ['해설', 'Scrooge loved money. He did not like to share.'],
      ['밥', 'Sir, tomorrow is Christmas. May I stay home?'],
      ['스크루지', 'Humph! Christmas is silly!'],
      ['해설', 'That night, a misty ghost came. Clink, clank went his chains.'],
      ['말리', 'Scrooge, I am your old friend Marley. Do not be greedy.'],
      ['말리', 'Three ghosts will visit you tonight. Watch and learn.'],
      ['해설', 'Ding, dong! The first ghost came, all shiny.'],
      ['과거유령', 'I am the Ghost of Christmas Past. Come with me.'],
      ['해설', 'They saw young Scrooge alone in an empty classroom.'],
      ['스크루지', 'I was so lonely then.'],
      ['현재유령', 'I am the Ghost of Christmas Present. Look at Bob’s home.'],
      ['해설', 'Bob’s family shared a little food. They laughed together.'],
      ['해설', 'Little Tim had a sore leg and a small crutch.'],
      ['팀', 'Our home is small, but it is warm. Merry Christmas!'],
      ['스크루지', 'Can I help that boy?'],
      ['해설', 'The last ghost showed a lonely Christmas. No one missed Scrooge.'],
      ['스크루지', 'No! I do not want to be lonely. I will change!'],
      ['해설', 'Scrooge woke up. Christmas bells were ringing!'],
      ['스크루지', 'It is not too late! It is Christmas!'],
      ['해설', 'Scrooge sent a big turkey to Bob’s home.'],
      ['스크루지', 'Bob, I will pay you more. I will help Tim, too.'],
      ['팀', 'Merry Christmas, Grandpa Scrooge!'],
      ['해설', 'When we share and laugh together, Christmas fills our hearts.'],
    ],
  },

  'cl-forever-shirt': {
    title: 'The Forever Shirt',
    names: { 해설: 'Narrator', 창남: 'Changnam', 선생님: 'Teacher', 친구: 'Friend', 어머니: 'Mom' },
    outro: [
      'What did you think of the story?',
      'If you were Changnam, would you give your clothes away?',
      'What did you share with a friend or neighbor?',
    ],
    lines: [
      ['해설', 'Long ago, there was a cheerful boy named Changnam.'],
      ['해설', 'His family was poor, but he always laughed.'],
      ['친구', 'Changnam, your pants have patches again! Ha ha!'],
      ['창남', 'Yes! My mom is great at sewing, right?'],
      ['해설', 'One very cold winter morning, it was gym class.'],
      ['선생님', 'Everyone, take off your jackets. Keep your shirts on!'],
      ['해설', 'But Changnam did not take off his jacket.'],
      ['선생님', 'Changnam, what is wrong? Take off your jacket.'],
      ['창남', 'Teacher, today I am wearing my forever shirt.'],
      ['선생님', 'A forever shirt? What is that?'],
      ['해설', 'Changnam took off his jacket. There was no shirt at all!'],
      ['창남', 'This is my forever shirt. It never gets dirty!'],
      ['해설', 'The children laughed, but the teacher was surprised.'],
      ['선생님', 'Changnam, where is your shirt on this cold day?'],
      ['창남', 'There was a fire in my town. My neighbors lost their homes.'],
      ['창남', 'They were so cold, so I gave them my clothes.'],
      ['어머니', 'We still have a roof. Let’s help our neighbors first.'],
      ['해설', 'The noisy classroom became very quiet.'],
      ['친구', 'Changnam, I am sorry. Share my scarf with me.'],
      ['선생님', 'You have a big heart. Please wear my coat.'],
      ['해설', 'The other children gave him gloves and socks, too.'],
      ['창남', 'Thank you, everyone! Now I am really warm!'],
      ['해설', 'A sharing heart is warmer than any coat.'],
    ],
  },
};
