// 영어 학습용 원고 (한국 초등 저학년, 영어 초급). 문장은 자체 각색.
// 키 = stories/serial-a.js 의 이야기 id. lines 의 첫 칸은 원래 이야기 cast 의 한국어 이름 그대로.
export default {
  'sr-pinocchio-1': {
    title: 'Pinocchio, Part 1',
    names: { 해설: 'Narrator', 제페토: 'Geppetto', 피노키오: 'Pinocchio', 귀뚜라미: 'Cricket' },
    outro: [
      'Did you like Part 1?',
      'If you were Pinocchio, would you listen to the cricket?',
      'Has someone given you something special?',
    ],
    lines: [
      ['해설', 'Long ago, an old man named Geppetto lived in Italy.'],
      ['해설', 'He was a woodcarver. He made things from wood.'],
      ['제페토', 'I will make a puppet from this log.'],
      ['해설', 'Chip, chip! He started to carve.'],
      ['피노키오', 'Hee hee! That tickles! Please be gentle!'],
      ['제페토', 'What? A log that talks?'],
      ['해설', 'He made a head, eyes, and a nose. The nose grew long!'],
      ['제페토', 'You are a little rascal. Your name is Pinocchio.'],
      ['해설', 'Then Pinocchio ran out the door. Tap, tap, tap!'],
      ['피노키오', 'I am free! Nobody can catch me!'],
      ['해설', 'That night, a little cricket spoke from the wall.'],
      ['귀뚜라미', 'Pinocchio, listen to your father, or you will be sorry.'],
      ['피노키오', 'I do not want to listen. I just want to play!'],
      ['귀뚜라미', 'One day, you will remember my words. Chirp, chirp.'],
      ['해설', 'The next day, Pinocchio was very hungry.'],
      ['해설', 'Geppetto gave him all of his pears.'],
      ['피노키오', 'Father, I will be good. I will go to school!'],
      ['해설', 'Geppetto sold his only coat. He bought a book.'],
      ['피노키오', 'Thank you, Father! I will buy you a new coat!'],
      ['해설', 'The next morning, Pinocchio went to school.'],
      ['해설', 'But far away, he heard drums. Boom, boom!'],
      ['해설', 'Remember the people who love you, and be thankful.'],
    ],
  },

  'sr-pinocchio-2': {
    title: 'Pinocchio, Part 2',
    names: { 해설: 'Narrator', 피노키오: 'Pinocchio', 불먹보: 'Fire-Eater', 여우: 'Fox', 고양이: 'Cat' },
    outro: [
      'Was Part 2 exciting?',
      'If you were Pinocchio, would you go with the fox?',
      'What would you do with five gold coins?',
    ],
    lines: [
      ['해설', 'Pinocchio was on his way to school. Do you remember?'],
      ['해설', 'He followed the drums to a puppet show.'],
      ['피노키오', 'I can go to school tomorrow. Just one show!'],
      ['해설', 'He sold his book and bought a ticket.'],
      ['해설', 'The puppets saw him and pulled him onto the stage.'],
      ['해설', 'The show stopped. The people shouted.'],
      ['해설', 'Then the big owner came out. His name was Fire-Eater.'],
      ['불먹보', 'You broke my show! I will lock you in the kitchen!'],
      ['피노키오', 'Please, no! My father is waiting for me!'],
      ['해설', 'But Fire-Eater had a soft heart. Achoo! He sneezed.'],
      ['불먹보', 'Your father sold his coat? Poor man!'],
      ['불먹보', 'Here are five gold coins. Give them to your father.'],
      ['피노키오', 'Thank you, sir! Father will be so happy!'],
      ['해설', 'On the way home, he met a fox and a cat.'],
      ['여우', 'Hello, Pinocchio. Your pocket jingles. Clink, clink.'],
      ['피노키오', 'I have five gold coins for my father!'],
      ['고양이', 'Only five? That is not much.'],
      ['여우', 'Plant them in the Magic Field. A money tree will grow!'],
      ['피노키오', 'Really? Then I can give Father lots of gold!'],
      ['해설', 'Far away, a cricket chirped. Go home, it seemed to say.'],
      ['해설', 'But the three went to an inn for the night.'],
      ['여우', 'We will wake you at midnight. Then we will go.'],
      ['해설', 'Think twice when someone only says sweet words.'],
    ],
  },

  'sr-pinocchio-3': {
    title: 'Pinocchio, Part 3',
    names: { 해설: 'Narrator', 피노키오: 'Pinocchio', 여우: 'Fox', 고양이: 'Cat', 요정: 'Fairy' },
    outro: [
      'Did you enjoy Part 3?',
      'If you were Pinocchio, what would you tell the fairy?',
      'How do you feel after you tell the truth?',
    ],
    lines: [
      ['해설', 'Pinocchio stayed at an inn with the fox and the cat.'],
      ['해설', 'At midnight, he woke up. The fox and the cat were gone.'],
      ['피노키오', 'Maybe they went to the field. I will go, too!'],
      ['해설', 'He walked in the dark woods. Rustle, rustle!'],
      ['해설', 'Two strange shadows in sacks were following him.'],
      ['여우', 'Give me your gold coins!'],
      ['해설', 'Pinocchio hid the coins under his tongue and ran.'],
      ['고양이', 'Stop! Oh, he is so fast!'],
      ['해설', 'He ran all night. At last, he fell down by a white house.'],
      ['해설', 'A fairy with blue hair lived in the house.'],
      ['요정', 'Poor thing! Come in and rest.'],
      ['해설', 'She gave him medicine. Soon he felt better.'],
      ['요정', 'Pinocchio, where are your gold coins?'],
      ['피노키오', 'Um, I lost them.'],
      ['해설', 'Then his nose grew long! The coins were in his pocket.'],
      ['요정', 'Really? Where did you lose them?'],
      ['피노키오', 'In the woods. No, I swallowed them!'],
      ['해설', 'With every lie, his nose grew longer and longer.'],
      ['요정', 'Lies grow bigger, just like your nose.'],
      ['피노키오', 'I am sorry! I will not tell lies again!'],
      ['해설', 'Woodpeckers came and made his nose short again. Peck, peck!'],
      ['요정', 'Your father is coming. Go and meet him.'],
      ['해설', 'But on the road, the fox and the cat came back.'],
      ['해설', 'Always tell the truth from the start.'],
    ],
  },

  'sr-pinocchio-4': {
    title: 'Pinocchio, Part 4',
    names: { 해설: 'Narrator', 피노키오: 'Pinocchio', 여우: 'Fox', 고양이: 'Cat', 요정: 'Fairy', 심지: 'Candlewick' },
    outro: [
      'How was Part 4?',
      'If you were Pinocchio, would you go to Toy Land?',
      'Tell me about a promise you kept.',
    ],
    lines: [
      ['해설', 'Pinocchio met the fox and the cat again. Do you remember?'],
      ['여우', 'Here is the Magic Field. Plant your coins!'],
      ['해설', 'Pinocchio dug a hole and planted the coins.'],
      ['고양이', 'Now take a walk. The money tree will grow.'],
      ['해설', 'When he came back, the hole was empty.'],
      ['해설', 'A parrot laughed. The fox and the cat took the coins!'],
      ['피노키오', 'I should have listened to the cricket.'],
      ['해설', 'Pinocchio walked to the sea. He saw a small boat.'],
      ['해설', 'Geppetto was in the boat. He was looking for Pinocchio.'],
      ['피노키오', 'Father! Father! I am here!'],
      ['해설', 'But big waves took the boat far away.'],
      ['해설', 'Pinocchio cried. Then the fairy with blue hair came.'],
      ['요정', 'You will see your father again. Be good until then.'],
      ['피노키오', 'I will! I will go to school every day!'],
      ['해설', 'Pinocchio went to school and learned his letters.'],
      ['심지', 'Pinocchio, let us go to Toy Land! There is no school!'],
      ['피노키오', 'No. I made a promise to the fairy.'],
      ['심지', 'Just one day! The coach comes tonight.'],
      ['피노키오', 'Okay, just one day.'],
      ['해설', 'In Toy Land, they played every day for months.'],
      ['해설', 'One morning, Pinocchio had long, furry ears!'],
      ['피노키오', 'What is this? Hee-haw! What is wrong with my voice?'],
      ['해설', 'Keep your promises, or you may lose something special.'],
    ],
  },

  'sr-pinocchio-5': {
    title: 'Pinocchio, Part 5',
    names: { 해설: 'Narrator', 피노키오: 'Pinocchio', 심지: 'Candlewick', 제페토: 'Geppetto', 귀뚜라미: 'Cricket', 요정: 'Fairy' },
    outro: [
      'Did you like the last part?',
      'If you were Pinocchio, how would you help your father?',
      'How do you help your family at home?',
    ],
    lines: [
      ['해설', 'Pinocchio had donkey ears in Toy Land. Do you remember?'],
      ['해설', 'The next day, he and Candlewick became donkeys!'],
      ['심지', 'Hee-haw! I am sorry, Pinocchio.'],
      ['피노키오', 'Hee-haw! I broke my promise, too.'],
      ['해설', 'Pinocchio went to a circus. He jumped through hoops.'],
      ['해설', 'Then he hurt his leg. His owner left him by the sea.'],
      ['해설', 'He went into the water. Splash! Fish took off his donkey fur.'],
      ['피노키오', 'My hands! My feet! I am a puppet again!'],
      ['해설', 'Then a giant shark swam up. Gulp!'],
      ['해설', 'Inside the shark, it was dark. But a candle was shining.'],
      ['제페토', 'Who is there? Is it Pinocchio?'],
      ['피노키오', 'Father! I missed you so much!'],
      ['제페토', 'I looked for you on the sea. The shark swallowed me.'],
      ['피노키오', 'Now I will take care of you. Let us go!'],
      ['해설', 'The shark slept with its mouth open. They tiptoed out.'],
      ['해설', 'Pinocchio swam with his father on his back.'],
      ['해설', 'On the beach, they found a little hut. Chirp, chirp!'],
      ['귀뚜라미', 'Pinocchio, you saved your father! Stay here.'],
      ['피노키오', 'Cricket, I am sorry I did not listen.'],
      ['해설', 'Every day, Pinocchio worked hard and helped his father.'],
      ['요정', 'You are kind and good. Now be a real boy.'],
      ['해설', 'In the morning, Pinocchio was a real boy!'],
      ['제페토', 'My Pinocchio! You are a good boy now!'],
      ['해설', 'Saying sorry and helping others make us grow.'],
    ],
  },

  'sr-alice-1': {
    title: 'Alice, Part 1',
    names: { 해설: 'Narrator', 앨리스: 'Alice', 흰토끼: 'White Rabbit' },
    outro: [
      'Did you like Part 1?',
      'If you were Alice, would you follow the rabbit?',
      'What are you curious about?',
    ],
    lines: [
      ['해설', 'One summer day, Alice sat by the river with her sister.'],
      ['해설', 'Her sister read a book with no pictures.'],
      ['앨리스', 'This is boring. A book with no pictures!'],
      ['해설', 'Then a white rabbit ran by. Hop, hop!'],
      ['흰토끼', 'Oh dear! Oh dear! I am late!'],
      ['해설', 'The rabbit wore a vest. He looked at his watch.'],
      ['앨리스', 'A rabbit with a watch? I will follow him!'],
      ['해설', 'The rabbit went down a big hole.'],
      ['해설', 'Alice went in, too. She fell down, down, down.'],
      ['해설', 'She fell very slowly, like a feather.'],
      ['앨리스', 'When will I stop falling?'],
      ['해설', 'At last, she landed on a pile of leaves.'],
      ['해설', 'There was a long hall with many doors.'],
      ['해설', 'She found a tiny gold key. It opened a tiny door.'],
      ['앨리스', 'I see a pretty garden! But I am too big.'],
      ['해설', 'Then she saw a bottle. It said, Drink Me.'],
      ['앨리스', 'Yum! It tastes like cherry pie!'],
      ['해설', 'Alice got smaller and smaller. Now she was tiny.'],
      ['앨리스', 'Oh no! I left the key on the table!'],
      ['해설', 'Then she ate a little cake. She grew very tall!'],
      ['해설', 'Alice cried and cried. Her tears made a big pool.'],
      ['흰토끼', 'Oh my! The Duchess is waiting!'],
      ['해설', 'Alice got small again. Splash! She fell into her tears.'],
      ['해설', 'Follow your curiosity, and a new adventure begins.'],
    ],
  },

  'sr-alice-2': {
    title: 'Alice, Part 2',
    names: { 해설: 'Narrator', 앨리스: 'Alice', 도도새: 'Dodo', 흰토끼: 'White Rabbit', 애벌레: 'Caterpillar' },
    outro: [
      'Was Part 2 fun?',
      'If you were Alice, which side of the mushroom would you eat?',
      'If you could be very big or very small, which would you pick?',
    ],
    lines: [
      ['해설', 'Alice fell into her pool of tears. Do you remember?'],
      ['해설', 'She swam and swam. Splash, splash!'],
      ['해설', 'A mouse, a duck, and a dodo were swimming, too.'],
      ['앨리스', 'I am sorry, everyone. These are my tears.'],
      ['해설', 'They all came out of the water. They were very wet.'],
      ['도도새', 'A race is the best way to get dry!'],
      ['앨리스', 'Where do we start? Where do we stop?'],
      ['도도새', 'Start anywhere. Stop when you want to.'],
      ['해설', 'Everyone ran around and around. Soon they were dry.'],
      ['앨리스', 'Who won?'],
      ['도도새', 'Everyone won! Everyone gets a prize!'],
      ['해설', 'Alice gave everyone a candy from her pocket.'],
      ['흰토끼', 'My gloves! My fan! Where are they?'],
      ['해설', 'Alice walked into the woods. She saw a big mushroom.'],
      ['해설', 'A blue caterpillar sat on top of it.'],
      ['애벌레', 'Who are you?'],
      ['앨리스', 'I was Alice this morning. Now I am not sure.'],
      ['애벌레', 'Do you like your size?'],
      ['앨리스', 'I want to be a little bigger.'],
      ['애벌레', 'One side makes you bigger. The other side makes you smaller.'],
      ['해설', 'Alice took a bite from each side. Nibble, nibble.'],
      ['앨리스', 'Hooray! Now I am my own size again!'],
      ['해설', 'Then, up in a tree, a big smile looked down at her.'],
      ['해설', 'Big or small, you are always special.'],
    ],
  },

  'sr-alice-3': {
    title: 'Alice, Part 3',
    names: { 해설: 'Narrator', 앨리스: 'Alice', 체셔고양이: 'Cheshire Cat', 모자장수: 'Hatter', 삼월토끼: 'March Hare', 겨울잠쥐: 'Dormouse' },
    outro: [
      'Did you enjoy the tea party?',
      'If you were Alice, would you stay at the party?',
      'What snack would you bring to a tea party?',
    ],
    lines: [
      ['해설', 'Alice saw a big smile in a tree. Do you remember?'],
      ['해설', 'It was a cat with a very, very big smile.'],
      ['체셔고양이', 'Hello, little guest. Where are you going?'],
      ['앨리스', 'Which way should I go?'],
      ['체셔고양이', 'That depends on where you want to go.'],
      ['체셔고양이', 'The Hatter lives this way. The March Hare lives that way.'],
      ['해설', 'The cat slowly disappeared. Only its smile was left.'],
      ['앨리스', 'A smile with no cat! How strange!'],
      ['해설', 'Alice walked on. She saw a long table under a tree.'],
      ['해설', 'The Hatter and the March Hare were having tea.'],
      ['삼월토끼', 'No room! No room!'],
      ['앨리스', 'There is lots of room! I will sit here.'],
      ['모자장수', 'Here is a riddle. Why is a teapot like a hat?'],
      ['앨리스', 'Um, they both have tops? What is the answer?'],
      ['모자장수', 'I do not know! That is why it is fun.'],
      ['삼월토끼', 'Have more tea. But there is no tea.'],
      ['앨리스', 'Then do not ask me!'],
      ['모자장수', 'It is always six o’clock here. It is always teatime.'],
      ['겨울잠쥐', 'Twinkle, twinkle, little star. Zzz.'],
      ['앨리스', 'This is the silliest tea party ever. Goodbye!'],
      ['해설', 'Alice opened a little door in a tree.'],
      ['해설', 'She saw the pretty garden. Card soldiers were painting roses.'],
      ['해설', 'Strange days can become fun stories when you smile.'],
    ],
  },

  'sr-alice-4': {
    title: 'Alice, Part 4',
    names: { 해설: 'Narrator', 앨리스: 'Alice', 병사: 'Card Soldier', 여왕: 'Queen', 왕: 'King', 흰토끼: 'White Rabbit', 모자장수: 'Hatter' },
    outro: [
      'Did you like the end of Alice’s dream?',
      'If you were Alice, what would you say to the Queen?',
      'What strange dream have you had?',
    ],
    lines: [
      ['해설', 'Alice saw card soldiers painting roses. Do you remember?'],
      ['앨리스', 'Why are you painting the white roses red?'],
      ['병사', 'Shh! The Queen only likes red roses.'],
      ['해설', 'Toot, toot! The Queen and King of Hearts came.'],
      ['여왕', 'Who is this girl? What is your name?'],
      ['앨리스', 'My name is Alice, Your Majesty.'],
      ['여왕', 'Can you play croquet? Come and play!'],
      ['해설', 'The balls were hedgehogs. The mallets were flamingos!'],
      ['앨리스', 'This game is so hard!'],
      ['여왕', 'I missed! Send that soldier away!'],
      ['왕', 'Calm down, dear. Everyone is scared.'],
      ['흰토끼', 'The trial is starting! Someone ate the Queen’s tarts!'],
      ['모자장수', 'I do not know anything. I was just drinking tea.'],
      ['해설', 'Then Alice began to grow bigger and bigger.'],
      ['흰토끼', 'Next, Alice!'],
      ['앨리스', 'I do not know anything about the tarts.'],
      ['여왕', 'First the punishment, then the proof!'],
      ['앨리스', 'That is silly! It is backward!'],
      ['여왕', 'How dare you! Send that girl away!'],
      ['앨리스', 'I am not scared. You are just a pack of cards!'],
      ['해설', 'The cards flew up and fell on her. Whoosh!'],
      ['해설', 'Alice woke up by the river. Leaves were on her face.'],
      ['앨리스', 'Sister, I had a very strange dream!'],
      ['해설', 'Curiosity and imagination are wings that can take you anywhere.'],
    ],
  },

  'sr-oz-1': {
    title: 'The Wizard of Oz, Part 1',
    names: { 해설: 'Narrator', 도로시: 'Dorothy', 엠아줌마: 'Aunt Em', 북쪽마녀: 'Witch of the North', 먼치킨: 'Munchkin' },
    outro: [
      'Did you like Part 1?',
      'If you were Dorothy, how would you feel in a new land?',
      'Who would you take on an adventure?',
    ],
    lines: [
      ['해설', 'Long ago, a girl named Dorothy lived in Kansas.'],
      ['해설', 'She lived with Aunt Em, Uncle Henry, and her dog, Toto.'],
      ['해설', 'Everything was gray. But Toto made Dorothy smile.'],
      ['해설', 'One day, a big wind came. Whoosh!'],
      ['엠아줌마', 'Dorothy! Go down to the cellar!'],
      ['도로시', 'Toto is under the bed! Come here, Toto!'],
      ['해설', 'Then the house flew up into the sky.'],
      ['해설', 'It went round and round. Dorothy fell asleep.'],
      ['해설', 'Bump! The house landed. Outside, there were pretty flowers.'],
      ['도로시', 'Where am I? This is not Kansas.'],
      ['북쪽마녀', 'Welcome. I am the good Witch of the North.'],
      ['먼치킨', 'Thank you! Your house chased away the bad Witch of the East!'],
      ['해설', 'The bad witch ran away. She left her silver shoes.'],
      ['북쪽마녀', 'These silver shoes are yours now. They are magic.'],
      ['도로시', 'Thank you. But I want to go home.'],
      ['북쪽마녀', 'The great Oz may help you. He lives in the Emerald City.'],
      ['도로시', 'How do I get there?'],
      ['북쪽마녀', 'Follow the yellow brick road. Here is a kiss for luck.'],
      ['해설', 'The kiss left a shiny mark. It would keep her safe.'],
      ['도로시', 'Come on, Toto! Let us find Oz!'],
      ['해설', 'Dorothy walked and walked. In a cornfield, someone winked at her.'],
      ['해설', 'Be brave and take one step. A new road will open.'],
    ],
  },

  'sr-oz-2': {
    title: 'The Wizard of Oz, Part 2',
    names: { 해설: 'Narrator', 도로시: 'Dorothy', 허수아비: 'Scarecrow', 양철나무꾼: 'Tin Woodman' },
    outro: [
      'Was Part 2 fun?',
      'If you were the Scarecrow, what would you think about first?',
      'Who helps you when you have a problem?',
    ],
    lines: [
      ['해설', 'Someone winked at Dorothy in a cornfield. Do you remember?'],
      ['해설', 'It was a scarecrow on a pole.'],
      ['허수아비', 'Hello! Can you help me down, please?'],
      ['해설', 'Dorothy helped him down. He stretched. Wobble, wobble!'],
      ['허수아비', 'Thank you! Where are you going?'],
      ['도로시', 'I am going to see Oz. I want to go home.'],
      ['허수아비', 'My head is full of straw. Can Oz give me a brain?'],
      ['도로시', 'Let us go together and ask him!'],
      ['해설', 'The Scarecrow fell into holes. Bump! But he was okay.'],
      ['허수아비', 'I am made of straw. It does not hurt!'],
      ['해설', 'In the woods, they heard a sad sound.'],
      ['해설', 'It was a man made of tin. He could not move.'],
      ['양철나무꾼', 'Oil. Please. Oil can.'],
      ['해설', 'Dorothy found an oil can. Drip, drip, drip!'],
      ['양철나무꾼', 'Thank you! I was rusty for a whole year.'],
      ['양철나무꾼', 'I have no heart. I want a heart to love.'],
      ['허수아비', 'Come with us! Oz can help you, too.'],
      ['도로시', 'Of course! Bring your oil can.'],
      ['해설', 'The Tin Woodman walked carefully. He did not step on ants.'],
      ['허수아비', 'You have no heart? But you are so kind!'],
      ['해설', 'The woods got darker and darker.'],
      ['해설', 'Then they heard a big sound. Roar!'],
      ['해설', 'Friends who help each other make the road easier.'],
    ],
  },

  'sr-oz-3': {
    title: 'The Wizard of Oz, Part 3',
    names: { 해설: 'Narrator', 도로시: 'Dorothy', 허수아비: 'Scarecrow', 양철나무꾼: 'Tin Woodman', 사자: 'Lion', 들쥐여왕: 'Mouse Queen', 문지기: 'Gatekeeper' },
    outro: [
      'Did you enjoy Part 3?',
      'If you were the Lion, how would you thank the mice?',
      'When did a small friend help you?',
    ],
    lines: [
      ['해설', 'Dorothy and her friends heard a roar. Do you remember?'],
      ['해설', 'A big lion jumped out. He knocked down the Scarecrow.'],
      ['사자', 'Roar! Nobody move!'],
      ['해설', 'The Lion went to Toto. Dorothy tapped his nose.'],
      ['도로시', 'Do not scare my little dog! You are a coward!'],
      ['사자', 'You are right. I am a coward. I am sorry.'],
      ['양철나무꾼', 'Ask Oz for courage. We are going to see him.'],
      ['사자', 'Can I come, too? I will keep you safe!'],
      ['해설', 'Soon they came to a big field of red flowers.'],
      ['해설', 'But the flowers made people very sleepy.'],
      ['도로시', 'I am so sleepy. Let me rest.'],
      ['해설', 'Dorothy and Toto fell asleep in the flowers.'],
      ['허수아비', 'Flowers cannot make us sleepy! Let us carry Dorothy!'],
      ['해설', 'The Lion ran, but he fell asleep, too.'],
      ['해설', 'Then the Tin Woodman saved a little field mouse.'],
      ['들쥐여왕', 'Thank you! I am the Queen of the Mice. I will help you.'],
      ['해설', 'The Tin Woodman made a cart. Many mice pulled it. Heave-ho!'],
      ['사자', 'I am awake! Little mice saved me!'],
      ['해설', 'At last, they saw a green city. It was the Emerald City!'],
      ['문지기', 'Welcome! Please wear these green glasses.'],
      ['도로시', 'Now we can meet Oz! Let us make our wishes!'],
      ['해설', 'Small friends can help big friends when they work together.'],
    ],
  },

  'sr-oz-4': {
    title: 'The Wizard of Oz, Part 4',
    names: { 해설: 'Narrator', 도로시: 'Dorothy', 오즈: 'Oz', 서쪽마녀: 'Witch of the West', 사자: 'Lion', 허수아비: 'Scarecrow' },
    outro: [
      'Was Part 4 exciting?',
      'If you were Dorothy, how would you feel in the castle?',
      'What do you do when something is hard?',
    ],
    lines: [
      ['해설', 'Dorothy and her friends were in the Emerald City. Do you remember?'],
      ['해설', 'Oz looked different to each friend.'],
      ['해설', 'He was a head, a lady, a beast, or a fireball.'],
      ['오즈', 'I am Oz, the Great. I will help you.'],
      ['오즈', 'But first, stop the bad Witch of the West.'],
      ['도로시', 'I am just a little girl. How can I do that?'],
      ['오즈', 'That is your job. Do not come back until then.'],
      ['해설', 'So the friends walked to the west.'],
      ['서쪽마녀', 'Who is in my land? Winged Monkeys, catch them!'],
      ['해설', 'The monkeys flew down. Flap, flap! They pulled the friends apart.'],
      ['해설', 'But the kiss on Dorothy’s head kept her safe.'],
      ['서쪽마녀', 'Clean the floor! Wash the pots! Do not stop!'],
      ['해설', 'The witch wanted Dorothy’s magic silver shoes.'],
      ['해설', 'One day, the witch tripped Dorothy. One shoe fell off.'],
      ['서쪽마녀', 'Ha! This shoe is mine now!'],
      ['도로시', 'Give it back! It is mine!'],
      ['해설', 'Dorothy was angry. She threw a bucket of water. Splash!'],
      ['서쪽마녀', 'Oh no! Water! I am getting smaller and smaller!'],
      ['해설', 'The wet witch got smaller and then disappeared like smoke.'],
      ['해설', 'Dorothy got her shoe back. She let the Lion out, too.'],
      ['사자', 'Thank you, Dorothy! Let us find our friends!'],
      ['해설', 'People helped fix the Scarecrow and the Tin Woodman.'],
      ['허수아비', 'Let us all go back to Oz!'],
      ['해설', 'Do not give up, even on hard and scary days.'],
    ],
  },

  'sr-oz-5': {
    title: 'The Wizard of Oz, Part 5',
    names: { 해설: 'Narrator', 도로시: 'Dorothy', 오즈: 'Oz', 사자: 'Lion', 허수아비: 'Scarecrow', 양철나무꾼: 'Tin Woodman', 글린다: 'Glinda', 엠아줌마: 'Aunt Em' },
    outro: [
      'Did you like the end of the story?',
      'If you were Dorothy, what would you say to your friends?',
      'What is your favorite place at home?',
    ],
    lines: [
      ['해설', 'Dorothy and her friends came back to Oz. Do you remember?'],
      ['오즈', 'Hmm. Come back tomorrow. I need time to think.'],
      ['사자', 'Roar! Keep your promise!'],
      ['해설', 'Toto jumped and knocked over a screen.'],
      ['해설', 'Behind it was a little old man.'],
      ['오즈', 'I am Oz. But I am not a wizard. I am just a man.'],
      ['허수아비', 'Then what about our wishes?'],
      ['오즈', 'Do not worry. I can give you what you need.'],
      ['해설', 'He gave the Scarecrow new brains of bran and pins.'],
      ['해설', 'He gave the Tin Woodman a red silk heart.'],
      ['해설', 'He gave the Lion a green drink for courage.'],
      ['사자', 'Gulp! Now I am full of courage!'],
      ['해설', 'Oz made a big balloon to take Dorothy home.'],
      ['해설', 'But Toto ran after a cat. The balloon left without Dorothy!'],
      ['해설', 'The friends took Dorothy to Glinda, the good witch.'],
      ['글린다', 'Dorothy, your silver shoes can take you home.'],
      ['글린다', 'Click your heels three times. Say where you want to go.'],
      ['양철나무꾼', 'My new heart feels sad. I will miss you.'],
      ['도로시', 'Thank you, friends. You were already smart, kind, and brave!'],
      ['도로시', 'Take me home to Aunt Em!'],
      ['해설', 'Whoosh! Dorothy was back in Kansas.'],
      ['엠아줌마', 'Dorothy! My dear girl! Where have you been?'],
      ['도로시', 'I went to the Land of Oz. But home is best!'],
      ['해설', 'What we look for may already be inside us.'],
    ],
  },
};
