// 청소년 영어 원고 (중학생 이상). 키 = stories/teen-sci2.js 의 이야기 id.
// 선생님이 학생에게 과학자와 원전, 실험을 해설하는 한국어 각색의 흐름대로 쉬운 영어로 새로 씀(과학자의 말은 지어내지 않음).
export default {
  'sc2-copernicus': {
    title: 'On the Revolutions',
    names: { 해설: 'Narrator', 선생님: 'Teacher', 학생: 'Student' },
    outro: [
      'Why was it so hard for people to accept the Sun at the center of the universe?',
      'How does the running track example make the backward motion of planets easy to understand?',
      'What courage and evidence do we need to disagree with an idea everyone has believed for a long time?',
    ],
    lines: [
      ['해설', 'In 1543, an astronomy book came out in Nuremberg, Germany.'],
      ['해설', 'It was On the Revolutions of the Heavenly Spheres, by Nicolaus Copernicus, a Polish churchman and astronomer.'],
      ['해설', 'In this story, a teacher introduces the book to a student.'],
      ['학생', 'Teacher, what did people believe about the universe back then?'],
      ['선생님', 'They thought the Earth stood still at the center. The Sun, the Moon, and the planets all moved around it.'],
      ['선생님', 'Ptolemy organized this system in the second century, and it was used for almost fourteen hundred years.'],
      ['학생', 'When you look at the sky, the Sun really seems to go around the Earth.'],
      ['선생님', 'True. But planets like Mars sometimes moved in a strange way.'],
      ['선생님', 'A planet moved east among the stars, stopped, and went back west for a while.'],
      ['해설', 'This is called the retrograde motion of a planet.'],
      ['학생', 'How did the old system explain that?'],
      ['선생님', 'It said a planet moved in a small circle while going around a big circle. The small one is called an epicycle.'],
      ['선생님', 'They kept adding circles to match what they saw, so the system became very complicated.'],
      ['해설', 'Copernicus put the Sun in the center. He saw the Earth as just one of the planets going around it.'],
      ['해설', 'He said the Earth spins once a day and goes around the Sun once a year.'],
      ['학생', 'Then what about the backward motion?'],
      ['선생님', 'Imagine you run on the inside lane of a track and pass a friend on an outside lane.'],
      ['선생님', 'While you pass, your friend seems to move backward.'],
      ['학생', 'Oh! When the Earth passes Mars, Mars only looks like it is going backward!'],
      ['선생님', 'Right. The backward motion was not real. It was only how things looked from the Earth.'],
      ['선생님', 'In this system, the order of the planets and their distances from the Sun could also be worked out.'],
      ['해설', 'But Copernicus still believed orbits were perfect circles, so he could not get rid of all the small circles.'],
      ['해설', 'So his system was not much more accurate than the old one.'],
      ['해설', 'He had this idea for a long time, but he hesitated for years before publishing it.'],
      ['해설', 'His young student Rheticus urged him, and the book was dedicated to Pope Paul the Third.'],
      ['해설', 'A preface with no name was added. It said readers should treat the idea as just a tool for calculation.'],
      ['해설', 'Later it was found that Osiander, a theologian who oversaw the printing, wrote it.'],
      ['학생', 'How did people react to the book?'],
      ['선생님', 'At first it was quiet. Decades later, Kepler and Galileo took up the idea, and a big debate began.'],
      ['해설', 'Copernicus died in 1543, the year the book came out.'],
    ],
  },

  'sc2-kepler': {
    title: 'Kepler’s Three Laws',
    names: { 해설: 'Narrator', 선생님: 'Teacher', 학생: 'Student' },
    outro: [
      'Why didn’t Kepler ignore a small difference of eight minutes of arc?',
      'How does drawing an ellipse with two pins and a string make the first law easy to see?',
      'Have you ever had to admit that the data was right and your idea was wrong?',
    ],
    lines: [
      ['해설', 'In 1600, the German mathematician Johannes Kepler went to a place near Prague.'],
      ['해설', 'He went there to work with the Danish astronomer Tycho Brahe.'],
      ['해설', 'Before the telescope, Tycho had collected the most accurate planet records ever made with the naked eye.'],
      ['학생', 'Teacher, how could he measure so accurately without a telescope?'],
      ['선생님', 'He built huge instruments for measuring angles, and he measured the same objects again and again for many years.'],
      ['해설', 'The next year Tycho died, and his records passed to Kepler.'],
      ['해설', 'Kepler’s big task was to find the orbit of Mars.'],
      ['선생님', 'Kepler followed Copernicus. He calculated as if Mars moved around the Sun in a circle.'],
      ['학생', 'But it did not match?'],
      ['선생님', 'It almost matched. But it was off by eight minutes of arc, a little more than one eighth of a degree.'],
      ['학생', 'Couldn’t he just ignore that much?'],
      ['선생님', 'Kepler believed Tycho’s records could not be that wrong. So he gave up the circle.'],
      ['해설', 'After years of calculation, Kepler concluded that the orbit of Mars was an ellipse.'],
      ['선생님', 'This is the first law. A planet moves in an ellipse, with the Sun at one focus.'],
      ['학생', 'What is a focus?'],
      ['선생님', 'Put a loop of string around two pins, pull it tight with a pencil, and draw. That is an ellipse. Each pin is a focus.'],
      ['선생님', 'The second law says a planet moves fast near the Sun and slowly far from it.'],
      ['선생님', 'That is because a line from the Sun to the planet sweeps out equal areas in equal times.'],
      ['학생', 'When it is close, the line is short. So it has to travel farther to sweep the same area.'],
      ['해설', 'These two laws appeared in his 1609 book, New Astronomy.'],
      ['해설', 'The third law was published in 1619 in The Harmony of the World.'],
      ['선생님', 'It says the square of a planet’s period is proportional to the cube of its average distance from the Sun.'],
      ['학생', 'So a farther planet takes much longer to go around once.'],
      ['선생님', 'Right. A planet four times farther than the Earth takes about eight years for one trip.'],
      ['해설', 'Kepler never found out why the planets move this way.'],
      ['해설', 'Later, Newton’s law of gravity gave the answer, and the three laws became important evidence for it.'],
      ['학생', 'It all came from not ignoring a small difference.'],
      ['선생님', 'He trusted the observations and changed his own idea. That is a very precious attitude in science.'],
      ['해설', 'Kepler died in 1630.'],
    ],
  },

  'sc2-archimedes': {
    title: 'Archimedes and Buoyancy',
    names: { 해설: 'Narrator', 선생님: 'Teacher', 학생: 'Student' },
    outro: [
      'The Eureka story may not be true. Why has it been told for so long?',
      'Why is weighing in water more accurate than measuring the water that spills over?',
      'Why is it important to tell a fun anecdote apart from a proven fact?',
    ],
    lines: [
      ['해설', 'In the third century BC, a scholar named Archimedes lived in Syracuse, a city on the island of Sicily.'],
      ['해설', 'In his work On Floating Bodies, he carefully studied the force on objects floating in water.'],
      ['해설', 'In this story, a teacher tells a student about his discovery.'],
      ['학생', 'Teacher, Archimedes is famous for shouting Eureka in the bath, right?'],
      ['선생님', 'That story comes from a book by the Roman architect Vitruvius, written about two hundred years later.'],
      ['선생님', 'No eyewitness wrote it down, so we should see it as a legend, not a fact.'],
      ['해설', 'Here is the legend. King Hiero of Syracuse had a golden crown made.'],
      ['해설', 'But there was a rumor that the craftsman had kept some gold and mixed in silver.'],
      ['해설', 'The king asked Archimedes to find out the truth without damaging the crown.'],
      ['선생님', 'While he was thinking, Archimedes got into a full bathtub, and the water spilled over.'],
      ['선생님', 'His body pushed away as much water as the part that went under. That gave him an idea.'],
      ['학생', 'And he was so happy that he ran into the street without his clothes, right?'],
      ['선생님', 'So the story goes. Eureka means I have found it in Greek.'],
      ['학생', 'But what does spilled water have to do with the crown?'],
      ['선생님', 'Silver is less dense than gold. So for the same weight, silver takes up more space.'],
      ['선생님', 'So a crown with silver would push away more water than pure gold of the same weight.'],
      ['해설', 'But the difference is very small. Many people think it would be hard to see with spilled water.'],
      ['해설', 'The principle Archimedes really found is clearly written in On Floating Bodies.'],
      ['선생님', 'An object in water is pushed up by a force equal to the weight of the water it pushes away. That is buoyancy.'],
      ['학생', 'Then does a heavy ship float because it pushes away a lot of water?'],
      ['선생님', 'Yes. It sinks until it pushes away water equal to its own weight. Then it floats there.'],
      ['선생님', 'Buoyancy can solve the crown problem too. First, balance the crown against the same weight of gold.'],
      ['선생님', 'Then put both in water. The bigger one gets more buoyancy and rises.'],
      ['학생', 'If the crown side goes up, it means silver was mixed in!'],
      ['학생', 'Can I try something at home?'],
      ['선생님', 'Put a potato into a full bowl of water and collect the water that spills. Then you know its volume.'],
      ['해설', 'Archimedes is also famous for the law of the lever and for calculating the range of pi.'],
      ['해설', 'It is said he died around 212 BC, when the Roman army captured Syracuse.'],
    ],
  },

  'sc2-franklin-kite': {
    title: 'Franklin’s Kite',
    names: { 해설: 'Narrator', 선생님: 'Teacher', 학생: 'Student' },
    outro: [
      'How did learning that lightning is electricity change people’s lives?',
      'Why did Franklin tie a dry silk ribbon at the end he held?',
      'When we hear about dangerous experiments, what should we learn, and what should we never copy?',
    ],
    lines: [
      ['해설', 'In the mid-eighteenth century, electricity experiments were very popular in Europe and America.'],
      ['해설', 'Benjamin Franklin, a famous printer in Philadelphia, also studied electricity with passion.'],
      ['해설', 'In this story, a teacher explains Franklin’s kite experiment to a student.'],
      ['학생', 'Teacher, could people make electricity back then?'],
      ['선생님', 'They rubbed glass to make static electricity and stored it in a Leyden jar.'],
      ['선생님', 'When they let the stored electricity out, a small spark jumped with a snap.'],
      ['학생', 'Like lightning?'],
      ['선생님', 'Franklin also thought lightning might be the same kind of electricity as that small spark.'],
      ['해설', 'He suggested putting up a tall, pointed iron rod to draw electricity from the clouds.'],
      ['해설', 'In May 1752, people in France tried his idea first, and it worked.'],
      ['해설', 'That summer, it is said, Franklin flew a silk kite as a storm came near.'],
      ['선생님', 'He put a pointed wire on top of the kite. Near the end of the string, he tied a metal key.'],
      ['선생님', 'The part he held was a dry silk ribbon. Dry silk does not carry electricity well.'],
      ['학생', 'Did lightning hit the kite?'],
      ['선생님', 'No. Electricity from the clouds slowly came down the string, wet with rain.'],
      ['선생님', 'The loose threads on the string stood up. When he touched the key, a small spark jumped.'],
      ['선생님', 'He could even fill a Leyden jar from the key. It was proof that lightning is electricity.'],
      ['해설', 'People learned of it from Franklin’s letter that autumn, and later from a book by Priestley.'],
      ['해설', 'The records are short, so some historians doubt it happened exactly that way.'],
      ['학생', 'Wow, I want to fly a kite on a rainy day too.'],
      ['선생님', 'Absolutely not. This is a very dangerous experiment. You could die.'],
      ['해설', 'The next year, Richmann, a scientist in Russia, was killed by lightning during a similar experiment.'],
      ['선생님', 'When it thunders, bring in your kite and go inside. Never fly a kite near power lines either.'],
      ['해설', 'From this research, Franklin suggested putting lightning rods on buildings.'],
      ['선생님', 'A pointed metal rod on the roof safely carries lightning’s electricity into the ground.'],
      ['학생', 'The experiment was dangerous, but it led to an invention that protects people.'],
      ['선생님', 'Yes. Let’s gladly learn the knowledge, but never copy the experiment.'],
      ['해설', 'Franklin’s letters on electricity were published in London in 1751 as Experiments and Observations on Electricity.'],
    ],
  },

  'sc2-faraday-induction': {
    title: 'Faraday and Electromagnetic Induction',
    names: { 해설: 'Narrator', 선생님: 'Teacher', 학생: 'Student' },
    outro: [
      'Electricity appears only when magnetism changes, not when it stays the same. Why was this discovery important?',
      'Faraday thought by drawing lines of force instead of formulas. What was good about that way of thinking?',
      'A man without much schooling became a great scientist. What does that mean for us today?',
    ],
    lines: [
      ['해설', 'In 1820, Oersted in Denmark saw a compass needle move next to a wire carrying electric current.'],
      ['해설', 'Electricity could make magnetism. So many people wondered whether magnetism could make electricity.'],
      ['해설', 'Michael Faraday of the Royal Institution in London was one of them.'],
      ['학생', 'Teacher, how did Faraday become a scientist?'],
      ['선생님', 'His family was poor, so he did not stay in school long. He read books while working as a bookbinder’s apprentice.'],
      ['선생님', 'He heard the chemist Humphry Davy’s lectures, sent him his neat notes, and later became his assistant.'],
      ['해설', 'In the summer of 1831, Faraday wound two separate coils of covered wire on one iron ring.'],
      ['해설', 'He connected one coil to a battery and the other to a galvanometer, which measures current.'],
      ['학생', 'If current flows in one coil, the ring becomes a magnet. So current will flow in the other coil too?'],
      ['선생님', 'You would think so. But while the current kept flowing, the needle stayed still.'],
      ['선생님', 'The needle moved only when the battery was connected or disconnected. And it moved opposite ways each time.'],
      ['학생', 'Why only at those moments?'],
      ['선생님', 'Because those were the moments when the ring’s magnetism appeared or disappeared. In other words, it changed.'],
      ['해설', 'Soon after, Faraday also pushed a bar magnet into a coil and pulled it out.'],
      ['선생님', 'Current flowed only while the magnet moved. When he left it inside, the needle stopped.'],
      ['학생', 'So magnetism must change, not just be there, to make electricity.'],
      ['선생님', 'Exactly. This is called electromagnetic induction.'],
      ['해설', 'Faraday also spun a copper disk between magnets and made a steady current.'],
      ['선생님', 'Generators in today’s power plants work the same way. They turn magnets and coils to make electricity.'],
      ['학생', 'Is wireless phone charging related too?'],
      ['선생님', 'Yes. The magnetism of the coil in the pad changes quickly and makes a current in the phone’s coil.'],
      ['해설', 'Faraday did not think in formulas. He drew lines of force spreading around magnets.'],
      ['해설', 'This idea later became the basis for Maxwell’s mathematical theory of electromagnetism.'],
      ['학생', 'I want to try it myself.'],
      ['선생님', 'With a coil of enamel wire, a magnet, and a sensitive meter, you can try it in the school lab.'],
      ['선생님', 'But never experiment with electricity from a wall socket. You could be badly hurt.'],
      ['해설', 'In November 1831, Faraday presented this discovery to the Royal Society in London.'],
      ['해설', 'Faraday died in 1867.'],
    ],
  },

  'sc2-lavoisier': {
    title: 'Lavoisier’s Scales',
    names: { 해설: 'Narrator', 선생님: 'Teacher', 학생: 'Student' },
    outro: [
      'How did the habit of careful weighing bring down the phlogiston theory?',
      'What did the sealed vessel show before it was opened and after it was opened?',
      'A great scientist was executed during a revolution. What does this make you think about science and society?',
    ],
    lines: [
      ['해설', 'In eighteenth-century Paris, there lived a chemist named Antoine Lavoisier.'],
      ['해설', 'In every experiment, he carefully weighed his materials on precise scales.'],
      ['해설', 'In this story, a teacher explains Lavoisier’s experiments to a student.'],
      ['학생', 'Teacher, when you burn wood, only a little ash is left. Doesn’t the weight disappear?'],
      ['선생님', 'Back then, many scholars thought something called phlogiston escaped from burning things.'],
      ['학생', 'But when iron rusts, it gets heavier, doesn’t it?'],
      ['선생님', 'Good question. People already knew that burning metals become heavier.'],
      ['해설', 'Lavoisier put tin in a glass vessel, sealed it tightly, and heated it for a long time.'],
      ['선생님', 'He weighed the whole vessel before heating, and again after heating.'],
      ['학생', 'What happened?'],
      ['선생님', 'Before opening, the weight was exactly the same, even though some metal had turned into a powder.'],
      ['선생님', 'But when he opened it, air rushed in, and the weight went up by that much.'],
      ['학생', 'Oh, the metal took in part of the air inside the vessel!'],
      ['선생님', 'Yes. The metal got heavier by exactly the amount of air that was missing.'],
      ['해설', 'Lavoisier named the gas in air that helps burning and breathing oxygen.'],
      ['해설', 'Scheele and Priestley separated this gas first, but Lavoisier explained its role.'],
      ['선생님', 'Burning is not something escaping. It is joining with oxygen.'],
      ['선생님', 'Wood gets lighter because it makes carbon dioxide and water vapor, which go into the air.'],
      ['학생', 'So if we collect those gases and weigh them too, the weight would be the same.'],
      ['선생님', 'That is the law of conservation of mass. The total mass does not change in a chemical reaction.'],
      ['해설', 'In 1789, Lavoisier published Elements of Chemistry, with this idea, a list of elements, and new chemical names.'],
      ['해설', 'His wife, Marie-Anne Lavoisier, helped record experiments and drew the pictures of equipment in the book.'],
      ['학생', 'Can we do a similar experiment?'],
      ['선생님', 'Put vinegar and baking soda in a bottle, cover it with a balloon, and weigh it before and after.'],
      ['선생님', 'But heating a tightly sealed container can make it explode. Never do experiments with fire alone.'],
      ['해설', 'Lavoisier was arrested during the French Revolution because he had worked as a tax collector.'],
      ['해설', 'He was executed by guillotine in Paris in 1794.'],
    ],
  },

  'sc2-humboldt': {
    title: 'Humboldt Explores Nature',
    names: { 해설: 'Narrator', 선생님: 'Teacher', 학생: 'Student' },
    outro: [
      'Why did Humboldt see nature as one connected web, not as separate pieces?',
      'A drawing of a mountain with plants written on it. What does it show better than words?',
      'Exploration and colonial rule were tied together then. How should we read the records of that time today?',
    ],
    lines: [
      ['해설', 'In 1799, the German scholar Alexander von Humboldt set sail with the French botanist Bonpland.'],
      ['해설', 'They headed for Spanish America, and the journey lasted five years, until 1804.'],
      ['학생', 'Teacher, what was Humboldt looking for?'],
      ['선생님', 'Not gold or land. He wanted to understand nature itself. He measured plants, rocks, and weather.'],
      ['선생님', 'He took dozens of instruments, such as thermometers, barometers, and a sextant.'],
      ['해설', 'They traveled up the Orinoco River in South America and collected many plant samples.'],
      ['해설', 'The journey would have been impossible without local Indigenous people who guided them and carried loads.'],
      ['해설', 'In 1802, they climbed Chimborazo, a mountain in what is now Ecuador.'],
      ['선생님', 'Back then it was thought to be the highest mountain in the world. They did not reach the top, but they climbed very high.'],
      ['학생', 'What did they see as they climbed?'],
      ['선생님', 'The plants changed as they went up. Tropical forest, grassland, moss, and then snow and ice.'],
      ['선생님', 'He saw that climbing one mountain near the equator was like traveling from the equator to the poles.'],
      ['해설', 'Humboldt made a large drawing of the mountain, with the plants that grow at each height written on it.'],
      ['해설', 'This drawing appeared in his 1807 Essay on the Geography of Plants.'],
      ['학생', 'It was not just a list of plants. It showed how plants and climate are connected at a glance.'],
      ['선생님', 'Right. Humboldt saw nature as one connected web.'],
      ['해설', 'Near Lake Valencia in Venezuela, he studied what happened after forests were cut down.'],
      ['선생님', 'He saw that without forests, the land could not hold water, and the soil was washed away.'],
      ['학생', 'So when people change nature, water and climate are affected too.'],
      ['선생님', 'Yes. This insight still helps us think about environmental problems today.'],
      ['해설', 'Humboldt is also known as the first to draw isotherms, lines joining places with the same average temperature.'],
      ['해설', 'Later, the cold ocean current off western South America was named the Humboldt Current after him.'],
      ['해설', 'European exploration then was tied to colonial rule, and he traveled with the Spanish king’s permission.'],
      ['해설', 'Still, Humboldt sharply criticized slavery and the exploitation of Indigenous people.'],
      ['학생', 'Measuring and recording things yourself was really important.'],
      ['선생님', 'Compare the temperature and plants in the shade and in the sun at a local park. That is a small exploration.'],
      ['선생님', 'But never go alone to unfamiliar mountains or water. Always go with an adult.'],
      ['해설', 'In his later years, Humboldt wrote Cosmos, about the whole universe and nature. The first volume came out in 1845.'],
    ],
  },

  'sc2-huygens-clock': {
    title: 'Huygens and the Pendulum Clock',
    names: { 해설: 'Narrator', 선생님: 'Teacher', 학생: 'Student' },
    outro: [
      'Why were accurate clocks so important for science and sailing?',
      'If a pendulum is four times longer, its period doubles. How could you check this?',
      'One person starts an idea, and the next person finishes it. What does this mean in science?',
    ],
    lines: [
      ['해설', 'In 1656, the Dutch scientist Christiaan Huygens designed a clock driven by a pendulum.'],
      ['해설', 'In this story, a teacher tells a student about Huygens’s clock and his book.'],
      ['학생', 'Teacher, were there no clocks before that?'],
      ['선생님', 'There were mechanical clocks run by springs or weights. But they were often off by several minutes a day.'],
      ['선생님', 'So to measure time exactly, scientists watched the Sun and stars, or even counted their pulse.'],
      ['해설', 'Earlier, Galileo had noticed that a pendulum swings with a steady beat.'],
      ['해설', 'Some say he learned it by watching a swinging lamp in a cathedral, but that story is not certain.'],
      ['학생', 'What does it mean that a pendulum swings steadily?'],
      ['선생님', 'Tie a weight to a string and swing it. Big swing or small swing, one round trip takes almost the same time.'],
      ['선생님', 'The time for one round trip is called the period.'],
      ['해설', 'Huygens connected this property of the pendulum to a set of gears to keep the clock’s beat.'],
      ['선생님', 'Each swing lets a gear move one tooth forward, and the pendulum gets a small push to keep swinging.'],
      ['해설', 'The next year he got a patent in the Netherlands, and pendulum clocks quickly spread.'],
      ['학생', 'How accurate did clocks become?'],
      ['선생님', 'Clocks that were off by several minutes a day became accurate to less than a minute.'],
      ['학생', 'But does a big swing really take the same time?'],
      ['선생님', 'Sharp question. Actually, a big swing is a little slower. Huygens knew that too.'],
      ['해설', 'Huygens found a curve called a cycloid. If the weight moves along it, not a circle, the period is exactly the same.'],
      ['선생님', 'A cycloid is the curve drawn by a point on the rim of a rolling wheel.'],
      ['해설', 'In 1673, in his book The Pendulum Clock, he explained this proof and how to find a pendulum’s period.'],
      ['선생님', 'The period does not depend on the weight. It is proportional to the square root of the pendulum’s length.'],
      ['학생', 'Then if the length is four times longer, the period doubles.'],
      ['선생님', 'Right. You can check it with a string and an eraser. Time ten swings and divide by ten for accuracy.'],
      ['해설', 'Huygens also built pendulum clocks for ships, to find longitude at sea.'],
      ['해설', 'But on a rocking ship, the pendulum did not work well, and his dream did not come true.'],
      ['선생님', 'In the next century, John Harrison of England carried it on with precise clocks without pendulums.'],
      ['해설', 'Huygens also found Saturn’s moon Titan with a telescope, and he first correctly explained Saturn’s rings.'],
      ['해설', 'Huygens died in The Hague in 1695.'],
    ],
  },

  'sc2-rontgen': {
    title: 'Röntgen’s X-rays',
    names: { 해설: 'Narrator', 선생님: 'Teacher', 학생: 'Student' },
    outro: [
      'Why did Röntgen call the new rays X?',
      'What role did the black cardboard around the tube play in the experiment?',
      'People did not know the dangers of a new technology at first. What can we learn from that?',
    ],
    lines: [
      ['해설', 'In November 1895, Wilhelm Röntgen, a physicist at the University of Würzburg in Germany, was testing a cathode ray tube.'],
      ['선생님', 'A cathode ray tube is a glass tube with almost no air inside. A high voltage is put across its two ends.'],
      ['해설', 'Röntgen covered the tube completely with black cardboard and made the room dark.'],
      ['해설', 'But a paper screen coated with a glowing material, placed a little way off, began to shine faintly.'],
      ['학생', 'Teacher, didn’t some light just leak out?'],
      ['선생님', 'The cardboard blocked all ordinary light. So something must have passed through it.'],
      ['해설', 'Röntgen stayed in his lab for weeks to study this unknown thing.'],
      ['선생님', 'He put books, wooden boards, and thin metal sheets in the way. It passed through many of them.'],
      ['선생님', 'But heavy, dense metals like lead let almost none of it through.'],
      ['학생', 'What about a hand?'],
      ['선생님', 'The flesh showed faintly, and the bones showed as dark shadows.'],
      ['해설', 'He called them X-rays, meaning unknown. In math, we write an unknown value as x.'],
      ['해설', 'They also left marks on photographic plates. That December, he took a picture of his wife Anna Bertha’s hand.'],
      ['선생님', 'You could clearly see her finger bones and her ring. People could look inside a living body for the first time.'],
      ['해설', 'At the end of that December, Röntgen published his paper On a New Kind of Rays.'],
      ['학생', 'People must have been amazed.'],
      ['선생님', 'Within weeks, it was in newspapers around the world. The next year, hospitals started using it.'],
      ['선생님', 'It helped a lot in finding broken bones and pieces of metal stuck in the body.'],
      ['해설', 'Röntgen did not patent this discovery. Anyone could use it freely.'],
      ['학생', 'But is it safe when X-rays pass through the body?'],
      ['선생님', 'Good question. X-rays can damage cells, but at first nobody knew that.'],
      ['해설', 'Many early researchers and technicians who were exposed to X-rays for a long time got burns or illnesses.'],
      ['선생님', 'So today we take X-rays only when needed, quickly, and cover other parts with a lead apron.'],
      ['학생', 'Airport scanners that look inside bags use X-rays too, right?'],
      ['선생님', 'Right. They are used in hospitals, airports, and factories. They also help scientists study the structure of materials.'],
      ['해설', 'Around 1912, scientists found that X-rays are electromagnetic waves like light, but with very short wavelengths.'],
      ['해설', 'In 1901, Röntgen received the very first Nobel Prize in Physics.'],
    ],
  },

  'sc2-einstein-1905': {
    title: 'Einstein’s Miracle Year, 1905',
    names: { 해설: 'Narrator', 선생님: 'Teacher', 학생: 'Student' },
    outro: [
      'The speed of light is the same for everyone. Why did this rule change our common sense about time?',
      'How does the light clock thought experiment show time dilation without any lab equipment?',
      'A patent office clerk changed physics. What does that make you think about study, work, and dreams?',
    ],
    lines: [
      ['해설', 'In 1905, Albert Einstein, a clerk at the patent office in Bern, Switzerland, published one paper after another.'],
      ['해설', 'That year, four papers changed the foundations of physics. People often call it the miracle year.'],
      ['학생', 'Teacher, what was each of the four papers about?'],
      ['선생님', 'The first said light behaves like little packets of energy. It explained the photoelectric effect.'],
      ['선생님', 'The second was about Brownian motion, the jiggling of tiny grains in water. It opened a way to prove atoms exist.'],
      ['선생님', 'The third was special relativity. The fourth gave a formula from it about mass and energy.'],
      ['학생', 'I heard relativity is too hard.'],
      ['선생님', 'It starts from just two rules. Let’s go one by one.'],
      ['선생님', 'First, the laws of physics are the same on a smoothly moving train and on the ground.'],
      ['학생', 'That is like Galileo’s ship example.'],
      ['선생님', 'Right. Second, the speed of light is always the same, no matter how the source or the viewer moves.'],
      ['학생', 'Is that strange?'],
      ['선생님', 'If you throw a ball forward on a moving train, from the ground it looks faster by the train’s speed.'],
      ['선생님', 'But light is different. Whoever measures it gets about three hundred thousand kilometers per second.'],
      ['해설', 'Einstein showed that if we accept both rules, we must change our common sense about time and space.'],
      ['선생님', 'Imagine a light clock. It ticks each time light goes up and down between two mirrors.'],
      ['학생', 'What if we put that clock on a moving train?'],
      ['선생님', 'From the ground, the train is moving, so the light travels a longer, slanted path.'],
      ['선생님', 'The speed of light is the same, but the path is longer. So each tick takes more time.'],
      ['학생', 'So a moving clock seems to run slow!'],
      ['선생님', 'Yes. It is called time dilation. It becomes clear only near the speed of light.'],
      ['해설', 'The same idea leads to another result. Two events at the same time for one person may not be so for another.'],
      ['해설', 'This effect was later confirmed by experiments. Particles called muons, falling from the sky, are a good example.'],
      ['선생님', 'Muons disappear very quickly. But they fly near the speed of light, so their time slows, and they reach the ground.'],
      ['해설', 'Satellite navigation also needs clock corrections from relativity to tell your position accurately.'],
      ['학생', 'The formula says energy equals mass times the speed of light squared, right? What does it mean?'],
      ['선생님', 'It means mass is a form of energy. The speed of light is huge, so even a little mass holds a lot of energy.'],
      ['해설', 'Einstein won the 1921 Nobel Prize in Physics, not for relativity, but for explaining the photoelectric effect.'],
    ],
  },
};
