// 청소년 영어 원고 (중학생 이상). 키 = stories/teen-shake2.js 의 이야기 id.
// 셰익스피어 원작(퍼블릭 도메인)을 한국어 각색의 흐름대로 쉬운 현대 영어로 새로 씀. 원작의 이름과 이름난 구절 몇 개만 살림.
export default {
  'tsp2-lear-1': {
    title: 'King Lear, Part 1',
    names: { 해설: 'Narrator', 리어: 'King Lear', 고너릴: 'Goneril', 리건: 'Regan', 코딜리아: 'Cordelia', 켄트: 'Kent', 에드먼드: 'Edmund', 글로스터: 'Gloucester' },
    outro: [
      'Why did Lear believe sweet words more than honest ones?',
      'When you compare quiet Cordelia with her two flattering sisters, what do you notice?',
      'Between pleasant words and honest words, which do I welcome more in my own life?',
    ],
    lines: [
      ['해설', 'Long ago, Lear, the old king of Britain, decided to set down the burden of the crown.'],
      ['해설', 'He would split his kingdom among his three daughters. The one who loved him most would get the most.'],
      ['리어', 'Now, tell me. Which of you loves your father most? I will give land to match your love.'],
      ['고너릴', 'Father, my love is greater than heaven and earth together. Nothing in the world is dearer than you.'],
      ['리건', 'My sister speaks my heart, but she says too little. I have no joy except your love.'],
      ['해설', 'The two sisters received wide, rich lands. Then Lear turned to his youngest, Cordelia.'],
      ['해설', 'Their smooth words made Cordelia’s heart heavy. Quietly, she said she had nothing to add.'],
      ['코딜리아', 'I love you exactly as a daughter should, no more and no less. I cannot puff up my words.'],
      ['코딜리아', 'If my sisters love only you, why do they have husbands? When I marry, I will share half my heart.'],
      ['리어', 'You, my dearest, are so cold to me? Very well. From today, you are no daughter of mine.'],
      ['해설', 'Kent, a loyal lord, stepped forward. He boldly said the king could not tell truth from flattery.'],
      ['켄트', 'Your Majesty, few words do not mean little love. Please take back this hasty decision.'],
      ['리어', 'You dare to oppose me? Leave this kingdom in six days. If you are found here after ten, you die.'],
      ['해설', 'With no dowry, the Duke of Burgundy took back his offer. But the King of France made Cordelia his queen.'],
      ['코딜리아', 'Sisters, take good care of Father. I hope your words were true.'],
      ['해설', 'As soon as Cordelia left, the two sisters began whispering that their father had grown old and moody.'],
      ['해설', 'Lear’s lord Gloucester had two sons. Edgar was the elder, and Edmund was born outside marriage.'],
      ['에드먼드', 'Must I stand behind my brother just because of my birth? I will use my wits and take his land.'],
      ['해설', 'Edmund forged a letter saying Edgar planned to kill their father, and let Gloucester find it.'],
      ['글로스터', 'Edgar has such a terrible plan? Find him at once!'],
      ['해설', 'Edmund told Edgar that their father was furious and he must hide. Edgar fled without knowing why.'],
      ['해설', 'Meanwhile, Lear gave up his crown and stayed at Goneril’s castle with a hundred knights.'],
      ['해설', 'Kent, banished, changed his clothes and his way of speaking, and became Lear’s servant in secret.'],
      ['해설', 'Goneril said her father’s knights were too noisy, and told her servants to treat him coldly.'],
      ['고너릴', 'Father, cut the number of your knights. This castle has become as rowdy as a tavern. Act your age.'],
      ['리어', 'Is this how I am treated? Am I still Lear? Is this a dream, or is my mind failing?'],
      ['리어', 'No knife cuts a father deeper than a thankless child. I will go to Regan.'],
      ['해설', 'Shaking with anger, Lear rode to his second daughter. He believed Regan, at least, would welcome him.'],
      ['해설', 'The story of King Lear comes from an old British legend about a king named Leir.'],
    ],
  },

  'tsp2-lear-2': {
    title: 'King Lear, Part 2',
    names: { 해설: 'Narrator', 리어: 'King Lear', 리건: 'Regan', 고너릴: 'Goneril', 광대: 'Fool', 에드거: 'Edgar', 에드먼드: 'Edmund', 글로스터: 'Gloucester' },
    outro: [
      'Having lost everything and standing in the storm, what did Lear newly understand?',
      'Gloucester learns the truth only after losing his eyes. What might that mean?',
      'What does the way a society treats old and weak people show about it?',
    ],
    lines: [
      ['해설', 'Last time, King Lear gave his kingdom to the two daughters with sweet words and sent away his honest youngest.'],
      ['해설', 'Treated badly by Goneril, Lear went to Regan. Regan and her husband were staying at Gloucester’s castle.'],
      ['해설', 'Kent, sent ahead with a letter, got into a quarrel. Regan’s husband, the Duke of Cornwall, put him in the stocks.'],
      ['리어', 'Who tied up my man like this? To insult the king’s messenger is to insult me.'],
      ['해설', 'Then Goneril arrived too. The two daughters stood side by side and looked down at their father.'],
      ['리건', 'Father, go back to my sister and say sorry. If you come to me, bring only twenty-five knights.'],
      ['고너릴', 'Why even twenty-five? Ten or five? Our servants can wait on you.'],
      ['리건', 'Why do you need even one?'],
      ['리어', 'Oh, reason not the need! If people had only what they need to live, they would be no better than beasts.'],
      ['리어', 'I will not cry in front of you. I would rather face the wind and rain with this old body.'],
      ['해설', 'Lear rushed out into the fields as a storm came. Behind him, his daughters locked the gates.'],
      ['해설', 'Thunder tore the sky and rain poured down. On the wild heath, Lear shouted with his white hair flying.'],
      ['리어', 'Pour down, wind and rain! I never gave you a kingdom. You owe me nothing, so strike me as you will.'],
      ['광대', 'Uncle, on a night like this, a dry roof beats the open air. Just bow your head to your daughters.'],
      ['해설', 'Kent, still in disguise, led the king to a nearby hut. Inside, a beggar in rags was crouching.'],
      ['해설', 'It was Edgar, now a hunted man. He was hiding by pretending to be a mad beggar called Poor Tom.'],
      ['에드거', 'Poor Tom is cold! A devil has dragged Tom through fire and through swamps.'],
      ['리어', 'Looking at you, with no clothes or home, I see it. Without a crown, every man is this weak.'],
      ['리어', 'When I ruled, I took too little care of the poor who shivered without a roof.'],
      ['해설', 'Around that time, Gloucester disobeyed the daughters’ orders and tried to help the king in secret.'],
      ['해설', 'He even told his son Edmund about a letter saying a French army was coming to help the king.'],
      ['에드먼드', 'What my father loses, I will gain. When the old fall, the young rise.'],
      ['해설', 'Edmund went straight to Cornwall and betrayed his father. As a reward, he became the new Earl of Gloucester.'],
      ['해설', 'Gloucester sent the king to safety at Dover. When he returned home, Cornwall and Regan seized him.'],
      ['글로스터', 'You left an old king out in the storm. I could not just stand by and watch such cruelty.'],
      ['해설', 'As punishment, Cornwall blinded Gloucester. A servant tried to stop him and badly wounded Cornwall with a sword.'],
      ['글로스터', 'Edmund, my son, where are you? Avenge this terrible deed.'],
      ['리건', 'The son you call for is the one who reported you. He hates you.'],
      ['글로스터', 'Then Edgar was innocent. Heaven, forgive my foolishness, and protect that boy.'],
      ['해설', 'King Lear tells two stories side by side: Lear and his daughters, and Gloucester and his sons.'],
    ],
  },

  'tsp2-lear-3': {
    title: 'King Lear, Part 3',
    names: { 해설: 'Narrator', 글로스터: 'Gloucester', 에드거: 'Edgar', 리어: 'King Lear', 코딜리아: 'Cordelia', 에드먼드: 'Edmund' },
    outro: [
      'What meaning does the short reunion of Lear and Cordelia have in this tragedy?',
      'Why did Edgar hide who he was while he guided his blind father?',
      'Can we say there is always time left to clear up misunderstandings in a family?',
    ],
    lines: [
      ['해설', 'Last time, Lear wandered in the storm after his daughters drove him out. Gloucester lost his eyes for helping him.'],
      ['해설', 'Gloucester, thrown out of his castle, met Edgar dressed as a beggar. Hiding who he was, Edgar took his father’s hand.'],
      ['글로스터', 'Take me to the edge of the high cliff at Dover. There I want to end this painful life.'],
      ['해설', 'Edgar told him a flat field was the cliff. Gloucester threw himself forward and simply fell to the ground.'],
      ['에드거', 'Sir, you fell from that great height and lived. Heaven has kept you alive.'],
      ['글로스터', 'Then from now on, I will bear my pain until it leaves me by itself.'],
      ['해설', 'Meanwhile, Cordelia heard what had happened to her father. She landed in Britain with a French army.'],
      ['해설', 'Soldiers found Lear wandering in the fields, his mind confused, wearing a crown of wildflowers and weeds.'],
      ['해설', 'When Lear woke from a deep sleep, Cordelia was sitting before him.'],
      ['리어', 'Where am I? I am a foolish old man, not in my right mind. But you look like my youngest child.'],
      ['리어', 'If you hate me, I cannot blame you. Your sisters had no reason to wrong me, but you do.'],
      ['코딜리아', 'No cause, no cause. I have never once blamed you, Father.'],
      ['해설', 'But the joy was short. The British army led by Edmund won, and Lear and Cordelia were captured.'],
      ['리어', 'What does prison matter? With you, we will talk of the past and ask each other’s forgiveness.'],
      ['해설', 'Edmund secretly handed an officer a written order to kill them both.'],
      ['해설', 'Goneril and Regan both fought to win Edmund. In the end, Goneril poisoned her sister.'],
      ['해설', 'Goneril’s husband, the Duke of Albany, got hold of a letter showing her plot. He named Edmund a traitor.'],
      ['해설', 'Then a knight with his face hidden by a helmet appeared and challenged Edmund. It was Edgar.'],
      ['에드거', 'You betrayed your father and your brother, and plotted against the king. My sword will judge you.'],
      ['해설', 'Edmund fell, badly wounded. Edgar took off his helmet and showed who he was.'],
      ['에드거', 'At last our father knew I was his son. But he could not bear the joy and grief together, and he died.'],
      ['해설', 'Meanwhile Regan died of the poison, and Goneril, her plot revealed, took her own life.'],
      ['에드먼드', 'Before I die, I want to do one good thing. Send someone to the prison now. Those two are in danger.'],
      ['해설', 'Soldiers rushed there, but it was too late. Lear appeared, holding the dead Cordelia in his arms.'],
      ['리어', 'Howl, howl! Are you men of stone? Why do you not weep? She is gone forever.'],
      ['리어', 'If even a feather moves, she lives. Look, do her lips not seem to move?'],
      ['해설', 'Gazing at his daughter’s face, Lear died. Kent, beside him, said he would soon follow his master.'],
      ['해설', 'Albany and Edgar survived. They carried the heavy task of rebuilding a wounded kingdom.'],
      ['해설', 'King Lear was first printed as a book in 1608.'],
    ],
  },

  'tsp2-othello-1': {
    title: 'Othello, Part 1',
    names: { 해설: 'Narrator', 이아고: 'Iago', 브라반쇼: 'Brabantio', 공작: 'Duke', 오셀로: 'Othello', 데스데모나: 'Desdemona' },
    outro: [
      'Why could people not easily accept the marriage of Othello and Desdemona?',
      'Which words and actions show that Iago’s outside and inside are different?',
      'How does judging someone by their looks or background still appear today?',
    ],
    lines: [
      ['해설', 'In Venice, the city on the water, there lived a famous general named Othello. He was a brave soldier called the Moor.'],
      ['해설', 'His ensign Iago was boiling inside. Othello had made young Cassio his lieutenant instead of him.'],
      ['이아고', 'A man who learned war from books is lieutenant? I will pretend to follow the general, but only for myself.'],
      ['해설', 'That night, Othello secretly married Desdemona, daughter of the senator Brabantio.'],
      ['해설', 'Iago stirred up Roderigo, who loved Desdemona, to shout outside Brabantio’s house in the middle of the night.'],
      ['해설', 'With rough words mocking Othello’s skin color and origin, the two set Brabantio’s anger on fire.'],
      ['해설', 'Those words carried the prejudice of European society at the time, which looked down on Africans.'],
      ['브라반쇼', 'My daughter would never go to such a man by choice. He must have used magic or drugs!'],
      ['해설', 'At the same hour, the senate held an urgent meeting. A Turkish fleet was sailing toward Cyprus.'],
      ['공작', 'Brave General Othello, you come at the right time. You must go to Cyprus at once.'],
      ['브라반쇼', 'My lord, this man stole my daughter. Without magic, she would never make such a choice.'],
      ['오셀로', 'It is true that I married your daughter. But I used no spells.'],
      ['오셀로', 'I only told her my stories. How I was sold as a slave, and how I crossed deserts and seas.'],
      ['오셀로', 'Desdemona wept at my stories. Her gentle heart won mine.'],
      ['공작', 'With stories like that, no magic was needed. Let us hear from your daughter herself.'],
      ['해설', 'Desdemona was called in. She spoke clearly before her father and the senators.'],
      ['데스데모나', 'Father, I will never forget that you raised me. But now my husband is General Othello.'],
      ['데스데모나', 'I saw his face in his mind, not in his skin. Let me go with him to Cyprus.'],
      ['브라반쇼', 'Look to her, Moor, if you have eyes to see. She deceived her father, and may deceive you.'],
      ['해설', 'These words stayed like a seed, and later grew in Othello’s heart.'],
      ['해설', 'Othello trusted Iago as the most honest man of all, and asked him to bring his wife to Cyprus.'],
      ['오셀로', 'Iago, I trust you with my wife. Let your wife Emilia look after her.'],
      ['해설', 'In despair, Roderigo said he would drown himself. Iago calmed him and told him to gather money instead.'],
      ['이아고', 'Put money in your purse and go to Cyprus. That marriage will not last. She will soon be yours.'],
      ['해설', 'When Roderigo left, Iago, alone, showed his true plan.'],
      ['이아고', 'The general believes people are what they seem. That honest nature will be the trap that brings him down.'],
      ['이아고', 'I will whisper that handsome, smooth-talking Cassio is too close to his wife. Then both will fall.'],
      ['해설', 'And so Iago’s dark plan began to grow, feeding on people’s trust.'],
      ['해설', 'The plot of Othello comes from a story collection by the Italian writer Cinthio, published in 1565.'],
    ],
  },

  'tsp2-othello-2': {
    title: 'Othello, Part 2',
    names: { 해설: 'Narrator', 오셀로: 'Othello', 데스데모나: 'Desdemona', 캐시오: 'Cassio', 이아고: 'Iago', 에밀리아: 'Emilia' },
    outro: [
      'How did a doubt without any proof turn into certainty for Othello?',
      'Which of Othello’s weak points and old wounds did Iago dig into?',
      'If you have ever doubted someone after hearing only another person’s words, what did you miss?',
    ],
    lines: [
      ['해설', 'Last time, Othello married Desdemona, and Iago, who missed the lieutenant’s post, secretly planned revenge.'],
      ['해설', 'The Turkish fleet heading for Cyprus was scattered by a fierce storm. The war ended without a battle.'],
      ['오셀로', 'Seeing your face, I forget the storms at sea. I fear no happier day will ever come.'],
      ['데스데모나', 'Our love and joy will only grow day by day. Heaven will make it so.'],
      ['해설', 'That night the island held a victory feast. Iago kept pushing drinks on Cassio, who could not hold his wine.'],
      ['해설', 'Drunk, Cassio fell for Roderigo’s taunts and swung his sword. He even wounded Montano, who tried to stop him.'],
      ['오셀로', 'Cassio, I care for you. But you are no longer my lieutenant.'],
      ['캐시오', 'A few drinks, and my good name is in the mud. Who will ever trust me now?'],
      ['이아고', 'Do not worry. The general’s wife moves his heart. Ask her, and you will get your post back.'],
      ['해설', 'It sounded like kind advice. But this was exactly the trap Iago had set.'],
      ['해설', 'The next day Cassio came, and Desdemona promised to persuade her husband.'],
      ['데스데모나', 'Do not worry, Cassio. I will beg and beg until my husband calls you back.'],
      ['해설', 'Then Othello and Iago came near. Ashamed to face the general, Cassio hurried away.'],
      ['이아고', 'Why, he slipped away the moment he saw you, sir. Why would he do that?'],
      ['해설', 'The more Desdemona begged him to forgive Cassio, the darker the shadow in Othello’s heart grew.'],
      ['이아고', 'Beware of jealousy, my lord. It is the green-eyed monster that eats the heart it lives in.'],
      ['이아고', 'Just watch your wife. They say Venetian women do many things behind their husbands’ backs.'],
      ['해설', 'Iago used the fact that Othello was a stranger to Venetian ways. He turned Othello’s difference into a weakness.'],
      ['오셀로', 'Because I look different from the people here and am older, has she turned away from me?'],
      ['해설', 'Iago’s words touched the wound of prejudice Othello had long endured. He began to lose faith in himself.'],
      ['해설', 'Then Desdemona dropped her husband’s first gift, a handkerchief with strawberries on it. Emilia picked it up.'],
      ['에밀리아', 'My husband kept asking me to steal this. What does he want it for?'],
      ['해설', 'Iago took the handkerchief and secretly dropped it in Cassio’s room.'],
      ['오셀로', 'Iago, show me proof that my wife is false. If you have no proof, I will not forgive you.'],
      ['이아고', 'You know the handkerchief with strawberries you gave her? Today I saw Cassio wipe his beard with it.'],
      ['해설', 'It was a lie. But to Othello, blind with rage, it sounded like the surest proof.'],
      ['오셀로', 'So my deep trust falls apart like this. All that is left to me is cold revenge.'],
      ['오셀로', 'Iago, within three days, get rid of Cassio. From today, you are my lieutenant.'],
      ['이아고', 'I am your own forever.'],
      ['해설', 'The first act of Othello takes place in Venice, and the rest on the island of Cyprus.'],
    ],
  },

  'tsp2-othello-3': {
    title: 'Othello, Part 3',
    names: { 해설: 'Narrator', 오셀로: 'Othello', 데스데모나: 'Desdemona', 비앙카: 'Bianca', 로도비코: 'Lodovico', 에밀리아: 'Emilia' },
    outro: [
      'Is Othello’s tragedy the fault of Iago’s lies, or of Othello’s own doubt?',
      'What courage does Emilia show in the scene where she reveals the truth?',
      'What does our society need so that prejudice and rumor do not destroy a person?',
    ],
    lines: [
      ['해설', 'Last time, Iago used a handkerchief to make Othello believe Desdemona and Cassio were close.'],
      ['오셀로', 'My lady, show me the handkerchief I gave you. It is a precious thing from my mother.'],
      ['데스데모나', 'I do not have it now. But first, please listen to me about Cassio.'],
      ['해설', 'The more she defended Cassio, the more Othello took it as proof that she was hiding something.'],
      ['해설', 'Iago hid Othello, then asked Cassio about his girlfriend Bianca. Cassio laughed and joked.'],
      ['해설', 'Watching only from far away, Othello believed Cassio was laughing at his wife. Then Bianca came with the handkerchief.'],
      ['비앙카', 'Which woman does this handkerchief belong to? You want me to copy the pattern? I will not!'],
      ['해설', 'Then Lodovico arrived from Venice. His orders called Othello home and gave the island to Cassio.'],
      ['해설', 'When Desdemona said she was glad for Cassio, Othello struck his wife in front of everyone.'],
      ['로도비코', 'Nobody in Venice would believe this. Is this the noble general everyone praised?'],
      ['해설', 'That night, as Emilia helped her to bed, Desdemona sang a sad willow song from her mother’s maid.'],
      ['데스데모나', 'Emilia, are there really wives who deceive their husbands? I would not do it for the whole world.'],
      ['에밀리아', 'Wives feel and hurt just like their husbands. When husbands do wrong, wives learn it from them.'],
      ['해설', 'That same night, Roderigo, tricked by Iago, attacked Cassio in the dark. Iago joined in and wounded Cassio’s leg.'],
      ['해설', 'Afraid of being found out, Iago secretly stabbed the wounded Roderigo to silence him.'],
      ['해설', 'Othello entered his sleeping wife’s room with a candle.'],
      ['오셀로', 'Her sleeping face is so pure. I must finish this before my heart grows weak.'],
      ['데스데모나', 'I have done nothing wrong. Ask Cassio yourself. Please, let me live at least tonight.'],
      ['해설', 'Othello would not listen. He smothered his wife with a pillow.'],
      ['해설', 'Emilia knocked and came in. Seeing Desdemona lying still, she screamed.'],
      ['오셀로', 'She deceived me and was close to Cassio. Your husband Iago told me everything.'],
      ['에밀리아', 'My husband? I found that handkerchief and gave it to him! You were fooled by a lie.'],
      ['해설', 'People rushed in and the truth came out. Iago stabbed his wife Emilia and ran, but he was caught.'],
      ['오셀로', 'What have I done? With one doubt, I have lost the most precious person in the world.'],
      ['해설', 'When they asked why he had done it, Iago kept his mouth shut to the end.'],
      ['로도비코', 'Tie him up tightly. The new governor, Cassio, will decide the right punishment for his crimes.'],
      ['오셀로', 'When you speak of me, do not make me better or worse. Say only that one not easily jealous was deceived.'],
      ['해설', 'Then Othello took his own life with a hidden dagger and fell beside his wife.'],
      ['해설', 'Othello was first printed as a book in 1622, after Shakespeare’s death.'],
    ],
  },
};
