// 청소년 영어 원고 (중학생 이상). 키 = stories/teen-sillok2.js 의 이야기 id.
// 『조선왕조실록』과 역사 기록을 바탕으로 한국어 각색의 흐름대로 쉬운 영어로 새로 씀.
// 실록 원문을 옮기거나 인물의 말을 지어내 기록 인용처럼 쓰지 않음. 고유 낱말은 로마자로 쓰고 짧게 풀이.
const N = { 해설: 'Narrator', 선생님: 'Teacher', 학생: 'Student' };

export default {
  'sl-11': {
    title: 'The Imjin War and the King’s Flight',
    names: N,
    outro: [
      'King Seonjo left the capital and fled north. What results did that choice bring to the country?',
      'If one king’s reign has two different Sillok, how should we read those records?',
      'In a great crisis, what do you think a leader needs most of all?',
    ],
    lines: [
      ['해설', 'In 1592, Toyotomi Hideyoshi, who had united Japan, sent his army across the sea.'],
      ['해설', 'The Japanese army landed at Busan, and the forts of Busanjin and Dongnae fell one after another.'],
      ['해설', 'Koreans call it the Imjin War, because it began in the year of Imjin.'],
      ['학생', 'Was Joseon not ready at all?'],
      ['선생님', 'The Japanese moved very fast with their muskets. Joseon was badly shocked.'],
      ['해설', 'The court sent General Sin Rip to stop them, but he lost badly at Tangeumdae in Chungju.'],
      ['해설', 'Hearing the news, King Seonjo decided to leave the capital and flee north.'],
      ['해설', 'The royal party passed Gaeseong and Pyeongyang and went all the way to Uiju, by the Amnok River.'],
      ['학생', 'The king left the capital behind? How did the people feel?'],
      ['선생님', 'Records say they were deeply disappointed and angry. The palaces in the capital also burned around this time.'],
      ['선생님', 'But who set the fires, and when, is still read in different ways.'],
      ['해설', 'On the road, Seonjo named his second son, Gwanghaegun, as crown prince.'],
      ['해설', 'Gwanghaegun led part of the court and traveled through the provinces, gathering soldiers and support.'],
      ['해설', 'The court asked Ming China for help, and a Ming army crossed the Amnok River.'],
      ['해설', 'In 1593, the Joseon and Ming forces took back the city of Pyeongyang.'],
      ['학생', 'Admiral Yi Sun-sin fought at sea, right?'],
      ['선생님', 'Yes. His navy won battle after battle in the south and blocked the Japanese sea routes.'],
      ['선생님', 'Volunteer fighters, called uibyeong, also rose up in their home towns, like Gwak Jae-u.'],
      ['해설', 'When peace talks failed, Japan invaded again in 1597. This is called the Jeongyu War.'],
      ['해설', 'Hideyoshi died in 1598, the Japanese army pulled out, and the seven-year war ended.'],
      ['학생', 'How was this war written in the Sillok?'],
      ['선생님', 'Here is an interesting point. There are two Sillok for King Seonjo’s reign.'],
      ['선생님', 'One was made under Gwanghaegun. The other was rewritten later by the Westerners, a political group called Seoin.'],
      ['학생', 'They wrote the same period twice?'],
      ['선생님', 'When a new group took power, they wanted to judge the people of that time again.'],
      ['선생님', 'So we should put the two records side by side and ask who wrote them, and why.'],
      ['해설', 'The war was over, but the land was ruined, and many people had died or been taken away as captives.'],
      ['해설', 'The Revised Sillok of King Seonjo was compiled under the Seoin, after they took power in 1623.'],
    ],
  },

  'sl-12': {
    title: 'Gwanghaegun and the Coup of 1623',
    names: N,
    outro: [
      'Between Ming and Later Jin, Gwanghaegun chose his own path. What did Joseon gain and lose from it?',
      'A dethroned king’s record was called a diary, not a Sillok. What does that tell us?',
      'Thinking of small countries between great powers today, what can we learn from Gwanghaegun’s problem?',
    ],
    lines: [
      ['해설', 'In 1608, King Seonjo died, and Gwanghaegun came to the throne.'],
      ['해설', 'The new king had to heal the wounds the war had left behind.'],
      ['해설', 'In his first year, he started the Daedong Law in Gyeonggi Province.'],
      ['학생', 'What is the Daedong Law?'],
      ['선생님', 'People used to pay local goods as tax. This law let them pay mostly in rice, to ease their burden.'],
      ['해설', 'In 1610, the doctor Heo Jun finished his great medical book, Donguibogam, and presented it to the king.'],
      ['해설', 'Around then, in Manchuria, Nurhaci united the Jurchen people and founded the Later Jin.'],
      ['해설', 'Ming China was fighting the Later Jin, and it demanded that Joseon send troops.'],
      ['학생', 'Ming had helped Joseon in the Imjin War, so it was hard to say no.'],
      ['선생님', 'Right. But if Joseon made an enemy of the Later Jin, it could become a battlefield again.'],
      ['해설', 'Gwanghaegun sent an army under the commander Gang Hong-rip.'],
      ['해설', 'In 1619, the army fought beside the Ming, lost badly, and Gang Hong-rip surrendered to the Later Jin.'],
      ['선생님', 'A story says the king told him beforehand to watch the situation and act carefully.'],
      ['선생님', 'But scholars disagree about how far that order really went.'],
      ['해설', 'After that, Gwanghaegun still tried not to lean too far toward either side.'],
      ['해설', 'Meanwhile, inside the palace, the fight over the throne went on.'],
      ['해설', 'Seonjo’s young son, Grand Prince Yeongchang, was sent to Ganghwa Island and died there.'],
      ['해설', 'His mother, Queen Dowager Inmok, was locked away in the West Palace.'],
      ['학생', 'That must have given his enemies a good excuse.'],
      ['선생님', 'Yes. The Seoin blamed him for killing a brother, locking up a mother, and turning away from Ming.'],
      ['해설', 'In 1623, the Seoin raised troops, drove Gwanghaegun out, and made Injo the king.'],
      ['해설', 'This is called the Injo Restoration. Gwanghaegun was exiled and later died on Jeju Island.'],
      ['학생', 'How was his reign recorded?'],
      ['선생님', 'Because he lost the throne, his record is called the Diary of Gwanghaegun, not a Sillok.'],
      ['선생님', 'So we must also think about the views of the people who wrote it.'],
      ['학생', 'His diplomacy was practical, but his politics were judged differently.'],
      ['선생님', 'Seeing many sides together is the real skill of reading history.'],
      ['해설', 'Yeonsangun and Gwanghaegun are the two Joseon kings who never received a royal temple name.'],
    ],
  },

  'sl-13': {
    title: 'The Qing Invasion and Namhansanseong',
    names: N,
    outro: [
      'Fight to the end, or make peace? Which was the better choice for Joseon at that time?',
      'Why is it hard to say only one side was right when we read about both groups?',
      'When principles and reality clash, what standard can we use to judge today?',
    ],
    lines: [
      ['해설', 'After the 1623 coup, Joseon stayed close to Ming and kept away from the Later Jin.'],
      ['해설', 'In 1627, the Later Jin invaded Joseon. This is called the Jeongmyo War.'],
      ['해설', 'Joseon promised to treat the Later Jin as an elder brother, and the fighting stopped.'],
      ['해설', 'In 1636, the Later Jin renamed itself Qing and demanded that Joseon become its subject.'],
      ['학생', 'So they wanted Joseon to go from brother to servant.'],
      ['선생님', 'Yes. The Joseon court refused.'],
      ['해설', 'That winter, Hong Taiji, the Qing emperor, led a huge army into Joseon himself.'],
      ['해설', 'The Qing army came so fast that King Injo could not reach Ganghwa Island.'],
      ['해설', 'Instead, he went into the mountain fortress of Namhansanseong.'],
      ['해설', 'There was not enough food inside, and the cold was terrible.'],
      ['학생', 'What did they argue about inside the fortress?'],
      ['선생님', 'One group said to fight to the end. The other said to make peace and save the country.'],
      ['선생님', 'Kim Sang-heon led the side that wanted to fight, and Choe Myeong-gil led the side that wanted peace.'],
      ['학생', 'Choe Myeong-gil must have been called a coward.'],
      ['선생님', 'He was blamed a lot. But he believed it was the way to protect the country and its people.'],
      ['해설', 'Armies from the provinces tried to come to the rescue, but the Qing blocked them.'],
      ['해설', 'Then Ganghwa Island, where the royal family had taken shelter, also fell.'],
      ['해설', 'Early in 1637, Injo finally came out of the fortress to surrender.'],
      ['해설', 'At Samjeondo, by the Han River, he bowed to the Qing emperor as a subject.'],
      ['학생', 'The king himself had to do that? It must have been a deep shame.'],
      ['선생님', 'That is why it stayed a painful memory for the people of Joseon for a long time.'],
      ['해설', 'Crown Prince Sohyeon and Grand Prince Bongnim were taken as hostages to Shenyang, the Qing capital.'],
      ['해설', 'Hong Ik-han, Yun Jip, and O Dal-je, who had argued for fighting, were taken to Shenyang and executed.'],
      ['해설', 'Later people called them the Three Scholars.'],
      ['해설', 'Many ordinary people were also taken away as captives, and many never came home.'],
      ['학생', 'So who was right, Kim Sang-heon or Choe Myeong-gil?'],
      ['선생님', 'It is hard to say. One tried to keep a principle, and the other tried to survive.'],
      ['선생님', 'Read what both men said, and judge for yourself.'],
      ['해설', 'Samjeondo is in today’s Songpa area of Seoul. The stone the Qing made Joseon set up there is called the Samjeondo Stele.'],
    ],
  },

  'sl-14': {
    title: 'King Hyojong and the Northern Campaign',
    names: N,
    outro: [
      'Hyojong’s plan to attack the north never happened. What did it still leave to Joseon?',
      'Troops trained to fight the Qing went to war at the Qing’s request. What does that record tell us?',
      'Can a goal that is hard to reach still bring people together?',
    ],
    lines: [
      ['해설', 'After the war, Crown Prince Sohyeon and Grand Prince Bongnim stayed in Shenyang for many years.'],
      ['해설', 'In 1645, Crown Prince Sohyeon came home, but he died soon after.'],
      ['학생', 'Right after he came back? What happened?'],
      ['선생님', 'Some people have doubts about his death, but we cannot call any of them a proven fact.'],
      ['해설', 'King Injo did not choose Sohyeon’s son. He made Grand Prince Bongnim the new crown prince.'],
      ['해설', 'In 1649, Injo died, and Bongnim became king. He is King Hyojong.'],
      ['해설', 'Hyojong wanted to repay the shame by attacking the Qing in the north. This plan was called bukbeol.'],
      ['학생', 'Could they really attack the Qing?'],
      ['선생님', 'So Hyojong worked hard to build up the army. He made military units like the Eoyeongcheong stronger.'],
      ['해설', 'Song Si-yeol and other Seoin scholars also supported the northern campaign.'],
      ['선생님', 'But Song Si-yeol said the king’s virtue and the order of the state should come before soldiers.'],
      ['학생', 'So people had different ideas, even about the same plan.'],
      ['해설', 'In 1653, a ship carrying the Dutchman Hendrick Hamel and his crew reached Jeju Island.'],
      ['해설', 'The court brought them to Seoul and put them in an army unit.'],
      ['선생님', 'About thirteen years later, Hamel escaped from Joseon and went back to the Netherlands.'],
      ['해설', 'At that time, the Qing were fighting Russian forces along the Amur River in the far north.'],
      ['해설', 'At the Qing’s request, Joseon sent musket soldiers there twice.'],
      ['학생', 'The army trained to attack the Qing went to help the Qing?'],
      ['선생님', 'It is ironic. But the Joseon musket soldiers showed real skill in those battles.'],
      ['해설', 'Getting ready for the campaign also put a heavy burden on the people.'],
      ['해설', 'The Qing grew stronger and stronger, and the campaign became harder to imagine.'],
      ['해설', 'In 1659, Hyojong died without reaching his goal.'],
      ['해설', 'Then a debate broke out over how long his stepmother, Queen Dowager Jaui, should wear mourning clothes.'],
      ['선생님', 'This is called the yesong, the rites debate. It made the Seoin and Namin groups bitter rivals.'],
      ['학생', 'They fought that hard over mourning clothes? That is surprising.'],
      ['선생님', 'Underneath was a deeper question: what kind of rightful king was Hyojong?'],
      ['선생님', 'Both the campaign and the debate were questions left by the wounds of the Qing invasion.'],
      ['해설', 'Hamel’s account of his years in Joseon is one of the earliest detailed Western records of Korea.'],
    ],
  },

  'sl-15': {
    title: 'King Sukjong and the Sudden Shifts',
    names: N,
    outro: [
      'King Sukjong replaced the ruling group again and again. How did that change Joseon politics?',
      'If the judgment of each side flipped with each change, how should we read the records of that time?',
      'When a person in a drama is different from the person in the records, what should we trust?',
    ],
    lines: [
      ['해설', 'In 1674, Sukjong became king while he was still a boy.'],
      ['해설', 'At that time, after the rites debates, the Seoin and Namin groups stood sharply against each other.'],
      ['학생', 'What does the word hwanguk mean?'],
      ['선생님', 'It means changing the board. The king replaced the whole ruling group at once.'],
      ['해설', 'In 1680, Sukjong pushed out the Namin and brought in the Seoin. This is the Gyeongsin Hwanguk.'],
      ['해설', 'Leading Namin figures were executed or sent into exile.'],
      ['해설', 'Later, the Seoin split into the Noron and the Soron over how hard to punish the Namin.'],
      ['해설', 'In 1689, Sukjong wanted to name the son of his royal concubine, Lady Jang, as his heir.'],
      ['해설', 'When the Seoin opposed it, Sukjong drove them out and called the Namin back.'],
      ['해설', 'This is the Gisa Hwanguk. Song Si-yeol, the Seoin leader, was ordered to take poison and died.'],
      ['해설', 'Queen Inhyeon lost her place, and Lady Jang became queen.'],
      ['학생', 'Is this the famous Jang Hui-bin?'],
      ['선생님', 'Yes. Hui-bin was her title before she became queen, and again after she was lowered.'],
      ['해설', 'In 1694, Sukjong pushed out the Namin again and brought back the Seoin. This is the Gapsul Hwanguk.'],
      ['해설', 'Queen Inhyeon returned, and Lady Jang was lowered to Hui-bin again.'],
      ['학생', 'The board flipped every few years. Why?'],
      ['선생님', 'Many say he made the groups fight each other to make the king’s power stronger.'],
      ['선생님', 'But the price was endless revenge, with each side killing the other.'],
      ['해설', 'In 1701, Queen Inhyeon died of illness.'],
      ['해설', 'Then Hui-bin was accused of cursing the queen, and Sukjong ordered her to take poison.'],
      ['학생', 'In the dramas I saw, one was clearly good and the other was clearly evil.'],
      ['선생님', 'Later novels and dramas often showed them that way. The Sillok gives a different picture.'],
      ['선생님', 'And the Sillok is not free from the view of the group that compiled it, so read it carefully.'],
      ['해설', 'Hui-bin’s son later became King Gyeongjong.'],
      ['해설', 'In Sukjong’s time, coins called sangpyeong tongbo also came into wide use, and the economy changed.'],
      ['학생', 'So it was not only political fights.'],
      ['선생님', 'Still, the deep hatred left by these shifts became a big problem for the kings who came next.'],
      ['해설', 'Sukjong ruled for forty-six years, from 1674 to 1720.'],
    ],
  },

  'sl-16': {
    title: 'King Yeongjo and the Policy of Balance',
    names: N,
    outro: [
      'Yeongjo tried to use talented people from every group. What did this policy achieve, and where did it fall short?',
      'Like the story of the tangpyeong dish, how can we tell later tales apart from the records?',
      'To make different sides work together, what does a community need today?',
    ],
    lines: [
      ['해설', 'In 1724, King Gyeongjong died, and his younger brother Yeongjo took the throne.'],
      ['해설', 'Even before Yeongjo was king, the fight between the Noron and the Soron was very fierce.'],
      ['해설', 'In 1728, people who denied Yeongjo’s right to rule rose in revolt. This is called the Yi In-jwa Rebellion.'],
      ['학생', 'A revolt so early in his reign? He must have felt heavy.'],
      ['선생님', 'So Yeongjo made calming the fights between groups the center of his politics.'],
      ['해설', 'He chose talented officials evenly from every group. This was called the tangpyeong policy.'],
      ['학생', 'Where does the word tangpyeong come from?'],
      ['선생님', 'An old Chinese classic, the Book of Documents, says the king’s way is broad and level, taking no sides.'],
      ['선생님', 'The word tangpyeong was taken from that passage.'],
      ['해설', 'In 1742, Yeongjo set up a stone monument at the gate of Seonggyungwan, the royal academy.'],
      ['선생님', 'Its message was that a true gentleman gets along with all and does not form cliques.'],
      ['선생님', 'It was based on a saying of Confucius. It was shown to the students who would become officials.'],
      ['해설', 'Yeongjo also worked to lighten the people’s burden.'],
      ['해설', 'In 1750, he started the Gyunyeok Law, cutting the cloth tax for military service from two rolls to one.'],
      ['학생', 'Then how did the state fill the gap?'],
      ['선생님', 'It tried to cover it with other income, like taxes on fishing and salt.'],
      ['해설', 'In 1760, he also began a big project to dig out the bed of Cheonggyecheon Stream in the capital.'],
      ['해설', 'Yeongjo often talked with his officials, and he also made chances to hear the people directly.'],
      ['학생', 'So did the fights between groups disappear?'],
      ['선생님', 'Not really. In the end, the Noron, who had supported Yeongjo, stayed very powerful.'],
      ['선생님', 'The policy calmed the fights, but it could not pull out their roots.'],
      ['학생', 'I heard that the dish called tangpyeongchae came from this policy.'],
      ['선생님', 'That is a story told in later times. It is hard to confirm in the Sillok.'],
      ['해설', 'Yeongjo sat on the throne longer than any other Joseon king.'],
      ['해설', 'But his long reign also held a deep tragedy.'],
      ['학생', 'You mean the story of Crown Prince Sado?'],
      ['선생님', 'Yes. Let us look at that story separately next time.'],
      ['해설', 'Yeongjo ruled for fifty-two years, from 1724 to 1776.'],
    ],
  },

  'sl-17': {
    title: 'King Yeongjo and Crown Prince Sado',
    names: N,
    outro: [
      'Yeongjo’s decision led to his own son’s death. What did it leave to the royal family and the court?',
      'When the Sillok and the Memoirs of Lady Hyegyeong show the same event differently, how should we read them?',
      'When a family conflict meets public duty, what should we think about?',
    ],
    lines: [
      ['해설', 'Yeongjo had a son late in life, and he made the boy crown prince very early.'],
      ['해설', 'As a child, the prince was praised for being bright.'],
      ['해설', 'When the prince grew up, Yeongjo let him handle state affairs in his place. This was called daericheongjeong.'],
      ['학생', 'So the father trusted his son with the work.'],
      ['선생님', 'At first. But Yeongjo often scolded him harshly, and they slowly grew apart.'],
      ['해설', 'The prince suffered from a serious mental illness. It is said that he even harmed people in the palace.'],
      ['해설', 'In 1762, someone reported the prince’s wrongdoings to the king, and things grew worse.'],
      ['해설', 'That summer, Yeongjo took away the prince’s title and shut him inside a wooden rice chest.'],
      ['해설', 'The prince died inside the chest a few days later.'],
      ['학생', 'A father let his son die like that? It is hard to believe.'],
      ['선생님', 'It was a very rare tragedy even in the Joseon royal family. It still raises many questions.'],
      ['해설', 'After the prince died, Yeongjo gave back his title and named him Sado.'],
      ['해설', 'Sado’s son would later become King Jeongjo.'],
      ['학생', 'Is this event written in detail in the Sillok?'],
      ['선생님', 'The Sillok of Yeongjo records it, but it does not explain the hidden story in detail.'],
      ['선생님', 'So people also read another record, the Hanjungnok.'],
      ['학생', 'Who wrote the Hanjungnok?'],
      ['선생님', 'Lady Hyegyeong, Sado’s wife. She wrote it many years later, looking back on her life.'],
      ['선생님', 'Unlike the official Sillok, it is a personal memoir.'],
      ['학생', 'Then which one should we believe?'],
      ['선생님', 'Instead of trusting only one, think about who wrote each one, and when.'],
      ['선생님', 'Lady Hyegyeong’s own family was also tied up in the event, so keep that in mind too.'],
      ['해설', 'Historians disagree about the causes of this event.'],
      ['해설', 'Some put the prince’s illness and the conflict between father and son at the center.'],
      ['해설', 'Others think the struggle between political groups around the prince mattered more.'],
      ['학생', 'So even one event can be seen in so many ways.'],
      ['선생님', 'That is why history is not about memorizing answers. It is about comparing records and asking questions.'],
      ['해설', 'The Hanjungnok is a memoir that Lady Hyegyeong wrote in Hangeul, the Korean alphabet.'],
    ],
  },

  'sl-18': {
    title: 'King Jeongjo and Hwaseong Fortress',
    names: N,
    outro: [
      'Jeongjo put great effort into Gyujanggak and Hwaseong. How was he trying to change Joseon?',
      'A detailed record of the building work later helped rebuild Hwaseong. What does that tell us about records?',
      'Are there still people today who cannot use their talents because of their background?',
    ],
    lines: [
      ['해설', 'In 1776, Yeongjo died, and his grandson came to the throne. He is King Jeongjo.'],
      ['해설', 'On the day he became king, Jeongjo told his officials that he was the son of Crown Prince Sado.'],
      ['학생', 'He followed his grandfather, but he spoke about his father.'],
      ['선생님', 'Yes. Many see it as a sign that he would never forget what happened to his father.'],
      ['해설', 'In his first year, Jeongjo set up Gyujanggak inside Changdeokgung Palace.'],
      ['해설', 'It kept the kings’ writings and books, and it became a place to study learning and policy.'],
      ['해설', 'Jeongjo also chose young officials and had them study again under his guidance.'],
      ['학생', 'Who worked at Gyujanggak?'],
      ['선생님', 'Scholars like Yi Deok-mu, Bak Je-ga, and Yu Deuk-gong were chosen as library officials.'],
      ['선생님', 'They were seoeol, sons of concubines, so their path to office was blocked. Jeongjo used their talent anyway.'],
      ['해설', 'Jeongjo kept the policy of balance, and he built a royal guard army called Jangyongyeong to strengthen his power.'],
      ['해설', 'In 1789, he moved his father’s tomb to Hwasan Mountain in Suwon.'],
      ['해설', 'Then he decided to build a new town and fortress nearby. This is Suwon Hwaseong.'],
      ['해설', 'Work on Hwaseong began in 1794 and was finished in 1796.'],
      ['학생', 'I heard they used new technology to build it.'],
      ['선생님', 'Jeong Yak-yong designed a lifting machine with pulleys to raise heavy stones.'],
      ['선생님', 'They also used bricks, and built a fortress that was both strong and beautiful.'],
      ['해설', 'Jeongjo paid wages to the workers who built it.'],
      ['해설', 'In 1795, Jeongjo traveled to Hwaseong with his mother, Lady Hyegyeong.'],
      ['선생님', 'That year, she and Sado would both have turned sixty. They held a feast at Hwaseong.'],
      ['해설', 'Every step of the work was written down in detail in a royal record book, an uigwe.'],
      ['학생', 'Why is that record so important?'],
      ['선생님', 'Hwaseong was badly damaged in modern times. In the 1970s, it was rebuilt using this record.'],
      ['학생', 'So a careful record brought the fortress back to life.'],
      ['해설', 'In 1800, Jeongjo died before he could finish many of his reforms.'],
      ['선생님', 'Many people ask what would have happened if he had lived longer. But that is only imagination.'],
      ['해설', 'Suwon Hwaseong was listed as a UNESCO World Heritage Site in 1997.'],
    ],
  },

  'sl-19': {
    title: 'In-law Rule and Hong Gyeong-rae',
    names: N,
    outro: [
      'A few families held all the power. What did this mean for the people and the future of the country?',
      'If we read an event the state called a rebellion from the rebels’ side, what might we see?',
      'Can you think of a modern example of how regional discrimination can shake a society?',
    ],
    lines: [
      ['해설', 'In 1800, Jeongjo’s son Sunjo became king at a young age.'],
      ['해설', 'At first, Queen Dowager Jeongsun, Yeongjo’s queen, ruled for him from behind a screen.'],
      ['해설', 'In 1801, the Catholics of Joseon were harshly persecuted.'],
      ['해설', 'Later, the Andong Kim family, the family of Sunjo’s queen, took great power.'],
      ['학생', 'Is this what people call sedo politics?'],
      ['선생님', 'Yes. It means rule by a few families, like the king’s in-laws, who keep all the power.'],
      ['선생님', 'Under the next kings too, families like the Andong Kim and the Pungyang Jo held power.'],
      ['해설', 'Government posts were bought and sold, and local officials squeezed the people harder.'],
      ['해설', 'The three main tax systems, on land, on military service, and on grain loans, fell into disorder.'],
      ['학생', 'Wasn’t the grain loan system made to help the people?'],
      ['선생님', 'Right. It lent grain to the poor, but it turned into a tool for taking high interest.'],
      ['해설', 'People in Pyeongan Province had long felt they were blocked from government posts, and they were bitter.'],
      ['해설', 'In the winter of 1811, Hong Gyeong-rae started an uprising in Gasan, Pyeongan Province.'],
      ['해설', 'Many kinds of people joined him: poor yangban nobles, merchants, landless farmers, and mine workers.'],
      ['해설', 'In a short time, the rebels took many towns north of the Cheongcheon River.'],
      ['학생', 'If it spread that fast, people must have been really angry.'],
      ['선생님', 'Yes. But when government troops fought back, the rebels retreated into Jeongju Fortress and held out.'],
      ['해설', 'The government army surrounded the fortress and attacked it for a long time.'],
      ['해설', 'In 1812, the soldiers buried gunpowder under the wall, blew it up, and took the fortress.'],
      ['해설', 'Hong Gyeong-rae was killed in the fighting, and many people captured inside were executed.'],
      ['학생', 'How is this event written in the Sillok?'],
      ['선생님', 'It is a state record, so of course it is called a traitors’ rebellion.'],
      ['선생님', 'But we must also ask why so many people rose up together. Then we see the event clearly.'],
      ['해설', 'The uprising failed, but the people’s resistance went on.'],
      ['해설', 'In 1862, farmers rose up in many places in the south, starting with Jinju.'],
      ['학생', 'So the state never really fixed the problems.'],
      ['선생님', 'Right. The shadow of in-law rule lasted into the late nineteenth century, when Joseon faced great change.'],
      ['해설', 'Anger at discrimination against Pyeongan Province was a major cause of Hong Gyeong-rae’s uprising.'],
    ],
  },

  'sl-20': {
    title: 'The People Who Saved the Sillok',
    names: N,
    outro: [
      'Even the king could not read the historians’ drafts. How did this rule affect politics in Joseon?',
      'If people wrote the Sillok, how much should we trust it, and how should we read it?',
      'Of the records we make today, what should be kept for hundreds of years?',
    ],
    lines: [
      ['해설', 'The Annals of the Joseon Dynasty, or Sillok, record each king’s reign day by day, from Taejo to Cheoljong.'],
      ['학생', 'Who wrote so many records?'],
      ['선생님', 'Officials called sagwan, the royal historians. They stayed near the king and wrote down state affairs and talks.'],
      ['해설', 'The drafts the historians wrote were called sacho.'],
      ['해설', 'After a king died, an office gathered the drafts and other papers and made them into a Sillok.'],
      ['학생', 'The king must have wanted to know what they wrote about him.'],
      ['선생님', 'Even so, the rule was that the king could not freely read the drafts or the Sillok.'],
      ['선생님', 'It was a way to keep the records from bowing to power.'],
      ['해설', 'There is a famous story about King Taejong. He fell from his horse and told people not to let the historians know.'],
      ['해설', 'But it is said that even his order to hide it was written down in the Sillok.'],
      ['학생', 'They even wrote down the order to hide it? Those historians were really stubborn.'],
      ['해설', 'Several copies of each finished Sillok were made and kept in separate archives called sago.'],
      ['선생님', 'If they were kept in one place, a fire or a war could destroy them all. So they spread them out.'],
      ['해설', 'Before the Imjin War, the archives were in the capital, Chungju, Seongju, and Jeonju.'],
      ['해설', 'When the war broke out, every copy except the one in Jeonju burned.'],
      ['학생', 'How did the Jeonju copy survive?'],
      ['선생님', 'Local scholars, An Ui and Son Hong-rok, and others carried it into Naejangsan Mountain.'],
      ['선생님', 'It is said they took turns guarding it in the mountains. Thanks to them, the earlier records survived.'],
      ['해설', 'After the war, the court used the Jeonju copy to print several new sets of the Sillok.'],
      ['해설', 'The new archives were mostly built deep in the mountains, safer from fire and war.'],
      ['해설', 'Counting later moves, they included Jeongjoksan on Ganghwa, Taebaeksan, Odaesan, and Jeoksangsan.'],
      ['학생', 'But can we say everything in the Sillok is true?'],
      ['선생님', 'Good question. Some parts were rewritten by political groups, like the Revised Sillok of King Seonjo.'],
      ['선생님', 'So the Sillok is a precious source, but we must also read it with a critical eye.'],
      ['해설', 'Such careful records kept over so many centuries are seen as rare in the world.'],
      ['학생', 'We can read them now because some people protected them.'],
      ['선생님', 'Yes. It is a heritage made by those who wrote it and those who kept it safe.'],
      ['해설', 'The Annals of the Joseon Dynasty were added to UNESCO’s Memory of the World Register in 1997.'],
    ],
  },
};
