// 청소년 영어 원고 (중학생 이상). 키 = stories/teen-essay.js 의 이야기 id.
// 고전 한문 수필(퍼블릭 도메인)을 한국어 각색의 흐름대로 쉬운 영어로 풀어 씀(원문 직역·인용 아님).
// 고유 낱말은 로마자로 쓰고 짧게 풀이.
export default {
  'ts-seulgyeon': {
    title: 'On the Louse and the Dog',
    names: { 해설: 'Narrator', 이규보: 'Yi Gyu-bo', 손님: 'Guest' },
    outro: [
      'Yi Gyu-bo said the death of a dog and the death of a louse are no different. What was he trying to teach?',
      'How did the example of biting your ten fingers shake the guest’s thinking?',
      'Do we value lives differently because of their size or usefulness?',
    ],
    lines: [
      ['해설', 'Yi Gyu-bo was a writer of the middle Goryeo period. He loved wine, music, and poetry.'],
      ['해설', 'He liked to write short essays that found lessons in small, everyday things.'],
      ['해설', 'Seulgyeonseol means an essay on the louse and the dog.'],
      ['해설', 'What you will hear is not the original text in classical Chinese, but a retelling in modern words.'],
      ['해설', 'One day, a guest came to visit Yi Gyu-bo and began to speak.'],
      ['손님', 'Last evening I saw a terrible sight.'],
      ['손님', 'A rough man was beating a stray dog to death with a big club. I felt so sorry for it.'],
      ['손님', 'So from then on, I decided not to eat dog meat or pork.'],
      ['이규보', 'I also saw something yesterday. A man sat by a fire, picking lice off and burning them.'],
      ['이규보', 'It hurt my heart, so I swore that I would never kill a louse again.'],
      ['해설', 'The guest looked disappointed and annoyed.'],
      ['손님', 'A louse is a tiny, worthless thing. I was talking about the death of a large animal.'],
      ['손님', 'You answer me with something like that? Are you making fun of me?'],
      ['이규보', 'Not at all. Everything with blood and breath is the same, from people and cattle to insects and ants.'],
      ['이규보', 'All of them love life and hate death.'],
      ['이규보', 'Why would only big creatures hate death, and small ones not?'],
      ['이규보', 'The death of a dog and the death of a louse are no different. That is why I spoke of it.'],
      ['이규보', 'If you do not believe me, bite your ten fingers. Does only the thumb hurt, and not the others?'],
      ['이규보', 'Every part of one body has blood and flesh, big or small, so the pain is the same.'],
      ['이규보', 'How much more so for living things that each received their own breath of life!'],
      ['이규보', 'Go home, close your eyes, and think quietly.'],
      ['이규보', 'When you can see a snail’s horn like an ox’s horn, and a quail like a giant bird, come back.'],
      ['이규보', 'Then, at last, I will talk with you about the Way.'],
      ['해설', 'The guest’s mind stayed only on large lives that were easy to see, like the dog.'],
      ['해설', 'Yi Gyu-bo was saying that the eye that measures big and small must change first.'],
      ['해설', 'The giant bird is the Peng, an imaginary bird in the Zhuangzi that flies ninety thousand li at once.'],
      ['해설', 'Through questions and answers, the essay breaks down the guest’s fixed ideas one by one.'],
      ['해설', 'We never learn how the guest answered. The thinking is left to the reader.'],
      ['해설', 'This essay comes down to us in Yi Gyu-bo’s collected works, Dongguk Isanggukjip.'],
    ],
  },

  'ts-iok': {
    title: 'On Repairing a House',
    names: { 해설: 'Narrator', 이규보: 'Yi Gyu-bo' },
    outro: [
      'What lesson did Yi Gyu-bo learn from repairing his house?',
      'The essay moves from fixing a house to personal faults, and then to politics. What effect does that have?',
      'Is there something in my life that I put off until it became a bigger problem?',
    ],
    lines: [
      ['해설', 'Yi Gyu-bo, a writer of Goryeo, left many poems and essays during his life.'],
      ['해설', 'He often took ordinary things around his house and turned them into deep thoughts.'],
      ['해설', 'Iokseol means an essay on repairing a house.'],
      ['해설', 'From here on, you will hear the ideas of the essay in modern words, not the original text.'],
      ['이규보', 'Three rooms in the servants’ wing of my house had grown old and were about to fall down.'],
      ['이규보', 'I had no choice but to repair all three.'],
      ['이규보', 'Two of them had been leaking for a long time.'],
      ['이규보', 'I knew it, but I kept putting it off and never fixed them.'],
      ['이규보', 'The other room had been rained on only once, so I replaced its roof tiles right away.'],
      ['이규보', 'When the work began, the two old leaking rooms had rotten rafters, pillars, and beams.'],
      ['이규보', 'Much of the wood could not be used, and the repair cost a lot.'],
      ['이규보', 'In the room that got wet only once, all the wood was still sound and could be used again.'],
      ['이규보', 'So that repair cost very little.'],
      ['해설', 'The house was the same, and the rain was the same, but the results were very different. Only the timing differed.'],
      ['해설', 'Here Yi Gyu-bo turns his thoughts to how people live.'],
      ['이규보', 'People are just like this.'],
      ['이규보', 'If you know your fault but do not fix it soon, you become like rotten wood. You cannot be used again.'],
      ['이규보', 'If you realize your fault and are not afraid to fix it, you can easily become a good person again.'],
      ['이규보', 'It is just like the wood that could be used again.'],
      ['해설', 'His thinking goes one step further, all the way to the government of a country.'],
      ['이규보', 'Ruling a country is the same.'],
      ['이규보', 'If harmful practices that hurt the people are left alone, the people grow tired and the country falls into danger.'],
      ['이규보', 'Then it is too late to set things right in a hurry. How can we not be careful?'],
      ['해설', 'The essay first shows the experience of repairing a house, and then draws out a lesson.'],
      ['해설', 'It is also worth noticing how the thinking widens, from one person’s faults to a whole country.'],
      ['해설', 'The lesson that small problems put off become big problems is still true today.'],
      ['해설', 'This essay is found in Dongguk Isanggukjip, the collected works of Yi Gyu-bo of the Goryeo period.'],
    ],
  },

  'ts-gyeong': {
    title: 'On the Mirror',
    names: { 해설: 'Narrator', 거사: 'Geosa', 손님: 'Guest' },
    outro: [
      'Why does the geosa look into a cloudy mirror on purpose? What attitude toward life does that show?',
      'A dusty mirror is compared to moonlight behind clouds. What does that say about the mirror’s clear nature?',
      'Showing others’ faults plainly, or waiting for the right time: which would I choose today?',
    ],
    lines: [
      ['해설', 'Yi Gyu-bo lived during Goryeo’s military rule. He left free-spirited poems and sharp essays.'],
      ['해설', 'A seol is a kind of classical essay that explains the nature of things to share the writer’s ideas.'],
      ['해설', 'Gyeongseol means an essay on the mirror. The geosa in it, a quiet scholar at home, can be read as the writer himself.'],
      ['해설', 'What you will hear is not the original text, but a retelling in modern words.'],
      ['해설', 'A geosa owned a mirror.'],
      ['해설', 'The mirror was covered in dust and looked dim, like moonlight hidden behind clouds.'],
      ['해설', 'Even so, he looked into it morning and evening, as if tidying his face.'],
      ['해설', 'One day, a guest saw this, found it strange, and asked him about it.'],
      ['손님', 'Isn’t a mirror something for looking at your face?'],
      ['손님', 'Or else a wise man looks at a mirror to learn from its clearness.'],
      ['손님', 'But your mirror is so cloudy that it cannot show a face, and it has no clearness to learn from.'],
      ['손님', 'Yet you look into it every day. Why on earth do you do that?'],
      ['거사', 'When a mirror is clear, good-looking people are happy, but ugly people hate it.'],
      ['거사', 'And in this world, there are few good-looking people and many ugly ones.'],
      ['거사', 'If an ugly person saw a clear mirror, he would surely break it.'],
      ['거사', 'So it is better for it to stay dim with dust.'],
      ['거사', 'The dust only clouds the surface. The clear nature of the mirror has not disappeared.'],
      ['거사', 'It will not be too late to polish it when I meet a good-looking person.'],
      ['거사', 'Ah, people of old looked into mirrors for clearness. I look into my mirror for dimness.'],
      ['거사', 'Why do you find that so strange?'],
      ['해설', 'The guest could not answer at all.'],
      ['해설', 'Here the mirror is not just an object. It can stand for the way a person faces the world.'],
      ['해설', 'Like a mirror that is too clear, a person who exposes every fault of others is easily hated and broken.'],
      ['해설', 'But that does not mean throwing away the clear nature. It means keeping it and waiting for the right time.'],
      ['해설', 'Which is right, clearness or dimness? Each reader can think about it differently.'],
      ['해설', 'Gyeongseol is a short essay in Dongguk Isanggukjip, the collected works of Yi Gyu-bo.'],
    ],
  },

  'ts-toshil': {
    title: 'On Tearing Down the Earth Room',
    names: { 해설: 'Narrator', 이규보: 'Yi Gyu-bo', 아들: 'Son' },
    outro: [
      'Why did Yi Gyu-bo order the warm, handy earth room torn down?',
      'The essay places the sons’ explanation and the father’s scolding in turn. How does that make the writer’s view stand out?',
      'Strawberries in winter, heating and cooling all year: how far should we accept comforts that go against nature?',
    ],
    lines: [
      ['해설', 'Yi Gyu-bo was a famous writer of the Goryeo period who boldly shared his ideas in writing.'],
      ['해설', 'Goetosilseol means an essay on tearing down the earth room.'],
      ['해설', 'Here, a tosil is a pit dug in the ground and covered with a roof. It stays warm even in winter.'],
      ['해설', 'What follows is a retelling in modern words, not the original text.'],
      ['이규보', 'On the first day of the tenth month, I came home. My boys had dug a room in the ground.'],
      ['이규보', 'It looked just like a grave. I pretended not to know and asked them.'],
      ['이규보', 'Why have you made a grave inside our home?'],
      ['아들', 'This is not a grave, Father. It is a tosil, an earth room.'],
      ['아들', 'In winter, it is a good place to keep flowers, plants, and fruit.'],
      ['아들', 'It is also a good place for the women to weave cloth.'],
      ['아들', 'Even on the coldest days, it is as warm as spring inside, so our hands do not crack.'],
      ['해설', 'Then Yi Gyu-bo scolded them strongly.'],
      ['이규보', 'Heat in summer and cold in winter is the natural law set by heaven.'],
      ['이규보', 'To go against it is something unnatural.'],
      ['이규보', 'The wise men of old had us wear fur in winter and hemp in summer. That is enough.'],
      ['이규보', 'If you build an earth room and turn cold into warmth, you go against heaven’s order.'],
      ['이규보', 'People are not snakes or toads. Lying in a hole in the ground is not a good thing.'],
      ['이규보', 'Weaving has its own season. Why must it be done in winter?'],
      ['이규보', 'Flowers bloom in spring and wither in winter. That is the true nature of plants.'],
      ['이규보', 'Anything that breaks that rule is unnatural.'],
      ['이규보', 'Raising unnatural things for out-of-season show takes away heaven’s power.'],
      ['이규보', 'This is not what I want. Tear it down at once.'],
      ['해설', 'The boys quickly tore down the earth room and used its wood as firewood.'],
      ['이규보', 'Only then did my mind feel at peace.'],
      ['해설', 'This essay strongly shows the writer’s belief that following the order of nature is right.'],
      ['해설', 'How far we should change nature for comfort is still a question worth thinking about today.'],
      ['해설', 'This essay is found in Dongguk Isanggukjip, the collected works of Yi Gyu-bo.'],
    ],
  },

  'ts-chama': {
    title: 'On Borrowing a Horse',
    names: { 해설: 'Narrator', 이곡: 'Yi Gok' },
    outro: [
      'Yi Gok said there is nothing in the world that is not borrowed. What was he warning people about?',
      'The essay grows from a small experience of riding a borrowed horse to a big lesson about owning things. Why is that persuasive?',
      'Of the things I enjoy now, which ones are really borrowed from others?',
    ],
    lines: [
      ['해설', 'Yi Gok was a scholar-official of late Goryeo. He was so learned that he even passed the state exam of Yuan China.'],
      ['해설', 'He was also the father of Yi Saek, who later became a famous scholar.'],
      ['해설', 'Chamaseol means an essay on borrowing a horse.'],
      ['해설', 'What you will hear is not the original text, but a retelling in modern words.'],
      ['이곡', 'My family is poor, and I have no horse. So sometimes I borrow other people’s horses.'],
      ['이곡', 'When I get a slow, thin horse, I dare not whip it, however urgent my business is.'],
      ['이곡', 'I ride carefully so it will not fall, and I get off and walk at streams and ditches.'],
      ['이곡', 'So I almost never have anything to regret.'],
      ['이곡', 'But when I get a fast horse with high hooves and sharp ears, things are different.'],
      ['이곡', 'I grow proud, whip it as I like, and let go of the reins.'],
      ['이곡', 'I gallop over hills and valleys as if they were flat ground. It feels wonderful.'],
      ['이곡', 'But then I cannot avoid nearly falling off in danger.'],
      ['이곡', 'Ah, how easily the human heart changes!'],
      ['이곡', 'If I am like this with something borrowed for a moment, what about something that is truly mine?'],
      ['이곡', 'But think about it carefully. Of all that people have, what is not borrowed?'],
      ['이곡', 'A king borrows strength from the people to hold a high and rich place.'],
      ['이곡', 'An official borrows power from the king to win favor and honor.'],
      ['이곡', 'A child borrows from parents, a wife from a husband, and a servant from a master.'],
      ['이곡', 'What they borrow is deep and great, but most people treat it as their own and never look back.'],
      ['이곡', 'Is this not a kind of blindness?'],
      ['이곡', 'If what was borrowed must be returned in a moment, a king who ruled all lands becomes a lonely man.'],
      ['이곡', 'A great family with a hundred carriages becomes a lonely servant. How much more for those below them?'],
      ['이곡', 'Mencius said that if you borrow something long and never return it, you forget it is not yours.'],
      ['이곡', 'His words moved me, so I wrote this essay to widen their meaning.'],
      ['해설', 'This essay starts with the small experience of riding a borrowed horse and moves to a big lesson about owning.'],
      ['해설', 'If rank and wealth are only held for a while, we should always stay humble and careful.'],
      ['해설', 'Chamaseol comes down to us in Gajeongjip, the collected works of Yi Gok.'],
    ],
  },

  'ts-ilya-guhdo': {
    title: 'Crossing a River Nine Times in One Night',
    names: { 해설: 'Narrator', 박지원: 'Park Ji-won' },
    outro: [
      'Crossing the river nine times, what did Park Ji-won learn about the ears, the eyes, and the mind?',
      'The same stream sounds different depending on the mind. How does that example prepare the essay’s conclusion?',
      'Do fear or fixed ideas ever make me see or hear something as bigger than it really is?',
    ],
    lines: [
      ['해설', 'Park Ji-won was a great writer and a silhak scholar of late Joseon, who valued practical learning. His pen name was Yeonam.'],
      ['해설', 'In 1780, he joined a Joseon mission going to China to celebrate the Qing emperor’s birthday.'],
      ['해설', 'His record of that journey is Yeolha Ilgi, and this essay is part of it.'],
      ['해설', 'The title means crossing a river nine times in one night. What follows is a retelling in modern words.'],
      ['박지원', 'The river flows out between two mountains. It crashes against the rocks and churns wildly, as if fighting.'],
      ['박지원', 'My home is in the mountains, and a big stream runs in front of my gate.'],
      ['박지원', 'After heavy summer rain, the stream suddenly swells and roars like carts, horses, cannons, and drums.'],
      ['박지원', 'Once I closed my door, lay down, and listened carefully to that sound, comparing it.'],
      ['박지원', 'When it sounded like wind in the pines, it was because I listened with a clear, calm mind.'],
      ['박지원', 'When it sounded like mountains tearing and hills falling, I listened with an angry mind.'],
      ['박지원', 'When it sounded like paper rattling in a window, I listened with a doubtful mind.'],
      ['박지원', 'I did not hear truly. The thoughts already in my mind made the sounds.'],
      ['박지원', 'On this journey, I crossed one river nine times in a single night.'],
      ['박지원', 'Crossing in the daytime, I could see the water. My eyes were fixed on the danger, and I trembled.'],
      ['박지원', 'So, strangely, the sound of the water never reached my ears.'],
      ['박지원', 'Crossing at night, I could see nothing. My ears were fixed on the sound, and I was terrified.'],
      ['박지원', 'Now at last I understood the Way.'],
      ['박지원', 'A person whose mind is calm and still cannot be shaken by the ears and eyes.'],
      ['박지원', 'A person who trusts only his ears and eyes suffers more, the sharper they are.'],
      ['박지원', 'That day, my groom’s foot was stepped on by a horse, and he was carried in the cart behind.'],
      ['박지원', 'Alone, I let go of the reins and floated on the river, my knees pulled up on the saddle.'],
      ['박지원', 'One fall, and it would be the river. So I told myself the river was the ground, my clothes, my body.'],
      ['박지원', 'Once I made up my mind that I might fall, I no longer heard the river at all.'],
      ['박지원', 'I crossed nine times without worry, as if I were sitting and lying down in my room.'],
      ['박지원', 'Sounds and colors are outside things. They always tie up the ears and eyes, so we cannot see and hear truly.'],
      ['박지원', 'The road of life is rougher than a river. How often do seeing and hearing become a sickness?'],
      ['박지원', 'I will go back to the mountains, listen to my stream again, and think about this lesson.'],
      ['박지원', 'And I will tell this story to clever people who trust only their own sharpness to get ahead.'],
      ['해설', 'The essay first tells an experience, then moves to the lesson that the mind matters more than the senses.'],
      ['해설', 'This essay is in the Sanjang Japgi section of Park Ji-won’s Yeolha Ilgi.'],
    ],
  },

  'ts-hogok': {
    title: 'A Good Place to Cry',
    names: { 해설: 'Narrator', 박지원: 'Park Ji-won', 정진사: 'Scholar Jeong' },
    outro: [
      'Seeing the wide Liaodong plain, why did Park Ji-won speak of crying, but not of sadness?',
      'How does the example of a newborn baby’s cry turn our usual idea of crying upside down?',
      'When I first left a small place and faced a wide world, what did I feel?',
    ],
    lines: [
      ['해설', 'In the summer of 1780, Park Ji-won crossed the Amnok River with a Joseon mission, heading for Qing China.'],
      ['해설', 'Not long after crossing the river, the group entered the endless Liaodong plain.'],
      ['해설', 'This day’s record is part of the Dogangnok section of Yeolha Ilgi. It is often called Hogokjangnon.'],
      ['해설', 'The name means a talk about a good place to cry. What follows is a retelling in modern words.'],
      ['해설', 'As they came around the foot of a mountain, the view suddenly opened wide. Not a single mountain could be seen.'],
      ['해설', 'Park Ji-won stopped his horse, looked all around, put his hand to his forehead, and cried out.'],
      ['박지원', 'What a fine place to cry! It is worth a good long cry.'],
      ['정진사', 'We have found such a wide-open world, and suddenly you want to cry? What do you mean?'],
      ['박지원', 'People think that, of the seven feelings, only sadness makes us cry.'],
      ['박지원', 'But they do not know that all seven feelings can make us cry.'],
      ['박지원', 'When joy goes to the very end, we can cry. When anger goes to the very end, we can cry.'],
      ['박지원', 'Pleasure, love, hate, and desire too can turn into tears when they go to the very end.'],
      ['박지원', 'To let out feelings tied up in the chest, nothing is faster than crying out loud.'],
      ['정진사', 'Then I should cry with you in this wide place. But which of the seven feelings should I choose?'],
      ['박지원', 'Ask a newborn baby. When a baby is born and cries for the first time, what feeling is it?'],
      ['박지원', 'People say the baby cries out of sadness for the pain and death it will face.'],
      ['박지원', 'But that is not knowing the baby’s true heart.'],
      ['박지원', 'The baby was shut in a dark, narrow place inside its mother. Then suddenly it came out into a wide place.'],
      ['박지원', 'It stretches its hands and feet, and its heart opens up. How could it not cry out freely?'],
      ['박지원', 'So we too should cry honestly, like a newborn baby.'],
      ['박지원', 'Looking at the East Sea from Birobong Peak of Geumgangsan is a place worth a good cry.'],
      ['박지원', 'The golden sand beach of Jangyeon in Hwanghae Province is also a place worth a good cry.'],
      ['박지원', 'From the Liaodong plain to Shanhai Pass is twelve hundred li. There is no mountain, and the sky meets the earth.'],
      ['박지원', 'Isn’t this also a place worth a good long cry?'],
      ['해설', 'To Park Ji-won, crying was not a sign of sadness. It was the sound of a closed heart suddenly opening.'],
      ['해설', 'Facing a wide world for the first time, he felt like a newborn baby.'],
      ['해설', 'The questions and answers that turn familiar ideas upside down make this writing lively.'],
      ['해설', 'Yeolha Ilgi is Park Ji-won’s record of his journey to Qing China in 1780.'],
    ],
  },

  'ts-suojae': {
    title: 'The House for Keeping Myself',
    names: { 해설: 'Narrator', 정약용: 'Jeong Yak-yong' },
    outro: [
      'Why did Dasan think that, of all things in the world, only the self must be guarded?',
      'He lists fields, houses, trees, and books, then gathers his thoughts on the self. What effect does that order have?',
      'If I ever lost myself to profit or trends, how could I find myself again?',
    ],
    lines: [
      ['해설', 'Jeong Yak-yong was a silhak scholar of late Joseon. His pen name was Dasan.'],
      ['해설', 'In 1801, he was caught up in a case about Catholics and sent into exile at Janggi in Gyeongsang Province.'],
      ['해설', 'Suojaegi is an essay about Suojae, which means the house for keeping myself.'],
      ['해설', 'Suojae was the name Dasan’s eldest brother gave to his house. What follows is a retelling in modern words.'],
      ['정약용', 'When I first heard that name, I was puzzled.'],
      ['정약용', 'Nothing sticks to me more closely than myself. Why would I need to guard it?'],
      ['정약용', 'But living alone in exile at Janggi, I thought about it, and suddenly I understood.'],
      ['정약용', 'Many things in the world need no guarding. Only the self must be guarded.'],
      ['정약용', 'Could anyone carry off my fields on his back? Fields need no guarding.'],
      ['정약용', 'Could anyone carry off my house on his back? A house needs no guarding.'],
      ['정약용', 'Could anyone pull up the flower and fruit trees in my garden? Their roots go deep into the earth.'],
      ['정약용', 'Could anyone steal my books and wipe them out? The books of the sages are as common as water and fire.'],
      ['정약용', 'Even if my clothes and food are stolen, I can make them again from the world’s thread and grain.'],
      ['정약용', 'But the self runs away easily, and comes and goes at no fixed time.'],
      ['정약용', 'It seems to stay close, but if you stop watching for a moment, it goes off anywhere.'],
      ['정약용', 'Tempt it with profit, and it leaves. Scare it with threats and disaster, and it leaves.'],
      ['정약용', 'It leaves when it hears merry music, and it leaves when it sees a pretty face.'],
      ['정약용', 'Once it leaves, it does not know how to return, and it will not stay even if you hold it.'],
      ['정약용', 'Nothing in the world is lost more easily than the self. Shouldn’t it be tied and locked up tight?'],
      ['정약용', 'I am a man who failed to keep myself and lost it.'],
      ['정약용', 'When I was young, the state exam looked good to me. I was lost in it for ten years.'],
      ['정약용', 'After I became an official, I ran wildly along the main roads in my official robes for twelve years.'],
      ['정약용', 'Then my fortune changed. I crossed the Han River and a high pass, leaving family and ancestors’ graves for the seaside.'],
      ['정약용', 'Then I asked myself: Why have you come all the way here? Won’t you go back home?'],
      ['정약용', 'But my self stood still, dazed, as if tied down. So I held on to it and stayed here with it.'],
      ['정약용', 'At that time, my second brother had also lost himself and was in exile by the southern sea.'],
      ['정약용', 'Only my eldest brother never lost himself. He sits calmly and properly in Suojae.'],
      ['정약용', 'Surely he has something he guards, so he never lost himself. That is why he named his house Suojae.'],
      ['해설', 'Dasan added that Mencius was right: of all things to guard, guarding oneself is the greatest.'],
      ['해설', 'The essay lists things that need no guarding, then gathers its thoughts on the true self, so easily lost.'],
      ['해설', 'Suojaegi comes down to us in Yeoyudang Jeonseo, the complete works of Jeong Yak-yong.'],
    ],
  },

  'ts-homin': {
    title: 'On the People to Be Feared',
    names: { 해설: 'Narrator', 허균: 'Heo Gyun' },
    outro: [
      'Why did Heo Gyun say that what rulers should fear most in the world is the people?',
      'He divides the people into three groups. How does that support his argument?',
      'Today, how can citizens’ voices become a warning to people in power?',
    ],
    lines: [
      ['해설', 'Heo Gyun was an official and writer of mid-Joseon. He is known as the author of The Tale of Hong Gil-dong.'],
      ['해설', 'He wrote many pieces that sharply criticized the unfairness of class and the system.'],
      ['해설', 'Hominnon is an essay about homin, the people who should be feared.'],
      ['해설', 'What you will hear is not the original text, but a retelling in modern words.'],
      ['허균', 'In all the world, the only thing to be feared is the people.'],
      ['허균', 'The people are more fearful than floods or fires, than tigers or leopards.'],
      ['허균', 'Yet those above look down on the people and work them as they please. How can this be?'],
      ['허균', 'There are three kinds of people.'],
      ['허균', 'The first are the hangmin. Tied to what is in front of them, they obey the law and their masters.'],
      ['허균', 'They are nothing to fear.'],
      ['허균', 'The second are the wonmin. They are squeezed until their skin peels and bones break, giving up all they produce.'],
      ['허균', 'They sigh and resent those above, but they are still not much to fear.'],
      ['허균', 'The third are the homin. They hide their tracks, keep secret plans, glare at the world, and wait.'],
      ['허균', 'These are the ones to fear.'],
      ['허균', 'A homin watches for cracks in the country. When the time comes, he rolls up his sleeves in a field and shouts.'],
      ['허균', 'Then the wonmin hear the sound alone and gather to shout with him.'],
      ['허균', 'The hangmin, too, looking for a way to live, follow with hoes, rakes, and spear handles.'],
      ['허균', 'The Qin dynasty fell because of Chen Sheng and Wu Guang. The Han fell into chaos because of the Yellow Turbans.'],
      ['허균', 'All of this was brought on by rulers who made the people suffer.'],
      ['허균', 'Our land is small, our people are few, and they are gentle, so great uprisings have been rare.'],
      ['허균', 'So those above think there are no homin in our country, and they do not know fear.'],
      ['허균', 'If someone like Gyeon Hwon or Gung Ye appeared, who can promise the angry people would not follow?'],
      ['허균', 'Those who rule must see clearly what is to be feared, and change their wrong ways.'],
      ['허균', 'If they do, things can still be set right.'],
      ['해설', 'By dividing the people into three groups, Heo Gyun shows that a country’s real power lies with its people.'],
      ['해설', 'The aim of this essay is not to stir up revolt, but to warn those who rule.'],
      ['해설', 'Fearing the people can also be read as making the people the foundation of the country.'],
      ['해설', 'Hominnon is found in Seongso Bubugo, the collected works of Heo Gyun.'],
    ],
  },

  'ts-dojaseol': {
    title: 'The Thief and His Son',
    names: { 해설: 'Narrator', 아버지: 'Father', 아들: 'Son', 주인: 'Owner' },
    outro: [
      'Why did the father teach his son in such a dangerous way, by locking him in a storehouse?',
      'Gang Hui-maeng used a thief’s story to talk about learning. What effect does that have?',
      'Have I ever learned something by facing it myself, not from an answer someone gave me?',
    ],
    lines: [
      ['해설', 'Gang Hui-maeng was a scholar-official of early Joseon. He passed the state exam under King Sejong and held many posts.'],
      ['해설', 'To teach his son, he wrote five short stories. Together they are called Hunja Oseol.'],
      ['해설', 'Today we will hear one of them, Dojaseol, the story of a thief and his son.'],
      ['해설', 'The words of the characters are retold in modern language, not copied from the original.'],
      ['해설', 'Long ago, there was a man who made his living as a thief. He taught his son all his skills.'],
      ['해설', 'Over time, the son grew more skillful. He went in ahead of his father and carried out the heavy loads.'],
      ['아들', 'Father, my skill is as good as yours now. And I am even stronger.'],
      ['아버지', 'You still have far to go. True wisdom comes from learning things for yourself.'],
      ['아버지', 'Your skill now is only what you learned from me. It is not something you found yourself.'],
      ['해설', 'One night, the two of them sneaked into the storehouse of a rich family.'],
      ['해설', 'The father sent his son inside, then shut the door from outside and locked it.'],
      ['해설', 'Then he rattled the lock on purpose so the owner would hear, and he went away.'],
      ['해설', 'The owner came out, but the lock was still closed. Feeling safe, he went back inside.'],
      ['해설', 'The son was trapped with no way out. Then an idea came to him.'],
      ['해설', 'He scratched the floor with his fingernails, making the sound of a rat gnawing.'],
      ['주인', 'A rat has gotten into the storehouse. It will ruin everything!'],
      ['해설', 'The moment the owner unlocked the door and looked in, the son shot out like an arrow and ran.'],
      ['해설', 'The household shouted and chased him. At a pond, the son threw a big stone into the water.'],
      ['주인', 'The thief fell into the water! Surround the pond and find him!'],
      ['해설', 'While everyone crowded around the pond, the son slipped away and got home safely.'],
      ['아들', 'Even birds and beasts protect their young. Why did you put me in such danger, Father?'],
      ['아버지', 'From now on, you will be a thief no one in the world can match.'],
      ['아버지', 'A skill learned from others has limits, but a skill you find yourself has endless uses.'],
      ['아버지', 'Besides, hard and desperate times make a person’s mind firm and his skill ripe.'],
      ['아버지', 'I drove you into a corner to keep you safe in the future.'],
      ['아버지', 'Getting out of the storehouse, throwing the stone into the pond, didn’t you think of it all by yourself?'],
      ['해설', 'Stealing is wrong, of course. Gang Hui-maeng borrowed this story to explain how learning works.'],
      ['해설', 'Do not stop at copying what others tell you. True skill comes from facing things and learning for yourself.'],
      ['해설', 'Hunja Oseol is a set of five essays that Gang Hui-maeng of early Joseon wrote to teach his son.'],
    ],
  },

  'ts-ganseochi': {
    title: 'The Life of a Book Fool',
    names: { 해설: 'Narrator', 이덕무: 'Yi Deok-mu' },
    outro: [
      'Yi Deok-mu called himself a fool who only reads books. What feelings are hidden in that name?',
      'It begins like someone else’s story and never gives a name. What flavor does that add?',
      'What do I get lost in, forgetting the time, no matter what others say?',
    ],
    lines: [
      ['해설', 'Yi Deok-mu was a scholar of late Joseon. He was a seoeol, a son of a concubine, so his path to office was blocked.'],
      ['해설', 'But he loved books more than anyone. Later King Jeongjo noticed him and made him a library official at Gyujanggak.'],
      ['해설', 'Ganseochijeon means the life of a fool who only reads books. In truth, Yi Deok-mu was writing about himself.'],
      ['해설', 'What follows is a retelling in modern words, not the original text.'],
      ['이덕무', 'Below Namsan Mountain there lived a foolish man.'],
      ['이덕무', 'He spoke clumsily, and he was lazy and awkward, so he knew little about worldly things.'],
      ['이덕무', 'He knew even less about baduk or janggi, the board games people played.'],
      ['이덕무', 'When people cursed him, he did not argue. When they praised him, he did not grow proud.'],
      ['이덕무', 'His only joy was reading. He forgot cold and heat, hunger and pain.'],
      ['이덕무', 'From childhood until he was twenty-one, he never let an old book leave his hands for a single day.'],
      ['이덕무', 'His room was very small, but it had windows on the east, the south, and the west.'],
      ['이덕무', 'He moved his seat as the sun moved, reading by its light.'],
      ['이덕무', 'When he got a book he had never read, he smiled with joy without knowing it.'],
      ['이덕무', 'So when his family saw him smiling, they knew he had found a rare book.'],
      ['이덕무', 'He especially loved the five-character poems of Du Fu, and he mumbled them like a sick man moaning.'],
      ['이덕무', 'When deep thought led him to understand something, he got up in delight and paced around the room.'],
      ['이덕무', 'The sound he made then was like the cawing of a crow.'],
      ['이덕무', 'Sometimes he stared quietly with wide-open eyes.'],
      ['이덕무', 'Other times he muttered to himself like a man in a dream.'],
      ['이덕무', 'People called him ganseochi, a fool who only reads books. He gladly accepted that name.'],
      ['이덕무', 'No one had written his life story, so I took up my brush to write it, and called it Ganseochijeon.'],
      ['이덕무', 'I do not write down his name.'],
      ['해설', 'It begins like someone else’s story, but as we read, we guess that it is the writer himself.'],
      ['해설', 'Calling himself a fool hides both a deep love of books and a quiet pride.'],
      ['해설', 'The essay shows a life given to what one loves, rather than to the world’s opinion.'],
      ['해설', 'Ganseochijeon comes down to us in Cheongjanggwan Jeonseo, the collected works of Yi Deok-mu.'],
    ],
  },
};
