// 청소년 영어 원고 (중학생 이상). 키 = stories/teen-talk3.js 의 이야기 id.
// 자체 집필 교양 강연(사회·경제)을 한국어 원고의 흐름대로 쉬운 강연체 영어로 새로 씀. 사실은 한국어 원고의 확인 메모와 같음.
// 한국 고유 낱말은 로마자로 쓰고 짧게 풀이.
export default {
  'tk3-money': {
    title: 'The Birth of Money',
    names: { 해설: 'Narrator', 강연자: 'Lecturer', 학생: 'Student' },
    outro: [
      'How did money solve the problems of barter?',
      'Why can paper or numbers in a record work as money?',
      'When I spend money, what promises am I trusting?',
    ],
    lines: [
      ['해설', 'Today’s lecture is about something we use every day: money.'],
      ['해설', 'When and why did money appear? Let’s listen to the lecturer.'],
      ['강연자', 'Imagine a time before money. People traded goods directly.'],
      ['강연자', 'We call this barter. For example, you give rice and get fish.'],
      ['강연자', 'But there was a big problem. Both sides had to want what the other had.'],
      ['강연자', 'What if I need fish, but the fisher wants shoes, not rice?'],
      ['학생', 'Then I have to find someone with shoes first. That sounds like a lot of trouble.'],
      ['강연자', 'Exactly. So things that everyone would accept became a bridge for trade.'],
      ['강연자', 'Depending on the place, shells, grain, salt, or cloth did this job.'],
      ['강연자', 'We call this commodity money. The money itself was a useful thing.'],
      ['강연자', 'But grain rots, cloth wears out, and both are heavy to carry.'],
      ['강연자', 'So people turned to metal, which lasts long and is easy to divide.'],
      ['강연자', 'Around the seventh century BC, some of the earliest coins appeared in Lydia.'],
      ['강연자', 'Lydia was a kingdom in what is now western Turkey.'],
      ['강연자', 'The state promised the weight and quality, so people did not have to weigh each piece.'],
      ['강연자', 'Next came paper. In Song China, people used paper money called jiaozi.'],
      ['학생', 'But paper itself is not very useful. Why did people accept it?'],
      ['강연자', 'Good question. The key is the belief that others will accept it, too.'],
      ['강연자', 'That belief is supported by the state, the law, and the promises of society.'],
      ['강연자', 'In Korea, in 996, under King Seongjong of Goryeo, iron coins called Geonwon Jungbo were made.'],
      ['강연자', 'But for a long time after that, people still used rice or hemp cloth like money.'],
      ['강연자', 'Money only takes root when people trust it and actually use it.'],
      ['강연자', 'To sum up, money helps exchange, measures value, and stores value.'],
      ['학생', 'So when I pay with a card, am I using money, too?'],
      ['강연자', 'Yes. Even when only numbers move, we trust the record, so it works as money.'],
      ['강연자', 'The form of money changes, but its base of trust stays the same.'],
      ['해설', 'From shells to numbers, money has changed its form together with trust.'],
      ['해설', 'In Joseon, a coin called Sangpyeong Tongbo came into wide use from 1678, under King Sukjong.'],
    ],
  },

  'tk3-market': {
    title: 'Markets and Prices',
    names: { 해설: 'Narrator', 강연자: 'Lecturer', 학생: 'Student' },
    outro: [
      'How is the equilibrium price decided?',
      'What costs are not shown in a price?',
      'When I decide whether to buy something, what signal does the price give me?',
    ],
    lines: [
      ['해설', 'Today’s lecture is about markets and prices. Who decides how much things cost?'],
      ['강연자', 'Everyone, why is fruit in season usually cheaper than fruit out of season?'],
      ['강연자', 'To answer this, we need two words: demand and supply.'],
      ['강연자', 'Demand is the wish and ability to buy. Supply is the wish and ability to sell.'],
      ['강연자', 'If other things stay the same, the higher the price, the less people want to buy.'],
      ['강연자', 'This is the law of demand. On the other hand, a higher price makes sellers want to sell more.'],
      ['강연자', 'This is the law of supply. The two forces move in opposite directions.'],
      ['학생', 'Buyers want it cheap and sellers want it expensive, so they always clash.'],
      ['강연자', 'Right. But at the end of that tug of war, there is a price where they meet.'],
      ['강연자', 'The price where the amount to buy equals the amount to sell is the equilibrium price.'],
      ['강연자', 'If the price is above it, goods are left over. This is called excess supply.'],
      ['강연자', 'Sellers lower the price to sell what is left, and it moves back toward equilibrium.'],
      ['강연자', 'If the price is below it, there are too many buyers. This is excess demand.'],
      ['강연자', 'Then the price rises, lines get longer, or the goods quickly run out.'],
      ['강연자', 'Now, back to fruit in season. In season, the harvest is big, so supply rises.'],
      ['강연자', 'When supply rises, prices tend to fall. Out of season, the opposite happens.'],
      ['학생', 'So is it because of demand that tickets for popular concerts sell out so fast?'],
      ['강연자', 'Yes. The number of seats is fixed, but many people want to go.'],
      ['강연자', 'In this way, prices become a signal of what is rare and what is common.'],
      ['강연자', 'The invisible hand, from Adam Smith’s book, is often used as an image for this market.'],
      ['강연자', 'But some point out that markets do not always solve every problem well.'],
      ['강연자', 'For example, when there are hidden costs like pollution, or when a monopoly appears.'],
      ['강연자', 'So economists also disagree about how far the government should step in.'],
      ['강연자', 'Those who trust the market and those who stress the government’s role both have reasons.'],
      ['학생', 'Then how can we know which side is right?'],
      ['강연자', 'In each case, we have to look at the data and carefully check the results.'],
      ['해설', 'A price is a signal made from the choices of countless people.'],
      ['해설', 'Adam Smith’s The Wealth of Nations was published in Britain in 1776.'],
    ],
  },

  'tk3-tax': {
    title: 'Why Do We Pay Taxes?',
    names: { 해설: 'Narrator', 강연자: 'Lecturer', 학생: 'Student' },
    outro: [
      'Why do we share the cost of common things through taxes?',
      'What does the rule that taxes must be set by law try to prevent?',
      'What taxes did I pay today, and what public services did I enjoy?',
    ],
    lines: [
      ['해설', 'Today’s topic is taxes. Why do we have to pay them?'],
      ['강연자', 'Think of the road you took to school. There were streets and traffic lights.'],
      ['강연자', 'When there is a fire, firefighters come. At night, streetlights light the way.'],
      ['강연자', 'These are not things one person buys and uses alone.'],
      ['강연자', 'Everyone uses them together, so we call them public goods. Taxes pay for them.'],
      ['학생', 'Can’t only the people who want to use them pay?'],
      ['강연자', 'Think of a streetlight. Can you stop people who did not pay from seeing its light?'],
      ['강연자', 'That would be hard. Then many people would want to use it without paying.'],
      ['강연자', 'So the community makes a promise to share the cost together.'],
      ['강연자', 'Taxes also pay for schools, hospitals, national defense, and welfare for neighbors in need.'],
      ['강연자', 'There are two main kinds of taxes: direct taxes and indirect taxes.'],
      ['강연자', 'A direct tax, like income tax, is paid and carried by the same person.'],
      ['강연자', 'An indirect tax is included in prices, so buyers pay it when they shop.'],
      ['강연자', 'Even when you buy a bag of snacks, you pay an indirect tax called value-added tax.'],
      ['학생', 'So I’ve already been paying taxes!'],
      ['강연자', 'That’s right. Taxes are not only a story for adults.'],
      ['강연자', 'But what if a country collected taxes however it liked?'],
      ['강연자', 'In history, heavy taxes often made people suffer and rise up in protest.'],
      ['강연자', 'Joseon’s Daedongbeop was a reform that let people pay rice and other goods instead of local specialties.'],
      ['강연자', 'Today, our Constitution says the kinds and rates of taxes must be set by law.'],
      ['강연자', 'This means the National Assembly, which the people elect, decides them.'],
      ['학생', 'How do we decide who should pay how much to be fair?'],
      ['강연자', 'People think differently about that. So we adjust it through debate and elections.'],
      ['강연자', 'Many people see taxes as membership fees for living together.'],
      ['강연자', 'Of course, it is also the citizens’ job to check that taxes are used properly.'],
      ['해설', 'Taxes are a way to prepare together the things we all share.'],
      ['해설', 'Joseon’s Daedongbeop was first carried out in Gyeonggi Province in 1608, under King Gwanghaegun.'],
      ['해설', 'Article 38 of the Korean Constitution says that all citizens have the duty to pay taxes.'],
    ],
  },

  'tk3-constitution': {
    title: 'Laws and the Constitution',
    names: { 해설: 'Narrator', 강연자: 'Lecturer', 학생: 'Student' },
    outro: [
      'How are a constitution and ordinary laws made differently?',
      'Why was the process of changing the Constitution made hard on purpose?',
      'Are there any rules in my class that clash with a higher rule?',
    ],
    lines: [
      ['해설', 'Today’s lecture looks at how laws and the Constitution are different.'],
      ['강연자', 'What comes to mind when you hear the word law? Maybe traffic rules.'],
      ['강연자', 'But there is a law above all other laws. It is the Constitution.'],
      ['학생', 'The Constitution is a law, too. Why does it have a special name?'],
      ['강연자', 'Because it is the most basic promise about how to run the country.'],
      ['강연자', 'It sets out people’s basic rights and the shape of bodies like the National Assembly, the government, and the courts.'],
      ['강연자', 'Article 1 of our Constitution says the Republic of Korea is a democratic republic.'],
      ['강연자', 'It also says that sovereignty belongs to the people, and all power comes from the people.'],
      ['강연자', 'Laws have layers. At the top is the Constitution. Below it are the acts the National Assembly makes.'],
      ['강연자', 'Below them are orders made by the government, and the local rules of local governments.'],
      ['강연자', 'A lower law must not go against a higher law.'],
      ['학생', 'What if the National Assembly makes a law that goes against the Constitution?'],
      ['강연자', 'The Constitutional Court can judge whether that law fits the Constitution.'],
      ['강연자', 'If it decides the law goes against the Constitution, the law loses its force, as a rule.'],
      ['강연자', 'They are also made differently. The National Assembly can pass or change an ordinary law by its vote.'],
      ['강연자', 'To change the Constitution, at least two thirds of all members of the National Assembly must agree first.'],
      ['강연자', 'Then comes a national vote. Over half of the voters must take part, and over half of them must agree.'],
      ['학생', 'Changing the Constitution is much harder. Why was it made that way?'],
      ['강연자', 'If the basic promise were easily shaken, people’s rights could be easily shaken, too.'],
      ['강연자', 'At the same time, it leaves a way open to change it when times change.'],
      ['강연자', 'When and how to change it is always a topic with many opinions.'],
      ['강연자', 'What matters is that the process must follow the steps the Constitution sets.'],
      ['강연자', 'Think of school. Class rules must not go against school rules.'],
      ['강연자', 'The layers of law are similar. The higher promise is the standard for the lower one.'],
      ['강연자', 'That is why the Constitution is often compared to the blueprint of a country.'],
      ['강연자', 'With a blueprint, every part of a house can find its proper place.'],
      ['해설', 'The Constitution is the country’s basic promise and the standard for all laws.'],
      ['해설', 'Our Constitution was proclaimed on July 17, 1948, and we mark this day as Constitution Day.'],
    ],
  },

  'tk3-powers': {
    title: 'The Separation of Powers',
    names: { 해설: 'Narrator', 강연자: 'Lecturer', 학생: 'Student' },
    outro: [
      'What does each of the legislative, executive, and judicial branches do?',
      'Why did people not only divide power but also make each branch check the others?',
      'What would happen in my class if the same person made the rules and judged them?',
    ],
    lines: [
      ['해설', 'Today’s lecture is about the separation of powers, which divides a country’s power into three.'],
      ['강연자', 'What if one person made the rules, carried them out, and also judged who broke them?'],
      ['학생', 'That person would do whatever they liked. Even if I were treated unfairly, I’d have nowhere to complain.'],
      ['강연자', 'The idea of the separation of powers came from exactly that worry.'],
      ['강연자', 'Power is divided into making laws, carrying them out, and judging. We call them legislative, executive, and judicial.'],
      ['강연자', 'In Korea, the National Assembly makes laws, the government carries them out, and the courts judge.'],
      ['강연자', 'Montesquieu of France is often named as the person who organized this idea clearly.'],
      ['강연자', 'In The Spirit of the Laws, he argued that freedom is in danger when power gathers in one place.'],
      ['강연자', 'Before him, John Locke of England had also said that power should be divided.'],
      ['강연자', 'The United States clearly built this principle into its Constitution in 1787.'],
      ['학생', 'But is dividing power enough? The branches might just go their own way.'],
      ['강연자', 'Sharp question. That is why checking each other matters as much as dividing.'],
      ['강연자', 'We call this checks and balances. Let’s look at a few examples.'],
      ['강연자', 'The National Assembly holds audits to see if the government is doing its job properly.'],
      ['강연자', 'The president can ask the National Assembly to vote again on a bill it has passed.'],
      ['강연자', 'This is often called the veto.'],
      ['강연자', 'Courts can ask whether a law used in a trial goes against the Constitution.'],
      ['강연자', 'If high officials break the Constitution or the law, the National Assembly can move to impeach them.'],
      ['강연자', 'The three branches watch one another, so that no side grows too strong.'],
      ['학생', 'With all that checking, things might get slow sometimes.'],
      ['강연자', 'True. Some see that as a weakness, and others see it as a safety device.'],
      ['강연자', 'How power is divided and what devices are used differ a little from country to country.'],
      ['강연자', 'Some countries have a presidential system, and others have a parliamentary system.'],
      ['강연자', 'But the idea of not putting all power in one place is widely accepted by democracies.'],
      ['강연자', 'If a player were also the referee, no one would trust the result of the game.'],
      ['강연자', 'In the end, the separation of powers is a device to protect everyone’s freedom.'],
      ['해설', 'The separation of powers divides power and makes the branches check each other to protect freedom.'],
      ['해설', 'Montesquieu’s The Spirit of the Laws was published in 1748.'],
    ],
  },

  'tk3-rights': {
    title: 'A History of Human Rights',
    names: { 해설: 'Narrator', 강연자: 'Lecturer', 학생: 'Student' },
    outro: [
      'Why did the Universal Declaration of Human Rights come after two world wars?',
      'What does it mean that the old rights documents were big steps but also had limits?',
      'When are dignity and rights not respected around me?',
    ],
    lines: [
      ['해설', 'Today we look at how human rights came to take their present shape.'],
      ['강연자', 'Human rights are the basic rights that every person should enjoy.'],
      ['강연자', 'They may seem natural now, but the idea grew little by little over a long time.'],
      ['강연자', 'Let’s follow its footsteps through a few documents.'],
      ['강연자', 'In 1215, English nobles made their king accept the Magna Carta, the Great Charter.'],
      ['강연자', 'It is seen as a seed of the idea that even the king must follow the law.'],
      ['강연자', 'But at that time, the people it protected were mainly nobles and some free men.'],
      ['강연자', 'In 1689, the English Bill of Rights stopped the king from collecting taxes without Parliament’s consent.'],
      ['강연자', 'In 1776, the American Declaration of Independence stated that all men are created equal.'],
      ['강연자', 'In 1789, during the French Revolution, the Declaration of the Rights of Man and of the Citizen appeared.'],
      ['학생', 'So did everyone become equal from then on?'],
      ['강연자', 'Sadly, no. Women, enslaved people, and the poor were left out for a long time.'],
      ['강연자', 'Many people had to work hard for a long time to close the gap between words and reality.'],
      ['강연자', 'So these documents are judged as big steps that also had limits.'],
      ['강연자', 'In the two world wars of the twentieth century, human dignity was badly trampled.'],
      ['강연자', 'In 1945, when the war ended, the United Nations was founded to keep the peace.'],
      ['강연자', 'Then in 1948, in Paris, the UN General Assembly adopted the Universal Declaration of Human Rights.'],
      ['강연자', 'Among the people who prepared it, Eleanor Roosevelt of the United States is well known.'],
      ['강연자', 'The Universal Declaration of Human Rights has thirty articles in all.'],
      ['강연자', 'Article 1 says that all people are born free and equal in dignity and rights.'],
      ['강연자', 'It goes on to rights such as life, liberty, freedom from torture, and education.'],
      ['학생', 'It’s a declaration, so it isn’t a law that must be obeyed, is it?'],
      ['강연자', 'That’s right. By itself, it was not a treaty with legal force.'],
      ['강연자', 'But it greatly influenced many later human rights treaties and national constitutions.'],
      ['강연자', 'The history of human rights is also a history of widening who can enjoy them.'],
      ['강연자', 'Many people believe that work is still going on.'],
      ['해설', 'Human rights were not given all at once. They are a promise widened by long effort.'],
      ['해설', 'December 10 is Human Rights Day, marking the adoption of the Universal Declaration.'],
    ],
  },

  'tk3-map': {
    title: 'The Rules of Maps',
    names: { 해설: 'Narrator', 강연자: 'Lecturer', 학생: 'Student' },
    outro: [
      'From where do we count latitude and longitude?',
      'Why must we give something up when we put the round Earth on a flat surface?',
      'What does the map I often use show large, and what does it shrink?',
    ],
    lines: [
      ['해설', 'Today’s lecture is about the rules behind how maps are drawn.'],
      ['강연자', 'In the middle of a wide ocean, how could you tell someone where you are?'],
      ['강연자', 'The sea has no buildings or street names. So people drew imaginary lines on the Earth.'],
      ['강연자', 'Lines drawn across are parallels. The number that shows their position is latitude.'],
      ['강연자', 'The equator is zero degrees. It is ninety degrees north to the North Pole, and ninety degrees south to the South Pole.'],
      ['강연자', 'Lines running from pole to pole are meridians. Their number is longitude.'],
      ['학생', 'Latitude starts at the equator. Where does longitude start?'],
      ['강연자', 'Good question. Longitude has no natural starting line.'],
      ['강연자', 'So in 1884, an international meeting chose the line through Greenwich, England, as the standard.'],
      ['강연자', 'This is the prime meridian. From here, we count up to 180 degrees east and west.'],
      ['강연자', 'With just these two numbers, you can point to any place on Earth.'],
      ['강연자', 'Korea Standard Time is also based on 135 degrees east longitude.'],
      ['강연자', 'But how did people learn the size of the Earth? Here is a story from ancient Greece.'],
      ['강연자', 'Eratosthenes noticed that, on the same day, the sun’s shadows fell at different angles in two cities.'],
      ['강연자', 'It is said he used that difference and the distance between the cities to calculate the Earth’s size quite closely.'],
      ['강연자', 'Today we know that the Earth is about forty thousand kilometers around.'],
      ['학생', 'But how do you put a round Earth onto flat paper?'],
      ['강연자', 'That is the puzzle of maps. If you flatten an orange peel, it tears or stretches.'],
      ['강연자', 'So every map gives up a little of area, shape, or distance.'],
      ['강연자', 'Mercator’s projection, made in 1569, showed directions correctly, so sailors used it.'],
      ['강연자', 'But lands grow larger toward the poles. Greenland looks very big.'],
      ['강연자', 'In fact, Africa is much larger than Greenland.'],
      ['강연자', 'Maps also have a scale. It tells how much real distance was shrunk.'],
      ['강연자', 'Contour lines connect places of the same height and show the rise and fall of the land.'],
      ['강연자', 'Today, we make far more exact maps with satellite photos and survey data.'],
      ['강연자', 'Still, we need an eye to see what a map stresses and what it leaves small.'],
      ['해설', 'A map is the result of rules and choices for putting the round Earth on a flat surface.'],
      ['해설', 'Kim Jeong-ho’s map of Korea, Daedong Yeojido, was printed from woodblocks in 1861.'],
    ],
  },

  'tk3-language': {
    title: 'Language Keeps Changing',
    names: { 해설: 'Narrator', 강연자: 'Lecturer', 학생: 'Student' },
    outro: [
      'What is the historical nature of language, and what examples can you give?',
      'How can language change while we still keep the shared rules that help us understand each other?',
      'Which words do I use that mean something different to my parents’ generation?',
    ],
    lines: [
      ['해설', 'Today we look at how the language we speak has changed over time.'],
      ['강연자', 'Have you ever heard a word you didn’t know while talking with your grandparents?'],
      ['강연자', 'And sometimes adults don’t understand the words you use.'],
      ['강연자', 'Like living things, words are born, change, and sometimes disappear.'],
      ['강연자', 'In Korean class, you learn this as the historical nature of language.'],
      ['강연자', 'Let’s start with letters. In 1443, King Sejong created Hunminjeongeum, the Korean alphabet.'],
      ['강연자', 'At first it had twenty-eight letters, but today we use twenty-four.'],
      ['학생', 'Where did the other four letters go?'],
      ['강연자', 'Four old letters, such as arae-a, slowly fell out of use.'],
      ['강연자', 'That is because the sounds they stood for changed or disappeared.'],
      ['강연자', 'Meanings change, too. The old word eorida once meant foolish.'],
      ['강연자', 'But today it means young.'],
      ['강연자', 'The old word eoyeobeuda meant pitiful, and it led to today’s word for pretty.'],
      ['학생', 'From pitiful to pretty? That’s amazing.'],
      ['강연자', 'Some explain that a feeling of pity turned into a feeling of care.'],
      ['강연자', 'The shapes of words change as well. Bulhwi in an old Joseon song is today’s ppuri, meaning root.'],
      ['강연자', 'New words appear, too. New things and new ideas need new names.'],
      ['강연자', 'Many words also came from other countries and settled in as Korean words.'],
      ['강연자', 'And when no one uses a word anymore, it quietly disappears.'],
      ['학생', 'So when language changes, does that mean it is breaking down?'],
      ['강연자', 'Linguists usually see change itself as natural.'],
      ['강연자', 'But shared rules for understanding each other matter, too. That is why we have standard language and spelling rules.'],
      ['강연자', 'Language lives and moves in a balance between change and shared rules.'],
      ['강연자', 'Remember also that even in the same period, each region has its own speech, called a dialect.'],
      ['강연자', 'A dialect is not wrong. It holds the history and life of its region.'],
      ['강연자', 'Someday, the words you use today will become old words, too.'],
      ['해설', 'Words are born, grow, and change together with the people who use them.'],
      ['해설', 'Hunminjeongeum was proclaimed in 1446, and Hangeul Day celebrates that proclamation.'],
    ],
  },

  'tk3-news': {
    title: 'Reading the News Wisely',
    names: { 해설: 'Narrator', 강연자: 'Lecturer', 학생: 'Student' },
    outro: [
      'What questions should we ask to judge whether news is trustworthy?',
      'How is doubting everything different from checking the evidence?',
      'Have I recently shared any news without checking it first?',
    ],
    lines: [
      ['해설', 'Today we learn how to pick out reliable information from a flood of news.'],
      ['강연자', 'How many news headlines do you see on your phone each day? Probably too many to count.'],
      ['강연자', 'Among them are accurate ones, wrong ones, and ones made up on purpose.'],
      ['강연자', 'Today, let’s practice five questions that help us sort them out.'],
      ['강연자', 'First, who wrote it? Check whether the source and the writer are made clear.'],
      ['강연자', 'If you cannot tell who wrote something, it is wise to step back.'],
      ['강연자', 'Second, when was it written? Old news sometimes spreads again as if it were new.'],
      ['학생', 'I didn’t know I had to check the date, too.'],
      ['강연자', 'Third, is it a fact or an opinion? The two are checked in different ways.'],
      ['강연자', 'Facts are checked against data. For opinions, we ask whether the reasons are strong.'],
      ['강연자', 'Fourth, can you find the same content somewhere else?'],
      ['강연자', 'Look at several different media and the original data from public agencies.'],
      ['강연자', 'Fifth, does it stir up your feelings too much? Be careful with posts that feed anger or fear.'],
      ['강연자', 'When feelings come first, it is easy to press share before checking.'],
      ['학생', 'If there’s a photo, can’t we believe it?'],
      ['강연자', 'Be careful with photos, too. A photo from another time or place is sometimes used in the wrong story.'],
      ['강연자', 'If you find where and when the photo first appeared, you can understand its context.'],
      ['강연자', 'Judging only by the headline is risky, too. The article sometimes says something different.'],
      ['강연자', 'Some ads look like news, so check whether there is an ad label.'],
      ['강연자', 'We should also ask ourselves whether we only read news that agrees with us.'],
      ['강연자', 'Hearing people who think differently makes our own judgment stronger.'],
      ['학생', 'Then should we doubt all news?'],
      ['강연자', 'Doubting everything is different from checking. The point is to look at the evidence.'],
      ['강연자', 'Trust well-checked information, and wait to judge what has not been checked.'],
      ['강연자', 'Just remembering who says it, when, and based on what will help a lot.'],
      ['강연자', 'The habit of checking once more before sharing protects everyone.'],
      ['해설', 'The ability to read news wisely is a basic skill for citizens who think for themselves.'],
      ['해설', 'Korea’s first modern newspaper, Hanseong Sunbo, was founded in 1883.'],
    ],
  },

  'tk3-climate': {
    title: 'The Evidence for Climate Change',
    names: { 해설: 'Narrator', 강연자: 'Lecturer', 학생: 'Student' },
    outro: [
      'How does the greenhouse effect keep the Earth warm?',
      'Why does it matter that many independent kinds of evidence point the same way?',
      'How can I tell the facts science gives us from the choices society must make?',
    ],
    lines: [
      ['해설', 'Today we look at the evidence scientists use to study climate change.'],
      ['강연자', 'First, let’s separate weather and climate. Rain today is weather.'],
      ['강연자', 'Climate is the average weather of a region over a long time, usually about thirty years.'],
      ['학생', 'So a cold winter this year doesn’t prove the climate hasn’t changed.'],
      ['강연자', 'Right. We have to look at the long trend, not one day or one year.'],
      ['강연자', 'Climate science starts with the greenhouse effect. The air is like a blanket over the Earth.'],
      ['강연자', 'Sunlight warms the ground, and the ground sends heat back out.'],
      ['강연자', 'Gases such as carbon dioxide and water vapor hold on to part of that heat.'],
      ['강연자', 'Without the greenhouse effect, the Earth would be a much colder planet.'],
      ['강연자', 'Around 1859, John Tyndall of Britain showed by experiment that such gases absorb heat.'],
      ['강연자', 'In the late nineteenth century, Svante Arrhenius of Sweden calculated the link between carbon dioxide and temperature.'],
      ['강연자', 'So, is carbon dioxide in the air really increasing?'],
      ['강연자', 'Since 1958, scientists have measured it steadily on Mauna Loa in Hawaii.'],
      ['강연자', 'That record shows that carbon dioxide levels have risen year after year.'],
      ['학생', 'How do we know about the air before measuring began?'],
      ['강연자', 'Deep in the ice of Antarctica and Greenland, old air is trapped in tiny bubbles.'],
      ['강연자', 'By drilling out ice cores and testing that air, we can learn about the distant past.'],
      ['강연자', 'Add to that thermometer records, shrinking glaciers, and rising seas.'],
      ['강연자', 'What matters is that many independent kinds of evidence point the same way.'],
      ['강연자', 'The group that reviews this research is the Intergovernmental Panel on Climate Change, the IPCC.'],
      ['강연자', 'The IPCC does not run its own experiments. It reviews scientists’ studies from around the world and writes reports.'],
      ['강연자', 'Those reports concluded that human activity is the main cause of recent global warming.'],
      ['학생', 'Then does science also decide what we should do next?'],
      ['강연자', 'Science tells us what is happening and why.'],
      ['강연자', 'How and how fast to respond is for society to discuss and decide together.'],
      ['강연자', 'There are many opinions in that discussion, but it should start from reliable evidence.'],
      ['해설', 'Climate science has grown from many kinds of observation and experiment supporting one another.'],
      ['해설', 'The IPCC was set up in 1988 by the World Meteorological Organization and the UN Environment Programme.'],
    ],
  },
};
