// 청소년 영어 원고: 세계 단편 영국·아일랜드 (stories/teen-ws3.js). 문장은 자체 각색.
// lines 의 첫 칸은 한국어 이야기 cast 의 이름 그대로.
export default {
  'wsb-nightingale': {
    title: 'The Nightingale and the Rose',
    names: { 해설: 'Narrator', 학생: 'Student', 나이팅게일: 'Nightingale', 도마뱀: 'Lizard', 장미나무: 'Rose-tree', 아가씨: 'Professor’s Daughter' },
    outro: [
      'What was Wilde saying about love by ending with a rose, paid for with a life, thrown into the street?',
      'How is the student, who trusts only his books and cannot understand the bird, shown in the story?',
      'Do we still see expensive gifts valued more than true feelings around us today?',
    ],
    lines: [
      ['해설', 'Beyond the garden, at a small window, a young student was crying.'],
      ['학생', 'She said she would dance with me if I brought her a red rose. But there is no red rose in my garden.'],
      ['해설', 'From her nest in the oak tree, the Nightingale heard him.'],
      ['나이팅게일', 'Here at last is a true lover. Night after night I have sung of him, and now I see him.'],
      ['학생', 'The Prince gives a ball tomorrow night. Without a rose, she will pass me by.'],
      ['도마뱀', 'He is crying over a red rose? How very silly!'],
      ['해설', 'The Lizard, the Butterfly and the Daisy laughed, but the Nightingale understood his sorrow.'],
      ['해설', 'She spread her wings and flew to a Rose-tree in the middle of the grass.'],
      ['나이팅게일', 'Give me one red rose, and I will sing you my sweetest song.'],
      ['장미나무', 'My roses are white. Go to my brother who grows round the old sundial.'],
      ['해설', 'The tree by the sundial had yellow roses. It sent her to its brother below the student’s window.'],
      ['장미나무', 'My roses are red. But the winter cold froze my buds, and I will have no roses this year.'],
      ['나이팅게일', 'One red rose is all I want. Is there really no way?'],
      ['장미나무', 'There is a way, but it is terrible. You must build the rose out of music by moonlight.'],
      ['장미나무', 'You must sing all night with your breast against a thorn. Your blood must flow into my veins.'],
      ['나이팅게일', 'Life is very dear. Yet love is better than life. What is the heart of a bird beside the heart of a man?'],
      ['나이팅게일', 'Be happy, you shall have your red rose. All I ask is that you be a true lover.'],
      ['해설', 'The student looked up, but he could not understand her. He only knew the things written in books.'],
      ['학생', 'She sings well, but she has no heart. She would never give up anything for others.'],
      ['해설', 'When the moon rose, the Nightingale pressed her breast against the thorn and began to sing.'],
      ['해설', 'She sang of the love of a boy and a girl, and a pale rose opened on the highest branch.'],
      ['장미나무', 'Press closer, little Nightingale. The rose must be finished before the day comes.'],
      ['해설', 'At last the thorn reached her heart. She sang of love made perfect by death, and the rose turned crimson.'],
      ['해설', 'When her last song ended, she fell into the long grass and did not move again.'],
      ['해설', 'In the morning, the student saw the red rose. He picked it and ran to the Professor’s house.'],
      ['학생', 'Here is the reddest rose in the world. Wear it tonight and dance with me.'],
      ['아가씨', 'It will not go with my dress. The Chamberlain’s nephew sent me real jewels. Jewels cost more than flowers.'],
      ['해설', 'Angrily, the student threw the rose into the street, and a cart wheel rolled over it.'],
      ['학생', 'What a silly thing love is! It is not half as useful as logic. I will go back to philosophy.'],
      ['해설', 'The Nightingale and the Rose appeared in 1888 in Wilde’s book The Happy Prince and Other Tales.'],
    ],
  },

  'wsb-canterville-1': {
    title: 'The Canterville Ghost, Part 1',
    names: { 해설: 'Narrator', 오티스: 'Mr. Otis', 엄니부인: 'Mrs. Umney', 워싱턴: 'Washington', 버지니아: 'Virginia', 유령: 'The Ghost', 쌍둥이: 'The Twins' },
    outro: [
      'In a story where a scary ghost becomes a joke, what is really being laughed at?',
      'What effect does the Otis family create by solving everything with products and cleaners?',
      'When old traditions meet new ideas, what happens in our society?',
    ],
    lines: [
      ['해설', 'Hiram B. Otis, the American Minister, bought Canterville Chase, an old house in England.'],
      ['해설', 'Lord Canterville honestly told him the house was haunted, but Mr. Otis only laughed.'],
      ['오티스', 'I come from a modern country. If there is a ghost, we can put it in an American museum.'],
      ['해설', 'On the day the family arrived, the sky suddenly grew dark, and heavy rain began to fall.'],
      ['해설', 'The old housekeeper, Mrs. Umney, led them to the library. There was a dark red stain by the fireplace.'],
      ['엄니부인', 'That is blood. In 1575, Lady Eleanore was murdered on that spot by her husband, Sir Simon.'],
      ['엄니부인', 'Nine years later, Sir Simon vanished. Since then, his spirit has haunted this house.'],
      ['워싱턴', 'Nonsense. Pinkerton’s Champion Stain Remover will clean it up in no time.'],
      ['해설', 'The eldest son, Washington, rubbed the floor with a small black stick, and the stain was gone.'],
      ['해설', 'At that moment, lightning flashed and thunder roared. Mrs. Umney fainted on the spot.'],
      ['해설', 'Next morning, the stain was back. Washington rubbed it away again and again, but it always returned.'],
      ['해설', 'One night at one o’clock, chains clanked in the hall. Mr. Otis put on his slippers and went out.'],
      ['해설', 'There stood an old man with burning red eyes. Rusty chains rattled on his wrists and ankles.'],
      ['오티스', 'My dear sir, you must oil those chains. I will leave you this American lubricator. One use will do.'],
      ['해설', 'Mr. Otis left the bottle on a table and went back to bed. The ghost smashed it on the floor in fury.'],
      ['해설', 'As the ghost ran off with a horrible laugh, two white pillows flew past his head.'],
      ['쌍둥이', 'Got him! We hit the ghost!'],
      ['유령', 'For three hundred years I have made duchesses faint and maids tremble. I have never met such rude people!'],
      ['해설', 'The ghost hid in his room for days. But every night, he still painted the stain in the library.'],
      ['해설', 'Strangely, the color changed every day. It was dull red, then bright red, then purple, then emerald green.'],
      ['버지니아', 'A green stain? That is so strange. Blood can’t be that color.'],
      ['해설', 'The family laughed, but fifteen-year-old Virginia always looked a little sad when she saw it.'],
      ['해설', 'At last the ghost planned a great revenge. Wrapped in a shroud, with a rusty dagger, he went toward the twins’ room.'],
      ['해설', 'But around the corner stood a horrible ghost, all in white, with a head like a turnip.'],
      ['유령', 'Ah! A ghost!'],
      ['해설', 'Having never seen a ghost before, the ghost fled to his room. Only at dawn did he creep back.'],
      ['해설', 'It was a dummy made of a bed curtain, a broom and a hollow turnip. A sign hung around its neck.'],
      ['쌍둥이', 'The Otis Ghost, the only true and original spook! Beware of imitations!'],
      ['유령', 'I have been tricked! I will pay those little devils back.'],
      ['해설', 'The Canterville Ghost first appeared in a magazine in 1887. Wilde was born in Dublin in 1854.'],
    ],
  },

  'wsb-canterville-2': {
    title: 'The Canterville Ghost, Part 2',
    names: { 해설: 'Narrator', 유령: 'The Ghost', 버지니아: 'Virginia', 부인: 'Mrs. Otis', 쌍둥이: 'The Twins', 공작: 'The Duke' },
    outro: [
      'As a funny ghost story turns into a story of forgiveness and rest, what does the work come to say?',
      'Virginia names the ghost’s crimes yet still prays for him. What does this show about her character?',
      'How is forgiving someone different from forgetting what they did?',
    ],
    lines: [
      ['해설', 'In the last part, the Otis family were not afraid of the Canterville ghost at all.'],
      ['해설', 'After that, the ghost lost again and again. The twins buttered the floors and hung jugs of water over doors.'],
      ['해설', 'Tired and ill, the ghost stopped dragging his chains. He stopped painting the stain, too.'],
      ['해설', 'One afternoon, Virginia saw the ghost sitting alone by a window in the Tapestry Room.'],
      ['해설', 'He looked so sad that Virginia forgot her fear and went to speak to him.'],
      ['버지니아', 'I am so sorry for you. My brothers go back to school soon. If you behave, nobody will bother you.'],
      ['유령', 'Behave? Rattling my chains and groaning is my job.'],
      ['버지니아', 'And you are a wicked man who killed his wife. I also know you took my paints for the stain.'],
      ['유령', 'Real blood is hard to find. As for my wife, her brothers starved me to death, so we are even.'],
      ['유령', 'I have not slept for three hundred years. Now I only want to rest.'],
      ['유령', 'Beyond the pine woods there is a Garden of Death. I want to lie in the grass there and sleep.'],
      ['유령', 'An old prophecy says that when a golden girl prays for a sinner, the dry almond tree will bloom.'],
      ['유령', 'Will you weep and pray for me? You will see terrible things in the dark, but they cannot hurt you.'],
      ['버지니아', 'I am not afraid. I will pray for you.'],
      ['해설', 'The ghost took her hand. The wall opened, and the two of them vanished into a cold wind.'],
      ['해설', 'By evening, Virginia was missing, and the house was in an uproar. Her father and brother searched all night.'],
      ['부인', 'Where in the world could our daughter be?'],
      ['해설', 'As the clock struck midnight, a wall at the top of the stairs opened, and a pale Virginia stepped out.'],
      ['버지니아', 'The ghost is dead. He was wicked, but he was truly sorry. And he gave me this box of jewels.'],
      ['해설', 'Virginia led her family to a secret room. A skeleton lay there, chained to the wall.'],
      ['해설', 'Just out of its reach were an empty plate and a water jug. Virginia knelt and prayed.'],
      ['쌍둥이', 'Look! The old dry almond tree is in bloom!'],
      ['해설', 'Outside the window, the old almond tree was white with blossoms in the moonlight.'],
      ['해설', 'Four days later, Sir Simon was buried under the pines. Virginia laid a cross of almond blossoms on the coffin.'],
      ['해설', 'Mr. Otis tried to return the jewels, but Lord Canterville said they belonged to the brave girl.'],
      ['해설', 'Some years later, Virginia married the Duke of Cheshire, who had loved her for a long time.'],
      ['공작', 'Virginia, will you never tell me what you saw with the ghost that night?'],
      ['버지니아', 'He taught me what life is, and what death means, and why love is stronger than both.'],
      ['해설', 'In 1891, The Canterville Ghost was included in Wilde’s book Lord Arthur Savile’s Crime and Other Stories.'],
    ],
  },

  'wsb-millionaire': {
    title: 'The Model Millionaire',
    names: { 해설: 'Narrator', 휴이: 'Hughie Erskine', 트레버: 'Alan Trevor', 노인: 'Old Beggar', 대령: 'Colonel Merton', 로라: 'Laura Merton' },
    outro: [
      'What did Wilde want to show through poor Hughie giving his last gold coin to a beggar?',
      'What fun comes from the title and the wordplay between a millionaire model and a model millionaire?',
      'Have you ever judged someone by their looks and been wrong? How did you feel?',
    ],
    lines: [
      ['해설', 'Hughie Erskine was handsome and kind, but he had no talent at all for making money.'],
      ['해설', 'All he had was two hundred pounds a year, left to him by an old aunt.'],
      ['해설', 'Hughie fell in love with Laura Merton, the daughter of a retired colonel. Laura loved him too.'],
      ['대령', 'Come to me when you have ten thousand pounds of your own. Then we will talk about marriage.'],
      ['로라', 'Father is always like that. But I will wait for you, Hughie.'],
      ['해설', 'One morning, on his way to see Laura, Hughie stopped at the studio of his friend Alan Trevor, a painter.'],
      ['해설', 'Trevor was painting a life-sized beggar. The model wore rags and leaned on a stick.'],
      ['휴이', 'What an amazing model! Where did you find a face like that?'],
      ['트레버', 'You meet a beggar like him once in a lifetime. Rembrandt would have made an etching of him.'],
      ['휴이', 'Poor old man. You will make a lot of money from this. How much do you pay him?'],
      ['트레버', 'A shilling an hour. The painting will sell for two thousand guineas.'],
      ['휴이', 'He works as hard as you do. That is not fair at all.'],
      ['트레버', 'You have no idea how hard painting is. Wait here. I need to talk to the frame-maker.'],
      ['해설', 'When Trevor left, the old man rested on a wooden bench. He looked so poor and lonely.'],
      ['해설', 'Hughie felt in his pocket. He had one gold coin and a few coppers. It was precious money to him, too.'],
      ['휴이', 'Poor old fellow. He needs this money far more than I do.'],
      ['해설', 'Hughie quietly pressed the gold coin into the old man’s hand. The man looked surprised, then smiled faintly.'],
      ['노인', 'Thank you, young man. Thank you very much.'],
      ['해설', 'Because of that, Hughie had to walk instead of taking a cab. That night he met Trevor at the club.'],
      ['트레버', 'That old man was very curious about you. He asked your name, your address and all about your money.'],
      ['휴이', 'Oh no. What if he tells everyone that I gave him a gold coin?'],
      ['트레버', 'He is Baron Hausberg, one of the richest men in Europe. He wanted a portrait of himself as a beggar.'],
      ['휴이', 'A baron? I gave a gold coin to a millionaire!'],
      ['해설', 'Trevor roared with laughter. Red in the face, Hughie walked slowly home.'],
      ['해설', 'Next morning, an old gentleman with gold glasses came with an envelope from the Baron.'],
      ['해설', 'On it was written, a wedding present to Hughie Erskine and Laura Merton, from an old beggar.'],
      ['해설', 'Inside was a check for ten thousand pounds.'],
      ['대령', 'Well, well. I have nothing more to say. You may marry my daughter.'],
      ['트레버', 'Millionaire models are rare enough. But model millionaires are rarer still!'],
      ['해설', 'The Model Millionaire first appeared in a magazine in 1887. In 1891 it was included in a book of Wilde’s stories.'],
    ],
  },

  'wsb-bottle-imp-1': {
    title: 'The Bottle Imp, Part 1',
    names: { 해설: 'Narrator', 케아웨: 'Keawe', 노인: 'Old Man', 로파카: 'Lopaka', 변호사: 'Lawyer' },
    outro: [
      'A bottle that grants every wish but demands hell as the price may stand for what kind of desire?',
      'When his wish came true through his uncle’s death, what do Keawe’s feelings show about him?',
      'How does the temptation to make a risky deal for something big appear today?',
    ],
    lines: [
      ['해설', 'On the island of Hawaii lived a young sailor named Keawe. He went to San Francisco to see the world.'],
      ['해설', 'Walking up a hill, he saw an old man with a worried face at the window of a palace-like house.'],
      ['노인', 'You seem to admire this house. Come in, and I will tell you how I got it.'],
      ['해설', 'The old man brought out a round-bellied glass bottle. Something like a shadow moved inside it.'],
      ['노인', 'An imp lives in this bottle. It gives its owner anything he wants, love or money.'],
      ['노인', 'But if you die with it, you will burn in hell forever. Sell it before then, and you are safe.'],
      ['노인', 'And you must sell it for less than you paid. Sell it for more, and it flies back like a pigeon.'],
      ['케아웨', 'If you have such a bottle, why do you look so troubled?'],
      ['노인', 'I have everything I wanted, and I am growing old. I will sell it to you for fifty dollars.'],
      ['해설', 'Half doubting, Keawe paid fifty dollars. Then he wished for his money back.'],
      ['해설', 'He put his hand in his pocket, and there were the fifty dollars. Scared, he tried to throw the bottle away.'],
      ['해설', 'But the bottle would not break, however hard he threw it. It always came back into his bag.'],
      ['해설', 'On the ship back to Hawaii, Keawe told everything to his friend Lopaka.'],
      ['로파카', 'Then make your wish first. After that, I will buy the bottle and wish for a ship.'],
      ['케아웨', 'I want a beautiful house with a garden. But I am afraid it will come through something evil.'],
      ['해설', 'In Hawaii, sad news was waiting. His rich uncle and his cousin had died, one after the other.'],
      ['변호사', 'Your uncle left all his land and money to you. You are a rich man now.'],
      ['케아웨', 'My uncle had to die for me to get a house. So this is how my wish came true.'],
      ['해설', 'His heart was heavy, but Keawe built a white house on a hill by the Kona coast.'],
      ['해설', 'Its windows sparkled in the sun, and every room was full of clocks, pictures and mirrors. People called it the Bright House.'],
      ['로파카', 'Now sell me the bottle, as you promised. But first, show me the imp just once.'],
      ['해설', 'When Keawe asked, the stopper came out. A small black thing jumped out and then slipped back in.'],
      ['해설', 'For a while, the two friends could not speak. That night, Lopaka bought the bottle for forty-nine dollars.'],
      ['케아웨', 'That is the end of it. I will never touch that bottle again.'],
      ['해설', 'Keawe lived in the Bright House. He was so happy that he laughed even as he lay in bed.'],
      ['해설', 'Still, when he remembered his uncle’s death and the shadow in the bottle, a chill ran through him.'],
      ['해설', 'But Keawe did not know yet. His story with the bottle was not over.'],
      ['해설', 'Stevenson spent his last years in Samoa in the South Pacific, and died there in 1894.'],
    ],
  },

  'wsb-bottle-imp-2': {
    title: 'The Bottle Imp, Part 2',
    names: { 해설: 'Narrator', 케아웨: 'Keawe', 코쿠아: 'Kokua', 청년: 'Young Man', 노인: 'Old Man', 갑판장: 'Boatswain' },
    outro: [
      'Keawe and Kokua are each ready to go to hell for the other. What does this say about love?',
      'How did the boatswain’s refusal to give up the bottle change the ending?',
      'Compared with times when sick people were sent far away, how do we treat patients today?',
    ],
    lines: [
      ['해설', 'In the last part, Keawe got the Bright House through the bottle imp, then sold the bottle to his friend.'],
      ['해설', 'One day, Keawe met a young woman named Kokua by the sea. Soon they promised to marry.'],
      ['해설', 'But that night, as he washed, Keawe froze. There was a patch on his skin. It was leprosy.'],
      ['해설', 'In Hawaii at that time, people with this disease were sent to Molokai Island, away from their families.'],
      ['해설', 'Today leprosy can be fully cured with medicine, and we know it does not spread easily.'],
      ['케아웨', 'What good is the Bright House if I cannot live with Kokua? I must find that bottle again.'],
      ['해설', 'Keawe went to Honolulu and followed the bottle. It had passed through many hands, and its price had fallen.'],
      ['해설', 'At last he found its owner, a young white man with a pale, frightened face.'],
      ['청년', 'I bought this bottle for two cents. Now I can only sell it for one cent.'],
      ['케아웨', 'If I buy it for one cent, I can never sell it again. Still, I will buy it.'],
      ['해설', 'Keawe made his wish, and his skin became clean. But he felt no joy. Now hell was waiting for him.'],
      ['해설', 'Even after the wedding, Keawe cried alone every night. At last Kokua asked him what was wrong.'],
      ['코쿠아', 'You risked your soul for me. This time, I will save you.'],
      ['코쿠아', 'There are coins smaller than a cent. French coins called centimes. Let us go to French Tahiti.'],
      ['해설', 'They went to Tahiti, but no one wanted a bottle with a devil in it. Only strange rumors spread.'],
      ['해설', 'One night, Kokua went to an old man sitting by the road and held out four coins.'],
      ['코쿠아', 'Please buy the bottle with this money. Then sell it back to me for three centimes.'],
      ['노인', 'A young wife buying hell? You must love your husband very much. I will do it.'],
      ['해설', 'So the bottle became Kokua’s. Keawe, knowing nothing, was overjoyed that the bottle had been sold.'],
      ['해설', 'But from his wife’s pale face and shaking voice, Keawe soon understood everything.'],
      ['케아웨', 'My wife is ready to go to hell for me. This time, I must save her.'],
      ['해설', 'Outside a bar, Keawe met a rough old boatswain. He gave him two centimes to buy the bottle.'],
      ['케아웨', 'Bring me the bottle, and I will buy it back for one centime. Then I alone will go to hell.'],
      ['해설', 'But the boatswain bought the bottle and would not give it up.'],
      ['갑판장', 'This is mine. Why would I give away a bottle that never runs out of brandy?'],
      ['케아웨', 'Don’t you know that if you die with it, you go to hell?'],
      ['갑판장', 'I am going there anyway. Now I have good company on the way. What more could I want?'],
      ['해설', 'Holding the bottle close, the boatswain staggered away. Keawe ran to his wife.'],
      ['해설', 'From that night on, peaceful days followed for the two of them in the Bright House.'],
      ['해설', 'The Bottle Imp came out in 1891 and was included in the 1893 book Island Nights’ Entertainments.'],
    ],
  },

  'wsb-three-strangers': {
    title: 'The Three Strangers',
    names: { 해설: 'Narrator', 페널: 'Shepherd Fennel', 페널부인: 'Mrs. Fennel', 첫손님: 'First Stranger', 둘째손님: 'Second Stranger', 셋째손님: 'Third Stranger', 순경: 'Constable' },
    outro: [
      'Through a man sentenced to hang for stealing one sheep, what side of the law did Hardy reveal?',
      'How is the first stranger, who calmly sang with the hangman, different from the third, who ran in fear?',
      'When a punishment set by law feels too harsh, how do you think people should act?',
    ],
    lines: [
      ['해설', 'It was a stormy night in March. On a lonely hill in Wessex stood the cottage of Shepherd Fennel.'],
      ['해설', 'That night there was a party to celebrate the christening of his second child. Neighbors danced and sang.'],
      ['페널부인', 'If the dancing goes on too long, the guests will drink everything. We must save the mead.'],
      ['해설', 'Then someone knocked. A stranger stood at the door, soaked with rain.'],
      ['첫손님', 'May I rest here for a while until the rain stops?'],
      ['페널', 'Of course, come in. It is a happy day, so rest as long as you like.'],
      ['해설', 'The man sat by the fire and borrowed some tobacco. He kept glancing at the door, like a hunted man.'],
      ['해설', 'Soon there was another knock. This time it was a round-faced man in gray clothes.'],
      ['둘째손님', 'Let me in too. I am going to Casterbridge, but this rain is too heavy.'],
      ['해설', 'The second stranger sat beside the first and gulped down the mead. Mrs. Fennel’s face grew stiff.'],
      ['페널부인', 'Who is this man, drinking up other people’s mead like that?'],
      ['페널', 'And what is your trade, sir?'],
      ['둘째손님', 'Let me tell you in a song. I hang people. I have a job at the jail tomorrow morning.'],
      ['해설', 'The room buzzed. He was the hangman. The first stranger sang loudly along with him.'],
      ['둘째손님', 'The man I hang tomorrow is a watchmaker. He stole a sheep to feed his hungry family.'],
      ['해설', 'In England at that time, a person could be hanged for stealing even one sheep.'],
      ['해설', 'Then a third man opened the door. When he saw the two men singing, his face went white.'],
      ['해설', 'The third man stumbled back, shut the door and ran off into the dark.'],
      ['해설', 'Just then, a gun boomed from the jail in the distance. It was the signal that a prisoner had escaped.'],
      ['둘째손님', 'My man has escaped! The one who just ran must be him. Everyone, after him!'],
      ['해설', 'The village constable and the men rushed up the hill with lanterns and sticks.'],
      ['해설', 'Meanwhile, the first stranger slipped quietly out of the cottage. Nobody paid him any attention.'],
      ['해설', 'They caught the third man hiding under a tree and took him to the jail.'],
      ['순경', 'He is not the one. The guards say he looks nothing like the prisoner.'],
      ['셋째손님', 'I am the prisoner’s brother. I was going to see him, and there he was, singing next to the hangman.'],
      ['셋째손님', 'His eyes told me to pretend I did not know him. So I ran, to protect him.'],
      ['해설', 'The first stranger, smoking by the fire, had been the escaped prisoner all along.'],
      ['해설', 'For days the neighbors only pretended to search. Hanging a man for one sheep seemed too cruel to them.'],
      ['해설', 'No one ever saw that man again.'],
      ['해설', 'The Three Strangers appeared in a magazine in 1883, and in Hardy’s 1888 book Wessex Tales.'],
    ],
  },

  'wsb-araby': {
    title: 'Araby',
    names: { 해설: 'Narrator', 소년: 'Boy', 맨건누나: 'Mangan’s Sister', 숙부: 'Uncle', 숙모: 'Aunt', 점원: 'Shop Girl' },
    outro: [
      'What did Joyce want to say through what the boy realized in the empty bazaar?',
      'How does the name Araby go from feeling magical to ending in disappointment for the boy?',
      'Have you ever been let down by something you waited for a long time? What did you learn?',
    ],
    lines: [
      ['해설', 'North Richmond Street in Dublin was a dead end. I lived there with my uncle and aunt.'],
      ['해설', 'On winter evenings, we played in the street until dark. Then Mangan’s sister would call her brother in.'],
      ['해설', 'For a long time I watched her dress swing and her soft hair move under the lamplight.'],
      ['해설', 'Every morning I lay by the window waiting for her. Then I followed her with my books.'],
      ['해설', 'Even in the noisy market streets, I said her name to myself like a prayer.'],
      ['해설', 'One day she spoke to me for the first time. I was so confused that I do not know what I answered.'],
      ['맨건누나', 'Are you going to Araby? I would love to go, but there is a retreat at my convent that week.'],
      ['소년', 'If I go, I will bring you something.'],
      ['해설', 'From that day, I could not focus on anything. Even in class, the word Araby rang in my head.'],
      ['해설', 'The word seemed to hold the magic of the East, and it held me under its spell.'],
      ['소년', 'Uncle, I want to go to the bazaar on Saturday night. May I have some money?'],
      ['숙부', 'Yes, yes. We will see on Saturday.'],
      ['해설', 'On Saturday, my uncle did not come home by evening. I walked around the empty upstairs rooms, listening to the clock.'],
      ['숙모', 'You had better give it up for tonight. It is too late now.'],
      ['해설', 'After nine, I heard his key at the door. He was talking to himself as he hung up his coat.'],
      ['숙부', 'Ah, that bazaar? I forgot all about it.'],
      ['숙모', 'You should have sent him earlier. You have kept him waiting far too long.'],
      ['숙부', 'All work and no play makes Jack a dull boy. Here, take this silver coin and go.'],
      ['해설', 'Holding the coin tight, I took an empty train. When I reached the bazaar, it was nearly ten.'],
      ['해설', 'Most of the great hall was dark. It was as silent as a church after the service.'],
      ['해설', 'I went to a stall that was still open. A young woman was laughing with two young Englishmen.'],
      ['점원', 'I never said such a thing! Really, I didn’t!'],
      ['해설', 'She turned to me, not very willingly.'],
      ['점원', 'Do you want to buy anything?'],
      ['소년', 'No, thank you.'],
      ['해설', 'I stood before the vases and teacups for a moment, then turned away. Someone shouted that the lights were going out.'],
      ['해설', 'Looking up into the dark, I saw myself as a creature driven and mocked by vanity.'],
      ['해설', 'My eyes burned with pain and anger.'],
      ['해설', 'Araby was published in 1914 in Joyce’s book of stories, Dubliners.'],
    ],
  },

  'wsb-garden-party': {
    title: 'The Garden Party',
    names: { 해설: 'Narrator', 로라: 'Laura', 일꾼: 'Workman', 조세: 'Jose', 엄마: 'Mrs. Sheridan', 여인: 'Woman', 로리: 'Laurie' },
    outro: [
      'What did Mansfield want to show by placing a grand party next to a poor neighbor’s death?',
      'What feelings are inside Laura’s words, sorry about her hat, in front of the dead man?',
      'Do we still see people in the same neighborhood living as if in different worlds?',
    ],
    lines: [
      ['해설', 'It was the perfect day for a garden party. There was no wind, and the sky had not a single cloud.'],
      ['해설', 'The Sheridan house was busy from early morning. Mother let the youngest daughter, Laura, look after the marquee.'],
      ['해설', 'Holding her bread and butter, Laura went into the garden to meet the men with the tent.'],
      ['일꾼', 'Miss, how about putting the marquee in front of those karaka trees? Everyone will see it there.'],
      ['로라', 'It would be a shame to hide those trees. Look how their leaves shine.'],
      ['해설', 'One workman picked a sprig of lavender and smelled it. Laura liked him for that.'],
      ['해설', 'She wished she could be friends with men like these. Class differences were so silly, she thought.'],
      ['해설', 'Pots of lilies arrived, and in the drawing room her sister Jose practiced singing at the piano.'],
      ['해설', 'Then terrible news came. A carter who lived in a cottage just below had been killed in an accident.'],
      ['해설', 'The young carter, Scott, was thrown from his frightened horse. He left a wife and five little children.'],
      ['로라', 'Jose, we must stop the party. A man has just died next door. We can’t have music.'],
      ['조세', 'Will that bring him back to life? Don’t be so sentimental.'],
      ['해설', 'Below the Sheridan house, poor little cottages stood by the road. The children were told never to go there.'],
      ['로라', 'Mother, they will hear our band from that house. It is too cruel.'],
      ['엄마', 'My dear, we cannot stop our party for something like that. Nobody expects us to.'],
      ['해설', 'Mother put her new hat on Laura. It was a black hat with gold daisies and a long black velvet ribbon.'],
      ['엄마', 'This hat looks much better on you.'],
      ['해설', 'Seeing herself in the mirror, Laura forgot the poor woman and her children for a while.'],
      ['해설', 'The party was beautiful. People strolled across the lawn, and everyone praised Laura’s hat.'],
      ['해설', 'After the guests left, Mother filled a basket with the leftover sandwiches and cakes.'],
      ['엄마', 'Laura, take this to that poor family. The children will love it.'],
      ['해설', 'Still wearing her hat, Laura carried the basket down the hill. People in the lane stared at her.'],
      ['해설', 'A woman opened the door and led Laura to an inner room. A young man lay there.'],
      ['여인', 'Go in and see him, miss. He looks fine. Just like he is asleep.'],
      ['해설', 'He was sleeping deeply and peacefully. Parties, baskets and lace dresses had nothing to do with him.'],
      ['로라', 'Forgive my hat.'],
      ['해설', 'Laura left the cottage in tears. At the end of the lane, her brother Laurie was waiting.'],
      ['로라', 'Laurie, isn’t life, isn’t life...'],
      ['로리', 'Isn’t it, darling?'],
      ['해설', 'The Garden Party is the title story of Mansfield’s 1922 book, The Garden Party.'],
    ],
  },

  'wsb-dolls-house': {
    title: 'The Doll’s House',
    names: { 해설: 'Narrator', 키지아: 'Kezia', 이저벨: 'Isabel', 릴: 'Lil Kelvey', 베릴이모: 'Aunt Beryl', 엘스: 'Else Kelvey' },
    outro: [
      'Through the children’s quarrel over a doll’s house, what adult world did Mansfield want to show?',
      'Even after being chased away, Else smiles and says she saw the little lamp. How does that ending stay with you?',
      'What would it take to stop someone being left out because of family background or rumors?',
    ],
    lines: [
      ['해설', 'A big doll’s house arrived for the Burnell children. It was a gift from old Mrs. Hay.'],
      ['해설', 'It had dark spinach-green walls and yellow windows. When the front opened, you could see every room.'],
      ['해설', 'Of all its treasures, the youngest girl, Kezia, loved the little amber lamp on the dining table.'],
      ['키지아', 'Look at that lamp. It looks like it could really light up.'],
      ['해설', 'The children could hardly wait to show it off at school. Mother said they could bring friends two at a time.'],
      ['이저벨', 'I am the eldest, so I will tell them first. And I will choose who comes.'],
      ['해설', 'At school, the children crowded around Isabel. But two girls only watched from far away.'],
      ['해설', 'They were the Kelvey sisters, Lil and Else. Their mother did other people’s washing, and people said their father was in prison.'],
      ['해설', 'Parents did not let their children play with the sisters. Even the teacher used a different voice with them.'],
      ['해설', 'Lil wore old clothes cut down from other people’s, and little Else always held on to her sister’s skirt.'],
      ['이저벨', 'There is a real carpet in the drawing room, and the oven in the kitchen has a door that opens.'],
      ['키지아', 'Isabel, you forgot the lamp.'],
      ['이저벨', 'Oh, right. There is a little lamp on the dining table, and it looks just like a real one.'],
      ['해설', 'Within a few days, every girl in class had seen the doll’s house, except the Kelveys.'],
      ['키지아', 'Mother, can’t the Kelveys see it just once?'],
      ['해설', 'Mother said certainly not. When Kezia asked why, Mother only said she knew quite well why.'],
      ['해설', 'At playtime, the girls circled the Kelveys and laughed, asking if they would be servants when they grew up.'],
      ['해설', 'Lil only smiled awkwardly, and Else looked at her sister without a word.'],
      ['해설', 'One afternoon, Kezia was swinging on the gate when she saw the Kelvey sisters coming down the road.'],
      ['키지아', 'You can come and see our doll’s house if you want.'],
      ['릴', 'Your mother told our mother that you are not allowed to speak to us.'],
      ['키지아', 'That doesn’t matter. Nobody is looking.'],
      ['해설', 'Kezia led them into the yard and opened the front of the doll’s house wide.'],
      ['키지아', 'This is the drawing room, and that is the dining room, and this is the...'],
      ['베릴이모', 'Kezia! Who let these children in? Off you go at once, and never come back!'],
      ['해설', 'Aunt Beryl shooed them out like chickens. The sisters shrank and hurried away.'],
      ['해설', 'After walking a long way, they sat down on a big pipe by the road. Lil’s cheeks were still burning.'],
      ['엘스', 'I seen the little lamp.'],
      ['해설', 'Else said only that, and smiled quietly. Then the two were silent again.'],
      ['해설', 'Born in New Zealand, Mansfield died in 1923 at the age of thirty-four.'],
    ],
  },

  'wsb-open-window': {
    title: 'The Open Window',
    names: { 해설: 'Narrator', 프램턴: 'Framton Nuttel', 베라: 'Vera', 새플턴부인: 'Mrs. Sappleton' },
    outro: [
      'With an adult fooled by a girl’s made-up story, what was Saki poking fun at?',
      'How did you feel when you learned who Vera, the girl telling a sad tale to the guest, really was?',
      'Where today do we see trouble caused by believing a good story without checking the facts?',
    ],
    lines: [
      ['해설', 'Framton Nuttel came to a quiet country village to cure his nerves.'],
      ['해설', 'Worried he would be lonely, his sister wrote him several letters of introduction to people there.'],
      ['해설', 'At Mrs. Sappleton’s house, her fifteen-year-old niece, Vera, came down to meet him first.'],
      ['베라', 'My aunt will be down soon. Until then, I will keep you company. Do you know many people here?'],
      ['프램턴', 'Hardly anyone. My sister stayed near here about four years ago, so she gave me letters.'],
      ['베라', 'Then you know nothing about my aunt’s great tragedy.'],
      ['해설', 'Vera pointed to a large window that stood wide open, though it was an October afternoon.'],
      ['베라', 'Three years ago today, my uncle and my aunt’s two brothers went out through that window to hunt.'],
      ['베라', 'They sank into a bog on the moor and never came back. Their bodies were never found.'],
      ['베라', 'But my aunt believes they will return. So every day she keeps the window open until dusk.'],
      ['베라', 'My uncle had his white raincoat over his arm. Ronnie, the youngest, was singing, Bertie, why do you bound?'],
      ['해설', 'Vera’s voice shook. A chill ran down Framton’s back. Then Mrs. Sappleton came in.'],
      ['새플턴부인', 'You don’t mind the open window? My husband and brothers will be home from hunting soon. They always come in this way.'],
      ['새플턴부인', 'They have gone after snipe in the marshes, so my carpets will be covered in mud.'],
      ['해설', 'She chatted happily about hunting. Framton, horrified, tried hard to change the subject.'],
      ['프램턴', 'The doctors say I need complete rest. No excitement, and no hard exercise.'],
      ['새플턴부인', 'Oh, really?'],
      ['해설', 'She seemed to hold back a yawn. Then suddenly she looked out the window, and her eyes lit up.'],
      ['새플턴부인', 'Here they are at last! Just in time for tea. Look at them, covered in mud!'],
      ['해설', 'Framton turned to Vera. The girl was staring out the window with eyes full of horror.'],
      ['해설', 'In the twilight, three men were walking toward the house with guns. One had a white coat over his arm.'],
      ['해설', 'A brown spaniel followed them. Someone sang in a hoarse voice. Bertie, why do you bound?'],
      ['해설', 'Framton grabbed his stick and hat and dashed out, nearly crashing into a man on a bicycle.'],
      ['새플턴부인', 'Dear, a strange man just ran out. He talked only about his illness and left without saying goodbye.'],
      ['베라', 'It must be the dog. He is terribly afraid of dogs.'],
      ['베라', 'In India, by the Ganges, he was chased by wild dogs and spent a night in a newly dug grave.'],
      ['베라', 'The dogs snarled above him, showing their teeth. Anyone’s nerves would be ruined after that.'],
      ['해설', 'Making up a believable story on the spot was Vera’s special talent.'],
      ['해설', 'The Open Window appeared in a 1914 book by Saki. Saki was the pen name of Hector Hugh Munro.'],
    ],
  },
};
