// 청소년 영어 원고 (중학생 이상). 키 = stories/teen-ws2.js 의 이야기 id.
// 프랑스·유럽 단편(퍼블릭 도메인)을 한국어 각색의 흐름대로 쉬운 영어로 새로 씀. 이름은 원작 표기.
export default {
  'wse-string': {
    title: 'The Piece of String',
    names: { 해설: 'Narrator', 오슈코른: 'Hauchecorne', 말랑댕: 'Malandain', 면장: 'Mayor', 포고꾼: 'Town Crier', 마을사람: 'Villager' },
    outro: [
      'Old Hauchecorne told the truth. Why could he never win people’s trust?',
      'The more he explains, the longer his story gets and the more people laugh. How does this deepen his tragedy?',
      'Where today can we see rumors and labels destroy a person?',
    ],
    lines: [
      ['해설', 'It was market day. Old Hauchecorne of Bréauté was also heading to the market in Goderville.'],
      ['해설', 'At the edge of the market, he saw a short piece of string lying on the ground.'],
      ['해설', 'Like a true Norman farmer who never passes up anything useful, he bent down and picked it up.'],
      ['해설', 'Just then, Malandain the harness maker was watching from his doorway. The two had quarreled long ago.'],
      ['해설', 'Ashamed to be seen picking up trash, the old man slipped the string into his pocket and pretended nothing happened.'],
      ['해설', 'Around noon, while people were eating lunch at the inn, a drum sounded outside.'],
      ['포고꾼', 'Attention! This morning, on the Beuzeville road, a black leather wallet with five hundred francs was lost.'],
      ['포고꾼', 'The finder should return it to Mr. Houlbrèque of Manneville. There is a reward of twenty francs.'],
      ['해설', 'Soon a police officer came into the inn looking for Hauchecorne. The mayor wanted to see him.'],
      ['면장', 'Mr. Hauchecorne, someone saw you pick up that wallet this morning.'],
      ['오슈코른', 'Me? Who on earth said that?'],
      ['면장', 'Mr. Malandain, the harness maker.'],
      ['오슈코른', 'Ah, that nasty man! Mr. Mayor, this is all I picked up. Just this piece of string.'],
      ['말랑댕', 'I saw it clearly. He picked something up and looked around for a long time for more.'],
      ['오슈코른', 'I swear before God, it’s a lie! I swear on my life!'],
      ['해설', 'He was even searched, but nothing was found. The mayor still doubted him but let him go.'],
      ['해설', 'The rumor had already spread. He showed his string to everyone he met and told them he was innocent.'],
      ['마을사람', 'Yes, yes, a piece of string. But I heard that string was pretty heavy.'],
      ['해설', 'The next day, Marius Paumelle, a farmhand from Ymauville, returned the wallet. He said he found it on the road.'],
      ['오슈코른', 'You see? I was right! A lie always comes out in the end!'],
      ['해설', 'Happily, the old man told everyone in town. But people reacted strangely.'],
      ['마을사람', 'Ha, you’re a clever one, old man. One man picks it up, and another one returns it, right?'],
      ['해설', 'He could hardly breathe. People believed he had made a partner return the wallet.'],
      ['해설', 'He explained again and again. His story grew longer and his oaths grew bigger, but people only laughed more.'],
      ['마을사람', 'Here comes Old Man String! Won’t you tell us the string story today?'],
      ['해설', 'He stopped working and grew visibly thin. The suspicion stuck in his heart was eating him away.'],
      ['해설', 'At the end of December, he took to his bed. Until his death, he kept repeating the same words.'],
      ['오슈코른', 'A piece of string, just a little piece of string. Look, Mr. Mayor, here it is.'],
      ['해설', 'The Piece of String is a short story by Maupassant, published in 1883 and set in a Norman market town.'],
    ],
  },

  'wse-two-friends': {
    title: 'Two Friends',
    names: { 해설: 'Narrator', 모리소: 'Morissot', 소바주: 'Sauvage', 대령: 'Colonel', 장교: 'Officer' },
    outro: [
      'By placing the friends’ fishing beside their death, what side of war did Maupassant want to show?',
      'How do the friends’ short goodbyes and the officer’s last words make you feel?',
      'How does violence that takes away ordinary people’s small joys still appear today?',
    ],
    lines: [
      ['해설', 'Paris was surrounded by the enemy and starving. That winter, even sparrows on the roofs were rare.'],
      ['해설', 'One clear January morning, Morissot, a watchmaker, walked down the boulevard in his guard uniform, with an empty stomach.'],
      ['해설', 'Then he saw a familiar face. It was Mr. Sauvage, a shopkeeper he used to fish with every Sunday before the war.'],
      ['해설', 'They had become friends sitting side by side on the riverbank at Marante Island. They spoke little, but understood each other.'],
      ['소바주', 'Mr. Morissot! How long has it been? The world has become terrible.'],
      ['모리소', 'Yes, it has. And yet the weather is so fine. It’s the first clear day this year.'],
      ['해설', 'They each drank a glass of absinthe at a café. On empty stomachs, the drink made them excited.'],
      ['소바주', 'How about it? Shall we go there? Fishing?'],
      ['모리소', 'Yes! But how can we get there?'],
      ['소바주', 'Colonel Dumoulin at the outposts is my friend. Let’s ask him for a pass.'],
      ['대령', 'Fishing? Ha, all right. But once you cross our lines, no one can protect you.'],
      ['해설', 'They crossed the empty fields near Colombes and went down to the river. Beyond the far hills were the Prussians.'],
      ['해설', 'In their old spot, they cast their lines. Silver fish came up one after another, and the basket filled.'],
      ['해설', 'Now and then, cannons roared from Fort Mont-Valérien, and the ground shook. White smoke rose into the sky.'],
      ['모리소', 'They’re firing again. With every shot, someone must be dying.'],
      ['소바주', 'It’s so stupid. Killing each other like that. It’s worse than animals.'],
      ['해설', 'Then they heard footsteps behind them. Four bearded soldiers stood there, pointing their guns.'],
      ['해설', 'The two men were taken to the island and brought before a Prussian officer. He spoke perfect French.'],
      ['장교', 'Did you enjoy your fishing? But you are spies sent to watch us. Spies are shot.'],
      ['장교', 'But tell me the password to get back through your lines, and I will let you live. No one will know.'],
      ['해설', 'Pale, the two men kept silent. The officer took Morissot aside and whispered.'],
      ['장교', 'Your friend won’t know. I am a soft-hearted man, so I say this. Just tell me the password.'],
      ['해설', 'Morissot shook his head. So did Sauvage. Twelve soldiers lined up with their guns.'],
      ['모리소', 'Goodbye, Mr. Sauvage.'],
      ['소바주', 'Goodbye, Mr. Morissot.'],
      ['해설', 'They shook hands. Shots rang out, and they fell. The soldiers tied stones to them and threw them into the river.'],
      ['해설', 'The officer noticed the fishing basket left on the grass. The fish were still jumping.'],
      ['장교', 'Wilhelm, fry these little things right away. They taste best while they’re still alive.'],
      ['해설', 'Two Friends is a short story by Maupassant, published in 1883. It is set during the siege of Paris in the Franco-Prussian War.'],
    ],
  },

  'wse-uncle-jules': {
    title: 'My Uncle Jules',
    names: { 해설: 'Narrator', 조제프: 'Joseph', 아버지: 'Father', 어머니: 'Mother', 선장: 'Captain', 쥘: 'Jules' },
    outro: [
      'Why did the family treat the rich uncle they imagined and the poor oyster seller so differently?',
      'How does the opening, where grown-up Joseph gives coins to beggars, change how we see the whole story?',
      'Do people still turn away from those close to them because of money or pride?',
    ],
    lines: [
      ['해설', 'I, Joseph Davranche, always give a silver coin to an old beggar. There is a reason for this.'],
      ['해설', 'We lived in Le Havre. My father was a poorly paid clerk, and we always tried to hide our poverty.'],
      ['해설', 'Every Sunday, the whole family put on our best clothes and went for a walk on the pier.'],
      ['해설', 'Whenever a big ship came in from the open sea, my father said the same thing.'],
      ['아버지', 'What a surprise it would be if Jules were on that ship!'],
      ['해설', 'Uncle Jules was my father’s younger brother. As a young man, he wasted money and even ate into my father’s inheritance.'],
      ['해설', 'Since he was the family’s problem, he was shipped off to America. But a few years later, a letter came.'],
      ['쥘', 'Brother, I have made good money here in business. When I have saved enough, I will come back and live with you.'],
      ['해설', 'With one letter, my uncle went from black sheep to family hope. My mother read it until it wore thin.'],
      ['어머니', 'When he comes back, everything will change for us. Jules is such a good man.'],
      ['해설', 'A man proposed to my younger sister after seeing that letter. After the wedding, we took a trip to Jersey.'],
      ['해설', 'On the boat, my father proudly bought oysters for his daughters and son-in-law.'],
      ['해설', 'The old man opening the oysters was wrinkled and dressed in rags. My father’s face went white.'],
      ['아버지', 'Dear, that oyster seller looks just like Jules.'],
      ['어머니', 'What nonsense. If you’re so worried, go ask the captain.'],
      ['아버지', 'Captain, who is that oyster seller?'],
      ['선장', 'An old French tramp. I brought him back from America. He has family here, but he owes them money, so he won’t go.'],
      ['해설', 'The name the captain added was Jules Davranche. My father came back unsteady, and my mother’s face hardened.'],
      ['어머니', 'I knew that thief would never become anything! If our son-in-law finds out, it’s a disaster.'],
      ['어머니', 'Joseph, go and pay for the oysters. Don’t say a word to that man.'],
      ['해설', 'I went up to my uncle. His hands holding the oysters were rough, and his eyes were tired.'],
      ['조제프', 'How much are the oysters?'],
      ['쥘', 'Two francs fifty.'],
      ['해설', 'I paid and added a ten-sou tip. And in my heart, I called him uncle.'],
      ['쥘', 'Thank you, young sir. God bless you.'],
      ['어머니', 'You gave him ten sous? Are you out of your mind? To a man like that!'],
      ['해설', 'On the way back, we took a different boat to avoid him. I never saw my uncle again.'],
      ['해설', 'That is why I still give coins to old men on the street. He might be someone’s abandoned uncle.'],
      ['해설', 'My Uncle Jules is a short story by Maupassant, published in 1883. It is set in the port city of Le Havre.'],
    ],
  },

  'wse-stars': {
    title: 'The Stars',
    names: { 해설: 'Narrator', 목동: 'Shepherd', 스테파네트: 'Stephanette' },
    outro: [
      'Why was the shepherd able to keep that night so pure and calm?',
      'How do the shepherd’s star names and the final image of a star on his shoulder make you feel?',
      'What does it mean in our lives to treasure feelings we cannot say out loud?',
    ],
    lines: [
      ['해설', 'When I kept sheep on the Luberon mountain, I saw no one but my dog and sheep for weeks.'],
      ['해설', 'Every two weeks, the farm boy or old Aunt Norade brought food up on a mule.'],
      ['해설', 'I asked them for news from below. What I wanted to know most was about Stephanette, my master’s daughter.'],
      ['해설', 'To a twenty-year-old shepherd, she was the most beautiful person around. I could never speak to her.'],
      ['해설', 'One Sunday afternoon, the food was late. Then I heard mule bells. On the mule sat Stephanette herself.'],
      ['스테파네트', 'The boy is sick, and Aunt Norade went to visit her children. So I came. I almost got lost.'],
      ['해설', 'She looked curiously around my hut. The straw bed, the coat on the wall, my staff, and my old gun.'],
      ['스테파네트', 'So this is where you live. Don’t you get lonely? What do you think about up here?'],
      ['해설', 'I wanted to say that I thought of her. But I only blushed and could not say a word.'],
      ['해설', 'She went down the mountain with the empty basket. The fading sound of the bells stayed with me for a long time.'],
      ['해설', 'At sunset, she came back soaking wet. The rain had swollen the Sorgue River, and she could not cross.'],
      ['스테파네트', 'What should I do? They’ll be worried at home. And I can’t go down this mountain at night.'],
      ['목동', 'Don’t worry, miss. It’s July, so the night is short. Morning will come soon.'],
      ['해설', 'I made a fire to dry her wet feet and brought her milk and cheese.'],
      ['해설', 'Then I spread fresh straw in the sheepfold, covered it with a sheepskin, and made her a bed.'],
      ['해설', 'I kept watch by the fire outside. My heart was full, knowing she slept near my sheep.'],
      ['해설', 'Soon the door creaked open, and she came out. The restless sheep kept her awake, she said.'],
      ['해설', 'I put a sheepskin around her shoulders and stirred up the fire. The mountain night was full of small sounds.'],
      ['스테파네트', 'There are so many stars. Do you know all their names?'],
      ['목동', 'Of course. Right above us is the Way of Saint James. It runs straight from France to Spain.'],
      ['목동', 'Over there, with four shining wheels, is the Chariot of Souls. Those three stars in a row are the Three Kings. They are our shepherds’ clock.'],
      ['스테파네트', 'Then what is that brightest star over there?'],
      ['목동', 'That is the Shepherd’s Star. It lights our way when we lead the sheep out at dawn and home at night.'],
      ['목동', 'We also call her Maguelonne. She chases Pierre of Provence and marries him once every seven years.'],
      ['스테파네트', 'Oh, do stars get married too?'],
      ['해설', 'Then something light and soft rested on my shoulder. It was her sleeping head.'],
      ['해설', 'I did not move. I watched the stars until dawn. My heart was clear, and I had only gentle thoughts.'],
      ['해설', 'I thought that the finest, brightest star had lost its way and come down to sleep on my shoulder.'],
      ['해설', 'In those days, a gap no one could cross lay between a master’s daughter and a shepherd. That made the night shine more quietly.'],
      ['해설', 'The Stars appears in Letters from My Windmill, by Alphonse Daudet, who was born in Nîmes, France.'],
    ],
  },

  'wse-cornille': {
    title: 'The Secret of Master Cornille',
    names: { 해설: 'Narrator', 프랑세: 'Francet', 코르니유: 'Cornille', 비베트: 'Vivette', 아들: 'Son' },
    outro: [
      'What was Master Cornille trying to protect by turning an empty millstone?',
      'How do the white earth pouring out and the old man crying over the wheat show his heart?',
      'How can our society protect the pride of people pushed aside by new technology?',
    ],
    lines: [
      ['해설', 'One evening, old Francet Mamaï, the fife player, drank wine and told an old village story.'],
      ['프랑세', 'This land used to be full of mills. On every hill, windmill sails turned in the mistral wind.'],
      ['해설', 'People brought wheat to the hilltop mills on mules. On Sundays, there was dancing in front of the mills.'],
      ['해설', 'But then Parisians built a steam mill on the Tarascon road. People followed the new thing there.'],
      ['해설', 'One by one, the windmills stopped, and their sails broke. Only Master Cornille’s windmill kept turning.'],
      ['해설', 'Cornille was a miller who had lived in flour for sixty years. He hated the steam mill.'],
      ['코르니유', 'A steam mill! That is the devil’s machine. Our windmills turn by the wind, the breath of God!'],
      ['해설', 'He sent away his only granddaughter, Vivette, to work on other farms and shut himself up in his mill.'],
      ['해설', 'It was strange. Nobody brought him wheat, yet his windmill turned every day.'],
      ['해설', 'In the evenings, people also saw him leading a mule loaded with heavy sacks along the road.'],
      ['프랑세', 'If anyone asked, he winked and said he had too much work. We all wondered about it.'],
      ['해설', 'Around then, Francet’s eldest son and Vivette fell in love. Francet climbed up to the mill to talk of marriage.'],
      ['코르니유', 'Go back! Go play your fife. Don’t poke around in another man’s mill!'],
      ['해설', 'A few days later, the young couple went to the mill while the old man was out. The door was locked, but they climbed in a window.'],
      ['비베트', 'I have to know what Grandfather is hiding. Let’s see how busy he really is.'],
      ['해설', 'The mill was empty. The millstone was turning with nothing in it. There was not a grain of wheat or a handful of flour.'],
      ['해설', 'When they opened the sacks in the corner, white earth and broken plaster poured out instead of wheat.'],
      ['아들', 'Look. This is what he was carrying on his mule.'],
      ['비베트', 'To protect the honor of his mill, Grandfather fooled everyone by turning an empty millstone.'],
      ['해설', 'In tears, the two ran to the village and told what they had seen. That night, every house gathered wheat.'],
      ['해설', 'The next day, mules loaded with wheat climbed the hill in a line. The old man was sitting on a sack of earth, crying.'],
      ['코르니유', 'Now I must die. The shame of my mill has been discovered.'],
      ['해설', 'Then the people shouted. Hey, miller! We brought wheat, real wheat!'],
      ['해설', 'The old man opened his eyes wide and put his hand into a sack. Holding a handful of grain, he cried and laughed.'],
      ['코르니유', 'Wheat! Good Lord, good wheat! My mill nearly starved to death.'],
      ['해설', 'From that day, people brought him work. He turned his millstone until the day he died.'],
      ['프랑세', 'After he was gone, no one took over the mill. What can you do? Everything in this world has an end.'],
      ['해설', 'As machines pushed out handwork, the villagers protected an old craftsman’s pride with sacks of wheat, not mockery.'],
      ['해설', 'The Secret of Master Cornille appears in Daudet’s collection, Letters from My Windmill.'],
    ],
  },

  'wse-goat': {
    title: 'Monsieur Seguin’s Goat',
    names: { 해설: 'Narrator', 도데: 'Daudet', 스갱: 'Mr. Seguin', 블랑케트: 'Blanquette', 늑대: 'Wolf' },
    outro: [
      'Was Blanquette foolish or brave to risk her life for the mountain?',
      'Why do you think Daudet wrote this story as a letter to Gringoire, a poor poet?',
      'If you had to choose between safety and freedom, which would you choose, and could you pay the price?',
    ],
    lines: [
      ['해설', 'This story is a letter from Daudet to his friend Gringoire, a poor poet.'],
      ['도데', 'Gringoire, you turned down a newspaper job to stay a poor poet. Let me tell you a story.'],
      ['해설', 'Mr. Seguin never managed to keep a goat. He had already lost six.'],
      ['해설', 'Every one of them broke its rope, ran off to the mountain, and was eaten by the wolf.'],
      ['해설', 'Still, Mr. Seguin did not give up. This time, he got a very young goat to raise.'],
      ['해설', 'The seventh goat, Blanquette, was a pretty little thing with snow-white fur and gentle eyes.'],
      ['해설', 'Mr. Seguin tied Blanquette with a long rope in the fenced meadow. At first, she was happy.'],
      ['해설', 'But one day, Blanquette looked up at the mountain. Suddenly the rope around her neck felt heavy.'],
      ['블랑케트', 'How wonderful it must be up there. If only I could run free with no rope around my neck.'],
      ['해설', 'Blanquette stopped eating grass and grew thin. Then one morning, she spoke to Mr. Seguin.'],
      ['블랑케트', 'Mr. Seguin, I can’t live here anymore. Please let me go to the mountain.'],
      ['스갱', 'What, you too? Is there not enough grass? Is the rope too short? What do you need?'],
      ['블랑케트', 'Nothing. I just want to go to the mountain.'],
      ['스갱', 'There is a wolf on the mountain. Remember old Renaude? She fought the wolf all night, and he ate her in the morning.'],
      ['블랑케트', 'I don’t care. Please let me go.'],
      ['해설', 'Mr. Seguin locked Blanquette in the dark goat shed. But he forgot to close the window.'],
      ['해설', 'As soon as he turned away, Blanquette jumped out the window and ran to the mountain.'],
      ['해설', 'The mountain welcomed her. The chestnut trees bent down their branches, and the flowers gave off their scent.'],
      ['해설', 'Blanquette ran and rolled to her heart’s content. Looking down, Mr. Seguin’s house and fence seemed tiny.'],
      ['블랑케트', 'How did I ever live shut up in such a small place?'],
      ['해설', 'At sunset, the mountain turned purple. Far below, she heard Mr. Seguin’s horn calling her.'],
      ['해설', 'Then came a howl. The wolf! Blanquette hesitated, but she thought of the rope and fence, and stayed.'],
      ['해설', 'Leaves rustled behind her. She saw two short, pointed ears and two shining eyes. It was the wolf.'],
      ['늑대', 'Ha, ha, Mr. Seguin’s little goat. No need to hurry. You are mine anyway.'],
      ['블랑케트', 'I will fight like old Renaude. At least until the sun comes up.'],
      ['해설', 'Blanquette lowered her horns and fought. Again and again, she drove the wolf back. One by one, the stars went out.'],
      ['해설', 'At last, dawn broke and a rooster crowed. When Blanquette fell, worn out, the wolf moved closer.'],
      ['도데', 'Do you hear, Gringoire? The price of dreaming of freedom is this heavy. Still, Blanquette fought until morning.'],
      ['해설', 'Whether to follow Mr. Seguin’s advice or Blanquette’s path was a question left to the poet.'],
      ['해설', 'Monsieur Seguin’s Goat appears in Letters from My Windmill, written as a letter to the poet Gringoire.'],
    ],
  },

  'wse-juggler': {
    title: 'Our Lady’s Juggler',
    names: { 해설: 'Narrator', 바르나베: 'Barnaby', 수도원장: 'Prior', 모리스: 'Brother Maurice', 마르보드: 'Brother Marbode' },
    outro: [
      'What does the scene of the Virgin wiping the juggler’s sweat say about devotion and talent?',
      'How do the old monks, who called it a sin, contrast with the prior’s last words?',
      'Have you ever shared your heart with someone through a small talent of yours?',
    ],
    lines: [
      ['해설', 'In the days of King Louis of France, Barnaby, a poor juggler from Compiègne, wandered from town to town.'],
      ['바르나베', 'Come, everyone! Here are the tricks of Barnaby of Compiègne!'],
      ['해설', 'On market days, he spread an old carpet in the square. He balanced a plate on his nose and juggled six copper balls.'],
      ['해설', 'When he stood on his hands and juggled twelve knives, people finally threw him coins.'],
      ['해설', 'Still, he never earned much. On rainy days he went hungry, and in winter he shivered, but he never complained.'],
      ['해설', 'Barnaby was a simple man of deep faith. Above all, he loved the Virgin Mary with all his heart.'],
      ['해설', 'One rainy evening, he met a monk on the road. He was the prior of a nearby monastery.'],
      ['수도원장', 'Brother, why do you walk with such a sad face?'],
      ['바르나베', 'I was wishing I could praise Our Lady every day, like you, Father. I am only a juggler.'],
      ['수도원장', 'Then come with me. I think God has led you to us.'],
      ['해설', 'And so Barnaby became a monk. Each of the brothers served the Virgin with his own talent.'],
      ['해설', 'The prior wrote books about her virtues. Brother Maurice painted beautiful pictures on parchment.'],
      ['모리스', 'Each of these petals is a prayer to Our Lady.'],
      ['해설', 'Brother Marbode carved statues of her from stone, and other brothers wrote songs in her praise.'],
      ['마르보드', 'I hope Our Lady’s face blooms wherever my chisel touches.'],
      ['해설', 'Watching them, Barnaby grew very sad. He could not write, paint, or sing.'],
      ['바르나베', 'They all offer such wonderful things. And I have nothing at all to give Our Lady.'],
      ['해설', 'Then one day, his face lit up. After that, he went into the chapel alone when no one was there.'],
      ['해설', 'The brothers grew suspicious. So the prior and two old monks secretly watched him through a crack in the door.'],
      ['해설', 'In front of the Virgin’s altar, Barnaby stood on his hands, juggling six copper balls and twelve knives.'],
      ['바르나베', 'Holy Mother, this is all I know how to do. I offer you my best trick.'],
      ['해설', 'The old monks thought it was a sin and were about to shout. The prior, too, wanted to drag him out.'],
      ['해설', 'Then the Virgin slowly came down from the altar. With the edge of her blue cloak, she wiped the juggler’s sweat.'],
      ['해설', 'The prior bowed down to the stone floor.'],
      ['수도원장', 'Blessed are the simple in heart, for they shall see God.'],
      ['해설', 'The old monks kissed the ground and answered, Amen.'],
      ['해설', 'What Barnaby offered was not great talent, but a heart that gave everything it had.'],
      ['해설', 'This story comes from an old legend of medieval France, retold by Anatole France.'],
      ['해설', 'Anatole France, who wrote Our Lady’s Juggler, won the Nobel Prize in Literature in 1921.'],
    ],
  },

  'wse-law': {
    title: 'Before the Law',
    names: { 해설: 'Narrator', 시골사람: 'Man from the Country', 문지기: 'Doorkeeper' },
    outro: [
      'The man waited his whole life at an open door. Was it the doorkeeper who stopped him, or the man himself?',
      'The doorkeeper says the door was meant only for him. How do these last words strike you?',
      'Have you ever missed a chance by only waiting for permission? What could you have done then?',
    ],
    lines: [
      ['해설', 'Before the Law stands a doorkeeper. One day, a man from the country comes and asks to enter the Law.'],
      ['문지기', 'I cannot let you in now.'],
      ['시골사람', 'Then will I be allowed to enter later?'],
      ['문지기', 'It is possible. But not now.'],
      ['해설', 'The door to the Law stands open as always. When the doorkeeper steps aside, the man bends down to look inside.'],
      ['문지기', 'If you are so tempted, try going in against my order. But remember, I am powerful.'],
      ['문지기', 'And I am only the lowest doorkeeper. In every hall stands another doorkeeper, each more powerful than the last.'],
      ['문지기', 'Even I cannot bear to look at the third one.'],
      ['해설', 'The man did not expect such trouble. He believed the Law should be open to everyone, always.'],
      ['해설', 'But he looked at the doorkeeper in his fur coat, with his big pointed nose and long black beard. He decided to wait.'],
      ['해설', 'The doorkeeper gave him a stool and let him sit beside the door. He sat there for days, and then for years.'],
      ['해설', 'He tried many times to get in, and he tired the doorkeeper with endless requests.'],
      ['해설', 'Sometimes the doorkeeper asked about his home, but only like a great man asking without interest. The answer was always, not yet.'],
      ['해설', 'The man had brought many things for his journey. He used them all, however valuable, to bribe the doorkeeper.'],
      ['문지기', 'I take this only so that you will not think you have left anything undone.'],
      ['해설', 'Over the long years, the man watched only this doorkeeper. He forgot the others. This one seemed the only barrier.'],
      ['해설', 'In the first years, he cursed his bad luck loudly. When he grew old, he only muttered to himself.'],
      ['해설', 'He became childish. He even begged the fleas in the doorkeeper’s fur collar to help change his mind.'],
      ['해설', 'At last, his eyes grew dim. Yet in the darkness, he saw a light streaming endlessly from the door of the Law.'],
      ['해설', 'Death was near. He could not raise his stiffening body, so he waved, and the doorkeeper bent low.'],
      ['문지기', 'What do you still want to know? You are never satisfied.'],
      ['시골사람', 'Everyone seeks the Law. So why, in all these years, has no one but me asked to come in?'],
      ['해설', 'The doorkeeper saw that the man was dying. He shouted loudly so his fading ears could hear.'],
      ['문지기', 'No one else could enter here, because this door was made only for you. Now I am going to shut it.'],
      ['해설', 'The story ends here. An open door, a doorkeeper, a lifetime of waiting. Kafka never explained its meaning.'],
      ['해설', 'Some readers see the door as a system of power and offices that ordinary people cannot reach.'],
      ['해설', 'Others think the man was stopped by his own fear and obedience. After all, the door was open from the start.'],
      ['해설', 'Still others read it as a person standing before truth or God. The words, only for you, stay with us.'],
      ['해설', 'Could the man really not enter? Or could he enter, but never did? That question is the key to this story.'],
      ['해설', 'Before the Law also appears in Kafka’s novel The Trial, where a priest tells it to Josef K.'],
    ],
  },

  'wse-hunger-artist': {
    title: 'A Hunger Artist',
    names: { 해설: 'Narrator', 광대: 'Hunger Artist', 흥행주: 'Manager', 감독: 'Overseer', 구경꾼: 'Visitor', 아이: 'Child' },
    outro: [
      'In the end, did the hunger artist want people’s admiration, or something else?',
      'How does the artist taken out of the straw contrast with the young panther put in his cage?',
      'How should we see people who keep doing their own work after the world has lost interest?',
    ],
    lines: [
      ['해설', 'In recent decades, interest in hunger artists has greatly declined. It was not always so.'],
      ['해설', 'Once, whole cities were excited about the hunger artist. He ate nothing for weeks in a barred cage covered with straw.'],
      ['해설', 'Adults came for fun, and children stared at his pale face with their mouths open.'],
      ['아이', 'Mom, does that man really eat nothing? I can see all his ribs.'],
      ['해설', 'At night, guards chosen by the public watched the cage. They were often butchers, and they suspected him.'],
      ['해설', 'Some guards played cards in a corner on purpose, to give him a chance to eat. That hurt him most of all.'],
      ['해설', 'He knew how easy fasting was. But no one believed it. He alone could witness his own fast.'],
      ['해설', 'The manager always set the fast at forty days. Any longer, he said, and the city would lose interest.'],
      ['해설', 'On the fortieth day, a military band played under flower decorations, and two ladies led him out of the cage.'],
      ['광대', 'Why stop now? I can fast longer. I can go beyond my limits.'],
      ['흥행주', 'Ladies and gentlemen, look! Here is our hero who lasted forty days! Now, let him eat!'],
      ['해설', 'The hunger artist was always sad, but people thought even that was because of hunger.'],
      ['해설', 'Then people’s tastes changed. They turned away from the hunger artist and rushed to other shows.'],
      ['해설', 'He left his manager and joined a big circus. His cage was placed on the path to the animal cages.'],
      ['해설', 'People passed his cage on their way to the animals. He hated the sound of their footsteps.'],
      ['구경꾼', 'A hunger artist? It’s all a trick. Come on, it’s feeding time for the wild animals.'],
      ['해설', 'At some point, no one updated the board counting his days. No one knew how long he had fasted, not even him.'],
      ['해설', 'Much later, the circus overseer stopped in front of a cage that seemed useless.'],
      ['감독', 'Why is this good cage empty? There’s only rotten straw in it.'],
      ['해설', 'When the workers poked the straw with a stick, they found the hunger artist inside.'],
      ['감독', 'Are you still fasting? When on earth will you stop?'],
      ['광대', 'Forgive me, everyone. I always wanted you to admire my fasting.'],
      ['감독', 'Well, we do admire it.'],
      ['광대', 'But you shouldn’t admire it. I had to fast. I couldn’t help it.'],
      ['감독', 'Why couldn’t you help it?'],
      ['광대', 'Because I couldn’t find the food I liked. If I had, I would have eaten my fill like everyone else.'],
      ['해설', 'Those were his last words. Yet his dimming eyes still held a firm belief that he would keep fasting.'],
      ['해설', 'They buried him with the straw. Then they put a young panther in his cage.'],
      ['해설', 'The panther ate its food happily, and joy of life burst from its whole body. People could not leave the cage.'],
      ['해설', 'A Hunger Artist was published in 1922. The book of the same title came out in 1924, the year Kafka died.'],
    ],
  },
};
