// 청소년 영어 원고: 80일간의 세계 일주 1~10화 (stories/teen-80days.js). 문장은 자체 각색.
// lines 의 첫 칸은 한국어 이야기 cast 의 이름 그대로.
export default {
  'ed-01': {
    title: 'Around the World in 80 Days, Part 1',
    names: { 해설: 'Narrator', 포그: 'Phileas Fogg', 파스파르투: 'Passepartout', 스튜어트: 'Stuart', 랠프: 'Ralph' },
    outro: [
      'When Fogg bet half his fortune, was he being reckless, or did he trust his own calculations?',
      'Why do you think the author paired the precise Fogg with the talkative Passepartout?',
      'When do you feel that the world has become smaller these days?',
    ],
    lines: [
      ['해설', 'In 1872, a gentleman named Phileas Fogg lived at No. 7, Savile Row, London.'],
      ['해설', 'He was rich, but nobody knew how he had made his money.'],
      ['해설', 'His days ran like a clock. He got up at the same time and walked the same number of steps to his club.'],
      ['해설', 'That morning, he fired his servant because the shaving water was two degrees too cold.'],
      ['해설', 'The new servant was a young Frenchman, Jean Passepartout. He had been a circus acrobat and a firefighter.'],
      ['파스파르투', 'A quiet master who lives by rules! At last I can stop wandering!'],
      ['포그', 'It is now twenty-nine minutes past eleven. From this moment, you are in my service.'],
      ['해설', 'Fogg went straight to the Reform Club and opened his newspaper in his usual seat.'],
      ['해설', 'That evening, the members talked about the fifty-five thousand pounds stolen from the Bank of England.'],
      ['스튜어트', 'The thief must be far away by now. The world is big, so there are many places to hide.'],
      ['포그', 'It was once.'],
      ['랠프', 'Fogg is right. The paper says you can now go around the world in eighty days.'],
      ['해설', 'The newspaper showed a route through Suez, Bombay, Calcutta, Hong Kong, Yokohama, San Francisco, and New York.'],
      ['스튜어트', 'That is only on paper. It doesn’t count storms, breakdowns, or accidents.'],
      ['포그', 'All included. I will bet twenty thousand pounds that I can do it in eighty days.'],
      ['해설', 'The members stopped laughing. Twenty thousand pounds was half of Fogg’s fortune.'],
      ['포그', 'Today is Wednesday, October 2nd. I will be back in this room on Saturday, December 21st, at a quarter to nine in the evening.'],
      ['랠프', 'Very well, we accept. If you are late, the money is ours.'],
      ['해설', 'He would spend the other twenty thousand on the trip. He could not waste a single day.'],
      ['해설', 'At ten to eight, Fogg came home and called Passepartout.'],
      ['포그', 'We leave for Dover in ten minutes. We are going around the world.'],
      ['파스파르투', 'Around the world? I was told you were a quiet master, and on my first day we go around the world!'],
      ['해설', 'They took only one small bag. Inside was a thick pile of banknotes.'],
      ['포그', 'Take good care of this bag. There are twenty thousand pounds in it.'],
      ['해설', 'At a quarter to nine, the train left Charing Cross station. The club members waved from the platform.'],
      ['파스파르투', 'Oh no! I left the gas lamp burning in my room!'],
      ['포그', 'Then the gas is at your expense. It will burn until we return.'],
      ['해설', 'Meanwhile, the London police were sending a description of the bank thief to ports around the world.'],
      ['해설', 'Surprisingly, that description looked exactly like the calm gentleman Phileas Fogg.'],
      ['해설', 'This novel first appeared in the French newspaper Le Temps in 1872 and came out as a book in 1873.'],
    ],
  },

  'ed-02': {
    title: 'Around the World in 80 Days, Part 2',
    names: { 해설: 'Narrator', 픽스: 'Fix', 영사: 'Consul', 포그: 'Phileas Fogg', 파스파르투: 'Passepartout' },
    outro: [
      'Why did Fix rely more on a description and his suspicions than on real evidence?',
      'How does Passepartout’s chatter make the story more tense?',
      'Have you ever judged someone by their looks and later changed your mind?',
    ],
    lines: [
      ['해설', 'Last time, Fogg made a bet to go around the world in eighty days and left London with Passepartout.'],
      ['해설', 'On October 9th, a thin man was walking up and down the docks of Suez in Egypt.'],
      ['해설', 'He was Detective Fix from Scotland Yard. He was checking every ship for the bank thief.'],
      ['픽스', 'Catching the thief means a big reward. I won’t miss a single Englishman passing through this port.'],
      ['해설', 'When the steamer Mongolia arrived, a servant with a French accent came up holding a passport.'],
      ['파스파르투', 'Excuse me, where is the consulate? My master’s passport needs a stamp.'],
      ['해설', 'Fix read the description in the passport, and his eyes lit up. It matched the one from London.'],
      ['픽스', 'The owner must bring his passport himself. The consulate is around that corner.'],
      ['해설', 'Fix ran to the consulate first and spoke to the consul.'],
      ['픽스', 'That man must be the thief. Don’t stamp his passport. Keep him here.'],
      ['영사', 'If the passport is in order, I must stamp it. That is the law.'],
      ['해설', 'Soon Fogg came in and handed over his passport. He only wanted proof of the route he had taken.'],
      ['포그', 'I only need a record that I passed through here. Thank you.'],
      ['해설', 'Fix had no arrest warrant yet, so he could do nothing. He sent a telegram to London.'],
      ['픽스', 'Send the warrant to Bombay. I will follow him.'],
      ['해설', 'Fogg did not even look around Suez. He went straight back to the ship. To him, travel was a series of calculations.'],
      ['해설', 'Instead, Passepartout wandered the market and met a friendly man. It was Fix.'],
      ['파스파르투', 'My master is going around the world because of a bet. He left London with lots of money.'],
      ['픽스', 'A bet? That is a clever excuse for a man rushing off with a lot of money.'],
      ['해설', 'The Mongolia passed through the Red Sea, stopped at Aden, and crossed the Indian Ocean.'],
      ['해설', 'On board, Fogg ate four meals a day and played whist, a card game. He did not care about the sea.'],
      ['해설', 'Fix slowly became friends with Passepartout. He pretended to be glad they were on the same ship.'],
      ['파스파르투', 'You’re going to Bombay too, Mr. Fix? What a strange coincidence!'],
      ['해설', 'On October 20th, the ship reached Bombay two days early. Fogg wrote in his notebook that he had gained two days.'],
      ['해설', 'But the warrant had not arrived at the Bombay police office. Fix gritted his teeth.'],
      ['픽스', 'Fine. Wherever he goes on British land, I will follow him to the end.'],
      ['해설', 'Meanwhile, with time before the train, Passepartout went sightseeing alone in Bombay.'],
      ['해설', 'He saw a beautiful temple and walked in with his shoes on, not knowing the custom.'],
      ['해설', 'The Suez Canal opened in 1869. It made the sea route from Europe to India much shorter.'],
    ],
  },

  'ed-03': {
    title: 'Around the World in 80 Days, Part 3',
    names: { 해설: 'Narrator', 파스파르투: 'Passepartout', 포그: 'Phileas Fogg', 크로마티: 'Sir Francis Cromarty', 차장: 'Conductor', 픽스: 'Fix' },
    outro: [
      'When the railway ended, Fogg bought an elephant without getting angry. What does this show about him?',
      'What does Passepartout’s trouble at the temple say about respecting the customs of other cultures?',
      'Why is it important to learn the rules of a place before you travel there?',
    ],
    lines: [
      ['해설', 'Last time, Detective Fix suspected Fogg of being the bank thief and followed him to Bombay.'],
      ['해설', 'Passepartout had entered a sacred temple with his shoes on. There, it was a serious insult.'],
      ['해설', 'The priests rushed to stop him. After a struggle, he lost his shoes and ran away.'],
      ['파스파르투', 'I ran all the way to the station barefoot! Master, I think I made a big mistake.'],
      ['포그', 'I hope it will not happen again. Get on the train.'],
      ['해설', 'Fix had secretly watched the scene, and he was delighted. This might let him hold Fogg back.'],
      ['픽스', 'What happened at the temple is a crime under British law too. I’ll send the priests to the court in Calcutta.'],
      ['해설', 'The train raced across India toward Calcutta. Sir Francis Cromarty, a general, sat across from Fogg.'],
      ['크로마티', 'Mr. Fogg, what have you seen on this trip? The land and its people, I mean.'],
      ['포그', 'I am not here to sightsee. My purpose is to arrive on time.'],
      ['해설', 'Mountains, forests, cotton fields, and villages passed by. Fogg saw them only as numbers in a timetable.'],
      ['해설', 'On the third morning after leaving Bombay, the train stopped at a small village in the middle of a forest.'],
      ['차장', 'Everyone, please get off. The railway ends here.'],
      ['크로마티', 'What do you mean? The newspapers said the line was finished.'],
      ['차장', 'The newspapers were too early. About fifty miles to the next station are still being built.'],
      ['해설', 'The passengers scattered to find carts and carriages. Fogg’s face did not change at all.'],
      ['포그', 'I gained two days for just this kind of problem. We will find another way.'],
      ['해설', 'At the edge of the village, Passepartout found an elephant. Its name was Kiouni.'],
      ['해설', 'The owner did not want to sell. Fogg raised his price again and again.'],
      ['포그', 'I will pay two thousand pounds. This elephant will carry our journey forward.'],
      ['파스파르투', 'Two thousand pounds for one elephant! It must be the most expensive elephant in the world.'],
      ['해설', 'A young Parsee who knew the way became their guide. General Cromarty decided to come too.'],
      ['해설', 'The four of them rode the elephant through the forest on a shortcut. Passepartout bounced all over.'],
      ['크로마티', 'Mr. Fogg, the elephant alone cost you a tenth of your bet.'],
      ['포그', 'Money spent to buy time is never wasted.'],
      ['해설', 'At sunset, they heard singing mixed with drums and horns from deep in the forest.'],
      ['해설', 'The guide hid the elephant among the trees. A procession with torches was slowly coming closer.'],
      ['해설', 'The railway across India from Bombay to Calcutta was completed in 1870, two years before the story.'],
    ],
  },

  'ed-04': {
    title: 'Around the World in 80 Days, Part 4',
    names: { 해설: 'Narrator', 안내인: 'Guide', 포그: 'Phileas Fogg', 파스파르투: 'Passepartout', 아우다: 'Aouda', 판사: 'Judge', 픽스: 'Fix' },
    outro: [
      'Fogg valued time so much, so why did he risk losing a day to save Aouda?',
      'How should we read the way European novels of the 1870s described other cultures?',
      'Have you ever had to put a person before your rules or plans?',
    ],
    lines: [
      ['해설', 'Last time, when the railway ended, Fogg and his group bought an elephant and crossed the forests of India.'],
      ['해설', 'In the middle of the procession, a young woman was being led along by the crowd.'],
      ['안내인', 'She is the wife of an old prince who has died. At dawn, she will be burned with her husband.'],
      ['해설', 'It was an old custom of burning a widow with her dead husband. The British had already banned it.'],
      ['해설', 'But in places where British power was weak, it still happened.'],
      ['안내인', 'Her name is Aouda. She is a Bombay merchant’s daughter and well educated, but she was forced to marry.'],
      ['해설', 'Fogg looked at his notebook for a moment and counted the time he had left.'],
      ['포그', 'I still have twelve hours to spare. I will use them for her.'],
      ['파스파르투', 'I thought my master’s heart was made of stone. Now I see it is made of gold!'],
      ['해설', 'The novel paints this custom very darkly. It reflects how European writers of that time saw India.'],
      ['해설', 'All night they watched the temple, but there were too many guards to get close.'],
      ['해설', 'At dawn, the procession moved toward the pile of wood. Fogg got ready to rush in alone.'],
      ['해설', 'At that moment, the dead prince suddenly stood up in the smoke. People fell to the ground in fear.'],
      ['해설', 'It was Passepartout in the prince’s clothes. He had sneaked onto the pile in the dark.'],
      ['파스파르투', 'Hurry, Master! We must run while everyone is in shock!'],
      ['해설', 'Passepartout carried the unconscious Aouda into the forest. They escaped on the elephant.'],
      ['해설', 'At Allahabad, Fogg thanked the guide generously.'],
      ['포그', 'You were brave and loyal. I give you this elephant, Kiouni.'],
      ['안내인', 'Such a great gift! I will take care of Kiouni all my life.'],
      ['해설', 'When Aouda woke up and saw the people who had saved her, she cried.'],
      ['아우다', 'You risked your lives for a stranger. I don’t know how I can ever repay you.'],
      ['포그', 'There is nothing to repay. If you have family in Hong Kong, we will take you there.'],
      ['해설', 'The train reached Calcutta safely. But in front of the station, the police arrested Fogg and Passepartout.'],
      ['해설', 'Fix had brought the priests from the Bombay temple to accuse them. Even the shoes were shown as evidence.'],
      ['판사', 'The servant gets fifteen days in prison, and the master eight days. You may go free on bail.'],
      ['포그', 'I will pay two thousand pounds in bail. We must take a ship today.'],
      ['해설', 'Fogg paid at once, and they boarded a ship to Hong Kong that same day.'],
      ['픽스', 'Throwing away two thousand pounds like that! Still, the warrant will come before he reaches Hong Kong.'],
      ['해설', 'As the ship left, no one noticed Fix boarding it from a corner of the dock.'],
      ['해설', 'The custom of burning widows was banned by law in British-ruled Bengal in 1829.'],
    ],
  },

  'ed-05': {
    title: 'Around the World in 80 Days, Part 5',
    names: { 해설: 'Narrator', 아우다: 'Aouda', 포그: 'Phileas Fogg', 파스파르투: 'Passepartout', 픽스: 'Fix', 번스비: 'John Bunsby' },
    outro: [
      'After hearing Fix’s confession, was Passepartout right not to tell his master?',
      'What effect does it have that Fogg never looks rushed, even after missing the ship?',
      'When your mistake caused trouble for someone else, how did you try to fix it?',
    ],
    lines: [
      ['해설', 'Last time, Fogg’s group saved Aouda, went through a court in Calcutta, and boarded a ship to Hong Kong.'],
      ['해설', 'On the ship, Aouda slowly opened her heart to Fogg’s cool but polite kindness.'],
      ['아우다', 'Mr. Fogg always looks at his watch, but he treats people very gently.'],
      ['해설', 'They reached Hong Kong on November 6th, but Aouda’s relative had already moved to Europe.'],
      ['포그', 'Then come with us to Europe. I will take responsibility for you.'],
      ['해설', 'Fogg told Passepartout to book cabins on the Carnatic, which would sail to Yokohama the next day.'],
      ['해설', 'But at the dock, Passepartout heard that the Carnatic would leave that very night.'],
      ['파스파르투', 'It’s leaving early? I must tell my master right away!'],
      ['해설', 'Just then, Fix came up to him. The warrant had not come to Hong Kong either, so he tried one last trick.'],
      ['픽스', 'Passepartout, I need to talk to you. Let’s go to a tavern.'],
      ['해설', 'Over drinks, Fix finally admitted that he was a detective.'],
      ['픽스', 'Your master is the bank thief. Help me keep him here, and I’ll share the reward with you.'],
      ['파스파르투', 'My master, a thief? He is the most honest man in the world!'],
      ['해설', 'Passepartout firmly said no. But the strong drink had already made his body heavy.'],
      ['해설', 'Fix even handed him an opium pipe, and Passepartout fell into a deep sleep.'],
      ['해설', 'The next morning, when Fogg and Aouda went to the dock, the Carnatic was already gone.'],
      ['해설', 'Fogg showed no surprise at losing his servant or missing the ship.'],
      ['포그', 'We will find another ship. If none goes straight to Yokohama, we will go to Shanghai.'],
      ['해설', 'An American steamer was leaving from Shanghai. It would stop at Yokohama and then go to San Francisco.'],
      ['해설', 'Fogg hired a small pilot boat, the Tankadere. Its captain was John Bunsby.'],
      ['번스비', 'You want to go out to sea in this little boat? The weather looks bad.'],
      ['포그', 'I will pay you well. If we arrive in time, you will get a bonus.'],
      ['해설', 'Fix saw this from the dock and panicked. To keep Fogg in sight, he asked to come along.'],
      ['해설', 'Fogg thought Fix was just another traveler who had missed the ship, and he gladly gave him a seat.'],
      ['픽스', 'A guest on the boat of the man I am chasing. Could anything be funnier?'],
      ['아우다', 'Where could Passepartout be? He is not the kind of man to abandon us.'],
      ['해설', 'In fact, Passepartout had woken up just in time and stumbled aboard the Carnatic.'],
      ['해설', 'As the little Tankadere left the harbor, dark clouds began to gather in the southern sky.'],
      ['해설', 'Hong Kong became British under the Treaty of Nanjing in 1842 and was returned to China in 1997.'],
    ],
  },

  'ed-06': {
    title: 'Around the World in 80 Days, Part 6',
    names: { 해설: 'Narrator', 번스비: 'John Bunsby', 포그: 'Phileas Fogg', 파스파르투: 'Passepartout', 바툴카: 'Batulcar', 아우다: 'Aouda', 픽스: 'Fix' },
    outro: [
      'Was Fix being honest when he said he would help Fogg now, or was it another calculation?',
      'Why is it fun that a falling human pyramid becomes the moment of reunion?',
      'Have you ever met someone or found a chance again in an unexpected place?',
    ],
    lines: [
      ['해설', 'Last time, Passepartout fell for Fix’s trick and sailed alone, and Fogg hired a small boat.'],
      ['해설', 'The Tankadere ran into a fierce storm. Each time a wave hit the deck, the boat shook like a toy.'],
      ['번스비', 'I have taken in the sails, but I am not sure we can last.'],
      ['포그', 'I trust your skill. Please keep going to Shanghai.'],
      ['해설', 'Aouda stayed by Fogg’s side, with calm eyes instead of a frightened face.'],
      ['해설', 'The storm passed, but time was short. Outside Shanghai, the American steamer was just leaving.'],
      ['포그', 'Lower the flag to half-mast and fire the signal gun. It is a call for help.'],
      ['해설', 'Hearing the cannon, the steamer turned around. Fogg and the others safely moved onto it.'],
      ['해설', 'Meanwhile, Passepartout had reached Yokohama first, without a penny. He had no master and no money.'],
      ['파스파르투', 'My stomach is empty and so are my pockets. I’ll have to sell what I can do.'],
      ['해설', 'In the streets, he saw a poster for an acrobat troupe. Its manager was an American named Batulcar.'],
      ['바툴카', 'You can do acrobatics? Good. You’re on stage starting tonight.'],
      ['해설', 'The troupe was about to tour America. Passepartout had found a way to get there.'],
      ['해설', 'That night, he wore a long fake nose and stood at the bottom of a human pyramid.'],
      ['해설', 'But as he looked around the audience, he saw a familiar face.'],
      ['파스파르투', 'Master! It’s my master!'],
      ['해설', 'He ran out, and the pyramid came crashing down. The crowd filled with laughter and shouts.'],
      ['바툴카', 'Hey! You ruined my show! Where do you think you’re going?'],
      ['해설', 'Without a word, Fogg paid the manager for the damage and left the theater with his servant.'],
      ['아우다', 'I’m so glad we found you again. We were all worried.'],
      ['해설', 'They boarded the General Grant for San Francisco. Fix secretly got on the same ship.'],
      ['해설', 'Passepartout could not bring himself to tell Fogg about Hong Kong. Instead, he punched Fix as soon as he saw him.'],
      ['파스파르투', 'That’s for the drinks in Hong Kong! Don’t ever get in my master’s way again.'],
      ['픽스', 'I deserved that. But listen. From now on, I am on your master’s side.'],
      ['픽스', 'The warrant only works on British land. So now my job is to get him to England quickly.'],
      ['파스파르투', 'All right. But if you try anything strange, you’ll get much worse than that.'],
      ['해설', 'The ship crossed the Pacific and reached San Francisco on December 3rd. Eighteen days were left.'],
      ['해설', 'When they stepped onto the dock, they heard the roar of a huge crowd in the middle of the city.'],
      ['해설', 'Yokohama opened its port to foreign ships in 1859 and soon grew into Japan’s leading trade port.'],
    ],
  },

  'ed-07': {
    title: 'Around the World in 80 Days, Part 7',
    names: { 해설: 'Narrator', 파스파르투: 'Passepartout', 프록터: 'Colonel Proctor', 포그: 'Phileas Fogg', 픽스: 'Fix', 기관사: 'Engineer', 아우다: 'Aouda' },
    outro: [
      'Was it wise to accept the engineer’s plan to cross the shaking bridge at full speed?',
      'What does Fogg’s wish to stand up to Colonel Proctor’s rudeness show about him?',
      'When you must choose between going fast and going safely, what guides your choice?',
    ],
    lines: [
      ['해설', 'Last time, the group came together again in Yokohama and crossed the Pacific to San Francisco.'],
      ['해설', 'In a San Francisco square, an election rally was in full swing. Two groups of supporters shouted at each other.'],
      ['파스파르투', 'Master, people in this country give speeches as if they were fighting!'],
      ['해설', 'Suddenly the group was caught in a brawl. A big man roughly shoved Fogg.'],
      ['프록터', 'Out of my way, you English gentleman!'],
      ['해설', 'Fix blocked the blow instead, and his hat was crushed. The man was Colonel Stamp Proctor.'],
      ['포그', 'I will remember your name. One day I will come back to answer this insult.'],
      ['픽스', 'Mr. Fogg, getting to England comes first. You can settle quarrels later.'],
      ['해설', 'That evening, they boarded the train across the continent to New York. The trip took seven days.'],
      ['해설', 'The train crossed the Sierra Nevada mountains and entered the endless plains.'],
      ['해설', 'One afternoon, the train suddenly stopped. Thousands of buffalo were crossing the tracks.'],
      ['파스파르투', 'Waiting for buffalo! In this country, cattle must be more important than trains.'],
      ['해설', 'It took more than three hours for the herd to pass. Fogg waited quietly.'],
      ['해설', 'The train passed near Salt Lake City. Passepartout listened with wonder to a Mormon lecture.'],
      ['해설', 'After crossing the Rocky Mountains, the train stopped again before the bridge at Medicine Bow.'],
      ['기관사', 'We got word that the bridge is shaking. It is dangerous for a heavy train.'],
      ['기관사', 'But if we go at full speed, we might get across before it falls.'],
      ['파스파르투', 'Wait! Why don’t the passengers walk across first and send the train over later?'],
      ['해설', 'But no one listened to him. The passengers even clapped for the engineer’s bold plan.'],
      ['해설', 'The train backed up and then shot forward at a terrible speed. It almost flew over the bridge.'],
      ['해설', 'The moment the last car reached the other side, the bridge crashed down into the river.'],
      ['아우다', 'If we had been a little later, we would all be in that river.'],
      ['해설', 'But there was a familiar face on the same train. It was Colonel Proctor.'],
      ['프록터', 'We meet again, Englishman. Shall we settle this here?'],
      ['포그', 'Very well. When the train stops at the next station, I will accept your challenge.'],
      ['해설', 'Aouda was terrified. Fix offered to fight instead, but Fogg would not step back.'],
      ['해설', 'Just as the two men entered an empty car for the duel, sharp war cries rang out outside.'],
      ['해설', 'Salt Lake City was founded in 1847 by Mormons who had moved west.'],
    ],
  },

  'ed-08': {
    title: 'Around the World in 80 Days, Part 8',
    names: { 해설: 'Narrator', 파스파르투: 'Passepartout', 포그: 'Phileas Fogg', 아우다: 'Aouda', 픽스: 'Fix', 머지: 'Mudge' },
    outro: [
      'How is the Fogg who chose to save Passepartout over his bet different from the Fogg at the start?',
      'If this scene shows only one side’s view of the Native Americans, what might their side of the story be?',
      'When someone accepted a loss to help you, how did you feel?',
    ],
    lines: [
      ['해설', 'Last time, the train barely crossed a falling bridge, and Fogg was about to duel Colonel Proctor.'],
      ['해설', 'Just then, Sioux warriors rode up on horses and attacked the train. The duel was stopped.'],
      ['해설', 'The novel shows them only as attackers. It leaves out the Native Americans who were losing their land.'],
      ['해설', 'In the gunfire, the engineer was hurt, and the engine began to race with no one driving it.'],
      ['해설', 'Just ahead was Fort Kearney station, with an army fort. If the train did not stop there, no help would come.'],
      ['파스파르투', 'I’ll stop the train! This is what an acrobat’s body is for!'],
      ['해설', 'Passepartout slid under the cars and moved forward along the chains.'],
      ['해설', 'With all his strength, he unhooked the engine from the cars. The cars slowly came to a stop.'],
      ['해설', 'Soldiers ran out from the fort, and the attackers pulled back. But Passepartout and two passengers were missing.'],
      ['아우다', 'They took Passepartout. He saved all of us!'],
      ['해설', 'Fogg closed his notebook. Going after him could cost him a whole day.'],
      ['포그', 'If he is alive, I will find him. I will not take one step without him.'],
      ['해설', 'Fogg left with thirty soldiers across the snowy plains. Aouda and Fix stayed at the station to wait.'],
      ['해설', 'The train did not wait. Watching Aouda left behind, Fix felt doubt for the first time.'],
      ['픽스', 'If he were really a thief, would he go this far for a servant?'],
      ['해설', 'The next morning, shots rang out in the distance, and Fogg and the soldiers returned. Passepartout was with them.'],
      ['파스파르투', 'Master, you lost a whole day because of me. I don’t know how to face you.'],
      ['포그', 'You stopped the train. Bringing you back was only natural.'],
      ['해설', 'But to reach New York in time, they needed a new idea. Fix brought a man to them.'],
      ['머지', 'I have a sledge with sails that runs on snow. With a good wind, we can reach Omaha fast.'],
      ['해설', 'With its sails spread wide, the sledge flew across the frozen plains. The cold wind cut their faces.'],
      ['해설', 'Fogg took off his coat and put it over Aouda. She looked at him without a word.'],
      ['해설', 'From Omaha to Chicago, and from Chicago to New York, they changed trains and raced east.'],
      ['해설', 'On the night of December 11th, they reached the New York docks. But the ship to Liverpool had left forty-five minutes earlier.'],
      ['파스파르투', 'Forty-five minutes! It’s all my fault.'],
      ['포그', 'We still have ten days. Tomorrow morning I will look for another ship.'],
      ['해설', 'The next morning, Fogg noticed an old cargo ship on the Hudson River.'],
      ['해설', 'America’s first transcontinental railroad was completed in 1869, when the eastern and western lines met in Utah.'],
    ],
  },

  'ed-09': {
    title: 'Around the World in 80 Days, Part 9',
    names: { 해설: 'Narrator', 스피디: 'Captain Speedy', 포그: 'Phileas Fogg', 파스파르투: 'Passepartout', 픽스: 'Fix', 아우다: 'Aouda' },
    outro: [
      'Was buying the ship and burning it for fuel going too far, or a sign of his will to keep his word?',
      'When the misunderstanding cleared, Fogg punched Fix. How does this change the way we see this calm man?',
      'If you were treated unfairly because of a misunderstanding, how did you handle your feelings?',
    ],
    lines: [
      ['해설', 'Last time, the group rescued Passepartout and reached New York, but missed the Liverpool ship by forty-five minutes.'],
      ['해설', 'The ship Fogg found was the Henrietta, a cargo ship going to Bordeaux in France. Its captain was Speedy.'],
      ['스피디', 'I don’t take passengers. And my ship goes to Bordeaux, not Liverpool.'],
      ['포그', 'Then I will go to Bordeaux. I will pay two thousand dollars each for four people.'],
      ['해설', 'The day after they sailed, the captain was locked in his cabin. Fogg was at the wheel.'],
      ['해설', 'Fogg had paid the sailors well to win them over, and he had turned the ship toward Liverpool.'],
      ['스피디', 'Open this door! This is piracy!'],
      ['파스파르투', 'Now my master is a ship’s captain! Is there anything he can’t do?'],
      ['해설', 'The Henrietta crossed the Atlantic through fierce winter winds. But now the coal was running out.'],
      ['포그', 'Keep the fires as hot as possible. When the coal is gone, there is another way.'],
      ['해설', 'Fogg set the captain free and politely offered him a deal.'],
      ['포그', 'Captain, I will buy this ship for sixty thousand dollars. You may keep the iron hull and the engine.'],
      ['스피디', 'Sixty thousand dollars? For this old ship? Done! I’ll sell!'],
      ['해설', 'From that day, every piece of wood on the ship went into the boiler. Cabins, deck, and masts all burned.'],
      ['파스파르투', 'Burning the ship to move the ship! There has never been a trip like this!'],
      ['해설', 'Only the shell of the ship reached Queenstown in Ireland. They changed to a train and a boat for Liverpool.'],
      ['해설', 'At twenty to twelve on December 21st, they landed at Liverpool. Six hours was enough to reach London.'],
      ['해설', 'Then Fix put his hand on Fogg’s shoulder. Now they were on British land.'],
      ['픽스', 'Phileas Fogg, I arrest you in the name of the Queen.'],
      ['아우다', 'This can’t be! He has done nothing wrong!'],
      ['해설', 'Fogg was locked in a cell in the customs house. Without a word, he placed his watch on the table.'],
      ['해설', 'At two thirty-three, the cell door opened, and Fix rushed in out of breath.'],
      ['픽스', 'Sir, forgive me. The real thief was caught three days ago. You are free.'],
      ['해설', 'Fogg looked straight at Fix. Then, for once in his life, he moved quickly, and his fist knocked Fix down.'],
      ['파스파르투', 'Well done, Master! He deserved it!'],
      ['해설', 'Fogg hired a special train and raced to London. But he could not make up for the lost time.'],
      ['해설', 'The station clock in London showed ten to nine. He was five minutes late.'],
      ['해설', 'Fogg did not go to the club. He quietly went home to Savile Row with the others.'],
      ['해설', 'In 1867, Jules Verne himself crossed the Atlantic on the giant steamship Great Eastern.'],
    ],
  },

  'ed-10': {
    title: 'Around the World in 80 Days, Part 10',
    names: { 해설: 'Narrator', 포그: 'Phileas Fogg', 아우다: 'Aouda', 파스파르투: 'Passepartout', 목사: 'Reverend Wilson', 스튜어트: 'Stuart' },
    outro: [
      'What was the greatest thing Fogg gained from this journey: the bet money, or something else?',
      'Which earlier scenes prepare us for the twist where a single date changes the ending?',
      'Right now, which do I need more: a precise plan, or an unexpected meeting?',
    ],
    lines: [
      ['해설', 'Last time, Fogg was wrongly arrested in Liverpool and reached London five minutes late.'],
      ['해설', 'The next day, Fogg stayed in his room all day. He had almost nothing left.'],
      ['해설', 'Passepartout sighed as he turned off the gas lamp in his room. It had burned for eighty days.'],
      ['해설', 'In the evening, Fogg went to see Aouda and bowed politely.'],
      ['포그', 'I brought you to England to give you a comfortable life. Now I can no longer do that.'],
      ['아우다', 'Mr. Fogg, I am not with you because of your money.'],
      ['아우다', 'If you will have me, I would like to be your wife.'],
      ['해설', 'For the first time, Fogg’s eyes showed emotion. He answered in a low, shaking voice.'],
      ['포그', 'I love you. More than anything in this world.'],
      ['해설', 'They called Passepartout and asked him to arrange the wedding. He jumped for joy.'],
      ['파스파르투', 'I’ll go to the minister right now! You can be married tomorrow, Monday!'],
      ['해설', 'At five past eight in the evening, Passepartout went to see the Reverend Samuel Wilson.'],
      ['목사', 'Tomorrow, Monday? No, tomorrow is Sunday. Today is Saturday.'],
      ['파스파르투', 'Saturday? Then we counted the days wrong!'],
      ['해설', 'Passepartout lost his hat and ran home like a madman.'],
      ['파스파르투', 'Master, today is Saturday! We still have ten minutes!'],
      ['해설', 'Fogg jumped into a cab. It raced through the streets of London, nearly crashing again and again.'],
      ['해설', 'At the Reform Club, the members were watching the clock. The hands had passed eight forty-four.'],
      ['스튜어트', 'Only a few seconds left. Mr. Fogg has lost after all.'],
      ['해설', 'Just as the pendulum swung for the last time, the door flew open.'],
      ['포그', 'Here I am, gentlemen.'],
      ['해설', 'It was exactly a quarter to nine. Fogg had gone around the world in eighty days and kept his word.'],
      ['해설', 'The secret was the direction. Fogg kept traveling east, toward the rising sun.'],
      ['해설', 'Each degree of longitude made his day four minutes shorter. After 360 degrees, he had gained a full day.'],
      ['해설', 'Fogg saw the sun pass overhead eighty times, but in London it passed only seventy-nine times.'],
      ['해설', 'After paying for the trip, about a thousand pounds of his winnings were left. He shared it between Passepartout and Fix.'],
      ['아우다', 'You won’t say that you gained nothing from this journey, will you?'],
      ['포그', 'No. I gained you. That is enough.'],
      ['해설', 'In 1889, the American reporter Nellie Bly took on the novel’s challenge and went around the world in seventy-two days.'],
    ],
  },
};
