// 청소년 영어 원고 (중학생 이상). 키 = stories/teen-talk2.js 의 이야기 id.
// 역사 교양 강연을 한국어 원고의 흐름대로 쉬운 영어로 새로 씀(강연자와 학생의 대화). 사실 근거는 한국어 파일 주석 참고.
export default {
  'tk2-writing': {
    title: 'The Birth of Writing',
    names: { 해설: 'Narrator', 강연자: 'Lecturer', 학생: 'Student' },
    outro: [
      'What did cuneiform, Chinese characters, and the alphabet each use as the basis for their letters?',
      'How did society change after writing appeared, and who held its power first?',
      'Which of your own writings would you like someone to read a thousand years from now?',
    ],
    lines: [
      ['해설', 'Today’s talk is about how people first invented writing.'],
      ['강연자', 'Humans have spoken for hundreds of thousands of years, but we have written for only about five thousand.'],
      ['강연자', 'Our story begins in Mesopotamia, the land between two rivers, in what is now Iraq.'],
      ['강연자', 'Around 3200 BCE, the Sumerians began pressing signs into clay tablets.'],
      ['강연자', 'The first things they wrote were not poems or stories, but numbers of barley and sheep.'],
      ['학생', 'You mean writing started with record books?'],
      ['강연자', 'Yes. They wrote to remember who paid what, and how much.'],
      ['강연자', 'When you press the tip of a reed into wet clay, it leaves a wedge-shaped mark.'],
      ['강연자', 'That is why this writing is called cuneiform, which means wedge-shaped.'],
      ['강연자', 'In Egypt, around the same time, people used picture-like signs called hieroglyphs.'],
      ['학생', 'Wouldn’t clay tablets break easily?'],
      ['강연자', 'When baked in a fire, they actually get harder. Many have survived to this day.'],
      ['강연자', 'Slowly they wrote laws, letters, and myths, and the pictures turned into signs for sounds.'],
      ['강연자', 'Far to the east, in China, people of the Shang dynasty carved writing on turtle shells and ox bones.'],
      ['강연자', 'This writing recorded the king’s fortune-telling. We call it oracle bone script.'],
      ['강연자', 'Many of its signs were pictures of things, and it is the ancestor of today’s Chinese characters.'],
      ['학생', 'Then where did the alphabet come from?'],
      ['강연자', 'The key lies with the Phoenicians, traders on the eastern shore of the Mediterranean Sea.'],
      ['강연자', 'Instead of one sign for each word, they used one sign for each sound.'],
      ['강연자', 'With just twenty-two consonant letters, they could write any word.'],
      ['강연자', 'The Greeks added letters for vowels.'],
      ['강연자', 'This alphabet passed to Rome and became the Roman letters we use to write English today.'],
      ['강연자', 'Thanks to writing, we can now read the thoughts of people from long ago.'],
      ['강연자', 'Do you see what the three have in common? Each one is an invention to keep memory outside the body.'],
      ['강연자', 'But at first very few people could read, so writing meant power.'],
      ['강연자', 'Those who collected taxes and announced laws were the ones who held writing.'],
      ['학생', 'Then everyone being able to read is something very recent.'],
      ['강연자', 'That’s right. The history of writing is also the story of sharing it with more and more people.'],
      ['해설', 'Cuneiform was forgotten for a long time, until scholars deciphered it again in the nineteenth century.'],
    ],
  },

  'tk2-hangul': {
    title: 'The Design of Hangeul',
    names: { 해설: 'Narrator', 강연자: 'Lecturer', 학생: 'Student' },
    outro: [
      'What did the consonants and vowels of Hangeul each copy in their shapes?',
      'How does a design that puts the rules of sound into the shapes of letters help learners?',
      'When you make something, what principles could you build in to help the people who use it?',
    ],
    lines: [
      ['해설', 'Today we look at the design behind Hangeul, the Korean alphabet.'],
      ['강연자', 'Hangeul is a rare writing system whose maker and design principles were recorded in a book.'],
      ['강연자', 'That book is the Hunminjeongeum Haerye, published in 1446.'],
      ['강연자', 'First, the consonants. The five basic letters copy the shapes of the speech organs as they make sounds.'],
      ['강연자', 'The first one shows the back of the tongue blocking the throat. The second shows the tongue touching the upper gums.'],
      ['강연자', 'Others show the shape of the mouth, a tooth, and the throat.'],
      ['학생', 'When I say a g sound now, I can feel the back of my tongue rise!'],
      ['강연자', 'Good observation. Next is the rule of adding strokes.'],
      ['강연자', 'When a sound gets stronger, you add a stroke. Add one to the g letter, and you get the k letter.'],
      ['강연자', 'In the same way, n leads to d and t, and m leads to b and p.'],
      ['강연자', 'So letters with similar shapes are made in the same place in the mouth.'],
      ['강연자', 'Since the rule is in the shapes, knowing the rule means you have less to memorize.'],
      ['강연자', 'The vowels copy heaven, earth, and people.'],
      ['강연자', 'Round heaven is a dot, flat earth is a flat line, and a standing person is a straight line.'],
      ['강연자', 'By combining these three, they made vowels for o, a, u, and eo.'],
      ['강연자', 'Vowels with the dot on the top or the outside were thought of as bright sounds.'],
      ['학생', 'But why do we put letters together in squares, not in a line?'],
      ['강연자', 'Because each syllable is split into a first, a middle, and a final sound, and written as one block.'],
      ['강연자', 'For final sounds, they made no new letters. They used the first-sound letters again.'],
      ['강연자', 'It was a very efficient choice, writing many sounds with few letters.'],
      ['강연자', 'There were twenty-eight letters at first. Today we use twenty-four.'],
      ['학생', 'Where did the other four letters go?'],
      ['강연자', 'As the sounds of the language changed, those four letters fell out of use.'],
      ['강연자', 'This shows that when a language changes, its letters change too.'],
      ['강연자', 'Of course, it took hundreds of years for Hangeul to be widely used.'],
      ['강연자', 'For a long time, official papers were written in Chinese characters, and Hangeul lived on in letters and songs.'],
      ['강연자', 'Even with a good design, a writing system gains power only when more people use it.'],
      ['해설', 'The Haerye clearly states the rule of using first-sound letters again for final sounds.'],
    ],
  },

  'tk2-printing': {
    title: 'Metal Type and the Printing Press',
    names: { 해설: 'Narrator', 강연자: 'Lecturer', 학생: 'Student' },
    outro: [
      'How is woodblock printing different from printing with movable type?',
      'Why did metal type in Goryeo and in Europe lead to such different results?',
      'How do I use today’s tools that spread information quickly?',
    ],
    lines: [
      ['해설', 'Today’s talk is about the history of printing, the art of making books.'],
      ['강연자', 'Before printing, people copied books by hand, one letter at a time.'],
      ['강연자', 'So a single book was very expensive, and few people owned one.'],
      ['강연자', 'The first method was woodblock printing, carving letters into a wooden board and printing from it.'],
      ['강연자', 'The woodblocks of the Tripitaka Koreana, carved in the Goryeo period, still remain at Haeinsa Temple.'],
      ['강연자', 'In 1966, a Buddhist scroll called the Mugujeonggwang Great Dharani Sutra was found in the Seokgatap Pagoda at Bulguksa Temple.'],
      ['강연자', 'It is counted among the oldest woodblock prints in the world.'],
      ['학생', 'If they had woodblocks, why did they need movable type?'],
      ['강연자', 'A woodblock works for only one book. To print another book, you must carve new blocks.'],
      ['강연자', 'With movable type, each letter is made separately and arranged again whenever it is needed.'],
      ['강연자', 'In the eleventh century, Bi Sheng of Song China is said to have made type from baked clay.'],
      ['강연자', 'Goryeo went a step further and made type from metal.'],
      ['학생', 'How did they make metal type?'],
      ['강연자', 'They poured melted metal into molds shaped like letters.'],
      ['강연자', 'Goryeo records say that in the thirteenth century, a book of rituals was printed with metal type.'],
      ['강연자', 'Sadly, that book does not survive.'],
      ['강연자', 'The oldest surviving book printed with metal type is the Jikji.'],
      ['강연자', 'It was printed in 1377 at Heungdeoksa Temple in Cheongju. Today it is in the National Library of France.'],
      ['강연자', 'More than seventy years later, Johannes Gutenberg began printing with metal type in Mainz, Germany.'],
      ['강연자', 'He used a press much like a wine press, along with an oil-based ink.'],
      ['강연자', 'Print shops spread quickly across Europe, and books became cheaper.'],
      ['강연자', 'In the sixteenth century, the ideas of the Reformation also spread fast through print.'],
      ['학생', 'Goryeo was first, so why do people say Europe was the one that changed the world?'],
      ['강연자', 'People often give a few reasons. Chinese characters had a huge number of letters.'],
      ['강연자', 'Also, printing was done mainly by the state and temples, and the market for books was small.'],
      ['강연자', 'Europe, on the other hand, needed only a few dozen letters, and many people bought books.'],
      ['강연자', 'It is not that one side was smarter. The societies around the technology were different.'],
      ['강연자', 'The same invention can have very different power, depending on who uses it and how.'],
      ['해설', 'In 2001, the Jikji was added to UNESCO’s Memory of the World Register.'],
    ],
  },

  'tk2-silkroad': {
    title: 'The Silk Road',
    names: { 해설: 'Narrator', 강연자: 'Lecturer', 학생: 'Student' },
    outro: [
      'Besides goods, what else traveled along the Silk Road?',
      'What were the good and bad points of trade in which many merchants passed goods along like a relay race?',
      'What road did one thing I use today take to reach my hands?',
    ],
    lines: [
      ['해설', 'Today we follow the Silk Road, the old routes that linked East and West.'],
      ['강연자', 'The Silk Road was not a single road. It was many roads, tangled like a spider’s web.'],
      ['강연자', 'They ran from China, across the deserts and mountains of Central Asia, to the Mediterranean Sea.'],
      ['학생', 'Did people back then also call it the Silk Road?'],
      ['강연자', 'No. The name was given in the nineteenth century by a German geographer, Ferdinand von Richthofen.'],
      ['강연자', 'It comes from the large amount of Chinese silk that was sold to the west.'],
      ['강연자', 'In the second century BCE, Emperor Wu of the Han dynasty sent Zhang Qian to the lands of the west.'],
      ['강연자', 'After years of hardship, Zhang Qian returned and told what he had learned about the western world.'],
      ['강연자', 'After that, the routes between East and West grew busier.'],
      ['강연자', 'Merchants led camel caravans, walking from one desert oasis city to the next.'],
      ['강연자', 'Sandstorms and bandits made every journey dangerous.'],
      ['학생', 'Did a single merchant travel all the way from China to Rome?'],
      ['강연자', 'Usually not. It was more like a relay race, with goods passed along from city to city.'],
      ['강연자', 'That is why most Romans did not know much about the country that made silk.'],
      ['강연자', 'Sogdian merchants from Central Asia were especially active on these routes.'],
      ['강연자', 'It was not only silk that moved. Horses, glass, and spices traveled too.'],
      ['강연자', 'Even greater was the movement of ideas and religions.'],
      ['강연자', 'Buddhism, born in India, came along these routes to China and the Korean Peninsula.'],
      ['강연자', 'Papermaking, on the other hand, spread from east to west.'],
      ['강연자', 'Not everything was good. Many believe the Black Death of the fourteenth century also spread along trade routes.'],
      ['강연자', 'Glass vessels that seem to have come from the west were found in ancient tombs in Gyeongju.'],
      ['강연자', 'Hyecho, a Buddhist monk from Silla, was also a traveler on these wide roads.'],
      ['강연자', 'In the eighth century, he traveled to India and wrote Memoir of a Pilgrimage to the Five Kingdoms of India.'],
      ['학생', 'It’s amazing that someone from Silla traveled so far!'],
      ['강연자', 'Roads move people, and people carry ideas.'],
      ['강연자', 'The Silk Road shows us that no civilization grew up completely alone.'],
      ['강연자', 'Today’s sea routes, air routes, and even the internet are, in a way, new Silk Roads.'],
      ['해설', 'Hyecho’s travel record was found in 1908 in a cave in Dunhuang, China.'],
    ],
  },

  'tk2-voyages': {
    title: 'The Age of Exploration',
    names: { 해설: 'Narrator', 강연자: 'Lecturer', 학생: 'Student' },
    outro: [
      'What crossed the Atlantic in both directions during the Columbian Exchange?',
      'What changes when we call the same event a discovery, an encounter, or an invasion?',
      'Which foods on my table came from across the sea, and what are their stories?',
    ],
    lines: [
      ['해설', 'Today we look at the Age of Exploration, which began in the late fifteenth century.'],
      ['강연자', 'Europeans looked for sea routes to get Asian spices and silk directly.'],
      ['강연자', 'Better shipbuilding, the compass, and sea charts also played a part.'],
      ['강연자', 'In 1492, Christopher Columbus sailed west, believing he would reach Asia.'],
      ['강연자', 'But he did not reach Asia. He reached islands in the Caribbean Sea.'],
      ['강연자', 'In 1498, Vasco da Gama sailed around Africa and reached India.'],
      ['강연자', 'Ferdinand Magellan’s crew were the first to sail around the world, but Magellan died on the way.'],
      ['학생', 'But people were already living in the Americas, weren’t they?'],
      ['강연자', 'Yes. That is why some point out that the word discovery shows only a European point of view.'],
      ['강연자', 'After this meeting, a huge exchange took place across the Atlantic.'],
      ['강연자', 'From the Americas, potatoes, corn, tomatoes, and chili peppers spread around the world.'],
      ['학생', 'Potatoes and chili peppers first came from the Americas?'],
      ['강연자', 'Yes. Before that, they were not found on tables in Europe or Asia.'],
      ['강연자', 'From Europe, horses, cattle, and wheat crossed to the Americas.'],
      ['강연자', 'Silver mined in the Americas also flowed in huge amounts to Europe and Asia.'],
      ['강연자', 'Historians call this the Columbian Exchange.'],
      ['강연자', 'Potatoes and corn fed many people in many regions.'],
      ['강연자', 'But the same ships also carried diseases like smallpox and measles.'],
      ['강연자', 'Native peoples, who had never faced these diseases, suffered terribly.'],
      ['강연자', 'With wars of conquest and forced labor added, the native population fell sharply.'],
      ['강연자', 'The losses were so great that scholars’ estimates of the exact numbers differ widely.'],
      ['학생', 'What happened when there were fewer people to do the work?'],
      ['강연자', 'European traders bought African people as slaves and shipped them across the Atlantic.'],
      ['강연자', 'They were forced to work on plantations. This trade went on for hundreds of years.'],
      ['강연자', 'The Age of Exploration linked the world together, but others paid the price.'],
      ['강연자', 'That is why we must look at one event from the places of many different people.'],
      ['강연자', 'Chili peppers, too, came to Korea on this wave and changed our food.'],
      ['해설', 'The term Columbian Exchange became widely known through a 1972 book by the American historian Alfred Crosby.'],
    ],
  },

  'tk2-industrial': {
    title: 'The Industrial Revolution',
    names: { 해설: 'Narrator', 강연자: 'Lecturer', 학생: 'Student' },
    outro: [
      'How did the Industrial Revolution change the way people worked?',
      'How is the fear that machines will take our jobs the same now as it was then, and how is it different?',
      'Is there anything I used today that was not made in a factory?',
    ],
    lines: [
      ['해설', 'Today’s talk is about the Industrial Revolution, which changed the world.'],
      ['강연자', 'In the late eighteenth century, the way things were made in Britain began to change greatly.'],
      ['학생', 'Why did it start in Britain, of all places?'],
      ['강연자', 'Many explain that Britain had plenty of coal and iron, and money from sea trade.'],
      ['강연자', 'Before that, people spun thread and wove cloth by hand at home.'],
      ['강연자', 'But then, one machine after another was invented to spin thread and weave cloth.'],
      ['강연자', 'The machines needed power to run, and the answer was the steam engine.'],
      ['학생', 'James Watt invented the steam engine, right?'],
      ['강연자', 'Steam engines existed before him. Watt greatly improved them so they used less fuel.'],
      ['강연자', 'Now factories did not have to be by rivers. They could be built anywhere there was coal.'],
      ['강연자', 'The factory system spread, with many workers gathered in one building, working to the pace of machines.'],
      ['강연자', 'In 1825, the first public railway using steam locomotives opened in England.'],
      ['강연자', 'In 1830, a railway linking Liverpool and Manchester opened.'],
      ['강연자', 'Goods and people could now move faster than ever before.'],
      ['강연자', 'A life of going to work by the factory clock also took root at this time.'],
      ['강연자', 'People crowded into cities to find work.'],
      ['강연자', 'But the cities were crowded and dirty, and the working day was very long.'],
      ['강연자', 'Even young children worked in factories and coal mines.'],
      ['학생', 'Children? Didn’t anyone stop it?'],
      ['강연자', 'As criticism grew, Britain passed the Factory Act in 1833.'],
      ['강연자', 'It banned textile mills from hiring children under nine.'],
      ['강연자', 'There was also the Luddite movement, in which workers who lost jobs to machines smashed them.'],
      ['강연자', 'Little by little, workers formed labor unions and demanded better conditions.'],
      ['강연자', 'The Industrial Revolution made goods plentiful and greatly changed daily life.'],
      ['강연자', 'At the same time, it created new kinds of poverty and environmental problems.'],
      ['강연자', 'If you look at only one side, you understand only half of it.'],
      ['강연자', 'This change spread through Europe and the United States, and then around the world.'],
      ['해설', 'The watt, the unit of power, is named after James Watt, who improved the steam engine.'],
    ],
  },

  'tk2-abolition': {
    title: 'The Movement to Abolish Slavery',
    names: { 해설: 'Narrator', 강연자: 'Lecturer', 학생: 'Student' },
    outro: [
      'What methods did the abolition movement use to change public opinion?',
      'How can we judge, in terms of justice, the decision to pay only the slave owners?',
      'How can I find out whose labor made the things I buy?',
    ],
    lines: [
      ['해설', 'Today we hear the story of the people who worked to end slavery.'],
      ['강연자', 'In the eighteenth century, the slave trade was a large and legal business in many countries.'],
      ['강연자', 'Ships crossed the Atlantic with people packed tightly below deck, and many died on the way.'],
      ['강연자', 'In 1787, a group to end the slave trade was formed in London.'],
      ['강연자', 'At its center were Quakers and people like Thomas Clarkson.'],
      ['강연자', 'Clarkson traveled to ports, gathering statements and evidence from sailors and doctors.'],
      ['학생', 'Did evidence alone change people’s minds?'],
      ['강연자', 'How it was shown mattered too. They spread a drawing of how people were packed inside a slave ship.'],
      ['강연자', 'The picture of people lying like cargo moved hearts more strongly than words.'],
      ['강연자', 'Olaudah Equiano, who had once been enslaved, wrote a book about his life, and many people read it.'],
      ['강연자', 'His firsthand account of being enslaved gave great strength to the movement.'],
      ['강연자', 'Many families also joined a boycott of sugar made by enslaved workers.'],
      ['강연자', 'In Parliament, William Wilberforce brought in a bill to end the trade again and again.'],
      ['학생', 'Why did it take so long?'],
      ['강연자', 'Because people who made huge profits from the slave trade fought hard against it.'],
      ['강연자', 'After many defeats, the act to abolish the slave trade finally passed in 1807.'],
      ['학생', 'So were all enslaved people freed then?'],
      ['강연자', 'No. Only the buying and selling across the sea stopped. People stayed enslaved.'],
      ['강연자', 'Britain did not pass a law to end slavery in its colonies until 1833.'],
      ['강연자', 'Even then, the government paid money not to the enslaved people, but to the slave owners.'],
      ['강연자', 'Enslaved people also fought for themselves. Haiti, in the Caribbean, is the best-known example.'],
      ['강연자', 'After an uprising that began in 1791, Haiti declared independence in 1804.'],
      ['강연자', 'After the Civil War, the United States changed its Constitution in 1865 to ban slavery.'],
      ['강연자', 'The last country in the Americas to end it was Brazil, in 1888.'],
      ['강연자', 'Freedom did not come from one law. It came from the struggles of many generations.'],
      ['강연자', 'We must also remember that discrimination lasted long after the laws changed.'],
      ['강연자', 'And forced labor still exists around the world today, in different forms.'],
      ['해설', 'Article 4 of the 1948 Universal Declaration of Human Rights says no one shall be held in slavery.'],
    ],
  },

  'tk2-democracy': {
    title: 'The History of Democracy',
    names: { 해설: 'Narrator', 강연자: 'Lecturer', 학생: 'Student' },
    outro: [
      'How is Athenian democracy similar to democracy today, and how is it different?',
      'As the right to vote expanded step by step, what drove those changes?',
      'What is needed so that everyone’s voice is heard in my school or group?',
    ],
    lines: [
      ['해설', 'Today we follow the long road that democracy has traveled.'],
      ['강연자', 'The word democracy comes from Greek and means rule by the people.'],
      ['강연자', 'In Athens in the fifth century BCE, citizens met in an assembly and decided state matters directly.'],
      ['강연자', 'Many officials were chosen by lot, and a dangerous person could be voted out of the city.'],
      ['학생', 'If you choose by lot, couldn’t the wrong person be picked?'],
      ['강연자', 'Athenians believed that drawing lots actually stopped the rich from taking all the power.'],
      ['학생', 'Could everyone vote?'],
      ['강연자', 'No. Only adult male citizens could. Women, slaves, and foreigners were left out.'],
      ['강연자', 'For a long time after that, most of the world was ruled by kings or nobles.'],
      ['강연자', 'In 1215, English nobles forced their king to accept the Magna Carta.'],
      ['강연자', 'It planted the seed of the idea that even the king is not above the law.'],
      ['강연자', 'The English Bill of Rights in 1689 stopped taxes without the consent of Parliament.'],
      ['강연자', 'In the late eighteenth century, revolutions followed one after another.'],
      ['강연자', 'The American Declaration of Independence of 1776 declared that people have rights that cannot be taken away.'],
      ['강연자', 'The French Declaration of the Rights of Man of 1789 said people are born free and equal in rights.'],
      ['학생', 'So could everyone vote from then on?'],
      ['강연자', 'No. For a long time, only men who owned property could vote.'],
      ['강연자', 'In Britain, the right to vote widened little by little through several reforms in the nineteenth century.'],
      ['강연자', 'Workers, women, and people facing racial discrimination fought, one group at a time, to win their rights.'],
      ['강연자', 'In 1893, New Zealand became the first country to let women vote in national elections.'],
      ['강연자', 'British women won the vote on the same terms as men in 1928.'],
      ['강연자', 'Once you reach a certain age, you get one vote, whatever your sex or wealth. That is universal suffrage.'],
      ['강연자', 'The Republic of Korea gave the vote to both men and women from its very first general election in 1948.'],
      ['강연자', 'Democracy is not only voting. It rests on the rule of law, separation of powers, and free speech.'],
      ['강연자', 'There has always been a warning that pure majority rule can crush minorities.'],
      ['강연자', 'So democracy is not a finished system. It is a process we keep improving.'],
      ['강연자', 'The more people take part in that process, the stronger it becomes.'],
      ['해설', 'The first general election of the Republic of Korea was held on May 10, 1948.'],
    ],
  },

  'tk2-provisional': {
    title: 'The Korean Provisional Government',
    names: { 해설: 'Narrator', 강연자: 'Lecturer', 학생: 'Student' },
    outro: [
      'What did it mean that the first article of the Provisional Charter chose a democratic republic?',
      'What were people trying to protect by keeping a government going outside the country for twenty-seven years?',
      'Have I ever tried to keep to my principles even in a difficult situation?',
    ],
    lines: [
      ['해설', 'Today we look at the path of the Provisional Government of the Republic of Korea, focusing on the facts.'],
      ['강연자', 'In 1910, the Korean Empire lost its sovereignty to Japan.'],
      ['강연자', 'On March 1, 1919, the independence movement, with people shouting for freedom, spread across the country.'],
      ['강연자', 'This movement led independence activists to decide to form a government.'],
      ['강연자', 'In April of that year, the Provisional Government of the Republic of Korea was founded in Shanghai, China.'],
      ['학생', 'Was the name Republic of Korea also chosen then for the first time?'],
      ['강연자', 'Yes. The Provisional Assembly chose the name Daehan Minguk, the Republic of Korea.'],
      ['강연자', 'The Provisional Assembly made laws, much like today’s National Assembly.'],
      ['강연자', 'The first article of the Provisional Charter declared the Republic of Korea a democratic republic.'],
      ['강연자', 'It set the direction from a country ruled by a king to a country where the people are in charge.'],
      ['강연자', 'That autumn, several provisional governments in different places united in Shanghai.'],
      ['강연자', 'To stay in touch with people back home, the government set up secret contact networks.'],
      ['강연자', 'It published a newspaper, The Independent, and appealed for independence through diplomacy.'],
      ['학생', 'Running a government outside the country must have been very hard.'],
      ['강연자', 'It was always short of money and people, and Japan watched it closely.'],
      ['강연자', 'After Yun Bong-gil’s attack in 1932, the government had to leave Shanghai.'],
      ['강연자', 'It moved from city to city in China and settled in Chongqing in 1940.'],
      ['강연자', 'That same year, in Chongqing, it created the Korean Liberation Army.'],
      ['강연자', 'In 1941, the Provisional Government declared war on Japan.'],
      ['학생', 'Did the Liberation Army really prepare to fight?'],
      ['강연자', 'It prepared an operation to enter Korea, but Japan surrendered before it could begin.'],
      ['강연자', 'At this time, the government was led by its chairman, Kim Gu.'],
      ['강연자', 'On August 15, 1945, Korea was finally liberated.'],
      ['강연자', 'But the government’s leaders had to return home as private persons, not as a government.'],
      ['강연자', 'The Provisional Government continued without a break from 1919 until liberation.'],
      ['강연자', 'There were conflicts over its direction inside, and opinions about it differ.'],
      ['강연자', 'Still, setting up the principle of a democratic republic is a clear legacy.'],
      ['해설', 'The preamble of Korea’s current Constitution says it carries on the legal tradition of the Provisional Government. That government was founded through the March First Movement.'],
    ],
  },

  'tk2-heritage': {
    title: 'What World Heritage Protects',
    names: { 해설: 'Narrator', 강연자: 'Lecturer', 학생: 'Student' },
    outro: [
      'What does World Heritage protect, and what does the Memory of the World protect?',
      'Why did people come to believe that all of humanity should protect one country’s heritage?',
      'What in my neighborhood would I most like to leave to the next generation?',
    ],
    lines: [
      ['해설', 'Today we talk about what World Heritage protects, and why.'],
      ['강연자', 'In the 1960s, Egypt built a huge dam on the Nile River.'],
      ['강연자', 'Because of it, the ancient temples of Abu Simbel were about to sink under water.'],
      ['강연자', 'When UNESCO called for help, many countries pooled their money and skills.'],
      ['강연자', 'The temples were cut into pieces, moved to higher ground, and built again.'],
      ['학생', 'Why did they help protect another country’s ruins?'],
      ['강연자', 'Because they believed that heritage belonged not to one country, but to all humanity.'],
      ['강연자', 'This experience led to the UNESCO World Heritage Convention in 1972.'],
      ['강연자', 'World Heritage includes cultural sites, natural sites, and mixed sites that have both.'],
      ['강연자', 'In 1992, the Memory of the World program began, to protect records.'],
      ['강연자', 'There is also a separate program for intangible heritage, like pansori, Korean storytelling through song.'],
      ['강연자', 'Not only buildings and landscapes, but books, documents, and records are humanity’s memory too.'],
      ['학생', 'Does heritage have to be old and grand?'],
      ['강연자', 'No. What matters is whether it has outstanding universal value for humanity.'],
      ['강연자', 'In Korea, Heo Jun’s Donguibogam, a book of medicine, joined the Memory of the World in 2009.'],
      ['강연자', 'Admiral Yi Sun-sin’s war diary, Nanjung Ilgi, joined in 2013.'],
      ['강연자', 'Janggyeong Panjeon at Haeinsa is a World Heritage building. It protects the Tripitaka woodblocks by controlling wind and moisture.'],
      ['학생', 'What changes when something is put on the list?'],
      ['강연자', 'The country promises the world that it will take care of that heritage.'],
      ['강연자', 'If a site faces serious damage, it may go on the list of World Heritage in Danger and get help.'],
      ['강연자', 'On the other hand, too many tourists can also damage a site.'],
      ['강연자', 'That is why being listed is not the end, but the start of protection.'],
      ['강연자', 'What heritage protects is not just stone and paper.'],
      ['강연자', 'It is the skills and ideas of the people who made it, and the memories they shared.'],
      ['강연자', 'When heritage is lost in war or disaster, those memories fade with it.'],
      ['강연자', 'So protecting heritage is not about the past. It is about the future.'],
      ['강연자', 'An old bridge or an old story in your neighborhood could be a small heritage too.'],
      ['해설', 'Korea’s first World Heritage sites, listed together in 1995, were Seokguram and Bulguksa, Haeinsa’s Janggyeong Panjeon, and Jongmyo Shrine.'],
    ],
  },
};
