// 청소년 영어 원고: 한국 근대 소설·수필 원문 낭독 (stories/teen-modern.js). 원문 번역이 아니라 줄거리를 간추린 자체 해설.
// lines 의 첫 칸은 한국어 이야기 cast 의 이름 그대로.
export default {
  'tm-camellia-1': {
    title: 'Camellias, Part 1',
    names: { 해설: 'Narrator' },
    outro: [
      'Why do you think the narrator refused the potatoes that Jeomsun gave him?',
      'What feelings might be behind Jeomsun’s rooster fights and her angry words?',
      'Have you ever had trouble because you could not read someone’s feelings?',
    ],
    lines: [
      ['해설', 'This story was written by Kim Yu-jeong and published in 1936.'],
      ['해설', 'It is set in a mountain village in Gangwon Province, told by a seventeen-year-old farm boy.'],
      ['해설', 'One spring afternoon, the boy sees his small rooster losing a fight again.'],
      ['해설', 'The big rooster belongs to Jeomsun’s family. It pecks his rooster’s comb until blood drips.'],
      ['해설', 'The boy is sure that Jeomsun, a girl his age, started the fight on purpose.'],
      ['해설', 'Why is she so mean to him these days? He thinks back to four days ago.'],
      ['해설', 'He was building a fence when Jeomsun quietly came up behind him and started teasing him.'],
      ['해설', 'Then she pushed three hot baked potatoes under his chin.'],
      ['해설', 'Your family doesn’t have these, right? she said. Spring potatoes taste great.'],
      ['해설', 'The boy felt hurt by her words. He said he did not eat potatoes and pushed them back.'],
      ['해설', 'Jeomsun’s face turned bright red, and tears filled her eyes. Then she ran away.'],
      ['해설', 'Her family manages the landlord’s fields, and the boy’s family rents land through them.'],
      ['해설', 'They even helped his family build a house when they first came to the village.'],
      ['해설', 'So his mother warned him to stay away from Jeomsun, or they might lose their land and home.'],
      ['해설', 'The next evening, the boy came down the mountain with a load of firewood on his jige, an A-frame carrier.'],
      ['해설', 'He found Jeomsun sitting alone, holding his family’s hen and beating it.'],
      ['해설', 'Die, die! she kept saying, as if it were her own hen.'],
      ['해설', 'He hit the fence with his stick and shouted, but she did not even flinch.'],
      ['해설', 'He could not run into her yard and fight a girl, so he could only hit the fence.'],
      ['해설', 'At last, she threw the hen at his head, and it left a mess on his forehead.'],
      ['해설', 'As he walked away, she called him names in a low voice, even insulting his father.'],
      ['해설', 'He turned to shout back, but she had already disappeared behind the fence.'],
      ['해설', 'He could not say a single word back. He was so angry that tears came to his eyes.'],
      ['해설', 'Readers can guess what the boy cannot: Jeomsun likes him, and the potatoes were her way of saying so.'],
    ],
  },

  'tm-camellia-2': {
    title: 'Camellias, Part 2',
    names: { 해설: 'Narrator' },
    outro: [
      'What was Jeomsun’s true feeling when she offered potatoes and started the rooster fights?',
      'Why does the narrator never notice Jeomsun’s feelings, and how does that make the story funny?',
      'Have you ever shown your liking for someone in a strange way, or seen a friend do it?',
    ],
    lines: [
      ['해설', 'Last time, Jeomsun offered the boy potatoes, and he refused. Since then, she has been making his life hard.'],
      ['해설', 'Whenever no one is around, she brings her strong rooster to fight his weak one.'],
      ['해설', 'The boy decides to fight back. He hears that gochujang, spicy red pepper paste, makes a fighting rooster strong.'],
      ['해설', 'He feeds his rooster half a dish of gochujang and lets it rest.'],
      ['해설', 'Then he sets it down next to Jeomsun’s rooster while she watches over the fence.'],
      ['해설', 'At first, his rooster loses. But suddenly it jumps up and pecks the big rooster’s comb.'],
      ['해설', 'The boy claps and cheers. He is sure he has found the secret.'],
      ['해설', 'But soon the big rooster strikes back hard, and Jeomsun laughs loudly so he can hear.'],
      ['해설', 'At home, he pours more gochujang water down the rooster’s throat through a pipe.'],
      ['해설', 'The poor rooster nearly dies. He hides it, and it barely recovers by the next morning.'],
      ['해설', 'Now, coming down the mountain, he finds the roosters fighting again. Jeomsun must have taken his rooster out.'],
      ['해설', 'Then he hears a willow whistle. Jeomsun is sitting among yellow camellia flowers, calmly playing it.'],
      ['해설', 'In this region, the yellow flower people call dongbaek, or camellia, is a kind of spicebush.'],
      ['해설', 'His rooster is bleeding and almost dead, and Jeomsun does not even blink.'],
      ['해설', 'Full of anger, the boy hits her big rooster with his stick, and it dies on the spot.'],
      ['해설', 'Jeomsun glares at him. Why did you kill our rooster? she shouts, and pushes him over.'],
      ['해설', 'Suddenly he realizes what he has done. His family might lose their land and home.'],
      ['해설', 'He covers his eyes with his sleeve and bursts into tears.'],
      ['해설', 'Then Jeomsun comes close and asks, So you won’t do it again?'],
      ['해설', 'He has no idea what she means, but he answers yes anyway.'],
      ['해설', 'Don’t worry about the rooster, she says. I won’t tell anyone.'],
      ['해설', 'Then she falls against his shoulder, and they both tumble into the yellow camellias.'],
      ['해설', 'The sharp, sweet smell of the flowers makes him dizzy, as if the ground is sinking.'],
      ['해설', 'Don’t tell anyone! she says. Okay! he answers.'],
      ['해설', 'Just then, Jeomsun’s mother calls her from below, angry that she left her sewing.'],
      ['해설', 'Jeomsun crawls quietly down the hill under the flowers, and the boy crawls up the mountain the other way.'],
      ['해설', 'The boy never quite understands Jeomsun, and that gap is what makes the story so funny and sweet.'],
    ],
  },

  'tm-bombom-1': {
    title: 'Spring, Spring, Part 1',
    names: { 해설: 'Narrator' },
    outro: [
      'Why does the narrator keep begging his future father-in-law to hold the wedding?',
      'What makes the father-in-law’s excuse about Jeomsun’s height so funny?',
      'When a promise keeps getting put off, how do you usually speak up?',
    ],
    lines: [
      ['해설', 'Spring, Spring is a short story by Kim Yu-jeong, published in 1935.'],
      ['해설', 'The narrator is a young man who works for a farmer as a future son-in-law.'],
      ['해설', 'This custom, called deril-sawi, meant a man lived and worked in his bride’s home before the wedding.'],
      ['해설', 'He has worked for three years and seven months without any pay.'],
      ['해설', 'Whenever he asks for the wedding, the farmer gives the same answer.'],
      ['해설', 'You fool! How can you marry her when she hasn’t grown up yet?'],
      ['해설', 'He means the height of his daughter, Jeomsun, the narrator’s future wife.'],
      ['해설', 'The narrator realizes the deal was wrong from the start. It had no clear end date.'],
      ['해설', 'He even carries water for Jeomsun, thinking the heavy water jar is keeping her short.'],
      ['해설', 'He also prays at the village shrine, asking the spirits to make her taller.'],
      ['해설', 'But she still only reaches up to his armpit.'],
      ['해설', 'One day, while planting rice, he suddenly feels it is all pointless.'],
      ['해설', 'Oh, my stomach! he cries, and he lies down on the bank of the rice field.'],
      ['해설', 'The father-in-law runs over angrily, grabs him by the collar, and slaps him.'],
      ['해설', 'His name is Bongpil, but villagers call him Yokpiri, from yok, the word for curses.'],
      ['해설', 'He manages a rich family’s land, so villagers must flatter him or lose their fields.'],
      ['해설', 'But he cannot be too harsh with the narrator, because the busy farming season is coming.'],
      ['해설', 'Last year, he promised a wedding in the fall to get the narrator back to work.'],
      ['해설', 'But when the harvest came, he just pointed at Jeomsun and said she was still too small.'],
      ['해설', 'Now the narrator says he will quit and asks for his wages.'],
      ['해설', 'Did you come here as a son-in-law or a farmhand? the father-in-law snaps.'],
      ['해설', 'The narrator drags him off by the sleeve to ask the village head to judge.'],
      ['해설', 'But the real reason for the fight happened the day before, in a field on the mountain.'],
      ['해설', 'There, on a warm spring day, he felt strangely restless and hit the ox for no reason.'],
    ],
  },

  'tm-bombom-2': {
    title: 'Spring, Spring, Part 2',
    names: { 해설: 'Narrator' },
    outro: [
      'What feelings are hidden in Jeomsun’s words, Are you just going to work forever?',
      'What does Mungtae’s story about the earlier sons-in-law show about the father-in-law?',
      'Have you ever changed what you did after listening to someone else? How did it turn out?',
    ],
    lines: [
      ['해설', 'Last time, the narrator pretended to be sick and took his father-in-law to the village head.'],
      ['해설', 'The day before, he had been upset after seeing Jeomsun bring him lunch.'],
      ['해설', 'Jeomsun is sixteen, ten years younger than him, but small for her age.'],
      ['해설', 'To him, she looks round and sweet, like a little yellow melon.'],
      ['해설', 'That day, as she picked up the dishes, she muttered to herself.'],
      ['해설', 'Are you just going to work forever?'],
      ['해설', 'Surprised, he asked the air, Then what should I do?'],
      ['해설', 'Ask him to hold the wedding, of course! she snapped, and ran off with a red face.'],
      ['해설', 'He thought that, like plants in spring, Jeomsun had grown up inside in just a few days.'],
      ['해설', 'Now at the village head’s house, the narrator explains everything.'],
      ['해설', 'The village head tells Bongpil to let them marry soon.'],
      ['해설', 'But when Bongpil insists his daughter is not grown yet, the village head just gives up.'],
      ['해설', 'Then how did my tiny mother-in-law have a child? the narrator asks.'],
      ['해설', 'The father-in-law laughs, then secretly elbows him in the ribs.'],
      ['해설', 'Later, the village head warns him quietly. Leaving work in the busy season could send him to prison.'],
      ['해설', 'Frightened, the narrator goes back to work without a word.'],
      ['해설', 'But that night, he visits his friend Mungtae, who mocks him for being slapped.'],
      ['해설', 'Mungtae tells him that the farmer’s first daughter went through fourteen sons-in-law in ten years.'],
      ['해설', 'The farmer has no sons, so he uses future sons-in-law as free workers.'],
      ['해설', 'The narrator is the third son-in-law for Jeomsun, the second daughter.'],
      ['해설', 'The third daughter is only six, so the farmer wants to keep him working for years.'],
      ['해설', 'Stop being a fool, Mungtae says. Make a fuss and demand the wedding!'],
      ['해설', 'These words stay in the narrator’s mind and lead to the big fight the next morning.'],
    ],
  },

  'tm-bombom-3': {
    title: 'Spring, Spring, Part 3',
    names: { 해설: 'Narrator' },
    outro: [
      'Why did the father-in-law keep using Jeomsun’s height as an excuse to delay the wedding?',
      'What makes the fight between the narrator and his father-in-law so funny?',
      'If you worked with someone who kept putting off a promise, what would you do?',
    ],
    lines: [
      ['해설', 'Last time, Mungtae told the narrator that his father-in-law was just using him.'],
      ['해설', 'The narrator does not fully believe Mungtae, who has his own grudge against the farmer.'],
      ['해설', 'The next morning, Jeomsun brings his breakfast and mutters again.'],
      ['해설', 'You just came back from the village head? You should have pulled his beard, you fool!'],
      ['해설', 'Then she runs inside with a red face. The narrator feels sad and ashamed.'],
      ['해설', 'If his future wife thinks he is a fool, his life will be miserable.'],
      ['해설', 'So he lies down in the yard and refuses to go to work.'],
      ['해설', 'Oh, my stomach! he groans, when the father-in-law tells him to get up.'],
      ['해설', 'The angry father-in-law pokes and kicks him with a stick, but he does not move.'],
      ['해설', 'He knows Jeomsun is watching through a hole in the fence.'],
      ['해설', 'So when he is hit hard, he jumps up and grabs his father-in-law’s beard.'],
      ['해설', 'Why won’t you hold the wedding? he shouts, and pushes the old man down a slope.'],
      ['해설', 'The father-in-law grabs him in a painful place, and the narrator nearly faints.'],
      ['해설', 'The narrator grabs him back the same way, and the old man cries out in pain.'],
      ['해설', 'Jeomsun! Jeomsun! the father-in-law calls for help.'],
      ['해설', 'Jeomsun and her mother rush out. The narrator expects Jeomsun to be on his side.'],
      ['해설', 'But Jeomsun pulls his ear and cries, You’re going to kill my father!'],
      ['해설', 'Shocked, the narrator loses all his strength. He just stares at her face.'],
      ['해설', 'The father-in-law beats him with the stick, but he does not even try to escape.'],
      ['해설', 'The story also tells what happens after the fight, though the narrator tells it before the ending.'],
      ['해설', 'His head is cut open, but the father-in-law treats the wound himself.'],
      ['해설', 'He gives him some tobacco and promises the wedding this fall.'],
      ['해설', 'Moved to tears, the narrator promises never to do it again and goes back to work.'],
      ['해설', 'Readers can see that the promise will probably be broken again, just like before.'],
      ['해설', 'Kim Yu-jeong uses humor to show how poor farmers were tricked by people with power.'],
    ],
  },

  'tm-lucky-day-1': {
    title: 'A Lucky Day, Part 1',
    names: { 해설: 'Narrator' },
    outro: [
      'Why does Kim Cheomji keep taking customers even though he knows his wife is sick?',
      'How does the scene where his wife begs him not to go out hint at what will happen?',
      'Have you ever kept yourself extra busy to forget a worry?',
    ],
    lines: [
      ['해설', 'A Lucky Day is a short story by Hyun Jin-geon, published in 1924.'],
      ['해설', 'It takes place in Seoul during Japanese colonial rule, on a cold, rainy winter day.'],
      ['해설', 'Kim Cheomji pulls a rickshaw, a small cart for carrying passengers.'],
      ['해설', 'For about ten days, he has earned almost nothing.'],
      ['해설', 'But today, his luck is good. His first two rides bring him eighty jeon, or cents.'],
      ['해설', 'With this money, he can buy a drink, and better yet, some seolleongtang for his sick wife.'],
      ['해설', 'Seolleongtang is a warm beef bone soup, and she has begged for it for three days.'],
      ['해설', 'His wife has been coughing for over a month, but they cannot afford any medicine.'],
      ['해설', 'Ten days ago, she ate half-cooked millet too fast and became even sicker.'],
      ['해설', 'Kim scolded her and hit her then, but his own eyes filled with tears.'],
      ['해설', 'Now his luck continues. A student asks to be taken to Namdaemun Station.'],
      ['해설', 'Kim hesitates. That morning, his wife begged him not to go out.'],
      ['해설', 'Please stay home today. I’m so sick, she said in a weak voice.'],
      ['해설', 'Kim answered roughly, but her pleading eyes stay in his mind.'],
      ['해설', 'Still, he asks for one won and fifty jeon, a huge price, and he is surprised at himself.'],
      ['해설', 'The student agrees, and Kim runs so fast he almost seems to fly.'],
      ['해설', 'But as he passes near his home, his legs suddenly feel heavy.'],
      ['해설', 'He seems to hear his wife’s voice, and his baby son Gaettong crying.'],
      ['해설', 'Kim stops in the middle of the road until the student shouts that he will miss the train.'],
      ['해설', 'Kim runs again. The farther he gets from home, the lighter his steps become.'],
      ['해설', 'It is as if running fast is the only way to forget his worries.'],
    ],
  },

  'tm-lucky-day-2': {
    title: 'A Lucky Day, Part 2',
    names: { 해설: 'Narrator' },
    outro: [
      'Why does Kim Cheomji stop at a bar instead of going straight home after earning so much?',
      'What fear can you sense when Kim gets drunk and angry?',
      'When you feel joy and worry at the same time, how do you usually act?',
    ],
    lines: [
      ['해설', 'Last time, Kim Cheomji took a student to the station for a big fare.'],
      ['해설', 'Holding the money, he feels as happy as if he were suddenly rich.'],
      ['해설', 'But as his sweat cools in the rain, he begins to shiver with cold and hunger.'],
      ['해설', 'He decides to wait near the station for one more customer.'],
      ['해설', 'He asks a fashionable young woman in a cape, but she shouts at him to go away.'],
      ['해설', 'Then he finds a man with a huge bag who could not fit on the crowded streetcar.'],
      ['해설', 'Kim agrees to take him to Insa-dong for sixty jeon.'],
      ['해설', 'With the heavy passenger, his body feels light. But after the ride, his heart grows heavy and nervous.'],
      ['해설', 'As he gets closer to home, he slows down.'],
      ['해설', 'He is afraid of learning some terrible news that is waiting for him.'],
      ['해설', 'He wants to hold on to his joy for as long as he can.'],
      ['해설', 'Just then, his friend Chisam comes out of a small bar.'],
      ['해설', 'Chisam is fat and red-faced, while Kim is thin and dry like an old stick.'],
      ['해설', 'Kim is so glad to see him that Chisam seems like someone who has saved his life.'],
      ['해설', 'Inside the warm bar, Kim eats pancakes and soup and drinks large cups of makgeolli, a rice wine.'],
      ['해설', 'Soon he is drunk. He boasts that he earned thirty won today, which is not true.'],
      ['해설', 'When the server hesitates, Kim gets angry and throws a one-won bill at him.'],
      ['해설', 'A few silver coins fall and ring on the floor.'],
      ['해설', 'His loud anger seems to hide a deep fear growing inside him.'],
    ],
  },

  'tm-lucky-day-3': {
    title: 'A Lucky Day, Part 3',
    names: { 해설: 'Narrator' },
    outro: [
      'How does the title, A Lucky Day, clash with the ending? What do we call this kind of technique?',
      'Why did Kim Cheomji keep putting off going home?',
      'How is the life of poor city people in the 1920s similar to or different from life today?',
    ],
    lines: [
      ['해설', 'Last time, Kim Cheomji got drunk with his friend Chisam at a bar.'],
      ['해설', 'Kim throws the coins at the wall and calls them cursed money.'],
      ['해설', 'Then he laughs loudly and copies the voice of the woman who rejected him.'],
      ['해설', 'Everyone in the bar laughs. But suddenly Kim begins to cry.'],
      ['해설', 'My wife is dead, he says.'],
      ['해설', 'Chisam does not believe him. Then Kim laughs again and says it was only a joke.'],
      ['해설', 'She isn’t dead, I tell you! he shouts, as if he is trying to believe it himself.'],
      ['해설', 'At last, Kim buys the seolleongtang and goes home in the cold rain.'],
      ['해설', 'His home is one small rented room, with no warmth and no money.'],
      ['해설', 'As he steps inside the gate, the house is terribly quiet.'],
      ['해설', 'There is no coughing and no heavy breathing.'],
      ['해설', 'He hears only the sound of the baby sucking at an empty breast.'],
      ['해설', 'Kim shouts angrily, as if his loud voice could chase away his fear.'],
      ['해설', 'He opens the door, and a bad smell of dirt and sickness fills the air.'],
      ['해설', 'He kicks his wife’s leg and yells at her to get up, but it feels like wood.'],
      ['해설', 'The baby lets go and cries weakly, too tired even to make a real sound.'],
      ['해설', 'Kim shakes his wife and shouts at her to speak. There is no answer.'],
      ['해설', 'Then he sees her eyes, staring blankly at the ceiling.'],
      ['해설', 'Big tears fall from his eyes onto her stiff face.'],
      ['해설', 'He presses his face against hers and murmurs.'],
      ['해설', 'I bought you seolleongtang. Why can’t you eat it? Strange, my luck was so good today.'],
      ['해설', 'The title’s cruel irony shows how hard life was for the poor in colonial Seoul.'],
    ],
  },

  'tm-buckwheat-1': {
    title: 'When the Buckwheat Blooms, Part 1',
    names: { 해설: 'Narrator' },
    outro: [
      'Why did Heo scold Dong-i at the Chungju House tavern?',
      'How is Heo’s donkey described, and what does it mean to him?',
      'Is there a day in your life that you think you will never forget?',
    ],
    lines: [
      ['해설', 'When the Buckwheat Blooms is a short story by Lee Hyo-seok, published in 1936.'],
      ['해설', 'It follows traveling merchants who move from one country market to another in Gangwon Province.'],
      ['해설', 'On a hot summer afternoon, the market in Bongpyeong is already quiet.'],
      ['해설', 'Heo, an old cloth seller with a pockmarked face, is left-handed.'],
      ['해설', 'Heo is called saengwon, an old title of respect for a man.'],
      ['해설', 'He decides to pack up with his partner, Jo, and walk all night to the next market in Daehwa.'],
      ['해설', 'Jo teases him about a woman who runs a tavern, called the Chungju House.'],
      ['해설', 'Heo has never been lucky with women, and just thinking of her makes him blush.'],
      ['해설', 'At the tavern, he sees Dong-i, a young merchant, flirting with the tavern woman.'],
      ['해설', 'Heo suddenly gets angry. He slaps Dong-i and scolds him like a father.'],
      ['해설', 'You must have parents too. Do your business properly. Get out of here!'],
      ['해설', 'Dong-i leaves without a word, and Heo soon feels sorry for being so harsh.'],
      ['해설', 'Later, Dong-i runs back, out of breath. Heo’s donkey has broken its rope!'],
      ['해설', 'Heo is touched that Dong-i came to tell him, even after being scolded.'],
      ['해설', 'Heo and his donkey have traveled together for twenty years and grown old together.'],
      ['해설', 'Like its owner, the donkey has thin hair, watery eyes, and worn-out hooves.'],
      ['해설', 'Some children have been teasing the donkey. They laugh at Heo and call him a left-handed man.'],
      ['해설', 'Heo chases them with a whip, but he cannot catch even one child.'],
      ['해설', 'For twenty years, Heo has walked from market to market, rarely missing Bongpyeong.'],
      ['해설', 'The beautiful roads between the markets have become his true hometown.'],
      ['해설', 'Once he lost all his savings in three days of gambling, but he refused to sell his donkey.'],
      ['해설', 'Heo has never had a family. His donkey is the only one close to him.'],
      ['해설', 'Yet there is one night in Bongpyeong, long ago, that he can never forget.'],
    ],
  },

  'tm-buckwheat-2': {
    title: 'When the Buckwheat Blooms, Part 2',
    names: { 해설: 'Narrator' },
    outro: [
      'How does the moonlit buckwheat field match Heo’s memory?',
      'What does the fact that Dong-i is left-handed lead us to guess at the end?',
      'Is there a scene or memory that you have kept in your heart for a long time?',
    ],
    lines: [
      ['해설', 'Last time, Heo, Jo, and Dong-i left Bongpyeong to walk all night to Daehwa.'],
      ['해설', 'The road is eighty li long, about thirty kilometers, over two hills and across a stream.'],
      ['해설', 'The moon is bright, and the hills are covered with white buckwheat flowers.'],
      ['해설', 'The flowers look like salt scattered under the moonlight, so beautiful it takes their breath away.'],
      ['해설', 'Once again, Heo begins the story Jo has heard so many times.'],
      ['해설', 'Long ago, on a night just like this, Heo went to bathe in a stream in Bongpyeong.'],
      ['해설', 'In an old mill, he met the most beautiful girl in town, the daughter of the Seong family.'],
      ['해설', 'She was crying because her family was in trouble. They talked, and they spent the night together.'],
      ['해설', 'The next day, her family left for Jecheon. Heo searched for her, but never found her again.'],
      ['해설', 'That is why he has loved Bongpyeong for half his life.'],
      ['해설', 'Then Dong-i tells his own story. He has never known his father.'],
      ['해설', 'His mother had him in Jecheon, after she was driven out of her home.'],
      ['해설', 'She married a stepfather who drank and beat them, so Dong-i left home at eighteen.'],
      ['해설', 'Crossing the cold stream, Heo asks where Dong-i’s mother’s family came from.'],
      ['해설', 'Bongpyeong, Dong-i answers. But he does not know his father’s name.'],
      ['해설', 'Shocked, Heo slips and falls into the water.'],
      ['해설', 'Dong-i carries him on his back across the stream. His back feels warm to Heo.'],
      ['해설', 'Heo learns that Dong-i’s mother now lives alone in Jecheon and wishes to meet his father.'],
      ['해설', 'After Daehwa, I’m going to Jecheon, says Heo. Will you come with me, Dong-i?'],
      ['해설', 'As they walk on, Heo notices that Dong-i holds the whip in his left hand.'],
      ['해설', 'Dong-i is left-handed, just like Heo.'],
      ['해설', 'The story never says it, but readers can guess that Dong-i may be Heo’s son.'],
      ['해설', 'The bells of the donkeys ring clearly over the dark fields, and the moon sinks low.'],
    ],
  },

  'te-youth': {
    title: 'In Praise of Youth',
    names: { 해설: 'Narrator' },
    outro: [
      'What does the writer value most about youth?',
      'What feelings do images like boiling blood and the engine of a great ship give you?',
      'What is your biggest dream or ideal right now?',
    ],
    lines: [
      ['해설', 'In Praise of Youth is an essay by Min Tae-won, first published in 1929.'],
      ['해설', 'It begins with one word: Youth! Just hearing it makes our hearts beat faster.'],
      ['해설', 'The writer asks young people to put their hands on their chests and listen to their hearts.'],
      ['해설', 'The blood of youth boils, and the heart beats as strong as the engine of a great ship.'],
      ['해설', 'He says this energy is what has moved human history forward.'],
      ['해설', 'Reason is clear but cold like ice, and wisdom is sharp but stays in its case like a sword.'],
      ['해설', 'Without the warm blood of youth, the world would be lonely and frozen.'],
      ['해설', 'Just as the spring wind wakes up plants and flowers, youth brings warmth and life.'],
      ['해설', 'Because of youth, love grows like grass, and ideals bloom like flowers.'],
      ['해설', 'Without love, life would be a desert with no oasis.'],
      ['해설', 'Without ideals, only decay would be left.'],
      ['해설', 'The writer asks why Buddha, Jesus, and Confucius traveled and suffered.'],
      ['해설', 'Was it for food, clothes, or comfort? No.'],
      ['해설', 'They had great ideals: to guide all people toward a happier, more peaceful life.'],
      ['해설', 'That is why their names are still remembered after thousands of years.'],
      ['해설', 'Even for ordinary people, ideals are like salt that keeps life from rotting.'],
      ['해설', 'Young people are pure, look far ahead, and have the courage to make their dreams real.'],
      ['해설', 'This is something children and old people cannot have in the same way.'],
      ['해설', 'Youth is the golden age of life, the writer says.'],
      ['해설', 'So let us sing and move forward with all our strength, to make the most of it!'],
    ],
  },
};
