// 청소년 영어 원고: 셜록 홈즈 2 (stories/teen-holmes2.js). 문장은 자체 각색.
// lines 의 첫 칸은 한국어 이야기 cast 의 이름 그대로.
export default {
  'hm2-pips-1': {
    title: 'The Five Orange Pips, Part 1',
    names: { 해설: 'Narrator', 홈즈: 'Holmes', 왓슨: 'Watson', 오픈쇼: 'John Openshaw' },
    outro: [
      'How did Doyle turn five ordinary orange pips into a sign of terror?',
      'What was the difference between the police, who called the warning a joke, and Holmes, who saw the danger at once?',
      'In real life, how can past wrongs come back instead of disappearing?',
    ],
    lines: [
      ['해설', 'It was a night in September 1887, and an autumn storm was sweeping over London. Watson was staying at Baker Street.'],
      ['왓슨', 'The doorbell, in this weather? Is it a friend of yours?'],
      ['홈즈', 'You are my only friend, Watson. Anyone who comes on a night like this must be a client.'],
      ['해설', 'In came a young man of about twenty-two. Rain dripped from his umbrella and raincoat.'],
      ['홈즈', 'You have come up from the south-west, I see. The clay and chalk on your shoes tell me so. Sit by the fire.'],
      ['오픈쇼', 'I come from Horsham. My name is John Openshaw. I hear you have never been beaten, Mr. Holmes.'],
      ['홈즈', 'I have been beaten four times. Three times by men, and once by a woman. Now, what is the matter?'],
      ['오픈쇼', 'It begins with my uncle Elias. As a young man, he went to America and became a planter in Florida.'],
      ['오픈쇼', 'In the Civil War he fought as a Confederate officer. Later he came back to England and lived alone in Horsham.'],
      ['해설', 'He said he left America because he hated the policy of giving Black people the vote. It was open racism.'],
      ['오픈쇼', 'In March 1883, a letter came for my uncle with a postmark from Pondicherry, India.'],
      ['오픈쇼', 'When he opened it, five dried orange pips fell out. My uncle’s face turned gray.'],
      ['오픈쇼', 'Inside the envelope were three letters K. He cried out that his sins had caught up with him.'],
      ['해설', 'Elias took papers from a brass box in the attic and burned them all. The lid also had three K’s on it.'],
      ['오픈쇼', 'Seven weeks later, he was found face down in a shallow pond in the garden. They called it suicide.'],
      ['해설', 'John’s father inherited the estate. Then, in January 1885, a letter came for the father.'],
      ['오픈쇼', 'It was from Dundee. The same five pips, the three K’s, and an order to put the papers on the sundial.'],
      ['오픈쇼', 'My father laughed it off as a joke. Three days later, he fell into a deep chalk pit and died.'],
      ['해설', 'This time they called it an accident. John inherited everything, and for two years and eight months, nothing happened.'],
      ['오픈쇼', 'But yesterday morning, this letter came. This time the postmark is East London.'],
      ['해설', 'Five dried orange pips rolled out of the envelope. The order about the sundial was the same.'],
      ['오픈쇼', 'The police laughed and called it a prank. They only left one constable at my house.'],
      ['홈즈', 'Incredible foolishness! But why did you not come to me at once? You have wasted a whole day.'],
      ['해설', 'John handed over a half-burned page. It had been torn from a diary for March 1869.'],
      ['오픈쇼', 'It says, set the pips on McCauley, Paramore, and John Swain. McCauley cleared.'],
      ['홈즈', 'Go home at once. Put this page into the brass box and set it on the sundial.'],
      ['홈즈', 'Add a note saying all the other papers were burned. And be very careful tonight.'],
      ['오픈쇼', 'Thank you. It is not yet nine, so if I keep to the main streets, I will be safe.'],
      ['해설', 'The young man walked out into the storm. What did the five pips and those three letters mean?'],
      ['해설', 'The Five Orange Pips first appeared in The Strand Magazine in November 1891.'],
    ],
  },

  'hm2-pips-2': {
    title: 'The Five Orange Pips, Part 2',
    names: { 해설: 'Narrator', 홈즈: 'Holmes', 왓슨: 'Watson' },
    outro: [
      'What did Doyle want to say by having the criminals vanish at sea instead of in a courtroom?',
      'How did Holmes reason, from postmarks and dates alone, that the killers traveled on a sailing ship?',
      'What should our society do to stop hatred and discrimination from turning into violence?',
    ],
    lines: [
      ['해설', 'Last time, John Openshaw received the five orange pips that had taken his uncle and his father.'],
      ['해설', 'After John left, Holmes took down an American encyclopedia and opened it to the letter K.'],
      ['홈즈', 'Listen, Watson. The Ku Klux Klan. A secret society formed by former Confederate soldiers after the Civil War.'],
      ['해설', 'The KKK was a violent white supremacist group. It threatened and killed Black people who tried to vote, and those who supported them.'],
      ['해설', 'What they did was not noble revenge but terrible crime. The American government even passed laws to punish them.'],
      ['홈즈', 'They sent a warning first. Oak leaves, melon seeds, or orange pips. Those who ignored it were harmed.'],
      ['홈즈', 'The society suddenly broke up in 1869. That is when the uncle ran off with its papers.'],
      ['왓슨', 'Then the names in the diary...'],
      ['홈즈', 'They were people who were sent the pips. You can guess what cleared means.'],
      ['홈즈', 'Now look at the postmarks. Pondicherry, Dundee, London. All ports. The sender travels by ship.'],
      ['홈즈', 'From warning to death, seven weeks from Pondicherry, three days from Dundee. Steamers carried the letters, but the men came by sailing ship.'],
      ['홈즈', 'But this letter came from London. That means they are already here.'],
      ['해설', 'The next morning, Watson opened the newspaper and froze.'],
      ['왓슨', 'Holmes, look at this. Last night a young gentleman drowned near Waterloo Bridge. It’s John Openshaw.'],
      ['해설', 'The paper called it an accident. In the dark storm, he had probably fallen from a landing stage.'],
      ['홈즈', 'That hurts my pride, Watson. He came to me for help, and I sent him away to his death.'],
      ['홈즈', 'This is my case now. I will catch that gang with my own hands.'],
      ['해설', 'Holmes was out all day and came back late at night. He cut an orange and put five pips into an envelope.'],
      ['해설', 'Inside the flap he wrote, S.H. for J.O. It was addressed to Captain James Calhoun of the ship Lone Star.'],
      ['홈즈', 'I searched all the shipping records. Only the Lone Star was in Pondicherry and in Dundee at those times.'],
      ['홈즈', 'She left London this morning for Savannah, in America. This letter will go by steamer and arrive first.'],
      ['홈즈', 'When they step ashore, these pips will be waiting. I have also cabled the Savannah police.'],
      ['해설', 'The only American-born men on board were the captain and his two mates. Holmes believed they were the three killers.'],
      ['해설', 'But that autumn, unusually fierce storms swept the Atlantic. The Lone Star never reached Savannah.'],
      ['해설', 'Long afterward, there was only news of a broken piece of a boat, marked L.S., floating far out at sea.'],
      ['해설', 'The killers never stood in court. Neither Holmes’s revenge nor the law’s judgment ever reached them.'],
      ['해설', 'And outside this story, the KKK’s violence went on for a long time. Its victims were real people.'],
      ['해설', 'This is the fifth story in The Adventures of Sherlock Holmes, published as a book in 1892.'],
    ],
  },

  'hm2-identity-1': {
    title: 'A Case of Identity, Part 1',
    names: { 해설: 'Narrator', 홈즈: 'Holmes', 왓슨: 'Watson', 메리: 'Mary Sutherland' },
    outro: [
      'What questions did Doyle leave in readers’ minds with a groom who vanished on his wedding day?',
      'What did Holmes learn from Mary’s sleeves and nose, and how does it show her character?',
      'How far could you trust someone you only knew through letters, without seeing their face clearly?',
    ],
    lines: [
      ['해설', 'One autumn day, Holmes and Watson sat facing each other by the fire at Baker Street.'],
      ['홈즈', 'Watson, life is far stranger than anything the human mind could invent.'],
      ['왓슨', 'Well, the cases in the newspapers all seem dull and dirty to me.'],
      ['홈즈', 'That is because the papers look in the wrong places. The real stories hide in small things. Look out the window.'],
      ['해설', 'On the opposite sidewalk, a woman in a large feathered hat was looking up at their window, hesitating.'],
      ['홈즈', 'Pacing like that means a love affair. An angry person would have rung the bell at once.'],
      ['해설', 'Soon the visitor came in. She was a young woman named Mary Sutherland.'],
      ['홈즈', 'With your short sight, isn’t it tiring to do so much typing?'],
      ['메리', 'Oh, how did you know? Anyway, please help me. Find my fiancé, Mr. Hosmer Angel.'],
      ['해설', 'Mary’s father had died, and her mother had married a man about fifteen years younger than herself.'],
      ['메리', 'My stepfather, Mr. Windibank, is only five years older than me. He often goes to France for a wine company.'],
      ['메리', 'I get about a hundred pounds a year in interest from money my uncle in New Zealand left me. We use it at home.'],
      ['메리', 'My stepfather didn’t like me going out. While he was in France, I went to a ball.'],
      ['메리', 'That’s where I met Mr. Hosmer. But when my stepfather came back, we couldn’t meet anymore.'],
      ['메리', 'So we wrote letters. His letters were always typewritten, even the signature.'],
      ['홈즈', 'How very interesting. Where does he work?'],
      ['메리', 'He said he was a cashier in an office on Leadenhall Street. I left my letters at the post office for him.'],
      ['홈즈', 'What did he look like?'],
      ['메리', 'He was very shy. His eyes were weak, so he wore tinted glasses, and he had bushy whiskers. He always whispered because of a sore throat.'],
      ['해설', 'When the stepfather went to France again, Hosmer came to the house and proposed. The wedding was set for that Friday.'],
      ['메리', 'He made me swear on the Bible that I would stay true to him, whatever happened.'],
      ['해설', 'On Friday morning, Hosmer put Mary and her mother into one cab, and got into another carriage himself.'],
      ['해설', 'The women reached the church first and waited for his carriage. But when the door opened, it was empty.'],
      ['메리', 'The driver was sure he saw him get in. Since then, there has been no word at all.'],
      ['메리', 'My mother told me never to speak of it again. But I will wait for him.'],
      ['홈즈', 'Forget him, Miss Sutherland. He has gone out of your life.'],
      ['메리', 'I can’t. I made him a promise.'],
      ['해설', 'Mary left four of Hosmer’s letters and went home. Holmes lit his pipe and sank into deep thought.'],
      ['해설', 'To Watson it was all a mystery, but Holmes already saw something. Who was the vanished groom?'],
      ['해설', 'A Case of Identity is a Holmes story first published in The Strand in September 1891.'],
    ],
  },

  'hm2-identity-2': {
    title: 'A Case of Identity, Part 2',
    names: { 해설: 'Narrator', 홈즈: 'Holmes', 왓슨: 'Watson', 윈디뱅크: 'James Windibank' },
    outro: [
      'Through a villain the law cannot punish, how did Doyle show the gap between law and justice?',
      'What thinking lies behind Holmes’s choice not to tell Mary the truth, and was it right?',
      'How does money tie down one person’s life within a family today?',
    ],
    lines: [
      ['해설', 'Last time, Mary Sutherland asked Holmes to find her fiancé, Hosmer Angel, who vanished on their wedding day.'],
      ['해설', 'The next evening, Watson returned to find Holmes in the middle of a chemistry experiment.'],
      ['왓슨', 'Have you solved the mystery?'],
      ['홈즈', 'There was hardly any mystery. I am only sorry that the law cannot punish the man.'],
      ['해설', 'Just then, a smooth-faced man of about thirty came in. It was Mary’s stepfather, James Windibank.'],
      ['윈디뱅크', 'I got your letter. My girl has made a needless fuss. That man will never come back.'],
      ['홈즈', 'On the contrary. I am quite sure I will find Mr. Hosmer Angel.'],
      ['해설', 'Windibank gave a start and dropped his gloves.'],
      ['홈즈', 'Mr. Windibank, did you know a typewriter has its own habits, just like handwriting?'],
      ['홈즈', 'Your reply was typed too. Every e is smudged, and every r is missing its tail.'],
      ['홈즈', 'Hosmer Angel’s four letters have the very same flaws. And fourteen others besides.'],
      ['해설', 'Windibank grabbed his hat and stood up. Holmes moved quickly to the door and turned the key.'],
      ['홈즈', 'I know everything. Sit down. Let me tell you the whole story from the beginning.'],
      ['홈즈', 'You married a much older woman for her money. Your stepdaughter’s interest helped pay for the house too.'],
      ['홈즈', 'If she married, a hundred pounds a year would be gone. So you made a plan to keep her.'],
      ['홈즈', 'With your wife’s help, you put on tinted glasses and false whiskers, and hid your voice in a whisper.'],
      ['홈즈', 'As Hosmer Angel, you courted your short-sighted stepdaughter. You only appeared when you were supposedly in France.'],
      ['홈즈', 'After making her swear on the Bible, you got into the carriage by one door and slipped out the other.'],
      ['홈즈', 'Because of that oath, she would not look at another man for ten years. That was your plan.'],
      ['홈즈', 'I wrote to your firm too. I described Hosmer without the disguise, and they said it matched you exactly.'],
      ['윈디뱅크', 'So what will you do? I have broken no law. You are the one breaking it by locking the door.'],
      ['홈즈', 'True, the law cannot touch you. Then let me open the door.'],
      ['홈즈', 'But if the young lady had a brother or a friend, he would lay a whip across your shoulders. And here is one.'],
      ['해설', 'As Holmes stepped toward his hunting crop, Windibank tumbled down the stairs and ran away.'],
      ['홈즈', 'A cold-blooded villain! A man like that goes from crime to crime, until he ends on the gallows.'],
      ['왓슨', 'Shouldn’t we tell Miss Sutherland the truth?'],
      ['홈즈', 'She would not believe it. An old Persian saying warns of danger to anyone who takes a dream from a woman.'],
      ['해설', 'In that era, women’s money and marriages were easily controlled by the men of the family.'],
      ['해설', 'Holmes’s choice to hide the truth may also have treated Mary as someone unable to judge for herself.'],
      ['해설', 'Arthur Conan Doyle was born in 1859 in Edinburgh, Scotland.'],
    ],
  },

  'hm2-carbuncle-1': {
    title: 'The Blue Carbuncle, Part 1',
    names: { 해설: 'Narrator', 홈즈: 'Holmes', 왓슨: 'Watson', 피터슨: 'Peterson' },
    outro: [
      'How did Doyle pull readers into the case with just one old hat?',
      'Which of Holmes’s guesses about the hat’s owner sound reasonable, and which seem forced?',
      'Why are innocent people sometimes suspected first because of past mistakes?',
    ],
    lines: [
      ['해설', 'On the second morning after Christmas, Watson stopped by Baker Street to wish Holmes a happy holiday.'],
      ['해설', 'Holmes, in a purple dressing gown, was studying a battered old hat hanging on the back of a chair.'],
      ['홈즈', 'It is not a crime, Watson. But this hat comes with a small puzzle.'],
      ['홈즈', 'Peterson the commissionaire saw it happen around four on Christmas morning, walking along Tottenham Court Road.'],
      ['홈즈', 'A tall man carrying a goose over his shoulder got into a fight with some street roughs.'],
      ['홈즈', 'Swinging his stick, he broke a shop window. When Peterson ran up in uniform, the man fled in fright.'],
      ['홈즈', 'He left behind this hat and a goose. A card on its leg said, for Mrs. Henry Baker.'],
      ['홈즈', 'There must be hundreds of Henry Bakers in London, so Peterson took the goose home before it spoiled.'],
      ['왓슨', 'So what can you learn from this hat?'],
      ['홈즈', 'A great deal. The owner is intelligent. A head this large must hold a lot.'],
      ['홈즈', 'He was well-off about three years ago, but now times are hard, and he has let himself go.'],
      ['홈즈', 'His wife no longer loves him, it seems. Weeks of dust lie on the hat, and no one has brushed it.'],
      ['홈즈', 'His hair is graying and was recently cut. His house has no gas. There are five candle-wax stains.'],
      ['왓슨', 'You are impossible. And yet every point sounds reasonable.'],
      ['해설', 'Just then the door burst open, and Peterson ran in, his face bright red.'],
      ['피터슨', 'The goose, Mr. Holmes! My wife found this in its crop while cleaning it!'],
      ['해설', 'In his palm lay a brilliant blue stone, a little smaller than a bean.'],
      ['홈즈', 'Good heavens, Peterson! This is the Countess of Morcar’s blue carbuncle.'],
      ['홈즈', 'It was stolen from the Hotel Cosmopolitan five days ago. There is a reward of a thousand pounds.'],
      ['해설', 'According to the paper, a hotel attendant, James Ryder, had taken a plumber, John Horner, to the countess’s room.'],
      ['해설', 'Horner was there to fix the fireplace grate. While Ryder stepped out, the jewel case was emptied.'],
      ['해설', 'Horner had been punished for theft before. He shouted that he was innocent, but he was arrested at once.'],
      ['홈즈', 'Now we must connect the jewel, the goose, and the hat. First, we must find Henry Baker.'],
      ['홈즈', 'Peterson, put an ad in every evening paper. Goose and hat to be claimed at Baker Street, at half past six tonight.'],
      ['홈즈', 'And buy a goose on your way back. We need a goose to give Mr. Baker.'],
      ['해설', 'After Peterson left, Holmes held the stone up to the light.'],
      ['홈즈', 'It came from the banks of the Amoy River in southern China less than twenty years ago. Already it has caused two murders and many thefts.'],
      ['해설', 'Would the hat’s owner come that evening? And was he really the jewel thief?'],
      ['해설', 'The Blue Carbuncle, Holmes’s Christmas story, appeared in The Strand in January 1892.'],
    ],
  },

  'hm2-carbuncle-2': {
    title: 'The Blue Carbuncle, Part 2',
    names: { 해설: 'Narrator', 홈즈: 'Holmes', 왓슨: 'Watson', 베이커: 'Henry Baker', 브레킨리지: 'Breckinridge', 라이더: 'James Ryder' },
    outro: [
      'What meaning did Doyle give this Christmas story by letting the thief go?',
      'What is clever about the way Holmes used Breckinridge’s love of betting?',
      'Which has more power to change a person, punishment or forgiveness?',
    ],
    lines: [
      ['해설', 'Last time, the stolen blue carbuncle turned up in the crop of a Christmas goose.'],
      ['해설', 'At half past six, Henry Baker arrived. He was dignified but wore a worn coat, just as Holmes had guessed.'],
      ['홈즈', 'Mr. Baker, we were afraid your goose would spoil, so we ate it. But we have another one, just as fat.'],
      ['베이커', 'Oh, that will do perfectly. Thank you very much.'],
      ['홈즈', 'We kept the feathers, legs, and crop of your old bird. Would you like them?'],
      ['베이커', 'Ha! What would I do with those? This fine new goose is enough.'],
      ['해설', 'Baker said he got the goose from a goose club at the Alpha Inn, near the British Museum. Then he left.'],
      ['홈즈', 'He knows nothing about the jewel. Watson, let us put off dinner and follow this clue.'],
      ['왓슨', 'Gladly. It is a cold night, but I will button up my coat.'],
      ['해설', 'Under cold, bright stars, they visited the Alpha Inn. Then they found a goose seller in Covent Garden Market.'],
      ['브레킨리지', 'Geese, geese! I am sick of people asking me where those geese came from!'],
      ['홈즈', 'I bet a friend a gold sovereign that the goose was country-bred. I think I’ll win.'],
      ['브레킨리지', 'Then you’ve lost. Look at my book. I got them from Mrs. Oakshott, 117 Brixton Road.'],
      ['해설', 'Holmes tossed him the coin and walked away. Under a lamp, he laughed silently.'],
      ['홈즈', 'When a man carries a racing paper in his pocket, offer him a bet. He would not have talked for money.'],
      ['해설', 'Just then, shouting broke out at the stall. A small, rat-faced man was being driven off for asking about the geese.'],
      ['홈즈', 'Excuse me, but if this is about the geese from Brixton Road, perhaps I can help.'],
      ['해설', 'The man said his name was John Robinson, but soon he turned pale. He was the hotel attendant, James Ryder.'],
      ['해설', 'At Baker Street, Holmes showed him the jewel. Ryder staggered and fell to his knees.'],
      ['라이더', 'I stole it with the maid, Catherine Cusack. I knew Horner would be blamed because of his record.'],
      ['라이더', 'I went to my sister’s, caught a goose with a barred tail, and pushed the stone down its throat.'],
      ['라이더', 'My sister had promised me a goose for Christmas. But there were two geese with barred tails.'],
      ['라이더', 'I took the wrong one. When I went back, the other had already been sold at the market.'],
      ['라이더', 'Please spare me! Think of my father and mother! I will never do it again!'],
      ['홈즈', 'While Mr. Horner sits in prison? But without your evidence, his case will fall apart. Get out!'],
      ['해설', 'Ryder clattered down the stairs, and the front door slammed.'],
      ['홈즈', 'Watson, I am not hired to fill the gaps in police work. That fellow will never do wrong again.'],
      ['홈즈', 'Send him to prison now, and he will be a prisoner for life. Besides, it is the season of forgiveness.'],
      ['해설', 'Holmes rang for dinner. Tonight, too, a bird would be on the table.'],
      ['해설', 'Doyle wrote Holmes stories in all, four novels and fifty-six short stories.'],
    ],
  },

  'hm2-beeches-1': {
    title: 'The Copper Beeches, Part 1',
    names: { 해설: 'Narrator', 홈즈: 'Holmes', 왓슨: 'Watson', 바이올렛: 'Violet Hunter', 루캐슬: 'Mr. Rucastle' },
    outro: [
      'How did Doyle build up the fear hidden behind a job offer that was too good to be true?',
      'What does Violet’s trick of watching the window with a piece of mirror show about her?',
      'What jobs today have strange conditions that people must accept because they badly need money?',
    ],
    lines: [
      ['해설', 'One early spring morning, Holmes was complaining that cases had become dull lately.'],
      ['해설', 'That day’s client was a governess, Violet Hunter, a young woman with rich chestnut hair.'],
      ['바이올렛', 'I went to an agency to find work. A very fat, smiling gentleman seemed delighted the moment he saw me.'],
      ['루캐슬', 'She is the one! Just look after one child of six, and I’ll pay you a hundred pounds a year.'],
      ['바이올렛', 'That was more than twice what I used to get. But the conditions were strange.'],
      ['루캐슬', 'My wife has odd fancies. You must wear the dress we give you and sit where we ask. And cut your hair short.'],
      ['바이올렛', 'I refused to cut my hair. But a few days later, a letter came offering a hundred and twenty pounds.'],
      ['바이올렛', 'I really need the money. Should I take the job?'],
      ['홈즈', 'I would not want my own sister to take it. But if danger comes, send me a telegram, day or night.'],
      ['해설', 'Violet cut her hair and left for the Copper Beeches, a house near Winchester.'],
      ['홈즈', 'Data! Data! Data! I cannot make bricks without clay.'],
      ['해설', 'Two weeks later, a telegram came late at night. It asked them to come to the Black Swan Hotel in Winchester at noon.'],
      ['왓슨', 'Look, Holmes. How peaceful those country houses are.'],
      ['홈즈', 'This lovely countryside frightens me more than London’s back streets. Here, no neighbor can hear a scream.'],
      ['해설', 'At the hotel, Violet poured out everything that had happened.'],
      ['바이올렛', 'His wife is much younger than he is and always looks sad. The boy loves to hurt small animals.'],
      ['바이올렛', 'At night they let a huge, hungry mastiff loose in the yard, so no one can come or go.'],
      ['바이올렛', 'He made me wear a blue dress and sit with my back to the window. Then he told funny stories until I was tired of laughing.'],
      ['바이올렛', 'I hid a piece of mirror in my handkerchief and looked behind me. A man in gray was watching from the road.'],
      ['바이올렛', 'Right away, the master told me to wave the man away.'],
      ['바이올렛', 'I opened a locked drawer and found a coil of chestnut hair, exactly like the hair I cut.'],
      ['바이올렛', 'And my own hair was still in my bag.'],
      ['바이올렛', 'One wing of the house is never used. Its windows are always shuttered.'],
      ['바이올렛', 'Yesterday the key was left in the door, so I went in. Behind a barred door, a shadow moved.'],
      ['루캐슬', 'If you ever cross that threshold again, I’ll throw you to the mastiff.'],
      ['바이올렛', 'He was smiling even as he said it. That frightened me even more.'],
      ['홈즈', 'We will come tonight at seven. We must find out who is behind that door.'],
      ['해설', 'Why did Violet have to cut her hair? And who was locked in that wing?'],
      ['해설', 'The Copper Beeches appeared in The Strand in June 1892. It is the last story in The Adventures of Sherlock Holmes.'],
    ],
  },

  'hm2-beeches-2': {
    title: 'The Copper Beeches, Part 2',
    names: { 해설: 'Narrator', 홈즈: 'Holmes', 왓슨: 'Watson', 바이올렛: 'Violet Hunter', 루캐슬: 'Mr. Rucastle', 톨러부인: 'Mrs. Toller' },
    outro: [
      'What did Doyle want to expose through the story of a father who tried to take his daughter’s money?',
      'Violet was afraid but stayed in that house to the end. What kind of person does this make her seem?',
      'How do people still limit someone’s freedom today in the name of family?',
    ],
    lines: [
      ['해설', 'Last time, the governess Violet told Holmes that someone was locked in the closed wing of the Copper Beeches.'],
      ['홈즈', 'Miss Hunter, you were sitting in that chair in someone else’s place.'],
      ['홈즈', 'The master’s daughter, Alice Rucastle. They said she went to America, but she must be locked in that wing.'],
      ['홈즈', 'You look like her in height and hair color. You had to cut your hair because she cut hers during an illness.'],
      ['홈즈', 'The man on the road must be her fiancé. Seeing you laugh at the window, he was meant to think she had changed her mind.'],
      ['왓슨', 'Is the boy’s cruelty to animals a clue too?'],
      ['홈즈', 'You can see the parents in the child. This family hides cruelty behind smiles.'],
      ['바이올렛', 'I’m frightened, but I can do it. What should I do?'],
      ['해설', 'That night the Rucastles went out. Violet cleverly locked the servant, Mrs. Toller, in the cellar.'],
      ['해설', 'Holmes and Watson went up to the wing and broke down the door. But the room was empty, and the skylight was open.'],
      ['홈즈', 'We are too late. Someone took her away with a ladder.'],
      ['해설', 'Then heavy footsteps sounded on the stairs. It was Rucastle, holding a thick stick.'],
      ['루캐슬', 'You thieves! Where have you taken my daughter? Fine, I’ll teach you a lesson!'],
      ['해설', 'He ran down the stairs. He was going to set the dog loose.'],
      ['홈즈', 'Watson, have your pistol ready!'],
      ['해설', 'But the hungry mastiff did not even know its master. A horrible scream came from the yard.'],
      ['해설', 'The dog had Rucastle by the throat and would not let go. Watson ran over and shot it.'],
      ['해설', 'Rucastle survived, but he was badly hurt and never the same again.'],
      ['해설', 'Freed from the cellar, Mrs. Toller finally told them the whole story.'],
      ['톨러부인', 'Miss Alice had money from her late mother. The master wanted to use it himself.'],
      ['톨러부인', 'When Mr. Fowler proposed, the master pressed her to sign a paper giving him the money even after marriage.'],
      ['톨러부인', 'She had a fever and had to cut her hair, but she never signed. So the master locked her up.'],
      ['톨러부인', 'Mr. Fowler didn’t give up. Tonight he put up a ladder and took her away.'],
      ['해설', 'In that era, women found it hard to protect their own money and lives. Some fathers even took away their daughters’ freedom.'],
      ['해설', 'Alice married Fowler, and her husband took a government post on Mauritius, an island in the Indian Ocean.'],
      ['홈즈', 'Miss Hunter, you were frightened, yet you held on to the end. You were truly brave.'],
      ['해설', 'Violet Hunter later became the head of a private school in Walsall.'],
      ['해설', 'Watson hoped Holmes would care more about her, but once the case was over, so was his interest.'],
      ['해설', 'Conan Doyle was knighted in 1902 and became Sir Arthur Conan Doyle.'],
    ],
  },

  'hm2-dancing-1': {
    title: 'The Dancing Men, Part 1',
    names: { 해설: 'Narrator', 홈즈: 'Holmes', 왓슨: 'Watson', 큐빗: 'Hilton Cubitt' },
    outro: [
      'What did Doyle want to show by turning drawings like children’s doodles into a frightening code?',
      'What principle did Holmes follow when he took the most common figure to be E?',
      'Should a promise never to ask about a loved one’s past always be kept, or are there times to break it?',
    ],
    lines: [
      ['해설', 'Holmes had been doing a chemistry experiment in silence for hours. Suddenly he turned to Watson.'],
      ['홈즈', 'So, Watson, you have decided not to put your money into South African stocks.'],
      ['왓슨', 'What? How did you know that?'],
      ['홈즈', 'There is billiard chalk on your left hand. You played billiards with the friend who suggested those stocks.'],
      ['홈즈', 'Besides, your checkbook is locked in my drawer, and you have not asked me for the key.'],
      ['왓슨', 'Now that you explain it, it seems simple.'],
      ['홈즈', 'It always does. Now, try to tell me what this is.'],
      ['해설', 'On the paper Holmes held out was a row of tiny figures that looked like dancing men.'],
      ['왓슨', 'It looks like a child’s game.'],
      ['해설', 'Soon the man who sent the drawing arrived. He was Hilton Cubitt, from an old family in Norfolk.'],
      ['큐빗', 'Last year in London, I met an American lady, Elsie Patrick, and married her.'],
      ['큐빗', 'Before the wedding she asked me one thing. There was nothing shameful, but I must never ask about her past.'],
      ['큐빗', 'But a month ago, she got a letter from America. She turned white and threw it into the fire.'],
      ['큐빗', 'Soon after, drawings like these began to appear in chalk on our windowsills and doors.'],
      ['큐빗', 'When my wife saw one, she fainted. Since then, she always looks afraid of something.'],
      ['큐빗', 'I promised, so I will not ask her. Instead, Mr. Holmes, please find out for me.'],
      ['홈즈', 'If new drawings appear, copy them exactly and send them to me. Every single one.'],
      ['해설', 'A few days later, Cubitt brought several more. They had been drawn on a tool-house door and on the sundial.'],
      ['큐빗', 'One night I kept watch with a pistol. I saw a shadow in the dark and tried to rush out, but my wife held me back.'],
      ['큐빗', 'And yet the next morning, there was a new drawing on the same door.'],
      ['해설', 'After Cubitt left, Holmes laid out the drawings and studied them late into the night.'],
      ['홈즈', 'Watson, this is a code. Each figure is one letter. A figure holding a flag marks the end of a word.'],
      ['홈즈', 'The most common letter in English is E. So I started by taking the most frequent figure as E.'],
      ['해설', 'Holmes matched the letters one by one. Once the name Elsie appeared, the rest came quickly.'],
      ['홈즈', 'Am here, Abe Slaney. At Elriges. Come, Elsie. And Elsie’s answer was, never.'],
      ['해설', 'Then the last drawing Cubitt had sent arrived. Holmes decoded it and jumped to his feet.'],
      ['홈즈', 'Elsie, prepare to meet thy God. Watson, this is no game anymore. It is a threat of murder!'],
      ['해설', 'But the next train to Norfolk was not until the following morning. Would they be in time?'],
      ['해설', 'The Adventure of the Dancing Men appeared in The Strand in December 1903.'],
    ],
  },

  'hm2-dancing-2': {
    title: 'The Dancing Men, Part 2',
    names: { 해설: 'Narrator', 홈즈: 'Holmes', 왓슨: 'Watson', 마틴: 'Inspector Martin', 슬레이니: 'Abe Slaney' },
    outro: [
      'What did Doyle want to show with a story where Holmes arrives too late to stop the crime?',
      'How did the smell of gunpowder in the hall and the bullet hole in the window frame change the truth of the case?',
      'When someone from the past threatens your life now, what do you need to ask for help instead of facing it alone?',
    ],
    lines: [
      ['해설', 'Last time, Holmes discovered that the dancing men were a murder threat against Elsie.'],
      ['해설', 'The next day at North Walsham station, the stationmaster asked if they were detectives from London.'],
      ['해설', 'The Cubitts had been shot. The husband was dead, and the wife was badly wounded in the head.'],
      ['왓슨', 'Holmes, we are too late.'],
      ['홈즈', 'We could not stop it, so we must at least uncover the truth.'],
      ['해설', 'Inspector Martin of the Norfolk police was at the house. He believed the wife had shot her husband and then herself.'],
      ['마틴', 'One revolver was found in the room. Two shots were fired, and two people were hurt.'],
      ['해설', 'Coming downstairs, the maid and the cook had smelled gunpowder in the hall. They said the window was shut.'],
      ['홈즈', 'If the window was shut, the smell could not spread into the hall. It must have been open at first.'],
      ['해설', 'Holmes examined the window. There was a bullet hole in the lower wooden frame.'],
      ['홈즈', 'A third bullet, Inspector. That means someone else fired a gun.'],
      ['해설', 'There were footprints in the flower bed outside, and an empty cartridge was found in the grass.'],
      ['홈즈', 'Inspector, is there a farm near here owned by someone named Elrige?'],
      ['마틴', 'There is one near East Ruston. But why?'],
      ['해설', 'Holmes drew dancing men on a sheet of paper and had it sent to a guest staying at that farm.'],
      ['홈즈', 'Only Mrs. Cubitt and that man know this code. He will think she sent it, and he will come.'],
      ['홈즈', 'I asked the New York police by telegram. They say Abe Slaney is the most dangerous crook in Chicago.'],
      ['해설', 'Sure enough, a tall, handsome man strode up and knocked. When the door opened, handcuffs snapped onto his wrists.'],
      ['슬레이니', 'Elsie is hurt? I never harmed a hair on her head. I only shot that man.'],
      ['해설', 'Slaney confessed that Elsie was the daughter of a Chicago gang leader, and that she had been engaged to him.'],
      ['해설', 'Elsie hated that world, so she ran away to England and married an honest man.'],
      ['슬레이니', 'At dawn Elsie came to the window and offered me money to leave. I got angry and grabbed her arm.'],
      ['슬레이니', 'Then her husband rushed in with a revolver. We fired almost at the same moment, and his bullet missed.'],
      ['해설', 'When her husband fell, Elsie shot herself with his revolver. That explained the three bullets Holmes had found.'],
      ['슬레이니', 'But who wrote that picture letter? Nobody but Elsie knows that code.'],
      ['홈즈', 'I wrote it. What one man can invent, another can discover.'],
      ['해설', 'Slaney was sentenced to death, but because Cubitt had fired first, his sentence was reduced to prison.'],
      ['해설', 'Elsie survived. She stayed on at her husband’s house and spent her life caring for the poor.'],
      ['해설', 'The Dancing Men was later collected in The Return of Sherlock Holmes, published in 1905.'],
    ],
  },
};
