// 청소년 영어 원고 (중학생 이상). 키 = stories/teen-speech.js 의 이야기 id.
// 연설자 대사는 원문(퍼블릭 도메인)의 짧은 구절을 살리거나 쉬운 영어로 옮긴 요지이며, 원문에 없는 말을 지어내지 않았다.
// 선생님·학생의 대화는 해설용으로 새로 쓴 것이다.
export default {
  'tsp2-pericles': {
    title: 'Pericles’ Funeral Oration',
    names: { 해설: 'Narrator', 페리클레스: 'Pericles', 선생님: 'Teacher', 학생: 'Student' },
    outro: [
      'Why did Pericles praise the Athenian way of life at length at a funeral for fallen soldiers?',
      'What impression does the contrast of loving beauty without luxury and wisdom without weakness give?',
      'Pericles called people who ignore public life useless. How does that idea connect to citizens today?',
    ],
    lines: [
      ['해설', 'In 431 BC, the Peloponnesian War began between Athens and Sparta.'],
      ['해설', 'That winter, Athens held a public funeral for those who died in the first year, as was the custom.'],
      ['해설', 'The man chosen to give the funeral speech was Pericles, the leader of Athens.'],
      ['학생', 'There were no recorders back then. How do we know what he said?'],
      ['선생님', 'The historian Thucydides wrote it down in his History of the Peloponnesian War.'],
      ['선생님', 'He admitted that he did not record it word for word. He kept the general sense.'],
      ['해설', 'What follows is the main idea of Thucydides’ record, in modern words.'],
      ['페리클레스', 'I will not speak long about our ancestors. Today I will speak about the way of life that made us great.'],
      ['페리클레스', 'Our government does not copy our neighbors. Instead, we are an example to others.'],
      ['페리클레스', 'Power is in the hands of the many, not the few. That is why we call it a democracy.'],
      ['페리클레스', 'In private disputes, all are equal before the law. People rise to office by ability, not by family.'],
      ['페리클레스', 'If a poor man can serve the city, his humble position does not block his way.'],
      ['페리클레스', 'In daily life we are tolerant of each other. In public matters we respect the law and our officials.'],
      ['페리클레스', 'Our city is open to the world. We do not drive out foreigners for fear they might spy on us.'],
      ['페리클레스', 'We love beauty without luxury, and we love wisdom without becoming weak.'],
      ['페리클레스', 'It is no shame to admit poverty. The real shame is not trying to escape it.'],
      ['페리클레스', 'We do not call a man who ignores public life quiet. We call him useless.'],
      ['페리클레스', 'In short, our whole city is the school of Greece.'],
      ['학생', 'This is a funeral, but he talks more about Athens than about the dead.'],
      ['선생님', 'That is the strategy. If they died for such a city, their deaths look like a worthy choice.'],
      ['페리클레스', 'These men fought bravely and fell so that they would not lose such a city.'],
      ['페리클레스', 'For famous men, the whole earth is their tomb. Their memory lives in hearts, not on stones.'],
      ['페리클레스', 'Know that happiness depends on freedom, and freedom on courage. Do not shrink from the dangers of war.'],
      ['학생', 'He seems to ask the families for courage more than he comforts them. It feels heavy.'],
      ['선생님', 'Right. And remember that the citizens he praised did not include women, slaves, or foreign residents.'],
      ['해설', 'At the end, Pericles comforted the families and promised that the city would raise the children of the dead.'],
      ['해설', 'The speech had two faces. It painted an ideal community, and it asked citizens to sacrifice for it.'],
      ['해설', 'The next year a plague struck Athens, and Pericles died in 429 BC.'],
    ],
  },

  'tsp2-tilbury': {
    title: 'Queen Elizabeth’s Speech at Tilbury',
    names: { 해설: 'Narrator', 여왕: 'Queen Elizabeth', 선생님: 'Teacher', 학생: 'Student' },
    outro: [
      'What was the key message Elizabeth I wanted to give her soldiers?',
      'What effect did the contrast between a weak woman’s body and a king’s heart have on the soldiers?',
      'Today, what words and actions does a leader need to win people’s trust in a crisis?',
    ],
    lines: [
      ['해설', 'In the summer of 1588, King Philip II of Spain sent a great fleet, the Armada, to invade England.'],
      ['해설', 'England gathered an army at Tilbury, near the mouth of the River Thames, to stop a landing.'],
      ['해설', 'That August, Queen Elizabeth I went to the camp at Tilbury herself and stood before her soldiers.'],
      ['학생', 'The queen went to the army camp herself? Wasn’t that dangerous?'],
      ['선생님', 'The fleet had already been pushed north after a sea battle. But no one in the camp was sure the danger was over.'],
      ['선생님', 'Also, this speech comes to us through a letter by a clergyman, Leonel Sharp, printed only in 1654.'],
      ['학생', 'So we cannot be sure she said those exact words.'],
      ['선생님', 'That’s why it is more accurate to call it a version that has come down to us.'],
      ['해설', 'Here is the main idea of that version, in modern words.'],
      ['여왕', 'My loving people, some have warned me to be careful of treachery when I come before armed crowds.'],
      ['여왕', 'But I do not wish to live distrusting my faithful and loving people.'],
      ['여왕', 'Let tyrants fear. I have always placed my chief strength and safeguard in the loyal hearts of my subjects.'],
      ['여왕', 'I have not come for pleasure. I have come to live or die among you in the heat of the battle.'],
      ['여왕', 'For my God, my kingdom, and my people, I will lay down my honor and blood, even in the dust.'],
      ['여왕', 'I know I have the body of a weak and feeble woman.'],
      ['여왕', 'But I have the heart and stomach of a king, and of a king of England too.'],
      ['여왕', 'If Parma, Spain, or any prince of Europe dares to invade my borders, I scorn it.'],
      ['여왕', 'Rather than let dishonor grow, I myself will take up arms. I will be your general, judge, and rewarder.'],
      ['여왕', 'Your bravery deserves rewards and crowns. On the word of a prince, they will be paid.'],
      ['여왕', 'If you obey, stay united, and fight bravely, we shall soon win a famous victory.'],
      ['학생', 'She admits she has a weak woman’s body first, then turns it around with a king’s heart.'],
      ['선생님', 'She brings out the doubt her listeners might have and answers it first. That blocks the objection early.'],
      ['학생', 'Saying she would not distrust her people also showed she trusted the soldiers. That must have lifted their spirits.'],
      ['선생님', 'And my God, my kingdom, my people repeats the same pattern to create rhythm.'],
      ['해설', 'At that time, female rulers were rare, and many people doubted that a woman could rule.'],
      ['해설', 'Elizabeth did not avoid that prejudice. She named it openly and used it to make her resolve shine.'],
      ['해설', 'The Spanish never landed. On the way home, the scattered fleet lost many ships in storms.'],
      ['해설', 'Elizabeth I took the throne in 1558 and ruled England until 1603.'],
    ],
  },

  'tsp2-henry': {
    title: 'Give Me Liberty or Give Me Death',
    names: { 해설: 'Narrator', 헨리: 'Patrick Henry', 선생님: 'Teacher', 학생: 'Student' },
    outro: [
      'What reasons did Patrick Henry give for arming right away?',
      'What pressure did his string of questions about when we would be stronger put on the audience?',
      'Henry demanded liberty while he owned enslaved people. What does that contradiction make us think about today?',
    ],
    lines: [
      ['해설', 'In the 1770s, conflict grew between Britain and its North American colonies over taxes and self-rule.'],
      ['해설', 'On March 23, 1775, leaders from Virginia met at St. John’s Church in Richmond.'],
      ['해설', 'The question was whether to keep hoping for peace with Britain or to raise a militia.'],
      ['해설', 'Then Patrick Henry stood up and argued for taking up arms.'],
      ['학생', 'Do we still have the text of that speech?'],
      ['선생님', 'No. Nobody wrote it down on the spot.'],
      ['선생님', 'In 1817, William Wirt wrote a biography of Henry and rebuilt the speech from listeners’ memories.'],
      ['해설', 'Here is the main idea of Wirt’s version, in modern words.'],
      ['헨리', 'I respect the patriotism of the gentlemen who spoke before me. But this is no time for ceremony.'],
      ['헨리', 'The question before us is nothing less than freedom or slavery.'],
      ['헨리', 'It is natural for man to indulge in the illusions of hope and shut his eyes to a painful truth.'],
      ['헨리', 'I have but one lamp by which my feet are guided, and that is the lamp of experience.'],
      ['헨리', 'Why are fleets and armies covering our waters and land? Are they not meant to force us to submit?'],
      ['헨리', 'We have petitioned, we have protested, and we have begged. All of it was ignored and scorned.'],
      ['헨리', 'We must give up our empty hopes. We must fight!'],
      ['헨리', 'They tell us we are weak. But when shall we be stronger? Will it be next week, or next year?'],
      ['헨리', 'Will it be when a British guard is placed in every house? Will lying still make us strong?'],
      ['헨리', 'The battle is not to the strong alone. It is to the watchful, the active, and the brave.'],
      ['헨리', 'Men may cry, peace, peace, but there is no peace. The war has already begun.'],
      ['헨리', 'Is life so dear, or peace so sweet, as to be bought at the price of chains and slavery?'],
      ['헨리', 'I know not what course others may take. But as for me, give me liberty or give me death!'],
      ['학생', 'He keeps asking questions, and at the end he makes a sharp declaration.'],
      ['선생님', 'He piles up questions with obvious answers, called rhetorical questions, so listeners reach the conclusion themselves.'],
      ['선생님', 'Repeating petitioned, protested, and begged also makes you feel they had tried everything.'],
      ['학생', 'But I heard that Henry, who demanded liberty, owned enslaved people too.'],
      ['선생님', 'Yes. Asking whose liberty he meant is an important way to read this speech.'],
      ['해설', 'In the end, the meeting voted to raise a militia to defend Virginia.'],
      ['해설', 'Less than a month later, on April 19, 1775, the first battles broke out at Lexington and Concord.'],
    ],
  },

  'tsp2-seneca-falls': {
    title: 'Seneca Falls: Declaration of Sentiments',
    names: { 해설: 'Narrator', 낭독자: 'Reader', 선생님: 'Teacher', 학생: 'Student' },
    outro: [
      'What did the Declaration of Sentiments demand, and why did the right to vote cause the most debate?',
      'What persuasive effect came from borrowing the form and words of the Declaration of Independence?',
      'Are there rights in our society today that are still not equally guaranteed to everyone?',
    ],
    lines: [
      ['해설', 'On July 19 and 20, 1848, a meeting on women’s rights was held in Seneca Falls, New York.'],
      ['해설', 'Elizabeth Cady Stanton, Lucretia Mott, and others organized it.'],
      ['해설', 'The Declaration of Sentiments presented there was mostly drafted by Stanton.'],
      ['학생', 'Sentiments? Was it a paper about feelings?'],
      ['선생님', 'Here, sentiments means beliefs and opinions that people declare in public.'],
      ['선생님', 'The writers deliberately borrowed the form of the 1776 Declaration of Independence.'],
      ['해설', 'Now let us hear the main points of the declaration, in modern words.'],
      ['낭독자', 'We hold these truths to be self-evident, that all men and women are created equal.'],
      ['학생', 'They took the line all men are created equal and added women to it.'],
      ['낭독자', 'The history of mankind is a history of repeated injuries by man toward woman.'],
      ['낭독자', 'Its aim was absolute tyranny over her. To prove this, let facts be submitted to the world.'],
      ['낭독자', 'He has never permitted her to use her inalienable right to vote.'],
      ['낭독자', 'He has forced her to obey laws that she had no voice in making.'],
      ['낭독자', 'If married, she became civilly dead in the eyes of the law. Even the wages she earned were taken.'],
      ['낭독자', 'He has taken almost all the well-paid jobs and closed the doors to a full education.'],
      ['낭독자', 'He has tried in every way to destroy her confidence and make her willing to live a dependent life.'],
      ['낭독자', 'So we demand that women be given at once all the rights and privileges of citizens of this nation.'],
      ['학생', 'Just as the Declaration of Independence listed the wrongs of the British king, this lists the wrongs of men.'],
      ['선생님', 'Exactly. They used a document every American respected, so it was hard to argue against.'],
      ['선생님', 'It asks to apply the same principle to women. It sounds like asking America to keep a promise.'],
      ['해설', 'The meeting discussed many resolutions, and the one on women’s right to vote caused the most debate.'],
      ['해설', 'The abolitionist Frederick Douglass stood up and supported the voting resolution.'],
      ['해설', 'It finally passed, but many people thought it was far too radical.'],
      ['학생', 'It is surprising that the right to vote was seen as the most extreme demand.'],
      ['선생님', 'It took more than seventy years before that demand was written into the Constitution.'],
      ['해설', 'One hundred people signed the declaration: sixty-eight women and thirty-two men.'],
      ['해설', 'American women won the right to vote in 1920 with the Nineteenth Amendment.'],
    ],
  },

  'tsp2-sojourner': {
    title: 'Sojourner Truth: Ain’t I a Woman?',
    names: { 해설: 'Narrator', 소저너: 'Sojourner Truth', 선생님: 'Teacher', 학생: 'Student' },
    outro: [
      'What was Sojourner Truth’s strongest argument for women’s rights?',
      'What effect came from turning her opponents’ Bible stories around and mixing in humor?',
      'Why is it important today to check which version a famous quote comes from?',
    ],
    lines: [
      ['해설', 'Sojourner Truth was born into slavery in New York. In 1826 she walked to freedom with her baby daughter.'],
      ['해설', 'Later she became a traveling speaker against slavery and for women’s rights.'],
      ['해설', 'In May 1851, she spoke at a women’s rights convention in Akron, Ohio.'],
      ['학생', 'Is this the famous speech where she keeps repeating, ain’t I a woman?'],
      ['선생님', 'That’s the problem. The famous version is a memory published by Frances Gage in 1863, twelve years later.'],
      ['선생님', 'The earliest report, printed by Marius Robinson in June 1851, does not have that repeated line.'],
      ['선생님', 'Gage also gave her a Southern accent. But Sojourner grew up in New York, and her first language was Dutch.'],
      ['해설', 'Here we follow Robinson’s 1851 report and give its main idea in modern words.'],
      ['소저너', 'I want to say a few words about this matter. I am for woman’s rights.'],
      ['소저너', 'I have as much muscle as any man, and I can do as much work as any man.'],
      ['소저너', 'I have plowed and reaped and husked and chopped and mowed. Can any man do more than that?'],
      ['소저너', 'I can carry as much as any man, and I can eat as much too, if I can get it.'],
      ['소저너', 'As for intellect, if woman has a pint and man a quart, why can’t she have her little pint full?'],
      ['소저너', 'Don’t be afraid we will take too much. We can’t take more than our pint will hold.'],
      ['학생', 'What are a pint and a quart?'],
      ['선생님', 'Units of volume. One quart is two pints. Even if men had more, that is no reason to deny rights.'],
      ['소저너', 'I can’t read, but I can hear. I have heard in the Bible that Eve caused man to sin.'],
      ['소저너', 'Well, if woman upset the world, give her a chance to set it right side up again.'],
      ['소저너', 'How did Jesus come into the world? Through God, and the woman who bore him. Man, where is your part?'],
      ['소저너', 'Now women are rising up, and a few men are rising up with them.'],
      ['소저너', 'The poor slave is on one side, and woman is on the other. Man is in a tight place.'],
      ['학생', 'She used the Bible stories her opponents used, but turned them around.'],
      ['선생님', 'She seems to accept their reasons, then flips the conclusion. Her humor also eased the tension.'],
      ['선생님', 'She used her own hard work as proof against the idea that women are weak.'],
      ['학생', 'So was the famous repeated line made up?'],
      ['선생님', 'There is no solid evidence that she really said it. Still, the 1863 version moved many people.'],
      ['선생님', 'So when you quote her, it is best to say whose record and which year you are using.'],
      ['해설', 'Sojourner Truth is remembered as a voice for both the end of slavery and women’s rights.'],
      ['해설', 'She chose the name Sojourner Truth herself in 1843. Her birth name was Isabella.'],
    ],
  },

  'tsp2-douglass': {
    title: 'What to the Slave Is the Fourth of July?',
    names: { 해설: 'Narrator', 더글러스: 'Frederick Douglass', 선생님: 'Teacher', 학생: 'Student' },
    outro: [
      'Why did Douglass openly attack slavery at a celebration of independence?',
      'What shock did contrasts like yours and mine, or light and fire, give the audience?',
      'A holiday can be a joy for some and not for others. How could we apply that idea to our society today?',
    ],
    lines: [
      ['해설', 'Frederick Douglass was born into slavery in Maryland and escaped to the North in 1838.'],
      ['해설', 'He became a great speaker and newspaper publisher who led the fight against slavery.'],
      ['해설', 'On July 5, 1852, he gave an Independence Day speech at Corinthian Hall in Rochester, New York.'],
      ['해설', 'The event was organized by the Rochester Ladies’ Anti-Slavery Society.'],
      ['학생', 'Wait, it was the fifth, not the fourth?'],
      ['선생님', 'July 4 that year was a Sunday, so the speech was held the next day.'],
      ['해설', 'The speech was very long, so here are its key parts in modern words.'],
      ['더글러스', 'Fellow citizens, may I ask why I am called upon to speak here today?'],
      ['더글러스', 'What have I, or those I speak for, to do with your national independence?'],
      ['더글러스', 'The founders of this nation were brave men who risked much for freedom. I honor them.'],
      ['더글러스', 'But I do not share the blessings you celebrate. This Fourth of July is yours, not mine.'],
      ['더글러스', 'You may rejoice, but I must mourn.'],
      ['더글러스', 'What, to the American slave, is your Fourth of July?'],
      ['더글러스', 'More than any other day of the year, it shows him the injustice and cruelty he always suffers.'],
      ['더글러스', 'To him, your celebration is a sham, and your boasted liberty is an unholy license.'],
      ['학생', 'The audience must have been shocked to hear this at a celebration.'],
      ['선생님', 'Douglass himself said that what was needed now was scorching irony, not convincing argument.'],
      ['더글러스', 'Must I prove that the slave is a man? Your own laws already admit it.'],
      ['더글러스', 'Laws that punish a slave for crimes admit that he is a responsible human being.'],
      ['더글러스', 'It is not light that is needed, but fire. It is not the gentle shower, but thunder.'],
      ['학생', 'Does he only criticize until the end?'],
      ['선생님', 'No. At the end he says he does not despair of this country. He believes its founding principles will win.'],
      ['해설', 'Douglass did not throw away America’s ideals. He used those very ideals to expose America’s reality.'],
      ['선생님', 'The contrast between you and me, rejoicing and mourning, is the backbone of this speech.'],
      ['선생님', 'He took a day the audience was proud of and turned its meaning upside down.'],
      ['학생', 'So the same day can be a festival for some people and a wound for others.'],
      ['해설', 'Slavery in the United States was abolished in 1865 by the Thirteenth Amendment.'],
    ],
  },

  'tsp2-lincoln-second': {
    title: 'Lincoln’s Second Inaugural Address',
    names: { 해설: 'Narrator', 링컨: 'Abraham Lincoln', 선생님: 'Teacher', 학생: 'Student' },
    outro: [
      'With victory near, why did Lincoln stress healing and humility more than victory?',
      'What effect came from placing both sides side by side, reading the same Bible and praying to the same God?',
      'What could with malice toward none mean for a society with deep conflicts today?',
    ],
    lines: [
      ['해설', 'On March 4, 1865, Abraham Lincoln took the oath of office for the second time at the Capitol in Washington.'],
      ['해설', 'The Civil War had lasted nearly four years, and it was turning in favor of the North.'],
      ['학생', 'They were winning, so it must have been a speech celebrating victory.'],
      ['선생님', 'Just the opposite. In a short speech of about seven hundred words, Lincoln hardly boasted at all.'],
      ['해설', 'Now let us hear its main idea in modern words.'],
      ['링컨', 'There is less reason now for a long speech than there was at my first inauguration.'],
      ['링컨', 'Four years ago, everyone feared a civil war, and everyone tried to avoid it.'],
      ['링컨', 'Both sides opposed war. But one would make war rather than let the nation survive.'],
      ['링컨', 'The other would accept war rather than let the nation die. And the war came.'],
      ['링컨', 'One eighth of the people were slaves, mostly in the South. Somehow, this interest was the cause of the war.'],
      ['링컨', 'Neither side expected the war to be so large or to last so long.'],
      ['링컨', 'Both read the same Bible and pray to the same God, and each asks for help against the other.'],
      ['링컨', 'It seems strange to ask a just God’s help while taking bread from the sweat of other men’s faces.'],
      ['링컨', 'But let us judge not, that we be not judged. The Almighty has His own purposes.'],
      ['학생', 'He criticizes slavery, but he does not attack the South directly.'],
      ['선생님', 'He says clearly that slavery was the cause, but he treats the war as a price both sides pay.'],
      ['링컨', 'If God wills, the war may go on until all the wealth from 250 years of unpaid labor is gone.'],
      ['링컨', 'Every drop of blood drawn with the lash may be paid by another drawn with the sword. Still, God’s judgment is true.'],
      ['링컨', 'With malice toward none, with charity for all, let us stand firm in the right.'],
      ['링컨', 'Let us finish the work, bind up the nation’s wounds, and care for the soldier, his widow, and his orphan.'],
      ['링컨', 'Let us work for a just and lasting peace among ourselves and with all nations.'],
      ['학생', 'In the middle of a war, he says to hold no malice even toward the enemy.'],
      ['선생님', 'He saw that North and South would have to live as one nation again. He put healing before revenge.'],
      ['선생님', 'By placing both sides side by side, he made them share the blame instead of dividing friend and enemy.'],
      ['해설', 'About a month later, on April 9, General Lee of the South surrendered at Appomattox.'],
      ['해설', 'On the night of April 14, Lincoln was shot at Ford’s Theatre, and he died the next day.'],
      ['해설', 'The full text of this speech is carved on a wall of the Lincoln Memorial, along with the Gettysburg Address.'],
    ],
  },

  'tsp2-anthony': {
    title: 'Susan B. Anthony on Woman Suffrage',
    names: { 해설: 'Narrator', 앤서니: 'Susan B. Anthony', 선생님: 'Teacher', 학생: 'Student' },
    outro: [
      'What was the core of Anthony’s argument that her vote was not a crime?',
      'What effect did the question are women persons and her list of family members have?',
      'How does Anthony’s choice to act against a law she thought unjust compare with citizen movements today?',
    ],
    lines: [
      ['해설', 'In November 1872, Susan B. Anthony voted in the presidential election in Rochester, New York.'],
      ['해설', 'Women could not vote then, so she was arrested and charged with illegal voting.'],
      ['해설', 'In 1873, before her trial, Anthony toured nearby towns and explained her case to citizens.'],
      ['학생', 'So she spoke directly to people who might sit on her jury?'],
      ['선생님', 'Yes. So the prosecutor moved the trial to the neighboring Ontario County.'],
      ['해설', 'Let us hear the main idea of her speech in modern words.'],
      ['앤서니', 'Friends and fellow citizens, I stand here charged with voting in the last presidential election without a right to vote.'],
      ['앤서니', 'I will show that I did not commit a crime. I only used a citizen’s right guaranteed by the Constitution.'],
      ['앤서니', 'The Constitution begins with the words, We, the people.'],
      ['앤서니', 'It was we, the people, not we, the white male citizens, nor we, the male citizens, who formed the Union.'],
      ['앤서니', 'The vote is the only way to secure the blessings of liberty. To deny it to women is a mockery.'],
      ['학생', 'She builds her whole argument on the first line of the Constitution.'],
      ['선생님', 'She starts from something nobody can deny, and then builds on it step by step.'],
      ['앤서니', 'An oligarchy of sex is the most hateful aristocracy ever set up on the face of the globe.'],
      ['앤서니', 'It makes father, brothers, husband, and sons the rulers over mother, sisters, wife, and daughters.'],
      ['앤서니', 'Now only one question is left. Are women persons?'],
      ['앤서니', 'I hardly believe any of our opponents would dare to say they are not.'],
      ['앤서니', 'Being persons, women are citizens. No state has the right to make a law that limits a citizen’s privileges.'],
      ['학생', 'The question are women persons is so obvious that it sounds even sharper.'],
      ['선생님', 'It is a rhetorical question with an obvious answer. It shows how unreasonable the other side is.'],
      ['선생님', 'By naming close family members one by one, she turned unfair treatment into a reality inside every home.'],
      ['해설', 'At the trial in June 1873, the judge told the jury to deliver a verdict of guilty.'],
      ['해설', 'Anthony was fined one hundred dollars, but she never paid it.'],
      ['학생', 'So she lost in court after all.'],
      ['선생님', 'But the trial made women’s right to vote a national issue.'],
      ['해설', 'Anthony died in 1906. The Nineteenth Amendment, which gave women the vote, was ratified in 1920.'],
      ['해설', 'It is also called the Anthony Amendment in her honor.'],
    ],
  },

  'tsp2-seattle': {
    title: 'Chief Seattle’s Speech',
    names: { 해설: 'Narrator', 시애틀: 'Chief Seattle', 선생님: 'Teacher', 학생: 'Student' },
    outro: [
      'In Smith’s version, how is Seattle’s idea of land different from that of the people who wanted to buy it?',
      'What feelings do nature images like people as many as grass and scattered trees bring up?',
      'What problems arise in our society when famous quotes spread without anyone checking who really said them?',
    ],
    lines: [
      ['해설', 'Seattle was a leader of the Duwamish and Suquamish peoples around Puget Sound, in today’s Washington State.'],
      ['해설', 'In the 1850s, the U.S. government wanted to buy Native lands there and move the people onto reservations.'],
      ['해설', 'Around 1854, Seattle is said to have given a speech before Governor Isaac Stevens.'],
      ['학생', 'Is this the famous speech about the environment, asking how anyone can buy or sell the sky?'],
      ['선생님', 'Actually, there is little evidence that Seattle said those lines. This speech has a complicated story.'],
      ['선생님', 'Seattle spoke in his own language, Lushootseed, and his words were passed on through interpreters.'],
      ['선생님', 'The speech first appeared in a newspaper in 1887. A doctor, Henry Smith, wrote it from his notes.'],
      ['학생', 'More than thirty years later? Then a lot of Smith’s own words must be mixed in.'],
      ['선생님', 'Yes. And the lines about selling the sky came from a new version written for a film in the early 1970s.'],
      ['해설', 'Here is the main idea of Smith’s 1887 version, in modern words. We cannot be sure Seattle said exactly this.'],
      ['시애틀', 'The sky that has wept tears of pity on my people for centuries may change. Today is fair, tomorrow may be cloudy.'],
      ['시애틀', 'But my words are like the stars that never change.'],
      ['시애틀', 'The great chief in Washington sends word that he wishes to buy our land.'],
      ['시애틀', 'His people are many, like the grass that covers wide prairies. My people are few, like scattered trees on a storm-swept plain.'],
      ['시애틀', 'Your God is not our God. Our religion is the tradition of our ancestors.'],
      ['시애틀', 'The ashes of our ancestors are sacred, and their resting place is holy ground.'],
      ['시애틀', 'Every hill, valley, and forest of this land has been made holy by sad or happy events of long ago.'],
      ['시애틀', 'When the last of my tribe is gone, these shores will still be full of our unseen spirits.'],
      ['시애틀', 'Dead, did I say? There is no death, only a change of worlds.'],
      ['학생', 'There are so many images from nature, like the sky, stars, grass, and trees.'],
      ['선생님', 'Comparing the two peoples to grass and scattered trees seems to calmly accept the difference in power.'],
      ['선생님', 'But he called the land holy with ancestral memory. So it was more than a thing to buy and sell.'],
      ['학생', 'It is a pity that we can hardly know Seattle’s real voice.'],
      ['선생님', 'It is a history of Native voices passed on by other hands. That is why we must name the version we quote.'],
      ['해설', 'In 1855, the tribes of the region signed the Treaty of Point Elliott with Governor Stevens.'],
      ['해설', 'Seattle was one of the Native leaders who signed it.'],
      ['해설', 'The city of Seattle was named after this leader.'],
    ],
  },

  'tsp2-wilson': {
    title: 'Woodrow Wilson’s Fourteen Points',
    names: { 해설: 'Narrator', 윌슨: 'Woodrow Wilson', 선생님: 'Teacher', 학생: 'Student' },
    outro: [
      'What was the core of the new world order Wilson described in the Fourteen Points?',
      'What persuasive effect came from offering a numbered, concrete list instead of an emotional appeal?',
      'A principle of justice for all peoples was applied to only some. What question does that raise about international relations today?',
    ],
    lines: [
      ['해설', 'World War I began in 1914 and took countless lives, mostly in Europe.'],
      ['해설', 'In 1917, the United States declared war on Germany and joined the fighting.'],
      ['해설', 'On January 8, 1918, President Woodrow Wilson explained his peace principles to a joint session of Congress.'],
      ['해설', 'They had fourteen items, so they are called the Fourteen Points.'],
      ['학생', 'The war wasn’t even over, and he was already talking about peace terms?'],
      ['선생님', 'That made it even more meaningful. He wanted to tell the world what they were fighting for.'],
      ['해설', 'Here is the main idea of the speech in modern words.'],
      ['윌슨', 'What we demand in this war is nothing special for ourselves.'],
      ['윌슨', 'It is that the world be made fit and safe to live in, and every peace-loving nation be treated fairly.'],
      ['윌슨', 'First, peace treaties should be made openly. After that, there should be no secret international agreements.'],
      ['윌슨', 'Second, there should be complete freedom of navigation on the seas outside territorial waters, in peace and in war.'],
      ['윌슨', 'Economic barriers between nations should be removed as far as possible. Weapons should be cut to what domestic safety needs.'],
      ['윌슨', 'In settling colonial claims, the interests of the people living there must have equal weight with the ruling government’s claims.'],
      ['학생', 'What about the later points?'],
      ['선생님', 'They deal with borders one by one, like restoring Belgium, Alsace-Lorraine, and an independent Poland.'],
      ['윌슨', 'Finally, a general association of nations must be formed. It should protect the independence and borders of great and small states alike.'],
      ['윌슨', 'Running through all of this is one principle: justice to all peoples and nations, whether strong or weak.'],
      ['학생', 'Numbering them first, second, and so on makes them easy to keep in my head.'],
      ['선생님', 'Instead of appealing to emotion, he gave a concrete list. It made the peace look like a workable plan.'],
      ['선생님', 'The first point, ending secret diplomacy, answered the criticism that secret treaties had helped cause the war.'],
      ['학생', 'Did the phrase self-determination come from here?'],
      ['선생님', 'That word does not actually appear in the Fourteen Points. But the points became a symbol of it.'],
      ['해설', 'The idea raised great hopes among colonized peoples. It also drew attention around Korea’s March First Movement in 1919.'],
      ['해설', 'But at the Paris Peace Conference, self-determination was mostly applied to the defeated powers’ lands, not the winners’ colonies.'],
      ['학생', 'He said all peoples, but in practice it was applied selectively.'],
      ['해설', 'The League of Nations began in 1920, but the U.S. Senate rejected the Treaty of Versailles, so America never joined.'],
      ['해설', 'For proposing the League of Nations, Wilson received the Nobel Peace Prize for 1919.'],
    ],
  },

  'tsp2-gandhi': {
    title: 'Gandhi’s Great Trial',
    names: { 해설: 'Narrator', 간디: 'Mahatma Gandhi', 선생님: 'Teacher', 학생: 'Student' },
    outro: [
      'Why did Gandhi not plead innocent but instead ask for the heaviest penalty?',
      'What effect came from paired phrases like non-cooperation with evil being as much a duty as cooperation with good?',
      'When we face a rule we believe is unjust, how can we stand against it today?',
    ],
    lines: [
      ['해설', 'On March 18, 1922, Mohandas Gandhi stood trial in a courtroom in Ahmedabad, India.'],
      ['해설', 'He was charged with stirring up hatred against the government in articles in his weekly paper, Young India.'],
      ['해설', 'Just before, in February, protesters at Chauri Chaura set fire to a police station, and policemen were killed.'],
      ['해설', 'Gandhi felt responsible for this violence and stopped the nationwide non-cooperation movement.'],
      ['해설', 'People later called this trial the Great Trial.'],
      ['학생', 'Did Gandhi plead not guilty?'],
      ['선생님', 'No, he admitted every charge. Then he explained to the judge how a loyal supporter became a non-cooperator.'],
      ['해설', 'Here is the main idea of his statement in court, in modern words.'],
      ['간디', 'For a long time, I was loyal to the British government and cooperated with it.'],
      ['간디', 'But after the Rowlatt Act and the horrors in the Punjab, I decided I could not cooperate with this government.'],
      ['간디', 'Under British rule, India has become more helpless than ever, politically and economically.'],
      ['간디', 'The law is used to serve the exploiter. Affection cannot be manufactured or regulated by law.'],
      ['간디', 'The section I am charged under is the prince of the political laws made to crush citizens’ liberty.'],
      ['간디', 'I knew that I was playing with fire. I took the risk, and if set free, I would do the same again.'],
      ['간디', 'In my humble opinion, non-cooperation with evil is as much a duty as cooperation with good.'],
      ['간디', 'So I do not ask for mercy. I am here to accept the highest penalty gladly.'],
      ['간디', 'By law it is a deliberate crime. To me, it seems the highest duty of a citizen.'],
      ['간디', 'If you believe this law is good, give me the severest penalty. If you think it is evil, resign your post.'],
      ['학생', 'Instead of asking for a lighter sentence, he asked for the heaviest one.'],
      ['선생님', 'By not avoiding punishment, he made the judge and the world ask whether the law itself was just.'],
      ['선생님', 'Notice the contrasts, too: cooperation and non-cooperation, good and evil, crime and duty.'],
      ['학생', 'It was pretty bold to tell the judge to resign.'],
      ['선생님', 'But his tone stayed polite to the end. He aimed at the unjust system, not at hating people.'],
      ['해설', 'Judge Broomfield respectfully said that Gandhi was in a different category from anyone he had ever tried.'],
      ['해설', 'Still, by law, he sentenced Gandhi to six years in prison, the same sentence the leader Tilak had once received.'],
      ['학생', 'It is impressive that the judge and the accused showed respect to each other.'],
      ['해설', 'After surgery for an illness, Gandhi was released in 1924, before finishing his sentence.'],
    ],
  },

  'tsp2-fdr-first': {
    title: 'FDR’s First Inaugural Address',
    names: { 해설: 'Narrator', 루스벨트: 'Franklin D. Roosevelt', 선생님: 'Teacher', 학생: 'Student' },
    outro: [
      'Why did Roosevelt talk about fear first, in the middle of an economic crisis?',
      'What effect came from comparing the crisis to a war and repeating the call for action now?',
      'When anxiety spreads, what attitude should leaders and citizens each have?',
    ],
    lines: [
      ['해설', 'After the New York stock market crash of 1929, America fell into a deep economic crisis called the Great Depression.'],
      ['해설', 'By early 1933, millions had no jobs, and banks were closing one after another.'],
      ['해설', 'On March 4, 1933, Franklin D. Roosevelt became president.'],
      ['학생', 'March 4? Isn’t the American inauguration in January?'],
      ['선생님', 'Now it is on January 20, but back then it was in March. This was the last one held in March.'],
      ['해설', 'Let us hear the main idea of his inaugural address in modern words.'],
      ['루스벨트', 'This is the time to speak the truth, the whole truth, frankly and boldly.'],
      ['루스벨트', 'This great nation will endure as it has endured. It will revive and will prosper.'],
      ['루스벨트', 'So first, let me state my firm belief that the only thing we have to fear is fear itself.'],
      ['루스벨트', 'I mean nameless, unreasoning, unjustified terror, which freezes the efforts needed to turn retreat into advance.'],
      ['학생', 'It’s a speech about the economy, but he starts with feelings.'],
      ['선생님', 'A bank crisis grows when worried people all take out their money at once. Fear was part of the problem.'],
      ['루스벨트', 'Values have shrunk, taxes have risen, farmers have no markets, and many families have lost their savings.'],
      ['루스벨트', 'But our trouble does not come from a lack of goods. Plenty is at our doorstep.'],
      ['루스벨트', 'The money changers have fled from their high seats in the temple of our civilization.'],
      ['루스벨트', 'Happiness does not lie in simply having money. It lies in the joy of achievement and the thrill of creative effort.'],
      ['루스벨트', 'Our greatest task is to put people to work.'],
      ['루스벨트', 'This nation asks for action, and action now.'],
      ['루스벨트', 'If Congress fails to act, I will ask for broad power to fight the crisis, as if we were invaded.'],
      ['학생', 'A president asking for wartime power sounds a little scary.'],
      ['선생님', 'Good point. He promised to stay within his constitutional duty, but crises can expand power, so we should always watch.'],
      ['선생님', 'In style, the comparison of the crisis to a war drives the whole speech. He tried to unite people like one army.'],
      ['학생', 'Money changers fleeing the temple reminds me of a Bible story.'],
      ['선생님', 'He borrowed the scene of Jesus driving the money changers out of the temple to scold careless bankers.'],
      ['해설', 'Two days later, on March 6, Roosevelt declared a bank holiday that closed the nation’s banks for a short time.'],
      ['해설', 'Then came a series of programs known as the New Deal.'],
      ['해설', 'Roosevelt is the only American president elected four times.'],
    ],
  },
};
