// 청소년 영어 원고 (중학생 이상). 키 = stories/teen-yusa.js 의 이야기 id.
// 『삼국유사』 이야기를 한국어 각색의 흐름대로 쉬운 영어로 새로 씀. 고유 낱말은 로마자로 쓰고 짧게 풀이.
export default {
  'sgy-01': {
    title: 'Seok Talhae, the Boy from the Sea',
    names: { 해설: 'Narrator', 노파: 'Old Woman', 탈해: 'Talhae', 호공: 'Hogong', 관리: 'Official', 남해왕: 'King Namhae' },
    outro: [
      'A stranger from across the sea became king of Silla. What does this story tell us about Silla society?',
      'Talhae secretly buried tools to win a house. Was his plan wisdom or a trick?',
      'What does a society need so that people can get chances no matter where they come from?',
    ],
    lines: [
      ['해설', 'According to legend, in King Namhae’s time, a flock of magpies gathered noisily by Silla’s eastern sea.'],
      ['해설', 'An old woman who lived by fishing looked out and saw a boat floating near the shore.'],
      ['노파', 'There are no rocks here, so why are the magpies gathering? Something strange is happening.'],
      ['해설', 'She pulled the boat in and opened a large chest on it. Inside sat a fine young boy.'],
      ['해설', 'Treasures and servants were with him. The old woman cared for the boy for seven days.'],
      ['탈해', 'I come from Yongseong, a land across the sea. My mother, the queen, gave birth to an egg.'],
      ['탈해', 'People said it was a bad sign. So my father put the egg in a chest and sent it out to sea.'],
      ['해설', 'Thanks to the magpies, he was given the family name Seok. His name, Talhae, meant escaping from the chest and the egg.'],
      ['해설', 'When he grew up, Talhae climbed Mount Toham and looked over the capital for a good place to live.'],
      ['해설', 'He saw a hill shaped like a crescent moon. But a man named Hogong already lived there.'],
      ['해설', 'One night Talhae secretly buried a whetstone and charcoal beside the house. The next morning he knocked on the gate.'],
      ['탈해', 'This house belonged to my ancestors. Please give it back.'],
      ['호공', 'What nonsense! My family has lived here for generations.'],
      ['해설', 'They argued without end, so they went to a government office to settle it.'],
      ['관리', 'Do you have any proof that this was your ancestors’ house?'],
      ['탈해', 'My family were blacksmiths. If you dig in the ground, you will find signs of our workshop.'],
      ['해설', 'The official ordered people to dig, and there were the whetstone and the charcoal. The house became Talhae’s.'],
      ['해설', 'When King Namhae heard this, he saw that Talhae was no ordinary man.'],
      ['남해왕', 'A young man this clever can be trusted with great work for the kingdom.'],
      ['해설', 'The king married his eldest daughter to Talhae and gave him a high post in the government.'],
      ['해설', 'After King Yuri, the next king, passed away, Talhae took the throne.'],
      ['해설', 'The boy in the chest from the sea, a stranger, had become the ruler of a kingdom.'],
      ['해설', 'It is said that the hill he won later became the site of Wolseong, the royal fortress of Silla.'],
      ['해설', 'Seok Talhae was the fourth king of Silla and the first king from the Seok family.'],
    ],
  },

  'sgy-02': {
    title: 'Kim Alji and the Golden Chest',
    names: { 해설: 'Narrator', 호공: 'Hogong', 탈해왕: 'King Talhae', 신하: 'Minister', 왕비: 'Queen' },
    outro: [
      'What image of the Kim royal family do the golden chest and the white rooster create?',
      'Alji gave up the throne, but his descendants later became kings. How can we read this?',
      'Where can we find families or nations telling special stories about their beginnings today?',
    ],
    lines: [
      ['해설', 'According to legend, one autumn night in the reign of King Talhae, Hogong was passing a village west of Wolseong.'],
      ['해설', 'Suddenly he saw a great light shining in the middle of a forest called Sirim.'],
      ['해설', 'A purple cloud hung from the sky down to the ground, touching a branch in the forest.'],
      ['호공', 'What is this light? Is that a golden chest hanging on that branch?'],
      ['해설', 'The light came from the golden chest. Under the tree, a white rooster was crowing.'],
      ['호공', 'Your Majesty, a golden chest that seems to come from heaven is hanging in Sirim forest.'],
      ['탈해왕', 'A white rooster and a purple cloud? This is no ordinary thing. I will go and see it myself.'],
      ['해설', 'The king went to the forest, took the chest down carefully, and opened the lid.'],
      ['해설', 'A baby boy was lying inside. When he saw the people, he sat up.'],
      ['신하', 'Your Majesty, this is just like the story of King Hyeokgeose coming out of an egg.'],
      ['탈해왕', 'Heaven has surely sent us this child. I will take him to the palace and raise him well.'],
      ['해설', 'It is said that birds and animals followed happily as the king carried the child home.'],
      ['왕비', 'What will you name the child?'],
      ['탈해왕', 'In our language, a little child is called alji. That will be his name.'],
      ['탈해왕', 'And since he came from a golden chest, his family name will be Kim, which means gold.'],
      ['해설', 'The king also renamed the forest Gyerim, the rooster forest, because the white rooster had crowed there.'],
      ['해설', 'Later, the name Gyerim was sometimes used for the whole kingdom of Silla.'],
      ['해설', 'Alji grew up wise and clever, and King Talhae made him crown prince.'],
      ['신하', 'The crown prince will be our next king, won’t he?'],
      ['해설', 'But Alji did not want the throne. He gave it up to Pasa and stepped aside.'],
      ['해설', 'Alji never became king, but his family line put down deep roots in Silla.'],
      ['해설', 'Generations later, his descendant Michu became the first king from the Kim family.'],
      ['해설', 'After that, the Kim family held the throne of Silla for a very long time.'],
      ['해설', 'The Gyerim forest in Gyeongju still remains and reminds visitors of this old tale.'],
      ['해설', 'The Kim royal family of Silla and the Gyeongju Kim clan honor Kim Alji as their founder.'],
    ],
  },

  'sgy-03': {
    title: 'King Suro and Queen Heo Hwang-ok',
    names: { 해설: 'Narrator', 목소리: 'Voice', 아도간: 'Adogan', 수로왕: 'King Suro', 허황옥: 'Heo Hwang-ok' },
    outro: [
      'A king from heaven met a queen from across the sea. What does this show about the kingdom of Gaya?',
      'King Suro refused the brides his ministers chose and waited for heaven. What was the purpose of this scene?',
      'To build a community with people from far away, what should we respect in each other?',
    ],
    lines: [
      ['해설', 'Long ago, before there was a kingdom, nine chiefs, including Adogan, ruled the land near the lower Nakdong River.'],
      ['해설', 'According to legend, in the spring of the year 42, a strange voice was heard on a peak called Gujibong.'],
      ['해설', 'Two or three hundred villagers gathered there. They could hear a voice, but they saw no one.'],
      ['목소리', 'Is anyone here?'],
      ['아도간', 'We are here.'],
      ['목소리', 'Heaven has told me to found a kingdom here and be its king. Dig the earth, sing, and dance.'],
      ['해설', 'The people dug the earth and danced, singing a song that told a turtle to show its head.'],
      ['해설', 'This song later came to be called Gujiga, the Song of Guji.'],
      ['해설', 'Soon a purple rope came down from the sky. At its end was a golden box wrapped in red cloth.'],
      ['해설', 'Inside were six golden eggs as round as the sun.'],
      ['해설', 'The next day, six boys came out of the eggs. The first one was named Suro.'],
      ['해설', 'Suro became king and founded Garak. The other five became kings of the other Gaya states.'],
      ['해설', 'Years passed, and the ministers kept asking the king to take a queen.'],
      ['아도간', 'Your Majesty, please choose the best of our daughters as your queen.'],
      ['수로왕', 'I came to this land by heaven’s command. Heaven will also choose my queen.'],
      ['해설', 'In the year 48, a ship with red sails and red flags came from the southwest sea.'],
      ['해설', 'The king sent his ministers to greet it and waited in a tent at the foot of a hill.'],
      ['해설', 'A young woman stepped off the ship. She took off her silk trousers and offered them to the mountain spirit.'],
      ['허황옥', 'I am a princess of Ayuta. My family name is Heo, my name is Hwang-ok, and I am sixteen.'],
      ['허황옥', 'The Lord of Heaven appeared in my parents’ dream. He said the king of Garak had no queen yet.'],
      ['허황옥', 'So they sent me across the long sea road, and here I am.'],
      ['수로왕', 'I believed I had a sacred fate, so I waited for you instead of following my ministers.'],
      ['수로왕', 'Now you have come by yourself. What greater fortune could there be?'],
      ['해설', 'The two married and ruled the kingdom together. The people who came with the queen also settled in Garak.'],
      ['해설', 'It is said that two of their sons took their mother’s family name, Heo.'],
      ['해설', 'A king from the sky and a queen from across the sea. Garak was built on their meeting.'],
      ['해설', 'This story comes down to us through the Garakgukgi, a record copied into the Samguk Yusa.'],
    ],
  },

  'sgy-04': {
    title: 'Manpasikjeok, the Flute of Peace',
    names: { 해설: 'Narrator', 박숙청: 'Park Suk-cheong', 김춘질: 'Kim Chun-jil', 신문왕: 'King Sinmun', 용: 'Dragon', 태자: 'Crown Prince' },
    outro: [
      'The dragon said one hand alone cannot make a sound. What lesson was it trying to teach?',
      'One flute could stop enemies, sickness, drought, and floods. What wishes does this idea reveal?',
      'If something like this flute could bring divided hearts together today, what would it be?',
    ],
    lines: [
      ['해설', 'After King Munmu, who unified the Three Kingdoms, passed away, his son King Sinmun took the throne.'],
      ['해설', 'King Sinmun built Gameunsa, a temple near the East Sea, to honor his father.'],
      ['해설', 'The Samguk Yusa tells that in the fifth month of the next year, an official rushed to the king.'],
      ['박숙청', 'I am Park Suk-cheong, guard of the sea. Your Majesty, a small mountain in the East Sea is floating back and forth toward Gameunsa.'],
      ['해설', 'The king found this strange and asked Kim Chun-jil, the royal fortune teller, to read the signs.'],
      ['김춘질', 'Your late father has become a dragon of the sea, and he is protecting the kingdom.'],
      ['김춘질', 'General Kim Yu-sin has become a god in heaven. Together they wish to give you a great treasure.'],
      ['해설', 'The king happily went to a seaside hill called Igyeondae and looked at the mountain.'],
      ['해설', 'The mountain looked like a turtle’s head, and a single bamboo stood on top.'],
      ['해설', 'Strangely, the bamboo split into two in the daytime and became one at night.'],
      ['해설', 'One day, when the bamboo joined into one, the earth shook, and storms raged for seven days.'],
      ['해설', 'When the wind finally stopped, the king sailed to the mountain.'],
      ['해설', 'A dragon appeared and gave the king a belt made of black jade.'],
      ['신문왕', 'Why does this bamboo sometimes split and sometimes join together?'],
      ['용', 'One hand alone cannot clap. A sound comes only when two hands meet.'],
      ['용', 'This bamboo makes a sound only when it is joined. It is a sign that a wise king will rule through sound.'],
      ['용', 'Cut this bamboo and make a flute. When you play it, the whole land will be at peace.'],
      ['해설', 'The king cut the bamboo and brought it back. Then the mountain and the dragon suddenly vanished.'],
      ['해설', 'The crown prince rode out to meet the king and looked closely at the jade belt.'],
      ['태자', 'Every decoration on this belt is a real dragon. Try putting one in the water.'],
      ['해설', 'They put one piece into a stream. It turned into a dragon at once and flew up into the sky.'],
      ['해설', 'The king made a flute from the bamboo and kept it safely in the royal storehouse.'],
      ['해설', 'It is said that when the flute was played, enemies retreated and the sick got well.'],
      ['해설', 'Rain fell in times of drought, and long rains stopped. The people treasured the flute.'],
      ['해설', 'They called it Manpasikjeok, the flute that calms ten thousand waves.'],
    ],
  },

  'sgy-05': {
    title: 'Seodong and Princess Seonhwa',
    names: { 해설: 'Narrator', 서동: 'Seodong', 아이들: 'Children', 진평왕: 'King Jinpyeong', 선화: 'Seonhwa', 지명법사: 'Monk Jimyeong' },
    outro: [
      'One song changed a princess’s fate. What does Seodongyo show about the power of rumors?',
      'From a boy digging yams to a king, which side of Seodong does the story stress?',
      'How do false rumors hurt people today, and what can we do about it?',
    ],
    lines: [
      ['해설', 'According to legend, a woman lived alone with her son beside a pond south of the Baekje capital.'],
      ['해설', 'The boy dug up yams and sold them to support his mother. People called him Seodong, the yam boy.'],
      ['해설', 'One day Seodong heard that Princess Seonhwa of Silla was the most beautiful woman in the world.'],
      ['서동', 'I want to meet her. But how can I meet a princess of a neighboring kingdom?'],
      ['해설', 'Seodong shaved his head, went to the Silla capital, and gave yams to the local children.'],
      ['해설', 'When the children began to follow him, he taught them a short song.'],
      ['해설', 'The song said that Princess Seonhwa had a secret sweetheart and visited Seodong every night.'],
      ['아이들', 'The yam boy taught us this song. Let’s all sing it together!'],
      ['해설', 'The song spread from street to street, and at last it reached the palace.'],
      ['해설', 'The ministers said the princess had behaved badly. Even the king could no longer protect her.'],
      ['진평왕', 'This rumor has spread through the whole kingdom. I have no choice but to send my daughter away.'],
      ['해설', 'On the day she left, the queen gave her a bag of pure gold for the journey.'],
      ['해설', 'On the road, Seodong suddenly appeared, bowed, and offered to guard her.'],
      ['해설', 'She did not know who he was, but she trusted him. Soon they grew close.'],
      ['선화', 'Your name is Seodong? I never thought that song would come true.'],
      ['해설', 'They went to Baekje together. The princess took out her gold to plan their life.'],
      ['서동', 'What is this? Where I used to dig yams, this stuff is piled up like dirt.'],
      ['선화', 'This is a great treasure. Why don’t we send some to my parents’ palace?'],
      ['해설', 'Seodong gathered a hill of gold and asked Monk Jimyeong how to send it.'],
      ['지명법사', 'I will send it with my special power. Bring me the gold and a letter from the princess.'],
      ['해설', 'In a single night, the monk moved the gold to the Silla palace.'],
      ['해설', 'King Jinpyeong was amazed and came to respect Seodong. He often sent letters to ask after him.'],
      ['해설', 'Seodong won the people’s hearts and finally became king of Baekje. He was King Mu.'],
      ['선화', 'It is my wish to build a great temple on this spot.'],
      ['해설', 'The king filled in a pond and built a great temple there. It is said to be Mireuksa in Iksan.'],
      ['해설', 'However, a record found at Mireuksa in 2009 says its builder was a queen from a Baekje noble family.'],
      ['해설', 'Seodongyo, the Song of Seodong, is a hyangga, an old Korean poem kept in the Samguk Yusa.'],
    ],
  },

  'sgy-06': {
    title: 'Cheoyong’s Song and Dance',
    names: { 해설: 'Narrator', 헌강왕: 'King Heongang', 일관: 'Fortune Teller', 처용: 'Cheoyong', 역신: 'Plague Spirit' },
    outro: [
      'Cheoyong answered with a song and a dance instead of anger. What kind of strength is that?',
      'People hung Cheoyong’s face on their gates to keep evil away. How did this custom change the story?',
      'When you feel angry or treated unfairly, what is your own way to calm your feelings?',
    ],
    lines: [
      ['해설', 'In King Heongang’s time, houses stretched from the Silla capital to the sea, and songs filled the streets.'],
      ['해설', 'According to legend, the king went on a trip to Gaeunpo by the East Sea and rested by the water.'],
      ['해설', 'Suddenly thick clouds and fog covered everything. No one could see the way.'],
      ['헌강왕', 'We are lost in broad daylight. What is happening?'],
      ['일관', 'This is the work of the Dragon of the East Sea. You must do a good deed to please him.'],
      ['헌강왕', 'Then I order a temple to be built near here for the dragon.'],
      ['해설', 'The moment he spoke, the clouds and fog cleared away. So the place was named Gaeunpo, the harbor where clouds opened.'],
      ['해설', 'The happy dragon appeared with his seven sons. They danced and sang to praise the king.'],
      ['해설', 'One of the sons followed the king to the capital to help with the kingdom’s work. His name was Cheoyong.'],
      ['해설', 'Hoping he would stay, the king gave him a beautiful wife and a government post.'],
      ['해설', 'But a plague spirit, who spread sickness among people, wanted Cheoyong’s wife.'],
      ['해설', 'One night, while Cheoyong was away, the spirit took a human form and slipped into his wife’s room.'],
      ['해설', 'Cheoyong came home late and saw a stranger in the room.'],
      ['해설', 'But he did not shout or draw his sword. Quietly, he began to sing and dance.'],
      ['해설', 'His song said, I played under the bright moon of the capital, but what was mine has been taken. What can I do?'],
      ['해설', 'When the song ended, Cheoyong danced his way out of the gate.'],
      ['해설', 'Then the spirit showed its true form and knelt before him.'],
      ['역신', 'I wanted your wife and did a terrible wrong.'],
      ['역신', 'But you did not get angry. Your kindness moves me so much that I cannot raise my head.'],
      ['역신', 'I swear that I will never enter any gate that has your picture on it.'],
      ['처용', 'Do not forget that promise. Now leave this house.'],
      ['해설', 'When this story spread, people began to hang pictures of Cheoyong’s face on their gates.'],
      ['해설', 'They hoped to drive away evil and welcome good fortune.'],
      ['헌강왕', 'The dragon kept his word, so I must keep mine.'],
      ['해설', 'Back in the capital, the king built a temple on a sunny slope of a mountain. It was called Manghaesa.'],
      ['해설', 'Cheoyong’s dance later became Cheoyongmu, a court dance performed for a long time.'],
      ['해설', 'Cheoyongga, the Song of Cheoyong, is a hyangga kept in the Samguk Yusa.'],
    ],
  },

  'sgy-07': {
    title: 'The Dream of Josin',
    names: { 해설: 'Narrator', 조신: 'Josin', 김씨: 'Lady Kim' },
    outro: [
      'Josin lived a whole life in one dream. What did he realize when he woke up?',
      'The story sets forty years in a dream against one short nap. What effect does this have on readers?',
      'Have you ever felt disappointed after getting something you wanted very much?',
    ],
    lines: [
      ['해설', 'Long ago, a Silla temple sent a monk named Josin to manage its farmland in the Myeongju region.'],
      ['해설', 'There Josin saw the daughter of Kim Heun, the local governor, and fell in love with her.'],
      ['해설', 'He went to Naksansa many times and secretly prayed to the Bodhisattva of Mercy to let him live with her.'],
      ['해설', 'But within a few years, she married another man.'],
      ['해설', 'Josin sat in front of the hall and blamed the Bodhisattva. He cried until the sun went down.'],
      ['해설', 'Tired, he fell asleep. In his dream, Lady Kim opened the door and came in with a bright smile.'],
      ['김씨', 'I have loved you for a long time. My parents made me marry another man, but I came to you.'],
      ['해설', 'Josin was overjoyed. He went back to his hometown with her and started a family.'],
      ['해설', 'They lived together for forty years and had five children. But they never had enough.'],
      ['해설', 'They could barely make even a thin vegetable porridge, so the family wandered from town to town, begging for food.'],
      ['해설', 'After ten years of wandering, their clothes were so torn they could hardly cover themselves.'],
      ['해설', 'While crossing a mountain pass, their fifteen-year-old son died of hunger.'],
      ['해설', 'Josin and his wife wept bitterly and buried him beside the road.'],
      ['해설', 'They built a straw hut by a road, but the couple grew old and sick and could hardly stand.'],
      ['해설', 'Their ten-year-old daughter went begging and came home crying after a village dog bit her.'],
      ['김씨', 'When we first met, I was young and pretty. We shared every bit of food and every piece of clothing.'],
      ['김씨', 'But now we are sick, and our hunger gets worse every day. We are only a burden to each other.'],
      ['김씨', 'It is not right to part in hard times. Still, I think it is better for us to separate.'],
      ['조신', 'You are right. Let’s each take two of the four children and find our own way.'],
      ['해설', 'Just as they let go of each other’s hands, Josin woke up.'],
      ['해설', 'The lamp in the hall was flickering, and the night was deep. Forty years had passed in less than one night.'],
      ['해설', 'In the morning, Josin’s hair and beard had turned completely white.'],
      ['조신', 'I feel as if I lived a whole life of pain in one night. My worldly desires have melted away like ice.'],
      ['해설', 'Josin went to the pass where he had buried his son in the dream. When he dug there, he found a stone Buddha.'],
      ['해설', 'He placed the statue in a nearby temple. Then he gave up his work and built a new temple.'],
      ['해설', 'It is said that he spent the rest of his life doing only good deeds.'],
      ['해설', 'Josin’s story was later retold by the writer Yi Kwang-su in his novel, Kkum, which means The Dream.'],
    ],
  },

  'sgy-08': {
    title: 'The King with Donkey Ears',
    names: { 해설: 'Narrator', 헌안왕: 'King Heonan', 응렴: 'Eungnyeom', 복두장: 'Hat Maker', 대숲: 'Bamboo Forest' },
    outro: [
      'This story says secrets always come out. What message does it give to people with power?',
      'Cutting the bamboo only changed the sound. It did not stop it. How can we read this ending?',
      'When we carry a secret we cannot tell, how can we take care of our hearts?',
    ],
    lines: [
      ['해설', 'In the time of King Heonan of Silla, an eighteen-year-old hwarang named Eungnyeom was invited to a royal feast.'],
      ['해설', 'The hwarang were young elite warriors of Silla who traveled and trained together.'],
      ['헌안왕', 'You have traveled to many places. What was the most remarkable thing you saw?'],
      ['응렴', 'I saw three people with good character.'],
      ['응렴', 'One came from a high family but was humble. Another was rich but lived simply.'],
      ['응렴', 'The third was noble and powerful, but he never showed off his power.'],
      ['해설', 'The king was moved to tears. He made Eungnyeom his son-in-law and later gave him the throne.'],
      ['해설', 'This man became King Gyeongmun of Silla.'],
      ['해설', 'According to the Samguk Yusa, after he became king, his ears suddenly began to grow long.'],
      ['해설', 'They grew bigger and bigger until they looked like a donkey’s ears.'],
      ['해설', 'The king told no one. Not even the queen or the court ladies knew.'],
      ['해설', 'Only one man knew the secret. He was the craftsman who made the king’s hats.'],
      ['해설', 'The hat maker never told anyone. If he did, his life would be in danger.'],
      ['복두장', 'Keeping this inside me is so hard that I can barely breathe.'],
      ['해설', 'Years later, old and sick, the hat maker went into an empty bamboo forest behind Dorimsa Temple.'],
      ['해설', 'He shouted the words he had held back for so long.'],
      ['복두장', 'The king has donkey ears!'],
      ['해설', 'He walked out of the forest looking relieved. Not long after, he passed away.'],
      ['해설', 'But after that, whenever the wind blew, a strange sound came from the bamboo forest.'],
      ['대숲', 'The king has donkey ears. The king has donkey ears.'],
      ['해설', 'The rumor spread quickly and reached the king. He was very displeased.'],
      ['해설', 'The king had all the bamboo cut down and planted cornelian cherry trees instead.'],
      ['해설', 'But when the wind blew, a sound came from the new trees too.'],
      ['대숲', 'The king has long ears. The king has long ears.'],
      ['해설', 'The sound became a little softer, but it never went away.'],
      ['해설', 'It is also said that snakes gathered in the king’s room every evening, but he slept beside them without fear.'],
      ['해설', 'This story teaches that the harder we hide the truth, the more it slips out another way.'],
      ['해설', 'King Gyeongmun was the forty-eighth king of Silla.'],
    ],
  },

  'sgy-09': {
    title: 'The Three Prophecies of Queen Seondeok',
    names: { 해설: 'Narrator', 선덕왕: 'Queen Seondeok', 신하: 'Minister', 알천: 'Alcheon' },
    outro: [
      'What abilities and qualities of Queen Seondeok do these three prophecies try to highlight?',
      'What role does the scene play when the ministers ask how she knew?',
      'Reading big changes from small clues is a useful skill. What kind of work needs it today?',
    ],
    lines: [
      ['해설', 'Queen Seondeok, the daughter of King Jinpyeong, was the first woman to rule Silla.'],
      ['해설', 'According to the Samguk Yusa, she foresaw three things during her sixteen years on the throne.'],
      ['해설', 'The first began with a gift from Tang China.'],
      ['해설', 'Emperor Taizong of Tang sent a painting of red, purple, and white peonies, along with peony seeds.'],
      ['선덕왕', 'These flowers look beautiful, but they will surely have no scent.'],
      ['신하', 'How can you know their scent just by looking at a painting?'],
      ['해설', 'She had the seeds planted. The flowers bloomed and faded, and indeed they had no scent.'],
      ['해설', 'The second thing happened one winter.'],
      ['해설', 'At a pond of Yeongmyosa Temple called Okmunji, frogs croaked loudly for days in the middle of winter.'],
      ['해설', 'People found it strange. The queen quickly called for two generals, Alcheon and Piltan.'],
      ['선덕왕', 'Take two thousand of your best soldiers to the western edge of the capital. There is a valley called Yeogeungok.'],
      ['선덕왕', 'Enemy soldiers are hiding there. Surround them quietly and capture them.'],
      ['해설', 'When the generals arrived, five hundred Baekje soldiers were indeed hiding in the valley.'],
      ['해설', 'The Silla army defeated them all and also drove back the Baekje troops that followed.'],
      ['알천', 'The enemy was exactly where you said. I am amazed at how you knew.'],
      ['해설', 'The third thing happened while the queen was still healthy.'],
      ['선덕왕', 'I will die on a certain day of a certain month and year. Bury me in the middle of Doricheon.'],
      ['신하', 'Doricheon? Where do you mean, Your Majesty?'],
      ['선덕왕', 'The south side of Mount Nang.'],
      ['해설', 'She died on that very day, and the ministers buried her south of Mount Nang.'],
      ['해설', 'Later, under King Munmu, a temple called Sacheonwangsa was built below her tomb.'],
      ['해설', 'Buddhist scripture says Doricheon is a heaven above the heaven of the Four Guardian Kings. Only then did people understand.'],
      ['해설', 'While she was alive, the ministers had asked how she knew the first two things.'],
      ['선덕왕', 'The painting had flowers but no butterflies. So I knew the flowers had no scent.'],
      ['선덕왕', 'Angry frogs look like soldiers. And the name Okmun matches the name of that western valley.'],
      ['해설', 'All the ministers admired her deep wisdom.'],
      ['해설', 'This story is called Jigisamsa, the three things the queen knew in advance.'],
      ['해설', 'It is a tale from the Samguk Yusa, told to praise the queen’s wisdom.'],
    ],
  },

  'sgy-10': {
    title: 'King Munmu and the Dragon Rock',
    names: { 해설: 'Narrator', 문무왕: 'King Munmu', 지의법사: 'Monk Jiui', 신문왕: 'King Sinmun', 신하: 'Minister' },
    outro: [
      'King Munmu wished to become a dragon to guard the kingdom. What worries of his time does this show?',
      'He chose the sea instead of a grand tomb. What does this choice show about him?',
      'If there is something you want to leave behind after you are gone, what is it?',
    ],
    lines: [
      ['해설', 'As crown prince, King Munmu helped his father, King Muyeol, defeat Baekje. As king, he defeated Goguryeo.'],
      ['해설', 'Then he drove out the Tang army that wanted the peninsula, and the long war finally ended.'],
      ['해설', 'But he always worried that Japanese soldiers might attack the eastern coast.'],
      ['해설', 'Even after the war, he avoided luxury and tried to lighten the people’s burden.'],
      ['해설', 'One day, while talking with Monk Jiui, the king shared a thought he had kept for a long time.'],
      ['문무왕', 'After I die, I want to become a great dragon, follow the Buddha’s teaching, and protect this kingdom.'],
      ['지의법사', 'A dragon is born as an animal. Why would you want such a path?'],
      ['문무왕', 'I grew tired of worldly glory long ago.'],
      ['문무왕', 'Even if I am born as an animal, I will be content if I can protect the kingdom.'],
      ['해설', 'Years later, the king fell seriously ill. He called his ministers and gave his last wishes.'],
      ['문무왕', 'When I die, do not build me a grand tomb. It would waste the people’s strength.'],
      ['문무왕', 'Cremate me and bury me in the East Sea. I will become a dragon and stop enemies from the sea.'],
      ['신하', 'Your Majesty, why do you wish to rest in the sea instead of on land?'],
      ['문무왕', 'I protected the kingdom while I lived. I want to protect it after death, too.'],
      ['해설', 'When the king died, the ministers held his funeral by the East Sea as he wished.'],
      ['해설', 'According to the records, he was laid to rest on a large rock in the sea. People called it Daewangam, the Great King Rock.'],
      ['해설', 'King Munmu had begun building a temple near the East Sea, but he could not finish it.'],
      ['해설', 'His son, King Sinmun, completed it and named it Gameunsa, the temple of gratitude.'],
      ['신문왕', 'Make a path so that my father can come and go from the sea as a dragon.'],
      ['해설', 'So a hole facing east was made under the main hall’s stone floor. The dragon could pass through it.'],
      ['해설', 'King Sinmun also chose a hill where he could look out over the sea where his father rested.'],
      ['해설', 'It was called Igyeondae, the hill where the dragon was seen.'],
      ['해설', 'It is said that King Sinmun later received the flute Manpasikjeok from his dragon father in this sea.'],
      ['해설', 'King Munmu’s dream was to protect a kingdom where people could live in peace after the war.'],
      ['해설', 'Daewangam off the coast of Gyeongju is called King Munmu’s tomb. Scholars disagree on whether his remains were really placed there.'],
      ['해설', 'At the site of Gameunsa in Gyeongju, two three-story stone pagodas stand side by side.'],
    ],
  },

  'sgy-11': {
    title: 'Wonhyo and Uisang',
    names: { 해설: 'Narrator', 원효: 'Wonhyo', 의상: 'Uisang', 공주: 'Princess Yoseok', 여인: 'Woman', 파랑새: 'Bluebird' },
    outro: [
      'The two left on the same road but spread Buddhism in different ways. What do their lives show?',
      'Wonhyo did not recognize the Bodhisattva of Mercy. How can we read that scene?',
      'Even when a friend takes a different path, what attitude do we need to respect each other?',
    ],
    lines: [
      ['해설', 'Wonhyo and Uisang, two monks of Silla, set out together for Tang China to study Buddhism more deeply.'],
      ['해설', 'But Wonhyo turned back on the way, and Uisang crossed the sea alone.'],
      ['해설', 'There is a famous tale of Wonhyo gaining insight beside a grave. It comes from a Chinese book of monks’ lives.'],
      ['원효', 'The truth is not far away. It is inside the mind. I will find my way in this land.'],
      ['의상', 'I will cross the sea and find a teacher. Let us meet again, each on his own path.'],
      ['해설', 'In Tang, Uisang studied the Hwaeom teachings under the master Zhiyan.'],
      ['해설', 'When he heard that Tang planned to attack Silla, he hurried home to warn the kingdom.'],
      ['해설', 'Meanwhile, Wonhyo surprised people with his unusual behavior in Silla.'],
      ['해설', 'He walked the streets singing, Who will lend me an axe without a handle? I will cut a pillar to hold up the sky.'],
      ['해설', 'No one understood, but King Muyeol guessed that Wonhyo wanted a noble wife and a wise son.'],
      ['해설', 'The king sent him to Princess Yoseok, a widow. On the way, Wonhyo fell into a stream on purpose.'],
      ['해설', 'He stayed at her palace to dry his clothes, and later the princess gave birth to a son, Seol Chong.'],
      ['공주', 'I hope this child grows up to be a great scholar of the kingdom.'],
      ['해설', 'After that, Wonhyo took off his monk’s robes and called himself a simple lay Buddhist.'],
      ['해설', 'He carried a large gourd and beat it like a drum as he traveled from village to village.'],
      ['해설', 'Thanks to his singing and dancing, even poor people and children learned the name of the Buddha.'],
      ['해설', 'According to the Samguk Yusa, Uisang built Naksansa where he met the Bodhisattva of Mercy in a seaside cave.'],
      ['해설', 'Later, Wonhyo also set out to meet the Bodhisattva there.'],
      ['해설', 'On the way, he jokingly asked a woman in white harvesting rice for some rice. She joked back.'],
      ['여인', 'The rice did not ripen well this year.'],
      ['해설', 'Further on, he asked a woman washing clothes in a stream for water. She gave him her washing water.'],
      ['해설', 'Wonhyo poured it out and drank from the stream. Then a bluebird sang from a pine tree.'],
      ['파랑새', 'Stop it, monk.'],
      ['해설', 'The bird vanished, and only one shoe was left under the pine. Then Wonhyo realized the women were the Bodhisattva.'],
      ['해설', 'He tried to enter the cave to meet her, but the rough waves stopped him, and he turned back.'],
      ['의상', 'You walk the streets, and I stay in mountain temples. Our paths differ, but our goal is the same.'],
      ['해설', 'Wonhyo wrote many books that spread Buddhism widely. Uisang trained students who carried on the Hwaeom teachings.'],
      ['해설', 'Buseoksa Temple in Yeongju was founded by Uisang.'],
    ],
  },

  'sgy-12': {
    title: 'Kim Hyeon and the Tiger Maiden',
    names: { 해설: 'Narrator', 김현: 'Kim Hyeon', 처녀: 'Maiden', 노파: 'Old Woman', 하늘: 'Heaven', 원성왕: 'King Wonseong' },
    outro: [
      'The maiden offered to take the punishment for her brothers. What value does her choice show?',
      'This story crosses the line between humans and tigers. What did the monk Iryeon want to stress?',
      'What does giving something up for others look like in our lives today?',
    ],
    lines: [
      ['해설', 'Every early spring, Silla people walked around the pagoda of Heungnyunsa Temple to pray for blessings.'],
      ['해설', 'The Samguk Yusa tells that under King Wonseong, a young man named Kim Hyeon circled the pagoda at night.'],
      ['해설', 'A maiden followed behind him, chanting prayers. Their eyes met, and their hearts were drawn together.'],
      ['해설', 'When she started to go home, Kim Hyeon followed. She tried hard to stop him.'],
      ['처녀', 'If you come to my house, something bad will happen. Please go back now.'],
      ['해설', 'Still he followed her to a small hut at the foot of a western hill. An old woman was inside.'],
      ['노파', 'Who is this with you? It is good news, but your brothers will be back soon. I am worried.'],
      ['해설', 'The old woman and the maiden quickly hid Kim Hyeon in a corner.'],
      ['해설', 'Soon three tigers came in, growling. They sniffed and said they smelled a human.'],
      ['노파', 'What is wrong with your noses? What nonsense are you talking?'],
      ['해설', 'Then a loud voice thundered from the sky.'],
      ['하늘', 'You have taken too many lives. I will kill one of you to punish your crimes.'],
      ['해설', 'The three tigers shook with fear. Then the maiden stepped forward.'],
      ['처녀', 'If my brothers go far away and regret their wrongs, I will take the punishment instead.'],
      ['해설', 'The tigers ran off happily. The maiden went back to Kim Hyeon.'],
      ['처녀', 'I will not hide it anymore. I am not a human but a tiger. That is why I told you not to come.'],
      ['처녀', 'Tomorrow I will attack people in the market. The king will offer a high post to whoever catches me.'],
      ['처녀', 'Then follow me to the forest north of the city. If I must be punished, I want it to be by your hand.'],
      ['김현', 'How could I sell the life of the one I love for a government post? I cannot do it.'],
      ['처녀', 'This is heaven’s will and my own wish. It will bring you joy and bring my family good fortune.'],
      ['처녀', 'The people I hurt will heal if they put sauce from Heungnyunsa on their wounds and hear its conch horn.'],
      ['해설', 'The next day, a tiger really burst into the city and hurt people. No one dared to stop it.'],
      ['원성왕', 'I will give a high post to anyone who catches that tiger.'],
      ['해설', 'Kim Hyeon took his sword into the northern forest. The tiger turned back into the maiden and greeted him.'],
      ['해설', 'She took his sword and ended her own life. Where she fell, a tiger lay on the ground.'],
      ['해설', 'The injured people did as she had said, and they all recovered. Kim Hyeon received his post.'],
      ['해설', 'To honor her, Kim Hyeon built a temple called Howonsa by a stream and prayed for her soul.'],
      ['해설', 'The title Kim Hyeon Gamho means Kim Hyeon moved a tiger’s heart.'],
    ],
  },
};
