// 청소년 영어 원고: 제인 에어 1~10화 (stories/teen-eyre.js). 문장은 자체 각색.
// lines 의 첫 칸은 한국어 이야기 cast 의 이름 그대로.
export default {
  'je-01': {
    title: 'Jane Eyre, Part 1',
    names: { 해설: 'Narrator', 제인: 'Jane Eyre', 존리드: 'John Reed', 리드부인: 'Mrs. Reed', 로이드: 'Mr. Lloyd', 베시: 'Bessie' },
    outro: [
      'Besides the dark, where did Jane’s fear in the red-room come from?',
      'What do Jane’s words to her cousin tell us about the kind of girl she is?',
      'What should adults do for a child who is always blamed at home?',
    ],
    lines: [
      ['해설', 'One winter afternoon, cold rain kept falling outside Gateshead Hall.'],
      ['해설', 'Ten-year-old Jane Eyre hid behind a window curtain and opened a picture book of birds.'],
      ['해설', 'Jane had lost her parents as a baby and lived in the house of her aunt, Mrs. Reed.'],
      ['해설', 'Her uncle took her in, and before he died, he asked his wife to look after her.'],
      ['해설', 'But to Mrs. Reed and her three children, Jane was always an unwanted burden.'],
      ['존리드', 'What are you doing back there? That book is ours. You live on our money.'],
      ['해설', 'Her fourteen-year-old cousin John threw the book. Jane hit her head on the door and bled.'],
      ['제인', 'You are a cruel bully! I will not just stand here and take it anymore!'],
      ['해설', 'When the two children fought, Mrs. Reed rushed in. Only Jane was punished.'],
      ['리드부인', 'Lock her in the red-room. Do not let her out until she is sorry.'],
      ['해설', 'The red-room was where Mr. Reed had died. Nobody used it.'],
      ['해설', 'Between red curtains and a cold mirror, Jane watched the sun go down alone.'],
      ['제인', 'Why am I always the one who is scolded? No one in this house cares for me.'],
      ['해설', 'In the dark, a ray of light passed over the wall. Jane thought her uncle’s ghost had come.'],
      ['제인', 'Please open the door! I can’t breathe in here!'],
      ['리드부인', 'Your tricks will not work. Stay there another hour.'],
      ['해설', 'When the door was locked again, Jane fainted and fell to the floor.'],
      ['해설', 'She woke up in the nursery bed. The apothecary, Mr. Lloyd, sat beside her.'],
      ['로이드', 'Tell me what happened, child. Is it hard for you to live in this house?'],
      ['제인', 'I have relatives, but they do not like me. The red-room was really frightening.'],
      ['로이드', 'Would you like to go to school? Living with other children may help you.'],
      ['제인', 'School? Yes, I want to go. Anywhere is fine, as long as it is not here.'],
      ['해설', 'Only Bessie, a maid, was sometimes kind to Jane and sang songs to her.'],
      ['베시', 'Miss Jane, don’t be so afraid. Just try to be a little sweeter to them.'],
      ['해설', 'That night, Jane overheard the maids talking and learned about her parents.'],
      ['해설', 'Her father was a poor clergyman. He and her mother died of a fever when Jane was a baby.'],
      ['해설', 'After hearing Mr. Lloyd, Mrs. Reed began to plan to send Jane far away.'],
      ['해설', 'Some time later, a stern man dressed in black came to Gateshead.'],
      ['해설', 'Charlotte Brontë published Jane Eyre in 1847.'],
    ],
  },

  'je-02': {
    title: 'Jane Eyre, Part 2',
    names: { 해설: 'Narrator', 제인: 'Jane Eyre', 브로클허스트: 'Mr. Brocklehurst', 리드부인: 'Mrs. Reed', 템플: 'Miss Temple', 헬렌: 'Helen Burns' },
    outro: [
      'Why couldn’t Jane easily accept Helen’s way of choosing forgiveness over hate?',
      'How is the scene where Jane first stands up to her aunt a turning point in the story?',
      'If a school only tells children to put up with hunger and cold, what is wrong?',
    ],
    lines: [
      ['해설', 'Last time, Jane fainted after being locked in the red-room, and a way to school opened up.'],
      ['해설', 'Jane was called to the sitting room. A tall man in black stood before her.'],
      ['해설', 'It was Mr. Brocklehurst, a clergyman who ran Lowood School.'],
      ['브로클허스트', 'So you are the child. Do you live in a way that pleases God?'],
      ['리드부인', 'This child tells lies. Please tell the teachers to watch her closely.'],
      ['브로클허스트', 'Do not worry. At Lowood, we first teach girls to be humble and to endure.'],
      ['해설', 'When he left, Jane stood straight in front of her aunt for the first time.'],
      ['제인', 'I am not a liar. You are the one who hides the truth.'],
      ['제인', 'If anyone asks me, I will tell them exactly how you treated me.'],
      ['해설', 'Mrs. Reed left the room with a stiff face. Jane felt she had won, but her heart felt cold.'],
      ['해설', 'In January, Jane rode alone in a coach all day and arrived at Lowood.'],
      ['해설', 'Lowood was a charity school that taught girls from poor families.'],
      ['해설', 'The morning porridge was burnt and impossible to eat. The classroom was cold enough to numb their hands.'],
      ['템플', 'No one could eat this morning. Please give everyone bread and cheese.'],
      ['해설', 'The head of the school, Miss Temple, truly cared about the students.'],
      ['해설', 'At break time, Jane spoke to a girl who was reading a book in a corner of the yard.'],
      ['제인', 'Is that book interesting? Have you been at this school long?'],
      ['헬렌', 'Quite a while. I’m Helen Burns. This place isn’t so bad.'],
      ['해설', 'The next day in class, Helen was whipped with a bundle of twigs because her nails were dirty.'],
      ['해설', 'That morning, the washing water had been frozen. Helen made no excuse and shed no tears.'],
      ['제인', 'If it were me, I would grab that rod and break it. Why do you just endure it?'],
      ['헬렌', 'Paying back hate with hate never ends. For me, forgiving is easier.'],
      ['헬렌', 'And it is true that I am not very tidy.'],
      ['해설', 'Jane did not understand everything Helen said, but she was drawn to her calm.'],
      ['해설', 'In those days, people thought it was a virtue for poor children to endure hunger and cold.'],
      ['해설', 'Lowood shows how lightly the charity schools of that time treated children’s pain.'],
      ['해설', 'A few weeks later, news came that Mr. Brocklehurst was coming to visit the school.'],
      ['해설', 'When the novel first came out, its author was given as Currer Bell, a pen name.'],
    ],
  },

  'je-03': {
    title: 'Jane Eyre, Part 3',
    names: { 해설: 'Narrator', 제인: 'Jane Eyre', 브로클허스트: 'Mr. Brocklehurst', 헬렌: 'Helen Burns', 템플: 'Miss Temple' },
    outro: [
      'Jane was called a liar in front of everyone. What helped her stand up again?',
      'Helen’s death is told simply and briefly. What feeling does that leave with the reader?',
      'Have I ever been given great strength by a friend’s small smile?',
    ],
    lines: [
      ['해설', 'Last time, Jane entered Lowood School and became friends with Helen Burns.'],
      ['해설', 'When Mr. Brocklehurst came into the classroom, Jane was so startled that she dropped her slate.'],
      ['브로클허스트', 'Put that girl on the stool. Everyone, look at her carefully.'],
      ['브로클허스트', 'This girl is a liar. No one is to speak to her. Keep away from her.'],
      ['해설', 'Jane had to stand on the stool for a long time while everyone stared.'],
      ['해설', 'Then Helen walked past and quietly smiled at Jane.'],
      ['해설', 'Because of that one smile, Jane was able to hold on without falling.'],
      ['제인', 'Now everyone will think I am a liar. I wish I could disappear.'],
      ['헬렌', 'People’s opinions change quickly. If your heart is clear, that is enough.'],
      ['템플', 'Jane, tell me your story calmly from the beginning. Add nothing and leave nothing out.'],
      ['해설', 'Miss Temple wrote to Mr. Lloyd and found that Jane had told the truth.'],
      ['템플', 'Everyone, the charge against Jane Eyre was not true.'],
      ['해설', 'From that day, Jane threw herself into her studies, learning drawing and French.'],
      ['해설', 'In spring, a fever spread through the school in the damp valley. Many girls fell sick.'],
      ['해설', 'Helen was not ill with the fever. She lay apart, sick with a lung disease she had long had.'],
      ['해설', 'One night, Jane secretly went to Helen’s room and stood by her bed.'],
      ['헬렌', 'Jane, your feet are bare. Come in and get under the blanket. You came to say goodbye.'],
      ['제인', 'Helen, where are you going? Don’t be sick. Stay with me.'],
      ['헬렌', 'I am not afraid at all. I believe I am going to a good place.'],
      ['해설', 'The two fell asleep holding each other. At dawn, Helen did not wake up.'],
      ['해설', 'When the fever became known, the school’s conditions came to light, and the way it was run changed.'],
      ['해설', 'Jane spent eight more years at Lowood, six as a student and two as a teacher.'],
      ['해설', 'When Miss Temple married and left, Jane wanted to see a wider world.'],
      ['제인', 'If freedom is too much to ask, at least let me find new work in a new place.'],
      ['해설', 'Jane placed an advertisement in the newspaper, looking for a job as a governess.'],
      ['해설', 'Soon, an answer came from a Mrs. Fairfax of a house called Thornfield.'],
      ['해설', 'Eighteen-year-old Jane carried a single trunk to a house she had never seen.'],
      ['해설', 'Charlotte Brontë’s two older sisters, Maria and Elizabeth, died of illness in 1825.'],
    ],
  },

  'je-04': {
    title: 'Jane Eyre, Part 4',
    names: { 해설: 'Narrator', 제인: 'Jane Eyre', 페어팩스: 'Mrs. Fairfax', 아델: 'Adèle', 로체스터: 'Mr. Rochester' },
    outro: [
      'What mystery does the laughter on the third floor plant in the story?',
      'What does Jane’s way of helping Rochester after his fall show about her character?',
      'Have you ever grown close to someone who seemed rude at first? What changed things?',
    ],
    lines: [
      ['해설', 'Last time, Jane said goodbye to Helen and left Lowood to become a governess.'],
      ['해설', 'At Thornfield Hall, Jane was welcomed by a kind old lady, Mrs. Fairfax.'],
      ['페어팩스', 'You must be cold after such a long trip. Come and warm yourself by the fire.'],
      ['해설', 'Jane thought Mrs. Fairfax owned the house. But she was the housekeeper.'],
      ['페어팩스', 'The master of this house is Mr. Rochester. He is hardly ever at home.'],
      ['해설', 'Jane’s pupil was Adèle, a French girl in Mr. Rochester’s care.'],
      ['아델', 'Teacher, can you speak French? I will sing you a song, too!'],
      ['해설', 'One day, Mrs. Fairfax showed Jane the third floor at the top of the house.'],
      ['해설', 'As they walked down a narrow hall, a low, strange laugh came from somewhere.'],
      ['제인', 'What was that sound? Who laughed?'],
      ['페어팩스', 'It must be Grace Poole, a servant. She sits and sews up on the third floor.'],
      ['해설', 'Jane decided to believe her. But she still heard the laugh from time to time.'],
      ['해설', 'About three months later, one January afternoon, Jane walked to a nearby village to mail a letter.'],
      ['해설', 'On the path at dusk, a big dog ran past, followed by the sound of hooves.'],
      ['해설', 'The horse slipped on the ice, and the rider fell onto the road.'],
      ['제인', 'Are you hurt? Shall I go and get someone?'],
      ['로체스터', 'Just stand aside. I have only sprained my ankle.'],
      ['해설', 'He tried to stand and groaned. Jane did not back away and helped him onto his horse.'],
      ['로체스터', 'Where are you coming from, alone at this late hour?'],
      ['제인', 'From Thornfield down there. I am the governess.'],
      ['해설', 'Without a word, he looked at her once and rode away.'],
      ['해설', 'When Jane got home, the same dog was lying on the rug by the fire.'],
      ['페어팩스', 'The master has come back. He fell from his horse and hurt his ankle.'],
      ['해설', 'The next evening, Mr. Rochester called Jane in and asked her all sorts of questions.'],
      ['로체스터', 'Was it you who made my horse fall? I thought you had bewitched him.'],
      ['제인', 'I was only passing by. The ice was to blame.'],
      ['해설', 'He looked through Jane’s drawings, gruffly, but for a long time.'],
      ['해설', 'The long talks between the gruff master and the bold governess were about to begin.'],
      ['해설', 'Charlotte Brontë herself worked as a governess when she was young.'],
    ],
  },

  'je-05': {
    title: 'Jane Eyre, Part 5',
    names: { 해설: 'Narrator', 제인: 'Jane Eyre', 로체스터: 'Mr. Rochester', 아델: 'Adèle', 페어팩스: 'Mrs. Fairfax' },
    outro: [
      'What was Jane trying to tell herself by drawing the two portraits side by side?',
      'Jane answered honestly when asked if he was handsome. How does that change their relationship?',
      'Have you ever held back your feelings because of money or social rank? How did it feel?',
    ],
    lines: [
      ['해설', 'Last time, Jane came to Thornfield and met its master, Rochester, on an icy road.'],
      ['해설', 'Every evening, Mr. Rochester called Jane in to talk.'],
      ['로체스터', 'Do you think me handsome? Tell me honestly.'],
      ['제인', 'No, sir.'],
      ['로체스터', 'Ha! You don’t know how to flatter. I like that.'],
      ['해설', 'He told her about the mistakes and regrets of his youth, and how Adèle came to him.'],
      ['해설', 'Adèle’s mother was a French dancer he once loved. She left her daughter behind.'],
      ['아델', 'Teacher, he gave me a present box! May I open it now?'],
      ['해설', 'In her moody, gruff master, Jane began to see the face of a lonely man.'],
      ['해설', 'Late one night, Jane woke to a low laugh outside her door.'],
      ['제인', 'Who is it? Is anyone there?'],
      ['해설', 'There was no answer. In the hall, she saw smoke coming from Mr. Rochester’s room.'],
      ['해설', 'The curtains of his bed were on fire, and he was fast asleep.'],
      ['해설', 'Jane threw the water from the basin and jug onto the bed and put out the fire.'],
      ['로체스터', 'Is there a flood? Jane, what on earth is going on?'],
      ['제인', 'There was a fire. I think someone set fire to this room.'],
      ['해설', 'He took a candle up to the third floor and came back with a hard face.'],
      ['로체스터', 'It was Grace Poole. Do not tell anyone about this.'],
      ['로체스터', 'You have saved my life. I do not know how to repay you.'],
      ['해설', 'He held her hand for a long time. Jane could not fall asleep again that night.'],
      ['해설', 'The next day, Grace Poole was sewing new curtains as if nothing had happened.'],
      ['해설', 'Early that morning, Mr. Rochester had left for a house far away.'],
      ['페어팩스', 'Miss Ingram will be there too. She is the most beautiful lady around here.'],
      ['해설', 'Jane scolded herself. What was a poor governess doing with such dreams?'],
      ['해설', 'She drew herself plainly and Miss Ingram beautifully, as she imagined her. Then she placed them side by side.'],
      ['제인', 'Every time I see these two pictures, I must come to my senses.'],
      ['해설', 'About two weeks later, news came that Mr. Rochester was returning with guests.'],
      ['해설', 'The novel’s subtitle is An Autobiography. The grown-up Jane looks back on her life.'],
    ],
  },

  'je-06': {
    title: 'Jane Eyre, Part 6',
    names: { 해설: 'Narrator', 제인: 'Jane Eyre', 블랑슈: 'Blanche Ingram', 점쟁이: 'Fortune-teller', 로체스터: 'Mr. Rochester', 메이슨: 'Mr. Mason' },
    outro: [
      'Was it fair for Rochester to dress up as a fortune-teller to test people’s hearts?',
      'If we put Blanche’s words next to Jane’s silence, how do the two characters differ?',
      'How does looking down on people for their job or rank still appear today?',
    ],
    lines: [
      ['해설', 'Last time, Jane put out a fire in Rochester’s room, and he went away.'],
      ['해설', 'Thornfield was crowded with fine guests. Blanche Ingram stood out the most.'],
      ['해설', 'Jane sat quietly by a window in a corner of the drawing room and watched them.'],
      ['블랑슈', 'Governesses? We had many at our house. They were all ridiculous.'],
      ['해설', 'Back then, the upper class often looked down on governesses as if they were servants.'],
      ['해설', 'Jane felt that Blanche wanted Mr. Rochester’s money more than the man himself.'],
      ['해설', 'One day, an old woman who called herself a wandering fortune-teller came to read the guests’ fortunes.'],
      ['점쟁이', 'You, young lady in the corner, come here too. I will read your palm.'],
      ['점쟁이', 'You act cold and alone, but happiness is very close to you.'],
      ['해설', 'The voice sounded familiar. When Jane looked straight at her, the old woman took off her hood.'],
      ['로체스터', 'It is me, Jane. I wanted to find out what my guests really thought.'],
      ['제인', 'That was an unfair trick. Still, I did not say anything foolish.'],
      ['해설', 'Jane told him a stranger had arrived. It was Mason, from the West Indies.'],
      ['해설', 'When he heard that name, the color drained from Mr. Rochester’s face.'],
      ['로체스터', 'Jane, let me lean on your shoulder for a moment. My legs feel weak.'],
      ['로체스터', 'If everyone blamed me and left me, what would you do?'],
      ['제인', 'I would stay, if there was anything I could do to help.'],
      ['해설', 'That night, a sharp scream from the third floor woke the whole house.'],
      ['로체스터', 'A servant just had a nightmare. Everyone, please go back to bed.'],
      ['해설', 'Mr. Rochester secretly called Jane and took her to a room on the third floor.'],
      ['해설', 'There sat Mason, leaning back, his arm and shoulder badly hurt.'],
      ['로체스터', 'I will bring a doctor. Clean his wounds while I am gone, but do not talk to each other.'],
      ['해설', 'Sounds came now and then from behind an inner door. Jane stayed by Mason all night.'],
      ['해설', 'Near dawn, the doctor came and bandaged him. Mason struggled to speak.'],
      ['메이슨', 'She did not know me. I only wanted to see her face.'],
      ['해설', 'Mason left by carriage before sunrise. Jane did not ask who was in that room.'],
      ['해설', 'A few days later, a visitor came from Gateshead to Thornfield, asking for Jane.'],
      ['해설', 'In the same year, 1847, Charlotte’s sisters Emily and Anne also published their first novels.'],
    ],
  },

  'je-07': {
    title: 'Jane Eyre, Part 7',
    names: { 해설: 'Narrator', 로버트: 'Robert Leaven', 제인: 'Jane Eyre', 리드부인: 'Mrs. Reed', 로체스터: 'Mr. Rochester' },
    outro: [
      'Why couldn’t Mrs. Reed accept Jane even at the very end?',
      'On the night of the proposal, lightning split the chestnut tree. What does that suggest?',
      'What does it really look like to treat each other as equals, even with different means?',
    ],
    lines: [
      ['해설', 'Last time, Mason came to Thornfield and left at night, wounded.'],
      ['해설', 'Robert, the coachman from Gateshead, came to see Jane. He was Bessie’s husband.'],
      ['로버트', 'Master John has died. The shock made the mistress fall ill.'],
      ['로버트', 'The mistress keeps asking for you, miss. Could you come?'],
      ['해설', 'With Mr. Rochester’s permission, Jane went back to Gateshead after many years.'],
      ['해설', 'Even on her sickbed, Mrs. Reed was cold to Jane. Jane quietly stayed by her side.'],
      ['리드부인', 'Open the drawer. There is a letter there. It was sent to you.'],
      ['해설', 'It was a letter from three years before, from Jane’s uncle, John Eyre, who lived in Madeira.'],
      ['해설', 'He had no children, and he wanted to adopt Jane and leave her his fortune.'],
      ['리드부인', 'I wrote back that you had died of fever at Lowood.'],
      ['리드부인', 'I could not bear to see you do well. My husband loved you more than my own children.'],
      ['제인', 'Aunt, it is all in the past now. I forgive you.'],
      ['해설', 'Mrs. Reed never took Jane’s hand. She died that night.'],
      ['해설', 'After the funeral, Jane said goodbye to her two cousins and set off.'],
      ['해설', 'On the way back to Thornfield, Jane realized she thought of it as home.'],
      ['해설', 'One midsummer evening, Mr. Rochester called Jane under the great chestnut tree in the orchard.'],
      ['로체스터', 'I am getting married soon. I have found you a job in Ireland.'],
      ['제인', 'Do you think that because I am a poor governess, I have no feelings?'],
      ['제인', 'Before God, we are equal. I speak to you as your equal.'],
      ['로체스터', 'The one I want to marry is not Miss Ingram. It is you, Jane.'],
      ['해설', 'Jane studied his face for a long time. When she saw he meant it, she nodded.'],
      ['제인', 'Yes, I will marry you.'],
      ['해설', 'That night, a fierce storm blew. Lightning struck the chestnut tree and split it in two.'],
      ['해설', 'Soon after, Jane wrote to her uncle in Madeira to tell him about her marriage.'],
      ['해설', 'The wedding day was set. The split chestnut tree stood black in the orchard.'],
      ['로체스터', 'Jane, now no one can come between us.'],
      ['해설', 'But on the night before the wedding, a strange shadow came into Jane’s room.'],
      ['해설', 'The second edition of Jane Eyre was dedicated to the novelist William Thackeray.'],
    ],
  },

  'je-08': {
    title: 'Jane Eyre, Part 8',
    names: { 해설: 'Narrator', 제인: 'Jane Eyre', 로체스터: 'Mr. Rochester', 목사: 'Clergyman', 브릭스: 'Mr. Briggs', 메이슨: 'Mr. Mason' },
    outro: [
      'Jane left the man she loved. What value mattered most in her choice?',
      'The novel never gives Bertha a single word to say. What problem does that leave?',
      'How does our society treat people with mental illness and their families today?',
    ],
    lines: [
      ['해설', 'Last time, Mrs. Reed gave Jane the hidden letter, and Rochester asked Jane to marry him.'],
      ['해설', 'Before the wedding, Mr. Rochester wanted to give Jane silk dresses and jewels.'],
      ['제인', 'I am not a doll. I want to marry you as the Jane I am now.'],
      ['해설', 'On the night before the wedding, Jane woke to candlelight. A strange woman stood in her room.'],
      ['해설', 'The woman tried on Jane’s veil, then tore it in two and threw it on the floor.'],
      ['해설', 'Jane fainted. In the morning, only the torn veil was left.'],
      ['로체스터', 'It must have been half a dream. Perhaps Grace Poole came in. Let us forget it today.'],
      ['해설', 'The next morning, the two stood at the altar of a small church with no guests.'],
      ['목사', 'If anyone knows a reason this marriage cannot take place, let him speak now.'],
      ['브릭스', 'This marriage cannot go on. Mr. Rochester has a wife who is still alive.'],
      ['해설', 'It was Briggs, a lawyer from London. Beside him stood Mason.'],
      ['메이슨', 'Fifteen years ago in Jamaica, this man married my sister, Bertha.'],
      ['해설', 'Mr. Rochester was silent for a while. Then he led them all back to Thornfield.'],
      ['로체스터', 'I will show you what I have hidden. Then you may judge me.'],
      ['해설', 'In an inner room on the third floor, a woman lived in the care of Grace Poole.'],
      ['해설', 'She was Bertha Mason. For many years, she had suffered from a serious mental illness.'],
      ['해설', 'The novel shows Bertha only as a frightening figure who never speaks.'],
      ['해설', 'This reflects the prejudice of that time, when people feared mental illness and locked patients away.'],
      ['해설', 'Seen today, she was a person who needed treatment and respect.'],
      ['해설', 'Jane’s uncle in Madeira had received her letter and told Mason, whom he knew.'],
      ['해설', 'The uncle was too ill to come, so he sent the lawyer instead.'],
      ['로체스터', 'Our families arranged that marriage for money. I have been trapped by this secret for years.'],
      ['로체스터', 'Jane, let us go far away together. I do not care what people think.'],
      ['제인', 'I love you. But that would not be right. I must keep my own self-respect.'],
      ['해설', 'Before dawn, Jane secretly left Thornfield with only a small bundle.'],
      ['해설', 'She got on the first coach she met on the road. She did not ask where it was going.'],
      ['해설', 'With only a few coins in her pocket, Jane faced the unknown moors.'],
      ['해설', 'In 1966, Jean Rhys published a novel that retold Bertha’s life from her side.'],
    ],
  },

  'je-09': {
    title: 'Jane Eyre, Part 9',
    names: { 해설: 'Narrator', 제인: 'Jane Eyre', 한나: 'Hannah', 세인트존: 'St. John Rivers', 다이애나: 'Diana Rivers', 메리: 'Mary Rivers' },
    outro: [
      'Why did Jane decide not to keep the great fortune for herself, but to divide it into four?',
      'How do the scene of being turned away at the door and the scene of finding cousins match?',
      'Is there someone who feels like family to me, even without being related by blood?',
    ],
    lines: [
      ['해설', 'Last time, Jane learned the truth at her wedding and left Thornfield alone.'],
      ['해설', 'Two days later, the coach let Jane off at Whitcross, a crossroads on the moors.'],
      ['해설', 'In her hurry, she had left her bundle in the coach. Now she had nothing at all.'],
      ['해설', 'Jane slept under the bushes and went around the village asking for work and bread.'],
      ['해설', 'After days of wandering, on a rainy night, she followed a light and knocked on a lonely house.'],
      ['한나', 'We have nothing for beggars. It is getting dark, so go away.'],
      ['해설', 'When the door closed, Jane sank down on the doorstep. She had no strength left to walk.'],
      ['세인트존', 'What are you doing here? Hannah, let her in. We cannot leave her like this.'],
      ['해설', 'It was a young clergyman coming home, St. John Rivers. The house was called Moor House.'],
      ['해설', 'His sisters, Diana and Mary, changed Jane’s wet clothes and put her warmly to bed.'],
      ['다이애나', 'Eat slowly. You have gone hungry for a long time, so eat a little at a time.'],
      ['제인', 'Thank you. My name is Jane Elliott. Please do not ask me anything more.'],
      ['메리', 'All right. Tell us when you are ready. Just rest well here.'],
      ['해설', 'The sisters and Jane soon became friends. They read books and studied German together.'],
      ['해설', 'St. John asked Jane to run a small girls’ school in the nearby village of Morton.'],
      ['세인트존', 'It is only a humble country school. But I believe you will do it well.'],
      ['해설', 'Jane taught farm girls and lived on her own in a small cottage.'],
      ['해설', 'Every night she thought of Rochester, but she tried to keep to her decision.'],
      ['해설', 'One day, St. John saw a name written on the corner of Jane’s drawing paper.'],
      ['세인트존', 'Your real name is Jane Eyre, isn’t it? A lawyer is looking for you.'],
      ['세인트존', 'Your uncle in Madeira, Mr. John Eyre, has died. He left you twenty thousand pounds.'],
      ['해설', 'Even more surprising news followed. John Eyre was also the Rivers’ uncle on their mother’s side.'],
      ['제인', 'Then we are cousins? Do I have a family too?'],
      ['해설', 'Jane was overjoyed. She said they should split the money equally among the four of them.'],
      ['세인트존', 'By law, the money is all yours. There is no need to share it.'],
      ['제인', 'Brothers and sisters are worth more than money. Five thousand pounds each is plenty.'],
      ['해설', 'That winter, a warm Christmas came to Moor House, with all four together.'],
      ['해설', 'But in St. John’s quiet eyes, there was another plan for Jane.'],
      ['해설', 'The Brontë sisters grew up in the parsonage at Haworth, where their father Patrick was a clergyman.'],
    ],
  },

  'je-10': {
    title: 'Jane Eyre, Part 10',
    names: { 해설: 'Narrator', 세인트존: 'St. John Rivers', 제인: 'Jane Eyre', 로체스터: 'Mr. Rochester', 여관주인: 'Innkeeper' },
    outro: [
      'How is Jane’s choice to refuse St. John and go back connected to the Jane of Part 1?',
      'What does the voice heard from far away show about the bond between the two?',
      'When the path others choose for me differs from my own, what will guide my choice?',
    ],
    lines: [
      ['해설', 'Last time, Jane learned the Rivers were her cousins and shared her fortune with them.'],
      ['세인트존', 'I am going to India as a missionary. Jane, come with me as my wife.'],
      ['제인', 'You do not love me. You only see me as a partner for your work.'],
      ['세인트존', 'Love is not needed. I need you for the work that heaven has given me.'],
      ['해설', 'Before St. John’s strong will, Jane almost said yes.'],
      ['해설', 'His mission to enlighten faraway lands carried the Europe-centered view of that time.'],
      ['해설', 'At that very moment, a voice from somewhere called Jane’s name.'],
      ['로체스터', 'Jane! Jane! Jane!'],
      ['제인', 'Where are you? I am coming!'],
      ['해설', 'The next day, Jane left for Thornfield. But only blackened walls were left there.'],
      ['여관주인', 'There was a big fire last autumn. The lady on the third floor started it in the middle of the night.'],
      ['여관주인', 'The master sent all the servants out and went up to the roof to save her.'],
      ['여관주인', 'But she fell from the roof and died.'],
      ['해설', 'So ended the life of Bertha Mason. She never found her own voice.'],
      ['여관주인', 'The master was caught under the falling stairs. He lost a hand and his sight.'],
      ['해설', 'Rochester was living at Ferndean, a lonely house in the woods, with two old servants.'],
      ['해설', 'Jane took a glass of water from a servant and carried it into his room.'],
      ['로체스터', 'Who is it? This voice, this hand… Is it Jane? If this is a dream, let me not wake.'],
      ['제인', 'It is me. I have my own money now, and I need no one’s permission.'],
      ['제인', 'If you want me, I will be your eyes and your hands.'],
      ['로체스터', 'Even though I am hurt like this?'],
      ['제인', 'You are not ruined. You are only a little hurt.'],
      ['로체스터', 'A few nights ago, I called your name three times. And I heard an answer.'],
      ['해설', 'The two were married quietly. Only the clergyman and the clerk were there.'],
      ['해설', 'Two years later, Rochester regained some sight in one eye and saw his first son’s face.'],
      ['해설', 'St. John went to India and followed his own path there to the end.'],
      ['해설', 'The girl once locked in the red-room found her place in a life she chose for herself.'],
      ['해설', 'Charlotte Brontë died in 1855, at the age of thirty-eight.'],
    ],
  },
};
