// 청소년 영어 원고 (중학생 이상). 키 = stories/teen-speech2.js 의 이야기 id.
// 연설자·문서의 대사는 원문(퍼블릭 도메인)의 짧은 구절을 살리거나 쉬운 영어로 옮긴 요지이며, 원문에 없는 말을 지어내지 않았다.
// 안창호·주시경의 말은 한국어 원고처럼 전해지는 짧은 구절만 소개했다. 선생님·학생의 대화는 해설용으로 새로 쓴 것이다.
export default {
  'sp2-declaration': {
    title: 'The Declaration of Independence',
    names: { 해설: 'Narrator', 낭독: 'Reader', 선생님: 'Teacher', 학생: 'Student' },
    outro: [
      'Why did the Declaration state human rights before listing the British king’s wrongs?',
      'How did the phrase self-evident truths make it hard for readers to argue back?',
      'The men who wrote that all men are created equal owned enslaved people. What does that contradiction make us think about?',
    ],
    lines: [
      ['해설', 'In the summer of 1776, delegates from thirteen North American colonies gathered in Philadelphia.'],
      ['해설', 'The war with Britain had already gone on for more than a year.'],
      ['해설', 'On July 2, the Continental Congress voted for independence. On July 4, it adopted a declaration explaining why.'],
      ['학생', 'Who wrote the Declaration?'],
      ['선생님', 'A committee of five was in charge, but thirty-three-year-old Thomas Jefferson wrote the draft almost alone.'],
      ['선생님', 'John Adams and Benjamin Franklin made changes, and Congress revised many more parts.'],
      ['해설', 'Now let us hear its key passages in modern words.'],
      ['낭독', 'When one people breaks the political bands that tie it to another, it should explain the causes to the world.'],
      ['낭독', 'We hold these truths to be self-evident, that all men are created equal.'],
      ['낭독', 'They have rights no one can take away, among them life, liberty, and the pursuit of happiness.'],
      ['낭독', 'Governments are set up to protect these rights. Their just powers come from the consent of the governed.'],
      ['낭독', 'When any government destroys these ends, the people may change or abolish it and form a new one.'],
      ['학생', 'Power comes from the people’s consent? The king must have been shocked.'],
      ['선생님', 'It turned upside down the idea that kings get their power from heaven. You can see thinkers like John Locke here.'],
      ['낭독', 'We know that long-established governments should not be changed for light reasons.'],
      ['낭독', 'But after a long train of abuses, it is their right and duty to throw off such a government.'],
      ['해설', 'The Declaration then listed the wrongs of King George III, one by one.'],
      ['해설', 'They included taxing without consent, keeping armies in times of peace, and taking away trial by jury.'],
      ['학생', 'It sets up principles first, then shows the evidence one piece at a time.'],
      ['선생님', 'Right. It moves from a big principle down to specific facts, like a charge sheet in court.'],
      ['해설', 'But the list also called Native Americans merciless savages.'],
      ['해설', 'A paragraph in Jefferson’s draft attacking the slave trade was cut during the debate.'],
      ['학생', 'They said all men are equal, but they left out enslaved people and Native Americans?'],
      ['선생님', 'People pointed out that contradiction even then. Jefferson himself owned many enslaved people all his life.'],
      ['선생님', 'But later, abolitionists and women’s rights activists used these very words to demand equality.'],
      ['낭독', 'To support this Declaration, we pledge to each other our lives, our fortunes, and our sacred honor.'],
      ['해설', 'Fifty-six men signed the Declaration.'],
      ['해설', 'Jefferson and Adams both died on the same day, July 4, 1826, the fiftieth anniversary of independence.'],
    ],
  },

  'sp2-rights-man': {
    title: 'Declaration of the Rights of Man',
    names: { 해설: 'Narrator', 낭독: 'Reader', 선생님: 'Teacher', 학생: 'Student' },
    outro: [
      'Why did the Declaration say that human rights are born with us, not given by the state?',
      'Freedom means doing anything that does not harm others. What are the strengths and limits of this definition?',
      'Women and enslaved people in the colonies were left out. What should human rights documents today look at more carefully?',
    ],
    lines: [
      ['해설', 'On July 14, 1789, the people of Paris stormed the Bastille prison.'],
      ['해설', 'On August 26, the National Assembly adopted the Declaration of the Rights of Man and of the Citizen.'],
      ['학생', 'Is that the document we call the French Declaration of Human Rights?'],
      ['선생님', 'Yes. It is short, with a preamble and seventeen articles. Lafayette led the drafting work.'],
      ['선생님', 'The American Declaration of Independence and the bills of rights of American states were also models.'],
      ['해설', 'The preamble said that ignoring or scorning human rights was the cause of public misery and corrupt government.'],
      ['해설', 'Now let us hear the main articles in modern words.'],
      ['낭독', 'Article 1. Men are born and remain free and equal in rights.'],
      ['낭독', 'Social distinctions may be based only on the common good.'],
      ['낭독', 'Article 2. The aim of every political association is to protect the natural rights of man.'],
      ['낭독', 'These rights are liberty, property, security, and resistance to oppression.'],
      ['낭독', 'Article 3. The source of all sovereignty lies essentially in the nation.'],
      ['학생', 'If sovereignty lies in the nation, what happens to the king?'],
      ['선생님', 'It means even the king’s power must come from the nation. This article shook the base of absolute monarchy.'],
      ['낭독', 'Article 4. Liberty means being able to do anything that does not harm others.'],
      ['낭독', 'Article 6. Law is the expression of the general will, and all citizens are equal before it.'],
      ['낭독', 'Article 9. Everyone is presumed innocent until found guilty.'],
      ['낭독', 'Article 11. The free sharing of thoughts and opinions is one of the most precious rights of man.'],
      ['학생', 'The presumption of innocence and freedom of speech seem to be in our constitution too.'],
      ['선생님', 'That’s why this Declaration is counted as one starting point of modern human rights.'],
      ['낭독', 'Article 17. Property is an inviolable and sacred right.'],
      ['선생님', 'The strong stress on property hints that the people leading it were citizens who owned property.'],
      ['해설', 'In practice, women were not included in the man and citizen of the Declaration.'],
      ['해설', 'In 1791, Olympe de Gouges challenged this gap. She wrote the Declaration of the Rights of Woman and of the Female Citizen.'],
      ['해설', 'She was sent to the guillotine in 1793, during the Reign of Terror.'],
      ['해설', 'Slavery in the French colonies was abolished only in 1794, and Napoleon brought it back in 1802.'],
      ['학생', 'Declaring rights and giving them to everyone were two different things.'],
      ['선생님', 'Even so, its words became the ground on which those left out demanded their rights.'],
      ['해설', 'Through the preamble of France’s current constitution, this Declaration still has constitutional force.'],
    ],
  },

  'sp2-magna-carta': {
    title: 'Magna Carta',
    names: { 해설: 'Narrator', 낭독: 'Reader', 선생님: 'Teacher', 학생: 'Student' },
    outro: [
      'Why did the barons want to bind the king’s power in a written document?',
      'Why was the short clause saying no free man could be jailed without lawful judgment remembered for so long?',
      'A promise made for a few slowly grew into rights for all. What can we learn from that process?',
    ],
    lines: [
      ['해설', 'In 1215, King John of England had lost the barons’ trust through heavy taxes and failed wars in France.'],
      ['해설', 'The rebel barons took London and demanded that the king negotiate.'],
      ['해설', 'In June, in the meadow of Runnymede by the River Thames, the king accepted a charter of their demands.'],
      ['학생', 'What does Magna Carta mean?'],
      ['선생님', 'It is Latin for Great Charter.'],
      ['선생님', 'It has more than sixty clauses, so I’ll explain only the key ones. These are explanations, not the exact text.'],
      ['해설', 'The original was written in Latin, and the clause numbers were added later by scholars.'],
      ['낭독', 'Clause 1. The English Church shall be free and keep its rights in full.'],
      ['낭독', 'Clause 12. No scutage or special aid shall be raised without the common counsel of the kingdom.'],
      ['선생님', 'But there were exceptions: the king’s ransom, knighting his eldest son, and the first marriage of his eldest daughter.'],
      ['학생', 'So to collect taxes, he had to discuss it first.'],
      ['선생님', 'Yes. This idea later grew into the principle of no taxation without the consent of Parliament.'],
      ['낭독', 'Clause 39. No free man shall be imprisoned except by the lawful judgment of his peers or the law of the land.'],
      ['낭독', 'Nor shall he be stripped of property, outlawed, exiled, or harmed in any way.'],
      ['낭독', 'Clause 40. To no one will we sell, refuse, or delay right or justice.'],
      ['학생', 'So even the king could not lock people up as he pleased.'],
      ['선생님', 'Right. The idea that even the king is under the law shows clearly here.'],
      ['낭독', 'Clause 61. Twenty-five barons shall be chosen to demand a remedy, and even resist, if the king breaks the charter.'],
      ['학생', 'They even made a system to watch whether he kept his promise.'],
      ['선생님', 'It was humiliating for the king. John soon asked the Pope to cancel the charter.'],
      ['해설', 'That August, Pope Innocent III declared the charter invalid, and civil war broke out again.'],
      ['해설', 'After John died the next year, the charter was revised and reissued several times.'],
      ['해설', 'But the free men in the charter were nobles and free people. Serfs, the majority, were left out.'],
      ['학생', 'So at first it was not a document for everyone.'],
      ['선생님', 'But centuries later, people began to read its clauses as rights for all.'],
      ['선생님', 'In the 1600s, Parliament used it against the king, and its spirit carried on into the American Constitution.'],
      ['학생', 'Can we still see the charter they made back then?'],
      ['해설', 'Four original copies of the 1215 charter still survive.'],
    ],
  },

  'sp2-emancipation': {
    title: 'The Emancipation Proclamation',
    names: { 해설: 'Narrator', 링컨: 'Abraham Lincoln', 선생님: 'Teacher', 학생: 'Student' },
    outro: [
      'Why did Lincoln first explain emancipation as a war measure rather than as justice?',
      'How might the short phrase henceforward shall be free have sounded to people who had been enslaved?',
      'Freedom took time to follow the proclamation. How is that like changes in laws and systems today?',
    ],
    lines: [
      ['해설', 'The American Civil War began in 1861. At first, it was a war to save the Union.'],
      ['해설', 'But as the war went on, the question of slavery could no longer be avoided.'],
      ['해설', 'In September 1862, just after the Battle of Antietam, Lincoln issued a preliminary proclamation.'],
      ['해설', 'It warned that slaves in states still in rebellion would be free from January 1 of the next year.'],
      ['학생', 'What if the South had stopped fighting in between?'],
      ['선생님', 'He left that door open. But the South did not stop, and the proclamation came on January 1, 1863.'],
      ['해설', 'Now let us hear its main points in modern words.'],
      ['링컨', 'As commander in chief of the army and navy, I order this as a fit and necessary war measure.'],
      ['링컨', 'I name the following states and parts of states that are now in rebellion against the United States.'],
      ['링컨', 'All persons held as slaves within them are, and henceforward shall be, free.'],
      ['링컨', 'The government, including the army and navy, will recognize and protect their freedom.'],
      ['링컨', 'I urge those set free to avoid violence, except in self-defense, and to work faithfully for fair wages.'],
      ['링컨', 'Those who are fit will be received into the armed service of the United States.'],
      ['링컨', 'I believe this is an act of justice allowed by the Constitution. I ask for the considerate judgment of mankind.'],
      ['학생', 'Forever free sounds huge. But why did he call it a war measure?'],
      ['선생님', 'The Constitution did not give the president power to end slavery. He had to rely on his wartime powers.'],
      ['해설', 'The proclamation did not apply to Delaware, Maryland, Kentucky, and Missouri, slave states that stayed in the Union.'],
      ['해설', 'Some parts of the South already held by Union troops were also left out.'],
      ['학생', 'So he left out the very places where people could be freed right away?'],
      ['선생님', 'Some criticized that. He was careful not to push the loyal slave states over to the South.'],
      ['선생님', 'Still, as Union troops moved south, more people were freed, and the purpose of the war itself changed.'],
      ['해설', 'Black men could now join the Union Army, and about 180,000 fought in it by the end of the war.'],
      ['해설', 'It also became harder for European countries to openly help a Confederacy fighting to keep slavery.'],
      ['해설', 'On June 19, 1865, Union troops reached Galveston, Texas, and announced that the enslaved were free.'],
      ['학생', 'So in some places the news came two and a half years later.'],
      ['선생님', 'The proclamation alone was not enough, so a constitutional amendment followed to end slavery completely.'],
      ['해설', 'The Thirteenth Amendment, which abolished slavery, was ratified in December 1865.'],
      ['해설', 'June 19 was long celebrated as Juneteenth, and in 2021 it became a federal holiday.'],
    ],
  },

  'sp2-anthony-trial': {
    title: 'The Trial of Susan B. Anthony',
    names: { 해설: 'Narrator', 앤서니: 'Susan B. Anthony', 판사: 'Judge Hunt', 선생님: 'Teacher', 학생: 'Student' },
    outro: [
      'Why did Anthony insist that she was a citizen using her right, not a criminal?',
      'What effect do the question are women persons and the scene of the judge cutting her off each have?',
      'How can we judge today Anthony’s refusal to obey a sentence she believed was unjust?',
    ],
    lines: [
      ['해설', 'In November 1872, Susan B. Anthony and more than ten other women voted for president in Rochester, New York.'],
      ['해설', 'Anthony was charged with illegal voting. The next spring, she gave speeches in the nearby towns.'],
      ['해설', 'The title of her speech was, Is It a Crime for a U.S. Citizen to Vote?'],
      ['학생', 'That speech has the question, are women persons, right?'],
      ['선생님', 'Right. Her basis was the Fourteenth Amendment: all persons born or naturalized in the United States are citizens.'],
      ['선생님', 'Women are persons, so they are citizens. Citizens can vote. It was simple and solid logic.'],
      ['해설', 'Today, instead of the speech, let us follow the record of the trial that came after.'],
      ['해설', 'In June 1873, the trial opened in a federal court in Canandaigua. The judge was Justice Ward Hunt.'],
      ['해설', 'After the arguments, Judge Hunt read an opinion written in advance. Then he ordered the jury to find her guilty.'],
      ['학생', 'The jury didn’t even get to talk about it?'],
      ['선생님', 'That’s why this trial is still criticized as unfair. A request to poll the jury was also refused.'],
      ['해설', 'Before passing sentence, the judge asked the prisoner if she had anything to say.'],
      ['해설', 'What follows is the main idea of the court record, in modern words.'],
      ['앤서니', 'Yes, I have many things to say. Your verdict has trampled on every vital principle of our government.'],
      ['앤서니', 'I have been degraded from a citizen to a subject. And not only I, but all of my sex.'],
      ['판사', 'Your lawyer has already argued that fully. The court cannot hear this.'],
      ['앤서니', 'The laws are made by men, interpreted by men, carried out by men, in favor of men.'],
      ['판사', 'The prisoner will sit down.'],
      ['앤서니', 'I do not ask for leniency. Rather, I ask for the full rigors of the law.'],
      ['해설', 'The judge sentenced her to pay a fine of one hundred dollars and the costs of the trial.'],
      ['앤서니', 'I shall never pay a dollar of your unjust penalty.'],
      ['해설', 'The judge did not order her to be jailed for not paying the fine.'],
      ['선생님', 'If she had been jailed, she could have taken the case to the Supreme Court. That road was now closed.'],
      ['학생', 'So he made sure she could neither win nor properly lose.'],
      ['선생님', 'Still, the trial record spread widely, and women’s right to vote became a national debate.'],
      ['선생님', 'Her speaking her mind despite the judge moved people outside the courtroom.'],
      ['해설', 'Anthony never paid that fine.'],
      ['해설', 'In 1979, the United States issued a one-dollar coin with Anthony’s face on it.'],
    ],
  },

  'sp2-atlanta': {
    title: 'The Atlanta Exposition Address',
    names: { 해설: 'Narrator', 워싱턴: 'Booker T. Washington', 선생님: 'Teacher', 학생: 'Student' },
    outro: [
      'Why did Washington tell both Black and white Americans to cast down their bucket where they were?',
      'How might separate as the fingers, yet one as the hand have sounded different to different listeners?',
      'Between compromise for survival now and demands for equality, what balance can we find today?',
    ],
    lines: [
      ['해설', 'In September 1895, the Cotton States and International Exposition opened in Atlanta, in the American South.'],
      ['해설', 'One opening speaker was Booker T. Washington, the head of the Tuskegee school in Alabama.'],
      ['해설', 'A Black man born into slavery rarely spoke to a white audience at a big Southern event.'],
      ['학생', 'What was life like for Black people in the South then?'],
      ['선생님', 'Thirty years after emancipation, they were losing the vote and suffering from unfair laws and lynching.'],
      ['해설', 'Let us hear the main idea of the speech in modern words.'],
      ['워싱턴', 'A ship lost at sea signaled to a passing ship that its crew was dying of thirst.'],
      ['워싱턴', 'The answer came back, cast down your bucket where you are. It came back the same each time.'],
      ['워싱턴', 'At last they cast down their bucket. It came up full of fresh water from the mouth of the Amazon River.'],
      ['워싱턴', 'Some of my race hope to better themselves in a faraway land. To them I say, cast down your bucket where you are.'],
      ['워싱턴', 'Cast it down in farming, in mechanics, in business, in domestic service, and in the professions.'],
      ['워싱턴', 'There is as much dignity in tilling a field as in writing a poem. We must begin at the bottom of life.'],
      ['워싱턴', 'To white people I say, don’t wait for foreign immigrants. Cast down your bucket among the Black people around you.'],
      ['워싱턴', 'In purely social things we can be as separate as the fingers. Yet we can be one as the hand for mutual progress.'],
      ['학생', 'Separate as the fingers? That sounds like he is accepting segregation.'],
      ['선생님', 'The white audience heard it that way and cheered loudly. Southern newspapers printed the speech widely.'],
      ['워싱턴', 'The wisest among my race understand that stirring up questions of social equality is the worst folly.'],
      ['워싱턴', 'No race that has anything to offer the markets of the world is shut out for long.'],
      ['선생님', 'His idea was to work and build wealth first, and rights would follow. He also wanted to avoid conflict.'],
      ['해설', 'But some Black thinkers strongly criticized this speech.'],
      ['해설', 'In The Souls of Black Folk, in 1903, W. E. B. Du Bois called its approach the Atlanta Compromise.'],
      ['해설', 'He argued that giving up the vote, civil equality, and higher education for Black youth meant surrender.'],
      ['학생', 'So even Black leaders had very different ideas.'],
      ['학생', 'I heard that the year after the speech, there was a ruling called separate but equal.'],
      ['선생님', 'Yes. The 1896 case Plessy v. Ferguson ruled that racial segregation was legal.'],
      ['선생님', 'The speech did not cause that ruling, but it shows how much segregation was being accepted.'],
      ['해설', 'Today the speech is read with a question: was it a realistic strategy under oppression, or a surrender to discrimination?'],
      ['해설', 'In 1901, Washington published his autobiography, Up from Slavery.'],
    ],
  },

  'sp2-angostura': {
    title: 'Bolívar’s Address at Angostura',
    names: { 해설: 'Narrator', 볼리바르: 'Simón Bolívar', 선생님: 'Teacher', 학생: 'Student' },
    outro: [
      'Why did Bolívar, a war hero, begin his speech by handing power back to the congress?',
      'How did the words we are neither Europeans nor Indians describe the identity of South Americans?',
      'He warned against copying another country’s system. What does that mean when we build systems today?',
    ],
    lines: [
      ['해설', 'In the early 1800s, wars of independence spread through Spain’s colonies in South America.'],
      ['해설', 'Simón Bolívar, born in Caracas, Venezuela, was a leader of those wars.'],
      ['해설', 'On February 15, 1819, a congress met in Angostura, a town on the Orinoco River.'],
      ['해설', 'At the opening, Bolívar gave a long speech about the constitution of the new republic.'],
      ['학생', 'He talked about a constitution in the middle of a war?'],
      ['선생님', 'Yes. While fighting Spanish troops, he was already planning what kind of nation to build after winning.'],
      ['해설', 'Let us hear the main idea of the speech in modern words.'],
      ['볼리바르', 'I return my power to this congress. Nothing is more dangerous than letting one citizen hold power for long.'],
      ['볼리바르', 'The people grow used to obeying him, and he grows used to commanding them.'],
      ['볼리바르', 'We are neither Europeans nor Indians. We are a people between the natives of this land and the Spanish.'],
      ['볼리바르', 'For a long time we were bound by ignorance and tyranny. We never had the chance to learn self-government.'],
      ['학생', 'So what kind of nation did he want?'],
      ['볼리바르', 'Trying to apply the laws of North America to Venezuela as they are would be a mistake.'],
      ['볼리바르', 'Laws must fit a country’s land and climate, and its people’s way of life, religion, and character.'],
      ['볼리바르', 'The most perfect government produces the greatest happiness, social security, and political stability.'],
      ['선생님', 'So he proposed a strong president and a hereditary senate, modeled on the British system.'],
      ['선생님', 'He also proposed a fourth branch, the Moral Power, to look after citizens’ morals and education.'],
      ['학생', 'A hereditary senate? It is surprising that a revolutionary wanted something so like nobility.'],
      ['선생님', 'He wanted to prevent chaos. But critics called it elitist, and the congress did not accept it as it was.'],
      ['볼리바르', 'Confirm the absolute freedom of the slaves. I beg this as I would beg for my life and the Republic’s.'],
      ['학생', 'He spoke about freeing the slaves so earnestly.'],
      ['선생님', 'But it took decades more for slavery to really end in many South American countries.'],
      ['해설', 'The congress elected Bolívar president, and he soon set out across the Andes Mountains.'],
      ['해설', 'After winning the Battle of Boyacá that August, the Republic of Colombia was proclaimed in December.'],
      ['해설', 'Historians call this nation Gran Colombia, to tell it apart from today’s Colombia.'],
      ['해설', 'Later, Bolívar offered a constitution with a president for life, and some suspected he wanted to be a dictator.'],
      ['학생', 'But he was the one who said holding power for long was dangerous.'],
      ['해설', 'Bolívar died in 1830 in Santa Marta, Colombia. The country of Bolivia is named after him.'],
    ],
  },

  'sp2-dosan': {
    title: 'Dosan Ahn Chang-ho',
    names: { 해설: 'Narrator', 선생님: 'Teacher', 학생: 'Student' },
    outro: [
      'Why did Ahn Chang-ho believe each person’s strength and character had to be built first for independence?',
      'What kind of person do the four words musil, yeokhaeng, chungui, and yonggam each describe?',
      'How can we see the idea today that small habits, like not lying, can change a community?',
    ],
    lines: [
      ['해설', 'Ahn Chang-ho was born in 1878 in Gangseo, South Pyeongan Province. His pen name was Dosan.'],
      ['해설', 'As a young man he studied new Western learning in Seoul and joined the Independence Club.'],
      ['해설', 'A speech he gave at Kwaejaejeong Pavilion in Pyongyang in the late 1890s is said to have made him famous.'],
      ['학생', 'Do we still have the text of that speech?'],
      ['선생님', 'No written text survives. It comes down to us mostly through the memories of people who heard it.'],
      ['해설', 'He went to America and led the Korean community there. In 1907 he returned and helped found the secret society Sinminhoe.'],
      ['해설', 'In 1908 he founded Daeseong School in Pyongyang to teach young people.'],
      ['학생', 'He was an independence fighter. Why did he start with a school?'],
      ['선생님', 'Ahn believed Korea lost its nation because it lacked strength, and that strength comes from people.'],
      ['선생님', 'So he made raising people with knowledge, character, and ability the base of independence.'],
      ['해설', 'In 1913 he founded Heungsadan in San Francisco.'],
      ['선생님', 'Heungsadan kept up its work even after liberation.'],
      ['해설', 'Heungsadan held up four spirits: musil, yeokhaeng, chungui, and yonggam.'],
      ['선생님', 'Musil means striving to be truthful. Yeokhaeng means working hard to put what you know into action.'],
      ['선생님', 'Chungui means giving your whole heart to your work and to people. Yonggam means not backing away from what is right.'],
      ['학생', 'They are less like grand slogans and more about one person’s attitude.'],
      ['선생님', 'Exactly. He saw lying as a great enemy of the nation and put truthfulness above everything.'],
      ['선생님', 'One saying of his that has come down to us is, even if you die, do not lie.'],
      ['선생님', 'Another is, despair is the death of youth, and when youth dies, the nation dies.'],
      ['학생', 'He even called despair the death of youth.'],
      ['선생님', 'It means when one person falls, the community falls too. So he valued self-discipline.'],
      ['해설', 'After the March First Movement of 1919, he went to Shanghai. There he served as Home Minister of the Korean Provisional Government.'],
      ['해설', 'He worked hard to unite independence groups divided by region and faction.'],
      ['학생', 'The man who stressed ability and character also worked for unity.'],
      ['해설', 'In 1932, after Yun Bong-gil’s bombing attack, Japanese police arrested him in Shanghai and sent him back to Korea.'],
      ['해설', 'In 1937 he was jailed again in the Suyang Dongwuhoe case. He grew very ill and was released on bail.'],
      ['선생님', 'The illness he got in prison never let him recover.'],
      ['해설', 'Ahn Chang-ho died in Gyeongseong, now Seoul, on March 10, 1938.'],
    ],
  },

  'sp2-ju-sigyeong': {
    title: 'Ju Si-gyeong and Hangeul',
    names: { 해설: 'Narrator', 선생님: 'Teacher', 학생: 'Student' },
    outro: [
      'Why did Ju Si-gyeong give his life to studying the Korean language while the nation was falling?',
      'What does his nickname, the bundle teacher, show about what kind of person he was?',
      'Whose efforts lie inside the spelling and spacing rules we use today?',
    ],
    lines: [
      ['해설', 'Ju Si-gyeong was born in 1876 in Bongsan, Hwanghae Province.'],
      ['해설', 'As a boy he studied classical Chinese. He is said to have wondered why it took so long just to understand the meaning.'],
      ['해설', 'While studying new subjects at Paichai School, he began working for the newspaper Dongnip Sinmun in 1896.'],
      ['학생', 'What did he do at the newspaper?'],
      ['선생님', 'Dongnip Sinmun was printed only in hangeul, the Korean alphabet. He is said to have worked as a proofreader.'],
      ['선생님', 'But back then, people spelled the same word in different ways. There were no fixed spelling rules.'],
      ['해설', 'At the newspaper, he formed a study group to find ways to make spelling the same for everyone.'],
      ['학생', 'So spelling research started from making one newspaper.'],
      ['해설', 'In 1907, when the Korean Empire’s education ministry set up a Korean language institute, he became a member.'],
      ['해설', 'He wrote books on Korean grammar and sounds, organizing how the language sounds and how it is built.'],
      ['선생님', 'One of his key ideas was to write each word so its original form stays clear.'],
      ['선생님', 'For example, you write meogeo, eat, with the root meok kept visible, not just as it sounds.'],
      ['학생', 'Then in meokda, meokgo, and meogeo, the root meok stays the same, so the meaning is easy to see.'],
      ['선생님', 'Yes. Today’s spelling rules come from this idea. He also argued early for spacing between words.'],
      ['해설', 'He rushed from school to school to teach Korean.'],
      ['해설', 'He always carried a bundle of books, so he is said to have been nicknamed the bundle teacher.'],
      ['해설', 'He also opened a Korean language school to teach grammar to young people.'],
      ['학생', 'Teaching Korean must have been hard when the nation was being taken away.'],
      ['선생님', 'He believed language and writing were what tied the people together.'],
      ['선생님', 'He is said to have written this. When the language rises, the nation rises. When it falls, the nation falls.'],
      ['학생', 'So protecting the language meant protecting the nation.'],
      ['해설', 'The name hangeul itself is known to have spread after Ju Si-gyeong and his students began using it.'],
      ['해설', 'In 1914, before he even turned forty, he died suddenly.'],
      ['해설', 'His work was carried on by students like Choe Hyeon-bae and Kim Du-bong.'],
      ['학생', 'The seeds one teacher left grew in his students.'],
      ['선생님', 'In 1921 his students formed the Korean Language Research Society, which later became the Korean Language Society.'],
      ['선생님', 'Even under Japanese rule, they kept working on spelling rules and a dictionary.'],
      ['해설', 'In 1933, the Korean Language Society announced the Unified Hangeul Spelling System.'],
    ],
  },

  'sp2-keller': {
    title: 'The Story of My Life',
    names: { 해설: 'Narrator', 헬렌: 'Helen Keller', 선생님: 'Teacher', 학생: 'Student' },
    outro: [
      'Why did the single word water become the key that opened the world for Helen Keller?',
      'What does her calm account of breaking the doll and her late regret tell us about the writer?',
      'What more should our society provide to support learning for people with disabilities?',
    ],
    lines: [
      ['해설', 'Helen Keller was born in 1880 in Tuscumbia, Alabama.'],
      ['해설', 'At about nineteen months old, a serious illness left her unable to see or hear.'],
      ['해설', 'In 1903, while still a college student, she published The Story of My Life about her childhood.'],
      ['학생', 'She wrote her life story as a college student?'],
      ['선생님', 'She wrote it while at Radcliffe College. Today we’ll hear a few parts, retold in modern words.'],
      ['해설', 'Helen’s lines below give the main idea of what the book says.'],
      ['헬렌', 'I made my wishes known with a few signs, and when no one understood, I burst into anger.'],
      ['헬렌', 'The most important day of my life was the day Miss Sullivan came. It was three months before I turned seven.'],
      ['헬렌', 'She gave me a doll and spelled the word doll into my hand with her fingers.'],
      ['헬렌', 'I copied the finger movements, but I did not know that everything has a name.'],
      ['학생', 'She wrote letters on her palm?'],
      ['선생님', 'She used the manual alphabet, finger shapes for letters, pressed into Helen’s hand.'],
      ['헬렌', 'One day I kept mixing up the words mug and water. I got angry and threw my new doll on the floor.'],
      ['헬렌', 'The doll broke, but I felt no sorrow or regret. In my world then, there was no tenderness.'],
      ['헬렌', 'We went to the well-house. Someone was drawing water, and my teacher put my hand under the stream.'],
      ['헬렌', 'As the cool water gushed over one hand, she spelled the word water into the other.'],
      ['헬렌', 'Suddenly I knew that water meant this wonderful cool thing flowing over my hand.'],
      ['헬렌', 'That living word awakened my soul and gave it light, hope, and joy.'],
      ['학생', 'One word opened up the whole world.'],
      ['선생님', 'The moment she realized everything has a name, her thoughts and feelings began to connect through language.'],
      ['헬렌', 'At home, I found the pieces of the broken doll and tried to put them together, but could not. My eyes filled with tears.'],
      ['헬렌', 'I learned many words that day. And for the first time, I went to bed longing for a new day to come.'],
      ['해설', 'Later she read books in braille, and from about age ten she learned to speak aloud.'],
      ['학생', 'What kind of person was Miss Sullivan?'],
      ['선생님', 'She had poor eyesight herself and went to the Perkins School for the Blind. She stayed by Helen for nearly fifty years.'],
      ['해설', 'The book also tells how, at eleven, she suffered when a story she wrote was suspected of being copied.'],
      ['해설', 'Later, Helen worked for the rights of disabled people, women’s right to vote, and workers’ rights.'],
      ['해설', 'In 1904 Helen Keller graduated from Radcliffe, the first deafblind person to earn a bachelor’s degree.'],
    ],
  },
};
