// 청소년 영어 원고 (중학생 이상). 키 = stories/teen-ws5.js 의 이야기 id.
// 루쉰·아쿠타가와·타고르 원작(퍼블릭 도메인)을 한국어 각색의 흐름대로 쉬운 영어로 새로 씀.
export default {
  'wsx-guxiang': {
    title: 'My Old Home',
    names: { 해설: 'Narrator', 쉰: 'Xun', 어머니: 'Mother', 룬투: 'Runtu', 양씨: 'Mrs. Yang', 훙얼: 'Hong’er' },
    outro: [
      'After twenty years, what built the thick wall between Xun and Runtu?',
      'The writer puts young Runtu under a golden moon beside old Runtu’s cracked hands. What effect does this create?',
      'Hope is like a road made by many walkers. What changes in our world need many people walking together?',
    ],
    lines: [
      ['해설', 'In the bitter cold of winter, Xun traveled a long way home after more than twenty years.'],
      ['해설', 'Under a yellow sky, the villages lay flat and lifeless.'],
      ['쉰', 'My hometown was much more beautiful in my memory. Was it always this lonely?'],
      ['해설', 'He had come to say goodbye. The family house was sold, and he had to take his family away.'],
      ['어머니', 'You’re here. Let’s pack slowly. Oh, Runtu said he would come to see you.'],
      ['해설', 'At that name, an old picture lit up in Xun’s mind.'],
      ['해설', 'A golden moon in a dark blue sky, a melon field by the sea, a boy with a silver necklace.'],
      ['해설', 'Thirty years ago, Runtu, a worker’s son, came to help at a big ceremony. The two boys became close friends.'],
      ['룬투', 'When it snows, I catch birds with a basket. In summer, I pick up pretty shells on the beach.'],
      ['룬투', 'At night, I guard the melons with a spear. The badgers are very fast.'],
      ['해설', 'Runtu knew a whole world that Xun did not. When he left, Xun cried and would not let go.'],
      ['해설', 'One day, while Xun was packing, a thin woman of about fifty stood before him, hands on hips.'],
      ['양씨', 'Don’t you know me? I’m Mrs. Yang from the tofu shop across the street. I used to hold you!'],
      ['해설', 'People once called her the beauty of the tofu shop. Now her face looked only sharp.'],
      ['양씨', 'You’re rich and important now, yet you won’t give away old furniture? The rich are always stingy.'],
      ['해설', 'Grumbling, she slipped a pair of Mother’s gloves into her pocket and walked out.'],
      ['해설', 'One cold afternoon, a visitor came. Xun jumped up with joy. It was Runtu.'],
      ['해설', 'He was tall now, but his face was gray and wrinkled. His hands were cracked like pine bark.'],
      ['쉰', 'Ah, Brother Runtu! You came!'],
      ['룬투', 'Master!'],
      ['해설', 'That one word made Xun shiver. He knew a thick wall now stood between them.'],
      ['룬투', 'Shuisheng, bow to the master. Back then I was foolish and called him my brother.'],
      ['어머니', 'Oh, you two were like brothers. Please talk as you used to.'],
      ['룬투', 'Life is hard. I have six children, bad harvests, heavy taxes, soldiers, and bandits.'],
      ['해설', 'Runtu only puffed on an empty pipe. From the things they offered, he chose an incense burner and candlesticks.'],
      ['해설', 'Mrs. Yang found bowls in the ashes and said Runtu had hidden them. Then she took something for herself.'],
      ['훙얼', 'Uncle, when are we coming back? Shuisheng asked me to come and play.'],
      ['해설', 'As the boat moved away, Xun hoped the children would never be trapped behind such a wall.'],
      ['해설', 'Hope is like a road on the earth. At first there is no road, but when many walk, a road appears.'],
      ['해설', 'Lu Xun published My Old Home in 1921, and later put it in his story collection Call to Arms.'],
    ],
  },

  'wsx-kongyiji': {
    title: 'Kong Yiji',
    names: { 해설: 'Narrator', 공을기: 'Kong Yiji', 손님: 'Customer', 주인: 'Owner', 점원: 'Shop Boy', 아이들: 'Children' },
    outro: [
      'Kong Yiji never took off his long gown. What did Lu Xun want to show through him?',
      'The story is told by a shop boy who does not care much. How does this make the tragedy more painful?',
      'Do we still see people who laugh at others’ misfortune today?',
    ],
    lines: [
      ['해설', 'At the Xianheng Tavern in Luzhen, workers in short coats drank standing, and men in long gowns sat down.'],
      ['해설', 'A twelve-year-old shop boy warmed wine all day. His only fun came when Kong Yiji visited.'],
      ['해설', 'Kong Yiji was the only man who drank standing up while wearing a long gown.'],
      ['해설', 'He was tall and pale. His gown was torn and dirty, as if it had not been washed for ten years.'],
      ['해설', 'He mixed old bookish words into everything he said, so people only half understood him.'],
      ['공을기', 'Two bowls of warm wine and a dish of aniseed beans, please.'],
      ['손님', 'Kong Yiji, you have a new scar on your face. You stole something again!'],
      ['공을기', 'Why do you dirty a man’s good name? Taking books is not stealing.'],
      ['공을기', 'Books are a scholar’s business. How can a scholar’s business be called stealing?'],
      ['손님', 'A scholar? You couldn’t even pass the first state exam!'],
      ['해설', 'His face turned gray, and he mumbled words no one could follow. The whole tavern roared with laughter.'],
      ['공을기', 'Boy, have you studied? Do you know how to write the character for anise?'],
      ['점원', 'It’s the grass sign on top of the word for return, right? I know that much.'],
      ['공을기', 'Good, good. There are four ways to write that return part. Remember them well.'],
      ['해설', 'When the village children heard the laughter and came running, he gave them one bean each.'],
      ['아이들', 'Mister, just one more, please!'],
      ['공을기', 'Not many, not many. Truly, not many left.'],
      ['해설', 'He usually paid his bills, but nineteen coins of his debt were still written on the board.'],
      ['주인', 'Kong Yiji hasn’t come for a long time. He still owes nineteen coins.'],
      ['손님', 'Didn’t you hear? He stole from the rich scholar Ding, got beaten all night, and broke his legs.'],
      ['주인', 'And then what happened?'],
      ['손님', 'Who knows? Maybe he is dead.'],
      ['해설', 'One day, when the autumn wind turned cold, a low voice came from below the counter.'],
      ['공을기', 'One bowl of warm wine.'],
      ['해설', 'He sat on a straw mat instead of his legs. He had crawled there on his hands.'],
      ['주인', 'Kong Yiji, did you steal again and break your legs?'],
      ['공을기', 'Don’t laugh at me. I fell, I just fell and broke them.'],
      ['해설', 'He paid four copper coins, drank his wine, and slowly crawled away on his hands.'],
      ['해설', 'Kong Yiji never came back after that. Perhaps he really did die.'],
      ['해설', 'Lu Xun published Kong Yiji in the magazine New Youth in 1919.'],
    ],
  },

  'wsx-ahq-1': {
    title: 'The True Story of Ah Q, Part 1',
    names: { 해설: 'Narrator', 아Q: 'Ah Q', 자오나리: 'Mr. Zhao', 왕털보: 'Whiskers Wang', 비구니: 'Young Nun', 우씨: 'Amah Wu' },
    outro: [
      'Ah Q believes he has won even after being beaten. What is his spiritual victory trying to hide?',
      'Ah Q bows to the strong and takes out his anger on the weak. In what tone does Lu Xun describe him?',
      'Have you ever covered up an unpleasant fact by winning only in your own mind?',
    ],
    lines: [
      ['해설', 'In the village of Weizhuang lived a man called Ah Q. Nobody knew his real name or where he came from.'],
      ['해설', 'He had no home, so he slept in the village temple and lived by doing odd jobs.'],
      ['아Q', 'My family name is Zhao too! In fact, I’m related to the great Mr. Zhao.'],
      ['자오나리', 'You, a Zhao? How dare you! You could never be a Zhao!'],
      ['해설', 'Mr. Zhao slapped him, and after that nobody asked his family name again.'],
      ['해설', 'Ah Q had shiny scars on his head, so he got angry whenever people said words like shiny or bright.'],
      ['해설', 'People said those words on purpose to tease him. When they fought, Ah Q always lost.'],
      ['아Q', 'Hmph, let’s say my son beat me. These days, sons even beat their fathers.'],
      ['해설', 'Then Ah Q walked away happily, like a winner. This was his method of spiritual victory.'],
      ['해설', 'People learned his secret. They grabbed his hair and said, admit that a man is beating an animal!'],
      ['아Q', 'You’re beating a bug, all right? I’m a bug. Now let me go!'],
      ['해설', 'Once free, Ah Q thought to himself, I am number one at putting myself down.'],
      ['해설', 'One day he won a pile of silver coins at gambling, but in a sudden fight it all disappeared.'],
      ['해설', 'Ah Q slapped his own face hard, twice. It felt like he had hit someone else, so he soon felt better.'],
      ['해설', 'One spring day, while picking lice by a wall, he picked a fight with Whiskers Wang.'],
      ['왕털보', 'Who do you think you are, you scabby fool?'],
      ['해설', 'Wang knocked Ah Q’s head against the wall five times. It was the worst shame of his life.'],
      ['해설', 'Just then, a young nun walked toward him. Ah Q had found someone to take his anger out on.'],
      ['아Q', 'Why is a shaved head walking here? Ha ha, your cheek is so smooth.'],
      ['비구니', 'You will die without children! How dare you touch my face!'],
      ['해설', 'The watchers laughed. In this village, nobody stopped the strong from bullying the weak.'],
      ['해설', 'That night her words kept ringing in his head. Without a son, no one would honor him after death.'],
      ['해설', 'A few days later, at the Zhao house, Ah Q suddenly knelt in front of Amah Wu, the maid.'],
      ['아Q', 'Live with me! Live with me!'],
      ['우씨', 'Oh! What are you doing? Help! Help!'],
      ['해설', 'Amah Wu ran out crying, and Mr. Zhao’s son beat Ah Q with a big stick.'],
      ['해설', 'To pay for his apology, he even pawned his cotton quilt. After that, nobody in the village gave him work.'],
      ['해설', 'Hungry and alone, Ah Q quietly disappeared from the village one day.'],
      ['해설', 'Lu Xun was born in Shaoxing, China, in 1881 and died in Shanghai in 1936.'],
    ],
  },

  'wsx-ahq-2': {
    title: 'The True Story of Ah Q, Part 2',
    names: { 해설: 'Narrator', 아Q: 'Ah Q', 자오나리: 'Mr. Zhao', 가짜양놈: 'Fake Foreign Devil', 관리: 'Officer', 구경꾼: 'Onlooker' },
    outro: [
      'A revolution came, so why did nothing change for Weizhuang or for Ah Q?',
      'In the last scene, Ah Q is ashamed that his circle is not round. What kind of person does this show?',
      'Watching an innocent person’s death as a show still happens in some form today. Where do we see it?',
    ],
    lines: [
      ['해설', 'In the last part, Ah Q left Weizhuang as if he had been chased away.'],
      ['해설', 'In autumn, he came back with heavy silver coins at his belt and even a silk skirt.'],
      ['해설', 'Suddenly people looked up to him. But soon a rumor spread that he had only kept watch for thieves.'],
      ['해설', 'People looked down on him again, though now they did not dare to bother him.'],
      ['해설', 'Then one night, news came that revolutionaries had entered the city. It was the year 1911.'],
      ['해설', 'When Ah Q saw rich landlords like Mr. Zhao trembling, he began to like the revolution.'],
      ['아Q', 'Revolution! Rebellion! Whatever I want is mine, and I’ll punish everyone I hate!'],
      ['자오나리', 'Oh, Ah Q, I mean, Brother Q. How are things with you these days?'],
      ['해설', 'Ah Q felt proud. Lying in the temple, he dreamed of carrying away the landlords’ things.'],
      ['해설', 'But by morning, Mr. Zhao’s son and the Fake Foreign Devil had already joined the revolution together.'],
      ['해설', 'The Fake Foreign Devil was a rich man’s son who had studied in Japan and wore a fake pigtail.'],
      ['해설', 'The two of them rushed into the nuns’ temple, smashed the emperor’s tablet, and took an incense burner.'],
      ['아Q', 'Please, sir, let me join the revolution too.'],
      ['가짜양놈', 'Get out! What does a man like you know about revolution?'],
      ['해설', 'In the county, the officials only changed their titles and kept their jobs. Nothing really changed.'],
      ['해설', 'Some time later, thieves robbed the Zhao house at night. Ah Q only watched from far away.'],
      ['해설', 'But a few nights later, soldiers surrounded the temple and dragged Ah Q away.'],
      ['관리', 'Tell the truth. Where are the others who robbed the house with you?'],
      ['아Q', 'I wanted to go with them, but nobody ever called me.'],
      ['관리', 'Sign your name here. If you can’t write, just draw a circle.'],
      ['해설', 'It was the first time Ah Q had ever held a brush. He tried his best, but the circle came out crooked.'],
      ['아Q', 'Oh no, my circle isn’t round. What a shame.'],
      ['해설', 'He did not even know what the paper was. He was only ashamed of his crooked circle.'],
      ['해설', 'The next day, he was paraded through the streets in a cart. Crowds gathered like ants.'],
      ['해설', 'At that moment, Ah Q felt eyes like a wolf’s biting into his flesh and soul.'],
      ['해설', 'He wanted to cry for help, but no sound came out of his mouth.'],
      ['해설', 'He was shot to death. The villagers said he must have been bad, since he was shot.'],
      ['구경꾼', 'Shooting is not as fun to watch as beheading. He didn’t even sing a single song.'],
      ['해설', 'The True Story of Ah Q came out in a Beijing newspaper from late 1921 to early 1922.'],
    ],
  },

  'wsx-rashomon': {
    title: 'Rashomon',
    names: { 해설: 'Narrator', 하인: 'Servant', 노파: 'Old Woman' },
    outro: [
      'The servant could not choose between starving and stealing. What finally made up his mind?',
      'The rainy gate, the dead bodies, and the torch are all dark. How do they reflect the characters’ hearts?',
      'Some say anything is fine if you do it to survive. How can we answer that idea?',
    ],
    lines: [
      ['해설', 'One evening, a servant waited for the rain to stop under Rashomon, the great gate of Kyoto.'],
      ['해설', 'For years, earthquakes, whirlwinds, fires, and famine had struck the capital. The city was in ruins.'],
      ['해설', 'Foxes and thieves lived in the broken gate, and people threw unclaimed bodies there.'],
      ['해설', 'A few days before, the servant had been dismissed by his master. He had nowhere to go.'],
      ['하인', 'At this rate, I’ll starve or freeze on the road. Or else I must become a thief.'],
      ['해설', 'But he had no courage to follow that thought to the end. He only touched a pimple on his right cheek.'],
      ['해설', 'Looking for a place to spend the night, he found a ladder leading up into the gate tower.'],
      ['해설', 'Halfway up, he held his breath. Someone above was holding a light.'],
      ['해설', 'Dead bodies lay all over the floor, and the smell of rot stung his nose.'],
      ['해설', 'Among them, a monkey-like old woman held a torch. She was pulling hairs from a dead woman, one by one.'],
      ['해설', 'Instead of fear, anger boiled up in the servant’s heart. It was a hatred of all evil.'],
      ['해설', 'He had completely forgotten that a moment ago, he was thinking of becoming a thief.'],
      ['하인', 'You old hag! Where do you think you’re going?'],
      ['노파', 'Oh, let me go! Let me go!'],
      ['하인', 'Tell me what you were doing here. If you don’t, I’ll cut you with this sword.'],
      ['노파', 'I was pulling out this hair to make a wig.'],
      ['해설', 'The answer was so ordinary that the servant was disappointed. Then cold contempt filled him again.'],
      ['노파', 'Pulling hair from the dead may be wrong. But this woman did wrong too.'],
      ['노파', 'She cut snakes into pieces, dried them, and sold them to the palace guards as dried fish.'],
      ['노파', 'She did it so she wouldn’t starve, so it wasn’t evil. The same goes for me.'],
      ['노파', 'She knew what it means to have no choice. She will forgive what I do.'],
      ['해설', 'As he listened, a new courage grew in the servant’s heart, a courage he had not had before.'],
      ['하인', 'Then don’t blame me if I take your clothes.'],
      ['하인', 'I will starve too if I don’t.'],
      ['해설', 'He quickly tore off her clothes and kicked her onto the bodies as she clung to him.'],
      ['해설', 'Then he rushed down the ladder and disappeared into the pitch-black night.'],
      ['해설', 'Much later, the old woman crawled to the top of the ladder and looked down, her white hair hanging.'],
      ['해설', 'Outside, there was only black night. Where the servant went, no one knows.'],
      ['해설', 'Rashomon was published in 1915, five years after Japan forced Korea under its rule.'],
    ],
  },

  'wsx-spider': {
    title: 'The Spider’s Thread',
    names: { 해설: 'Narrator', 부처: 'Buddha', 간다타: 'Kandata', 죄인들: 'Sinners' },
    outro: [
      'What was the real reason Kandata could not escape from hell?',
      'The writer shows the quiet lotus pond of paradise next to the boiling pit of hell. How does that feel?',
      'Have you ever felt the wish to save only yourself clash with the wish to live together?',
    ],
    lines: [
      ['해설', 'One morning, the Buddha was walking alone beside the lotus pond in paradise.'],
      ['해설', 'The lotus flowers were white as pearls, and a sweet smell spread from them without end.'],
      ['해설', 'The Buddha looked down between the leaves. The bottom of the pond reached straight down to hell.'],
      ['해설', 'In the Pool of Blood, sinners rose and sank. Among them was a man named Kandata.'],
      ['해설', 'Kandata was a great robber who had killed people and burned houses. But he had done one good deed.'],
      ['해설', 'Once on a forest path, he almost stepped on a small spider. He stopped, thinking it was also a life.'],
      ['부처', 'I should reward that one kind moment. Perhaps I can save this man.'],
      ['해설', 'The Buddha took a silver thread from a spider on a lotus leaf and lowered it down to hell.'],
      ['해설', 'In the darkness of hell, Kandata was choking and struggling. Everything was terribly silent.'],
      ['해설', 'Then, from the darkness above, a silver spider thread came gently gliding down.'],
      ['간다타', 'A spider’s thread! If I climb it, I can get out of hell!'],
      ['해설', 'Kandata grabbed the thread and climbed up and up. As a thief, he was good at this.'],
      ['해설', 'But hell and paradise were very far apart. Tired, he hung on the thread and rested.'],
      ['해설', 'When he looked down, the Pool of Blood was already far below.'],
      ['간다타', 'I did it! I did it! At this rate, I’ll get out of hell!'],
      ['해설', 'But below him, countless sinners were climbing the thread like a line of ants.'],
      ['죄인들', 'Save us too! Let us climb too!'],
      ['간다타', 'How can this thin thread hold so many people? If it breaks, I’ll fall too.'],
      ['간다타', 'Hey, this thread is mine! Who said you could climb it? Get down! Get down!'],
      ['해설', 'At that moment, the thread snapped just above Kandata’s hands.'],
      ['해설', 'Kandata spun like a top and fell headfirst into the darkness.'],
      ['해설', 'Only the broken silver thread hung shining in the sky with no moon or stars.'],
      ['해설', 'The Buddha watched all this from the edge of the pond.'],
      ['부처', 'His wish to escape alone dropped him back where he started.'],
      ['해설', 'With a sad face, the Buddha slowly began to walk again.'],
      ['해설', 'But the lotus flowers of paradise did not care. The white flowers just swayed.'],
      ['해설', 'Their sweet smell kept spreading. In paradise, it was almost noon.'],
      ['해설', 'The Spider’s Thread was published in 1918 in a Japanese children’s magazine called Red Bird.'],
    ],
  },

  'wsx-nose': {
    title: 'The Nose',
    names: { 해설: 'Narrator', 나이구: 'Zenchi Naigu', 제자: 'Disciple', 동자: 'Boy Monk' },
    outro: [
      'Naigu’s nose became short, but he suffered even more. Why?',
      'People feel a little sorry when someone escapes misfortune. In what tone does the writer criticize these watchers?',
      'Have you ever changed yourself to fit others’ eyes, only to feel more uncomfortable?',
    ],
    lines: [
      ['해설', 'Zenchi Naigu, a high priest of Ikenoo, had a nose about six inches long.'],
      ['해설', 'It hung from above his upper lip to below his chin, like a thin sausage.'],
      ['해설', 'On the outside, Naigu acted as if his nose did not matter. Inside, he always suffered.'],
      ['해설', 'At meals, a disciple had to sit across from him and lift his nose with a flat board.'],
      ['해설', 'Once, a boy monk held the board, sneezed, and the nose fell right into the rice porridge.'],
      ['동자', 'Achoo! Oh, Master, I’m so sorry!'],
      ['해설', 'The story quickly spread all the way to Kyoto. Naigu’s pride was hurt.'],
      ['해설', 'He studied the nose of every visitor. Finding even one nose like his would have comforted him.'],
      ['해설', 'He searched the holy books and old writings, but he found no saint with a long nose.'],
      ['제자', 'Master, I learned a way to shorten noses from a doctor in Kyoto.'],
      ['나이구', 'Hmm, must we really try such a thing? Well, if you insist.'],
      ['해설', 'The disciple boiled the nose in hot water, laid it on the floor, and stepped on it hard.'],
      ['제자', 'Doesn’t it hurt? The doctor told me to step on it as hard as I can.'],
      ['나이구', 'It doesn’t hurt. It feels nice, like someone stepping on an itchy spot.'],
      ['해설', 'Tiny drops of oil came out like grains of millet, and the disciple pulled them out with tweezers.'],
      ['해설', 'After one more boiling, the nose had shrunk to the size of an ordinary hooked nose.'],
      ['나이구', 'Now no one will laugh at me.'],
      ['해설', 'But it was strange. Visitors to the temple giggled at him more openly than before.'],
      ['해설', 'People pity others’ misfortune. But when someone escapes it, they feel a little disappointed.'],
      ['해설', 'In fact, they even want to push him back into it. This is the selfishness of onlookers.'],
      ['해설', 'Day by day, Naigu grew more irritable, and people spoke badly of him behind his back.'],
      ['동자', 'You bad dog! You’ll get hit on the nose! On the nose!'],
      ['해설', 'The boy monk was chasing a dog with a board. It was the same board that once held up the nose.'],
      ['해설', 'Naigu grabbed the board and scolded the boy. Then he regretted shortening his nose.'],
      ['해설', 'One night, his nose itched and felt hot. The next morning, Naigu touched his nose.'],
      ['해설', 'It hung from above his lip to below his chin, just as before.'],
      ['나이구', 'Now that it is like this, surely no one will laugh at me again.'],
      ['해설', 'Naigu let his long nose swing in the autumn wind of dawn and whispered with a light heart.'],
      ['해설', 'The Nose was published in 1916 and was praised by the novelist Natsume Soseki.'],
    ],
  },

  'wsx-duzichun': {
    title: 'Du Zichun',
    names: { 해설: 'Narrator', 두자춘: 'Du Zichun', 노인: 'Old Man', 신장: 'Divine General', 염라왕: 'King Yama', 어머니: 'Mother' },
    outro: [
      'Du Zichun called out to his mother instead of becoming an immortal. What does his choice tell us?',
      'He becomes rich three times and poor three times. What role does this repeating pattern play?',
      'Have you ever felt that living like a decent person matters more than money or success?',
    ],
    lines: [
      ['해설', 'At sunset on a spring day, a young man named Du Zichun stood blankly by the west gate of Luoyang.'],
      ['해설', 'He was once a rich man’s son, but he had wasted everything. Tonight he had no place to sleep.'],
      ['노인', 'What are you thinking about? Dig where the shadow of your head falls in the evening sun.'],
      ['해설', 'He dug there and found a cartload of gold. Overnight, Du Zichun became very rich.'],
      ['해설', 'But he lived in luxury, and in three years he was poor again. His friends left without a word.'],
      ['해설', 'The old man appeared again and gave him gold, and again Du Zichun wasted it all.'],
      ['해설', 'The third time he stood by the west gate, the old man spoke to him. Du Zichun shook his head.'],
      ['두자춘', 'I don’t want money anymore. I’m sick of people who come when I’m rich and leave when I’m poor.'],
      ['두자춘', 'You are an immortal, aren’t you? Please take me as your student.'],
      ['노인', 'You are sharp. I am Tieguanzi of Mount Emei. Very well, I will take you.'],
      ['해설', 'The old man flew him on a green bamboo stick and landed on the top of Mount Emei.'],
      ['노인', 'Sit here until I return. Whatever happens, you must not say a single word.'],
      ['해설', 'When the old man left, a tiger and a white snake attacked, and thunder and heavy rain poured down.'],
      ['신장', 'Who are you? Answer me, or you will die!'],
      ['해설', 'Du Zichun kept his mouth shut. The general stabbed him with a trident, and his soul fell into hell.'],
      ['염라왕', 'Why were you sitting on Mount Emei? Tell me the truth!'],
      ['해설', 'He suffered through valleys of fire and seas of ice, but he still did not speak.'],
      ['해설', 'Then demons dragged in two horses. Their faces were those of his dead father and mother.'],
      ['염라왕', 'Still silent? Then your parents will suffer for you. Whip them!'],
      ['해설', 'Iron whips rained down until the horses fell, covered in blood. Then a faint voice was heard.'],
      ['어머니', 'Don’t worry, my child. We are all right. If you are happy, that is enough.'],
      ['어머니', 'Whatever the king says, you don’t have to speak if you don’t want to.'],
      ['두자춘', 'Mother!'],
      ['해설', 'He ran to the horse, held its neck, and cried. When he woke up, he was back at the west gate.'],
      ['노인', 'So you cannot be my student. If you had stayed silent then, I would have taken your life.'],
      ['두자춘', 'I no longer want to be an immortal or rich. I will live honestly, like a true human being.'],
      ['노인', 'Don’t forget those words. I will give you a house and a field at the foot of Mount Tai.'],
      ['노인', 'The peach blossoms must be in full bloom there now.'],
      ['해설', 'The old man laughed happily as he said this, and then he went away.'],
      ['해설', 'Based on an old Tang story, Du Zichun was published in 1920. The writer died in 1927.'],
    ],
  },

  'wsx-kabuliwala': {
    title: 'The Kabuliwala',
    names: { 해설: 'Narrator', 아버지: 'Father', 미니: 'Mini', 라흐맛: 'Rahmat', 어머니: 'Mother' },
    outro: [
      'How does the piece of paper Rahmat carried change the meaning of the story?',
      'The father took money from the wedding and gave it to Rahmat. What feelings are in that act?',
      'Have you ever doubted someone from another country just because of how they looked?',
    ],
    lines: [
      ['해설', 'A writer in Kolkata, India, had a five-year-old daughter named Mini. Mini never stopped talking.'],
      ['미니', 'Father, they say elephants in the sky spray water with their trunks, and that’s rain. Is it true?'],
      ['해설', 'One day Mini looked out the window and shouted, Kabuliwala! Kabuliwala!'],
      ['해설', 'Rahmat, a tall peddler from Kabul in Afghanistan, was passing with a big bag on his back.'],
      ['해설', 'Mini was afraid there were children in his bag, so she ran and hid inside the house.'],
      ['해설', 'But a few days later, her father saw Mini sitting beside Rahmat and chatting away.'],
      ['라흐맛', 'Little lady, when are you going to your father-in-law’s house?'],
      ['미니', 'Are you going to your father-in-law’s house?'],
      ['라흐맛', 'I will beat my father-in-law like this. Bang! Bang!'],
      ['해설', 'Mini laughed and laughed. Rahmat always gave her a handful of raisins and almonds.'],
      ['어머니', 'Can we trust that man? They say such men carry children away in their bags.'],
      ['해설', 'Doubting strangers without reason was a common prejudice then. The father just laughed it off.'],
      ['해설', 'Then one day, Rahmat was being dragged away by policemen, with a bloody knife.'],
      ['해설', 'A customer had refused to pay for a shawl and lied about it. In the fight, Rahmat stabbed him.'],
      ['미니', 'Kabuliwala! Are you going to your father-in-law’s house?'],
      ['라흐맛', 'Yes, I’m going there. I want to beat him, but my hands are tied.'],
      ['해설', 'Rahmat went to prison. The years passed, Mini grew up, and slowly she forgot him.'],
      ['해설', 'Many years later, on the morning of Mini’s wedding, a familiar man stood at the door. It was Rahmat.'],
      ['아버지', 'We have a big event in the house today. I’m sorry, but please come another time.'],
      ['라흐맛', 'May I just see the little one’s face? Please give her these raisins. I don’t want any money.'],
      ['라흐맛', 'Sir, I have a daughter at home too. I came to see Mini because she reminds me of her.'],
      ['해설', 'He took out an old piece of paper. On it was the print of a small hand, rubbed with soot.'],
      ['해설', 'The father’s eyes grew hot. One was a peddler, one a writer, but both were fathers of daughters.'],
      ['해설', 'The father called Mini in her bridal clothes. Shyly, she lowered her head.'],
      ['라흐맛', 'Little one, so you are going to your father-in-law’s house.'],
      ['해설', 'Now Mini knew what it meant, and she blushed. Rahmat sighed, thinking his own daughter must be grown too.'],
      ['아버지', 'Take this money and go home to your daughter. If you meet her, my Mini will be blessed.'],
      ['해설', 'The father had to cut back on the lights and the band. Still, the wedding felt brighter than ever.'],
      ['해설', 'In 1913, Tagore became the first Asian to win the Nobel Prize in Literature.'],
    ],
  },

  'wsx-postmaster': {
    title: 'The Postmaster',
    names: { 해설: 'Narrator', 국장: 'Postmaster', 라탄: 'Ratan' },
    outro: [
      'For the postmaster it was a passing meeting. What was it for Ratan?',
      'Compare the postmaster’s thoughts on the boat with Ratan’s waiting. How are they different?',
      'A child with no one to lean on may cling to one word from an adult. How should we see this reality?',
    ],
    lines: [
      ['해설', 'A young postmaster who grew up in Kolkata was sent to Ulapur, a small village in Bengal.'],
      ['해설', 'The post office was a straw hut beside an indigo factory. He was lonely, like a fish out of water.'],
      ['해설', 'An orphan girl named Ratan worked for him. She was about twelve, with little hope of marriage.'],
      ['해설', 'In those days, a poor orphan girl had no one to care for her and worked for her food.'],
      ['국장', 'Ratan, please light the lamp. And tell me about your mother.'],
      ['라탄', 'I remember my father more. In the evenings he came home from work and held me.'],
      ['해설', 'The postmaster talked about his home too. Ratan began to speak of his mother and sister like neighbors.'],
      ['해설', 'Bored, the postmaster decided to teach Ratan to read. She learned quickly.'],
      ['해설', 'One rainy season, the postmaster caught a bad fever. He longed for his mother’s gentle hand.'],
      ['해설', 'Ratan was no longer a little girl then. She sat by his bed all night and cooked porridge for him.'],
      ['라탄', 'Do you feel a little better? It’s time for your medicine.'],
      ['해설', 'A few days later, the fever went down. But the postmaster decided to leave the village.'],
      ['해설', 'He asked for a transfer, but it was refused. In the end, he quit his job.'],
      ['국장', 'Ratan, I’m leaving tomorrow.'],
      ['라탄', 'Will you come back?'],
      ['국장', 'No, I will never come back.'],
      ['해설', 'Ratan asked nothing more. The lamp flickered, and rain dripped from the roof into a pot.'],
      ['라탄', 'Can’t you take me to your home?'],
      ['국장', 'Ha ha, how could that ever happen?'],
      ['해설', 'The postmaster did not know how much his laugh hurt Ratan.'],
      ['해설', 'The next morning, he asked the new postmaster to take good care of Ratan.'],
      ['국장', 'Ratan, here is part of my pay. Live on this for a while.'],
      ['라탄', 'No, please don’t give me anything. I don’t need anything.'],
      ['해설', 'Ratan fell at his feet and cried, and then she ran away.'],
      ['해설', 'As the boat floated down the river, his heart ached. Should he go back and bring her?'],
      ['해설', 'But the sail had already caught the wind. He told himself that life is full of partings like this.'],
      ['해설', 'Ratan had no such comfort. She wandered around the post office, waiting for him to return.'],
      ['해설', 'The human heart clings to false hope, and in the end that hope hurts it again.'],
      ['해설', 'Tagore published The Postmaster in 1891.'],
    ],
  },
};
