// 청소년 영어 원고: 몬테크리스토 백작 1~10화 (stories/teen-monte.js). 문장은 자체 각색.
// lines 의 첫 칸은 한국어 이야기 cast 의 이름 그대로.
export default {
  'mc-01': {
    title: 'The Count of Monte Cristo, Part 1',
    names: { 해설: 'Narrator', 모렐: 'Monsieur Morrel', 당테스: 'Edmond Dantès', 당글라르: 'Danglars', 메르세데스: 'Mercédès', 페르낭: 'Fernand', 카드루스: 'Caderousse' },
    outro: [
      'What effect does the writer create by bringing misfortune at the very moment Dantès is happiest?',
      'What does the scene of Danglars writing with his left hand show about what kind of man he is?',
      'What do we need so that jealousy of someone’s success does not turn into action?',
    ],
    lines: [
      ['해설', 'In February 1815, the trading ship Pharaon sailed into Marseille, a port in the south of France.'],
      ['해설', 'The man leading the ship was its nineteen-year-old first mate, Edmond Dantès.'],
      ['해설', 'The captain had died of illness during the voyage, so Dantès took command and brought the ship home safely.'],
      ['모렐', 'Well done, Dantès. From the next voyage, you will be captain.'],
      ['당테스', 'Thank you, Monsieur Morrel. How happy my father will be!'],
      ['해설', 'Danglars, the ship’s accountant, overheard them. He bitterly envied young Dantès’s success.'],
      ['당글라르', 'That boy, a captain? I won’t let him stand in my way.'],
      ['해설', 'Before he died, the captain had asked Dantès to stop at the island of Elba and deliver a package.'],
      ['해설', 'On Elba lived Napoleon, who had been forced to give up his throne as emperor.'],
      ['해설', 'There Dantès was given a letter for someone in Paris. He did not think much about it.'],
      ['해설', 'After landing, he first visited his old father, then hurried to the Catalan village by the sea.'],
      ['메르세데스', 'Edmond! You’re back safe. I watched the sea and prayed every day.'],
      ['해설', 'Mercédès’s cousin Fernand was there too. He had loved her for a long time.'],
      ['페르낭', 'Mercédès only looks at him. She never even glances at me.'],
      ['해설', 'That evening, Danglars sat down at a tavern with Fernand and Caderousse, a tailor who lived nearby.'],
      ['당글라르', 'What if someone reported that Dantès brought back a letter from Napoleon’s side?'],
      ['해설', 'At that time, France was ruled by a king again, and helping Napoleon was a serious crime.'],
      ['해설', 'To hide his handwriting, Danglars wrote the letter of accusation with his left hand.'],
      ['카드루스', 'This joke has gone too far. Dantès is a good friend.'],
      ['해설', 'Danglars pretended to crumple the letter and throw it away. Fernand secretly picked it up.'],
      ['해설', 'Caderousse was drunk. He saw it all but never said a word.'],
      ['해설', 'The next day, Dantès and Mercédès held their engagement party. Everyone raised a glass.'],
      ['당테스', 'Mercédès, soon you’ll be my wife. I’m the luckiest man in the world.'],
      ['해설', 'Suddenly the door opened and officers rushed in. They called out Dantès’s name.'],
      ['메르세데스', 'Edmond! What has he done wrong? Why are you doing this?'],
      ['당테스', 'Don’t worry. There must be some mistake. I’ll be back soon.'],
      ['해설', 'Fernand turned his head away, and Danglars smiled quietly.'],
      ['해설', 'But the prosecutor who could clear up the mistake was the son of the man the letter was meant for.'],
      ['해설', 'Dumas published The Count of Monte Cristo in a newspaper from 1844 to 1846.'],
    ],
  },

  'mc-02': {
    title: 'The Count of Monte Cristo, Part 2',
    names: { 해설: 'Narrator', 빌포르: 'Villefort', 당테스: 'Edmond Dantès', 모렐: 'Monsieur Morrel', 아버지: 'Old Dantès' },
    outro: [
      'Did Villefort lock Dantès away for the sake of justice or for his own career?',
      'How does Villefort’s kind voice as he burns the letter reveal his character?',
      'What do we need so that people in power cannot bend their judgment for their own gain?',
    ],
    lines: [
      ['해설', 'Last time, Dantès was arrested at his engagement party because of a report by jealous men.'],
      ['해설', 'The man who questioned him was Villefort, a young deputy prosecutor. It was his engagement day, too.'],
      ['해설', 'Villefort dreamed of rising in the world by marrying the daughter of a royalist noble family.'],
      ['빌포르', 'You have been reported as one of Napoleon’s men. Tell me the truth.'],
      ['당테스', 'I know nothing about politics, sir. I only did what my dying captain asked.'],
      ['해설', 'Villefort liked this honest young man. He thought he could let him go.'],
      ['빌포르', 'Where is the letter now? Who were you told to give it to?'],
      ['당테스', 'Here it is. I was to give it to a Monsieur Noirtier in Paris.'],
      ['해설', 'Villefort’s face went white. Noirtier was his own father.'],
      ['해설', 'His father supported Napoleon, and the letter was linked to the emperor’s plan to return.'],
      ['빌포르', 'Does anyone else know about this letter? Did you read it?'],
      ['당테스', 'No one knows. I never even opened the envelope.'],
      ['해설', 'Villefort burned the letter in the candle flame. Then he spoke in a gentle voice.'],
      ['빌포르', 'Now there is no evidence. Stay here just for tonight, and you will soon be free.'],
      ['해설', 'Dantès thanked him. But late that night, he was put on a boat and taken out to sea.'],
      ['해설', 'The boat was heading for the Château d’If, a fortress on a rocky island off Marseille.'],
      ['당테스', 'Prison without a trial? The prosecutor said I would be set free soon!'],
      ['해설', 'The Château d’If was a prison for people thought to be dangerous to the nation.'],
      ['해설', 'Villefort rushed to Paris and warned the king of Napoleon’s plan. He won the king’s trust.'],
      ['해설', 'Not long after, Napoleon really did escape from Elba and return to France.'],
      ['해설', 'During the Hundred Days when the emperor ruled again, Morrel went to Villefort to plead for Dantès.'],
      ['모렐', 'Dantès was arrested for helping the emperor. Now you must set him free.'],
      ['해설', 'Villefort had Morrel write a request that made Dantès look like a passionate supporter of the emperor.'],
      ['해설', 'When Napoleon fell again after Waterloo, that request became a chain that held Dantès in prison.'],
      ['해설', 'In Marseille, the old father waited for his son and slowly stopped eating.'],
      ['아버지', 'Until Edmond comes back, I cannot swallow a thing.'],
      ['해설', 'Some time later, the father died, calling his son’s name.'],
      ['해설', 'Year after year, the cell door stayed shut. Then one night, a sound came from behind the wall.'],
      ['해설', 'The Château d’If is a real old fortress on a small island off Marseille.'],
    ],
  },

  'mc-03': {
    title: 'The Count of Monte Cristo, Part 3',
    names: { 해설: 'Narrator', 당테스: 'Edmond Dantès', 감독관: 'Inspector', 파리아: 'Abbé Faria' },
    outro: [
      'Was meeting Abbé Faria a hope for Dantès, or the beginning of his revenge?',
      'What does the phrase the cell became a school show about the two men?',
      'What can we do to keep someone who has been treated unfairly from falling into despair?',
    ],
    lines: [
      ['해설', 'Last time, Villefort locked the innocent Dantès in the Château d’If to protect his own father.'],
      ['해설', 'For the first few years, Dantès asked himself again and again what he had done wrong.'],
      ['해설', 'When an inspector came to visit the prison, he begged for at least a trial.'],
      ['당테스', 'If I am guilty, I will accept punishment. Just tell me what my crime is.'],
      ['감독관', 'The record only says you are a dangerous supporter of Napoleon. I can tell you nothing more.'],
      ['해설', 'After that, no news came. Dantès had prayed, but slowly he began to blame heaven.'],
      ['해설', 'In despair, he secretly threw away his food and decided to starve himself.'],
      ['해설', 'One night, as his strength was almost gone, he heard a scratching sound behind the wall.'],
      ['해설', 'Someone was digging. Dantès began to eat again and started digging from his side, too.'],
      ['해설', 'A few days later, a stone in the floor lifted, and an old man with a white beard looked out.'],
      ['파리아', 'Oh dear, I meant to dig to the outside, but I got my measurements wrong. I am Abbé Faria.'],
      ['해설', 'Faria was a scholar from Italy. For years, he had been secretly digging a tunnel.'],
      ['해설', 'He made pens from fish bones and was writing a book on cloth torn from his shirts.'],
      ['당테스', 'Father, please teach me too. I do not want to rot away in this darkness.'],
      ['해설', 'From that day, the cell became a school. Faria taught languages, history, and science.'],
      ['해설', 'Dantès learned amazingly fast. In a few years, he could speak several languages.'],
      ['해설', 'One day, Faria asked Dantès to tell him again everything about the day of his arrest.'],
      ['파리아', 'Who would lose if you became captain? Who else loved your fiancée?'],
      ['당테스', 'Danglars and Fernand. Surely not those two?'],
      ['파리아', 'The letter was for Noirtier, you said? What was the prosecutor’s name?'],
      ['당테스', 'It was Villefort. So that was why he was so kind as he burned the letter.'],
      ['파리아', 'Noirtier is Villefort’s father. He buried you to protect his own family.'],
      ['해설', 'Dantès said nothing for a long time. That night, for the first time, he thought of revenge.'],
      ['파리아', 'I am not sure I was right to tell you. Hatred eats away first at the one who holds it.'],
      ['해설', 'The two decided to dig an escape route together. But Faria had a hidden illness.'],
      ['해설', 'One night, his body suddenly went stiff and he collapsed. Dantès barely woke him with medicine.'],
      ['파리아', 'If another attack comes, it will be my end. Before that, I have something to give you.'],
      ['해설', 'What Faria took out was an old sheet of paper, half burned.'],
      ['해설', 'Dumas wrote this novel with the help of partners such as Auguste Maquet.'],
    ],
  },

  'mc-04': {
    title: 'The Count of Monte Cristo, Part 4',
    names: { 해설: 'Narrator', 파리아: 'Abbé Faria', 당테스: 'Edmond Dantès', 간수: 'Jailer', 자코포: 'Jacopo' },
    outro: [
      'In a prison only the dead could leave, what does his decision to become a dead man mean?',
      'How does the scene where he does not recognize his face in the mirror show fourteen lost years?',
      'If someone cannot go back to who they were after a long ordeal, is that a loss?',
    ],
    lines: [
      ['해설', 'Last time, Dantès learned from Abbé Faria and found out who had betrayed him.'],
      ['해설', 'The paper Faria unfolded was a record of a treasure secretly hidden by the Spada family of Italy.'],
      ['파리아', 'This treasure lies under the rocks of a small island called Monte Cristo. I found this paper long ago.'],
      ['당테스', 'So this treasure story is why people called you mad.'],
      ['파리아', 'Yes. But you are like a son to me, so this secret is now yours.'],
      ['해설', 'Monte Cristo was a rocky island off the coast of Italy where no one lived.'],
      ['해설', 'More than treasure, Dantès longed for the day he could see the open sky with Faria.'],
      ['해설', 'But in the fourteenth year of Dantès’s imprisonment, Faria’s third attack came.'],
      ['파리아', 'Edmond, go. Find your freedom, and please be happy.'],
      ['해설', 'Holding Dantès’s hand, Faria died. Dantès was alone again.'],
      ['해설', 'The jailers sewed Faria’s body into a sack and left. They said the burial would be at night.'],
      ['당테스', 'If only the dead can leave this place, then I will be the dead man.'],
      ['해설', 'Dantès laid Faria on his own bed, got into the sack instead, and sewed it shut from inside.'],
      ['해설', 'Holding the knife Faria had left him, he held his breath. At night, the jailers lifted the sack.'],
      ['간수', 'This old man is heavier than he looks.'],
      ['해설', 'They tied a heavy iron ball to the foot of the sack. The graveyard of the Château d’If was the sea.'],
      ['해설', 'The sack was thrown from a high rock into the sea. Dantès sank fast into the water.'],
      ['해설', 'He cut the sack open with the knife and cut the rope. Out of breath, he finally rose to the surface.'],
      ['해설', 'After swimming for hours through the stormy sea at night, he reached the rocks of a nearby island.'],
      ['해설', 'The next morning, a small passing boat pulled him out of the sea.'],
      ['자코포', 'Who are you? We heard a cannon from the Château d’If earlier. Did you come from there?'],
      ['당테스', 'I am a sailor from Malta. My ship was wrecked. Let me work on this boat.'],
      ['해설', 'It was a smugglers’ boat. With his great skill, Dantès soon won the crew’s trust.'],
      ['해설', 'Looking in a mirror for the first time in fourteen years, Dantès did not recognize his own face.'],
      ['해설', 'The cheerful young man of nineteen was gone. In his place was a pale, hard-faced man of thirty-three.'],
      ['당테스', 'Danglars, Fernand, Villefort. I will not forget those names for a single day.'],
      ['해설', 'He worked on the smugglers’ boat and waited for the day he could go to Monte Cristo.'],
      ['해설', 'At last, the boat came near the island. Dantès pretended to be hurt and stayed there alone.'],
      ['해설', 'On the empty rocky island, he began checking the rocks one by one, following Faria’s paper.'],
      ['해설', 'The island of Montecristo really exists, off the coast of Tuscany in Italy.'],
    ],
  },

  'mc-05': {
    title: 'The Count of Monte Cristo, Part 5',
    names: { 해설: 'Narrator', 당테스: 'Edmond Dantès', 카드루스: 'Caderousse', 모렐: 'Monsieur Morrel', 쥘리: 'Julie' },
    outro: [
      'Why did Dantès help the Morrel family before taking revenge?',
      'What feeling does the scene of Morrel’s old purse returning to him create?',
      'How is repaying kindness different from paying back a wound?',
    ],
    lines: [
      ['해설', 'Last time, Dantès escaped from the Château d’If and stayed alone on the island of Monte Cristo.'],
      ['해설', 'Searching between the rocks, Dantès found a heavy chest deep inside a cave.'],
      ['해설', 'When he opened the lid, gold coins and jewels shone brightly in the torchlight.'],
      ['당테스', 'Father Faria, are you watching? This is the second life you have given me.'],
      ['해설', 'Now enormously rich, Dantès first decided to find out what had happened over the years.'],
      ['해설', 'Disguised as a priest called Abbé Busoni, he visited a country inn in the south. The innkeeper was Caderousse.'],
      ['당테스', 'I have come with the last wishes of a man named Dantès. He died in prison.'],
      ['카드루스', 'Poor Edmond! His father died of hunger while waiting for his son.'],
      ['해설', 'When he heard about a diamond Dantès had left, Caderousse told him everything.'],
      ['카드루스', 'Danglars wrote the accusation, and Fernand sent it. I didn’t stop them.'],
      ['카드루스', 'Fernand rose in the army, became a count, and married Mercédès. Danglars became a banker and a baron.'],
      ['해설', 'Dantès just listened quietly. The glass in his hand shook very slightly.'],
      ['카드루스', 'Only Monsieur Morrel helped the old man to the end. But now his company is about to go under.'],
      ['해설', 'Dantès gave Caderousse the diamond and left. He planned to repay kindness first.'],
      ['해설', 'In Marseille, the Morrel company had lost ship after ship, and its debts were piling up.'],
      ['해설', 'Disguised as an English bank clerk, Dantès bought up Morrel’s debts and gave him three more months.'],
      ['모렐', 'Three months? Thank you. If only the Pharaon comes back by then.'],
      ['해설', 'But the Pharaon sank at sea. When the day came, Morrel had no money.'],
      ['해설', 'That morning, Morrel sat alone in his study, even thinking of ending his life.'],
      ['해설', 'Around then, his daughter Julie received a note signed Sinbad the Sailor.'],
      ['쥘리', 'It says there’s a red silk purse in the old house where Grandfather Dantès lived!'],
      ['해설', 'Inside the purse Julie found were the paid-off debt papers and a large diamond.'],
      ['해설', 'It was the purse Morrel had secretly left long ago to help Dantès’s father.'],
      ['해설', 'Just then, cheers rang out from the harbor. A new ship exactly like the old Pharaon was sailing in.'],
      ['모렐', 'If this is not a dream, who on earth has done this for us?'],
      ['해설', 'From a far corner of the dock, Dantès quietly watched the scene.'],
      ['당테스', 'I have repaid the good man in full. Now it is the turn of those who destroyed me.'],
      ['해설', 'He boarded a small boat and disappeared. Years later, he would appear as the Count of Monte Cristo.'],
      ['해설', 'In the same year, 1844, Dumas also published The Three Musketeers as a serial.'],
    ],
  },

  'mc-06': {
    title: 'The Count of Monte Cristo, Part 6',
    names: { 해설: 'Narrator', 알베르: 'Albert', 당테스: 'Count of Monte Cristo', 밤파: 'Luigi Vampa', 페르낭: 'Fernand', 메르세데스: 'Mercédès', 하이데: 'Haydée' },
    outro: [
      'When the Count saved Albert, his enemy’s son, was it kindness or part of a plan?',
      'Without words, what feeling does the scene of refusing the grapes show?',
      'When we read about a time when people were bought and sold, what should we think about today?',
    ],
    lines: [
      ['해설', 'Last time, Dantès found the treasure, secretly saved the Morrel family, and vanished.'],
      ['해설', 'During the Rome carnival of 1838, some young nobles from Paris were staying at a hotel.'],
      ['해설', 'One of them was Albert de Morcerf, the only son of Fernand and Mercédès.'],
      ['해설', 'Nearby stayed a mysterious guest, the Count of Monte Cristo. He was pale and spoke little.'],
      ['알베르', 'Who are you, Count? Your money and your knowledge seem to have no end.'],
      ['당테스', 'I am only a man who has seen much and endured much.'],
      ['해설', 'On the last night of the carnival, Albert was tricked and captured by a gang of bandits.'],
      ['해설', 'Their leader was Luigi Vampa, a bandit famous around Rome. He demanded a large ransom.'],
      ['해설', 'Hearing the news, the Count went to the old underground tombs where the bandits were hiding.'],
      ['밤파', 'Count! I didn’t know he was your friend. Please forgive me.'],
      ['해설', 'Vampa had once owed the Count his life. Albert was released at once.'],
      ['알베르', 'How can I repay you? If you come to Paris, I will introduce you to all of high society.'],
      ['당테스', 'Very well. Three months from now, I will come to your house at half past ten in the morning.'],
      ['해설', 'On the promised day, at exactly that time, the Count appeared at Albert’s house in Paris.'],
      ['해설', 'Albert introduced the Count to his parents. Fernand, now the Count de Morcerf, did not recognize him.'],
      ['페르낭', 'Thank you for saving my son. I have spent my whole life as a soldier serving my country.'],
      ['해설', 'But the moment Mercédès saw him, her face turned white.'],
      ['해설', 'Later, at a ball at the Morcerf house, Mercédès offered the Count some grapes.'],
      ['당테스', 'Thank you, but no.'],
      ['메르세데스', 'Then at least have this peach. Will you eat nothing at all in this house?'],
      ['당테스', 'In the East, they say those who share bread and salt under one roof can never be enemies.'],
      ['해설', 'Mercédès asked no more. She already knew who he was.'],
      ['해설', 'A Greek girl named Haydée lived in the Count’s house.'],
      ['해설', 'She had been sold as a slave, and the Count paid to take her away. People were bought and sold then.'],
      ['해설', 'The novel paints Haydée as a mysterious Eastern woman. This, too, reflects how Europe saw the East then.'],
      ['하이데', 'My lord, every time I hear that man’s name, my heart still aches.'],
      ['당테스', 'Haydée, you are not a slave. You are free to leave whenever you wish.'],
      ['해설', 'The Count’s eyes now turned to the homes of the banker Danglars and the prosecutor Villefort.'],
      ['해설', 'Dumas’s father, Thomas-Alexandre Dumas, was a general during the French Revolution.'],
    ],
  },

  'mc-07': {
    title: 'The Count of Monte Cristo, Part 7',
    names: { 해설: 'Narrator', 당글라르: 'Danglars', 당테스: 'Count of Monte Cristo', 베르투초: 'Bertuccio', 막시밀리앙: 'Maximilien', 발랑틴: 'Valentine', 빌포르부인: 'Madame de Villefort' },
    outro: [
      'The Count does not harm his enemies directly but lets their weaknesses come out. Is that fair?',
      'What role does Noirtier, who speaks only with his eyes, play in the story?',
      'Today, in what forms can a single false rumor move huge amounts of money?',
    ],
    lines: [
      ['해설', 'Last time, the Count appeared in Paris society, and Mercédès recognized him.'],
      ['해설', 'The Count went to Danglars’s bank and asked for unlimited credit.'],
      ['당글라르', 'Unlimited? Who has ever heard of such a deal?'],
      ['당테스', 'Then I will find another bank, if yours is not strong enough.'],
      ['해설', 'His pride hurt, Danglars finally agreed. He did not recognize the Count.'],
      ['해설', 'At that time, France had signal towers that sent news far away by moving arms on top.'],
      ['해설', 'The Count paid a poor signalman at a country tower to send false news.'],
      ['해설', 'The news said there was a great uprising in Spain. The rumor soon reached Danglars.'],
      ['해설', 'Danglars hurried to sell his Spanish bonds. The next day, the news proved to be false.'],
      ['당글라르', 'How did this happen? So much money lost overnight!'],
      ['해설', 'Around then, the Count introduced Andrea Cavalcanti, a young Italian noble, to society.'],
      ['해설', 'Danglars believed he was a rich noble and wanted him to marry his daughter Eugénie.'],
      ['해설', 'But Andrea’s real name was Benedetto. He was a convict who had escaped from prison.'],
      ['해설', 'Meanwhile, the Count bought a house in Auteuil, near Paris. His steward Bertuccio trembled when he saw it.'],
      ['베르투초', 'Count, long ago in this garden, a man buried a newborn baby in a box.'],
      ['베르투초', 'That man was the prosecutor Villefort. I dug up the box and saved the baby.'],
      ['해설', 'That baby was Benedetto. The Count kept this secret in his heart.'],
      ['해설', 'Villefort’s house had its shadows too. His father Noirtier was paralyzed and could speak only with his eyes.'],
      ['해설', 'Villefort’s daughter Valentine cared for her grandfather and secretly loved Morrel’s son Maximilien.'],
      ['막시밀리앙', 'Valentine, your father has chosen another man for you. What should I do?'],
      ['발랑틴', 'Grandfather will help us. No one can win against his eyes.'],
      ['해설', 'But one by one, people in Villefort’s house fell ill and died: Valentine’s grandparents and an old servant.'],
      ['해설', 'The doctor said poison was used. The killer was Madame de Villefort, Valentine’s stepmother.'],
      ['빌포르부인', 'All the money in this house must go to my son Édouard.'],
      ['해설', 'She had learned about poisons from an earlier talk with the Count.'],
      ['해설', 'The Count guessed what that talk might spark, but he did not step in.'],
      ['당테스', 'Villefort, you have lived by judging the crimes of others. Can you not see the crimes in your own house?'],
      ['해설', 'Meanwhile, a short newspaper article appeared that dug up Fernand’s past.'],
      ['해설', 'Dumas was born in 1802 and died in 1870.'],
    ],
  },

  'mc-08': {
    title: 'The Count of Monte Cristo, Part 8',
    names: { 해설: 'Narrator', 페르낭: 'Fernand', 하이데: 'Haydée', 알베르: 'Albert', 메르세데스: 'Mercédès', 당테스: 'Count of Monte Cristo' },
    outro: [
      'Was Haydée’s testimony personal revenge, or justice that brought a hidden truth to light?',
      'What power does the scene have where Mercédès calls the name Edmond after more than twenty years?',
      'How should children face the wrongs of their parents once they learn about them?',
    ],
    lines: [
      ['해설', 'Last time, the Count caused Danglars a great loss and uncovered the secrets of Villefort’s family.'],
      ['해설', 'The newspaper article was about the fall of a castle at Janina in Greece long ago.'],
      ['해설', 'It said a French officer named Fernand had betrayed Ali Pasha, who trusted him, to his enemies.'],
      ['해설', 'Ali Pasha lost his life, and his wife and young daughter were sold as slaves.'],
      ['해설', 'The Chamber of Peers called Fernand, the Count de Morcerf, to answer for this.'],
      ['페르낭', 'It is all lies. I tried to protect the Pasha to the end. Bring a witness if you have one.'],
      ['해설', 'Just then, a woman in a veil walked in. It was Haydée.'],
      ['하이데', 'I am the daughter of Ali Pasha. The man who betrayed my father is standing right there.'],
      ['하이데', 'He also sold my mother and me to a slave trader. Here is the bill of sale.'],
      ['해설', 'Fernand could not say a word and left the hall. The Chamber found him guilty.'],
      ['해설', 'Albert discovered that the Count of Monte Cristo was behind it all.'],
      ['알베르', 'Count, you are the one who destroyed my father. I challenge you to a duel tomorrow morning!'],
      ['해설', 'That night, Mercédès came to the Count’s house, wearing a veil.'],
      ['메르세데스', 'Edmond, please don’t kill my son.'],
      ['해설', 'After more than twenty years, she called him by that name. For a while, the Count could not answer.'],
      ['당테스', 'Edmond Dantès died in the Château d’If. Because of one letter.'],
      ['해설', 'The Count laid the old letter of accusation before her. Mercédès learned the truth for the first time.'],
      ['메르세데스', 'I believed you were dead. Since then, I have lived half dead myself.'],
      ['당테스', 'Very well. Tomorrow I will not dodge your son’s bullet.'],
      ['해설', 'He decided to let his enemy’s son live and to die himself. That night he wrote his will.'],
      ['해설', 'The next morning, Albert came to the dueling ground and offered an apology instead of a shot.'],
      ['알베르', 'I know what my father did. You had your reasons. I ask your forgiveness.'],
      ['해설', 'Albert and Mercédès decided to leave that house and everything they had received from Fernand.'],
      ['해설', 'Furious, Fernand rushed to the Count’s house. The Count met him dressed in old sailor’s clothes.'],
      ['당테스', 'Fernand, do you remember this face? The sailor who was going to marry Mercédès?'],
      ['페르낭', 'Edmond Dantès!'],
      ['해설', 'Fernand staggered home. His wife and son were just leaving him.'],
      ['해설', 'A moment later, a single gunshot rang out from his room. Fernand had taken his own life.'],
      ['해설', 'Now the Count’s steps reached the door of the prosecutor Villefort.'],
      ['해설', 'Dumas’s son, Alexandre Dumas fils, wrote The Lady of the Camellias.'],
    ],
  },

  'mc-09': {
    title: 'The Count of Monte Cristo, Part 9',
    names: { 해설: 'Narrator', 당테스: 'Count of Monte Cristo', 발랑틴: 'Valentine', 막시밀리앙: 'Maximilien', 빌포르: 'Villefort', 베네데토: 'Benedetto' },
    outro: [
      'What does the Count’s shock at the death of an innocent child say about revenge?',
      'What irony is created when a prosecutor who judged others is judged in his own court?',
      'How can we notice when we are crossing a line in the name of justice?',
    ],
    lines: [
      ['해설', 'Last time, Fernand’s old betrayal came to light. He lost his family and took his own life.'],
      ['해설', 'Around then, in Villefort’s house, even Valentine drank poisoned water and fell ill.'],
      ['해설', 'The Count had bought the house next door and was secretly watching over Valentine from behind the wall.'],
      ['해설', 'One night, the Count quietly appeared in Valentine’s room.'],
      ['당테스', 'Do not be afraid. I am Maximilien’s friend. If you want to live, swallow this pill.'],
      ['당테스', 'For a while, you will look as if you have died. Whatever happens, trust me.'],
      ['발랑틴', 'If I can see Maximilien again, I will do anything.'],
      ['해설', 'The next morning, Valentine lay as if her breath had stopped. The house was filled with weeping.'],
      ['막시밀리앙', 'Valentine is gone. What is the point of living on alone?'],
      ['해설', 'At the same time, Andrea Cavalcanti was signing a marriage contract at Danglars’s house when he had to flee.'],
      ['해설', 'He was suspected of killing Caderousse, his old prison mate, who had tried to rob the Count’s house.'],
      ['해설', 'Andrea was caught, and the prosecutor at his trial was Villefort. Villefort already knew his wife’s crime.'],
      ['빌포르', 'I know you used poison. Before I return from court, choose your own way out.'],
      ['해설', 'The trial began. The judge asked the accused for his name and his father’s name.'],
      ['베네데토', 'My name is Benedetto. My father is the prosecutor sitting right there, Villefort.'],
      ['베네데토', 'He buried me as a baby in the garden at Auteuil. Even so, I survived.'],
      ['해설', 'The courtroom buzzed. Villefort sat frozen for a long time, then slowly stood up.'],
      ['빌포르', 'What this young man says is true. I will wait for the day I am judged.'],
      ['해설', 'Villefort rushed home. He meant to take back his words to his wife and flee far away with her.'],
      ['해설', 'But it was too late. His wife had already taken poison, and taken little Édouard with her.'],
      ['해설', 'Just then, the Count entered the house. At last, he told Villefort his real name.'],
      ['당테스', 'I am Edmond Dantès, the man you buried in the Château d’If.'],
      ['빌포르', 'Dantès! Then look. Look at what your revenge has left!'],
      ['해설', 'Seeing the dead child, the Count froze. The child had done nothing wrong.'],
      ['해설', 'Villefort ran out to the garden and began digging. He never came back to his senses.'],
      ['당테스', 'I believed I was doing the will of heaven. But have I gone too far?'],
      ['해설', 'For the first time, the Count’s heart wavered. He thought of the last name left.'],
      ['해설', 'At that moment, the ruined Danglars was secretly fleeing Paris with his remaining money.'],
      ['해설', 'In 2002, Dumas’s remains were moved to the Panthéon in Paris.'],
    ],
  },

  'mc-10': {
    title: 'The Count of Monte Cristo, Part 10',
    names: { 해설: 'Narrator', 메르세데스: 'Mercédès', 당테스: 'Count of Monte Cristo', 당글라르: 'Danglars', 밤파: 'Luigi Vampa', 막시밀리앙: 'Maximilien', 발랑틴: 'Valentine', 하이데: 'Haydée' },
    outro: [
      'After finishing his revenge, why did the Count leave a message of waiting and hope instead of hatred?',
      'If you place the letter of accusation in Part 1 next to the farewell letter in Part 10, what difference do you see?',
      'How can our society support people going through times when they cannot see what lies ahead?',
    ],
    lines: [
      ['해설', 'Last time, Villefort’s hidden crime came out and he lost everything, and the Count wavered for the first time.'],
      ['해설', 'The Count returned to Marseille. Albert had already joined the army and left for Africa.'],
      ['해설', 'Mercédès was living alone in the small house where Dantès’s father once lived.'],
      ['메르세데스', 'Edmond, I did not wait for you to the end. That has been the mistake of my life.'],
      ['당테스', 'It was not your fault. We both had our lives stolen by one letter someone else wrote.'],
      ['메르세데스', 'Now I will live praying for my son. I pray you find peace too.'],
      ['해설', 'And so they parted. The Count looked around the Château d’If one last time, then headed for Italy.'],
      ['해설', 'Around then, the bankrupt Danglars fled to Rome with his remaining money and was caught by the bandit Vampa.'],
      ['해설', 'The bandits did not beat him in their cave. They just charged crazy prices for every meal.'],
      ['당글라르', 'One chicken costs as much as a house? This is robbery!'],
      ['밤파', 'That is the price here. If you do not like it, you need not eat.'],
      ['해설', 'With every meal his money shrank. Starving to save his last coins, he finally fell to his knees.'],
      ['당글라르', 'Take it all. Just please spare my life.'],
      ['해설', 'Then a man stepped out of the darkness.'],
      ['당테스', 'Danglars, I am Edmond Dantès, locked away for fourteen years because of your letter.'],
      ['당테스', 'My father had to endure to the end the hunger you have felt for a few days. Still, I forgive you.'],
      ['해설', 'The Count gave him back his remaining money and let him go. Danglars’s hair had turned white.'],
      ['해설', 'Maximilien had lost Valentine and wished only to die. The Count had asked him to wait one month.'],
      ['해설', 'On the promised day, Maximilien came to the island of Monte Cristo at the Count’s call.'],
      ['막시밀리앙', 'This is the promised day. Now please send me to her side.'],
      ['해설', 'The Count led him to a room inside the cave. There stood Valentine, alive.'],
      ['발랑틴', 'Maximilien! The Count protected me.'],
      ['해설', 'The next morning, the Count was already gone. All that was left was a short letter.'],
      ['당테스', 'Only those who have walked through a long night know how precious morning is. I leave this island to you both.'],
      ['당테스', 'Hold on, even on days when you cannot see tomorrow. Wait and hope, and believe that tomorrow will come.'],
      ['해설', 'Far away on the horizon, a white sail grew smaller. Haydée was by the Count’s side.'],
      ['하이데', 'Wherever you go, I will be by your side.'],
      ['해설', 'The man who lost everything because of one letter left behind hope with another letter.'],
      ['해설', 'Dumas built a mansion near Paris and named it the Château de Monte-Cristo.'],
    ],
  },
};
