// 청소년 영어 원고 (중학생 이상). 키 = stories/teen-talk1.js 의 이야기 id.
// 과학 교양 강연을 한국어 원고의 흐름대로 쉬운 영어로 새로 씀(강연자와 학생의 대화). 사실 근거는 한국어 파일 주석 참고.
export default {
  'tk1-atom': {
    title: 'Inside the Atom',
    names: { 해설: 'Narrator', 강연자: 'Lecturer', 학생: 'Student' },
    outro: [
      'What do we count inside an atom to decide which element it is?',
      'If an atom is almost empty, why doesn’t your hand pass through the desk when you press on it?',
      'Like the scientists who guessed at things they could not see, when have you used evidence to work something out?',
    ],
    lines: [
      ['해설', 'Today’s science talk is about atoms, the tiny pieces that make up everything around us.'],
      ['해설', 'Let us step into a small world that our eyes cannot see.'],
      ['강연자', 'The lead in your pencil, the water you drink, and the air you breathe are all made of atoms.'],
      ['강연자', 'Atoms are very small. One is only about one hundred-millionth of a centimeter across.'],
      ['강연자', 'For a long time, people thought atoms could not be broken into smaller parts.'],
      ['강연자', 'But in 1897, the British scientist J. J. Thomson found the electron, far lighter than any atom.'],
      ['강연자', 'For the first time, people learned that something smaller was hidden inside the atom.'],
      ['학생', 'Then what does the inside of an atom look like? Is it packed full of electrons?'],
      ['강연자', 'Good question. Rutherford’s team answered it with the famous gold foil experiment.'],
      ['강연자', 'They shot tiny particles at a very thin sheet of gold. Most of them went straight through.'],
      ['강연자', 'But once in a while, a few particles bounced sharply back.'],
      ['강연자', 'This meant the atom is mostly empty, with a small, heavy center.'],
      ['강연자', 'Rutherford shared this idea in 1911. That center is what we call the nucleus.'],
      ['강연자', 'The nucleus is made of positive protons and neutrons, which have no charge.'],
      ['강연자', 'James Chadwick found the neutron in 1932. Around the nucleus are the electrons.'],
      ['강연자', 'Electrons are negative, and they are about 1,800 times lighter than protons.'],
      ['강연자', 'A normal atom has the same number of protons and electrons, so it has no overall charge.'],
      ['학생', 'So what makes a gold atom different from an oxygen atom?'],
      ['강연자', 'The number of protons in the nucleus. We call it the atomic number.'],
      ['강연자', 'One proton means hydrogen. Six means carbon, eight means oxygen, and seventy-nine means gold.'],
      ['강연자', 'Atoms with the same number of protons but different numbers of neutrons are called isotopes.'],
      ['강연자', 'Some carbon atoms have six neutrons, and some have eight. Both are still carbon.'],
      ['강연자', 'Now, imagine an atom made as big as a huge sports stadium.'],
      ['강연자', 'The nucleus would be no bigger than a small marble in the middle of the field.'],
      ['강연자', 'Yet almost all of the atom’s mass is packed into that tiny nucleus.'],
      ['강연자', 'So our bodies, and this lecture hall too, are mostly empty space.'],
      ['해설', 'Step by step, through experiments and careful thinking, people uncovered the shape of the invisible atom.'],
      ['해설', 'A common hydrogen atom, with one proton and one electron, is the simplest atom of all.'],
    ],
  },

  'tk1-plates': {
    title: 'The Moving Ground: Plate Tectonics',
    names: { 해설: 'Narrator', 강연자: 'Lecturer', 학생: 'Student' },
    outro: [
      'Why are earthquakes and volcanoes gathered along plate boundaries instead of spread evenly over the Earth?',
      'Why was Wegener’s idea rejected at first, and what brought it back to life?',
      'If an earthquake hits your school or home, do you know where to take cover and how to get out?',
    ],
    lines: [
      ['해설', 'Today’s science talk is about how the ground under our feet is moving.'],
      ['해설', 'We will find out why earthquakes and volcanoes happen more in certain places.'],
      ['강연자', 'Look at a world map. The east coast of South America and the west coast of Africa look alike.'],
      ['강연자', 'They fit together like pieces of one puzzle that broke apart.'],
      ['강연자', 'In 1912, a German scientist, Alfred Wegener, said the continents were once one piece of land.'],
      ['강연자', 'He called this giant land Pangaea.'],
      ['강연자', 'He also pointed out that the same ancient fossils are found on continents across the ocean.'],
      ['학생', 'If he had evidence, why didn’t people accept it right away?'],
      ['강연자', 'Because he could not explain what force could move whole continents.'],
      ['강연자', 'Then, in the mid-twentieth century, scientists began to study the ocean floor.'],
      ['강연자', 'In the middle of the Atlantic, they found a long underwater mountain chain, called a ridge.'],
      ['강연자', 'At the ridge, new sea floor was forming and spreading out to both sides.'],
      ['강연자', 'In this way, the theory of plate tectonics was accepted in the 1960s.'],
      ['강연자', 'The Earth’s outer shell is broken into several hard plates, and they move slowly.'],
      ['강연자', 'They move a few centimeters a year, about as fast as your fingernails grow.'],
      ['강연자', 'Where two plates meet, three kinds of things happen.'],
      ['강연자', 'First, plates move apart. Ocean ridges and Iceland are examples.'],
      ['강연자', 'Second, plates push together. Sometimes one plate dives under the other.'],
      ['강연자', 'The Himalayas rose up when India crashed into the Eurasian continent.'],
      ['강연자', 'Third, plates slide past each other, like the San Andreas Fault in the United States.'],
      ['강연자', 'When stress built up at a boundary is suddenly released, the ground shakes. That is an earthquake.'],
      ['강연자', 'Near places where one plate dives under another, magma forms, and lines of volcanoes appear.'],
      ['강연자', 'The belt of earthquakes and volcanoes around the Pacific is called the Ring of Fire.'],
      ['학생', 'Korea is far from a plate boundary, so we don’t need to worry about earthquakes, right?'],
      ['강연자', 'Big earthquakes are rare here because we are far from a boundary, but they still happen.'],
      ['강연자', 'In 2016, a magnitude 5.8 earthquake struck Gyeongju. So please learn what to do.'],
      ['강연자', 'While it shakes, protect your head under a table. When it stops, take the stairs to an open area.'],
      ['해설', 'Over a very long time, the slow movement of plates lifted the sea floor up to mountaintops.'],
      ['해설', 'In rocks near the top of Mount Everest, people have found fossils of sea creatures.'],
    ],
  },

  'tk1-cell': {
    title: 'Cells and DNA',
    names: { 해설: 'Narrator', 강연자: 'Lecturer', 학생: 'Student' },
    outro: [
      'Which bases pair up in DNA, and why are these pairs important for copying information?',
      'If cells share the same DNA, why do they do different jobs, like muscle, nerve, and skin cells?',
      'Now that you know your body is made of tens of trillions of cells, how does it look different to you?',
    ],
    lines: [
      ['해설', 'Today’s science talk is about cells, the basic units of life, and the DNA inside them.'],
      ['해설', 'Let us open the blueprint of the great city we call the human body.'],
      ['강연자', 'In 1665, the English scientist Robert Hooke looked at a thin slice of cork under a microscope.'],
      ['강연자', 'He saw rows of tiny rooms, so he called them cells, from a word for a small room.'],
      ['강연자', 'By the nineteenth century, scientists agreed that all living things are made of cells.'],
      ['강연자', 'Some living things, like bacteria, are just one cell. We are made of tens of trillions.'],
      ['학생', 'Do all those cells look the same?'],
      ['강연자', 'No. Muscle cells are long, and nerve cells spread out like tree branches.'],
      ['강연자', 'But the nucleus of most cells holds the very same blueprint.'],
      ['강연자', 'That blueprint is a long molecule called DNA.'],
      ['강연자', 'In 1953, James Watson and Francis Crick shared a model of DNA as a double helix.'],
      ['강연자', 'An X-ray photo taken by Rosalind Franklin’s team gave them a key clue.'],
      ['강연자', 'DNA looks like a twisted ladder. Each step of the ladder is a pair of two bases.'],
      ['강연자', 'There are four bases, A, T, G, and C. A pairs with T, and G pairs with C.'],
      ['강연자', 'So if you know one side of the ladder, you can rebuild the other side exactly.'],
      ['강연자', 'That is the secret of how a cell copies its DNA so well when it divides in two.'],
      ['학생', 'How can only four letters hold the information to build a person?'],
      ['강연자', 'Even four letters can write countless sentences if you line up enough of them.'],
      ['강연자', 'Certain parts of DNA, called genes, carry the instructions for making proteins.'],
      ['강연자', 'Proteins build our bodies, and they also help chemical reactions inside us.'],
      ['강연자', 'If you joined all the DNA from one cell end to end, it would be about two meters long.'],
      ['강연자', 'This long DNA wraps around proteins and is packed into bundles called chromosomes.'],
      ['학생', 'If the blueprint is the same, why do cells have different shapes?'],
      ['강연자', 'Because each cell reads different pages of the blueprint.'],
      ['강연자', 'It is like using one cookbook. Different pages give you different dishes.'],
      ['강연자', 'Right now, the cells in your body are each reading their own pages.'],
      ['해설', 'Understanding cells and DNA is the base for understanding and treating diseases.'],
      ['해설', 'Each human body cell holds twenty-three pairs of chromosomes, forty-six in all.'],
    ],
  },

  'tk1-evolution': {
    title: 'How Natural Selection Works',
    names: { 해설: 'Narrator', 강연자: 'Lecturer', 학생: 'Student' },
    outro: [
      'What conditions must a group of living things have for natural selection to happen?',
      'What does it mean to say evolution favors the better fit for the environment, not simply the stronger?',
      'How is taking all of your prescribed antibiotics, the right way, connected to natural selection?',
    ],
    lines: [
      ['해설', 'Today’s science talk is about evolution, how living things change over long periods of time.'],
      ['해설', 'We will look at how natural selection, the heart of evolution, really works.'],
      ['강연자', 'Why did giraffes get long necks? Let us compare two explanations.'],
      ['강연자', 'One. They stretched to reach high leaves, their necks grew longer, and they passed this on.'],
      ['강연자', 'Two. Neck lengths were already different, and those with longer necks survived and had more young.'],
      ['학생', 'The first one sounds more likely to me.'],
      ['강연자', 'Many people feel that way. But features gained during life are usually not passed on.'],
      ['강연자', 'Muscles you build at the gym are not handed down to your children.'],
      ['강연자', 'The explanation science accepts today is the second one, natural selection.'],
      ['강연자', 'Natural selection needs four conditions.'],
      ['강연자', 'First, members of the same species are a little different from each other. This is called variation.'],
      ['강연자', 'Second, some of those differences are passed from parents to their young.'],
      ['강연자', 'Third, living things have more young than can possibly survive.'],
      ['강연자', 'Fourth, those that fit their environment better survive more and leave more young.'],
      ['강연자', 'When this goes on for many generations, the features of the whole group change.'],
      ['강연자', 'This change is happening even now. Bacteria that resist antibiotics are one example.'],
      ['강연자', 'Antibiotics kill most bacteria, but a few tougher ones may survive.'],
      ['강연자', 'When the survivors multiply, the new group is hard to kill with that medicine.'],
      ['강연자', 'Sometimes people do the choosing. Dogs came from ancient wolves that people tamed and bred over a long time.'],
      ['학생', 'So did humans evolve from monkeys?'],
      ['강연자', 'That is a common mistake. Humans and today’s apes are relatives with a shared ancestor long ago.'],
      ['강연자', 'Evolution is not like climbing a ladder. It is more like a tree with spreading branches.'],
      ['강연자', 'Also, evolution has no goal set in advance. When the environment changes, the answer changes too.'],
      ['강연자', 'The evidence is in many places, in fossils, in body structures, and in DNA.'],
      ['강연자', 'Studies show that the more closely related two species are, the more alike their DNA is.'],
      ['강연자', 'Body structures tell the same story. Animals may look different, but their bones are arranged alike.'],
      ['해설', 'Evolution is the theory that ties together the many fields of biology today.'],
      ['해설', 'A human arm, a bat’s wing, and a whale’s flipper all have the same basic set of bones.'],
    ],
  },

  'tk1-light': {
    title: 'The Secrets of Light and Color',
    names: { 해설: 'Narrator', 강연자: 'Lecturer', 학생: 'Student' },
    outro: [
      'What does a red apple do with light that makes it look red?',
      'Can you explain why the sky turns red at sunset, comparing it with the blue sky at noon?',
      'How could you check whether the colors you see are really the same as the colors your friend sees?',
    ],
    lines: [
      ['해설', 'Today’s science talk is about light and color.'],
      ['해설', 'Let us follow what really happens when we see a color.'],
      ['강연자', 'Light is the fastest thing in the universe. In a vacuum, it travels about 300,000 kilometers a second.'],
      ['강연자', 'The Earth is about 40,000 kilometers around, so light could circle it seven and a half times a second.'],
      ['강연자', 'Light is a kind of electromagnetic wave, and its nature changes with its wavelength.'],
      ['강연자', 'The light our eyes can see has wavelengths of about 400 to 700 nanometers.'],
      ['강연자', 'We see the longer waves as red and the shorter waves as violet.'],
      ['강연자', 'Longer than that is infrared, and shorter is ultraviolet. Our eyes cannot see either one.'],
      ['학생', 'So is an apple red because it gives off red light?'],
      ['강연자', 'An apple makes no light of its own. It takes in sunlight and sends only part of it back.'],
      ['강연자', 'It absorbs much of the other colors and mostly reflects red light.'],
      ['강연자', 'That reflected light enters our eyes, and we see red.'],
      ['강연자', 'Leaves look green because chlorophyll absorbs less green light and reflects it.'],
      ['강연자', 'Now, our eyes. The retina has three kinds of cone cells that sense color.'],
      ['강연자', 'Each kind reacts most strongly to light near red, green, or blue.'],
      ['강연자', 'The brain compares how strongly the three react, and it tells apart a huge number of colors.'],
      ['강연자', 'That is why mixing only red, green, and blue light can make almost any color.'],
      ['강연자', 'Look at a phone screen through a magnifying glass, and you will see tiny dots of these three colors.'],
      ['학생', 'What color do you get if you mix red light and green light?'],
      ['강연자', 'It looks yellow. And if you mix all three, you get white.'],
      ['강연자', 'Paint works the other way. It gets darker as you mix, because each paint takes away light.'],
      ['강연자', 'Lastly, why is the sky blue? Sunlight hits tiny air molecules and scatters.'],
      ['강연자', 'Blue light, with its short waves, scatters much more than red light with its long waves.'],
      ['강연자', 'That scattered blue light reaches our eyes from every part of the sky.'],
      ['강연자', 'At sunset, light passes through more air. The blue scatters away, and the red is left.'],
      ['강연자', 'Looking straight at the Sun is dangerous. Always observe it in a safe, indirect way.'],
      ['해설', 'Color is an experience made by objects, light, and our eyes and brain working together.'],
      ['해설', 'Sunlight takes about eight minutes and twenty seconds, on average, to reach the Earth.'],
    ],
  },

  'tk1-sound': {
    title: 'Sound Is a Vibration',
    names: { 해설: 'Narrator', 강연자: 'Lecturer', 학생: 'Student' },
    outro: [
      'Which properties of a wave decide how high or low a sound is, and how loud it is?',
      'Why can’t we hear the sound of a huge explosion in outer space from the Earth?',
      'Have you thought about what could happen to your ears if you listen to loud music for a long time?',
    ],
    lines: [
      ['해설', 'Today’s science talk is about the world we hear, sound and waves.'],
      ['해설', 'We will learn how sound is made and how it reaches our ears.'],
      ['강연자', 'Put your hand on your throat and say ah. Can you feel it shaking?'],
      ['강연자', 'Sound starts with something shaking. We call this a vibration.'],
      ['강연자', 'A vibrating object pushes and pulls the air around it.'],
      ['강연자', 'This makes crowded and spread-out areas of air, one after another, that travel outward.'],
      ['강연자', 'A vibration passed along like this is called a wave.'],
      ['학생', 'So does the air fly all the way to my ears?'],
      ['강연자', 'No. The bits of air only shake back and forth in place. Only the vibration travels.'],
      ['강연자', 'Water waves are similar. A floating leaf bobs up and down, but it does not drift away.'],
      ['강연자', 'So sound needs some material to carry the vibration. We call it a medium.'],
      ['강연자', 'If you pump the air out of a glass jar, a bell ringing inside gets quieter and quieter.'],
      ['강연자', 'In space, where there is almost no air, sound cannot travel.'],
      ['강연자', 'In air, sound travels about 340 meters a second. In water, it goes even faster.'],
      ['학생', 'Is that why we hear thunder long after we see lightning?'],
      ['강연자', 'Right. Light arrives almost at once, but sound arrives later.'],
      ['강연자', 'If you hear thunder about three seconds after the flash, the lightning is about one kilometer away.'],
      ['강연자', 'We can describe a sound in three ways.'],
      ['강연자', 'The number of vibrations per second is the frequency. A higher frequency makes a higher sound.'],
      ['강연자', 'The size of the vibration is the amplitude. A bigger amplitude makes a louder sound.'],
      ['강연자', 'A piano and a violin sound different on the same note because their wave shapes are different.'],
      ['강연자', 'People can hear sounds from about 20 to 20,000 vibrations per second.'],
      ['강연자', 'This range differs from person to person, and as we age, high sounds are the first to fade.'],
      ['강연자', 'Sound higher than that is called ultrasound. Bats find their way with ultrasound echoes.'],
      ['강연자', 'Hospitals use ultrasound to look inside the body.'],
      ['강연자', 'Loud sounds for a long time can hurt your ears, so keep your earphone volume low.'],
      ['해설', 'Sound is a wave that reaches us as a vibration passed from neighbor to neighbor.'],
      ['해설', 'In air, sound moves forward about 340 meters every second.'],
    ],
  },

  'tk1-energy': {
    title: 'Energy Never Disappears',
    names: { 해설: 'Narrator', 강연자: 'Lecturer', 학생: 'Student' },
    outro: [
      'According to the law of conservation of energy, can energy be created or destroyed?',
      'If energy never disappears, why do we still say we must save energy?',
      'Where did the energy in this morning’s breakfast come from, and where is it going now?',
    ],
    lines: [
      ['해설', 'Today’s science talk is about one of nature’s firmest laws, the conservation of energy.'],
      ['해설', 'Let us follow energy as it changes form and travels around.'],
      ['강연자', 'Think of a roller coaster. First, the train is pulled up to a high place.'],
      ['강연자', 'Something high up has the ability to fall. We call this potential energy.'],
      ['강연자', 'As it goes down, it speeds up. Potential energy turns into the energy of motion, kinetic energy.'],
      ['강연자', 'When it climbs again, kinetic energy turns back into potential energy.'],
      ['학생', 'Then can a roller coaster go up and down forever after one push?'],
      ['강연자', 'No. The wheels rub against the rails, and the train pushes against the air.'],
      ['강연자', 'Then some of the energy turns into heat and sound and spreads out around it.'],
      ['강연자', 'That is why each later hill must be built lower than the first one.'],
      ['강연자', 'The key point is this. The energy is not lost. It has only changed form.'],
      ['강연자', 'In the 1840s, the English scientist James Joule showed this with an experiment.'],
      ['강연자', 'He let a heavy weight fall and turn a paddle wheel in water. The water got slightly warmer.'],
      ['강연자', 'He measured how motion turns into heat, and found that the amount was always the same.'],
      ['강연자', 'So we named a unit of energy after him, the joule.'],
      ['강연자', 'Here comes the law. Energy only changes form. The total amount always stays the same.'],
      ['강연자', 'This is the law of conservation of energy. No one has ever found an exception.'],
      ['강연자', 'So we cannot build a perpetual motion machine, which works forever with no energy put in.'],
      ['학생', 'But if energy never disappears, why do you tell us to save it?'],
      ['강연자', 'Sharp question. After we use energy, it usually becomes heat that spreads out.'],
      ['강연자', 'Spread-out heat is very hard to gather and use again. The amount is the same, but it is less useful.'],
      ['강연자', 'Saving energy means saving energy in a useful form.'],
      ['강연자', 'Our bodies work the same way. Our food holds chemical energy.'],
      ['강연자', 'That energy comes from sunlight that plants captured through photosynthesis.'],
      ['강연자', 'We use it to keep our bodies warm, to walk, and to think.'],
      ['강연자', 'Sunlight becomes rice, and rice becomes our movement and body heat.'],
      ['해설', 'Energy only changes its form. It all remains somewhere in the universe.'],
      ['해설', 'One calorie is the heat needed to warm one gram of water by one degree, about 4.2 joules.'],
    ],
  },

  'tk1-star': {
    title: 'The Life of a Star',
    names: { 해설: 'Narrator', 강연자: 'Lecturer', 학생: 'Student' },
    outro: [
      'How is the energy that lets a star shine for so long made in its center?',
      'You might think heavier stars live longer, so why do they actually live shorter lives?',
      'How does it feel to know the elements in your body were made inside stars long ago?',
    ],
    lines: [
      ['해설', 'Today’s science talk is about how the stars in the night sky are born and how they die.'],
      ['해설', 'We will fit a star’s life, which can last billions of years, into one short talk.'],
      ['강연자', 'Stars are born in clouds of gas and dust floating in space. We call these clouds nebulae.'],
      ['강연자', 'When part of a cloud starts to pull together by gravity, it gets hotter and hotter.'],
      ['강연자', 'When the center becomes hot and dense enough, something amazing begins.'],
      ['강연자', 'Hydrogen nuclei join together to become helium. This is called nuclear fusion.'],
      ['강연자', 'It releases a huge amount of energy, and the star finally shines by itself.'],
      ['학생', 'So is the Sun burning like that too? Like a fire?'],
      ['강연자', 'Fire is a chemical reaction with oxygen. The Sun shines because atomic nuclei join together.'],
      ['강연자', 'The Sun has been shining like this for about 4.6 billion years.'],
      ['강연자', 'Scientists expect it to keep shining like this for about five billion more years.'],
      ['강연자', 'When the hydrogen in its center runs out, the Sun will swell into a red giant.'],
      ['강연자', 'After that, its outer layers will drift off into space, leaving only a small, hot core.'],
      ['강연자', 'This leftover star is called a white dwarf. It slowly cools down.'],
      ['강연자', 'Stars much heavier than the Sun end in a different way.'],
      ['학생', 'Heavy stars have more fuel, so they must live longer, right?'],
      ['강연자', 'The opposite. Heavy stars burn their fuel much faster, so their lives are shorter.'],
      ['강연자', 'In the end, they blow up in a giant explosion called a supernova.'],
      ['강연자', 'What is left is a very dense neutron star or a black hole.'],
      ['강연자', 'A star’s color is a clue too. Blue stars are hot, and red stars are cooler.'],
      ['강연자', 'Now, here is the important part. Elements heavier than helium are also made inside stars.'],
      ['강연자', 'Carbon, oxygen, iron, and more. When a star explodes, these elements scatter into space.'],
      ['강연자', 'The scattered elements become the material for new stars, planets, and life.'],
      ['강연자', 'The carbon in our bodies and the iron in our blood were made in stars long ago.'],
      ['강연자', 'So you could say we are made of star dust.'],
      ['강연자', 'Starlight left its star long ago. When we look at a star, we see its past.'],
      ['해설', 'A light-year is the distance light travels in a year, about 9.5 trillion kilometers.'],
      ['해설', 'The Sun is a star that was born about 4.6 billion years ago.'],
    ],
  },

  'tk1-climate': {
    title: 'Weather and Climate Are Different',
    names: { 해설: 'Narrator', 강연자: 'Lecturer', 학생: 'Student' },
    outro: [
      'What is the most important difference between weather and climate?',
      'If one winter is unusually cold, can we say the Earth is not getting warmer?',
      'What marks has your local climate left on your clothes, your food, and the shape of your home?',
    ],
    lines: [
      ['해설', 'Today’s science talk is about two words people often mix up, weather and climate.'],
      ['해설', 'They seem alike, but they look at very different lengths of time.'],
      ['강연자', 'Is it raining today? Is the wind strong? That is weather.'],
      ['강연자', 'Weather is the state of the air over a few hours or a few days.'],
      ['강연자', 'Climate is the average pattern of weather in one place over many years.'],
      ['강연자', 'People often say weather is like your mood today, and climate is like your personality.'],
      ['학생', 'How long is many years?'],
      ['강연자', 'The World Meteorological Organization usually uses the average over thirty years.'],
      ['강연자', 'Let us look at Korea. It has four clear seasons, spring, summer, fall, and winter.'],
      ['강연자', 'In summer, hot and humid winds blow in from the ocean and bring a lot of rain.'],
      ['강연자', 'The long rainy spell in early summer is called jangma, the monsoon rains.'],
      ['강연자', 'In winter, cold and dry winds blow from the northwest, from the continent.'],
      ['강연자', 'Winds that change direction with the seasons like this are called monsoon winds.'],
      ['강연자', 'Climate depends on things like latitude, distance from the sea, and height above sea level.'],
      ['강연자', 'Places near the equator get more sunlight and are hot. High mountains are cool, even at the same latitude.'],
      ['강연자', 'We forecast weather, but we study climate by collecting and analyzing records.'],
      ['강연자', 'The further ahead a weather forecast looks, the harder it is to get it right.'],
      ['강연자', 'That is because in the air, small differences can grow much bigger over time.'],
      ['학생', 'Then what about climate change? What if this winter was really cold?'],
      ['강연자', 'The weather of one day or one year is not enough to tell us about climate.'],
      ['강연자', 'To see climate, we must collect decades of records and see how the average moves.'],
      ['강연자', 'Records like these show that the Earth’s average temperature has risen since industrialization.'],
      ['강연자', 'The greenhouse effect plays a part. Carbon dioxide and water vapor trap heat.'],
      ['강연자', 'The greenhouse effect itself is not all bad. Without it, the Earth would freeze.'],
      ['강연자', 'The problem is that more greenhouse gases trap more and more heat.'],
      ['강연자', 'Packing an umbrella today is about weather. Our village’s farming calendar fits our climate.'],
      ['해설', 'You could say weather looks at a single day, while climate looks at a whole generation.'],
      ['해설', 'Without the greenhouse effect, the Earth’s average temperature is calculated to be about minus eighteen degrees Celsius.'],
    ],
  },

  'tk1-vaccine': {
    title: 'Microbes and Vaccines',
    names: { 해설: 'Narrator', 강연자: 'Lecturer', 학생: 'Student' },
    outro: [
      'After a vaccine, what stays in the immune system to protect us the next time an infection comes?',
      'How does herd immunity work to protect even people who cannot get vaccines?',
      'Can you explain why it is not right to ask for antibiotics when you have a cold?',
    ],
    lines: [
      ['해설', 'Today’s science talk is about our invisible neighbors, microbes, and about vaccines.'],
      ['해설', 'We will look at these tiny living things and at our body’s defense system.'],
      ['강연자', 'In the 1670s, Antonie van Leeuwenhoek of the Netherlands looked at drops of water through microscopes he made himself.'],
      ['강연자', 'He was the first to describe in detail the tiny wriggling creatures inside them.'],
      ['강연자', 'Living things too small to see with the naked eye are called microbes.'],
      ['강연자', 'The main ones are bacteria and fungi, and viruses are often studied with them.'],
      ['강연자', 'Viruses are much smaller than bacteria, and they can multiply only inside the cells of other living things.'],
      ['학생', 'When I hear the word microbe, I think of germs first.'],
      ['강연자', 'In fact, most microbes are harmless, and many are helpful.'],
      ['강연자', 'Kimchi ripens thanks to lactic acid bacteria, and bread rises thanks to yeast.'],
      ['강연자', 'Microbes also break down dead living things and return them to the soil.'],
      ['강연자', 'Still, some microbes cause disease. We call them pathogens.'],
      ['강연자', 'When a pathogen enters, our immune system begins to fight.'],
      ['강연자', 'White blood cells attack the invader and make antibodies that fit it exactly.'],
      ['강연자', 'Fighting a new pathogen takes time, so we get sick for a while.'],
      ['강연자', 'But even after the fight ends, cells that remember the pathogen stay in our body.'],
      ['강연자', 'If the same pathogen comes back, the body can stop it much faster and more strongly.'],
      ['학생', 'So does a vaccine make that memory in advance?'],
      ['강연자', 'Exactly. It gives you the memory without the illness.'],
      ['강연자', 'It trains the immune system with weakened or killed pathogens, or just a part of them.'],
      ['강연자', 'For vaccines to protect the whole community, it also matters that many people get them.'],
      ['강연자', 'When many people are immune, a pathogen has a hard time spreading from person to person.'],
      ['강연자', 'Then babies, and sick people who cannot get vaccines, are protected too.'],
      ['강연자', 'This is called herd immunity.'],
      ['강연자', 'Let us also learn about antibiotics. They are medicines that attack bacteria.'],
      ['강연자', 'Colds are usually caused by viruses, so antibiotics will not cure them.'],
      ['강연자', 'Washing your hands works against every kind of microbe. It is the easiest defense.'],
      ['해설', 'Microbes can cause disease, but they also support our lives and the natural world.'],
      ['해설', 'Antibiotics are medicines that attack bacteria, and they do not work on viruses.'],
    ],
  },
};
