// 청소년 영어 원고 (중학생 이상). 키 = stories/teen-g.js 의 이야기 id.
// 고전·연설·기록의 내용을 한국어 각색의 흐름대로 쉬운 영어로 새로 씀. 원문을 그대로 옮긴 곳은
// 게티즈버그 연설의 짧은 구절(퍼블릭 도메인)뿐이며, 한국 기록은 지어낸 인용 없이 내용을 간추림.
export default {
  'tg-apology-1': {
    title: 'The Apology of Socrates, Part 1',
    names: { 해설: 'Narrator', 선생님: 'Teacher', 학생: 'Student' },
    outro: [
      'Why can knowing that you do not know be the starting point of wisdom?',
      'Socrates showed the weak points of others only by asking questions. How do you think those people felt?',
      'Is there something you believed you knew well, but actually did not?',
    ],
    lines: [
      ['해설', 'In 399 BC, the philosopher Socrates, over seventy years old, stood on trial in a court in Athens.'],
      ['해설', 'His accuser was Meletus, and Anytus and Lycon joined him.'],
      ['해설', 'The charges were that he did not believe in the city’s gods, brought in new spirits, and corrupted the young.'],
      ['해설', 'The Apology is his student Plato’s written version of the speech Socrates gave that day.'],
      ['해설', 'What follows is not a quotation. It retells the meaning of the work in today’s words.'],
      ['학생', 'Teacher, apology sounds like saying sorry or making excuses.'],
      ['선생님', 'Here it means defending yourself in court. It comes from the Greek word apologia.'],
      ['해설', 'Socrates first said he would deal with the old rumors about him.'],
      ['선생님', 'People said he studied things in the sky and under the earth, and made weak arguments look strong.'],
      ['선생님', 'He pointed out that he was shown that way in a comedy by Aristophanes.'],
      ['해설', 'To explain why people hated him, he told the story of the oracle at Delphi.'],
      ['선생님', 'His friend Chaerephon went to Delphi and asked if anyone was wiser than Socrates.'],
      ['선생님', 'The oracle answered that no one was wiser.'],
      ['학생', 'Then Socrates must have been very happy!'],
      ['선생님', 'Actually, he was puzzled. He did not think he was wise. So he set out to find what it meant.'],
      ['해설', 'He went to a politician who was famous for his wisdom and talked with him.'],
      ['해설', 'But it turned out the man only believed he knew. In fact, he did not know much.'],
      ['해설', 'Socrates said it was much the same with poets and craftsmen.'],
      ['선생님', 'Craftsmen knew their own skills, but because of that, they thought they knew other great things too.'],
      ['학생', 'Oh, so that is where the idea of knowing that you do not know comes from.'],
      ['선생님', 'Right. He was a little wiser only because he knew his own ignorance. People call it Socratic wisdom.'],
      ['해설', 'But his questions embarrassed people, and he said that was how he made many enemies.'],
      ['해설', 'Next, Socrates questioned his accuser Meletus directly.'],
      ['선생님', 'He asked, if I am the one who corrupts the young, then who makes them better?'],
      ['선생님', 'In the end, Meletus had to say that every Athenian made them better, except Socrates.'],
      ['학생', 'Everyone makes them better, and only one man ruins them? That sounds strange.'],
      ['선생님', 'Socrates used horses as an example. Only a few trainers can make horses better, not everyone.'],
      ['해설', 'He also showed that saying he believed in no gods, yet brought in new spirits, was a contradiction.'],
      ['학생', 'He shows the holes in the other side’s argument just by asking questions.'],
      ['선생님', 'That was his way. But no one knew yet which way the jury would lean.'],
      ['해설', 'The temple of Apollo at Delphi was famous in ancient Greece for its oracle.'],
    ],
  },

  'tg-apology-2': {
    title: 'The Apology of Socrates, Part 2',
    names: { 해설: 'Narrator', 선생님: 'Teacher', 학생: 'Student' },
    outro: [
      'Why did Socrates put a life of questioning before his own life?',
      'Socrates compared himself to a gadfly on the city. What role was he choosing for himself?',
      'When does a community truly need someone who asks uncomfortable questions?',
    ],
    lines: [
      ['해설', 'As his defense went on, Socrates asked himself whether he feared death, and then answered.'],
      ['해설', 'Again, this is not a quotation. It retells the meaning of the work.'],
      ['선생님', 'He said a person should ask whether an action is right or wrong, not whether he will live or die.'],
      ['선생님', 'And fearing death, he said, is pretending to know what you do not know.'],
      ['학생', 'Because nobody knows if death is good or bad?'],
      ['선생님', 'Yes. The idea of knowing your ignorance from Part 1 continues here.'],
      ['해설', 'Socrates made it clear he would not stop doing philosophy, even if that were the price of his freedom.'],
      ['선생님', 'He would obey the god rather than people, and keep questioning as long as he lived.'],
      ['해설', 'He said he had always urged people to care for wisdom, truth, and the soul, not money or fame.'],
      ['해설', 'He compared Athens to a big, slow horse, and himself to a gadfly stuck to it.'],
      ['학생', 'A gadfly? The insect that bites cows and horses?'],
      ['선생님', 'Right. Someone who keeps stinging a sleepy city to wake it up.'],
      ['해설', 'He said that since childhood, a divine voice had sometimes stopped him from doing things.'],
      ['해설', 'That voice kept him out of politics, and he believed it had kept him alive.'],
      ['선생님', 'Still, he refused injustice. Under the Thirty Tyrants, he refused an order to arrest Leon of Salamis.'],
      ['해설', 'He had three sons, but he would not bring his family to court to cry for pity.'],
      ['해설', 'When the votes were counted, Socrates was found guilty.'],
      ['선생님', 'He said the vote was closer than he expected. If thirty votes had changed, he would have been freed.'],
      ['해설', 'Next, each side proposed a punishment. The accusers asked for death.'],
      ['학생', 'So what punishment did Socrates suggest?'],
      ['선생님', 'Surprisingly, at first he said he deserved free meals in the Prytaneum, like a public hero.'],
      ['해설', 'Then Plato and other friends offered to guarantee the money, and he proposed a fine of thirty minae of silver.'],
      ['해설', 'But the jury chose death.'],
      ['학생', 'The famous line about the unexamined life is in this work too, right?'],
      ['선생님', 'Yes. While discussing his punishment, he says a life without questioning is not worth living.'],
      ['해설', 'After the sentence, Socrates said death must be one of two things.'],
      ['선생님', 'A deep sleep without dreams, or a move to where those who died before are. Either way, not bad.'],
      ['선생님', 'He also asked them to scold his sons, as he had scolded others, if they valued money over goodness.'],
      ['해설', 'Finally, he said he was going to die and they were going to live, but only the god knew which was better.'],
      ['학생', 'He stayed calm until the end. He really valued a questioning life as much as life itself.'],
      ['해설', 'In 399 BC, following his death sentence, Socrates drank poison and died.'],
    ],
  },

  'tg-analects-learn': {
    title: 'The Analects: On Learning',
    names: { 해설: 'Narrator', 선생님: 'Teacher', 학생: 'Student' },
    outro: [
      'Why did Confucius put the joy of learning at the very beginning of the Analects?',
      'Learning without thinking, or thinking without learning. Which one am I closer to?',
      'When three people walk together, one of them can be my teacher. What have I learned from a friend lately?',
    ],
    lines: [
      ['해설', 'The Analects is a book of the sayings and deeds of Confucius and his disciples.'],
      ['해설', 'His disciples and their students put it together after Confucius died.'],
      ['해설', 'It has twenty books, and most of them are named after words in their first line.'],
      ['해설', 'Today we look at famous sayings about learning and what they mean.'],
      ['학생', 'Teacher, I heard the very first line of the Analects is about learning.'],
      ['선생님', 'Yes. The first book begins, isn’t it a joy to learn and to practice what you learned from time to time?'],
      ['학생', 'Studying is a joy? Honestly, I don’t really feel that.'],
      ['선생님', 'Practicing means repeating something until it becomes part of you. It’s the joy of finally being able to do it.'],
      ['선생님', 'Next comes, isn’t it a delight when a friend comes from far away?'],
      ['선생님', 'The first passage ends by saying a true gentleman does not get angry when others do not know him.'],
      ['학생', 'Being okay when nobody recognizes me sounds the hardest.'],
      ['해설', 'In the second book, Confucius looked back on his life. At fifteen, he set his heart on learning.'],
      ['선생님', 'At thirty he stood firm, and at forty he had no doubts. So in Korea, forty is called bulhok, no doubts.'],
      ['해설', 'The same book says that one who reviews the old and learns the new can be a teacher.'],
      ['학생', 'I know that as a four-character saying, ongojisin!'],
      ['선생님', 'It also says learning without thinking leaves you lost, and thinking without learning puts you in danger.'],
      ['학생', 'So just memorizing is not enough, and just thinking alone is not enough either.'],
      ['해설', 'Confucius told his disciple Zilu that knowing means saying you know what you know, and admitting what you don’t.'],
      ['선생님', 'That is in the second book too. Many people compare it with Socrates’ idea of knowing your ignorance.'],
      ['해설', 'Another book says that when three people walk together, one of them is surely my teacher.'],
      ['선생님', 'It goes on: follow their good points, and use their bad points to fix your own faults.'],
      ['학생', 'So I can learn from friends who do well and from friends who make mistakes.'],
      ['해설', 'Confucius also said knowing something is not as good as loving it, and loving it is not as good as enjoying it.'],
      ['학생', 'That sounds like the saying that nobody can beat someone who enjoys what they do.'],
      ['선생님', 'You could see it that way. But here, enjoying means finding joy in learning itself.'],
      ['학생', 'Then it connects to the joy in the very first line.'],
      ['선생님', 'Good point. In the Analects, sayings from different books shine light on each other.'],
      ['해설', 'Confucius lived in the state of Lu during the Spring and Autumn period, and he taught many students.'],
    ],
  },

  'tg-analects-ren': {
    title: 'The Analects: Being Truly Human',
    names: { 해설: 'Narrator', 선생님: 'Teacher', 학생: 'Student' },
    outro: [
      'Why did Confucius give a different answer to each disciple who asked about ren?',
      'Do not do to others what you do not want. How is this different from telling people what to do?',
      'Today, many people decorate their words and faces. How can we recognize a sincere heart?',
    ],
    lines: [
      ['해설', 'One of the most important ideas in the Analects is ren, which means humaneness or goodness.'],
      ['해설', 'But Confucius never defined ren in one sentence. He answered differently, depending on who asked.'],
      ['학생', 'Teacher, what exactly is ren? I only know it means being kind.'],
      ['선생님', 'That is what makes the Analects interesting. Each disciple got a different answer. Let’s look at them.'],
      ['해설', 'When his disciple Fan Chi asked about ren, Confucius said it was loving people.'],
      ['해설', 'When his favorite disciple Yan Hui asked, he said ren was mastering yourself and returning to proper manners.'],
      ['학생', 'What does mastering yourself mean?'],
      ['선생님', 'People usually explain it as controlling selfish wants and following the right way between people.'],
      ['선생님', 'Confucius added, do not look, listen, speak, or move in ways that go against proper manners.'],
      ['해설', 'When Zhonggong asked, Confucius told him not to do to others what he did not want for himself.'],
      ['학생', 'I’ve heard that one! In Korean, gisobulyok mulsieoin.'],
      ['선생님', 'It appears again later. Zigong asked for one word to live by, and Confucius said, perhaps shu.'],
      ['학생', 'What does shu mean?'],
      ['선생님', 'It is often explained as using your own heart to understand another person’s heart.'],
      ['해설', 'Once Confucius said one thread ran through all his teaching. His disciple Zengzi said it was zhong and shu.'],
      ['선생님', 'Zhong means doing your best with your whole heart. Shu means thinking of others. That is the usual explanation.'],
      ['해설', 'In the first book, Confucius said few people with clever words and a put-on smile are truly good.'],
      ['학생', 'People who only act nice on the outside, right?'],
      ['해설', 'In the same book, the disciple Youzi said caring for parents and brothers was probably the root of ren.'],
      ['선생님', 'It means ren starts with the people closest to you, not with something grand.'],
      ['학생', 'So is ren just having a kind heart?'],
      ['선생님', 'It must go beyond the heart and show in actions. Confucius also said, if I want ren, ren is already here.'],
      ['학생', 'Ren is not far away. That gives me a little courage.'],
      ['해설', 'Another saying goes, the gentleman understands what is right, and the small man understands what pays.'],
      ['선생님', 'Throughout the book, Confucius used the word gentleman for a person who works hard to practice ren.'],
      ['학생', 'Today, I’ll start by not doing to others what I don’t like.'],
      ['해설', 'Like most books of the Analects, their names come from words in the first line of each book.'],
    ],
  },

  'tg-analects-gov': {
    title: 'The Analects: Government and Virtue',
    names: { 해설: 'Narrator', 선생님: 'Teacher', 학생: 'Student' },
    outro: [
      'Why did Confucius value leading by virtue and manners more than leading by laws and punishments?',
      'The leader’s virtue is the wind, and the people’s virtue is the grass. What responsibility does this place on leaders?',
      'Trust comes before food. Does this idea still fit our politics and society today?',
    ],
    lines: [
      ['해설', 'Confucius lived in the Spring and Autumn period, a troubled time when many states fought one another.'],
      ['해설', 'He dreamed of government by virtue, not force, and traveled from state to state.'],
      ['학생', 'Teacher, did Confucius talk about politics a lot?'],
      ['선생님', 'Of course. A whole book opens with it. Ruling by virtue is like the North Star, he said.'],
      ['선생님', 'The North Star stays in its place, and all the other stars turn around it.'],
      ['학생', 'So if a leader is upright, people will follow naturally.'],
      ['해설', 'Confucius said that if you lead only with laws and punishments, people avoid punishment but feel no shame.'],
      ['해설', 'But if you lead with virtue and guide them with proper manners, they feel shame and correct themselves.'],
      ['학생', 'So he thought laws were not needed?'],
      ['선생님', 'That goes too far. He meant punishment alone cannot change hearts. People still debate this today.'],
      ['해설', 'When Zigong asked about government, Confucius named enough food, enough soldiers, and the people’s trust.'],
      ['학생', 'What if one of the three had to go?'],
      ['선생님', 'Zigong asked the same thing. Confucius said, give up the soldiers first, and then the food.'],
      ['선생님', 'Without the people’s trust, a state cannot stand. In Korean, this is minmusinbullip.'],
      ['학생', 'Trust before food? That’s a bold idea.'],
      ['해설', 'When Ji Kangzi, the real power in the state of Lu, asked about government, Confucius said governing means being upright.'],
      ['선생님', 'He went on, if you lead with uprightness, who would dare not be upright? Leaders must go first.'],
      ['해설', 'When Duke Jing of Qi asked, Confucius said the ruler should act as a ruler and the minister as a minister.'],
      ['해설', 'He added that the father should act as a father, and the son as a son.'],
      ['학생', 'So everyone should act right for their own place.'],
      ['해설', 'Confucius also said that if he ran a government, he would first correct the names of things.'],
      ['선생님', 'If names are not right, words do not flow, and in the end nothing gets done.'],
      ['학생', 'In today’s words, he warned against people who have titles but avoid the duties that come with them.'],
      ['해설', 'Confucius compared the leader’s virtue to the wind and the people’s to grass. When the wind blows, the grass bends.'],
      ['선생님', 'That was another answer to Ji Kangzi. It shows how powerful a leader’s example is.'],
      ['학생', 'But did Confucius actually succeed in politics?'],
      ['선생님', 'Not really. Late in life, he returned to Lu, taught his students, and put old texts in order.'],
      ['학생', 'His teaching survived as a book, so he spread his ideas another way.'],
      ['해설', 'That book of the Analects begins by comparing government by virtue to the North Star.'],
    ],
  },

  'tg-myeongsim': {
    title: 'Myeongsim Bogam: A Mirror for the Heart',
    names: { 해설: 'Narrator', 선생님: 'Teacher', 학생: 'Student' },
    outro: [
      'Why did Myeongsim Bogam begin its first chapter by urging people to do good?',
      'Words can be an axe that hurts people. Where do you see this in today’s world?',
      'Among old teachings, how can we tell what to keep today and what to think about again?',
    ],
    lines: [
      ['해설', 'Myeongsim Bogam means a precious mirror that makes the heart bright.'],
      ['해설', 'It collects good sayings from Confucius, Mencius, other sages, and many books, sorted by topic.'],
      ['해설', 'There are several theories about who put it together.'],
      ['해설', 'In the Joseon period, beginners at the seodang, the village school, read it widely.'],
      ['학생', 'Teacher, this book sounds like a collection of nagging.'],
      ['선생님', 'Ha, I can see why. Today I will explain the meanings, not read the original lines.'],
      ['해설', 'The first chapter, Gyeseon, begins by urging people to do good.'],
      ['선생님', 'The first line is from Confucius. Heaven repays good people with blessings and bad people with trouble.'],
      ['학생', 'Be good and you will be blessed? Isn’t that too simple?'],
      ['선생님', 'You might feel that way. But the same chapter also talks about small good and small evil.'],
      ['해설', 'The chapter includes the last advice Liu Bei of Shu Han left his son before dying.'],
      ['해설', 'Do not skip a good deed because it is small. Do not do a bad deed because it is small.'],
      ['학생', 'So small kindness and small lies both add up to something big.'],
      ['해설', 'Other chapters teach how to care for parents and how to study hard.'],
      ['선생님', 'One chapter has a saying passed down from Zhu Xi. Do not say there is tomorrow when you do not study today.'],
      ['학생', 'Time doesn’t wait for me, right? I hear that every exam season.'],
      ['해설', 'Another chapter warns about one’s temper and praises patience again and again.'],
      ['선생님', 'A famous line says, hold back your anger for one moment, and you will avoid a hundred days of worry.'],
      ['학생', 'If I hold back just once when I’m angry, I’ll have fewer regrets.'],
      ['해설', 'A chapter on speech warns that words can become an axe that hurts people.'],
      ['선생님', 'Today, that fits comments and text messages perfectly.'],
      ['해설', 'A chapter on friendship says living with good people is like entering a room full of sweet flowers.'],
      ['학생', 'My parents tell me to choose good friends too.'],
      ['선생님', 'So that advice has very old roots.'],
      ['학생', 'But should we follow old teachings exactly as they are today?'],
      ['선생님', 'Good question. Some parts, like those about social class or roles of men and women, don’t fit today. Read wisely.'],
      ['학생', 'Patience, careful words, and steady learning still seem useful now.'],
      ['선생님', 'Yes. Think of a classic not as a book to copy, but as a book to talk with.'],
      ['해설', 'The first chapter of Myeongsim Bogam is Gyeseon, which urges people to do good.'],
    ],
  },

  'tg-mencius': {
    title: 'Mencius: The Four Sprouts',
    names: { 해설: 'Narrator', 선생님: 'Teacher', 학생: 'Student' },
    outro: [
      'Why did Mencius use the moment of seeing a child about to fall into a well as proof that human nature is good?',
      'What does the story of the farmer who pulled up his sprouts warn us not to do?',
      'What can I do every day to grow the small sprouts of goodness in my heart?',
    ],
    lines: [
      ['해설', 'Mencius was a thinker of China’s Warring States period who carried on and developed the teachings of Confucius.'],
      ['해설', 'The book Mencius records his talks with kings of many states and with his disciples.'],
      ['해설', 'Today we explain two famous ideas from it, the four sprouts and the flood-like energy.'],
      ['학생', 'Teacher, Mencius said human nature is good, right?'],
      ['선생님', 'Yes. And the example he gave is very famous.'],
      ['선생님', 'Imagine someone suddenly sees a small child about to fall into a well.'],
      ['선생님', 'Anyone would be shocked and feel alarm and pity.'],
      ['해설', 'Mencius said this feeling does not come from wanting the parents’ friendship, praise, or escape from blame.'],
      ['학생', 'So the heart moves before we even think about gain.'],
      ['해설', 'Mencius called this feeling of pity the sprout of humaneness.'],
      ['해설', 'Shame at wrongdoing was the sprout of rightness, and the heart that gives way to others was the sprout of manners.'],
      ['해설', 'The heart that tells right from wrong was the sprout of wisdom. Together they are called the four sprouts.'],
      ['학생', 'So a sprout means a starting point?'],
      ['선생님', 'Yes. Mencius said having the four sprouts is as natural as having four limbs.'],
      ['선생님', 'If you grow them, they spread like a fire that has just caught or a spring that has just burst out.'],
      ['학생', 'So a good heart is useless if you don’t grow it.'],
      ['선생님', 'Exactly. In the same part, his disciple Gongsun Chou asks how to keep the heart from being shaken.'],
      ['해설', 'Mencius said he understood people’s words well, and he nourished his flood-like energy well.'],
      ['학생', 'I’ve heard of that energy many times. What is it exactly?'],
      ['선생님', 'Mencius said it was hard to explain. He called it the greatest and strongest energy.'],
      ['해설', 'If it is nourished with honesty and not harmed, he said, it fills the space between heaven and earth.'],
      ['해설', 'It grows from many right actions over time. One right action alone cannot produce it.'],
      ['선생님', 'That is where the story of a farmer from the state of Song comes in.'],
      ['해설', 'A man of Song worried that his grain sprouts were growing too slowly, so he pulled each one up a little.'],
      ['해설', 'He came home and said he had helped them grow. His son ran out, but the sprouts had already dried up.'],
      ['학생', 'Oh! So that’s where the Korean word jojang, forcing growth, comes from!'],
      ['선생님', 'Yes. Do not forget to grow them, but do not force them either. Growing the heart is the same.'],
      ['학생', 'So hearts and skills don’t grow overnight.'],
      ['해설', 'Mencius’ view that human nature is good is often compared with Xunzi’s view that human nature is bad.'],
    ],
  },

  'tg-gettysburg': {
    title: 'The Gettysburg Address',
    names: { 해설: 'Narrator', 선생님: 'Teacher', 학생: 'Student' },
    outro: [
      'At a ceremony for the dead, why did Lincoln stress the work left for the living?',
      'What effect did the words we can not dedicate this ground have on the listeners?',
      'How fully is the ideal of government of the people, by the people, for the people realized in our society today?',
    ],
    lines: [
      ['해설', 'In 1861, the United States split into North and South over slavery and secession, and civil war began.'],
      ['해설', 'In early July 1863, a huge three-day battle was fought at Gettysburg, Pennsylvania.'],
      ['해설', 'Both sides lost many men, and a national cemetery was made there to bury the dead.'],
      ['해설', 'On November 19, 1863, at the cemetery’s dedication, President Abraham Lincoln gave a short speech.'],
      ['학생', 'Teacher, was the speech really that short?'],
      ['선생님', 'It is under three hundred words. It takes only a few minutes.'],
      ['해설', 'The main speaker that day was Edward Everett, who spoke for nearly two hours.'],
      ['학생', 'But it’s Lincoln’s short speech that people remember.'],
      ['선생님', 'That’s why it is a model of a short, deep speech. Let’s follow it, with a few of its own words.'],
      ['해설', 'Lincoln began, Four score and seven years ago our fathers brought forth on this continent, a new nation.'],
      ['선생님', 'A score is twenty. Four times twenty, plus seven, makes eighty-seven years.'],
      ['학생', 'And 1863 minus 87 is 1776, the year of the Declaration of Independence!'],
      ['해설', 'That nation was conceived in Liberty, and dedicated to the proposition that all men are created equal.'],
      ['해설', 'He said the present war was testing whether such a nation could long endure.'],
      ['선생님', 'And he said they had come to dedicate part of the field as a final resting place for the fallen.'],
      ['해설', 'But Lincoln said that in a larger sense, we can not dedicate this ground.'],
      ['해설', 'The brave men who struggled there had already made it holy, far beyond our power to add or take away.'],
      ['학생', 'It’s interesting that he came to a dedication and said we cannot dedicate it.'],
      ['선생님', 'He said, The world will little note, nor long remember what we say here.'],
      ['선생님', 'But it can never forget what they did here.'],
      ['학생', 'Yet the world remembers that speech so well. How ironic.'],
      ['해설', 'Lincoln said the living must devote themselves to the unfinished work the fallen had begun.'],
      ['해설', 'They should make sure these dead had not died in vain, and that the nation would have a new birth of freedom.'],
      ['선생님', 'And the last line is the most famous of all.'],
      ['해설', 'He ended by saying that government of the people, by the people, for the people, shall not perish from the earth.'],
      ['학생', 'That’s the line people always quote to explain democracy.'],
      ['선생님', 'The speech never uses the words North, South, or slavery. Instead, it speaks of the ideals of the whole nation.'],
      ['학생', 'Instead of taking sides, he spoke of a goal everyone should protect.'],
      ['해설', 'In April 1865, as the Civil War was ending, Lincoln was assassinated.'],
      ['해설', 'The Gettysburg Address was given on November 19, 1863, at the dedication of the national cemetery at Gettysburg.'],
    ],
  },

  'tg-march-first': {
    title: 'The March First Declaration of Independence',
    names: { 해설: 'Narrator', 선생님: 'Teacher', 학생: 'Student' },
    outro: [
      'Why did the Declaration focus on rebuilding Korea itself rather than blaming Japan?',
      'The age of force is passing, and the age of moral justice is coming. What hope is in these words?',
      'What do the principles of order and fairness in the Three Pledges mean for citizens’ actions today?',
    ],
    lines: [
      ['해설', 'On March 1, 1919, national representatives gathered at Taehwagwan in Seoul and declared Korea’s independence.'],
      ['해설', 'On the same day at Tapgol Park, students and citizens read the Declaration aloud and shouted manse, long live Korea.'],
      ['해설', 'Choe Nam-seon drafted the Declaration, and thirty-three national representatives, including Son Byeong-hui, signed it.'],
      ['해설', 'The representatives were religious leaders from Cheondogyo, Christianity, and Buddhism.'],
      ['학생', 'Teacher, the original has so many Chinese characters. It’s hard to read.'],
      ['선생님', 'It was written in mixed Korean and Chinese script. Today I will explain its meaning in modern words.'],
      ['선생님', 'Remember, this is an explanation, not the original text.'],
      ['선생님', 'The opening declares that Korea is an independent nation and that Koreans are a free people.'],
      ['선생님', 'It goes on to say they announce this to the world to show the great truth that all humans are equal.'],
      ['선생님', 'They also tell it to all future generations, so the nation can keep its rightful freedom forever.'],
      ['해설', 'The Declaration said Koreans had suffered under another nation for ten years because of old-fashioned aggression.'],
      ['해설', 'It said they had lost their right to live freely and their chance to grow as a people.'],
      ['학생', 'I thought it would attack Japan harshly, but the mood feels different.'],
      ['선생님', 'Sharp eyes. The Declaration says it does not intend to blame Japan for breaking its promises.'],
      ['선생님', 'Its attitude is that Koreans are too busy improving themselves to waste time resenting others.'],
      ['해설', 'The Declaration also argued that Korea’s independence was needed for peace in East Asia and the world.'],
      ['학생', 'So independence was not only for Koreans.'],
      ['해설', 'It said the age of force was passing and the age of moral justice was coming, as a new world opened.'],
      ['선생님', 'This hopeful part shows the mood just after the First World War ended.'],
      ['해설', 'At the end are the Three Pledges, which set out the rules for action.'],
      ['해설', 'First, this is a people’s demand for justice, humanity, survival, and dignity, so do not be driven by hatred of others.'],
      ['해설', 'Second, to the last person and the last moment, clearly express the people’s rightful will.'],
      ['해설', 'Third, respect order in every action, so that our claims and attitude remain fair and honorable.'],
      ['학생', 'So keep going to the end, but in an orderly and fair way.'],
      ['선생님', 'Right. The Declaration is dated the 4252nd year since the founding of Korea, March 1.'],
      ['학생', 'They used the Dangun calendar. 1919 is the year 4252 in that calendar.'],
      ['해설', 'The manse movement soon spread across the country and even to Korean communities abroad.'],
      ['해설', 'In April of the same year, the Provisional Government of the Republic of Korea was founded in Shanghai, China.'],
      ['해설', 'Today, March 1 is Samiljeol, a national holiday in South Korea.'],
    ],
  },

  'tg-peace-east': {
    title: 'On Peace in East Asia',
    names: { 해설: 'Narrator', 선생님: 'Teacher', 학생: 'Student' },
    outro: [
      'Why did An Jung-geun try to explain his act as part of the larger cause of peace in East Asia?',
      'He criticized a nation that talked about peace but broke the peace. What contradiction was he pointing out?',
      'What efforts are needed today for neighboring countries to keep the peace together?',
    ],
    lines: [
      ['해설', 'On October 26, 1909, An Jung-geun shot Ito Hirobumi at Harbin Station in China.'],
      ['해설', 'Ito had forced the Eulsa Treaty on Korea and became the first Japanese Resident-General, leading Japan’s takeover of Korea.'],
      ['해설', 'An Jung-geun was put on trial while held in a prison in Lushun, and in February 1910 he was sentenced to death.'],
      ['해설', 'In prison, he began to write On Peace in East Asia.'],
      ['학생', 'Teacher, he wrote a book even after being sentenced to death?'],
      ['선생님', 'Yes. He said his act was for peace in East Asia, and he wanted to put those ideas in writing.'],
      ['해설', 'He planned the book in five parts, including a preface, lessons from the past, and questions and answers.'],
      ['해설', 'But he finished only the preface and part of the second section. He was executed on March 26, 1910.'],
      ['학생', 'Didn’t he ask for time to finish it?'],
      ['선생님', 'He asked them to delay his execution until he finished, but the sentence was carried out anyway.'],
      ['선생님', 'He wrote in classical Chinese. From here on, I will explain the content, not quote it.'],
      ['해설', 'In the preface, he pointed to Western powers pushing into East Asia.'],
      ['해설', 'At such a time, he said, the nations of East Asia should join forces to protect themselves.'],
      ['해설', 'In the Russo-Japanese War, Japan claimed to fight for peace in East Asia and Korea’s independence.'],
      ['해설', 'Because of that, he believed, Koreans and Chinese had helped Japan.'],
      ['학생', 'But what did Japan do after winning the war?'],
      ['해설', 'He criticized Japan for abandoning that cause after its victory and invading its neighbor, Korea.'],
      ['선생님', 'A nation that talked of peace had broken the peace. He saw that trust between neighbors had collapsed.'],
      ['해설', 'In the next section, he looked at the time of the Sino-Japanese and Russo-Japanese Wars for lessons.'],
      ['학생', 'If the book is unfinished, can we know his solutions?'],
      ['선생님', 'Before his execution, he talked with a Japanese chief judge, and a record of that talk survives. It shows his concrete plans.'],
      ['해설', 'According to that record, he suggested making Lushun a neutral zone where Korea, China, and Japan would hold peace talks.'],
      ['해설', 'He also suggested that the three nations set up a joint bank and a shared currency.'],
      ['해설', 'He even proposed an army of young people from all three nations, who would learn each other’s languages.'],
      ['학생', 'A shared currency? That reminds me of the euro in the European Union.'],
      ['선생님', 'That’s why many people say his ideas were ahead of his time.'],
      ['선생님', 'His act was resistance against invasion, and behind it was a vision of living in peace with neighbors.'],
      ['학생', 'At first it felt strange that a man who used a gun wrote about peace. Now I understand a little.'],
      ['해설', 'He asked that his remains be moved to Korea once it was free, but they have not been found for a long time.'],
    ],
  },

  'tg-nanjung-1': {
    title: 'The War Diary of Yi Sun-sin, Part 1',
    names: { 해설: 'Narrator', 선생님: 'Teacher', 학생: 'Student' },
    outro: [
      'Why did Yi Sun-sin keep recording each day, even during the war?',
      'How do the strict commander and the son who missed his mother appear together in the diary?',
      'If I recorded my days, what could that record mean to me and to others later?',
    ],
    lines: [
      ['해설', 'In 1592, Japan invaded Joseon, and the Imjin War began.'],
      ['해설', 'Yi Sun-sin, then naval commander of the eastern half of Jeolla Province, kept a diary throughout the war.'],
      ['해설', 'This diary is called Nanjung Ilgi, which means a diary written during war.'],
      ['해설', 'Yi did not give it that title. It was named when his writings were collected and published under King Jeongjo.'],
      ['학생', 'Teacher, a general’s diary must be only about battles, right?'],
      ['선생님', 'Not at all. Today we’ll look at its contents by topic. I will sum them up, not quote the diary.'],
      ['해설', 'Almost every entry records the weather. Many days begin with words like clear, cloudy, or rain.'],
      ['학생', 'Why did he write down the weather so carefully?'],
      ['선생님', 'Many people think it’s because wind and waves mattered so much to a navy fighting at sea.'],
      ['해설', 'He often wrote that he practiced archery. He trained with his officers by shooting arrows together.'],
      ['해설', 'There is also a record that he test-fired the cannons of a turtle ship just before the war broke out.'],
      ['학생', 'So he was ready for the war in advance.'],
      ['해설', 'That year, his fleet won battle after battle, at Okpo, at Hansando, and elsewhere.'],
      ['선생님', 'The Battle of Hansando is famous for the crane-wing formation, which surrounded the enemy like a crane spreading its wings.'],
      ['해설', 'In 1593, Yi became Samdo Sugun Tongjesa, the commander of the navies of three provinces.'],
      ['해설', 'The diary also strictly records how he judged his men and gave rewards and punishments.'],
      ['학생', 'He must have been a very strict general.'],
      ['선생님', 'If military discipline falls apart, so does the army. But as you read on, you see another side of him.'],
      ['해설', 'He wrote about days he suffered from illness, and nights he could not sleep, worrying about his country.'],
      ['해설', 'Above all, his worry for his mother and his longing for her appear again and again.'],
      ['선생님', 'He often worried about her health and felt relieved when news came that she was well.'],
      ['학생', 'So even the great general was a son who missed his mother.'],
      ['해설', 'He also wrote honestly about his anger at fellow commanders, especially Won Gyun.'],
      ['선생님', 'He did not write it for others to read, so his feelings show without any decoration.'],
      ['학생', 'Yi Sun-sin the human feels closer to me than Yi Sun-sin the hero.'],
      ['선생님', 'That is the power of this diary. Steady writing preserved both one man’s heart and the reality of war.'],
      ['해설', 'In 2013, Nanjung Ilgi was listed in UNESCO’s Memory of the World Register.'],
    ],
  },

  'tg-nanjung-2': {
    title: 'The War Diary of Yi Sun-sin, Part 2',
    names: { 해설: 'Narrator', 선생님: 'Teacher', 학생: 'Student' },
    outro: [
      'When it seemed he had lost everything, what gave Yi Sun-sin the strength to rise again?',
      'Those who seek death will live. What kind of resolve did this demand from the commanders before Myeongnyang?',
      'If I had to do my duty in the middle of great sadness, what would help me hold on?',
    ],
    lines: [
      ['해설', 'In 1597, under suspicion from the royal court, Yi Sun-sin lost his command and was taken to Hanyang and jailed.'],
      ['해설', 'He escaped death, but was ordered to follow the army without rank. This was called baegui jonggun.'],
      ['학생', 'Teacher, they put the general who saved the country in prison?'],
      ['선생님', 'Many things were tangled together. Today we focus on his diary from that time. Again, I’ll sum it up.'],
      ['해설', 'As he set out, a greater sorrow struck. His mother died while traveling to see her son.'],
      ['해설', 'He could not even hold a proper funeral for her before he had to leave again.'],
      ['선생님', 'The diary shows his loud weeping and deep grief from that time.'],
      ['학생', 'He lost his mother right after leaving prison. That’s so cruel.'],
      ['해설', 'That summer, the Joseon navy under Won Gyun suffered a terrible defeat at Chilcheollyang.'],
      ['해설', 'Yi was made naval commander of the three provinces again, but only a few ships were left.'],
      ['선생님', 'Some at court even talked about giving up the navy and fighting on land.'],
      ['해설', 'Before the Battle of Myeongnyang, he gathered his officers and strengthened their resolve with a saying from military books.'],
      ['해설', 'Those who are ready to die will live, and those who try only to live will die.'],
      ['학생', 'Pilsa jeuksaeng, pilsaeng jeuksa. So that saying is in his diary!'],
      ['선생님', 'Yes. And in the narrow strait of Myeongnyang, he drove back a far larger number of enemy ships.'],
      ['해설', 'After the victory at Myeongnyang, the Joseon navy began to regain its strength to guard the sea.'],
      ['해설', 'But that fall, his third son, Myeon, was killed fighting Japanese soldiers in their hometown of Asan.'],
      ['해설', 'When Yi heard the news, he wrote of a sorrow that felt like his heart was tearing apart.'],
      ['학생', 'He lost his son right after a victory. How did he bear it?'],
      ['선생님', 'The diary shows both a commander carrying on his duties and a father grieving for his son.'],
      ['해설', 'In 1598, as the Japanese army tried to withdraw, Yi sailed to the sea of Noryang with the Ming navy.'],
      ['해설', 'In the Battle of Noryang, he was hit by an enemy bullet and fell.'],
      ['선생님', 'The story that he said not to announce his death during the battle comes from other records, not the diary.'],
      ['학생', 'Then when does the diary end?'],
      ['선생님', 'It stops in the eleventh month of 1598, just before Noryang. He could not write that final scene himself.'],
      ['학생', 'It makes my heart heavy that the diary ends that way.'],
      ['선생님', 'Some days are missing, but through nearly seven years of war, he kept the diary going.'],
      ['학생', 'He kept writing even on hard days. I want to learn from that.'],
      ['해설', 'Yi Sun-sin died in the Battle of Noryang in 1598.'],
    ],
  },

  'tg-mokmin': {
    title: 'Mokmin Simseo: Admonitions on Governing the People',
    names: { 해설: 'Narrator', 선생님: 'Teacher', 학생: 'Student' },
    outro: [
      'Why did Jeong Yak-yong put integrity at the center of a magistrate’s attitude?',
      'The title means a book written only in the heart, because he could not put it into practice. What feelings are in that?',
      'Which teaching of Mokmin Simseo do public officials today need most?',
    ],
    lines: [
      ['해설', 'Jeong Yak-yong was sent into exile in 1801, and he lived mostly in Gangjin, Jeolla Province, until 1818.'],
      ['해설', 'He wrote many books there. Mokmin Simseo was completed in 1818, as his exile was coming to an end.'],
      ['해설', 'Mokmin means caring for the people. Magistrates who ruled local towns were called mokmingwan.'],
      ['학생', 'Teacher, then what does simseo mean?'],
      ['선생님', 'A book of the heart. In the preface, he said he had the heart to care for people but could not act on it himself.'],
      ['학생', 'Because he was in exile and could not govern a town himself.'],
      ['해설', 'When he was younger, Dasan, as he was also known, worked as a secret royal inspector in Gyeonggi Province.'],
      ['해설', 'He also governed Goksan as its magistrate.'],
      ['해설', 'Along the way, he saw for himself how people suffered under cruel magistrates and local clerks.'],
      ['선생님', 'He used that experience and many records to lay out a magistrate’s duties in order. Let’s look at the contents.'],
      ['해설', 'Mokmin Simseo has forty-eight volumes, divided into twelve parts with six sections each, seventy-two sections in all.'],
      ['해설', 'The first part begins with taking office, being appointed and traveling to the town.'],
      ['학생', 'So it starts from the moment of appointment.'],
      ['선생님', 'Yes. And the last part is about finishing the job and leaving the town. It covers everything from start to end.'],
      ['해설', 'In between are parts on personal conduct, serving the state, and loving the people.'],
      ['해설', 'Then six parts cover the duties of each area of government, such as taxes, rites, military, justice, and public works.'],
      ['해설', 'He also wrote a separate part on saving starving people in years of bad harvest.'],
      ['학생', 'The order looks just like a work guide for public officials.'],
      ['선생님', 'Right. It is a very practical handbook. But at its center is one attitude.'],
      ['해설', 'In the part on personal conduct, Dasan called integrity a magistrate’s basic duty and the source of all goodness.'],
      ['학생', 'Why is integrity so important?'],
      ['선생님', 'Because when a magistrate is greedy, the burden falls on the people in the end.'],
      ['해설', 'In another essay, Dasan wrote that magistrates exist for the people, not the people for the magistrates.'],
      ['학생', 'That applies to public officials today too.'],
      ['해설', 'The part on loving the people covers caring for the old, children, and the poor and sick.'],
      ['선생님', 'It would be interesting to compare those sections with today’s welfare policies.'],
      ['학생', 'It’s amazing that someone thought this way two hundred years ago.'],
      ['해설', 'Mokmin Simseo is counted among Dasan’s greatest works, along with Gyeongse Yupyo and Heumheum Sinseo.'],
      ['해설', 'Jeong Yak-yong was born in 1762 and died in 1836.'],
    ],
  },
};
