// 청소년 영어 원고: 위대한 유산 1~10화 (stories/teen-expect.js). 문장은 자체 각색.
// lines 의 첫 칸은 한국어 이야기 cast 의 이름 그대로.
export default {
  'ge-01': {
    title: 'Great Expectations, Part 1',
    names: { 해설: 'Narrator', 핍: 'Pip', 매그위치: 'The Convict', 누나: 'Mrs. Joe', 조: 'Joe Gargery', 병사: 'Sergeant' },
    outro: [
      'While frightened Pip helped the convict, which was stronger in him, fear or pity?',
      'What do Joe’s words to the convict show us about the kind of man Joe is?',
      'How much do you agree that even a criminal is just a human being when he is starving?',
    ],
    lines: [
      ['해설', 'On the afternoon of Christmas Eve, a boy stood alone in a churchyard beside the gray marshes.'],
      ['해설', 'His name was Philip Pirrip. As a small child he could not say it, so he called himself Pip.'],
      ['해설', 'Pip had never seen his parents’ faces. The names on their gravestones were all he knew.'],
      ['해설', 'Suddenly a man with an iron on his leg rose up from among the graves.'],
      ['매그위치', 'Keep still, boy. If you scream, you’ll be sorry.'],
      ['해설', 'The man turned Pip upside down and emptied his pockets. All he found was a piece of bread.'],
      ['매그위치', 'Bring me a file and some food by early tomorrow. And don’t tell anyone.'],
      ['핍', 'I will bring them. I promise I will.'],
      ['해설', 'Pip was raised by his sister, who was more than twenty years older and married to Joe, the blacksmith.'],
      ['해설', 'His sister often beat him. In those days, beating children to control them was common.'],
      ['누나', 'Where have you been running around? Do you know how hard it is to bring you up?'],
      ['조', 'Pip, old chap, your sister is on the rampage today. Be careful.'],
      ['해설', 'Joe was a big man with a gentle heart, and he protected Pip like a friend.'],
      ['해설', 'That night, guns boomed in the distance. It meant a convict had escaped from the prison ship.'],
      ['해설', 'At dawn, Pip took bread, cheese and a pork pie from the pantry, and a file from the forge.'],
      ['해설', 'On the foggy marsh, the man gulped down the food like a hungry dog.'],
      ['핍', 'I am glad you enjoy it, sir.'],
      ['매그위치', 'You’re a good boy. I won’t forget this.'],
      ['해설', 'When Pip mentioned another escaped convict on the marsh, the man’s face twisted with rage.'],
      ['해설', 'At Christmas dinner, when his sister got up to fetch the pork pie, Pip almost stopped breathing.'],
      ['해설', 'At that very moment the door flew open, and soldiers rushed in holding handcuffs.'],
      ['병사', 'Blacksmith, we are hunting escaped convicts. Please fix these handcuffs for us.'],
      ['해설', 'Joe and Pip followed the soldiers to the marsh. In a ditch, two convicts were fighting.'],
      ['매그위치', 'I caught him! I could not let this one get away!'],
      ['해설', 'As he was taken away, the man’s eyes met Pip’s. Pip shook his head to show he had not told.'],
      ['매그위치', 'I took food from the blacksmith’s house. I ate the pie too.'],
      ['조', 'Whatever you have done, we would not have you starve for it, poor fellow.'],
      ['해설', 'The man was taken back to the prison ship, and Pip never told anyone what had happened.'],
      ['해설', 'No one knew then that this strange convict would change Pip’s whole life.'],
      ['해설', 'Great Expectations appeared in the weekly magazine All the Year Round from December 1860 to August 1861.'],
    ],
  },

  'ge-02': {
    title: 'Great Expectations, Part 2',
    names: { 해설: 'Narrator', 펌블추크: 'Uncle Pumblechook', 누나: 'Mrs. Joe', 에스텔라: 'Estella', 해비셤: 'Miss Havisham', 핍: 'Pip', 허버트: 'Pale Young Gentleman', 조: 'Joe' },
    outro: [
      'Why did a few words from Estella make Pip ashamed of his hands and boots?',
      'What do the stopped clocks and the faded wedding dress tell us about Miss Havisham?',
      'Have you ever felt small because of how you looked in someone else’s eyes?',
    ],
    lines: [
      ['해설', 'Last time, Pip secretly brought food to an escaped convict on the marshes.'],
      ['해설', 'Some time later, Joe’s uncle Pumblechook, a corn merchant, arrived looking excited.'],
      ['펌블추크', 'Miss Havisham, the rich lady in town, wants a boy to come and play there.'],
      ['누나', 'If she likes you, who knows what luck may come? Go and scrub your face!'],
      ['해설', 'Miss Havisham’s house was large and gloomy. Its windows were bricked up or covered with iron bars.'],
      ['해설', 'The gate was opened by Estella, a pretty, proud girl about Pip’s age.'],
      ['에스텔라', 'Come in, boy. Bring the candle and follow me.'],
      ['해설', 'In a dark room sat a woman in a wedding dress that had turned yellow with age.'],
      ['해설', 'She wore only one shoe. Every clock in the room had stopped at twenty minutes to nine.'],
      ['해비셤', 'Are you afraid? I have not left this room since before you were born.'],
      ['해비셤', 'My heart has been broken ever since that day. Now, you two, play cards.'],
      ['해설', 'As Estella dealt the cards, she openly looked down on Pip.'],
      ['에스텔라', 'He calls the knaves Jacks, this boy! And what coarse hands and thick boots he has!'],
      ['해비셤', 'She says such things, and you say nothing? What do you think of her?'],
      ['핍', 'I think she is very proud. And very pretty.'],
      ['해설', 'For the first time, Pip felt ashamed of his rough hands and his old boots.'],
      ['해설', 'Seeing working hands as a mark of low rank was the class-minded view of that time.'],
      ['해설', 'When Estella handed him bread and meat as if he were a dog, Pip hid behind a wall and cried.'],
      ['해설', 'After that, Pip went to the house on fixed days and pushed Miss Havisham’s chair around the room.'],
      ['해설', 'One day in the garden, a pale young gentleman suddenly challenged him to a boxing match.'],
      ['허버트', 'Don’t ask why. Come and fight! Let’s keep to the rules.'],
      ['해설', 'The boy fell down again and again but got up smiling. At last, he held out his hand.'],
      ['허버트', 'That means you have won. It was a good fight.'],
      ['에스텔라', 'Come here. You may kiss my cheek if you like.'],
      ['해설', 'Yet Pip was not happy. He felt as if he had been tossed a coin like a beggar.'],
      ['해설', 'At home, Pip told wild lies, such as a black velvet coach inside the house.'],
      ['핍', 'Joe, it was all lies. Why am I so common and so low?'],
      ['조', 'Pip, if you want to be uncommon, lies won’t do it. You must go straight.'],
      ['해설', 'From that day, two words settled in Pip’s heart: Estella and gentleman.'],
      ['해설', 'This novel is told in the first person by the grown-up Pip, looking back on his past.'],
    ],
  },

  'ge-03': {
    title: 'Great Expectations, Part 3',
    names: { 해설: 'Narrator', 해비셤: 'Miss Havisham', 조: 'Joe', 핍: 'Pip', 오릭: 'Orlick', 누나: 'Mrs. Joe', 비디: 'Biddy' },
    outro: [
      'Where did the change come from, that the forge Pip once loved now made him ashamed?',
      'How does Biddy’s question reveal feelings that Pip himself had not seen?',
      'If I choose my dream only to win someone’s approval, is that dream truly mine?',
    ],
    lines: [
      ['해설', 'Last time, Pip met Estella and felt ashamed of his own life for the first time.'],
      ['해설', 'His visits to the house went on for years. Estella grew more beautiful, but stayed cold.'],
      ['해설', 'Whenever Estella treated Pip coldly, Miss Havisham whispered with delight.'],
      ['해비셤', 'Yes, break their hearts, my pride and hope. Break them for me too.'],
      ['해설', 'When Pip grew older, Miss Havisham sent for Joe. It was time for Pip to become a blacksmith’s apprentice.'],
      ['해비셤', 'This is for the boy’s visits all this time. Twenty-five guineas.'],
      ['조', 'Thank you, ma’am. Pip is my apprentice now, and my friend.'],
      ['해설', 'That day the visits ended, and Pip officially became Joe’s apprentice.'],
      ['해설', 'Once, this would have made him happy. But now Pip was only ashamed of the forge.'],
      ['핍', 'What if Estella sees my face covered in soot through the window?'],
      ['해설', 'Orlick, who worked at the forge, had a nasty temper and hated Pip and his sister.'],
      ['오릭', 'Does only the young apprentice get a day off? I want a half-holiday too.'],
      ['누나', 'You lazy fellow! Joe, why do you keep a man like that?'],
      ['해설', 'They had a big quarrel. It only ended when Joe knocked Orlick to the ground.'],
      ['해설', 'A few nights later, Pip came home from town and found a crowd in front of the house.'],
      ['해설', 'Someone had struck his sister down in the kitchen. A leg iron lay beside her.'],
      ['해설', 'It was a convict’s leg iron, cut open with a file. Pip felt it was somehow his fault.'],
      ['해설', 'His sister lived, but she lost her speech and could not move well. Strangely, her temper grew gentler.'],
      ['해설', 'Biddy, who had studied with Pip at the village school, came to live with them and care for her.'],
      ['해설', 'Biddy was clever and warm. Only to her did Pip open his heart.'],
      ['핍', 'Biddy, I want to be a gentleman. Because of the girl at that house.'],
      ['비디', 'Do you want to be a gentleman for yourself, or to show her?'],
      ['비디', 'If she looks down on you like that, I don’t think she is worth caring about.'],
      ['핍', 'You are right. If only I could fall in love with you, everything would be easier.'],
      ['해설', 'Biddy only smiled sadly and said nothing.'],
      ['해설', 'Later, when Pip visited the house, he heard Estella had gone abroad to be educated as a lady.'],
      ['해비셤', 'Do you miss her? She is now far out of your reach.'],
      ['해설', 'Then, in the fourth year of Pip’s apprenticeship, a strange gentleman appeared at the village inn.'],
      ['해설', 'Dickens spent several years of his childhood in Chatham, a dockyard town in Kent.'],
    ],
  },

  'ge-04': {
    title: 'Great Expectations, Part 4',
    names: { 해설: 'Narrator', 재거스: 'Mr. Jaggers', 조: 'Joe', 핍: 'Pip', 펌블추크: 'Uncle Pumblechook', 해비셤: 'Miss Havisham', 비디: 'Biddy' },
    outro: [
      'Why did the news of great expectations feel so different to Pip, Joe and Biddy?',
      'What satire is hidden in how the tailor and Pumblechook suddenly change toward Pip?',
      'Does the world still treat people differently when they suddenly become rich?',
    ],
    lines: [
      ['해설', 'Last time, Pip became Joe’s apprentice, and his sister was attacked and lost her speech.'],
      ['해설', 'One Saturday night at the village inn, a large gentleman came up to Joe and Pip.'],
      ['해설', 'Pip had once seen him on the stairs at Miss Havisham’s. He was Jaggers, a London lawyer.'],
      ['재거스', 'Joseph Gargery, the blacksmith? I have something to say about your apprentice, Pip.'],
      ['재거스', 'If you release this young man from his apprenticeship, do you want payment?'],
      ['조', 'If it’s for Pip’s good, I want no money. I wouldn’t think of it.'],
      ['재거스', 'Then I will tell you. This young man has great expectations.'],
      ['재거스', 'A person of property wishes him to be brought up as a gentleman.'],
      ['해설', 'There were two conditions. Pip must always keep the name Pip, and he must not ask who the giver was.'],
      ['재거스', 'The name is secret until that person reveals it. Even if you guess, do not say it.'],
      ['해설', 'Pip’s heart raced. He believed only Miss Havisham could do such a thing.'],
      ['핍', 'She wants to make me a gentleman good enough for Estella.'],
      ['재거스', 'From now on, I am your guardian. Come to London in a week. Here is money for clothes.'],
      ['해설', 'After Jaggers left, a strange silence filled the kitchen.'],
      ['조', 'Our Pip, a gentleman. That’s a fine thing, a very fine thing indeed.'],
      ['해설', 'Joe smiled, but his eyes were wet. Biddy said nothing and kept on sewing.'],
      ['해설', 'When Pip went to town for new clothes, the tailor who had ignored him now bowed low.'],
      ['해설', 'Pumblechook grabbed Pip’s hand and boasted that he had seen Pip’s future from the start.'],
      ['펌블추크', 'I always said so! I said this boy would be great!'],
      ['해설', 'When Pip went to say goodbye, Miss Havisham smiled as if she knew everything.'],
      ['해비셤', 'Goodbye, Pip. Wherever you go, you must always keep the name of Pip.'],
      ['해설', 'The night before he left, Pip asked Biddy to help Joe improve himself.'],
      ['핍', 'If Joe learns to read and has better manners, I won’t be so embarrassed to bring him up later.'],
      ['비디', 'Joe has his pride. He is a fine man just as he is.'],
      ['핍', 'Biddy, aren’t you just envious of my good luck?'],
      ['비디', 'If you think so, I have nothing more to say.'],
      ['해설', 'At dawn, Joe and Biddy threw an old shoe after Pip for good luck as he left.'],
      ['해설', 'At the signpost at the end of the village, Pip burst into tears. But once on the coach, his tears dried.'],
      ['해설', 'At the end of the road, where the mist had lifted, the wide world of London was waiting.'],
      ['해설', 'In 1861, when the serial ended, the novel came out as a book in three volumes.'],
    ],
  },

  'ge-05': {
    title: 'Great Expectations, Part 5',
    names: { 해설: 'Narrator', 재거스: 'Mr. Jaggers', 웨믹: 'Wemmick', 허버트: 'Herbert Pocket', 핍: 'Pip' },
    outro: [
      'Who was hurt when Miss Havisham stopped the clocks and raised Estella as a tool of revenge?',
      'What fun and meaning does Wemmick add by being a different person at the office and at home?',
      'In a society that measures gentlemen by looks and spending, where does true dignity come from?',
    ],
    lines: [
      ['해설', 'Last time, Pip was promised a fortune by an unknown giver and left his village.'],
      ['해설', 'London was dirtier and noisier than Pip had imagined. Jaggers’s office was near the courts.'],
      ['해설', 'On the office shelf stood plaster casts of the faces of former clients who had been hanged.'],
      ['재거스', 'Give me facts. I do not trust guesses or rumors.'],
      ['해설', 'The clerk Wemmick took Pip to his rooms. His mouth was as stiff and straight as a post-office slot.'],
      ['웨믹', 'At the office, I am an office man. At home, I am somebody else.'],
      ['해설', 'Pip was to share rooms with Herbert Pocket. The two stared at each other in surprise.'],
      ['허버트', 'Why, it’s you! You’re the boy who knocked me down in that garden!'],
      ['해설', 'Herbert had been sent to the house that day as Miss Havisham’s relative. They both laughed.'],
      ['허버트', 'Pip sounds a bit stiff. May I call you Handel? He wrote a piece called The Harmonious Blacksmith.'],
      ['해설', 'Herbert kindly taught Pip table manners, one by one.'],
      ['허버트', 'Handel, in London, it’s better not to put your knife in your mouth. It’s just how things are done.'],
      ['해설', 'He also told Pip the story of Miss Havisham’s past.'],
      ['허버트', 'She was a rich heiress. Then a smooth-talking man asked her to marry him.'],
      ['허버트', 'On the morning of the wedding, she got a letter from him saying he would not marry her.'],
      ['허버트', 'That was at twenty minutes to nine. At that moment, she stopped every clock in the house.'],
      ['허버트', 'They say the man was a swindler who plotted with her half-brother to get her money.'],
      ['허버트', 'Estella is her adopted daughter. She raised her to take revenge on men.'],
      ['핍', 'So that is how Estella was brought up.'],
      ['해설', 'Pip studied with Herbert’s father, Matthew Pocket, and learned the life of a gentleman.'],
      ['해설', 'He bought expensive clothes and furniture, and joined a club of young gentlemen.'],
      ['해설', 'Drummle, an arrogant rich man’s son, was there too. Pip disliked him from the start.'],
      ['해설', 'However much money they had, it was never enough. Pip and Herbert sighed over lists of debts.'],
      ['허버트', 'Handel, just writing our debts down neatly somehow makes me feel rich.'],
      ['해설', 'Invited to Wemmick’s home, Pip saw a little house built like a castle, and Wemmick’s aged father.'],
      ['웨믹', 'I fire this little cannon every evening to please my Aged Parent.'],
      ['해설', 'Unlike his stiff face at the office, Wemmick at home was a loving son.'],
      ['해설', 'Then one day a letter came from home. Joe was coming to London.'],
      ['해설', 'Dickens published A Christmas Carol in 1843.'],
    ],
  },

  'ge-06': {
    title: 'Great Expectations, Part 6',
    names: { 해설: 'Narrator', 조: 'Joe', 핍: 'Pip', 에스텔라: 'Estella', 비디: 'Biddy', 허버트: 'Herbert' },
    outro: [
      'What lay deep in Pip’s heart when he could not welcome Joe’s visit?',
      'What does Estella’s warning that she has no heart reveal about her?',
      'Like Pip secretly helping his friend, what is the value of doing good without being seen?',
    ],
    lines: [
      ['해설', 'Last time, Pip began a gentleman’s life in London with Herbert.'],
      ['해설', 'Pip was not glad to hear Joe was coming. He worried about who might see him.'],
      ['해설', 'Joe stood awkwardly in his best clothes. The hat in his hand kept falling.'],
      ['조', 'Pip, I mean, sir. I am glad to see you living so well.'],
      ['핍', 'Joe, don’t call me sir. Just call me Pip.'],
      ['해설', 'But there was irritation in Pip’s voice, and Joe felt it.'],
      ['조', 'Miss Havisham asked me to tell you. Estella has come home, and you should go and see her.'],
      ['조', 'Pip, I am most myself at the forge. Here, I keep turning into the wrong man.'],
      ['조', 'Next time, come to the forge and look at me through the window. That’s more like us.'],
      ['해설', 'Only after Joe left did Pip feel ashamed. He ran after him, but Joe was gone.'],
      ['해설', 'Back home, Pip met Estella, now a grown lady. She was dazzlingly beautiful.'],
      ['에스텔라', 'Let me tell you now. I have no heart.'],
      ['에스텔라', 'No sympathy, no tenderness. So you had better not love me.'],
      ['해설', 'Even after hearing this, Pip fell deeper in love with her.'],
      ['해설', 'Yet he went back to London without stopping at Joe’s house, so close by.'],
      ['해설', 'In London society, Estella played with the hearts of many men.'],
      ['해설', 'Drummle was one of them. Pip burned with jealousy, but Estella did not care.'],
      ['해설', 'Around then, news came from home that Pip’s sister had died.'],
      ['해설', 'On the day of the funeral, Joe said nothing and held Pip’s hand tightly.'],
      ['비디', 'At the end, she called Joe, then said Pardon, and then said your name.'],
      ['핍', 'Biddy, I will come often now. I will not leave Joe alone.'],
      ['비디', 'Are you sure you can keep that promise?'],
      ['해설', 'Pip got angry, but deep down he feared Biddy’s doubt might be right.'],
      ['해설', 'Back in London, Pip quietly arranged one good thing.'],
      ['해설', 'With Wemmick’s help, he used his own money to get Herbert a place in a trading company.'],
      ['허버트', 'Handel, listen! I’ve got a place in a company! My luck has finally turned!'],
      ['해설', 'Herbert never knew the money came from Pip. It was the best fruit his fortune ever bore.'],
      ['해설', 'In Pip’s twenty-third year, on a stormy night, strange footsteps came up the stairs.'],
      ['해설', 'In David Copperfield, too, Dickens had told the story through the hero looking back in the first person.'],
    ],
  },

  'ge-07': {
    title: 'Great Expectations, Part 7',
    names: { 해설: 'Narrator', 매그위치: 'Abel Magwitch', 핍: 'Pip', 재거스: 'Mr. Jaggers', 허버트: 'Herbert' },
    outro: [
      'Why was it such a shock for Pip to learn that Magwitch was his benefactor?',
      'How does Pip’s mistaken belief in Miss Havisham make us see the earlier story differently?',
      'Do you think the value of help changes depending on who gives it?',
    ],
    lines: [
      ['해설', 'Last time, Pip’s love for Estella grew, and he secretly helped Herbert’s future.'],
      ['해설', 'On a stormy night while Herbert was away on business, Pip sat alone reading.'],
      ['해설', 'Up the stairs came an old man with graying hair and skin darkened by the sun.'],
      ['매그위치', 'You’re Pip, aren’t you? You’ve grown. You’ve grown up so fine.'],
      ['해설', 'The man held out both hands. Confused, Pip stepped back.'],
      ['해설', 'Then Pip recognized him. He was the convict from the marshes long ago.'],
      ['핍', 'If you have come to thank me for that day, I accept it. Now let us go our separate ways.'],
      ['해설', 'The man looked slowly and sadly around at the fine furniture and books.'],
      ['매그위치', 'These clothes, these books, this room. Do you know whose money paid for them?'],
      ['매그위치', 'Your guardian, the lawyer. His name begins with a J, doesn’t it? Jaggers.'],
      ['해설', 'The color drained from Pip’s face. His benefactor was not Miss Havisham.'],
      ['매그위치', 'Yes, Pip. I am the one who made you a gentleman.'],
      ['매그위치', 'That day, you helped me when I was starving. I swore every penny I earned would go to you.'],
      ['해설', 'Magwitch said he had been sent to Australia as a convict and made a fortune raising sheep.'],
      ['매그위치', 'I could never be a gentleman. But I thought I could make one.'],
      ['해설', 'Pip heard his dreams crash down. His belief that he would marry Estella was a mistake too.'],
      ['해설', 'At that time, a transported convict who returned to England without permission could be put to death.'],
      ['매그위치', 'If they catch me, I’ll hang. Still, I had to see you once.'],
      ['해설', 'Pip did not sleep all night. It tortured him to think he had abandoned Joe for this man.'],
      ['해설', 'The next day, Jaggers confirmed only one name and pretended not to know the rest.'],
      ['재거스', 'I simply passed on money from a man named Magwitch in New South Wales.'],
      ['재거스', 'As for that man being in England now, I will treat it as something I never heard.'],
      ['해설', 'When Herbert came back a few days later, Pip told him everything.'],
      ['허버트', 'Handel, we can’t leave him alone in danger. First, let’s get him out of the country.'],
      ['핍', 'I won’t take another penny of his money. But we must save his life.'],
      ['해설', 'Magwitch hid in lodgings nearby under a false name, Provis.'],
      ['해설', 'Even in his fear, Pip could not turn away the old man who had risked his life for him.'],
      ['해설', 'That night, Magwitch began to talk about the other convict caught with him on the marshes.'],
      ['해설', 'The first British ships carrying convicts reached Australia in 1788.'],
    ],
  },

  'ge-08': {
    title: 'Great Expectations, Part 8',
    names: { 해설: 'Narrator', 매그위치: 'Magwitch', 허버트: 'Herbert', 핍: 'Pip', 해비셤: 'Miss Havisham', 에스텔라: 'Estella' },
    outro: [
      'Is Miss Havisham’s regret too late, or does it still have meaning?',
      'What effect does it have when the stories of Magwitch and Miss Havisham both lead to Compeyson?',
      'Do people still treat others differently because of their clothes and the way they speak?',
    ],
    lines: [
      ['해설', 'Last time, Pip learned that his benefactor was Magwitch, not Miss Havisham.'],
      ['매그위치', 'The man I fought with on the marsh that day was a swindler called Compeyson.'],
      ['매그위치', 'He cheated people while dressed as a gentleman. When we were caught, he put all the blame on me.'],
      ['해설', 'They were tried together, but neat, well-dressed Compeyson got a lighter sentence.'],
      ['해설', 'Giving a lighter sentence to someone who looked like a gentleman reflected the class-minded view of that time.'],
      ['해설', 'As they listened, Herbert quietly passed Pip a note.'],
      ['허버트', 'Handel, the man who left Miss Havisham was also named Compeyson.'],
      ['해설', 'The wounds of two different people came from the same man.'],
      ['해설', 'Pip went to Miss Havisham’s house. Estella was there too.'],
      ['핍', 'Miss Havisham, I know who my benefactor is. It was not you.'],
      ['해비셤', 'Yes. I let you believe it. What of it?'],
      ['핍', 'Estella, I have loved you since the first day I saw you.'],
      ['에스텔라', 'Your words do not touch me at all. I am going to marry Drummle.'],
      ['핍', 'Him, of all people? He will treat you badly.'],
      ['에스텔라', 'It is my own choice. I do not want to make you unhappy too.'],
      ['해설', 'Soon after, Estella married Drummle. Pip’s heart felt empty.'],
      ['해설', 'A few weeks later, Miss Havisham sent for Pip, and he went to the house again.'],
      ['해비셤', 'I shaped her heart to be like my own wound. Only now do I see what I have done.'],
      ['해비셤', 'Pip, can you forgive me?'],
      ['핍', 'I already have. Instead, could you help my friend Herbert?'],
      ['해설', 'Miss Havisham gladly gave nine hundred pounds for Herbert’s business.'],
      ['해설', 'As Pip was leaving, he turned back to look at the room one last time.'],
      ['해설', 'The fire caught her old dress, and Miss Havisham ran toward him, wrapped in flames.'],
      ['해설', 'Pip wrapped her in his coat, pushed her to the floor, and put out the fire. His hands were badly burned.'],
      ['해설', 'Her mind wandering, Miss Havisham lay in bandages and kept repeating the same words.'],
      ['해비셤', 'What have I done to her? Forgive me.'],
      ['해설', 'Miss Havisham survived, but she grew very weak and died not long after.'],
      ['해설', 'While caring for Pip’s bandaged hands, Herbert began an unexpected story.'],
      ['해설', 'Dickens died in 1870 and was buried in Westminster Abbey in London.'],
    ],
  },

  'ge-09': {
    title: 'Great Expectations, Part 9',
    names: { 해설: 'Narrator', 허버트: 'Herbert', 재거스: 'Mr. Jaggers', 매그위치: 'Magwitch', 관리: 'Officer', 핍: 'Pip' },
    outro: [
      'How has Pip’s heart changed, from disgust at Magwitch to a wish to protect him to the end?',
      'What does the secret of Estella’s birth show about this novel’s view of class and family?',
      'How should we respond to deep love shown by someone who once committed a crime?',
    ],
    lines: [
      ['해설', 'Last time, Pip saved Miss Havisham from the fire, and Estella married Drummle.'],
      ['허버트', 'Provis had a wife and a little daughter. His wife was tried for murder.'],
      ['허버트', 'Thanks to Mr. Jaggers, she was set free. But after that, both she and the girl disappeared.'],
      ['해설', 'Pip remembered Molly, Jaggers’s housekeeper. Her eyes and hands were just like Estella’s.'],
      ['재거스', 'Let me put a case. Suppose a lawyer defended a woman and got her set free.'],
      ['재거스', 'And suppose he sent her daughter to a lonely rich lady, to give the child a chance in life.'],
      ['해설', 'Estella was the daughter of Magwitch and Molly. Pip kept the secret in his heart.'],
      ['해설', 'Meanwhile, Compeyson learned that Magwitch had come back. Wemmick secretly warned Pip.'],
      ['해설', 'Pip and Herbert rowed on the Thames every day with their friend Startop.'],
      ['허버트', 'If we take the boat out every day, no one will think it strange on the day we really go.'],
      ['해설', 'The plan was to row Magwitch down the river and put him on a steamer going abroad.'],
      ['해설', 'Just before they left, Pip got a mysterious letter asking him to come to the sluice-house on the marshes.'],
      ['해설', 'Orlick was hiding there. He confessed that he was the one who had attacked Pip’s sister.'],
      ['해설', 'Just as Orlick was about to kill Pip too, Herbert and Startop rushed in and saved him.'],
      ['해설', 'On the chosen morning, they took Magwitch aboard and went down the river with the tide.'],
      ['매그위치', 'Out on the river with my dear boy. Could there be a better day than this?'],
      ['해설', 'They spent a night at a riverside inn. The next day, a steamer came toward them.'],
      ['해설', 'Then another boat blocked their way. In it were officers and a man hiding his face in a cloak.'],
      ['관리', 'You there, Magwitch, a returned convict! Surrender!'],
      ['해설', 'Magwitch leaped forward and pulled off the man’s cloak. It was Compeyson.'],
      ['해설', 'The steamer struck their boat and turned it over. The two men sank together, locked in a struggle.'],
      ['해설', 'Soon Magwitch came up, badly hurt. Compeyson never came up again.'],
      ['해설', 'Magwitch was arrested on the spot. Pip held his hand as he was taken away.'],
      ['매그위치', 'Pip, you don’t need to look after me now. You must live as a gentleman.'],
      ['핍', 'No. I will stay with you to the end, just as you never forgot me.'],
      ['해설', 'The convict who had once horrified Pip now seemed more loving than anyone.'],
      ['해설', 'Magwitch’s wealth would go to the Crown. That was how Pip’s fortune disappeared.'],
      ['해설', 'The day of the trial came closer. Magwitch grew weaker day by day.'],
      ['해설', 'From 1858, Dickens gave paid public readings of his own works.'],
    ],
  },

  'ge-10': {
    title: 'Great Expectations, Part 10',
    names: { 해설: 'Narrator', 매그위치: 'Magwitch', 핍: 'Pip', 조: 'Joe', 비디: 'Biddy', 에스텔라: 'Estella' },
    outro: [
      'Pip lost his whole fortune. What did he gain in the end?',
      'Both the beginning and the end feature the marsh village and Joe. What feeling does this create?',
      'What makes a true gentleman, or simply a good person, money or the heart?',
    ],
    lines: [
      ['해설', 'Last time, Magwitch was caught while trying to escape, and Compeyson drowned in the river.'],
      ['해설', 'The court sentenced Magwitch to death. But he was already lying in the prison hospital.'],
      ['해설', 'Every day Pip visited him, sat beside him, and held his hand.'],
      ['매그위치', 'Pip, you come every day. That is enough for me.'],
      ['핍', 'Can you hear me? You had a daughter. She is alive, and she has become a beautiful lady.'],
      ['핍', 'And I love her.'],
      ['해설', 'Magwitch raised Pip’s hand to his lips and quietly died, before the sentence could be carried out.'],
      ['해설', 'Left alone and chased by debts, Pip fell ill with a high fever.'],
      ['해설', 'When he woke, a familiar face was beside his bed. It was Joe.'],
      ['조', 'Don’t worry, Pip. We’re still friends, old chap, ever the best of friends.'],
      ['해설', 'Joe nursed Pip for weeks and, without telling him, even paid his debts.'],
      ['핍', 'Joe, I was ashamed of you. Can you still forgive me?'],
      ['조', 'What is there to forgive? What’s past is past.'],
      ['해설', 'Once he was well, Pip went home to ask Biddy to marry him.'],
      ['해설', 'But that very day was Joe and Biddy’s wedding day.'],
      ['비디', 'Pip, thank you for coming. Today I married Joe.'],
      ['핍', 'I hope you will both be happy. With all my heart.'],
      ['해설', 'Pip joined Herbert’s company, worked at its office abroad, lived simply, and paid off his debts.'],
      ['해설', 'Eleven years passed. By the fire in the old kitchen sat a little boy.'],
      ['조', 'His name is Pip. We named him after you.'],
      ['해설', 'That evening, Pip visited the place where Miss Havisham’s house had stood. It had been torn down.'],
      ['해설', 'A woman stood in the misty empty ground. It was Estella.'],
      ['해설', 'Drummle, who had treated her cruelly, had died in an accident some years before.'],
      ['에스텔라', 'I have suffered a great deal. Because of that, I think I finally understand your heart.'],
      ['에스텔라', 'Even if we are apart, will you stay my friend?'],
      ['핍', 'We are friends. And I will not lose you again.'],
      ['해설', 'Pip took her hand and walked out of the ruins. He saw no shadow of another parting.'],
      ['해설', 'After a long journey, Pip learned that the heart, not inherited money, makes a good person.'],
      ['해설', 'Dickens first wrote an ending where the two part, then changed it on the advice of Bulwer-Lytton.'],
    ],
  },
};
