// 청소년 영어 원고 (중학생 이상). 키 = stories/teen-h.js 의 이야기 id.
// 과학 고전의 핵심 실험과 생각을 한국어 각색의 흐름대로 쉬운 영어로 새로 씀(과학자와 가상의 학생의 대화).
export default {
  'th2-galileo-1': {
    title: 'Galileo’s Dialogue, Part 1',
    names: { 해설: 'Narrator', 갈릴레오: 'Galileo Galilei', 학생: 'Student' },
    outro: [
      'Why did Galileo explain the moving Earth through a talk among three people, not a dry paper?',
      'How does the ship’s cabin thought experiment explain why we cannot feel the Earth moving?',
      'Does the fact that scientists can be wrong mean we cannot trust science, or does it mean something else?',
    ],
    lines: [
      ['해설', 'In 1632, in Florence, Italy, Galileo Galilei published his Dialogue Concerning the Two Chief World Systems.'],
      ['해설', 'This story imagines Galileo explaining his book to a student.'],
      ['학생', 'Sir, which two world systems do you mean?'],
      ['갈릴레오', 'One is the system of Ptolemy. The Earth stands still at the center, and the Sun and stars go around it.'],
      ['갈릴레오', 'The other is the system of Copernicus. The Sun is at the center, and the Earth spins daily and circles the Sun.'],
      ['학생', 'But why did you write a dialogue instead of a paper?'],
      ['갈릴레오', 'I had three men debate for four days. Salviati speaks for Copernicus, and Simplicio for Aristotle.'],
      ['갈릴레오', 'Sagredo is an educated man who listens to both and judges. I also wrote in Italian, not Latin.'],
      ['해설', 'Galileo’s ideas grew stronger after he began watching the sky with telescopes he made himself, from around 1609.'],
      ['갈릴레오', 'I found four small stars circling Jupiter. Not every heavenly body goes around the Earth.'],
      ['갈릴레오', 'Venus also had phases like the Moon. Ptolemy’s system could hardly explain that.'],
      ['학생', 'But if the Earth spins so fast, why don’t we feel anything?'],
      ['학생', 'If you drop a stone from a tall tower, the ground moves meanwhile. Shouldn’t the stone land behind?'],
      ['갈릴레오', 'Simplicio makes that same objection in my book. So Salviati asks us to imagine the cabin of a large ship.'],
      ['갈릴레오', 'Below deck, put butterflies, flies, a bowl of fish, and a bottle that drips water drop by drop.'],
      ['갈릴레오', 'When the ship sails smoothly and steadily over a calm sea, what changes inside the cabin?'],
      ['학생', 'Well, the butterflies would be pushed to the back, and the drops would fall at a slant?'],
      ['갈릴레오', 'No. The butterflies fly equally in every direction, and the drops fall straight into the bottle below.'],
      ['갈릴레오', 'Nothing differs from when the ship is still. Everything in the cabin moves along with the ship.'],
      ['학생', 'Oh, so we on the ground, and the falling stone too, are all moving with the Earth!'],
      ['갈릴레오', 'Exactly. Inside something moving steadily, no experiment can show that it is moving.'],
      ['해설', 'This idea later became known as Galilean relativity, and it became a foundation for Newton’s laws of motion.'],
      ['해설', 'But not all his arguments were right. He claimed the tides were caused by the Earth’s motion.'],
      ['해설', 'Today we know tides are caused mainly by the pull of the Moon and the Sun.'],
      ['학생', 'Sir, I want to see sunspots through a telescope too.'],
      ['갈릴레오', 'Looking at the Sun directly through a telescope can badly hurt your eyes. Project its image onto white paper instead.'],
      ['해설', 'Even today, never look at the Sun directly. Use proper equipment, and observe with an adult.'],
      ['해설', 'Because of this book, Galileo was put on trial in Rome the next year, in 1633.'],
    ],
  },

  'th2-galileo-2': {
    title: 'Galileo’s Dialogue, Part 2',
    names: { 해설: 'Narrator', 갈릴레오: 'Galileo Galilei', 학생: 'Student' },
    outro: [
      'Why did Galileo keep doing research even while he was confined after his trial?',
      'How did the thought experiment of tying two stones find a contradiction without any equipment?',
      'What attitude do we need to tell whether a well-known story is fact or legend?',
    ],
    lines: [
      ['해설', 'In 1633, Galileo was called before the court of the Inquisition in Rome. His Dialogue had defended a moving Earth.'],
      ['해설', 'In the end, he had to declare he gave up that idea. He was confined to his house at Arcetri, near Florence.'],
      ['해설', 'Many say he then muttered, and yet it moves. But this is an unconfirmed legend.'],
      ['해설', 'Even while confined, Galileo kept working. This time his subject was falling objects.'],
      ['학생', 'Sir, isn’t it obvious that a heavy stone falls faster than a light one?'],
      ['갈릴레오', 'Aristotle taught that heavier things fall faster. But let’s think it through.'],
      ['갈릴레오', 'Imagine tying a heavy stone and a light stone together with a string and dropping them.'],
      ['갈릴레오', 'The light stone wants to fall slowly, so it holds the heavy one back. The pair should be slower.'],
      ['학생', 'But tied together, they are heavier than the heavy stone alone. So they should fall faster!'],
      ['갈릴레오', 'Exactly. From the same idea, we get two answers, slower and faster.'],
      ['갈릴레오', 'That means the idea was wrong. Without air in the way, things fall equally fast, whatever their weight.'],
      ['학생', 'Is this the experiment where you dropped balls from the Leaning Tower of Pisa?'],
      ['해설', 'The Pisa story comes from a biography written later by his student. Whether it really happened is uncertain.'],
      ['해설', 'What Galileo carefully recorded was his ramp experiment. It slowed down falling so he could measure it.'],
      ['갈릴레오', 'I tilted a long wooden board with a smooth groove, and rolled a hard bronze ball down it.'],
      ['갈릴레오', 'I had no exact clock. So I weighed the water that flowed out while the ball rolled, to measure time.'],
      ['학생', 'So what did you find out?'],
      ['갈릴레오', 'The distance was proportional to the square of the time. Twice the time meant four times the distance.'],
      ['갈릴레오', 'This means the ball speeds up steadily. We call it uniformly accelerated motion.'],
      ['학생', 'But in real life, a feather falls much more slowly than a stone.'],
      ['갈릴레오', 'That is because the air holds the feather back. Without air resistance, it would fall with the stone.'],
      ['해설', 'This work was published in 1638 in Leiden, the Netherlands, as Two New Sciences. Publishing it in Italy was difficult.'],
      ['학생', 'If I drop a sheet of paper and a book apart, the book lands first. But paper on top of the book falls with it!'],
      ['갈릴레오', 'Excellent. Checking for yourself is how we read the book of nature.'],
      ['해설', 'When you try dropping things, use unbreakable objects from a low place, and make sure no one is below.'],
      ['해설', 'In 1971, Apollo 15’s David Scott dropped a hammer and a feather on the Moon. They hit the ground together.'],
    ],
  },

  'th2-newton-prism': {
    title: 'Newton’s Prism',
    names: { 해설: 'Narrator', 뉴턴: 'Isaac Newton', 학생: 'Student' },
    outro: [
      'Why did Newton think he needed two prisms, not just one, to reach a conclusion?',
      'White light is a mixture of many colors. How does this change the way we see a rainbow?',
      'Have you ever tested with an experiment an idea you had long taken for granted?',
    ],
    lines: [
      ['해설', 'Around 1666, while Cambridge University was closed because of the plague, young Isaac Newton studied light and color.'],
      ['해설', 'His results first appeared in a 1672 paper sent to the Royal Society. Later, he gathered them in a book, Opticks.'],
      ['학생', 'Sir, when sunlight shines through a prism, rainbow colors appear. Doesn’t the glass color the light?'],
      ['뉴턴', 'Many scholars thought so then. White light was pure, and colors appeared when glass changed it.'],
      ['뉴턴', 'Let’s test that idea with an experiment.'],
      ['해설', 'Newton darkened his room. A small hole in the window shutter let in a thin beam of sunlight.'],
      ['해설', 'The light passed through a prism and hit the far wall. Instead of a round spot, a long band of colors appeared.'],
      ['뉴턴', 'The hole was round, but the band was several times longer than it was wide. Each color bent by a different amount.'],
      ['학생', 'Each color bends differently?'],
      ['뉴턴', 'Violet bends more, and red bends less. So light that was mixed together spreads apart.'],
      ['학생', 'But maybe the glass still made the colors.'],
      ['뉴턴', 'A good objection. So I did a deciding experiment with two prisms.'],
      ['해설', 'In front of the color band, Newton set a board with a small hole. Only one color could pass.'],
      ['해설', 'Then he sent that light through a second prism.'],
      ['뉴턴', 'If glass made colors, the second prism should split or change the color again.'],
      ['학생', 'What happened?'],
      ['뉴턴', 'Red light stayed red, and it bent just as much as before. It did not split any further.'],
      ['뉴턴', 'My conclusion is this. White sunlight is a mixture of colored lights that bend by different amounts.'],
      ['학생', 'Then if you gather the colors back together, do they become white?'],
      ['뉴턴', 'Yes. Gather the band again with a lens or prism, and you get light close to white.'],
      ['해설', 'Newton divided the band into seven colors, red, orange, yellow, green, blue, indigo, and violet.'],
      ['뉴턴', 'In truth, the colors flow into each other without breaks. I chose seven to match the seven notes of a musical scale.'],
      ['학생', 'Does the rainbow in the sky work the same way?'],
      ['뉴턴', 'Yes. Each raindrop bends sunlight and reflects it inside, spreading out the colors.'],
      ['뉴턴', 'Lenses also focus each color at a different point, so images blur. So I built a telescope with a mirror instead.'],
      ['학생', 'A glass of water on a sunny windowsill makes a small rainbow on the floor. Same idea, right?'],
      ['뉴턴', 'A fine observation. Nature always keeps materials for experiments close to us.'],
      ['해설', 'If you try this experiment, never look straight at the Sun, even through a prism.'],
      ['해설', 'A lens can focus sunlight enough to burn paper, so always use lenses with an adult.'],
      ['해설', 'Newton’s Opticks was first published in 1704, in English rather than Latin.'],
    ],
  },

  'th2-beagle-1': {
    title: 'The Voyage of the Beagle, Part 1',
    names: { 해설: 'Narrator', 다윈: 'Charles Darwin', 학생: 'Student' },
    outro: [
      'Why did Darwin carefully write down even puzzles he could not answer yet?',
      'How did the rising land after the Chilean earthquake support Lyell’s ideas?',
      'Can you find a big change in your life or around you that built up little by little over a long time?',
    ],
    lines: [
      ['해설', 'In December 1831, the British navy survey ship Beagle left Plymouth. On board was Charles Darwin, age twenty-two.'],
      ['해설', 'This story imagines Darwin sharing memories of the voyage with a student.'],
      ['학생', 'Sir, did you board the ship as a biologist from the start?'],
      ['다윈', 'No. I gave up studying medicine, and at Cambridge I studied to become a clergyman.'],
      ['다윈', 'But I loved collecting beetles and studying rocks. Professor Henslow recommended me to Captain FitzRoy.'],
      ['해설', 'The Beagle’s main task was to survey the coasts of South America. The voyage lasted almost five years.'],
      ['학생', 'That long? Wasn’t life on the ship hard?'],
      ['다윈', 'I was terribly seasick. So while the ship surveyed the coast, I explored on land as long as I could.'],
      ['해설', 'In Brazil, Darwin entered a tropical rainforest for the first time and was deeply moved by its richness.'],
      ['다윈', 'I packed specimens in boxes and sent them to Professor Henslow in England. They made my name known first.'],
      ['다윈', 'On the ship I read Lyell’s Principles of Geology. It said small changes over long ages reshape the land.'],
      ['해설', 'From cliffs on the coast of Argentina, Darwin dug up fossil bones of huge mammals that no longer exist.'],
      ['다윈', 'Yet those lost animals looked somewhat like the armadillos and sloths living in the same land today.'],
      ['학생', 'Why does it matter that old and living animals of the same land look alike?'],
      ['다윈', 'At the time, I didn’t know either. But I wrote that puzzle carefully in my notebook.'],
      ['해설', 'In February 1835, a great earthquake struck Chile. Darwin saw the ruined city of Concepcion for himself.'],
      ['다윈', 'After the quake, the coast had risen. Beds of shellfish that had been underwater were now out of the water.'],
      ['다윈', 'With this in mind, I could guess why I found fossil shells high in the Andes mountains.'],
      ['학생', 'So rising like this, again and again over ages, turned the sea floor into mountains!'],
      ['다윈', 'Just as Lyell said. Even small changes, over a very long time, bring huge results.'],
      ['해설', 'This view of slow, steady change later gave Darwin a clue for thinking about how living things change.'],
      ['해설', 'When observing plants, animals, and rocks outdoors, go with an adult, and never touch or eat unknown living things.'],
      ['학생', 'Sir, where did you go after leaving South America?'],
      ['다윈', 'Out into the Pacific. Our next stop was a group of volcanic islands near the equator.'],
      ['해설', 'In September 1835, the Beagle reached the Galapagos Islands.'],
      ['다윈', 'What I saw on those islands later shook my thinking deeply. I’ll tell you about that next time.'],
      ['해설', 'Darwin’s account of the voyage was first published in 1839. Today it is widely known as The Voyage of the Beagle.'],
    ],
  },

  'th2-beagle-2': {
    title: 'The Voyage of the Beagle, Part 2',
    names: { 해설: 'Narrator', 다윈: 'Charles Darwin', 학생: 'Student' },
    outro: [
      'Why did Darwin wait almost twenty years after the Galapagos before announcing natural selection?',
      'How are the slightly different tortoises and birds of each island connected to natural selection?',
      'Has a small clue you once missed later become important? What did you learn then?',
    ],
    lines: [
      ['해설', 'In September 1835, the Beagle reached the Galapagos Islands in the Pacific, west of South America.'],
      ['해설', 'Darwin explored the islands for about five weeks.'],
      ['다윈', 'The ground was hardened black lava. And most living things there were ones I had never seen anywhere else.'],
      ['학생', 'Sir, what animals were there?'],
      ['다윈', 'Giant tortoises, big enough for a person to ride, moved slowly about.'],
      ['다윈', 'Marine iguanas crowded the rocks by the shore. They are lizards that swim into the sea to eat seaweed.'],
      ['해설', 'Lawson, who managed the islands, told Darwin he could tell which island a tortoise came from by its shell.'],
      ['학생', 'So the tortoises were a little different on each island?'],
      ['다윈', 'At the time, I didn’t think much of it. Only later did I see its importance, and I deeply regretted it.'],
      ['다윈', 'The mockingbirds were different. I noticed they varied by island, so I wrote down where I caught each one.'],
      ['다윈', 'I caught many small finches too, but I did not label them well by island.'],
      ['해설', 'In October 1836, after almost five years, the Beagle returned to England.'],
      ['해설', 'The next year, the bird expert John Gould examined Darwin’s birds.'],
      ['해설', 'He told Darwin the finches were many separate species with different beaks.'],
      ['다윈', 'I had thought some of them were completely different kinds of birds. But they were all close relatives, finches.'],
      ['학생', 'Why were their beaks different?'],
      ['다윈', 'Birds that cracked hard seeds had thick beaks, and birds that caught insects had thin ones. They seemed fitted to their food.'],
      ['다윈', 'I began to wonder. Perhaps ancestors from the mainland had slowly changed in each island’s different conditions.'],
      ['해설', 'From 1837, Darwin wrote in secret notebooks that species might change.'],
      ['해설', 'In 1838, while reading Malthus’ Essay on the Principle of Population, he found a key clue.'],
      ['다윈', 'Living things have far more young than can survive. So there is a struggle to stay alive.'],
      ['다윈', 'In that struggle, individuals with variations even slightly better suited to their surroundings tend to survive and leave young.'],
      ['다윈', 'Over many generations, this adds up, and living things change. I called this natural selection.'],
      ['학생', 'So did you announce it right away?'],
      ['다윈', 'No. I gathered evidence for almost twenty years. I bred pigeons and studied barnacles for years.'],
      ['해설', 'In 1858, Darwin received a paper from Alfred Russel Wallace, a naturalist in the Malay Archipelago with the same idea.'],
      ['해설', 'Their papers were presented together that year at the Linnean Society in London, and Darwin hurried to finish his book.'],
      ['학생', 'Those small island birds led to such a big idea.'],
      ['해설', 'Today the Galapagos is protected. Visitors must stay on marked paths and must not touch or feed the animals.'],
      ['해설', 'Darwin’s On the Origin of Species was published in London in November 1859.'],
    ],
  },

  'th2-mendel-pea': {
    title: 'Mendel’s Peas',
    names: { 해설: 'Narrator', 멘델: 'Gregor Mendel', 학생: 'Student' },
    outro: [
      'Why did Mendel’s work get almost no attention when it was first published?',
      'Can you explain the three to one ratio of round and wrinkled seeds using dominant, recessive, and segregation?',
      'How could a steady habit of counting and recording help my studies or daily life?',
    ],
    lines: [
      ['해설', 'In the mid-1800s, a monk grew peas in a monastery garden in Brno, now in the Czech Republic. He was Gregor Mendel.'],
      ['학생', 'Father, why do your experiments use peas?'],
      ['멘델', 'Peas are easy to grow, and you see results within a year. Above all, their traits are clearly different, like round or wrinkled seeds.'],
      ['멘델', 'Also, a pea flower usually pollinates itself. So it is easy to cross only the pairs I choose.'],
      ['학생', 'How do you cross only the pairs you choose?'],
      ['멘델', 'Before a flower opens, I remove its stamens. Then I brush on pollen from another plant.'],
      ['멘델', 'And I take care that no other pollen gets mixed in.'],
      ['해설', 'First, Mendel worked hard to make sure his peas were pure lines, showing the same trait generation after generation.'],
      ['해설', 'Then he chose seven clearly different traits to study, such as seed shape and seed color.'],
      ['멘델', 'I crossed a pure line with only round seeds and a pure line with only wrinkled seeds. What do you think happened?'],
      ['학생', 'They blended, so the seeds came out half wrinkled?'],
      ['멘델', 'Many people thought so then. But in the next generation, every seed was round.'],
      ['멘델', 'I called the trait that showed dominant, and the one that hid recessive.'],
      ['학생', 'So did the wrinkled trait disappear completely?'],
      ['멘델', 'I wondered too. So I let the plants from those round seeds pollinate themselves.'],
      ['해설', 'In the next generation, wrinkled seeds appeared again. Counting thousands, round to wrinkled was about three to one.'],
      ['멘델', 'Other traits also showed ratios close to three to one. That is hard to call chance.'],
      ['학생', 'But why three to one?'],
      ['멘델', 'It makes sense if each trait is set by a pair of factors. You get one from each parent.'],
      ['멘델', 'Plants from the first cross each have one round factor and one wrinkled factor. They are round because round is dominant.'],
      ['멘델', 'When pollen and egg cells form, the pair splits, and each gets only one. So two such plants make four combinations equally.'],
      ['학생', 'Round-round, round-wrinkled, wrinkled-round, wrinkled-wrinkled. Three are round. Only the wrinkled pair is wrinkled!'],
      ['멘델', 'Exactly. Today this splitting of paired factors is called the law of segregation.'],
      ['해설', 'Mendel presented his results to the Natural History Society of Brno in 1865. The next year, he published Experiments on Plant Hybrids.'],
      ['해설', 'His factors are what we now call genes, but the word gene came much later.'],
      ['학생', 'If I toss two coins many times and count heads-heads, heads-tails, tails-heads, and tails-tails, I’ll get similar ratios!'],
      ['멘델', 'Good idea. You will also see that the more you toss, the closer the ratio gets to what you expect.'],
      ['해설', 'When growing plants, handle scissors and tweezers carefully, and wash your hands after touching soil.'],
      ['해설', 'Mendel’s work became widely known around 1900, when de Vries, Correns, and Tschermak each rediscovered it.'],
    ],
  },

  'th2-curie-radium': {
    title: 'Marie Curie and Radium',
    names: { 해설: 'Narrator', 마리: 'Marie Curie', 피에르: 'Pierre Curie', 학생: 'Student' },
    outro: [
      'Why did Marie Curie have to spend years measuring the atomic weight of radium?',
      'The ore’s radioactivity could not be explained by uranium alone. How did this lead to new elements?',
      'What do you think about sharing scientific results with everyone instead of patenting them?',
    ],
    lines: [
      ['해설', 'In 1896, Henri Becquerel of France found that uranium compounds gave off rays that darkened photographic plates, even without light.'],
      ['해설', 'The next year, in Paris, the Polish-born Marie Curie was looking for a doctoral topic. She chose these invisible rays.'],
      ['학생', 'Madame Curie, how did you measure the rays? You can’t even see them.'],
      ['마리', 'The rays make the air around them carry electricity. So I measured very weak currents flowing through the air.'],
      ['마리', 'A precise measuring device made by my husband Pierre and his brother Jacques helped a lot.'],
      ['해설', 'Marie tested many substances one after another, and found that thorium gave off the same rays.'],
      ['마리', 'The strength of the rays depended on the amount of uranium. I thought it was a property of the atoms themselves.'],
      ['마리', 'So I proposed calling this property radioactivity.'],
      ['학생', 'But how did you find new elements?'],
      ['마리', 'A uranium ore called pitchblende was strange. Its rays were too strong to be explained by its uranium alone.'],
      ['마리', 'That meant an unknown element, much more active than uranium, was hiding in the ore.'],
      ['피에르', 'That idea pulled me in. I put aside my crystal research to work with Marie.'],
      ['해설', 'They separated the ore chemically, measured the radioactivity of each part, and followed the stronger part.'],
      ['해설', 'In July 1898, they announced a new element. They named it polonium, after Marie’s homeland, Poland.'],
      ['해설', 'That December they announced another, radium, from the Latin word for ray.'],
      ['학생', 'So did you have radium in your hands then?'],
      ['마리', 'No. We only knew a tiny amount was mixed in. Other scientists wanted to see it with their own eyes.'],
      ['해설', 'In a leaky old shed of a lab, the couple boiled, dissolved, and filtered tons of leftover ore.'],
      ['피에르', 'Marie stirred boiling pots all day with a heavy iron rod. It was truly hard work.'],
      ['해설', 'In 1902, Marie finally obtained a tiny amount of pure radium chloride. She measured radium’s atomic weight for the first time.'],
      ['마리', 'At night in the lab, radium compounds in glass bottles glowed faintly in the dark.'],
      ['학생', 'Beautiful, but wasn’t it dangerous?'],
      ['마리', 'Back then we did not know how harmful radiation was. Our hands were burned, and we were often sick.'],
      ['해설', 'Today, only licensed experts handle radioactive materials, in places with proper shielding. Never try to copy this.'],
      ['해설', 'In 1903, the Curies shared the Nobel Prize in Physics with Becquerel. In 1911, Marie won the Nobel Prize in Chemistry.'],
      ['학생', 'I heard you didn’t patent your method of getting radium.'],
      ['마리', 'Radium belongs to science, so I thought everyone should be able to use it.'],
      ['해설', 'Marie Curie was the first person to win Nobel Prizes in two different sciences.'],
    ],
  },

  'th2-pasteur-flask': {
    title: 'Pasteur’s Swan-Neck Flask',
    names: { 해설: 'Narrator', 파스퇴르: 'Louis Pasteur', 학생: 'Student' },
    outro: [
      'Why did Pasteur leave the flask open instead of sealing it?',
      'What role did the broken-necked or tilted flasks play as controls in the experiment?',
      'How has understanding invisible microbes changed our hygiene habits today?',
    ],
    lines: [
      ['해설', 'Until the mid-1800s, many people believed tiny living things in spoiled broth appeared on their own. This was called spontaneous generation.'],
      ['해설', 'Around 1860, the French chemist Louis Pasteur decided to answer this old debate with experiments.'],
      ['학생', 'Sir, if you leave meat broth out for days, it turns cloudy. Didn’t the microbes appear by themselves?'],
      ['파스퇴르', 'It looks that way. But I thought the microbes came in on dust in the air.'],
      ['해설', 'Back in the 1600s, the Italian Redi showed that meat covered with cloth did not get maggots.'],
      ['해설', 'But many still argued that invisible microbes, at least, could appear on their own.'],
      ['학생', 'Then why not seal the flask tight and boil it?'],
      ['파스퇴르', 'The other side said life needs fresh air. If you seal the flask, of course nothing grows.'],
      ['파스퇴르', 'So I needed a flask that let air in freely but kept dust out.'],
      ['해설', 'Pasteur poured broth into a flask. He heated its glass neck and bent it into a long curve, like a swan’s neck.'],
      ['해설', 'Then he boiled the broth well to kill the microbes in it. The end of the curved neck was left open.'],
      ['학생', 'But it’s open, so air gets in.'],
      ['파스퇴르', 'Yes, air gets in. But dust and microbes get caught in the bend of the neck and never reach the broth.'],
      ['해설', 'Days and even weeks passed, and the broth stayed clear.'],
      ['학생', 'So air alone does not make microbes appear!'],
      ['파스퇴르', 'We are not done yet. Now let’s tilt the flask so the broth flows into the bend of the neck.'],
      ['해설', 'When broth that had touched the dusty bend flowed back in, it soon turned cloudy.'],
      ['파스퇴르', 'Breaking the neck short does the same. Dust falls straight in, and the broth spoils quickly.'],
      ['학생', 'Same broth, same air. The only difference is whether dust reached it.'],
      ['파스퇴르', 'That is the power of a controlled experiment. Change only one thing, keep the rest the same, and you can find the cause.'],
      ['해설', 'He also opened flasks near a glacier in the Alps. He showed that the amount of microbes in the air differs by place.'],
      ['해설', 'For this work, Pasteur won a prize from the French Academy of Sciences in 1862.'],
      ['해설', 'In 1864, he shared his results widely in a lecture at the Sorbonne.'],
      ['학생', 'How was this discovery used in daily life?'],
      ['파스퇴르', 'If microbes come in from outside and spoil food, we can find ways to block and kill them.'],
      ['해설', 'This idea also influenced the British surgeon Lister as he worked on ways to disinfect surgical wounds.'],
      ['해설', 'If you try this at school, always do it with a teacher. Boiling liquid and flames can burn you.'],
      ['해설', 'Cloudy broth is full of microbes. Do not smell or taste it, and dispose of it safely afterward.'],
      ['학생', 'Covering food with a lid after boiling it works the same way, right?'],
      ['파스퇴르', 'Yes. Making the invisible visible, that is what a well-designed experiment does.'],
      ['해설', 'Pasteurization, a way of heating food just enough to reduce microbes, is named after Pasteur.'],
    ],
  },

  'th2-jenner-vaccine': {
    title: 'Jenner and the Smallpox Vaccine',
    names: { 해설: 'Narrator', 제너: 'Edward Jenner', 학생: 'Student' },
    outro: [
      'Why did Jenner collect cases instead of ignoring a story told in the countryside?',
      'By today’s research ethics, what problems does the experiment on James Phipps have?',
      'Why does vaccination protect not just me, but the whole community?',
    ],
    lines: [
      ['해설', 'In eighteenth-century Europe, smallpox was one of the most feared diseases. Survivors were often left with deep scars.'],
      ['해설', 'Edward Jenner, a doctor in the village of Berkeley in Gloucestershire, England, searched for a way to stop it.'],
      ['학생', 'Sir, was there no way at all to prevent smallpox then?'],
      ['제너', 'There was inoculation. Pus from a smallpox patient was put into a healthy person, to cause a mild case.'],
      ['제너', 'But some people became very sick, and the inoculated person could spread smallpox to others.'],
      ['해설', 'In the countryside, people said that milkmaids who had caught cowpox rarely got smallpox.'],
      ['학생', 'What is cowpox?'],
      ['제너', 'A disease of cows. Milkers get blisters on their hands too, but in people it is usually mild.'],
      ['제너', 'I did not ignore that story. For years, I collected cases of people who had had cowpox.'],
      ['해설', 'In May 1796, Jenner took a little fluid from a cowpox blister on the hand of a milkmaid, Sarah Nelmes.'],
      ['해설', 'He made small cuts on the arm of James Phipps, his gardener’s eight-year-old son, and put the fluid in.'],
      ['학생', 'On a child? Was he all right?'],
      ['제너', 'He had a slight fever and felt unwell for a few days, but he soon recovered.'],
      ['해설', 'A few weeks later, in July, Jenner exposed the boy to smallpox matter. The boy did not get smallpox.'],
      ['학생', 'Having cowpox gave him the power to beat smallpox!'],
      ['제너', 'That is what I thought. But one child’s result was not enough. I had to gather more cases.'],
      ['해설', 'In 1798, Jenner collected many cases and published his study on cowpox vaccination at his own expense.'],
      ['해설', 'The Latin word for cow is vacca, and this is where the word vaccine comes from.'],
      ['해설', 'Later, Pasteur honored Jenner by using the word for all kinds of vaccination.'],
      ['제너', 'At first, many people laughed at putting a cow’s disease into people. There was even a cartoon of people turning into cows.'],
      ['해설', 'But vaccination was much safer than inoculation, so it spread quickly through Europe and around the world.'],
      ['해설', 'In Joseon, Ji Seok-yeong learned vaccination around 1879 and worked hard to spread it.'],
      ['학생', 'But now it seems dangerous to do such an experiment on a child.'],
      ['해설', 'That is right. Today, research on people requires full explanation, consent, and an ethics review.'],
      ['해설', 'Jenner did not know what happened inside the body. Today we know vaccines teach the immune system to remember germs.'],
      ['해설', 'Vaccines must always be given by medical workers such as doctors and nurses. Never try to copy this.'],
      ['학생', 'So all the shots I’ve had started from this idea.'],
      ['해설', 'In 1980, the World Health Organization officially declared smallpox wiped out from the Earth.'],
    ],
  },

  'th2-harvey-blood': {
    title: 'Harvey and the Circulation of Blood',
    names: { 해설: 'Narrator', 하비: 'William Harvey', 학생: 'Student' },
    outro: [
      'Why did Harvey begin to doubt Galen’s teaching, which had lasted for over a thousand years?',
      'How did his estimate of blood volume and the arm-binding experiment each support circulation?',
      'When should we test even an idea that many people believe, using evidence?',
    ],
    lines: [
      ['해설', 'In 1628, William Harvey, a doctor to the English king, published a thin book in Latin. It was On the Motion of the Heart and Blood.'],
      ['학생', 'Sir, before that, how did people think blood moved?'],
      ['하비', 'For over a thousand years, doctors followed Galen, a physician of ancient Roman times.'],
      ['하비', 'He taught that the liver kept making new blood from food. The blood flowed out and was used up.'],
      ['하비', 'People also believed some blood seeped from the right side of the heart to the left through invisible holes.'],
      ['학생', 'What seemed strange about that?'],
      ['하비', 'I estimated how much blood the heart pushes out with each beat. I purposely kept the number very small.'],
      ['하비', 'Even so, multiplied by the beats in one hour, it came to far more blood than a person’s weight.'],
      ['학생', 'Nobody could make that much new blood from food in one hour.'],
      ['하비', 'Exactly. So the same blood must travel around the body and come back to the heart.'],
      ['해설', 'Harvey reached his conclusion by calculation, then confirmed it by observing and experimenting on many animals.'],
      ['해설', 'He closely watched the heart moving in animals with slow heartbeats, such as snakes and fish.'],
      ['하비', 'When the heart squeezes, it pushes the blood out with force. It is a pump made of muscle.'],
      ['학생', 'Can we check it in the human body too?'],
      ['하비', 'There is an arm-binding experiment. Tie the upper arm very tightly, and even the arteries close. The hand turns cold and pale.'],
      ['하비', 'Tie it a little looser. Blood enters through the deep arteries, but cannot return through the veins near the skin.'],
      ['하비', 'So the veins below the band swell up.'],
      ['학생', 'That proves blood goes in through arteries and comes out through veins!'],
      ['하비', 'Veins have valves inside. My teacher Fabricius found them, but he did not understand their purpose.'],
      ['하비', 'Try pushing blood in a swollen vein away from the heart, and the valves stop it. Blood flows only toward the heart.'],
      ['해설', 'So Harvey showed that blood leaves the heart through arteries, travels the body, and returns through veins. This is circulation.'],
      ['학생', 'But where do arteries and veins connect?'],
      ['하비', 'I could not see that with my own eyes. I could only guess they were joined by very tiny passages.'],
      ['해설', 'At first, many doctors opposed Harvey’s idea, but over time it was gradually accepted.'],
      ['해설', 'Tying your arm tightly with a cord can harm nerves and blood vessels, so never try it.'],
      ['해설', 'Instead, feel the pulse inside your wrist. Or quietly look at the blue veins on the back of your hand.'],
      ['학생', 'After running, my pulse gets faster. That’s to move blood around faster, right?'],
      ['하비', 'Yes. When the body needs more, the heart beats faster and harder.'],
      ['해설', 'In 1661, the Italian Malpighi first saw the capillaries Harvey had missed, in a frog’s lung under a microscope.'],
    ],
  },
};
