// 청소년 영어 원고: 세계 단편 미국 (stories/teen-ws4.js). 문장은 자체 각색.
// lines 의 첫 칸은 한국어 이야기 cast 의 이름 그대로.
export default {
  'wsa-stone-face': {
    title: 'The Great Stone Face',
    names: { 해설: 'Narrator', 어니스트: 'Ernest', 어머니: 'Mother', 개더골드: 'Mr. Gathergold', 장군: 'The General', 정치가: 'The Statesman', 시인: 'The Poet' },
    outro: [
      'What did Hawthorne mean by making Ernest, not a rich man, a general or a statesman, the man of the prophecy?',
      'Ernest never thought he was the one. What does this show about his character?',
      'Who do people look up to today, and how is that different from the life Ernest lived?',
    ],
    lines: [
      ['해설', 'Thousands of people lived in a wide valley surrounded by mountains. High on a mountainside, rocks formed a huge face.'],
      ['해설', 'From far away, the forehead, nose and lips were clear. People called it the Great Stone Face. It looked kind and noble.'],
      ['해설', 'One evening, young Ernest sat at the cottage door with his mother, looking at the face.'],
      ['어니스트', 'Mother, I wish that face could speak. Its voice would surely be kind.'],
      ['어머니', 'There is an old prophecy. Someday a child born in this valley will look just like that face. He will be the greatest man of his time.'],
      ['해설', 'The prophecy was said to come from the Native people who lived here first. Picturing them only as legend was the settlers’ view.'],
      ['어니스트', 'I hope I can meet him while I am alive.'],
      ['해설', 'Ernest never forgot those words. Helping his mother and working in the fields, he looked at the face every day.'],
      ['해설', 'One year, word spread that Mr. Gathergold, a son of the valley who had become very rich, was coming home. People said he was the one.'],
      ['해설', 'But the face at the carriage window was dry and wrinkled, with thin lips pressed tightly together.'],
      ['개더골드', 'Out of the way, all of you. Throw them a few coins and let us go.'],
      ['해설', 'People still cried that he looked just like the Stone Face. Ernest turned and looked up at the mountain.'],
      ['어니스트', 'That face is still waiting. He will come. I know he will.'],
      ['해설', 'As a young man, Ernest often sat alone after work, gazing at the face. It seemed to encourage him.'],
      ['해설', 'Next, an old general, a war hero, came home. At the feast, people compared his face with the Stone Face.'],
      ['장군', 'Thank you for your welcome. I am a man who has spent his whole life on the battlefield.'],
      ['해설', 'The general’s face showed a strong will. But Ernest could not find the wisdom and kindness of the Stone Face in it.'],
      ['해설', 'In middle age, Ernest was still a simple farmer. But his words were so wise that people began to visit him.'],
      ['해설', 'Then a statesman with a gift for speeches appeared. When people talked of him for President, they called him the Stone Face.'],
      ['정치가', 'My dear friends of the valley, I will always stand on your side!'],
      ['해설', 'His voice was grand, but Ernest saw something empty in his face. It had dignity, but no heart to fill it.'],
      ['해설', 'When Ernest’s hair had turned white, a poet’s book moved him deeply. Then that very poet came to the valley.'],
      ['시인', 'I have come to hear you speak. Your words are deeper than my poems.'],
      ['어니스트', 'Reading your poems, I hoped you might be the man of the prophecy.'],
      ['시인', 'I am not worthy. My poems are beautiful, but I have not lived up to them.'],
      ['해설', 'At sunset, Ernest spoke to the villagers as usual. His words were exactly like the life he had lived.'],
      ['해설', 'The evening light shone on his white hair. At that moment, the poet threw up his arms and cried out.'],
      ['시인', 'Look! Ernest himself is the likeness of the Great Stone Face!'],
      ['해설', 'The people nodded. But as Ernest walked home, he still hoped that a wiser and better man would soon come.'],
      ['해설', 'The Great Stone Face is a short story Nathaniel Hawthorne published in 1850.'],
    ],
  },

  'wsa-rip-van-winkle': {
    title: 'Rip Van Winkle',
    names: { 해설: 'Narrator', 립: 'Rip Van Winkle', 아내: 'Dame Van Winkle', 낯선이: 'Stranger', 연설꾼: 'Speaker', 마을노인: 'Old Villager', 딸: 'Judith' },
    outro: [
      'What did the changed world mean to Rip, who came down after sleeping twenty years on the mountain?',
      'How does King George turning into General Washington on the inn sign cleverly show a great change?',
      'If you woke up twenty years from now, what do you think would be most different in our society?',
    ],
    lines: [
      ['해설', 'At the foot of the Catskill Mountains, west of the Hudson River, there was a small Dutch village. There lived Rip Van Winkle.'],
      ['해설', 'Rip was good-natured and always helped his neighbors. But he would never do the work on his own farm or house.'],
      ['아내', 'The fence is falling down and the field is full of weeds! The children are in rags, and you are going out again?'],
      ['립', 'Now, now, dear. I am just going up the mountain with Wolf to hunt squirrels.'],
      ['해설', 'Rip took his gun and his dog Wolf up the mountain. As the sun went down, someone called him from the valley below.'],
      ['낯선이', 'Rip Van Winkle! Rip Van Winkle!'],
      ['해설', 'A short old man in old Dutch clothes was carrying a big keg. Rip thought it strange, but helped him carry it.'],
      ['해설', 'In an open space among the rocks, men in the same clothes were playing ninepins. The rolling balls sounded like thunder.'],
      ['해설', 'They did not laugh or speak. Rip secretly took a sip of their drink, then another, and fell into a deep sleep.'],
      ['해설', 'When he woke, it was a bright morning. His gun was rusty and its wooden stock had rotted. Wolf did not come when he called.'],
      ['립', 'Oh dear, I slept all night on the mountain. What will I tell my wife?'],
      ['해설', 'In the village, every face was new. People stared at his chin, so he touched it. His beard was a foot long.'],
      ['해설', 'Where his old inn had been stood a strange hotel. On the sign, King George had become General Washington.'],
      ['연설꾼', 'You there! Which way will you vote? Federal or Democrat?'],
      ['립', 'Vote? I am a man of this place, and a loyal subject of King George!'],
      ['연설꾼', 'What? A Tory! A spy! Throw him out!'],
      ['해설', 'After the uproar, Rip asked about his old friends. Some had died, and some had gone to war and never returned.'],
      ['립', 'Then does anyone know Rip Van Winkle?'],
      ['마을노인', 'Of course. That is Rip Van Winkle over there, leaning against the tree.'],
      ['해설', 'There stood a lazy young man who looked just like Rip on the day he climbed the mountain. Rip no longer knew who he was.'],
      ['해설', 'Then a young woman with a baby came up. In a shaking voice, Rip asked her name and her father’s name.'],
      ['딸', 'I am Judith Gardenier. My father was Rip Van Winkle. Twenty years ago he went to the mountain with his gun and never came back.'],
      ['립', 'And what happened to your mother?'],
      ['딸', 'She died not long ago. She got so angry while arguing with a peddler.'],
      ['립', 'I am your father! Young Rip Van Winkle is now old Rip Van Winkle!'],
      ['마을노인', 'My father told me that Hudson’s crew play ninepins on that mountain every twenty years. That is the thunder.'],
      ['해설', 'Rip went to live with his daughter. He was now old enough to be idle without shame, so he sat on a bench by the inn.'],
      ['해설', 'He told every visitor about his sleep on the mountain. While he slept, the colonies had become a free country.'],
      ['해설', 'Rip Van Winkle first appeared in Washington Irving’s The Sketch Book in 1819.'],
    ],
  },

  'wsa-sleepy-hollow': {
    title: 'The Legend of Sleepy Hollow',
    names: { 해설: 'Narrator', 이카보드: 'Ichabod Crane', 브롬: 'Brom Bones', 반타셀: 'Baltus Van Tassel' },
    outro: [
      'Who do you think the Headless Horseman really was? What clues does the story give?',
      'In what tone and from what view does the writer show timid, greedy Ichabod?',
      'Rumors and legends made a man disappear from the village. How is that like rumors today?',
    ],
    lines: [
      ['해설', 'Near Tarry Town on the Hudson River lay a quiet valley called Sleepy Hollow. A dreamy feeling always hung over it.'],
      ['해설', 'In the Revolutionary War, a Hessian soldier lost his head to a cannonball. People believed he rode every night looking for it.'],
      ['해설', 'To this valley came Ichabod Crane, a schoolteacher from Connecticut. He was tall and lanky, with long limbs and big ears.'],
      ['해설', 'He had a huge appetite and loved ghost stories. On dark roads, he sang hymns loudly to chase away his fear.'],
      ['해설', 'Ichabod fell for Katrina, the only daughter of a rich farmer named Van Tassel. He also had his eye on the farm.'],
      ['이카보드', 'Those fat pigs and geese, those endless fields of wheat! If I marry Katrina, all this will be mine.'],
      ['해설', 'But Katrina already had a suitor, Brom Bones. He was strong, loved pranks and was a fine horseman.'],
      ['브롬', 'That beanpole teacher is after Katrina? I will teach him a lesson.'],
      ['해설', 'Brom and his friends blocked the school chimney and turned the classroom upside down. Still, Ichabod did not give up.'],
      ['해설', 'One autumn day, a Black servant of the Van Tassels rode up with an invitation to a party that night.'],
      ['해설', 'The original makes fun of this servant and the Black workers at the party. It shows the prejudice of white writers then.'],
      ['해설', 'Ichabod brushed his only old suit and rode to the party on Gunpowder, an old borrowed horse.'],
      ['반타셀', 'Welcome, teacher! Eat, drink and dance as much as you like!'],
      ['해설', 'The tables were full of doughnuts, pies, roast chicken and ham. Ichabod ate his fill and danced happily with Katrina.'],
      ['해설', 'Late at night, people sat around telling ghost stories. Soon they came to the Headless Horseman.'],
      ['브롬', 'I met the horseman myself. We raced, and at the church bridge he vanished in a flash of fire.'],
      ['해설', 'After the guests left, Ichabod talked with Katrina alone. Whatever happened, he came out looking crushed.'],
      ['해설', 'Around midnight, he rode Gunpowder home alone along the dark road. Every ghost story came back to him.'],
      ['이카보드', 'Wh-who are you? Answer me!'],
      ['해설', 'Out of the dark, a huge rider silently appeared and rode beside him. In the moonlight, Ichabod saw he had no head.'],
      ['해설', 'The head was resting on the front of his saddle! Ichabod kicked his horse and fled, but the rider stayed close behind.'],
      ['이카보드', 'I just have to cross the bridge! They say a ghost cannot follow past the church bridge!'],
      ['해설', 'As Ichabod crossed and looked back, the rider threw his head at him. It hit Ichabod, and he tumbled from his horse.'],
      ['해설', 'Next morning, Gunpowder came home without a saddle. Ichabod did not show up at school.'],
      ['해설', 'By the stream, people found his hat. Next to it lay a smashed pumpkin.'],
      ['해설', 'The old women of the village whispered that the ghost had carried him off. Soon after, Brom married Katrina.'],
      ['해설', 'Years later, word came that Ichabod had become a judge far away. Whenever the pumpkin was mentioned, Brom laughed out loud.'],
      ['브롬', 'That teacher? I could say a lot about that night, but, ha ha, let us leave it there.'],
      ['해설', 'The Legend of Sleepy Hollow appeared in Washington Irving’s The Sketch Book in 1820.'],
    ],
  },

  'wsa-banknote': {
    title: 'The Million Pound Bank Note',
    names: { 해설: 'Narrator', 헨리: 'Henry Adams', 형: 'Older Brother', 동생: 'Younger Brother', 토드: 'Tod', 포샤: 'Portia Langham' },
    outro: [
      'Why do you think a bank note that could not even be spent changed Henry’s life?',
      'What role does Tod, the tailor’s clerk who changed his attitude the moment he saw the note, play as satire?',
      'How does treating people by their money or appearance show up today?',
    ],
    lines: [
      ['해설', 'Henry Adams was a clerk for a mining broker in San Francisco. One day he went out in a small boat and drifted out to sea.'],
      ['해설', 'A ship bound for London picked him up. He worked for his passage and landed in London with just one dollar.'],
      ['해설', 'Starving, he was about to pick up a pear in the street. Two old gentlemen were watching him from a window.'],
      ['해설', 'The brothers had just made a bet. Could a man with only a million-pound note survive for a month?'],
      ['형', 'No one can change such a note, so he cannot spend it. He will starve or end up in jail.'],
      ['동생', 'Not at all. An honest, clever man could easily last a month.'],
      ['해설', 'The brothers called Henry in and handed him an envelope. They only told him to open it outside.'],
      ['해설', 'Henry ate his fill at a cheap eating house, then opened the envelope. It was a million-pound note. He froze.'],
      ['해설', 'The owner saw the note and bowed low. He could not change it, so Henry could pay whenever he liked.'],
      ['해설', 'Henry rushed back to the house, but the brothers had already left on a trip. A letter in the envelope said this.'],
      ['해설', 'This money is lent to you for thirty days. Then come back. If you do well, I will give you a position.'],
      ['해설', 'Henry went to a tailor’s shop for clothes. The clerk, Tod, looked at his worn clothes and gave him a leftover suit.'],
      ['토드', 'I suppose you have change? A gentleman like you would not carry large bills.'],
      ['해설', 'When Henry handed over the note, Tod turned pale. Even the owner ran out and bowed again and again.'],
      ['토드', 'Oh, forgive me, sir! We will make you a custom suit. Please pay whenever you like.'],
      ['해설', 'The story quickly spread across London. Every paper talked about the strange American with the million-pound note.'],
      ['해설', 'Without a penny, Henry lived in a fine house and wore fine clothes. Everyone gladly gave him credit.'],
      ['헨리', 'I will write down every debt. When the brothers return, I will get a job and pay it all back from my salary.'],
      ['해설', 'At the American Minister’s dinner, Henry met an English girl, Portia Langham. He fell in love at first sight.'],
      ['해설', 'He told Portia everything. She laughed until she cried, and Henry found even her laugh lovely.'],
      ['포샤', 'So even the clothes you are wearing are on credit? And a man like that wants to marry me?'],
      ['해설', 'Around then, his old friend Hastings was struggling to sell shares in a mine. Henry agreed to lend him his name.'],
      ['헨리', 'Just tell people that I stand behind the mine. If there is a profit, we will split it.'],
      ['해설', 'Once people heard the million-pound man was behind it, the shares sold fast. Henry made a fortune at once.'],
      ['해설', 'On the promised day, Henry and Portia visited the brothers. He returned the note and showed his bank deposit.'],
      ['동생', 'I win, brother! This young man neither starved nor went to jail.'],
      ['헨리', 'If you will give me the position you promised, I would like to be this young lady’s husband.'],
      ['해설', 'It turned out that Portia was the stepdaughter of one of the gentlemen. He laughed and blessed them both.'],
      ['해설', 'The Million Pound Bank Note is a short story Mark Twain published in 1893.'],
    ],
  },

  'wsa-jumping-frog': {
    title: 'The Celebrated Jumping Frog',
    names: { 해설: 'Narrator', 나: 'Visitor', 휠러: 'Simon Wheeler', 스마일리: 'Jim Smiley', 낯선이: 'Stranger' },
    outro: [
      'Jim Smiley would bet on anything, yet he was finally tricked. What is the story poking fun at?',
      'How does Wheeler’s endless, serious way of talking make the story funnier?',
      'Have you ever been so focused on winning that you missed something important? How do you see it now?',
    ],
    lines: [
      ['해설', 'A friend in the East asked me a favor. So I visited an old tavern in Angel’s Camp, a California mining camp.'],
      ['해설', 'Dozing by the stove was Simon Wheeler, a fat, bald old man. His face looked gentle and easygoing.'],
      ['나', 'Do you know the Reverend Leonidas W. Smiley? My friend asked me to find out about him.'],
      ['해설', 'Wheeler backed me into a corner. Then, without a trace of a smile, he began an endless story.'],
      ['휠러', 'I don’t know any reverend. But there was a fellow named Jim Smiley. He would bet on anything.'],
      ['휠러', 'Horse races, dog fights, which of two birds would fly off first. It made no difference to him.'],
      ['휠러', 'He had an old mare that always wheezed. But at the end of a race she ran hard and won by a nose.'],
      ['휠러', 'And that frog! Jim spent three months teaching a frog to jump. Its name was Dan’l Webster.'],
      ['스마일리', 'Flies, Dan’l, flies! Jump!'],
      ['휠러', 'And he would shoot up like lightning, snap a fly, then sit down and scratch his head like nothing happened.'],
      ['해설', 'Jim carried the frog in a little box and made bets. One day a stranger looked into the box.'],
      ['낯선이', 'What might that be in the box? A canary?'],
      ['스마일리', 'It’s a frog. He can out-jump any frog in Calaveras County.'],
      ['낯선이', 'Well, I don’t see any points about that frog that’s better than any other frog.'],
      ['스마일리', 'Then I will bet forty dollars he can out-jump any frog in Calaveras County.'],
      ['낯선이', 'I’m a stranger here, and I have no frog. If I had a frog, I would bet you.'],
      ['스마일리', 'That’s easy. Hold my box a minute. I’ll go to the swamp and catch you one.'],
      ['해설', 'While Jim searched the swamp, the stranger opened Dan’l’s mouth and filled him with quail shot.'],
      ['해설', 'Covered in mud, Jim came back with a frog. They set the two frogs side by side.'],
      ['스마일리', 'One, two, three, jump!'],
      ['휠러', 'The new frog hopped off. But Dan’l just lifted his shoulders and could not budge, as if he was nailed down.'],
      ['해설', 'The stranger took the money and went out the door, saying one thing over his shoulder.'],
      ['낯선이', 'Well, I don’t see any points about that frog that’s better than any other frog.'],
      ['스마일리', 'What is wrong with Dan’l? Is he sick? He feels so heavy.'],
      ['휠러', 'Jim turned him upside down, and he spit out a double handful of shot. Jim chased the man but never caught him.'],
      ['해설', 'Then someone called Wheeler. He told me to stay put and left. I could not see what this had to do with the reverend.'],
      ['해설', 'Wheeler came back and began a story about a yellow, one-eyed cow with no tail. I quickly said goodbye and left.'],
      ['해설', 'Only then did I guess. There had never been any Reverend Smiley. My friend had played a trick on me.'],
      ['해설', 'This story appeared in a New York magazine in 1865 and made Mark Twain’s name widely known.'],
    ],
  },

  'wsa-build-fire': {
    title: 'To Build a Fire',
    names: { 해설: 'Narrator', 사내: 'The Man', 노인: 'Old-timer' },
    outro: [
      'Through a man’s confidence breaking down before vast nature, what did Jack London want to show?',
      'What effect comes from placing a nameless man next to a dog that follows its instincts?',
      'Have you ever ignored advice from someone with experience and regretted it? What did you learn?',
    ],
    lines: [
      ['해설', 'On a cold, gray morning, a man turned off the main Yukon trail. He took a narrow path through the spruce forest.'],
      ['해설', 'It was nine in the morning, but the sun had not risen. There was only snow and ice, and it was far below minus fifty degrees Celsius.'],
      ['해설', 'The man was a newcomer to this land. He knew the cold only as a number and never thought about what it meant.'],
      ['해설', 'He planned to eat lunch at the forks of the creek at half past twelve. He would reach his friends’ camp by six.'],
      ['해설', 'A big wolf dog followed him. By instinct, the dog knew no one should travel on a day like this.'],
      ['해설', 'When the man spat, the spit cracked and froze in the air. That meant it was colder than he had thought.'],
      ['사내', 'It is cold, all right. Still, I will have lunch at the forks by half past twelve.'],
      ['해설', 'Under the snow on the creek, there were hidden springs that never froze. A wet foot would freeze quickly.'],
      ['해설', 'At a doubtful spot, the man made the dog go first. The dog’s feet got wet, and it bit off the ice with its teeth.'],
      ['해설', 'At lunch, as soon as he took off his mittens, he felt his fingers go numb. He made a small fire, warmed himself and ate biscuits.'],
      ['해설', 'Suddenly he remembered what the old-timer at Sulphur Creek had told him.'],
      ['노인', 'When it is this cold, no one should travel alone in this land. You must always have a partner.'],
      ['사내', 'Old-timers are scared of everything. A real man can travel alone.'],
      ['해설', 'Soon after he set out again, the firm-looking snow gave way. He fell into water up to his knees.'],
      ['사내', 'Blast, I am wet. I must build a fire and dry my feet. It will cost me an hour.'],
      ['해설', 'Under a spruce tree, he gathered dry twigs and calmly lit a fire. When the flames grew, he felt relieved.'],
      ['사내', 'See, I did it alone. That old man was exaggerating.'],
      ['해설', 'But he had made a mistake. He had built the fire under a tree heavy with snow. The heat made the branches shake.'],
      ['해설', 'Snow slid from branch to branch and poured onto the fire. In an instant, the fire was out.'],
      ['해설', 'The man felt as if he had heard his own death sentence. With a partner, the partner could have built the fire.'],
      ['해설', 'He tried to build another fire, but his fingers had no feeling. He could not even pick up a single match.'],
      ['해설', 'He held the whole bunch of matches between his palms and struck them all. His hands burned, but he felt no pain.'],
      ['해설', 'The weak flame scattered from his clumsy hands and died. He tried to warm his hands on the dog, but could not hold it.'],
      ['해설', 'Filled with panic, he ran toward the camp. He hoped running would warm his blood, but he fell in the snow again and again.'],
      ['사내', 'Stop panicking. I should meet death with dignity.'],
      ['사내', 'You were right, old man. You were right.'],
      ['해설', 'He sat in the snow and gave in to sleep. It felt comfortable. The dog sat waiting beside him and whined as night fell.'],
      ['해설', 'Smelling death on the man, the dog turned away. It trotted toward the camp, where people had fire and food.'],
      ['해설', 'Jack London went to the Klondike in the 1897 gold rush. To Build a Fire was published in 1908.'],
    ],
  },

  'wsa-lady-tiger': {
    title: 'The Lady, or the Tiger?',
    names: { 해설: 'Narrator', 왕: 'The King', 공주: 'The Princess', 청년: 'The Young Man' },
    outro: [
      'Behind the door the princess pointed to, was it the lady or the tiger? Why do you think so?',
      'The writer never reveals the answer. What role does this open ending give the reader?',
      'Compare the king’s trials of pure luck with fair trials today. What is different?',
    ],
    lines: [
      ['해설', 'Long, long ago there lived a semi-barbaric king. He took in ideas from his neighbors, but his own thinking stayed wild and willful.'],
      ['해설', 'The original calls this land semi-barbaric. The phrase shows how Westerners of that time looked down on other cultures.'],
      ['해설', 'The king thought of a strange way to judge crimes. He held trials of chance in a huge arena.'],
      ['해설', 'Before the accused were two doors that looked the same. Behind one was a hungry tiger, behind the other a beautiful lady.'],
      ['왕', 'If the tiger comes out, he is guilty and is punished on the spot. If the lady comes out, he is innocent and must marry her at once.'],
      ['해설', 'It did not matter if the man already had a wife or a sweetheart. The people thought it fair, since everything was left to chance.'],
      ['해설', 'The king had a daughter as fiery and stubborn as he was. She secretly loved a handsome young man of low rank.'],
      ['해설', 'Their love lasted for months, but in the end the king found out. The young man was thrown into prison at once.'],
      ['왕', 'How dare he look at the king’s daughter! Put him in the arena. Choose the fiercest tiger and the loveliest maiden.'],
      ['해설', 'On the day of the trial, the arena was packed. When the young man entered, people sighed at his youth and good looks.'],
      ['왕', 'Bring the accused forward. Let today’s trial begin!'],
      ['해설', 'The young man bowed to the king. Then at once he looked at the princess, seated beside her father.'],
      ['해설', 'The princess had already learned the secret of the doors. With power and gold, she found out what was behind each one.'],
      ['해설', 'She knew who the lady was, too. It was a maiden of the court she hated, suspecting her of eyeing the young man.'],
      ['해설', 'The young man knew the princess well. He knew she could not rest until she learned the secret.'],
      ['청년', 'She must know. Which door is it? Tell me, please.'],
      ['해설', 'Unseen by anyone, the princess raised her right hand slightly and pointed to the right. Only the young man saw it.'],
      ['해설', 'Without a moment’s doubt, he turned and walked across the arena. Then he opened the door on the right.'],
      ['해설', 'Here is the point of the story. Did the tiger come out of that door, or the lady?'],
      ['해설', 'To find the answer, we must understand the hot, fierce heart of the princess. For days and nights, this question had tormented her.'],
      ['공주', 'Give him to the tiger? If I picture him falling, I will cover my face and scream.'],
      ['공주', 'But give him to that woman? Then I must watch him marry her with joy on his face.'],
      ['공주', 'Ringing bells, falling petals, cheering crowds. Rather than see them smiling together, I would...'],
      ['공주', 'No, I cannot let him die. But I cannot send him to that woman either.'],
      ['해설', 'She knew he would ask, so she had decided her answer long before. Her hand only followed that decision.'],
      ['해설', 'What was her answer? The writer never told us.'],
      ['해설', 'The question is left to the reader. Which came out of the right-hand door, the lady, or the tiger?'],
      ['해설', 'Published by Stockton in 1882, the story started a long debate among readers about its ending.'],
    ],
  },

  'wsa-witches-loaves': {
    title: 'Witches’ Loaves',
    names: { 해설: 'Narrator', 마사: 'Miss Martha', 블룸버거: 'Mr. Blumberger', 젊은이: 'Young Man' },
    outro: [
      'Why do you think Martha’s kindness ended up causing so much harm?',
      'How does Martha’s belief, from one stain on his fingers, that he was a poor artist set up the twist?',
      'Has help you gave with good intentions, without asking first, ever become a burden to someone?',
    ],
    lines: [
      ['해설', 'Miss Martha Meacham, forty years old, ran a small bakery on a corner. She had two thousand dollars in the bank and a warm heart.'],
      ['해설', 'One customer came in two or three times a week. The middle-aged man always bought just two loaves of stale bread.'],
      ['해설', 'He spoke with a German accent, and his clothes were worn but neat. Martha slowly began to look forward to his visits.'],
      ['해설', 'One day Martha saw a red and brown stain on his fingers. She was sure of it. He was a poor artist.'],
      ['마사', 'Poor man. He must paint in an attic and chew on stale bread. I wish I could give him something good to eat.'],
      ['해설', 'To test her guess, Martha hung a painting she had bought at a sale behind the counter.'],
      ['블룸버거', 'Two loaves of stale bread, please. You have a fine picture, madam. But the perspective is not true.'],
      ['해설', 'He took his bread and hurried out. Martha looked at the picture again and sighed. He had to be an artist.'],
      ['마사', 'A man who sees the perspective at a glance, living on stale bread.'],
      ['해설', 'After that, Martha took care with her looks. She wore a blue-dotted silk blouse and used a beauty cream she made herself.'],
      ['해설', 'His cheeks seemed to grow thinner. She wanted to give him fresh food, but feared hurting an artist’s pride.'],
      ['해설', 'One day he ordered his two stale loaves as usual. A fire engine roared past, and he went to the door to look.'],
      ['해설', 'An idea flashed into Martha’s mind. Under the counter was a pound of fresh butter delivered that morning.'],
      ['해설', 'With her bread knife, Martha cut deep slits in the stale loaves. She pushed in plenty of butter and pressed them shut.'],
      ['마사', 'When he breaks the bread, he will find the butter. It is my little gift to a poor artist.'],
      ['해설', 'He took the bag, bowed politely and left. All day long, Martha’s face kept turning pink.'],
      ['해설', 'But that afternoon, the door burst open, and the customer came in. A young man with him tried to hold him back.'],
      ['블룸버거', 'You foolish woman! Do you know what you have done? You have ruined everything!'],
      ['젊은이', 'Mr. Blumberger, please go. I will do the talking.'],
      ['해설', 'The young man led Blumberger outside, then came back in to explain to Martha.'],
      ['젊은이', 'He is an architectural draftsman. For three months, he has been drawing a plan for a new city hall contest.'],
      ['젊은이', 'He draws in pencil, inks the lines, then rubs out the pencil with stale bread crumbs. It is cleaner than an eraser.'],
      ['젊은이', 'That is why he bought stale bread. But today there was butter inside the bread.'],
      ['젊은이', 'The plan is covered in butter. Now it is good for nothing but wrapping sandwiches.'],
      ['해설', 'Martha went into the back room. She took off the blue-dotted silk blouse and put on her old brown dress.'],
      ['해설', 'Then she threw her homemade beauty cream out the window into the trash can.'],
      ['해설', 'Her daydreams about a man she did not really know had led her warm heart in the wrong direction.'],
      ['해설', 'O. Henry’s real name was William Sydney Porter. He died in New York in 1910.'],
    ],
  },

  'wsa-reformation': {
    title: 'A Retrieved Reformation',
    names: { 해설: 'Narrator', 간수: 'Guard', 지미: 'Jimmy Valentine', 벤: 'Ben Price', 은행장: 'Mr. Adams', 메이: 'May', 애너벨: 'Annabel Adams' },
    outro: [
      'Jimmy opened the safe knowing he would be found out. What does his choice show?',
      'What kind of twist does Ben Price give with his final words, pretending not to know Jimmy?',
      'If someone has truly changed, how do you think society should treat their past?',
    ],
    lines: [
      ['해설', 'Jimmy Valentine was working in the prison shoe shop when a guard called him out. The governor had signed his pardon.'],
      ['간수', 'Valentine, you go out tomorrow morning. Straighten up and live right. Stop cracking safes.'],
      ['지미', 'Me? I never cracked a safe in my life.'],
      ['해설', 'Free after ten months, Jimmy took a hidden suitcase from his old room. Inside were the finest safe-cracking tools.'],
      ['해설', 'A week later, a safe was robbed in Richmond. Then the same thing happened in Logansport and Jefferson City.'],
      ['해설', 'The famous detective Ben Price took the case. One look at how the safes were opened, and he knew the man.'],
      ['벤', 'That is Jimmy Valentine’s work. He is back in business. This time he will not get off with a short term.'],
      ['해설', 'One afternoon, Jimmy got off the train in Elmore, a small town in Arkansas. He came to look over the bank.'],
      ['해설', 'But in front of the bank, he met a young woman. The moment he saw her, Jimmy became another man.'],
      ['해설', 'She was Annabel Adams, the banker’s daughter. Jimmy decided to stay in town under the name Ralph Spencer.'],
      ['해설', 'Ralph Spencer opened a shoe store and did well. He won the town’s trust and even got engaged to Annabel.'],
      ['해설', 'Two weeks before the wedding, Jimmy wrote to an old friend. He would give him all his tools if they met.'],
      ['지미', 'I have quit the old business. I am living honestly, and I am marrying the finest girl in the world.'],
      ['해설', 'Around then, Ben Price quietly came to Elmore. From across the street, he watched Ralph Spencer.'],
      ['벤', 'Going to marry the banker’s daughter, are you, Jimmy? Well, we will see.'],
      ['해설', 'Next morning, Jimmy stopped by the bank with the Adams family, carrying his tool case. The bank had a new vault.'],
      ['은행장', 'This vault is the very latest. It has a time lock, so no one can open it before the set time.'],
      ['해설', 'Then Agatha, the little daughter of Annabel’s sister May, got shut inside the vault while the children were playing.'],
      ['은행장', 'I cannot open the door! The clock has not been wound, and the combination has not been set!'],
      ['메이', 'Agatha! Can you hear Mommy? Somebody break the door down, please!'],
      ['은행장', 'There is not enough air in there. If she faints from fear, it will be terrible.'],
      ['해설', 'Annabel turned to Jimmy with pain in her eyes. She believed the man she loved could do anything.'],
      ['애너벨', 'Ralph, can’t you do something?'],
      ['지미', 'Annabel, will you give me that rose you are wearing?'],
      ['해설', 'Jimmy put the rose in his vest pocket and threw off his coat. Ralph Spencer was gone, and Jimmy Valentine stood there.'],
      ['해설', 'He took out his tools. In ten minutes the steel bolts were thrown back and the door opened. Agatha was safe in her mother’s arms.'],
      ['해설', 'Jimmy put on his coat and walked out of the bank. Ben Price was standing at the door.'],
      ['지미', 'Hello, Ben. You got here at last. Let us go. It doesn’t matter now.'],
      ['벤', 'I think you are mistaken, Mr. Spencer. I don’t believe I know you. Your buggy is waiting, isn’t it?'],
      ['해설', 'A Retrieved Reformation is a short story O. Henry published in 1903. It was later made into a play.'],
    ],
  },
};
