// 청소년 영어 원고 (중학생 이상). 키 = stories/teen-shake3.js 의 이야기 id.
// 셰익스피어 원작(퍼블릭 도메인)을 한국어 각색의 흐름대로 쉬운 현대 영어로 새로 씀. 원작의 이름과 이름난 구절 몇 개만 살림.
export default {
  'tsp3-tempest-1': {
    title: 'The Tempest, Part 1',
    names: { 해설: 'Narrator', 프로스페로: 'Prospero', 미랜더: 'Miranda', 에어리얼: 'Ariel', 캘리밴: 'Caliban', 퍼디낸드: 'Ferdinand' },
    outro: [
      'Was the storm Prospero raised meant for revenge, or did it have another purpose?',
      'How does Caliban’s claim that the island was his change the way we see the story?',
      'How should we view newcomers ruling over the land of people who lived there first?',
    ],
    lines: [
      ['해설', 'In the middle of the sea, a ship was caught in a violent storm. The sails tore, and people screamed.'],
      ['해설', 'On board were Alonso, King of Naples, his son Ferdinand, and Antonio, Duke of Milan.'],
      ['해설', 'From a rock on a lonely island nearby, a girl named Miranda watched and stamped her feet.'],
      ['미랜더', 'Father, if your magic has made the sea like this, please stop it.'],
      ['프로스페로', 'Calm down. Not one person is hurt. Now it is time to tell you who we are.'],
      ['프로스페로', 'Twelve years ago, I was the Duke of Milan. But I cared more about books and magic than ruling.'],
      ['프로스페로', 'My brother Antonio, who ran the state for me, joined the King of Naples and drove me out.'],
      ['해설', 'Prospero and three-year-old Miranda were set adrift on the sea in a rotten little boat.'],
      ['해설', 'A kind lord, Gonzalo, secretly gave them food, clothes, and the books Prospero loved.'],
      ['프로스페로', 'The men on that ship are those very enemies. Fate has brought them close to my island.'],
      ['해설', 'When Miranda fell asleep, Ariel, a spirit of the air, flew in like the wind with news.'],
      ['에어리얼', 'Master, I wrapped the ship in flames as you ordered. I scattered the people safely around the island.'],
      ['에어리얼', 'Is it not time to set me free, as you promised?'],
      ['프로스페로', 'Have you forgotten? The witch Sycorax shut you in a split pine tree, and I freed you.'],
      ['프로스페로', 'Work two more days. Then I will set you as free as the sky.'],
      ['해설', 'There was one more person on the island, Caliban, son of Sycorax. He served Prospero and carried firewood.'],
      ['캘리밴', 'This island was left to me by my mother. Then you came and took it from me.'],
      ['캘리밴', 'At first you petted me and taught me words. I showed you the fresh springs and the fruit.'],
      ['캘리밴', 'Now I am a slave, locked in a rocky cave. With the words you taught me, I will curse.'],
      ['프로스페로', 'It is because you tried to harm Miranda. Now go and bring the firewood.'],
      ['해설', 'The play shows Caliban as a beastly monster. It holds the colonial view that native people were savage.'],
      ['해설', 'But Caliban’s protest about who owns the island also stays clearly in the play.'],
      ['해설', 'Meanwhile, drawn by Ariel’s song, Prince Ferdinand was wandering along the shore.'],
      ['퍼디낸드', 'My father has drowned in the sea. Where is this music coming from?'],
      ['해설', 'The moment Ferdinand and Miranda’s eyes met, they fell in love. It was just what Prospero wanted.'],
      ['프로스페로', 'What is won too easily is valued lightly. You are a spy. Go and carry logs.'],
      ['퍼디낸드', 'If I can only see this lady, I can bear prison and heavy logs.'],
      ['해설', 'Prospero acted strict on purpose, but secretly he was glad about their love.'],
      ['해설', 'The Tempest was printed as the very first play in the 1623 collection of Shakespeare’s plays.'],
    ],
  },

  'tsp3-tempest-2': {
    title: 'The Tempest, Part 2',
    names: { 해설: 'Narrator', 프로스페로: 'Prospero', 에어리얼: 'Ariel', 캘리밴: 'Caliban', 스테파노: 'Stephano', 앤토니오: 'Antonio', 세바스찬: 'Sebastian', 미랜더: 'Miranda' },
    outro: [
      'Prospero had every power to take revenge. Why did he choose to forgive in the end?',
      'How are the situations of Ariel, who wins freedom, and Caliban, who stays on the island, different?',
      'Is forgiving someone who hurt me for their sake, or for mine?',
    ],
    lines: [
      ['해설', 'Last time, Prospero’s magic storm brought his old enemies to the island, and Miranda fell for Ferdinand.'],
      ['해설', 'On one side of the island, Alonso, King of Naples, grieved for his lost son and fell asleep.'],
      ['앤토니오', 'Sebastian, the prince is dead. If we kill your brother now, the crown of Naples is yours.'],
      ['세바스찬', 'Just as you drove out your brother and took Milan? Very well. Let us draw our swords.'],
      ['해설', 'At that moment, Ariel sang into old Gonzalo’s ear and woke him. The plot stopped just in time.'],
      ['해설', 'Elsewhere, Caliban met Stephano, a drunken butler, and Trinculo, a jester.'],
      ['캘리밴', 'Did this drink fall from heaven? I will serve you as my new master.'],
      ['스테파노', 'Good, monster. Kill that magician, and I will be king of this island. You will be my servant.'],
      ['캘리밴', 'When he naps, take his books first. Without his books, he is just a fool like me.'],
      ['해설', 'To escape his life on the island, Caliban chose to serve yet another master.'],
      ['해설', 'Meanwhile, Ariel appeared before Alonso’s group as a harpy and made their feast vanish in an instant.'],
      ['에어리얼', 'You three are the sinners who drove good Prospero out to sea. The sea has not forgotten.'],
      ['해설', 'Alonso, Antonio, and Sebastian lost their senses in fear and were bound by magic.'],
      ['에어리얼', 'Master, if you saw them now, your heart would soften. Mine would, if I were human.'],
      ['프로스페로', 'If you, who are only air, feel their pain, how can I, a human like them, ignore it?'],
      ['프로스페로', 'Forgiveness is a rarer thing than revenge. If they are sorry, I want nothing more.'],
      ['해설', 'Caliban’s plot fell into Ariel’s tricks and ended uselessly in a muddy pond.'],
      ['해설', 'When Alonso woke from the spell, Prospero appeared before him in the robes of the Duke of Milan.'],
      ['해설', 'Alonso begged forgiveness and gave back the stolen dukedom. Antonio stood in silence.'],
      ['해설', 'Prospero drew back a curtain. Ferdinand, thought dead, was playing chess with Miranda.'],
      ['미랜더', 'So many wonderful people! How amazing is the brave new world that has such people in it!'],
      ['프로스페로', 'It is new to you. I have watched that world a little longer.'],
      ['해설', 'With the young couple’s marriage decided, the old hatred between Milan and Naples ended.'],
      ['캘리밴', 'I was a fool to worship this drunkard like a god. From now on, I will be wiser.'],
      ['해설', 'The play closes Caliban’s story with his regret, but says nothing of his future without his island.'],
      ['프로스페로', 'Ariel, now you are free. Fly into the wind as you please.'],
      ['해설', 'Prospero said he would break his magic staff and bury it, and throw his book deep into the sea.'],
      ['해설', 'He asked the audience to free him with their applause, and left the stage.'],
      ['해설', 'There is a record of The Tempest being performed at Whitehall Palace in London on November 1, 1611.'],
    ],
  },

  'tsp3-twelfth-1': {
    title: 'Twelfth Night, Part 1',
    names: { 해설: 'Narrator', 바이올라: 'Viola', 선장: 'Captain', 오시노: 'Orsino', 올리비아: 'Olivia', 말볼리오: 'Malvolio', 마리아: 'Maria', 토비: 'Sir Toby' },
    outro: [
      'Because Viola is dressed as a man, how do the loves of three people get tangled?',
      'What feeling is in Viola’s words that time must untangle this knot?',
      'Have you ever judged or liked someone only because of how they looked?',
    ],
    lines: [
      ['해설', 'After a shipwreck in a storm, a young woman washed up on the shore of a land called Illyria. Her name was Viola.'],
      ['바이올라', 'What has happened to my twin brother Sebastian? Surely he has not drowned?'],
      ['선장', 'I saw your brother tie himself to a mast and ride the waves. He may still be alive.'],
      ['해설', 'Alone now, Viola dressed as a man, took the name Cesario, and went to serve Duke Orsino.'],
      ['해설', 'Orsino loved the countess Olivia. But Olivia was grieving her dead brother and would not see any man.'],
      ['오시노', 'If music be the food of love, play on. If I hear too much, perhaps this longing will fade.'],
      ['해설', 'In just three days, Cesario became the duke’s most trusted servant. The duke sent him on a love errand.'],
      ['오시노', 'Cesario, with your young face, she will open her door. Tell her how I feel.'],
      ['바이올라', 'I will do my best. But how hard this is. I want to be his wife myself.'],
      ['해설', 'Viola had fallen in love with Orsino. Yet she had to carry his love to someone else.'],
      ['해설', 'At Olivia’s house, the steward Malvolio blocked the visitor with a sour face.'],
      ['말볼리오', 'My lady sees no one. But this young man will not leave, no matter how I send him away.'],
      ['해설', 'Olivia came out in a veil. Little by little, she listened closely to Cesario’s bold and poetic words.'],
      ['바이올라', 'If I were the duke, I would build a willow cabin at your gate and call your name all night.'],
      ['올리비아', 'Then my heart might move. But go back and tell the duke I cannot love him.'],
      ['해설', 'After Cesario left, Olivia sent Malvolio after him with a ring.'],
      ['말볼리오', 'My lady says to return the ring you left. Do not come again.'],
      ['바이올라', 'I left no ring. Oh, she has fallen for this fake young man.'],
      ['바이올라', 'The duke loves her, she loves me, and I love the duke. O time, you must untangle this, not I.'],
      ['해설', 'Olivia’s uncle, Sir Toby, lived in the same house. He drank and sang every night.'],
      ['해설', 'When Malvolio scolded them, Toby and the maid Maria decided to play a trick on the proud steward.'],
      ['토비', 'That steward thinks he is better than us. We should knock him down a peg.'],
      ['마리아', 'My handwriting looks just like my lady’s. I will write a letter saying she secretly loves him.'],
      ['해설', 'Malvolio found the letter on the garden path and firmly believed it was Olivia’s confession.'],
      ['말볼리오', 'Wear yellow stockings, cross my garters, and always smile? My lady, I will do it all!'],
      ['해설', 'Hiding nearby, Toby and Maria held their stomachs, trying not to laugh.'],
      ['해설', 'Malvolio, a servant, dreamed of becoming master of a noble house. The trick began by mocking that dream.'],
      ['해설', 'Around that time, Sebastian, believed dead, had reached another shore alive.'],
      ['해설', 'The title means the twelfth night after Christmas, the night the Christmas season ends.'],
    ],
  },

  'tsp3-twelfth-2': {
    title: 'Twelfth Night, Part 2',
    names: { 해설: 'Narrator', 바이올라: 'Viola', 말볼리오: 'Malvolio', 올리비아: 'Olivia', 앤드루: 'Sir Andrew', 토비: 'Sir Toby', 세바스찬: 'Sebastian', 오시노: 'Orsino' },
    outro: [
      'The moment the twins appear together, how do the tangled loves find their right places?',
      'In an ending where everyone laughs, how should we see Malvolio, who alone cries for revenge?',
      'Where do you think the line is between a joke and bullying?',
    ],
    lines: [
      ['해설', 'Last time, Viola, dressed as a man, loved the duke, while Olivia fell for Viola.'],
      ['해설', 'Fooled by the fake letter, Malvolio appeared before Olivia in bright yellow stockings, cross-gartered.'],
      ['말볼리오', 'My lady, I am smiling as you wished. Some are born great, and some have greatness thrust upon them.'],
      ['올리비아', 'This man must truly be mad. Tell my uncle Toby to take good care of him.'],
      ['해설', 'Toby treated Malvolio as a madman and locked him in a dark room. The joke grew crueler.'],
      ['말볼리오', 'I am not mad! This room is as dark as hell, but my mind is as clear as anyone’s.'],
      ['해설', 'Meanwhile Sir Andrew, a cowardly knight who wanted to marry Olivia, grew jealous of Cesario.'],
      ['토비', 'Challenge him to a duel, Sir Andrew. Show courage in front of the lady, and you will win her heart.'],
      ['앤드루', 'Fine, but what if he is good with a sword? Can I give him my grey horse and forget it?'],
      ['바이올라', 'I have never held a sword. A little more fear and I will confess I am not a man.'],
      ['해설', 'As the two cowards raised their swords, Sebastian’s friend, the sea captain Antonio, rushed in to protect Cesario.'],
      ['해설', 'But Antonio was soon arrested by the duke’s officers. He called Cesario Sebastian and blamed him for betrayal.'],
      ['바이올라', 'Sebastian? If my brother is alive, the waves were kind after all.'],
      ['해설', 'Meanwhile the real Sebastian came into town. Andrew and Toby took him for Cesario, attacked, and were soundly beaten.'],
      ['해설', 'Olivia ran out and led him home. Sebastian was confused, but did not refuse the beautiful lady.'],
      ['세바스찬', 'If this is a dream, let me never wake. I will do as you wish.'],
      ['해설', 'The two went straight to a chapel and promised to marry. Olivia believed she was bound to Cesario.'],
      ['해설', 'Soon Duke Orsino came to see Olivia. She called Cesario, standing beside the duke, her husband.'],
      ['오시노', 'You traitor! You went on my errand and stole my love?'],
      ['바이올라', 'I swear I did not. I love you more than my own life.'],
      ['해설', 'Then Sebastian walked in. Everyone saw two identical faces and could not believe their eyes.'],
      ['세바스찬', 'I had one sister, but the waves swallowed her. Who are you?'],
      ['바이올라', 'My father had a mole on his brow, and he died when I was thirteen. Brother, it is me.'],
      ['해설', 'The twins hugged each other. Olivia found her real husband, and Orsino asked Viola to marry him.'],
      ['오시노', 'You told me many times that you loved me. Now change your clothes and be my wife.'],
      ['해설', 'Last of all, Malvolio was set free and came in. When he heard the whole story of the trick, he did not laugh.'],
      ['말볼리오', 'I will be revenged on the whole pack of you.'],
      ['해설', 'In the festive ending, only the anger of the steward, mocked for reaching above his rank, stayed unresolved.'],
      ['해설', 'In Shakespeare’s time, boy actors played women’s roles like Viola on the English stage.'],
    ],
  },

  'tsp3-caesar-1': {
    title: 'Julius Caesar, Part 1',
    names: { 해설: 'Narrator', 점쟁이: 'Soothsayer', 시저: 'Julius Caesar', 카시우스: 'Cassius', 브루투스: 'Brutus', 카스카: 'Casca', 포셔: 'Portia', 칼푸르니아: 'Calpurnia' },
    outro: [
      'Why did Brutus join the plot to kill Caesar, who had been his friend?',
      'What words did Cassius use to move Brutus’s heart?',
      'Can a goal we believe is right ever justify violence?',
    ],
    lines: [
      ['해설', 'Ancient Rome. When Caesar returned after winning a civil war, citizens poured into the streets and cheered.'],
      ['해설', 'In the festival parade, an old soothsayer pushed through the crowd and called out to Caesar.'],
      ['점쟁이', 'Caesar, beware the ides of March.'],
      ['시저', 'He is a dreamer. Leave him, and let us go.'],
      ['해설', 'After the parade passed, Cassius took aside Brutus, Caesar’s friend and a respected Roman.'],
      ['카시우스', 'Caesar is a man just like us. He shook with fever, and once he cried to me for help in the river.'],
      ['카시우스', 'Now he stands over the world like a giant, and we crawl about between his legs.'],
      ['카시우스', 'The fault, dear Brutus, is not in our stars, but in ourselves.'],
      ['브루투스', 'I love Rome. I will think about what is good for Rome.'],
      ['해설', 'Just then, three shouts rose from the square. Casca came over and told them what had happened.'],
      ['카스카', 'Antony offered him a crown three times. Caesar pushed it away each time, but each time more unwillingly.'],
      ['해설', 'That night a terrible storm hit Rome. People whispered that it was a bad omen.'],
      ['해설', 'Cassius had letters, made to look as if citizens wrote them, thrown through Brutus’s window.'],
      ['브루투스', 'I hold nothing personal against him. But if he wears a crown, his nature may change.'],
      ['브루투스', 'A snake must be crushed while it is still in the egg. Once it hatches, it is too late.'],
      ['해설', 'At dawn, the plotters came to Brutus. They agreed to kill Caesar in the Senate on the ides of March.'],
      ['해설', 'Cassius wanted to kill Antony, Caesar’s right-hand man, as well. But Brutus refused.'],
      ['브루투스', 'Let us be sacrificers, not butchers. We only need to defeat the spirit of Caesar.'],
      ['포셔', 'My husband, why can you not sleep at night? If I am your wife, share your secret with me.'],
      ['해설', 'That same night, Caesar’s wife Calpurnia dreamed that blood spouted from her husband’s statue.'],
      ['칼푸르니아', 'Do not go out today. When beggars die, no comets are seen. The heavens are warning you.'],
      ['시저', 'Cowards die many times before their deaths. The brave taste death only once.'],
      ['해설', 'For his wife’s sake, Caesar meant to stay home. But Decius, one of the plotters, gave the dream a happy meaning.'],
      ['해설', 'Hearing that the Senate would offer him a crown that day, Caesar changed his mind and went out.'],
      ['시저', 'The ides of March have come.'],
      ['점쟁이', 'Yes, Caesar, but they have not gone.'],
      ['해설', 'In the Senate, the plotters surrounded Caesar, pretending to plead with him. Casca struck first.'],
      ['해설', 'Blade followed blade. Caesar saw Brutus’s face at last and stopped fighting back.'],
      ['시저', 'Et tu, Brute? Then fall, Caesar.'],
      ['해설', 'In history, Julius Caesar was assassinated in Rome on March 15, 44 BC.'],
    ],
  },

  'tsp3-caesar-2': {
    title: 'Julius Caesar, Part 2',
    names: { 해설: 'Narrator', 브루투스: 'Brutus', 안토니우스: 'Mark Antony', 시민: 'Citizen', 카시우스: 'Cassius', 시저: 'Caesar’s Ghost' },
    outro: [
      'Did the men who killed Caesar protect Rome’s freedom, or bring even greater chaos?',
      'While pretending to praise Brutus, how did Antony turn the crowd’s hearts around?',
      'What should we check so that we are not carried away by a skilled speaker?',
    ],
    lines: [
      ['해설', 'Last time, Brutus, Cassius, and the others killed Caesar in the Senate in the name of Rome’s freedom.'],
      ['해설', 'Antony, Caesar’s right-hand man, came and asked to speak at Caesar’s funeral.'],
      ['해설', 'Cassius tried to stop it, but Brutus agreed. He believed it was enough if he spoke first.'],
      ['브루투스', 'Citizens of Rome, I loved Caesar. But I loved Rome more.'],
      ['브루투스', 'Would you rather Caesar lived and you all died slaves, or Caesar died and you all lived free?'],
      ['시민', 'Long live Brutus! Let us honor him as we did Caesar!'],
      ['해설', 'When Brutus left, Antony stepped up to speak, with Caesar’s body before him.'],
      ['안토니우스', 'Friends, Romans, countrymen, lend me your ears. I come to bury Caesar, not to praise him.'],
      ['안토니우스', 'Brutus says Caesar was ambitious. And Brutus is an honorable man, so it must be true.'],
      ['안토니우스', 'Yet the ransoms Caesar won for his captives all went into the public treasury. Is that ambition?'],
      ['안토니우스', 'When the poor cried, Caesar wept too. Still, Brutus is an honorable man.'],
      ['안토니우스', 'You all saw it. Three times I offered him a crown, and three times he refused.'],
      ['안토니우스', 'Please wait a moment. My heart is in the coffin there with Caesar.'],
      ['시민', 'There is sense in what he says. Was Caesar killed unjustly?'],
      ['해설', 'Antony took out Caesar’s will, then folded it, saying he would not read it. The crowd begged to hear.'],
      ['해설', 'He held up Caesar’s torn cloak and named a plotter for every hole.'],
      ['안토니우스', 'This hole was made by Brutus, whom Caesar loved most. That was the unkindest cut of all.'],
      ['안토니우스', 'The will gives money to every citizen, and leaves his gardens to all of you as a public park.'],
      ['시민', 'Catch the traitors! Burn their houses!'],
      ['해설', 'The crowd poured into the streets with torches. Brutus and Cassius fled from Rome.'],
      ['해설', 'Antony joined Octavius, Caesar’s adopted son, and raised an army. Rome fell into civil war again.'],
      ['카시우스', 'Brutus, to fight between ourselves! It hurts me that you attacked me over money.'],
      ['브루투스', 'Forgive me. I have heard that Portia is dead, and my mind is troubled.'],
      ['해설', 'That night, Caesar’s ghost appeared in Brutus’s tent.'],
      ['시저', 'I am your evil spirit. You will see me again at Philippi.'],
      ['해설', 'At the battle of Philippi, Cassius misjudged how the fight was going and asked his servant to kill him.'],
      ['해설', 'When defeat was certain, Brutus ran upon his own sword. He died calling Caesar’s name.'],
      ['안토니우스', 'The other plotters acted out of envy. This man alone took up the sword believing it was for Rome.'],
      ['해설', 'Shakespeare based this play on Thomas North’s 1579 English translation of Plutarch’s Lives.'],
    ],
  },
};
