// 청소년 영어 원고: 레 미제라블 1~10화 (stories/teen-lesmis.js). 문장은 자체 각색.
// lines 의 첫 칸은 한국어 이야기 cast 의 이름 그대로.
export default {
  'lm-01': {
    title: 'Les Misérables, Part 1',
    names: { 해설: 'Narrator', 장발장: 'Jean Valjean', 여관주인: 'Innkeeper', 미리엘: 'Bishop Myriel', 헌병: 'Gendarme', 제르베: 'Petit Gervais' },
    outro: [
      'Why did the bishop’s gift of the candlesticks change Valjean more than any punishment?',
      'What question does the writer raise by placing one loaf of bread next to nineteen years?',
      'How many second chances does our society give to people who once did wrong?',
    ],
    lines: [
      ['해설', 'In October 1815, at sunset, a man with an old bag walked into the town of Digne.'],
      ['해설', 'His name was Jean Valjean. He had just been set free from the prison at Toulon.'],
      ['해설', 'Years before, he had stolen a loaf of bread for his sister’s seven hungry children.'],
      ['해설', 'He got five years, but he tried to escape again and again. In the end, he served nineteen.'],
      ['해설', 'His yellow passport told everyone that he was a dangerous man.'],
      ['장발장', 'I have money. I only want a meal and a bed.'],
      ['여관주인', 'I know who you are. There is no room for you here. Get out.'],
      ['해설', 'No inn would take him. Even a dog kennel was closed to him.'],
      ['해설', 'As he lay on a stone bench, an old woman pointed to a small house across the street.'],
      ['해설', 'It was the home of Myriel, the Bishop of Digne.'],
      ['장발장', 'I am a convict. I was in prison for nineteen years. Will you still let me in?'],
      ['미리엘', 'This door does not ask a man’s name. You are tired and hungry. Come in and rest.'],
      ['해설', 'The bishop called him sir. He set out silver plates and lit two silver candlesticks.'],
      ['해설', 'But late that night, Valjean woke up. He could think of nothing but the silver.'],
      ['해설', 'He took the basket of silver, climbed over the wall, and ran into the dark.'],
      ['해설', 'The next morning, gendarmes dragged him back to the bishop’s house.'],
      ['헌병', 'He had your silver, Bishop. He says you gave it to him.'],
      ['미리엘', 'Ah, there you are! But why did you leave the candlesticks? I gave you those, too.'],
      ['해설', 'The puzzled gendarmes let Valjean go and left.'],
      ['미리엘', 'Do not forget your promise to use this silver to become an honest man.'],
      ['미리엘', 'My brother, you no longer belong to evil, but to good.'],
      ['해설', 'Valjean had never made such a promise. Without a word, he walked away.'],
      ['해설', 'In a field, a poor wandering boy dropped a silver coin, and Valjean put his foot on it.'],
      ['제르베', 'Sir, that’s my money! Please move your foot!'],
      ['장발장', 'Go away!'],
      ['해설', 'Only after the boy ran off crying did Valjean understand what he had done.'],
      ['장발장', 'Gervais! Little Gervais! Come back!'],
      ['해설', 'There was no answer. He fell to the ground and wept for the first time in nineteen years.'],
      ['해설', 'That night, a convict disappeared, and a man who wanted to change was left behind.'],
      ['해설', 'Victor Hugo published Les Misérables in 1862.'],
    ],
  },

  'lm-02': {
    title: 'Les Misérables, Part 2',
    names: { 해설: 'Narrator', 장발장: 'Jean Valjean', 주민: 'Townswoman', 자베르: 'Javert', 포슐르방: 'Fauchelevent' },
    outro: [
      'As Mayor Madeleine, how did Valjean pass on the kindness he had received?',
      'Which detail about Javert best shows that he believes only in law and order?',
      'If helping someone meant your secret might come out, what would you do?',
    ],
    lines: [
      ['해설', 'Last time, Bishop Myriel gave Valjean the silver candlesticks, and Valjean decided to change.'],
      ['해설', 'At the end of 1815, a fire broke out in the town hall of Montreuil-sur-Mer.'],
      ['해설', 'A stranger ran into the flames and carried out the two children of the police captain.'],
      ['해설', 'Nobody asked to see his passport. He said his name was Madeleine.'],
      ['해설', 'The town made black glass beads and jewelry for a living.'],
      ['해설', 'Madeleine found a cheaper way to make them and built a factory.'],
      ['해설', 'Soon there were jobs for everyone. With his money, he built a school and a hospital.'],
      ['주민', 'Monsieur Madeleine, you must be our mayor. You saved this town!'],
      ['장발장', 'I am not the right man for that.'],
      ['해설', 'He said no many times, but in 1820 he finally became mayor.'],
      ['해설', 'The next year, the newspaper reported that the Bishop of Digne had died. Madeleine wore black.'],
      ['해설', 'But one man in town watched Madeleine with suspicion.'],
      ['해설', 'It was Javert, the new police inspector. Born in a prison, he believed in the law like a religion.'],
      ['자베르', 'I have seen that face before. But where?'],
      ['해설', 'One day, a horse fell on a muddy road, and old Fauchelevent was trapped under his cart.'],
      ['포슐르방', 'Help! It is crushing my chest! Somebody save me!'],
      ['장발장', 'Can anyone lift this cart? I will pay well!'],
      ['해설', 'People only looked at each other. The cart sank slowly into the mud.'],
      ['자베르', 'I have known only one man strong enough to lift a cart with his back.'],
      ['자베르', 'He was a convict at Toulon. A man like you, Mayor, could never do it.'],
      ['해설', 'Madeleine turned pale. Javert’s eyes did not leave him.'],
      ['해설', 'After a moment, Madeleine knelt in the mud and crawled under the cart.'],
      ['해설', 'He pushed with all his strength. The cart rose slowly, and people pulled the old man out.'],
      ['포슐르방', 'Mayor, heaven sent you to me.'],
      ['해설', 'Fauchelevent’s knee was hurt, so Madeleine found him a job as a gardener at a convent in Paris.'],
      ['자베르', 'That convict’s name was Jean Valjean.'],
      ['해설', 'Javert turned and walked away. Madeleine stood there for a long time.'],
      ['해설', 'At that time, a young woman with a secret was working in Madeleine’s factory.'],
      ['해설', 'In the novel, Valjean’s prisoner number at Toulon was 24601.'],
    ],
  },

  'lm-03': {
    title: 'Les Misérables, Part 3',
    names: { 해설: 'Narrator', 팡틴: 'Fantine', 테나르디에: 'Thénardier', 감독: 'Forewoman', 바마타부아: 'Bamatabois', 자베르: 'Javert', 장발장: 'Jean Valjean' },
    outro: [
      'Was Fantine ruined by one person’s cruelty, or by many people not caring?',
      'Why do you think the story tells about selling her hair and teeth so briefly?',
      'How can a single rumor still destroy someone’s job and life today?',
    ],
    lines: [
      ['해설', 'Last time, Valjean became Mayor Madeleine, but Javert began to suspect him.'],
      ['해설', 'Fantine, a worker in his factory, had been fooled by a man in Paris and left alone with a baby.'],
      ['해설', 'No one would hire a woman with a child. She stopped at an inn in Montfermeil.'],
      ['해설', 'The innkeepers, the Thénardiers, agreed to keep three-year-old Cosette for monthly payments.'],
      ['팡틴', 'Please take good care of my Cosette. I will earn money and come back for her.'],
      ['해설', 'But they dressed Cosette in rags and worked her like a servant. Their letters only asked for money.'],
      ['테나르디에', 'The child has a fever. Send forty francs for medicine at once.'],
      ['해설', 'A rumor spread in the factory that Fantine had someone write secret letters for her.'],
      ['감독', 'You have a child and no husband? We cannot keep someone like you here.'],
      ['해설', 'The mayor knew nothing about it. But Fantine believed he had thrown her out.'],
      ['해설', 'To send money, she sold her golden hair. Then she sold two of her front teeth.'],
      ['팡틴', 'Now I have nothing left but myself. But Cosette must stay warm.'],
      ['해설', 'Chased by debt and sickness, Fantine was finally forced to sell herself on the streets.'],
      ['해설', 'One snowy night, a rich idler named Bamatabois mocked her and pushed snow down her back.'],
      ['바마타부아', 'Your shoulders are bare in this cold! Let me cover them with snow.'],
      ['해설', 'Fantine screamed and attacked him. Javert appeared and arrested only her.'],
      ['자베르', 'You struck a gentleman. Six months in prison.'],
      ['팡틴', 'Please, Inspector! If I go to prison, my little girl will end up on the street!'],
      ['해설', 'Then Mayor Madeleine came in. Fantine spat in his face.'],
      ['장발장', 'Inspector Javert, let this woman go.'],
      ['자베르', 'Mayor, I cannot free someone who broke the law.'],
      ['장발장', 'I saw everything. The man was to blame. As mayor, I order you.'],
      ['해설', 'Only then did Fantine see that this man had come to save her, not to hurt her.'],
      ['해설', 'She fell ill with fever. The mayor put her in the hospital and promised to bring Cosette.'],
      ['해설', 'Javert felt insulted. He wrote to the Paris police that Madeleine was Jean Valjean.'],
      ['해설', 'But an answer came back. The real Jean Valjean had been caught somewhere else.'],
      ['자베르', 'I accused you falsely, Mayor. Please dismiss me.'],
      ['해설', 'Madeleine forgave him. But the story of the captured man kept him awake at night.'],
      ['해설', 'Hugo wrote much of this novel while living in exile on the island of Guernsey.'],
    ],
  },

  'lm-04': {
    title: 'Les Misérables, Part 4',
    names: { 해설: 'Narrator', 장발장: 'Jean Valjean', 샹마티외: 'Champmathieu', 재판장: 'Judge', 팡틴: 'Fantine', 자베르: 'Javert' },
    outro: [
      'Everyone would have been better off if Valjean stayed silent, so why did he go to the court in Arras?',
      'Why do you think Hugo compared Valjean’s long night of struggle to a storm?',
      'If someone else were paying for your mistake, could you stay silent to the end?',
    ],
    lines: [
      ['해설', 'Last time, Mayor Madeleine saved Fantine and heard that the real Jean Valjean had been caught.'],
      ['해설', 'The captured man was an old worker named Champmathieu. He was on trial in Arras for stealing apples.'],
      ['해설', 'Old convicts said he was Jean Valjean. If he was found guilty, he would be locked up for life.'],
      ['해설', 'That night, Madeleine walked around his room, asking himself the same question again and again.'],
      ['장발장', 'If I stay quiet, I am free forever. I can protect the factory, the town, and Fantine.'],
      ['장발장', 'But then an innocent old man will wear chains under my name.'],
      ['해설', 'He threw his old convict things into the fire. Then his eyes met the silver candlesticks.'],
      ['해설', 'At dawn, he rented a carriage and left for Arras. A wheel broke, but he did not stop.'],
      ['해설', 'It was night when he reached the court. The trial was almost over.'],
      ['샹마티외', 'I don’t know any Jean Valjean. I just picked up a branch of apples from the road.'],
      ['재판장', 'All the witnesses say you are Jean Valjean of Toulon. Do you have anything else to say?'],
      ['해설', 'Then a gentleman stood up among the crowd. It was the Mayor of Montreuil-sur-Mer.'],
      ['장발장', 'Let that man go. I am Jean Valjean.'],
      ['해설', 'The courtroom was in an uproar. The judge thought the mayor had lost his mind.'],
      ['해설', 'Madeleine named the old convicts’ scars and secrets from prison, one by one.'],
      ['장발장', 'Now I have something I must do. The prosecutor knows where to find me.'],
      ['해설', 'No one stopped him. Champmathieu was set free, and Madeleine went back to Montreuil.'],
      ['해설', 'He went straight to Fantine’s hospital room. She asked about Cosette first.'],
      ['팡틴', 'Mayor, where is my Cosette? I can see her soon, can’t I?'],
      ['해설', 'At that moment, the door opened and Javert walked in. His face showed a cold joy.'],
      ['자베르', 'It is over, Jean Valjean. Come with me.'],
      ['장발장', 'Give me three days. I must bring this woman her child. Then I will go anywhere you want.'],
      ['자베르', 'A convict making deals with an inspector? Don’t make me laugh!'],
      ['해설', 'The mayor was a convict, and she would never see her child. Fantine shook with fear.'],
      ['해설', 'She fell back and never rose again. That is how Fantine died.'],
      ['해설', 'Valjean held her hand and whispered something in her ear. Then he quietly followed Javert.'],
      ['해설', 'Without Madeleine, the factory closed, and the town became poor again.'],
      ['해설', 'Valjean was taken back to the prison at Toulon. But he did not forget his promise.'],
      ['해설', 'Back in 1829, Hugo wrote The Last Day of a Condemned Man against the death penalty.'],
    ],
  },

  'lm-05': {
    title: 'Les Misérables, Part 5',
    names: { 해설: 'Narrator', 장발장: 'Jean Valjean', 코제트: 'Cosette', 안주인: 'Madame Thénardier', 테나르디에: 'Thénardier' },
    outro: [
      'What does the scene where Valjean carries Cosette’s bucket tell us about their future?',
      'How does Thénardier’s way of talking show his character when he raises the price?',
      'What should society do to stop adults from using children to make money?',
    ],
    lines: [
      ['해설', 'Last time, Valjean revealed who he was to save another man, and Fantine died.'],
      ['해설', 'In the autumn of 1823, Valjean was working on a warship at Toulon when he saved a sailor.'],
      ['해설', 'But right after he put the sailor safely on deck, he fell into the sea and disappeared.'],
      ['해설', 'The newspaper said the convict Jean Valjean had drowned. But he was alive.'],
      ['해설', 'That Christmas Eve, a little girl was alone on a dark forest path near Montfermeil.'],
      ['해설', 'It was eight-year-old Cosette. She was carrying water from the spring, as she had been told.'],
      ['코제트', 'It’s too heavy. Oh God, I’m so scared.'],
      ['해설', 'Then a large hand reached out and took the handle of her bucket.'],
      ['장발장', 'This is too heavy for you, child. Let me carry it. How old are you?'],
      ['코제트', 'I’m eight. I don’t have a mother. That’s what everyone says.'],
      ['해설', 'Valjean realized that this girl was Fantine’s daughter.'],
      ['해설', 'At the inn, Madame Thénardier scolded Cosette for being late and looked the stranger up and down.'],
      ['안주인', 'You lazy thing! Half a day for one bucket? And you, sir, pay for your room first.'],
      ['해설', 'The Thénardiers’ two daughters played with a doll. Cosette knitted under the table.'],
      ['해설', 'Valjean went out and bought the biggest doll in the shop. He gave it to Cosette.'],
      ['코제트', 'Is it really mine? Madame, may I touch it?'],
      ['해설', 'That night, Cosette found a gold coin in her old wooden shoe by the fireplace.'],
      ['해설', 'The next morning, Valjean said he would take Cosette away. Thénardier’s eyes lit up.'],
      ['테나르디에', 'That child is as dear to us as our own lives. We can’t just let her go.'],
      ['테나르디에', 'When I count everything she cost us, I must ask for fifteen hundred francs.'],
      ['해설', 'Valjean silently put fifteen hundred francs on the table. Then he dressed Cosette in black mourning clothes.'],
      ['해설', 'After they left, Thénardier ran after them. He thought he had asked too little.'],
      ['테나르디에', 'You need a note from her mother to take her. Or pay me a thousand crowns more.'],
      ['해설', 'Valjean showed him a note from Fantine. It said to give the child to this man.'],
      ['해설', 'Valjean held a thick club. Thénardier did not dare come any closer.'],
      ['해설', 'Cosette held her doll tight and took Valjean’s hand. His hand was big and warm.'],
      ['코제트', 'Sir, where are we going now?'],
      ['장발장', 'To Paris. No one will ever make you fetch water again.'],
      ['해설', 'They hid in a shabby house at the edge of Paris. But a shadow was following them.'],
      ['해설', 'In the novel, Cosette’s real name is Euphrasie. Cosette is the nickname she had as a little girl.'],
    ],
  },

  'lm-06': {
    title: 'Les Misérables, Part 6',
    names: { 해설: 'Narrator', 장발장: 'Jean Valjean', 코제트: 'Cosette', 자베르: 'Javert', 포슐르방: 'Fauchelevent', 무덤꾼: 'Gravedigger' },
    outro: [
      'What was Valjean protecting when he took the risk of lying in a coffin?',
      'How does the chase from the dark streets to the high wall build tension?',
      'Would you rather grow up in a safe place away from the world, or in the free world outside?',
    ],
    lines: [
      ['해설', 'Last time, Valjean took Cosette out of the Thénardiers’ inn and went to Paris.'],
      ['해설', 'In the Gorbeau house at the edge of Paris, the two spent their first peaceful days.'],
      ['해설', 'Valjean taught Cosette to read, and Cosette called him Father.'],
      ['코제트', 'Father, now I can laugh all day and nobody scolds me.'],
      ['해설', 'But one day, as he gave a coin to a beggar near the church, Valjean caught his breath.'],
      ['해설', 'The face under the hat looked like Javert’s. Javert had moved to Paris by then.'],
      ['해설', 'A few nights later, Valjean took Cosette’s hand and slipped out of the house.'],
      ['해설', 'Every time they turned a corner, footsteps followed. It was Javert and his men.'],
      ['자베르', 'No need to hurry. That street is a dead end. Block both sides.'],
      ['해설', 'Ahead was a high wall. He could not climb it while carrying Cosette.'],
      ['해설', 'Valjean cut the rope from a street lamp and climbed the corner of the wall with his bare hands.'],
      ['해설', 'He pulled Cosette up with the rope, and they dropped down into a garden on the other side.'],
      ['코제트', 'Father, I’m scared. Is that woman chasing us?'],
      ['장발장', 'Shh, be patient a little longer. Now no one can find us.'],
      ['해설', 'It was the Petit-Picpus convent, closed off from the world. No man was allowed inside.'],
      ['해설', 'An old gardener with a little bell on his knee came toward them.'],
      ['포슐르방', 'Why, Mayor Madeleine! You saved me from under that cart!'],
      ['장발장', 'Fauchelevent, this time I need your help.'],
      ['해설', 'To stay in the convent, Valjean first had to go out and then come in properly through the gate.'],
      ['해설', 'Just then, a nun died. The two men agreed to bury her secretly inside the convent.'],
      ['해설', 'Instead, Valjean lay down in her coffin, and it was carried to the cemetery.'],
      ['해설', 'But the old gravedigger, Fauchelevent’s drinking friend, had been replaced. Fauchelevent turned pale.'],
      ['무덤꾼', 'I’m new here. I have to cover this with dirt before dark, so move.'],
      ['해설', 'Fauchelevent hid the man’s entry card. While he went to look for it, Fauchelevent opened the coffin.'],
      ['포슐르방', 'Mayor, open your eyes! Please be alive!'],
      ['해설', 'After a long time, Valjean gasped for air. After dark, they knocked boldly on the convent gate.'],
      ['해설', 'He became the gardener’s brother and worked in the garden. Cosette entered the convent school.'],
      ['해설', 'Years went by. Cosette was slowly becoming a young woman.'],
      ['해설', 'At the convent, Valjean was known by the name Ultime Fauchelevent.'],
    ],
  },

  'lm-07': {
    title: 'Les Misérables, Part 7',
    names: { 해설: 'Narrator', 질노르망: 'Gillenormand', 마리우스: 'Marius', 코제트: 'Cosette', 테나르디에: 'Thénardier', 장발장: 'Jean Valjean', 에포닌: 'Éponine' },
    outro: [
      'How did learning the truth about his father change Marius’s life?',
      'When Éponine leads Marius to Cosette, what do you think she is feeling?',
      'If your family’s beliefs clashed with your own, what choice could you make?',
    ],
    lines: [
      ['해설', 'Last time, Valjean hid from Javert in a convent, and Cosette grew up there.'],
      ['해설', 'In Paris lived a young man named Marius. His royalist grandfather, Gillenormand, raised him.'],
      ['해설', 'His father, Colonel Pontmercy, had fought for Napoleon. The grandfather hated him.'],
      ['해설', 'After the colonel died, Marius learned that his father had secretly watched him and missed him.'],
      ['해설', 'The colonel left a last wish. Marius must repay a man named Thénardier, who saved him at Waterloo.'],
      ['질노르망', 'If you call that traitor your father, get out of my house!'],
      ['마리우스', 'Grandfather, I will never be ashamed of my father.'],
      ['해설', 'Marius lived in a poor rented room and worked as a translator. He made friends with republican students.'],
      ['해설', 'In the Luxembourg Garden, he kept seeing an old gentleman and his daughter on the same bench.'],
      ['해설', 'They were Valjean and Cosette, who had left the convent. One day, Cosette looked up at him.'],
      ['마리우스', 'One look from her, and the whole world has changed.'],
      ['해설', 'Valjean noticed and stopped their walks. He moved away. Marius did not even know her name.'],
      ['해설', 'Next door to Marius lived a poor family called Jondrette. They were really the ruined Thénardiers.'],
      ['해설', 'One day, a kind gentleman visited them. Through a crack in the wall, Marius saw the old man from the garden.'],
      ['해설', 'Thénardier recognized him as the man who took Cosette, and he set a trap.'],
      ['테나르디에', 'This time he won’t get away. When he comes back tonight, we tie him up and squeeze out his money.'],
      ['해설', 'Marius told the police. The officer in charge was Javert. That night, the gentleman was caught.'],
      ['장발장', 'I am not afraid of you. You will get nothing from me.'],
      ['해설', 'Marius learned that Thénardier was the man who had saved his father, and he hesitated.'],
      ['해설', 'Then Javert burst in. In the confusion, the gentleman escaped through the window.'],
      ['해설', 'Éponine, Thénardier’s eldest daughter, secretly loved Marius. She found where the girl lived.'],
      ['에포닌', 'I found where she lives. It’s on the Rue Plumet. Follow me.'],
      ['해설', 'Every night, Marius met Cosette in the garden behind the wall. For the first time, they held hands.'],
      ['코제트', 'At last I know your name. Marius, will you come again tomorrow night?'],
      ['마리우스', 'On days I can’t see you, I think I’ll forget how to breathe.'],
      ['해설', 'But a note telling Valjean to move fell into his yard. He began to prepare to leave for England.'],
      ['해설', 'At the same time, the streets of Paris were boiling with anger. June 1832 was coming.'],
      ['해설', 'Hugo is said to have put much of his own young self into the poor law student Marius.'],
    ],
  },

  'lm-08': {
    title: 'Les Misérables, Part 8',
    names: { 해설: 'Narrator', 앙졸라: 'Enjolras', 가브로슈: 'Gavroche', 자베르: 'Javert', 마리우스: 'Marius', 에포닌: 'Éponine', 장발장: 'Jean Valjean' },
    outro: [
      'How is Valjean’s choice to free Javert connected to the bishop in Part 1?',
      'What weight does a young boy like Gavroche add by standing in the middle of the fight?',
      'What do you think about wanting to change the world and the sacrifices it can cost?',
    ],
    lines: [
      ['해설', 'Last time, Marius and Cosette shared their love, but Valjean prepared to leave.'],
      ['해설', 'On June 5, 1832, the funeral of General Lamarque, a hero of the people, passed through Paris.'],
      ['해설', 'It soon turned into an uprising. Students and workers built barricades with carts and furniture.'],
      ['해설', 'In front of the Corinthe wine shop on the Rue de la Chanvrerie stood the student leader Enjolras.'],
      ['앙졸라', 'We may fall today. But the people of tomorrow will be freer.'],
      ['해설', 'Gavroche, a homeless street boy, ran around among the flying bullets.'],
      ['가브로슈', 'That tall man looks suspicious. He smells like a police spy!'],
      ['해설', 'Gavroche was right. Javert had sneaked in disguised, and now he was tied to a post.'],
      ['자베르', 'Do what you like. I only did my duty.'],
      ['해설', 'Marius, in despair because Cosette was leaving, also came to the barricade.'],
      ['해설', 'A soldier aimed at him, but someone covered the gun with a hand. It was Éponine, dressed as a boy.'],
      ['해설', 'The bullet went through Éponine. She leaned against Marius’s knees, breathing hard.'],
      ['에포닌', 'I hid Cosette’s letter. I’m sorry. But I’m glad I can die next to you.'],
      ['해설', 'Éponine died there. Marius read the letter and wrote a farewell reply.'],
      ['마리우스', 'Gavroche, take this letter to the Rue de l’Homme-Armé. Deliver it in the morning.'],
      ['해설', 'At that moment, Valjean was reading Cosette’s letter, reflected backward in a mirror.'],
      ['해설', 'He learned that Cosette loved someone, and he suffered for a long time.'],
      ['해설', 'Then Gavroche arrived with Marius’s letter. Valjean put on a guard’s uniform and went out.'],
      ['해설', 'At the barricade, Valjean helped quietly and saved those who fell.'],
      ['장발장', 'Let me take care of that spy. That is the only reward I ask.'],
      ['해설', 'Valjean led Javert into an alley and cut the ropes.'],
      ['장발장', 'You are free. I live at number seven, Rue de l’Homme-Armé.'],
      ['자베르', 'Be careful. You would do better to kill me.'],
      ['해설', 'Valjean fired his gun into the air. Everyone thought the spy had been shot.'],
      ['해설', 'When bullets ran low, Gavroche went out singing to collect cartridges from fallen soldiers.'],
      ['가브로슈', 'A few bullets don’t scare me at all!'],
      ['해설', 'But one shot hit him. His small body fell on the street and did not rise again.'],
      ['해설', 'Morning came. The army brought cannons and got ready for the final attack.'],
      ['해설', 'The June Rebellion of 1832 was crushed two days later, on June 6.'],
    ],
  },

  'lm-09': {
    title: 'Les Misérables, Part 9',
    names: { 해설: 'Narrator', 앙졸라: 'Enjolras', 장발장: 'Jean Valjean', 테나르디에: 'Thénardier', 자베르: 'Javert' },
    outro: [
      'What could Javert not accept in the end: Valjean, or the doubt inside himself?',
      'How might the dark, wet sewer stand for Valjean’s whole life?',
      'When following the rules and saving a person clash, how would you decide?',
    ],
    lines: [
      ['해설', 'Last time, Valjean set Javert free at the barricade, and Gavroche was killed.'],
      ['해설', 'The army’s final attack began. Cannonballs broke the barricade apart.'],
      ['앙졸라', 'Long live the Republic! Aim at me.'],
      ['해설', 'Enjolras stood firm to the end and was shot. All the young men at the barricade fell.'],
      ['해설', 'In the chaos, Valjean lifted Marius, who was shot and unconscious, onto his back.'],
      ['해설', 'Soldiers were everywhere. He lifted an iron grate in the street and went underground.'],
      ['해설', 'It was the sewer of Paris. In the dark and the stink, he followed the flowing water.'],
      ['장발장', 'Hold on, young man. Cosette is waiting for you.'],
      ['해설', 'In one place, the floor was deep mud. He sank to his chest, then to his chin.'],
      ['해설', 'He held Marius above his head and kept going. At last, his feet touched solid stone.'],
      ['해설', 'Hours later, he reached an exit by the river. But the iron gate was locked.'],
      ['해설', 'Then a man came out of the dark. It was Thénardier, hiding from the police.'],
      ['테나르디에', 'You killed someone and came to dump the body? I have the key. Let’s split the money.'],
      ['해설', 'Valjean’s face was covered in mud. Thénardier did not recognize him.'],
      ['해설', 'Thénardier took the money. Secretly, he also tore a piece from Marius’s coat.'],
      ['해설', 'The gate opened. But another man was waiting on the riverbank. It was Javert.'],
      ['자베르', 'Jean Valjean, this time I am arresting you.'],
      ['장발장', 'Very well. But first let me take this young man to his grandfather’s house.'],
      ['해설', 'Javert was silent for a moment. Then he called a carriage.'],
      ['해설', 'After they left Marius at Gillenormand’s house, Valjean asked to stop at home to say goodbye.'],
      ['해설', 'At the Rue de l’Homme-Armé, Javert said he would wait. But when Valjean looked out, Javert was gone.'],
      ['해설', 'Javert stood alone on a bridge over the Seine.'],
      ['자베르', 'A convict saved my life, and I let that convict go. I have betrayed the law.'],
      ['자베르', 'But if that man is right, then what have I believed in all my life?'],
      ['해설', 'He went back to the police office and left a short report on how to improve the service.'],
      ['해설', 'Then he returned to the river and threw himself into the dark water. That was the end of Javert.'],
      ['해설', 'At the same time, at Gillenormand’s house, the doctor said Marius was breathing again.'],
      ['해설', 'Marius had no memory of who had saved him.'],
      ['해설', 'In this novel, Hugo wrote several whole chapters about the history of the Paris sewers.'],
    ],
  },

  'lm-10': {
    title: 'Les Misérables, Part 10',
    names: { 해설: 'Narrator', 마리우스: 'Marius', 코제트: 'Cosette', 장발장: 'Jean Valjean', 테나르디에: 'Thénardier' },
    outro: [
      'How is the humble Valjean at the end the same as, and different from, the hungry convict in Part 1?',
      'What does it mean that the candlesticks from the beginning appear again in the last scene?',
      'Thinking of our society today, why do you think Hugo named his novel The Miserable Ones?',
    ],
    lines: [
      ['해설', 'Last time, Valjean saved Marius through the sewer, and Javert threw himself into the Seine.'],
      ['해설', 'Marius was sick for months before he got up again. His grandfather welcomed him with joy.'],
      ['해설', 'He was allowed to marry Cosette. Valjean gave almost all his money to Cosette.'],
      ['해설', 'In February 1833, they were married. Valjean said he had hurt his hand, so he did not sign.'],
      ['마리우스', 'Cosette, now only happiness lies ahead of us.'],
      ['해설', 'The day after the wedding, Valjean came to see Marius alone.'],
      ['장발장', 'I was a convict at Toulon. My name is Jean Valjean.'],
      ['장발장', 'To stay near Cosette while hiding this would be another kind of stealing.'],
      ['해설', 'Marius was shocked and afraid. He grew cold to Valjean and slowly pushed him away.'],
      ['해설', 'Valjean came to see Cosette every day, then less often, and finally not at all.'],
      ['해설', 'Alone in his empty room, he looked at the little black dress Cosette once wore, and he faded away.'],
      ['해설', 'One day, a man came to see Marius. It was Thénardier, using a different name.'],
      ['테나르디에', 'I’ve come to sell you a secret about your father-in-law. He is a murderer.'],
      ['테나르디에', 'I saw him carry a dead body through the sewer. Here is a piece of the dead man’s coat.'],
      ['해설', 'Marius held the cloth against his own coat. It fit the torn place exactly.'],
      ['마리우스', 'That body was me! He was the one who carried me out!'],
      ['해설', 'Marius threw money at Thénardier and sent him away. Thénardier took it and left for America.'],
      ['해설', 'Marius and Cosette jumped into a carriage and hurried to the Rue de l’Homme-Armé.'],
      ['코제트', 'Father! We’re here. Why didn’t you tell us anything all this time?'],
      ['장발장', 'Cosette, you came. Now it is all right. Everything is all right.'],
      ['마리우스', 'Please forgive me. I knew nothing, and I sent you away.'],
      ['해설', 'On the table, the two silver candlesticks from Bishop Myriel were burning.'],
      ['장발장', 'I leave these candlesticks to Cosette. The man who gave them to me is watching from heaven.'],
      ['장발장', 'Cosette, your mother’s name was Fantine. Love her. She suffered so much.'],
      ['장발장', 'Love each other always. There is almost nothing more precious in this world.'],
      ['해설', 'Holding their hands, Valjean quietly closed his eyes. The candlelight shone on his face.'],
      ['해설', 'He was buried in a Paris cemetery, under a stone with no name.'],
      ['해설', 'The long road of a man that began with a loaf of bread ended beside the people he loved.'],
      ['해설', 'When Hugo died in 1885, France gave him a state funeral, and he was laid to rest in the Panthéon.'],
    ],
  },
};
