// 청소년 영어 원고 (중학생 이상). 키 = stories/teen-f.js 의 이야기 id.
// 한국 고전 산문(퍼블릭 도메인)을 한국어 각색의 흐름대로 쉬운 영어로 새로 씀. 고유 낱말은 로마자로 쓰고 짧게 풀이.
export default {
  'tf-chunhyang-1': {
    title: 'The Tale of Chunhyang, Part 1',
    names: { 해설: 'Narrator', 몽룡: 'Yi Mong-ryong', 방자: 'Bangja', 춘향: 'Chunhyang', 향단: 'Hyangdan', 월매: 'Wolmae' },
    outro: [
      'What walls of Joseon society stood in front of the promise between Mong-ryong and Chunhyang, who came from different classes?',
      'Chunhyang answered with the wild goose and the butterfly. What effect does this indirect way of speaking have?',
      'If family or other people made it hard to keep a precious promise, what would you do?',
    ],
    lines: [
      ['해설', 'In the time of King Sukjong of Joseon, Yi Mong-ryong was the sixteen-year-old son of the magistrate of Namwon.'],
      ['해설', 'He was a gifted writer. On Dano, the spring festival of the fifth month, he grew tired of his books and called his servant Bangja.'],
      ['몽룡', 'Bangja, where is the best view in this town? I want some fresh air.'],
      ['방자', 'Why does a young master who should be studying want a view? But if I must choose, Gwanghallu Pavilion is the best.'],
      ['해설', 'From Gwanghallu, Mong-ryong saw a young woman swinging high among the willow trees.'],
      ['몽룡', 'Who is that, swinging as if she were flying through the clouds?'],
      ['방자', 'That is Chunhyang, daughter of Wolmae, a retired gisaeng, or court entertainer. She refuses that life and studies books and sewing.'],
      ['몽룡', 'I want to meet her. Go and bring her here.'],
      ['해설', 'Bangja delivered the message, but Chunhyang did not come right away.'],
      ['춘향', 'Tell him only this. The wild goose follows the sea, and the butterfly follows the flower.'],
      ['향단', 'Miss, that means whoever wants to see you should come to you himself, right?'],
      ['해설', 'Mong-ryong understood. That night, with Bangja leading the way, he went to Chunhyang’s house.'],
      ['월매', 'Why has the magistrate’s son come to this humble house?'],
      ['몽룡', 'I saw Chunhyang today and made up my mind. This is no game. Please let me marry her.'],
      ['월매', 'You are a yangban, a nobleman. If this is a passing whim, what will become of my daughter when you leave?'],
      ['몽룡', 'Then I will write my vow down. Heaven and earth are my witnesses.'],
      ['해설', 'Mong-ryong wrote a promise never to abandon her and handed it to Wolmae.'],
      ['춘향', 'If your heart does not change, I will keep this promise all my life too.'],
      ['해설', 'And so, before Wolmae, the two promised to become husband and wife.'],
      ['해설', 'From that day, Mong-ryong used his studies as an excuse and went to Chunhyang’s house every evening.'],
      ['향단', 'Just hearing his footsteps makes your face light up, Miss.'],
      ['춘향', 'Stop talking nonsense and bring us some tea.'],
      ['해설', 'But their joy did not last. Mong-ryong’s father was given a new post in Hanyang, the capital.'],
      ['방자', 'Young master, it’s terrible! The magistrate is going to Hanyang, and the whole family is leaving.'],
      ['몽룡', 'If I say I married a gisaeng’s daughter, my path to the state exam will close. My family will throw me out.'],
      ['해설', 'Having no choice, Mong-ryong went to tell Chunhyang that he could not take her with him.'],
      ['춘향', 'You cannot take me? Then whom am I supposed to wait for here in Namwon?'],
      ['몽룡', 'I will surely pass the state exam and come back for you. Please wait until then.'],
      ['해설', 'Holding back her tears, Chunhyang could not let go of his sleeve. The day of parting was coming.'],
      ['해설', 'The Tale of Chunhyang grew out of the pansori song Chunhyangga into a novel. Its author is unknown.'],
    ],
  },

  'tf-chunhyang-2': {
    title: 'The Tale of Chunhyang, Part 2',
    names: { 해설: 'Narrator', 춘향: 'Chunhyang', 몽룡: 'Yi Mong-ryong', 월매: 'Wolmae', 향단: 'Hyangdan', 변사또: 'Magistrate Byeon', 사령: 'Officer', 봉사: 'Blind Man' },
    outro: [
      'When Chunhyang refused Magistrate Byeon’s order, was she protecting her love, or standing against unjust power?',
      'In the Song of Ten Strokes, each line starts with the number of the blow. What effect does this have as pansori lyrics?',
      'When powerful people use their position to make unfair demands on the weak, how can our society stop them?',
    ],
    lines: [
      ['해설', 'On the day Mong-ryong left, Chunhyang followed him to Ori Pavilion to say a last goodbye.'],
      ['춘향', 'Please take this jade ring. Think of it as my heart and keep it with you.'],
      ['몽룡', 'I will give you this mirror. As a mirror’s shine never changes, my heart will never change.'],
      ['해설', 'When his horse disappeared over the hill, Chunhyang sank to the ground and cried for a long time.'],
      ['월매', 'My child, stop crying and come inside. If you trust only the heart of a man who left, you will be the one hurt.'],
      ['춘향', 'Mother, he will surely come back. I will wait.'],
      ['해설', 'A few months later, a new magistrate, Byeon Hak-do, came to Namwon. He cared more for pleasure than for his duties.'],
      ['변사또', 'They say a beauty named Chunhyang lives here. Why was she not at the roll call of the gisaeng, the court entertainers?'],
      ['사령', 'Chunhyang is not on the gisaeng list, sir. And she is already promised to the former magistrate’s son.'],
      ['변사또', 'A gisaeng’s daughter is a gisaeng. What promise? Bring her here at once.'],
      ['해설', 'When Chunhyang was dragged to the office, Byeon ordered her to serve him as his companion.'],
      ['춘향', 'A loyal subject does not serve two kings, and a faithful wife does not serve two husbands. I cannot obey.'],
      ['변사또', 'A lowborn girl dares to talk of loyalty? You will be punished for defying an official.'],
      ['춘향', 'Did you not come here to keep the law of the land? Is it lawful to take another man’s wife?'],
      ['해설', 'Furious, Byeon had her beaten. Still, Chunhyang did not bow her head.'],
      ['해설', 'This part is called the Song of Ten Strokes. With each blow, Chunhyang began a line with that number and held to her heart.'],
      ['춘향', 'One heart, one true heart. Do you think a beating will change it?'],
      ['해설', 'People watching clicked their tongues and looked away. Chunhyang was locked in prison with a heavy wooden collar on her neck.'],
      ['월매', 'Oh, my poor daughter! That man in Seoul has not sent a single letter, and you suffer all alone.'],
      ['향단', 'Miss, please eat a little rice porridge. You must keep up your strength.'],
      ['춘향', 'I am all right, Hyangdan. I only worry how I will look to him when he comes.'],
      ['해설', 'One night, Chunhyang had a strange dream. A mirror broke, and a scarecrow hung above a door.'],
      ['해설', 'Thinking it was a bad sign, she asked a blind fortune-teller passing the prison to explain the dream.'],
      ['봉사', 'A breaking mirror makes a loud sound. So something good will happen that the whole town will hear about.'],
      ['봉사', 'A scarecrow above a door means everyone will look up to you. Happy news will come soon.'],
      ['해설', 'But Byeon swore he would punish Chunhyang harshly once his birthday feast was over.'],
      ['변사또', 'After the feast, I will drag out that stubborn girl and make an example of her.'],
      ['해설', 'Through the prison bars, Chunhyang gazed for a long time at the northern sky where Mong-ryong had gone.'],
      ['춘향', 'Young master, if I could see you just once more while I am alive, I would have no regrets.'],
      ['해설', 'There are many versions of The Tale of Chunhyang. The best known is the Wanpan edition, Yeollyeo Chunhyang Sujeolga.'],
    ],
  },

  'tf-chunhyang-3': {
    title: 'The Tale of Chunhyang, Part 3',
    names: { 해설: 'Narrator', 몽룡: 'Yi Mong-ryong', 춘향: 'Chunhyang', 월매: 'Wolmae', 향단: 'Hyangdan', 변사또: 'Magistrate Byeon', 농부: 'Farmer', 운봉: 'Magistrate of Unbong' },
    outro: [
      'What behavior of local officials does the poem Mong-ryong wrote at the feast expose?',
      'Mong-ryong hides who he is by dressing as a beggar. How does this make the story more tense and more satisfying?',
      'Who in our society today plays the role of the secret royal inspector, watching over those in power?',
    ],
    lines: [
      ['해설', 'In Hanyang, Mong-ryong studied day and night. At last he passed the state exam with the highest score.'],
      ['해설', 'The king made him amhaeng-eosa, a secret royal inspector, for Jeolla Province. His job was to judge officials in disguise.'],
      ['해설', 'Mong-ryong put on ragged clothes and a crushed hat and entered Namwon dressed as a beggar.'],
      ['해설', 'Farmers planting rice in the fields stopped singing and began to talk about the new magistrate.'],
      ['농부', 'This magistrate doesn’t care how people live. He only works hard at feasts and taxes.'],
      ['몽룡', 'And what became of the woman named Chunhyang?'],
      ['농부', 'She refused him and was thrown in prison. That nobleman in Seoul hasn’t even sent word. What a rotten man.'],
      ['해설', 'Mong-ryong’s face burned, but he said nothing and went to Chunhyang’s house.'],
      ['해설', 'In the back yard, Wolmae set out a bowl of fresh water. She was praying for her son-in-law in Seoul.'],
      ['월매', 'Oh, what a sight! Instead of an official, you came back a beggar?'],
      ['향단', 'Madam, he has come back all the same. We must tell Miss Chunhyang quickly.'],
      ['해설', 'That night Mong-ryong went to the prison. Chunhyang saw her husband in rags, yet she did not blame him.'],
      ['춘향', 'I have seen you again while I am alive. That is enough. Mother, if I die, please make him some clothes.'],
      ['몽룡', 'Don’t cry. Only heaven knows what tomorrow will bring.'],
      ['해설', 'The next day was Byeon’s birthday feast. Officials from nearby towns gathered, played music, and passed the wine.'],
      ['몽룡', 'I am just a traveler passing by. Let me have a cup of wine at this fine feast.'],
      ['변사또', 'A beggar barging into a nobleman’s feast? If you can write poetry, then write us a poem.'],
      ['해설', 'Mong-ryong took a brush and wrote a poem in one breath. This was its meaning.'],
      ['해설', 'The fine wine in golden cups is the blood of a thousand people. The rich food on jade plates is the fat of ten thousand.'],
      ['해설', 'When candle wax drips, the people’s tears drip too. Where songs ring loud, cries of resentment ring loud too.'],
      ['운봉', 'This poem is no ordinary poem. Something big is about to happen. I will leave first.'],
      ['해설', 'Just then, the inspector’s men burst in, shouting. Make way, the royal inspector is here!'],
      ['해설', 'The feast turned upside down in an instant. Officials looked for places to hide, and Byeon was seized and forced to kneel.'],
      ['변사또', 'My lord inspector, please spare my life!'],
      ['해설', 'The inspector freed those who had been wrongly imprisoned. Last of all, he called for Chunhyang.'],
      ['몽룡', 'I hear you defied an official to stay faithful. Will you now serve the inspector instead?'],
      ['춘향', 'Why is every official who comes here the same? Just kill me now.'],
      ['몽룡', 'Raise your head and look at me. I still have the jade ring you gave me.'],
      ['해설', 'Chunhyang raised her head and almost stopped breathing. The beggar at the prison last night was the royal inspector.'],
      ['춘향', 'Young master! Is it really you?'],
      ['해설', 'Byeon was thrown out of office. Chunhyang went to Hanyang with Mong-ryong and received a royal title for her faithfulness.'],
      ['해설', 'Chunhyangga is one of the five pansori works that have been handed down and sung to this day.'],
    ],
  },

  'tf-guunmong-1': {
    title: 'The Cloud Dream of the Nine, Part 1',
    names: { 해설: 'Narrator', 대사: 'Master Yukgwan', 성진: 'Seongjin', 용왕: 'Dragon King', 선녀: 'Fairy', 염라: 'King Yeomra' },
    outro: [
      'Seongjin envied worldly wealth and fame more than life in the mountains. Can we simply call that wrong?',
      'What mood do magical events, like peach blossoms turning into pearls, add to the story?',
      'When someone else’s life looks better than yours, how is it best to handle that feeling?',
    ],
    lines: [
      ['해설', 'On Lotus Peak of Mount Heng in southern China, a great monk named Master Yukgwan taught the Buddha’s way.'],
      ['해설', 'Of all his many disciples, the one he loved most was Seongjin, a young monk of about twenty.'],
      ['대사', 'Seongjin, go and give my greetings to the Dragon King of Lake Dongting.'],
      ['해설', 'When Seongjin reached the palace under the water, the Dragon King welcomed him warmly and held a feast.'],
      ['용왕', 'You have come a long way. Please accept this cup of wine.'],
      ['성진', 'Wine clouds the mind, so Buddhist monks do not drink.'],
      ['용왕', 'This wine does not confuse anyone. It is a sign of my respect, so do not refuse it.'],
      ['해설', 'Seongjin could not refuse in the end. He drank three cups and left the palace with a flushed face.'],
      ['해설', 'Meanwhile, Lady Wei’s eight fairies had visited the Master. On their way home, they rested on a stone bridge.'],
      ['성진', 'I am a disciple of Master Yukgwan of Lotus Peak. The path is narrow. Would you please step aside?'],
      ['선녀', 'We sat on this bridge first. Why don’t you take another path, monk?'],
      ['선녀', 'They say a man of the Way can walk on water. Must you really cross this bridge?'],
      ['해설', 'Seongjin smiled, broke off a branch of peach blossoms, and threw it before the fairies.'],
      ['해설', 'When the blossoms touched the ground, they turned into eight shining pearls. The fairies each picked one up and left.'],
      ['해설', 'Back at the temple, Seongjin could not sleep that night.'],
      ['성진', 'Some men study, rise to high office, and become famous.'],
      ['성진', 'But I must grow old in these lonely mountains with one bowl of rice and one robe.'],
      ['해설', 'The fairies’ faces kept coming back to him. Even when he chanted prayers, he could not calm his mind.'],
      ['대사', 'Seongjin, your heart has already left the mountain. You drank wine, talked with fairies, and longed for worldly riches.'],
      ['성진', 'I was wrong. Please forgive me just this once.'],
      ['대사', 'I send you away because you want to go. Go wherever you wish.'],
      ['해설', 'The Master called a messenger from the underworld to take Seongjin to King Yeomra, the judge of the dead.'],
      ['염라', 'Why has Seongjin of Lotus Peak come here? If it is the Master’s will, I must send him to the human world.'],
      ['해설', 'Soon the eight fairies were also brought before King Yeomra for the same fault.'],
      ['염라', 'You too will all be born into the human world. Each of you, follow your own fate.'],
      ['해설', 'A great wind rose, and the nine were scattered across the world.'],
      ['해설', 'When Seongjin came to his senses, he was a crying newborn baby in the house of Master Yang in Huainan.'],
      ['해설', 'Master Yang and his wife treasured this son born to them late in life. They named him Soyu.'],
      ['해설', 'The Cloud Dream of the Nine was written by Kim Man-jung under King Sukjong. It is the best-known Korean novel about life seen through a dream.'],
    ],
  },

  'tf-guunmong-2': {
    title: 'The Cloud Dream of the Nine, Part 2',
    names: { 해설: 'Narrator', 처사: 'Master Yang', 양소유: 'Yang Soyu', 채봉: 'Jin Chaebong', 경패: 'Jeong Gyeongpae', 태후: 'Empress Dowager' },
    outro: [
      'Yang Soyu’s high office, wealth, and many relationships fulfill which of Seongjin’s dreams?',
      'Soyu disguises himself as a female Taoist priest to meet Gyeongpae. How does this scene reveal his character?',
      'Soyu chose to keep faith with the Jeong family over the Empress Dowager’s order. Have you ever struggled between a promise and your own gain?',
    ],
    lines: [
      ['해설', 'From childhood, Yang Soyu was handsome and wrote brilliantly. People called him a child genius.'],
      ['해설', 'When Soyu was ten, his father, Master Yang, left for the mountains and never returned. He seemed to have been an immortal.'],
      ['처사', 'I do not truly belong to this world, so I must leave. Take good care of your mother.'],
      ['해설', 'At about fifteen, Soyu set off alone for the capital to take the state exam.'],
      ['해설', 'Passing through Huayin, he saw a pavilion hung with willows, and he recited a poem about the willows.'],
      ['해설', 'Jin Chaebong, a young woman in the pavilion, heard the poem. She wrote a reply and sent it through her nurse.'],
      ['채봉', 'Your poem tells me what kind of man you are. My father is far away, so I ask you myself to marry me.'],
      ['양소유', 'I will treasure this bond. I will come back tomorrow, and we will settle our promise.'],
      ['해설', 'But that night a rebellion broke out, and Soyu fled into the mountains. When he returned, Chaebong’s family was gone.'],
      ['해설', 'Years later, in the capital, Soyu heard that Jeong Gyeongpae, daughter of Minister Jeong, was wise and knew music well.'],
      ['양소유', 'How can I give my whole life to someone without seeing her face even once? I must think of a trick.'],
      ['해설', 'Soyu dressed as a female Taoist priest, carried a geomungo, a Korean zither, into Minister Jeong’s house, and played.'],
      ['해설', 'After many tunes, Soyu played one last song about a phoenix searching for its mate.'],
      ['경패', 'This is a song about a man seeking a wife. I will not listen any longer.'],
      ['해설', 'Gyeongpae left the room. When she realized she had been tricked, she felt deeply ashamed.'],
      ['해설', 'That year, Soyu passed the state exam with the highest score, and Minister Jeong chose him as his son-in-law.'],
      ['경패', 'Marry a man who tricked his way into seeing my face? Someday I will pay him back for this shame.'],
      ['해설', 'After that, whenever war broke out, Soyu went and won great victories. He rose to high office while still young.'],
      ['해설', 'The Empress Dowager noticed him and wanted him to marry her daughter, Princess Nanyang.'],
      ['태후', 'I have chosen you as the princess’s husband. Break off your engagement with the Jeong family.'],
      ['양소유', 'I have already promised to marry into the Jeong family. I cannot break my word.'],
      ['해설', 'The Empress Dowager was furious. But Princess Nanyang met Gyeongpae herself and admired her character.'],
      ['해설', 'In the end, the Empress Dowager adopted Gyeongpae, made her Princess Yeongyang, and married both princesses to Soyu.'],
      ['태후', 'Let there be no higher or lower between the two princesses. Let them live like sisters.'],
      ['해설', 'Soyu met Chaebong again, now a palace maid. One by one, he also met other women along his way.'],
      ['해설', 'So Soyu came to live in one house with eight women, two wives and six concubines.'],
      ['양소유', 'Heaven has blessed me so greatly. What more could anyone want in one lifetime?'],
      ['해설', 'The eight women lived like sisters without jealousy. Soyu became prime minister and enjoyed great wealth.'],
      ['해설', 'Some readers may have guessed already. These eight women were the eight fairies from the stone bridge.'],
      ['해설', 'The title Guunmong means the cloud dream of nine people, Seongjin and the eight fairies.'],
    ],
  },

  'tf-guunmong-3': {
    title: 'The Cloud Dream of the Nine, Part 3',
    names: { 해설: 'Narrator', 양소유: 'Yang Soyu', 경패: 'Jeong Gyeongpae', 난양: 'Princess Nanyang', 노승: 'Old Monk', 선녀: 'Fairy' },
    outro: [
      'Why did Yang Soyu feel emptiness after enjoying every kind of wealth and glory?',
      'The story moves from reality into a dream and back again. How does this structure reveal its theme?',
      'Like Seongjin waking from his dream, what would you need to achieve to feel truly satisfied?',
    ],
    lines: [
      ['해설', 'Years passed. Yang Soyu retired from office and lived quietly with the eight women in a palace in the mountains.'],
      ['해설', 'One autumn, on his birthday, Soyu climbed a high terrace with the eight women and looked out in all directions.'],
      ['해설', 'In the distance, the ruins and tombs of ancient emperors lay covered in weeds under the setting sun.'],
      ['양소유', 'Even the heroes who once ruled the world have become dust in those tombs.'],
      ['양소유', 'A hundred years from now, this place where we enjoy ourselves will be an empty field. Only woodcutters and shepherds will pass by.'],
      ['해설', 'Soyu took out a bamboo flute and played a sad tune. The eight women fell silent, their eyes filling with tears.'],
      ['경패', 'My lord, you have gained wealth and fame. Why are you so sad today?'],
      ['양소유', 'All the pleasures of the world are empty. I want to leave now and seek the Buddha’s way.'],
      ['난양', 'We will all follow you.'],
      ['해설', 'Just then, a strange old monk with a walking stick climbed up to the terrace. He had long eyebrows and clear eyes.'],
      ['노승', 'My lord, do you not recognize an old friend?'],
      ['양소유', 'You seem familiar, but I cannot remember where we met.'],
      ['노승', 'You have forgotten someone you lived with for years. Then let me wake you from your dream.'],
      ['해설', 'The monk tapped the stone railing a few times with his stick. White clouds rose on all sides and hid everything.'],
      ['양소유', 'Master, why do you play tricks on me instead of leading me on the right path?'],
      ['해설', 'When the clouds cleared, the monk, the eight women, and the splendid palace were all gone.'],
      ['해설', 'He was sitting on a cushion in a small hermitage. His head was shaved, and prayer beads hung around his neck.'],
      ['해설', 'Yang Soyu was once again Seongjin, the young monk of Lotus Peak. His whole life had been one night’s dream.'],
      ['해설', 'Seongjin hurried to Master Yukgwan and bowed low, begging forgiveness. The monk on the terrace had been the Master.'],
      ['노승', 'You went into the world full of desire, and you came back when the desire was spent. What have I to do with it?'],
      ['노승', 'You split the dream and the world in two. Did Zhuangzi dream he was a butterfly, or did a butterfly dream it was Zhuangzi?'],
      ['노승', 'If you cannot tell which is the dream and which is real, you have not yet woken up.'],
      ['해설', 'Then the eight fairies came and bowed before the Master. They too had woken from the same dream.'],
      ['선녀', 'We also failed to control our hearts and did wrong. Now we will follow your teaching.'],
      ['해설', 'The fairies shaved their heads and became disciples, and the Master opened the Diamond Sutra to teach them all.'],
      ['해설', 'Soon after, the Master gave Seongjin his robe, his bowl, and his staff, and left for the west.'],
      ['해설', 'Seongjin became the great master of Lotus Peak. It is said that in the end, all nine reached paradise.'],
      ['해설', 'Kim Man-jung was a scholar-official under King Sukjong who also wrote Lady Sa’s Journey South. He is said to have written this novel in exile.'],
    ],
  },

  'tf-yangban': {
    title: 'The Tale of a Yangban',
    names: { 해설: 'Narrator', 양반: 'Yangban', 아내: 'Wife', 부자: 'Rich Man', 군수: 'Magistrate' },
    outro: [
      'Through a story about buying and selling the yangban title, what contradiction of the noble class did Park Ji-won reveal?',
      'The deed is read twice. What side of the yangban does each version show, and what laughter does the repetition create?',
      'If people still buy status or qualifications with money today, what problems would that cause in society?',
    ],
    lines: [
      ['해설', 'In Jeongseon, Gangwon Province, there lived a kind yangban, a nobleman, who loved to read.'],
      ['해설', 'He was so respected that every new magistrate visited his house first to greet him.'],
      ['해설', 'But he was poor, so every year he borrowed grain from the government. His debt grew to a thousand sacks.'],
      ['해설', 'A provincial governor, checking the records on a tour, found out and grew very angry.'],
      ['해설', 'He ordered the yangban who had wasted the state’s grain to be arrested.'],
      ['해설', 'The local magistrate felt sorry for the yangban, but there was no way to repay the debt.'],
      ['양반', 'Oh, there is no way to pay. What am I to do?'],
      ['아내', 'You have read books all your life, and they are no use for paying back the government grain.'],
      ['아내', 'Yangban, yangban, you always say. But a yangban is not worth a single penny.'],
      ['해설', 'A rich man in the village heard the news and gathered his family to talk.'],
      ['부자', 'A yangban is always honored, however poor he is. We are always looked down on, however rich we are.'],
      ['부자', 'We cannot even ride a horse freely. We must bow low whenever we see a yangban. What shame!'],
      ['부자', 'That yangban is in trouble because he cannot pay his debt. Let us buy his rank.'],
      ['해설', 'The rich man offered to pay the debt. Delighted, the yangban agreed to hand over his rank.'],
      ['해설', 'The rich man soon brought a thousand sacks of grain to the government office.'],
      ['해설', 'The surprised magistrate visited the yangban. He found him lying face down in the road, in a felt hat and short clothes.'],
      ['양반', 'This humble man has already sold his rank. That rich man is the yangban now.'],
      ['군수', 'We must make a deed to settle this properly. Call all the townspeople together.'],
      ['군수', 'One who becomes a yangban must rise at dawn, kneel properly, and recite books aloud.'],
      ['군수', 'Bear hunger. Do not warm your hands at the fire when cold. Do not take off your socks when hot.'],
      ['군수', 'Do not touch money or ask the price of rice. Do not throw dishes even when angry.'],
      ['부자', 'Is that all a yangban is? I heard they live like immortals. This is a terrible loss for me.'],
      ['부자', 'Please change the deed so I gain more from it.'],
      ['해설', 'The magistrate rewrote the deed and read it again. This time it listed what a yangban gains.'],
      ['군수', 'A yangban neither farms nor trades. With a little study, he can pass the state exam and get an office.'],
      ['군수', 'He may plow his own field first with his neighbor’s ox and make villagers weed his field. Who would dare refuse?'],
      ['군수', 'Those who disobey may have lye poured in their noses and their topknots shaken, yet they dare not complain.'],
      ['부자', 'Stop, stop! Do you mean to make me a thief, sir?'],
      ['해설', 'The rich man shook his head and ran away. For the rest of his life, he never spoke the word yangban again.'],
      ['해설', 'The Tale of a Yangban is a story in classical Chinese by Park Ji-won, found in his collection Banggyeonggak Oejeon.'],
    ],
  },

  'tf-hojil': {
    title: 'The Tiger’s Rebuke',
    names: { 해설: 'Narrator', 범: 'Tiger', 창귀: 'Changgwi', 북곽: 'Master Bukgwak', 아들: 'Son', 농부: 'Farmer' },
    outro: [
      'Why did the writer choose a tiger to scold the scholar and humankind?',
      'Covered in dung, Master Bukgwak still speaks in fine words. How does this make the satire stronger?',
      'Can we find people in our society today whose words sound right but whose actions are different?',
    ],
    lines: [
      ['해설', 'The tiger was wise, swift, and brave. No beast in the world could match it. One evening, the tiger was very hungry.'],
      ['범', 'Night has fallen. What should I eat? You choose for me.'],
      ['해설', 'By the tiger’s side were changgwi, the ghosts of people the tiger had eaten, who now ran its errands.'],
      ['창귀', 'How about a doctor? He eats all kinds of herbs, so his flesh smells good.'],
      ['범', 'Doctors test medicines they barely understand on people and kill some every year. Their flesh is full of grudges.'],
      ['창귀', 'Then how about a shaman?'],
      ['범', 'Shamans cheat people out of their money in the name of spirits. Their flesh is not fit to eat either.'],
      ['창귀', 'Then a scholar would be best. He is kind and righteous and full of the classics. He must taste clean and sweet.'],
      ['해설', 'The tiger licked its lips, but it did not look pleased.'],
      ['해설', 'Meanwhile, in a town in the land of Zheng, lived a famous scholar, Master Bukgwak. He had edited or written over twenty thousand books.'],
      ['해설', 'In the same town lived a widow, Dongnija, praised for staying faithful to her late husband. Yet her five sons all had different family names.'],
      ['해설', 'One night, Master Bukgwak visited Dongnija’s house and was politely exchanging poems with her.'],
      ['아들', 'The rules say no man enters a widow’s house. The wise Master Bukgwak would never do such a thing.'],
      ['아들', 'They say a fox lives in the broken part of the town wall. It must be a fox disguised as the Master!'],
      ['해설', 'The five sons grabbed clubs and burst into the room.'],
      ['해설', 'Terrified that someone would recognize him, Master Bukgwak hopped away like a dancing ghost.'],
      ['해설', 'Then he fell into a manure pit in the field. He barely crawled out, covered in dung from head to toe.'],
      ['해설', 'When he raised his head, the tiger was standing right in front of him, blocking the way.'],
      ['범', 'Ugh! They call you a scholar, but you stink terribly.'],
      ['북곽', 'Your virtue is perfect, great Tiger. A humble scholar like me only wishes to follow your teaching.'],
      ['범', 'Don’t come near me. Usually you curse me as cruel, but now that you are in danger, you flatter me.'],
      ['범', 'A tiger stops hunting when it is full. But people keep robbing each other even when they are full.'],
      ['범', 'Haven’t far more people been killed by other people than eaten by tigers?'],
      ['범', 'You talk of goodness and justice, then secretly satisfy your greed. How dare you call me cruel!'],
      ['해설', 'Master Bukgwak kept his head bowed and did not move. When he finally looked up, the tiger was gone.'],
      ['해설', 'At dawn, a farmer coming out to weed his field found this strange and asked him a question.'],
      ['농부', 'Sir, what are you bowing to out in the field so early in the morning?'],
      ['북곽', 'As the saying goes, though the sky is high, one must bow. Though the earth is solid, one must walk with care.'],
      ['해설', 'In this scholar keeping up appearances while covered in dung, we see the writer’s sharp laughter.'],
      ['해설', 'The Tiger’s Rebuke is a story in classical Chinese that Park Ji-won recorded in his travel diary, Yeolha Ilgi.'],
    ],
  },

  'tf-yedeok': {
    title: 'The Tale of Master Yedeok',
    names: { 해설: 'Narrator', 선귤자: 'Seongyulja', 자목: 'Jamok' },
    outro: [
      'Why did Park Ji-won honor Eom Haengsu, a man who carried away night soil, with the title Master?',
      'The story moves through questions and answers between a teacher and his student. How does this help deliver the writer’s ideas?',
      'How does our society treat people who quietly do the jobs that others avoid?',
    ],
    lines: [
      ['해설', 'Seongyulja had a friend he called Master Yedeok. He was Eom Haengsu, who lived east of Jongbon Pagoda.'],
      ['해설', 'Every day Eom Haengsu went around the village, cleaned out the toilets, and carried the waste away as fertilizer. That was how he lived.'],
      ['해설', 'Seongyulja’s student Jamok did not like his teacher honoring such a man as a friend.'],
      ['자목', 'Teacher, you once said a friend is a wife who lives apart and a brother not of your blood.'],
      ['자목', 'Yet you turn away famous scholars who want your friendship. Instead, you call a village laborer Master and make him your friend.'],
      ['자목', 'I am ashamed. I cannot stay as your student any longer.'],
      ['선귤자', 'Sit down. Let me tell you the right way to make friends.'],
      ['선귤자', 'Friends made through profit drift apart when the profit is gone. Friends made through flattery do not last.'],
      ['선귤자', 'A true friend is made with the heart, and friendship is built on virtue.'],
      ['해설', 'Seongyulja told him how Eom Haengsu lived.'],
      ['선귤자', 'He gets up before dawn, puts a basket on his back, and goes into the village to clean the toilets.'],
      ['선귤자', 'Even in cold winter he does not rest. He collects human waste, horse dung, and cow dung.'],
      ['선귤자', 'He spreads it on radish fields in Wangsimni, turnip fields in Salgoji, and taro fields in Itaewon. The vegetables grow well.'],
      ['선귤자', 'He earns a good deal of money. Yet he says one bowl of rice in the morning and one at night is enough.'],
      ['자목', 'He earns that much and still does not eat a single piece of meat?'],
      ['선귤자', 'He says that once food goes down the throat, greens and meat fill you the same. Why fuss over taste?'],
      ['선귤자', 'He mends his clothes when they wear out and does not envy others. Praise does not puff him up, and insults do not anger him.'],
      ['선귤자', 'He flatters no one and lives honestly by his own labor. What life could be cleaner than that?'],
      ['자목', 'But isn’t his work dirty and smelly?'],
      ['선귤자', 'His work may look dirty, but his conduct is truly fragrant.'],
      ['선귤자', 'A person’s worth does not lie in his job. He is far cleaner than scholars who bow and scrape for office.'],
      ['선귤자', 'So I dare not call him by his name. I call him Master Yedeok, one who hides virtue in dirt.'],
      ['해설', 'Jamok was silent for a while, then lowered his head.'],
      ['자목', 'Teacher, I judged people only by their looks and their work.'],
      ['선귤자', 'Showing your poverty on your face is shameful. So is showing off when you succeed.'],
      ['선귤자', 'How many scholars could stand before Eom Haengsu without shame? I simply wish to make him my teacher.'],
      ['해설', 'In this way, the life of Eom Haengsu, a nameless laborer, became a biography read for a long time.'],
      ['해설', 'The Tale of Master Yedeok is a story in classical Chinese by Park Ji-won, found in Banggyeonggak Oejeon.'],
    ],
  },

  'tf-isaeng': {
    title: 'Student Yi Peeks Over the Wall',
    names: { 해설: 'Narrator', 이생: 'Yi', 최씨: 'Lady Choe', 이생부: 'Yi’s Father' },
    outro: [
      'A dead wife returns to live with her husband. What does this tell us about love and the wounds left by war?',
      'The two share their feelings by exchanging poems. How does this shape the mood of the story?',
      'How can we remember and comfort people who have lost loved ones to war or disaster?',
    ],
    lines: [
      ['해설', 'Near the end of Goryeo, an eighteen-year-old scholar named Yi lived by Nakta Bridge in Songdo. Every day he went to the national academy.'],
      ['해설', 'On his way, in Seonjuk Village, lived Lady Choe, the daughter of a noble family. She was good at embroidery and poetry.'],
      ['해설', 'One day, Yi peeked over a wall and saw Lady Choe reciting a poem under a flowering tree.'],
      ['해설', 'The gyujang in the Korean title means peeking over a wall. Yi wrote a poem on paper and threw it over the wall.'],
      ['최씨', 'I have read your poem. Do not doubt me. Come back after the sun goes down.'],
      ['해설', 'The two met in secret, shared their feelings, and promised to spend their whole lives together.'],
      ['해설', 'But when Yi’s father found out, he scolded him harshly.'],
      ['이생부', 'I sent you to study, and you peeked over someone’s wall? Go down to our farm in Ulju at once!'],
      ['해설', 'After Yi left and no news came, Lady Choe grew sick with grief and took to her bed.'],
      ['해설', 'When her worried parents asked why, she showed them the poems and told them the truth.'],
      ['최씨', 'If I cannot marry Yi, I will never marry anyone.'],
      ['해설', 'Wanting to save their daughter, her parents sent a matchmaker to Yi’s family to propose marriage.'],
      ['이생부', 'My son is still young and our family is not rich. How could he be a match for your noble daughter?'],
      ['해설', 'But the Choe family asked again and again with great sincerity. At last the two were married.'],
      ['해설', 'Yi passed the state exam and became an official. Their happiness made the neighbors envious.'],
      ['해설', 'Then in the year of sinchuk, the Red Turban bandits invaded, and Songdo fell. People scattered to save their lives.'],
      ['해설', 'Yi fled with his family. But chased by the bandits, he was separated from his wife.'],
      ['해설', 'Lady Choe was captured by the bandits. She refused to give in to the end, and she lost her life there.'],
      ['해설', 'When the war was over, Yi came home. His house had burned down, and he heard only the sound of insects.'],
      ['해설', 'That night, as he sat alone in grief, he heard footsteps far away. His dead wife appeared before him.'],
      ['최씨', 'My husband, it is me. I died refusing to give in to the bandits. But our bond was not over, so I came.'],
      ['이생', 'I know you have left this world. Yet here you are in front of me. Is this a dream, or is it real?'],
      ['최씨', 'In the chaos of war, our parents’ remains were never gathered. Let us go together and lay them to rest.'],
      ['해설', 'The two gathered the scattered remains of both families’ parents and buried them with care. Then they lived together again.'],
      ['해설', 'Yi no longer wanted any office. He spent several years exchanging poems with his wife.'],
      ['최씨', 'The time the underworld allowed me is over. I cannot stay any longer.'],
      ['이생', 'Then I will follow you.'],
      ['최씨', 'You still have a life to live in this world. My remains were never gathered. Please bury them.'],
      ['해설', 'Lady Choe slowly faded and was gone. Yi found her remains and buried them beside her parents.'],
      ['해설', 'Afterward, Yi fell ill from missing his wife, and he died a few months later.'],
      ['해설', 'This is one of five stories in Geumo Sinhwa, a collection in classical Chinese by Kim Si-seup.'],
    ],
  },

  'tf-unyeong-1': {
    title: 'The Tale of Unyeong, Part 1',
    names: { 해설: 'Narrator', 유영: 'Yu Yeong', 진사: 'Kim Jinsa', 운영: 'Unyeong', 대군: 'Grand Prince Anpyeong', 자란: 'Jaran' },
    outro: [
      'Suseong Palace locked the palace maids behind walls and cut them off from the world. What social order might it stand for?',
      'Yu Yeong listens to the story of the two lovers. What distance and effect does this frame story create?',
      'When rules and personal feelings clash, what would you use as your standard for choosing?',
    ],
    lines: [
      ['해설', 'Under King Seonjo of Joseon, a scholar named Yu Yeong visited the ruins of Suseong Palace one spring day. Grand Prince Anpyeong had once lived there.'],
      ['해설', 'After the war, the palace walls had fallen and weeds grew thick. Yu Yeong drank wine in the shade of the flowers and fell asleep.'],
      ['해설', 'When he opened his eyes, a young scholar and a beautiful woman came and sat beside him.'],
      ['유영', 'Who are you, in this lonely old palace?'],
      ['진사', 'I am called Kim Jinsa, and this is Unyeong, once a maid of this palace. Please listen to our story.'],
      ['해설', 'Wiping her tears, Unyeong began to tell what had happened.'],
      ['운영', 'Grand Prince Anpyeong, the third son of King Sejong, loved literature and calligraphy dearly.'],
      ['운영', 'He chose ten palace maids and taught them writing and poetry. I was one of them.'],
      ['대군', 'If any of you lets even your name pass to someone outside the palace, you will be punished by death.'],
      ['운영', 'We lived inside the high walls, writing poems. We were like birds in a cage.'],
      ['해설', 'One day, the Grand Prince called a talented young scholar, Kim Jinsa, to the palace to write poems.'],
      ['해설', 'As Unyeong served beside him, a drop of ink fell from his brush onto her finger.'],
      ['운영', 'I could not bear to wipe that ink away. From that day, I could not forget him.'],
      ['해설', 'A few days later, the Grand Prince had the maids write poems on the theme of smoke.'],
      ['대군', 'The other poems are all good. But Unyeong’s poem shows a heart longing for someone.'],
      ['운영', 'I only wrote what came to mind. There is no hidden meaning.'],
      ['해설', 'The Grand Prince asked no more, but Unyeong felt a chill in her heart.'],
      ['해설', 'Unyeong secretly wrote a letter, but there was no way to send it over the high palace walls.'],
      ['자란', 'Unyeong, why do you look so thin? Tell me, at least.'],
      ['운영', 'Sister, I am sick with thoughts of him. When I think of growing old locked in here, I can’t breathe.'],
      ['자란', 'If you are caught, your life is in danger. But if that is how you feel, I will help as much as I can.'],
      ['해설', 'With the help of a shaman who came and went at the palace, the two could finally exchange letters.'],
      ['진사', 'From the day I got her letter, I walked under the palace wall every night. The wall seemed as high as the sky.'],
      ['운영', 'Just knowing he was outside the wall helped me get through the night.'],
      ['해설', 'Listening to the story, Yu Yeong put down his cup and sighed deeply.'],
      ['유영', 'High walls stood between you. Then what happened next?'],
      ['진사', 'From the day we decided to climb the wall, our fate changed completely.'],
      ['해설', 'The Tale of Unyeong is a Joseon story in classical Chinese by an unknown author. It is also called Suseonggung Mongyurok.'],
    ],
  },

  'tf-unyeong-2': {
    title: 'The Tale of Unyeong, Part 2',
    names: { 해설: 'Narrator', 진사: 'Kim Jinsa', 운영: 'Unyeong', 특: 'Teuk', 자란: 'Jaran', 대군: 'Grand Prince Anpyeong', 유영: 'Yu Yeong' },
    outro: [
      'Beyond love, what hope for a truly human life can we hear in the palace maids’ pleas?',
      'Unlike most classic Korean stories, this one ends in tragedy. What feeling does that leave with readers?',
      'If a rule blocks even people’s most basic wishes, how should that rule change?',
    ],
    lines: [
      ['해설', 'Kim Jinsa had a clever servant named Teuk. Teuk told his master how to climb over the wall.'],
      ['특', 'Sir, I will make you a light ladder. If you wear fur socks, your steps won’t make a sound.'],
      ['해설', 'From that night, Kim Jinsa climbed the wall to see Unyeong, and the two sat and talked in secret.'],
      ['운영', 'If we are caught meeting like this, neither of us will survive.'],
      ['진사', 'Then let us leave the palace together. We can go far away and live in hiding.'],
      ['해설', 'Little by little, Unyeong sent her valuables out of the palace for the escape. Teuk kept them for her.'],
      ['자란', 'Unyeong, think of how much the Grand Prince has cared for you. Will you betray his kindness and run away?'],
      ['자란', 'If you disappear, the blame will fall on the rest of us. Heaven is watching.'],
      ['해설', 'Jaran’s words made Unyeong hesitate, and in the end the two did not run away.'],
      ['해설', 'Meanwhile, Teuk stole Unyeong’s valuables and pretended he had been robbed.'],
      ['특', 'Sir, bandits took everything I hid in the mountains!'],
      ['해설', 'Worse, Teuk talked carelessly about the palace outside, and strange rumors spread.'],
      ['해설', 'The rumors finally reached the Grand Prince. He called the maids who lived with Unyeong and questioned them sternly.'],
      ['대군', 'I hear someone met a man from outside the wall in secret. If you do not tell the truth, none of you will be safe.'],
      ['자란', 'Palace maids are human too. We are locked inside walls in spring. Is longing for the outside a crime worth death?'],
      ['운영', 'All the blame is mine. The others did nothing wrong. Punish me alone.'],
      ['해설', 'After hearing the maids’ pleas, the Grand Prince was silent for a long time, and his anger softened a little.'],
      ['해설', 'He had Unyeong locked in a separate room. But that night, Unyeong died alone.'],
      ['해설', 'When Kim Jinsa heard, he was lost in grief. He gave her belongings as offerings at a temple and prayed for her soul.'],
      ['진사', 'Unyeong, in the next life, let us meet where there are no walls and no ranks.'],
      ['해설', 'Not long after, Teuk, who had lived by lies, met an unexpected death.'],
      ['해설', 'Kim Jinsa stopped eating and took to his bed. Before long, he followed Unyeong.'],
      ['해설', 'When the two finished their story, they wept, and Yu Yeong comforted them.'],
      ['유영', 'You two are together again now. Please let go of a little of your sorrow.'],
      ['진사', 'Now we live together in heaven. But when we come here, the old sorrow returns.'],
      ['운영', 'Please, sir, tell this story to the world so it is not forgotten.'],
      ['해설', 'Yu Yeong, drunk, fell asleep again. When birdsong woke him, the two were gone, and only a book remained.'],
      ['해설', 'Yu Yeong kept the book with care. Later he wandered among famous mountains, and no one knows where his life ended.'],
      ['해설', 'The Tale of Unyeong is a Joseon story in classical Chinese, told as a tale heard in a dream.'],
    ],
  },

  'tf-sassi-1': {
    title: 'Lady Sa’s Journey South, Part 1',
    names: { 해설: 'Narrator', 사씨: 'Lady Sa', 한림: 'Yu Yeonsu', 교씨: 'Lady Gyo', 두부인: 'Lady Du', 동청: 'Dong Cheong' },
    outro: [
      'Through the conflict between Lady Sa and Lady Gyo, what did Kim Man-jung want to say about good, evil, and order in the family?',
      'Lady Gyo says one thing to her husband and another behind his back. How does this reveal her character?',
      'When we see someone suffer from false rumors or a frame-up, what can we do?',
    ],
    lines: [
      ['해설', 'In the Ming dynasty, a young scholar named Yu Yeonsu passed the state exam early and became a royal scholar.'],
      ['해설', 'He married Lady Sa, who was kind and learned. She ran the household well and was widely praised.'],
      ['해설', 'But after many years of marriage they still had no child. So Lady Sa spoke to her husband first.'],
      ['사씨', 'Carrying on the family line is important. Please take a good woman as your concubine.'],
      ['한림', 'How could I hurt you just because we have no child? Take back those words.'],
      ['사씨', 'I have already made up my mind. It is for the family, so please do not refuse.'],
      ['해설', 'And so a woman named Lady Gyo came into the house as a concubine. She was beautiful and a smooth talker.'],
      ['두부인', 'My dear, one should not let a person in for her looks alone. No one yet knows what is in her heart.'],
      ['해설', 'Lady Du was Yu’s aunt. The next year, Lady Gyo had a son. Soon after, Lady Sa also had a son at last.'],
      ['교씨', 'Now that the first wife has a son, my son will always come second.'],
      ['해설', 'Jealousy grew in Lady Gyo’s heart. One day she sang a vulgar song, and Lady Sa quietly warned her.'],
      ['사씨', 'If a woman of this house sings such songs, people will gossip. It would be better to be careful.'],
      ['교씨', 'Yes, my lady. I will keep that in mind.'],
      ['교씨', 'She wants to put me down and drive me out. I must strike first.'],
      ['해설', 'Lady Gyo lied to her husband, saying that Lady Sa was jealous and treated her cruelly.'],
      ['해설', 'Dong Cheong, a guest who often stayed at the house, was a sly man. Lady Gyo joined him in a plot to drive Lady Sa out.'],
      ['동청', 'To get rid of the first wife, we need proof the master cannot help but believe.'],
      ['해설', 'They secretly took a ring Lady Sa treasured and made it look as if she had done something shameful.'],
      ['해설', 'At that time, Lady Du had left with her son for a faraway place. No one was left to take Lady Sa’s side.'],
      ['해설', 'Then Lady Gyo’s little son died. Lady Gyo blamed even that crime on Lady Sa.'],
      ['교씨', 'My lord, my lady killed my son! What shall I do with this grief?'],
      ['한림', 'I never knew you were so terrible. I cannot keep you in this house any longer.'],
      ['사씨', 'I have done nothing to be ashamed of before heaven. Someday the truth will come out.'],
      ['해설', 'Lady Sa left the house without defending herself. She had to part from her little son as well.'],
      ['해설', 'She built a hut beside the graves of her parents-in-law and lived there, bearing her sorrow.'],
      ['해설', 'Meanwhile, Lady Gyo became the first wife. Dong Cheong won Yu’s trust and ran the household as he pleased.'],
      ['동청', 'This house is in our hands now. If we get rid of Lady Sa for good, we will have nothing to worry about.'],
      ['해설', 'Now the hands of Lady Gyo and Dong Cheong were reaching even Lady Sa in her hut.'],
      ['해설', 'Lady Sa’s Journey South was written by Kim Man-jung under King Sukjong. It is a family novel about a wife and a concubine.'],
    ],
  },

  'tf-sassi-2': {
    title: 'Lady Sa’s Journey South, Part 2',
    names: { 해설: 'Narrator', 사씨: 'Lady Sa', 한림: 'Yu Yeonsu', 교씨: 'Lady Gyo', 동청: 'Dong Cheong', 시아버지: 'Father-in-law', 묘혜: 'Myohye' },
    outro: [
      'Lady Sa regains her honor after great hardship. What kind of world order did the writer hope for?',
      'Dreams and mysterious help save Lady Sa. What role do these play in the story’s structure?',
      'Some say this novel hinted at events in the royal court. What stories today criticize society in a similar way?',
    ],
    lines: [
      ['해설', 'One night, as Lady Sa slept in her hut, her late father-in-law appeared in her dream.'],
      ['시아버지', 'My child, if you stay here, great harm will come to you. Go south at once.'],
      ['해설', 'At dawn, Lady Sa set out south with only a few people. She planned to rely on Lady Du.'],
      ['해설', 'But at the end of the long road, she found that Lady Du had already moved somewhere else.'],
      ['해설', 'With nowhere to turn, Lady Sa stood by Lake Dongting, staring blankly at the water.'],
      ['사씨', 'How cruel heaven is! I am falsely accused, and in this wide world I have no place to rest.'],
      ['해설', 'Exhausted, Lady Sa fell asleep for a moment in a shrine by the water. In her dream, queens of ancient times came to comfort her.'],
      ['해설', 'They told her that her hardship would not last. She must treasure her life and wait for her time.'],
      ['해설', 'When she awoke, Myohye, a Buddhist nun from a hermitage on Mount Jun, appeared before her.'],
      ['묘혜', 'My lady, I came because of a sign in a dream. Come to our hermitage and wait for your time.'],
      ['해설', 'Lady Sa followed Myohye to a small hermitage on an island in the lake. There she hid and calmed her heart.'],
      ['해설', 'Meanwhile, in Yu’s house, the true faces of Lady Gyo and Dong Cheong began to show.'],
      ['동청', 'If I report that he insulted the court, all the wealth of this house will be ours.'],
      ['해설', 'Because of Dong Cheong’s report, Yu lost his post and was sent into exile far away.'],
      ['해설', 'Lady Gyo took the family’s valuables and went to Dong Cheong. He flattered a powerful official and won a high post.'],
      ['해설', 'Suffering in exile, Yu finally learned that everything had been the plot of Lady Gyo and Dong Cheong.'],
      ['한림', 'I drove out my good wife and trusted wicked people. All of this is my own foolishness.'],
      ['해설', 'Later, Yu was pardoned. On his way home, Dong Cheong’s men chased him, trying to kill him.'],
      ['해설', 'Trapped at a riverbank, Yu saw a small boat coming toward him. In it were Myohye and Lady Sa, whom he had longed to find.'],
      ['한림', 'My lady, how can I face you? Please forgive me.'],
      ['사씨', 'All that happened was heaven’s will. We have met again alive. That is enough.'],
      ['해설', 'Later, when the corrupt officials fell, Yu returned to office. Dong Cheong’s crimes came to light, and he was punished.'],
      ['해설', 'Lady Gyo, who had wandered with no one to depend on, was finally caught and knelt before Yu.'],
      ['교씨', 'My lord, please spare my life just once. Dong Cheong made me do it all.'],
      ['한림', 'Heaven knows all your crimes. Make no more excuses.'],
      ['해설', 'In the end, Lady Gyo was punished for her crimes, and Lady Sa became the lady of the house again.'],
      ['해설', 'Later, Lady Sa’s lost son was found too, and at last the family was at peace.'],
      ['해설', 'The title means the story of Lady Sa going south. Its author is Kim Man-jung, who also wrote The Cloud Dream of the Nine.'],
    ],
  },
};
