// 청소년 영어 원고 (중학생 이상). 키 = stories/teen-talk4.js 의 이야기 id.
// 자체 집필 교양 강연(예술·도시)을 한국어 원고의 흐름대로 쉬운 강연체 영어로 새로 씀. 사실은 한국어 원고의 확인 메모와 같음.
// 한국 고유 낱말은 로마자로 쓰고 짧게 풀이.
export default {
  'tk4-perspective': {
    title: 'The Discovery of Perspective',
    names: { 해설: 'Narrator', 강연자: 'Lecturer', 학생: 'Student' },
    outro: [
      'What is a vanishing point, and what role does it play in a perspective drawing?',
      'What does single-point perspective show well, and what do landscapes with many viewpoints show well?',
      'When I take a photo or draw a picture, what can I try to create a sense of depth?',
    ],
    lines: [
      ['해설', 'Today’s lecture is about perspective, a way to create depth in a picture.'],
      ['해설', 'Our stage is Florence, Italy, in the early fifteenth century.'],
      ['강연자', 'In many medieval European paintings, more important figures were painted larger.'],
      ['강연자', 'Size showed importance in faith, not how big things looked to the eye.'],
      ['강연자', 'Renaissance painters wanted to capture the world just as the eye sees it.'],
      ['강연자', 'Think of railroad tracks. The two parallel rails seem to meet far away.'],
      ['강연자', 'The point where parallel lines seem to meet is called the vanishing point.'],
      ['강연자', 'It is said that the architect Brunelleschi showed this principle with an experiment.'],
      ['강연자', 'He reportedly made a small hole in the middle of a panel painting of the Florence Baptistery.'],
      ['강연자', 'Through the hole, people saw the painting in a mirror and compared it with the real building.'],
      ['학생', 'So the painting matched the real building exactly?'],
      ['강연자', 'That is the story. But the panel no longer exists, so we cannot know the details.'],
      ['강연자', 'Around 1435, Alberti explained this method in writing in his book On Painting.'],
      ['강연자', 'He said to think of a picture as an open window looking out on the world.'],
      ['강연자', 'In his wall painting The Holy Trinity, Masaccio made the ceiling seem to go deep into the wall.'],
      ['강연자', 'He made a flat wall look as if a space had opened in it.'],
      ['강연자', 'In Leonardo da Vinci’s The Last Supper, the lines meet at the head of Jesus.'],
      ['강연자', 'This naturally pulls the viewer’s eyes to the center of the picture.'],
      ['강연자', 'Perspective is not only about lines. Faraway mountains look pale and bluish.'],
      ['강연자', 'Using this effect in painting is called aerial perspective, or atmospheric perspective.'],
      ['학생', 'Then are pictures without perspective less advanced?'],
      ['강연자', 'Good question. We can’t say that.'],
      ['강연자', 'East Asian landscape paintings sometimes show mountains from several viewpoints in one picture.'],
      ['강연자', 'Guo Xi of the Northern Song divided the ways of viewing mountains into three: high, deep, and level.'],
      ['강연자', 'It is good to understand perspective as one of many ways to see the world.'],
      ['강연자', 'Still, perspective is seen as a famous moment when math and art joined hands.'],
      ['해설', 'Later, perspective was also widely used in architecture and stage design.'],
      ['해설', 'The Last Supper is painted on the wall of a monastery dining hall in Milan.'],
    ],
  },

  'tk4-impression': {
    title: 'What Was New About Impressionism',
    names: { 해설: 'Narrator', 강연자: 'Lecturer', 학생: 'Student' },
    outro: [
      'What did the Impressionists want to paint more than the objects themselves?',
      'What does it tell us that a name meant as a joke became the name of an art movement?',
      'Have I ever seen the same place look different in the morning and in the evening?',
    ],
    lines: [
      ['해설', 'Today we go to Paris in nineteenth-century France to meet Impressionist paintings.'],
      ['해설', 'Imagine the lecturer standing in the middle of an exhibition hall as you listen.'],
      ['강연자', 'For French painters back then, the most important stage was the official exhibition called the Salon.'],
      ['강연자', 'The Salon praised smooth, detailed paintings of history and myth.'],
      ['강연자', 'In 1874, a group of painters held their own exhibition outside the Salon.'],
      ['강연자', 'They included Monet, Renoir, Degas, Pissarro, and Berthe Morisot.'],
      ['강연자', 'One of Monet’s paintings there was called Impression, Sunrise.'],
      ['강연자', 'It is said that a critic mocked this title and called them Impressionists.'],
      ['강연자', 'So a name meant as a joke became the name of this art.'],
      ['학생', 'What was so strange about those paintings?'],
      ['강연자', 'First, the subjects were different. They painted the city life of their time, like train stations, cafes, and riverside outings.'],
      ['강연자', 'Second, they often left the studio and painted outdoors, looking at real light.'],
      ['강연자', 'Just then, paint in metal tubes appeared, which made it easy to carry.'],
      ['강연자', 'Third, they did not hide their brushstrokes. They dabbed paint in short, quick strokes.'],
      ['강연자', 'Instead of mixing all colors on the palette, they placed them side by side to blend in the eye.'],
      ['강연자', 'Fourth, they sometimes painted shadows blue or purple instead of black.'],
      ['강연자', 'If you look closely at shadows in sunlight, they really contain many colors.'],
      ['학생', 'So what were the Impressionists really trying to paint?'],
      ['강연자', 'You could say it was the light and air touching things at that moment, more than the things themselves.'],
      ['강연자', 'Monet painted Rouen Cathedral and haystacks many times, in different hours and weather.'],
      ['강연자', 'He showed that the same subject becomes a totally different picture when the light changes.'],
      ['강연자', 'Of course, each painter had a different style. Degas loved to paint dancers indoors.'],
      ['강연자', 'Some think that as photography spread, painters asked what only painting could do.'],
      ['강연자', 'The bold layouts of ukiyo-e, Japanese woodblock prints, also influenced them.'],
      ['강연자', 'At first, people laughed that the works looked unfinished, but this experiment opened a new road.'],
      ['강연자', 'Later, painters like Cezanne, Van Gogh, and Gauguin went one step further.'],
      ['해설', 'Impressionism greatly changed the way Western art later dealt with light and color.'],
      ['해설', 'The Impressionists held eight group exhibitions from 1874 to 1886.'],
    ],
  },

  'tk4-joseon-art': {
    title: 'Paintings of Joseon',
    names: { 해설: 'Narrator', 강연자: 'Lecturer', 학생: 'Student' },
    outro: [
      'How was true-view landscape painting different from earlier landscape painting?',
      'How did Jeong Seon, Kim Hong-do, and Shin Yun-bok each try to show something different?',
      'If I left one picture of our day for people three hundred years from now, what would I paint?',
    ],
    lines: [
      ['해설', 'Today’s story is about the eighteenth century, in late Joseon, when paintings began to show the real Joseon.'],
      ['해설', 'We will meet three painters in turn: Jeong Seon, Kim Hong-do, and Shin Yun-bok.'],
      ['강연자', 'For a long time, Joseon landscape painters often followed Chinese models.'],
      ['강연자', 'They painted imaginary mountains and rivers they had never visited, in set ways.'],
      ['강연자', 'But Jeong Seon, known as Gyeomjae, traveled to real mountains and rivers in Korea and painted them.'],
      ['강연자', 'These works are called jingyeong sansuhwa, which means true-view landscape painting.'],
      ['강연자', 'His masterpiece, Inwang Jesaekdo, shows Mount Inwang after the rain has cleared.'],
      ['강연자', 'He swept dark ink boldly down the wet rocks, giving them a heavy weight.'],
      ['강연자', 'In Geumgang Jeondo, he gathered the many peaks of the Diamond Mountains into one round picture.'],
      ['학생', 'If they are real views, did he paint them exactly, like a photo?'],
      ['강연자', 'No. He combined views from several places and boldly stressed some parts.'],
      ['강연자', 'You could say he painted our mountains as he felt them, more than as he saw them.'],
      ['강연자', 'Now let’s turn to people. Kim Hong-do, known as Danwon, was a court painter at the Dohwaseo.'],
      ['강연자', 'The Dohwaseo was the office for the state’s painting work. He even helped paint the king’s portrait.'],
      ['강연자', 'His genre paintings show the daily lives of ordinary people, like wrestling, village schools, and blacksmiths.'],
      ['강연자', 'In Ssireum, or Wrestling, each face in the circle of watchers has a different expression.'],
      ['강연자', 'He hardly painted any background, so our eyes go to the people’s movements.'],
      ['강연자', 'Shin Yun-bok, known as Hyewon, loved to paint the style and fun of city men and women.'],
      ['강연자', 'In Dano Pungjeong, women wash their hair by a stream and ride swings on the Dano holiday.'],
      ['강연자', 'Clear, lovely colors and fine lines are seen as features of his paintings.'],
      ['학생', 'Why did so many of these paintings appear at that time?'],
      ['강연자', 'Under Kings Yeongjo and Jeongjo, culture flourished, and people tried to see their own things in a new way.'],
      ['강연자', 'Trade grew, and more people bought and enjoyed paintings. That is also named as a reason.'],
      ['강연자', 'But it is better to see several causes together than to name just one.'],
      ['강연자', 'Thanks to these three painters, we can still meet the mountains and people of Joseon from three centuries ago.'],
      ['강연자', 'When you visit a museum, take time to look at each person’s face in the paintings.'],
      ['해설', 'Kim Hong-do’s Wrestling and Village School are in an album called Danwon Pungsokdocheop.'],
      ['해설', 'Hyewon Jeonsincheop, the album with Shin Yun-bok’s Dano Pungjeong, is a National Treasure of Korea.'],
    ],
  },

  'tk4-scale': {
    title: 'Scales and Chords',
    names: { 해설: 'Narrator', 강연자: 'Lecturer', 학생: 'Student' },
    outro: [
      'What do the words octave, scale, and chord each mean?',
      'Does the order of numbers hidden in music make it more beautiful, or does it lock it in a frame?',
      'Can I find out why my favorite song sounds bright or lonely?',
    ],
    lines: [
      ['해설', 'Today we look at the basic building blocks of music: scales and chords.'],
      ['해설', 'Next to the lecturer are a simple one-string instrument and a piano.'],
      ['강연자', 'Sound happens when an object shakes and moves the air, and that reaches our ears.'],
      ['강연자', 'The number of shakes per second is called frequency. The more shakes, the higher the sound.'],
      ['강연자', 'If you hold the string at half its length and pluck it, the frequency doubles.'],
      ['강연자', 'That sound has the same name as the first one, but it sounds one level higher.'],
      ['강연자', 'This distance is called an octave. From low do to high do is one octave.'],
      ['학생', 'Who first found the rule between string length and pitch?'],
      ['강연자', 'It is said that Pythagoras of ancient Greece and his followers studied these ratios.'],
      ['강연자', 'If you make the string two thirds as long, you get notes that blend well, like do and sol.'],
      ['강연자', 'This interval is called a perfect fifth. The simpler the ratio, the better the notes blend.'],
      ['강연자', 'In Western music, one octave is divided into twelve half steps.'],
      ['강연자', 'Look at a piano. Seven white keys and five black keys repeat again and again.'],
      ['강연자', 'Choosing some of these notes and lining them up by pitch gives a scale.'],
      ['강연자', 'The first note, the center of the scale, is called the tonic.'],
      ['강연자', 'The major scale from do goes whole, whole, half, whole, whole, whole, half.'],
      ['강연자', 'Those half steps are why there is no black key between mi and fa, or between ti and do.'],
      ['강연자', 'The minor scale starting from la uses the same white keys but has a different color.'],
      ['강연자', 'Now let’s sound several notes at once. This is called a chord.'],
      ['강연자', 'Press do, mi, and sol together, and you get a bright, stable sound: a major chord.'],
      ['강연자', 'Press la, do, and mi, and you get a minor chord that sounds a little lonely.'],
      ['학생', 'Does major sound happy and minor sound sad to everyone?'],
      ['강연자', 'Many people feel that way, but it can depend on the music you grew up with.'],
      ['강연자', 'Remember, too, that music around the world has used many different scales.'],
      ['강연자', 'Korean traditional music often uses a five-note scale.'],
      ['강연자', 'Music is an art that moves the heart, but an order of numbers lies beneath it.'],
      ['해설', 'Try singing the first line of a favorite song in do, re, mi. You will see the scale more clearly.'],
      ['해설', 'A standard piano has eighty-eight keys, with seven white and five black keys in each octave.'],
    ],
  },

  'tk4-beethoven': {
    title: 'Beethoven and Romanticism',
    names: { 해설: 'Narrator', 강연자: 'Lecturer', 학생: 'Student' },
    outro: [
      'What did Classical music and Romantic music each value more?',
      'Why is Beethoven called a bridge between two periods?',
      'Even in great difficulty, what is something I want to keep holding on to?',
    ],
    lines: [
      ['해설', 'Today we see an age of music change through one composer.'],
      ['해설', 'Our main figure is Ludwig van Beethoven, born in Bonn, Germany, in 1770.'],
      ['강연자', 'As a young man, Beethoven moved to Vienna, then the center of European music.'],
      ['강연자', 'In Vienna, Haydn and Mozart had brought what we call Classical music to full bloom.'],
      ['강연자', 'Classical music valued balance, order, and clear form.'],
      ['강연자', 'A symphony usually had four movements, and the first often followed sonata form.'],
      ['강연자', 'Sonata form presents themes, develops them, and then returns to them.'],
      ['강연자', 'In Vienna, Beethoven also took lessons from Haydn.'],
      ['강연자', 'But from his late twenties, a great trial came. He slowly began to lose his hearing.'],
      ['강연자', 'In 1802, in Heiligenstadt, he wrote a letter to his brothers, almost like a will.'],
      ['강연자', 'It shows his despair, but also his will to endure for the sake of his art.'],
      ['학생', 'How could he keep composing when he couldn’t hear?'],
      ['강연자', 'He was trained so deeply that he could imagine sounds in his head and write them down.'],
      ['강연자', 'From around this time, his music grew bigger, more dramatic, and more personal.'],
      ['강연자', 'There is a story that he first meant to dedicate his Third Symphony to Napoleon.'],
      ['강연자', 'When Napoleon made himself emperor, Beethoven was disappointed and scratched out the name on the title page.'],
      ['강연자', 'This work went far beyond earlier symphonies in length and scale.'],
      ['강연자', 'In his last symphony, the Ninth, he added solo singers and a choir to the final movement.'],
      ['강연자', 'The words came from Ode to Joy, a poem by the German poet Schiller.'],
      ['강연자', 'It is said that at the 1824 premiere, he could not hear the applause, so someone turned him around.'],
      ['학생', 'So is Beethoven a Classical composer or a Romantic composer?'],
      ['강연자', 'You could say both. On top of Classical forms, he built a bridge to the next age.'],
      ['강연자', 'Romantic music put personal feelings, imagination, nature, and stories ahead of form.'],
      ['강연자', 'Composers who followed, like Schubert, Chopin, and Schumann, widened that road.'],
      ['강연자', 'Beethoven tried to live as an independent artist, rather than a musician tied to nobles.'],
      ['강연자', 'He did receive support, but he also made a living by publishing his works and holding concerts.'],
      ['해설', 'Beethoven died in Vienna in 1827.'],
      ['해설', 'He left nine symphonies in all.'],
    ],
  },

  'tk4-pansori': {
    title: 'Pansori and Korean Folk Songs',
    names: { 해설: 'Narrator', 강연자: 'Lecturer', 학생: 'Student' },
    outro: [
      'In pansori, what roles do the singer, the drummer, and the audience play?',
      'What strengths and weaknesses do songs passed down by memory, without written music, have?',
      'Have I ever used call and response when singing or cheering with friends?',
    ],
    lines: [
      ['해설', 'Today we enter the world of Korean traditional singing: pansori and minyo, or folk songs.'],
      ['해설', 'On the stage lie a straw mat and a single drum.'],
      ['강연자', 'Pansori is a performance where one singer tells a long story through song and speech.'],
      ['강연자', 'The person beside the singer who keeps the rhythm on a drum is called the gosu.'],
      ['강연자', 'With a fan in hand, the singer acts out rowing a boat or swinging a sword.'],
      ['강연자', 'The sung parts are called sori, and the spoken parts are called aniri.'],
      ['강연자', 'Telling the story with body movements is called ballim.'],
      ['학생', 'Since when has pansori been sung?'],
      ['강연자', 'It is thought to have taken root among common people in late Joseon.'],
      ['강연자', 'There are few records of its exact beginning, so there are several views.'],
      ['강연자', 'It is said there were once twelve works, but only five are fully sung today.'],
      ['강연자', 'They are Chunhyangga, Simcheongga, Heungboga, Sugungga, and Jeokbyeokga.'],
      ['강연자', 'In the nineteenth century, Shin Jae-hyo wrote down the pansori texts and supported singers.'],
      ['강연자', 'Another star of pansori is the audience.'],
      ['강연자', 'They give the singer strength with shouts called chuimsae, like eolssigu, jota, and jalhanda.'],
      ['강연자', 'There is a saying: the drummer first, the singer second.'],
      ['강연자', 'It means the drum rhythm brings the singing to life and leads it.'],
      ['강연자', 'Now let’s move on to minyo. Minyo are songs that ordinary people made and sang together.'],
      ['강연자', 'Many came from life and work, like work songs sung while planting or weeding rice.'],
      ['강연자', 'Often one person sings a leading line, and many others answer. This is call and response.'],
      ['강연자', 'Arirang has different tunes and words in each region. Jeongseon, Jindo, and Miryang Arirang are famous.'],
      ['학생', 'Why is the same Arirang different in each region?'],
      ['강연자', 'As it passed from mouth to mouth, each region’s way of speaking and living seeped into it.'],
      ['강연자', 'So folk songs came to have a different sound color in each region.'],
      ['강연자', 'Pansori and minyo are alike in that they were passed down through voices and memory more than written music.'],
      ['강연자', 'The moment you clap along and shout chuimsae, you become part of the performance, too.'],
      ['해설', 'In 2003, UNESCO named pansori a Masterpiece of the Oral and Intangible Heritage of Humanity.'],
      ['해설', 'In 2012, Arirang was added to UNESCO’s list of the Intangible Cultural Heritage of Humanity.'],
    ],
  },

  'tk4-arch': {
    title: 'Columns and Arches',
    names: { 해설: 'Narrator', 강연자: 'Lecturer', 학생: 'Student' },
    outro: [
      'How does an arch spread and carry weight better than posts and beams?',
      'Did Gothic cathedrals become tall and bright because of new technology, or new ideas?',
      'Where can I find columns and arches in my school or neighborhood buildings?',
    ],
    lines: [
      ['해설', 'Today we follow the history of architecture: how people held up heavy roofs.'],
      ['해설', 'The lecturer has stacked a few wooden blocks and begins to speak.'],
      ['강연자', 'The simplest way is to stand two posts and lay a beam across the top.'],
      ['강연자', 'Ancient Greek temples refined this method beautifully.'],
      ['강연자', 'The Parthenon, built on the Acropolis of Athens in the fifth century BC, is a famous example.'],
      ['강연자', 'Greek columns come in three orders: Doric, Ionic, and Corinthian.'],
      ['강연자', 'Doric is thick and simple. Ionic has scroll shapes at the top.'],
      ['강연자', 'Corinthian is the fanciest, carved with layers of acanthus leaves.'],
      ['학생', 'But why are the columns of temples so close together?'],
      ['강연자', 'Because stone is strong when pressed, but weak when bent or pulled.'],
      ['강연자', 'If the columns are too far apart, the stone beam on top may break in the middle.'],
      ['강연자', 'The arch broke through this limit. The Romans developed the arch greatly.'],
      ['강연자', 'Stack wedge-shaped stones in a half circle and fit a keystone at the top. They press on each other and hold.'],
      ['강연자', 'The weight pressing down flows along the arch to both sides.'],
      ['강연자', 'The Romans linked arches to build aqueducts that carried water, and they built the Colosseum.'],
      ['강연자', 'Turn an arch all the way around, and you get a round roof, a dome. Rome’s Pantheon is famous.'],
      ['강연자', 'The Romans built huge structures with concrete mixed with volcanic ash.'],
      ['강연자', 'In the Middle Ages, large stone churches rose all over Europe.'],
      ['강연자', 'At first they were Romanesque, with round arches, thick walls, and small windows.'],
      ['강연자', 'When the Gothic style appeared in twelfth-century France, churches became much taller and brighter.'],
      ['학생', 'Walls need to be thick to stand. How did they make them tall and bright?'],
      ['강연자', 'First, a pointed arch sends more weight down rather than out to the sides.'],
      ['강연자', 'Second, stone ribs in the ceiling, like a rib cage, gather the weight onto the columns.'],
      ['강연자', 'Third, they added supports that hold up the walls from outside, called flying buttresses.'],
      ['강연자', 'They are called flying because they seem to float in the air.'],
      ['강연자', 'Once the walls carried less weight, they could have huge stained glass windows.'],
      ['강연자', 'The history of architecture is also a history of skills for handling weight and force.'],
      ['해설', 'Notre-Dame Cathedral in Paris is a Gothic church begun in the late twelfth century.'],
    ],
  },

  'tk4-river-city': {
    title: 'Cities by the River',
    names: { 해설: 'Narrator', 강연자: 'Lecturer', 학생: 'Student' },
    outro: [
      'Can I give three reasons why early cities grew up by big rivers?',
      'If rivers helped civilizations grow, what troubles did rivers bring them?',
      'What role does the river or stream in my neighborhood play in people’s lives?',
    ],
    lines: [
      ['해설', 'Today we spread out a map and look for where the oldest cities were.'],
      ['해설', 'The lecturer has drawn a few thick blue lines on a world map.'],
      ['강연자', 'These lines are the Tigris and Euphrates, the Nile, the Indus, and the Yellow River.'],
      ['강연자', 'Most early human civilizations arose in the valleys of big rivers like these.'],
      ['강연자', 'We often call them the four great civilizations, but there were early civilizations in other places, too.'],
      ['학생', 'Why rivers, of all places? There must have been floods.'],
      ['강연자', 'Good question. In fact, those floods are the first reason.'],
      ['강연자', 'When rivers overflowed, rich soil from upstream settled on the fields, so crops grew well.'],
      ['강연자', 'Second, people and crops need water, and river water could be led to the fields.'],
      ['강연자', 'Third, rivers became roads for carrying goods and people by boat.'],
      ['강연자', 'When there was enough food, people who did not farm could also live.'],
      ['강연자', 'A place where craftspeople, traders, priests, and officials lived together was a city.'],
      ['강연자', 'Mesopotamia means the land between two rivers.'],
      ['강연자', 'The Sumerians there built cities like Ur and Uruk and wrote in cuneiform, a wedge-shaped script.'],
      ['강연자', 'The Egyptians farmed in step with the Nile’s flood, which came every year.'],
      ['강연자', 'And they made and used a calendar with three hundred sixty-five days in a year.'],
      ['강연자', 'Mohenjo-daro, in the Indus valley, had straight streets and drains.'],
      ['강연자', 'In the Yellow River valley, the Shang dynasty carved oracle bone script on turtle shells and animal bones.'],
      ['학생', 'Floods are dangerous, so everyone must have had to work together to stop them.'],
      ['강연자', 'Right. Building banks and digging channels took the strength of many people.'],
      ['강연자', 'Some scholars think this kind of work helped states grow.'],
      ['강연자', 'But others argue that it cannot explain the birth of states by itself.'],
      ['강연자', 'Rivers helped civilizations grow, but they also brought great floods and salty soil.'],
      ['강연자', 'Many big cities today are also on rivers or coasts.'],
      ['강연자', 'Think of the Han River in Seoul, the Seine in Paris, and the Thames in London.'],
      ['강연자', 'People have always gathered where water and roads meet.'],
      ['해설', 'Managing rivers is still a big task that cities must solve today.'],
      ['해설', 'The ancient Egyptians divided the year into three seasons based on the Nile’s flood.'],
    ],
  },

  'tk4-sanitation': {
    title: 'Cholera and Clean Water',
    names: { 해설: 'Narrator', 강연자: 'Lecturer', 학생: 'Student' },
    outro: [
      'How did John Snow come to suspect that water caused cholera?',
      'Which saved more lives, doctors’ treatments or engineers’ sewers?',
      'How would my day change if clean water were cut off?',
    ],
    lines: [
      ['해설', 'Today we visit a nineteenth-century European city to learn why clean water matters.'],
      ['해설', 'Our stage is London, England, crowded with people because of the Industrial Revolution.'],
      ['강연자', 'As factories grew, huge numbers of people moved to cities to find work.'],
      ['강연자', 'Several families lived packed into small houses, and toilets and waste disposal were terrible.'],
      ['강연자', 'Waste flowed straight into the river, and people sometimes drank that water again.'],
      ['강연자', 'The disease that struck such cities again and again was cholera.'],
      ['강연자', 'Cholera causes severe diarrhea. People lost water from their bodies and sometimes died.'],
      ['학생', 'What did people back then think caused the disease?'],
      ['강연자', 'Many believed it came from bad air that smelled of rot.'],
      ['강연자', 'This is called the miasma theory. But a doctor, John Snow, thought differently.'],
      ['강연자', 'When cholera spread in Soho, London, in 1854, he marked the homes of the dead on a map.'],
      ['강연자', 'The deaths were clustered around one public pump on Broad Street.'],
      ['강연자', 'He blamed the water from that pump and had its handle removed.'],
      ['학생', 'Did blocking the pump really reduce the number of patients?'],
      ['강연자', 'The outbreak was already falling, so we can’t be sure of the effect. But his judgment was right.'],
      ['강연자', 'Finding the cause of disease with maps and data is often called a starting point of epidemiology.'],
      ['강연자', 'In the summer of 1858, the Thames smelled so bad that it was called the Great Stink.'],
      ['강연자', 'After that, the engineer Joseph Bazalgette built a huge sewer network in London.'],
      ['강연자', 'It carried waste away from the river in the city, far downstream.'],
      ['강연자', 'Around the same time, Paris was also rebuilt with wide streets and sewers.'],
      ['강연자', 'In the 1880s, Robert Koch of Germany identified the germ that causes cholera.'],
      ['강연자', 'It became clear that the cause was germs in water, not bad air.'],
      ['학생', 'So what is the difference between water supply and sewers?'],
      ['강연자', 'Water supply pipes bring clean water to homes. Sewers carry used water away.'],
      ['강연자', 'By separating the two and filtering and cleaning the water, cities became much safer.'],
      ['강연자', 'When we turn on a tap and wash our hands today, we stand on this long history.'],
      ['강연자', 'Hand washing and clean water are still basic ways to prevent infectious diseases.'],
      ['해설', 'A city’s health is protected not only by hospitals, but also by hidden pipes underground.'],
      ['해설', 'Cholera is an infectious disease caught by eating or drinking food or water polluted with cholera germs.'],
    ],
  },

  'tk4-hanyang': {
    title: 'The Story of the Hanyang City Wall',
    names: { 해설: 'Narrator', 강연자: 'Lecturer', 학생: 'Student' },
    outro: [
      'Why did Joseon make Hanyang its capital and build the wall along the mountain ridges?',
      'How can we look at the modern changes that tore down parts of the wall and gates?',
      'Where and how do old borders or roads remain in my city?',
    ],
    lines: [
      ['해설', 'Today we walk along Hanyang Doseong, the wall around Hanyang, the old name of Seoul.'],
      ['해설', 'In 1394, King Taejo, Yi Seong-gye, who founded Joseon, moved the capital to Hanyang.'],
      ['강연자', 'Hanyang is land surrounded by four mountains: Bugaksan, Naksan, Namsan, and Inwangsan.'],
      ['강연자', 'A stream called Gaecheon flowed through the middle, and the great Han River flowed to the south.'],
      ['강연자', 'The mountains made it easy to defend, and the river made it easy to bring in grain and goods.'],
      ['강연자', 'Gyeongbokgung Palace was built in 1395, and the next year, in 1396, work on the wall began.'],
      ['강연자', 'Records say that Jeong Do-jeon gave Gyeongbokgung its name.'],
      ['강연자', 'The wall follows the ridges of the four mountains and runs about eighteen kilometers around.'],
      ['강연자', 'The wall had four large gates and four small gates.'],
      ['강연자', 'The great gates were Heunginjimun to the east, Donuimun to the west, Sungnyemun to the south, Sukjeongmun to the north.'],
      ['학생', 'What do the in, ui, and ye in the gate names mean?'],
      ['강연자', 'They come from in, ui, ye, and ji, the virtues that Confucianism valued.'],
      ['강연자', 'In means kindness, ui means rightness, and ye means courtesy. Even the gates carried the nation’s ideals.'],
      ['강연자', 'A big bell hung in the bell pavilion on Jongno to tell when to open and close the gates.'],
      ['강연자', 'The night bell to close the gates was called injeong, and the dawn bell to open them was called paru.'],
      ['강연자', 'As you walk the wall, you can see that the stones look different in each section.'],
      ['강연자', 'After it was first built under King Taejo, it was rebuilt several times, under King Sejong, King Sukjong, and others.'],
      ['강연자', 'Each period shaped stones differently, so the stones show which period they came from.'],
      ['강연자', 'Under King Yeongjo, there was a big project called juncheon to dig out the mud in the stream.'],
      ['학생', 'But now the wall is broken in many places.'],
      ['강연자', 'In modern times, parts of the wall and gates were torn down to make roads and tram lines.'],
      ['강연자', 'Donuimun was torn down during the Japanese colonial period and no longer exists.'],
      ['강연자', 'Today, broken sections have been repaired and joined, and there is a trail along the wall.'],
      ['강연자', 'The wall was a barrier against enemies, and also a border between inside and outside the city.'],
      ['강연자', 'Walking the wall shows you the frame on which the capital Seoul was first built.'],
      ['강연자', 'Try to find out whether old borders and roads remain in your city, too.'],
      ['해설', 'The Gaecheon stream that flowed through the walled city is today’s Cheonggyecheon.'],
      ['해설', 'Heunginjimun is the only one of the four great gates with an outer half-circle wall, called an ongseong.'],
    ],
  },
};
