// 청소년 영어 원고: 프랑켄슈타인 1~10화 (stories/teen-frank.js). 문장은 자체 각색.
// lines 의 첫 칸은 한국어 이야기 cast 의 이름 그대로.
export default {
  'fk-01': {
    title: 'Frankenstein, Part 1',
    names: { 해설: 'Narrator', 월턴: 'Robert Walton', 선원: 'Sailor', 빅터: 'Victor Frankenstein' },
    outro: [
      'Why did Victor see Walton’s wish to risk his life for a dream as such a sad thing?',
      'The story is told inside letters. What distance and tension does this frame create for the reader?',
      'How far should we cheer for people who want to go where no one has gone, and when should they stop?',
    ],
    lines: [
      ['해설', 'In the late eighteenth century, a young English explorer named Robert Walton was in Archangel, a port in northern Russia.'],
      ['해설', 'He wrote letters to his sister Margaret in England and prepared to sail into the Arctic sea.'],
      ['월턴', 'Sister, I want to leave the first footprint on a land no one has ever walked on.'],
      ['월턴', 'I also want to discover what power pulls the needle of a compass.'],
      ['해설', 'As a boy, he had read every book of sea voyages in his uncle’s library.'],
      ['해설', 'After years of training his body and learning the sea, he hired a ship and gathered a crew.'],
      ['월턴', 'But, sister, I have no friend at all to share my heart with.'],
      ['해설', 'At the end of July, as the ship sailed north, it became trapped in ice on every side.'],
      ['해설', 'In the thick fog, the sailors held their breath and waited for the ice to break.'],
      ['선원', 'Captain, look over there! Something is running across the ice!'],
      ['해설', 'A sledge pulled by dogs raced past. On it sat a figure shaped like a man, but enormous.'],
      ['해설', 'The sledge sped away between hills of ice and soon disappeared.'],
      ['월턴', 'Who could possibly be out here, so far from any land?'],
      ['해설', 'The next morning, another sledge drifted up to the ship on a piece of ice.'],
      ['해설', 'Only one dog was still alive, and a half-frozen man was huddled on the sledge.'],
      ['빅터', 'Where is this ship going?'],
      ['월턴', 'We are exploring toward the North Pole. Come aboard quickly, or you will freeze to death.'],
      ['해설', 'Only after hearing this answer did the man climb aboard. He was terribly thin and exhausted.'],
      ['해설', 'Once he was warm, he asked about the giant sledge from the day before. His eyes burned strangely.'],
      ['빅터', 'When did you see it? Which way did it go?'],
      ['해설', 'The man said his name was Victor Frankenstein. Walton soon felt drawn to him.'],
      ['해설', 'Some days later, Walton shared his dream. He said he would give his life to reach it.'],
      ['빅터', 'Unhappy man! Do you share my madness too?'],
      ['빅터', 'Listen to my story. Then you may think again about your dream.'],
      ['빅터', 'I do not have long to live. I only hope my story will be a warning to you.'],
      ['해설', 'Every night, Walton wrote down the story Victor told that day and sent it to his sister.'],
      ['해설', 'So from beginning to end, this novel sits inside the frame of an explorer’s letters.'],
      ['해설', 'Next time, Victor begins his story with his childhood in Geneva.'],
      ['해설', 'Frankenstein was first published in London in January 1818, without the author’s name.'],
    ],
  },

  'fk-02': {
    title: 'Frankenstein, Part 2',
    names: { 해설: 'Narrator', 어머니: 'Caroline Frankenstein', 알퐁스: 'Alphonse Frankenstein', 빅터: 'Victor', 클레르발: 'Henry Clerval', 엘리자베스: 'Elizabeth Lavenza', 발트만: 'Professor Waldman' },
    outro: [
      'At what point did Victor’s curiosity about nature’s secrets turn into a dangerous desire?',
      'How does the scene of the oak struck by lightning hint at Victor’s future?',
      'When adults forbid something without giving a reason, how do we often react?',
    ],
    lines: [
      ['해설', 'Last time, Victor was rescued from the Arctic ice and agreed to tell Walton his story.'],
      ['해설', 'Victor Frankenstein was born the eldest son of a respected family in Geneva, Switzerland.'],
      ['해설', 'His father, Alphonse, had served the public for many years. His mother, Caroline, was warm and kind.'],
      ['해설', 'His parents took in a little girl, Elizabeth, and raised her with Victor like brother and sister.'],
      ['어머니', 'Victor, this girl is a present for you. Take good care of her.'],
      ['해설', 'Elizabeth loved poetry and nature. Victor cared for her more than anyone.'],
      ['해설', 'His school friend, Henry Clerval, was a cheerful boy who loved tales of knights and adventure.'],
      ['해설', 'But what captured Victor’s heart was the secret of nature, the hidden laws that move the world.'],
      ['해설', 'When he was about thirteen, he happened to open a book by Cornelius Agrippa at an inn.'],
      ['알퐁스', 'Ah, that book. Do not waste your time on it, my boy.'],
      ['해설', 'His father did not explain why. So Victor sank even deeper into it.'],
      ['해설', 'He eagerly read old thinkers such as Paracelsus and Albertus Magnus.'],
      ['빅터', 'If I could find the elixir of life, I could protect people from sickness and death.'],
      ['해설', 'When he was fifteen, lightning struck an old oak tree near the house during a violent storm.'],
      ['해설', 'The next morning, the tree was shattered, with only thin strips of wood left behind.'],
      ['해설', 'Around then, Victor heard about electricity, and the old books suddenly seemed foolish to him.'],
      ['해설', 'At seventeen, he decided to go to the university in Ingolstadt, Germany.'],
      ['해설', 'Just before he left, Elizabeth caught scarlet fever. His mother stayed by her side and nursed her.'],
      ['해설', 'Elizabeth recovered, but his mother caught the illness and never rose again.'],
      ['어머니', 'I hoped to see you two united one day. Elizabeth, please take my place with the younger children.'],
      ['클레르발', 'I want to go with you, but my father says I must learn business first.'],
      ['엘리자베스', 'Write to us often, Victor. We will all be waiting for you.'],
      ['해설', 'In Ingolstadt, Victor attended the lectures of Waldman, a professor of chemistry.'],
      ['발트만', 'The old masters promised impossible things. Modern scientists promise little, yet they truly perform miracles.'],
      ['발트만', 'We have learned how the blood moves, and even the nature of the air we breathe.'],
      ['빅터', 'I will go further. I will reveal the deepest mysteries of creation to the world.'],
      ['해설', 'That night, Victor could not sleep. His fate was being decided.'],
      ['해설', 'Next time, Victor touches the secret of life and finally faces a terrible result.'],
      ['해설', 'Mary Shelley was born in London in 1797. Her father was the thinker William Godwin.'],
    ],
  },

  'fk-03': {
    title: 'Frankenstein, Part 3',
    names: { 해설: 'Narrator', 빅터: 'Victor', 클레르발: 'Henry Clerval' },
    outro: [
      'What does it mean that Victor ran away at the very moment his dream came true?',
      'How do you feel when you compare the newly awake being reaching out with Victor’s reaction?',
      'How much responsibility should a person take for the things they create?',
    ],
    lines: [
      ['해설', 'Last time, Victor began to pour his whole heart into natural science at the University of Ingolstadt.'],
      ['해설', 'He studied chemistry and anatomy like a madman. After two years, even his professors were amazed.'],
      ['해설', 'He wanted to know where life came from. To learn that, he first had to understand death.'],
      ['해설', 'Day and night he visited graveyards and vaults, watching how bodies decayed.'],
      ['해설', 'Then one day, he believed he had found a way to give life to lifeless matter.'],
      ['빅터', 'At last I have found it! The secret of putting breath into a body that does not breathe!'],
      ['해설', 'Victor never told anyone his method. Even to Walton, he refused to explain it.'],
      ['해설', 'Small parts were hard to work with, so he decided to make a huge body about eight feet tall.'],
      ['해설', 'An attic room became his workshop. He collected materials from dissecting rooms and slaughterhouses.'],
      ['빅터', 'A new species will bless me as its creator. I will be their father.'],
      ['해설', 'He did not notice the seasons change. He stopped writing to his family and grew thinner and thinner.'],
      ['해설', 'On a dreary night in November, at one in the morning, rain beat against the window. The candle was nearly out.'],
      ['해설', 'In the dim light, the being opened a dull yellow eye. It breathed hard, and its limbs began to move.'],
      ['해설', 'Victor had tried to make its face beautiful. But once it moved, it looked horrible.'],
      ['해설', 'Veins showed under its yellow skin, and its shiny black hair made it even more frightening.'],
      ['빅터', 'What have I done? Is this what my dream of two years looks like?'],
      ['해설', 'Victor rushed out of the room to his bedroom. He fell asleep exhausted but had nightmares.'],
      ['해설', 'When he opened his eyes, the being had lifted the bed curtain and was looking down at him.'],
      ['해설', 'It held out a hand and muttered something. Instead of answering, Victor ran down the stairs.'],
      ['해설', 'He spent the night in the courtyard. At dawn, he wandered the rainy streets with no goal.'],
      ['해설', 'Then a coach stopped, and a familiar face stepped out.'],
      ['클레르발', 'Victor! I finally persuaded my father, so I came to study too. But why do you look so ill?'],
      ['해설', 'When the two returned to Victor’s rooms, they were empty. The being was gone.'],
      ['해설', 'Victor laughed wildly with relief and then collapsed. He had a serious nervous fever.'],
      ['해설', 'For months, Clerval stayed by his side and nursed him.'],
      ['클레르발', 'Here is a letter from Elizabeth. She is desperate to hear from you.'],
      ['해설', 'By spring, Victor was up again, but he shook at the mere sight of his equipment. He never shared his secret.'],
      ['해설', 'Next time, Victor receives tragic news from home and hurries back to Geneva.'],
      ['해설', 'This novel began in the summer of 1816, with a ghost story contest at the Villa Diodati by Lake Geneva.'],
    ],
  },

  'fk-04': {
    title: 'Frankenstein, Part 4',
    names: { 해설: 'Narrator', 알퐁스: 'Alphonse Frankenstein', 빅터: 'Victor', 에르네스트: 'Ernest Frankenstein', 엘리자베스: 'Elizabeth', 쥐스틴: 'Justine Moritz' },
    outro: [
      'How is Victor’s silence, though he knew the truth, connected to Justine’s death?',
      'How does the figure revealed by lightning show Victor’s fear and guilt?',
      'Where do we still see people judged guilty only by evidence and rumor today?',
    ],
    lines: [
      ['해설', 'Last time, Victor created life, but he fled in horror and was sick for a long time.'],
      ['해설', 'The next May, a letter came from his father. Victor’s youngest brother, William, was dead.'],
      ['해설', 'William had gone missing while playing in the fields of Plainpalais and was found dead that night.'],
      ['해설', 'There were finger marks on his neck. A small picture of his mother that he carried was missing.'],
      ['알퐁스', 'Victor, come home quickly and comfort Elizabeth. She blames herself and cannot stop crying.'],
      ['해설', 'Victor set off at once. When he reached Geneva, the city gates were already shut.'],
      ['해설', 'He went to the fields where his brother had died. Thunder rolled in the sky above the lake.'],
      ['해설', 'In a flash of lightning, a huge figure appeared behind a tree. It was the being Victor had made.'],
      ['빅터', 'It is him. He is the one who took my brother’s life.'],
      ['해설', 'In an instant, the figure climbed the steep side of Mont Salève and vanished into the dark.'],
      ['해설', 'Victor told no one. His story would surely sound like the ravings of a madman.'],
      ['에르네스트', 'Brother, they have caught the murderer. But I cannot believe it. It is Justine.'],
      ['해설', 'Justine was a servant who had lived with the family for years. The picture was found in her dress.'],
      ['엘리자베스', 'Justine could never do that. She loved William like her own little brother.'],
      ['빅터', 'She is innocent. The real murderer is someone else.'],
      ['해설', 'But Victor could never bring himself to say who that murderer was.'],
      ['해설', 'At the trial, Justine said the gates were shut that night, so she slept in a barn.'],
      ['쥐스틴', 'I do not know how the picture got into my dress. Only God knows.'],
      ['해설', 'Elizabeth stood up in court and spoke of Justine’s good character, but it was no use.'],
      ['해설', 'Before the verdict, Justine confessed. People nodded as if they had expected it.'],
      ['해설', 'Elizabeth and Victor visited her in prison.'],
      ['쥐스틴', 'I did not do it. The priest kept pressing me and said I would be punished if I did not confess.'],
      ['쥐스틴', 'Since you believe me, miss, I can face my end calmly now.'],
      ['엘리자베스', 'Justine, we will never forget you. Never.'],
      ['해설', 'The next day, Justine was executed. Victor felt that both deaths had come from him.'],
      ['해설', 'He could not sleep. Night after night, he rowed alone across the lake.'],
      ['알퐁스', 'Victor, too much grief becomes a burden to those who are still alive.'],
      ['해설', 'Victor could not answer. His heart was full of regret and hatred.'],
      ['해설', 'Next time, Victor meets the being he created on a glacier in the Alps.'],
      ['해설', 'When Mary Shelley began writing this novel in 1816, she was eighteen years old.'],
    ],
  },

  'fk-05': {
    title: 'Frankenstein, Part 5',
    names: { 해설: 'Narrator', 빅터: 'Victor', 피조물: 'The Creature' },
    outro: [
      'The creature says he was good until misery changed him. Do you agree with him?',
      'What might it symbolize when the creature learns warmth and pain together from a fire?',
      'How are people who throw stones because of someone’s looks similar to scenes in our society?',
    ],
    lines: [
      ['해설', 'Last time, William was killed, and innocent Justine was executed for the crime.'],
      ['해설', 'Unable to bear his pain, Victor went alone to the valley of Chamonix in the Alps.'],
      ['해설', 'He climbed Montanvert and looked down on the great glacier called the Sea of Ice.'],
      ['해설', 'Then a figure crossed the cracks in the glacier, moving far faster than any man.'],
      ['빅터', 'How dare you come near me? Go away, now!'],
      ['피조물', 'I expected this welcome. People hate those who are wretched.'],
      ['피조물', 'But even you, who made me, hate me.'],
      ['해설', 'Victor sprang at him, but the creature easily stepped aside.'],
      ['피조물', 'Calm down. I am bigger and stronger than you, but I will not fight you.'],
      ['피조물', 'I was good and kind at first. Misery made me evil.'],
      ['피조물', 'Hear my whole story. You can judge me after that.'],
      ['해설', 'Victor hesitated. For the first time, he thought about what a creator owes to his creation.'],
      ['해설', 'They went into a mountain hut, lit a fire, and sat facing each other. The creature’s story began.'],
      ['피조물', 'When I first opened my eyes, light, sound and smell rushed in together. I could not tell them apart.'],
      ['피조물', 'I put on a coat from your room, went out, and reached a forest near Ingolstadt.'],
      ['피조물', 'When hungry, I ate berries. When thirsty, I drank from a stream. I was cold and afraid, and I wept.'],
      ['피조물', 'One day I found a fire left by travelers. I put my hand in and cried out in pain.'],
      ['피조물', 'That day I learned that the thing that gives warmth can also give pain.'],
      ['해설', 'Looking for food, he entered a hut. An old man inside screamed and ran away.'],
      ['해설', 'In the next village, people shouted and threw stones. Wounded, he fled into the fields.'],
      ['피조물', 'That day I learned that people were terrified just to see me, though I did not know why.'],
      ['해설', 'He hid in a low shed attached to a cottage. Through a crack in the wall, he could see inside.'],
      ['해설', 'A blind old man lived there with a young brother and sister. They were poor, but the home felt gentle.'],
      ['피조물', 'When the old man played music, the girl cried. For the first time, I felt joy and sorrow together.'],
      ['피조물', 'I decided to spend the winter there, watching that family.'],
      ['해설', 'Victor listened in silence. Outside the hut, the wind blew hard.'],
      ['해설', 'Next time, the creature learns to speak and read near that family, and begins to ask who he is.'],
      ['해설', 'The novel’s subtitle is The Modern Prometheus, after the Titan in Greek myth who gave fire to humans.'],
    ],
  },

  'fk-06': {
    title: 'Frankenstein, Part 6',
    names: { 해설: 'Narrator', 피조물: 'The Creature', 펠릭스: 'Felix De Lacey', 아가사: 'Agatha De Lacey', 드라세: 'Old De Lacey', 사피: 'Safie' },
    outro: [
      'Did learning words and letters bring the creature joy, or a deeper loneliness?',
      'How does the scene where he first sees himself in a pool become a turning point?',
      'How much has the idea that money, family and name decide a person’s worth disappeared today?',
    ],
    lines: [
      ['해설', 'Last time, Victor met the creature on the glacier, and the creature began to tell his story.'],
      ['해설', 'In the cottage he watched lived old De Lacey, his son Felix, and his daughter Agatha.'],
      ['해설', 'The family was very poor. The young brother and sister often gave their own food to their father.'],
      ['해설', 'When the creature saw this, he stopped taking their food at night.'],
      ['해설', 'Instead, he gathered firewood in the forest and piled it at their door.'],
      ['펠릭스', 'Agatha, look at this! Someone stacked all this wood here during the night.'],
      ['아가사', 'Some kind person must be helping us.'],
      ['해설', 'The creature realized that the sounds they made to each other carried meaning.'],
      ['해설', 'He learned words one by one, like fire, bread and wood. He learned father, sister and son too.'],
      ['해설', 'One day, he saw his own reflection in a clear pool for the first time.'],
      ['피조물', 'At first I could not believe it was me. Then deep despair washed over me.'],
      ['해설', 'In spring, a stranger arrived on horseback. Felix’s face lit up with joy.'],
      ['해설', 'She was Safie, an Arabian woman. She did not know their language at all.'],
      ['해설', 'While Felix taught Safie to speak and read, the creature learned too, from behind the wall.'],
      ['해설', 'Felix read aloud Volney’s Ruins of Empires and told her the history of many nations.'],
      ['피조물', 'I learned that humans can be so noble and, at the same time, so cruel.'],
      ['피조물', 'People value wealth and family. I had neither. I did not even have a name.'],
      ['해설', 'He also overheard the family’s past. They had once been a well-off family in Paris.'],
      ['해설', 'Felix had freed a Turkish merchant who was unjustly sentenced to death. Safie was his daughter.'],
      ['해설', 'When this came out, the family lost everything and was driven from France. The merchant broke his promise.'],
      ['해설', 'The novel shows the merchant as untrustworthy, a view mixed with the prejudice of Europe at that time.'],
      ['해설', 'Safie had left her father and traveled a long way alone to find Felix.'],
      ['드라세', 'My children, how good it is to hear laughter in our home again.'],
      ['사피', 'Now I want to live here freely, as I choose.'],
      ['해설', 'The creature came to love them. Someday, he wanted to show himself to them.'],
      ['피조물', 'If they could see my heart beyond my looks, I believed I could have a family too.'],
      ['피조물', 'But who am I? Where did I come from, and what was I born for?'],
      ['해설', 'Next time, the creature gathers his courage and appears before the blind old man.'],
      ['해설', 'In 1831, Mary Shelley published a revised edition with changes to the text and a new introduction.'],
    ],
  },

  'fk-07': {
    title: 'Frankenstein, Part 7',
    names: { 해설: 'Narrator', 피조물: 'The Creature', 드라세: 'Old De Lacey', 윌리엄: 'William Frankenstein', 빅터: 'Victor' },
    outro: [
      'Why did the creature feel closer to Satan than to Adam?',
      'What does it mean that only the blind old man welcomed the creature warmly?',
      'What can a person and a society do so that repeated rejection does not turn into rage?',
    ],
    lines: [
      ['해설', 'Last time, the creature learned to speak and read while watching the De Lacey family.'],
      ['해설', 'One day in the forest, he found a leather bag. Inside were three books.'],
      ['해설', 'They were Milton’s Paradise Lost, Plutarch’s Lives, and Goethe’s The Sorrows of Young Werther.'],
      ['피조물', 'Adam in Paradise Lost was made by God, but he was not alone like me.'],
      ['피조물', 'I felt more like Satan. When I saw happy people, jealousy boiled inside me.'],
      ['해설', 'In the pocket of the coat from Victor’s room, he found some papers. It was Victor’s journal.'],
      ['피조물', 'It described the four months before you made me. It also showed how much you hated me.'],
      ['피조물', 'Cursed creator! Why did you make me so hideous?'],
      ['해설', 'Near the end of winter, while the young people were out, he visited the blind old man.'],
      ['드라세', 'Who is there? Come in and warm yourself. I am blind, so I cannot welcome you properly.'],
      ['피조물', 'I am a lonely traveler looking for friends. I fear they will be frightened when they see me.'],
      ['드라세', 'If your heart is true, do not despair. If I can help you, I will.'],
      ['해설', 'Just then, Felix, Safie and Agatha came back. Agatha fainted, and Safie ran outside.'],
      ['해설', 'Felix tore the creature away from the old man’s knees and struck him hard with a stick.'],
      ['해설', 'The creature could have fought back. Instead, he fled to his shed.'],
      ['해설', 'Days later, the family left the cottage. The creature set the empty house on fire and went away.'],
      ['피조물', 'That day, I swore hatred against all humans, and above all against you, my maker.'],
      ['해설', 'He headed for Geneva, the hometown named in the journal. He walked only at night.'],
      ['해설', 'On the way, he saved a girl who had fallen into a river. But her companion shot at him.'],
      ['피조물', 'My reward for saving a human life was a bullet in my shoulder.'],
      ['해설', 'Near Geneva, he caught hold of a little boy. He believed a child would have no prejudice.'],
      ['윌리엄', 'Let me go! My father is a Frankenstein! You will be punished!'],
      ['해설', 'At that name, the creature’s rage exploded. The boy died on the spot.'],
      ['해설', 'He took the boy’s little picture and slipped it into the dress of Justine, who was asleep in a barn.'],
      ['피조물', 'Make me a mate who looks like me. Then we will leave the world of humans forever.'],
      ['피조물', 'We will live quietly on the wide plains of South America, eating fruit and berries.'],
      ['빅터', 'Very well. I promise. But you must never appear before people again.'],
      ['해설', 'Next time, Victor travels to a faraway Scottish island to make a second life.'],
      ['해설', 'Paradise Lost, which the creature read, is an epic poem published by the English poet John Milton in 1667.'],
    ],
  },

  'fk-08': {
    title: 'Frankenstein, Part 8',
    names: { 해설: 'Narrator', 알퐁스: 'Alphonse Frankenstein', 빅터: 'Victor', 엘리자베스: 'Elizabeth', 클레르발: 'Henry Clerval', 피조물: 'The Creature', 어부: 'Fisherman' },
    outro: [
      'Was Victor’s choice to destroy the second body a duty to humanity, or another betrayal?',
      'How does the creature’s grinning face at the window make this scene more frightening?',
      'When we cannot know all the results of new technology, what should tell us to stop?',
    ],
    lines: [
      ['해설', 'Last time, the creature told his past and demanded that Victor make him a mate.'],
      ['해설', 'Back in Geneva, Victor could not bring himself to begin the work for weeks.'],
      ['알퐁스', 'Victor, does marrying Elizabeth trouble you? Is there someone else?'],
      ['빅터', 'No. I love Elizabeth. But first I must finish something.'],
      ['해설', 'He said he needed to learn from scholars in England and set off on a journey. Clerval went with him.'],
      ['엘리자베스', 'You must come back, Victor. When you return, let us be married.'],
      ['해설', 'They traveled down the Rhine, stayed in London, and visited Oxford and Scotland.'],
      ['클레르발', 'Look at these mountains and rivers! There is so much to see in the world.'],
      ['해설', 'Victor could not share his friend’s joy. He knew the creature was following them.'],
      ['해설', 'He left Clerval in Perth and went alone to a remote island in the Orkneys.'],
      ['해설', 'The rocky island had only a few huts. He rented one and began his work.'],
      ['빅터', 'Will she keep his promise to leave with him? What if they come to hate each other?'],
      ['빅터', 'And if they have children, will a race be born that threatens all of humanity?'],
      ['해설', 'One night he looked up. The creature was watching him through the window, grinning.'],
      ['해설', 'Trembling, Victor tore apart the second body, which was almost finished.'],
      ['해설', 'The creature howled and vanished. A few hours later, he opened the door and came in.'],
      ['피조물', 'You have broken your promise. I suffered so much to follow you here.'],
      ['빅터', 'I will never make another being like you. Get out!'],
      ['피조물', 'You are my creator, but now I am your master. Wait and see.'],
      ['피조물', 'And remember this. I will be with you on your wedding night.'],
      ['해설', 'Victor thought those words meant the creature would come for his life.'],
      ['해설', 'At dawn, he put the pieces in a basket. He rowed out in a small boat and sank them in the sea.'],
      ['해설', 'While he slept in the boat, the wind grew strong and drove him to an unknown shore.'],
      ['해설', 'It was Ireland. The villagers surrounded him and took him to the magistrate.'],
      ['어부', 'Last night, a young man was found dead on the beach. There were finger marks on his neck.'],
      ['해설', 'Victor was led into the room where the body lay. The man lying there was Clerval.'],
      ['빅터', 'Henry, even you, because of me. I did this to you.'],
      ['해설', 'Victor fainted on the spot. Next time, he finally reaches his wedding night.'],
      ['해설', 'Mary Shelley’s mother, Mary Wollstonecraft, was a thinker who wrote A Vindication of the Rights of Woman.'],
    ],
  },

  'fk-09': {
    title: 'Frankenstein, Part 9',
    names: { 해설: 'Narrator', 커윈: 'Mr. Kirwin', 알퐁스: 'Alphonse Frankenstein', 빅터: 'Victor', 엘리자베스: 'Elizabeth', 피조물: 'The Creature' },
    outro: [
      'What kind of revenge logic made the creature attack the people Victor loved, instead of Victor himself?',
      'How does Victor’s misreading of the threat make the tragedy even deeper?',
      'Does revenge really heal a wound, or does it destroy the avenger as well?',
    ],
    lines: [
      ['해설', 'Last time, Victor destroyed the second body, and Clerval was found dead in Ireland.'],
      ['해설', 'For two months in prison, Victor suffered from fever and talked wildly.'],
      ['해설', 'The magistrate, Mr. Kirwin, cared for him kindly and sent word to his family in Geneva.'],
      ['커윈', 'You have a visitor. It is your father.'],
      ['알퐁스', 'Victor, Elizabeth and Ernest are safe. Let us go home.'],
      ['해설', 'It was shown that Victor was on the Orkneys when Clerval died, so he was set free.'],
      ['해설', 'All the way home, Victor kept thinking about the creature’s words.'],
      ['빅터', 'He said he would come on my wedding night. Very well. That night, one of us will meet his end.'],
      ['해설', 'Before he reached home, Elizabeth wrote to ask if his heart belonged to someone else.'],
      ['빅터', 'Elizabeth, I have a terrible secret. I will tell you everything the day after our wedding.'],
      ['해설', 'Ten days later, they were married. Victor always carried pistols and a dagger.'],
      ['해설', 'The couple crossed the lake by boat and stayed at an inn in Evian.'],
      ['엘리자베스', 'Why do you look so uneasy today? What are you so afraid of?'],
      ['빅터', 'Once tonight is over, all will be well. Go to our room first and rest.'],
      ['해설', 'Believing the creature was after him, Victor searched the halls and every corner of the house.'],
      ['해설', 'Then a sharp scream came from the room.'],
      ['해설', 'When Victor rushed in, Elizabeth was already lying dead on the bed.'],
      ['해설', 'Through the open window, he saw the creature’s face. It pointed mockingly at Elizabeth.'],
      ['해설', 'Victor fired his pistol, but the creature plunged into the lake and disappeared.'],
      ['해설', 'Only then did Victor understand. The creature had never aimed at him, but at those he loved.'],
      ['해설', 'His old father could not bear the news. A few days later, he died in Victor’s arms.'],
      ['해설', 'For months, Victor lost his mind. People kept him locked in a lonely cell.'],
      ['해설', 'When he recovered, he told a judge everything, but the judge only half believed him.'],
      ['해설', 'Victor took what money was left and left Geneva. First, he knelt at his family’s graves.'],
      ['빅터', 'Before those who sleep here, I swear it. I will find him and end this.'],
      ['해설', 'Loud laughter rang out in the dark. Then a low voice whispered close to his ear.'],
      ['피조물', 'I am satisfied, miserable wretch. You have decided to live and chase me. That is enough for me.'],
      ['해설', 'Under the moon, a huge figure ran away faster than any man.'],
      ['해설', 'Next time, Victor’s chase leads to the icy northern sea, and the story returns to Walton’s ship.'],
      ['해설', 'Mary Shelley’s husband, the poet Percy Bysshe Shelley, drowned in 1822 when his boat sank in a storm off Italy.'],
    ],
  },

  'fk-10': {
    title: 'Frankenstein, Part 10',
    names: { 해설: 'Narrator', 피조물: 'The Creature', 빅터: 'Victor', 선원: 'Sailor', 월턴: 'Robert Walton' },
    outro: [
      'Who do you think was the real monster in this story, and why?',
      'How do the last words of the nameless creature connect to Victor’s warning in Part 1?',
      'What questions might this novel ask today’s scientists and engineers who create new things?',
    ],
    lines: [
      ['해설', 'Last time, the creature took Elizabeth’s life, and Victor swore revenge.'],
      ['해설', 'Victor chased the creature down the Rhone to the Mediterranean, to the Black Sea, and across Russia.'],
      ['해설', 'The creature left signs on purpose. He carved words into tree bark and stones to show the way.'],
      ['피조물', 'Follow me. In the icy lands of the north, you will taste cold and hunger.'],
      ['해설', 'Victor got a sledge and dogs and went out onto the frozen sea. Once, he saw the creature ahead.'],
      ['해설', 'But the ice broke, and water opened between them. Victor was left on a floating piece of ice.'],
      ['해설', 'Just then, Walton’s ship found him. This is how the story joins the first letter.'],
      ['빅터', 'If I die, find him and finish it. Do not be fooled by his clever words.'],
      ['해설', 'By then, the ship was trapped in the ice again. The sailors feared they would all freeze to death.'],
      ['선원', 'Captain, promise us that when the ice breaks, we will sail straight back south.'],
      ['빅터', 'You came on this ship to do something glorious. Will you turn back because you fear danger?'],
      ['해설', 'The sailors looked at one another in silence. Walton thought for a long time.'],
      ['월턴', 'I cannot risk their lives for my dream. When the ice breaks, we will return.'],
      ['해설', 'In September, the ice split and a path opened. The sailors cheered, and the ship turned south.'],
      ['해설', 'Victor grew weaker and weaker. With his last strength, he spoke to Walton.'],
      ['빅터', 'Seek happiness in a quiet life. Stay away from the desire for fame.'],
      ['빅터', 'And yet, perhaps someone else may succeed.'],
      ['해설', 'That night, Victor died quietly. A faint smile was left on his lips.'],
      ['해설', 'At midnight, a strange sound came from Victor’s cabin. A huge figure stood beside the body.'],
      ['피조물', 'He too has fallen because of me. Forgive me. But now he can never answer.'],
      ['월턴', 'You are sorry now? You should have been sorry while he was alive.'],
      ['피조물', 'I wanted to be loved. Without it, I became a monster. Still, my crimes cannot be washed away.'],
      ['피조물', 'I will go to the farthest north and burn myself on a fire. No one will remember me.'],
      ['해설', 'He jumped through the cabin window onto an ice raft beside the ship.'],
      ['해설', 'The raft was carried away by the waves and soon lost in the darkness.'],
      ['해설', 'On the ship heading south, Walton finished his last letter to his sister.'],
      ['해설', 'So the story of the creator and the created ended on a cold sea.'],
      ['해설', 'The being who never even got a name still asks us what responsibility means.'],
      ['해설', 'Mary Shelley died in London in 1851.'],
    ],
  },
};
