// 청소년 영어 원고 (중학생 이상). 키 = stories/teen-sg1.js 의 이야기 id.
// 나관중 『삼국지연의』(퍼블릭 도메인)를 한국어 각색의 흐름대로 쉬운 영어로 새로 씀. 이름은 병음, 연의와 정사 구분 해설 유지.
export default {
  'sg-01': {
    title: 'Romance of the Three Kingdoms, Part 1',
    names: { 해설: 'Narrator', 장각: 'Zhang Jue', 유비: 'Liu Bei', 장비: 'Zhang Fei', 관우: 'Guan Yu' },
    outro: [
      'Liu Bei had nothing, yet he won the hearts of Guan Yu and Zhang Fei. Why do you think that was?',
      'What feeling does the peach garden in full bloom add to the three men’s oath?',
      'When you choose friends who share your dreams, what matters most to you?',
    ],
    lines: [
      ['해설', 'The story of the Three Kingdoms begins as the Han dynasty, nearly four hundred years old, was fading away.'],
      ['해설', 'In the palace, eunuchs used the emperor’s power to sell government posts. The people suffered from hunger and heavy taxes.'],
      ['해설', 'Then Zhang Jue of Julu spread a teaching called the Way of Great Peace. Hundreds of thousands followed him.'],
      ['장각', 'The age of the blue sky is over. Now the yellow sky will rise!'],
      ['해설', 'His followers tied yellow scarves around their heads. People called them the Yellow Turbans.'],
      ['해설', 'As the rebels attacked government offices, the court ordered every town to gather volunteer soldiers.'],
      ['해설', 'A notice went up at the gate of Zhuo County. One man stood in front of it for a long time.'],
      ['해설', 'It was Liu Bei, who made straw sandals and mats to support his widowed mother. He was a distant relative of the Han emperors.'],
      ['유비', 'The country is falling apart, and here I am, weaving mats.'],
      ['장비', 'Why does a grown man sigh instead of doing something for his country?'],
      ['해설', 'It was Zhang Fei, with round eyes and a beard like a tiger’s. He had grown rich by selling meat and wine.'],
      ['유비', 'I want to fight the rebels and save the people, but I have no power and no money.'],
      ['장비', 'I have money! Let us gather the young men of the town and do something great together.'],
      ['해설', 'As the two men talked in an inn, a tall man pushing a cart came in and called out.'],
      ['관우', 'Innkeeper, bring me a cup of wine, quickly. I am on my way to join the volunteer army.'],
      ['해설', 'He had a face as red as a jujube and a long beard down to his chest. It was Guan Yu from Hedong.'],
      ['관우', 'I punished a cruel bully in my hometown, and I have been on the run for years.'],
      ['유비', 'We share the same goal. Will you join us?'],
      ['장비', 'There is a peach garden behind my house. Tomorrow, let us swear an oath there to heaven and earth!'],
      ['해설', 'The next day, among the peach blossoms, the three men set out offerings and burned incense side by side.'],
      ['유비', 'Though our family names differ, from today we are brothers. We will help the country and bring peace to the people.'],
      ['관우', 'We were not born on the same day, but we hope to die on the same day.'],
      ['장비', 'If anyone breaks this oath, may heaven and men punish him together!'],
      ['해설', 'By age, Liu Bei became the eldest brother, Guan Yu the second, and Zhang Fei the youngest.'],
      ['해설', 'Passing horse traders were moved and gave them horses and iron. A blacksmith made their weapons.'],
      ['해설', 'Liu Bei took a pair of swords, and Guan Yu the Green Dragon Blade. Zhang Fei held a snake-headed spear.'],
      ['해설', 'With about five hundred men, they scattered a large Yellow Turban army in their first battle.'],
      ['장비', 'Brothers, this is only the beginning! Let us sweep away these yellow scarves.'],
      ['해설', 'But a general they rescued looked down on them because they had no official rank. His name was Dong Zhuo.'],
      ['해설', 'The Peach Garden Oath appears in the novel. The official history only says the three men were as close as brothers and shared one bed.'],
    ],
  },

  'sg-02': {
    title: 'Romance of the Three Kingdoms, Part 2',
    names: { 해설: 'Narrator', 동탁: 'Dong Zhuo', 조조: 'Cao Cao', 진궁: 'Chen Gong', 원소: 'Yuan Shao', 관우: 'Guan Yu' },
    outro: [
      'What do Cao Cao’s words after killing Lu Boshe’s family reveal about his character?',
      'Why does the scene of the still-warm wine feel stronger than a long description of the battle?',
      'Have you ever misunderstood someone because of suspicion? What should you have checked first?',
    ],
    lines: [
      ['해설', 'Last time, Liu Bei, Guan Yu, and Zhang Fei became sworn brothers and fought the Yellow Turbans.'],
      ['해설', 'The rebellion died down, but inside the palace, eunuchs and ministers fought each other until both sides fell.'],
      ['해설', 'In the chaos, Dong Zhuo, a general from the far west, marched into the capital, Luoyang, with a huge army.'],
      ['동탁', 'The emperor is weak. The Prince of Chenliu is clever, so I will make him the new emperor.'],
      ['해설', 'The ministers objected, but Dong Zhuo replaced the emperor anyway and took control of the court as chancellor.'],
      ['해설', 'He walked through the palace wearing a sword, and his soldiers freely robbed the people.'],
      ['해설', 'At a feast at minister Wang Yun’s house, the old officials wept. But one young officer clapped and laughed.'],
      ['조조', 'Will crying bring Dong Zhuo down? Lend me a fine sword, and I will kill him myself.'],
      ['해설', 'Cao Cao hid Wang Yun’s precious sword and went to Dong Zhuo’s bedroom. The heavy Dong Zhuo was lying on his bed.'],
      ['해설', 'As Cao Cao drew the sword, Dong Zhuo saw its flash in a mirror and turned around.'],
      ['동탁', 'Mengde, what are you doing?'],
      ['조조', 'I found a rare sword, Chancellor, and I wanted to give it to you.'],
      ['해설', 'Cao Cao handed over the sword. Then he said he would try out a new horse and rode straight out of Luoyang.'],
      ['해설', 'Too late, Dong Zhuo realized he had been fooled. He sent Cao Cao’s portrait to every town in the land.'],
      ['해설', 'Cao Cao was caught in Zhongmou County. That night, the county magistrate, Chen Gong, secretly called him in.'],
      ['진궁', 'The chancellor treated you well. Why did you risk your life?'],
      ['조조', 'I am a servant of the Han. I will go home, call on the whole land, and attack Dong Zhuo.'],
      ['진궁', 'If you truly mean it, I will give up my post and follow you.'],
      ['해설', 'The two stayed with Lu Boshe, an old friend of Cao Cao’s father. Then they heard a knife being sharpened.'],
      ['해설', 'Filled with suspicion, Cao Cao attacked the family. But they had only been getting ready to kill a pig for their guests.'],
      ['해설', 'On the road, they met Lu Boshe coming back with wine. Fearing trouble later, Cao Cao killed him too.'],
      ['진궁', 'You knew it was a mistake, and you still did it? This is a terrible wrong!'],
      ['조조', 'I would rather betray the world than let the world betray me.'],
      ['해설', 'That night, Chen Gong left Cao Cao asleep and went away alone.'],
      ['해설', 'Back home, Cao Cao raised an army and sent out a call. Many lords gathered, with Yuan Shao as their leader.'],
      ['원소', 'Dong Zhuo’s general Hua Xiong has beaten our generals one after another. Who will face him?'],
      ['관우', 'I will go out and defeat Hua Xiong.'],
      ['해설', 'Yuan Shao laughed at him as a mere archer. But Cao Cao poured a cup of warm wine and handed it to Guan Yu.'],
      ['관우', 'Please set the wine down for now. I will drink it when I return.'],
      ['해설', 'Before the drums had even died down, Guan Yu came back. The wine Cao Cao poured was still warm.'],
      ['해설', 'Cornered, Dong Zhuo burned Luoyang and dragged the emperor west to Chang’an. There, a new plan began to grow.'],
      ['해설', 'In the novel, Guan Yu kills Hua Xiong. In the official history, it was Sun Jian’s army that killed him.'],
    ],
  },

  'sg-03': {
    title: 'Romance of the Three Kingdoms, Part 3',
    names: { 해설: 'Narrator', 왕윤: 'Wang Yun', 초선: 'Diaochan', 여포: 'Lu Bu', 동탁: 'Dong Zhuo' },
    outro: [
      'Did Wang Yun use Diaochan for the good of the country, or did he use a person as a tool?',
      'How could the chain plan split two men apart without a single sword?',
      'When rumors try to come between two people, how can we find the truth?',
    ],
    lines: [
      ['해설', 'Last time, Cao Cao failed to kill Dong Zhuo and fled. Dong Zhuo burned Luoyang and moved to Chang’an.'],
      ['해설', 'In Chang’an, nothing could stop Dong Zhuo. Beside him always stood his adopted son Lu Bu, the greatest warrior in the land.'],
      ['해설', 'Minister Wang Yun could not sleep at night. By force, he could never beat Dong Zhuo or Lu Bu.'],
      ['해설', 'One moonlit night, he heard a sigh in the garden. It was Diaochan, a singing girl raised in his house.'],
      ['왕윤', 'Diaochan, what worry makes you sigh?'],
      ['초선', 'I see you worrying day and night, and I cannot help you. That pains me.'],
      ['왕윤', 'If the future of the Han were in your hands, what would you do?'],
      ['초선', 'If I can repay you for raising me, I will do anything.'],
      ['해설', 'Wang Yun told her his plan. It was the chain plan, linking two men with one ring to make them fight.'],
      ['해설', 'First he invited Lu Bu to a feast and had Diaochan pour his wine.'],
      ['여포', 'Who is this beautiful lady?'],
      ['왕윤', 'She is my daughter, Diaochan. If you like her, I will send her to you on a lucky day.'],
      ['해설', 'A few days later, Wang Yun invited Dong Zhuo and had Diaochan dance for him in the same way.'],
      ['동탁', 'I want to keep that girl by my side.'],
      ['왕윤', 'To offer her to you, Chancellor, is the greatest honor.'],
      ['해설', 'When he heard Diaochan had gone to Dong Zhuo’s house, Lu Bu rushed to Wang Yun.'],
      ['여포', 'You promised Diaochan to me. Why did you send her to the chancellor?'],
      ['왕윤', 'The chancellor took her himself and said he would give her to you. How could I refuse him?'],
      ['해설', 'But Dong Zhuo did not give her up. Whenever Diaochan met Lu Bu’s eyes, she looked sad and begged for help.'],
      ['초선', 'I wanted to serve you, General, but now there is nothing I can do.'],
      ['해설', 'One day at the Phoenix Pavilion, Dong Zhuo saw Diaochan and Lu Bu standing face to face.'],
      ['동탁', 'How dare you look at my woman!'],
      ['해설', 'Dong Zhuo threw a halberd at him. Lu Bu dodged and ran, and a deep crack opened between them.'],
      ['여포', 'The man I called father threw a weapon at me.'],
      ['왕윤', 'Your family name is Lu, and his is Dong. When he threw that halberd, where was a father’s love?'],
      ['해설', 'At last Lu Bu joined Wang Yun. A false message said the emperor would give up the throne, so Dong Zhuo went to the palace.'],
      ['동탁', 'Where is my son? Come and protect me!'],
      ['여포', 'I come with the emperor’s order to punish a traitor!'],
      ['해설', 'Lu Bu’s spear flashed, and Dong Zhuo, who had made the whole land tremble, fell at the palace gate.'],
      ['해설', 'People danced in the streets. But Dong Zhuo’s old followers were already planning to take Chang’an back.'],
      ['해설', 'Diaochan does not appear in the official history. It only says Lu Bu had a secret affair with one of Dong Zhuo’s maids.'],
    ],
  },

  'sg-04': {
    title: 'Romance of the Three Kingdoms, Part 4',
    names: { 해설: 'Narrator', 조조: 'Cao Cao', 장비: 'Zhang Fei', 진궁: 'Chen Gong', 여포: 'Lu Bu', 유비: 'Liu Bei' },
    outro: [
      'Cao Cao tried to save Chen Gong but executed Lu Bu. What does this tell us about his leadership?',
      'Liu Bei blamed the thunder for dropping his chopsticks. What skill with words and actions do you see?',
      'Have you seen that even a very talented person is hard to work with once trust is lost?',
    ],
    lines: [
      ['해설', 'Last time, Wang Yun and Diaochan’s chain plan led to Dong Zhuo’s death at Lu Bu’s hands.'],
      ['해설', 'But Dong Zhuo’s old followers retook Chang’an, and Lu Bu was driven out to wander from place to place.'],
      ['해설', 'Meanwhile, Cao Cao brought the young emperor to Xuchang. Now he could give orders in the emperor’s name.'],
      ['조조', 'If I serve the Son of Heaven, my words become the court’s words. Now I have a reason to attack anyone who disobeys.'],
      ['해설', 'Liu Bei, who ruled Xuzhou, took in the homeless Lu Bu. But Lu Bu saw his chance and seized Xuzhou.'],
      ['장비', 'Brother, why did you trust a man who repays kindness with betrayal? He has already betrayed two fathers!'],
      ['해설', 'Liu Bei turned to Cao Cao for help, and the two surrounded Lu Bu’s castle at Xiapi.'],
      ['해설', 'Beside Lu Bu was Chen Gong, who had left Cao Cao and now served as Lu Bu’s adviser.'],
      ['진궁', 'General, camp outside the walls. If we help each other from inside and outside, Cao Cao cannot last long.'],
      ['여포', 'My wife does not want me to leave. These walls are strong, so do not worry.'],
      ['해설', 'Again and again, Chen Gong’s plans were ignored. Cao Cao led river water in and flooded Xiapi.'],
      ['해설', 'Lu Bu’s tired officers tied him up while he slept and opened the gates. He was dragged to the White Gate Tower.'],
      ['여포', 'Lord Cao, let me lead your horsemen while you lead the foot soldiers. Then the land is easily yours.'],
      ['조조', 'Xuande, what do you think?'],
      ['유비', 'My lord, have you forgotten what happened to Ding Yuan and Dong Zhuo?'],
      ['여포', 'You big-eared man! Have you forgotten how I saved you with one arrow at the camp gate?'],
      ['해설', 'Cao Cao nodded, and Lu Bu lost his life. Even the greatest warrior had no place to stand once trust was gone.'],
      ['해설', 'Chen Gong was also captured. Cao Cao offered him a way to live, but Chen Gong held his head high.'],
      ['진궁', 'I left you because your heart was not right. I will keep my path by dying. Only take care of my old mother.'],
      ['해설', 'Cao Cao wept as he sent Chen Gong to his death. As promised, he cared for Chen Gong’s family to the end.'],
      ['해설', 'Back in Xuchang, Liu Bei quietly grew vegetables in his backyard to avoid Cao Cao’s suspicion.'],
      ['해설', 'One day, Cao Cao invited Liu Bei. Green plums and warm wine were set out in a pavilion.'],
      ['조조', 'Xuande, who do you think are the true heroes of this age?'],
      ['유비', 'Perhaps Yuan Shao in the north, Yuan Shu in Huainan, or Sun Ce in the east?'],
      ['조조', 'They are not heroes. A hero holds a great ambition in his heart and understands the ways of heaven and earth.'],
      ['조조', 'The only heroes in the world today are you and I.'],
      ['해설', 'At that moment, Liu Bei dropped his chopsticks. Just then, thunder roared in the sky.'],
      ['유비', 'The thunder was so loud that it startled me. How embarrassing.'],
      ['조조', 'Even a grown man fears thunder? Ha ha.'],
      ['해설', 'Cao Cao laughed it off, but from that day, Liu Bei counted the days until he could escape Xuchang.'],
      ['해설', 'At last, Liu Bei left Xuchang with an army. That choice would soon bring Guan Yu a great trial.'],
      ['해설', 'The official history also says Liu Bei dropped his chopsticks when Cao Cao called them the only two heroes.'],
    ],
  },

  'sg-05': {
    title: 'Romance of the Three Kingdoms, Part 5',
    names: { 해설: 'Narrator', 장료: 'Zhang Liao', 관우: 'Guan Yu', 조조: 'Cao Cao', 장비: 'Zhang Fei', 유비: 'Liu Bei' },
    outro: [
      'Guan Yu returned to Liu Bei after all of Cao Cao’s kindness. How would you judge that choice?',
      'When Cao Cao said not to chase Guan Yu, what calculation and what feeling were behind it?',
      'If you had to choose between someone who is kind to you and your first promise, what would guide you?',
    ],
    lines: [
      ['해설', 'Last time, Cao Cao’s talk of heroes shocked Liu Bei, and he finally escaped from Xuchang to Xuzhou.'],
      ['해설', 'Furious, Cao Cao attacked Xuzhou with a huge army. Liu Bei fled to Yuan Shao, and Zhang Fei went missing.'],
      ['해설', 'Guan Yu, who was guarding Liu Bei’s two wives at Xiapi, was trapped alone on a hill outside the walls.'],
      ['해설', 'Cao Cao’s general Zhang Liao, a friend of Guan Yu, climbed the hill alone.'],
      ['장료', 'Yunchang, if you die fighting here, who will protect your sisters-in-law? Who will keep the Peach Garden Oath?'],
      ['관우', 'If you promise me three things, I will lay down my weapon.'],
      ['관우', 'I surrender to the Han emperor, not to Cao Cao. And my sisters-in-law must be treated with respect.'],
      ['관우', 'And once I learn where my brother is, I will leave that very day, no matter how far.'],
      ['해설', 'Cao Cao hesitated, but he felt no promise was too much if he could win Guan Yu.'],
      ['해설', 'He held small feasts every three days and big ones every five, and sent silk and gold. Guan Yu locked it all away.'],
      ['해설', 'One day, Cao Cao gave him Red Hare, the horse Lu Bu once rode. For the first time, Guan Yu bowed deeply.'],
      ['조조', 'Gold and jewels did not move you, but you bow for one horse?'],
      ['관우', 'I hear it runs a thousand li a day. When I find my brother, I can reach him in a single day.'],
      ['해설', 'A shadow of disappointment crossed Cao Cao’s face. Around then, Yuan Shao’s general Yan Liang surrounded Baima.'],
      ['해설', 'Guan Yu rode Red Hare into the middle of the enemy and struck down Yan Liang in a single charge.'],
      ['해설', 'Soon after, news reached Guan Yu that Liu Bei was staying in Yuan Shao’s camp.'],
      ['관우', 'My brother is in the north! Now it is time to go.'],
      ['해설', 'Guan Yu went to say goodbye, but Cao Cao hung a sign on his gate refusing all visitors.'],
      ['해설', 'Guan Yu sealed up the gold, hung up his official seal, and set off guarding his sisters-in-law’s carriage.'],
      ['조조', 'He comes and goes openly. He is a true man. Do not chase him. Send him a silk robe for the road.'],
      ['해설', 'But the generals guarding the passes blocked his way, saying he had no travel pass.'],
      ['해설', 'As he passed five gates, six generals stood in his way. One by one, they all fell before his great blade.'],
      ['해설', 'At the town of Gucheng, he found Zhang Fei in control. But Zhang Fei pointed his spear at him.'],
      ['장비', 'I heard you surrendered to Cao Cao and took a post. Have you come to capture me too?'],
      ['관우', 'Brother, listen to me. How could I ever break our oath?'],
      ['해설', 'Just then, Cao Cao’s general Cai Yang came chasing Guan Yu. Guan Yu struck him down before the drum sounded three times.'],
      ['장비', 'Brother, I was wrong! Please forgive this foolish younger brother for doubting you.'],
      ['해설', 'Soon Liu Bei also reached Gucheng. The three brothers held hands and could not speak for a long time.'],
      ['유비', 'My brothers, now that we are together again, I fear nothing.'],
      ['해설', 'Meanwhile, Yuan Shao in the north and Cao Cao in Xuchang were getting ready to fight for the north.'],
      ['해설', 'The official history records Guan Yu killing Yan Liang at Baima. But the five passes and six generals appear only in the novel.'],
    ],
  },

  'sg-06': {
    title: 'Romance of the Three Kingdoms, Part 6',
    names: { 해설: 'Narrator', 원소: 'Yuan Shao', 전풍: 'Tian Feng', 순욱: 'Xun Yu', 조조: 'Cao Cao', 허유: 'Xu You' },
    outro: [
      'Yuan Shao jailed Tian Feng, but Cao Cao burned the letters. What difference between the two leaders does this show?',
      'Why was attacking the food stores better than a head-on fight for Cao Cao’s smaller army?',
      'Between a friend who tells hard truths and one who only says nice things, whom do you listen to more?',
    ],
    lines: [
      ['해설', 'Last time, Guan Yu passed five gates and met Liu Bei and Zhang Fei again at Gucheng.'],
      ['해설', 'In the north, Yuan Shao ruled four provinces and raised a huge army. Cao Cao’s army was only a fraction of its size.'],
      ['원소', 'Cao Cao uses the emperor to do as he pleases. This time I will sweep away Xuchang in one blow.'],
      ['전풍', 'My lord, do not hurry. If we hold out and wear Cao Cao down, he will fall on his own.'],
      ['원소', 'Your cowardly words weaken my soldiers’ spirit! Throw him in prison.'],
      ['해설', 'The two armies faced each other at Guandu. Yuan Shao’s men built earth mounds and rained arrows from towers.'],
      ['해설', 'Cao Cao built stone-throwing carts to smash the towers. When Yuan Shao dug tunnels, Cao Cao dug a long ditch to stop them.'],
      ['해설', 'Months passed, and Cao Cao’s food began to run out. He wondered whether to pull back to Xuchang.'],
      ['순욱', 'Now the weak side has its hand on the strong side’s throat. Whoever steps back first will lose.'],
      ['조조', 'You are right. I will hold on here and wait for my chance.'],
      ['해설', 'Around then, Yuan Shao’s adviser Xu You suggested a surprise attack on Cao Cao, but Yuan Shao would not listen.'],
      ['해설', 'Then Xu You’s family members were jailed for a crime. So he turned against Yuan Shao and went to Cao Cao’s camp at night.'],
      ['해설', 'Hearing that Xu You had come, Cao Cao ran out barefoot to greet him, without even putting on his shoes.'],
      ['조조', 'Ziyuan, now that you are here, my cause is won!'],
      ['허유', 'How much food does your army have left?'],
      ['조조', 'Enough for a year.'],
      ['허유', 'Tell me the truth.'],
      ['조조', 'Ha ha, actually, only enough for one month.'],
      ['허유', 'All of Yuan Shao’s food is stored at Wuchao, and its guard is always drunk. Burn it, and Yuan Shao will fall.'],
      ['해설', 'Cao Cao himself led five thousand fast horsemen. Carrying Yuan Shao’s flags, they rode through the night.'],
      ['해설', 'At dawn, flames shot up at Wuchao. Mountains of food carts sank into the red fire.'],
      ['해설', 'Without food, Yuan Shao’s army collapsed, and his generals surrendered. Yuan Shao barely escaped across the river with a few hundred riders.'],
      ['해설', 'In Yuan Shao’s empty camp, Cao Cao’s men found a bundle of letters. Some of Cao Cao’s own officers had secretly written to Yuan Shao.'],
      ['조조', 'When Yuan Shao was strong, even I could barely hold on. How much harder for others? Burn them all.'],
      ['해설', 'Cao Cao burned the letters without reading them. His nervous officers bowed their heads at his generosity.'],
      ['해설', 'Meanwhile, in prison, Tian Feng heard that Yuan Shao had lost badly.'],
      ['전풍', 'If he had won, he might have spared me. Now that he has lost, his shame will not let me live.'],
      ['해설', 'Just as he said, Yuan Shao had him killed. A few years later, Yuan Shao died of illness, and Cao Cao became master of the north.'],
      ['해설', 'At that time, Liu Bei was staying in Jingzhou. He sighed at his fat thighs, for he no longer rode into battle. He still had no adviser.'],
      ['해설', 'The Battle of Guandu took place in 200. The official history also says Xu You’s defection and the Wuchao raid decided it.'],
    ],
  },

  'sg-07': {
    title: 'Romance of the Three Kingdoms, Part 7',
    names: { 해설: 'Narrator', 서서: 'Xu Shu', 동자: 'Servant Boy', 장비: 'Zhang Fei', 유비: 'Liu Bei', 관우: 'Guan Yu', 제갈량: 'Zhuge Liang' },
    outro: [
      'Liu Bei humbled himself and visited three times. What attitude does this show a leader needs?',
      'In what ways did Zhuge Liang’s plan to divide the land into three read the situation correctly?',
      'If there is someone you really want to learn from, what could you do to win their heart?',
    ],
    lines: [
      ['해설', 'Last time, Cao Cao defeated Yuan Shao at Guandu and took the north.'],
      ['해설', 'Liu Bei was staying in Xinye, a small town in Jingzhou. He was well over forty, but he had still achieved nothing.'],
      ['해설', 'Then Liu Bei gained an adviser named Xu Shu and beat Cao Cao’s army. So Cao Cao captured Xu Shu’s mother.'],
      ['서서', 'My mother is a hostage, so I must go. But let me recommend someone in my place.'],
      ['서서', 'He is Zhuge Liang of Longzhong, also called Kongming. People call him the Sleeping Dragon.'],
      ['서서', 'You cannot call him to come to you. You must go to see him yourself.'],
      ['해설', 'Liu Bei took gifts and went with Guan Yu and Zhang Fei to a thatched cottage in Longzhong.'],
      ['동자', 'My master left early this morning. I do not know when he will be back.'],
      ['해설', 'The first visit was for nothing. Some time later, on a day of heavy snow, Liu Bei set out again.'],
      ['장비', 'All this trouble on a cold day for one country scholar? Just send someone to fetch him.'],
      ['유비', 'If you are cold, go back first. I want to show my sincerity.'],
      ['해설', 'The second time, Zhuge Liang was also away. Liu Bei left a heartfelt letter and turned back.'],
      ['해설', 'When spring came in the new year, Liu Bei chose a good day and set out a third time.'],
      ['관우', 'Brother, maybe he refused twice because his fame is bigger than his skill.'],
      ['장비', 'If he acts proud again, I will tie him up with a rope and drag him here!'],
      ['유비', 'Even the wise kings of old humbled themselves to find good men. Never say such things again.'],
      ['동자', 'My master is home, but he is taking a nap right now.'],
      ['해설', 'Liu Bei said not to wake him and stood below the steps with his hands together. He waited there until evening.'],
      ['해설', 'At last Zhuge Liang woke up, dressed, and came out. He was tall with a bright face, holding a feather fan.'],
      ['유비', 'The Han is falling, but I lack the strength to do what I want. Please show me the way.'],
      ['제갈량', 'Cao Cao in the north controls the emperor and commands a million soldiers. You cannot face him now.'],
      ['제갈량', 'Sun Quan in the east is the third of his family to rule there, and the people follow him. Make him an ally, not an enemy.'],
      ['제갈량', 'Take Jingzhou as your base, then take Yizhou in the west and build your strength.'],
      ['제갈량', 'Then the land will stand on three legs like a cauldron. When the time comes, you can march on the heartland.'],
      ['해설', 'This young man of twenty-seven, hidden in a cottage, already had a map of the whole land in his head.'],
      ['유비', 'If you do not help, what will become of the suffering people?'],
      ['해설', 'Liu Bei’s tears wet his sleeves, and Zhuge Liang finally decided to leave his cottage.'],
      ['해설', 'Afterward, Liu Bei spent day and night with Zhuge Liang. Guan Yu and Zhang Fei began to show their displeasure.'],
      ['유비', 'Having Kongming is like a fish having water. Say no more, my brothers.'],
      ['해설', 'Meanwhile, Cao Cao had finished getting ready to march his great army south.'],
      ['해설', 'The phrase three visits to the cottage comes from Zhuge Liang’s own memorial to the throne. There he wrote that the late emperor visited him three times.'],
    ],
  },

  'sg-08': {
    title: 'Romance of the Three Kingdoms, Part 8',
    names: { 해설: 'Narrator', 장비: 'Zhang Fei', 유비: 'Liu Bei', 제갈량: 'Zhuge Liang', 관우: 'Guan Yu', 하후돈: 'Xiahou Dun' },
    outro: [
      'Guan Yu and Zhang Fei dropped their doubts and bowed to Zhuge Liang. What does this say about how trust grows?',
      'At Bowang and Xinye, Zhuge Liang used land, wind, and water. What do his methods have in common?',
      'Have you ever earned the respect of people who did not believe in you at first?',
    ],
    lines: [
      ['해설', 'Last time, after three visits to the cottage, Liu Bei welcomed Zhuge Liang as his military adviser.'],
      ['해설', 'Cao Cao gave his general Xiahou Dun a hundred thousand soldiers to attack Liu Bei at Xinye.'],
      ['장비', 'Brother, you called Kongming your water. This time, why not send the water to stop the enemy?'],
      ['유비', 'I will borrow wisdom from Kongming and courage from my brothers. Stop talking like that.'],
      ['해설', 'Zhuge Liang received Liu Bei’s sword and seal and called the generals together.'],
      ['제갈량', 'Bowang Slope has hills and woods on both sides and a narrow road. And it is full of dry reeds.'],
      ['제갈량', 'General Guan, hide on the left hill. General Zhang, hide in the right woods. When fire rises in the south, attack together.'],
      ['제갈량', 'Zhao Zilong, fight at the front, but do not win. Pretend to lose and lead the enemy into the valley.'],
      ['관우', 'We all go out to fight. What will you be doing, adviser?'],
      ['제갈량', 'I will guard this town and wait here with our lord.'],
      ['장비', 'Ha! We risk our lives, and you sit at home?'],
      ['제갈량', 'The sword and seal are here. Anyone who disobeys will be punished by military law.'],
      ['해설', 'Half in doubt, Guan Yu and Zhang Fei led their troops away.'],
      ['해설', 'When Xiahou Dun’s army reached Bowang Slope, Zhao Zilong crossed spears a few times, then turned and fled.'],
      ['하후돈', 'That is Liu Bei’s army? This Zhuge Liang is nothing special. Chase them to the end!'],
      ['해설', 'The sun set and the wind rose. An officer behind him grew uneasy, saying the road was narrow and the reeds were thick.'],
      ['하후돈', 'Oh no, if they use fire, we are finished! Stop the army!'],
      ['해설', 'Before he finished, fire burst out on all sides. Driven by the wind, it swallowed the reeds and filled the valley.'],
      ['해설', 'Out of the smoke, Guan Yu and Zhang Fei charged from both sides. Cao Cao’s soldiers pushed each other and scattered into the dark.'],
      ['해설', 'The next day, when Guan Yu and Zhang Fei saw Zhuge Liang’s carriage, they got off their horses and bowed.'],
      ['관우', 'You are truly a great man, adviser. I am ashamed of my narrow mind.'],
      ['해설', 'But this time, Cao Cao himself came south with a great army. Liu Biao, the lord of Jingzhou, had also died.'],
      ['제갈량', 'Xinye is too small to hold for long. Take the people and move to Fancheng.'],
      ['해설', 'In empty Xinye, Zhuge Liang hid fire on every roof. He had Guan Yu dam the upper White River with sandbags.'],
      ['해설', 'Cao Ren’s army entered the empty town. As they cooked dinner, fire broke out everywhere at once.'],
      ['해설', 'The soldiers fled to the White River. Then Guan Yu broke the sandbags, and the water came roaring down.'],
      ['장비', 'Ha ha, fire and water take turns welcoming our guests! Not even ghosts could guess your plans, adviser.'],
      ['유비', 'Without Kongming, what would have happened to us all today?'],
      ['해설', 'But the victory was short. Tens of thousands of people who wanted to follow Liu Bei lined up behind him.'],
      ['해설', 'Cao Cao’s fast horsemen were thundering toward the slow line of refugees.'],
      ['해설', 'The novel makes the fire at Bowang Zhuge Liang’s first battle. In the official history, Liu Bei beat Xiahou Dun there before he met Zhuge Liang.'],
    ],
  },

  'sg-09': {
    title: 'Romance of the Three Kingdoms, Part 9',
    names: { 해설: 'Narrator', 유비: 'Liu Bei', 조자룡: 'Zhao Zilong', 미부인: 'Lady Mi', 조조: 'Cao Cao', 장비: 'Zhang Fei' },
    outro: [
      'Refusing to abandon the people cost Liu Bei in battle. What did it gain him instead?',
      'Zhang Fei stopped a great army with dust and a loud shout. What feeling in the enemy did he use?',
      'Have you seen someone keep their responsibility to the end to protect another person?',
    ],
    lines: [
      ['해설', 'Last time, Zhuge Liang beat Cao Cao’s army with fire and water at Bowang and Xinye.'],
      ['해설', 'But more than a hundred thousand refugees followed Liu Bei. Pulling carts and bundles, they walked only about ten li a day.'],
      ['해설', 'His generals said to leave the people and hurry to Jiangling, but Liu Bei shook his head.'],
      ['유비', 'To do great things, people must come first. How can I abandon those who trusted and followed me?'],
      ['해설', 'Meanwhile, five thousand of Cao Cao’s fast horsemen rode day and night and caught Liu Bei at Changban.'],
      ['해설', 'At dawn, the horsemen charged with a roar, and the line broke apart. Liu Bei’s family was scattered too.'],
      ['해설', 'In the chaos, Zhao Zilong rode back into the enemy. He was looking for Liu Bei’s two wives and his little son, A Dou.'],
      ['조자룡', 'My lord trusted me with his family. If I cannot find them, how can I face him?'],
      ['해설', 'Someone shouted that Zhao Zilong had gone to surrender to Cao Cao. Zhang Fei glared in anger.'],
      ['유비', 'Zilong would never abandon me. There must be a reason.'],
      ['해설', 'Zhao Zilong first found Lady Gan and took her to safety. Then he rode deep into the enemy again.'],
      ['해설', 'By a dry well beside a broken wall sat Lady Mi, her leg wounded, holding A Dou in her arms.'],
      ['미부인', 'General, this child is my lord’s only son. Please take him to his father.'],
      ['조자룡', 'My lady, please get on my horse. I will clear a path on foot.'],
      ['미부인', 'There is only one horse. If you try to protect us both, we will both be lost. I cannot walk anymore.'],
      ['해설', 'Lady Mi handed A Dou to Zhao Zilong. Not wanting to be a burden, she threw herself into the well.'],
      ['해설', 'Zhao Zilong pushed the wall down to cover the well. He loosened his armor and held A Dou tightly to his chest.'],
      ['해설', 'Then he gripped his spear and broke through ring after ring of enemies. The flags in his way fell one by one.'],
      ['조조', 'Who is that general? Do not shoot a tiger like him. Bring him to me alive.'],
      ['해설', 'Thanks to this order from Cao Cao on the hill, Zhao Zilong escaped the arrows and raced to Changban Bridge.'],
      ['해설', 'On the bridge, Zhang Fei stood alone with his spear. In the woods behind him, dust rose thick, stirred up on purpose.'],
      ['조자룡', 'Yide, help me!'],
      ['장비', 'Zilong, cross quickly! I will handle the ones chasing you.'],
      ['해설', 'Cao Cao’s great army reached the bridge. Fearing an ambush in the dusty woods, no one dared to step forward.'],
      ['장비', 'I am Zhang Yide of Yan! Who will fight me to the death?'],
      ['해설', 'His thunderous shout rang out again and again. One of Cao Cao’s officers fell off his horse in fright, and the army turned back.'],
      ['해설', 'Zhao Zilong reached Liu Bei and held out A Dou. Liu Bei took the child and set him on the ground.'],
      ['유비', 'Because of this one little child, I almost lost a great general.'],
      ['해설', 'Zhao Zilong bowed to the ground in tears. When Zhang Fei came back after cutting the bridge, Cao Cao began chasing again.'],
      ['해설', 'At the Hanjin ferry, ships brought by Guan Yu were waiting on the river. Now the war would spread to the east.'],
      ['해설', 'The official history also says Zhang Fei cut the bridge, held his spear, and shouted his name. No one dared come near.'],
    ],
  },

  'sg-10': {
    title: 'Romance of the Three Kingdoms, Part 10',
    names: { 해설: 'Narrator', 노숙: 'Lu Su', 제갈량: 'Zhuge Liang', 손권: 'Sun Quan', 주유: 'Zhou Yu', 황개: 'Huang Gai' },
    outro: [
      'Sun Quan cut the desk to show his decision. What kind of courage does this show a leader needs?',
      'Zhuge Liang hurt Sun Quan’s pride on purpose. What effect was he aiming for?',
      'For a big goal, how much hardship would you be willing to take on?',
    ],
    lines: [
      ['해설', 'Last time, thanks to Zhao Zilong and Zhang Fei, Liu Bei barely escaped at Changban and fled to Jiangxia.'],
      ['해설', 'Having taken Jingzhou, Cao Cao sent a letter to Sun Quan in the east. He suggested a hunt with his eight hundred thousand soldiers. It was a threat.'],
      ['해설', 'Sun Quan’s official Lu Su visited Liu Bei’s camp and came back east with Zhuge Liang.'],
      ['노숙', 'Sir, in front of my lord, please do not mention how big Cao Cao’s army is.'],
      ['해설', 'The famous scholars of the east surrounded Zhuge Liang and asked him sharp questions one after another.'],
      ['해설', 'Why did Liu Bei keep losing? Was Zhuge Liang not too proud, comparing himself to great ministers of old?'],
      ['제갈량', 'To cure a serious illness, you first give the patient porridge to build strength. Only then do you use strong medicine.'],
      ['제갈량', 'My lord had few soldiers, but he did not abandon the people who followed him. Can you call that mere defeat?'],
      ['제갈량', 'Some scholars only polish words, then talk of surrender when the country is in danger. That is the true shame of a scholar.'],
      ['해설', 'One by one, the scholars fell silent. This scene became known as the debate with the scholars.'],
      ['손권', 'Why does Liu Bei not surrender to Cao Cao?'],
      ['제갈량', 'My lord is of royal blood. If he fails, it is heaven’s will. How could he bow to another?'],
      ['해설', 'Sun Quan’s face turned red. Zhuge Liang had touched his pride on purpose to stir up his will to fight.'],
      ['해설', 'Sun Quan called back Zhou Yu, who had been training the navy at Poyang Lake.'],
      ['주유', 'Cao Cao’s men are northerners who are poor on water. They are tired from the long march, and disease is spreading.'],
      ['주유', 'Give me your best soldiers, and I will surely defeat him.'],
      ['해설', 'Sun Quan drew his sword and struck off a corner of the desk in front of him.'],
      ['손권', 'Anyone who speaks of surrender again will end up like this desk!'],
      ['해설', 'Zhou Yu admired Zhuge Liang’s talent. But he also felt that this man would one day be a great danger to the east.'],
      ['해설', 'Across the river, Cao Cao’s northern soldiers grew seasick on the ships. So he had the Jingzhou navy, which had surrendered, train them.'],
      ['해설', 'One night, the old general Huang Gai quietly came to Zhou Yu’s tent.'],
      ['황개', 'They are many and we are few, so we cannot hold out long. We must attack with fire.'],
      ['주유', 'I think so too. But there is no way to get fire ships close to their fleet.'],
      ['황개', 'I will pretend to surrender. So that they do not suspect me, punish me harshly.'],
      ['주유', 'General, can you bear that pain?'],
      ['황개', 'My family has served the Sun family for three generations. I will not spare this body.'],
      ['해설', 'At the next day’s war council, Huang Gai loudly argued that Cao Cao could not be beaten.'],
      ['해설', 'Zhou Yu pretended to be angry and had Huang Gai beaten. He fainted several times but endured to the end.'],
      ['노숙', 'Sir, why did you not stop it? All the generals were crying and begging.'],
      ['제갈량', 'Both the one who struck and the one who was struck wanted it. How could I interfere?'],
      ['해설', 'A few days later, Huang Gai’s letter of surrender crossed the river. But Zhou Yu had already tested Zhuge Liang first.'],
      ['해설', 'In the official history, Huang Gai first suggested the fire attack and the false surrender. The beating appears only in the novel.'],
    ],
  },

  'sg-11': {
    title: 'Romance of the Three Kingdoms, Part 11',
    names: { 해설: 'Narrator', 주유: 'Zhou Yu', 제갈량: 'Zhuge Liang', 노숙: 'Lu Su', 조조: 'Cao Cao', 방통: 'Pang Tong' },
    outro: [
      'Zhou Yu tested Zhuge Liang and feared him. What difficulty of alliances does this show?',
      'What was the most important foundation of Zhuge Liang’s plans with the fog and the wind?',
      'When you face something others call impossible, how could you prepare to gain confidence?',
    ],
    lines: [
      ['해설', 'Last time, Huang Gai let himself be beaten to prepare a false surrender that would fool Cao Cao.'],
      ['해설', 'A few days before that, Zhou Yu called Zhuge Liang before the generals and asked him a question.'],
      ['주유', 'On water, arrows are the best weapon. Could you make a hundred thousand arrows in ten days?'],
      ['제갈량', 'Cao Cao’s army will come soon, so ten days is too late. Three days is enough.'],
      ['주유', 'There are no jokes in the army. Will you sign a pledge to accept military law if you fail?'],
      ['해설', 'Zhuge Liang signed it without hesitation. Worried, Lu Su went to see him.'],
      ['노숙', 'Sir, why did you promise three days? The craftsmen have been told to work slowly on purpose!'],
      ['제갈량', 'Please prepare twenty boats with thirty soldiers each. Cover each boat with cloth and stand piles of straw on it. Keep it secret from Zhou Yu.'],
      ['해설', 'For two days, Zhuge Liang did nothing. On the third day before dawn, a thick fog settled on the river.'],
      ['해설', 'Zhuge Liang took Lu Su aboard and led the twenty roped-together boats toward Cao Cao’s camp.'],
      ['제갈량', 'Beat the drums and have the men shout.'],
      ['노숙', 'What if Cao Cao’s army comes out to attack?'],
      ['제갈량', 'In fog like this, Cao Cao will not dare come out. Let us drink wine and wait.'],
      ['조조', 'The fog is thick, and there may be an ambush. Do not go out. Just shoot arrows!'],
      ['해설', 'Arrows poured like rain into the straw. When one side was full, Zhuge Liang turned the boats to catch arrows on the other.'],
      ['해설', 'As the sun rose and the fog cleared, the boats came calmly back, full of arrows like hedgehogs.'],
      ['제갈량', 'Thank you for the arrows, Chancellor!'],
      ['주유', 'Kongming’s wonderful calculations are beyond me.'],
      ['해설', 'After the beating plan, the scholar Pang Tong visited Cao Cao’s camp. Cao Cao gladly welcomed the famous scholar.'],
      ['방통', 'Your northern soldiers are seasick because the ships rock on the waves. Link the big ships together with iron rings.'],
      ['조조', 'Then the decks will be as steady as flat ground! What an excellent plan.'],
      ['해설', 'Once the ships were tied together, they could not scatter if fire broke out. Pang Tong made Cao Cao lock the chains himself.'],
      ['해설', 'Everything was ready. But as Zhou Yu watched the flags by the river, he suddenly collapsed and took to his bed.'],
      ['해설', 'In the middle of winter, only the northwest wind blew on the river. With that wind, fire would burn their own ships instead.'],
      ['제갈량', 'I can cure your illness, Commander. All you need is a southeast wind.'],
      ['주유', 'Can you really bring that wind?'],
      ['제갈량', 'Build me an altar of the Seven Stars on Nanping Mountain. I will pray for a great wind for three days and nights.'],
      ['해설', 'Late on the promised night, the flags began to flap the other way. The southeast wind had come.'],
      ['주유', 'He can command heaven and earth! If he lives, he will be a danger to the east.'],
      ['해설', 'Zhou Yu sent soldiers to catch Zhuge Liang. But he had already left on a small boat that Zhao Zilong had brought.'],
      ['해설', 'The wind was now pushing at the backs of the eastern ships. All that was left was a single spark.'],
      ['해설', 'The official history has no record of Zhuge Liang getting arrows with straw boats or praying for the southeast wind.'],
    ],
  },

  'sg-12': {
    title: 'Romance of the Three Kingdoms, Part 12',
    names: { 해설: 'Narrator', 제갈량: 'Zhuge Liang', 관우: 'Guan Yu', 유비: 'Liu Bei', 조조: 'Cao Cao', 주유: 'Zhou Yu' },
    outro: [
      'Was Guan Yu letting Cao Cao go an act of loyalty, or did he fail in his duty?',
      'Cao Cao chose the smoky road on purpose. What weakness of clever people does this show?',
      'When rules clash with a personal debt of kindness, what would guide your decision?',
    ],
    lines: [
      ['해설', 'Last time, Zhuge Liang got arrows with straw boats in the fog and called up the southeast wind.'],
      ['해설', 'On the night the wind changed, Zhuge Liang returned to Liu Bei’s camp. He gave the generals their tasks one by one.'],
      ['제갈량', 'Zilong, hide in the Wulin woods. Yide, hide at the mouth of Hulu Valley. Attack Cao Cao’s men as they flee.'],
      ['해설', 'When his name was never called, Guan Yu could not hold back.'],
      ['관우', 'Adviser, I have fought many battles for my brother. Why do you leave me out this time?'],
      ['제갈량', 'I have a place for you, a narrow road called Huarong. But I worry about the kindness Cao Cao once showed you.'],
      ['관우', 'I repaid that kindness at Baima. If I let Cao Cao go, I will accept military law. I will sign a pledge.'],
      ['해설', 'When Guan Yu left with his troops, Liu Bei asked anxiously.'],
      ['유비', 'My brother has a deep sense of loyalty. Can he really stop Cao Cao?'],
      ['제갈량', 'The stars tell me Cao Cao’s time has not yet come. It is not bad to let Yunchang repay his debt.'],
      ['해설', 'Meanwhile, north of the river, Cao Cao stood at the front of his ship, waiting for Huang Gai.'],
      ['조조', 'A southeast wind is blowing. If Huang Gai rides this wind, he will come even faster.'],
      ['해설', 'Twenty ships with blue dragon flags came closer. But the ships were floating too lightly on the water.'],
      ['해설', 'Cao Cao’s adviser Cheng Yu noticed it. Ships carrying food should have sat deep in the water.'],
      ['조조', 'Stop those ships! Do not let them come near!'],
      ['해설', 'It was too late. Huang Gai raised his sword as a signal, and the ships, full of dry wood and oil, burst into flames.'],
      ['해설', 'The fire ships flew like arrows on the wind. Cao Cao’s chained fleet could not scatter and became a sea of fire.'],
      ['주유', 'Now! Beat the drums! All ships, forward!'],
      ['해설', 'The river and sky turned red together. Cao Cao’s great army broke and fled onto the land and into the woods.'],
      ['해설', 'Cao Cao fled with what was left. At Wulin he met Zhao Zilong, and at Hulu Valley he met Zhang Fei.'],
      ['해설', 'At a fork, the main road had no smoke. But smoke was rising from the narrow Huarong road.'],
      ['조조', 'Kongming is full of tricks. He made smoke to drive us onto the main road. I will not be fooled. To Huarong!'],
      ['해설', 'The road was a muddy swamp from the rain. Tired soldiers filled it with grass and wood to make a path.'],
      ['조조', 'Ha ha, Zhuge Liang and Zhou Yu still have much to learn. A few hundred men hidden here would have finished us.'],
      ['해설', 'Before his laughter stopped, drums sounded. Guan Yu sat on Red Hare, holding his great blade.'],
      ['조조', 'Yunchang, how have you been? I lost the battle and now I am running for my life. Remember our old friendship.'],
      ['관우', 'I repaid your kindness at Baima. Today is the country’s business, so I cannot follow my personal feelings.'],
      ['조조', 'When you killed generals at the five passes, did I ever once blame you?'],
      ['해설', 'Guan Yu lowered his head. He saw the soldiers shaking in the mud, and silently turned his horse to open the way.'],
      ['해설', 'Guan Yu came back empty-handed and was spared only because Liu Bei begged. Now a new tug-of-war over Jingzhou was about to begin.'],
      ['해설', 'The official history says Cao Cao retreated by the Huarong road. But Guan Yu letting him go appears only in the novel.'],
    ],
  },
};
