// 청소년 영어 원고: 돈키호테 1~10화 (stories/teen-quixote.js). 문장은 자체 각색.
// lines 의 첫 칸은 한국어 이야기 cast 의 이름 그대로.
export default {
  'dq-01': {
    title: 'Don Quixote, Part 1',
    names: { 해설: 'Narrator', 돈키호테: 'Don Quixote', 여관주인: 'Innkeeper', 노새꾼: 'Muleteer' },
    outro: [
      'Why did the real world look so different to Alonso Quijano after he believed his books too much?',
      'What kind of laughter comes from calling a poor inn a castle and its owner a lord?',
      'Has a story or a screen ever changed the way you see the real world?',
    ],
    lines: [
      ['해설', 'In a village in La Mancha, Spain, there lived a country gentleman of nearly fifty.'],
      ['해설', 'His name was Alonso Quijano. An old lance, a shield, and a thin horse were all he had.'],
      ['해설', 'He loved books about knights so much that he sold his fields to buy more of them.'],
      ['해설', 'He read about giants, wizards, and brave knights day and night, until he lost his wits.'],
      ['돈키호테', 'The world is still full of wrongs to set right. I must become a knight-errant!'],
      ['해설', 'He polished his great-grandfather’s rusty armor and made a visor for his helmet out of cardboard.'],
      ['해설', 'He gave his bony old horse a grand name, Rocinante.'],
      ['해설', 'For himself, he chose the name Don Quixote de la Mancha.'],
      ['돈키호테', 'Every knight needs a lady to give his heart to.'],
      ['해설', 'He thought of Aldonza Lorenzo, a farm girl from a nearby village.'],
      ['해설', 'He named her Dulcinea del Toboso and decided to serve her like a princess.'],
      ['해설', 'She herself knew nothing about any of this.'],
      ['해설', 'Early one hot July morning, he secretly rode away without telling anyone.'],
      ['해설', 'At sunset he reached a shabby roadside inn. To his eyes, it was a castle with tall towers.'],
      ['해설', 'Even a pig herder’s horn sounded like a trumpet welcoming him to the castle.'],
      ['돈키호테', 'Lord of the castle, please give a tired knight-errant a place for the night.'],
      ['여관주인', 'Lord, is it? I like the sound of that. If you want to stay, I have a bed for you.'],
      ['해설', 'The innkeeper saw at once that his guest was not right in the head, so he played along.'],
      ['해설', 'Dinner was badly cooked dried fish and hard black bread. He ate it like a royal feast.'],
      ['돈키호테', 'I have one request. I am not yet a true knight, so you must make me one.'],
      ['해설', 'He promised to guard his armor all night. He laid it on a water trough in the yard.'],
      ['해설', 'When a muleteer moved the armor to water his mules, Don Quixote struck him with his lance.'],
      ['노새꾼', 'Ouch! I only wanted to give my mules a drink! What did I do wrong?'],
      ['해설', 'As the noise grew louder, the innkeeper decided to finish the ceremony quickly.'],
      ['여관주인', 'I will read from this account book as if it were a holy book. Kneel down, sir knight.'],
      ['해설', 'The innkeeper mumbled over the book and tapped him on the shoulder with the sword.'],
      ['돈키호테', 'I will never forget this kindness. Now I am a true knight!'],
      ['해설', 'He did not pay a single coin, but the innkeeper was only glad to see him go.'],
      ['해설', 'Next time, the new knight sets out on his first adventures, but things do not go as planned.'],
      ['해설', 'The first part of Don Quixote was published in Madrid in 1605.'],
    ],
  },

  'dq-02': {
    title: 'Don Quixote, Part 2',
    names: { 해설: 'Narrator', 안드레스: 'Andrés', 돈키호테: 'Don Quixote', 농부: 'Farmer', 상인: 'Merchant', 조카: 'Niece', 신부: 'Priest', 산초: 'Sancho Panza' },
    outro: [
      'Why did Don Quixote’s help end up making the boy suffer even more?',
      'What does Don Quixote’s belief that a wizard stole his library show about him?',
      'What should we check so that our good intentions do not hurt others?',
    ],
    lines: [
      ['해설', 'Last time, Alonso Quijano became Don Quixote and was made a knight by an innkeeper in a silly ceremony.'],
      ['해설', 'The innkeeper told him to get money, shirts, and a squire, so he turned back toward his village.'],
      ['해설', 'In the woods he heard crying. A farmer was beating a boy tied to a tree with a leather belt.'],
      ['안드레스', 'I won’t do it again! I’ll watch the sheep more carefully!'],
      ['돈키호테', 'You coward, beating a child who cannot fight back! Untie him at once!'],
      ['해설', 'The farmer, Juan Haldudo, was terrified of the man in armor pointing a lance at him.'],
      ['농부', 'He keeps losing my sheep, sir. But I will pay him all his wages.'],
      ['돈키호테', 'Swear by the order of knighthood that you will pay him every coin for nine months of work.'],
      ['해설', 'The farmer swore, and Don Quixote rode away proud that he had done justice.'],
      ['해설', 'But as soon as he was gone, the farmer tied the boy up again and beat him even harder.'],
      ['해설', 'Justice without care for what comes next had only made life harder for the weak.'],
      ['해설', 'Soon after, he met a group of merchants from Toledo on the road.'],
      ['돈키호테', 'No one passes until he admits that Dulcinea del Toboso is the most beautiful woman in the world!'],
      ['상인', 'How can we admit that about a lady we have never seen? Show us a portrait at least.'],
      ['해설', 'Angry, he charged with his lance, but Rocinante tripped and he rolled on the ground.'],
      ['해설', 'One of the merchants’ servants broke his lance and beat him with the pieces.'],
      ['해설', 'A neighbor passing by found him lying helpless, put him on a donkey, and took him home.'],
      ['해설', 'At home, his niece, his housekeeper, the village priest, and the barber were waiting anxiously.'],
      ['조카', 'It’s all because of those terrible books. Uncle stayed up all night and slashed at the walls with his sword.'],
      ['신부', 'Tomorrow we will look through his library. Books that cloud the mind must go.'],
      ['해설', 'The priest and the barber judged the books one by one. They kept a few and burned the rest.'],
      ['해설', 'Then they walled up the door of the library. When he woke and looked for it, his niece spoke.'],
      ['조카', 'A wizard came on a cloud and carried the whole library away.'],
      ['돈키호테', 'It must be Freston! That wizard has always hated me.'],
      ['해설', 'After about two quiet weeks, he went to see a poor neighbor, a farmer named Sancho Panza.'],
      ['돈키호테', 'Be my squire. If I win an island on our adventures, I will make you its governor.'],
      ['산초', 'Governor of an island? Then my wife would be a governor’s wife. I’ll come!'],
      ['해설', 'One night the two slipped out of the village. Sancho followed on his beloved donkey.'],
      ['해설', 'Next time, the two of them meet a row of huge shapes standing in a field.'],
      ['해설', 'Miguel de Cervantes was born in 1547 in Alcalá de Henares, Spain.'],
    ],
  },

  'dq-03': {
    title: 'Don Quixote, Part 3',
    names: { 해설: 'Narrator', 돈키호테: 'Don Quixote', 산초: 'Sancho Panza', 비스카야: 'Basque Squire', 귀부인: 'Lady' },
    outro: [
      'How do Don Quixote, who sees giants, and Sancho, who sees windmills, see the world differently?',
      'What fun does the writer create by suddenly stopping the story in the middle of a sword fight?',
      'When should we trust what we see even if others disagree, and when should we doubt it?',
    ],
    lines: [
      ['해설', 'Last time, Don Quixote made the farmer Sancho Panza his squire by promising him an island.'],
      ['해설', 'As they crossed a plain, they saw thirty or forty windmills standing there.'],
      ['돈키호테', 'Look, Sancho! A crowd of terrible giants stands over there.'],
      ['산초', 'Giants, sir? Those are windmills. What look like arms are the sails that turn in the wind.'],
      ['돈키호테', 'You know nothing of adventures. If you are afraid, step aside and pray.'],
      ['해설', 'Crying out Dulcinea’s name, he rode Rocinante straight at the first windmill.'],
      ['해설', 'Just as his lance struck a sail, the wind blew and the sail turned.'],
      ['해설', 'The lance broke into pieces, and horse and knight were thrown across the field.'],
      ['산초', 'Didn’t I tell you? They were windmills!'],
      ['돈키호테', 'Quiet. The wizard who stole my library turned the giants into windmills.'],
      ['산초', 'Sir, if it hurts, just say so. I groan even when a needle pricks me.'],
      ['돈키호테', 'A knight-errant never complains, no matter how much his wounds hurt.'],
      ['해설', 'The next day, two monks in black came on mules, and a lady’s coach followed behind them.'],
      ['돈키호테', 'Those black wizards are kidnapping a princess. I must rescue her!'],
      ['산초', 'Sir, they’re just monks. This will be even worse than the windmills!'],
      ['해설', 'When Don Quixote attacked, one monk fell off his mule and the other ran away.'],
      ['해설', 'Then a Basque squire guarding the coach drew his sword and blocked the way.'],
      ['비스카야', 'Get out of the way now! If you do not step back, you will fight me!'],
      ['해설', 'The two raised their swords high, ready to strike each other.'],
      ['해설', 'At that very moment, the writer stopped, saying the manuscript ended there.'],
      ['해설', 'Searching for the rest, he found an old notebook written in Arabic at a market in Toledo.'],
      ['해설', 'It was the story of Don Quixote by an Arab historian, Cide Hamete Benengeli. He had it translated.'],
      ['해설', 'In the translation, the swords moved again. The Basque’s blow knocked off part of Don Quixote’s helmet.'],
      ['해설', 'Don Quixote struck back with all his strength and knocked the man off his mule.'],
      ['귀부인', 'Sir knight, I will do whatever you say. Please spare his life.'],
      ['돈키호테', 'Very well. But he must go to El Toboso and tell Lady Dulcinea of this deed.'],
      ['산초', 'Sir, you won an island in this fight, didn’t you? When do I become governor?'],
      ['돈키호테', 'This was only a roadside fight, not an adventure that wins islands. Be patient a little longer.'],
      ['해설', 'Next time, Don Quixote sees two great armies about to clash in clouds of dust.'],
      ['해설', 'Cervantes pretended that his novel was a translation of the Arab historian Cide Hamete Benengeli’s record.'],
    ],
  },

  'dq-04': {
    title: 'Don Quixote, Part 4',
    names: { 해설: 'Narrator', 돈키호테: 'Don Quixote', 산초: 'Sancho Panza', 히네스: 'Ginés de Pasamonte' },
    outro: [
      'Why did the prisoners Don Quixote freed throw stones at him instead of thanking him?',
      'In the scene about the barber’s basin, how do Don Quixote’s and Sancho’s ways of talking contrast?',
      'When our wish to help someone does not match what that person really wants, what should we do?',
    ],
    lines: [
      ['해설', 'Last time, Don Quixote charged at windmills and won a sword fight with a Basque squire.'],
      ['해설', 'After that, their adventures always ended in beatings and bruises.'],
      ['해설', 'At one inn, they left without paying, and Sancho was tossed into the air in a blanket.'],
      ['해설', 'One day, two clouds of dust rose from the far end of the road.'],
      ['돈키호테', 'Look, Sancho! Two great armies are about to fight. I will help the weaker side!'],
      ['산초', 'Sir, can’t you hear them baa? Those are flocks of sheep!'],
      ['해설', 'Don Quixote rode into the middle of the sheep and stabbed at them with his lance.'],
      ['해설', 'The angry shepherds threw stones with their slings, and he fell with several teeth knocked out.'],
      ['돈키호테', 'A wizard turned the armies into sheep. If you follow them, they will be men again.'],
      ['산초', 'And now you’ve lost your teeth, too. You really are the Knight of the Sorrowful Face.'],
      ['해설', 'Don Quixote liked the name. From that day on, he was the Knight of the Sorrowful Face.'],
      ['해설', 'Days later, in the rain, a man on a donkey came near with something shining on his head.'],
      ['해설', 'He was a barber going to work in the next village. He wore his brass basin to keep his new hat dry.'],
      ['돈키호테', 'That is the golden helmet of Mambrino from the old legends!'],
      ['해설', 'When Don Quixote charged with his lance, the barber dropped the basin and ran for his life.'],
      ['산초', 'No matter how I look at it, sir, it’s a barber’s basin.'],
      ['돈키호테', 'Someone melted it down and remade it, so it only looks like a basin. I will wear this helmet.'],
      ['해설', 'Next, they met twelve men being led along, chained together in a line.'],
      ['해설', 'They were prisoners sent by the king’s order to row in the galleys as punishment.'],
      ['돈키호테', 'It is a knight’s duty to free people who are taken away by force!'],
      ['해설', 'He drove off the guards and set the prisoners free. Their leader was Ginés.'],
      ['돈키호테', 'Now that you are free, go to El Toboso and tell Lady Dulcinea what I have done.'],
      ['히네스', 'If we go there, we’ll be caught again. Here is our thank-you instead!'],
      ['해설', 'The prisoners threw stones, took even Sancho’s coat, and ran away.'],
      ['해설', 'Afraid of being chased by officers, the two hid in the mountains of the Sierra Morena.'],
      ['돈키호테', 'Like the knights of old, I will suffer here for love. You must take a letter to Lady Dulcinea.'],
      ['산초', 'Lady Dulcinea is Aldonza Lorenzo? That girl is famous for her loud voice!'],
      ['해설', 'Sancho set off on Rocinante. But his master forgot to give him the notebook with the letter.'],
      ['해설', 'Next time, Sancho meets two familiar faces from his home village on the road.'],
      ['해설', 'Cervantes was wounded at the Battle of Lepanto in 1571 and could never fully use his left hand again.'],
    ],
  },

  'dq-05': {
    title: 'Don Quixote, Part 5',
    names: { 해설: 'Narrator', 신부: 'Priest', 산초: 'Sancho Panza', 도로테아: 'Dorotea', 돈키호테: 'Don Quixote', 여관주인: 'Innkeeper', 이발사: 'Barber', 조카: 'Niece' },
    outro: [
      'His friends tricked Don Quixote to save him. Was this kind of trick the right thing to do?',
      'How does the scene of cutting wineskins as giants show both the laughter and sadness of Part One?',
      'What should guide us when choosing between stopping a dreamer and protecting that dreamer?',
    ],
    lines: [
      ['해설', 'Last time, Don Quixote charged at sheep, freed prisoners, and then hid in the mountains.'],
      ['해설', 'On his way with the letter, Sancho met the village priest and the barber in front of an inn.'],
      ['신부', 'Sancho, where is your master? Nothing bad has happened to him, I hope?'],
      ['산초', 'He’s suffering for love in the mountains. He’s doing somersaults on the rocks.'],
      ['해설', 'The priest and the barber made a plan to bring Don Quixote home.'],
      ['해설', 'Dorotea, a young woman they met in the mountains, offered to help with the plan.'],
      ['해설', 'Dressed as Princess Micomicona from a faraway land, Dorotea knelt before Don Quixote.'],
      ['도로테아', 'Brave knight, a giant has taken my kingdom. Please help me.'],
      ['돈키호테', 'Rise, Princess. I will take no other adventure until I defeat that giant.'],
      ['산초', 'If he wins back the princess’s kingdom, my master will be king, and I’ll finally get land!'],
      ['해설', 'The group set out for the princess’s kingdom, but they were really heading home.'],
      ['해설', 'Sancho claimed he had delivered the letter to Dulcinea. In fact, he had never met her.'],
      ['해설', 'They stayed at the same inn again. In the middle of the night, a loud noise came from the attic.'],
      ['산초', 'Wake up, everyone! My master is fighting a giant. He cut off the giant’s head!'],
      ['해설', 'They ran upstairs. Fighting in his sleep, Don Quixote had slashed open the leather bags of wine.'],
      ['해설', 'The floor was flooded with red wine. Sancho believed it was the giant’s blood.'],
      ['여관주인', 'Oh, my wine! Who is going to pay for all this?'],
      ['해설', 'Many guests gathered at the inn and each told a story of love and adventure.'],
      ['해설', 'The priest and the barber covered their faces and built a big cage out of wooden poles.'],
      ['해설', 'They tied up the sleeping Don Quixote, put him in the cage, and loaded it onto an ox cart.'],
      ['이발사', 'Knight of the Sorrowful Face, do not worry. You will soon be united with Lady Dulcinea.'],
      ['돈키호테', 'Ah, I am under a spell. The knights of old were often carried off like this.'],
      ['산초', 'Sir, this isn’t magic. It’s the priest and the barber! Just listen to their voices.'],
      ['돈키호테', 'Wizards have borrowed their shapes. It is a trick to fool me.'],
      ['해설', 'Six days later, at noon, the ox cart rolled into the square of his home village.'],
      ['해설', 'His niece and housekeeper met him in tears. Sancho’s wife first asked if the donkey was all right.'],
      ['조카', 'Uncle, please stay home now. Never go on those adventures again.'],
      ['해설', 'Part One ended there, leaving only a rumor that he had someday set out again.'],
      ['해설', 'From next time, we enter Part Two, published ten years later, where Don Quixote is a famous book character.'],
      ['해설', 'From 1575, Cervantes was held captive in Algiers for about five years.'],
    ],
  },

  'dq-06': {
    title: 'Don Quixote, Part 6',
    names: { 해설: 'Narrator', 산초: 'Sancho Panza', 카라스코: 'Sansón Carrasco', 돈키호테: 'Don Quixote', 조카: 'Niece', 시골처녀: 'Peasant Girl' },
    outro: [
      'How did the news that his story had become a book change Don Quixote’s heart?',
      'This time Sancho tricks his master. How has their relationship changed since Part One?',
      'If someone wrote or showed a version of you that was different from the real you, how would you feel?',
    ],
    lines: [
      ['해설', 'Last time, Don Quixote came home locked in a wooden cage, believing he was under a spell.'],
      ['해설', 'After about a month of rest, his body healed. But his eyes still lit up at any talk of knights.'],
      ['해설', 'Then one day, Sancho came running in, out of breath, with amazing news.'],
      ['산초', 'Sir, they say our story is in a book! Even my name is in it.'],
      ['해설', 'The news came from Sansón Carrasco, a young scholar just back from the University of Salamanca.'],
      ['카라스코', 'More than twelve thousand copies have been printed already. People know your adventures by heart.'],
      ['돈키호테', 'My story is known to the world! How does the book describe me?'],
      ['카라스코', 'Some say you get beaten too often, but most readers praise you highly.'],
      ['산초', 'But I hear the writer got the story of my donkey all mixed up?'],
      ['해설', 'The news that the book was real lit the dying spark of adventure once again.'],
      ['해설', 'The niece and housekeeper begged the scholar to stop him, but he urged him to go instead.'],
      ['조카', 'Why are you encouraging him too, sir? What if Uncle gets hurt again?'],
      ['해설', 'Carrasco had a secret plan, made together with the priest and the barber.'],
      ['해설', 'Don Quixote and Sancho set off on their third journey. Their first stop was Dulcinea’s town, El Toboso.'],
      ['해설', 'They reached the town at midnight. There were only barking dogs, and no palace anywhere.'],
      ['돈키호테', 'Sancho, you came here with my letter, so lead me to her palace.'],
      ['해설', 'Sancho began to sweat. His lie in Part One about delivering the letter had caught up with him.'],
      ['산초', 'He sees windmills as giants. He’ll believe any girl is Lady Dulcinea.'],
      ['해설', 'The next morning, Sancho saw three peasant girls on donkeys and ran to his master.'],
      ['산초', 'Sir, Lady Dulcinea is coming with her maids! She’s sparkling with jewels from head to toe!'],
      ['돈키호테', 'I see nothing but three peasant girls riding donkeys.'],
      ['해설', 'Sancho knelt and called one girl princess. Don Quixote knelt down beside him.'],
      ['시골처녀', 'What kind of joke is this? Stop blocking the road and get out of the way!'],
      ['해설', 'The girls rode off on their donkeys. Don Quixote let out a deep sigh.'],
      ['돈키호테', 'Ah, a wizard has changed Lady Dulcinea into a peasant girl!'],
      ['해설', 'Sancho tried hard not to laugh. This time, the squire had played the wizard.'],
      ['해설', 'From then on, Don Quixote’s greatest wish was to break the spell on Dulcinea.'],
      ['해설', 'Next time, a stranger knight wearing a coat covered in mirrors challenges Don Quixote to a duel.'],
      ['해설', 'Part Two of Don Quixote was published in 1615, ten years after Part One.'],
    ],
  },

  'dq-07': {
    title: 'Don Quixote, Part 7',
    names: { 해설: 'Narrator', 거울기사: 'Knight of the Mirrors', 돈키호테: 'Don Quixote', 토메: 'Tomé Cecial', 산초: 'Sancho Panza', 사자지기: 'Lion Keeper' },
    outro: [
      'Was Don Quixote standing firm before the lion’s cage an act of courage or of foolishness?',
      'What might a knight covered in mirrors be trying to reflect back to Don Quixote?',
      'How far can we go in fooling someone in order to set that person right?',
    ],
    lines: [
      ['해설', 'Last time, Sancho tricked Don Quixote into believing that Dulcinea was under a spell.'],
      ['해설', 'While spending the night in a forest, they met another knight singing a sad song.'],
      ['해설', 'His coat was covered with small pieces of mirror that sparkled.'],
      ['거울기사', 'I have already defeated a knight called Don Quixote de la Mancha. It made me very famous.'],
      ['돈키호테', 'The man you beat must have been a fake. The real Don Quixote is right here!'],
      ['거울기사', 'Then let us fight at dawn. The loser must obey the winner.'],
      ['해설', 'Meanwhile, the two squires sat side by side, sharing wine and chatting.'],
      ['토메', 'Your master or mine, they both make their squires suffer just the same.'],
      ['해설', 'At dawn, Sancho was shocked. The other squire’s nose was huge and lumpy, like an eggplant.'],
      ['해설', 'The duel began. But the horse of the Knight of the Mirrors would not move at all.'],
      ['해설', 'Don Quixote seized the chance, charged hard, and knocked his enemy off his horse.'],
      ['해설', 'When he pulled off the fallen knight’s helmet, he was amazed to see the face of Sansón Carrasco.'],
      ['돈키호테', 'Look, Sancho! The wizards gave him the scholar’s face to hide my victory!'],
      ['해설', 'The squire’s false nose fell off, too. He was Tomé Cecial, Sancho’s neighbor.'],
      ['산초', 'Uncle Tomé? What are you doing here?'],
      ['토메', 'I had my reasons. Please don’t hurt my master.'],
      ['돈키호테', 'The loser must go to El Toboso and kneel before Lady Dulcinea.'],
      ['해설', 'And so Carrasco’s plan to beat Don Quixote and send him home failed.'],
      ['해설', 'Soon after, a cart came along carrying two lions as a gift for the king.'],
      ['돈키호테', 'Open the cage! Let us see if a lion can frighten this knight.'],
      ['사자지기', 'Sir, these lions are starving. Please, I beg you, don’t do this!'],
      ['산초', 'Sir, this isn’t a windmill. It’s a real lion! A real one!'],
      ['해설', 'The keeper had no choice but to open the cage. Don Quixote stood before it with his sword.'],
      ['해설', 'The lion yawned and stretched, looked around once, then turned its back and lay down again.'],
      ['돈키호테', 'The lion has refused to fight, so my courage is proven.'],
      ['해설', 'From that day on, he called himself the Knight of the Lions instead of the Knight of the Sorrowful Face.'],
      ['해설', 'Don Diego, a gentleman in a green coat, watched it all. He could not tell if Don Quixote was mad or brave.'],
      ['해설', 'Next time, a noble couple who have read his book invite Don Quixote to their castle.'],
      ['해설', 'The original title of Part One was The Ingenious Gentleman Don Quixote of La Mancha.'],
    ],
  },

  'dq-08': {
    title: 'Don Quixote, Part 8',
    names: { 해설: 'Narrator', 공작부인: 'Duchess', 공작: 'Duke', 산초: 'Sancho Panza', 돈키호테: 'Don Quixote' },
    outro: [
      'Among all the pranks of the Duke and Duchess, who was truly the foolish one?',
      'What other side of Don Quixote, called a mad knight, does his advice to Sancho show?',
      'In what forms does making fun of weaker people for amusement appear today?',
    ],
    lines: [
      ['해설', 'Last time, Don Quixote defeated the Knight of the Mirrors and did not step back even before a lion.'],
      ['해설', 'One day, the two met a duchess who was hunting with falcons in a field.'],
      ['공작부인', 'Are you not the Knight of the Sorrowful Face from the book? I hear you are now the Knight of the Lions.'],
      ['해설', 'The Duke and Duchess had read Part One and knew all about them. For fun, they decided to treat him like a real knight.'],
      ['공작', 'Please stay at our castle. We will honor you as a knight deserves.'],
      ['해설', 'For the first time, Don Quixote was welcomed like a knight in a book. He was sure he was a real knight.'],
      ['해설', 'But everything that happened in the castle was a prank planned by the Duke and Duchess.'],
      ['해설', 'This part asks readers who is more foolish, the one being mocked or the ones mocking.'],
      ['공작부인', 'Sancho, has your master really ever seen Lady Dulcinea?'],
      ['산초', 'To tell the truth, I played a little trick. But my master is always sincere.'],
      ['해설', 'The Duchess confused him by saying that Sancho himself had been fooled by a wizard.'],
      ['해설', 'The pranks grew bigger. One night, bearded ladies-in-waiting begged them to break a giant’s curse.'],
      ['해설', 'To break the curse, they had to fly to a faraway land on a wooden horse called Clavileño.'],
      ['공작', 'Cover your eyes, both of you. You will get dizzy when you rise high into the sky.'],
      ['해설', 'The two climbed onto the wooden horse with their eyes covered. Servants blew wind at them with bellows.'],
      ['산초', 'Sir, the wind is so strong! We’re at the very top of the sky, aren’t we?'],
      ['해설', 'Finally, they set fire to its tail. The wooden horse exploded, and the two fell onto the garden floor.'],
      ['해설', 'The Duke then said the promised time had come. Sancho would govern an island.'],
      ['공작', 'I give you the island of Barataria. Get ready to leave soon.'],
      ['산초', 'An island? At last, my master’s words have come true!'],
      ['해설', 'Before Sancho left, Don Quixote called him and sat down face to face with him.'],
      ['돈키호테', 'Do not be ashamed of being a farmer’s son. No one can look down on a humble man.'],
      ['돈키호테', 'When you judge, look more closely at a poor man’s tears than at a rich man’s gifts.'],
      ['돈키호테', 'When you punish, let mercy come first. And do not eat garlic or onions, or your breath will smell.'],
      ['산초', 'I’ll hold on to every word, sir. I can’t read, so I’ll keep them in my head.'],
      ['해설', 'The advice of the so-called mad knight was as wise as the words of any wise man.'],
      ['해설', 'Next time, the farmer governor who cannot even read must judge the quarrels of his people.'],
      ['해설', 'In 1614, another writer using the name Avellaneda published a fake sequel to Don Quixote.'],
    ],
  },

  'dq-09': {
    title: 'Don Quixote, Part 9',
    names: { 해설: 'Narrator', 원고: 'Plaintiff', 피고: 'Defendant', 산초: 'Sancho Panza', 의사: 'Doctor Pedro Recio', 돈키호테: 'Don Quixote', 주민: 'Townswoman' },
    outro: [
      'Where did Sancho, who could not even read, find the power to be a wise judge?',
      'How does the scene where he leaves his post and hugs his donkey complete the character of Sancho?',
      'Why can a high position or power fail to make people happy?',
    ],
    lines: [
      ['해설', 'Last time, the Duke gave Sancho the island of Barataria as a joke.'],
      ['해설', 'Barataria was not an island but a small town on the Duke’s land. Sancho did not know that.'],
      ['해설', 'Following the Duke’s orders, the townspeople welcomed the new governor loudly. Then a trial began at once.'],
      ['해설', 'An old man brought in another old man who walked with a cane, and made his complaint.'],
      ['원고', 'I lent this man ten gold coins, but no matter how often I ask, he won’t pay me back.'],
      ['피고', 'I certainly paid him back. I will swear to it. Hold this cane for a moment.'],
      ['해설', 'The defendant gave the cane to the plaintiff and swore that he had put the money back into his hands.'],
      ['해설', 'Then he took back his cane and started to leave. Sancho rested his chin on his hand and thought for a long time.'],
      ['산초', 'Wait! Give me that cane. Now break it open.'],
      ['해설', 'When they broke the cane, ten gold coins poured out. Everyone stood with mouths open.'],
      ['산초', 'He gave the money to the other man, cane and all, while swearing. So his oath was not a lie. Clever trick!'],
      ['해설', 'All the people of Barataria were amazed by the wisdom of a governor who could not read.'],
      ['해설', 'But at the dinner table, Sancho’s troubles began. Beside him stood a doctor, Pedro Recio.'],
      ['해설', 'Each time Sancho reached out, the doctor pointed at the dish with his stick, and servants took it away.'],
      ['의사', 'That food is hard to digest. That one heats the body. The governor’s health comes first.'],
      ['산초', 'At this rate the governor will starve to death! What good is a post where I can’t even eat?'],
      ['해설', 'Still, Sancho walked around the town every night and made rules to keep market prices fair.'],
      ['해설', 'Don Quixote, still at the Duke’s castle, sent Sancho a letter of advice.'],
      ['돈키호테', 'Do not make too many rules. Make few, but make sure they are kept.'],
      ['해설', 'On the seventh night, bells and shouts suddenly rang out. Enemies had attacked the island.'],
      ['주민', 'Governor, take up your weapons and lead us, quickly!'],
      ['해설', 'They tied huge shields to Sancho’s front and back. Like a turtle, he fell and could not move.'],
      ['해설', 'People ran over him, pretending to fight. This, too, was all a prank.'],
      ['해설', 'When it was over, Sancho silently went to the stable and hugged his donkey.'],
      ['산초', 'My friend, I was happy when I traveled with you. A high position does not fit me.'],
      ['산초', 'I came with nothing, and I will leave with nothing. A handful of barley for my donkey is enough.'],
      ['해설', 'He gave up his post. Even the people who had mocked him admired his honesty.'],
      ['해설', 'Next time, the two face a final duel on the beach at Barcelona.'],
      ['해설', 'Cervantes dedicated Part Two of Don Quixote to the Count of Lemos.'],
    ],
  },

  'dq-10': {
    title: 'Don Quixote, Part 10',
    names: { 해설: 'Narrator', 하얀달기사: 'Knight of the White Moon', 돈키호테: 'Don Quixote', 산초: 'Sancho Panza', 조카: 'Niece' },
    outro: [
      'Is the death of Alonso Quijano, with his mind clear again, a happy ending or a sad one?',
      'What does the last scene, where Sancho now begs his master to go on adventures, tell us?',
      'Between a life of only facing reality and a life of chasing dreams, what balance do I want?',
    ],
    lines: [
      ['해설', 'Last time, Sancho gave up his post as governor of Barataria and returned to his master.'],
      ['해설', 'The two reached Barcelona. For the first time in their lives, they saw the sea.'],
      ['해설', 'One morning on the beach, a knight with a white moon painted on his shield appeared before Don Quixote.'],
      ['하얀달기사', 'Admit that my lady is more beautiful than Dulcinea, or we fight.'],
      ['하얀달기사', 'If I win, you must go home and not take up your sword for one year.'],
      ['돈키호테', 'I cannot accept words that insult Lady Dulcinea. Let us fight.'],
      ['해설', 'The two knights charged. Hit by the stronger horse, Rocinante and Don Quixote were thrown down at once.'],
      ['하얀달기사', 'Admit that you are beaten, and keep your promise.'],
      ['돈키호테', 'Lady Dulcinea is the most beautiful lady in the world. My weakness cannot change that truth.'],
      ['하얀달기사', 'I will leave her beauty alone. You only need to stay home for one year.'],
      ['해설', 'The Knight of the White Moon was Sansón Carrasco. This time, he truly meant to send him home.'],
      ['해설', 'Don Quixote kept his word. He took off his armor and slowly headed home.'],
      ['돈키호테', 'Sancho, for one year, shall we become shepherds and sing songs in the fields?'],
      ['산초', 'Fine by me, sir. If we bring the priest and the scholar along, it’ll be quite something.'],
      ['해설', 'Not long after he got home, he caught a fever and lay in bed for six days.'],
      ['해설', 'His friends thought it was sorrow from his defeat. Sancho never left his bedside.'],
      ['해설', 'After a long sleep, he woke up and spoke in a clear voice.'],
      ['돈키호테', 'I am no longer Don Quixote. I am Alonso Quijano, whom people called the Good.'],
      ['돈키호테', 'Now I see that the books of knighthood blinded me. I am grateful that my mind is clear.'],
      ['돈키호테', 'I leave my property to my niece. But she must not marry a man who reads books of knighthood.'],
      ['조카', 'Uncle, don’t say such things. Please get well and get up.'],
      ['산초', 'Sir, you mustn’t die! Get up, and let’s go out to the fields as shepherds.'],
      ['산초', 'Say that you lost the duel because I tied the saddle wrong. Let’s go find Lady Dulcinea again!'],
      ['돈키호테', 'Sancho, I made you dream empty dreams too. There are no birds this year in last year’s nests.'],
      ['해설', 'Three days after making his will, Alonso Quijano died quietly, surrounded by family and friends.'],
      ['해설', 'The priest had a notary write a paper proving his death. That way, no one could bring him back to write more stories.'],
      ['해설', 'His niece, his housekeeper, and Sancho missed him for a long time.'],
      ['해설', 'He had set out as a mad knight, but he ended his long journey as a good man.'],
      ['해설', 'Cervantes died in Madrid in 1616, the year after Part Two came out.'],
    ],
  },
};
