// 청소년 영어 원고 (중학생 이상). 키 = stories/teen-sagi.js 의 이야기 id.
// 『삼국사기』 이야기를 한국어 각색의 흐름대로 쉬운 영어로 새로 씀. 기록과 후대 전승의 구분은 해설에 그대로 살림.
export default {
  'sgs-01': {
    title: 'Eulji Mundeok and the Battle of Salsu',
    names: { 해설: 'Narrator', 을지문덕: 'Eulji Mundeok', 우중문: 'Yu Zhongwen', 우문술: 'Yuwen Shu', 유사룡: 'Liu Shilong' },
    outro: [
      'Eulji Mundeok chose to wear the enemy out instead of fighting head-on. What can we learn from this strategy?',
      'His poem sounded like praise. What effect did he want it to have on the enemy general?',
      'When is it wiser to wait for the right moment than to charge at a strong opponent?',
    ],
    lines: [
      ['해설', 'In 612, Emperor Yang of Sui invaded Goguryeo with an army of more than a million soldiers.'],
      ['해설', 'Liaodong Fortress would not fall. So he sent over three hundred thousand men straight to Pyongyang under Yuwen Shu and Yu Zhongwen.'],
      ['해설', 'King Yeongyang of Goguryeo sent his minister Eulji Mundeok to the enemy camp. He pretended to surrender to spy on them.'],
      ['을지문덕', 'I am Eulji Mundeok, a minister of Goguryeo. My king has sent me to offer surrender.'],
      ['해설', 'Yu Zhongwen had a secret order from the emperor. If the Goguryeo king or Eulji Mundeok came, he must capture them.'],
      ['우중문', 'Eulji Mundeok himself has walked right in. We should seize him now.'],
      ['유사룡', 'General, it is wrong to arrest an envoy who came to surrender. Let him go.'],
      ['해설', 'So Yu Zhongwen let him go. But he soon regretted it and sent a messenger to call him back.'],
      ['해설', 'Eulji Mundeok did not even look back. He crossed the Yalu River.'],
      ['해설', 'He had already seen that the enemy soldiers were hungry. They had secretly thrown away their heavy food supplies.'],
      ['우문술', 'Our food is running out. We have no choice but to go back.'],
      ['우중문', 'How can we face the emperor without catching even one enemy general? Let us chase him.'],
      ['해설', 'Eulji Mundeok retreated on purpose every time. In one day he fought seven battles and pretended to lose all seven.'],
      ['해설', 'Excited by their victories, the Sui troops crossed the Salsu River and camped thirty li from Pyongyang.'],
      ['해설', 'Then Eulji Mundeok sent Yu Zhongwen a poem. Its meaning went something like this.'],
      ['을지문덕', 'Your clever plans reach the laws of heaven. Your skillful counting covers the laws of the earth.'],
      ['을지문덕', 'You have already won great glory. Why not be satisfied and stop here?'],
      ['해설', 'Behind the praise hid sharp mockery. Yu Zhongwen only wrote back with a warning to Goguryeo.'],
      ['해설', 'Eulji Mundeok sent another messenger and once again pretended to surrender.'],
      ['을지문덕', 'If you turn your army back, I will bring our king to visit your emperor.'],
      ['해설', 'Yuwen Shu looked at his tired soldiers and the high walls of Pyongyang. Taking the fortress seemed impossible.'],
      ['우문술', 'They promised to surrender, so we can retreat without losing face. Turn the army around.'],
      ['해설', 'The Sui army retreated in a square formation. Goguryeo soldiers attacked from all sides without rest.'],
      ['해설', 'At the Salsu River, when half the enemy had crossed, Goguryeo troops struck the units at the rear.'],
      ['해설', 'The Sui general Xin Shixiong was killed, and the Sui army fell apart and fled.'],
      ['해설', 'According to the records, of 305,000 men who crossed the Liao River, only 2,700 returned to Liaodong.'],
      ['해설', 'After repeated failed wars and many revolts, the Sui dynasty fell in 618.'],
      ['해설', 'The story of Eulji Mundeok is recorded in the Samguk Sagi, the History of the Three Kingdoms.'],
    ],
  },

  'sgs-02': {
    title: 'Eul Paso, the Farmer Minister',
    names: { 해설: 'Narrator', 왕: 'King Gogukcheon', 안류: 'Anryu', 을파소: 'Eul Paso', 신하: 'Minister', 백성: 'Villager' },
    outro: [
      'What does the way King Gogukcheon found Eul Paso tell us about choosing talented people?',
      'Why did Eul Paso really refuse his first post, and what do you think of that choice?',
      'To find hidden talent today and trust it with real work, what does society need?',
    ],
    lines: [
      ['해설', 'In the time of King Gogukcheon of Goguryeo, the queen’s relatives abused their power and finally rebelled.'],
      ['해설', 'After putting down the revolt, the king felt he needed someone to set the kingdom right.'],
      ['왕', 'Posts were given out as favors, and people without virtue rose high. The people suffered, and the kingdom shook.'],
      ['왕', 'Each of the four regions must find wise and able people hidden among the common folk.'],
      ['해설', 'All four regions recommended the same man, Anryu of the eastern region. The king wanted to give him the job.'],
      ['안류', 'I am foolish, Your Majesty. I am not fit for such great work.'],
      ['안류', 'But in a village by the western Yalu, there is a man named Eul Paso. He is strong-willed and wise.'],
      ['안류', 'No one recognizes his talent, so he lives by farming. If you want to rule well, you need him.'],
      ['해설', 'The king sent messengers with humble words and rich gifts to bring Eul Paso to the palace.'],
      ['해설', 'The king gave Eul Paso a middle-ranking post and a title.'],
      ['왕', 'My virtue is thin and my skills are few. Please do not hide your talent. Help me.'],
      ['을파소', 'I am slow and dull, Your Majesty. I cannot carry out such a strict command.'],
      ['을파소', 'Please choose another wise man, give him a higher post, and let him do the great work.'],
      ['해설', 'Eul Paso was not just being modest. Such a low post was not enough to fix the kingdom. The king understood.'],
      ['해설', 'The king made him guksang, the prime minister, and put him in charge of the government.'],
      ['해설', 'The old officials and the royal in-laws hated him. They said the newcomer was splitting the court.'],
      ['신하', 'A country farmer becomes prime minister overnight? How can this be?'],
      ['왕', 'Noble or common, anyone who disobeys the prime minister will be punished along with his whole family.'],
      ['을파소', 'When the time is wrong, a scholar hides. When the time is right, he serves. That is his duty.'],
      ['을파소', 'The king trusts me so deeply. How could I think of hiding again?'],
      ['해설', 'Eul Paso served with all his heart. He made the laws clear and gave rewards and punishments with care.'],
      ['해설', 'The people lived in peace, and the kingdom was safe inside and out.'],
      ['왕', 'Anryu, without your words I would never have found Eul Paso. This peace is thanks to you.'],
      ['해설', 'A few years later, in a year of bad harvest, the king saw a man crying by the road.'],
      ['백성', 'I work for wages to feed my mother. But this year there is no work, and I cannot care for her.'],
      ['해설', 'The king gave him clothes and food. Then he made a law to lend grain in spring and collect it in winter.'],
      ['해설', 'This law, called jindaebeop, was made while Eul Paso was prime minister. But the records do not name him directly.'],
      ['해설', 'The story of Eul Paso is recorded in the Samguk Sagi.'],
    ],
  },

  'sgs-03': {
    title: 'Gyebaek at Hwangsanbeol',
    names: { 해설: 'Narrator', 계백: 'Gyebaek', 군사: 'Soldier', 김유신: 'Kim Yu-sin', 관창: 'Gwanchang' },
    outro: [
      'Gyebaek knew he would lose, so why did he fight to the end? How do you judge his loyalty?',
      'Gyebaek once let Gwanchang go free. What side of his character can we see in that choice?',
      'When the values we protect clash with the lives of people we love, how should we decide?',
    ],
    lines: [
      ['해설', 'In 660, the Tang general Su Dingfang crossed the sea with a huge army. Kim Yu-sin of Silla marched on Baekje with fifty thousand men.'],
      ['해설', 'The Baekje court fell into chaos. General Gyebaek chose five thousand men ready to die and set out to stop the enemy.'],
      ['계백', 'One kingdom is facing the great armies of Tang and Silla. No one knows if our country will survive.'],
      ['계백', 'I would rather my family die with honor than be captured and shamed as slaves.'],
      ['해설', 'The record briefly says that Gyebaek took his own family’s lives and then left for battle.'],
      ['해설', 'It was a grim decision that cut off any way back. Later writers judged it in very different ways.'],
      ['해설', 'At Hwangsanbeol, the plain of Hwangsan, Gyebaek set up three camps and stood before his men.'],
      ['계백', 'Long ago, King Goujian of Yue defeated a huge army of Wu with only five thousand soldiers.'],
      ['계백', 'Today let each of us fight with all our strength and repay our country’s kindness.'],
      ['군사', 'We will fight with you to the very end, General!'],
      ['해설', 'The Silla army charged. But each Baekje soldier fought as if he were a thousand men.'],
      ['해설', 'They clashed four times, and Baekje won all four. The much larger Silla army hesitated and fell back.'],
      ['김유신', 'Our soldiers have lost heart. Like this, we cannot cross that plain.'],
      ['해설', 'First, Bangul, son of the Silla general Heumchun, charged into the enemy and never came back.'],
      ['해설', 'Then a young hwarang rode out alone. He was Gwanchang, son of General Pumil.'],
      ['관창', 'Baekje general, come out and fight me!'],
      ['해설', 'Gwanchang was soon captured and brought to Gyebaek. When his helmet came off, he had a boy’s face.'],
      ['계백', 'So young and yet so brave. I cannot bring myself to kill him.'],
      ['계백', 'Silla has many fine people. If a boy is like this, what must its grown men be like?'],
      ['해설', 'Gyebaek sent Gwanchang back alive. But Gwanchang rode straight back into the Baekje camp.'],
      ['해설', 'When Gwanchang was captured a second time, Gyebaek did not let him live.'],
      ['해설', 'The Silla soldiers saw the young hwarang’s death and burned with grief and anger. They beat their drums and charged together.'],
      ['계백', 'Do not step back. This is the last ground we must defend.'],
      ['해설', 'The enemy was many, and his men were few. The Baekje army finally broke, and Gyebaek died on that plain.'],
      ['해설', 'The Silla army crossed the plain, joined the Tang army, and marched on Sabi. That year, Baekje came to an end.'],
      ['해설', 'Gyebaek knew the battle was lost, yet he held his ground. His name became a lasting symbol of loyalty.'],
      ['해설', 'The story of Gyebaek is recorded in the biographies of the Samguk Sagi.'],
    ],
  },

  'sgs-04': {
    title: 'Gwanchang, the Young Hwarang',
    names: { 해설: 'Narrator', 관창: 'Gwanchang', 품일: 'Pumil', 계백: 'Gyebaek', 흠춘: 'Heumchun', 반굴: 'Bangul' },
    outro: [
      'How can we read Gwanchang’s courage today, and what parts of it can we look at critically?',
      'Gyebaek spared Gwanchang, while Pumil sent his son ahead. How do these two adults contrast?',
      'How far can a community fairly ask a person, especially a young one, to sacrifice for it?',
    ],
    lines: [
      ['해설', 'Gwanchang was the son of Pumil, a Silla general. He was well-mannered, became a hwarang early, and got along with everyone.'],
      ['해설', 'The hwarang were young elite warriors of Silla who trained together in body and mind.'],
      ['해설', 'At sixteen, he was already skilled at riding and archery, and a general recommended him to King Muyeol.'],
      ['해설', 'In 660, Silla joined Tang to attack Baekje. The king sent Gwanchang with the army as a junior officer.'],
      ['해설', 'At Hwangsanbeol, the Silla army met Gyebaek’s soldiers. They fought four times and lost all four.'],
      ['해설', 'As the soldiers lost heart, General Heumchun called his son Bangul.'],
      ['흠춘', 'For a subject, loyalty comes first. For a son, duty to parents comes first. In danger, giving your life fulfills both.'],
      ['반굴', 'I will do as you wish, Father.'],
      ['해설', 'Bangul charged into the enemy, fought hard, and never came back. Then Pumil called Gwanchang forward.'],
      ['품일', 'You are young, but you have spirit. Today is the day to win glory. Will you be brave?'],
      ['관창', 'Yes, Father.'],
      ['해설', 'Gwanchang mounted his horse, lowered his spear, and rode straight into the enemy lines.'],
      ['해설', 'He struck down a few men, but alone he could not face so many. He was captured and brought to Gyebaek.'],
      ['해설', 'Gyebaek had his helmet removed. Underneath was the face of a young boy.'],
      ['계백', 'A child like this charged into the enemy alone? I cannot bear to kill him.'],
      ['계백', 'Silla truly has many fine people. If a boy is like this, what about its grown men?'],
      ['해설', 'Gyebaek sighed and sent Gwanchang back alive.'],
      ['관창', 'I did not defeat their general or take their flag. I cannot bear the shame.'],
      ['관창', 'If I go in again, I will surely do it.'],
      ['해설', 'Gwanchang drank water from a well with his hands. Then he rode back toward the enemy.'],
      ['해설', 'This time Gyebaek did not spare him. Gwanchang came back lifeless, carried on his horse.'],
      ['해설', 'Pumil wiped his son’s face with his sleeve and spoke.'],
      ['품일', 'My child’s face still looks alive. He gave his life for the kingdom. I will take comfort in that.'],
      ['해설', 'Seeing this, the Silla soldiers were filled with emotion and found new resolve.'],
      ['해설', 'Drums and shouts shook the plain. The Silla army charged all at once and crushed the Baekje army.'],
      ['해설', 'The king gave Gwanchang a rank after his death and held a proper funeral. His family received silk, cloth, and grain.'],
      ['해설', 'Gwanchang is remembered as a symbol of young courage. His story also makes us ask what war demanded of a boy.'],
      ['해설', 'The story of Gwanchang is recorded in the biographies of the Samguk Sagi.'],
    ],
  },

  'sgs-05': {
    title: 'Kim Yu-sin, the Young Hwarang',
    names: { 해설: 'Narrator', 유신: 'Kim Yu-sin', 난승: 'Nanseung' },
    outro: [
      'Why were these stories of young Kim Yu-sin passed down? How did people want to remember him?',
      'What role do mysterious scenes, like the old man in the cave or starlight on a sword, play in a hero’s story?',
      'What promise would you like to make to yourself now for a goal you want to reach?',
    ],
    lines: [
      ['해설', 'Kim Yu-sin was born in 595. He was a descendant of King Suro, who founded Geumgwan Gaya.'],
      ['해설', 'His family had joined Silla in his great-grandfather’s time.'],
      ['해설', 'His father, Seohyeon, met a woman named Manmyeong on the road, and the two fell in love without a matchmaker.'],
      ['해설', 'Her angry father locked her in a separate house under guard.'],
      ['해설', 'Suddenly lightning struck the gate, and the guards ran. Manmyeong escaped through a window and followed Seohyeon.'],
      ['해설', 'Seohyeon dreamed of two stars coming down to him. Manmyeong dreamed of a child in golden armor riding a cloud into the house.'],
      ['해설', 'The child born to them was Yu-sin. At fifteen he became a hwarang, and many young men gladly followed him.'],
      ['해설', 'At that time, Goguryeo, Baekje, and the Malgal people kept crossing Silla’s borders. Seventeen-year-old Yu-sin could not hold back his anger.'],
      ['유신', 'Neighboring kingdoms are trampling our land. How long must we just watch? I will end this chaos.'],
      ['해설', 'Yu-sin went alone into a stone cave on Mount Jungak. He purified his body and mind and made a vow to heaven.'],
      ['유신', 'I am a humble person, but I want to end my country’s suffering. Heaven, please lend me strength.'],
      ['해설', 'On the fourth day, an old man in rough clothes appeared.'],
      ['난승', 'This place is full of poisonous snakes and wild beasts. Why is a boy from a noble family here alone?'],
      ['유신', 'Where are you from, sir? May I ask your name?'],
      ['난승', 'I have no fixed home. I come and go as fate leads me. My name is Nanseung.'],
      ['해설', 'Yu-sin knew he was no ordinary man. With tears, he bowed again and again, six or seven times, and begged to be taught.'],
      ['난승', 'So young, and you dream of uniting the three kingdoms. That is truly admirable.'],
      ['해설', 'The old man taught Yu-sin a secret method and gave him a warning.'],
      ['난승', 'Do not pass this on carelessly. If you use it for wrong purposes, disaster will fall on you.'],
      ['해설', 'Then he left. Yu-sin ran after him, but he was gone. Only a five-colored light glowed over the mountain.'],
      ['해설', 'The next year, enemy attacks grew worse. Yu-sin took a fine sword into a deep valley on Mount Yeolbak.'],
      ['해설', 'He burned incense and prayed as before. On the third night, starlight came down and touched the sword, which seemed to move.'],
      ['해설', 'Years later, in 629, Silla attacked Nangbi Fortress in Goguryeo. Yu-sin fought there with his father.'],
      ['해설', 'Goguryeo soldiers came out to fight, and the Silla army was badly pushed back. The men lost their will.'],
      ['유신', 'Father, our army is broken. I promised to be loyal and to honor my parents all my life. I cannot retreat.'],
      ['유신', 'Lift the collar, and the whole coat hangs straight. Pull the main rope, and the net opens. Let me be that collar and that rope.'],
      ['해설', 'Yu-sin drew his sword, leaped his horse over the trench, and rode in and out of the enemy lines. He struck down their general.'],
      ['해설', 'Seeing this, the Silla army took heart and pushed forward. In the end, Nangbi Fortress surrendered.'],
      ['해설', 'The old man in the cave and the starlight on the sword are legends. The Samguk Sagi simply wrote them down.'],
      ['해설', 'Yu-sin is also famous for killing his horse at a woman’s house. That story comes from later writings, not the Samguk Sagi.'],
      ['해설', 'The story of young Kim Yu-sin is recorded in the first part of his biography in the Samguk Sagi.'],
    ],
  },

  'sgs-06': {
    title: 'Kim Yu-sin and the Unification',
    names: { 해설: 'Narrator', 유신: 'Kim Yu-sin', 춘추: 'Kim Chun-chu', 소정방: 'Su Dingfang' },
    outro: [
      'If we divide Kim Yu-sin’s role in the unification into war, diplomacy, and politics, what do we see?',
      'On the night the star fell, he flew a burning kite. What does this show about how leaders handle people’s feelings?',
      'Kim Yu-sin said ending well matters more than starting. What does that mean for us today?',
    ],
    lines: [
      ['해설', 'In 642, Baekje captured Silla’s Daeya Fortress. Its lord, Pumseok, and his wife, Gotaso, were killed.'],
      ['해설', 'Gotaso was Kim Chun-chu’s daughter. It is said that he leaned on a pillar all day without even blinking.'],
      ['춘추', 'Can a true man not swallow even one Baekje? I will go to Goguryeo and ask for troops.'],
      ['해설', 'Before leaving, Chun-chu went to see Yu-sin.'],
      ['춘추', 'You and I are like one body, the arms and legs of this kingdom. If something happens to me, what will you do?'],
      ['유신', 'If you do not return, my horses’ hooves will surely trample the courts of Goguryeo and Baekje.'],
      ['해설', 'Chun-chu promised to return within sixty days. But Goguryeo demanded old lands back and held him there.'],
      ['해설', 'When the day passed, Yu-sin marched to the border with his bravest men. With Chun-chu’s own trick, Goguryeo let him go.'],
      ['해설', 'In 647, a high official named Bidam rebelled, saying a woman could not rule the kingdom.'],
      ['해설', 'One night, a large star fell toward Wolseong, where the queen stayed.'],
      ['해설', 'Bidam’s men shouted that blood would flow where the star fell. The royal soldiers trembled with fear.'],
      ['유신', 'Good and bad luck are not fixed. They depend on what people do. Do not let one star shake your hearts.'],
      ['해설', 'Yu-sin set fire to a scarecrow, tied it to a big kite, and flew it into the night sky. It looked like a star rising again.'],
      ['해설', 'The next day, word spread that the fallen star had gone back up. The soldiers took heart, and the revolt was crushed.'],
      ['해설', 'In 654, Kim Chun-chu became king. He was King Muyeol.'],
      ['해설', 'In 660, Silla and Tang attacked Baekje. Yu-sin barely broke through Gyebaek’s soldiers at Hwangsanbeol.'],
      ['해설', 'Because Silla arrived later than promised, the Tang general Su Dingfang tried to punish a Silla officer, Kim Mun-yeong.'],
      ['소정방', 'You broke the agreed date. I will punish you by military law.'],
      ['유신', 'You did not even see the battle at Hwangsan, yet you blame us for being late. We will not accept this insult.'],
      ['유신', 'Then we will fight the Tang army first and deal with Baekje after.'],
      ['해설', 'Yu-sin stood at the gate holding a great axe, his hair standing on end. Su Dingfang finally let Kim Mun-yeong go.'],
      ['해설', 'That year, Baekje fell. The next year King Muyeol died, and his son, King Munmu, took the throne.'],
      ['해설', 'In 662, the Tang army around Pyongyang was starving. The aging Yu-sin carried food to them through a winter snowstorm.'],
      ['해설', 'In 668, Goguryeo finally fell. Yu-sin was ill, so he stayed behind to guard the capital.'],
      ['해설', 'To honor his service, King Munmu gave him the highest rank in Silla.'],
      ['해설', 'In 673, Yu-sin fell gravely ill, and the king came to visit him in person.'],
      ['유신', 'Every king has a beginning, but few kings end well. Please make sure what we built does not fall apart.'],
      ['유신', 'Keep away from petty people and stay close to good ones. Then the court will be at peace, and the people will be safe.'],
      ['해설', 'Yu-sin died that year at the age of seventy-nine. The war against Tang ended after his death.'],
      ['해설', 'Later, King Heungdeok honored him with the title Great King Heungmu.'],
      ['해설', 'In the Samguk Sagi, Kim Yu-sin’s biography is the longest one. It fills three volumes.'],
    ],
  },

  'sgs-07': {
    title: 'Lady Seol and Gasil',
    names: { 해설: 'Narrator', 설씨: 'Lady Seol', 아버지: 'Father', 가실: 'Gasil' },
    outro: [
      'Why did Lady Seol try to keep her promise to the end, and what value does it show?',
      'What role does the broken mirror play in the story, and what about the horse left behind?',
      'When your family’s wishes clash with your own promise, how would you choose?',
    ],
    lines: [
      ['해설', 'In the time of King Jinpyeong of Silla, a daughter of the Seol family lived in a village called Yulli.'],
      ['해설', 'Her family was poor, but she was graceful and well-behaved.'],
      ['해설', 'One year, her old father was ordered to guard the faraway border.'],
      ['설씨', 'How can I send my old, sick father so far away? And as a woman, I cannot go in his place.'],
      ['해설', 'A young man named Gasil heard the news. He was poor but honest, and he had long admired her.'],
      ['가실', 'I may be humble, but I am proud of my spirit. Let me take your father’s place.'],
      ['해설', 'She happily told her father, and he called Gasil to sit with him.'],
      ['아버지', 'You will take this old man’s place? I am grateful and sorry. Please take my daughter as your wife.'],
      ['가실', 'I never even dared to hope for this.'],
      ['해설', 'When Gasil asked to set a wedding date, she answered.'],
      ['설씨', 'Marriage is a big step, so we should not rush. But I have given you my heart, and it will never change.'],
      ['설씨', 'When you come back from the border, we can hold the wedding then.'],
      ['해설', 'She broke a mirror in two, and each of them kept one half.'],
      ['설씨', 'Let this be our sign of trust. Someday we will put the pieces together again.'],
      ['가실', 'I have a good horse. No one will care for it while I am gone. Please raise it for me.'],
      ['해설', 'Gasil left. His duty was three years, but trouble in the kingdom kept anyone from replacing him. Six years passed.'],
      ['아버지', 'He promised three years, and that time is long gone. Now you must marry into another family.'],
      ['설씨', 'He made that promise to help you. For years he has suffered hunger and cold near enemy land.'],
      ['설씨', 'If I break that trust, how could I call myself a decent person? I cannot obey you in this.'],
      ['해설', 'But her old father worried she would grow old alone. He secretly arranged her marriage to a village man.'],
      ['해설', 'On that day, she firmly refused and tried to run away, but she could not.'],
      ['해설', 'She went to the stable, looked at the horse Gasil had left, and cried with a long sigh.'],
      ['해설', 'Just then, Gasil came back. He was skin and bones, and his clothes were in rags. No one recognized him.'],
      ['아버지', 'Who are you? I have never seen you before.'],
      ['해설', 'Without a word, Gasil stepped forward and tossed down his half of the mirror.'],
      ['해설', 'She picked it up. The two pieces fit perfectly, and she burst into tears.'],
      ['설씨', 'You came back. You really came back.'],
      ['해설', 'Her father and the whole family were overjoyed. The two married on a good day and grew old together.'],
      ['해설', 'The story of Lady Seol and Gasil is recorded in the biographies of the Samguk Sagi.'],
    ],
  },

  'sgs-08': {
    title: 'Domi and His Wife',
    names: { 해설: 'Narrator', 도미: 'Domi', 아내: 'Wife', 왕: 'King', 가짜왕: 'False King' },
    outro: [
      'Facing a cruel ruler, what did Domi and his wife protect to the end?',
      'Domi’s wife escaped danger twice. What parts of her character do those scenes show?',
      'How do powerful people unfairly test or control other people’s lives today?',
    ],
    lines: [
      ['해설', 'Domi was a man of Baekje. He was an ordinary commoner, but he knew what loyalty meant.'],
      ['해설', 'His wife was beautiful and famous for her faithful, upright character. People always praised her.'],
      ['해설', 'King Gaeru heard about her and called Domi to the palace.'],
      ['왕', 'A woman’s greatest virtue is faithfulness. But in a secret place, few could resist sweet words.'],
      ['도미', 'People’s hearts are hard to know. But my wife would never change her heart, even if it cost her life.'],
      ['해설', 'The king wanted to test this. He kept Domi at the palace and sent a servant dressed as the king to Domi’s house.'],
      ['해설', 'That night, the false king sent word that the king was coming. Then he spoke to Domi’s wife.'],
      ['가짜왕', 'I have long heard of your beauty. I won a bet with Domi, so tomorrow I will take you to the palace.'],
      ['해설', 'Domi’s wife answered calmly.'],
      ['아내', 'A king would never speak empty words. How could I refuse? Please go in first. I will change my clothes and come.'],
      ['해설', 'She stepped out, dressed up a maid, and sent the maid into the room instead.'],
      ['해설', 'When the king learned he had been tricked, he was furious. He had the innocent Domi blinded.'],
      ['해설', 'Then he put the blind Domi in a small boat and set it adrift on the river.'],
      ['해설', 'The king dragged Domi’s wife to the palace and tried to force her will.'],
      ['아내', 'I have lost my husband. How can I live alone? How could I go against the king’s order?'],
      ['아내', 'But right now my body is not clean. Let me wash and come back in a few days.'],
      ['해설', 'The king believed her. She used the chance to slip out of the palace and run away.'],
      ['해설', 'She reached the mouth of the river, but there was no boat. She looked up at the sky and wept.'],
      ['해설', 'Suddenly an empty boat drifted toward her. She got in and let the current carry her.'],
      ['해설', 'The boat reached an island called Cheonseongdo. There she found her husband, alive and eating roots to survive.'],
      ['아내', 'My dear, you are alive!'],
      ['도미', 'That voice is yours! I thought I would never meet you again.'],
      ['해설', 'Together they sailed to the foot of a mountain in Goguryeo.'],
      ['해설', 'The Goguryeo people pitied them and shared clothes and food.'],
      ['해설', 'The couple lived poor and wandering in that strange land, and they died there.'],
      ['해설', 'Their faith, unbroken even by a king, was told for a long time as a story of loyalty.'],
      ['해설', 'The record names the king as Gaeru, but some think it was really King Gaero, based on the period.'],
      ['해설', 'The story of Domi and his wife is recorded in the biographies of the Samguk Sagi.'],
    ],
  },

  'sgs-09': {
    title: 'Park Je-sang',
    names: { 해설: 'Narrator', 제상: 'Park Je-sang', 왕: 'King Nulji', 미사흔: 'Misaheun', 아내: 'Wife' },
    outro: [
      'Why did Park Je-sang choose a road from which he could not return?',
      'He used very different methods in Goguryeo and in Japan. What does his judgment show?',
      'What does it mean to find balance between your country, your family, and your own life?',
    ],
    lines: [
      ['해설', 'In the time of King Silseong of Silla, two sons of King Naemul were sent away as hostages.'],
      ['해설', 'Misaheun was sent to Japan, and his older brother Bokho to Goguryeo.'],
      ['해설', 'King Nulji, who took the throne next, could not stop worrying about his two younger brothers.'],
      ['왕', 'My brothers have been held in foreign lands for years. Is there any way to bring them home alive?'],
      ['해설', 'Three village chiefs together recommended Park Je-sang, the head of Sapnyang. They said he was brave and clever.'],
      ['제상', 'I am foolish and lacking, but how could I refuse your command?'],
      ['해설', 'Je-sang went to Goguryeo first and met its king.'],
      ['제상', 'Neighbors should be friends through sincerity and trust. Exchanging hostages is not what good times call for.'],
      ['제상', 'My king cannot stop missing his brother. If you send him home, we will never forget your kindness.'],
      ['해설', 'The Goguryeo king agreed, and Je-sang came home with Bokho.'],
      ['왕', 'My two brothers were like my left and right arms. Now I have one arm back. What about the other?'],
      ['제상', 'Goguryeo is a great kingdom, so words worked there. Japan cannot be moved by words. We must use a trick.'],
      ['제상', 'When I go to Japan, accuse me of betraying the country. Then they will believe me.'],
      ['해설', 'Je-sang did not even stop at home. He went straight to the port and boarded a ship. His wife ran to the shore.'],
      ['아내', 'Please come back safely!'],
      ['제상', 'I am going into an enemy land by the king’s order. Do not hope to see me again.'],
      ['해설', 'In Japan, Je-sang acted like a man who had betrayed Silla and run away. At first the Japanese king doubted him.'],
      ['해설', 'Then news came that the Silla king had jailed the families of Je-sang and Misaheun. Only then did the Japanese king trust him.'],
      ['해설', 'Japan raised an army to attack Silla. Je-sang and Misaheun boarded the ships as guides.'],
      ['해설', 'While they stayed on an island, the two went out in a boat every day to catch fish and ducks.'],
      ['해설', 'The Japanese thought the two had no secret plans and relaxed. Then Je-sang whispered to Misaheun.'],
      ['제상', 'Go back home secretly, now.'],
      ['미사흔', 'I think of you as my father. How could I go back alone?'],
      ['제상', 'If we both disappear, the plan will be discovered. I will stay here.'],
      ['해설', 'Misaheun hugged him, cried, said goodbye, and left for Silla.'],
      ['해설', 'The next day, Je-sang stayed in his room until late. He was buying time so Misaheun could get farther away.'],
      ['제상', 'I was tired from the boat yesterday, so I slept late.'],
      ['해설', 'When the Japanese finally found out, they chased Misaheun, but thick fog hid his boat.'],
      ['해설', 'The Japanese king sent Je-sang to an island and soon after took his life.'],
      ['해설', 'King Nulji mourned deeply and gave him a high rank. Misaheun married Je-sang’s second daughter to repay him.'],
      ['해설', 'The Samguk Yusa gives his family name as Kim and adds other famous scenes. This story follows the Samguk Sagi.'],
      ['해설', 'The story of Park Je-sang is recorded in the biographies of the Samguk Sagi.'],
    ],
  },

  'sgs-10': {
    title: 'Master Baekgyeol',
    names: { 해설: 'Narrator', 선생: 'Master Baekgyeol', 아내: 'Wife', 이웃: 'Neighbor' },
    outro: [
      'Is Master Baekgyeol’s attitude toward poverty giving up, or is it wisdom? Why do you think so?',
      'What does the idea of playing the sound of grain pounding on a geomungo add to the story?',
      'When you have little, what is your own way to comfort the people around you?',
    ],
    lines: [
      ['해설', 'No one knows where Master Baekgyeol came from. He lived at the foot of Mount Nang in the time of King Jabi of Silla.'],
      ['해설', 'He was very poor. His clothes were patched in a hundred places, as if quails were hanging all over him.'],
      ['해설', 'So people called him Baekgyeol, which means a hundred patches.'],
      ['이웃', 'There goes the master in his patched clothes. He is carrying his geomungo again today.'],
      ['해설', 'The geomungo is a Korean string instrument played on the lap.'],
      ['해설', 'The master admired Rong Qiqi, an ancient Chinese hermit who lived happily in poverty, playing music.'],
      ['해설', 'He always kept his geomungo close. When he was happy, angry, or sad, he let it all out through music.'],
      ['해설', 'One year, near the end of the year, the sound of pounding grain rang out from every house.'],
      ['해설', 'Thump, thump. People were pounding grain to welcome the new year.'],
      ['해설', 'But there was not a single grain in the master’s house. Listening to the sound, his wife sighed.'],
      ['아내', 'Everyone else is pounding grain, and we have nothing. How will we get through this year?'],
      ['해설', 'The master looked up at the sky, sighed, and spoke quietly.'],
      ['선생', 'Life and death depend on fate, and wealth and honor depend on heaven.'],
      ['선생', 'We cannot stop what comes or chase what goes. So why are you so sad?'],
      ['선생', 'Let me make the sound of pounding grain to comfort you.'],
      ['해설', 'He placed the geomungo on his knees, tuned the strings, and slowly began to play.'],
      ['해설', 'Then the sound of pounding grain came out of the instrument. Thump, thump.'],
      ['해설', 'The heavy pestle falling and the grain bouncing in the mortar became a melody that filled the room.'],
      ['아내', 'Why, it sounds just like someone pounding grain in our own yard!'],
      ['해설', 'At last, a faint smile spread across her face.'],
      ['해설', 'No rice appeared, but that New Year’s Eve their room was as full of sound as any house.'],
      ['이웃', 'I hear pounding from the master’s house too. But isn’t that a geomungo?'],
      ['해설', 'The tune was passed down, and people called it Daeak, which means the pounding song.'],
      ['해설', 'Instead of blaming his poverty, he found peace of mind within it. People talked about him for a long time.'],
      ['해설', 'There is also a story that he was Park Je-sang’s son, but it comes from much later writings.'],
      ['해설', 'The Samguk Sagi says only that no one knows where he was from.'],
      ['해설', 'The story of Master Baekgyeol is recorded in the biographies of the Samguk Sagi.'],
    ],
  },

  'sgs-11': {
    title: 'Solgeo the Painter',
    names: { 해설: 'Narrator', 승려: 'Monk', 아이: 'Child', 나그네: 'Traveler' },
    outro: [
      'After the painting was repainted, the birds stopped coming. What does this say about art?',
      'Why do people remember one scene from such a short record for so long?',
      'When we repair or renew something, what should we be careful about to keep its true value?',
    ],
    lines: [
      ['해설', 'Solgeo was a man of Silla. His family was humble, so the records do not name his ancestors.'],
      ['해설', 'But he was a born painter.'],
      ['해설', 'Once, Solgeo painted an old pine tree on a wall of Hwangnyongsa Temple.'],
      ['해설', 'Its trunk was covered with cracked bark like scales, and its branches and needles twisted and spread out.'],
      ['해설', 'When the painting was finished, something strange happened.'],
      ['해설', 'Crows, kites, swallows, and sparrows sometimes flew over and tried to land on the pine tree.'],
      ['아이', 'Look at that bird, sir! It is flying into the wall!'],
      ['해설', 'The birds tried to land on the branches, hit the wall, and slid down in confusion.'],
      ['승려', 'The birds think the painting is a real tree. How amazing!'],
      ['해설', 'The news spread quickly. People came to Hwangnyongsa to see the pine tree.'],
      ['나그네', 'From a distance, it looks like a living tree. I feel I could hear the needles rustle in the wind.'],
      ['해설', 'Years went by, and the colors of the painting slowly faded.'],
      ['승려', 'What a shame to see such a precious painting fade. We must repaint it and bring it back to life.'],
      ['해설', 'A monk of the temple painted over it with bright temple paints. The colors became vivid again.'],
      ['해설', 'But after that, the birds never came back.'],
      ['아이', 'Sir, the birds do not come anymore. Why not?'],
      ['승려', 'We painted new colors, but it seems something inside could not be painted again.'],
      ['해설', 'Solgeo’s brush did not stay only at Hwangnyongsa.'],
      ['해설', 'It is said that a painting of the Bodhisattva of Mercy at Bunhwangsa was also his work.'],
      ['해설', 'People called his paintings sinhwa, which means paintings made by a god’s hand.'],
      ['해설', 'The Samguk Sagi does not say when Solgeo lived or how he learned to paint.'],
      ['해설', 'Stories that he lived under King Jinheung or practiced on rocks as a boy were added or guessed later.'],
      ['해설', 'Because the record is so short, the scene of the birds stands out even more clearly.'],
      ['아이', 'I want to see that pine tree someday, too.'],
      ['해설', 'Hwangnyongsa burned down during the Mongol invasions in the Goryeo period. Only its foundation stones remain.'],
      ['해설', 'The story of Solgeo is recorded in the biographies of the Samguk Sagi.'],
    ],
  },

  'sgs-12': {
    title: 'Mulgyeja',
    names: { 해설: 'Narrator', 물계자: 'Mulgyeja', 동료: 'Comrade', 아내: 'Wife' },
    outro: [
      'When his service was not recognized, why did Mulgyeja look at himself instead of blaming others?',
      'How are his refusal to boast and his final choice to go into the mountains connected?',
      'When your effort is not recognized, how can you calm your own heart?',
    ],
    lines: [
      ['해설', 'Mulgyeja lived in the time of King Naehae of Silla. His family was not grand, but he had big dreams and a generous spirit.'],
      ['해설', 'At that time, eight small coastal states joined forces to attack the state of Ara. Ara’s prince asked Silla for help.'],
      ['해설', 'King Naehae sent a royal grandson with soldiers from nearby towns and the six districts to help Ara.'],
      ['해설', 'The Silla army finally defeated the eight states. Mulgyeja did great deeds in this battle.'],
      ['해설', 'But the royal grandson disliked him, so Mulgyeja’s deeds were not recorded.'],
      ['해설', 'People whispered that his name was missing even though he had done so much.'],
      ['동료', 'Your service was the greatest, yet you were left out of the record. Aren’t you upset?'],
      ['물계자', 'Why should I be upset?'],
      ['동료', 'Then why not tell the king yourself?'],
      ['물계자', 'Boasting about your deeds and seeking fame is not what a person of purpose does.'],
      ['물계자', 'I will just sharpen my will, work hard, and wait for the future.'],
      ['해설', 'Mulgyeja never spoke of it again.'],
      ['해설', 'Three years later, people from three coastal states attacked Silla’s Galhwa Fortress.'],
      ['해설', 'The king led the army himself to rescue it, and the three states were badly defeated.'],
      ['해설', 'Once again, Mulgyeja fought at the front and did great deeds. And once again, no one spoke of his service.'],
      ['해설', 'When he returned home, Mulgyeja spoke to his wife.'],
      ['물계자', 'I have heard that serving a king means giving your life in danger and forgetting yourself in hardship.'],
      ['물계자', 'Those two battles were truly dangerous and hard.'],
      ['물계자', 'Yet no one said I gave my life or forgot myself. How can I face the market or the court?'],
      ['아내', 'Then where will you go now?'],
      ['물계자', 'I will leave the world and live with only my geomungo as a friend.'],
      ['해설', 'Mulgyeja let down his hair and went into Mount Sache with his geomungo, a Korean string instrument.'],
      ['해설', 'There he lived in hiding, writing songs and tunes with the bamboo and the stream as his friends.'],
      ['해설', 'And he never returned to the world.'],
      ['해설', 'He did not blame others for his disappointment. He kept looking at himself to the end.'],
      ['해설', 'Some readers may see his choice as too proud and strict. Others may see it as firm self-respect.'],
      ['해설', 'The story of Mulgyeja is recorded in the biographies of the Samguk Sagi.'],
    ],
  },
};
