// 청소년 영어 원고 (중학생 이상). 키 = stories/teen-sg2.js 의 이야기 id.
// 나관중 『삼국지연의』(퍼블릭 도메인)를 한국어 각색의 흐름대로 쉬운 영어로 새로 씀. 이름은 병음, 연의와 정사 구분 해설 유지.
export default {
  'sg-13': {
    title: 'Romance of the Three Kingdoms, Part 13',
    names: { 해설: 'Narrator', 유비: 'Liu Bei', 제갈량: 'Zhuge Liang', 주유: 'Zhou Yu', 노숙: 'Lu Su', 손권: 'Sun Quan', 오국태: 'Lady Wu', 손부인: 'Lady Sun' },
    outro: [
      'Liu Bei went east knowing the danger. Was it a leader’s courage or recklessness?',
      'What did Zhuge Liang’s three silk pouches foresee, and what tension do they add to the story?',
      'Can you think of a plan to fool someone that ended up hurting the planner?',
    ],
    lines: [
      ['해설', 'The fire at Red Cliffs drove Cao Cao’s army away. But clouds of a new conflict soon rose south of the river.'],
      ['해설', 'While Zhou Yu fought Cao Cao’s generals, Liu Bei followed Zhuge Liang’s plan. He quickly took the towns of southern Jingzhou.'],
      ['주유', 'We risked our lives to win that battle, and Liu Bei picked the fruit. I cannot let this go.'],
      ['해설', 'When Lu Su came to ask for Jingzhou back, Liu Bei silently looked at Zhuge Liang.'],
      ['노숙', 'Imperial Uncle, Jingzhou is land the east won in battle. Please return it now.'],
      ['제갈량', 'Jingzhou belonged to Liu Biao, and my lord is a member of the same Han royal family.'],
      ['제갈량', 'But we have nowhere else to live now. When we take the west, we will return Jingzhou.'],
      ['해설', 'Lu Su went back with only a written promise. People said Liu Bei had borrowed Jingzhou.'],
      ['해설', 'Zhou Yu stamped his feet when he saw it. Then news came that Liu Bei’s wife had died.'],
      ['주유', 'My lord, invite Liu Bei to marry your sister. When he comes, we will hold him and trade him for Jingzhou.'],
      ['손권', 'A good plan. But do not tell my sister. You know her temper.'],
      ['해설', 'When the marriage offer came, Liu Bei hesitated. It meant walking into a tiger’s den on his own feet.'],
      ['유비', 'Adviser, is this not a trap? I fear that if I go, I will never come back.'],
      ['제갈량', 'Go. Zhao Yun will go with you. I have given Zilong three silk pouches.'],
      ['제갈량', 'Whenever the way is blocked, open one. Inside, you will find a way out.'],
      ['해설', 'Following the first pouch, Zhao Yun spread news of the marriage all over the city as soon as they arrived.'],
      ['해설', 'The rumor reached Lady Wu, Sun Quan’s mother. She was furious that she alone had not known about her daughter’s marriage.'],
      ['오국태', 'You want to use my daughter as bait? First I will see this man with my own eyes.'],
      ['해설', 'When Lady Wu met Liu Bei at Ganlu Temple, she liked his generous face and polite speech.'],
      ['오국태', 'He is truly worthy to be my son-in-law. Whoever harms him harms me.'],
      ['해설', 'The trick had become a real marriage. So Zhou Yu tried to keep Liu Bei in the east with fine palaces and feasts.'],
      ['해설', 'As the year ended, Zhao Yun opened the second pouch. Then he gave Liu Bei false news that Jingzhou was in danger.'],
      ['손부인', 'I belong to the Liu family now. Wherever my husband goes, I will go too.'],
      ['해설', 'Lady Sun was so bold that even her maids carried swords. The couple left the city, saying they would hold a New Year ceremony.'],
      ['해설', 'When eastern generals blocked the road, Zhao Yun opened the third pouch and told Lady Sun everything.'],
      ['손부인', 'My brother used me as bait? I will not forgive anyone who blocks my way. Stand aside!'],
      ['해설', 'The generals did not dare stop Lady Sun. At the river, boats sent ahead by Zhuge Liang were waiting.'],
      ['해설', 'Zhou Yu’s soldiers chased by boat but fell into an ambush. On the bank, men mocked them for losing a bride and an army.'],
      ['주유', 'Heaven gave birth to me. Why did it also give birth to Zhuge Liang?'],
      ['해설', 'Unable to calm his anger, Zhou Yu died not long after, at only thirty-six.'],
      ['해설', 'Around then, Pang Tong, the Young Phoenix, came to Liu Bei. Now Liu Bei looked west, beyond the rough mountains to Yizhou.'],
      ['해설', 'From this story comes a saying about losing a wife and an army too. It describes a trick that doubles your own loss.'],
    ],
  },

  'sg-14': {
    title: 'Romance of the Three Kingdoms, Part 14',
    names: { 해설: 'Narrator', 유비: 'Liu Bei', 방통: 'Pang Tong', 제갈량: 'Zhuge Liang', 장비: 'Zhang Fei', 엄안: 'Yan Yan' },
    outro: [
      'Liu Bei took the land of Liu Zhang, his own relative. How would you judge it, between loyalty and reality?',
      'What did Zhang Fei gain by freeing Yan Yan, and what does winning by heart mean?',
      'When keeping your principles clashes with reaching a goal, how do you decide?',
    ],
    lines: [
      ['해설', 'Liu Bei had borrowed Jingzhou and could breathe again. Now both the Sleeping Dragon and the Young Phoenix were at his side.'],
      ['해설', 'Around then, Zhang Song came from Yizhou in the west. He carried a map of its mountain roads, castles, and storehouses.'],
      ['해설', 'Liu Zhang, the lord of Yizhou, was soft-hearted. He always feared that Zhang Lu of Hanzhong would invade from the north.'],
      ['해설', 'Zhang Song and Fa Zheng believed Liu Bei was the man to protect Yizhou. They persuaded Liu Zhang to invite him.'],
      ['유비', 'Liu Zhang is a member of the Han royal family like me. If I take his land, what will the world say?'],
      ['방통', 'In a world of chaos, those who only walk the straight path protect nothing. Take it, then care for the people well. That is true loyalty.'],
      ['해설', 'After long thought, Liu Bei left Jingzhou to Zhuge Liang, Guan Yu, Zhang Fei, and Zhao Yun. He went west with Pang Tong.'],
      ['해설', 'Liu Zhang came out of his city to welcome Liu Bei warmly. But before long, the two fell out.'],
      ['방통', 'Now you must decide. If you wait, you will face enemies in front and behind.'],
      ['해설', 'Liu Bei’s army marched south and surrounded Luo Castle. The mountains were high and the roads narrow, so the fight dragged on.'],
      ['해설', 'On the morning of the attack, Pang Tong’s horse reared up in fright. Liu Bei gave him his own white horse.'],
      ['유비', 'Adviser, this horse is gentle. Ride it, and please take care.'],
      ['방통', 'I accept your kindness, my lord. This trip will be the key to opening Luo Castle.'],
      ['해설', 'The narrow valley Pang Tong passed through was called Luofengpo, the Slope of the Fallen Phoenix.'],
      ['해설', 'Archers in the woods thought the rider on the white horse was Liu Bei. They shot all at once, and the Young Phoenix never rose again.'],
      ['유비', 'How can heaven be so cruel? If only I had not given him that horse.'],
      ['해설', 'Hearing the news, Zhuge Liang left Jingzhou to Guan Yu. He hurried west with Zhang Fei and Zhao Yun.'],
      ['해설', 'In Bajun, Zhang Fei was blocked by an old general, Yan Yan. Though captured, the white-haired Yan Yan held his head high.'],
      ['엄안', 'In our land there are generals who lose their heads, but none who kneel and surrender.'],
      ['장비', 'Well, well, what a man. I lose. I bow to your spirit.'],
      ['해설', 'Zhang Fei untied the ropes himself and gave Yan Yan the seat of honor. Moved, Yan Yan opened the castles along the road.'],
      ['제갈량', 'General Zhang won a man not by force but by heart. That is the greatest victory.'],
      ['해설', 'Soon Ma Chao, a fierce general from the west, came to join Liu Bei. When he appeared before Chengdu, the city was shaken.'],
      ['해설', 'Saying he could not let the people suffer anymore, Liu Zhang opened the gates and walked out.'],
      ['유비', 'This was not what I first wanted, but it has come to this. Your family and property will be kept safe.'],
      ['해설', 'In 214, Liu Bei entered Chengdu and became lord of Yizhou. The wandering general finally had a solid home.'],
      ['제갈량', 'Now you hold Jingzhou and Yizhou. Half of the plan I told you in the cottage has come true.'],
      ['해설', 'But the joy did not last. The east asked for Jingzhou again, and in the north, Cao Cao was reaching for Hanzhong.'],
      ['해설', 'The name Luofengpo comes from the novel. The official history says Pang Tong was hit by an arrow at Luo and died at thirty-six.'],
    ],
  },

  'sg-15': {
    title: 'Romance of the Three Kingdoms, Part 15',
    names: { 해설: 'Narrator', 조조: 'Cao Cao', 유비: 'Liu Bei', 제갈량: 'Zhuge Liang', 황충: 'Huang Zhong', 양수: 'Yang Xiu' },
    outro: [
      'Was Cao Cao’s punishment of Yang Xiu a fair decision, or jealousy of his talent?',
      'What was Cao Cao really feeling when he said chicken ribs? Try to explain it.',
      'Is there something in your life like chicken ribs, something you cannot use but cannot let go?',
    ],
    lines: [
      ['해설', 'While Liu Bei settled in Yizhou, Cao Cao defeated Zhang Lu and took Hanzhong first. Now he pressed on Yizhou’s northern gate.'],
      ['해설', 'Hanzhong was like the throat of Yizhou. Neither Liu Bei nor Cao Cao could give it up.'],
      ['제갈량', 'Without Hanzhong, Yizhou will be a house without a door. Now is the time to take it.'],
      ['해설', 'Liu Bei led his army north. Cao Cao’s general guarding Hanzhong was Xiahou Yuan.'],
      ['해설', 'In Liu Bei’s camp was the white-haired old general Huang Zhong. People worried about his age, but he only snorted.'],
      ['황충', 'Hands pull the bowstring, not age. Leave Dingjun Mountain to this old man.'],
      ['해설', 'With the adviser Fa Zheng, Huang Zhong took a high peak across from Dingjun Mountain. Then he waited for the enemy to tire.'],
      ['해설', 'As the sun went down and Xiahou Yuan’s men grew careless, drums boomed like thunder from the mountain.'],
      ['해설', 'Huang Zhong raced down the slope like the wind and struck down Xiahou Yuan in one charge. The enemy camp collapsed.'],
      ['황충', 'They say an old horse knows the way. Today this old man opened the way.'],
      ['해설', 'In 219, hearing the news, Cao Cao came down to Hanzhong himself with a great army.'],
      ['조조', 'How dare Liu Bei beat my general! This time I will bring him to his knees myself.'],
      ['해설', 'But Liu Bei camped in rough places and would not come out. Zhao Yun struck their supplies, and Cao Cao’s men grew weaker every day.'],
      ['해설', 'The way forward was blocked, but retreat might make him a laughingstock. Cao Cao sat thinking over a bowl of chicken soup.'],
      ['해설', 'Then Xiahou Dun came in and asked for the night’s password. Cao Cao looked at the chicken ribs in his bowl.'],
      ['조조', 'Chicken ribs. Let it be chicken ribs.'],
      ['해설', 'When Yang Xiu, a record keeper, heard this, he started packing at once.'],
      ['양수', 'Chicken ribs have no meat to eat, but they are a pity to throw away. The chancellor has already decided to go home.'],
      ['해설', 'As Yang Xiu’s reading spread, the whole camp started packing. Cao Cao saw it on his night rounds, and his face hardened.'],
      ['조조', 'Who dared guess my mind and shake the army’s spirit?'],
      ['해설', 'In the novel, Cao Cao executes Yang Xiu for disturbing the army. But a few days later, Cao Cao pulled back after all.'],
      ['해설', 'Yang Xiu was very talented, but he showed off his talent too much and earned Cao Cao’s hatred.'],
      ['해설', 'At last Hanzhong fell into Liu Bei’s hands. His officials asked him to become a king.'],
      ['유비', 'I am a servant of the Han. How could I dare call myself a king?'],
      ['제갈량', 'The people look to you because you will restore the Han. When your title is right, your cause stands too.'],
      ['해설', 'In 219, Liu Bei became King of Hanzhong. Guan Yu, Zhang Fei, Ma Chao, and Huang Zhong received high titles as generals.'],
      ['해설', 'In Jingzhou, Guan Yu heard the news and looked north toward Fancheng. Now it was his turn to take a great step.'],
      ['해설', 'The chicken rib story comes from an old record quoted in the notes to the official history. It became a word for being stuck between two choices.'],
    ],
  },

  'sg-16': {
    title: 'Romance of the Three Kingdoms, Part 16',
    names: { 해설: 'Narrator', 관우: 'Guan Yu', 여몽: 'Lu Meng', 육손: 'Lu Xun', 손권: 'Sun Quan' },
    outro: [
      'Was Guan Yu’s great pride his strength or his weakness? Think about the attitude a leader needs.',
      'What did Lu Meng and Lu Xun use before their swords? Why did the plan with merchants in white succeed?',
      'Have you ever relaxed because of praise or humble words, and then regretted it? How should we take such words?',
    ],
    lines: [
      ['해설', 'In the year Liu Bei became King of Hanzhong, Guan Yu, who guarded Jingzhou, led an army north to Fancheng.'],
      ['해설', 'Fancheng was a key castle held by Cao Cao’s cousin Cao Ren. Cao Cao sent Yu Jin and Pang De with a large army to save it.'],
      ['관우', 'Once the northern gate opens, the capital is close. This time I will open the way to restore the Han.'],
      ['해설', 'As autumn deepened, heavy rain poured for more than ten days. Guan Yu watched the sky and had boats and rafts made ready.'],
      ['해설', 'Soon the Han River overflowed, and the fields became a sea. Yu Jin’s seven armies, camped on low ground, were trapped by water.'],
      ['해설', 'Guan Yu sailed out and accepted Yu Jin’s surrender. Pang De refused to kneel to the end and lost his life.'],
      ['해설', 'Guan Yu’s name shook the heartland. Even Cao Cao talked about moving his capital to escape his blade.'],
      ['관우', 'Only Fancheng is left. It is just a matter of time before it falls.'],
      ['해설', 'But while Guan Yu looked only north, other eyes across the river to the east were watching Jingzhou.'],
      ['해설', 'Lu Meng, a general of the east, waited for Guan Yu to leave Jingzhou empty. He pretended to be very ill and stepped down.'],
      ['여몽', 'Guan Yu is brave but too proud, and he looks down on others. If an unknown young man takes my place, he will relax.'],
      ['해설', 'Lu Meng’s place went to Lu Xun, a young scholar. Lu Xun sent Guan Yu a very humble letter.'],
      ['육손', 'Not even the famous generals of old can match your glory. A scholar like me can only look up to you from afar.'],
      ['관우', 'Sun Quan has made a young bookworm his general. Now I need not worry about the east.'],
      ['해설', 'Guan Yu called more soldiers from Jingzhou to Fancheng. That was the very moment Lu Meng had been waiting for.'],
      ['해설', 'Lu Meng dressed his best soldiers in white like merchants and hid them in trading boats.'],
      ['해설', 'The boats sailed up the river and silently passed Guan Yu’s beacon towers. The warning fires were never lit.'],
      ['여몽', 'Do not touch even a needle of the people’s things. Care for the families of Guan Yu’s soldiers as if they were my own.'],
      ['해설', 'Jingzhou’s castles fell to the east one after another. Hearing their families were safe, Guan Yu’s soldiers lost the will to fight.'],
      ['해설', 'Cao Cao’s rescue army was in front, and the eastern army behind. Guan Yu led his remaining men into Maicheng, a small castle.'],
      ['관우', 'Losing Jingzhou is my fault. But how could Guan Yunchang ever kneel to an enemy?'],
      ['해설', 'Guan Yu left flags and straw figures on the walls and slipped out at night with a few soldiers.'],
      ['해설', 'But eastern soldiers were hiding along every mountain road. Guan Yu and his son Guan Ping were finally captured.'],
      ['손권', 'General, will you join me and win the land together? I truly value your talent.'],
      ['관우', 'I cannot break the oath I swore with my brother in the Peach Garden. Jade may break, but its whiteness never changes.'],
      ['해설', 'That winter, Guan Yu refused to surrender to the end and died with his son. The novel says even Red Hare stopped eating.'],
      ['해설', 'When news of Jingzhou’s loss reached Chengdu, Liu Bei collapsed. The brothers’ oath was turning into a fire of revenge.'],
      ['해설', 'Guan Yu was later worshiped as a god, and shrines were built in many places. Dongmyo, outside Dongdaemun Gate in Seoul, is one of them.'],
    ],
  },

  'sg-17': {
    title: 'Romance of the Three Kingdoms, Part 17',
    names: { 해설: 'Narrator', 조조: 'Cao Cao', 화타: 'Hua Tuo', 조비: 'Cao Pi', 조식: 'Cao Zhi', 헌제: 'Emperor Xian' },
    outro: [
      'What do Cao Cao’s last words tell us about the kind of leader he was?',
      'What does Cao Zhi’s seven-step poem say through beans and stalks, and what power does such a comparison have?',
      'When people who are close become rivals, what feelings should we not lose?',
    ],
    lines: [
      ['해설', 'After Guan Yu died, Sun Quan sent his remains to Cao Cao in Luoyang. He hoped to push the blame onto Cao Cao.'],
      ['조조', 'Yunchang, you never became my man. But I never forgot you.'],
      ['해설', 'Cao Cao buried Guan Yu with the honors of a lord. Around then, terrible headaches began to attack Cao Cao.'],
      ['해설', 'People called for Hua Tuo, a famous doctor. After examining Cao Cao, Hua Tuo said nothing for a long time.'],
      ['화타', 'The root of the illness is deep in your head. You must take a sleeping medicine, and then I will open your head to treat it.'],
      ['조조', 'Open my head? You were close to Guan Yu. You want to kill me with this chance!'],
      ['해설', 'The suspicious Cao Cao threw Hua Tuo in prison. The novel says Hua Tuo died there, and his medical book was lost.'],
      ['해설', 'The illness grew worse every day. Cao Cao called his sons and officials to his bedside.'],
      ['조조', 'For over thirty years I fought across the land and beat many heroes. But I never beat Sun Quan and Liu Bei.'],
      ['조조', 'When I die, keep my funeral simple, and put no gold or jade in my tomb. Generals, do not leave your posts.'],
      ['조조', 'Pi, my eldest son, you will take charge of this country. Take good care of your brothers.'],
      ['해설', 'In the first month of 220, Cao Cao died in Luoyang at sixty-six. It was the end of a cunning hero who had shaken an age.'],
      ['해설', 'Cao Pi, who took his place, first kept an eye on his younger brother Cao Zhi. Cao Zhi was a genius whose poems simply flowed.'],
      ['조비', 'They say you are a great writer. Make a poem while you walk seven steps. If not, you will be punished.'],
      ['해설', 'Cao Zhi slowly began to walk. Before the seventh step, he recited in a low voice.'],
      ['조식', 'Beans are boiled over a fire of bean stalks. In the pot, the beans are weeping.'],
      ['조식', 'We grew from the same root. Why are you in such a hurry to burn me?'],
      ['해설', 'Cao Pi blushed with shame. He ended the matter by sending Cao Zhi far away.'],
      ['해설', 'That winter, Cao Pi’s officials pressed Emperor Xian of Han again and again to give up the throne.'],
      ['헌제', 'The four-hundred-year Han ends in my hands. If heaven’s will has moved, how can I go against it?'],
      ['해설', 'Emperor Xian built a high platform and handed the imperial seal to Cao Pi. This was called a peaceful handing over of the throne.'],
      ['해설', 'In 220, Cao Pi became emperor and named his country Wei. So the Han dynasty came to an end.'],
      ['해설', 'Cao Pi honored his father as Emperor Wu. Cao Cao, who never became emperor in life, got the title after death.'],
      ['해설', 'A false rumor reached Chengdu that Emperor Xian had been killed. Liu Bei wore mourning clothes and wept.'],
      ['해설', 'His officials begged him to take the throne, saying only he could carry on the Han.'],
      ['해설', 'In 221, Liu Bei became emperor in Chengdu. His country was still called Han, but later people called it Shu Han.'],
      ['해설', 'Now there were two emperors under heaven. But only one thought burned in Liu Bei’s heart. He wanted revenge on the east for Guan Yu.'],
      ['해설', 'The seven-step poem first appears in an old book of tales called Shishuo Xinyu. It is not in the official history.'],
    ],
  },

  'sg-18': {
    title: 'Romance of the Three Kingdoms, Part 18',
    names: { 해설: 'Narrator', 유비: 'Liu Bei', 장비: 'Zhang Fei', 조운: 'Zhao Yun', 육손: 'Lu Xun', 제갈량: 'Zhuge Liang' },
    outro: [
      'Liu Bei rejected Zhao Yun’s advice. How would you judge his balance of feelings and judgment?',
      'Lu Xun waited for over half a year without fighting. Why was this a brilliant plan?',
      'Have you ever regretted a decision made in anger? What could help in such moments?',
    ],
    lines: [
      ['해설', 'The first thing Emperor Liu Bei said was that he would attack the east. Grief for Guan Yu clouded his judgment.'],
      ['조운', 'Your Majesty, our enemy is Wei, not Sun Quan. If we strike Wei first, the east will bow on its own.'],
      ['유비', 'If I cannot avenge my brother, what use is being emperor? Do not stop me anymore.'],
      ['해설', 'Zhang Fei, guarding Langzhong, wept day and night and urged him to march. When drunk, he often treated his men harshly.'],
      ['장비', 'In three days, make white armor and white flags for the whole army! We will march in mourning to avenge my brother!'],
      ['해설', 'His officers Fan Jiang and Zhang Da said the time was too short. Zhang Fei tied them to a tree and punished them harshly.'],
      ['해설', 'Full of hatred, the two killed Zhang Fei that night as he lay drunk. Then they fled to the east.'],
      ['해설', 'When Liu Bei heard an urgent letter had come from Zhang Fei’s camp, he groaned before even opening it.'],
      ['유비', 'Ah, Yide is gone. My brothers who swore to die on the same day are both gone now.'],
      ['해설', 'In autumn 221, Liu Bei led a great army east along the Yangtze River. He won the first few battles.'],
      ['해설', 'Worried, Sun Quan asked for peace, but Liu Bei refused. Sun Quan made the young Lu Xun his grand commander.'],
      ['해설', 'The old generals of the east grumbled about taking orders from a scholar. Lu Xun stood before them, holding the sword Sun Quan gave him.'],
      ['육손', 'My lord gave me this sword because I know how to be patient. Anyone who fights without orders will face military law.'],
      ['해설', 'Lu Xun shut his camp tight and did not fight for over half a year. However much the enemy challenged him, he did not answer.'],
      ['해설', 'Summer came with burning heat. Liu Bei moved his tired soldiers into cool forests and valleys to camp.'],
      ['해설', 'The camps stretched one after another along the mountains and woods for hundreds of li.'],
      ['육손', 'They have lost their first sharpness, and their camps are strung out in the woods. Now it is time to win with fire.'],
      ['해설', 'One summer night in 222, eastern soldiers each carried a bundle of grass. They crept up to Liu Bei’s camps and set them on fire.'],
      ['해설', 'Riding the wind, the fire spread from forest to forest. The linked camps fell one after another, and the night sky turned red.'],
      ['해설', 'The same fire that had crushed Cao Cao at Red Cliffs now fell upon Liu Bei’s army.'],
      ['유비', 'Beaten by that young scholar? Is this also heaven’s will?'],
      ['해설', 'His generals threw themselves at the enemy to open a path, and Liu Bei barely escaped to Baidi Castle.'],
      ['해설', 'In the novel, Lu Xun gives chase but gets lost in a maze of stones at Yufu. It was the Eight Formations Zhuge Liang had built.'],
      ['해설', 'In Chengdu, Zhuge Liang heard of the defeat and let out a long sigh.'],
      ['제갈량', 'If Fa Zheng were alive, he would have stopped His Majesty. Even if he went, we would not have lost so badly.'],
      ['해설', 'In a war that began with one man’s anger, Shu Han lost almost all of its best soldiers.'],
      ['해설', 'Liu Bei stayed at Baidi Castle and never returned to Chengdu. Day by day, his body and spirit grew weaker.'],
      ['해설', 'The official history says Cao Pi heard that Liu Bei’s camps stretched seven hundred li. He said Liu Bei did not understand war.'],
    ],
  },

  'sg-19': {
    title: 'Romance of the Three Kingdoms, Part 19',
    names: { 해설: 'Narrator', 유비: 'Liu Bei', 제갈량: 'Zhuge Liang', 유선: 'Liu Shan', 등지: 'Deng Zhi' },
    outro: [
      'Liu Bei even told Zhuge Liang to take the country himself. Was it deep trust, or a test?',
      'Do not do evil because it is small, and do not skip good because it is small. Why is this pattern so memorable?',
      'If someone trusted you deeply with a big task, how would you want to answer that trust?',
    ],
    lines: [
      ['해설', 'After his great defeat at Yiling, Liu Bei fell ill at Baidi Castle. In spring 223, he urgently called Zhuge Liang from Chengdu.'],
      ['해설', 'When Zhuge Liang arrived, Liu Bei was so thin that even sitting up was hard for him.'],
      ['해설', 'By the sickbed stood Ma Su and several officials who had come with Zhuge Liang, holding their breath.'],
      ['유비', 'Chancellor, I did not listen to you and insisted on my own way. Now I am too ashamed to face you.'],
      ['제갈량', 'Your Majesty, please do not say that. When you recover, you will have your chance again.'],
      ['해설', 'Liu Bei weakly shook his head. When Ma Su stepped out, he asked in a low voice.'],
      ['유비', 'Chancellor, what do you think of Ma Su?'],
      ['제갈량', 'He has rare talent and knowledge. I think he is one of the finest minds of our time.'],
      ['유비', 'To me, his words go beyond his real ability. Do not give him important tasks. Please watch him carefully.'],
      ['해설', 'Zhuge Liang bowed his head. He did not yet know how heavily this advice would come back later.'],
      ['해설', 'Liu Bei called all his officials in. Then he took Zhuge Liang’s hand with a trembling hand.'],
      ['유비', 'Your talent is ten times that of Cao Pi. You will surely bring peace to the country and achieve the great task.'],
      ['유비', 'If my son is worth helping, help him. But if he is not up to it, you should take the country yourself.'],
      ['해설', 'The room fell silent as if frozen. Zhuge Liang wept and bowed down to the floor.'],
      ['제갈량', 'How could I ever dare? I will serve with all my strength and keep your wishes until my life ends.'],
      ['해설', 'Liu Bei left a last letter for his son, Crown Prince Liu Shan, in Chengdu.'],
      ['유비', 'Do not do an evil thing because it is small. Do not fail to do a good thing because it is small.'],
      ['유비', 'Only kindness and virtue make people follow you. Serve the chancellor like a father, and run the country with him.'],
      ['해설', 'In summer 223, Liu Bei died at sixty-three. Nearly forty years had passed since the young mat weaver swore his oath.'],
      ['해설', 'Back in Chengdu, Zhuge Liang made seventeen-year-old Liu Shan emperor.'],
      ['유선', 'Chancellor, I still know nothing. I leave all the country’s affairs to you.'],
      ['해설', 'Zhuge Liang faced a mountain of work. The army had shrunk, the storehouses were empty, and the southern towns were restless.'],
      ['제갈량', 'We cannot fight Wei and Wu at the same time. First, we must join hands with the east again.'],
      ['해설', 'Zhuge Liang sent Deng Zhi, a skilled speaker, to the east. In the novel, Sun Quan greets him with a pot of boiling oil.'],
      ['등지', 'Shu has steep mountains, and Wu has a great river. Together we can stop Wei. Apart, we will be swallowed one by one.'],
      ['해설', 'Sun Quan laughed and had the pot taken away. The two countries that had become enemies joined hands again.'],
      ['해설', 'With the east calmed, Zhuge Liang now looked south. Meng Huo of Nanzhong had gathered his people to resist Shu.'],
      ['해설', 'Liu Bei telling Zhuge Liang to take the country himself is not only a scene in the novel. It is also in the official history.'],
    ],
  },

  'sg-20': {
    title: 'Romance of the Three Kingdoms, Part 20',
    names: { 해설: 'Narrator', 제갈량: 'Zhuge Liang', 마속: 'Ma Su', 맹획: 'Meng Huo', 축융: 'Lady Zhurong' },
    outro: [
      'Why did Zhuge Liang free Meng Huo seven times even after winning? How would you judge his leadership?',
      'How does Ma Su’s advice to attack hearts connect to the seven captures?',
      'Winning by force or persuading by heart: which has lasted longer in your own life?',
    ],
    lines: [
      ['해설', 'After joining hands with the east again, Zhuge Liang led his army south himself in the spring of 225.'],
      ['해설', 'Nanzhong was a land of high mountains, deep jungles, heat, and disease. Its people followed Meng Huo as their leader.'],
      ['해설', 'On the day he left, Ma Su came out of the city to see him off and spoke carefully.'],
      ['마속', 'The southern people trust in their far and rough land. Even if they give in today, they will turn against us tomorrow.'],
      ['마속', 'Attacking hearts is better than attacking castles. Winning hearts is better than winning with soldiers.'],
      ['제갈량', 'That is just what I think. This trip is not to win land, but to win people’s hearts.'],
      ['해설', 'In midsummer, the Shu army crossed the hot Lu River and went deep into the south. The midday heat took their breath away.'],
      ['해설', 'In the first battle, Meng Huo fell into Zhuge Liang’s ambush and was easily captured.'],
      ['맹획', 'I was caught only because the road was narrow. If we fight again, I will never lose!'],
      ['제갈량', 'Then go back and gather your army again. If you are caught next time, will you truly follow me?'],
      ['해설', 'The generals were amazed. But Zhuge Liang fed Meng Huo, showed him around the camp, and sent him home.'],
      ['맹획', 'So this is all the Shu camp is? Next time, I will surely catch Kongming himself.'],
      ['해설', 'But the second and third times ended the same way. Once, his own tired men even tied him up and handed him over.'],
      ['해설', 'Meng Huo tried a false surrender to find a chance, but Zhuge Liang saw through it and caught him again.'],
      ['해설', 'Meng Huo’s wife, Lady Zhurong, also rode out. She was a woman warrior whose swift blade troubled the Shu generals.'],
      ['축융', 'If the men cannot do it, I will. I will protect the pride of the south!'],
      ['해설', 'But Lady Zhurong was also caught by Zhuge Liang’s trick, and he politely sent her back too.'],
      ['해설', 'Meng Huo fell back to a land with poisonous springs. He even borrowed the help of a tribe that commanded wild beasts.'],
      ['해설', 'Local people told Zhuge Liang about a spring that cured poison. He also built huge beast-shaped carts that scared the wild animals away.'],
      ['해설', 'The more he was caught and freed, the quieter Meng Huo’s boasting became.'],
      ['해설', 'The seventh time he was caught, Zhuge Liang again told him to go home. But Meng Huo did not move.'],
      ['맹획', 'No one has ever been caught seven times and freed seven times. Even I know shame.'],
      ['맹획', 'Chancellor, you have the power of heaven. The people of the south will never rebel again.'],
      ['해설', 'Zhuge Liang left Nanzhong to Meng Huo and the local leaders. He did not leave many Shu officials or soldiers there.'],
      ['제갈량', 'If outsiders stay, we must feed soldiers, and hatred will grow. Letting them rule themselves is the lasting way.'],
      ['해설', 'With the south at peace, Shu Han gained supplies and soldiers. Its backyard was now strong enough for a march north.'],
      ['해설', 'Back in Chengdu, Zhuge Liang took up a long-delayed task. It was the late emperor’s last wish, to attack Wei in the north.'],
      ['해설', 'The seven captures are not in the main text of the official history. The story comes from an old record quoted in its notes.'],
    ],
  },

  'sg-21': {
    title: 'Romance of the Three Kingdoms, Part 21',
    names: { 해설: 'Narrator', 제갈량: 'Zhuge Liang', 유선: 'Liu Shan', 조운: 'Zhao Yun', 위연: 'Wei Yan', 강유: 'Jiang Wei' },
    outro: [
      'Zhuge Liang chose the main road over a risky shortcut. How would you judge that as a leader?',
      'How does Zhuge Liang show his true heart in the memorial, and why has it been read for so long?',
      'Have you ever given your all to repay someone’s trust and kindness?',
    ],
    lines: [
      ['해설', 'After calming the south, Zhuge Liang trained soldiers and gathered grain. In 227, he was finally ready to march north.'],
      ['해설', 'Before leaving, Zhuge Liang sent a letter to Emperor Liu Shan. It was the Chu Shi Biao, the Memorial on Sending Out the Army.'],
      ['해설', 'It held advice for the young emperor and longing for the late emperor.'],
      ['제갈량', 'The late emperor died before his great work was half done. The land is split in three, and Yizhou is worn out. This is a time of real danger.'],
      ['제갈량', 'Your Majesty, open your ears to honest words. Do not belittle yourself and close the mouths of your officials.'],
      ['제갈량', 'Staying close to wise ministers made the Former Han rise. Staying close to petty men made the Later Han fall.'],
      ['제갈량', 'I was only a farmer in Nanyang, hoping just to stay alive in a troubled world.'],
      ['제갈량', 'But the late emperor did not look down on me. He humbled himself and visited my cottage three times.'],
      ['제갈량', 'On his deathbed he left the great task to me. Since then, I have worried day and night that I might fail him.'],
      ['제갈량', 'Now the south is at peace and our army is strong. I will retake the heartland and restore the Han.'],
      ['제갈량', 'As I leave on a long journey, tears blur my eyes, and I do not know what I have written.'],
      ['해설', 'As he read the memorial, Liu Shan’s eyes also turned red.'],
      ['유선', 'Father Chancellor, you just came back from the south. Why must you suffer again?'],
      ['제갈량', 'Since the late emperor’s request, I have not slept in peace for a single day. If I do not go now, there will be no other chance.'],
      ['해설', 'The next spring, the Shu Han army marched north. The white-haired old general Zhao Yun asked to lead the way.'],
      ['조운', 'If you leave me behind because I am old, I will regret it all my life. Let me lead the front.'],
      ['해설', 'At the war council, Wei Yan offered a bold plan.'],
      ['위연', 'Give me just five thousand of our best soldiers. I will take the steep Ziwu Valley and strike Chang’an at once.'],
      ['제갈량', 'That road is too dangerous. If it goes wrong, we will lose everyone. We will take the main road and gain land step by step.'],
      ['위연', 'Chancellor, you are too careful. At this rate, we will miss our good chance.'],
      ['해설', 'Leaving Wei Yan’s complaints behind, Zhuge Liang marched to Qishan. Three districts of Wei soon joined the Shu side.'],
      ['해설', 'In Tianshui there was a young general named Jiang Wei. He saw through Zhuge Liang’s plans several times and troubled the Shu army.'],
      ['제갈량', 'This is the man to whom I can pass on everything I have learned in my life.'],
      ['해설', 'Zhuge Liang used a trick to make Wei suspect Jiang Wei. With nowhere to go, Jiang Wei finally stood before Zhuge Liang.'],
      ['강유', 'I will give myself to the one who sees my worth. I will follow your will, Chancellor.'],
      ['해설', 'The Wei court was thrown into an uproar. Cao Rui, who followed Cao Pi as emperor, called back a man who had been sent away.'],
      ['해설', 'It was Sima Yi, the rival Zhuge Liang feared most. And the fate of the Shu army would hang on a small pass called Jieting.'],
      ['해설', 'The full text of the Chu Shi Biao is recorded in Zhuge Liang’s biography in the official history.'],
    ],
  },

  'sg-22': {
    title: 'Romance of the Three Kingdoms, Part 22',
    names: { 해설: 'Narrator', 제갈량: 'Zhuge Liang', 사마의: 'Sima Yi', 마속: 'Ma Su', 왕평: 'Wang Ping', 장합: 'Zhang He' },
    outro: [
      'Zhuge Liang did not forgive Ma Su, whom he loved. Was it right for a leader? Was there another way?',
      'How did Ma Su and Wang Ping judge differently? How is knowing the books different from reading the situation?',
      'If a close friend broke a rule, how would you act between fairness and friendship?',
    ],
    lines: [
      ['해설', 'Zhuge Liang’s first march north went well. But when Sima Yi of Wei came with a great army, the tide began to turn.'],
      ['사마의', 'Zhuge Liang’s weak spot is Jieting. If we take it, their supply line is cut, and they must retreat.'],
      ['해설', 'Jieting was the throat of the supply road from Hanzhong. Zhuge Liang thought long about whom to send there.'],
      ['마속', 'Chancellor, I will guard Jieting. I have read books on war since I was young. Surely I can hold one small pass.'],
      ['제갈량', 'Jieting has no walls and no strong fort. If we lose it, our whole army will fall.'],
      ['마속', 'If I fail, I will gladly face military law. I will write a pledge.'],
      ['해설', 'Zhuge Liang sent Ma Su to Jieting with the careful general Wang Ping. He told them again and again to camp across the road.'],
      ['해설', 'When Ma Su reached Jieting, he looked up at a mountain beside the road.'],
      ['마속', 'The books say attacking from high ground is as easy as splitting bamboo. We will camp on the mountain.'],
      ['왕평', 'General, there is no water on the mountain. If the enemy surrounds it and cuts off the water, we will fall without a fight.'],
      ['마속', 'You do not know the art of war. When you stand on deadly ground, a way to live opens.'],
      ['해설', 'Wang Ping had no choice. He took only a thousand men and camped below. Then he drew the camp and sent the drawing to Zhuge Liang.'],
      ['해설', 'When Wei general Zhang He arrived, he saw the Shu army on the mountain and laughed out loud.'],
      ['장합', 'Sitting on a mountain with no water? If we surround it and block the water, they will fall on their own.'],
      ['해설', 'Zhang He surrounded the mountain and cut off the water path. The thirsty Shu soldiers lost strength day by day and scattered.'],
      ['해설', 'Ma Su broke through and fled. Wang Ping held firm and beat his drums, so the rest could retreat in order.'],
      ['해설', 'When Zhuge Liang opened Wang Ping’s drawing, he struck his desk.'],
      ['제갈량', 'Ma Su has ruined our army. Now that Jieting is lost, we must pull back all our troops.'],
      ['해설', 'They had to give up the three districts they had worked so hard to win. So the first march north ended in sorrow.'],
      ['해설', 'Back in Hanzhong, Ma Su tied himself up and came to bow before Zhuge Liang.'],
      ['마속', 'You loved me like a son, but I failed you. Please take care of my family.'],
      ['제갈량', 'We were like brothers. I will look after your family to the end. But I cannot set aside military law.'],
      ['해설', 'The generals begged him to spare such a talent, but Zhuge Liang shook his head.'],
      ['제갈량', 'If the law is not upheld, how can we beat the enemy? If I bend the law for those I love, who will obey orders again?'],
      ['해설', 'As Ma Su was led away, Zhuge Liang covered his face with his sleeve and wept for a long time.'],
      ['해설', 'He remembered the late emperor’s warning at Baidi Castle. Ma Su’s words went beyond his ability, so he should not get big tasks.'],
      ['해설', 'Zhuge Liang took the blame for the defeat and asked to be lowered three ranks. Wang Ping was praised and promoted.'],
      ['해설', 'The novel also says that on the very day Jieting fell, Zhuge Liang played the zither in an empty town.'],
      ['해설', 'The saying weeping while executing Ma Su means punishing even a loved one strictly by the rules.'],
    ],
  },

  'sg-23': {
    title: 'Romance of the Three Kingdoms, Part 23',
    names: { 해설: 'Narrator', 제갈량: 'Zhuge Liang', 사마의: 'Sima Yi', 사마소: 'Sima Zhao' },
    outro: [
      'Between Zhuge Liang’s boldness and Sima Yi’s caution, which do you think was the better judgment?',
      'The empty fort plan used what the enemy believed about Zhuge Liang. Can you explain the key to this trick?',
      'Do you know a time when someone stayed calm in a crisis and overcame it?',
    ],
    lines: [
      ['해설', 'Let us go back to the day Jieting fell. Zhuge Liang was in a small town called Xicheng, moving army food.'],
      ['해설', 'His generals were scattered, and only about two thousand old and weak soldiers remained in the town.'],
      ['해설', 'Then an urgent report arrived. Sima Yi was coming to Xicheng with a hundred and fifty thousand soldiers.'],
      ['해설', 'The officials turned pale. From the wall, they saw a cloud of dust covering the sky.'],
      ['제갈량', 'Lower all the flags, and let the soldiers hide. Anyone who moves around or makes noise will be punished.'],
      ['제갈량', 'Open all four gates wide. At each gate, dress twenty soldiers as townspeople and have them calmly sweep the road.'],
      ['해설', 'Zhuge Liang put on a robe of crane feathers and a silk cap and climbed the gate tower. He lit incense and set a zither on his knees.'],
      ['해설', 'When Sima Yi’s front troops reached the town, clear zither music was flowing from the tower.'],
      ['해설', 'Unable to believe the report, Sima Yi rode close to the town himself.'],
      ['해설', 'Zhuge Liang was playing the zither with a smile. Beside him stood two boys holding a sword and a whisk.'],
      ['사마의', 'The gates are open, and the sweepers are calm. Kongming has never taken a risk in his life. There must be an ambush.'],
      ['사마의', 'All troops, retreat! Turn the army to the northern mountain road at once!'],
      ['사마소', 'Father, maybe he has no soldiers and is doing this on purpose. Why retreat?'],
      ['사마의', 'You do not understand. If we fall into his trap, none of us will return alive.'],
      ['해설', 'When the Wei army left, the people in the town finally let out the breath they had been holding.'],
      ['제갈량', 'Sima Yi knows I am always careful, so he suspected a trick. I had no choice but to use this plan.'],
      ['해설', 'Later, when Sima Yi learned the truth, he looked up at the sky and sighed deeply.'],
      ['사마의', 'I am no match for Kongming.'],
      ['해설', 'After that, Zhuge Liang marched north several more times. But the road was always hard.'],
      ['해설', 'At Chencang, the Wei general Hao Zhao held the castle with few soldiers. The Shu army had to leave after about twenty days.'],
      ['해설', 'The greatest enemy of the northern marches was the rough mountain roads. The supply roads were long and narrow, and the soldiers were often hungry.'],
      ['해설', 'Zhuge Liang made carts called the wooden ox and the gliding horse to move food along steep mountain roads.'],
      ['제갈량', 'If soldiers go hungry, even the best plan is useless. Whoever beats the road wins the battle.'],
      ['해설', 'In 231, the famous Wei general Zhang He chased the retreating Shu army. He was shot down by arrows at Mumen.'],
      ['해설', 'But Sima Yi never fought head-on. He guarded his camp firmly and waited for the Shu army to run out of food.'],
      ['사마의', 'Kongming has come a long way, so he cannot last long. If we just wait, we win.'],
      ['해설', 'In the spring of 234, Zhuge Liang set out on his last march north. The Shu army camped on the Wuzhang Plains, south of the Wei River.'],
      ['해설', 'The empty fort story is in the notes to the official history, told by Guo Chong. But the note writer doubted it, since Sima Yi was elsewhere.'],
    ],
  },

  'sg-24': {
    title: 'Romance of the Three Kingdoms, Part 24',
    names: { 해설: 'Narrator', 제갈량: 'Zhuge Liang', 사마의: 'Sima Yi', 강유: 'Jiang Wei', 위연: 'Wei Yan', 사신: 'Messenger' },
    outro: [
      'Zhuge Liang never stopped marching north. Was it loyalty, or stubbornness?',
      'Dead Zhuge scared away living Zhongda. What irony is hidden in this saying?',
      'Which leader from the Three Kingdoms do you think our society needs most today?',
    ],
    lines: [
      ['해설', 'At the Wuzhang Plains, Zhuge Liang faced Sima Yi for over a hundred days. But Sima Yi never came out to fight.'],
      ['해설', 'Zhuge Liang had his soldiers farm the land to prepare for a long stay. Then he sent Sima Yi a woman’s dress and headscarf.'],
      ['제갈량', 'You call yourself a general, but you only hide and never fight. This dress suits you better.'],
      ['해설', 'The Wei generals were furious, but Sima Yi smiled and accepted the dress. Then he casually asked the Shu messenger a question.'],
      ['사마의', 'How is the chancellor these days? Does he eat well?'],
      ['사신', 'The chancellor rises at dawn and sleeps late at night, and he handles even small matters himself. He eats very little.'],
      ['해설', 'After the messenger left, Sima Yi turned to his generals.'],
      ['사마의', 'He eats little and works much. How long can he last?'],
      ['해설', 'Just as he said, Zhuge Liang’s illness grew worse. The autumn wind shook the tents on the Wuzhang Plains.'],
      ['해설', 'The novel says Zhuge Liang lit seven lamps in his tent. He prayed to the Big Dipper for a longer life.'],
      ['해설', 'If the main lamp stayed lit for seven days, his life would be longer. But on the sixth night, Wei Yan rushed in and his step put it out.'],
      ['위연', 'Chancellor, the Wei army is coming! Oh no, the lamp!'],
      ['제갈량', 'Life and death are up to heaven. They cannot be won by prayer.'],
      ['해설', 'Zhuge Liang called Jiang Wei and gave him a book of all the war strategies he had learned.'],
      ['제갈량', 'Boyue, only you can carry on my will. When I die, do not cry aloud. Pull the army back step by step.'],
      ['제갈량', 'If Sima Yi chases you, put a wooden statue of me in a carriage and turn the flags around.'],
      ['강유', 'Chancellor, please get up. There is still so much left to do.'],
      ['해설', 'In autumn 234, Zhuge Liang died in his tent at the age of fifty-four. That night, they say a great star fell over the camp.'],
      ['해설', 'When the Shu army quietly retreated, Sima Yi chased them. Then the Shu army turned its flags and beat its drums.'],
      ['해설', 'In the carriage sat Zhuge Liang, neatly dressed in his crane-feather robe.'],
      ['사마의', 'Kongming is alive! I have been fooled again. Retreat at once!'],
      ['해설', 'Sima Yi turned his horse and fled in panic. People laughed that dead Zhuge scared away living Zhongda, which was Sima Yi’s courtesy name.'],
      ['해설', 'After Zhuge Liang, Jiang Wei continued the northern marches, but Shu Han grew weaker and weaker.'],
      ['해설', 'In 263, Wei soldiers crossed the rough mountains and reached Chengdu. Liu Shan opened the gates and surrendered, and Shu Han fell first.'],
      ['해설', 'Wei did not last long either. In 265, Sima Yi’s grandson Sima Yan took the Wei throne and founded the Jin dynasty.'],
      ['해설', 'In 280, Jin soldiers crossed the Yangtze, and Sun Hao, the last emperor of Wu, surrendered. At last, the land was one again.'],
      ['해설', 'Cao Cao had shaken the Han, and Cao Pi took its throne. In the very same way, Wei’s throne passed to the Sima family.'],
      ['해설', 'Nearly a hundred years had passed since the Peach Garden Oath. The heroes were all gone, but their stories lived on.'],
      ['해설', 'The saying about dead Zhuge and living Zhongda was a folk saying of that time. It is in an old record quoted in the official history’s notes.'],
    ],
  },
};
