// 청소년 영어 원고 (중학생 이상). 키 = stories/teen-ws6.js 의 이야기 id.
// 헤세·슈토름·투르게네프·고골·체호프·모파상·아나톨 프랑스·라겔뢰프 원작(퍼블릭 도메인)을 한국어 각색의 흐름대로 쉬운 영어로 새로 씀.
export default {
  'ws6-emperor-moth': {
    title: 'The Emperor Moth',
    names: { 해설: 'Narrator', 친구: 'Friend', 에밀: 'Emil', 어머니: 'Mother' },
    outro: [
      'Why do you think the friend crushed his own butterflies, one by one, at the end?',
      'Emil did not shout. He only showed cold contempt. Why was that a heavier punishment for the boy?',
      'When we make a mistake that cannot be undone, how should we live with it afterward?',
    ],
    lines: [
      ['해설', 'One summer evening, I showed an old friend the butterfly box I had started collecting again.'],
      ['해설', 'He looked at a yellow moth for a long time. Then he quietly closed the lid.'],
      ['친구', 'Forgive me. I collected butterflies as a boy too. But I ruined that memory with my own hands.'],
      ['친구', 'At ten, I was crazy about butterflies. I ran through the fields with my net and forgot my meals.'],
      ['친구', 'We were not rich, so I kept my butterflies pinned in an old cardboard box lined with cork.'],
      ['해설', 'Next door lived Emil, the teacher’s son. He was a perfect, model student.'],
      ['친구', 'His collection was small but very neat. I disliked him, and I envied him at the same time.'],
      ['친구', 'One day I caught a rare blue butterfly. I wanted to show it off, so I took it to Emil.'],
      ['에밀', 'It is a rare one. But you spread the wings badly. The feelers are bent, and the legs are damaged.'],
      ['친구', 'After that, I never showed him a butterfly again. Two years went by.'],
      ['해설', 'Then a rumor spread. Emil had raised a caterpillar into an emperor moth.'],
      ['친구', 'An emperor moth! The one with great eyes on its wings. I had only seen it in books.'],
      ['해설', 'The boy ran to Emil’s house. Nobody answered, and the door to Emil’s room was open.'],
      ['친구', 'It lay on the drying board. The four eyes on its brown wings stared right at me.'],
      ['친구', 'Before I knew it, the moth was in my hand. I only wanted to have it.'],
      ['해설', 'On the stairs, he heard someone coming up. He pushed the moth into his pocket.'],
      ['친구', 'Then I understood. I had become a thief. I hurried back to the room and took out my hand.'],
      ['친구', 'The moth was broken. A front wing and a feeler had come off. There was no way to fix it.'],
      ['해설', 'At home, he sat curled up all evening. At last he told his mother everything.'],
      ['어머니', 'Go to Emil and tell him yourself. Offer him anything you have, and ask him to forgive you.'],
      ['해설', 'Emil was trying to repair the broken moth. The boy stammered out the truth.'],
      ['해설', 'Emil did not shout. He only clicked his tongue once and looked at the boy for a long time.'],
      ['에밀', 'I see. Now I know exactly what kind of person you are.'],
      ['친구', 'I offered him all my toys. He shook his head, so I offered him my whole collection.'],
      ['에밀', 'No, thanks. I have seen your collection. And today I saw how you treat butterflies.'],
      ['친구', 'At that moment I was a villain, and he stood there as cold as the law of the world.'],
      ['해설', 'At home, his mother asked nothing. She kissed him and left him alone.'],
      ['친구', 'In the dark, I opened my box and crushed my butterflies with my fingers, one by one.'],
      ['해설', 'Hermann Hesse published this story in 1911, and later he wrote a revised version of it.'],
    ],
  },

  'ws6-immensee-1': {
    title: 'Immensee, Part 1',
    names: { 해설: 'Narrator', 라인하르트: 'Reinhard', 엘리자베트: 'Elisabeth', 어머니: 'Mother' },
    outro: [
      'Why do you think Reinhard lost Elisabeth?',
      'The story begins in an old man’s room and goes back to his childhood. What mood does this create?',
      'Have you ever put off saying something important and missed your chance? What made you hesitate?',
    ],
    lines: [
      ['해설', 'One late autumn afternoon, a well-dressed old man slowly walked up a hill with his cane.'],
      ['해설', 'Back in his room, he sat in an armchair. Moonlight fell on a small portrait on the wall.'],
      ['라인하르트', 'Elisabeth.'],
      ['해설', 'As he said the name, time ran backward. The old man was ten-year-old Reinhard again.'],
      ['해설', 'Elisabeth, the girl next door, was five years younger. The two always played together.'],
      ['라인하르트', 'Elisabeth, when I grow up, I will go to India. There are tigers there. I will take you too.'],
      ['엘리자베트', 'Will my mother let me go? And isn’t India too hot?'],
      ['라인하르트', 'Let’s go when we are grown up. Then nobody can stop us.'],
      ['해설', 'Years later, they went on a picnic in the woods with the grown-ups. The game was to find strawberries.'],
      ['해설', 'The two went deep into the forest and got lost. They did not find a single strawberry.'],
      ['엘리자베트', 'Reinhard, I’m scared. I hear strange sounds.'],
      ['라인하르트', 'Don’t worry. It’s only the wind. I will find the way, I promise.'],
      ['해설', 'That night, Reinhard wrote his first poem for Elisabeth in an old notebook.'],
      ['해설', 'Soon he left home for the university. He promised to send her stories in his letters.'],
      ['해설', 'On Christmas Eve in the university town, he spent a noisy night with friends in a cellar tavern.'],
      ['해설', 'In the corner, a wandering girl played the zither and sang to him. Today, only today, I am beautiful.'],
      ['해설', 'Back at his room, a package from home was waiting. There were letters from his mother and Elisabeth.'],
      ['엘리자베트', 'The little bird you gave me died last night. And you don’t send me any stories these days.'],
      ['라인하르트', 'Elisabeth, I have forgotten you for far too long.'],
      ['해설', 'Around Easter, he came home. But Elisabeth seemed somehow different.'],
      ['해설', 'A yellow canary sat by her window. Erich had given it to her in place of the dead bird.'],
      ['엘리자베트', 'Erich got his father’s farm by Immensee lake. He sometimes asks about you.'],
      ['라인하르트', 'You mean Erich, who played with us as a child? He gave you a bird?'],
      ['해설', 'The day before he left, they walked in the garden. Reinhard could hardly open his mouth.'],
      ['라인하르트', 'I can’t come back for two years. Then I will have something to tell you. Will you wait?'],
      ['엘리자베트', 'Yes. I will wait.'],
      ['해설', 'But before two years had passed, a letter came from his mother.'],
      ['어머니', 'Erich asked Elisabeth to marry him again. She said no twice, but this time she said yes.'],
      ['해설', 'Theodor Storm first published Immensee in 1849, and later he revised it and published it again.'],
    ],
  },

  'ws6-immensee-2': {
    title: 'Immensee, Part 2',
    names: { 해설: 'Narrator', 라인하르트: 'Reinhard', 엘리자베트: 'Elisabeth', 에리히: 'Erich', 노부인: 'Old Lady' },
    outro: [
      'What do you think the white water lily, which Reinhard could never reach, stands for?',
      'How do the quiet conversations and the descriptions of nature show the feelings of the two people?',
      'In those days, parents often chose whom their children married. How is that different today?',
    ],
    lines: [
      ['해설', 'In the last part, Reinhard heard that Elisabeth would marry Erich.'],
      ['해설', 'Years went by. A young man with a backpack walked down to the farm by Immensee lake.'],
      ['에리히', 'Reinhard! You really came! I didn’t tell Elisabeth on purpose. I want to surprise her.'],
      ['해설', 'Elisabeth came out in a white dress. When she saw Reinhard, she stopped still.'],
      ['엘리자베트', 'Reinhard... Welcome. I’m glad you came.'],
      ['해설', 'Erich was a kind and hardworking master. Elisabeth’s mother lived in the house too.'],
      ['해설', 'Reinhard was traveling from place to place, collecting the folk songs people sang.'],
      ['에리히', 'Tonight, let us hear the songs you have collected. We will all listen.'],
      ['해설', 'Under the lamp, Reinhard took out a sheet of paper and read in a low voice.'],
      ['라인하르트', 'It was my mother’s wish. I had to take another. I had to forget the one I loved.'],
      ['해설', 'Elisabeth quietly stood up and walked out into the dark garden without a word.'],
      ['노부인', 'She must have something to do outside. Don’t mind her.'],
      ['해설', 'In those days, a daughter’s marriage was often decided by her parents. The song touched that wound.'],
      ['해설', 'That night, Reinhard went down to the lake alone. Far out, a white water lily floated among broad leaves.'],
      ['라인하르트', 'I must pick that flower.'],
      ['해설', 'He went into the water. The flower looked close, but no matter how he swam, he could not reach it.'],
      ['해설', 'Stems wrapped around his legs. The flower floated alone on the black water. He turned back.'],
      ['해설', 'The next afternoon, Reinhard and Elisabeth walked together in the woods across the lake.'],
      ['라인하르트', 'Behind those blue mountains lies our childhood. Where has it all gone?'],
      ['해설', 'Elisabeth did not answer. He felt her hand tremble slightly.'],
      ['해설', 'Reinhard knew he could not stay any longer. He decided to leave quietly at dawn.'],
      ['해설', 'As he stepped out with his bag, Elisabeth was standing by the door.'],
      ['엘리자베트', 'You will never come back, will you?'],
      ['라인하르트', 'No. Never.'],
      ['해설', 'He walked on without looking back. As the sunlight spread, the farm grew smaller behind him.'],
      ['해설', 'The story returns to the old man’s room. The moonlight had already left the portrait.'],
      ['해설', 'Before his eyes rose the white lily on the black water. Far away, alone, and out of reach.'],
      ['해설', 'The maid brought in a lamp. The old man pulled up his chair and opened the books of his youth.'],
      ['해설', 'Storm was born in Husum, a seaside town in northern Germany. He worked as a lawyer and wrote poems and stories.'],
    ],
  },

  'ws6-first-love-1': {
    title: 'First Love, Part 1',
    names: { 해설: 'Narrator', 블라디미르: 'Vladimir', 지나이다: 'Zinaida', 말렙스키: 'Malevsky' },
    outro: [
      'For sixteen-year-old Vladimir, was first love a joy or a pain?',
      'Zinaida used to play with her admirers. What does her sudden change suggest?',
      'Have you ever done something risky to win someone’s approval? How did you feel then?',
    ],
    lines: [
      ['해설', 'After the guests had gone, three friends stayed and agreed to tell about their first loves.'],
      ['해설', 'Vladimir Petrovich said it was hard to tell aloud. He would write it in a notebook and read it to them.'],
      ['블라디미르', 'I was sixteen then. In the summer of 1833, my family stayed at a country house near Moscow.'],
      ['블라디미르', 'I said I was studying for exams, but I just walked in the garden every day, waiting for something.'],
      ['해설', 'A poor princess moved into the small house next door. She had a twenty-one-year-old daughter.'],
      ['블라디미르', 'I first saw her over the fence. She was laughing and tapping young men on the forehead with flowers.'],
      ['해설', 'The next day, his mother sent him on an errand to the princess, and he met Zinaida.'],
      ['지나이다', 'Vladimir, is it? You’re still a child. Let’s be friends. Will you help me wind this yarn?'],
      ['해설', 'From that day, the boy went there every day. Her admirers always gathered there.'],
      ['해설', 'A cavalry officer, a doctor, a count, a poet. One word from Zinaida made them smile or sulk.'],
      ['지나이다', 'Let’s play forfeits. Whoever draws the lucky ticket kisses my hand.'],
      ['블라디미르', 'The ticket came to me. When I kissed her hand, my head began to spin.'],
      ['해설', 'His father was young, handsome, and cold. He had married the boy’s mother, ten years older, for her money.'],
      ['블라디미르', 'My father was kind one moment and pushed me away the next. Still, I looked up to him.'],
      ['해설', 'One day, his father visited the princess and talked with Zinaida for a long time.'],
      ['해설', 'After that, Zinaida changed. She took long walks alone, grew pale, and was sharp with her admirers.'],
      ['블라디미르', 'I knew she was in love. But with whom?'],
      ['해설', 'One day, the boy was sitting on top of an old wall. Zinaida looked up at him and spoke.'],
      ['지나이다', 'If you really love me, jump down from there.'],
      ['해설', 'He jumped at once. He fainted for a moment, and when he woke, she was kissing him.'],
      ['지나이다', 'Why are you so silly? You’re not hurt, are you? Get up. But don’t follow me.'],
      ['블라디미르', 'That day I was the happiest person in the world. But the next day she treated me like a child again.'],
      ['지나이다', 'Volodya, you are my page. A page must never leave his queen’s side.'],
      ['해설', 'Then one day, Count Malevsky passed by and whispered to the boy with a mocking smile.'],
      ['말렙스키', 'A page should guard his queen at night too. Watch who comes and goes in the garden.'],
      ['해설', 'That night, the boy hid in the garden bushes with a pocketknife. His heart burned with jealousy.'],
      ['해설', 'Near dawn, someone in a cloak came up to her window. The boy recognized the face.'],
      ['블라디미르', 'It was my father. The knife fell from my hand into the grass.'],
      ['해설', 'Ivan Turgenev published his short novel First Love in 1860.'],
    ],
  },

  'ws6-first-love-2': {
    title: 'First Love, Part 2',
    names: { 해설: 'Narrator', 블라디미르: 'Vladimir', 지나이다: 'Zinaida', 하인: 'Servant', 어머니: 'Mother', 아버지: 'Father', 마이다노프: 'Maidanov' },
    outro: [
      'What do you think Vladimir learned about love through this first love?',
      'Zinaida kisses the mark left by the whip. What does it show about her, and why is it shocking?',
      'How can we recognize and stop a relationship that hurts someone in the name of love?',
    ],
    lines: [
      ['해설', 'In the last part, Vladimir found out that the man Zinaida loved was his own father.'],
      ['블라디미르', 'I could not hate her, and I could not blame my father. I just lived in a daze.'],
      ['해설', 'A few days later, there was shouting in the house. Someone had sent his mother an unsigned letter.'],
      ['하인', 'Young master, a letter came for the mistress. It was about the master and the young lady next door. She cried so hard.'],
      ['어머니', 'I can’t stay in this house another day. We are going back to the city at once!'],
      ['해설', 'The family hurried to pack. Before leaving, the boy went to see Zinaida.'],
      ['지나이다', 'Volodya, don’t think too badly of me. I couldn’t help it.'],
      ['블라디미르', 'I will love you and honor you all my life. No matter what.'],
      ['해설', 'Zinaida held him and kissed him for a long time. It was their last goodbye.'],
      ['해설', 'One day back in the city, his father took him out horse riding.'],
      ['해설', 'In a strange lane, his father gave the reins to his son and walked alone to a small house.'],
      ['블라디미르', 'I got tired of waiting and went that way. Through an open window, I saw Zinaida.'],
      ['지나이다', 'Please. Talk to me a little longer.'],
      ['해설', 'His father said something. Zinaida shook her head and held out her arm to him.'],
      ['해설', 'At that moment, his father struck her arm with the riding whip in his hand.'],
      ['해설', 'Zinaida trembled. Then, without a word, she kissed the red mark on her arm.'],
      ['블라디미르', 'I ran away. If this was love, then I knew nothing about love at all.'],
      ['해설', 'It was violence hiding behind the name of love. The boy saw the dark side of the adult world for the first time.'],
      ['해설', 'Eight months later, his father died of a stroke. A letter he received a few days before had upset him deeply.'],
      ['해설', 'Among his father’s papers, there was a short note to his son.'],
      ['아버지', 'My son, beware of a woman’s love. Beware of that happiness, that poison.'],
      ['해설', 'Later, his mother sent quite a large sum of money to Moscow. She never said who received it.'],
      ['해설', 'Four years passed. After finishing university, Vladimir happened to meet the poet Maidanov.'],
      ['마이다노프', 'Do you remember Zinaida? She is Madame Dolskaya now, and she is staying at a hotel near here.'],
      ['블라디미르', 'I made up my mind to visit her. But I put it off for weeks because of this and that.'],
      ['해설', 'When he finally went to the hotel, she had died four days before, giving birth to a child.'],
      ['블라디미르', 'A few days later, I happened to be there when a poor old woman died.'],
      ['블라디미르', 'Beside that old woman, I prayed for Zinaida, for my father, and for myself.'],
      ['해설', 'Turgenev said that this novel was based on what really happened to him in his youth.'],
    ],
  },

  'ws6-gogol-nose': {
    title: 'The Nose',
    names: { 해설: 'Narrator', 이발사: 'Barber', 아내: 'Wife', 경찰: 'Policeman', 코발료프: 'Kovalyov', 코: 'The Nose', 직원: 'Clerk' },
    outro: [
      'Through the strange case of a missing nose, what kind of society did Gogol want to laugh at?',
      'Kovalyov trembles before his own nose because it has a higher rank. Why is this funny and bitter at once?',
      'Do we still judge people by their looks or job titles today? Where can you see it?',
    ],
    lines: [
      ['해설', 'On the twenty-fifth of March, a very strange thing happened in Saint Petersburg.'],
      ['해설', 'In the morning, the barber Ivan Yakovlevich cut open a fresh loaf of bread. There was something hard inside.'],
      ['이발사', 'What’s this? A nose! And I know it! It’s the nose of Mr. Kovalyov, whom I shave!'],
      ['아내', 'You beast! You cut off a customer’s nose? Throw it away now. Not in my house!'],
      ['해설', 'The barber wrapped the nose in a rag and went out. Every time he tried to drop it, someone he knew spoke to him.'],
      ['해설', 'At last he reached Saint Isaac’s Bridge and secretly let the bundle fall into the river.'],
      ['경찰', 'Hey, what are you doing there? What did you just throw over the rail?'],
      ['해설', 'What happened next is wrapped in thick fog. Nobody knows.'],
      ['해설', 'That same morning, Kovalyov, an official of the eighth rank, woke up. He liked to call himself Major.'],
      ['해설', 'He picked up a mirror to look at a pimple. Where his nose had been, the skin was as flat as a pancake.'],
      ['코발료프', 'Impossible! My nose is gone! Like this, I can’t visit any fine lady or any office!'],
      ['해설', 'He covered his face with a handkerchief and went out. Just then, a carriage stopped.'],
      ['해설', 'A gentleman in a gold-trimmed uniform stepped out. Kovalyov was horrified. It was his own nose.'],
      ['해설', 'The Nose wore a hat with a plume and the uniform of the fifth rank. It ranked three steps above its owner.'],
      ['해설', 'The Nose went into the Kazan Cathedral and prayed with great devotion. Kovalyov hesitated, then went up to it.'],
      ['코발료프', 'Excuse me, sir. I must ask you to return to your place. You see, you are my nose.'],
      ['코', 'I have no idea what you mean. I am myself. Judging by your uniform, we work in different departments.'],
      ['해설', 'The Nose turned away and went on praying. While Kovalyov stood confused, it disappeared.'],
      ['해설', 'He tried to place an ad in a newspaper. But the clerk refused, saying it would hurt the paper’s reputation.'],
      ['직원', 'What a pity, sir. Would you like a pinch of snuff? It might cheer you up.'],
      ['코발료프', 'Are you making fun of me? Where is my nose to smell your snuff with?'],
      ['해설', 'That evening, the same policeman from the morning came to Kovalyov’s home.'],
      ['경찰', 'We found your nose, sir. It was caught trying to board a coach to Riga with someone else’s passport.'],
      ['해설', 'But the joy did not last. No matter how he pressed the nose to his face, it would not stick.'],
      ['해설', 'The doctor told him to live without it. He even said the nose in a jar of alcohol might sell well.'],
      ['해설', 'Rumors spread that the nose took walks on Nevsky Avenue. Crowds of people gathered to see it.'],
      ['해설', 'Then, on the morning of the seventh of April, he woke up and found his nose back in place.'],
      ['코발료프', 'Ha ha, my nose! Ivan Yakovlevich, come and shave me. And be careful near the nose!'],
      ['해설', 'How could such a thing happen? Even the storyteller does not know. He only says it happens, though rarely.'],
      ['해설', 'Gogol’s The Nose appeared in 1836 in The Contemporary, a magazine edited by Pushkin.'],
    ],
  },

  'ws6-oysters': {
    title: 'Oysters',
    names: { 해설: 'Narrator', 소년: 'Boy', 아버지: 'Father', 신사: 'Gentleman' },
    outro: [
      'What did Chekhov want to show through the gentlemen who laugh at the boy eating oysters?',
      'In the hungry boy’s mind, the oyster keeps changing shape. What effect does this create?',
      'How can a poor person’s situation become a show for others today?',
    ],
    lines: [
      ['해설', 'On a rainy autumn evening, an eight-year-old boy stood with his father on a big street in Moscow.'],
      ['해설', 'His father had looked for work for five months. Today he had come out to beg for the first time.'],
      ['해설', 'He wore an old summer coat, and his rubber overshoes had holes in them.'],
      ['소년', 'Papa, I’m hungry. My legs keep giving way.'],
      ['아버지', 'Hold on a little longer. Let’s wait just a little more.'],
      ['해설', 'A restaurant sign floated before the boy’s eyes. One big word stuck in his mind. Oysters.'],
      ['소년', 'Papa, what are oysters?'],
      ['아버지', 'Oysters are animals that live in the sea.'],
      ['해설', 'At once the boy imagined something tasty, somewhere between a fish and a shrimp.'],
      ['해설', 'Just thinking of it made his mouth water. He seemed to smell a rich fish soup.'],
      ['소년', 'Are they good to eat?'],
      ['아버지', 'People eat them alive. They live inside a hard shell, like a turtle’s. A shell in two halves.'],
      ['해설', 'The tasty picture fell apart. He imagined something like a frog in a shell, with shining eyes.'],
      ['소년', 'They eat live things, shell and all? Do they have claws? That’s scary.'],
      ['해설', 'It was disgusting. And yet the boy’s mouth was moving by itself, as if chewing something.'],
      ['해설', 'He was so hungry. In his mind, he was gulping down the oysters, shells, frogs, and all.'],
      ['소년', 'Give me oysters! Give me some oysters!'],
      ['아버지', 'Stop it, son! Gentlemen, I’m so ashamed. The child is hungry.'],
      ['해설', 'Two passing gentlemen stopped and looked closely at the boy.'],
      ['신사', 'He wants to eat oysters? This little one? Ha ha, how funny. Let’s watch him eat.'],
      ['해설', 'The gentlemen took the boy into a warm restaurant. People stood around him and laughed.'],
      ['해설', 'He shut his eyes tight and swallowed something salty and slimy. It smelled damp.'],
      ['신사', 'Are you going to chew the shell too? That’s not for eating, you silly boy!'],
      ['해설', 'With the shell between his teeth, the boy heard the laughter. He remembered nothing after that.'],
      ['해설', 'When he woke up, he was lying in bed at home. His mouth tasted bitter, and his body burned with fever.'],
      ['아버지', 'I’m a fool. A real fool. I can’t even beg properly.'],
      ['해설', 'His father paced the room, waving his hands. The boy listened and thought.'],
      ['소년', 'Do oysters really have claws?'],
      ['해설', 'Anton Chekhov published the short story Oysters in 1884.'],
    ],
  },

  'ws6-pierrot': {
    title: 'Pierrot',
    names: { 해설: 'Narrator', 르페브르: 'Madame Lefèvre', 로즈: 'Rose', 일꾼: 'Worker' },
    outro: [
      'What finally made Madame Lefèvre give up on Pierrot?',
      'At the end, she eats the leftover bread on her way home. What does this tell us about her?',
      'Do people today still measure the value of a life only by money and usefulness?',
    ],
    lines: [
      ['해설', 'Madame Lefèvre was a widow in the Normandy countryside. She was one of the stingiest people in the village.'],
      ['해설', 'One night, a dozen onions disappeared from her vegetable garden.'],
      ['르페브르', 'Thief! Rose, come here! Someone climbed the wall and stole my onions!'],
      ['로즈', 'Madame, why don’t you get a dog? Just its barking would keep thieves away.'],
      ['르페브르', 'A big dog eats too much. I might think about a little one that just barks.'],
      ['해설', 'The baker next door gave them a little yellow puppy with short legs for free.'],
      ['해설', 'The two women named the puppy Pierrot.'],
      ['로즈', 'Pierrot, come here. Bark! When a thief comes, you bark loudly like this.'],
      ['해설', 'But Pierrot did not bark. At night, he curled up and slept quietly.'],
      ['르페브르', 'This little thing only knows how to wag its tail. It isn’t worth its food.'],
      ['해설', 'Then they heard that dog owners had to pay a tax. It was eight francs a year.'],
      ['르페브르', 'Eight francs! Eight francs for a dog that doesn’t even bark! I must get rid of it.'],
      ['해설', 'Nobody wanted to take the dog. So she decided to throw Pierrot into the pit.'],
      ['해설', 'In the middle of the fields, there was a deep old pit where people had dug marl. People threw dogs there.'],
      ['해설', 'One night, the two women wrapped Pierrot in an apron and carried him to the pit.'],
      ['해설', 'When they held him over the hole, Pierrot wagged his tail, not knowing anything.'],
      ['해설', 'Madame let go. There was the sound of something falling, and a thin cry rose from under the ground.'],
      ['해설', 'That night, the cry kept ringing in her ears, and she could not sleep.'],
      ['해설', 'The next morning, she went to the pit worker and asked him to bring the dog out.'],
      ['일꾼', 'Give me four francs, and I’ll get him out for you.'],
      ['르페브르', 'Four francs? Are you mad? Four francs to bring out a dog I threw away?'],
      ['해설', 'In the end, she decided to bring bread every day and throw it into the pit.'],
      ['로즈', 'Pierrot! Pierrot! Here’s your bread!'],
      ['해설', 'But the next day, they heard two dogs in the pit. Someone had thrown in a big dog too.'],
      ['해설', 'Each time they threw bread, the big dog jumped on it and ate it all. Pierrot’s cries grew weaker.'],
      ['르페브르', 'I can’t feed that big dog as well. Let’s go, Rose.'],
      ['해설', 'Madame took the leftover bread and turned back. As she walked, she nibbled on it little by little.'],
      ['해설', 'From the pit, no more sounds came.'],
      ['해설', 'Guy de Maupassant published the short story Pierrot in 1882.'],
    ],
  },

  'ws6-crainquebille': {
    title: 'Crainquebille',
    names: { 해설: 'Narrator', 크랭크빌: 'Crainquebille', 바야르: 'Madame Bayard', 순경: 'Policeman', 판사: 'Judge' },
    outro: [
      'Through Crainquebille’s fall, what side of law and power did Anatole France criticize?',
      'At the end, his shout to get sent back to prison is ignored. Why does that feel even lonelier?',
      'What should a society do so that the words of powerless people are not ignored?',
    ],
    lines: [
      ['해설', 'For half a century, Crainquebille had pushed his vegetable cart through the streets of Montmartre in Paris.'],
      ['해설', 'He could not read, but he was honest. He called out cabbages, carrots, and leeks, and lived quietly.'],
      ['크랭크빌', 'Cabbages! Turnips! Carrots too!'],
      ['해설', 'One day, Madame Bayard, the shoemaker’s wife, picked out a bunch of leeks.'],
      ['바야르', 'Fourteen sous? A bit expensive, but fine. I’ll just go into the shop for the money.'],
      ['해설', 'Crainquebille stopped his cart and waited. Then Policeman Number 64 came up.'],
      ['순경', 'You there with the cart, don’t stop. Move along!'],
      ['크랭크빌', 'I have to get my money. As soon as I get fourteen sous, I’ll go.'],
      ['순경', 'I don’t care. When I say move, you move. Now!'],
      ['해설', 'Carriages and carts piled up behind him, and the drivers cursed. He did not know what to do.'],
      ['크랭크빌', 'What about my fourteen sous? I need to get them... Oh, for goodness’ sake!'],
      ['순경', 'Did you just say death to the cops? That’s insulting an officer. Come with me!'],
      ['해설', 'Crainquebille had not said that. But the policeman believed he had heard it.'],
      ['해설', 'A passing doctor named Matthieu said the old man had not said it. But it was no use.'],
      ['해설', 'Crainquebille was dragged to the police station, leaving his cart in the street.'],
      ['해설', 'At the trial, the judge believed the policeman, because a policeman stood for the power of the state.'],
      ['판사', 'I have heard the witness. But an officer’s word weighs more. Fifteen days in jail and a fifty-franc fine.'],
      ['크랭크빌', 'I didn’t say that... I don’t understand what happened.'],
      ['해설', 'The prison was surprisingly clean and quiet. Crainquebille even felt rather comfortable there.'],
      ['해설', 'The trouble came after he was set free. His old customers avoided him because he had been in prison.'],
      ['바야르', 'Fourteen sous? I don’t know anything about that. I buy nothing from a jailbird.'],
      ['크랭크빌', 'You nasty woman! Give me my fourteen sous!'],
      ['해설', 'He grew rough and began to drink. His cart grew emptier, and winter came.'],
      ['해설', 'On a night of pouring rain, hungry and tired, he remembered the warm bed in prison.'],
      ['크랭크빌', 'In prison there’s food and a roof. Yes, I just need to say those words.'],
      ['해설', 'He went up to a policeman under a streetlight and shouted in a hoarse voice. Death to the cops!'],
      ['순경', 'You shouldn’t say that, old man. Not at your age. Go on home.'],
      ['해설', 'The policeman did not arrest him. Crainquebille hung his head and walked into the rainy dark.'],
      ['해설', 'A court that did not believe the powerless, and poverty, followed him to the very end.'],
      ['해설', 'Anatole France published Crainquebille in 1901. He won the Nobel Prize in Literature in 1921.'],
    ],
  },

  'ws6-christmas-rose': {
    title: 'The Legend of the Christmas Rose',
    names: { 해설: 'Narrator', 수사: 'Lay Brother', 강도아내: 'Robber’s Wife', 원장: 'Abbot Hans', 대주교: 'Archbishop Absalon', 아이: 'Child' },
    outro: [
      'Why did Abbot Hans try to bring back the miracle flower for the sake of a robber?',
      'The miracle disappears at one doubting shout from the lay brother. What does this scene say?',
      'What would it take to give a second chance to someone the world has thrown away?',
    ],
    lines: [
      ['해설', 'A robber’s family lived in a cave in Göinge Forest in southern Sweden. The father was an outlaw.'],
      ['해설', 'One day, the robber’s wife came begging to Övid Cloister with her children.'],
      ['해설', 'She marched into a garden whose gate was open. It was Abbot Hans’s beloved herb garden.'],
      ['수사', 'Get out! This is a holy cloister. It is no place for a band of robbers!'],
      ['강도아내', 'You call this a great garden? It’s nothing compared to our forest, which blooms every Christmas night.'],
      ['해설', 'Abbot Hans came out at the noise, and his eyes lit up at her words.'],
      ['원장', 'I have heard that the forest becomes a garden every Christmas night. Is it true?'],
      ['강도아내', 'Of course it is. If you come alone, I will send a child to show you the way.'],
      ['해설', 'The abbot went to Archbishop Absalon and asked him to pardon the robber in the forest.'],
      ['대주교', 'He is a sinner. But if you bring me a flower from that forest, I will write him a letter of pardon.'],
      ['해설', 'On Christmas Eve, the abbot took the lay brother who kept the garden and went into the snowy forest.'],
      ['아이', 'This way. Mother said the forest will wake up tonight.'],
      ['해설', 'The robber in the cave greeted them roughly. But the abbot did not mind and sat by the fire.'],
      ['해설', 'Near midnight, Christmas bells rang far away. At that moment, the forest grew bright.'],
      ['해설', 'The snow melted, and grass came up. Flowers bloomed on every tree, and birds sang and built nests.'],
      ['해설', 'Bears and foxes walked about gently, and angels seemed to come down from the sky.'],
      ['원장', 'Thank you, Lord. I have seen this miracle.'],
      ['해설', 'But the lay brother could not believe any of it. To him, it all looked like the devil’s trick.'],
      ['수사', 'This is no holy miracle. It is the work of the devil! Go away!'],
      ['해설', 'With that shout, the light went out. Flowers, birds, and angels vanished, and snow covered the forest again.'],
      ['해설', 'The abbot reached out to catch a flower. Then he fell on the snow and died.'],
      ['해설', 'When they carried him back to the cloister, he was holding a few muddy roots tightly in his hand.'],
      ['해설', 'The lay brother planted the roots in the abbot’s garden and cared for them for a year. No flowers came.'],
      ['해설', 'The next Christmas Eve, the roots sent up stems through the snow and opened silvery white flowers.'],
      ['수사', 'Father Abbot, I was wrong to doubt. Your flowers have bloomed.'],
      ['해설', 'The lay brother took the flowers to the archbishop.'],
      ['대주교', 'Abbot Hans kept his promise. I will keep mine too.'],
      ['해설', 'The lay brother brought the letter of pardon to the robber. Then he stayed in that cave and lived as a hermit.'],
      ['해설', 'People called the flower that blooms in the snow of midwinter the Christmas rose.'],
      ['해설', 'In 1909, Selma Lagerlöf became the first woman to win the Nobel Prize in Literature.'],
    ],
  },
};
