// 청소년 영어 원고 (중학생 이상). 문장은 자체 각색, 원작이 영어인 작품은 원작의 이름과 핵심 표현을 살림.
// 키 = stories/teen-c.js 의 이야기 id. lines 의 첫 칸은 원래 이야기 cast 의 한국어 이름 그대로.
export default {
  'tc-chameleon': {
    title: 'The Chameleon',
    names: { 해설: 'Narrator', 서장: 'Ochumelov', 순경: 'Yeldyrin', 흐류킨: 'Khryukin', 프로호르: 'Prokhor', 구경꾼: 'Onlooker' },
    outro: [
      'What was Chekhov criticizing through an officer who changes his mind depending on the dog’s owner?',
      'How do the coat and the title, The Chameleon, add to the satire?',
      'Do people today still judge others differently because of their status or background?',
    ],
    lines: [
      ['해설', 'Police Inspector Ochumelov crossed the market square in a new overcoat.'],
      ['해설', 'A policeman followed him, carrying a basket of berries they had taken from someone.'],
      ['해설', 'The square was quiet. Then someone shouted. It bit me! Don’t let it go!'],
      ['해설', 'A crowd gathered by a woodshed. In the middle stood Khryukin, the goldsmith, holding up a bleeding finger.'],
      ['해설', 'At his feet, a small white puppy was shaking with fear.'],
      ['서장', 'What is going on here? Why is everyone standing around? And what happened to your finger?'],
      ['흐류킨', 'Sir, I was just walking along, and this dog bit my finger. I need this hand for my work!'],
      ['서장', 'I will not let this go. Dog owners must learn a lesson. Whose dog is this?'],
      ['구경꾼', 'I think it belongs to General Zhigalov.'],
      ['서장', 'The general’s? Hmm. Yeldyrin, take my coat off. It’s terribly hot today.'],
      ['서장', 'But how could such a tiny dog reach your finger? Maybe you cut it on a nail and blamed the dog.'],
      ['구경꾼', 'He poked the dog’s nose with his cigarette for fun. The dog isn’t stupid, so it bit him.'],
      ['흐류킨', 'That’s a lie! My brother is a policeman. The law is the same for everyone!'],
      ['순경', 'No, sir, this isn’t the general’s dog. The general only keeps fine hunting dogs.'],
      ['서장', 'You’re right. Look at this ugly little mutt. The general would never keep it. Get rid of it!'],
      ['순경', 'But wait. It might be the general’s dog after all. I saw one like it in his yard.'],
      ['서장', 'Yeldyrin, put my coat back on. There’s a cold wind. Take this dog to the general’s house.'],
      ['서장', 'And you, Khryukin, don’t go poking your finger at things. You could hurt a valuable dog.'],
      ['해설', 'Just then, the general’s cook, Prokhor, walked by. The crowd called him over.'],
      ['서장', 'Prokhor, is this your master’s dog?'],
      ['프로호르', 'I’ve never seen it before. We don’t have a dog like this.'],
      ['서장', 'Then it’s settled. It’s a stray. We can get rid of strays.'],
      ['프로호르', 'Oh, wait! This belongs to the general’s brother, Vladimir Ivanovich. He arrived a few days ago. He loves hunting dogs.'],
      ['서장', 'His brother is here? I haven’t seen him for ages! So it’s his dog. What a clever little fellow!'],
      ['서장', 'He bit this man’s finger? Ha ha! Good boy. You were angry, weren’t you?'],
      ['해설', 'Prokhor called the dog and took it away. The crowd laughed at Khryukin.'],
      ['서장', 'I’ll deal with you later, Khryukin!'],
      ['해설', 'Ochumelov pulled his coat tight and walked on across the market square.'],
      ['해설', 'Anton Chekhov published The Chameleon in 1884.'],
    ],
  },

  'tc-clerk-death': {
    title: 'The Death of a Government Clerk',
    names: { 해설: 'Narrator', 체르뱌코프: 'Chervyakov', 장군: 'General Brizzhalov', 아내: 'Wife' },
    outro: [
      'What kind of society was Chekhov showing through a clerk destroyed by a single sneeze?',
      'How does the exaggerated story make us laugh and feel bitter at the same time?',
      'Have you ever worried too much about what someone above you thought? How do you see it now?',
    ],
    lines: [
      ['해설', 'One fine evening, a minor clerk named Ivan Dmitritch Chervyakov sat in the second row of the theater.'],
      ['해설', 'He watched the opera through his opera glasses and felt perfectly happy.'],
      ['해설', 'Suddenly his face twisted, his eyes narrowed, and his breath stopped. Achoo! He sneezed.'],
      ['해설', 'Sneezing is not forbidden to anyone, so he simply wiped his nose with his handkerchief.'],
      ['해설', 'But the old man in front of him was rubbing his bald head and neck with his glove and muttering.'],
      ['해설', 'Chervyakov saw that the man was General Brizzhalov, a high official in the Ministry of Transport.'],
      ['체르뱌코프', 'I sprayed the general! He isn’t my boss, but still, this is awful. I must apologize.'],
      ['체르뱌코프', 'Excuse me, Your Excellency. I sneezed on you. I didn’t mean to.'],
      ['장군', 'It’s nothing, it’s nothing.'],
      ['체르뱌코프', 'Please forgive me. I really didn’t mean to do it.'],
      ['장군', 'Oh, sit down, please! Let me watch the opera.'],
      ['해설', 'Chervyakov smiled foolishly and looked at the stage, but he was no longer happy. Worry ate at him.'],
      ['해설', 'During the break, he went up to the general and nervously began again.'],
      ['체르뱌코프', 'Your Excellency, I sprayed you. Please forgive me. I only...'],
      ['장군', 'Oh, enough! I have already forgotten it, and you keep talking about it!'],
      ['체르뱌코프', 'He says he forgot, but his eyes are so angry. I must explain properly.'],
      ['해설', 'At home, he told his wife what had happened. She was scared at first. But she relaxed when she heard the general worked in another department.'],
      ['아내', 'Still, go and apologize. He may think you don’t know how to behave in public.'],
      ['해설', 'The next day, Chervyakov put on his new uniform, had his hair cut, and went to see the general.'],
      ['체르뱌코프', 'Your Excellency, last night at the theater I sneezed and sprayed you. Please...'],
      ['장군', 'What nonsense! Next! What can I do for you?'],
      ['체르뱌코프', 'He won’t even speak to me. He must be very angry. I can’t leave it like this.'],
      ['해설', 'When the general finished with the last visitor, Chervyakov followed him and began again.'],
      ['체르뱌코프', 'Your Excellency, I dare to trouble you again. I wasn’t laughing at you. I am truly sorry...'],
      ['장군', 'Are you making fun of me?'],
      ['해설', 'The general shut the door. Making fun? Chervyakov had no idea what he meant.'],
      ['해설', 'The next day he went back once more. He only wanted to say he hadn’t been making fun of him.'],
      ['체르뱌코프', 'Your Excellency, yesterday I didn’t come to make fun of you. I came to apologize for sneezing...'],
      ['장군', 'Get out!'],
      ['해설', 'The general’s face turned blue, and he stamped his feet. Something seemed to snap inside Chervyakov.'],
      ['해설', 'Seeing nothing and hearing nothing, he stumbled out into the street and dragged himself home.'],
      ['해설', 'Without taking off his uniform, he lay down on the sofa, and he died.'],
      ['해설', 'Chekhov published The Death of a Government Clerk in 1883, early in his career.'],
    ],
  },

  'tc-bet': {
    title: 'The Bet',
    names: { 해설: 'Narrator', 은행가: 'Banker', 법률가: 'Lawyer', 손님: 'Guest', 경비원: 'Watchman' },
    outro: [
      'Why do you think the lawyer gave up the two million rubles after fifteen years of reading?',
      'What does the banker’s turning away in tears reveal about him?',
      'Among money, freedom, and knowledge, which would be hardest for you to give up, and why?',
    ],
    lines: [
      ['해설', 'On a dark autumn night, an old banker paced his study. He was remembering a party from fifteen years ago.'],
      ['해설', 'That night, the guests argued about which was more humane, the death penalty or life in prison.'],
      ['손님', 'The death penalty is wrong. Not even the state may take a life it cannot give back.'],
      ['은행가', 'I disagree. Execution kills you at once. Life in prison kills you slowly. Which is crueler?'],
      ['법률가', 'Both are wrong. But if I had to choose, I’d choose prison. Living somehow is better than not living at all.'],
      ['은행가', 'Nonsense! I’ll bet two million rubles you couldn’t last five years alone in a cell.'],
      ['법률가', 'If you mean it, I’ll stay not five years, but fifteen.'],
      ['해설', 'So the young lawyer, only twenty-five, was locked in a small lodge in the banker’s garden. He could see or hear no one.'],
      ['해설', 'He could ask for books, music, and wine by note, through a small window. If he left even once, he lost.'],
      ['해설', 'In the first year, he was lonely and sad. He played the piano and read light novels. He refused wine and tobacco.'],
      ['해설', 'In the second year, the piano went silent, and he read the classics. Later he studied languages, philosophy, and history.'],
      ['해설', 'In four years, he read about six hundred books. In the tenth year, he read only the Gospels. Then religion, science, and poetry.'],
      ['해설', 'Meanwhile, the banker lost most of his money on risky deals. Paying two million rubles would ruin him.'],
      ['은행가', 'Tomorrow at noon, he will be free, and I will be a beggar. Only his death can save me.'],
      ['해설', 'At three in the morning, he took the key and walked through the wind and rain. The watchman was asleep somewhere.'],
      ['해설', 'Through the window, he saw the lawyer, as thin as a skeleton, asleep at the table. A letter lay before him.'],
      ['해설', 'The banker went in and picked up the letter.'],
      ['법률가', 'Tomorrow at twelve, I will be free. But before I leave this room, I want to say a few words.'],
      ['법률가', 'For fifteen years, in my books, I loved, climbed mountains, built cities, and destroyed kingdoms.'],
      ['법률가', 'With the wisdom I gained, I see that your wealth and worldly happiness are only a mirage.'],
      ['법률가', 'So I give up the two million I once dreamed of like heaven. I will leave five hours early and break the bet.'],
      ['해설', 'The banker put down the letter and kissed the sleeping man’s head. Then he left the lodge in tears.'],
      ['해설', 'Even after his worst losses on the stock market, he had never despised himself so much.'],
      ['해설', 'At home he lay in bed, but tears and excitement kept him awake for a long time.'],
      ['경비원', 'Sir, the man in the lodge climbed out the window, went through the garden gate, and disappeared.'],
      ['해설', 'The banker went with his servants and saw that the prisoner was really gone.'],
      ['해설', 'To stop any gossip, he took the letter from the table and locked it in his safe.'],
      ['해설', 'Chekhov published The Bet in 1889.'],
    ],
  },

  'tc-necklace': {
    title: 'The Necklace',
    names: { 해설: 'Narrator', 마틸드: 'Mathilde', 루아젤: 'Monsieur Loisel', 포레스티에: 'Madame Forestier' },
    outro: [
      'What did Maupassant want to say about vanity and pride through Mathilde’s ten years?',
      'How does the final twist, that the necklace was fake, change how we see Mathilde’s sacrifice?',
      'Have you ever pushed yourself too hard to look good to others? What did you really want?',
    ],
    lines: [
      ['해설', 'Mathilde was a beautiful woman. But she was born poor and married a minor clerk at the Ministry of Education.'],
      ['해설', 'She believed she was born for luxury. Her shabby home and worn chairs made her miserable.'],
      ['해설', 'One evening, her husband, Loisel, proudly handed her an envelope. It was an invitation to the Minister’s ball.'],
      ['루아젤', 'I thought you’d be pleased. It was hard to get. All the important people will be there.'],
      ['마틸드', 'What am I supposed to do with this? I have nothing to wear.'],
      ['해설', 'Loisel gave her the four hundred francs he had saved for a hunting gun. She had a dress made.'],
      ['마틸드', 'I don’t have a single jewel. I’d rather not go than look poor.'],
      ['루아젤', 'Ask your friend Madame Forestier to lend you something. You’re close enough for that.'],
      ['해설', 'Madame Forestier opened her jewel box. In a black satin case, Mathilde found a diamond necklace, and her heart raced.'],
      ['마틸드', 'Could you lend me this? Only this?'],
      ['포레스티에', 'Of course.'],
      ['해설', 'At the ball, Mathilde shone brighter than anyone. Men wanted to dance with her, and even the Minister noticed her.'],
      ['해설', 'At four in the morning, she stood before the mirror at home and screamed. The necklace was gone.'],
      ['해설', 'Loisel retraced their steps and went to the police and the newspapers. But the necklace was nowhere.'],
      ['루아젤', 'Write to your friend that the clasp broke and it’s being fixed. We need time.'],
      ['해설', 'At a jeweler’s in the Palais-Royal, they found a necklace that looked the same. They bought it for thirty-six thousand francs.'],
      ['해설', 'Loisel used the eighteen thousand francs his father had left him. He borrowed the rest and signed dangerous promises.'],
      ['해설', 'When Madame Forestier got the necklace back, she did not even open the case. She only said it was late.'],
      ['해설', 'Then they learned the horror of poverty. They sent away their maid and moved into an attic.'],
      ['해설', 'Mathilde washed dishes and clothes until her nails wore down. Her husband copied documents late into the night.'],
      ['해설', 'Ten years later, the debt was paid. But Mathilde had become a strong, rough woman of a poor household.'],
      ['해설', 'One Sunday on the Champs-Élysées, she met Madame Forestier, still young and beautiful.'],
      ['포레스티에', 'Mathilde? Oh my goodness, you’ve changed so much!'],
      ['마틸드', 'I’ve had hard days since I last saw you. And it was all because of you.'],
      ['마틸드', 'I lost the necklace you lent me. I bought one just like it and gave it back. It took ten years to pay for it.'],
      ['포레스티에', 'You bought a diamond necklace to replace mine?'],
      ['마틸드', 'Yes. You never noticed, did you? They were exactly alike.'],
      ['해설', 'Madame Forestier took both of Mathilde’s hands.'],
      ['포레스티에', 'Oh, my poor Mathilde! Mine was fake. It was worth five hundred francs at most!'],
      ['해설', 'Guy de Maupassant’s The Necklace first appeared in 1884 in the Paris newspaper Le Gaulois.'],
    ],
  },

  'tc-twenty-years': {
    title: 'After Twenty Years',
    names: { 해설: 'Narrator', 순경: 'Policeman', 밥: 'Bob', 형사: 'Detective' },
    outro: [
      'How does O. Henry show the conflict between friendship and duty through Jimmy’s choice?',
      'How does the twist, that the first policeman was Jimmy, change the earlier conversation?',
      'If a friend did something wrong, how could you stay loyal and still do what is right?',
    ],
    lines: [
      ['해설', 'It was just before ten at night. A policeman walked his beat along the street with an impressive step.'],
      ['해설', 'A cold wind and rain had emptied the streets. Twirling his club, he checked the doors of the shops.'],
      ['해설', 'In the doorway of a dark hardware store, a man leaned with an unlit cigar in his mouth.'],
      ['밥', 'It’s all right, officer. I’m just waiting for a friend. We made a promise twenty years ago.'],
      ['밥', 'Twenty years ago, Big Joe Brady’s restaurant stood here. I ate here with my best friend, Jimmy Wells.'],
      ['밥', 'The next day, I went West to make my fortune. Jimmy would never leave New York. So we made a promise.'],
      ['밥', 'We would meet here again, on this date and at this hour, twenty years later. No matter what, no matter how far.'],
      ['해설', 'The man lit his cigar. The match showed a pale, square face and a small white scar near his right eyebrow.'],
      ['해설', 'His scarfpin held a large diamond, and his watch sparkled with small diamonds too.'],
      ['순경', 'Did you hear from your friend after you left?'],
      ['밥', 'We wrote for a while, then lost touch. But Jimmy was the most loyal friend in the world. If he’s alive, he’ll come.'],
      ['밥', 'I did very well out West. Jimmy was a good guy but slow. He couldn’t have done as well as me.'],
      ['순경', 'I hope your friend comes. Good night.'],
      ['해설', 'About twenty minutes later, a tall man crossed the street. The collar of his long coat was turned up to his ears.'],
      ['형사', 'Is that you, Bob?'],
      ['밥', 'Jimmy Wells! You came! Twenty years is a long time. The restaurant’s gone, but here we are.'],
      ['해설', 'They walked arm in arm. Bob talked on and on about his success in the West.'],
      ['해설', 'But at a brightly lit drugstore, Bob suddenly stopped and pulled his arm away.'],
      ['밥', 'You’re not Jimmy Wells. Twenty years is long, but not long enough to change a man’s nose from Roman to pug.'],
      ['형사', 'It sometimes changes a good man into a bad one. You’ve been under arrest for ten minutes, Silky Bob.'],
      ['형사', 'Chicago police thought you might come this way. You’d better come quietly.'],
      ['형사', 'Before we go to the station, here’s a note for you. Patrolman Wells asked me to give it to you.'],
      ['해설', 'Bob opened the note. His hand was steady when he began, but it trembled a little by the end.'],
      ['순경', 'Bob, I was at the place on time. When you struck the match, I saw the face of the man wanted in Chicago.'],
      ['순경', 'Somehow I couldn’t arrest you myself. So I went and got a plainclothes man to do the job. Jimmy.'],
      ['해설', 'After Twenty Years appeared in O. Henry’s collection The Four Million in 1906.'],
    ],
  },

  'tc-cop-anthem': {
    title: 'The Cop and the Anthem',
    names: { 해설: 'Narrator', 소피: 'Soapy', 경찰: 'Policeman', 웨이터: 'Waiter', 신사: 'Gentleman', 여인: 'Young Woman' },
    outro: [
      'What was O. Henry saying through a man who gets arrested only after he gives up trying?',
      'What irony is created when Soapy is caught right after deciding to start a new life?',
      'What should our society do so that no one wishes for prison just to survive the winter?',
    ],
    lines: [
      ['해설', 'On his bench in Madison Square, Soapy felt a dead leaf fall into his lap. Winter was coming.'],
      ['해설', 'Soapy had no home. For him, the best way to spend winter was three months in the prison on Blackwell’s Island.'],
      ['소피', 'A warm bed, regular meals, and nobody to bother me. I’ll spend this winter there too.'],
      ['해설', 'First, he planned to eat a big meal at a fancy restaurant and then say he had no money.'],
      ['해설', 'But at the door, the head waiter’s eyes fell on his worn trousers and old shoes.'],
      ['웨이터', 'This is no place for someone like you. Get out.'],
      ['해설', 'Next, Soapy picked up a stone and smashed a shop window. People gathered, and a policeman ran up.'],
      ['소피', 'I did it.'],
      ['경찰', 'The man who broke it wouldn’t wait around. That man running for the streetcar is the one!'],
      ['해설', 'Then he went into a cheap restaurant, ate his fill, and admitted he didn’t have a cent.'],
      ['웨이터', 'We don’t need a cop for this. Hey, help me throw this guy out.'],
      ['해설', 'Two waiters threw him onto the sidewalk. No policeman came.'],
      ['해설', 'Next, right beside a policeman, he began to annoy a young woman looking in a shop window.'],
      ['여인', 'Oh, then will you buy me a beer? The cop’s watching, so follow me to the corner.'],
      ['해설', 'Soapy ran away in horror. Then he pretended to be drunk, shouting and singing in the street.'],
      ['경찰', 'Just college boys celebrating. We were told to leave them alone tonight.'],
      ['해설', 'Finally, in a cigar store, he took a stranger’s silk umbrella and calmly walked out. The owner hurried after him.'],
      ['소피', 'This is my umbrella. Why don’t you call a cop? There’s one right there.'],
      ['신사', 'Well, actually, I picked it up in a restaurant this morning. If it’s yours, I’m sorry.'],
      ['해설', 'Soapy threw the umbrella down and grumbled. The police seemed to treat him like a king who could do no wrong.'],
      ['해설', 'He came to an old church on a quiet street. Through the window, an organ was playing an anthem.'],
      ['해설', 'He had loved that song in the days of his mother, his friends, and clean collars. He stopped at the iron fence.'],
      ['소피', 'How did I fall so low? It’s not too late. I’ll climb out of this mud and live like a man again.'],
      ['소피', 'Tomorrow I’ll go downtown and find work. A fur importer once offered me a job as a driver.'],
      ['해설', 'Then a hand fell on his shoulder. He turned and saw the broad face of a policeman.'],
      ['경찰', 'What are you doing here, hanging around? Come along with me.'],
      ['해설', 'The next morning, the judge in the police court said, Three months on the Island.'],
      ['해설', 'The Cop and the Anthem appeared in O. Henry’s collection The Four Million in 1906.'],
    ],
  },

  'tc-red-chief': {
    title: 'The Ransom of Red Chief',
    names: { 해설: 'Narrator', 샘: 'Sam', 빌: 'Bill', 추장: 'Red Chief', 도셋: 'Ebenezer Dorset' },
    outro: [
      'What does O. Henry turn upside down in a story where the kidnappers end up paying?',
      'How do the boy’s nickname, Red Chief, and the reversed ending make us laugh?',
      'Have you seen a plan to make easy money go wrong, around you or in the news?',
    ],
    lines: [
      ['해설', 'Sam and Bill came up with a plan in a small Alabama town called Summit. They would kidnap a child for ransom.'],
      ['해설', 'They chose the ten-year-old son of a rich man, Ebenezer Dorset. He was a freckled boy with red hair.'],
      ['해설', 'They tricked the boy into their buggy with candy. On the way, he hit Bill in the eye with a brick.'],
      ['해설', 'That evening, Sam returned to their cave in the mountains. The boy had feathers in his hair and was threatening Bill.'],
      ['추장', 'I’m Red Chief! Old Hank the Trapper is my prisoner. At sunrise, I’m going to scalp him!'],
      ['빌', 'Look at him, Sam. He doesn’t want to go home at all.'],
      ['추장', 'I hate home. This is way more fun. Why do trees move? Are stars hot? Why can parrots talk but monkeys can’t?'],
      ['해설', 'The boy never stopped talking. At dawn, Sam woke up to Bill’s screams.'],
      ['빌', 'Sam! He sat on my chest and pulled my hair, saying he would scalp me!'],
      ['해설', 'Sam decided to write a ransom letter. He wanted to ask for two thousand dollars, but Bill stopped him.'],
      ['빌', 'Make it fifteen hundred. No parents would pay two thousand for a kid like that.'],
      ['해설', 'While Sam went to mail the letter, Bill had to crawl around the cave as the boy’s horse.'],
      ['추장', 'Giddy up! My horse must run fast. We have ninety miles to go before the scouts catch us!'],
      ['해설', 'When Sam returned, Bill was exhausted. He admitted he had kicked the boy toward home.'],
      ['빌', 'Sorry, Sam. I’m a strong man, but I just couldn’t take any more of him.'],
      ['해설', 'At that moment, Red Chief popped up behind Bill. Bill sank to the ground.'],
      ['해설', 'That night, Sam found Mr. Dorset’s reply under the fence post they had agreed on.'],
      ['도셋', 'Your ransom is a bit high, so I have a counter offer. Pay me two hundred and fifty dollars, and I’ll take him back.'],
      ['도셋', 'Better bring him at night. The neighbors think he is lost, and I can’t say what they’d do to anyone bringing him back.'],
      ['샘', 'What a shameless old man!'],
      ['빌', 'Sam, two hundred and fifty is cheap. Please, let’s take the offer.'],
      ['해설', 'At midnight, they brought the boy to his house. They paid Mr. Dorset two hundred and fifty dollars from Bill’s wallet.'],
      ['추장', 'No! I won’t go home! I want to keep playing with Hank!'],
      ['해설', 'The boy clung to Bill’s leg like a leech and howled. Mr. Dorset slowly pulled him off.'],
      ['빌', 'How long can you hold him?'],
      ['도셋', 'I’m not as strong as I used to be, but I think I can hold him for ten minutes.'],
      ['빌', 'That’s enough. In ten minutes, I’ll be across the state line, running for Canada.'],
      ['해설', 'It was dark, and Bill was fat. Still, Sam didn’t catch up with him until a mile and a half out of Summit.'],
      ['해설', 'O. Henry was a pen name. The writer’s real name was William Sydney Porter.'],
    ],
  },

  'tc-purloined': {
    title: 'The Purloined Letter',
    names: { 해설: 'Narrator', 뒤팽: 'Dupin', 청장: 'Prefect G', 나: 'Dupin’s Friend' },
    outro: [
      'What did Poe want to say with the idea that the most obvious place is the best hiding place?',
      'What effect comes from setting the Prefect’s careful search against Dupin’s reasoning?',
      'Have you ever tried to read someone’s mind to find an answer? How did it help?',
    ],
    lines: [
      ['해설', 'One autumn evening in Paris, I sat silently smoking with my friend Dupin in his small library.'],
      ['해설', 'Then the door opened, and Monsieur G, the Prefect of the Paris police, came in. He had a simple but very strange case.'],
      ['청장', 'A very important royal person has had a letter stolen. The thief is Minister D. He took it right in front of her.'],
      ['청장', 'He left a similar letter in its place. Another person was present, so she could only watch in silence.'],
      ['청장', 'As long as he holds the letter, he has power over her. Once he uses it, the power is gone, so he won’t.'],
      ['뒤팽', 'Then the letter must be somewhere he can reach quickly, in his own house.'],
      ['청장', 'For three months, we searched his house every night. We took apart chair legs and probed cushions with needles.'],
      ['청장', 'We turned every page of his books. We even had him robbed twice in the street to search him. Nothing!'],
      ['뒤팽', 'Then search the house again, very thoroughly.'],
      ['해설', 'A month later, the Prefect returned. Now he said he would pay fifty thousand francs to anyone who found it.'],
      ['뒤팽', 'Then write me a check for that amount. When you sign it, I’ll give you the letter.'],
      ['해설', 'The Prefect sat as if struck by lightning. Then he wrote the check, and Dupin took the letter from a drawer.'],
      ['해설', 'The Prefect checked it and rushed out without a word. I asked Dupin how he had done it.'],
      ['뒤팽', 'The police are very good in their own way. But they always assume the criminal thinks just like them.'],
      ['뒤팽', 'A boy who wins at even and odd judges how clever his opponent is. Then he follows the other boy’s thinking.'],
      ['뒤팽', 'The Minister is both a mathematician and a poet. He knew the police would search everywhere. So he didn’t hide it at all.'],
      ['뒤팽', 'Think of a game of finding names on a map. The huge names stretching across the map are the hardest to notice.'],
      ['해설', 'Dupin put on green glasses and visited the Minister. He acted bored while his eyes searched the room.'],
      ['뒤팽', 'A cheap card rack hung over the fireplace. In it was a crumpled, dirty letter.'],
      ['뒤팽', 'The seal and handwriting were different. But it looked too carelessly handled, and it had been folded inside out.'],
      ['해설', 'Dupin left his snuffbox there on purpose. The next day, he returned to get it.'],
      ['뒤팽', 'Then a gunshot and screams came from outside. While the Minister ran to the window, I swapped the letter for a fake.'],
      ['나', 'Did you arrange that gunshot?'],
      ['뒤팽', 'I paid a man to do it. The Minister still thinks he has the letter, and he will try to use it.'],
      ['뒤팽', 'Then he will ruin himself. Inside the fake, I wrote a few lines of verse in my own handwriting, which he knows.'],
      ['뒤팽', 'Once in Vienna, he did me a bad turn. He will surely wonder who has paid him back.'],
      ['해설', 'The Purloined Letter is the last of Edgar Allan Poe’s three stories about the detective Dupin.'],
    ],
  },

  'tc-tell-tale': {
    title: 'The Tell-Tale Heart',
    names: { 해설: 'Narrator', 나: 'The Storyteller', 노인: 'Old Man', 경관: 'Officer' },
    outro: [
      'What was Poe trying to show through a narrator who confesses even though he would never be caught?',
      'What tension and distrust does a first-person narrator who keeps saying he is not mad create?',
      'Have you ever seen guilt or anxiety show on the outside, in yourself or in a story?',
    ],
    lines: [
      ['해설', 'This is the story of a man who insists that he is not mad.'],
      ['나', 'True! I was nervous, very nervous, and I still am. But why do you say that I am mad?'],
      ['나', 'My illness only made my senses sharper. Listen! See how calmly I can tell you the whole story.'],
      ['해설', 'He lived with an old man. The old man had never wronged him or insulted him. He did not want his money.'],
      ['나', 'It was his eye! A pale blue eye with a film over it, like a vulture’s. Whenever it looked at me, my blood ran cold.'],
      ['해설', 'So he decided to be rid of that eye forever. The idea haunted him day and night.'],
      ['나', 'That whole week, I was kinder to the old man than ever. And every night at midnight, I opened his door very slowly.'],
      ['나', 'It took me an hour to put my head inside. Then I opened my lantern a tiny crack and shone it on the eye.'],
      ['해설', 'For seven nights, the eye was always closed. He hated the eye, not the man, so he could not act.'],
      ['해설', 'On the eighth night, his thumb slipped on the lantern’s metal latch. The old man sat up in bed.'],
      ['노인', 'Who’s there?'],
      ['해설', 'He did not move for a whole hour. The old man did not lie down either. He sat listening in the dark.'],
      ['해설', 'Then he heard a low groan. It was the sound of deep terror rising from the old man’s soul.'],
      ['나', 'I opened the lantern a little. A thin ray of light fell straight on the vulture eye. It was wide open.'],
      ['나', 'Then I heard a low, dull, quick sound, like a watch wrapped in cotton. It was the old man’s heart.'],
      ['나', 'It beat faster and louder. I feared the neighbors would hear. With a loud yell, I rushed into the room.'],
      ['해설', 'The old man screamed only once. Before the night was over, his heart had stopped beating.'],
      ['해설', 'He lifted three boards from the floor and hid everything beneath them. He left no trace at all.'],
      ['해설', 'At four in the morning, someone knocked. A neighbor had heard a scream, and three police officers had come.'],
      ['경관', 'Someone reported a scream from this house during the night. May we look around?'],
      ['나', 'That scream was mine, in a dream. The old man is away in the country. Please, search all you like.'],
      ['해설', 'Proudly, he led them to the old man’s room. He brought chairs and had them sit right over the spot.'],
      ['해설', 'The officers chatted happily. But then a sound began ringing in his ears.'],
      ['나', 'A low, dull, quick sound, like a watch wrapped in cotton. Why do they pretend not to hear it?'],
      ['해설', 'He talked louder, paced the floor, and dragged his chair. But the sound grew louder, and louder, and louder.'],
      ['나', 'They know! They are mocking my terror! I cannot bear their false smiles any longer!'],
      ['나', 'Villains! Pretend no more! I admit the deed! Tear up the planks! Here, here! It is the beating of his hideous heart!'],
      ['해설', 'Edgar Allan Poe published The Tell-Tale Heart in 1843.'],
    ],
  },

  'tc-how-much-land': {
    title: 'How Much Land Does a Man Need?',
    names: { 해설: 'Narrator', 파홈: 'Pahom', 악마: 'The Devil', 촌장: 'Bashkir Chief', 아내: 'Pahom’s Wife' },
    outro: [
      'What answer does Tolstoy give to the title’s question in the ending?',
      'What might the Devil overhearing Pahom and the race until sunset each symbolize?',
      'Have you ever felt that just a little more would make you happy? How much is enough?',
    ],
    lines: [
      ['해설', 'An older sister from the city visited her younger sister in the country. She bragged about how wonderful city life was.'],
      ['아내', 'Our life may be simple, but we have no worries. In the city, you can get rich fast, but you can lose everything fast too.'],
      ['해설', 'Her husband, Pahom, lay on top of the stove, listening to the sisters talk.'],
      ['파홈', 'We peasants work the land from childhood, so we have no time for foolish ideas. The only trouble is, we don’t have enough land.'],
      ['파홈', 'If I had plenty of land, I wouldn’t fear even the Devil himself.'],
      ['해설', 'The Devil, hiding behind the stove, heard this. He was pleased.'],
      ['악마', 'Very well. I will give you plenty of land. And through that land, I will get you.'],
      ['해설', 'Pahom bought land from a neighboring landowner. At first, his heart swelled every time he looked at his fields.'],
      ['해설', 'But soon he was always quarreling with neighbors over their cattle and taking them to court. He never had peace.'],
      ['해설', 'He heard of more land beyond the Volga and moved there. His land grew many times larger, but it still wasn’t enough.'],
      ['해설', 'One day, a passing merchant told him about the Bashkirs far away. Their land was rich, and they sold it very cheaply.'],
      ['해설', 'Pahom took many gifts and went to the Bashkirs. They welcomed him kindly.'],
      ['촌장', 'Our price is one thousand rubles a day. All the land you walk around in one day will be yours.'],
      ['촌장', 'But you must return to your starting point before sunset. If you don’t, you lose your money.'],
      ['해설', 'That night, Pahom had a dream. The chief was laughing and holding his belly. Then he saw it was the Devil.'],
      ['해설', 'In front of the Devil lay a barefoot man in his underclothes. Looking closer, Pahom saw it was himself.'],
      ['해설', 'At dawn, Pahom set off from the hill where the chief had placed his cap. He dug holes with a spade to mark his way.'],
      ['파홈', 'That low ground over there would grow good crops. It would be a shame to lose it. Just a little farther.'],
      ['해설', 'Whenever he saw good land, he went a little farther, and then farther still. Soon the sun was past noon.'],
      ['파홈', 'I’ve made the circle too big. I must go straight back now. If I’m late, everything is lost.'],
      ['해설', 'He threw away his coat, his boots, and his water flask, and ran. His chest heaved like a blacksmith’s bellows.'],
      ['파홈', 'I wanted too much. But if I stop now, they’ll call me a fool.'],
      ['해설', 'Just as the sun touched the horizon, he crawled up the hill and fell forward, reaching for the cap.'],
      ['촌장', 'Well done! You have won much land!'],
      ['해설', 'His servant tried to lift him, but blood was flowing from his mouth. Pahom was dead.'],
      ['해설', 'The Bashkirs clicked their tongues in pity.'],
      ['해설', 'His servant took the spade and dug a grave. Six feet from head to heel was all the land he needed.'],
      ['해설', 'Leo Tolstoy published this story in 1886. He wrote it in the style of a folk tale.'],
    ],
  },

  'tc-metamorphosis-1': {
    title: 'The Metamorphosis, Part 1',
    names: { 해설: 'Narrator', 그레고르: 'Gregor', 어머니: 'Mother', 아버지: 'Father', 그레테: 'Grete', 지배인: 'Chief Clerk' },
    outro: [
      'What does it tell us that Gregor worries about work and debt before his own body?',
      'How does Kafka’s refusal to explain the change make the story stranger and more powerful?',
      'Have you ever felt people judged your worth by usefulness or grades? How did it feel?',
    ],
    lines: [
      ['해설', 'One morning, Gregor Samsa woke from troubled dreams and found himself changed into a huge insect in his bed.'],
      ['해설', 'He lay on his hard, armor-like back. When he lifted his head, he saw his brown belly and thin legs waving helplessly.'],
      ['그레고르', 'What’s happened to me? It isn’t a dream. This is my room, a little small, but a normal human room.'],
      ['해설', 'He was a traveling salesman who carried cloth samples. Outside, rain was tapping on the window.'],
      ['그레고르', 'Maybe I should sleep a little more and forget this nonsense. Oh, why did I choose such a hard job? Trains every day, strangers every day.'],
      ['그레고르', 'If it weren’t for my parents’ debt, I’d have quit long ago. Five or six more years, and I can pay it off.'],
      ['해설', 'He looked at the clock and was shocked. It was past six thirty. The five o’clock train was gone, and the next left at seven.'],
      ['어머니', 'Gregor, it’s a quarter to seven. Don’t you have a train to catch?'],
      ['그레고르', 'Yes, yes. Thank you, Mother. I’m getting up now.'],
      ['해설', 'His voice had a painful squeak mixed in it. Soon his father and his sister, Grete, were knocking too.'],
      ['그레테', 'Gregor, are you sick? Do you need anything?'],
      ['해설', 'He tried to get out of bed, but his many legs moved on their own. He rocked his body and fell to the floor.'],
      ['해설', 'Just after seven, the doorbell rang. The chief clerk from his company had come in person.'],
      ['그레고르', 'What a company, suspecting you after one small delay. The chief clerk himself has come. How awful.'],
      ['어머니', 'Sir, my son must be ill. He would never miss a train otherwise. He thinks about work even in the evenings.'],
      ['지배인', 'Mr. Samsa, what is going on? You lock yourself in, worry your parents, and neglect your work.'],
      ['지배인', 'Do you know your sales have been very poor lately? The boss even mentioned the money you collect.'],
      ['그레고르', 'Sir, wait a moment! I just felt a little dizzy. I’ll open the door soon and take the eight o’clock train.'],
      ['지배인', 'Did you hear that? That was not a human voice.'],
      ['어머니', 'Grete, go get the doctor! Gregor is very sick!'],
      ['해설', 'Gregor leaned on the wardrobe and stood up. He gripped the key with his toothless jaws and turned it with all his strength. Click!'],
      ['해설', 'Seeing him at the door, the chief clerk covered his mouth and backed away. His mother sank to the floor.'],
      ['해설', 'His father clenched his fist, then burst into tears.'],
      ['그레고르', 'I’ll get dressed and pack my samples right away. Sir, please speak well of me to the boss. I want to work.'],
      ['해설', 'But the chief clerk did not listen to a word and fled toward the stairs. Gregor crawled after him.'],
      ['해설', 'Then his father grabbed the cane and newspaper the chief clerk had left. Stamping his feet, he drove Gregor back toward his room.'],
      ['아버지', 'Shoo! Shoo! Get in! Get back in there!'],
      ['해설', 'Gregor got stuck in the narrow doorway and hurt his side. His father pushed hard, and he tumbled into the room.'],
      ['해설', 'The door was slammed shut with the cane. Then at last, everything was quiet.'],
      ['해설', 'Franz Kafka’s novella The Metamorphosis was published in 1915.'],
    ],
  },

  'tc-metamorphosis-2': {
    title: 'The Metamorphosis, Part 2',
    names: { 해설: 'Narrator', 그레고르: 'Gregor', 그레테: 'Grete', 어머니: 'Mother', 아버지: 'Father', 하숙인: 'Lodger', 할멈: 'Cleaning Woman' },
    outro: [
      'What is Kafka asking through the ending, where the family feels relieved after Gregor is gone?',
      'What does Grete’s change, from kind sister to the one who wants him gone, symbolize?',
      'How do you think families and society should treat people who are sick or seen as useless?',
    ],
    lines: [
      ['해설', 'From that day, caring for Gregor became his sister Grete’s job. Every day she brought food into his room.'],
      ['해설', 'Gregor no longer touched the milk he used to love. Instead, he happily ate old cheese and half-rotten vegetables.'],
      ['해설', 'He hid under the sofa. He even covered himself with a sheet so his sister wouldn’t be frightened.'],
      ['그레고르', 'So Father had saved some money in secret. But it won’t last us long.'],
      ['그레고르', 'I wanted to send Grete to music school next year. I was going to tell her at Christmas.'],
      ['해설', 'He began crawling over the walls and ceiling. Grete suggested taking out the furniture so he could crawl freely.'],
      ['어머니', 'If we take everything out, won’t it look like we’ve given up hope that Gregor will come back?'],
      ['해설', 'Gregor wanted to save one thing, a picture of a lady in furs. He pressed himself onto its glass. Seeing him, his mother fainted.'],
      ['해설', 'His father came home from work. Thinking Gregor had turned violent, he threw apples at him one by one.'],
      ['해설', 'One apple stuck in Gregor’s back. No one dared to remove it, and it slowly rotted there.'],
      ['해설', 'Because of the wound, Gregor could hardly move for over a month. But in the evenings, the family left his door a little open.'],
      ['해설', 'Money grew tight. His father worked as a bank messenger, his mother sewed, and Grete worked as a shop girl.'],
      ['해설', 'Grete grew careless in her care. Morning and evening, she pushed in any food with her foot and shut the door.'],
      ['해설', 'A big old cleaning woman came to work. She was not afraid of Gregor and called him an old dung beetle.'],
      ['할멈', 'Come here, you old dung beetle. Let’s have a look at you.'],
      ['해설', 'They rented a room to three bearded lodgers. All the useless things were piled into Gregor’s room.'],
      ['해설', 'One evening, Grete played the violin for the lodgers. Drawn by the music, Gregor crawled out without meaning to.'],
      ['그레고르', 'Could an animal be so moved by music? It feels like the food I’ve longed for is right here.'],
      ['하숙인', 'There’s a disgusting thing in this house! We are leaving at once, and we won’t pay a cent for our stay!'],
      ['그레테', 'Father, Mother, we can’t live like this. I won’t call that thing my brother. We have to get rid of it.'],
      ['그레테', 'If it were Gregor, he would understand that people can’t live with such a creature. He would have left on his own.'],
      ['아버지', 'If only he could understand us.'],
      ['해설', 'Gregor slowly turned and went back to his room. The door was slammed shut and locked at once.'],
      ['해설', 'In the dark, he thought of his family with tenderness and love. He believed even more firmly than his sister that he must disappear.'],
      ['해설', 'He heard the clock strike three. As the sky began to brighten outside, Gregor breathed his last.'],
      ['할멈', 'Come and look! It’s croaked! It’s dead and done for!'],
      ['해설', 'The family sent the lodgers away and took the day off. For the first time in months, they rode the streetcar to the countryside.'],
      ['어머니', 'Look at Grete, dear. After all her hardship, she has grown into such a pretty young woman.'],
      ['해설', 'When the streetcar reached the last stop, Grete stood up first and stretched her young body.'],
      ['해설', 'Her parents thought it was time to find her a good husband. They watched her like a new dream and hope.'],
      ['해설', 'Kafka asked his publisher not to draw the insect itself on the cover of The Metamorphosis.'],
    ],
  },
};
