// 청소년 영어 원고 (중학생 이상). 키 = stories/teen-sillok1.js 의 이야기 id.
// 『조선왕조실록』 이야기를 한국어 각색의 흐름대로 쉬운 영어로 새로 씀. 실록 문장을 옮기지 않고 뜻만 풀었으며,
// 인물의 대사는 지어낸 극화임을 해설이 밝힌다. 고유 낱말은 로마자로 쓰고 짧게 풀이.
export default {
  'sl-01': {
    title: 'The Retreat from Wihwado',
    names: { 해설: 'Narrator', 이성계: 'Yi Seong-gye', 조민수: 'Jo Min-su', 최영: 'Choe Yeong' },
    outro: [
      'Was turning the army back against the king’s order a choice to protect the people, or a revolt to seize power?',
      'How might records written by a new dynasty describe the end of the old one, and what should we question?',
      'When an order from above feels wrong, how can people disagree with it in today’s organizations?',
    ],
    lines: [
      ['해설', 'This story retells events from the Annals of the Joseon Dynasty and other records of late Goryeo.'],
      ['해설', 'The characters’ words are made up to match the records. They are not quotes from the records.'],
      ['해설', 'It was 1388, under King U of Goryeo. Ming China said it would take land north of Cheollyeong, and the court was in uproar.'],
      ['해설', 'General Choe Yeong wanted to attack Liaodong in return, and King U agreed.'],
      ['최영', 'If we step back, we lose our land. We must raise an army and strike Liaodong.'],
      ['해설', 'But General Yi Seong-gye opposed the war with four reasons. People call them the Four Reasons Against.'],
      ['이성계', 'First, it is not right for a small country to go against a great one.'],
      ['이성계', 'A summer war will ruin the farming. And if the country is empty, Japanese pirates will attack.'],
      ['이성계', 'Also, in the rainy season the glue on our bows will melt, and sickness will spread among the soldiers.'],
      ['해설', 'His objection was rejected. Jo Min-su led the left army and Yi Seong-gye the right, and they marched north.'],
      ['해설', 'Choe Yeong stayed with King U in Seogyeong, today’s Pyongyang, to direct the war.'],
      ['해설', 'The army reached Wihwado, an island in the Amnok River. But heavy rain had flooded the river.'],
      ['해설', 'The two generals asked for permission to turn back, but no permission came.'],
      ['조민수', 'We can neither go forward nor back. If this goes on, our soldiers will all suffer.'],
      ['이성계', 'To protect the people and the soldiers, we have no choice but to turn back.'],
      ['해설', 'At last the two generals disobeyed the king and turned the army around. This is the Retreat from Wihwado.'],
      ['해설', 'An army returning against the king’s order also meant one thing. It was coming for power in the capital.'],
      ['최영', 'Gather the soldiers. We must defend Gaegyeong.'],
      ['해설', 'Choe Yeong fought back but was captured, sent into exile, and later executed. King U was also removed.'],
      ['해설', 'In 1391, Yi Seong-gye and the new scholar-officials changed the land system and grew stronger.'],
      ['해설', 'In 1392, Jeong Mong-ju, who tried to protect Goryeo, was killed by men on Yi Bang-won’s side.'],
      ['해설', 'Stories of bloodstains on Seonjuk Bridge, or of the two men trading poems, came later, not from the Annals.'],
      ['해설', 'That same year, Yi Seong-gye took the throne in Gaegyeong, and Goryeo’s last king stepped down.'],
      ['해설', 'The next year, the new country was named Joseon.'],
      ['해설', 'The Annals were compiled after each king died, from notes left by sagwan, the royal historians.'],
      ['해설', 'Events before Taejo became king, like the retreat, are summarized at the start of the Annals of King Taejo.'],
      ['해설', 'But these records were made by the new dynasty. We must also read the wish to make Joseon’s founding look right.'],
      ['해설', 'Wihwado is an island near the mouth of the Amnok River.'],
    ],
  },

  'sl-02': {
    title: 'A New Capital and Jeong Do-jeon',
    names: { 해설: 'Narrator', 태조: 'King Taejo', 정도전: 'Jeong Do-jeon', 하륜: 'Ha Ryun' },
    outro: [
      'Jeong Do-jeon dreamed of a country led by ministers. What strengths and dangers did it have compared to a king-centered one?',
      'The Annals’ picture of Jeong Do-jeon was written in the era of those who killed him. How should we read it?',
      'What values and hopes are found in the names of today’s cities and public buildings?',
    ],
    lines: [
      ['해설', 'This story is based on the building of a new capital, as told in the Annals of King Taejo. The dialogue is added.'],
      ['해설', 'King Taejo, Yi Seong-gye, wanted to leave Gaegyeong, the old Goryeo capital, and build a new one.'],
      ['태조', 'A new country needs a new capital. We cannot stay in the land of the old powers.'],
      ['해설', 'At first, a site below Gyeryongsan Mountain was chosen, and building began.'],
      ['해설', 'But Ha Ryun argued the place was not right for a capital, and the work stopped.'],
      ['하륜', 'Gyeryongsan lies too far south. It is hard to travel there from every part of the country.'],
      ['해설', 'These words are a short, made-up summary of his view. He also suggested the Muak area instead.'],
      ['해설', 'After much debate, they chose Hanyang, surrounded by mountains, with the Han River beside it.'],
      ['해설', 'In 1394, Joseon moved its capital to Hanyang.'],
      ['해설', 'The man who played a big part in designing the new capital was Jeong Do-jeon.'],
      ['정도전', 'To the left of the palace, let us build Jongmyo for the royal ancestors.'],
      ['정도전', 'To the right, Sajik, the altar for the gods of land and grain.'],
      ['해설', 'This followed the order of a capital described in the Confucian classics.'],
      ['해설', 'When the palace was finished in 1395, Jeong Do-jeon named it Gyeongbokgung, the Palace of Great Blessings.'],
      ['정도전', 'It means to enjoy great blessings. But it also means blessings come only when a king grows in virtue.'],
      ['해설', 'The names of its main halls also carried a message: rule with hard work and care.'],
      ['태조', 'Every name seems to scold me a little.'],
      ['해설', 'This line is made up. But it is true that Jeong Do-jeon put warnings for the king into those names.'],
      ['해설', 'The next year, a great wall was built around the city. It is called the Seoul City Wall today.'],
      ['해설', 'Jeong Do-jeon also wrote a book that organized the systems and ruling principles of the new country.'],
      ['해설', 'He believed wise ministers should lead the government, and the king should choose them well.'],
      ['정도전', 'If a country depends only on one king’s talent, its fate becomes far too risky.'],
      ['해설', 'This idea clashed with Prince Yi Bang-won, who wanted a strong king.'],
      ['해설', 'In 1398, Jeong Do-jeon was killed in a sudden revolt led by Yi Bang-won.'],
      ['해설', 'The Annals were written by the side that ended his era, so they may judge him harshly.'],
      ['해설', 'Stories that the monk Muhak chose the site, or about the place name Wangsimni, are later legends.'],
      ['해설', 'We should read such stories apart from the facts that the Annals can confirm.'],
      ['해설', 'The name Gyeongbokgung was taken from a line in the Book of Songs, an ancient Chinese poetry collection.'],
    ],
  },

  'sl-03': {
    title: 'King Taejong and the Princes’ Strife',
    names: { 해설: 'Narrator', 이방원: 'Yi Bang-won', 태조: 'King Taejo', 이방간: 'Yi Bang-gan' },
    outro: [
      'Taejong killed brothers and old allies to become a strong king. How did his power prepare the way for Sejong?',
      'Even the king’s order to hide it from the historian ended up in the Annals. What does that say about records?',
      'Can a good goal justify any means? How would I judge that idea in today’s politics and society?',
    ],
    lines: [
      ['해설', 'This story is based on the two Strifes of the Princes recorded in the Annals. The dialogue is added.'],
      ['해설', 'King Taejo made his youngest son, Yi Bang-seok, the crown prince. He was the son of Taejo’s second queen.'],
      ['해설', 'The sons of his first wife had worked hard to found Joseon. The fifth son, Yi Bang-won, was especially angry.'],
      ['이방원', 'We risked our lives to build this country, and now we are being pushed aside.'],
      ['해설', 'On top of that, Jeong Do-jeon wanted to take away the princes’ private armies. That was a big threat to Bang-won.'],
      ['해설', 'In 1398, Yi Bang-won moved his soldiers and killed Jeong Do-jeon and his allies.'],
      ['해설', 'Crown Prince Bang-seok and his older brother also lost their lives. This was the First Strife of the Princes.'],
      ['태조', 'In the country I built with my own hands, my sons point swords at each other.'],
      ['해설', 'Heartbroken, Taejo gave the throne to his second son, Yi Bang-gwa. He became King Jeongjong.'],
      ['해설', 'Under Jeongjong, the capital moved back to Gaegyeong for a while.'],
      ['해설', 'In 1400, the fourth son, Yi Bang-gan, joined with an official named Bak Po and rose against Bang-won.'],
      ['이방간', 'I cannot let my younger brother hold all the power.'],
      ['해설', 'The brothers’ armies clashed in Gaegyeong, and Bang-won won. This was the Second Strife of the Princes.'],
      ['해설', 'Bang-won did not kill his brother but sent him into exile. Bak Po, however, was executed.'],
      ['해설', 'That year, Bang-won became crown prince and soon took the throne. He became King Taejong.'],
      ['해설', 'Taejong broke up the private armies and put the military under the state. In 1405, he moved the capital back to Hanyang.'],
      ['해설', 'For a long time, Taejo and Taejong did not get along.'],
      ['해설', 'There is a tale that messengers sent to Taejo in Hamheung never came back. Later unofficial histories greatly exaggerated it.'],
      ['해설', 'It differs from the Annals, so we should separate legend from fact.'],
      ['해설', 'A famous story about a historian also comes from Taejong’s reign.'],
      ['해설', 'The king fell from his horse while hunting and told people not to let the historian know.'],
      ['해설', 'But the historian wrote down even those words. The Annals kept even what kings wanted to hide.'],
      ['이방원', 'If every word and deed of the king is written down, even a king cannot act as he pleases.'],
      ['해설', 'This line is made up. But it is clear that the historians’ records helped keep kings in check.'],
      ['해설', 'Taejong also broke the power of the queen’s family. Queen Min’s brothers lost their lives in the process.'],
      ['해설', 'He also removed his eldest son, Grand Prince Yangnyeong, as crown prince and chose his third son, Grand Prince Chungnyeong.'],
      ['해설', 'In 1418, the same year, Taejong passed the throne to the new crown prince. He became King Sejong.'],
    ],
  },

  'sl-04': {
    title: 'King Sejong and Hunminjeongeum',
    names: { 해설: 'Narrator', 세종: 'King Sejong', 최만리: 'Choe Man-ri', 정인지: 'Jeong In-ji' },
    outro: [
      'Sejong pushed ahead with new letters despite strong opposition. What did that choice leave for later Korean history?',
      'If we read Choe Man-ri’s objection through the eyes of his time, what logic was behind his worries?',
      'Today, what tools or systems are needed so that everyone can easily read and write information?',
    ],
    lines: [
      ['해설', 'This story is based on events in the Annals of King Sejong. The dialogue is made up from the meaning of the records.'],
      ['해설', 'In 1420, early in his reign, Sejong greatly expanded the Jiphyeonjeon, the Hall of Worthies, as a research center.'],
      ['해설', 'Young scholars studied old systems and classics. The king even gave them time off just to read.'],
      ['세종', 'When the people are wronged, they cannot even complain, because they cannot write. How sad that is.'],
      ['해설', 'In those days, writing meant Chinese characters, and most people could not afford to learn them.'],
      ['해설', 'In 1443, the Annals noted that the king himself had made twenty-eight letters, called eonmun.'],
      ['해설', 'Scholars of the Hall helped with the research, but the Annals name Sejong as the creator of the letters.'],
      ['해설', 'The next year, Choe Man-ri and other scholars sent a letter opposing them. It is also in the Annals.'],
      ['최만리', 'Making letters different from China’s goes against our duty to the great country.'],
      ['최만리', 'We already have idu, a way of writing Korean with Chinese characters. New letters may make people neglect learning.'],
      ['해설', 'These lines are a short summary of their letter. Sejong called them in and argued back himself.'],
      ['세종', 'Do you understand the rules of sounds and letters? If I do not set them right, who will?'],
      ['해설', 'This too is a made-up version of the point of Sejong’s reply.'],
      ['해설', 'Sejong had the officials who opposed him locked up for a day, then set them free.'],
      ['해설', 'In 1446, the new letters were announced as Hunminjeongeum, the correct sounds for teaching the people.'],
      ['해설', 'A book explaining how the letters worked, now called the Haerye edition, came out at the same time.'],
      ['정인지', 'A wise person can learn them before the morning ends. Even a slow person can learn them in ten days.'],
      ['해설', 'This retells a famous idea from Jeong In-ji’s preface to that book.'],
      ['해설', 'The consonants copy the shape of the mouth and tongue. The vowels stand for heaven, earth, and people.'],
      ['해설', 'But in a yangban, or noble, society that used Chinese characters, the letters were long looked down on.'],
      ['해설', 'Meanwhile, Sejong wanted to read the Annals of his father, Taejong, but his ministers opposed it.'],
      ['해설', 'If a king read the Annals, they said, historians would be too afraid to write the truth.'],
      ['세종', 'Perhaps by not reading them, I protect honest records for the future.'],
      ['해설', 'These words are made up, but the Annals do say that Sejong gave up reading them.'],
      ['해설', 'The Haerye book was forgotten for a long time. It was found again in the twentieth century.'],
      ['해설', 'Today, Hangeul Day is set by the date of announcement written in that book.'],
      ['해설', 'In 1997, the Haerye edition of Hunminjeongeum was added to UNESCO’s Memory of the World Register.'],
    ],
  },

  'sl-05': {
    title: 'King Sejong and Jang Yeong-sil',
    names: { 해설: 'Narrator', 세종: 'King Sejong', 장영실: 'Jang Yeong-sil', 신하: 'Official' },
    outro: [
      'Sejong gave a post to Jang Yeong-sil despite his low birth. What did that choice bring to science in Joseon?',
      'Many think Jang Yeong-sil made the rain gauge, but the Annals say otherwise. What does that teach about reading sources?',
      'How has knowing the exact time and weather changed our lives today?',
    ],
    lines: [
      ['해설', 'This story is based on records in the Annals of King Sejong. The dialogue is added.'],
      ['해설', 'The Annals say Jang Yeong-sil was born a government slave who belonged to an office in Dongnae.'],
      ['해설', 'He was so skilled with his hands that he worked for the palace from Taejong’s time. Sejong valued him even more.'],
      ['신하', 'Your Majesty, giving an official post to a man born a slave goes against our laws.'],
      ['세종', 'If we throw away a talented man because of his birth, is that not a loss for the country?'],
      ['해설', 'This talk is dramatized. But the Annals do say Sejong discussed it with officials and gave him a post.'],
      ['해설', 'In a time when farming was the base of the nation, exact time and weather mattered greatly to the people.'],
      ['세종', 'Telling the people the right seasons of Heaven is a great duty of a king.'],
      ['해설', 'Under Sejong, instruments were made to measure the movements of the stars and the sun.'],
      ['해설', 'Officials and scholars like Yi Cheon worked together with craftsmen like Jang Yeong-sil.'],
      ['해설', 'In 1434, Jagyeongnu, a water clock that announced the time by itself, was completed.'],
      ['장영실', 'As water rises steadily, a ball rolls down, and the figures strike the bell and drum.'],
      ['해설', 'This explanation is made up to show the idea simply. The clock told time without anyone watching it.'],
      ['해설', 'That same year, Angbu Ilgu, a sundial shaped like a bowl, was also made.'],
      ['해설', 'Some were placed along busy streets, so ordinary people could also see the time.'],
      ['해설', 'Records also say the hours were shown with animal pictures for people who could not read.'],
      ['해설', 'Jang Yeong-sil also helped make Gabinja, a set of metal printing type.'],
      ['해설', 'In 1441, a vessel for measuring rainfall was made. This is the cheugugi, the rain gauge.'],
      ['해설', 'Many believe Jang Yeong-sil invented it. But the Annals say the crown prince, later King Munjong, designed it.'],
      ['해설', 'The next year, rain gauges were sent across the country, and each town measured and reported its rainfall.'],
      ['해설', 'But in 1442, a royal carriage made under Jang Yeong-sil’s watch broke.'],
      ['신하', 'The king’s own carriage has broken. The man in charge must bear heavy blame.'],
      ['해설', 'Jang Yeong-sil was punished for this and lost his post.'],
      ['장영실', 'So my years of serving His Majesty end like this.'],
      ['해설', 'This line is made up. How he lived after that is not recorded in the Annals.'],
      ['해설', 'Many have imagined his last years. But it is honest to say that what is not recorded, we cannot know.'],
      ['해설', 'Jagyeongnu was completed in 1434 and set up in a special pavilion at Gyeongbokgung Palace.'],
    ],
  },

  'sl-06': {
    title: 'King Sejong and the Northern Frontier',
    names: { 해설: 'Narrator', 세종: 'King Sejong', 최윤덕: 'Choe Yun-deok', 김종서: 'Kim Jong-seo', 백성: 'Villager' },
    outro: [
      'Pushing the border north helped the nation. But what did it mean for the people who were moved there?',
      'Thinking about how Joseon’s records described the Jurchen, how should we imagine their side of the story?',
      'If we know when and how today’s borders were made, how might we see our neighbors differently?',
    ],
    lines: [
      ['해설', 'This story is based on the northern campaigns told in the Annals of King Sejong. The dialogue is added.'],
      ['해설', 'In early Joseon, many Jurchen tribes lived along the Amnok and Duman Rivers.'],
      ['해설', 'Sometimes they traded with Joseon, and sometimes they raided border villages. People in the north never felt safe.'],
      ['세종', 'How can the nation be at peace when the people of the north cannot live safely?'],
      ['해설', 'Sejong sent Choe Yun-deok to the Amnok River side and Kim Jong-seo to the Duman River side.'],
      ['해설', 'In 1433, Choe Yun-deok crossed the Amnok and attacked the Jurchen along the Pajeo River.'],
      ['최윤덕', 'We will build forts along the river, so our people are never carried off again.'],
      ['해설', 'Later, four counties were set up one by one along the upper Amnok River. These are the Four Counties.'],
      ['해설', 'On the Duman side, Kim Jong-seo stayed for many years and built forts.'],
      ['김종서', 'Keeping land is harder than winning it. Land is only kept when people live on it.'],
      ['해설', 'Six forts were built near the lower Duman River, including Hoeryeong and Gyeongwon. These are the Six Garrisons.'],
      ['해설', 'To keep the land, people had to live there. The court moved people from the south to the north.'],
      ['백성', 'We must leave the home of our ancestors and go to the cold border?'],
      ['해설', 'This villager’s words are made up. But records suggest that many people did not want to move.'],
      ['해설', 'The court gave benefits to settlers and also hired local people as officials there.'],
      ['해설', 'Some ministers opposed the plan, saying the cost and the suffering were too great.'],
      ['세종', 'I cannot give up the land of our ancestors just because it is hard.'],
      ['해설', 'These words are made up to show why Sejong pushed the plan forward.'],
      ['해설', 'In this process, Jurchen people also lost their homes or were caught up in fighting.'],
      ['해설', 'Joseon’s records were written from Joseon’s point of view, so we must think about the Jurchen side separately.'],
      ['해설', 'The Four Counties were hard to defend, so they were closed after Sejong died.'],
      ['해설', 'The Six Garrisons remained and became the center of northern defense.'],
      ['해설', 'In this way, a border along the Amnok and Duman Rivers mostly took shape.'],
      ['해설', 'Kim Jong-seo later rose to high office under King Danjong, but he was killed in a power struggle.'],
      ['해설', 'Opening the north took more than force. It was a long process of moving people and building systems.'],
      ['해설', 'The Four Counties were on the upper Amnok River, and the Six Garrisons near the lower Duman River.'],
    ],
  },

  'sl-07': {
    title: 'King Danjong and the Gyeyu Coup',
    names: { 해설: 'Narrator', 수양: 'Prince Suyang', 김종서: 'Kim Jong-seo', 한명회: 'Han Myeong-hoe', 단종: 'King Danjong' },
    outro: [
      'Did Prince Suyang’s coup bring stability to the nation, or did he steal the throne?',
      'In records made by Sejo’s followers, how were Danjong and Kim Jong-seo described, and what should we doubt?',
      'Does the side with power still write the records today? If so, how can we prevent it?',
    ],
    lines: [
      ['해설', 'This story is based on records in the Annals. The characters’ words are made up.'],
      ['해설', 'Sejong’s son, King Munjong, was weak and died only a few years after taking the throne.'],
      ['해설', 'In 1452, a twelve-year-old crown prince became king. He was later called King Danjong.'],
      ['해설', 'Senior ministers like Hwangbo In and Kim Jong-seo ran the government for the young king.'],
      ['단종', 'Ministers, please help me well.'],
      ['해설', 'But the king’s uncle, Prince Suyang, believed the ministers had taken power and pushed the royal family aside.'],
      ['한명회', 'My lord, if you do not move first, they will raise their swords first.'],
      ['수양', 'If I, a royal, do not act, this country will belong to the ministers.'],
      ['해설', 'In 1453, Prince Suyang led his men to Kim Jong-seo’s house.'],
      ['김종서', 'My lord, what brings you here at this hour of night?'],
      ['해설', 'The Annals say that one of Suyang’s followers struck Kim Jong-seo with an iron hammer.'],
      ['해설', 'Then, using the king’s name, they called ministers to the palace and killed Hwangbo In and others.'],
      ['해설', 'This event is called the Gyeyu Coup, after the name of that year in the old calendar.'],
      ['해설', 'Suyang claimed that Kim Jong-seo and others had plotted treason. The Annals told the story from that view.'],
      ['해설', 'We must remember that Sejo’s side put together the records of this period.'],
      ['해설', 'Suyang’s younger brother, Prince Anpyeong, was also sent into exile and then killed.'],
      ['해설', 'After the coup, Suyang became the chief minister and took control of the country.'],
      ['단종', 'I sit on this throne, but I decide nothing at all.'],
      ['해설', 'In 1455, Danjong gave the throne to Suyang and became the retired king. Suyang became King Sejo.'],
      ['해설', 'The next year, a plan to put Danjong back on the throne was discovered, and many people were executed.'],
      ['해설', 'Danjong was lowered to the rank of Prince Nosan and exiled to Yeongwol in Gangwon Province.'],
      ['해설', 'When Sejo’s brother, Prince Geumseong, plotted again and was caught, Danjong lost his life that same year.'],
      ['해설', 'Records from Sejo’s time say he took his own life, but many find this hard to believe.'],
      ['해설', 'Many different stories about his death were passed down later.'],
      ['해설', 'The records of Danjong’s reign were first compiled as the Diary of Prince Nosan.'],
      ['해설', 'When he was restored as king under King Sukjong, the records came to be called the Annals of King Danjong.'],
      ['해설', 'The royal title Danjong was given to him in 1698, under King Sukjong.'],
    ],
  },

  'sl-08': {
    title: 'The Six Martyrs and Six Loyal Subjects',
    names: { 해설: 'Narrator', 성삼문: 'Seong Sam-mun', 박팽년: 'Bak Paeng-nyeon', 세조: 'King Sejo', 김시습: 'Kim Si-seup' },
    outro: [
      'Some risked their lives to restore Danjong, and others gave up office and hid. How were their choices different and alike?',
      'People the Annals called traitors were later honored as loyal. What makes historical judgments change?',
      'When my own interest and my principles clash, what standard will I use to choose?',
    ],
    lines: [
      ['해설', 'This story is based on the Annals and later records. The characters’ words are made up.'],
      ['해설', 'When Sejo took the throne, some scholars from the Hall of Worthies could not accept it.'],
      ['성삼문', 'The retired king is still alive. How can we serve another king?'],
      ['박팽년', 'Let us wait for the right time. The day will come when we serve the retired king again.'],
      ['해설', 'In 1456, they planned to kill Sejo at a banquet for Ming envoys and restore Danjong.'],
      ['해설', 'But plans changed that day, and they had to delay.'],
      ['해설', 'Anxious, a member named Kim Jil told his father-in-law, Jeong Chang-son, who then told Sejo.'],
      ['세조', 'The men who served me were holding knives behind my back?'],
      ['해설', 'Those involved were arrested and harshly questioned. Many were executed or died in prison.'],
      ['해설', 'Their families were also severely punished for their crime.'],
      ['해설', 'The Annals of Sejo’s time recorded them as criminals who plotted treason.'],
      ['해설', 'There is a famous story that Seong Sam-mun refused to call Sejo king, using a lower title instead.'],
      ['해설', 'But scenes like that do not come from the Annals. They come from later works like Nam Hyo-on’s Biographies of the Six.'],
      ['해설', 'Seong Sam-mun, Bak Paeng-nyeon, Ha Wi-ji, Yi Gae, Yu Seong-won, and Yu Eung-bu were the six.'],
      ['해설', 'Calling these six the Six Martyrs also began with that book.'],
      ['해설', 'In fact, many more than six people were involved.'],
      ['해설', 'Others did not risk their lives, but they refused to serve Sejo’s court and stayed loyal all their lives.'],
      ['김시습', 'I will break my brush and wander the world. That is the loyalty I can keep.'],
      ['해설', 'It is said that Kim Si-seup burned his books, became a monk, and wandered across the country.'],
      ['해설', 'Kim Si-seup, Won Ho, Yi Maeng-jeon, Jo Ryeo, Seong Dam-su, and Nam Hyo-on are called the Six Loyal Subjects.'],
      ['해설', 'Nam Hyo-on, who wrote the book about the six martyrs, is counted among them too.'],
      ['해설', 'Under King Sukjong in late Joseon, the Six Martyrs’ titles were restored, and they were honored as loyal subjects.'],
      ['해설', 'The same people were traitors in one age and heroes in another.'],
      ['해설', 'Their tombs are in Noryangjin, Seoul.'],
      ['해설', 'Even in modern times, people have argued over who should be counted among the Six Martyrs.'],
      ['해설', 'The Annals saw them through the eyes of power. The Biographies honored them. We should read both side by side.'],
      ['해설', 'Kim Si-seup wrote Geumo Sinhwa, often called the first Korean book of stories written in Chinese.'],
    ],
  },

  'sl-09': {
    title: 'King Seongjong and the Great Code',
    names: { 해설: 'Narrator', 성종: 'King Seongjong', 대비: 'Queen Dowager', 김종직: 'Kim Jong-jik' },
    outro: [
      'Seongjong completed a law code to rule by law. How did that choice change Joseon society?',
      'Reading the articles of the code, what can we learn about class and gender discrimination in that age?',
      'How is the way laws change today similar to, or different from, the making of the Great Code?',
    ],
    lines: [
      ['해설', 'This story is based on the Annals of King Seongjong and other records. The dialogue is dramatized.'],
      ['해설', 'In 1469, King Yejong died young, and the boy Seongjong took the throne.'],
      ['해설', 'Because he was young, his grandmother, Sejo’s queen, ruled from behind a screen.'],
      ['대비', 'Until you can rule the country yourself, I will help you from behind.'],
      ['해설', 'This was called suryeom cheongjeong. A senior royal woman sat behind a bamboo screen and helped with state affairs.'],
      ['해설', 'As he grew, Seongjong faithfully attended royal lectures, studying classics and history with his officials.'],
      ['성종', 'If a king does not learn, he cannot even understand his ministers’ honest advice.'],
      ['해설', 'At that time, Joseon’s laws were not gathered in one place. Many separate rules were scattered about.'],
      ['해설', 'King Sejo had begun to compile Gyeongguk Daejeon, the Great Code, to be followed forever.'],
      ['해설', 'But it was not finished under Sejo, and the work of fixing and polishing went on.'],
      ['성종', 'If laws change too often, the people do not know what to follow. We must settle them this time.'],
      ['해설', 'At last, under Seongjong, the Great Code was completed and put into effect in 1485.'],
      ['해설', 'It was divided into six parts: officials, finance, rites, military, punishment, and building and crafts.'],
      ['해설', 'For example, it said that parents’ property should be divided equally between sons and daughters.'],
      ['해설', 'But there was also a rule that the children of remarried women could not take the state exam.'],
      ['해설', 'Detailed rules about the status of slaves were included too. The class system was fixed by law.'],
      ['해설', 'The code brought order to the nation, but it also carried the discrimination of its time.'],
      ['해설', 'Seongjong set up the Hongmungwan, an office that followed the Hall of Worthies, to study and advise the king.'],
      ['해설', 'He also brought Kim Jong-jik and other scholars from the southeast, called the sarim, into the court.'],
      ['김종직', 'A scholar must think of what is right before thinking of rank.'],
      ['해설', 'The sarim kept the king and ministers in check with honest words. This also planted seeds of conflict.'],
      ['해설', 'Seongjong’s reign also had dark moments. Queen Yun was removed and later forced to drink poison.'],
      ['해설', 'The deposed Queen Yun was the mother of the crown prince, the future Yeonsangun.'],
      ['해설', 'This would bring a storm of blood in the next reign.'],
      ['해설', 'Later codes revised and added to it, but the Great Code remained the base of Joseon law until the end.'],
      ['해설', 'The Great Code has six sections, one for each of the six ministries of the government.'],
    ],
  },

  'sl-10': {
    title: 'Yeonsangun and the Restoration of 1506',
    names: { 해설: 'Narrator', 연산군: 'Yeonsangun', 김일손: 'Kim Il-son', 박원종: 'Bak Won-jong' },
    outro: [
      'Was removing the king in 1506 a just end to tyranny, or just another struggle for power?',
      'The Diary of Yeonsangun was compiled by those who removed him. What parts should we read carefully?',
      'When people in power try to block criticism and records, what can check them in today’s society?',
    ],
    lines: [
      ['해설', 'This story is based on the Diary of Yeonsangun and the Annals of King Jungjong. The dialogue is dramatized.'],
      ['해설', 'In 1494, Yeonsangun took the throne after his father, King Seongjong.'],
      ['해설', 'At first there were no big problems. But he began to clash more and more with officials who spoke honestly.'],
      ['해설', 'The first big incident began with the making of the Annals.'],
      ['해설', 'While the Annals of King Seongjong were being compiled, a piece by Kim Jong-jik was found in Kim Il-son’s notes.'],
      ['해설', 'Some read the piece as hidden criticism of Sejo for taking the throne from Danjong.'],
      ['김일손', 'A historian only writes what he sees and hears, without hiding anything.'],
      ['해설', 'When the king learned of this in 1498, Kim Il-son and many sarim scholars were executed or exiled.'],
      ['해설', 'Even Kim Jong-jik, already dead, was given a harsh punishment after death. This was the Purge of 1498.'],
      ['해설', 'Kings were not supposed to see the historians’ notes or the Annals. This incident broke that rule.'],
      ['해설', 'In 1504, Yeonsangun punished everyone connected to the death of his mother, the deposed Queen Yun.'],
      ['연산군', 'Find every last person who drove my mother to her death.'],
      ['해설', 'Even the dead were punished, and many officials lost their lives. This was the Purge of 1504.'],
      ['해설', 'Yeonsangun stopped the royal lectures and closed the office that gave the king honest advice.'],
      ['해설', 'When writings in Hangeul criticizing him spread, he banned people from teaching or using Hangeul.'],
      ['연산군', 'When the words scolding the king are gone, the country will be quiet.'],
      ['해설', 'But only honest words went quiet. Luxury and feasts went on, and the people’s burden grew.'],
      ['해설', 'In 1506, Bak Won-jong, Seong Hui-an, Yu Sun-jeong, and others raised troops.'],
      ['박원종', 'The king has abandoned the duty of a king. We must serve a new one.'],
      ['해설', 'They made Seongjong’s son, Grand Prince Jinseong, the new king. He became King Jungjong.'],
      ['해설', 'This event is called Jungjong Banjeong, the restoration that put Jungjong on the throne.'],
      ['해설', 'Yeonsangun was lowered to the rank of prince and sent to Gyodong Island. He died that same year.'],
      ['해설', 'The new leaders also removed Jungjong’s queen, Lady Sin. Her father had opposed them and been killed.'],
      ['해설', 'The records of Yeonsangun’s reign were compiled by the side that removed him.'],
      ['해설', 'So even if his tyranny was real, we should keep in mind that some parts may be exaggerated.'],
      ['해설', 'His records are called the Diary of Yeonsangun because he was driven from the throne.'],
      ['해설', 'Among Joseon kings, only the records of Yeonsangun and Gwanghaegun are called diaries, not annals.'],
    ],
  },
};
