// 청소년 영어 원고 (중학생 이상). 키 = stories/teen-b.js 의 이야기 id.
// 오 헨리 작품은 원작의 이름·핵심 표현을 살리되 한국어 각색의 흐름대로 새로 씀. 도데·패러데이는 쉬운 영어로 새로 씀.
export default {
  'tb-last-leaf': {
    title: 'The Last Leaf',
    names: { 해설: 'Narrator', 수: 'Sue', 존시: 'Johnsy', 의사: 'Doctor', 베어먼: 'Behrman' },
    outro: [
      'Through Behrman’s last painting, what did O. Henry want to say about a true masterpiece?',
      'The last leaf was really painted on the wall. How does this twist change the meaning of the story?',
      'What could you take on yourself to protect someone else’s hope?',
    ],
    lines: [
      ['해설', 'In Greenwich Village, New York, two young artists, Sue and Johnsy, lived at the top of an old brick building.'],
      ['해설', 'They had met at a small restaurant, found they liked the same kind of art, and opened a studio together.'],
      ['해설', 'That November, pneumonia swept through the neighborhood like a cold stranger, and Johnsy fell ill.'],
      ['해설', 'After the doctor examined her, he called Sue out into the hallway.'],
      ['의사', 'She has about one chance in ten. And that chance depends on her wanting to live.'],
      ['의사', 'But she seems to have given up already. Is there anything she really cares about?'],
      ['수', 'She once said she wanted to paint the Bay of Naples someday.'],
      ['의사', 'Not painting. Something she truly cares about. That would make her chances much better.'],
      ['해설', 'When the doctor left, Sue cried for a long time. Then she walked into Johnsy’s room, whistling on purpose.'],
      ['해설', 'While Sue drew pictures for a magazine, Johnsy looked out the window and counted backward in a low voice.'],
      ['존시', 'Twelve, eleven, ten, nine. Eight, seven.'],
      ['수', 'Johnsy, what are you counting?'],
      ['존시', 'Leaves. On the ivy vine on that brick wall. Three days ago there were almost a hundred. Now there are only five.'],
      ['존시', 'When the last one falls, I must go too. Didn’t the doctor tell you?'],
      ['수', 'What nonsense! What does an old ivy leaf have to do with you getting well?'],
      ['해설', 'Downstairs lived Behrman, a painter over sixty. He always talked about his masterpiece, but his canvas had been blank for twenty-five years.'],
      ['해설', 'When Sue told him about Johnsy, Behrman shouted angrily, his eyes red.'],
      ['베어먼', 'People dying because leaves fall from a vine? What a foolish idea!'],
      ['베어먼', 'That good girl should not lie sick in a place like this. Someday I will paint my masterpiece, and we will all go away.'],
      ['해설', 'That night, cold rain and sleet beat against the window until morning.'],
      ['해설', 'In the morning, Johnsy asked Sue to raise the shade. Sue pulled the cord with shaking hands.'],
      ['해설', 'One leaf still hung on the brick wall. Its edges were yellow, but near the stem it was still dark green.'],
      ['존시', 'It is the last one. I thought it would fall in the night. It will fall today, and I will go with it.'],
      ['해설', 'The day ended, and the north wind blew all night again. But the next morning, the leaf was still there.'],
      ['존시', 'Sue, I have been a bad girl. That leaf stayed there to show me. It is wrong to want to die.'],
      ['존시', 'Could you bring me some soup? And a mirror. Someday I will paint the Bay of Naples.'],
      ['해설', 'That afternoon, the doctor said her chances were even. The next day, he said she was out of danger.'],
      ['의사', 'But Mr. Behrman downstairs has pneumonia too. He is old and weak, and there is no hope. He goes to the hospital today.'],
      ['수', 'Johnsy, Mr. Behrman died in the hospital today. He was sick for only two days.'],
      ['수', 'On that stormy night, they found him soaking wet. Beside him were a ladder, a lantern, and a palette of green and yellow.'],
      ['수', 'Look at that leaf. It never moved in the wind. It is Behrman’s masterpiece. He painted it the night the last leaf fell.'],
      ['해설', 'The Last Leaf appears in The Trimmed Lamp, a collection of O. Henry’s short stories published in 1907.'],
    ],
  },

  'tb-gift-magi': {
    title: 'The Gift of the Magi',
    names: { 해설: 'Narrator', 델라: 'Della', 짐: 'Jim', 소프로니: 'Madame Sofronie' },
    outro: [
      'Why did O. Henry call these two the wisest, even though their gifts became useless?',
      'Each of them secretly sold a treasure for the other. What effect does this crossing of gifts create?',
      'Have you ever given or received a gift whose heart meant more than its price?',
    ],
    lines: [
      ['해설', 'One dollar and eighty-seven cents. That was all Della had, and sixty cents of it was in pennies.'],
      ['해설', 'She had saved it a few cents at a time, blushing as she bargained with the grocer. And tomorrow was Christmas.'],
      ['해설', 'Della threw herself on the shabby little couch and cried. After crying, she could think a little again.'],
      ['해설', 'Their furnished flat cost eight dollars a week. Her husband Jim’s pay had fallen from thirty dollars a week to twenty.'],
      ['델라', 'What can I buy Jim with one dollar and eighty-seven cents? I want something fine, something worthy of him.'],
      ['해설', 'The couple had two proud treasures. One was Jim’s gold watch, passed down from his grandfather and father. The other was Della’s hair.'],
      ['해설', 'When she let it down, her brown hair fell below her knees, rippling and shining like a waterfall.'],
      ['해설', 'Della stood before the mirror for a long time. Then she put on her old brown jacket and hat and went out.'],
      ['해설', 'She stopped at the shop of Madame Sofronie, who sold hair goods of all kinds.'],
      ['델라', 'Will you buy my hair?'],
      ['소프로니', 'I buy hair. Take your hat off and let me have a look at it.'],
      ['해설', 'Down rippled the brown waterfall. Madame lifted the mass of hair with a practiced hand to judge its weight.'],
      ['소프로니', 'Twenty dollars.'],
      ['델라', 'Give it to me quick.'],
      ['해설', 'The next two hours flew by on rosy wings. Della searched every store for Jim’s present.'],
      ['해설', 'At last she found it. It was a simple, elegant platinum watch chain, and it cost twenty-one dollars.'],
      ['델라', 'This is it. It is perfect for Jim’s watch. Now he won’t have to look at the time secretly because of his old leather strap.'],
      ['해설', 'Della came home with eighty-seven cents. She heated the curling iron and curled her short hair.'],
      ['델라', 'Please God, make him think I am still pretty.'],
      ['해설', 'At seven o’clock the door opened and Jim stepped in. When he saw Della, he stood frozen.'],
      ['해설', 'It was not anger, surprise, or disappointment on his face. It was a look Della could not understand.'],
      ['델라', 'Jim, don’t look at me like that. I sold my hair to buy you a present. It will grow out again.'],
      ['짐', 'You’ve cut off your hair? It is really gone?'],
      ['해설', 'Jim woke as if from a dream and hugged Della. Then he took a package from his coat pocket and put it on the table.'],
      ['짐', 'No haircut could make me love you any less. But if you open that, you will see why I was so stunned.'],
      ['해설', 'Inside were the combs Della had admired in a Broadway window for so long. They were tortoise shell, with jeweled rims.'],
      ['델라', 'My hair grows so fast, Jim! Oh, and look at your present. Give me your watch. I want to see how it looks with the chain.'],
      ['짐', 'Della, let’s put our Christmas presents away for a while. They’re too nice to use just now. I sold the watch to buy your combs.'],
      ['짐', 'And now, let’s cook the chops for dinner.'],
      ['해설', 'The magi were wise men who brought gifts to the Babe in the manger. The custom of Christmas presents began with them.'],
      ['해설', 'These two foolishly gave up their greatest treasures for each other. Yet of all who give gifts, these two were the wisest.'],
      ['해설', 'The story first appeared in The Four Million, O. Henry’s short story collection, in 1906.'],
    ],
  },

  'tb-last-class': {
    title: 'The Last Lesson',
    names: { 해설: 'Narrator', 프란츠: 'Franz', 아멜: 'Monsieur Hamel', 대장장이: 'Blacksmith' },
    outro: [
      'Through the last lesson, what did Daudet want to say about what a mother tongue means to a people?',
      'What feelings do Monsieur Hamel’s last words on the board and his silent wave stand for?',
      'How does this story connect with the efforts of Koreans who tried to protect their own language in our history?',
    ],
    lines: [
      ['해설', 'That morning, Franz was late for school. Worse, he had not learned the rules for participles that Monsieur Hamel had assigned.'],
      ['해설', 'The sky was clear and warm. Birds sang in the woods, and Prussian soldiers were drilling in the field.'],
      ['해설', 'Franz was tempted to skip school and wander outside. But he made up his mind and ran to school.'],
      ['해설', 'A crowd stood before the bulletin board at the town hall. For two years, all the bad news had come from that board.'],
      ['대장장이', 'Don’t hurry so, boy. You will get to school in plenty of time.'],
      ['해설', 'Franz thought the man was teasing him. Out of breath, he hurried into the schoolyard.'],
      ['해설', 'Usually the classroom was noisy with desks banging and children reciting. Today it was as quiet as a Sunday morning.'],
      ['해설', 'Blushing, Franz opened the door. Monsieur Hamel did not scold him. He spoke gently instead.'],
      ['아멜', 'Go to your place quickly, little Franz. We were about to begin without you.'],
      ['해설', 'Only then did Franz notice the fine green coat his teacher wore only on inspection days and prize days.'],
      ['해설', 'Village people sat on the empty benches at the back. Old Hauser was there in his three-cornered hat, with the former mayor and postman.'],
      ['해설', 'Old Hauser held an old spelling book open on his knees. Its edges were worn thin.'],
      ['아멜', 'My children, this is the last time I will teach you.'],
      ['아멜', 'An order has come from Berlin. Only German may be taught in the schools of Alsace and Lorraine. The new teacher comes tomorrow.'],
      ['아멜', 'This is your last French lesson. I beg you to listen carefully.'],
      ['해설', 'Franz’s heart sank. That was the news posted on the board.'],
      ['프란츠', 'My last lesson? I can hardly even write. Will I never learn any more?'],
      ['해설', 'He was so sorry for the hours he had wasted hunting birds’ nests and sliding on the ice.'],
      ['해설', 'His grammar book and his book of saints, once so heavy and dull, now felt like old friends he hated to leave.'],
      ['해설', 'Then it was Franz’s turn to recite. He stumbled on the very first rule and hung his head at his desk.'],
      ['아멜', 'I won’t scold you, little Franz. You are punished enough. We have always put off learning until tomorrow.'],
      ['아멜', 'Now they will say, you call yourselves French, yet you can neither read nor write your own language.'],
      ['아멜', 'French is the most beautiful and the clearest language in the world. Never forget it. Guard it well.'],
      ['아멜', 'When a people is enslaved, as long as it holds on to its language, it holds the key to its prison.'],
      ['해설', 'In the writing lesson, new copies hung from every desk like little flags. They read France, Alsace in beautiful letters.'],
      ['해설', 'Pigeons cooed softly on the roof. Franz wondered, will they make the pigeons sing in German too?'],
      ['해설', 'Old Hauser put on his glasses and read the letters aloud with the children. His voice was shaking.'],
      ['해설', 'The church clock struck twelve, and the bell rang for prayer. Outside, the Prussian trumpets sounded as the soldiers returned.'],
      ['아멜', 'My friends, I, I.'],
      ['해설', 'He could not go on. He turned to the board and wrote as large as he could, pressing hard with the chalk. Long live France!'],
      ['해설', 'Then he leaned his head against the wall and waved his hand without a word. It is over. Go.'],
      ['해설', 'The Last Lesson appears in Monday Tales, a collection of Alphonse Daudet’s short stories published in 1873.'],
    ],
  },

  'tb-candle-1': {
    title: 'The Chemical History of a Candle, Part 1',
    names: { 해설: 'Narrator', 패러데이: 'Michael Faraday', 학생: 'Student' },
    outro: [
      'Why do you think Faraday chose a single candle to begin his science lectures?',
      'How did the salt pillar experiment show what happens inside a candle wick?',
      'Can you find an example of capillary action in your everyday life?',
    ],
    lines: [
      ['해설', 'In the winter of 1860, a hall at the Royal Institution in London was full of young people. Michael Faraday stood at the front.'],
      ['패러데이', 'From today, we will talk about a single candle. Hardly any law of nature has nothing to do with a candle.'],
      ['학생', 'Sir, you will give several lectures about just one candle?'],
      ['패러데이', 'Yes. There is no better key than a candle for opening the door to the study of nature.'],
      ['해설', 'Faraday set out many candles on the table. Some were made of animal fat, some of beeswax, and some of stearin.'],
      ['패러데이', 'Long ago, people soaked the pith of rushes in fat to make light. Now we use cleaner stuff like stearin and wax.'],
      ['해설', 'He lit one candle and brought it forward so everyone could see.'],
      ['패러데이', 'Look just below the flame. The top of the candle is hollow like a little cup, and melted fuel lies in it.'],
      ['학생', 'Why doesn’t the edge melt too? Why does it stay in a cup shape?'],
      ['패러데이', 'Air heated by the flame rises. Then cool air rushes in from below and cools the edge of the candle.'],
      ['패러데이', 'So only the middle melts. The edge stays solid like a wall and becomes a cup for the melted fuel.'],
      ['패러데이', 'If wind blows from one side, the cup breaks there and wax runs down. Air must rise evenly to make an even cup.'],
      ['학생', 'But how does the melted wax climb up to the flame? I would expect it to flow down.'],
      ['패러데이', 'Good question. To answer it, I have prepared a pillar of salt.'],
      ['해설', 'He stood a pillar of packed salt in a dish. Then he poured strong salt water, colored blue, into the dish.'],
      ['해설', 'Soon the blue liquid slowly crept up the white salt pillar.'],
      ['패러데이', 'Liquid is drawn up through the tiny spaces between the grains. We call this capillary action.'],
      ['패러데이', 'The same thing happens in a candle wick. Melted fuel climbs through the spaces between the threads to the flame.'],
      ['패러데이', 'When you dry your hands, the towel soaks up the water in the same way.'],
      ['학생', 'Then why doesn’t the wick burn away all at once?'],
      ['패러데이', 'Because the fuel soaked into the wick burns instead. So the wick gets shorter only little by little from the top.'],
      ['해설', 'Next, Faraday blew the candle out. At once he held another flame to the white smoke rising from it.'],
      ['해설', 'The fire ran down the stream of smoke and lit the wick again.'],
      ['패러데이', 'Did you see? A candle does not burn as a solid or a liquid. It burns only after the heat turns it into vapor.'],
      ['학생', 'Does the flame always stand tall and pointed because of the moving air too?'],
      ['패러데이', 'Yes. Hot air rises and pulls the flame upward. Next time, we will look inside the flame.'],
      ['패러데이', 'And remember this. Experiments with fire must only be done in a safe place with a teacher or another adult.'],
      ['해설', 'Around Christmas 1860, Faraday gave these six lectures for young people at the Royal Institution in London.'],
    ],
  },

  'tb-candle-2': {
    title: 'The Chemical History of a Candle, Part 2',
    names: { 해설: 'Narrator', 패러데이: 'Michael Faraday', 학생: 'Student' },
    outro: [
      'What did Faraday want his audience to learn by studying the flame one part at a time?',
      'Why does a candle shine so brightly, and what role does soot play in that?',
      'Have you ever seen the difference between a smoky fire and a clean-burning one in daily life?',
    ],
    lines: [
      ['해설', 'At the second lecture, Faraday said they would look more closely at the candle flame.'],
      ['패러데이', 'A flame looks the same everywhere, but each part is different. Inside, around the wick, it is dark. Outside, it shines.'],
      ['해설', 'He carefully put one end of a thin glass tube into the dark center of the flame.'],
      ['해설', 'White vapor flowed out through the tube. When he held a light to the other end, a new flame appeared there.'],
      ['학생', 'What came out of the middle of a flame can burn again!'],
      ['패러데이', 'The dark part of the flame holds candle vapor that has not burned yet. It has not met the air.'],
      ['패러데이', 'Now I will pass a sheet of paper quickly across the middle of the flame.'],
      ['해설', 'When he pulled the paper out, its center was almost clean. It was scorched only in the shape of a ring.'],
      ['학생', 'So the center didn’t burn. Only the outer ring was hot.'],
      ['패러데이', 'Right. It burns most strongly at the outside, where it meets the air. Burning always needs air.'],
      ['해설', 'Faraday put a glass cover over a candle. The flame burned well at first, then grew dim and went out.'],
      ['학생', 'The air inside the cover must have been used up.'],
      ['패러데이', 'If no fresh air comes in, a fire cannot burn. What part of the air is used, we will find out later.'],
      ['학생', 'Sir, then why does a candle shine so brightly?'],
      ['패러데이', 'The secret is in tiny solid particles floating in the flame.'],
      ['해설', 'Faraday lit gunpowder mixed with iron filings. The sparks of burning iron were much brighter than the burning powder.'],
      ['패러데이', 'Solid particles in a flame glow as they heat up. A flame of gas alone is very hot but not very bright.'],
      ['패러데이', 'In a candle, those particles are carbon, or soot. They glow for a moment before they burn away.'],
      ['학생', 'Soot? You mean the black powder in chimneys?'],
      ['패러데이', 'Yes. Hold something cold in a candle flame and it turns black. That is carbon that did not get to burn.'],
      ['해설', 'Then Faraday showed a large, waving flame that poured out black smoke. It was a flame without enough air.'],
      ['패러데이', 'With plenty of air, all the carbon burns and there is no smoke. A candle burns cleanly because air flows in evenly.'],
      ['학생', 'But a candle gets smaller as it burns. Where does it go?'],
      ['패러데이', 'Nothing disappears. It only changes into other substances and spreads into the air.'],
      ['해설', 'Faraday held a cold, dry glass jar upside down over a candle. Soon the inside of the jar became cloudy.'],
      ['패러데이', 'What gathered in the jar, and what invisible gas is there? From next time, we will check them one by one.'],
      ['패러데이', 'Today we used hot flames and gunpowder. Don’t try this at home. Do it only in a lab with a teacher.'],
      ['해설', 'As a young man, Faraday joined the Royal Institution as assistant to the chemist Humphry Davy.'],
    ],
  },

  'tb-candle-3': {
    title: 'The Chemical History of a Candle, Part 3',
    names: { 해설: 'Narrator', 패러데이: 'Michael Faraday', 학생: 'Student' },
    outro: [
      'Why did Faraday stress that the water from a candle is the same as any other water?',
      'What properties of water do the cracked iron bottle and the crushed tin can show?',
      'Like frozen water pipes bursting in winter, can you find other effects of water’s properties around you?',
    ],
    lines: [
      ['해설', 'At the third lecture, Faraday returned to the mist that had formed inside the glass jar last time.'],
      ['패러데이', 'When a candle burns, something is made. Today we will catch one of those things and find out what it is.'],
      ['해설', 'He put a dish, made very cold with ice and salt, above a candle. Drops formed under the dish and dripped down.'],
      ['학생', 'Water comes from a candle? But fire and water seem like opposites.'],
      ['패러데이', 'It is easy to think so. But there is a way to check whether this is really water.'],
      ['해설', 'Faraday dropped a piece of a metal called potassium into the liquid. It burst into flame, just as it does on water.'],
      ['패러데이', 'Potassium reacts violently with water like this. It is very dangerous, so never handle it outside a lab.'],
      ['패러데이', 'This water is exactly like water from a river, the rain, or the sea. Wherever it comes from, water is the same.'],
      ['학생', 'So burning a candle makes water, and lighting a lamp makes water too?'],
      ['패러데이', 'Yes. Burning oil or gas also makes water. That is why a cold window near a lamp gets foggy.'],
      ['학생', 'Then a candle is a little water factory!'],
      ['해설', 'Next, Faraday began to study water itself. Water can become ice, and it can become steam.'],
      ['패러데이', 'Water grows larger when it freezes. That is why ice floats. Most substances do not behave like this.'],
      ['해설', 'He filled a thick iron bottle with water, closed it tightly, and set it in a mixture of ice and salt.'],
      ['해설', 'Some time later, with a dull crack, the iron bottle split. Surprised voices rose from the audience.'],
      ['학생', 'The iron lost to the ice! That is why water pipes burst in winter.'],
      ['패러데이', 'Exactly. Water that seeps into cracks in rocks can split the rocks when it freezes.'],
      ['해설', 'This time he boiled a little water in a tin can. When steam filled the can, he closed it and poured cold water over it.'],
      ['해설', 'The can crumpled and caved in. As the steam cooled back into water, the inside became almost empty.'],
      ['패러데이', 'The inside could not hold back the push of the air outside. Steam shrinks to a tiny bit of water when it cools.'],
      ['학생', 'Then where did the water in the candle come from? There was no water inside the candle.'],
      ['패러데이', 'Right. No water was hiding in the candle. Part of the candle met something in the air, and new water was made.'],
      ['패러데이', 'What is water made of? If we could split water, we would know why a candle makes it.'],
      ['학생', 'Split water? I can’t even imagine it.'],
      ['패러데이', 'I will show you next time. For today, remember one thing. A burning candle makes water.'],
      ['패러데이', 'Also, freezing or boiling water in a tightly closed container is dangerous. It can burst. Don’t copy this carelessly.'],
      ['해설', 'After the lecture, the audience stared for a long time at the foggy jar and the cracked iron bottle.'],
      ['해설', 'These lectures were published as a book in 1861 under the title The Chemical History of a Candle.'],
    ],
  },

  'tb-candle-4': {
    title: 'The Chemical History of a Candle, Part 4',
    names: { 해설: 'Narrator', 패러데이: 'Michael Faraday', 학생: 'Student' },
    outro: [
      'Why did Faraday split water in several ways and then put it back together?',
      'How do the experiment that split water and the one that burned hydrogen work as a pair to support his conclusion?',
      'Today people try to use hydrogen as a fuel. What possibilities and dangers can you think of?',
    ],
    lines: [
      ['해설', 'At the fourth lecture, Faraday said he would split water, just as he had promised.'],
      ['패러데이', 'Last time, the water we saw came from a burning candle. Now let us find out what that water is made of.'],
      ['해설', 'He heated an iron tube full of iron filings until it glowed red. Then he passed steam through it.'],
      ['해설', 'The gas from the far end was collected in a jar held upside down in water. The water was pushed out as gas filled it.'],
      ['패러데이', 'One part of the steam joined with the iron and stayed. The rest came out as a gas. We call it hydrogen.'],
      ['학생', 'What does the name hydrogen mean?'],
      ['패러데이', 'Hydrogen means the thing that makes water. You will soon see why it got that name.'],
      ['해설', 'Faraday also showed an easier way to get hydrogen, by pouring weak acid over pieces of zinc.'],
      ['해설', 'He blew soap bubbles filled with hydrogen, and they floated up toward the ceiling.'],
      ['패러데이', 'Hydrogen is the lightest substance of all. It is much lighter than air.'],
      ['해설', 'Then he lit the hydrogen coming out of a tube. It burned quietly with a faint, pale flame.'],
      ['패러데이', 'Shall we hold cold glass over this flame? Watch what forms on it.'],
      ['학생', 'Water drops! Just like the ones over the candle.'],
      ['패러데이', 'Yes. Burning hydrogen makes water. The water from a candle also comes from the hydrogen in the candle burning.'],
      ['학생', 'Then what in the air does hydrogen join with?'],
      ['패러데이', 'To find out, we must split water another way. This time, we will borrow the power of electricity.'],
      ['해설', 'Faraday connected a large voltaic battery. Tiny bubbles rose steadily from two platinum plates in the water.'],
      ['패러데이', 'Hydrogen comes from one side and another gas from the other. There is about twice as much hydrogen.'],
      ['해설', 'He put a stick with only a glowing tip into the other gas. The stick burst back into bright flame.'],
      ['패러데이', 'This gas is oxygen. It does not burn by itself, but it helps other things burn very strongly.'],
      ['학생', 'So water is made of hydrogen and oxygen!'],
      ['패러데이', 'Yes. Then if we join the two again, we should get water back. Let us check.'],
      ['해설', 'He put a little of the two gases in a thick glass tube and sent an electric spark through it. With a bang, the gases vanished.'],
      ['학생', 'The gases disappeared! Where did they go?'],
      ['패러데이', 'They became water. There is too little to see easily. Water is hydrogen and oxygen joined together.'],
      ['패러데이', 'A mixture of hydrogen and oxygen explodes loudly when it meets fire. Only experts should do this experiment.'],
      ['패러데이', 'Then where does a candle get its oxygen? Next time, we will study the air around us.'],
      ['해설', 'Faraday found the laws of electrolysis, and he helped spread words like electrode and electrolyte.'],
    ],
  },

  'tb-candle-5': {
    title: 'The Chemical History of a Candle, Part 5',
    names: { 해설: 'Narrator', 패러데이: 'Michael Faraday', 학생: 'Student' },
    outro: [
      'Why did Faraday say it is lucky that air is not made only of oxygen?',
      'What does the nitrogen experiment, where the candle went out, show about nitrogen’s nature and uses?',
      'Have you ever felt the power of invisible air in your daily life?',
    ],
    lines: [
      ['해설', 'At the fifth lecture, Faraday began with the oxygen he had taken out of water last time.'],
      ['패러데이', 'A candle burns very brightly and strongly in oxygen. Then why doesn’t it burn as strongly in air?'],
      ['해설', 'He put a candle into a jar of oxygen and another into a jar of air. The candle in oxygen blazed brilliantly.'],
      ['학생', 'The one in oxygen is much brighter. Is there only a little oxygen in air?'],
      ['패러데이', 'There is oxygen in air. But most of the air is another gas.'],
      ['패러데이', 'If you divide air into five parts, about one part is oxygen. Most of the rest is a gas called nitrogen.'],
      ['해설', 'Faraday put a burning candle into a jar of nitrogen. The flame went out at once.'],
      ['학생', 'Nitrogen puts out fire. So is it a useless gas?'],
      ['패러데이', 'Not at all. Nitrogen has no smell or taste, and it hardly reacts with anything. That is what makes it so precious.'],
      ['패러데이', 'If air were all oxygen, even the iron grate of a fireplace would burn. Nitrogen thins the oxygen and keeps fire under control.'],
      ['학생', 'So thanks to nitrogen, fires burn just right.'],
      ['해설', 'Next, Faraday showed that air has weight. When he pumped more air into a jar hanging from a scale, the scale tipped.'],
      ['패러데이', 'We live as if air were nothing, but air is truly a substance with weight.'],
      ['학생', 'Then we could weigh the air in this whole hall.'],
      ['패러데이', 'Yes. And the weight of all the air piled high in the sky is pressing down on all of us.'],
      ['학생', 'Then why don’t we get squashed flat?'],
      ['패러데이', 'Because air pushes evenly from every side, not just from above. Our bodies push back from inside with the same force.'],
      ['해설', 'Faraday put his palm on top of a glass jar and pumped out the air. His hand stuck tight and would not come off.'],
      ['해설', 'Then he fitted two metal half-spheres together and pumped out the air inside. Pulling from both sides could not easily separate them.'],
      ['학생', 'I thought air was nothing, but it has such strong force!'],
      ['패러데이', 'Air also shrinks when squeezed and springs back when let go. That is why a toy pop-gun goes pop.'],
      ['패러데이', 'Now back to the candle. When a candle burns, it makes one more substance besides water.'],
      ['해설', 'He took out a jar of clear limewater. When he shook it with air from a burned candle, it turned milky white.'],
      ['학생', 'The water turned white! You only added air.'],
      ['패러데이', 'Ordinary air does not cloud it so fast. A gas made by the candle met the limewater and made a white powder.'],
      ['패러데이', 'What that gas is, and how it relates to our breath, I will tell you at the last lecture.'],
      ['패러데이', 'Where there is a lot of oxygen, fire can spread out of control. That is why you must never use fire near oxygen tanks.'],
      ['해설', 'Faraday never went to university. He taught himself science by reading books while working at a bookbinder’s shop.'],
    ],
  },

  'tb-candle-6': {
    title: 'The Chemical History of a Candle, Part 6',
    names: { 해설: 'Narrator', 패러데이: 'Michael Faraday', 학생: 'Student' },
    outro: [
      'Why did Faraday compare a candle with human life in his last lecture?',
      'How are a burning candle and the breathing of our bodies alike, and how are they different?',
      'Can you connect the science of the candle to today’s climate problems involving carbon dioxide?',
    ],
    lines: [
      ['해설', 'On the day of the sixth and last lecture, Faraday began with the gas that had clouded the limewater.'],
      ['패러데이', 'In those days it was called carbonic acid gas. Today we call it carbon dioxide. It forms when carbon in a candle joins with oxygen.'],
      ['학생', 'Carbon? You mean the soot that made the flame bright last time?'],
      ['패러데이', 'Exactly. When the glowing carbon in the flame burns completely, it becomes invisible carbon dioxide.'],
      ['해설', 'Faraday tipped a jar of carbon dioxide as if pouring water. The invisible gas flowed down, and a candle below went out.'],
      ['패러데이', 'Carbon dioxide is heavier than air. So it flows down like water and collects in low places.'],
      ['학생', 'Then what happens if we burn a lump of carbon in oxygen?'],
      ['해설', 'He put a piece of red-hot charcoal into a jar of oxygen. It burned brightly with sparks and almost completely disappeared.'],
      ['패러데이', 'The charcoal did not vanish. It met the oxygen and became carbon dioxide, which is still in the jar.'],
      ['학생', 'Sir, does anything besides candles make carbon dioxide?'],
      ['패러데이', 'Yes. You do. Every time we breathe, something similar happens inside our bodies.'],
      ['해설', 'Faraday put a tube into a jar of limewater and asked a student to breathe slowly into it.'],
      ['학생', 'I breathed into it, and the limewater turned milky!'],
      ['패러데이', 'Carbon from our food joins with the oxygen we breathe in. We breathe out the carbon dioxide that forms.'],
      ['패러데이', 'A candle burning in air and our breathing are amazingly alike. But in the body it happens slowly, without flame.'],
      ['학생', 'Then a person is a candle that burns very slowly.'],
      ['패러데이', 'A fine way to put it. That is also why our bodies stay warm.'],
      ['학생', 'But if people, animals, and every fire give off carbon dioxide, won’t the air fill up with it?'],
      ['패러데이', 'Plants ease that worry. They take in carbon dioxide through their leaves and use the carbon to grow.'],
      ['패러데이', 'What is harmful to us is food for plants. In this way, living things depend on each other.'],
      ['패러데이', 'It is also lucky that carbon burns into a gas. If solid waste piled up, a fire would soon choke and die.'],
      ['패러데이', 'Small spaces where carbon dioxide collects are dangerous. Burning charcoal where there is no fresh air can kill.'],
      ['해설', 'Ending his six lectures, Faraday spoke his last words to the audience.'],
      ['패러데이', 'I hope your lives may be like a candle. May you shine as lights to those around you.'],
      ['패러데이', 'And in all you do, may you do your duty to others honestly and well, and so be worthy of the candle’s beauty.'],
      ['학생', 'I never knew one small candle held so many stories.'],
      ['해설', 'The candle in the hall was still burning quietly. The audience looked at its light with new eyes.'],
      ['해설', 'The Royal Institution Christmas Lectures, which Faraday started in 1825, later became a long tradition.'],
    ],
  },
};
