// 청소년 영어 원고 (중학생 이상). 키 = stories/teen-ch.js 의 이야기 id.
// 「초한지」(원전: 사마천 『사기』, 명대 소설 『서한연의』, 퍼블릭 도메인)를 한국어 각색의 흐름대로 쉬운 영어로 새로 씀.
// 인물·지명은 중국어 병음으로, 고사성어는 병음으로 쓰고 짧게 풀이.
export default {
  'ch-01': {
    title: 'The Chu-Han Contention, Part 1',
    names: { 해설: 'Narrator', 조고: 'Zhao Gao', 이사: 'Li Si', 진승: 'Chen Sheng', 오광: 'Wu Guang' },
    outro: [
      'Zhao Gao and Li Si, two men the First Emperor trusted, shook the whole empire. Why must a leader choose people carefully?',
      'When Chen Sheng spoke of swallows and swans, what did he compare himself to, and what did he mean?',
      'When others think my dream is too small, how can I hold on to it?',
    ],
    lines: [
      ['해설', 'In 221 BC, King Zheng of Qin defeated six kingdoms, one by one, and united China for the first time.'],
      ['해설', 'The title of king was not enough for him. He called himself the First Emperor.'],
      ['해설', 'He made one writing system, one kind of money, and one set of measures. But his laws were harsh.'],
      ['해설', 'Countless people were dragged far from home to build walls, palaces, and the emperor’s own tomb.'],
      ['해설', 'In 210 BC, while touring his empire, the First Emperor fell ill on the road and died.'],
      ['해설', 'Before he died, he wrote to his eldest son, Fusu, telling him to come to the capital for the funeral.'],
      ['해설', 'But the letter was in the hands of the eunuch Zhao Gao. He secretly visited the chancellor, Li Si.'],
      ['조고', 'Chancellor, if Prince Fusu becomes emperor, General Meng Tian will stand beside him. Where will that leave you?'],
      ['이사', 'You speak of ruining the nation. How can a servant overturn the emperor’s will?'],
      ['조고', 'The youngest prince, Huhai, is my own student. Join us, and your family will stay rich for generations.'],
      ['해설', 'Li Si hesitated for a long time, but at last he nodded. Together they changed the will and made Huhai heir.'],
      ['해설', 'A false order was sent to Fusu, telling him to take his own life. Sadly, he obeyed.'],
      ['해설', 'The emperor’s death was kept secret. Salted fish were even loaded on the carts to cover the smell.'],
      ['해설', 'Huhai became the Second Emperor, but Zhao Gao held the real power, and the people suffered even more.'],
      ['해설', 'The next year, nine hundred farmers marching north to guard the border were stopped by heavy rain.'],
      ['해설', 'The roads were cut, and they were already late. Under Qin law, being late meant death for all.'],
      ['해설', 'Two of their leaders, Chen Sheng and Wu Guang, put their heads together in secret.'],
      ['진승', 'If we run, we die. If we rebel and fail, we die. Why not die for a great cause?'],
      ['오광', 'Agreed. But to win the men’s hearts, we need a sign that Heaven is on our side.'],
      ['해설', 'They wrote, Chen Sheng will be king, in red on a piece of silk and hid it inside a fish.'],
      ['해설', 'The soldiers bought the fish, cut it open, and whispered about the words. That night a fire flickered in the woods.'],
      ['오광', 'Great Chu will rise again! Chen Sheng will be king!'],
      ['해설', 'It was Wu Guang, crying out like a fox. By morning, the soldiers looked at Chen Sheng with new eyes.'],
      ['해설', 'As a young man, Chen Sheng had been a hired farmhand. When he talked of riches, his friends laughed at him.'],
      ['진승', 'Ah, how can swallows and sparrows understand the dreams of a swan?'],
      ['해설', 'Finally, Chen Sheng and Wu Guang killed the two officers guarding them and stood before the men.'],
      ['진승', 'Are kings, lords, generals, and ministers born from a special seed? No!'],
      ['해설', 'The soldiers roared in reply. They cut trees for weapons and raised tall poles as flags.'],
      ['해설', 'They named their new state Zhang Chu, and their numbers quickly grew to tens of thousands.'],
      ['해설', 'Chen Sheng’s uprising did not last long. But the fire he started soon spread all over the land.'],
      ['해설', 'The saying about swallows and swans comes from the chapter on Chen She in the Records of the Grand Historian.'],
    ],
  },

  'ch-02': {
    title: 'The Chu-Han Contention, Part 2',
    names: { 해설: 'Narrator', 항우: 'Xiang Yu', 유방: 'Liu Bang', 범증: 'Fan Zeng', 항량: 'Xiang Liang', 여공: 'Lord Lü' },
    outro: [
      'Xiang Liang listened to Fan Zeng, a seventy-year-old adviser. What does a leader gain from an experienced adviser?',
      'Xiang Yu said he would take the emperor’s place, while Liu Bang said a real man should be like that. What do these words show?',
      'Am I closer to someone who leads with strength, or someone who brings people together?',
    ],
    lines: [
      ['해설', 'News of Chen Sheng’s revolt spread fast. In the lands of the six fallen kingdoms, rebels rose against Qin.'],
      ['해설', 'Among them were two men who would later fight for the whole empire: Xiang Yu and Liu Bang.'],
      ['해설', 'Xiang Yu was the grandson of a famous Chu general. He was raised by his uncle, Xiang Liang.'],
      ['해설', 'He was very tall and so strong that he could lift a heavy bronze cauldron alone.'],
      ['해설', 'As a boy, he quit learning to write, and then quit learning the sword. When his uncle scolded him, he said this.'],
      ['항우', 'Writing is only for signing my name. A sword fights only one man. I want to learn to fight ten thousand.'],
      ['해설', 'Xiang Liang happily taught him the art of war. But once Xiang Yu grasped the basics, he stopped studying.'],
      ['해설', 'One day the First Emperor’s parade passed by. Watching it, Xiang Yu suddenly spoke.'],
      ['항우', 'That man’s place, I could take it from him.'],
      ['항량', 'Hush! Watch your tongue! If anyone hears that, our whole family will die.'],
      ['해설', 'Xiang Liang silenced his nephew, but secretly he admired the boy’s boldness.'],
      ['해설', 'In the year of Chen Sheng’s revolt, Xiang Liang and Xiang Yu raised an army of eight thousand fine soldiers.'],
      ['해설', 'Meanwhile, in the county of Pei, lived Liu Bang, a village officer who loved wine and people more than work.'],
      ['해설', 'Once, while doing labor in the capital, he had also seen the emperor pass. He let out a long sigh.'],
      ['유방', 'Ah, this is how a real man should live!'],
      ['해설', 'Liu Bang was generous and loved to give, so people always gathered around him.'],
      ['해설', 'Once he came empty-handed to Lord Lü’s feast. Yet he boldly announced a gift of ten thousand coins.'],
      ['해설', 'Surprised, Lord Lü came out to greet him. After one look at his face, he gave Liu Bang the best seat.'],
      ['여공', 'I have read faces since I was young, but I have never seen one like yours. Please marry my daughter.'],
      ['해설', 'That daughter would later become Empress Lü of the Han dynasty.'],
      ['해설', 'One day, Liu Bang was leading workers to a building site, but they kept running away on the road.'],
      ['해설', 'He would be punished anyway when he arrived. So one night he untied the workers who were left.'],
      ['유방', 'Go, all of you. I will disappear somewhere, too.'],
      ['해설', 'Moved by his kindness, about ten young men stayed and followed him.'],
      ['해설', 'When the revolt began, the people of Pei made Liu Bang their leader. They called him the Lord of Pei.'],
      ['해설', 'After Chen Sheng fell, the rebels gathered around Xiang Liang. Then a seventy-year-old man, Fan Zeng, came to him.'],
      ['범증', 'Chu fell most unjustly of all six kingdoms. People say that even with three homes left, Chu will destroy Qin.'],
      ['범증', 'Find a descendant of the Chu kings and make him king. Then the people’s hearts will come to you.'],
      ['해설', 'Xiang Liang found the old king’s grandson, who was herding sheep, and made him King Huai of Chu.'],
      ['해설', 'Liu Bang also joined Xiang Liang. The fierce Xiang Yu and the generous Liu Bang now stood under one flag.'],
      ['해설', 'Both men’s words about the First Emperor are recorded in the Records of the Grand Historian.'],
    ],
  },

  'ch-03': {
    title: 'The Chu-Han Contention, Part 3',
    names: { 해설: 'Narrator', 항우: 'Xiang Yu', 범증: 'Fan Zeng', 송의: 'Song Yi', 영포: 'Ying Bu' },
    outro: [
      'Xiang Yu removed the slow Song Yi and took command himself. Was that a wise decision or a dangerous one?',
      'Sinking the boats and watching from the walls both come from one battle. How are these two attitudes different?',
      'Have I ever given everything with no way back? What pushed me forward then?',
    ],
    lines: [
      ['해설', 'After many victories over Qin, Xiang Liang began to look down on his enemy.'],
      ['해설', 'Then the Qin general Zhang Han attacked him by surprise. Xiang Liang was badly defeated and killed.'],
      ['해설', 'The proud Qin army marched north into Zhao and surrounded the city of Julu.'],
      ['해설', 'King Huai sent an army to save Zhao. Song Yi was the commander, with Xiang Yu and Fan Zeng under him.'],
      ['해설', 'But when Song Yi reached Anyang, he did not move his army for forty-six days.'],
      ['항우', 'Zhao is dying! How long will we sit here? We must cross the river and strike now!'],
      ['송의', 'Let Qin and Zhao wear each other out. Then we will strike. That is the best plan.'],
      ['송의', 'In armor with a spear, I am no match for you. But in making plans, you are no match for me.'],
      ['해설', 'Song Yi held a great feast for his son. Meanwhile, his soldiers were starving in the cold rain.'],
      ['해설', 'The next morning, Xiang Yu walked into Song Yi’s tent, killed him, and faced the army.'],
      ['항우', 'Song Yi plotted to betray Chu. By the king’s order, I have punished him!'],
      ['해설', 'No general dared to oppose him, and King Huai had to make Xiang Yu the new commander.'],
      ['해설', 'Xiang Yu first sent Ying Bu across the river with twenty thousand men. Then the whole army crossed.'],
      ['영포', 'General, everyone is across. Where shall we tie the boats?'],
      ['항우', 'No need to tie them. Sink every boat. Smash every cooking pot!'],
      ['항우', 'Burn the tents, too. Carry food for three days only. There is no way back, only the way to victory!'],
      ['해설', 'The soldiers held their breath. With no place to retreat, their fear turned into fierce courage.'],
      ['범증', 'General, look at their eyes. The fate of Chu depends on this battle.'],
      ['해설', 'At Julu, the Chu army fought the Qin army nine times.'],
      ['해설', 'Each Chu soldier fought like ten men, and their battle cries shook the sky.'],
      ['해설', 'Other rebel armies were camped nearby, but none dared to join. They only watched from their walls.'],
      ['해설', 'From this came the saying zuo bi shang guan, watching from the walls while others fight.'],
      ['해설', 'At last the Qin general Wang Li was captured, and the army around Julu fell apart.'],
      ['해설', 'Afterward, Xiang Yu called in the other generals. They came in on their knees, and no one dared to look up.'],
      ['영포', 'Now every rebel army in the land stands under your flag, General.'],
      ['항우', 'All the way to Xianyang, the heart of Qin, no one will stand in my way.'],
      ['해설', 'Soon Zhang Han himself surrendered, and Xiang Yu’s name made the whole land tremble.'],
      ['해설', 'But at Xin’an, Xiang Yu had over two hundred thousand surrendered Qin soldiers killed.'],
      ['해설', 'This left deep hatred in the hearts of the Qin people and later became a heavy burden for him.'],
      ['해설', 'The saying po fu chen zhou, break the pots and sink the boats, comes from the record of this battle.'],
    ],
  },

  'ch-04': {
    title: 'The Chu-Han Contention, Part 4',
    names: { 해설: 'Narrator', 유방: 'Liu Bang', 장량: 'Zhang Liang', 번쾌: 'Fan Kuai', 소하: 'Xiao He', 노인: 'Old Man' },
    outro: [
      'While others grabbed treasure, Xiao He took the records. What kind of person can see what truly matters?',
      'Honest advice is hard to hear. What happened because Liu Bang accepted it?',
      'If my class or club could keep only three rules, which three would I choose?',
    ],
    lines: [
      ['해설', 'While Xiang Yu fought the main Qin army, Liu Bang took the western road toward Guanzhong, the heart of Qin.'],
      ['해설', 'Before they left, King Huai made a promise. Whoever entered Guanzhong first would become its king.'],
      ['해설', 'Beside Liu Bang was Zhang Liang. His family had served as ministers of the old state of Han.'],
      ['해설', 'Once he had hired a strong man to smash the First Emperor’s carriage with an iron club. But they hit the wrong one.'],
      ['장량', 'My lord, instead of breaking every city, persuade the Qin generals to surrender. We will move much faster.'],
      ['해설', 'Liu Bang followed this advice and pushed forward until he reached Bashang, near the capital.'],
      ['해설', 'Meanwhile, the Qin court was falling apart. Zhao Gao removed the Second Emperor, then was killed by the new ruler, Ziying.'],
      ['해설', 'Ziying came out with a cord around his neck, riding a white horse cart, and surrendered the imperial seal.'],
      ['해설', 'Some generals wanted to kill Ziying, but Liu Bang shook his head.'],
      ['유방', 'King Huai sent me because I am merciful. Harming a man who has already surrendered brings bad luck.'],
      ['해설', 'Inside the palace, the beautiful rooms, treasures, and many palace ladies caught Liu Bang’s eye.'],
      ['유방', 'So this is the palace of the man who ruled the world. I think I will stay here a few days.'],
      ['번쾌', 'My lord, do you want the whole world, or do you want to be a rich old man? This luxury destroyed Qin!'],
      ['해설', 'Liu Bang pretended not to hear. Then Zhang Liang quietly stepped forward.'],
      ['장량', 'Qin was cruel, and that is why you are here. If you enjoy its pleasures now, how are you different from Qin?'],
      ['장량', 'Honest words hurt the ear but help your actions. Good medicine tastes bitter but cures the sickness.'],
      ['해설', 'Liu Bang sealed the treasure rooms, left the palace, and took his army back to Bashang.'],
      ['해설', 'While everyone rushed for gold, Xiao He went alone to the government office and collected laws, maps, and records.'],
      ['소하', 'Treasure disappears once it is spent. But these papers show the roads, the people, and how they live.'],
      ['해설', 'Liu Bang called together the elders and leaders of the towns in Guanzhong.'],
      ['유방', 'You have suffered under the cruel laws of Qin. Criticize the state, and your whole family was punished.'],
      ['유방', 'Now I promise you only three laws. First, whoever kills a person will pay with his life.'],
      ['유방', 'Second and third, whoever hurts others or steals will be punished for it. All the other Qin laws are gone.'],
      ['노인', 'Only three laws! At last we can breathe again!'],
      ['해설', 'People rushed to bring cattle, sheep, wine, and food, but Liu Bang politely refused them.'],
      ['유방', 'Our storehouses have plenty of grain. I do not want to be a burden to you.'],
      ['해설', 'The people of Guanzhong even began to worry that Liu Bang might not become their king.'],
      ['해설', 'But in the east, Xiang Yu was coming toward the pass with an army of four hundred thousand.'],
      ['해설', 'The story of the three laws, yue fa san zhang, is recorded in the Basic Annals of Emperor Gaozu.'],
    ],
  },

  'ch-05': {
    title: 'The Chu-Han Contention, Part 5',
    names: { 해설: 'Narrator', 항우: 'Xiang Yu', 유방: 'Liu Bang', 장량: 'Zhang Liang', 범증: 'Fan Zeng', 번쾌: 'Fan Kuai' },
    outro: [
      'Xiang Yu hesitated at the key moment, while Liu Bang humbled himself and survived. What was the difference between these two leaders?',
      'A sword dance with a hidden aim means a show that hides a real purpose. Where could we use this saying today?',
      'When I am misunderstood, do I fight back with emotion, or do I calmly explain?',
    ],
    lines: [
      ['해설', 'When Xiang Yu reached the pass, Liu Bang’s soldiers were guarding it. In fury, Xiang Yu broke through.'],
      ['해설', 'Xiang Yu camped at Hongmen with four hundred thousand men. Liu Bang had only one hundred thousand.'],
      ['범증', 'The Lord of Pei once loved money and women. Here he touched nothing. That shows his goals are not small.'],
      ['범증', 'They say clouds shaped like dragons and tigers hang over his camp. That is the sign of an emperor. Strike now!'],
      ['해설', 'That night, Xiang Yu’s uncle, Xiang Bo, secretly rode to see Zhang Liang, who had once saved his life.'],
      ['해설', 'Xiang Bo begged him to flee, but Zhang Liang would not leave his lord. He told Liu Bang everything.'],
      ['장량', 'My lord, can your army stand against Xiang Yu’s?'],
      ['유방', 'Not a chance. What should I do?'],
      ['장량', 'Tell Xiang Bo yourself that you have no plan to betray Xiang Yu.'],
      ['해설', 'Liu Bang treated Xiang Bo like an elder brother, offered him wine, and even promised a marriage between their children.'],
      ['유방', 'I touched nothing here and waited for the general. I guarded the pass only to stop bandits.'],
      ['해설', 'Xiang Bo went back and calmed Xiang Yu. The next morning, Liu Bang came to Hongmen with only about a hundred riders.'],
      ['유방', 'I only fought Qin side by side with you. Small-minded men have tried to drive us apart.'],
      ['항우', 'It was your own officer, Cao Wushang, who said it. Otherwise, why would I be angry?'],
      ['해설', 'Xiang Yu held a feast. Three times, Fan Zeng raised the jade ring at his belt as a signal.'],
      ['해설', 'It meant, act now. But Xiang Yu only drank in silence. So Fan Zeng went out and called Xiang Zhuang, Xiang Yu’s cousin.'],
      ['범증', 'Go in and perform a sword dance for fun. When you see a chance, strike the Lord of Pei.'],
      ['해설', 'As Xiang Zhuang danced, Xiang Bo also drew his sword and danced, shielding Liu Bang with his own body.'],
      ['해설', 'Zhang Liang hurried out of the camp gate to find Fan Kuai.'],
      ['장량', 'Xiang Zhuang is doing a sword dance, but his aim is our lord.'],
      ['번쾌', 'This is urgent! Let me go in. I will live or die with my lord!'],
      ['해설', 'Fan Kuai pushed past the guards with his shield and burst into the tent. His hair stood on end with rage.'],
      ['항우', 'What a warrior! Give this man a big cup of wine.'],
      ['번쾌', 'I do not fear death, so why fear a cup of wine? My lord did great things, yet he gets suspicion, not reward.'],
      ['해설', 'Xiang Yu could not find an answer. A little later, Liu Bang slipped out, saying he needed the toilet.'],
      ['해설', 'Leaving his carriage behind, Liu Bang rode off alone. Fan Kuai and three others ran beside him back to Bashang.'],
      ['해설', 'Zhang Liang stayed behind. He gave a pair of white jade discs to Xiang Yu and a pair of jade cups to Fan Zeng.'],
      ['해설', 'Fan Zeng set the cups on the ground, drew his sword, and smashed them.'],
      ['범증', 'Bah! You cannot plan great things with a foolish boy! The man who takes his empire will be the Lord of Pei.'],
      ['해설', 'The saying about Xiang Zhuang’s sword dance, aimed at the Lord of Pei, comes from this feast at Hongmen.'],
    ],
  },

  'ch-06': {
    title: 'The Chu-Han Contention, Part 6',
    names: { 해설: 'Narrator', 한신: 'Han Xin', 장량: 'Zhang Liang', 유방: 'Liu Bang', 소하: 'Xiao He', 백정: 'Butcher', 표모: 'Washerwoman' },
    outro: [
      'What did Xiao He see in Han Xin when everyone else ignored him, and why did he push for such a high position?',
      'Han Xin crawled between a bully’s legs. Was he a coward, or did he have a greater kind of courage?',
      'Have I ever swallowed my pride for a bigger goal?',
    ],
    lines: [
      ['해설', 'After the feast, Xiang Yu entered the capital, executed Ziying, and set the palace on fire. It burned for three months.'],
      ['해설', 'Xiang Yu became the Hegemon-King of Western Chu. Breaking the promise, he gave Liu Bang the far, rough land of Hanzhong.'],
      ['해설', 'As Liu Bang, now King of Han, headed into the mountains, Zhang Liang came up with a plan.'],
      ['장량', 'Burn the wooden roads along the cliffs behind us. That will show Xiang Yu you never plan to return.'],
      ['해설', 'At that time, there was a young man in the Han camp named Han Xin.'],
      ['해설', 'Han Xin was poor. At home he lived on other people’s food, and people looked down on him.'],
      ['해설', 'One day, as he fished by a river, an old washerwoman saw him starving and shared her food for weeks.'],
      ['한신', 'One day I will repay this kindness many times over.'],
      ['표모', 'I fed you because I felt sorry for a man who cannot feed himself. I want nothing back.'],
      ['해설', 'Another day in the market, a young butcher blocked the way of Han Xin, who always carried a sword.'],
      ['백정', 'You are big and you carry a sword, but you are a coward inside. If you are brave, stab me.'],
      ['백정', 'If you cannot, crawl between my legs!'],
      ['해설', 'Han Xin stared at him for a long time. Then he got down and crawled between the butcher’s legs.'],
      ['해설', 'The whole market laughed at him. But Han Xin would not risk his great dream for a moment of anger.'],
      ['해설', 'Han Xin had first served in Xiang Yu’s army, but none of his plans were ever used.'],
      ['해설', 'Even after joining Han, he held only a low rank. The one man who noticed him was the chancellor, Xiao He.'],
      ['해설', 'When the army reached Nanzheng, homesick officers ran away one after another. Han Xin left too.'],
      ['해설', 'Hearing this, Xiao He jumped on a horse and chased Han Xin without even telling the king.'],
      ['해설', 'Liu Bang heard that his chancellor had run away and felt he had lost both arms. A day or two later, Xiao He returned.'],
      ['유방', 'Dozens of officers ran away and you chased none of them. Now you chased Han Xin? Do not lie to me.'],
      ['소하', 'Ordinary officers are easy to find. But Han Xin has no equal in the whole country.'],
      ['소하', 'If you are happy ruling Hanzhong, you do not need him. But to win the empire, there is no one else.'],
      ['유방', 'Very well. For your sake, I will make him a general.'],
      ['소하', 'A general is not enough to keep him. Choose a good day, build an altar, and make him Grand General with full honors.'],
      ['해설', 'Every officer hoped to be chosen. When Han Xin climbed the altar, the whole army was stunned.'],
      ['한신', 'When Xiang Yu shouts, a thousand men fall down. But he cannot trust good generals, so his courage is only one man’s courage.'],
      ['한신', 'He weeps and shares food with sick soldiers. Yet he cannot bear to give rewards to those who earn them.'],
      ['유방', 'I am sorry I did not see your worth sooner.'],
      ['해설', 'The crawl between the legs and the man without equal both come from the biography of Han Xin.'],
    ],
  },

  'ch-07': {
    title: 'The Chu-Han Contention, Part 7',
    names: { 해설: 'Narrator', 한신: 'Han Xin', 장이: 'Zhang Er', 이좌거: 'Li Zuoche', 진여: 'Chen Yu' },
    outro: [
      'Han Xin freed the captured adviser Li Zuoche and treated him as a teacher. What does that show about a leader?',
      'Is fighting with your back to the river always a good plan? What was the real reason Han Xin’s plan worked?',
      'Have I ever left myself no way out before a test or contest? How did it turn out?',
    ],
    lines: [
      ['해설', 'While Liu Bang faced Xiang Yu, Han Xin conquered the northern states one by one.'],
      ['해설', 'After defeating Wei, Han Xin and Zhang Er led tens of thousands of soldiers toward Zhao.'],
      ['해설', 'To reach Zhao, they had to pass through a narrow mountain pass. Zhao boasted of an army of two hundred thousand.'],
      ['해설', 'Li Zuoche, a wise adviser of Zhao, offered a plan to the commander, Chen Yu.'],
      ['이좌거', 'In that pass, two carts cannot ride side by side. Their food wagons are sure to fall behind.'],
      ['이좌거', 'Give me thirty thousand men. I will cut their supply line, and within ten days, Han Xin will be ours.'],
      ['진여', 'A righteous army does not use tricks. If we avoid a tired enemy, the other lords will laugh at us.'],
      ['해설', 'When his spies brought him this news, Han Xin was delighted and marched close to the pass.'],
      ['해설', 'At midnight, he chose two thousand fast riders and gave each one a red Han flag.'],
      ['한신', 'Hide in the hills and watch their camp. When we run, the Zhao army will empty its camp to chase us.'],
      ['한신', 'Then rush in, pull down their flags, and put up our red ones.'],
      ['해설', 'Han Xin handed out only a light snack to his officers and said this.'],
      ['한신', 'Today, after we defeat Zhao, we will all eat a big meal together.'],
      ['장이', 'Yes, as you say.'],
      ['해설', 'Nobody believed him, but they answered politely anyway.'],
      ['해설', 'Han Xin sent ten thousand men ahead to set up camp with their backs to the river. The Zhao soldiers laughed.'],
      ['해설', 'At dawn, Han Xin marched out with drums and banners. The Zhao army poured out of its camp.'],
      ['해설', 'After a long fight, Han Xin and Zhang Er dropped their flags and drums. They fled to the riverside camp.'],
      ['진여', 'Han Xin is running! Everyone, go out and seize those flags and drums!'],
      ['해설', 'The Zhao army left its camp to chase them. But the Han soldiers, with the river behind them, fought to the death.'],
      ['해설', 'Meanwhile, the two thousand hidden riders rushed into the empty Zhao camp and raised two thousand red flags.'],
      ['해설', 'Seeing red flags over their own camp, the Zhao soldiers thought their king was captured, and they scattered.'],
      ['해설', 'Attacked from front and back, the Zhao army collapsed. Chen Yu was killed, and the King of Zhao was captured.'],
      ['장이', 'The books say to keep mountains behind you and water in front. But you won with a river behind you. How?'],
      ['한신', 'That is in the books too. Put soldiers where they must die, and they will find a way to live.'],
      ['한신', 'Our men were barely trained, like people from the market. With an easy way out, they would have run away.'],
      ['해설', 'Han Xin himself untied the captured Li Zuoche and asked him to be his teacher.'],
      ['이좌거', 'A defeated general should not talk of courage. But even a wise man makes one mistake in a thousand thoughts.'],
      ['이좌거', 'And even a fool gets one thing right in a thousand thoughts. So let me share my ideas.'],
      ['해설', 'The saying bei shui zhen, a camp with your back to the river, comes from the biography of Han Xin.'],
    ],
  },

  'ch-08': {
    title: 'The Chu-Han Contention, Part 8',
    names: { 해설: 'Narrator', 항우: 'Xiang Yu', 유방: 'Liu Bang', 장량: 'Zhang Liang', 범증: 'Fan Zeng', 한신: 'Han Xin' },
    outro: [
      'Xiang Yu doubted Fan Zeng and sent him away, while Liu Bang kept Han Xin’s loyalty. How did they treat talent differently?',
      'Zhang Liang said not to raise a tiger and urged Liu Bang to break the treaty. Was that smart strategy or a shameful choice?',
      'When a misunderstanding grows between friends or teammates, how can we choose trust instead of doubt?',
    ],
    lines: [
      ['해설', 'The war between Chu and Han went on for years. At one point, Xiang Yu trapped Liu Bang in the city of Xingyang.'],
      ['해설', 'Then Chen Ping, a Han adviser, made a plan to drive Xiang Yu and Fan Zeng apart.'],
      ['해설', 'When Xiang Yu’s messenger arrived, Han served a fine meal. Then they took it away, saying they expected Fan Zeng’s messenger.'],
      ['해설', 'Hearing this, Xiang Yu began to doubt Fan Zeng and slowly took away his power.'],
      ['범증', 'The fate of the empire is nearly decided. Do the rest yourself, Your Majesty. This old man will go home.'],
      ['해설', 'Before he even reached Pengcheng, Fan Zeng died of a sore on his back. Xiang Yu had lost his only adviser.'],
      ['해설', 'Later, the two armies faced each other across a deep valley. Each could clearly see the other’s camp.'],
      ['해설', 'Han had plenty of grain. But Chu grew hungry, because Peng Yue kept cutting its supply lines.'],
      ['해설', 'Growing impatient, Xiang Yu put Liu Bang’s captured father on a high chopping block and shouted.'],
      ['항우', 'Surrender now, or I will boil your father alive!'],
      ['유방', 'You and I swore to be brothers under King Huai. So my father is your father too.'],
      ['유방', 'If you must boil your own father, please send me a bowl of the soup.'],
      ['해설', 'Xiang Yu was furious, but his uncle Xiang Bo stopped him. Hurting the old man would only bring more hatred.'],
      ['해설', 'In the end, Xiang Yu spared Liu Bang’s father. As the standoff dragged on, he shouted across the valley.'],
      ['항우', 'The world has suffered for years because of us two. Let us fight one on one and end this!'],
      ['유방', 'I would rather fight with my wits than with my strength.'],
      ['해설', 'Liu Bang listed ten crimes of Xiang Yu. In anger, Xiang Yu had a hidden crossbow fired, and it hit Liu Bang’s chest.'],
      ['해설', 'Fighting the pain, Liu Bang grabbed his foot instead.'],
      ['유방', 'That rascal hit my toe!'],
      ['해설', 'He hid his wound so his soldiers would not panic. Zhang Liang helped him walk through the camp to calm the men.'],
      ['해설', 'Meanwhile, Han Xin had conquered Qi and become its king. An adviser urged him to split the empire three ways.'],
      ['한신', 'The King of Han gave me his carriage, his clothes, and his food. How could I betray such kindness?'],
      ['해설', 'At last the tired sides agreed on a border. Han took the west, Chu the east, and Liu Bang’s family was freed.'],
      ['해설', 'Xiang Yu turned his army east. Liu Bang was about to go west, but Zhang Liang stopped him.'],
      ['장량', 'Han now holds half the empire, and the lords follow us. Chu is exhausted and out of food.'],
      ['장량', 'If you let this chance go, it is like raising a tiger that will hurt you later. Chase them now.'],
      ['유방', 'Very well. Even if people say I broke my word, I will end this war here.'],
      ['해설', 'The saying yang hu yi huan, raising a tiger and inviting trouble, comes from the Basic Annals of Xiang Yu.'],
    ],
  },

  'ch-09': {
    title: 'The Chu-Han Contention, Part 9',
    names: { 해설: 'Narrator', 항우: 'Xiang Yu', 유방: 'Liu Bang', 장량: 'Zhang Liang', 한신: 'Han Xin', 우희: 'Lady Yu' },
    outro: [
      'After losing a battle, Liu Bang promised land to Han Xin and Peng Yue. What does that teach about moving talented people?',
      'Why can a plan that shakes people’s hearts, like the songs of Chu, sometimes be stronger than a sword?',
      'When I feel that no one is on my side, what can I lean on to keep going?',
    ],
    lines: [
      ['해설', 'Breaking the treaty, Liu Bang chased Xiang Yu east. But Han Xin and Peng Yue did not come, and Liu Bang lost badly.'],
      ['유방', 'The lords did not come when they promised. What should I do?'],
      ['장량', 'Chu will soon fall, but they do not know what land they will get. Promise to share the empire with them.'],
      ['해설', 'When Liu Bang promised them land, Han Xin and Peng Yue came at once. Great armies gathered from all sides.'],
      ['해설', 'Xiang Yu camped at Gaixia. His soldiers were few, his food was gone, and enemies surrounded him.'],
      ['한신', 'Fighting Xiang Yu head-on is hard. I will strike first and then pretend to fall back.'],
      ['해설', 'Han Xin led three hundred thousand men at the front. He clashed and pulled back, and the generals on both sides attacked.'],
      ['해설', 'Then Han Xin turned and struck again, and the Chu army was pushed back into its camp.'],
      ['해설', 'Later novels, like the Romance of the Western Han, describe what happened that night as Zhang Liang’s plan.'],
      ['장량', 'The Chu soldiers are tired of war. If they hear songs from home, their hearts will break before their swords.'],
      ['해설', 'That night, songs rose from the Han camps on every side. They were the songs of Chu.'],
      ['항우', 'Has Han already taken all of Chu? Why are there so many Chu people in their camps?'],
      ['해설', 'The novel says that, hearing the songs of home, Chu soldiers slipped away into the dark one by one.'],
      ['해설', 'Xiang Yu could not sleep. He rose and drank wine in his tent.'],
      ['해설', 'Beside him was Lady Yu, who always traveled with him, and his famous horse, Zhui.'],
      ['해설', 'Unable to hold back his feelings, Xiang Yu made up a song and sang it.'],
      ['항우', 'My strength could pull up mountains, my spirit covered the world. But the times are against me, and Zhui will not run.'],
      ['항우', 'If Zhui will not run, what can I do? Oh Yu, my Yu, what will become of you?'],
      ['해설', 'Xiang Yu sang it again and again, and Lady Yu answered him in song.'],
      ['우희', 'Your Majesty, I will stay by your side to the end. Only, please do not let your spirit break.'],
      ['해설', 'Tears ran down Xiang Yu’s cheeks. Everyone around him wept, and no one could look up.'],
      ['항우', 'Before this night ends, I will break through. If Heaven has not abandoned me, there will be a way.'],
      ['우희', 'Your path is my path. Do not hesitate.'],
      ['해설', 'That night, Xiang Yu mounted Zhui and broke out with about eight hundred riders, racing south.'],
      ['해설', 'Only after sunrise did the Han army realize that Xiang Yu had escaped.'],
      ['유방', 'Send five thousand riders after him. This time, he must not get away!'],
      ['한신', 'Few soldiers are left with Xiang Yu. The end is in sight.'],
      ['해설', 'The saying si mian chu ge, songs of Chu on all four sides, comes from this scene at Gaixia.'],
    ],
  },

  'ch-10': {
    title: 'The Chu-Han Contention, Part 10',
    names: { 해설: 'Narrator', 항우: 'Xiang Yu', 유방: 'Liu Bang', 장량: 'Zhang Liang', 한신: 'Han Xin', 정장: 'Ferryman' },
    outro: [
      'Liu Bang admitted he was not as good as his three helpers. Why did this attitude become his greatest strength?',
      'Xiang Yu blamed Heaven for his defeat. Was he right, or what did he miss as a leader?',
      'When I achieve something, how can I remember and share the credit with those who helped me?',
    ],
    lines: [
      ['해설', 'When Xiang Yu crossed the Huai River after escaping Gaixia, only about a hundred riders were still with him.'],
      ['해설', 'Lost on the road, he asked a farmer for directions. The farmer lied and told him to go left.'],
      ['해설', 'To the left was a great swamp. Meanwhile, the Han riders drew closer and closer.'],
      ['해설', 'By the time he reached Dongcheng, only twenty-eight riders were left. Thousands of Han riders were chasing them.'],
      ['항우', 'For eight years I have fought over seventy battles. I never lost once, and I won the whole land.'],
      ['항우', 'Today I am trapped because Heaven wants to destroy me, not because I cannot fight!'],
      ['해설', 'He split his riders into four groups and charged in all directions. The Han army made way before his fury.'],
      ['해설', 'When they gathered again after charge after charge, he had lost only two riders.'],
      ['해설', 'Xiang Yu rode east to the Wu River. Across it lay the land where he had first raised his army.'],
      ['정장', 'Your homeland is small, but it is a thousand li wide, with many people. It is enough to rule. Please get on the boat.'],
      ['정장', 'This is the only boat here. Even if the Han soldiers come, they cannot cross.'],
      ['항우', 'Heaven is destroying me. What good is crossing the river?'],
      ['항우', 'Eight thousand young men crossed this river with me, and not one returns. How could I face their parents?'],
      ['항우', 'For five years this horse has had no equal. I cannot bear to leave him, so I give him to you.'],
      ['해설', 'Xiang Yu got off his horse and fought his last battle on foot. Many Han soldiers fell back before him.'],
      ['해설', 'Then, among the chasing soldiers, he recognized the face of an old friend, Lü Matong.'],
      ['항우', 'I hear Han has offered a great reward for my head. I will give that honor to you.'],
      ['해설', 'With those words, Xiang Yu took his own life. It was the end of the Hegemon-King who had shaken the world.'],
      ['해설', 'Liu Bang buried Xiang Yu with the honors of a lord, wept for him, and left.'],
      ['해설', 'Then Liu Bang became emperor. It was the beginning of the Han dynasty, which would last over four hundred years.'],
      ['해설', 'One day, Emperor Liu Bang held a feast in the palace at Luoyang and asked his ministers a question.'],
      ['유방', 'Why do you think I won the empire, and Xiang Yu lost it?'],
      ['유방', 'Making plans in a tent that decide battles a thousand li away, I am not as good as Zhang Liang.'],
      ['유방', 'Running the country and keeping the army fed, I am behind Xiao He. Winning battles, I am behind Han Xin.'],
      ['유방', 'I knew how to use these three men, so I won. Xiang Yu had one, Fan Zeng, and could not even use him.'],
      ['장량', 'Your Majesty, seeing people’s worth and trusting them, that was your road to the empire.'],
      ['해설', 'But once peace came, the fates of the heroes split apart. Han Xin was suspected, arrested, and demoted.'],
      ['한신', 'When the quick rabbit dies, the hunting dog is cooked. When the enemy falls, the clever minister is thrown away.'],
      ['해설', 'And so the struggle between Chu and Han after the fall of Qin ended in victory for Han.'],
      ['해설', 'Liu Bang’s words about using three men are recorded in the Basic Annals of Emperor Gaozu.'],
    ],
  },
};
