// 청소년 영어 원고: 오만과 편견 1~10화 (stories/teen-pride.js). 문장은 자체 각색.
// lines 의 첫 칸은 한국어 이야기 cast 의 이름 그대로.
export default {
  'pp-01': {
    title: 'Pride and Prejudice, Part 1',
    names: { 해설: 'Narrator', 베넷부인: 'Mrs. Bennet', 베넷씨: 'Mr. Bennet', 빙리: 'Mr. Bingley', 제인: 'Jane', 다아시: 'Mr. Darcy', 엘리자베스: 'Elizabeth' },
    outro: [
      'What situation was hidden behind Mrs. Bennet’s hurry to marry off her daughters?',
      'Elizabeth laughed at Darcy’s insult instead of getting angry. What does this show about her?',
      'How far do you think you can trust your first impression of someone?',
    ],
    lines: [
      ['해설', 'In the early nineteenth century, the Bennet family lived in Longbourn, a village in Hertfordshire, England.'],
      ['해설', 'Mr. and Mrs. Bennet had five daughters: Jane, Elizabeth, Mary, Kitty, and Lydia.'],
      ['해설', 'Their house and land could only pass to a male heir. This was called an entail.'],
      ['해설', 'With no son, the estate would go to a distant male cousin when Mr. Bennet died.'],
      ['해설', 'So Mrs. Bennet’s greatest wish was to marry her daughters into rich families.'],
      ['베넷부인', 'My dear, a rich young man has taken Netherfield! Four or five thousand a year!'],
      ['베넷씨', 'So? Did he move here just to meet our girls?'],
      ['베넷부인', 'Don’t tease me! He might marry one of them, you know.'],
      ['해설', 'His name was Bingley. Mr. Bennet pretended not to care, but secretly visited him first.'],
      ['해설', 'Soon after, Bingley came to the ball at Meryton with his sisters and a friend.'],
      ['해설', 'The friend was Mr. Darcy, a gentleman with a large estate in Derbyshire and ten thousand a year.'],
      ['해설', 'At first everyone admired him, but soon they whispered that he was cold and proud.'],
      ['빙리', 'Miss Bennet, will you dance the next dance with me too?'],
      ['제인', 'With pleasure. I haven’t enjoyed a ball this much in a long time.'],
      ['해설', 'Bingley danced twice with Jane, the eldest daughter. The whole town watched them.'],
      ['해설', 'Darcy danced only with his own party and refused even to be introduced to anyone new.'],
      ['빙리', 'Darcy, don’t stand alone. Dance! Miss Bennet’s sister is sitting right there.'],
      ['다아시', 'She is tolerable, but not handsome enough to tempt me. I won’t bother with girls other men ignore.'],
      ['해설', 'Elizabeth, the second daughter, was sitting close by and heard every word. At home she was called Lizzy.'],
      ['엘리자베스', 'Oh dear, I am not good enough for such a fine gentleman. I shall never sleep again.'],
      ['해설', 'Instead of getting angry, she told the story to her friends as a joke.'],
      ['해설', 'At home, Mrs. Bennet could not stop praising Bingley and criticizing Darcy.'],
      ['베넷부인', 'That Darcy insulted our Lizzy! Don’t dance with him even if he asks you.'],
      ['해설', 'Late that night, Jane quietly shared her feelings with her sister.'],
      ['제인', 'Lizzy, Mr. Bingley is so kind and polite. I have never met anyone like him.'],
      ['엘리자베스', 'If you like him, so do I. You always find the good in everyone.'],
      ['해설', 'Elizabeth firmly decided in her heart that Darcy was a proud man.'],
      ['해설', 'A few days later, Jane got an invitation from Netherfield. Rain clouds were gathering in the sky.'],
      ['해설', 'Jane Austen published Pride and Prejudice in 1813.'],
    ],
  },

  'pp-02': {
    title: 'Pride and Prejudice, Part 2',
    names: { 해설: 'Narrator', 베넷부인: 'Mrs. Bennet', 캐럴라인: 'Caroline Bingley', 다아시: 'Mr. Darcy', 엘리자베스: 'Elizabeth', 빙리: 'Mr. Bingley', 제인: 'Jane' },
    outro: [
      'Why did Darcy try to control his feelings even though he was drawn to Elizabeth?',
      'Caroline and Darcy saw different things in the same muddy dress. What does that scene show?',
      'Do you think people are still judged by their family or background today?',
    ],
    lines: [
      ['해설', 'Last time, Bingley danced with Jane at the ball, and Darcy insulted Elizabeth.'],
      ['해설', 'A few days later, Bingley’s sisters invited Jane to dinner at Netherfield.'],
      ['베넷부인', 'No carriage. Go on horseback. If it rains, you will have to stay the night.'],
      ['해설', 'Just as her mother hoped, it poured. Soaked through, Jane caught a bad cold and fell ill.'],
      ['해설', 'Worried about her sister, Elizabeth walked alone for three miles along muddy roads to Netherfield.'],
      ['해설', 'Her skirt was splashed with mud. Bingley’s sisters stared at her with wide eyes.'],
      ['캐럴라인', 'Look at her skirt! Walking across the fields alone! How very country.'],
      ['해설', 'But Darcy did not notice the mud. He noticed her face, glowing from the fresh air.'],
      ['해설', 'Elizabeth stayed at Netherfield for several days to take care of Jane.'],
      ['해설', 'Every evening in the drawing room, there were books, letters, and conversations that were almost arguments.'],
      ['캐럴라인', 'A truly accomplished lady must know music, drawing, dancing, and foreign languages.'],
      ['다아시', 'And I would add that she must improve her mind by wide reading.'],
      ['엘리자베스', 'I am surprised you know any such ladies. I have never met a single one.'],
      ['해설', 'Darcy found himself thinking more and more about this young woman who dared to argue with him.'],
      ['엘리자베스', 'Mr. Darcy has no faults, I suppose? That is why he can laugh at others so freely.'],
      ['다아시', 'I have faults. My good opinion, once lost, is lost forever.'],
      ['엘리자베스', 'Then your fault is a tendency to hate everybody.'],
      ['다아시', 'And yours, I think, is to misunderstand people on purpose.'],
      ['해설', 'Caroline did not like the way Darcy kept looking at Elizabeth.'],
      ['캐럴라인', 'Think of her mother and relatives. I pity the man who marries into that family.'],
      ['해설', 'Darcy did not answer. He too felt the Bennet family was below his rank.'],
      ['해설', 'In those days, upper-class marriage joined two families, so rank and money were thought to matter.'],
      ['해설', 'The way Darcy and Caroline looked at others came from that way of thinking.'],
      ['해설', 'Darcy took control of his feelings. On the last day, he hardly spoke to Elizabeth at all.'],
      ['해설', 'When Jane was better, the sisters got ready to go back to Longbourn.'],
      ['빙리', 'Take care of yourself, Miss Bennet. I am going to give a ball soon. Please come.'],
      ['제인', 'Thank you so much for looking after me so kindly.'],
      ['해설', 'At home, Mr. Bennet was waiting for them, waving a letter from a stranger.'],
      ['해설', 'The novel’s first title was First Impressions. Austen began writing it in 1796.'],
    ],
  },

  'pp-03': {
    title: 'Pride and Prejudice, Part 3',
    names: { 해설: 'Narrator', 베넷씨: 'Mr. Bennet', 콜린스: 'Mr. Collins', 리디아: 'Lydia', 위컴: 'Mr. Wickham', 엘리자베스: 'Elizabeth', 제인: 'Jane' },
    outro: [
      'Why didn’t Elizabeth doubt anything Wickham said, even though she had just met him?',
      'Collins always talks about Lady Catherine. How does this habit show what kind of man he is?',
      'Why is it easier to believe bad rumors about someone we already dislike?',
    ],
    lines: [
      ['해설', 'Last time, Elizabeth stayed at Netherfield to look after Jane, and argued with Darcy.'],
      ['해설', 'The letter was from William Collins, the distant cousin who would inherit Longbourn after Mr. Bennet died.'],
      ['베넷씨', 'He wants to make peace over the inheritance. From his letter, he seems quite a funny fellow.'],
      ['해설', 'Collins was a clergyman at Hunsford in Kent. He never stopped praising the great lady who gave him the post.'],
      ['콜린스', 'Lady Catherine de Bourgh is so very kind, even to a humble man like me.'],
      ['콜린스', 'She told me to marry. So I have come to choose a wife from among your daughters.'],
      ['해설', 'First he chose Jane. When he heard she might soon be engaged, he quickly switched to Elizabeth.'],
      ['해설', 'At that time, soldiers were staying in Meryton, and the officers were very popular with the local girls.'],
      ['리디아', 'Look at the officers in their red coats! All of Meryton is sparkling!'],
      ['해설', 'One day, in town, the sisters met a handsome young man named Wickham who had just joined the regiment.'],
      ['해설', 'Just then, Darcy rode past. When Darcy and Wickham saw each other, both their faces changed color.'],
      ['해설', 'A few days later, at their aunt’s party, Wickham sat next to Elizabeth and began to talk.'],
      ['위컴', 'I am the son of the steward old Mr. Darcy trusted. I grew up in that house.'],
      ['위컴', 'The old gentleman promised to give me a position as a clergyman in the church.'],
      ['위컴', 'But when he died, Mr. Darcy gave that position to someone else.'],
      ['엘리자베스', 'How could he? That is so cruel! Why would he do such a thing?'],
      ['위컴', 'Jealousy, I suppose. His father loved me more. Still, for his father’s sake, I keep quiet.'],
      ['해설', 'Elizabeth did not doubt Wickham at all. It seemed just like something Darcy would do.'],
      ['해설', 'She did not find it strange that he told such private things to someone he had just met.'],
      ['엘리자베스', 'Jane, Mr. Darcy is not only proud on the outside. He is cold inside too.'],
      ['제인', 'Lizzy, maybe neither of them is a bad man. There may be something we don’t know.'],
      ['엘리자베스', 'You really are on everyone’s side in the world, aren’t you?'],
      ['해설', 'Meanwhile, Bingley announced that, as promised, he would hold a ball at Netherfield.'],
      ['콜린스', 'Miss Elizabeth, I hope you will dance the first two dances with me?'],
      ['해설', 'Elizabeth wanted to dance with Wickham, but she had no choice but to nod.'],
      ['리디아', 'A ball! Mr. Wickham will come, won’t he? And all the officers too?'],
      ['해설', 'Elizabeth counted the days until she could meet Wickham at the ball.'],
      ['해설', 'But on the night of the ball, the face she looked for was missing, and Darcy came toward her.'],
      ['해설', 'Austen sold the rights to this novel to the publisher Thomas Egerton for 110 pounds.'],
    ],
  },

  'pp-04': {
    title: 'Pride and Prejudice, Part 4',
    names: { 해설: 'Narrator', 다아시: 'Mr. Darcy', 엘리자베스: 'Elizabeth', 베넷부인: 'Mrs. Bennet', 콜린스: 'Mr. Collins', 베넷씨: 'Mr. Bennet', 샬럿: 'Charlotte Lucas' },
    outro: [
      'How did Elizabeth and Charlotte answer the question of marriage differently?',
      'Why did the writer make Collins’s proposal sound like a list of conditions, not a confession of love?',
      'When a society blocks people from earning their own living, how free can their choices be?',
    ],
    lines: [
      ['해설', 'Last time, Elizabeth heard from Wickham that Darcy had cheated him, and she believed every word.'],
      ['해설', 'At last, the day of the Netherfield ball came. But Wickham did not come, saying he had business.'],
      ['해설', 'The first dance with Collins was a cycle of stepping on toes and saying sorry.'],
      ['다아시', 'Miss Elizabeth, will you dance the next dance with me?'],
      ['해설', 'She was so surprised that she said yes before she knew it.'],
      ['엘리자베스', 'They say one must talk while dancing. It is your turn now, Mr. Darcy.'],
      ['다아시', 'As you wish. What would you like to hear?'],
      ['엘리자베스', 'I met Mr. Wickham the other day. He makes friends very easily.'],
      ['다아시', 'He may make them easily. Whether he can keep them is less certain.'],
      ['해설', 'They said no more. The dance ended, but they were further apart than ever.'],
      ['해설', 'At supper, Mrs. Bennet loudly told everyone that Jane would soon marry Bingley.'],
      ['베넷부인', 'His family is rich, so my other girls will find good husbands too!'],
      ['해설', 'Mary sang a long song no one had asked for, and Collins suddenly introduced himself to Darcy.'],
      ['해설', 'Seeing Darcy silently watch it all, Elizabeth felt her face burn.'],
      ['해설', 'The next morning, Collins asked to speak with Elizabeth alone.'],
      ['콜린스', 'My reason for marrying is, above all, that Lady Catherine advised it.'],
      ['콜린스', 'I also wish to make up for inheriting your family’s estate. I will take you as my wife.'],
      ['엘리자베스', 'You honor me, but I must refuse. I could never make you happy.'],
      ['콜린스', 'I have heard that young ladies always say no at first. I will not give up.'],
      ['해설', 'Mrs. Bennet was furious and begged her husband to make Elizabeth change her mind.'],
      ['베넷씨', 'Lizzy, I would be disappointed in you if you agreed to spend your life with that man.'],
      ['해설', 'A few days later, Elizabeth’s friend Charlotte Lucas accepted Collins’s proposal.'],
      ['엘리자베스', 'Charlotte, is it true? You will spend your life with a man like that?'],
      ['샬럿', 'Lizzy, I am twenty-seven, and I have no money of my own. I am not romantic. I need a comfortable home.'],
      ['해설', 'At that time, marriage was seen as almost the only way for a woman without money to secure her living.'],
      ['해설', 'Charlotte’s choice was a practical one that many women of her time made.'],
      ['해설', 'Elizabeth tried to understand her friend, but a corner of her heart felt lonely.'],
      ['해설', 'Then, as winter came near, unexpected news arrived from Netherfield.'],
      ['해설', 'Jane Austen was born in 1775 in Steventon, Hampshire, England, the daughter of a clergyman.'],
    ],
  },

  'pp-05': {
    title: 'Pride and Prejudice, Part 5',
    names: { 해설: 'Narrator', 제인: 'Jane', 엘리자베스: 'Elizabeth', 샬럿: 'Charlotte', 콜린스: 'Mr. Collins', 캐서린: 'Lady Catherine' },
    outro: [
      'When Bingley left, why did Jane blame herself while Elizabeth blamed others?',
      'Elizabeth never told Lady Catherine her age. What side of her does this scene show?',
      'What does it take to speak with confidence in front of someone of higher rank?',
    ],
    lines: [
      ['해설', 'Last time, Elizabeth refused Collins’s proposal, and Charlotte agreed to marry him.'],
      ['해설', 'The day after the ball, Bingley left for London, saying he would be back soon.'],
      ['해설', 'Soon his sister Caroline wrote to Jane. The whole party would spend the winter in London, she said.'],
      ['해설', 'The letter even said that Bingley had feelings for Darcy’s sister, Georgiana.'],
      ['제인', 'Lizzy, Mr. Bingley was only being kind to me. I must have imagined the rest.'],
      ['엘리자베스', 'No, Jane. Caroline is trying to keep Mr. Bingley away from you.'],
      ['해설', 'Jane looked calm on the outside, but she smiled much less all that winter.'],
      ['해설', 'At Christmas, their uncle and aunt, Mr. and Mrs. Gardiner, came to visit. They were sensible people in trade in London.'],
      ['해설', 'Their aunt warned Elizabeth, who was drawn to Wickham, to be careful about loving a man without money.'],
      ['해설', 'Jane decided to go back to London with the Gardiners and stay with them.'],
      ['해설', 'In London, Jane visited Caroline, but she was met with an icy coldness.'],
      ['해설', 'Bingley never appeared. At last, Jane understood what Caroline really felt.'],
      ['해설', 'Before long, Wickham turned his attention to Miss Mary King, who had just inherited ten thousand pounds.'],
      ['해설', 'Elizabeth was not very hurt. She thought a poor officer’s situation was understandable.'],
      ['해설', 'In March, Elizabeth went to visit the newly married Charlotte at the parsonage in Hunsford, Kent.'],
      ['샬럿', 'Thank you for coming, Lizzy. It is small, but it is my home. I am quite content here.'],
      ['콜린스', 'You will soon be invited to Rosings. Please do not be too amazed by its grandeur.'],
      ['해설', 'Near the parsonage stood Rosings, Lady Catherine’s great house. She was Darcy’s aunt.'],
      ['해설', 'Lady Catherine liked to give orders about every detail of other people’s households.'],
      ['캐서린', 'Five sisters? And no governess? Your mother must have had a hard time.'],
      ['엘리자베스', 'Those of us who wished to learn always could. That was enough.'],
      ['캐서린', 'You speak very boldly for a young lady. How old are you?'],
      ['엘리자베스', 'With three younger sisters grown up, must I really tell your ladyship my age?'],
      ['해설', 'Almost no one ever answered Lady Catherine like that.'],
      ['해설', 'She planned to marry her only daughter, Anne, to her nephew Darcy.'],
      ['해설', 'Around Easter, Darcy and his cousin, Colonel Fitzwilliam, came to Rosings.'],
      ['샬럿', 'Lizzy, Mr. Darcy came to call so soon. I think it must be because of you.'],
      ['해설', 'And that spring, a few words from Colonel Fitzwilliam would shake Elizabeth’s heart.'],
      ['해설', 'Pride and Prejudice came out without the author’s name, as a book by the author of Sense and Sensibility.'],
    ],
  },

  'pp-06': {
    title: 'Pride and Prejudice, Part 6',
    names: { 해설: 'Narrator', 피츠윌리엄: 'Colonel Fitzwilliam', 엘리자베스: 'Elizabeth', 다아시: 'Mr. Darcy' },
    outro: [
      'Darcy’s proposal was a confession of love, so why did it make Elizabeth angry?',
      'Darcy listed the faults of her family while proposing. What does this reveal about him?',
      'What does it look like to respect someone when you tell them you like them?',
    ],
    lines: [
      ['해설', 'Last time, Elizabeth visited Charlotte at Hunsford and met Darcy again at Rosings.'],
      ['해설', 'Darcy often came to the parsonage. He would sit without saying much, and then leave.'],
      ['해설', 'Walking in the woods, Elizabeth met Darcy many times. It was too often to be by chance.'],
      ['해설', 'One day, Colonel Fitzwilliam joined her on a walk and began to talk about his cousin.'],
      ['피츠윌리엄', 'Darcy takes good care of his friends. I hear he recently saved Bingley from an unwise marriage.'],
      ['엘리자베스', 'An unwise marriage? What happened?'],
      ['피츠윌리엄', 'I don’t know the details. I only heard there were strong objections to the lady’s family.'],
      ['해설', 'Elizabeth knew at once that the lady was Jane.'],
      ['해설', 'Her sister’s sadness was his doing. Her head ached, so she did not go to Rosings that evening.'],
      ['해설', 'While everyone else was at Rosings, Darcy unexpectedly came to the parsonage where she sat alone.'],
      ['해설', 'He walked around the room, then suddenly stopped in front of her.'],
      ['다아시', 'In vain have I struggled. I must tell you how much I love you.'],
      ['다아시', 'Your family is far below mine. That is why I hesitated for so long.'],
      ['다아시', 'I ask you against my pride and my reason. I trust you will accept.'],
      ['해설', 'His proposal sounded less like love and more like a list of the sacrifices he was making.'],
      ['엘리자베스', 'I never wanted your feelings. I cannot accept this proposal.'],
      ['다아시', 'May I know why I am refused so coldly?'],
      ['엘리자베스', 'Did you think I didn’t know you ruined my sister’s happiness?'],
      ['다아시', 'I do not deny it. I did everything I could to separate my friend from her.'],
      ['엘리자베스', 'I have heard about Mr. Wickham, too. You took away his future without a second thought.'],
      ['다아시', 'You take a great interest in that man.'],
      ['다아시', 'If I had hidden my doubts and only said pleasant things, I would not be scolded like this.'],
      ['엘리자베스', 'No matter how you had asked, my answer would be the same. From the first day, you looked down on others.'],
      ['다아시', 'I understand you completely. Forgive me for taking your time. I wish you every happiness.'],
      ['해설', 'When the door closed, Elizabeth sank into a chair and cried for a long time.'],
      ['해설', 'It amazed and confused her that such a proud man had loved her.'],
      ['해설', 'But when she thought of what he had done to Jane, she could not regret refusing him.'],
      ['해설', 'The next morning, on her walk, Darcy handed her a thick letter.'],
      ['해설', 'Pride and Prejudice was first published in three volumes.'],
    ],
  },

  'pp-07': {
    title: 'Pride and Prejudice, Part 7',
    names: { 해설: 'Narrator', 다아시: 'Mr. Darcy', 엘리자베스: 'Elizabeth', 리디아: 'Lydia', 베넷씨: 'Mr. Bennet', 제인: 'Jane' },
    outro: [
      'After reading Darcy’s letter, what mistake did Elizabeth realize she had made?',
      'How does this part show that both pride and prejudice belong to both main characters?',
      'Have you ever had to admit you were wrong? What was the hardest part?',
    ],
    lines: [
      ['해설', 'Last time, Darcy proposed, but Elizabeth refused him, blaming him for Jane and for Wickham.'],
      ['해설', 'Darcy handed her the letter and left without a word. Elizabeth opened it on the path in the woods.'],
      ['다아시', 'I do not write to propose again. I only wish to answer the two charges you made against me.'],
      ['다아시', 'I believed your sister had no special feelings for Bingley. She always seemed so calm.'],
      ['다아시', 'I was also worried by the behavior of your mother and younger sisters. Not you or Jane.'],
      ['해설', 'Elizabeth’s face burned. She remembered the scenes from the night of the ball.'],
      ['다아시', 'Wickham himself refused the church position my father left him. He took three thousand pounds instead.'],
      ['다아시', 'He spent it all, came back, and asked for the position again. I refused.'],
      ['다아시', 'Later, he tried to persuade my fifteen-year-old sister, Georgiana, to run away with him.'],
      ['다아시', 'He was after her fortune of thirty thousand pounds. Luckily, I found out in time.'],
      ['다아시', 'If you doubt me, ask Colonel Fitzwilliam.'],
      ['해설', 'Elizabeth read the letter again and again. At first, she did not want to believe it.'],
      ['해설', 'But looking back, Wickham had told his whole story freely on the very first day they met.'],
      ['해설', 'He had said he would not avoid Darcy, yet he did not come to the ball.'],
      ['엘리자베스', 'I was so proud of seeing through people, and yet I was this blind.'],
      ['엘리자베스', 'Pleased by one man’s praise and hurt by another’s insult, I could not see the truth.'],
      ['엘리자베스', 'I am ashamed, but till this moment, I never knew myself.'],
      ['해설', 'Pride was not Darcy’s alone, and prejudice belonged to Elizabeth as well.'],
      ['해설', 'Back at Longbourn, there was news that the regiment in Meryton was moving to Brighton, by the sea.'],
      ['리디아', 'Mrs. Forster is taking me to Brighton! Of all my sisters, only me!'],
      ['해설', 'Elizabeth went to her father and begged him not to let Lydia go.'],
      ['엘리자베스', 'Father, Lydia is far too silly. She will make our whole family look ridiculous.'],
      ['베넷씨', 'She will never be quiet until she embarrasses herself somewhere. Brighton is as good a place as any.'],
      ['해설', 'Elizabeth did not tell her family the truth about Wickham. He would be leaving soon, she thought.'],
      ['해설', 'Only to Jane did she tell everything.'],
      ['제인', 'So that is the kind of man Mr. Wickham was. Poor Mr. Darcy, how unfairly he was judged!'],
      ['해설', 'Lydia left for Brighton, full of excitement.'],
      ['해설', 'In summer, Elizabeth went on a trip north to Derbyshire with her uncle and aunt.'],
      ['해설', 'Jane Austen had an older sister, Cassandra, who was her closest friend all her life.'],
    ],
  },

  'pp-08': {
    title: 'Pride and Prejudice, Part 8',
    names: { 해설: 'Narrator', 레이놀즈: 'Mrs. Reynolds', 다아시: 'Mr. Darcy', 엘리자베스: 'Elizabeth', 조지아나: 'Georgiana', 제인: 'Jane' },
    outro: [
      'How was the Darcy she met at Pemberley different from the Darcy of last spring?',
      'What effect does it have to show Darcy again through the words of his housekeeper?',
      'People once saw one person’s mistake as the shame of a whole family. How should we see that today?',
    ],
    lines: [
      ['해설', 'Last time, Darcy’s letter showed Elizabeth the truth about Wickham, and she saw her own prejudice.'],
      ['해설', 'Darcy’s estate, Pemberley, was in Derbyshire. Their aunt really wanted to see the house.'],
      ['해설', 'Elizabeth hesitated. She agreed to go only after hearing that the owner was away.'],
      ['해설', 'Past the woods, a beautiful stone house appeared on a rise, with a stream in front of it.'],
      ['해설', 'It kept the beauty of nature rather than showy decoration, and Elizabeth was lost in wonder.'],
      ['해설', 'Mrs. Reynolds, the elderly housekeeper, showed them around.'],
      ['레이놀즈', 'The master has had a sweet temper since he was a boy. I have never once seen him angry.'],
      ['레이놀즈', 'To his servants and his tenants, there is no better master anywhere.'],
      ['해설', 'Elizabeth was surprised. This was a completely different man from the proud Darcy she knew.'],
      ['해설', 'When they went out to the garden, Darcy suddenly appeared in front of them.'],
      ['해설', 'Both of them blushed at the same time. Elizabeth did not know where to look.'],
      ['엘리자베스', 'We heard you were away, so we came. I am sorry to drop in like this.'],
      ['다아시', 'I only came back a day early. Is all your family well?'],
      ['해설', 'Unlike before, he spoke gently and politely. He greeted her uncle and aunt with great courtesy.'],
      ['다아시', 'While you are staying nearby, may I introduce my sister to you?'],
      ['해설', 'The next day, Darcy brought his shy sister, Georgiana, to the inn.'],
      ['조지아나', 'My brother has told me so much about you, Miss Elizabeth. I have wanted to meet you.'],
      ['해설', 'From the way Darcy looked at Elizabeth, her aunt could read his heart.'],
      ['해설', 'In Elizabeth’s heart too, gratitude and respect were growing in place of dislike.'],
      ['해설', 'But a few days later, two letters from Jane arrived together.'],
      ['제인', 'Lizzy, Lydia has run away from Brighton with Mr. Wickham. It seems he does not mean to marry her.'],
      ['해설', 'In those days, a woman who ran off with a man without marrying was thought to disgrace her whole family.'],
      ['해설', 'The shame could even ruin her sisters’ chances of marriage. That was the harsh view of the time.'],
      ['해설', 'As Elizabeth stood there, white with shock, Darcy walked in.'],
      ['엘리자베스', 'My sister has run off with Wickham. She has no money and no connections. It is all over.'],
      ['다아시', 'I should have told people what he was long ago. Much of the blame is mine.'],
      ['해설', 'With a stern face, Darcy hurried away. Elizabeth thought she would never see him again.'],
      ['해설', 'They left for Longbourn at once. A long wait to find Lydia began.'],
      ['해설', 'Austen published four novels in her lifetime. The other two came out after her death.'],
    ],
  },

  'pp-09': {
    title: 'Pride and Prejudice, Part 9',
    names: { 해설: 'Narrator', 베넷부인: 'Mrs. Bennet', 베넷씨: 'Mr. Bennet', 리디아: 'Lydia', 위컴: 'Mr. Wickham', 엘리자베스: 'Elizabeth', 가디너부인: 'Mrs. Gardiner' },
    outro: [
      'Why do you think Darcy solved Lydia’s problem while hiding his own name?',
      'What role does the scene where Lydia carelessly lets the secret slip play in the story?',
      'Have you ever helped someone, or been helped, without anyone knowing?',
    ],
    lines: [
      ['해설', 'Last time, Elizabeth met a changed Darcy at Pemberley, but then Lydia ran off with Wickham.'],
      ['해설', 'Longbourn was full of tears. Mrs. Bennet shut herself in her room, crying about her poor nerves.'],
      ['베넷부인', 'What if Wickham won’t marry our Lydia? What if my husband fights a duel?'],
      ['해설', 'Mr. Bennet went to London and searched for the two, but came back with nothing.'],
      ['베넷씨', 'Lizzy, I should have listened to you. For once in my life, let me blame myself.'],
      ['해설', 'A few days later, a letter came from their uncle, Mr. Gardiner, who had stayed in London.'],
      ['해설', 'He had found them, and Wickham had agreed to marry Lydia for very little.'],
      ['베넷씨', 'He would never marry her for so little. Your uncle must have spent a lot. How can I ever repay him?'],
      ['베넷부인', 'My daughter is getting married! The first of them all! What shall she wear?'],
      ['해설', 'Lydia and Wickham married and came to visit Longbourn. Lydia felt no shame at all.'],
      ['리디아', 'Look at me, sisters! I married first. Now I go before all of you!'],
      ['위컴', 'I hear you visited Pemberley, sister. Is Mrs. Reynolds well?'],
      ['엘리자베스', 'Yes, she is well. We are family now, so let us not talk about the past.'],
      ['해설', 'But while Lydia chattered about her wedding, she let a name slip.'],
      ['리디아', 'Oh, Mr. Darcy was there that day! Oops, that was supposed to be a secret.'],
      ['해설', 'Elizabeth could not bear it, so she wrote to her aunt to ask what had happened.'],
      ['해설', 'Her aunt’s reply held an amazing truth.'],
      ['해설', 'Darcy had searched London alone and found the two. Lydia had refused to leave Wickham.'],
      ['해설', 'Darcy paid Wickham’s debts, found him a new army post, and arranged the marriage.'],
      ['해설', 'Then he asked them to give the credit to her uncle, and never to reveal his name.'],
      ['가디너부인', 'He said he was making up for his mistake of not exposing Wickham sooner.'],
      ['가디너부인', 'But Lizzy, was that really his only reason?'],
      ['해설', 'Elizabeth put down the letter and thought for a long time.'],
      ['엘리자베스', 'He looked down on my family so much, and yet he risked having Wickham as a brother-in-law.'],
      ['엘리자베스', 'Did he do all this for me? I refused him once. Can I hope again?'],
      ['해설', 'Lydia and Wickham left for his regiment in the north. Mrs. Bennet cried for a long time.'],
      ['해설', 'One had set aside his pride, and the other had let go of her prejudice. The distance between them was shrinking.'],
      ['해설', 'That autumn, news spread through the village that Bingley was returning to Netherfield.'],
      ['해설', 'Jane Austen died in Winchester in 1817 at the age of forty-one, and was buried in Winchester Cathedral.'],
    ],
  },

  'pp-10': {
    title: 'Pride and Prejudice, Part 10',
    names: { 해설: 'Narrator', 빙리: 'Mr. Bingley', 제인: 'Jane', 캐서린: 'Lady Catherine', 엘리자베스: 'Elizabeth', 다아시: 'Mr. Darcy', 베넷씨: 'Mr. Bennet' },
    outro: [
      'What did each of them have to let go of before they could finally understand each other?',
      'What is ironic about Lady Catherine’s visit giving Darcy hope?',
      'What do we need to build relationships based on respect and understanding, not rank and money?',
    ],
    lines: [
      ['해설', 'Last time, Elizabeth learned that Darcy had secretly helped behind Lydia’s marriage.'],
      ['해설', 'In autumn, Bingley returned to Netherfield. Darcy was with him.'],
      ['해설', 'Darcy confessed to his friend that he had misjudged Jane’s feelings.'],
      ['빙리', 'Miss Bennet, I have never stopped thinking of you. Will you be my wife?'],
      ['제인', 'Yes, with all my heart. Lizzy, I am the happiest person in the world!'],
      ['해설', 'Mrs. Bennet was overjoyed. Laughter came back to Longbourn.'],
      ['해설', 'A few days later, Lady Catherine burst into Longbourn in a grand carriage.'],
      ['캐서린', 'I have heard a rumor that you will soon be engaged to my nephew. Tell me at once it is false.'],
      ['엘리자베스', 'If there is such a rumor, your coming all this way will only spread it further.'],
      ['캐서린', 'Darcy is meant for my daughter. A girl from a family like yours has no right to him.'],
      ['엘리자베스', 'He is a gentleman, and I am a gentleman’s daughter. So far we are equal.'],
      ['캐서린', 'Then promise me you will never accept him. I will not leave until you do.'],
      ['엘리자베스', 'I will make no promise. My happiness is mine to decide.'],
      ['해설', 'Lady Catherine left in a rage and went straight to tell Darcy everything.'],
      ['해설', 'But the news that Elizabeth had refused to promise gave Darcy new hope.'],
      ['해설', 'A few days later, Darcy came to Longbourn, and he and Elizabeth found themselves walking alone.'],
      ['엘리자베스', 'I know now everything you did for Lydia. On behalf of my whole family, thank you.'],
      ['다아시', 'Your family owes me nothing. I thought only of you.'],
      ['다아시', 'If your feelings are still what they were last spring, tell me so. I will never ask again.'],
      ['엘리자베스', 'My feelings are completely different now. I accept you with all my heart.'],
      ['다아시', 'Because of you, I saw my own pride for the first time. I am grateful for your scolding.'],
      ['엘리자베스', 'And because of you, I saw my prejudice. I judged you only by first impressions.'],
      ['해설', 'Mr. Bennet could hardly believe that his daughter, who had disliked Darcy so much, had changed her mind.'],
      ['베넷씨', 'Lizzy, do you really love him? Life with a partner you cannot respect is unhappy.'],
      ['엘리자베스', 'Father, he is the best man I know. I have only just realized it.'],
      ['해설', 'Jane married Bingley, and Elizabeth married Darcy. The Gardiners became honored guests at Pemberley.'],
      ['해설', 'Once trapped by first impressions, the two learned to see each other anew and walked on together.'],
      ['해설', 'In 2017, a portrait of Jane Austen appeared on Britain’s new ten-pound note.'],
    ],
  },
};
