// 청소년 영어 원고 (중학생 이상). 키 = stories/teen-e.js 의 이야기 id.
// 셰익스피어 원작(퍼블릭 도메인)의 이름·핵심 구절을 살리되, 문장은 한국어 각색의 흐름을 따라 쉬운 영어로 새로 씀.
export default {
  'tsp-romeo-1': {
    title: 'Romeo and Juliet, Part 1',
    names: { 해설: 'Narrator', 로미오: 'Romeo', 줄리엣: 'Juliet', 영주: 'Prince Escalus', 티볼트: 'Tybalt', 유모: 'Nurse' },
    outro: [
      'How does the old hatred between the two families shadow the first meeting of the young lovers?',
      'Juliet says a rose would smell as sweet by any other name. What does she mean?',
      'If your group thinks one way and your heart feels another, which would you follow?',
    ],
    lines: [
      ['해설', 'In the Italian city of Verona, two noble families had been enemies for generations: the Montagues and the Capulets.'],
      ['해설', 'One morning, servants from both houses started a quarrel in the street. Soon swords were out everywhere.'],
      ['영주', 'Stop! Three times now your silly words have turned this city into a battlefield.'],
      ['영주', 'If anyone draws a sword in these streets again, he will pay for it with his life.'],
      ['해설', 'Romeo, the only son of the Montagues, was not in the fight. He was sighing over a girl who ignored him.'],
      ['해설', 'That night, the Capulets held a great masked ball. Romeo and his friends put on masks and slipped inside.'],
      ['해설', 'In the candlelit hall, Romeo’s eyes stopped on one girl. She was Juliet, the only daughter of the Capulets.'],
      ['로미오', 'Who is she? She teaches the torches to burn bright! I never knew true love until tonight.'],
      ['해설', 'Someone recognized his voice. It was Tybalt, Juliet’s hot-tempered cousin.'],
      ['티볼트', 'That is a Montague! He came in a mask to laugh at our feast. Bring me my sword!'],
      ['해설', 'But old Capulet told Tybalt not to make trouble in front of the guests. Tybalt stepped back, angry.'],
      ['티볼트', 'I will wait for now. But this sweet visit will turn bitter one day.'],
      ['해설', 'Meanwhile, Romeo took Juliet’s hand. After only a few words, their hearts turned to each other.'],
      ['해설', 'As the party ended, Juliet asked her Nurse to find out who the young man was.'],
      ['유모', 'His name is Romeo, miss. He is a Montague, the only son of your family’s great enemy.'],
      ['줄리엣', 'My only love sprung from my only hate! I saw him too early and learned his name too late.'],
      ['해설', 'Romeo could not go home. He climbed the orchard wall and hid in the dark below Juliet’s window.'],
      ['해설', 'Soon Juliet appeared on the balcony. Thinking she was alone, she spoke to the night sky.'],
      ['줄리엣', 'O Romeo, Romeo, wherefore art thou Romeo? Give up your name, or I will give up mine.'],
      ['줄리엣', 'What’s in a name? A rose would smell just as sweet by any other name.'],
      ['로미오', 'Then call me only your love. From today, I will never be Romeo again.'],
      ['줄리엣', 'Who is there, hiding in the dark? If my family finds you here, they will kill you.'],
      ['로미오', 'I flew over these walls on the light wings of love. Stone walls cannot keep love out.'],
      ['해설', 'Under the moonlight, they told each other their love. Then the Nurse called Juliet from inside.'],
      ['줄리엣', 'If your love is true, I will send someone tomorrow. Tell them when and where we will marry.'],
      ['줄리엣', 'Good night, good night! Parting is such sweet sorrow. I could say good night until morning.'],
      ['로미오', 'At dawn I will go to Friar Laurence. He will help us.'],
      ['해설', 'That night, two children of enemy houses promised to marry in secret. But swords still flashed in Verona’s streets.'],
      ['해설', 'The play Romeo and Juliet is set in Verona, a city in northern Italy.'],
    ],
  },

  'tsp-romeo-2': {
    title: 'Romeo and Juliet, Part 2',
    names: { 해설: 'Narrator', 로미오: 'Romeo', 줄리엣: 'Juliet', 로런스: 'Friar Laurence', 머큐쇼: 'Mercutio', 티볼트: 'Tybalt', 영주: 'Prince Escalus' },
    outro: [
      'How did the duel right after the secret wedding change the fate of the two lovers?',
      'When Mercutio cries, a plague on both your houses, who is he really blaming?',
      'What can we do so that a moment of anger does not lead to something we cannot undo?',
    ],
    lines: [
      ['해설', 'Romeo and Juliet met at a masked ball, swore their love at the balcony, and decided to marry in secret.'],
      ['해설', 'Early in the morning, Romeo visited Friar Laurence, who was gathering herbs. The friar was shocked by his story.'],
      ['로런스', 'A few days ago you were crying over another girl. Now you love a Capulet after just one night?'],
      ['로미오', 'Father, this time is different. She loves me too. Please marry us today.'],
      ['로런스', 'This marriage may turn your families’ hate into love. Very well. But go slowly. Those who run fast fall down.'],
      ['해설', 'That afternoon, Juliet came to the church, saying she needed to confess. The friar quietly married them.'],
      ['해설', 'At noon the town square was hot. Romeo’s friend Mercutio was leaning in the shade and telling jokes.'],
      ['해설', 'Then Tybalt arrived with his men. He was still angry that Romeo had sneaked into the feast.'],
      ['티볼트', 'Romeo, you are a villain. Draw your sword.'],
      ['로미오', 'Tybalt, I do not hate you. For a reason you do not know, I now love the name Capulet.'],
      ['머큐쇼', 'What a shameful surrender! Tybalt, you king of cats, I will fight you myself.'],
      ['해설', 'Mercutio and Tybalt crossed swords. Romeo jumped between them to stop the fight.'],
      ['해설', 'At that moment, Tybalt’s sword reached under Romeo’s arm and stabbed Mercutio. Then Tybalt ran away.'],
      ['머큐쇼', 'It is only a scratch, but it is enough. Why did you come between us? I was hurt under your arm.'],
      ['머큐쇼', 'A plague on both your houses! Your quarrel has made me food for worms.'],
      ['해설', 'His friends helped Mercutio away, but he soon died. Romeo shook with grief and rage.'],
      ['로미오', 'Sweet Juliet, your beauty has made me weak. Mercutio’s soul is waiting above for Tybalt to join him.'],
      ['해설', 'When Tybalt came back, Romeo pointed his sword at him. After a short, wild fight, Tybalt fell and did not rise.'],
      ['로미오', 'O, I am fortune’s fool!'],
      ['해설', 'Romeo fled. The Prince and both families rushed to the square, and Lady Capulet demanded Romeo’s death.'],
      ['영주', 'Tybalt killed Mercutio, and Romeo killed Tybalt. But blood cannot only be paid for with more blood.'],
      ['영주', 'I banish Romeo from Verona. If he is found in this city again, that day will be his last.'],
      ['해설', 'When Juliet heard the news, she was more crushed by her husband’s banishment than by her cousin’s death.'],
      ['줄리엣', 'Banished! That one word is worse than ten thousand Tybalts dead.'],
      ['해설', 'Friar Laurence hid Romeo. He told him to see Juliet that night and leave for Mantua at dawn.'],
      ['로런스', 'Be patient. I will make peace between the families, announce your marriage, and ask the Prince to forgive you.'],
      ['해설', 'After one short night together, the two said a tearful goodbye when they heard the morning lark.'],
      ['해설', 'But Juliet’s father knew nothing. He decided she would marry a nobleman named Paris in three days.'],
      ['해설', 'In Shakespeare’s play, Juliet is a girl who is not yet fourteen years old.'],
    ],
  },

  'tsp-romeo-3': {
    title: 'Romeo and Juliet, Part 3',
    names: { 해설: 'Narrator', 줄리엣: 'Juliet', 로미오: 'Romeo', 로런스: 'Friar Laurence', 캐풀렛: 'Capulet', 유모: 'Nurse', 영주: 'Prince Escalus' },
    outro: [
      'Why did the deaths of the two lovers finally bring peace between their families?',
      'Like the letter that never arrived, can you find other small mistakes that made the tragedy worse?',
      'What can stop old conflicts between adults from becoming a burden for the next generation?',
    ],
    lines: [
      ['해설', 'Romeo was banished from Verona for killing Tybalt, and Juliet had to marry Paris in three days.'],
      ['줄리엣', 'Father, please, take back this marriage. I cannot marry anyone yet.'],
      ['캐풀렛', 'Ungrateful girl! If you will not go to church on Thursday, never look me in the face again.'],
      ['유모', 'Miss, Romeo is banished. Maybe it is better to marry Count Paris instead.'],
      ['해설', 'Even the Nurse she trusted most had turned away. Alone, Juliet went to Friar Laurence.'],
      ['로런스', 'There is one way. Drink this the night before the wedding. You will sleep like the dead for forty-two hours.'],
      ['로런스', 'Everyone will think you are dead and lay you in the family tomb. Meanwhile, I will write to Romeo.'],
      ['줄리엣', 'Do not talk to me of fear. Give me the bottle. Love will give me strength.'],
      ['해설', 'On the night before the wedding, Juliet sat alone with the bottle. Terrible thoughts filled her mind, but she drank it.'],
      ['해설', 'In the morning, the Capulet house was full of tears. The wedding music became a funeral song.'],
      ['해설', 'But the friar who carried the letter was locked in a house because of the plague. He never reached Mantua.'],
      ['해설', 'Instead, a servant reached Romeo first with the news that Juliet was dead and buried.'],
      ['로미오', 'Then I defy you, stars! Tonight I will lie beside Juliet.'],
      ['해설', 'Romeo gave gold to a poor apothecary and bought poison. Then he returned to Verona in the dark.'],
      ['해설', 'At the Capulet tomb he met Paris, who had come to guard Juliet’s grave. They fought, and Paris fell.'],
      ['해설', 'Romeo went inside with a single candle. Juliet lay there as if asleep.'],
      ['로미오', 'Death has taken your breath, but not your beauty. Your lips and cheeks are still red.'],
      ['로미오', 'Here’s to my love! Here, beside you, I will rest forever.'],
      ['해설', 'Romeo drank the poison and fell beside her. Just then, the friar rushed in, knowing the letter had failed.'],
      ['해설', 'Juliet slowly opened her eyes. Before the friar could explain, they heard the guards coming.'],
      ['로런스', 'Juliet, come away quickly. I will hide you with the nuns. People are coming!'],
      ['해설', 'The frightened friar ran away first. Left alone, Juliet saw the empty bottle in Romeo’s hand.'],
      ['줄리엣', 'You drank it all and left no drop for me. Then I will use your dagger.'],
      ['해설', 'Juliet took her own life with Romeo’s dagger and fell upon her husband’s chest.'],
      ['해설', 'At dawn, the Prince and both families gathered at the tomb. Friar Laurence told them everything.'],
      ['영주', 'Capulet, Montague, see what your hate has done. Heaven has used love to take away your joys.'],
      ['캐풀렛', 'O brother Montague, give me your hand. That is all I ask for my daughter now.'],
      ['해설', 'The two fathers promised to build golden statues of each other’s children. A sad peace came to Verona.'],
      ['영주', 'For never was a story of more woe than this of Juliet and her Romeo.'],
      ['해설', 'The play begins with a prologue that tells the audience the two lovers will die in the end.'],
    ],
  },

  'tsp-merchant-1': {
    title: 'The Merchant of Venice, Part 1',
    names: { 해설: 'Narrator', 안토니오: 'Antonio', 바사니오: 'Bassanio', 샤일록: 'Shylock' },
    outro: [
      'What kind of tension does the strange deal of a pound of flesh create in the story?',
      'Where does Shylock say his hatred for Antonio comes from?',
      'When you take a big risk for a friend, where does friendship end and foolishness begin?',
    ],
    lines: [
      ['해설', 'In Venice, the city on the water, lived a merchant named Antonio. His ships carried silk and spices across the seas.'],
      ['해설', 'Antonio was rich and generous, but lately he felt sad, and he did not know why.'],
      ['안토니오', 'I do not know why I am so sad. The world is a stage, and I must play a sad part.'],
      ['해설', 'Then his dearest friend Bassanio came to see him. Bassanio spent money freely and already owed Antonio a lot.'],
      ['바사니오', 'Antonio, in Belmont there is a lady named Portia. She is rich, and even more beautiful and wise.'],
      ['바사니오', 'Suitors come from everywhere. I want to try too, but I have no money to look the part.'],
      ['안토니오', 'As you know, all my wealth is at sea right now. I have no cash.'],
      ['안토니오', 'But borrow as much as my name allows. I will guarantee the loan.'],
      ['해설', 'Bassanio went to Shylock, a Jewish moneylender. He lent money and charged interest.'],
      ['해설', 'In those days, Jews in Venice had to live in a separate area, and Christians openly looked down on them.'],
      ['바사니오', 'I want to borrow three thousand ducats for three months. Antonio will be responsible for it.'],
      ['샤일록', 'Antonio. His ships are in Tripoli, the Indies, Mexico, and England. But ships are only boards, and there are pirates.'],
      ['해설', 'Just then, Antonio came in. Shylock secretly clenched his teeth.'],
      ['샤일록', 'He hates my people. He insults me in front of merchants and lends money for free to ruin my business.'],
      ['샤일록', 'Signior Antonio, you have insulted me many times. You spat on my coat and kicked me like a dog.'],
      ['샤일록', 'And now you want my money? Does a dog have money? Can a dog lend three thousand ducats?'],
      ['안토니오', 'I may call you that again. Do not lend it as to a friend. Lend it as to an enemy.'],
      ['안토니오', 'Then if I break my promise, you can punish me with an easy heart.'],
      ['샤일록', 'Why, how angry you are! I want to be your friend. This time I will take no interest at all.'],
      ['샤일록', 'Just for fun, let us add one line. If you cannot pay on time, I may cut a pound of your flesh.'],
      ['바사니오', 'No, Antonio! Do not sign such a bond for me.'],
      ['안토니오', 'Do not worry. Within two months my ships will return with nine times this amount. I will sign.'],
      ['샤일록', 'What use is a pound of human flesh? It is worth less than mutton or beef. It is just a sign of friendship.'],
      ['해설', 'The three men signed the bond before a notary. No one knew what was hiding behind Shylock’s smile.'],
      ['바사니오', 'I do not like fair words from a villain’s mind.'],
      ['안토니오', 'Now hurry to Belmont. I hope your love comes true.'],
      ['해설', 'Bassanio left for Belmont with the money. There, three boxes of gold, silver, and lead were waiting for suitors.'],
      ['해설', 'In The Merchant of Venice, Antonio borrows three thousand ducats from Shylock.'],
    ],
  },

  'tsp-merchant-2': {
    title: 'The Merchant of Venice, Part 2',
    names: { 해설: 'Narrator', 포샤: 'Portia', 네리사: 'Nerissa', 모로코: 'Prince of Morocco', 바사니오: 'Bassanio', 샤일록: 'Shylock' },
    outro: [
      'Why was Portia’s picture in the lead box and not in the gold or silver one?',
      'How does the line, all that glitters is not gold, reflect the choices of the suitors?',
      'Have you ever chosen something because of how it looked and then regretted it?',
    ],
    lines: [
      ['해설', 'With Antonio’s guarantee, Bassanio borrowed three thousand ducats from Shylock and set off for Portia’s home in Belmont.'],
      ['해설', 'Before he died, Portia’s father left a strange will. Her husband had to be chosen by one of three boxes.'],
      ['포샤', 'Nerissa, I cannot choose a man I like or refuse a man I dislike. I am tied by my dead father’s will.'],
      ['네리사', 'Your father was a good and wise man. Only someone who truly loves you will choose the right box.'],
      ['해설', 'Each box had words carved on it. There was a gold box, a silver box, and a plain lead box.'],
      ['해설', 'The first to try was the Prince of Morocco. He studied each box and read the words.'],
      ['모로코', 'The gold box says, who chooses me shall gain what many men desire. What all men desire is this lady!'],
      ['모로코', 'Such a precious jewel would never be kept in anything worse than gold. I choose the gold box.'],
      ['해설', 'But inside the gold box, there was only a skull and a rolled-up scroll.'],
      ['모로코', 'All that glitters is not gold. Many have sold their lives for a shining outside. How cold it is.'],
      ['해설', 'Next came the Prince of Arragon. He chose the silver box, found a picture of a fool, and left sadly.'],
      ['해설', 'Meanwhile, in Venice, Shylock’s daughter Jessica ran away with her lover and took her father’s money.'],
      ['샤일록', 'My daughter, my ducats! People laugh at me. But hath not a Jew eyes? Hands, feelings, a heart?'],
      ['샤일록', 'If you prick us, do we not bleed? If you tickle us, do we not laugh? If you wrong us, shall we not revenge?'],
      ['해설', 'Then news came, again and again, that Antonio’s ships were wrecked at sea. Shylock’s eyes shone coldly.'],
      ['해설', 'At last, Bassanio arrived in Belmont. From the first moment, Portia was drawn to him.'],
      ['포샤', 'Please wait a little. If you choose wrong, I will lose you. Stay with me a day or two first.'],
      ['바사니오', 'This waiting is torture. Let me try my fortune now.'],
      ['해설', 'Bassanio stood before the boxes and thought for a long time.'],
      ['바사니오', 'Outside beauty often hides what is inside. Gold tricks people, and silver is just common money.'],
      ['바사니오', 'But you, pale lead, warn more than you promise. Your honesty moves me. I choose you.'],
      ['해설', 'He opened the lead box, and inside was Portia’s picture. Full of joy, Portia gave him a ring.'],
      ['포샤', 'Myself, this house, and all I have are now yours. Promise me you will never lose this ring or give it away.'],
      ['바사니오', 'The day this ring leaves my finger, my life will leave my body.'],
      ['해설', 'Then a letter arrived from Venice. As Bassanio read it, his face turned white.'],
      ['바사니오', 'Antonio’s ships are all lost. The deadline has passed, and Shylock wants his pound of flesh.'],
      ['포샤', 'Go now! Pay twenty times the debt if you must. Your friend must not lose a single hair because of you.'],
      ['해설', 'After Bassanio left, Portia called Nerissa and whispered something. She had a plan of her own.'],
      ['해설', 'Portia’s three boxes were gold, silver, and lead, and her picture was in the cheapest one, the lead box.'],
    ],
  },

  'tsp-merchant-3': {
    title: 'The Merchant of Venice, Part 3',
    names: { 해설: 'Narrator', 공작: 'Duke', 포샤: 'Portia', 샤일록: 'Shylock', 안토니오: 'Antonio', 바사니오: 'Bassanio' },
    outro: [
      'By reading every word of the law closely, what did Portia show?',
      'How might we read Shylock’s punishment after the trial with today’s eyes?',
      'When justice and mercy clash, which one should our society give more weight to?',
    ],
    lines: [
      ['해설', 'When he heard Antonio’s ships were lost, Bassanio left Portia right after their engagement and hurried back to Venice.'],
      ['해설', 'In the court of Venice, the Duke sat high above. Antonio stood accused, and Shylock held a knife and scales.'],
      ['공작', 'Shylock, everyone believes you will show mercy at the last moment.'],
      ['샤일록', 'I have sworn to have my bond. If you ask why I want a pound of flesh, I say it is my wish.'],
      ['바사니오', 'Here are six thousand ducats, twice what was borrowed.'],
      ['샤일록', 'Even if it were six times more, I would not take it. I want what the bond says.'],
      ['해설', 'Then a young doctor of law walked in. It was really Portia dressed as a man, but no one knew her.'],
      ['포샤', 'The bond does not break the law. So the Jew must be merciful.'],
      ['샤일록', 'Why must I? Tell me that.'],
      ['포샤', 'The quality of mercy is not forced. It falls like gentle rain from heaven upon the ground.'],
      ['포샤', 'Mercy blesses twice, both the giver and the receiver. It suits a king better than his crown.'],
      ['샤일록', 'My deeds are on my own head. I want the law. Give me the penalty in the bond.'],
      ['포샤', 'Then the law of Venice cannot stop it. Merchant, prepare your chest.'],
      ['샤일록', 'O wise young judge! A Daniel has come to judgment!'],
      ['안토니오', 'Bassanio, I am ready. Do not grieve for me. Tell your wife how much I loved you.'],
      ['바사니오', 'Antonio, I have a wife as dear as life. But neither she nor the world is worth more than your life.'],
      ['해설', 'Shylock sharpened his knife and moved toward Antonio. The courtroom was completely silent.'],
      ['포샤', 'Wait. There is one more thing. This bond gives you no blood at all. It says only a pound of flesh.'],
      ['포샤', 'Take your flesh. But if you shed one drop of Christian blood, your lands and goods will be taken by law.'],
      ['포샤', 'And it must be exactly one pound. If it is more or less by a hair, you will lose your life.'],
      ['샤일록', 'Then I will take three times the money. Just give me that.'],
      ['포샤', 'You already refused the money in open court. You shall have nothing but the bond.'],
      ['해설', 'Portia then named another law. A foreigner who tried to kill a citizen would lose his wealth and face the Duke’s judgment.'],
      ['해설', 'The Duke spared Shylock’s life but ordered him to give up his wealth and change his religion. Shylock left, broken.'],
      ['샤일록', 'I am not well. Send the papers after me, and I will sign them. Let me go.'],
      ['해설', 'Bassanio offered anything as thanks. The young doctor asked for the ring on his finger.'],
      ['바사니오', 'Not this ring. My wife gave it to me. No, what would I not give the man who saved Antonio? Take it.'],
      ['해설', 'Back in Belmont, Portia showed the ring and teased Bassanio before revealing all her secrets.'],
      ['해설', 'She also brought happy news. Three of Antonio’s ships had safely returned to port.'],
      ['해설', 'At the trial, Portia disguised herself as a young doctor of law named Balthazar.'],
    ],
  },

  'tsp-hamlet-1': {
    title: 'Hamlet, Part 1',
    names: { 해설: 'Narrator', 햄릿: 'Hamlet', 호레이쇼: 'Horatio', 유령: 'Ghost', 클로디어스: 'Claudius', 거트루드: 'Gertrude', 폴로니어스: 'Polonius' },
    outro: [
      'Why did Hamlet decide to act mad instead of taking revenge right after he heard the Ghost?',
      'Something is rotten in the state of Denmark. What does this line say about the country?',
      'When you try to find a truth you cannot see, what do you base your judgment on?',
    ],
    lines: [
      ['해설', 'Elsinore Castle, Denmark. At midnight in the cold wind, a ghost in armor appeared before the guards on the walls.'],
      ['해설', 'It looked exactly like old King Hamlet, who had died suddenly two months before. The guards called the scholar Horatio.'],
      ['호레이쇼', 'It is surely the late king. This must be a sign that something terrible will happen to our country.'],
      ['해설', 'Inside the castle, there was a feast for the new king. He was Claudius, the dead king’s brother.'],
      ['해설', 'Less than two months after his brother’s death, he had married the queen, Gertrude.'],
      ['클로디어스', 'Hamlet, my nephew and now my son. Even grief for a father must have its limits.'],
      ['거트루드', 'Hamlet, take off those black clothes. All that lives must die. That is the way of the world.'],
      ['해설', 'Young Prince Hamlet lowered his head and said nothing. When he was alone, bitter words burst out.'],
      ['햄릿', 'Two months, not even two! Before her funeral shoes were old, my mother married my uncle.'],
      ['해설', 'Then Horatio told him about the ghost on the walls. That night, Hamlet climbed up to see for himself.'],
      ['해설', 'At midnight, the ghost appeared again and waved for Hamlet to follow.'],
      ['호레이쇼', 'Do not go, my lord. It may lead you to the edge of a cliff and drive you mad.'],
      ['햄릿', 'My life is not worth a pin. And my soul cannot die, just like that ghost. What should I fear?'],
      ['해설', 'When they were alone, the ghost slowly spoke.'],
      ['유령', 'I am your father’s spirit. People say a snake bit me while I slept in my garden.'],
      ['유령', 'But listen. The snake that took your father’s life now wears his crown.'],
      ['유령', 'My brother poured poison into my ear as I slept. He stole my life, my crown, and my queen at once.'],
      ['유령', 'If you loved your father, revenge this foul murder. But leave your mother to heaven.'],
      ['유령', 'The morning is coming. Farewell. Remember me.'],
      ['햄릿', 'I will remember. I will wipe everything else from the book of my memory and keep only your words.'],
      ['해설', 'Hamlet made Horatio and the guards swear on his sword never to speak of what they saw.'],
      ['햄릿', 'If I act strangely later, pretend you know nothing. The time is out of joint, and I was born to set it right.'],
      ['호레이쇼', 'Something is rotten in the state of Denmark.'],
      ['해설', 'After that night, Hamlet wandered the castle in messy clothes, saying strange things.'],
      ['해설', 'The king’s old adviser Polonius firmly believed Hamlet had gone mad from love for his daughter Ophelia.'],
      ['폴로니어스', 'Your Majesty, I will be brief, since brevity is the soul of wit. Your son is mad, and the cause is love.'],
      ['클로디어스', 'Very well. We will see for ourselves whether that is true.'],
      ['해설', 'Around that time, a group of traveling actors came to the castle. A plan formed in Hamlet’s mind.'],
      ['해설', 'Elsinore is the English name for Helsingør, a port town in Denmark.'],
    ],
  },

  'tsp-hamlet-2': {
    title: 'Hamlet, Part 2',
    names: { 해설: 'Narrator', 햄릿: 'Hamlet', 호레이쇼: 'Horatio', 클로디어스: 'Claudius', 거트루드: 'Gertrude', 폴로니어스: 'Polonius', 오필리아: 'Ophelia' },
    outro: [
      'What does the speech, to be or not to be, reveal about Hamlet’s mind?',
      'Hamlet used a play to expose the king’s crime. What are the strengths and dangers of this plan?',
      'When you are not sure and put off a decision, is that being careful or just hesitating?',
    ],
    lines: [
      ['해설', 'The Ghost told Hamlet that his father had been poisoned. Hamlet pretended to be mad and waited for his chance.'],
      ['해설', 'But doubt remained in his heart. Was the ghost really his father, or a devil trying to trick him?'],
      ['햄릿', 'I need proof. The actors will play a murder just like my uncle’s. The play’s the thing to catch the king’s conscience.'],
      ['해설', 'One day before the play, Hamlet walked alone down an empty hallway, deep in thought.'],
      ['햄릿', 'To be, or not to be, that is the question.'],
      ['햄릿', 'Is it nobler to suffer the arrows of cruel fortune, or to fight a sea of troubles and end them?'],
      ['햄릿', 'Fear of what comes after death makes cowards of us all. Too much thinking turns our courage pale.'],
      ['해설', 'Then Ophelia came near. Polonius and the king were hiding behind a curtain, listening.'],
      ['오필리아', 'My lord, I have come to return your gifts. Rich gifts become poor when the giver’s love grows cold.'],
      ['햄릿', 'I never gave you anything. I did love you once. No, I never loved you. Do not believe me.'],
      ['해설', 'Hamlet said harsh words and left. Ophelia stayed behind, crying.'],
      ['오필리아', 'O, what a noble mind is broken here! It is like sweet bells cracked and out of tune.'],
      ['해설', 'On the night of the play, Hamlet asked Horatio to watch the king’s face closely. The play was called The Mousetrap.'],
      ['해설', 'On stage, a man poured poison into a sleeping king’s ear in a garden. He took the crown and won the queen.'],
      ['클로디어스', 'Give me some light! Stop the play! I am leaving!'],
      ['해설', 'The king turned pale and rushed out. The whole court hurried after him in confusion.'],
      ['햄릿', 'Horatio, did you see? Now I would bet a thousand pounds on the ghost’s word.'],
      ['호레이쇼', 'I saw it clearly, my lord. At the very moment the poison appeared.'],
      ['해설', 'Alone, the king knelt down and tried to pray, but the words would not come.'],
      ['클로디어스', 'My crime smells to heaven. It carries the oldest curse, a brother’s murder. My words fly up, but my heart stays below.'],
      ['해설', 'Hamlet happened to pass behind him. He drew his sword, then stopped.'],
      ['햄릿', 'If I kill him while he prays, he goes to heaven. That is not revenge. I will wait for a worse moment.'],
      ['해설', 'The queen called her son to her room. Again, Polonius hid behind a hanging curtain to listen.'],
      ['거트루드', 'Hamlet, you have greatly offended your father.'],
      ['햄릿', 'Mother, you have greatly offended my father.'],
      ['해설', 'When Hamlet came closer, the frightened queen screamed. A panicked voice cried out from behind the curtain.'],
      ['폴로니어스', 'Help! Help, someone!'],
      ['햄릿', 'What is this? A rat? Die!'],
      ['해설', 'Hamlet stabbed through the curtain. But the man who fell was not the king. It was old Polonius.'],
      ['거트루드', 'What a rash and bloody deed!'],
      ['해설', 'Using this as an excuse, the king sent Hamlet to England. A secret letter asked the English king to kill him.'],
      ['해설', 'Hamlet called the play within the play The Mousetrap.'],
    ],
  },

  'tsp-hamlet-3': {
    title: 'Hamlet, Part 3',
    names: { 해설: 'Narrator', 햄릿: 'Hamlet', 호레이쇼: 'Horatio', 클로디어스: 'Claudius', 거트루드: 'Gertrude', 오필리아: 'Ophelia', 레어티즈: 'Laertes' },
    outro: [
      'What do you think was left behind once the revenge was over?',
      'How did holding the jester Yorick’s skull change Hamlet’s attitude toward death?',
      'Why did Hamlet, in his last moment, ask Horatio to tell his story?',
    ],
    lines: [
      ['해설', 'Hamlet stabbed Polonius behind the curtain, thinking he was the king. The king then sent Hamlet away to England.'],
      ['해설', 'Ophelia lost her father and could not bear the grief. She lost her mind and sang as she gave out flowers.'],
      ['오필리아', 'There’s rosemary, that’s for remembrance. And pansies, that’s for thoughts. The violets all withered when my father died.'],
      ['해설', 'Ophelia’s brother Laertes came back from France. He was furious about his father’s death and his sister’s state.'],
      ['레어티즈', 'I will take revenge on my father’s killer. I fear nothing in this world or the next.'],
      ['해설', 'Soon the queen brought sad news. Ophelia had tried to hang flowers on a willow, fallen into a stream, and drowned.'],
      ['해설', 'Meanwhile, on the way to England, Hamlet escaped during a pirate attack and returned to Denmark.'],
      ['클로디어스', 'Laertes, let us hold a fencing match. Leave your sword sharp and poison it. One scratch, and Hamlet will die.'],
      ['클로디어스', 'Just in case, I will also prepare a poisoned cup. When he is thirsty, we will hand it to him.'],
      ['해설', 'On their way back to the castle, Hamlet and Horatio were handed a skull by a gravedigger.'],
      ['햄릿', 'Alas, poor Yorick! I knew him, Horatio. A jester full of endless jokes, who carried me on his back a thousand times.'],
      ['햄릿', 'Even Alexander the Great turned to dust. Who knows if that dust now plugs a barrel?'],
      ['해설', 'Then a funeral came near. It was Ophelia’s. Only then did Hamlet learn of her death, and he leapt into the grave.'],
      ['햄릿', 'I loved Ophelia. The love of forty thousand brothers could not match mine.'],
      ['해설', 'A few days later, the king’s fencing match began. Horatio had a bad feeling and tried to stop Hamlet.'],
      ['햄릿', 'There is a special providence in the fall of a sparrow. If not now, it will come later. The readiness is all.'],
      ['해설', 'Hamlet won the first and second rounds. To celebrate her son, the queen lifted the cup on the table.'],
      ['클로디어스', 'Gertrude, do not drink!'],
      ['거트루드', 'I will, my lord. Please forgive me.'],
      ['해설', 'In the third round, Laertes’s poisoned blade cut Hamlet. In the struggle the swords were switched, and Hamlet wounded Laertes.'],
      ['거트루드', 'The drink, the drink! O my dear Hamlet, I am poisoned!'],
      ['해설', 'The queen fell. Dying from the poison, Laertes used his last strength to confess everything.'],
      ['레어티즈', 'Hamlet, you will not live half an hour. The sword tip was poisoned. The king is to blame.'],
      ['해설', 'Hamlet struck the king with the poisoned sword and forced the rest of the poisoned drink into his mouth. The king died.'],
      ['해설', 'Horatio reached for the cup, but Hamlet took it from him.'],
      ['햄릿', 'Horatio, live and tell my story truly. Breathe a little longer in this harsh world.'],
      ['햄릿', 'The rest is silence.'],
      ['호레이쇼', 'Now cracks a noble heart. Good night, sweet prince, and may angels sing you to your rest.'],
      ['해설', 'Soon after, Prince Fortinbras of Norway marched in with his army and took the empty throne of Denmark.'],
      ['해설', 'Hamlet is the longest of all Shakespeare’s plays.'],
    ],
  },

  'tsp-dream-1': {
    title: 'A Midsummer Night’s Dream, Part 1',
    names: { 해설: 'Narrator', 허미아: 'Hermia', 헬레나: 'Helena', 라이샌더: 'Lysander', 드미트리: 'Demetrius', 오베론: 'Oberon', 티타니아: 'Titania', 퍽: 'Puck', 보텀: 'Bottom' },
    outro: [
      'A single flower’s juice can change someone’s heart. What does this idea say about love?',
      'What role does Puck, the mischievous fairy, play in this story?',
      'What problems can happen when we try to force someone’s heart to change?',
    ],
    lines: [
      ['해설', 'Four days before Duke Theseus of Athens was to marry, a father dragged his daughter Hermia before him.'],
      ['해설', 'The father wanted her to marry Demetrius, but Hermia loved Lysander. The Duke ordered her to obey her father.'],
      ['라이샌더', 'The course of true love never did run smooth. Hermia, meet me in the woods tomorrow night, and we will escape Athens.'],
      ['허미아', 'Yes. I swear by Cupid’s strongest bow. I will wait for you in the woods tomorrow night.'],
      ['해설', 'Hermia told this secret to her best friend Helena. But Helena secretly loved Demetrius.'],
      ['헬레나', 'I will tell Demetrius. He will chase Hermia, but at least I can follow him into the woods.'],
      ['해설', 'That night in the woods, Oberon and Titania, the fairy king and queen, were quarreling over a little servant boy.'],
      ['티타니아', 'That boy is the son of my dear friend. I will not give him up for your whole fairy kingdom.'],
      ['오베론', 'Go, then. You will not leave this wood until I pay you back for this insult.'],
      ['오베론', 'Puck, bring me that flower. Put its juice on sleeping eyelids, and they will madly love the first thing they see.'],
      ['퍽', 'I’ll put a girdle round about the earth in forty minutes!'],
      ['해설', 'Then Demetrius came into the woods looking for Hermia, and Helena followed close behind him.'],
      ['드미트리', 'Stop following me. I feel sick when I look at you.'],
      ['헬레나', 'And I feel sick when I cannot look at you. Treat me like your puppy. Hit me, but let me follow.'],
      ['해설', 'Oberon watched them and felt sorry for Helena. When Puck brought the flower, he gave him one more job.'],
      ['오베론', 'There is a young man in Athenian clothes. Put the juice on his eyes so he wakes to see that lady first.'],
      ['해설', 'But the young Athenian Puck found was not Demetrius. It was Lysander, sleeping near Hermia.'],
      ['퍽', 'Here he is, the fellow in Athenian clothes. Drip, drip goes the juice on his eyes.'],
      ['해설', 'Just then, tired Helena passed by. Lysander woke up, saw Helena, and jumped to his feet.'],
      ['라이샌더', 'Helena, I would run through fire for you! Hermia? Now I love only you.'],
      ['헬레나', 'Are you making fun of me? Was I born to be laughed at like this?'],
      ['해설', 'In another part of the woods, some Athenian workmen were practicing a play for the Duke’s wedding.'],
      ['보텀', 'Let me play the hero and the lion too! I will roar as gently as a baby dove.'],
      ['해설', 'Feeling playful, Puck changed the weaver Bottom’s head into a donkey’s head. His friends ran away in terror.'],
      ['보텀', 'They want to scare me, but I will not move. I will walk around here and sing.'],
      ['해설', 'His singing woke Titania, who was asleep among the flowers. Oberon had already put the juice on her eyelids.'],
      ['티타니아', 'What angel wakes me from my flowery bed? Sweet one, sing again. I have fallen in love with you.'],
      ['퍽', 'Lord, what fools these mortals be! There will be even more trouble before this night is over.'],
      ['해설', 'A Midsummer Night’s Dream takes place in the ancient Greek city of Athens and the woods nearby.'],
    ],
  },

  'tsp-dream-2': {
    title: 'A Midsummer Night’s Dream, Part 2',
    names: { 해설: 'Narrator', 허미아: 'Hermia', 헬레나: 'Helena', 라이샌더: 'Lysander', 드미트리: 'Demetrius', 오베론: 'Oberon', 티타니아: 'Titania', 퍽: 'Puck', 보텀: 'Bottom' },
    outro: [
      'After one night in the woods, how did the four lovers find their way back to the right partners?',
      'Why did Puck ask the audience to think of everything as just a dream?',
      'Have you ever been moved by a performance or work that was clumsy but full of heart?',
    ],
    lines: [
      ['해설', 'Because of Puck’s mistake, Lysander loved Helena, and Queen Titania fell for Bottom, who now had a donkey’s head.'],
      ['오베론', 'Puck, what have you done? You have twisted a true love and failed to fix a false one.'],
      ['퍽', 'I only looked for Athenian clothes. But I must say, this mess is quite fun to watch.'],
      ['해설', 'Oberon put the juice on sleeping Demetrius’s eyes too. When he woke, the first person he saw was also Helena.'],
      ['드미트리', 'O Helena, goddess! What can I compare your eyes to? Even crystal looks cloudy beside them.'],
      ['헬레나', 'You are both mocking me together. Yesterday you fought over Hermia. Now you compete to laugh at me?'],
      ['해설', 'Hermia appeared, searching for Lysander. But Lysander coldly pushed her away.'],
      ['허미아', 'Lysander, why are you doing this? You loved me until last night.'],
      ['라이샌더', 'Let go of me. The one I love is Helena.'],
      ['허미아', 'Helena, you thief! You came in the night and stole my love’s heart!'],
      ['헬레나', 'You too? We grew up sitting on one chair and singing one song. How can you tear our friendship apart?'],
      ['해설', 'The two young men went deeper into the woods to fight a duel. Oberon gave Puck one last order.'],
      ['오베론', 'Cover the woods with fog so they cannot find each other. When they fall asleep, put this cure on Lysander’s eyes.'],
      ['퍽', 'This way, coward! No, over here! Ha ha, they spin in circles like lost sheep.'],
      ['해설', 'Puck copied their voices and led all four around until they fell asleep in one place, worn out.'],
      ['퍽', 'When you wake, you will see your first true love again. Jack shall have Jill, and all shall be well.'],
      ['해설', 'Oberon got the servant boy he wanted. Then he put the cure on Titania’s eyes as well.'],
      ['티타니아', 'Oberon, I had a strange dream. I was in love with a donkey. Oh, that face over there gives me chills.'],
      ['오베론', 'Now we are friends again. Take my hand and let us dance. Tomorrow we will bless the Duke’s wedding.'],
      ['해설', 'In the morning, Duke Theseus came hunting and found the four young people asleep in the woods.'],
      ['드미트리', 'My lord, I do not know how, but my love for Hermia melted like snow. Now I love only Helena.'],
      ['해설', 'The Duke overruled Hermia’s father and let both couples marry on the same day as himself.'],
      ['보텀', 'I have had a most rare dream. No eye has heard it, and no ear has seen it.'],
      ['해설', 'At the wedding feast that night, the workmen performed the tragedy Pyramus and Thisbe. Their clumsy acting made everyone laugh.'],
      ['보텀', 'Now die, die, die, die, die! Tongue, lose your light! Moon, take your flight!'],
      ['해설', 'When everyone went to bed, the fairies sang blessings through the palace. Finally, Puck stood before the audience.'],
      ['퍽', 'If we shadows have offended, think that you have only slept and had a dream.'],
      ['퍽', 'If you are kind, we will do better next time. Honest Puck promises. Give me your hands, if we be friends.'],
      ['해설', 'The play the Athenian workmen perform at the wedding is the story of Pyramus and Thisbe.'],
    ],
  },

  'tsp-macbeth-1': {
    title: 'Macbeth, Part 1',
    names: { 해설: 'Narrator', 맥베스: 'Macbeth', 맥베스부인: 'Lady Macbeth', 뱅코: 'Banquo', 마녀들: 'Witches', 덩컨: 'King Duncan' },
    outro: [
      'Did the witches’ words decide Macbeth’s fate, or did they wake up a desire he already had?',
      'Blood that will not wash off his hands. How does this image show Macbeth’s state of mind?',
      'What lines do you think we should never cross, even to reach our goals?',
    ],
    lines: [
      ['해설', 'A Scottish heath in thunder and lightning. Three witches met in the fog and chanted like a spell.'],
      ['마녀들', 'Fair is foul, and foul is fair. Hover through the fog and filthy air.'],
      ['해설', 'At that time, the generals Macbeth and Banquo were returning in triumph after defeating rebels and invaders.'],
      ['맥베스', 'So foul and fair a day I have not seen.'],
      ['해설', 'Three bearded witches stood in the generals’ way.'],
      ['마녀들', 'All hail, Macbeth, Thane of Glamis! All hail, Thane of Cawdor! All hail, Macbeth, who shall be king!'],
      ['뱅코', 'Nothing for me? If you can look into the seeds of time, tell me which will grow.'],
      ['마녀들', 'Lesser than Macbeth, and greater. Not so happy, yet much happier. You will not be king, but your children will.'],
      ['해설', 'The witches vanished like bubbles. Then the king’s messenger arrived. Macbeth had been named Thane of Cawdor.'],
      ['맥베스', 'One prophecy has already come true. Then the crown too? No, why does such a horrible thought make my heart pound?'],
      ['뱅코', 'Be careful. The tools of darkness tell us small truths to win us, then betray us when it matters most.'],
      ['해설', 'King Duncan warmly welcomed Macbeth and said he would stay at his castle that night. He also named his son Malcolm as heir.'],
      ['덩컨', 'Macbeth, your service is so great that my thanks cannot keep up. Tonight I will rest at your castle.'],
      ['해설', 'Lady Macbeth learned everything from her husband’s letter. She made up her mind before he did.'],
      ['맥베스부인', 'You want to be great, but you are too full of the milk of human kindness. We must not miss tonight.'],
      ['맥베스부인', 'Look like the innocent flower, but be the serpent under it. Leave the rest to me.'],
      ['해설', 'While the feast went on, Macbeth slipped away alone and hesitated.'],
      ['맥베스', 'He is my guest and my king. And he is such a kind ruler. We will go no further in this.'],
      ['맥베스부인', 'Then will you live as a coward all your life? Wanting something, but never daring to reach for it?'],
      ['맥베스부인', 'When the king sleeps, I will make his servants drunk. If we put daggers in their hands, who will suspect us?'],
      ['해설', 'Late at night, when all were asleep, Macbeth saw a dagger floating in the air before him.'],
      ['맥베스', 'Is this a dagger which I see before me, the handle toward my hand? I cannot hold it, yet I still see it.'],
      ['해설', 'A bell rang. Macbeth went into the king’s room. Soon he came out holding the daggers that had killed the king.'],
      ['맥베스', 'I heard a voice cry, sleep no more! Macbeth has murdered sleep!'],
      ['맥베스부인', 'Why did you bring the daggers out? Take them back. Put them beside the servants.'],
      ['맥베스', 'I will not go back. All the oceans could not wash this blood from my hand.'],
      ['해설', 'Lady Macbeth took the daggers back herself. Then loud knocking at the gate broke the silence of the night.'],
      ['해설', 'At dawn the king’s death was discovered. His two frightened sons fled abroad, and the crown went to Macbeth.'],
      ['해설', 'But the witches’ words still rang in Macbeth’s ears. Banquo’s children would be kings.'],
      ['해설', 'The real Macbeth ruled Scotland as king from 1040 to 1057.'],
    ],
  },

  'tsp-macbeth-2': {
    title: 'Macbeth, Part 2',
    names: { 해설: 'Narrator', 맥베스: 'Macbeth', 맥베스부인: 'Lady Macbeth', 마녀들: 'Witches', 맥더프: 'Macduff', 맬컴: 'Malcolm', 의사: 'Doctor' },
    outro: [
      'After winning the crown, why did the lives of Macbeth and his wife slowly fall apart?',
      'In the speech that calls life a walking shadow, what did Macbeth come to realize?',
      'How can we stop ourselves from hiding one wrong by doing another?',
    ],
    lines: [
      ['해설', 'Led by the witches’ prophecy, Macbeth killed King Duncan and finally wore the crown of Scotland.'],
      ['해설', 'But he was uneasy. The witches had said Banquo’s children would be kings. So Macbeth sent murderers to kill Banquo.'],
      ['해설', 'At a feast that night, Macbeth saw Banquo’s ghost sitting in his seat. To everyone else, the chair was empty.'],
      ['맥베스', 'Do not shake your bloody head at me! You cannot say I did it!'],
      ['맥베스부인', 'Friends, my lord has had this illness since he was young. Let us end the feast for tonight.'],
      ['해설', 'Driven by fear, Macbeth went back to the witches. They chanted spells around a boiling pot.'],
      ['마녀들', 'Beware Macduff. But do not fear. No man born of woman shall harm Macbeth.'],
      ['마녀들', 'Macbeth shall never fall until Birnam Wood comes to Dunsinane Hill.'],
      ['맥베스', 'A forest cannot walk. And every man is born of woman. Then I am safe forever.'],
      ['해설', 'Macbeth heard that Macduff had gone to England to join Prince Malcolm. He attacked Macduff’s castle and killed his wife and children.'],
      ['해설', 'When Macduff heard the news in England, he could not speak for a long time.'],
      ['맥더프', 'All? All my pretty ones? All at one fell swoop?'],
      ['맬컴', 'Bear it like a man. Let this grief sharpen your sword. Let anger make your heart sharp, not dull.'],
      ['맥더프', 'I will. But first I must feel it as a man. Bring that devil before my sword.'],
      ['해설', 'Meanwhile, in Dunsinane Castle, Lady Macbeth walked the halls every night in her sleep, holding a candle.'],
      ['의사', 'Her eyes are open, but they see nothing. Look, she is pretending to wash her hands.'],
      ['맥베스부인', 'Out, damned spot! All the perfumes of Arabia will not sweeten this little hand.'],
      ['맥베스부인', 'What’s done cannot be undone. To bed, to bed, to bed.'],
      ['의사', 'This illness is beyond my skill. She needs God more than a doctor.'],
      ['해설', 'Malcolm and Macduff marched with an English army. Malcolm told each soldier to cut a branch from Birnam Wood.'],
      ['해설', 'Then women’s cries came from inside the castle. The queen was dead.'],
      ['맥베스', 'Tomorrow, and tomorrow, and tomorrow creeps in day by day, to the last word of recorded time.'],
      ['맥베스', 'Life’s but a walking shadow, a poor player who struts on the stage and is gone. Full of sound and fury, signifying nothing.'],
      ['해설', 'A guard ran in to report that Birnam Wood was moving toward the castle. It was an army hidden by branches.'],
      ['해설', 'On the battlefield, Macbeth finally came face to face with Macduff.'],
      ['맥베스', 'Stand back. No man born of woman can defeat me.'],
      ['맥더프', 'Give up your charm. Macduff was taken from his mother’s body early, before his time.'],
      ['해설', 'Macbeth realized the prophecies were all tricks of words. Still, he fought to the end and fell by Macduff’s hand.'],
      ['맬컴', 'The time of the tyrant is over. By the grace of heaven, we will set all things right in their time and place.'],
      ['해설', 'Macbeth is the shortest of Shakespeare’s tragedies.'],
    ],
  },
};
