// 청소년 영어 원고 (중학생 이상). 문장은 자체 각색, 도일·스티븐슨 원작의 이름과 핵심 표현을 살림.
// 키 = stories/teen-d.js 의 이야기 id. lines 의 첫 칸은 원래 이야기 cast 의 한국어 이름 그대로.
export default {
  'td-bohemia-1': {
    title: 'A Scandal in Bohemia, Part 1',
    names: { 해설: 'Narrator', 홈즈: 'Sherlock Holmes', 왓슨: 'Dr. Watson', 왕: 'The King of Bohemia', 노턴: 'Godfrey Norton' },
    outro: [
      'What was Doyle poking fun at by showing a king so troubled by a single photograph?',
      'What fun and tension does Holmes add when, disguised as a groom, he becomes a wedding witness?',
      'How do old photos or records cause trouble for people these days?',
    ],
    lines: [
      ['해설', 'In March 1888, Watson, now married and living elsewhere, visited 221B Baker Street for the first time in a while.'],
      ['홈즈', 'Marriage suits you, Watson. You’ve gained seven pounds. And you’re back in practice as a doctor.'],
      ['홈즈', 'You were soaked in the rain recently, and you have a very clumsy servant girl. Your shoe has six scratches.'],
      ['왓슨', 'If you had lived a few centuries ago, you would have been burned as a witch. You’re right about everything.'],
      ['홈즈', 'You see, but you do not observe. How many steps lead up from the hall to this room?'],
      ['왓슨', 'I’ve gone up hundreds of times, but I don’t know.'],
      ['홈즈', 'Seventeen. I have both seen and observed. Now, read this letter. A visitor is coming tonight.'],
      ['해설', 'The paper had a watermark showing it was made in Bohemia, and the writing sounded German.'],
      ['해설', 'At exactly eight, a tall man in a black mask entered, dressed in rich furs.'],
      ['왕', 'I am Count Von Kramm. What I tell you must stay secret for two years.'],
      ['홈즈', 'The mask is useless, Your Majesty. I know I am speaking to the King of Bohemia.'],
      ['해설', 'The man tore off his mask and threw it to the floor. He was indeed the King of Bohemia.'],
      ['왕', 'Five years ago in Warsaw, I met a woman named Irene Adler. She was a famous opera singer.'],
      ['왕', 'She has a photograph of the two of us together. I am soon to marry a princess of Scandinavia.'],
      ['왕', 'If her family sees that photo, the marriage is over. My men have tried five times to get it back. They all failed.'],
      ['왕', 'She says she will send it on the day the engagement is announced. That is next Monday.'],
      ['해설', 'The King left gold and banknotes for expenses. Holmes wrote down Irene’s address.'],
      ['해설', 'The next day, Holmes dressed as a drunken groom and joined the men at the stables near Irene’s house.'],
      ['해설', 'According to the stablemen, her only regular visitor was a young lawyer, Godfrey Norton.'],
      ['해설', 'That afternoon, Norton rushed off in a cab. Soon Irene followed in another carriage.'],
      ['해설', 'Holmes caught a cab and followed them. The carriages stopped at the Church of St. Monica.'],
      ['노턴', 'Thank God! You’ll do. Come! Come! Just three minutes. Without a witness, the marriage won’t be legal.'],
      ['해설', 'Holmes was pulled to the altar. He became the witness at Irene Adler’s wedding to Godfrey Norton.'],
      ['홈즈', 'I’ve never been in such a funny position in my life, Watson. The bride even gave me a gold coin.'],
      ['왓슨', 'Then the matter is more urgent. Who knows what she’ll do now?'],
      ['홈즈', 'That’s why I need your help tonight. We may have to break the law a little. Do you mind?'],
      ['왓슨', 'Not at all, if it’s for a good cause.'],
      ['홈즈', 'When I raise my hand, throw this smoke rocket through the window and shout fire. That’s all.'],
      ['해설', 'That evening, Holmes put on a new disguise as a simple clergyman. What would happen at Irene’s house?'],
      ['해설', 'A Scandal in Bohemia appeared in The Strand Magazine in July 1891. It was the first Holmes short story.'],
    ],
  },

  'td-bohemia-2': {
    title: 'A Scandal in Bohemia, Part 2',
    names: { 해설: 'Narrator', 홈즈: 'Sherlock Holmes', 왓슨: 'Dr. Watson', 왕: 'The King of Bohemia', 아이린: 'Irene Adler', 하녀: 'Housekeeper' },
    outro: [
      'Through Irene Adler, who outwits Holmes, what prejudice about women of that time did Doyle overturn?',
      'What insight into the human mind lies in Holmes’s fire alarm trick?',
      'Have you ever underestimated someone and learned from them instead? What did you realize?',
    ],
    lines: [
      ['해설', 'Holmes had promised the King to get back a photograph. Instead, he had become a witness at Irene Adler’s wedding.'],
      ['해설', 'That evening, Holmes, dressed as a clergyman, waited with Watson outside Irene’s house, Briony Lodge.'],
      ['해설', 'The street was full of loafers, a knife grinder, guardsmen, and young men smoking.'],
      ['홈즈', 'Watson, the photo is too big to carry around. It must be somewhere in the house.'],
      ['해설', 'When Irene’s carriage stopped at the door, the loafers fought each other to open it for her.'],
      ['해설', 'Holmes rushed in as if to protect her. Then he cried out and fell, holding his face.'],
      ['아이린', 'Is the poor gentleman hurt? Bring him inside. Lay him on the sofa in the sitting room.'],
      ['해설', 'The window opened. Holmes, lying on the sofa, raised his hand. Watson threw the smoke rocket and shouted.'],
      ['왓슨', 'Fire!'],
      ['해설', 'At once, everyone in the street was shouting fire. Thick smoke filled the room.'],
      ['해설', 'A moment later, Holmes called out that it was a false alarm. Watson slipped away to the corner they had agreed on.'],
      ['홈즈', 'Well done, Watson. I know where the photograph is.'],
      ['홈즈', 'When there’s a fire, people rush to what they value most. She ran to a panel above the bell-pull.'],
      ['홈즈', 'Tomorrow morning, I’ll bring the King. We’ll take the photo before she wakes up.'],
      ['해설', 'Holmes was looking for his key at his door on Baker Street. A slim youth in a long coat passed by.'],
      ['아이린', 'Good night, Mister Sherlock Holmes.'],
      ['홈즈', 'I’ve heard that voice before. Now, who could it have been?'],
      ['해설', 'The next morning, Holmes, Watson, and the King went to Briony Lodge. An elderly housekeeper opened the door.'],
      ['하녀', 'Mr. Sherlock Holmes, I believe? My mistress left this morning with her husband for Europe. She will never come back.'],
      ['해설', 'Holmes opened the panel. Inside was a photo of Irene alone in an evening dress, and a letter.'],
      ['아이린', 'My dear Mr. Holmes, you really did it very well. Until the fire alarm, you completely fooled me.'],
      ['아이린', 'But then I realized. I was trained as an actress, so men’s clothes are nothing new. I followed you and even said good night.'],
      ['아이린', 'I love and am loved by a better man. The King may rest easy.'],
      ['아이린', 'I will keep the photo only to protect myself. Instead, I leave a photo the King may like to have.'],
      ['왕', 'What a woman! If only she had been of my rank, what a queen she would have made!'],
      ['홈즈', 'From what I have seen, she is indeed on a very different level from Your Majesty.'],
      ['왕', 'She will keep her word. I want to reward you. Please take this emerald ring.'],
      ['홈즈', 'I want something more valuable than a ring. Your Majesty, please give me this photograph.'],
      ['해설', 'After that, Holmes never used her name. To him, Irene Adler was always the woman.'],
      ['해설', 'Sherlock Holmes first appeared in the novel A Study in Scarlet, published in 1887.'],
    ],
  },

  'td-redhead-1': {
    title: 'The Red-Headed League, Part 1',
    names: { 해설: 'Narrator', 홈즈: 'Sherlock Holmes', 왓슨: 'Dr. Watson', 윌슨: 'Jabez Wilson' },
    outro: [
      'How did Doyle use the odd Red-Headed League to catch the reader’s curiosity?',
      'When Holmes read Wilson’s past from his hands and sleeves, what were the clues?',
      'If someone offered you a lot of easy money, what should you be suspicious of first?',
    ],
    lines: [
      ['해설', 'In the autumn of 1890, Watson visited his friend Sherlock Holmes at 221B Baker Street.'],
      ['해설', 'With Holmes sat a red-faced, middle-aged gentleman with fiery red hair.'],
      ['홈즈', 'You’re just in time, Watson. This is Mr. Jabez Wilson. He has brought a very strange story.'],
      ['홈즈', 'He once did hard manual work, he has been to China, and he writes a lot lately. That’s all I know.'],
      ['윌슨', 'How did you know that? I never said I was a ship’s carpenter or mentioned China!'],
      ['홈즈', 'Your right hand is larger than your left. And the fish tattoo on your wrist is a style found only in China.'],
      ['홈즈', 'Your right cuff is shiny with wear. Your left sleeve has a smooth patch where the elbow rests on a desk.'],
      ['윌슨', 'Well, now that you explain it, it’s nothing special. I thought you had done something clever.'],
      ['해설', 'Wilson owned a small pawnshop. Business was slow, so he had only one assistant.'],
      ['윌슨', 'His name is Vincent Spaulding. He wanted to learn the trade, so he agreed to work for half wages.'],
      ['윌슨', 'His only fault is photography. He’s always running down to the cellar to develop his pictures.'],
      ['해설', 'Two months earlier, this same Spaulding came in with a newspaper and pointed to an advertisement.'],
      ['윌슨', 'The Red-Headed League was looking for a member. Four pounds a week for purely nominal work!'],
      ['윌슨', 'An American millionaire with red hair left his fortune to help men with the same hair color.'],
      ['해설', 'Outside the office on Fleet Street, a crowd of red-haired men of every shade had gathered.'],
      ['해설', 'A man named Duncan Ross looked delighted when he saw Wilson. Then he pulled hard on Wilson’s hair.'],
      ['윌슨', 'He said he was checking for a wig. Then he chose me at once and sent everyone else away.'],
      ['윌슨', 'The job was to copy the Encyclopaedia Britannica in the office every day from ten to two.'],
      ['윌슨', 'But I could never leave the office during those hours. If I did, I would lose the job.'],
      ['해설', 'For eight weeks, Wilson went every day. He copied almost all the entries starting with A.'],
      ['윌슨', 'But this morning, the door was locked. There was only a note saying the Red-Headed League was dissolved.'],
      ['해설', 'Watson burst out laughing, and Holmes laughed too. Wilson’s face turned as red as his hair.'],
      ['홈즈', 'Forgive us for laughing. But this may be far more serious than it looks. What does Spaulding look like?'],
      ['윌슨', 'Short and stout, about thirty. He has a white acid splash on his forehead, and his ears are pierced.'],
      ['해설', 'Holmes’s eyes flashed. After Wilson left, he sank deep into his chair.'],
      ['홈즈', 'It is quite a three-pipe problem. Watson, please don’t speak to me for fifty minutes.'],
      ['해설', 'A long while later, Holmes jumped up and grabbed his coat.'],
      ['왓슨', 'Have you figured something out, Holmes? To me, it sounds like a silly joke.'],
      ['홈즈', 'Watson, let’s go to Saxe-Coburg Square, where Mr. Wilson’s shop is. I want to see the area myself.'],
      ['해설', 'Who would want to keep a man away from his shop for four hours every day, and why? The answer lay in that square.'],
      ['해설', 'The Red-Headed League appeared in The Strand in August 1891, the month after A Scandal in Bohemia.'],
    ],
  },

  'td-redhead-2': {
    title: 'The Red-Headed League, Part 2',
    names: { 해설: 'Narrator', 홈즈: 'Sherlock Holmes', 왓슨: 'Dr. Watson', 존스: 'Inspector Jones', 메리웨더: 'Mr. Merryweather', 클레이: 'John Clay' },
    outro: [
      'What was Doyle showing by hiding a careful bank robbery plan behind a silly league?',
      'What clues did Holmes get by tapping the pavement and looking at the assistant’s trouser knees?',
      'Have you ever missed something important because you were focused on a small gain?',
    ],
    lines: [
      ['해설', 'Thanks to his red hair, the pawnbroker Wilson had copied an encyclopedia every day. Then, suddenly, the job was gone.'],
      ['해설', 'Holmes and Watson went to Saxe-Coburg Square, where Wilson’s shop stood. It was a shabby old square.'],
      ['해설', 'Holmes struck the pavement in front of the shop hard with his stick several times. Then he knocked and asked for directions.'],
      ['해설', 'The assistant who opened the door was a sharp-looking young man. He politely gave directions and shut the door.'],
      ['홈즈', 'I wasn’t looking at the way. I was looking at the knees of his trousers. They were worn, wrinkled, and dirty.'],
      ['해설', 'Holmes walked around to the busy street behind the square. There stood a branch of the City and Suburban Bank.'],
      ['홈즈', 'Watson, come back tonight at ten. It may be dangerous, so bring your army revolver.'],
      ['해설', 'That night at Baker Street were Inspector Peter Jones of Scotland Yard and Mr. Merryweather, a bank director.'],
      ['메리웨더', 'This is the first Saturday night in twenty-seven years that I’ve missed my card game. I hope it’s worth it.'],
      ['존스', 'Don’t worry. Tonight we’re after John Clay. His grandfather was a royal duke, and he is one of London’s top criminals.'],
      ['해설', 'The four men entered the bank. They passed a heavy iron gate and went down to the stone cellar.'],
      ['메리웨더', 'These boxes hold thirty thousand gold coins borrowed from the Bank of France. Word seems to have got out.'],
      ['홈즈', 'That’s why they chose tonight. Now I’ll cover the lantern. Don’t make a sound.'],
      ['해설', 'An hour and a quarter passed in total darkness. To Watson, it felt like the whole night.'],
      ['해설', 'Then a thin line of light appeared between the stones in the floor. A stone lifted, and a white hand came out.'],
      ['해설', 'Next, a young face rose from the hole. It was the same assistant who had given them directions.'],
      ['클레이', 'It’s all clear, Archie. Come on up. Wait! Jump, Archie, jump!'],
      ['해설', 'Holmes sprang forward and seized the man by the collar. His partner escaped down the hole, but police were waiting at the other end.'],
      ['홈즈', 'It’s no use, John Clay. It’s over.'],
      ['클레이', 'So I see. Don’t touch me. I have royal blood, so kindly say please when you speak to me.'],
      ['존스', 'All right. Would you please march upstairs, Your Highness? A cab is waiting.'],
      ['해설', 'At dawn, back at Baker Street, Holmes explained the whole case to Watson.'],
      ['홈즈', 'From the start, the League was a trick to get Mr. Wilson out of his shop for hours every day.'],
      ['홈즈', 'An assistant working for half pay, and a hobby that took him to the cellar. He was digging a tunnel to the bank.'],
      ['홈즈', 'When I tapped the pavement, I learned the tunnel wasn’t in front. So it went behind, toward the bank.'],
      ['홈즈', 'And when the League suddenly closed, it meant the tunnel was finished. They would act very soon.'],
      ['왓슨', 'Brilliant reasoning. Once again, thanks to you, a great criminal has been caught.'],
      ['홈즈', 'Work like this saves me from boredom. As a French writer said, the man is nothing, the work is everything.'],
      ['해설', 'The Red-Headed League is the second story in the 1892 collection The Adventures of Sherlock Holmes.'],
    ],
  },

  'td-band-1': {
    title: 'The Speckled Band, Part 1',
    names: { 해설: 'Narrator', 홈즈: 'Sherlock Holmes', 왓슨: 'Dr. Watson', 헬렌: 'Helen Stoner', 로일롯: 'Dr. Roylott' },
    outro: [
      'What fear and curiosity did Doyle plant with the strange last words, the speckled band?',
      'What kind of contest is shown when Roylott bends the poker and Holmes straightens it?',
      'If a friend were too afraid of someone close to ask for help, how could you reach out?',
    ],
    lines: [
      ['해설', 'Early one morning in April 1883, Holmes shook Watson awake.'],
      ['홈즈', 'Wake up, Watson. A young lady has come, and she is terribly frightened. This looks like a case worth taking.'],
      ['해설', 'The woman wore black and a veil. Her name was Helen Stoner. She was about thirty, but her hair was already turning gray.'],
      ['홈즈', 'Don’t be afraid. You came on the early train. Before that, you rode a long way in a dog-cart on muddy roads.'],
      ['헬렌', 'How did you know?'],
      ['홈즈', 'Your left sleeve has mud in no less than seven places. That happens when you sit on the driver’s left.'],
      ['헬렌', 'I live at Stoke Moran with my stepfather, Dr. Roylott. He used to be a doctor in India.'],
      ['헬렌', 'He has a terrible temper, and the villagers avoid him. He also lets a cheetah and a baboon from India roam free.'],
      ['헬렌', 'My mother left money. When my twin sister or I married, he had to give each of us a yearly share.'],
      ['해설', 'Two years earlier, Helen’s sister, Julia, was two weeks from her wedding. That was when strange things began.'],
      ['헬렌', 'My sister asked me if I had heard a low whistle around three in the morning.'],
      ['해설', 'Julia’s room was in the middle. Helen’s room was on one side, and the doctor’s room was on the other.'],
      ['헬렌', 'On that stormy night, I heard a scream. Then a whistle, and then a metallic clang.'],
      ['헬렌', 'I ran out and saw my sister stagger out and fall. She pointed toward the doctor’s room and cried out.'],
      ['헬렌', 'Helen! It was the band! The speckled band! Those were her last words. She died soon after.'],
      ['해설', 'The coroner found no wound and no sign of poison. Her door and shutters had been locked from inside.'],
      ['헬렌', 'Now I am engaged too. Because of repairs, I moved into my sister’s room. Last night, I heard that whistle.'],
      ['홈즈', 'Show me your wrist. There are five finger marks. You are protecting your stepfather.'],
      ['해설', 'Helen blushed and covered her wrist. Holmes promised to come to Stoke Moran that afternoon.'],
      ['해설', 'Soon after Helen left, the door burst open. A man so tall his head almost touched the door frame came in.'],
      ['로일롯', 'I am Dr. Roylott of Stoke Moran. My stepdaughter was here, wasn’t she? What did she tell you?'],
      ['홈즈', 'The crocuses should be out soon. It’s quite warm today.'],
      ['로일롯', 'You meddler! Stay out of my business. I am a dangerous man.'],
      ['해설', 'Roylott grabbed the steel poker from the fireplace. He bent it with his huge hands and stormed out.'],
      ['해설', 'Holmes laughed and picked up the poker. With one great effort, he straightened it again.'],
      ['홈즈', 'If he had stayed a little longer, I’d have shown him my grip is not much weaker than his.'],
      ['왓슨', 'With a stepfather like that, I understand why Miss Stoner was trembling.'],
      ['해설', 'Holmes soon looked up the will of Helen’s mother. If the daughters married, the doctor’s income would shrink greatly.'],
      ['홈즈', 'Watson, bring your revolver. It’s the best answer to a gentleman who can twist steel pokers into knots.'],
      ['해설', 'A locked room, a whistle in the night, and a speckled band. The two men boarded the train to Stoke Moran.'],
      ['해설', 'The Speckled Band is the eighth of the twelve stories in The Adventures of Sherlock Holmes.'],
    ],
  },

  'td-band-2': {
    title: 'The Speckled Band, Part 2',
    names: { 해설: 'Narrator', 홈즈: 'Sherlock Holmes', 왓슨: 'Dr. Watson', 헬렌: 'Helen Stoner' },
    outro: [
      'What was Doyle saying with an ending where a trap meant for others turns on its owner?',
      'What clues did the fake bell-pull, the bed fixed to the floor, and the saucer of milk give?',
      'To notice hidden dangers, what small signs around us should we pay attention to?',
    ],
    lines: [
      ['해설', 'Helen’s twin sister died after saying the speckled band. Now Helen had heard the same whistle in that room.'],
      ['해설', 'One afternoon while Dr. Roylott was away, Holmes and Watson arrived at the old house at Stoke Moran.'],
      ['해설', 'First, Holmes checked the windows and shutters from outside. There wasn’t a gap wide enough for a knife blade.'],
      ['홈즈', 'No one could get in through the window. So the answer must be inside the room.'],
      ['해설', 'In Julia’s room, a bell-pull hung beside the bed. Holmes pulled it, but no bell rang.'],
      ['홈즈', 'It’s a fake. The rope is just tied to a hook. And right above it is a ventilator.'],
      ['헬렌', 'That ventilator and the bell-pull were put in shortly before my sister died.'],
      ['홈즈', 'A ventilator that opens not to the outside, but to the next room, the doctor’s room. And the bed is fixed to the floor.'],
      ['해설', 'In the doctor’s room stood a large iron safe. On top of it was a small saucer of milk.'],
      ['헬렌', 'We don’t have a cat. Only the cheetah and the baboon.'],
      ['해설', 'A dog lash hung on the bedpost. Its end was tied into a loop.'],
      ['홈즈', 'When a doctor goes wrong, he is the first of criminals. He has brains and knowledge.'],
      ['홈즈', 'Miss Stoner, tonight we will wait in that room. You must stay in your old room.'],
      ['해설', 'That night, Helen gave a signal with a lamp in the window. Holmes and Watson slipped quietly into the room.'],
      ['해설', 'They sat by the bed in the dark. Holmes held a thin cane in his hand.'],
      ['해설', 'Eleven, twelve, one, two. Each time the church bell rang in the distance, time seemed to crawl.'],
      ['해설', 'Around three, a light flashed briefly from the ventilator. There was a smell of burning oil.'],
      ['해설', 'Then came a very soft hiss, like steam escaping from a kettle.'],
      ['해설', 'At that moment, Holmes struck a match and lashed furiously at the bell-pull with his cane.'],
      ['홈즈', 'You see it, Watson? Did you see it?'],
      ['해설', 'Watson saw nothing. Then a horrible cry tore through the darkness from the next room.'],
      ['해설', 'They took the lamp into the doctor’s room. Dr. Roylott sat dead in his chair.'],
      ['해설', 'Around his head was a yellow band with brownish speckles. Slowly, the band raised its head.'],
      ['홈즈', 'The band! The speckled band! It is a swamp adder, a deadly snake from India. The schemer has fallen into his own trap.'],
      ['해설', 'Holmes caught the snake with the loop of the dog lash, threw it into the safe, and shut the door.'],
      ['홈즈', 'The doctor trained the snake with milk and called it back with a whistle. The clang was the safe door closing.'],
      ['홈즈', 'The snake came through the ventilator and down the fake rope to the bed. That’s why the bed was fixed to the floor.'],
      ['홈즈', 'When I struck it, the snake went back and bit its master. I am partly responsible, but it won’t weigh much on my conscience.'],
      ['왓슨', 'Now Miss Stoner can start a new life without fear.'],
      ['해설', 'In 1927, Arthur Conan Doyle listed his favorite Holmes stories. He put The Speckled Band at the top.'],
    ],
  },

  'td-napoleon-1': {
    title: 'The Six Napoleons, Part 1',
    names: { 해설: 'Narrator', 홈즈: 'Sherlock Holmes', 왓슨: 'Dr. Watson', 레스트레이드: 'Inspector Lestrade', 하커: 'Horace Harker', 지배인: 'Manager' },
    outro: [
      'What question did Doyle raise with a strange case where only busts of Napoleon are smashed?',
      'Lestrade saw it as a madman’s work. What clue made Holmes see it differently?',
      'Have you ever realized that strange behavior might have a hidden reason?',
    ],
    lines: [
      ['해설', 'One evening, Inspector Lestrade of Scotland Yard dropped by Baker Street.'],
      ['레스트레이드', 'Mr. Holmes, it’s nothing big, but it’s odd. Someone is smashing plaster busts of Napoleon, and only those.'],
      ['레스트레이드', 'First, a bust was smashed in an art shop on Kennington Road. Nothing else was touched.'],
      ['레스트레이드', 'Last night, two more were smashed nearby, at Dr. Barnicot’s home and office. Both came from that shop.'],
      ['왓슨', 'Isn’t it just a madman who hates Napoleon?'],
      ['홈즈', 'That seems strange. There must be hundreds of Napoleon busts in London. Why only ones from the same shop?'],
      ['해설', 'Early the next morning, a telegram came from Lestrade. Come at once to Pitt Street, Kensington.'],
      ['해설', 'It was the home of a journalist, Horace Harker. His bust was gone, and a stranger lay dead at the front door.'],
      ['하커', 'I’ve written about other people’s cases all my life. Now it happens at my door, and I can’t write a line.'],
      ['하커', 'I heard a scream at dawn and came down to find this man lying here. Someone took my bust through the window.'],
      ['레스트레이드', 'We found a photo in the dead man’s pocket. It shows a man with a face like an ape.'],
      ['해설', 'Pieces of the bust lay under a streetlamp in the garden of an empty house nearby. Holmes studied them for a long time.'],
      ['홈즈', 'Why break it under the light? The dark would be much safer. Remember this point, Watson.'],
      ['레스트레이드', 'I’ll look for the man in the photo. Mr. Holmes, you’re too focused on these busts.'],
      ['해설', 'Holmes visited the shops that sold the busts. Harker’s bust came from Harding Brothers.'],
      ['해설', 'Both shops got their busts from the same factory, Gelder and Company in Stepney.'],
      ['지배인', 'We made six of those busts from one mold. Three went to Harding Brothers, and three to the shop in Kennington.'],
      ['홈즈', 'Do you know the man in this photo?'],
      ['지배인', 'Ah, that’s Beppo! An Italian who worked here. About a year ago, he stabbed someone in the street.'],
      ['지배인', 'He ran into this factory to escape the police, and he was caught right here. It was just when those busts were made.'],
      ['지배인', 'He got a year in prison, so he should be out by now.'],
      ['해설', 'From the shops’ records, Holmes found the addresses of the two people who bought the last two busts.'],
      ['홈즈', 'One went to Mr. Josiah Brown of Chiswick, and one to Mr. Sandeford of Reading.'],
      ['해설', 'That afternoon, Lestrade arrived, very pleased. He had found out who the dead man was.'],
      ['레스트레이드', 'His name is Pietro Venucci, from Naples. He was mixed up with a secret society. It must be revenge.'],
      ['홈즈', 'Excellent. Then come with me to Chiswick tonight. I’ll help you catch the criminal.'],
      ['해설', 'Holmes let Harker publish a story about a madman. He wanted the criminal to feel safe.'],
      ['해설', 'Two busts remained. Which one would the criminal go after tonight?'],
      ['해설', 'The Six Napoleons appears in The Return of Sherlock Holmes, a collection published in 1905.'],
    ],
  },

  'td-napoleon-2': {
    title: 'The Six Napoleons, Part 2',
    names: { 해설: 'Narrator', 홈즈: 'Sherlock Holmes', 왓슨: 'Dr. Watson', 레스트레이드: 'Inspector Lestrade', 샌드퍼드: 'Mr. Sandeford' },
    outro: [
      'What kind of detective story fun did Doyle show with the twist of a pearl hidden in a bust?',
      'How did the clue of breaking busts under a streetlamp help Holmes’s reasoning?',
      'If a rival sincerely praised you, how do you think you would feel?',
    ],
    lines: [
      ['해설', 'The man smashing Napoleon busts was an Italian named Beppo. And one man had already lost his life.'],
      ['해설', 'Of the six busts, only two were left, one in Chiswick and one in Reading. Holmes headed for Chiswick.'],
      ['해설', 'At eleven at night, Holmes, Watson, and Lestrade hid in the shadow of the garden fence at Mr. Brown’s house.'],
      ['레스트레이드', 'Mr. Holmes, are you sure he’ll come here?'],
      ['홈즈', 'Hush! Look there.'],
      ['해설', 'The garden gate opened without a sound. A small, quick figure ran to the house, opened a window, and climbed in.'],
      ['해설', 'Soon he came out holding something white. He smashed the bust on the ground and searched through the pieces.'],
      ['해설', 'The three men jumped on him at once. It was the ape-like face from the photo. It was Beppo.'],
      ['해설', 'Beppo refused to say a word. Holmes examined the broken pieces, but found nothing.'],
      ['홈즈', 'Inspector, come to Baker Street tomorrow at six in the evening. I’ll show you the last link in the chain.'],
      ['해설', 'The next evening, Mr. Sandeford of Reading came to Baker Street carrying a bust.'],
      ['샌드퍼드', 'I got your letter. You’ll pay ten pounds for this? I only paid fifteen shillings.'],
      ['홈즈', 'You are very honest. Still, I’ll pay ten pounds as promised. Just sign this paper, please.'],
      ['해설', 'After Sandeford left, Holmes spread a white cloth on the table and placed the bust on it.'],
      ['해설', 'Then he raised his hunting crop and struck the top of the bust hard. It broke into pieces.'],
      ['해설', 'Holmes picked up one piece. In it was something round and dark, like a plum stone.'],
      ['홈즈', 'Gentlemen, let me introduce the famous black pearl of the Borgias.'],
      ['해설', 'Lestrade and Watson clapped without thinking. Holmes’s pale cheeks turned pink, and he bowed like an actor.'],
      ['홈즈', 'This pearl disappeared from the Prince of Colonna’s hotel bedroom. The police never found it.'],
      ['홈즈', 'Pietro Venucci, the dead man, had a sister. She was the maid of the Princess of Colonna.'],
      ['홈즈', 'Beppo got the pearl, but then he was chased for the stabbing. He hid in the Gelder factory.'],
      ['홈즈', 'Six busts were drying there. He made a hole in one, put the pearl inside, and covered it up.'],
      ['홈즈', 'Once free, Beppo broke the busts one by one. Venucci wanted the pearl too, and their fight ended in his death.'],
      ['왓슨', 'And breaking the busts under the streetlamp?'],
      ['홈즈', 'He needed light to see if the pearl was inside. That was not a madman, but a man searching for something.'],
      ['레스트레이드', 'Mr. Holmes, I’ve never seen such neat work. We at Scotland Yard aren’t jealous of you. We’re proud of you.'],
      ['레스트레이드', 'If you come down tomorrow, everyone from the oldest inspector to the newest constable will want to shake your hand.'],
      ['홈즈', 'Thank you. Thank you very much.'],
      ['해설', 'Holmes turned away. On his usually cold face, Watson saw a warmth he had never seen before.'],
      ['홈즈', 'Watson, put the pearl in the safe and get out the papers for our next case. Inspector, come again.'],
      ['해설', 'Before Arthur Conan Doyle became famous as a writer, he was a doctor caring for patients.'],
    ],
  },

  'td-jekyll-1': {
    title: 'Dr. Jekyll and Mr. Hyde, Part 1',
    names: { 해설: 'Narrator', 어터슨: 'Mr. Utterson', 엔필드: 'Mr. Enfield', 래니언: 'Dr. Lanyon', 하이드: 'Mr. Hyde', 지킬: 'Dr. Jekyll' },
    outro: [
      'What mystery did Stevenson plant with a respected doctor leaving his fortune to a stranger like Hyde?',
      'What effect comes from everyone feeling disgust at Hyde without being able to explain why?',
      'Have you ever judged someone only by rumors or a first impression?',
    ],
    lines: [
      ['해설', 'Mr. Utterson was a London lawyer. He was quiet and stern, but he was forgiving of other people’s faults.'],
      ['해설', 'Every Sunday, he walked with his distant cousin, Mr. Enfield. One day, they passed an old door on a back street.'],
      ['해설', 'It was a shabby door in a wall without a single window. Enfield pointed at it with his cane.'],
      ['엔필드', 'That door always reminds me of something. One winter night, around three in the morning, I was walking home.'],
      ['엔필드', 'A small man ran into a girl coming around the corner. Then he calmly walked right over her as she lay there.'],
      ['엔필드', 'I caught him, and a crowd gathered. Strangely, everyone hated him the moment they saw him.'],
      ['엔필드', 'Luckily, the girl wasn’t badly hurt. We demanded a hundred pounds, and he came out of that door with a check.'],
      ['엔필드', 'The check was signed by a well-known, respectable gentleman. And the bank actually paid it.'],
      ['어터슨', 'What was the man’s name?'],
      ['엔필드', 'Hyde. There’s something twisted about him, but I can’t say exactly what.'],
      ['해설', 'That night, Utterson took a document from his safe. It was the will of his friend, Dr. Henry Jekyll.'],
      ['해설', 'If Jekyll died or disappeared for over three months, everything would go to Edward Hyde.'],
      ['어터슨', 'I used to think it was just a foolish will. Now it looks like some shameful secret.'],
      ['해설', 'Utterson went to see Dr. Lanyon, an old friend of Jekyll’s.'],
      ['래니언', 'Jekyll? About ten years ago, he got into strange research. It was nonsense, not science.'],
      ['래니언', 'I’ve hardly seen him since. And I’ve never heard the name Hyde.'],
      ['해설', 'From that day on, Utterson watched that door whenever he could, morning and night.'],
      ['어터슨', 'If he is Mr. Hyde, then I shall be Mr. Seek.'],
      ['해설', 'One clear, cold night, light and strange footsteps came near. A small man took out a key.'],
      ['어터슨', 'Mr. Hyde, I think? I am Mr. Utterson, an old friend of Dr. Jekyll’s.'],
      ['하이드', 'How did you know me? Jekyll would never have told you. Don’t lie to me!'],
      ['해설', 'Hyde laughed an ugly laugh and vanished through the door. Utterson stood there for a long time.'],
      ['어터슨', 'If ever I read Satan’s signature on a face, it is on his. Poor Jekyll, what trouble is he in?'],
      ['해설', 'Utterson learned that the door led to the laboratory behind Dr. Jekyll’s house.'],
      ['해설', 'Two weeks later, after a dinner at Jekyll’s, Utterson stayed behind and brought up the will.'],
      ['지킬', 'I know you don’t like that will. But this is a very unusual situation.'],
      ['지킬', 'Let me be clear. The moment I choose, I can be rid of Mr. Hyde. So please don’t ask any more.'],
      ['지킬', 'But if anything happens to me, promise you will help him get what is his.'],
      ['어터슨', 'I can’t pretend I will ever like him. But I promise.'],
      ['해설', 'About a year later, a crime shook all of London. And at its center was Mr. Hyde.'],
      ['해설', 'Robert Louis Stevenson published Strange Case of Dr Jekyll and Mr Hyde in 1886.'],
    ],
  },

  'td-jekyll-2': {
    title: 'Dr. Jekyll and Mr. Hyde, Part 2',
    names: { 해설: 'Narrator', 어터슨: 'Mr. Utterson', 하녀: 'Maid', 지킬: 'Dr. Jekyll', 게스트: 'Mr. Guest', 래니언: 'Dr. Lanyon' },
    outro: [
      'What was Stevenson hinting at with the clue that two handwritings seemed to come from one hand?',
      'What does Jekyll’s change, from cheerful after Hyde vanished to shutting his door again, show?',
      'How can trying to hide a part of ourselves make life more painful?',
    ],
    lines: [
      ['해설', 'Respectable Dr. Jekyll had left his fortune to the strange Mr. Hyde. Utterson could not understand why.'],
      ['해설', 'Nearly a year later, in October, a crime shocked all of London.'],
      ['해설', 'Late at night, a maid in a house near the river sat by her window. She looked down at the moonlit street.'],
      ['하녀', 'A white-haired gentleman politely spoke to a small man. That small man was Mr. Hyde.'],
      ['하녀', 'Suddenly Mr. Hyde flew into a rage and struck the gentleman down with his cane. Then I fainted.'],
      ['해설', 'The old gentleman did not survive. He was Sir Danvers Carew, a respected member of Parliament.'],
      ['해설', 'Half of a broken cane lay at the scene. Utterson, who came with the police, recognized it at once.'],
      ['어터슨', 'This is the cane I gave Jekyll long ago.'],
      ['해설', 'Utterson led the police to Hyde’s home in Soho. Hyde was already gone.'],
      ['해설', 'The rooms had been turned upside down. In the fireplace was a half-burned checkbook. The other half of the cane was there too.'],
      ['해설', 'That afternoon, Utterson visited Jekyll. In the room behind the laboratory, Jekyll looked deathly pale.'],
      ['어터슨', 'You aren’t hiding that man, are you?'],
      ['지킬', 'I swear I will never see him again. I am done with him. He will never be heard of again.'],
      ['지킬', 'He left a letter. Read it and judge for yourself.'],
      ['해설', 'The letter, signed Hyde, told his benefactor Jekyll not to worry. It said he would escape far away.'],
      ['해설', 'That night, Utterson showed the letter to his head clerk, Mr. Guest, who was an expert on handwriting.'],
      ['해설', 'By chance, there was a dinner invitation from Jekyll. Guest put the two side by side.'],
      ['게스트', 'How odd. The two hands are the same in many ways. Only the slope is different.'],
      ['어터슨', 'Don’t tell anyone about this. Henry Jekyll forging a letter for a murderer!'],
      ['해설', 'With Hyde gone, Jekyll became cheerful again. For two months, he saw his friends and did good works.'],
      ['해설', 'But in early January, Jekyll’s door suddenly closed. No matter how often Utterson called, he was turned away.'],
      ['해설', 'Utterson visited Lanyon. The shadow of death lay heavy on Lanyon’s face.'],
      ['래니언', 'I have had a terrible shock. I will not live long. Don’t speak of Jekyll. I don’t want to hear his name.'],
      ['해설', 'Within two weeks, Lanyon was dead. He left an envelope for Utterson.'],
      ['해설', 'It said not to open it until Henry Jekyll had died or disappeared. Utterson locked it in his safe.'],
      ['해설', 'One Sunday, Utterson and Enfield walked down that back street. They saw Jekyll sitting at the laboratory window.'],
      ['어터슨', 'Jekyll! Are you feeling better? Come out and walk with us.'],
      ['지킬', 'Thank you, Utterson. I would love to, but I cannot.'],
      ['해설', 'At that moment, the smile vanished from Jekyll’s face. Terror and despair took its place. The window slammed shut.'],
      ['해설', 'The two men left the street in silence. What was happening inside Jekyll’s room?'],
      ['해설', 'Three years before this novel, in 1883, Stevenson published his adventure story Treasure Island as a book.'],
    ],
  },

  'td-jekyll-3': {
    title: 'Dr. Jekyll and Mr. Hyde, Part 3',
    names: { 해설: 'Narrator', 어터슨: 'Mr. Utterson', 풀: 'Poole', 래니언: 'Dr. Lanyon', 지킬: 'Dr. Jekyll' },
    outro: [
      'How did Stevenson show, through Jekyll’s confession, the idea that good and evil live in one person?',
      'What might it symbolize that Jekyll, once changing only by choice, later changed on his own?',
      'Have you seen a habit or urge you thought you could control slowly start to control you?',
    ],
    lines: [
      ['해설', 'Dr. Lanyon had died in terror, and Jekyll had locked himself in the room behind his laboratory.'],
      ['해설', 'On a windy evening in March, Jekyll’s butler, Poole, came to Utterson, his face pale.'],
      ['풀', 'Sir, you must come with me. For a week, something strange has been happening in my master’s room.'],
      ['풀', 'The voice in that room is not my master’s. And day and night, he orders me to find a certain drug.'],
      ['풀', 'It must be pure, he says. I search every chemist’s shop, but he sends it all back. Not this, he says.'],
      ['풀', 'Once I saw him come out. He was small and twisted. That was not my master.'],
      ['해설', 'Utterson stood with Poole at the laboratory door. Inside, light, strange footsteps paced back and forth.'],
      ['어터슨', 'Jekyll, let me see you! If you don’t open the door, I will break it down!'],
      ['해설', 'The voice that answered was not Jekyll’s, but Hyde’s. Utterson told Poole to take up an axe.'],
      ['해설', 'On the fifth blow, the door fell in. Hyde lay on the floor in Jekyll’s clothes. He had taken poison.'],
      ['해설', 'Jekyll was nowhere to be found. On the desk were letters for Utterson and a new will in Utterson’s name.'],
      ['해설', 'Utterson went home and first opened the letter Lanyon had left.'],
      ['래니언', 'Jekyll asked me to take some chemicals from his drawer. I was to give them to a man coming at midnight.'],
      ['래니언', 'At midnight, a small, unpleasant man came. He mixed the drugs, raised the glass, and asked if I wanted to watch.'],
      ['래니언', 'He drank it. His face twisted and changed, and there before my eyes stood Henry Jekyll.'],
      ['해설', 'Next, Utterson read Jekyll’s final confession.'],
      ['지킬', 'I learned early that man is not truly one, but two. Behind my respectable face were desires I hid.'],
      ['지킬', 'I made a drug to separate the two. When I drank it, I became Hyde, young, light, and free of all rules.'],
      ['지킬', 'Hyde was small. Perhaps the evil in me had been used less, so it had grown less.'],
      ['지킬', 'At first it was fun. As Hyde, I could do what I liked without a single stain on Jekyll’s name.'],
      ['지킬', 'But one morning, I woke up and saw that my hand was Hyde’s hand. I had not taken the drug.'],
      ['지킬', 'Becoming Hyde grew easier and easier. Coming back to Jekyll grew harder and harder.'],
      ['지킬', 'For two months I held out. Then I drank the drug again. Hyde, locked up so long, raged and killed Sir Danvers Carew.'],
      ['지킬', 'After that I tried never to become Hyde again. But one day, on a park bench, I changed on my own.'],
      ['지킬', 'That was when I asked Lanyon for help. After that, only a double dose let me stay Jekyll.'],
      ['지킬', 'My first supply of salt ran out. The new supply did not work. Some unknown impurity in the first must have been the key.'],
      ['지킬', 'This is the last thing I will write as Jekyll. When I put down this pen, the life of unhappy Henry Jekyll will end.'],
      ['해설', 'Utterson put down the letter. What swallowed his friend was not a strange monster, but another face inside him.'],
      ['해설', 'Today, Jekyll and Hyde is a common phrase for a person with two very different sides.'],
    ],
  },
};
